add: Ratge the borg
ss220-space/Paradise pull request #1000
Opened 2022-06-10 03:02 UTC by Den109G

## What Does This PR Do
Добавляет скин для борга-уборщика.
Добавляет новую переменную для борга и строки кода, связанные с ней.

## Why It's Good For The Game
[Предложка прошла.](https://discord.com/channels/617003227182792704/755125334097133628/983474836372344882) Они должны делаться.

## Changelog
:cl:
add: Added new icon for jani-borg
/:cl:

2022-06-10 10:12 UTC, Vallat requested changes
Из описания ПРа совершенно непонятно что код должен делать. Из кода собственно тоже. Внёс некоторые изменения, но у меня всё еще нет понимания, что конкретно вносится этим ПРом

2022-06-10 10:12 UTC, Vallat commented on code/modules/mob/living/silicon/robot/robot.dm
> +			return
```suggestion
		for(var/mob/mouse in W.contents)
			if(mouse.ckey)
				to_chat(user, "<span class='notify'>You fell guilty putting this mouse in those wires. Try diffrent mouse, more wild one.</span>")
				return
			mouse_skin = TRUE //i mean, no one mentions mouse to be alive for icon
			to_chat(user, "You put mouse into machine.")
			user.unEquip(W)
			qdel(W)
```

2022-06-10 10:12 UTC, Vallat commented on code/modules/mob/living/silicon/robot/robot.dm
> +	var/mouse_skin = 0 //so cyborgs can have mouse/rat icons
```suggestion
	var/mouse_skin = FALSE //if cyborg have mouse/rat inside
```

2022-06-10 14:21 UTC, Den109G commented
Да я тоже не имею понятия что ПР делает.

2022-08-17 07:53 UTC, PhantornRU approved these changes

2022-09-10 19:26 UTC, closed without merging

2022-09-11 05:47 UTC, Den109G commented
:aiKEK: