Фикс пустых имен големов + созданных оболочек големов
ss220-space/Paradise pull request #1015
Opened 2022-06-12 15:52 UTC by PhantornRU

## What Does This PR Do
Добавляет дополнительную проверку на пустую строку имени голема или отсутствие его имени в случае возникновения при вселения в оболочку голема. Редкий баг, который вызывается путем ... А не понятно каким путем. До сих пор выясняем. Но ясно что он вызывается при хайпопе из-за того что ломается генератор имен и выдает големам имя "Unknown" из-за чего получение рандомного имени вызывает сбой функции и оставляет имя "Unknown" или пустую не нулевую (not null) строку.

Также попутно исправляет перевод создания инертных големских оболочек (которые пишут префикс, но не пишут его склонение) и допереводит пару големских строчек.
Фиксы "the"
Перевод напоминалки для голема.

## Why It's Good For The Game
Големы еще лучше русифицированы и исправлены

2022-06-13 06:32 UTC, Vallat requested changes
> Но ясно что он вызывается при хайпопе из-за того что ломается генератор имен

Нет, не ясно.

2022-06-13 06:32 UTC, Vallat commented on code/modules/awaymissions/mission_code/ghost_role_spawners/golems.dm
> +		if(!name || name == "" || name == "Unknown") //Существует баг который заставляет всех големов бегать без имени. Я так и не нашел почему он вызывается и как, поэтому пускай будет хоть какая-то прове
```suggestion
		if(!name || name == "Unknown") //Существует баг который заставляет всех големов бегать без имени. Я так и не нашел почему он вызывается и как, поэтому пускай будет хоть какая-то проверка при создании големов.
```

2022-06-13 06:32 UTC, Vallat commented on code/modules/awaymissions/mission_code/ghost_role_spawners/golems.dm
>  		if(transfer_choice != "Yes")
А здесь менять проверку кто будет?

2022-06-13 06:41 UTC, PhantornRU commented on code/modules/awaymissions/mission_code/ghost_role_spawners/golems.dm
> +		if(!name || name == "" || name == "Unknown") //Существует баг который заставляет всех големов бегать без имени. Я так и не нашел почему он вызывается и как, поэтому пускай будет хоть какая-то прове
Допустим. Надеюсь ты был прав и пустая строка действительно сама по себе возвращает null значение

2022-06-13 06:41 UTC, PhantornRU commented on code/modules/awaymissions/mission_code/ghost_role_spawners/golems.dm
>  		if(transfer_choice != "Yes")
```suggestion
		if(transfer_choice != "Да")
```

2022-06-13 06:43 UTC, Vallat approved these changes

2022-06-13 06:44 UTC, PhantornRU commented
> > Но ясно что он вызывается при хайпопе из-за того что ломается генератор имен
> 
> Нет, не ясно. И баг исправленным не считаю.

Я запросил педалей предоставить мне данные бага. Они ж ответственные за разработку. Вот ждёт.

2022-06-15 11:07 UTC, Bizzonium commented
Необходимо разделить PR. в таком виде не приму

2022-06-16 05:32 UTC, PhantornRU commented
выпилил подчистую переводы. Всеравно они не нужны. Оставил только багфиксы

2022-06-16 11:04 UTC, merged