Improved "examine" styles
ss220-space/Paradise pull request #1041
Opened 2022-06-23 11:12 UTC by AddRaiser

## What Does This PR Do
New styles for examine

## Why It's Good For The Game
Better visuals

## Images of changes
![image](https://user-images.githubusercontent.com/49074954/175285750-e1113082-1ef7-49ea-9dca-83a6201694be.png)

![image](https://user-images.githubusercontent.com/49074954/175285634-9d3651e8-d27a-4571-84f1-bcf9630bb98e.png)
![image](https://user-images.githubusercontent.com/49074954/175285842-ba86cf9b-86f8-4107-acb1-4b921d9b0e01.png)

## Changelog
:cl:
tweak: Changed styles for both bright and dark chat
/:cl:

2022-06-23 11:39 UTC, dj-34 commented on goon/browserassets/css/browserOutput-dark.css
> +	background: #171c20;
Не уверен, что хорошая идея, с учетом того, что у нас все интерфейсы в темном цвете без лишних оттенков.
Имхо стоило бы подобрать цвет для бэка, чем для всего чата - тогда и предложка вовсе не нужна. Например #353535

2022-06-23 12:07 UTC, AddRaiser commented on goon/browserassets/css/browserOutput-dark.css
> +	background: #171c20;
В целом можешь попробовать на локалке и скинуть результат

2022-06-23 16:19 UTC, dj-34 commented on goon/browserassets/css/browserOutput-dark.css
> +	background: #171c20;
![image](https://user-images.githubusercontent.com/20109643/175345588-7d4898d6-5f72-4074-a93e-38d7401df518.png)

Вот, **#252525**, выглядит вполне себе.

2022-06-23 16:21 UTC, AddRaiser commented on goon/browserassets/css/browserOutput-dark.css
> +	background: #171c20;
Значит будет еще 1 вариант админам на выбор

2022-06-26 15:46 UTC, TrashDoxx requested changes
Перепиши значения в 'px' на 'em'-единицы, чтобы блоки менялись в зависимости от размера шрифта.

2022-06-26 15:49 UTC, TrashDoxx requested changes
Также снеси визуальные разделители `*---------*` в описаниях, так как они теперь не нужны.

2022-06-29 14:43 UTC, merged

2022-06-30 14:01 UTC, AndreiVNK commented
![black](https://user-images.githubusercontent.com/100762963/176696295-1d23fe58-1810-4029-886c-58da54e388fa.png)
Контрастность на темной теме слишко сильно варьируется, и приводит к дискомфорту при просмотре. Советую снизить разницу контрастности красного и белого текста. Также, советую уменьшить контрастность текста рекордсов, на уровне текста крови, или ниже. 
Я одобряю увеличения контрастности текста при осмотре, так как это логично с точки зрения визуального языка (высококонтрастный текст при использовании ./me и сообщения ПДА, разговоры на галактическом общем) 


![Монтажная область 12](https://user-images.githubusercontent.com/100762963/176696500-0b5a4542-6938-47c1-8691-775fd34653f8.png)
На белой теме проблем не вижу.