Feature/better decompression
ss220-space/Paradise pull request #1069
Opened 2022-07-05 10:33 UTC by AddRaiser

## What Does This PR Do
Добавление взрывной декомпрессии в игру
На данный момент разгерметизация выкачивает откачивает воздух очень медленно
Этот PR нацелен на то, чтобы имитировать быструю потерю атмосферы в ограниченной зоне при появлении разгерметизации

## Why It's Good For The Game
Больше нельзя будет спокойно бегать в тайле от разгермы без защиты
Инженеры (особенно атмотехи) получат больше работы
Больше возможностей для саботажа

<details>
  <summary>Как это работает СЕЙЧАС</summary>

https://user-images.githubusercontent.com/49074954/177309060-63f4cc2e-e753-42fd-9c27-167de9dd921b.mp4
</details>

<details>
  <summary>Как это будет работать после ПР</summary>

https://user-images.githubusercontent.com/49074954/177308500-0a2408a6-d1c9-4c87-9785-ce33767d6efa.mp4
</details>

## Changelog
:cl:
experiment: Добавлена имитация взрывной декомпрессии
/:cl:

2022-07-16 08:25 UTC, BeebBeebBoob requested changes
Я боюсь но возможно будут проблемы на лаве.

2022-07-16 08:25 UTC, BeebBeebBoob commented on code/LINDA/LINDA_turf_tile.dm
> +				if (is_station_level(loc.z) && current_moles > 5 && isspaceturf(enemy_tile))
is_station_level? 
А если это на тайпане будет или на шаттле шахтеров?

2022-07-16 08:25 UTC, BeebBeebBoob commented on code/LINDA/LINDA_turf_tile.dm
> +			carbon.apply_effect(3, WEAKEN, 0)
На carbon.AdjustWeaken() лучше

2022-07-16 08:25 UTC, BeebBeebBoob commented on code/LINDA/LINDA_turf_tile.dm
> +		if (istype(src, /mob/living/carbon) && pressure_difference > 50)
istype(src, /mob/living/carbon) >> iscarbon(src)

2022-07-18 13:22 UTC, Bizzonium commented on code/LINDA/LINDA_turf_tile.dm
> +			carbon.apply_effect(3, WEAKEN, 0)
Тут ещё была проблема, что Weaken применялся несколько раз, что приводило к станлоку моба. На тестмерже я убрал эту часть кода. Надо понять, как исправить стаки эффектов

2022-07-19 11:38 UTC, BeebBeebBoob commented on code/LINDA/LINDA_turf_tile.dm
> +			carbon.apply_effect(3, WEAKEN, 0)
Возможно добавить if weaken дабы не стакался так много. Все же если будет продолжаться декомпрессия то после окончания стана снова будет стан пока не уйдет.

2022-07-22 14:26 UTC, merged