Feat: Clockwork mender (balance and fixes)
ss220-space/Paradise pull request #1095
Opened 2022-07-19 04:33 UTC by Den109G

## What Does This PR Do

Меняет баланс по [заметкам Биба](https://discord.com/channels/617003227182792704/981565006762106891/997387930358255716):
- Меняет время для зачарований (телепортация, сокрытие шестерней, ускорения и другие).
- Даёт защиту от ЭМИ киборгам после Ratvar_act.
- Меняет мультитул у cogscarab (чисто декор).
- Увеличение урона у копья, меча.
- Уменьшение урона у щита.
- Увеличивает скорость перемещения у зачарованной робы.

Меняет чуть-чуть код вещей, чтобы балансерам легче было менять циферки (у кирасы - absorb_uses и reflect_uses возвращаются через initial(), то же самое и с мечом).

Чинит баги:
- Копьё клокеров; теперь им можно ударить (спасибо Бибу).
- Заклинание Harden plates корректно работает (спасибо Бибу).

Добавляет:
- Киборги собранные через Soul Vessel получают способности клокеров.
- Шесткарабеи получают язык дронов (который `:d` ).
- Обычный экипаж не может пользоваться часами с телепортом/сокрытием.

## Why It's Good For The Game
Обычный смертный не сможет залететь на базу шестерней через телепорт.
Копьём наконец-то можно снова бить.
Броня не будет ломаться от своего же заклинания.
Баланс

## Changelog
:cl:
add: Added EMP protection for cyborgs from ratvar act
add: if check for clockslab
add: drone language for cogscarab
tweak: how games give/return vars, so it will be easier to balance
tweak: changed damage for few weapons
tweak: speed for haste enchant
tweak: cogscarab's multitool now made from brass
fix: fixed a spear attack
fix: fixed harden plates for armor
/:cl:

sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
experiment: added an experimental thingy
/:cl:

2022-07-19 10:23 UTC, BeebBeebBoob requested changes
Решить пару вопросов и балансов и можно выпустить.

2022-07-19 10:23 UTC, BeebBeebBoob commented on code/modules/mob/language.dm
> +		if(drone_only && !(istype(S,/mob/living/silicon/robot/drone)||(istype(S,/mob/living/silicon/robot/cogscarab))))
```suggestion
		if(drone_only && !(istype(S,/mob/living/silicon/robot/drone)||iscogscarab(S)))
```

2022-07-19 10:23 UTC, BeebBeebBoob commented on code/modules/mob/living/silicon/robot/robot.dm
> +		pdahide = TRUE
Там уже`UnlinkSelf()` убирает все признаки соединения к станции как помню

2022-07-19 10:23 UTC, BeebBeebBoob commented on code/__DEFINES/clockwork.dm
>  #define CLOCK_POWER_PER_CREW 400
```suggestion
#define CLOCK_POWER_PER_CREW 300
```
Я заметил что всегда именно задание на питание делают последним
Стоит тогда увеличить на 0.10 в 108 и 112 строке дабы сразу не раскрыли ибо в процентах все таки(хотя там палятся руки и их слегка трудно заметить но они светятся (не в темноте))

Также 92 на 50 бафнуть и 93 до 500 ибо это минус целое тело

2022-07-19 11:28 UTC, Den109G commented on code/modules/mob/living/silicon/robot/robot.dm
> +		pdahide = TRUE
UnlinkSelf лишь скрывает мессенджер, но не выключает. Т.е. без этой строчки, боргов нельзя увидеть по мессенджеру, но можно получать от них сообщения.
Можно конечно убрать `pdahide = TRUE`, но смысла особого не вижу. Просто борги смогут писать через мессенджер (у них и так есть связь хирефанта, зачем ПДА?).
![image](https://user-images.githubusercontent.com/87372121/179738838-6d0d3ee7-d4f5-41ee-8b6e-6a85a0e657dc.png)
![image](https://user-images.githubusercontent.com/87372121/179738884-b0d9dfa9-1dc6-45c0-907a-0596245ac65a.png)
![image](https://user-images.githubusercontent.com/87372121/179739009-b721fc24-e9f9-40ca-8952-aa30c7b6cd6e.png)

2022-07-19 11:41 UTC, Den109G commented on code/__DEFINES/clockwork.dm
>  #define CLOCK_POWER_PER_CREW 400
Надеюсь правильно понял, что надо поправить.

2022-07-19 11:44 UTC, Den109G commented on code/modules/mob/living/silicon/robot/robot.dm
> +		pdahide = TRUE
(Ещё не учитываем что оно нормально не работает, ибо ПДА меняется только после смены имени)

2022-07-19 17:59 UTC, BeebBeebBoob commented on code/__DEFINES/clockwork.dm
> +#define CLOCK_POWER_CONVERT 100
слегка имел в виду до 200 дабы те кого законвертовали могли что-то сделать себе за это количество питания.

2022-07-19 18:10 UTC, BeebBeebBoob commented on code/modules/mob/living/silicon/robot/robot.dm
> +		pdahide = TRUE
ну тогда вопрос отпал

2022-07-19 20:38 UTC, BeebBeebBoob commented
Последняя правка и этот ПР я считаю готовым.

2022-07-19 20:44 UTC, Den109G commented on code/__DEFINES/clockwork.dm
> +#define CLOCK_POWER_CONVERT 100
👌

2022-07-19 20:53 UTC, Den109G commented
145 файлов + конфликты... Будет весело.

2022-07-20 08:01 UTC, BeebBeebBoob commented
А как так получилось??

2022-07-20 08:13 UTC, Den109G commented
После force-push'а появились. Ну ничего, мне не лень пересоздавать ПР.

2022-07-20 08:28 UTC, Den109G commented
А говорил я себе. Не спи. Они снова нападут на ПР.
Ну не поверил я себе, вот что случилось. 🤡

2022-07-20 23:11 UTC, closed without merging