Новая должность: Бриг Офицер
ss220-space/Paradise pull request #1119
Opened 2022-07-25 19:57 UTC by Robustin3

## What Does This PR Do
Добавление новой должности для охраны.

## Why It's Good For The Game
Смотрителю будет легче, всегда есть под рукой офицер, которого можно послать в пермабриг, а сам открывать аеги, или приказать посадить кого-то в камеру, пока сам в карго.

## Images of changes
![image](https://user-images.githubusercontent.com/109764045/180863659-e2043d97-a2ed-499c-9bc9-35d96c966151.png)

## Changelog
:cl:
add: brig officer job
brig officer's cloth, pda
brig officer's skin for plasmamen
brig officer's own closet
/:cl:

2022-07-25 21:20 UTC, BeebBeebBoob commented
Такой ПР не пойдет совсем. Тебе надо было открывать и изменять карты, которые dmm файлы в спец программах как strongdmm или ещё одна которую не помню.

2022-07-26 07:14 UTC, VasilevAY commented
Считаю, что данную предложку не имеет смысла мерджить до тех пор, пока не будет пройдена отдельная предложка по СРП для бриг офицера. В том виде, в котором она есть (см. оригинальную предложку в дс), она не может быть принята, на мой взгляд

2022-07-26 07:29 UTC, PhantornRU commented
Без клоуна-смотрителя, предложка не является полноценной

2022-07-26 10:43 UTC, larentoun commented
А засквашить не судьба? Так и жду увидеть 10 коммитов "шкафчик"

2022-07-26 11:03 UTC, VasilevAY commented
> Ладно, будет вам карта delta.dmm в strongdmm... Только не сейчас.

а как это относится к данной предложке?

2022-07-26 11:05 UTC, larentoun commented
> Ладно, будет вам карта delta.dmm в strongdmm... Только не сейчас.

И на кибериаду тоже нужно

2022-07-26 12:45 UTC, Murguletto commented
А черт, это я ст твинка пишу

2022-07-26 16:23 UTC, Robustin3 commented
ну как бы дельта и кибериада, шкфчики есть, карты измменены в strongdmm.

2022-07-27 08:02 UTC, BeebBeebBoob commented
тебе надо было изначально это сделать. Теперь тебе надо удалить все карты которые ты изменил, потом скачать с гитхаба самую актуальную от азиза. И всё ещё...
![image](https://user-images.githubusercontent.com/32985153/181194527-994c3599-564d-4d49-8bdc-970a17a3a987.png)
слишком много

2022-07-27 08:06 UTC, BeebBeebBoob requested changes

2022-07-27 08:06 UTC, BeebBeebBoob commented on .gitignore
> +paradise.dme
Это вообще не надо трогать.

2022-07-27 08:06 UTC, BeebBeebBoob commented on .gitignore
> +paradise.dme
```suggestion

```
всё ещё не надо трогать .gitignore. Это не в наших силах, это в силах азиза делать такие здесь изменения если потребуются.

2022-07-27 08:06 UTC, BeebBeebBoob commented on paradise.dme
> +#include "_maps\map_files\Delta\delta.dmm"
```suggestion

```
здесь идут только файлы .dm. не карты, не звуки, ничего кроме dm

2022-07-27 14:10 UTC, Robustin3 commented on paradise.dme
> +#include "_maps\map_files\Delta\delta.dmm"
я вообще в первый раз, если надо что-то изменить, то без проблем

2022-08-05 14:02 UTC, closed without merging