Tweak: minor addictions now less probable, more sustainable and can be taken in rounstart disabilities
ss220-space/Paradise pull request #1128
Opened 2022-07-28 17:19 UTC by Dimach

## What Does This PR Do
Меняет логину минорных зависимостей (никотин, кофеин, алкоголь, чай) таким образом чтобы их было намного сложнее подхватить, но при этом оставались они намного дольше (45 минут)

Добавляет возможность брать эти минорные зависимости в раундстартовых disabilities

## Why It's Good For The Game
Больше возможностей для РП отыгрыша персонажей который курит 30 лет (раньше зависимость можно было получить только на станции)

Назойливые сообщения о том чтобы покурить теперь появляются не через минуту а через 9 минут что позволяет не ходить с сигаретой в зубах все время

## Changelog
Убрано: зависимость от сыра, зависимость от капсаицина
Добавлено: зависимость от алкоголя
Изменено: таймер минорных зависимостей - 45 минут вместо 8
Изменено: время до появления сообщений о том что хочется Х для минорных зависимостей увеличено с 1 минуты до 9
Изменено: логика расчета времени перехода на следующую стадию зависимости для минорных зависимостей, теперь она меньше полагается на рандом и меньше зависит от тикрейта сервера
Добавлено: механика зависимостей одного типа для разных реагентов, пример: все виды алкоголя это разный реагент но теперь они все дают и утоляют зависимость от этанола. Аналогично для чая и кофе.

2022-07-28 17:19 UTC, Dimach commented
Пока не мержить, ждем голосовалку

2022-07-28 21:06 UTC, BeebBeebBoob requested changes
Ну там и комменты обновить, кто мы такие чтобы это делать? :Ratge:

2022-07-28 21:06 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/holder.dm
> +		var/datum/reagent/R = A
```suggestion
	for(var/datum/reagent/R in reagent_list)
```

2022-07-28 21:06 UTC, BeebBeebBoob commented on code/__DEFINES/genetics.dm
> +#define DISABILITY_FLAG_NICOTINE_ADDICT 32768
думаю тут уже стоило бы все поменять от (1<<1) где 11 строка до (1<<16) последняя.
Ну типо
`#define DISABILITY_FLAG_NEARSIGHTED (1<<1)`
`...`
`#define DISABILITY_FLAG_NICOTINE_ADDICT (1<<16)`

2022-07-28 21:06 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/holder.dm
> +#define MINOR_ADDICTION_TIME 27000 //45 minutes
ну или
`#define MINOR_ADDICTION_TIME 45 MINUTES //45 minutes`
у нас же есть SECONDS MINUTES и даже HOURS которые прописаны в code/_HELPERS/time.dm 
:)

2022-07-28 21:06 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents.dm
> +		var/datum/reagent/AD = A
```suggestion
	for(var/datum/reagent/AD in M.reagents.addiction_list)
```

2022-07-28 21:06 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents.dm
> +	addict_supertype = type
Не понял тут слегка помысел.
Думаю вот так удобнее и лучше брать Initialize() нежели New() чтобы не нависать запуск сервера каждый раз(хотя мало но вес всё ещё есть)
```suggestion
	var/datum/reagent/addict_supertype = null
```

2022-07-29 11:05 UTC, Dimach commented on code/modules/reagents/chemistry/holder.dm
> +#define MINOR_ADDICTION_TIME 27000 //45 minutes
Я сохранял тот "стиль" который был в оригинальном коде, поэтому не рефачил все это до более читабельного вида

2022-07-29 11:20 UTC, Dimach commented on code/modules/reagents/chemistry/reagents.dm
> +	addict_supertype = type
Этот код не сработает. Тут суть в том чтобы получить в переменную addict_supertype тот тип зависимость от которого должна срабатывать, пример: никотин даёт зависимость от никотина, но водка даёт зависимость от этанола, как и пиво и другие виды алкоголя. 

Проблема в том что если в каждый реагент указывать от какого реагента он должен давать зависимость (в 95% случаев - от самого себя) получится много лишнего кода. Этот конструктор позволяет выставить зависимость по умолчанию от самого себя, а если нужно этот конструктор оверрайдится

Можно конечно переписать это так чтобы там вообще не использовалась переменная и не нужно было её вызывать в момент создания датума, но зачем?

2022-07-31 20:34 UTC, Dimach commented
Голосовалка прошла, можно мержить
https://discord.com/channels/617003227182792704/755125334097133628/1003400112845901834

2022-08-16 12:42 UTC, merged