feat: Russian update (prime)
ss220-space/Paradise pull request #1152
Opened 2022-08-05 13:31 UTC by larentoun

## What Does This PR Do

- Исправление и стандартизация перевода
- Перевод задач
- Перевод осмотра
- Мелкие правки перевода attacktext
- Частичный перевод Принца Террора, Коровы, Уники и Челюстей Жизни для тестов перевода
- Возвращение частоты сообщений шуток скелета
- Перенос дефайнов падежей в _DEFINES
- Перевод проков дальнобойного оружия

## Why It's Good For The Game

Русский язык на русскоязычном билде.

## Images of changes

2022-08-05 14:15 UTC, PhantornRU commented on code/datums/mind.dm
> +		output += "<HR><B>Задачи профессии:</B><UL>"
Давай попробуем так Либо же Должностные обязательства. Так звучит получше и по русски.
```suggestion
		output += "<HR><B>Должностные задачи:</B><UL>"
```

2022-08-05 14:21 UTC, PhantornRU commented on code/game/atoms.dm
> +	var/atom_say_verb = "говорит"
Вот здесь самое интересное, т.к. должен определяться падеж того кто говорит.
Сказал(а/и)

2022-08-05 14:26 UTC, PhantornRU commented on code/game/atoms.dm
> +			f_name = "<span class='danger'>[genderize_ru(gender, "окровавленный", "окровавленная", "окровавленное", "окровавленные")]</span> [declent_ru(NOMINATIVE)][infix]!"
Сначала слово, потом гендерные окончания
```suggestion
			f_name = "<span class='danger'>окровавленн[genderize_ru(gender, "ый", "ая", "ое", "ые")]</span> [declent_ru(NOMINATIVE)][infix]!"
```

2022-08-05 14:27 UTC, PhantornRU commented on code/game/atoms.dm
> +			f_name = "[genderize_ru(gender, "обмасленный", "обмасленная", "обмасленное", "обмасленные")] [declent_ru(NOMINATIVE)][infix]."
Сначала слово, потом гендерные окончания

2022-08-05 14:29 UTC, PhantornRU commented on code/game/atoms.dm
> +			. += "<span class='notice'>Контейнер содержит:</span>"
Стоит ли обозначать что это контейнер? Это может быть своеобразная емкость. 
Тут на свое усмотрение. Можно в принципе так и так.
```suggestion
			. += "<span class='notice'>Содержание:</span>"
```

2022-08-05 14:30 UTC, PhantornRU commented on code/game/atoms.dm
> +				. += "<span class='notice'>ничего.</span>"
```suggestion
				. += "<span class='notice'>Ничего.</span>"
```

2022-08-05 14:31 UTC, PhantornRU commented on code/game/atoms.dm
> +				. += "<span class='notice'>Контейнер содержит [reagents.total_volume] единиц веществ.</span>"
Либо так, либо "емкость". Бутылка и кружка тоже не совсем контейнер, но по прежнему емкость.
```suggestion
				. += "<span class='notice'>Содержит [reagents.total_volume] единиц веществ.</span>"
```

2022-08-05 14:32 UTC, PhantornRU commented on code/game/atoms.dm
> +				. += "<span class='danger'>Контейнер пуст.</span>"
Либо "Емкость пуста"
```suggestion
				. += "<span class='danger'>Пустой.</span>"
```

2022-08-05 14:34 UTC, PhantornRU commented on code/game/atoms.dm
> +		prompt = "Какой ярлык вы хотите поставить на [declent_ru(ACCUSATIVE)]?"
Здесь точно всё ок и не нужно уточнять что нужно падежить? Мне кажется или он не видит что здесь нужно падежить?
```suggestion
		prompt = "Какой ярлык вы хотите поставить на [src.declent_ru(ACCUSATIVE)]?"
```

2022-08-05 14:34 UTC, PhantornRU commented on code/game/atoms.dm
> +	var/t = input(user, prompt, "Переименование [declent_ru(GENITIVE)]", default_value)  as text | null
```suggestion
	var/t = input(user, prompt, "Переименование [src.declent_ru(GENITIVE)]", default_value)  as text | null
```

2022-08-05 14:35 UTC, PhantornRU commented on code/game/atoms.dm
> +	var/f_name = "[declent_ru(NOMINATIVE)][infix]."
Проверь этот момент, точно ли он падежит всё правильно? Мне кажется лучше уточнить ему, что падежить нужно сурс.
```suggestion
	var/f_name = "[src.declent_ru(NOMINATIVE)][infix]."
```

2022-08-05 14:38 UTC, PhantornRU commented on code/game/atoms.dm
> +		to_chat(user, "<span class='warning'>У вас нет ручки, чтобы переименовать [declent_ru(ACCUSATIVE)].</span>")
```suggestion
		to_chat(user, "<span class='warning'>У вас нет ручки, чтобы переименовать [src.declent_ru(ACCUSATIVE)].</span>")
```

2022-08-05 14:39 UTC, PhantornRU commented on code/game/atoms.dm
> +		to_chat(user, "<span class='warning'>Вы не можете переименовать [declent_ru(ACCUSATIVE)] отсюда.</span>")
Указать что именно падежит.

2022-08-05 14:40 UTC, PhantornRU commented on code/game/atoms.dm
> +		to_chat(user, "<span class='warning'>Вы не можете переименовать [declent_ru(ACCUSATIVE)] в вашем текущем состоянии.</span>")
Указать что именно падежит.

2022-08-05 14:43 UTC, PhantornRU commented on code/game/atoms_movable.dm
> +			to_chat(user, "<span class='warning'>[src.declent_ru(NOMINATIVE)] слишком тяжелый!</span>")
Да, знаю что это был когда-то мой старый перевод.
Тут тоже проверь, всё ли будет ок по падежу, т.к. предметы/объекты, да и в целом Атомы, если не ошибаюсь тоже имеют пол.
```suggestion
			to_chat(user, "<span class='warning'>[src.declent_ru(NOMINATIVE)] слишком тяжел[genderize_ru(src.gender,"ый","ая","ое","ые")]!</span>")
```

2022-08-05 14:44 UTC, PhantornRU commented on code/game/gamemodes/vampire/vampire.dm
> +	vampire_mind.current.visible_message("<span class='userdanger'>Кажется, будто тяжёлый груз упал с плеч [vampire_mind.current]!</span>", "<span class='userdanger'>Тёмная пелена спала с вашего рассудк
вынести слово отдельно от гендеризации

2022-08-05 14:46 UTC, PhantornRU commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	user.visible_message("<span class='warning'>Внешность [user.declent_ru(GENITIVE)] изменяется!</span>")
```suggestion
	user.visible_message("<span class='warning'>[user.declent_ru(GENITIVE)] преображается!</span>")
```

2022-08-05 14:47 UTC, PhantornRU commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		user.visible_message("<span class='warning'>[user.declent_ru(NOMINATIVE)] кусает [target.declent_ru(ACCUSATIVE)] в шею!</span>", "<span class='warning'>Вы кусаете [target.declent_ru(ACCUSATIVE)] в
Нужна гендеризация глаголов

2022-08-05 14:48 UTC, PhantornRU commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
А может так переведем, кстати?
```suggestion
		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] где-то витает, поэтому порабощение не удастся.</span>")
```

2022-08-05 14:49 UTC, PhantornRU commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		C.visible_message("<span class='warning'>Похоже что [C.declent_ru(NOMINATIVE)] сопротивляется захвату!</span>", "<span class='notice'>Вы ощущаете в голове знакомое ощущение, но оно быстро проходит.
Нужна гендеризация глаголов - сопротивля**[ЕТ/ЮТ]**ся.
Дионы например имеют множественный пол

2022-08-05 14:49 UTC, PhantornRU commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		C.visible_message("<span class='warning'>Похоже что [C.declent_ru(NOMINATIVE)] сопротивляется захвату!</span>", "<span class='notice'>Вера в [SSticker.Bible_deity_name] защищает ваш разум от всяког
Аналогично

2022-08-05 14:52 UTC, PhantornRU commented on code/game/machinery/Freezer.dm
> +	ru_names = list(NOMINATIVE = "нагреватель", GENITIVE = "нагревателя", DATIVE = "нагревателю", ACCUSATIVE = "нагреватель", INSTRUMENTAL = "нагревателем", PREPOSITIONAL = "нагревателе")
Может "Обогреватель"? Его чаще используют

2022-08-05 14:54 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	user.visible_message("<span class='suicide'>[user] Игра[pluralize_ru(user.gender,"ет","ют")] со смертью! Похоже [genderize_ru(user.gender, "он пытается", "она пытается", "оно пытается", "они пытаютс
Не стоит мешать всё в одну кучу
```suggestion
	user.visible_message("<span class='suicide'>[user] Игра[pluralize_ru(user.gender,"ет","ют")] со смертью! Похоже, он[genderize_ru(user.gender,"","а","о","и")] пыта[pluralize_ru(user.gender,"ется","ются")] покончить жизнь самоубийством!</span>")

```

2022-08-05 14:55 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	user.visible_message("<span class='suicide'>[user] играет со смертью! Похоже [genderize_ru(user.gender, "он пытается", "она пытается", "оно пытается", "они пытаются")] покончить жизнь самоубийством!
опять всё в куче

2022-08-05 14:56 UTC, PhantornRU commented on code/game/verbs/suicide.dm
> +		to_chat(viewers(src), "<span class='danger'>[src.declent_ru(NOMINATIVE)] [pick(dna.species.suicide_messages)] Похоже, что [genderize_ru(gender, "он хочет", "она хочет", "оно хочет", "они хотят")] с
опять куча мала

2022-08-05 14:56 UTC, PhantornRU commented on code/modules/food_and_drinks/drinks/drinks.dm
> +			. += "<span class='notice'> \The [src.declent_ru(NOMINATIVE)] наполовину наполон!</span>"// We're all optimistic, right?!
```suggestion
			. += "<span class='notice'> \The [src.declent_ru(NOMINATIVE)] наполовину полон!</span>"// We're all optimistic, right?!
```

2022-08-05 14:59 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +			status = "имеет ушибы"
отсутствует гендеризация.
"Помят" будет звучать получше. Тоже гендеризировать нужно

2022-08-05 15:03 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +			to_chat(src, "<span class='notice'>Вы пока что не хотите есть еще больше нездоровой пищи.</span>")
```suggestion
			to_chat(src, "<span class='notice'>Вам больше не хочется есть вредную пищу.</span>")
```

2022-08-05 15:05 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +			to_chat(src, "<span class='notice'>Вы не хотя берете кусок [toEat.declent_ru(GENITIVE)].</span>")
```suggestion
			to_chat(src, "<span class='notice'>Вы неохотно прожевываете немного [toEat.declent_ru(GENITIVE)].</span>")
```

2022-08-05 15:06 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +			to_chat(src, "<span class='warning'>Вы больше не можете заставить себя проглотить [toEat.declent_ru(ACCUSATIVE)].</span>")
```suggestion
			to_chat(src, "<span class='warning'>В вас больше не лезет [toEat.declent_ru(ACCUSATIVE)].</span>")
```

2022-08-05 15:07 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +			visible_message("<span class='warning'>[user.declent_ru(NOMINATIVE)] пытается насильно [src.declent_ru(ACCUSATIVE)] [toEat.apply_method] [toEat.declent_ru(ACCUSATIVE)].</span>")
ет/ют

2022-08-05 15:07 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +		visible_message("<span class='warning'>[user.declent_ru(NOMINATIVE)] больше не может насильно заставить [src.declent_ru(ACCUSATIVE)] проглотить [toEat.declent_ru(ACCUSATIVE)].</span>")
может/могут

2022-08-05 15:08 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +			visible_message("<span class='warning'>[user.declent_ru(NOMINATIVE)] пытается насильно [src.declent_ru(ACCUSATIVE)] [toEat.apply_method] [toEat.declent_ru(ACCUSATIVE)].</span>")
[pluralize_ru(user.gender,"ет","ют")]

2022-08-05 15:09 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/golem.dm
> +			"<span class='userdanger'>[P.declent_ru(NOMINATIVE)] тонет в песчаном теле [H.declent_ru(GENITIVE)] без видимого вреда здоровью!</span>")
ет/ют

2022-08-05 15:10 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/grey.dm
> +			to_chat(H, "<span class='danger'>[genderize_ru(H.wear_mask.gender, "Ваш", "Ваша", "Ваше", "Ваши")] [H.wear_mask.declent_ru(NOMINATIVE)] защищает вас от кислоты!</span>")
отделить ВАШ от гендеризации

2022-08-05 15:10 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/grey.dm
> +			to_chat(H, "<span class='danger'>[genderize_ru(H.wear_mask.gender, "Ваш", "Ваша", "Ваше", "Ваши")] [H.wear_mask.declent_ru(NOMINATIVE)] защищает вас от кислоты!</span>")
отделить слово от гендеризации

2022-08-05 15:11 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/skeleton.dm
> +		if(prob(3)) //3% шанс на случайную шутливую фразу
Правильно фикс, а то Мистер Скелетал из-за моей правки всех задалбывать начал)

2022-08-05 15:13 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/hostile/killertomato.dm
> +	attacktext = "ударяет"
Это гребаный томат убийца. У него зубы с половину его тела :)))
```suggestion
	attacktext = "вгрызается"
```

2022-08-05 15:14 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
> +	attacktext = "ударяет"
Иерофант, проникает своей волной
```suggestion
	attacktext = "проникает"
```

2022-08-05 15:14 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/hostile/netherworld.dm
> +	attacktext = "разрывает"
Миго заставляет твою голову ныть, он именно что мучает. Это создание сотоны
```suggestion
	attacktext = "мучает"
```

2022-08-05 15:15 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/hostile/retaliate/kangaroo.dm
> +	attacktext = "полоснул"
Это кенгуру, с чего он полощет, а не пинает?
```suggestion
	attacktext = "пинает"
```

2022-08-05 15:15 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/shade.dm
> +	attacktext = "высасывает жизнь из"
Это и есть опустошает
```suggestion
	attacktext = "опустошает"
```

2022-08-05 15:17 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +		. += "<span class='notice'>Используйте ручку, чтобы переименовать оружие.</span>"
```suggestion
		. += "<span class='notice'>Воспользуйтесь ручкой, для переименования оружия.</span>"
```

2022-08-05 15:20 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +		. += "Оружие имеет [can_bayonet ? "" : "перманентно "]закрепленн[genderize_ru(bayonet.gender, "ый", "ую", "ое", "ые")] [bayonet.declent_ru(ACCUSATIVE)]."
```suggestion
		. += "У оружия [can_bayonet ? "закрепленн[genderize_ru(bayonet.gender, "ый", "ую", "ое", "ые")]" : "встроен[genderize_ru(bayonet.gender, "ый", "ая", "ое", "ые")]"] [bayonet.declent_ru(ACCUSATIVE)]."
```

2022-08-05 15:21 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +			. += "<span class='info'>Похоже, что [bayonet.declent_ru(ACCUSATIVE)] можно снять отверткой.</span>"
```suggestion
			. += "<span class='info'>Похоже [bayonet.declent_ru(ACCUSATIVE)] можно снять отверткой.</span>"
```

2022-08-05 15:21 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +		. += "На оружии есть крепление для <b>байонеты</b>."
```suggestion
		. += "На оружии есть крепление для <b>штыка</b>."
```

2022-08-05 15:21 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +				user.visible_message("<span class='danger'>[user.declent_ru(NOMINATIVE)] стреляет из [src.declent_ru(GENITIVE)] в упор по [target.declent_ru(DATIVE)]!</span>", "<span class='danger'>Вы стреляете
ет/ют. Не забываем про дион с пулеметами

2022-08-05 15:22 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +				user.visible_message("<span class='danger'>[user.declent_ru(NOMINATIVE)] стреляет из [src.declent_ru(GENITIVE)]!</span>", "<span class='danger'>Вы стреляете из [src.declent_ru(GENITIVE)]!</span>"
ет/ют

2022-08-05 15:23 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +		to_chat(user, "<span class='userdanger'>Вам нужна вторая свободная рука для стрельбы из [src.declent_ru(GENITIVE)]!</span>")
```suggestion
		to_chat(user, "<span class='userdanger'>Для стрельбы из [src.declent_ru(GENITIVE)] нужны свободные руки!</span>")
```

2022-08-05 15:23 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +		to_chat(user, "<span class='danger'>[src.declent_ru(NOMINATIVE)] несовместим[genderize_ru(src, "", "а", "о", "и")] с вашей биологией!</span>")
```suggestion
		to_chat(user, "<span class='danger'>[src.declent_ru(NOMINATIVE)] несовместим[genderize_ru(src, "", "а", "о", "ы")] с вашей биологией!</span>")
```

2022-08-05 15:24 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +				to_chat(user, "<span class='warning'>[src.declent_ru(NOMINATIVE)] заряжен летальным патроном! Вы не хотите никому случайно навредить...</span>")
```suggestion
				to_chat(user, "<span class='warning'>[src.declent_ru(NOMINATIVE)] заряжен летальным патроном! Вам не хочется никому навредить...</span>")
```

2022-08-05 15:24 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +					to_chat(user, "<span class='warning'>[src.declent_ru(NOMINATIVE)] заряжен летальным патроном! Вы не хотите никому случайно навредить...</span>")
```suggestion
					to_chat(user, "<span class='warning'>[src.declent_ru(NOMINATIVE)] заряжен летальным патроном! Вам не хочется никому навредить...</span>")
```

2022-08-05 15:25 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +				to_chat(user, "<span class='notice'>Вы присоединили [S.declent_ru(ACCUSATIVE)] на [src.declent_ru(ACCUSATIVE)].</span>")
```suggestion
				to_chat(user, "<span class='notice'>Вы присоединили [S.declent_ru(ACCUSATIVE)] к [src.declent_ru(ACCUSATIVE)].</span>")
```

2022-08-05 15:26 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +				to_chat(user, "<span class='notice'>Вы назвали оружие - [name]. Скажи привет своему новому другу.</span>")
Никто не говорит "скажи ему привет"
```suggestion
				to_chat(user, "<span class='notice'>Вы назвали оружие - [name]. Передай привет своему новому другу.</span>")
```

2022-08-05 15:27 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +		to_chat(user, "<span class='notice'>Вы закрепили [K.declent_ru(ACCUSATIVE)] на крепление для байонетты у [src.declent_ru(GENITIVE)].</span>")
```suggestion
		to_chat(user, "<span class='notice'>Вы вставили [K.declent_ru(ACCUSATIVE)] на крепление штыка у [src.declent_ru(GENITIVE)].</span>")
```

2022-08-05 15:28 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +		visible_message("<span class='danger'>Свет от [src.declent_ru(GENITIVE)] тухнет и отключается.</span>")
```suggestion
		visible_message("<span class='danger'>Свет [src.declent_ru(GENITIVE)] тухнет и погасает.</span>")
```

2022-08-05 15:29 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +	var/choice = input(M,"Внимание! Вы можете поменять раскраску только один раз!","Перекраска оружия") in options
```suggestion
	var/choice = input(M,"Внимание! Вы можете перекрасить оружие только один раз!","Перекраска оружия") in options
```

2022-08-05 15:30 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +		to_chat(M, "У вашего оружия сейчас стоит раскраска [choice]. Скажи привет своему новому другу.")
```suggestion
		to_chat(M, "У вашего оружия сейчас раскраска [choice]. Передай привет своему новому другу.")
```

2022-08-05 15:30 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +		to_chat(M, "У вашего оружия сейчас стоит раскраска [choice]. Скажи привет своему новому другу.")
Но честно, я бы "новому" заменил на "Обновленному".

2022-08-05 15:32 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +				user.visible_message("<span class='notice'>[user.declent_ru(NOMINATIVE)] решает, что жизнь того стоит.</span>")
Думаю для более лучшего словца и против косоязычия:
```suggestion
				user.visible_message("<span class='notice'>[user.declent_ru(NOMINATIVE)] решает, что жизнь не так безнадежна.</span>")
```

2022-08-05 15:35 UTC, PhantornRU commented on code/modules/projectiles/guns/projectile/revolver.dm
> +		to_chat(user, "<span class='notice'>Вы заряжаете [num_loaded] единиц боезапаса в [src.declent_ru(ACCUSATIVE)].</span>")
единиц боезопаса лучше заменить на "патрон[/ов]"

2022-08-05 15:35 UTC, PhantornRU commented on code/modules/projectiles/guns/projectile/revolver.dm
> +		to_chat(user, "<span class='notice'>Вы разряжаете [num_unloaded] единиц боезапаса из [src.declent_ru(GENITIVE)].</span>")
тоже самое

2022-08-05 15:36 UTC, PhantornRU commented on code/modules/reagents/chemistry/machinery/pandemic.dm
> +		visible_message("<span class='notice'>[src.declent_ru(NOMINATIVE)] гремит и печатает лист бумаги.</span>")
ит/ят
ет/ют

2022-08-05 15:37 UTC, PhantornRU requested changes
Проверил перевод, убил пару часов. Жду исправлений

2022-08-05 15:41 UTC, PhantornRU commented
Мог какие-то моменты пропустить. Но если ты какие-то слова в кучу смешивал и я на это не указал, или ет/ют пропустил, не указал что именно нужно гендеризировать - это тоже самостоятельно поправь

2022-08-06 01:57 UTC, PhantornRU requested changes

2022-08-06 01:57 UTC, PhantornRU commented on code/datums/mind.dm
> +			output += "<LI><B>Задача #[obj_count]</B>: [objective.get_description("ru")]</LI>"
Хммм, а может как "запрос" сделать?

2022-08-06 01:58 UTC, PhantornRU commented on code/datums/mind.dm
> +			output += "<LI><B>Задача #[obj_count]</B>: [objective.get_description("ru")]</LI>"
Да, давай тогда лучше на "запрос" поменяем. Это гораздо логичнее и не будет сливаться с другими задачами.

2022-08-08 09:29 UTC, larentoun commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Это набор челюстей жизни, и магия науки позволила нам поместить это в достаточно маленькое устройство, чтобы оно вместилось в пояс для инструментов. Установлена выпирающая головка"
Да и вообще, оставить их так или в "гидравлические" перевести?

2022-08-08 09:29 UTC, larentoun commented on code/game/objects/items/tools/wirecutters.dm
> +	desc = "Это набор челюстей жизни, и магия науки позволила нам поместить это в достаточно маленькое устройство, чтобы оно вместилось в пояс для инструментов. Установлена разрезающая головка"
.

2022-08-08 09:29 UTC, larentoun commented on code/game/objects/items/toys.dm
> +	. +=  "Из них заряжено: [fake_bullets]"
Есть лучше идеи?

2022-08-08 09:29 UTC, larentoun commented on code/modules/mob/living/simple_animal/bot/bot.dm
> +	visible_message("<span class='danger'>[user.declent_ru(NOMINATIVE)] полоснул [src.declent_ru(ACCUSATIVE)]!</span>")
.

2022-08-08 09:29 UTC, larentoun commented on code/modules/projectiles/gun.dm
> +			to_chat(user, "<span class='notice'>Вы открутили фонарик от [src.declent_ru(GENITIVE)].</span>")
.

2022-08-08 09:29 UTC, larentoun commented on code/modules/projectiles/guns/projectile.dm
> +	. += "Боезапаса внутри: [get_ammo()]"
.

2022-08-08 09:29 UTC, larentoun commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	. += "Из них заряжено: [get_ammo(0,0)]"
.

2022-08-08 09:29 UTC, larentoun commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	desc = "Сильный ретро авторевольвер, который обычно используется офицерами Новорусской армии. Использует патроны калибра .357"	//>10mm hole >.357
.

2022-08-08 09:29 UTC, larentoun commented on code/game/objects/items.dm
> +			size = "гигантский"
.

2022-08-08 09:29 UTC, larentoun commented on code/game/objects/items.dm
> +			size = "огромный"
.

2022-08-08 09:29 UTC, larentoun commented on code/game/objects/items.dm
> +			size = "громоздкий"
.

2022-08-08 09:29 UTC, larentoun commented on code/game/objects/items.dm
> +			size = "обычного размера"
.

2022-08-08 09:29 UTC, larentoun commented on code/game/objects/items.dm
> +			size = "маленький"
.

2022-08-08 09:29 UTC, larentoun commented on code/game/objects/items.dm
> +			size = "крохотный"
.

2022-08-08 09:29 UTC, larentoun commented on code/game/turfs/simulated/floor/plating.dm
> +			visible_message("<span class='danger'>[user.declent_ru(NOMINATIVE)] проламывает [src.declent_ru(ACCUSATIVE)] с помощью [C.declent_ru(GENITIVE)]!</span>")
.

2022-08-08 09:29 UTC, larentoun commented on code/game/turfs/simulated/floor/plating.dm
> +			visible_message("<span class='warning'>[C.declent_ru(NOMINATIVE)] отскакивает от [src.declent_ru(GENITIVE)]!</span>")
.

2022-08-08 09:29 UTC, larentoun commented on code/game/turfs/simulated/floor/plating.dm
> +		M.visible_message("<span class='notice'>[M.declent_ru(NOMINATIVE)] подталкивает [src.declent_ru(ACCUSATIVE)].</span>")
.

2022-08-08 09:29 UTC, larentoun commented on code/game/atoms.dm
> +	var/atom_say_verb = "говорит"
Хм, тогда думаю лучше по умолчанию оставить. Не желательно тут делать функции

2022-08-08 09:29 UTC, larentoun commented on code/game/atoms.dm
> +	var/f_name = "[declent_ru(NOMINATIVE)][infix]."
Стоит, да. И подежит нормально

2022-08-08 09:29 UTC, larentoun commented on code/modules/mob/living/carbon/carbon.dm
>  			status = "weirdly shapen."
.

2022-08-08 09:29 UTC, larentoun commented on code/modules/mob/living/carbon/human/species/skeleton.dm
> +		if(prob(3)) //3% шанс на случайную шутливую фразу
:D

2022-08-08 09:29 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/netherworld.dm
> +	attacktext = "разрывает"
А, вот оно как

2022-08-08 09:29 UTC, larentoun commented on code/game/atoms.dm
> +			. += "<span class='notice'>Контейнер содержит:</span>"
Подождем мнения остальных, сам не знаю, как лучше.

2022-08-08 09:29 UTC, larentoun commented on code/game/atoms.dm
> +				. += "<span class='danger'>Контейнер пуст.</span>"
Или уточнить, что "Внутри пусто.". Подождем остальных

2022-08-08 09:29 UTC, larentoun commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
Тоже можно, подождем остальных

2022-08-08 09:29 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/killertomato.dm
> +	attacktext = "ударяет"
По звуку, видимо, томат всей своей массой таранит)

2022-08-08 09:29 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
> +	attacktext = "ударяет"
По звуку, видимо, он сам собой бьет. Он же палка! Надо в игре глянуть

2022-08-08 09:29 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/retaliate/kangaroo.dm
> +	attacktext = "полоснул"
По звуку и комментарию - у кенгуру очень острые когти тут :D

2022-08-08 09:29 UTC, larentoun commented on code/modules/projectiles/gun.dm
> +		to_chat(M, "У вашего оружия сейчас стоит раскраска [choice]. Скажи привет своему новому другу.")
Тут вероятно больше фокус на то, что именно сейчас пушка стала другом, с именем

2022-08-08 09:29 UTC, larentoun commented on code/modules/projectiles/guns/projectile/revolver.dm
> +		to_chat(user, "<span class='notice'>Вы заряжаете [num_loaded] единиц боезапаса в [src.declent_ru(ACCUSATIVE)].</span>")
1 патрон, 2-4 патрона, 5+ патронов. Неужели проверку пихать на последнюю цифру? Нужно что-то придумать

2022-08-08 09:29 UTC, larentoun commented on code/modules/projectiles/guns/projectile/revolver.dm
> +		to_chat(user, "<span class='notice'>Вы разряжаете [num_unloaded] единиц боезапаса из [src.declent_ru(GENITIVE)].</span>")
ответ выше

2022-08-08 09:33 UTC, VasilevAY commented on code/datums/mind.dm
> +	var/output = {"<meta charset="UTF-8"><B>Память [current.real_name]:</B><HR>"}
Здесь лучше "Воспоминания", как мне кажется

2022-08-08 09:33 UTC, VasilevAY commented on code/datums/mind.dm
> +		output += "<HR><B>Должностные задачи:</B><UL>"
Еще лучше звучит "должностные инструкции"

2022-08-08 09:33 UTC, VasilevAY commented on code/game/atoms.dm
> +			. += "<span class='notice'>Контейнер содержит:</span>"
а почему нельзя "В контейнере : "?

2022-08-08 09:34 UTC, PhantornRU commented on code/datums/mind.dm
> +	var/output = {"<meta charset="UTF-8"><B>Память [current.real_name]:</B><HR>"}
Согласен, так будет лучше

2022-08-08 09:34 UTC, PhantornRU commented on code/datums/mind.dm
> +		output += "<HR><B>Должностные задачи:</B><UL>"
Инструкции здесь излишни и не подходят по смыслу

2022-08-08 09:34 UTC, larentoun commented on code/game/atoms.dm
> +			. += "<span class='notice'>Контейнер содержит:</span>"
Можно еще как вариант "Внутри:"

2022-08-08 09:35 UTC, PhantornRU commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
Уж точно не оставлять "сейчас не здесь". Это очень плохое словосочетание.

2022-08-08 09:36 UTC, PhantornRU commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Это набор челюстей жизни, и магия науки позволила нам поместить это в достаточно маленькое устройство, чтобы оно вместилось в пояс для инструментов. Установлена выпирающая головка"
Челюсти Жизни - это название, лучше их так и оставить.

2022-08-08 09:37 UTC, PhantornRU commented on code/game/objects/items/toys.dm
> +	. +=  "Из них заряжено: [fake_bullets]"
Патронтаж

2022-08-08 09:38 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/hostile/killertomato.dm
> +	attacktext = "ударяет"
Звук - это заглушка. Этот томат злой и беспощадный. Он точно не банально бьет.

2022-08-08 09:38 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
> +	attacktext = "ударяет"
Не по звуку думай, а по логике.

2022-08-08 09:39 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/hostile/retaliate/kangaroo.dm
> +	attacktext = "полоснул"
Not sound. Use logic

Вообще, лапами не только синяки можно поставить с размаха, но и надрезать. + "пинок" был изначально.

2022-08-08 09:40 UTC, PhantornRU commented on code/game/atoms.dm
> +			. += "<span class='notice'>Контейнер содержит:</span>"
Внутри находятся предметы. А это реагенты.

Нужно использовать содержание, либо емкость. Тоесть:
- Содержит:
- Емкость содержит:

2022-08-08 09:40 UTC, VasilevAY commented on code/game/atoms.dm
> +			. += "<span class='notice'>Контейнер содержит:</span>"
> Можно еще как вариант "Внутри:"

звучит классно

2022-08-08 09:41 UTC, PhantornRU commented on code/game/atoms.dm
> +				. += "<span class='danger'>Контейнер пуст.</span>"
Можно так, действительно

2022-08-08 09:41 UTC, VasilevAY commented on code/game/atoms.dm
> +				. += "<span class='danger'>Контейнер пуст.</span>"
> Или уточнить, что "Внутри пусто.". Подождем остальных

Звучит классно

2022-08-08 09:42 UTC, VasilevAY commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
а напомните контекст, что происходит?

2022-08-08 09:43 UTC, VasilevAY commented on code/modules/projectiles/guns/projectile/revolver.dm
> +		to_chat(user, "<span class='notice'>Вы заряжаете [num_loaded] единиц боезапаса в [src.declent_ru(ACCUSATIVE)].</span>")
вариант, когда нужно еще падежи учитывать - плохо, надо подумать, согласен

2022-08-08 09:44 UTC, VasilevAY commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Это набор челюстей жизни, и магия науки позволила нам поместить это в достаточно маленькое устройство, чтобы оно вместилось в пояс для инструментов. Установлена выпирающая головка"
Лучше так 
Это - "Челюсти Жизни", и магия....

"набор челюстей жизни" - выглядит и звучит плохо

2022-08-08 09:46 UTC, PhantornRU commented on code/game/atoms.dm
> +			. += "<span class='notice'>Контейнер содержит:</span>"
Против "Внутри". Нужно делать упор на "Содержание" и/или Емкость. Т.к. это идёт работа именно с реагентами и емкостями, а не всякими коробками.

2022-08-08 09:47 UTC, larentoun commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
Во время траллирования цель была в ССД/в гостах

2022-08-08 09:47 UTC, PhantornRU commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
игрок покинул тело (админ ф6 или кататоник)

2022-08-08 09:48 UTC, PhantornRU commented on code/modules/projectiles/gun.dm
> +		to_chat(M, "У вашего оружия сейчас стоит раскраска [choice]. Скажи привет своему новому другу.")
значит оставляем "новому другу"

2022-08-08 09:48 UTC, PhantornRU commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Это набор челюстей жизни, и магия науки позволила нам поместить это в достаточно маленькое устройство, чтобы оно вместилось в пояс для инструментов. Установлена выпирающая головка"
согласен

2022-08-08 09:49 UTC, larentoun commented on code/game/objects/items/toys.dm
> +	. +=  "Из них заряжено: [fake_bullets]"
"Боезапаса внутри:" сменить на "Патронтаж:"?

2022-08-08 09:51 UTC, VasilevAY commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
ага
Предлагаю так
"Душа name покинуло тело, поэтому порабощение не удастся"

2022-08-08 09:54 UTC, VasilevAY commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
> 

кстати, говно идея. Нужен падеж на это.

2022-08-08 09:55 UTC, PhantornRU commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
покинула*

Душа - женский род

2022-08-08 09:57 UTC, larentoun commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
Падежы не проблема - скоро сделаю систему для падежей имен персонажей

2022-08-08 09:57 UTC, larentoun commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Разум [C.declent_ru(GENITIVE)] сейчас не здесь, поэтому порабощение не удастся.</span>")
Тогда лучше вариант с "Душа покинула"?

2022-08-08 10:01 UTC, VasilevAY commented on code/game/objects/items.dm
> +			size = "обычного размера"
в остальных размер пишется без приставки "... размера", а тут обычного размера
Может просто "обычный"?

2022-08-08 10:05 UTC, PhantornRU commented on code/modules/projectiles/guns/projectile/revolver.dm
> +		to_chat(user, "<span class='notice'>Вы заряжаете [num_loaded] единиц боезапаса в [src.declent_ru(ACCUSATIVE)].</span>")
пока можно оставить так как есть и оставить мозгоебку для потомков. СБ-шники переводчики думаю когда-нибудь да поправят как им самим хочется и напишут падежные системы.

2022-08-08 10:05 UTC, PhantornRU commented on code/game/objects/items/toys.dm
> +	. +=  "Из них заряжено: [fake_bullets]"
пока можно оставить так как есть и оставить мозгоебку для потомков. СБ-шники переводчики думаю когда-нибудь да поправят как им самим хочется и напишут падежные системы.

2022-08-08 12:38 UTC, PhantornRU approved these changes

2022-08-08 13:14 UTC, VasilevAY approved these changes

2022-08-08 13:16 UTC, PhantornRU approved these changes

2022-08-09 13:38 UTC, larentoun commented
Надо новый коммит проверить. Я вроде потыкала - работает

2022-12-10 20:02 UTC, closed without merging