Добавление анимаций при взаимодействии с предметами (взять/положить)
ss220-space/Paradise pull request #1166
Opened 2022-08-07 18:14 UTC by EtoZheJih

## What Does This PR Do
Добавляет анимации при взаимодействии с предметами (взять предмет/положить предмет), работает со столами, полом и контейнерами.
Добавляет преф, который будет выключать анимации в случае, если юзеру они не нравятся.
При использовании перчаток с перком pickpoint - анимация поднятия предметов НЕ будет воспроизводиться

Делается по предложке https://discord.com/channels/617003227182792704/618952559607939072/1005449320260177991
(В момент публикации ПРа соотношение голосов 140 ЗА - 13 ПРОТИВ, так что заранее его выкладываю)

## Why It's Good For The Game
Это красиво
Это немного дополняет РП образ

## Images of changes
![af9c8f8e506d6bad](https://user-images.githubusercontent.com/81481817/183305092-512d1bf7-ce92-4649-930a-7dc37051688e.gif)

## Changelog
:cl:
add: Добавлены анимации, новый преф
/:cl:

2022-08-07 18:51 UTC, larentoun requested changes

2022-08-07 18:51 UTC, larentoun commented on code/game/objects/items.dm
> +	if(isturf(original_loc))
Может, сначала стоит делать проверку преференса, а потом все остальные?

2022-08-07 18:51 UTC, larentoun commented on code/game/objects/items.dm
> +	if(!istype(loc, /turf))
!isturf()

2022-08-07 18:51 UTC, larentoun commented on code/game/objects/items.dm
> +	if(!istype(loc, /turf))
!isturf()

2022-08-07 18:51 UTC, larentoun commented on code/game/objects/items.dm
> +	var/original_loc = loc
А обязательно нужна эта переменная? loc где-то меняется до строки 296?

2022-08-07 18:51 UTC, larentoun commented on code/game/objects/items.dm
> +		var/show_anim = (user.client.prefs.toggles2 & PREFTOGGLE_2_PICKUP_ANIMATIONS)
Ты ведь сделал макрос check_animations()

2022-08-07 18:51 UTC, larentoun commented on code/game/objects/structures/crates_lockers/closets.dm
> +			if((user.client.prefs.toggles2 & PREFTOGGLE_2_PICKUP_ANIMATIONS))
Сделан макрос check_animations()

2022-08-07 18:51 UTC, larentoun commented on code/game/objects/structures/tables_racks.dm
> +	if((user.client.prefs.toggles2 & PREFTOGGLE_2_PICKUP_ANIMATIONS))
Сделан макрос check_animations()

2022-08-07 18:51 UTC, larentoun commented on code/modules/mob/living/carbon/human/inventory.dm
> +	var/show_anim = (user.client.prefs.toggles2 & PREFTOGGLE_2_PICKUP_ANIMATIONS)
Сделан макрос check_animations()

2022-08-08 10:48 UTC, EtoZheJih commented
Кукла одна, префы включены - анимации работают
Кукла одна, префы отключены - анимации не работают
Куклы две, смотрим от лица куклы с отключенными префами - анимации не работают, КРОМЕ АНИМАЦИИ "Положить на стол"
Я не понимаю как это пофиксить, нужна помощь

2022-08-08 11:30 UTC, larentoun requested changes

2022-08-08 11:30 UTC, larentoun commented on code/modules/mob/inventory.dm
> +/mob/proc/put_in_hands(obj/item/W, ignore_anim = TRUE)
А у тебя где-то переменная ignore_anim используется?

2022-08-08 11:30 UTC, larentoun commented on code/modules/mob/living/carbon/human/inventory.dm
>  /mob/living/carbon/human/put_in_hands(obj/item/I)
Видимо, здесь ты и должен был использовать эту переменную ignore_anim. Либо меняй, либо удаляй переменную

2022-08-08 11:30 UTC, larentoun commented on code/game/objects/items.dm
> +/obj/item/proc/do_pickup_animation(atom/target)
Так как ты всегда передаешь mob, лучше не atom/target, а сразу на моба. Не нужно будет делать новую переменную var/mob/user = target

2022-08-08 11:30 UTC, larentoun commented on code/game/objects/items.dm
> +/obj/item/proc/do_pickup_animation(atom/target)
Так же, у тебя ведь эти две функции почти идентичны. Собери их в одну и добавь флаг-условие, что выбирается подбирание или выброс предмета

2022-08-09 17:30 UTC, Vallat requested changes

2022-08-09 17:30 UTC, Vallat commented on code/game/objects/items.dm
> +			animate(alpha = 0, transform = matrix().Scale(0.7), time = 1)
```suggestion
	
		var/image/pickup_animation = image(icon = src, loc = loc, layer = layer + 0.1)
		pickup_animation.plane = GAME_PLANE
		pickup_animation.transform.Scale(0.75)
		pickup_animation.appearance_flags = APPEARANCE_UI_IGNORE_ALPHA

		var/turf/current_turf = get_turf(src)
		var/direction = get_dir(current_turf, user)
		var/to_x = user.pixel_x
		var/to_y = user.pixel_y

		if(direction & NORTH)
			to_y += 32
		else if(direction & SOUTH)
			to_y -= 32
		if(direction & EAST)
			to_x += 32
		else if(direction & WEST)
			to_x -= 32
		if(!direction)
			to_y += 10
			pickup_animation.pixel_x += 6 * (prob(50) ? 1 : -1) //6 to the right or left, helps break up the straight upward move

		flick_overlay(pickup_animation, pickup_viewing, 4)
		var/matrix/animation_matrix = new(pickup_animation.transform)
		animation_matrix.Turn(pick(-30, 30))
		animation_matrix.Scale(0.65)

		animate(pickup_animation, alpha = 175, pixel_x = to_x, pixel_y = to_y, time = 3, transform = animation_matrix, easing = CUBIC_EASING)
		animate(alpha = 0, transform = matrix().Scale(0.7), time = 1)
```

2022-08-09 17:30 UTC, Vallat commented on code/game/objects/items.dm
> +			animate(src, alpha = old_alpha, pixel_x = old_x, pixel_y = old_y, transform = old_transform, time = 3, easing = CUBIC_EASING)
```suggestion

		var/image/drop_animation = image(icon = src, loc = loc, layer = layer + 0.1)
		var/matrix/old_transform = drop_animation.transform
		drop_animation.plane = GAME_PLANE
		drop_animation.transform.Scale(0.7)
		drop_animation.transform.Turn(pick(-30, 30))
		drop_animation.appearance_flags = APPEARANCE_UI_IGNORE_ALPHA

		var/turf/current_turf = get_turf(src)
		var/direction = get_dir(user, current_turf)
		var/from_x = user.pixel_x
		var/from_y = user.pixel_y

		if(direction & NORTH)
			from_y -= 32
		else if(direction & SOUTH)
			from_y += 32
		if(direction & EAST)
			from_x -= 32
		else if(direction & WEST)
			from_x += 32
		if(!direction)
			from_y += 10
			from_x += 6 * (prob(50) ? 1 : -1) //6 to the right or left, helps break up the straight upward move

			//We're moving from these chords to our current ones
			var/old_x = pixel_x
			var/old_y = pixel_y
			var/old_alpha = alpha

			drop_animation.pixel_x = from_x
			drop_animation.pixel_y = from_y
			drop_animation.alpha = 0

			flick_overlay(drop_animation, drop_viewing, 3)

			// This is instant on byond's end, but to our clients this looks like a quick drop
			animate(drop_animation, alpha = old_alpha, pixel_x = old_x, pixel_y = old_y, transform = old_transform, time = 3, easing = CUBIC_EASING)
```

2022-08-09 18:22 UTC, closed without merging