Feat: Дюрантканевый дюффельбаг. Не мержить пока не пройдет голосовалка
ss220-space/Paradise pull request #1188
Opened 2022-08-11 20:00 UTC by frikadeliSpaghetti

Добавил новый дюффельбаг.
Крафт из шести листов дюраткани, не имеет штрафа к скорости. 
![storage_duffel-durathread](https://user-images.githubusercontent.com/48985748/184228792-bebf1560-6a90-45a4-935f-b2ab7923f845.png)
![clothing_lefthand_duffel-durathread](https://user-images.githubusercontent.com/48985748/184228881-bec0335d-1d49-4e2a-9c38-8ef98440e0fb.png)
![clothing_righthand_duffel-durathread](https://user-images.githubusercontent.com/48985748/184228924-a7c3586e-79f4-42d0-8ccc-6ccd8c9146f5.png)
![back_duffel-durathread](https://user-images.githubusercontent.com/48985748/184229005-e3718bce-c4ef-4f5d-81e9-a09676a2ed17.png)

2022-08-12 13:04 UTC, larentoun reviewed
А почему уменьшился размер icons/mob/back.dmi ?

2022-08-12 13:09 UTC, larentoun requested changes

2022-08-12 13:09 UTC, larentoun commented on code/game/objects/items/weapons/storage/backpack.dm
> +/obj/item/storage/backpack/durathread
Ты ведь сделал дуффель, почему он наследуется не от дуффеля, а от обычного рюкзака?

2022-08-12 18:41 UTC, frikadeliSpaghetti commented on code/game/objects/items/weapons/storage/backpack.dm
> +/obj/item/storage/backpack/durathread
оу, проглядел

2022-08-12 19:07 UTC, larentoun approved these changes

2022-08-16 13:05 UTC, Bizzonium commented
![image](https://user-images.githubusercontent.com/8555356/184886625-faaf570c-ea01-4fd9-8652-074f542478bf.png)

2022-08-16 13:43 UTC, frikadeliSpaghetti commented
короче, просто переделаю пр

2022-08-16 13:43 UTC, closed without merging

2022-08-16 13:47 UTC, PhantornRU commented
> короче, просто переделаю пр

зачем переделывать, просто реши конфликт и всё.
Сохрани те файлы которые у тебя щас есть (бекап), потом замержи конфликтные правки, они перепишут твой файл. После чего уже в них добавь свои иконки. И всё, конфликт решен.