Tweak: Generalist can upgrade hypospray
ss220-space/Paradise pull request #1197
Opened 2022-08-13 18:14 UTC by Robustin4

Теперь с помощью того же улучшения, что и медборга, можно улучшить гипоспрей генералиста, теперь там может быть помимо имеющихся уголь, салициловая кислота и сальбутамол.

2022-10-26 07:05 UTC, Dimach commented
Если я правильно понимаю код второго комита то он позволит ЛЮБОМУ боргу дать сох, лавапруф и тд, а это не годится. Откатывай второй комит целиком, первый я закину на воут

2022-10-26 07:28 UTC, Robustin4 commented
Я просто хотел сделать больше генералисту улучшений. Ладно ща будет.

2022-10-26 07:28 UTC, Robustin4 commented
Я ещё не за Компом. Найду время.

2022-10-26 09:00 UTC, Dimach commented
На самом деле можешь подождать конца воута, но судя по всему народ не настроен вообще бафать генералиста хоть бы и на капельку, а значи у тебя будет время на доработку/переработку

2022-10-27 01:28 UTC, Dimach requested changes
Нет нужды в этой куче проверок, если код дошел до этого момента то значит что у борга нет гипоспрея и H и H2 == 0

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +	if(!H)
```suggestion
	to_chat(usr, "<span class='notice'>There's no hypospray in this unit!</span>")
	return 0
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +			return
```suggestion
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +		if(H2)
```suggestion
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +		else
```suggestion
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +			to_chat(usr, "<span class='notice'>There's no hypospray in this unit!</span>")
```suggestion
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +			return 0
```suggestion
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +	else if(!H2)
```suggestion
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +		if(H)
```suggestion
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +			return
```suggestion
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +		else
```suggestion
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +			to_chat(usr, "<span class='notice'>There's no hypospray in this unit!</span>")
```suggestion
```

2022-10-27 01:28 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +			return 0
```suggestion
```

2022-10-27 01:39 UTC, Dimach commented on code/game/objects/items/robot/robot_upgrades.dm
> +			return 0
```suggestion
	to_chat(usr, "<span class='notice'>There's no hypospray in this unit!</span>")
	return 0
```

2022-10-29 10:17 UTC, merged