Tweak: Оружие для гейта
ss220-space/Paradise pull request #1199
Opened 2022-08-14 05:55 UTC by PhantornRU

## What Does This PR Do
- Добавлена возможность крафта оружия для гейта.
- Крафт оружия без кейса, т.к. оно безопасно.
- Нарисована уникальная иконка.
- Усредненные технологии и стоимость между лазером и АЕГом.
- Оружия в гейте пауков обновили спрайты
- Маленький рефактор, перенос оружия из кода гейта в код оружий.

Сделано по запросу Максима Wycc220 на Прайм.
https://discord.com/channels/617003227182792704/734823601110515882/1008135365284073522

Голосование для добавления на мейн проведется отдельно.

## Why It's Good For The Game

- Гейтерам не придется бегать весь раунд за пушками и ХОС более охотно выдает им оружие.

## Images of changes

Слева АЕГ, справа Gate-Gun
![image](https://user-images.githubusercontent.com/41479614/184524459-f10d520f-79c7-4a7f-9ac6-79faf09bab2b.png)

2022-08-14 09:20 UTC, dj-34 requested changes
1. Название не соответствует запросу
2. Вырезан режим стана и дизейбла?

![image](https://user-images.githubusercontent.com/20109643/184530543-6ec78f78-18c6-4978-be50-6b11a781196a.png)

2022-08-14 10:00 UTC, PhantornRU commented
> 

1. Прямо на стриме Мэксон выбрал вариант с переделкой уже существующего оружия. Я ему предлагал его вариант и текущий. Он выбрал текущий.
2. Это лазерная пушка, у него не может быть стана и дизейбла.

2022-08-14 10:43 UTC, Den109G commented
Может, если ток на Прайм, сменить ветку, куда хочешь залить ПР?

2022-08-14 10:58 UTC, dj-34 approved these changes

2022-08-14 14:49 UTC, larentoun commented
> * Маленький рефактор, перенос оружия из кода гейта в код оружий.

Этот рефактор можно и на мейны пустить спокойно

2022-08-14 14:51 UTC, larentoun commented on code/modules/projectiles/guns/energy/laser.dm
> +	selfcharge = 1 // Selfcharge is enabled and disabled, and used as the away mission tracker
Может лучше заменить на TRUE? Он же либо 0, либо 1

2022-08-14 15:01 UTC, PhantornRU commented on code/modules/projectiles/guns/energy/laser.dm
> +	selfcharge = 1 // Selfcharge is enabled and disabled, and used as the away mission tracker
Нужно тогда всё оружие доделывать, иначе будет выбиваться.

2022-08-14 15:31 UTC, larentoun commented on code/modules/projectiles/guns/energy/laser.dm
> +	selfcharge = 1 // Selfcharge is enabled and disabled, and used as the away mission tracker
Так дальше в коде я вижу, что ты ставить selfcharge = TRUE/FALSE. Оно работает?

2022-08-15 05:23 UTC, PhantornRU commented
По запросу Максона добавлена возможность ЕМАГа оружия, после которого он может стрелять и заряжаться не только в гейте.
![image](https://user-images.githubusercontent.com/41479614/184580902-5ea52924-b423-4889-8e8d-21b348783d00.png)

> Название оружия не соответствует запросу
Разделил ГЕЙТОВСКОЕ и РНДшное печатанное оружие разными названиями.
> Может лучше заменить на TRUE? Он же либо 0, либо 1
Заменил на TRUE/FALSE

2022-08-15 05:24 UTC, PhantornRU commented on code/modules/projectiles/guns/energy/laser.dm
> +	selfcharge = 1 // Selfcharge is enabled and disabled, and used as the away mission tracker
Поправил

2022-08-15 08:05 UTC, larentoun commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Первый прототип самозаряжающегося оружия для исследований вне станции и ближайших к ней секторов. Благодаря встроенному экспериментальному миниатюрному реактору и записанными протоколами сис
Лучшее описание, вам пять с плюсом!

2022-08-15 08:05 UTC, larentoun approved these changes

2022-08-15 10:30 UTC, dj-34 commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Первый прототип самозаряжающегося оружия для исследований вне станции и ближайших к ней секторов. Благодаря встроенному экспериментальному миниатюрному реактору и записанными протоколами сис
Согласен, целый лор лять xD

2022-08-15 10:31 UTC, dj-34 approved these changes

2022-08-16 13:15 UTC, Bizzonium commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Первый прототип самозаряжающегося оружия для исследований вне станции и ближайших к ней секторов. Благодаря встроенному экспериментальному миниатюрному реактору и записанными протоколами сис
Мне не нравится данное описание и упоминание игровых персонажей. Это заставляет персонажей знать историю и лор этих событий из раунда в раунд

2022-08-16 13:16 UTC, Bizzonium commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Первый прототип самозаряжающегося оружия для исследований вне станции и ближайших к ней секторов. Благодаря встроенному экспериментальному миниатюрному реактору и записанными протоколами сис
К тому же, компания не может называться П.У.П.С., это неправдоподобно

2022-08-16 13:19 UTC, PhantornRU commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Первый прототип самозаряжающегося оружия для исследований вне станции и ближайших к ней секторов. Благодаря встроенному экспериментальному миниатюрному реактору и записанными протоколами сис
```suggestion
	desc = "Первый прототип оружия с миниатюрным реактором и записанными протоколами безопасности для исследований в крайне отдаленных секторах.

2022-08-16 13:20 UTC, PhantornRU commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Первый прототип самозаряжающегося оружия для исследований вне станции и ближайших к ней секторов. Благодаря встроенному экспериментальному миниатюрному реактору и записанными протоколами сис
> К тому же, компания не может называться П.У.П.С., это неправдоподобно

Убрал ЛОРную часть, оставил только основу.

2022-08-16 13:31 UTC, PhantornRU commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Первый прототип оружия с миниатюрным реактором и записанными протоколами безопасности для исследований в крайне отдаленных секторах.
```suggestion
	desc = "Первый прототип оружия с миниатюрным реактором для исследований в крайне отдаленных секторах. Данную модель невозможно подключить к зарядной станции, во избежание истощения подключенных источников питания, в связи с протоколами безопасности, опустошающие заряд при нахождении вне предназначенных мест использования устройств. 
```

2022-08-16 13:31 UTC, PhantornRU commented on code/modules/projectiles/guns/energy/laser.dm
> +	name = "Exploreverse Strangler MK1"
```suggestion
	name = "Exploreverse MK1"
```

2022-08-16 13:33 UTC, PhantornRU reviewed
Внесение правок в описание в соответствии с нормами по описаниям у распечатаных оружий (пример Lazarus injector, wormhole jaunter)

2022-08-17 10:32 UTC, Bizzonium commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Первый прототип оружия с миниатюрным реактором для исследований в крайне отдаленных секторах. Данную модель невозможно подключить к зарядной станции, во избежание истощения подключенных исто
```suggestion
	desc = "Первый прототип оружия с миниатюрным реактором для исследований в крайне отдаленных секторах. Данную модель невозможно подключить к зарядной станции, во избежание истощения подключенных источников питания, в связи с протоколами безопасности, опустошающие заряд при нахождении вне предназначенных мест использования устройств."
```

2022-08-17 10:33 UTC, Bizzonium commented on code/modules/projectiles/guns/energy/laser.dm
> +	if (!emagged)
```suggestion
	if (emagged)
		return
```

2022-08-17 10:33 UTC, Bizzonium commented on code/modules/projectiles/guns/energy/laser.dm
> +	if (!emagged)
Над

2022-08-17 10:34 UTC, Bizzonium commented on code/modules/projectiles/guns/energy/laser.dm
> +	if (!emagged)
тут тоже пирамида

2022-08-17 11:02 UTC, PhantornRU commented
Произвел корректировку, всё стабильно работает.
![image](https://user-images.githubusercontent.com/41479614/185102602-b45466d3-917e-4572-9263-1c124aafb02c.png)

2022-08-18 10:33 UTC, PhantornRU commented
Авоут на мейн не пройден, заливать только на ПРАЙМ
https://discord.com/channels/617003227182792704/755125334097133628/1009769394034970644

2022-08-18 14:05 UTC, PhantornRU commented
ПР закрыт, т.к. педали против заливания на мейн, создан ПР для переноса сразу на Прайм 
https://github.com/ss220-space/Paradise/pull/1224

2022-08-18 14:05 UTC, closed without merging