Перевести события и коды безопасности
ss220-space/Paradise pull request #12
Opened 2021-05-28 18:33 UTC by MorgoWizard

Большая часть событий переведена, как и коды безопасности

2021-05-28 18:55 UTC, semoro requested changes

2021-05-28 18:55 UTC, semoro commented on code/modules/events/abductor.dm
> +		message_admins("Игроки на роли Абдукторов не были найдены. Повторная попытка через 30 секунд.")
Давайте не будем переводить сообщения админам

2021-05-28 18:55 UTC, semoro commented on code/modules/events/alien_infestation.dm
> +		log_and_message_admins("Внимание: не удалось создать существо для события 'Нашествие Чужих'")
Давайте не будем переводить сообщения админам

2021-05-28 18:55 UTC, semoro commented on code/modules/events/apc_overload.dm
> +	GLOB.event_announcement.Announce("Зафиксирована перегрузка энергосети станции [station_name ()]. Инженерному отделу надлежит проверить все терминалы ЛКП под напольным покрытием.", "КРИТИЧЕСКИЙ СБОЙ
лишний пробел между station_name и скобками `[station_name ()]`

2021-05-28 18:55 UTC, semoro commented on code/modules/events/apc_overload.dm
> +		GLOB.event_announcement.Announce("Зафиксирована перегрузка энергосети станции [station_name ()]. Инженерному отделу надлежит проверить все терминалы ЛКП под напольным покрытием.", "КРИТИЧЕСКИЙ СБОЙ
лишний пробел между station_name и скобками `[station_name ()]`

2021-05-28 18:55 UTC, semoro commented on code/modules/events/apc_short.dm
> +	GLOB.event_announcement.Announce("Зафиксирована перегрузка энергосети станции [station_name ()]. Инженерному отделу надлежит проверить все замкнувшие ЛКП.", "СБОЙ СИСТЕМЫ ПИТАНИЯ", new_sound = 'soun
лишний пробел между station_name и скобками `[station_name ()]`

2021-05-28 18:55 UTC, semoro commented on code/modules/events/apc_short.dm
> +		GLOB.event_announcement.Announce("Зафиксирована перегрузка энергосети станции [station_name ()]. Инженерному отделу надлежит проверить все замкнувшие ЛКП.", "СБОЙ СИСТЕМЫ ПИТАНИЯ", new_sound = 'sou
лишний пробел между station_name и скобками `[station_name ()]`

2021-05-28 18:55 UTC, semoro commented on code/modules/events/brand_intelligence.dm
> +	GLOB.event_announcement.Announce("На борту станции [station_name ()] зафиксировано распространение цифрового торгового вируса, пожалуйста, будьте наготове. Вирус, предположительно, берет начало от \
лишний пробел между station_name и скобками `[station_name ()]`

2021-05-28 18:55 UTC, semoro commented on code/modules/events/rogue_drones.dm
> +		msg = "Группа боевых дронов, оперируемых с борта ИКН ''Икар'', не вернулась с зачистки сектора. В случае контакта с дронами проявляйте осторожность."
Кавычки или одиночные `'` или `\"`

2021-05-28 18:55 UTC, semoro commented on code/modules/events/rogue_drones.dm
> +		msg = "Потеряна связь с группой боевых дронов, оперируемых с борта ИКН ''Икар''. В случае контакта с дронами проявляйте осторожность."
Кавычки или одиночные `'` или `\"`

2021-05-28 18:55 UTC, semoro commented on code/modules/events/rogue_drones.dm
> +		msg = "Неопознанные хакеры взломали систему контроля боевых дронов, оперируемых с борта ИКН ''Икар''. В случае контакта с дронами проявляйте осторожность."
Кавычки или одиночные `'` или `\"`

2021-05-28 18:55 UTC, semoro commented on code/modules/events/rogue_drones.dm
> +		GLOB.event_announcement.Announce("Система контроля боевых дронов сообщает, что все единицы успешно вернулись на борт ''Икара''.", "ВНИМАНИЕ: СБОЙНЫЕ ДРОНЫ")
Кавычки или одиночные `'` или `\"`

2021-05-28 18:55 UTC, semoro commented on code/modules/events/spider_terror.dm
> +		log_and_message_admins("Внимание: Не удалось создать существо для события ''Пауки Ужаса''")
Кавычки или одиночные `'` или `\"`

2021-05-28 18:55 UTC, semoro commented on code/modules/events/traders.dm
> +		GLOB.event_announcement.Announce("Торговому шаттлу со станции Юпитер было отказано в разрешении на стыковку из-за повышенной угрозы безопасности на борту [station_name()].", "Запрос на стыковку шат
Со станции на орбите Юпитера наверное

2021-05-28 18:55 UTC, semoro commented on code/modules/events/traders.dm
> +			GLOB.event_announcement.Announce("Торговый шаттл со станции Юпитер получил разрешение на стыковку в порту прибытия 4 [station_name()].", "Запрос на стыковку шаттла торговцев принят")
Со станции на орбите Юпитера наверное

2021-05-28 18:55 UTC, semoro commented on code/modules/events/vent_clog.dm
> +	GLOB.event_announcement.Announce("Зафиксирован скачок обратного давления в системе вытяжных труб. Возможен выплеск содержимого.", "ВНИМАНИЕ: ГАЗЫ")
Выброс содержимого

2021-05-28 18:55 UTC, semoro commented on code/modules/security_levels/security_levels.dm
> +				GLOB.security_announcement_up.Announce("Центральным командованием был установлен код ЭПСИЛОН. Считайте, что все контракты расторгнуты.","ВНИМАНИЕ! КОД ЭПСИЛОН", new_sound = sound('sound/effects/p
`Центральным командованием был установлен код ЭПСИЛОН. Все контракты расторгнуты.`

2021-05-28 18:55 UTC, semoro commented on code/modules/security_levels/security_levels.dm
> +				GLOB.security_announcement_up.Announce(" Механизм самоуничтожения станции задействован. Все члены экипажа обязан подчиняться всем указаниям, данными Главами отделов. Любые нарушения этих приказов
Пробел лишний в начале

2021-05-28 18:55 UTC, semoro commented on code/modules/events/blob.dm
> +		log_and_message_admins("ВНИМАНИЕ: Не удалось создать существо для проведения события 'Блоб'")
Админские сообщения переводить не надо

2021-05-28 18:55 UTC, semoro commented on code/modules/events/meaty_ops.dm
> +	var/meteor_declaration = "Метеориты заявили о своем намерении полностью уничтожить [station_name()] своими собственными телами. Осмелится ли экипаж остановить их?"
МБ `МетеоритыКо`

2021-05-28 22:16 UTC, semoro submitted a review, later dismissed

2021-05-28 22:16 UTC, semoro commented on code/modules/events/infestation.dm
> +			locstring = "убежище"
Хранилище

2021-05-28 22:16 UTC, semoro commented on code/modules/events/traders.dm
> +		GLOB.event_announcement.Announce("Торговому шаттлу с орбиты Юпитера было отказано в разрешении на стыковку из-за повышенной угрозы безопасности на борту [station_name()].", "Запрос на стыковку шатт
со станции Юпитер-6

2021-05-28 22:16 UTC, semoro commented on code/modules/events/traders.dm
> +			GLOB.event_announcement.Announce("Торговый шаттл с орбиты Юпитера получил разрешение на стыковку в порту прибытия 4 [station_name()].", "Запрос на стыковку шаттла торговцев принят")
со станции Юпитер-6

2021-05-28 23:05 UTC, PapaLeroy commented on code/modules/events/alien_infestation.dm
>  		log_and_message_admins("Warning: Could not spawn any mobs for event Alien Infestation")
Внимание: Невозможно создать существо для событья Нашествие Чужих.

2021-05-28 23:07 UTC, PapaLeroy commented on code/modules/events/alien_infestation.dm
> +		var/list/candidates = SSghost_spawns.poll_candidates("Вы хотите сыграть за Чужого?", ROLE_ALIEN, TRUE, source = /mob/living/carbon/alien/larva)
Вы хотите занять роль Чужого?
_Типа, везде так же прописано, чоб не тут тоже?_

2021-05-28 23:09 UTC, PapaLeroy commented on code/modules/events/carp_migration.dm
> +		announcement = "Неизвестные биологические объекты были обнаружены вблизи станции [station_name()], будьте наготове."
Вместо "обнаружено" стилистически корректно все-таки будет "зафиксировано"

2021-05-28 23:12 UTC, PapaLeroy commented on code/modules/events/money_hacker.dm
> +без вмешательства эта атака будет успешной примерно через 10 минут. Требуемое вмешательство: временно приостановтье любую активность затронутой учетной записи до тех пор, пока атака не прекратится. \
Требуется вмешательство - временно заморозьте учетную запись...

2021-05-28 23:14 UTC, PapaLeroy commented on code/modules/events/spider_terror.dm
>  		message_admins("Warning: not enough players volunteered to be terrors. Could only spawn [length(candidates)] out of [spawncount]!")
Внимание: недостаточно игроков заняли роль пауков Ужаса - всего [length(candidates)] из [spawncount]!

_Я хз, просто так это вставлю, потому что не знаю, воспринимают ли админские логи кириллицу._

2021-05-29 13:15 UTC, MorgoWizard commented on code/modules/events/spider_terror.dm
>  		message_admins("Warning: not enough players volunteered to be terrors. Could only spawn [length(candidates)] out of [spawncount]!")
решили не переводить сообщения для администрации

2021-05-29 14:38 UTC, Zigamus commented on code/modules/events/abductor.dm
> +		message_admins("Игроки на роли Абдукторов не были найдены. Повторная попытка через 30 секунд.")
А почему?

2021-06-02 18:16 UTC, merged