Add: Morphs Anonce
ss220-space/Paradise pull request #1201
Opened 2022-08-14 15:12 UTC by Honker9999999

## What Does This PR Do
При шести морфах делает анонс "Внимание! Зафиксировано критическое биожизни морфического типа на [station_name()]. Необходимо уничтожить их для восстановления безопасной среды."
Добавлены соотвествующий прок и две переменных (сделан ли анонс и кол-во живых морфов, хотя и второе сделано немного тухедски)

## Why It's Good For The Game
Предложка
Ладно

## Changelog
:cl:
add: Анонс при шести морфах
/:cl:

2022-08-14 16:06 UTC, larentoun reviewed
А ты вообще проверил, что анонс будет?

2022-08-14 16:39 UTC, Robustin4 commented
может переменные глобальными сделать?

2022-08-14 16:46 UTC, Honker9999999 commented
> может переменные глобальными сделать?

Хз нужно ли, ибо они только в этом файле упоминаются.

2022-08-14 16:48 UTC, Honker9999999 commented
> А ты вообще проверил, что анонс будет?

Я тестил все разы как менял этот код кроме последнего, ибо там изменение было мелким, но эыые и оно все сломало. Да, действительно теперь не работает, щас починю.

2022-08-14 19:09 UTC, Honker9999999 commented
Жестко нахотфиксил целый ПР хотфиксов

2022-08-14 21:20 UTC, larentoun requested changes

2022-08-14 21:20 UTC, larentoun commented on code/game/gamemodes/miniantags/morph/morph.dm
>  var/anonced = FALSE
announced

2022-08-14 21:20 UTC, larentoun commented
В остальном, вроде нормально. Немного грамматики поменять

2022-08-14 21:21 UTC, larentoun requested changes

2022-08-14 21:21 UTC, larentoun commented on code/game/gamemodes/miniantags/morph/morph.dm
> +		GLOB.command_announcement.Announce("Внимание! Зафиксировано критическое биожизни морфического типа на [station_name()]. Необходимо уничтожить их для восстановления безопасной среды.", "Central Comm
"Внимание! Зафиксировано критическое количество биожизни морфического типа на [station_name()]. Необходимо уничтожить их для восстановления безопасной среды."

2022-08-16 13:24 UTC, larentoun approved these changes

2022-08-16 13:32 UTC, Bizzonium commented on code/game/gamemodes/miniantags/morph/morph.dm
> +		GLOB.command_announcement.Announce("Внимание! Зафиксированы множественные био-угрозы 6-М уровня на [station_name()]. Необходимо уничтожение для продолжения безопасной работы.", "Central Command Bio
`био-угрозы 6-М уровня` ?

2022-08-16 13:39 UTC, larentoun commented on code/game/gamemodes/miniantags/morph/morph.dm
> +		GLOB.command_announcement.Announce("Внимание! Зафиксированы множественные био-угрозы 6-М уровня на [station_name()]. Необходимо уничтожение для продолжения безопасной работы.", "Central Command Bio
> `био-угрозы 6-М уровня` ?

Видимо, где-то в чатах сказали, что это угроза 6-М. И такой вроде не было у нас ранее

2022-08-18 06:44 UTC, Honker9999999 commented on code/game/gamemodes/miniantags/morph/morph.dm
> +		GLOB.command_announcement.Announce("Внимание! Зафиксированы множественные био-угрозы 6-М уровня на [station_name()]. Необходимо уничтожение для продолжения безопасной работы.", "Central Command Bio
Самое логичное что я смог придумать, т.к. он страшнее вируса, но не такой страшный как блоб или терроры. А так ингейм не упоминается какой именно у морфа уровень биогурозы и есть ли он у него.

2022-08-18 07:57 UTC, larentoun commented on code/game/gamemodes/miniantags/morph/morph.dm
> +		GLOB.command_announcement.Announce("Внимание! Зафиксированы множественные био-угрозы 6-М уровня на [station_name()]. Необходимо уничтожение для продолжения безопасной работы.", "Central Command Bio
> Самое логичное что я смог придумать, т.к. он страшнее вируса, но не такой страшный как блоб или терроры. А так ингейм не упоминается какой именно у морфа уровень биогурозы и есть ли он у него.

ЭЭЭЭ, НЕТ! Спрашивай у викиделов/лороделов/админов, отсебятины, особенно такой важной, нельзя

2022-08-19 07:34 UTC, Honker9999999 commented on code/game/gamemodes/miniantags/morph/morph.dm
> +		GLOB.command_announcement.Announce("Внимание! Зафиксированы множественные био-угрозы 6-М уровня на [station_name()]. Необходимо уничтожение для продолжения безопасной работы.", "Central Command Bio
Я буквально и есть викидел и лородел.

2022-08-19 08:03 UTC, larentoun commented on code/game/gamemodes/miniantags/morph/morph.dm
> +		GLOB.command_announcement.Announce("Внимание! Зафиксированы множественные био-угрозы 6-М уровня на [station_name()]. Необходимо уничтожение для продолжения безопасной работы.", "Central Command Bio
Тогда ладно

2022-08-19 11:12 UTC, merged

2022-08-19 14:51 UTC, LiquidPotroh commented
С русским языком, конечно, тут проблемки. Неужели никому не режет слух "критическое биожизни"? Критическое что? Может критическое количество "биожизни"? Биожизнь это вообще не слово, а какой то бред. Необходимо уничтожить "их". Чтобы использовать "их" до этого должны быть какие-нибудь "они", а у автора только "критическое биожизни".

2022-08-19 15:28 UTC, Honker9999999 commented
> С русским языком, конечно, тут проблемки. Неужели никому не режет слух "критическое биожизни"? Критическое что? Может критическое количество "биожизни"? Биожизнь это вообще не слово, а какой то бред. Необходимо уничтожить "их". Чтобы использовать "их" до этого должны быть какие-нибудь "они", а у автора только "критическое биожизни".

Поэтому собсна исправили. Я забыл это изначально исправить, так что пришлось делать хотфикс.