Fix: cryoxadone condition (turf temp -> mob temp)
ss220-space/Paradise pull request #1206
Opened 2022-08-16 00:53 UTC by fake123acc

## What Does This PR Do

Починил условие активации криоксадона, теперь определяющей является температура моба, а не турфа под ним.
+ лечение криоксадоном с криостиланом/фрост оилом
- лечение криоксадоном в космосе/криокапсуле/холодильнике, пока носишь риг

## Why It's Good For The Game
Логика, которой нам отчаянно не хватает

## Changelog
:cl: nopeucant
fix: fixed cryoxadone activation conditions
/:cl:

2022-08-16 01:41 UTC, PhantornRU approved these changes
Фикс бага, нужен мерж. Педали с этим согласны.

2022-08-16 07:54 UTC, BeebBeebBoob requested changes

2022-08-16 07:54 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> -		external_temp = C.temperature_archived
Боюсь вот это надо было все такие как-то оставить. 
Не уверен кто крио будет теперь работать в капсуле

2022-08-16 07:54 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> -		external_temp = T.temperature
Вот здесь надо было бы сделать проверку не на турф, а на моба

2022-08-16 18:10 UTC, fake123acc commented on code/modules/reagents/chemistry/reagents/medicine.dm
> -		external_temp = C.temperature_archived
> Боюсь вот это надо было все такие как-то оставить. Не уверен кто крио будет теперь работать в капсуле

Могу уверить, что зря боишься.
1) Крио работает
2) Если сделать по-твоему, человек в скафандре будет лечиться в крио, не засыпая и не охлаждаясь.

2022-08-16 18:11 UTC, fake123acc commented on code/modules/reagents/chemistry/reagents/medicine.dm
> -		external_temp = T.temperature
Ответил выше, нет, не надо было.

2022-08-16 23:59 UTC, fake123acc commented
@BeebBeebBoob если моих слов недостаточно - попробуй запустить у себя на машине, я протестировал все кейсы, которые мне пришли в голову (около 500ч меда, имею наглость заявлять, что эти тесты должны были покрыть все возможные ситуации), и во всех поведение совпадало с ожидаемым.

2022-08-17 05:52 UTC, BeebBeebBoob commented
Если так работает то все ок тогда.

2022-08-17 08:22 UTC, BeebBeebBoob commented
Кстати это будет нёрфом как я предполагаю тогда, для плазмачей. Ониж в костюме, но хз.

2022-08-17 10:23 UTC, Bizzonium commented
> Кстати это будет нёрфом как я предполагаю тогда, для плазмачей. Ониж в костюме, но хз.

Кстати, да, этот момент надо продумать. Либо это станет новым дебаффом к плазмаменам

2022-08-17 10:28 UTC, BeebBeebBoob commented
Сейчас медики будут брать температурные пушки и ставить там до минимальных значениях, заливать в плазмамена крио и стрелять потом в них чтоб сбросили температуру. Или будут видимо звать атмосферников которые построят камеру из холодной плазмы(видимо вот в кабинках для пациентов, в углу медбея).

2022-08-17 13:35 UTC, fake123acc commented
> > Кстати это будет нёрфом как я предполагаю тогда, для плазмачей. Ониж в костюме, но хз.
> 
> Кстати, да, этот момент надо продумать. Либо пусть станет новым дебаффом к плазмаменам

Ну, мы договорились, что риг с термоизоляцией не должен позволять лечиться в криокамере, игнорируя ту часть, где она "крио". 
Отдельно про плазмаменов это не проговаривали.
Однако я бы сказал, что это должно быть закономерным следствием.

Если не так, дайте сигнал — если нужно дополнительное подтверждение, я повторю опрос асостава. Если нужно поменять механ крио для плазмаменов — поменяю код.

2022-08-18 14:15 UTC, fake123acc commented
Бамп

2022-08-19 11:11 UTC, merged