Fix: bar sign disappearance when panel is open
ss220-space/Paradise pull request #1212
Opened 2022-08-16 20:19 UTC by valldemar2017

## What Does This PR Do

Починил исчезновение барной вывески при раскручивании  отверткой
## Why It's Good For The Game

## Images of changes

## Changelog
:cl:
fix: Починил исчезновение барной вывески при раскручивании  отверткой

/:cl:

2022-08-16 20:41 UTC, valldemar2017 commented
Буду очень рад резонным дополнениям, исправлениям и предложениям

2022-08-17 00:24 UTC, PhantornRU approved these changes
Убрал 	**pick_sign()**
Чтобы добавить 	**pick_sign()**

2022-08-17 00:41 UTC, valldemar2017 commented
Это vs code так посчитал манипуляцию со строками)

2022-08-17 01:17 UTC, Den109G commented
> Убрал **pick_sign()** Чтобы добавить **pick_sign()**

Гитхаб посчитал, что пустая строка на том же месте важней, чем перенос функции, из-за чего так выходит. Кодер момент.

2022-08-17 09:19 UTC, larentoun requested changes

2022-08-17 09:19 UTC, larentoun commented on code/game/objects/structures/barsign.dm
> +	if(istype(I, /obj/item/screwdriver))
А зачем тебе проверка на тип предмета, если screwdriver_act подразумевает, что тип объекта - уже screwdriver?

2022-08-17 09:56 UTC, valldemar2017 commented on code/game/objects/structures/barsign.dm
> +	if(istype(I, /obj/item/screwdriver))
Код в screwdriver_act это копипаста из attackby. В какой момент я убрал эту проверку. Но потом я неправильно зафиксировал коммит и мне пришлось разгребать лапшу из гитхаба. Похоже что я не сохранил-откатил изменения. Сейчас починю

2022-08-17 10:03 UTC, larentoun requested changes
Также, если компилится и нет больше фантомных разборов барных знаков, то последняя правка, надеюсь

2022-08-17 10:03 UTC, larentoun commented on code/game/objects/structures/barsign.dm
> +		panel_open = 1
Почему бы не использовать TRUE/FALSE? Что значит 1, что значит 0, значит ли, что есть 2?

2022-08-17 10:05 UTC, valldemar2017 commented on code/game/objects/structures/barsign.dm
> +		panel_open = 1
Так задумал автор данного кода. 1 и 0 в выражениях if переводятся в TRUE и FALSE соответственно. Можно поменять. Но это отразиться только на коде

2022-08-17 10:06 UTC, valldemar2017 commented on code/game/objects/structures/barsign.dm
> +		panel_open = 1
Кстати если даже там будет 2 то все равно это будет TRUE)

2022-08-17 10:07 UTC, valldemar2017 commented on code/game/objects/structures/barsign.dm
> +		panel_open = 1
Но в коде подобное значение задано быть не может. Только если кто-то будет шалить с VV(Читать как "У кого-то из адмемов будут чесаться руки")

2022-08-17 10:26 UTC, valldemar2017 commented on code/game/objects/structures/barsign.dm
> +		panel_open = 1
переименовать их? В принципе дело на пять минут

2022-08-17 10:27 UTC, larentoun commented on code/game/objects/structures/barsign.dm
> +		panel_open = 1
Очень желательно, да. И да, только для читабельности кода

2022-08-17 10:28 UTC, valldemar2017 commented on code/game/objects/structures/barsign.dm
> +		panel_open = 1
Окей

2022-08-17 10:45 UTC, valldemar2017 commented on code/game/objects/structures/barsign.dm
> +		panel_open = 1
Переделал, и не только panel_open

2022-08-17 10:45 UTC, valldemar2017 commented on code/game/objects/structures/barsign.dm
> +		panel_open = 1
о7

2022-08-17 10:51 UTC, larentoun approved these changes

2022-08-19 11:16 UTC, merged