Tweak: disable user controlled emotes when human sleeping
ss220-space/Paradise pull request #1233
Opened 2022-08-20 17:47 UTC by Dimach

## What Does This PR Do
Эмоуты из эмоутпанели теперь нельзя прожимать когда кукла спит (проверка написана аналогично той что уже есть для me)

## Why It's Good For The Game
Теперь нельзя больше кричать во сне, меньше проблем антагам которые усыпили жертву и пытаются её скрытно унести

## Changelog
Эмоуты через эмоутпанель теперь нельзя прожимать во сне

2022-08-20 18:55 UTC, larentoun commented
Проверка для просто ввода команды есть?
Можно ли все еще просто писать "/say *deathgasp"?

И я бы лучше рефакторнула сами эмоуты, подсмотрев их со скайрата

2022-08-20 19:56 UTC, Dimach commented
Если например запретить кричать во сне (в коде самого эмоута) то не управляемые пользователем эмоуты тоже перестанут работать (например тебе во сне ломают руку а ты молчишь как партизан) поэтому этот ПР реализует ровно то что обещает - запрещает прожимать эмоуты во сне потому что ты как бы во сне целенаправленно делать что-то не может, как это сделано сейчас например для me
Что до say *deathgasp я проверю, и если нужно тоже поправлю

2022-08-20 20:06 UTC, larentoun commented
> Если запретить эмоутить во сне (например кричать, в коде самого эмоута) то не управляемые пользователем эмоуты тоже перестанут работать (например тебе во сне ломают руку а ты молчишь как партизан) поэтому этот ПР реализует ровно то что обещает - запрещает прожимать эмоуты во сне потому что ты как бы во сне целенаправленно делать что-то не можешь, как это сделано сейчас для me

Потому я и советую посмотреть, как сделали на ТГ/скайрате. Там как раз-таки все вызываемые игроком эмоуты (чат, панель) имеют свой флаг

2022-08-20 20:16 UTC, Dimach commented
Так, я проверил, через say эмоутить во сне тоже нельзя, это раз.

Два - у нас проблема не с эмоутами вызываемыми игроком, а с эмоутпанелью которая в обход всех проверок вызывает эмоут

Три - можно конечно проставить флаги, но какой смысл? Я запрещаю не конкретные эмоуты а просто запрещают тригерить их в обход проверок на сон и тд., по сути возвращаю все так как оно должно было быть написано изначально

2022-08-20 20:44 UTC, larentoun commented
> Так, я проверил, через say эмоутить во сне тоже нельзя, это раз.
> 
> Два - у нас проблема не с эмоутами вызываемыми игроком, а с эмоутпанелью которая в обход всех проверок вызывает эмоут
> 
> Три - можно конечно проставить флаги, но какой смысл? Я запрещаю не конкретные эмоуты а просто запрещают тригерить их в обход проверок на сон и тд., по сути возвращаю все так как оно должно было быть написано изначально

Ну, раз есть защита вызываемых эмоутов, тогда топ

2022-08-21 14:23 UTC, larentoun requested changes

2022-08-21 14:23 UTC, larentoun commented on code/modules/mob/emote.dm
> +/mob/proc/user_triggered_emote(act, type, message, force)
Можно было прок дать хуману, так как эмоут панель как раз только там и есть

2022-08-21 18:50 UTC, Dimach commented on code/modules/mob/emote.dm
> +/mob/proc/user_triggered_emote(act, type, message, force)
Можно, но эмоутить у нас умеет не только хуман, может кто-то оформит эмоут панель для боргов? Или симплмобов?

2022-08-21 18:56 UTC, larentoun commented on code/modules/mob/emote.dm
> +/mob/proc/user_triggered_emote(act, type, message, force)
> Можно, но эмоутить у нас умеет не только хуман, может кто-то оформит эмоут панель для боргов? Или симплмобов?

Эмоут панель, повторюсь, есть только у хуманов. Ты решил сделать вот так вот прямо, а не как я советовала

2022-08-21 19:35 UTC, Dimach commented on code/modules/mob/emote.dm
> +/mob/proc/user_triggered_emote(act, type, message, force)
У тебя есть гарантии что эмоут панель БУДЕТ только у хуманов? Не смотря на то что боргам её тоже не хватает с их *yes *no *buzz и тд. Я вижу смысл сделать этот прок более абстрактным потому что это логично с точки зрения ООП и задела на будущее, а причин делать его чисто хуману не вижу

2022-08-21 19:38 UTC, larentoun commented on code/modules/mob/emote.dm
> +/mob/proc/user_triggered_emote(act, type, message, force)
> У тебя есть гарантии что эмоут панель БУДЕТ только у хуманов? 

![image](https://user-images.githubusercontent.com/31931237/185808018-c13ee24f-706c-440c-b3a5-8ecd5bd7694c.png)
Да.

> Я вижу смысл сделать этот прок более абстрактным потому что это логично с точки зрения ООП и задела на будущее, а причин делать его чисто хуману не вижу

Если хочешь сделать "логично", я повторюсь в третий раз. Сделай рефактор эмоутов. Я даже сказала, где искать - у скайрата.

2022-08-21 19:43 UTC, Dimach commented on code/modules/mob/emote.dm
> +/mob/proc/user_triggered_emote(act, type, message, force)
Если хочешь делать рефактор, делай рефактор, хоть в стиле ТГ хоть в стиле скайрата.

Этот ПР решает ОДНУ конкретную проблему - спам крика, предсмертного хрипа и всяких других эмоутов во сне. Больше он ничего не решает.

И я не понимаю откуда взялась железная уверенность что боргам нельзя закодить эмоутпанель потому что текущие вербы указаны для хумана

2022-08-21 19:52 UTC, larentoun commented on code/modules/mob/emote.dm
> +/mob/proc/user_triggered_emote(act, type, message, force)
> Если хочешь делать рефактор, делай рефактор, хоть в стиле ТГ хоть в стиле скайрата.
> 
> Этот ПР решает ОДНУ конкретную проблему - спам крика, предсмертного хрипа и всяких других эмоутов во сне. Больше он ничего не решает.
> 
> И я не понимаю откуда взялась железная уверенность что боргам нельзя закодить эмоутпанель потому что текущие вербы указаны для хумана

А я и не говорила, что нельзя. Я сама это сделала для скайрата с особенностями эмоутов для каждого подтипа моба. Кто будет это делать сюда?

2022-08-21 20:09 UTC, Dimach commented on code/modules/mob/emote.dm
> +/mob/proc/user_triggered_emote(act, type, message, force)
Меня этот вопрос не волнует. Я сделал этот ПР по админской голосовалке для решения конкретного бага. По существу есть что добавить? Код забагован? Не соответствует стайлгайдам? Не покрывает все случаи? Расписывай, я поправлю. А то что он не соответствует эмоутпанели скайрата меня не интересует, у нас не скайрат

2022-08-22 10:39 UTC, Dimach commented
Голосовалка прошла
https://discord.com/channels/617003227182792704/755125334097133628/1011220879398670356

2022-08-25 02:32 UTC, merged