Feat: Амбиции
ss220-space/Paradise pull request #1236
Opened 2022-08-21 12:52 UTC by PhantornRU

## What Does This PR Do
Кучу времени я разрабатывал время от времени систему амбиций и наконец-то доделал.
Что такое амбиции?
Амбиции - РП-задачи не нацеленные на антагонистские действия, не нарушающие правила и разнообразивающие РП-игру игроков, которые решили себе их выдать.

Данные амбиции подразделяются на несколько видов: Общие, Отделов, Глав-Отделов, Глав.
**Общие** - могут выдаваться всем подряд
**Отделов** - выдаются только членам отделам и заданным профессиям, у них также имеются свои внутренние работы
**Глав-отделы** - могут получить работу как глав, так и случайного члена отдела.
**Глав** - амбиция глав.

В конце раунда данные амбиции не выводятся в общем чате, но выводятся в окне итогов смены. Выводятся только амбиции, которые игрок посчитал выполненными.

Игрок самостоятельно может переключать выполнение амбиций [красный/зеленый], а также удалять и добавлять амбиции.
Ограничение амбиций - 6 штук на одну память.

Все амбиции записаны отдельно от должностных задач, а значит не будут сливаться в одну кашу в памяти (например у РНД и Робо).

## Why It's Good For The Game
Игроки смогут находить себе задачи, когда им скучно.

## Images of changes
### **СБ и Капитан:**
![image](https://user-images.githubusercontent.com/41479614/185791754-b7031129-e52a-4a3d-b911-56aed851f457.png)

### **Конец раунда:**
![image](https://user-images.githubusercontent.com/41479614/185791758-91c56dce-11fd-470a-87ab-7d75b47c8595.png)

### **Не смешивается с задачами по работе:**
![image](https://user-images.githubusercontent.com/41479614/185791764-724402b4-03c7-4a1d-8a1e-87227b5edf89.png)

2022-08-23 14:06 UTC, dj-34 reviewed
Мельком пробежался

2022-08-23 14:06 UTC, dj-34 commented on code/datums/mind.dm
> +			to_chat(usr, "<span class='warning'>Пожалуй [pluralize_ru(usr.gender,"Моя","Наша")] амбиция еще не выполнена. Но у [pluralize_ru(usr.gender,"меня","нас")] еще будут возможности!</span>")
```suggestion
			to_chat(usr, "<span class='warning'>Пожалуй [pluralize_ru(usr.gender,"моя","наша")] амбиция еще не выполнена. Но у [pluralize_ru(usr.gender,"меня","нас")] еще будут возможности!</span>")
```

2022-08-23 14:06 UTC, dj-34 commented on strings/ambition_objectives_engineering.json
> +		"",
Правильно ли будет оставлять кучу пустых строчек?

2022-08-23 14:06 UTC, dj-34 commented on strings/ambition_objectives_engineering.json
> +		"Меня укачивает в поде... Буду вручную работать в космосе!",
каво?

2022-08-23 14:06 UTC, dj-34 commented on strings/ambition_objectives_generic.json
> +		"Я хочу чтобы [random_pet] и [random_pet] стали лучшими питомцами друг для друга!",
Животные не могут быть питомцами друг для друга.

```suggestion
		"Я хочу чтобы [random_pet] и [random_pet] стали лучшими друзьями!",
```

2022-08-23 14:06 UTC, dj-34 commented on strings/ambition_objectives_generic.json
> +		"А ведь я мог стать космонавтов... Правильным космонавтом...",
```suggestion
		"А ведь я мог стать космонавтом... Правильным космонавтом...",
```

2022-08-23 14:06 UTC, dj-34 commented on strings/ambition_objectives_security.json
> +		"Меня укачивает в поде... Буду вручную работать в космосе!",
каво x2

2022-08-23 14:46 UTC, dj-34 commented on strings/ambition_objectives_engineering.json
> +		"Меня укачивает в поде... Буду вручную работать в космосе!",
> каво?

Странно занимать должность механика/под пилота, при этом укачиваясь в поде - нет логики

2022-08-24 00:47 UTC, PhantornRU commented on strings/ambition_objectives_engineering.json
> +		"",
Да. Они так снижают шансы выпадения амбиции профы, у которой меньше всего амбиций. В результате чего меньше повторов возникает.

2022-08-24 00:47 UTC, PhantornRU commented on strings/ambition_objectives_engineering.json
> +		"Меня укачивает в поде... Буду вручную работать в космосе!",
Странно не странно, но собирать поды никто по прежнему не мешает.

2022-08-24 00:48 UTC, PhantornRU commented on strings/ambition_objectives_engineering.json
> +		"Меня укачивает в поде... Буду вручную работать в космосе!",
Да и не заставляет эту амбицию выполнять. Это подсказка, а не обязательное действие.

2022-08-26 14:57 UTC, PhantornRU commented
ПР прошел А-воут. Ревью со стороны педалей произведено. Правки внесены. Одобрено. @Bizzonium 
https://discord.com/channels/617003227182792704/755125334097133628/1012641966091153448

2022-08-26 17:57 UTC, dj-34 commented on strings/ambition_objectives_law.json
> +		"Экипаж мало заботится СРП. Значит мне нужно им объяснить, почему ему следует следовать!",
```suggestion
		"Экипаж мало заботит СРП. Это недопустимо.",
		"Экипаж мало заботит СРП. Значит мне нужно им объяснить, почему ему следует следовать!",
```

2022-08-26 19:17 UTC, EternalDrifter commented
![Screen Shot 08-27-22 at 03 12 AM](https://user-images.githubusercontent.com/97734691/186975971-0a67eedf-d794-40d8-a88c-8159c1c02008.PNG)

**Есть:**
_Вы противитесь технологий, избегайте их и работайте старыми методами и ни в коем случаи не пользуйтесь ручным сканнером!_ 
**Надо:**
_Вы противитесь технологи**ям**. **И**збегайте их, работайте старыми методами и ни в коем случаи не пользуйтесь ручным ска**н**ером!_

2022-08-26 19:26 UTC, EternalDrifter commented
![Screen Shot 08-27-22 at 02 56 AM](https://user-images.githubusercontent.com/97734691/186976963-7a9e15e3-efbb-458e-af72-bc40daa7ef43.PNG)
Повтор так и должен быть, чтобы чаще выпадал? Хотя у повара такого нет, с аналогичной амбицией

2022-08-27 00:46 UTC, PhantornRU commented
@EternalDrifter Чтобы отвечать, нужно на интересующей тебя строчке нажать +, а потом Rewiew Changed
![image](https://user-images.githubusercontent.com/41479614/187007582-eeabd3d4-c50b-49c1-8eff-abdb7933d8ce.png)


> ![Screen Shot 08-27-22 at 03 12 AM](https://user-images.githubusercontent.com/97734691/186975971-0a67eedf-d794-40d8-a88c-8159c1c02008.PNG)
> 
> **Есть:** _Вы противитесь технологий, избегайте их и работайте старыми методами и ни в коем случаи не пользуйтесь ручным сканнером!_ **Надо:** _Вы противитесь технологи**ям**. **И**збегайте их, работайте старыми методами и ни в коем случаи не пользуйтесь ручным ска**н**ером!_

2022-08-27 00:47 UTC, PhantornRU commented on strings/ambition_objectives_support.json
> +		"Сегодня стоит сделать самый сложный напиток и обязательно угостить им каждого!",
```suggestion
```

2022-08-27 00:48 UTC, PhantornRU commented on strings/ambition_objectives_security.json
> +		"Вы противитесь технологий, избегайте их и работайте старыми методами и ни в коем случаи не пользуйтесь ручным сканнером!",
```suggestion
		"Вы противник технологий. Избегайте их, и работайте старыми методами, и ни в коем случаи не пользуйтесь ручным сканером!",
```

2022-08-27 00:48 UTC, PhantornRU reviewed
правки выше

2022-08-27 10:20 UTC, PhantornRU commented
Ждём мержа. Pepechill

2022-08-27 10:20 UTC, PhantornRU commented
Ну-ка кое-что проверим
:PepeChil:

2022-08-27 16:21 UTC, dj-34 approved these changes
вроде нормалды lgtm

2022-08-28 00:11 UTC, PhantornRU commented
Шел третий день без еды, воды и merg'a, мы надеялись на лучшее, но приписы оказывались на исходе.
Когда-нибудь нас найдет спасательная группа @Bizzonium

2022-08-29 13:01 UTC, PhantornRU commented
Шел четвертый день без еды, воды и MERG'а. Сегодня мы потеряли нашего клоуна. Он 28 раз упал на нож и сварился в котле. Похоже этот день мы еще сможем прожить. Всех пробило на смешинку.

2022-08-30 05:14 UTC, PhantornRU commented
Шел пятый день без мерджа. Сознание тускнело. У мима началась рвота и тошнота. Мы и так замечали что в последнее время он крайне молчалив, но похоже его это совсем вывело из себя. Он накрыл себя невидимой коробкой, схватился за коленки и зарыдал.
Сегодня мы доедали ноги клоуна. На вкус они как апельсиновый сок и мелки.

2022-08-31 14:45 UTC, PhantornRU commented
Шел 6й день мерджа. Говорят другие ПРы уже спасли и замержили. Но это пока слухи. Мы не знаем когда это закончится. Но мы выстоим. Мы сильны.

2022-08-31 15:08 UTC, Den109G commented
Поставь капкан в тех файлах этого ПРа. Вдруг какая зверина мешает.

2022-09-06 05:25 UTC, PhantornRU commented
16 день без амбиций.
Амбиции:
Амбиция #1: Приготовлю Этанол и сам же его выпью.

![image](https://user-images.githubusercontent.com/41479614/188553419-33ca469a-ad74-4b50-97de-a32a7532d28b.png)

2022-09-06 13:56 UTC, PhantornRU commented
Интересный факт. Всего готово ~1500 амбиций.

2022-09-11 09:57 UTC, PhantornRU commented
Шла 3-я неделя без амбиций. Наши амбиции тухли на глазах.

За это время я даже пофиксить их успел при нахождении новых багов. 
А еще убрал все "Вы", теперь есть только "Я"

2022-09-11 11:11 UTC, semoro requested changes

2022-09-11 11:11 UTC, semoro commented on strings/ambition_objectives_science.json
> +		"",
Пустые строки здесь явно не нужны

2022-09-11 11:11 UTC, semoro commented on code/modules/economy/Job_Departments.dm
> +GLOBAL_LIST_INIT(station_departments, list("Command", "Medical", "Engineering", "Science", "Security", "Cargo", "Support", "Civilian", "Silicon", "Law", "Representative", "Antag", "Central"))
А для чего это изменение?

2022-09-11 11:11 UTC, semoro commented on code/game/jobs/job_objective.dm
> +			text += "<br>&nbsp;<font color='green'><B>[employee.name] выполнил[genderize_ru(usr.gender,"","а","о","и")] свою чёртову работу!</B></font>"
Не является частью сабжа, давай не будем менять

2022-09-11 11:11 UTC, semoro commented on strings/ambition_objectives_engineering.json
> +		"Я могу и сам накормить и снабдить станцию дарами космоса.",		"",
Пустая строка в конец попала

2022-09-11 11:11 UTC, semoro commented on code/controllers/subsystem/jobs.dm
> +			for(var/objectiveType in job.ambitions_objectives)
А где в этот список вообще что-либо добавляется?

2022-09-11 11:11 UTC, semoro commented on code/datums/mind.dm
> +			output += "<font color=[objective.completed ? "green" : "red"]>[objective.completed ? "Передумать" : "Выполнить"]</font>"
Зеленая кнопка Передумать и красная Выполнить? на самом деле не очень очевидно
Если не сложно, приложи скриншот того как это выглядит

2022-09-11 11:11 UTC, semoro commented on code/datums/mind.dm
> +	var/ambition_func = FALSE
Отдели пожалуйста это всё в отдельную функцию

2022-09-11 11:11 UTC, semoro commented on code/datums/mind.dm
> +			var/counter = 0
Что-то я не понял логики этого цикла
Ты хочешь чтобы амбиции были уникальные?

2022-09-11 11:11 UTC, semoro commented on code/datums/mind.dm
> +			var/datum/ambition_objective/objective = new /datum/ambition_objective(usr.mind)
Замечу, что это приводит к добавлению амбиции сразу-же

2022-09-11 11:11 UTC, semoro commented on code/game/jobs/job/job.dm
> +	var/ambitions_objectives=list() // Список амбиций
Не вижу мест где в этот список хоть что-то добавляется

2022-09-11 11:11 UTC, semoro commented on code/game/ambitions/ambition_objective.dm
> +		job = "Общий"
Давай в качестве ключей не будем использовать русский текст во избежание проблем с кодировками
Переименуй в Common и соответственно Common Special

2022-09-11 11:11 UTC, semoro commented on code/game/ambitions/ambition_objective.dm
> +#define FINDAMBITIONTASK_DEFAULT_NEW 1 // Make a new task of this type if one can't be found.
А где должна использоваться вот эта функция? Если она не нужна, то надо убрать думаю

2022-09-11 11:11 UTC, semoro commented on code/game/ambitions/ambition_objective.dm
> +				if (!result)
If (!result) return result OwO??

2022-09-11 11:11 UTC, semoro commented on code/game/ambitions/ambition_objective.dm
> +			if("Magistrate" && (prob(chance_other_departament_ambition))) //шанс что магистрат возьмёт общую амбицию глав.
Ты хотел проверить что роль стоит магистрат?
Тогда оставь только верхнюю проверку

2022-09-11 11:11 UTC, semoro commented on code/game/ambitions/ambition_objective.dm
> +			if("Nanotrasen Representative" && (prob(chance_other_departament_ambition))) //шанс что НТР возьмёт общую амбицию закона.
Та же история что и с магистратом

2022-09-11 11:11 UTC, semoro commented on code/game/ambitions/ambition_objective.dm
> +	switch(owner.assigned_role)
Используй либо job везде, либо owner.assigned_role

2022-09-11 11:11 UTC, semoro commented on code/modules/economy/Job_Departments.dm
> +/datum/job/scientist/department = "Science"
Для того чтобы работало остальное - изменение этого файла не нужно, откати пожалуйста

2022-09-11 11:11 UTC, semoro commented on code/game/ambitions/ambition_objective.dm
> +	while(picked in choose_list)
Сделай этот список просто аргументом, а не храни в датуме

2022-09-11 11:11 UTC, semoro commented on strings/ambition_objectives_special.json
> +{
Этот файл нигде не используется, убери его пожалуйста

2022-09-11 11:11 UTC, semoro commented on code/game/ambitions/ambition_objective.dm
> +		if (!result)
Тут тоже что-то не так с result, кажется тут нужен безусловный return просто

2022-09-11 11:11 UTC, semoro commented on code/game/ambitions/ambition_objective.dm
> +			item = replacetextEx_char(item, "[code]\]", random_choose(code))
А ты не смотрел, есть ли какое-то готовое решение для этой задачи мб?

2022-09-11 11:35 UTC, PhantornRU commented on code/datums/mind.dm
> +			output += "<font color=[objective.completed ? "green" : "red"]>[objective.completed ? "Передумать" : "Выполнить"]</font>"
![image](https://user-images.githubusercontent.com/41479614/189525286-2bad8ac8-4d7b-453d-baa3-5248f2403922.png)
В самом посте показывал как выглядит. Пока один из приемлимых вариантов что пришли в голову и не слишком заморочны в реализации, без лишних слов и предлогов.

2022-09-11 11:41 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +	switch(owner.assigned_role)
job - включает в себя амбиции должности и "общую амбицию".
Овнером - указываем что всегда нужно выбирать только амбиции определенной должности
Job'ом - указываем, что можем также выбрать общую амбицию отдела

2022-09-11 11:42 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +			if("Magistrate" && (prob(chance_other_departament_ambition))) //шанс что магистрат возьмёт общую амбицию глав.
Это идут одновременно проверки АВД и Магистрата, у которых потом выбираются дополнительные амбиции, для Магистрата идет дополнительные амбиции командование, а амбиции командования нельзя дать АВД.

2022-09-11 11:44 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +				if (!result)
В голове была мысля о выборе пустой строки, но потом я внёс доп. проверки (буквально на днях), а такие формулировки остались. Выпилю их все.

2022-09-11 11:44 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +			if("Nanotrasen Representative" && (prob(chance_other_departament_ambition))) //шанс что НТР возьмёт общую амбицию закона.
Тож самое, мне не нужно чтобы блющилд взял амбиции LAW Отдела.

2022-09-11 11:44 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +		if (!result)
выпилю

2022-09-11 11:45 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +			item = replacetextEx_char(item, "[code]\]", random_choose(code))
есть что-то наподобии пенкода. До этого я код на его манер и делал, но по итогу это оказалось крайне грязно и не удобно, поэтому я сделал такую обработку. Примеров для этого нету, а я немало искал, это самописное.

2022-09-11 11:47 UTC, PhantornRU commented on code/game/jobs/job/job.dm
> +	var/ambitions_objectives=list() // Список амбиций
Убрал его

2022-09-11 11:47 UTC, PhantornRU commented on code/game/jobs/job_objective.dm
> +			text += "<br>&nbsp;<font color='green'><B>[employee.name] выполнил[genderize_ru(usr.gender,"","а","о","и")] свою чёртову работу!</B></font>"
Попутная корректировка какого-то древнего перевода под современные стандарты.

2022-09-11 11:49 UTC, PhantornRU commented on code/modules/economy/Job_Departments.dm
> +GLOBAL_LIST_INIT(station_departments, list("Command", "Medical", "Engineering", "Science", "Security", "Cargo", "Support", "Civilian", "Silicon", "Law", "Representative", "Antag", "Central"))
Изначально обработка должна была быть через эти списки, из-за чего я их дополнил. Но потом оказалось что я залез не туда. А эти списки устарели уже на десяток лет. Для актуальности и будущих обработок оставил их.

2022-09-11 11:49 UTC, PhantornRU commented on code/modules/economy/Job_Departments.dm
> +/datum/job/scientist/department = "Science"
Жаль, но ок.

2022-09-11 11:51 UTC, PhantornRU commented on strings/ambition_objectives_science.json
> +		"",
Они нужны для уравнивания шансов выпадения амбиций. Если выпадает пустая строка, то генератор идет на второй круг и может выбрать амбицию не только отдела, но и самой должности или общую.
Если убрать пустые строки, то постоянно будут падать повторы. Поэтому их либо нужно заполнить, либо оставить пустыми чтобы избежать повтором на одной и той же роли.

2022-09-11 11:53 UTC, PhantornRU commented on code/controllers/subsystem/jobs.dm
> +			for(var/objectiveType in job.ambitions_objectives)
Убрал его. Пропустил когда чистил и переносил.

2022-09-11 11:55 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +		job = "Общий"
Переименовано в Common

2022-09-11 11:57 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +				if (!result)
Заменил

2022-09-11 11:59 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +	while(picked in choose_list)
Не совсем понял как это должно реализоваться, ведь мне и нужно было их хранить в датуме чтобы проверять наличия повторов

2022-09-11 11:59 UTC, PhantornRU commented on code/game/jobs/job_objective.dm
> +			text += "<br>&nbsp;<font color='green'><B>[employee.name] выполнил[genderize_ru(usr.gender,"","а","о","и")] свою чёртову работу!</B></font>"
Вернул как было.

2022-09-11 12:03 UTC, PhantornRU reviewed
Мелкие ошибки исправил, сейчас пойду переопределять функции

2022-09-11 12:05 UTC, PhantornRU commented on code/datums/mind.dm
> +			var/counter = 0
Именно так, я не хочу повторов. Я пробовал сначала делать с проверкой по айдишникам, но по итогу оказалось, что айдишники сразу не определяются и всегда равняются нулям... Поэтому сделал через счетчик.
Сейчас попробую опять переделать.

2022-09-11 12:22 UTC, PhantornRU commented on code/datums/mind.dm
> +			var/datum/ambition_objective/objective = new /datum/ambition_objective(usr.mind)
Именно так, ни шагу назад и уже с новым датумом мы работаем и заполняем его

2022-09-11 12:33 UTC, PhantornRU commented on code/datums/mind.dm
> +	var/ambition_func = FALSE
Вынес в отдельную функцию

2022-09-11 12:35 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +#define FINDAMBITIONTASK_DEFAULT_NEW 1 // Make a new task of this type if one can't be found.
Мусор убран

2022-09-12 12:39 UTC, PhantornRU commented on strings/ambition_objectives_science.json
> +		"",
Пустые строки убраны, заменены весом

2022-09-12 15:31 UTC, Den109G commented on strings/ambition_objectives_supply.json
> +		"Что?! Кто-то пропустил точку?! Я не буду принимать такие бланки! Всё должно быть заполнено ИДЕАЛЬНО!",		""
:KotVShlyapi:
Потерялись бедные, пустые, даже без единственного пробела скобки.

2022-09-14 06:03 UTC, PhantornRU commented on strings/ambition_objectives_supply.json
> +		"Что?! Кто-то пропустил точку?! Я не буду принимать такие бланки! Всё должно быть заполнено ИДЕАЛЬНО!",		""
Да йапонаметь. Во заныкались. Щас удалю

2022-09-16 19:56 UTC, Dimach commented on code/game/ambitions/ambition_objective.dm
> +			if("Magistrate" && (prob(chance_other_departament_ambition))) //шанс что магистрат возьмёт общую амбицию глав.
То что ты написал "Magistrate" && (prob(chance_other_departament_ambition)) эквивалентно true && (prob(chance_other_departament_ambition))
У магистрата та же проблема. Чтобы проверить что роль магистрат тебе надо написать owner.assigned_role == "Magistrate"

2022-09-16 23:33 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +			if("Magistrate" && (prob(chance_other_departament_ambition))) //шанс что магистрат возьмёт общую амбицию глав.
А, догнал. Блин, а ведь действительно... Пойду править

2022-09-16 23:57 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +			if("Nanotrasen Representative" && (prob(chance_other_departament_ambition))) //шанс что НТР возьмёт общую амбицию закона.
Поправил

2022-09-16 23:57 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +			if("Magistrate" && (prob(chance_other_departament_ambition))) //шанс что магистрат возьмёт общую амбицию глав.
Поправил

2022-09-17 01:12 UTC, PhantornRU commented
Выпилена шиза
![image](https://user-images.githubusercontent.com/41479614/190834728-ef1b81e9-7710-483e-85bd-7a5adf99d329.png)

2022-09-17 01:12 UTC, PhantornRU commented on code/game/ambitions/ambition_objective.dm
> +	while(picked in choose_list)
Сделано

2022-09-19 02:44 UTC, Dimach approved these changes

2022-09-20 01:58 UTC, PhantornRU commented
Ура, прошел месяц ожидания амбиций!

2022-09-20 06:50 UTC, merged

2022-09-20 09:09 UTC, PhantornRU commented
Ура он был замержен! Ехууу! Праздник! Шампанское!