[BOUNTY] Космический Ниндзя
ss220-space/Paradise pull request #1272
Opened 2022-08-30 07:16 UTC by Furukia

# Космический ниндзя
Запрошенный Шуссом для прайма Космический Ниндзя. За основу был взят ниндзя с тг. Но переделан практически под чистую. Совершенно новая система покупки способностей. TGUI интерфейс для костюма. Новые цели - более логичные чем взлом кучки дверей с тг...  Ну обо всём по порядку. Так же естественно это дело планируется продвигать на мейн сервера.

## Интерфейс, кастомизация и способности
![2022-08-30_09-08-58](https://user-images.githubusercontent.com/67807868/187362611-7a2e8433-4c00-4a63-87ce-a4acc3fb1a3f.png)
Интерфейс костюма полностью сделан на TGUI. С уникальным стилем, обилием кнопок-подсказок призванных помочь игроку буквально встраивая в костюм некое IC-вики и не только. Так же есть возможность кастомизации своего образа посредством менюшки справа. Есть два стиля костюма - классический и новый и три стиля красная, зелёная и синяя  расцветки влияющие на лампочки на модельке ниндзя и на интерфейс способностей ниндзя. Ещё в интерфейсе есть кнопки управления шаттлом ниндзя. Позволяющему ему удалённо его призывать или отзывать.
### Способности (Кратко)
![f765578062be5ca3](https://user-images.githubusercontent.com/67807868/187372336-b317ade4-74ee-48db-8f69-6a9eca666e8a.gif)
^ Гифка немного старая.
Способности разделены на три столбца. При покупке 1 способности - покупка способности из соседнего столбца того же ряда, становится невозможной. Таким образом формируются "тройки" способностей которые нельзя взять вместе друг с другом. Список способностей ниже, разбитый по тройкам

| Дымовая завеса | Встроенный кунай на верёвке | Энергетические сюрекены
| Невидимость | Исцеляющий коктейль | Всплеск Адреналина
| Энергетические клоны | Экстренная телепортация | Электромагнитный взрыв
| Хамелион | Электро-чеснок (Калтропы) | Второй шанс (Одноразовая клонёрка на базе)
| Форма духа (Хождение сквозь любые стены) | Энергетическая сеть | Боевое Искусство Ползучей Вдовы

## Цели
Я выбрала немного необычный подход к целям ниндзя и сделала разбивку их на 3 набора среди которых выбирается один при спавне ниндзя и затем генерируется. 

- Первый набор целей заточен на более скрытную игру. Среди целей в этом наборе встречаются следующие:

1. Защита цели (Игра сгенерирует агентов с обычными целями, но как минимум 1 цель у каждого будет целью на убийство того самого кого ниндзя нужно защитить. Делая цель на защиту гораздо более интересной чем раньше)
2. Подставить цель (Игроку придётся придумать, как организовать легальное задержание цели и арест с выставлением статуса в консоли. И естественно если станция будет знать, что на ней водится ниндзя - то это будет сделать проблематично, ибо СБ будет занято ниндзя... )
3. Выжить

Этот набор небольшой, но это скорее потому, что цели в нём довольно сложные и в раунде если ниндзя выпал такой набор - будут сгенерированы дополнительно, трейторы. В соотношении 5 трейторов на 100 человек.

- Второй набор целей заточен на взломы разных устройств для саботажа станции и кражи. Среди целей в этом наборе встречаются следующие:

1. Кража борга (Взлом оного перчатками и "Эволюция" оного в новый модуль борга - борг клана паука)
2. Добыча денег (Собрать определённую сумму денег наличкой)
3. Саботаж ИИ (Взлом консоли законов ИИ !В АПЛОУДЕ! который при успехе сотрёт у ИИ все законы и выдаст ему 3 ионки, эффективно сводя боргов с ума, пока законы не поменяют. При начале взлома - оповещает ИИ)
4. Саботаж исследований (Взлом серверов РНД который при успехе удаляет ВСЕ данные и исследования накопленные на станции, сбрасывая их до 1-цы. Включая даже фабрикатор механика... При начале взлома - оповещает ИИ)
5. Обычная кража хайриска
6. Выжить

Этот набор больше предыдущего. Но цели на саботаж ИИ или РНД не встречаются вместе. Все эти цели при проверке не требуют людей и поэтому, если прошлый набор не смог сгенерироваться из-за лоупопа( Впрочем это маловероятно из-за требований для запуска режима). Будет сгенерирован этот набор

- Третий набор целей заточен на агрессивную игру. Среди целей в этом наборе встречаются следующие:

1. Кража борга
2. Подрыв отдела специальной бомбой (почти лимитка. выдаётся с целью)
3. Похищения (Поиск определённого обладающего информацией человека, среди написанных в самой цели отделов, через сканирование в устройстве на базе. Выполнение присуждается в двух случаях. Либо ты найдёшь нужного человека. Либо ты просканируешь определённое количество людей - минимум 3)
4. Обычное убийство
5. Выжить

Этот набор довольно агрессивен и с ним, ниндзя сто процентов будет замечен.

## Додзё и шаттл
![ninja_dojo](https://user-images.githubusercontent.com/67807868/187370638-87b751dd-59f8-408b-8d2f-cd527194a1b4.png)
В качестве зоны старта антагониста - было создано специальное додзё "в горах". Местечко вполне уютно и для жизни и для рп с похищенными и не только. Способов попадания на станцию у ниндзя - два:

- Шаттл
- Телепортация через консоль

Так же для шаттла специально был поправлен код угловых стен, дабы они всегда создавали какой никакой андерлей и система замены оного при перелёте - работала. Это всяко лучше, чем ставить два турфа в одно место(Так можно... И судя по всему в древности с этой системой так и делали...)

## Благодарности
Отдельная благодарность Синди Кролику за спрайт наушника, Элл Гууду за спрайты для почти всего, что я просила и @semoro за помощь с кодом пары моментов, сигналами и не только.
А так же спасибо тем кто помогал тестировать для ловли багов с целями, абилками и т.д.

2022-08-30 07:28 UTC, Furukia commented
Отдельно хочу добавить, что ниндзя использует конфиги для определения шанса выпадения режима в secret и количества людей для начала игры

Рекомендуемый текст для конфигов следующий
`PROBABILITY SPACE-NINJA 2`
`MINPLAYERS SPACE-NINJA 25`

2022-08-30 08:15 UTC, VasilevAY commented
> Запрошенный Шуссом для прайма Космический Ниндзя.

Так ПР для мастер и будет на мейнах, или только на прайм?
ПР сделан для мастера, поэтому и вопрос

2022-08-30 08:19 UTC, Furukia commented
> > Запрошенный Шуссом для прайма Космический Ниндзя.
> 
> Так ПР для мастер и будет на мейнах, или только на прайм? ПР сделан для мастера, поэтому и вопрос

Планирую как на прайм так и на мейны. Уверена пустить его на мейны будет не сложно. Даже если потребуется авоут.

2022-08-30 10:29 UTC, dj-34 approved these changes
В душе не ебу как ревьювить ПР на 16+ тысяч срок, поэтому получите просто ревью с теста.
Протестил в игре, багов не заметил. По механикам вопросов нет, но нужна статья на Вики с более подробным объяснением механик, для тех же боевых искусств. Имеются вопросы только по тексту (он кривой в интерфейсе), и к тому что шрифт русского и английского различаются (было бы неплохо подобрать совмещающийся).
И еще меня немного огорчило то, что выкрики Ниндзи на английском, хотя весь остальной текст на русском (в том числе общение игроков). Для меня это создает некий диссонанс.

2022-08-30 10:33 UTC, VasilevAY commented
> В душе не ебу как ревьювить ПР на 16+ тысяч срок, поэтому получите просто ревью с теста. Протестил в игре, багов не заметил. По механикам вопросов нет, но нужна статья на Вики с более подробным объяснением механик, для тех же боевых искусств. Имеются вопросы только по тексту (он кривой в интерфейсе), и к тому что шрифт русского и английского различаются (было бы неплохо подобрать совмещающийся). И еще меня немного огорчило то, что выкрики Ниндзи на английском, хотя весь остальной текст на русском. Для меня это создает некий диссонанс.

Поддерживаю замечания по тексту в интерфейсе, а еще бросается в глаза неровность стрелки и вопросика относительно иконки, в которой они расположены. А так, побегал, в первом приближении все работает. Не хватает вики странички с каким-нибудь гайдом.

2022-08-30 10:34 UTC, VasilevAY approved these changes

2022-08-30 11:58 UTC, larentoun approved these changes
Пробежалась глазами по коду, линтеры не ноют, все должно быть хорошо. Доверюсь коллегам, что фичи рабочие.

Могу лишь сказать, что желательно комментированный текст удалить (не в span_N), так как вряд ли кто-то будет возвращаться туда.

После этого мерджа, нужно будет потом кому-нибудь зарефакторить span class в код...

2022-08-30 11:58 UTC, PhantornRU approved these changes
Баги прям на стриме нашли, Фура сказал что все вкурсе, Ден на один указал. Сам баги и арбузы не нашел, кроме уже известных не касающихся ниндзи.

2022-08-30 12:36 UTC, AddRaiser reviewed
Тут я вспомнил, что мне за это не платят и дальше лень :DogeSmile:

2022-08-30 12:36 UTC, AddRaiser commented on code/LINDA/LINDA_system.dm
> +	if(istype(mover) && mover.checkpass(PASSEVERYTHINGELSE))
Как минимум - избавиться от else
Как максимум - сделать уже просто return со всеми условиями в строке

2022-08-30 12:36 UTC, AddRaiser commented on code/__DEFINES/dcs/signals.dm
> +	#define COMPONENT_SIMPLE_ANIMAL_NO_ATTACK (1<<0)
Как будто табуляция по пизде пошла

2022-08-30 12:36 UTC, AddRaiser commented on code/_onclick/item_attack.dm
> +			if(!attempt_initiate_surgery(src, target, user,1))
Знаю, что написал не ты, но вот эти return можно заодно тоже нормально написать

2022-08-30 12:42 UTC, BeebBeebBoob requested changes
А спонсор безумия проверки 206 файлов: t+pazolite

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/__DEFINES/flags.dm
> +#define PASSEVERYTHINGELSE 128
Не очень понятно что остальное всё. Там и двери, фоум, AM и многое другое. Эх если бы всё было разделено

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/__DEFINES/flags.dm
> +#define PASS_COMPLETELY_EVERYTHING PASSTABLE|PASSGLASS|PASSGRILLE|PASSBLOB|PASSMOB|LETPASSTHROW|PASSFENCE|PASSEVERYTHINGELSE
```suggestion
#define PASSEVERYTHING PASSTABLE|PASSGLASS|PASSGRILLE|PASSBLOB|PASSMOB|LETPASSTHROW|PASSFENCE|PASSEVERYTHINGELSE
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/__DEFINES/span.dm
> +// Старые капсом написанные SPAN_WARNING() и т.д. удалены и заменены в файлах где применялись, на аналоги ниже. без КАПСА!
Только это надо было бы делать отдельным ПРом от ПРа нинзди. Иначе это Ниндзя+рефактор span классов и вероятно другие вещи

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/__HELPERS/maths.dm
> +///Calculate the angle between two points and the west|east coordinate
стоит тогда перенести из code/__DEFINES/math.dm сюда остальный проки которые не под define

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/__DEFINES/dcs/signals.dm
> +///from base of atom/attackby(): (/obj/item, /mob/living, params)
Не думаю что это будет хорошая идея. Ну типо я не видел его использования и есть всегда парочку других сигналеров... есть COMSIG_MOVABLE_IMPACT_ZONE от mob/living/hitby() и COMSIG_MOB_ITEM_ATTACK от obj/item/attack()
И если всё так будешь оставлять то лучше 
```
///from base of atom/attackby(): (/obj/item, /atom/source, params) sends singal on user who attacked source
#define COMSIG_ATOM_ATTACK "atom_attack"

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/datums/action.dm
> +	var/action_initialisation_text = null	//Space ninja abilities only
Ах я бы конечно покричал что вот эту переменную покрывает комменты, и что лучше бы называть action_ninja_init_text ну не думаю что кто-то не поймёт

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/datums/helper_datums/icon_snapshot.dm
> +	var/examine_text
```suggestion
	var/examine_text	//используется только для ниндзя
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/datums/mind.dm
> +											"custom")
Список большой, но это кошмарно видеть его ещё и в таком виде
![image](https://user-images.githubusercontent.com/32985153/187397688-4048211c-7650-44d0-a98a-d7acea0d9906.png)
```suggestion
		var/list/objective_types = list(
			"assassinate", "blood", "debrain", "protect", "prevent", "brig", "hijack",
			"escape", "survive", "steal", "download", "nuclear", "capture", "absorb",
			"destroy", "maroon", "identity theft",)
		if(src in SSticker.mode.space_ninjas) // Цели для ниндзя //
			objective_types += list("get money", "find and scan", "set up", "research corrupt", "ai corrupt",
			"plant explosive", "cyborg hijack")
		objective_types += "custom"
```
N

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/area/ss13_areas.dm
```suggestion
	sound_environment = SOUND_AREA_STANDARD_STATION

```
Мы же не хотим оставлять аутпост без звука?

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/gamemodes/nuclear/pinpointer.dm
> +		var/closest_distance = 1000
O_O

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/gamemodes/nuclear/pinpointer.dm
> +		var/closest_distance = 1000
Можно было бы добавить как постоянную переменную нежели временную про проке. Может админы будут дёргать дистанцию
```suggestion
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/gamemodes/nuclear/pinpointer.dm
> +
```suggestion
	modes = list(MODE_NINJA)
	var/closest_distance = 1000

```
Вот здесь

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/gamemodes/nuclear/pinpointer.dm
> +		return FALSE
double check?
```suggestion
	scan_for_ninja()
	point_at(nearest_ninja, FALSE)
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/gamemodes/objective.dm
> +	var/check_cryo = TRUE
```suggestion
	var/check_cryo = TRUE //if the objective goes cryo, do we check for a new objective or ignore it
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/gamemodes/objective.dm
> +			log_debug("Ninja_Objectives_Log: Удаляем цели на защищаемого у убийц.")
Вот с этого момента идут очень много log_debug()
Видимо для тестирования использовалось но теперь это не нужно
В целом log_debug юзается для важных вещей или логирование не рантайм ошибки

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/gamemodes/spaceninja/space_ninja.dm
> +/datum/ninja
Всегда можно выделить отдельный ninja_datum.dm Но это больше как предложение

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/jobs/job_exp.dm
> +	ROLE_NINJA = 50,	// Я нахожу ниндзя более скилозависимым антагом чем того же мага и думаю, что лишние 20 часов требования не помешают.
Ми би лайк с более 1000 часов уже, но ни разу не играл на всех антагах и не знает как. :Kekwat:

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +/obj/item/tank/emergency_oxygen
У нас уже есть /obj/item/tank/internals/emergency_oxygen
Придётся всё здесь менять и удалять из-за копии

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +
```suggestion
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/objects/structures/mineral_doors.dm
> +/obj/structure/mineral_door/wood/paperframe
А создать его никто не сможет? Или это чисто для админов под ЕРП зону? KEKW

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/objects/structures/morgue.dm
> +	to_chat(CM, span_alert("You attempt to slide yourself out of \the [src]..."))
А это как попало в ПР про ниндзей? :NotLikeThis: часть разрабов у нас вероятно будут продолжать юзать <span class> и в итоге у нас будет миксер спанов, а это плохо-плохо

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/objects/structures/window.dm
> +/obj/structure/window/full/paperframe
Админ-онли комната моумент

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/shuttle_engines.dm
> +	resistance_flags = INDESTRUCTIBLE			// То что у нас двигатели ломаются от пары пуль - бред
На момент я подумал что это укреплённый пол. Всегда можно накрутить integrity до 1000 (это примерно 4 канистры) ну да ладно

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/game/turfs/simulated/shuttle.dm
> +/turf/simulated/shuttle/wall/Initialize()
Мне трындец как не нравиться что таким путём построен. Кто изначально сделал T/sim/shuttle/wall и другие турфы, у того нужно отобрать доступ изменять код. По сути это должно быть /turf/sim/wall/shuttle но видимо урон коду уже нанесено и исправлять его будут в другом ПРе

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/clothing/masks/miscellaneous.dm
> + * Я пожалуй оставлю, но закоменчу этот код.
Потому что его добавили в игру 10 лет назад так ещё тот кто добавил не проверял и видимо на пох добавили
![image](https://user-images.githubusercontent.com/32985153/187413858-3f4bf5c2-7668-459a-a9c2-6ea289e0475d.png)

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/mining/equipment/survival_pod.dm
> +//						/obj/item/katana/energy,
```suggestion
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/mob/living/carbon/human/human.dm
> +	// Ниндзя не пользуется чужими пушками. В этом нет чести, нет уважения, нет САКЭ!
Bruh

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/datums/mind.dm
> +	var/datum/ninja/ninja				//ninja holder
В руки datum/antagonist и советую вот так ПОКА не поздно https://github.com/ParadiseSS13/Paradise/pull/17166

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/mob/living/silicon/robot/robot.dm
> +	var/module_override_protected = FALSE // Флаг запрещающий Ниндзя взломать этого киборга и сделать из него своего.
Я увидел что защита есть только у дрона(ибо не борг), синдикатовских и у syndicate/saboteur/ninja(который уже имеет TRUE от сабтипа syndicate)
Так почему нету у админ борг, боргов дедов или ЕРТ боргов?

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/__ninjaDefines.dm
> +#define IS_SPACE_NINJA(ninja) (isninja(ninja))
НЕ ЗДЕСЬ. ПРОШУ. 
code/__DEFINES/ninja.dm !!!

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/__ninjaDefines.dm
> +#define IS_SPACE_NINJA(ninja) (isninja(ninja))
#define IS_SPACE_NINJA(ninja) (isninja(ninja))
То есть это глобал прок, который вызывает другой глобал прок? Зачем?
#define isninja(ninja) (isninja(ninja))

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/components/ninja_states_breaker.dm
> +									COMSIG_CARBON_HITBY))
```suggestion
	UnregisterSignal(parent, list(
		COMSIG_ATOM_BLOB_ACT,
		COMSIG_PARENT_ATTACK,
		COMSIG_PARENT_ATTACKBY,
		COMSIG_MOB_DEATH,
		COMSIG_ATOM_BULLET_ACT,
		COMSIG_ITEM_ATTACK,
		COMSIG_MOB_ITEM_ATTACK,
		COMSIG_MOB_APPLY_DAMAGE,
		COMSIG_SIMPLE_ANIMAL_ATTACKEDBY,
		COMSIG_CARBON_HITBY))
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/components/ninja_states_breaker.dm
> +									COMSIG_CARBON_HITBY), .proc/cancel_states)
```suggestion
	RegisterSignal(parent, list(
		COMSIG_ATOM_BLOB_ACT,
		COMSIG_PARENT_ATTACK,
		COMSIG_PARENT_ATTACKBY,
		COMSIG_MOB_DEATH,
		COMSIG_ATOM_BULLET_ACT,
		COMSIG_ITEM_ATTACK,
		COMSIG_MOB_ITEM_ATTACK,
		COMSIG_MOB_APPLY_DAMAGE,
		COMSIG_SIMPLE_ANIMAL_ATTACKEDBY,
		COMSIG_CARBON_HITBY), .proc/cancel_states)

```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/Ninja_Readme.dm
> -// TODO
Рекомендую перенести все файлы из этой папки ninja в code/game/gamemodes/spaceninja
Рекомендация исходит из того что это вещи антага, а не отдельный модуль в игру(game/modules).
Также сделан кровавый культ, многие миниантаги, маг, блоб и т.д.

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninjaDrainAct.dm
> +	if(area && istype(area, /area/engine/engineering))
/area/engine/supermatter ? Хотя я не помню как там работает СМ и сможет ли он взорваться без АПЦ

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninjaDrainAct.dm
> +/obj/machinery/power/apc/ninjadrain_act(obj/item/clothing/suit/space/space_ninja/ninja_suit, mob/living/carbon/human/ninja, obj/item/clothing/gloves/space_ninja/ninja_gloves)
каждый акт лучше просунуть в каждый свой файл чем держать всё это в одном файле

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninjaDrainAct.dm
> +		// Ровно разместить полоски в чате самой игры не выйдет увы...
Я думал что не стану комментировать, но если он будет плохо выходить в игру из-за изменение фонта и размера фонтов, то это надо придётся убирать. Также рекомендую это вероятно прибрать на потом, либо через конфиг в текст файл, либо не знаю или будет у борга насрано прям трындец. Даже при емаге нету такого

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_chameleon.dm
> +	qdel(ninja.GetComponent(/datum/component/ninja_states_breaker))
Боже нет. это не простой там датум а компонент.
```suggestion
	ninja.GetComponent(/datum/component/examine_override).RemoveComponent()
	ninja.GetComponent(/datum/component/ninja_states_breaker).RemoveComponent()
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_stealth.dm
> +		qdel(ninja.GetComponent(/datum/component/ninja_states_breaker))
```suggestion
		ninja.GetComponent(/datum/component/ninja_states_breaker).RemoveComponent()
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/suit.dm
> +							)
```suggestion
	actions_types = list(
		/datum/action/item_action/SpiderOS,
		/datum/action/item_action/ninja_autodust,
		/datum/action/item_action/ninjastatus,
		/datum/action/item_action/ninja_sword_recall,
/*		/datum/action/item_action/ninja_stealth, Не используется
		/datum/action/item_action/ninja_chameleon,
		/datum/action/item_action/ninja_spirit_form,
		/datum/action/item_action/ninjaboost,
		/datum/action/item_action/ninjaheal,
		/datum/action/item_action/ninja_clones,
		/datum/action/item_action/ninjapulse,
		/datum/action/item_action/ninja_smoke_bomb,
		/datum/action/item_action/ninja_caltrops,
		/datum/action/item_action/ninja_emergency_blink,
		/datum/action/item_action/johyo,
		/datum/action/item_action/ninjanet,
		/datum/action/item_action/toggle_shuriken_fire_mode
		/datum/action/item_action/ninjastar, */ 
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_suit_initialisation.dm
> +))
может вместо того чтобы делать это глобальным, засунуть в сам костюм?

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/suit.dm
> +											"headset_green")
![image](https://user-images.githubusercontent.com/32985153/187430929-c3500662-b7a5-4706-a5a0-3dc6a38272fa.png)
Ха?...
```suggestion
	var/static/list/allowed_states = list(
		"shuriken", "ninja_cloak", "ninja_spirit_form", "dust", "chameleon",
		"kunai", "smoke", "adrenal", "energynet", "emergency_blink",
		"ninja_clones", "emp", "chem_injector", "healthstatus", "caltrop",
		"cloning", "spider_green", "spider_red", "spider_blue", "work_in_progress",
		"ninja_sleeper", "ai_face", "ninja_borg", "server", "buckler",
		"cash", "handcuff", "spider_charge", "ninja_teleport", "headset_green")
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/suit.dm
> +	/// Лист доступных спрайтов из 'icons/mob/ninja_previews.dmi' для tgui.
Пока ещё не упустил момент. Комменты лучше делать на английском ибо происходит такое 
![image](https://user-images.githubusercontent.com/32985153/187431906-a2197d92-f7a9-438b-aee5-d48ac0a8b361.png)

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/suit.dm
> +													"ninja_preview_new_scarf_new_red_f")
```suggestion
	"ninja_preview_classic_hood_green", "ninja_preview_classic_hood_red",
	"ninja_preview_classic_hood_blue", "ninja_preview_classic_hood_green_f",
	"ninja_preview_classic_hood_red_f", "ninja_preview_classic_hood_blue_f",
	"ninja_preview_new_hood_green", "ninja_preview_new_hood_blue",
	"ninja_preview_new_hood_red", "ninja_preview_new_hood_green_f",
	"ninja_preview_new_hood_blue_f", "ninja_preview_new_hood_red_f",
	// Шарф отличается от стиля костюма
	"ninja_preview_new_scarf_classic_green", "ninja_preview_new_scarf_classic_blue",
	"ninja_preview_new_scarf_classic_red", "ninja_preview_new_scarf_classic_green_f",
	"ninja_preview_new_scarf_classic_blue_f", "ninja_preview_new_scarf_classic_red_f",
	"ninja_preview_classic_scarf_new_green", "ninja_preview_classic_scarf_new_red",
	"ninja_preview_classic_scarf_new_blue", "ninja_preview_classic_scarf_new_green_f",
	"ninja_preview_classic_scarf_new_red_f", "ninja_preview_classic_scarf_new_blue_f",
	// Шарф имеет такой же стиль как и костюм
	"ninja_preview_classic_scarf_classic_green", "ninja_preview_classic_scarf_classic_red",
	"ninja_preview_classic_scarf_classic_blue", "ninja_preview_classic_scarf_classic_green_f",
	"ninja_preview_classic_scarf_classic_red_f", "ninja_preview_classic_scarf_classic_blue_f",
	"ninja_preview_new_scarf_new_green", "ninja_preview_new_scarf_new_blue",
	"ninja_preview_new_scarf_new_red", "ninja_preview_new_scarf_new_green_f",
	"ninja_preview_new_scarf_new_blue_f", "ninja_preview_new_scarf_new_red_f")
```
А лучше и легче будет если заполнить в Initialize через парочку for циклов

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/suit.dm
> +									"I'M LIGHTNING! THE RAIN TRANSFORMED!")
```suggestion
	var/list/boost_phrases = list(
		"A CORNERED FOX IS MORE DANGEROUS THAN A JACKAL!",
		"I'M A SHADOW, ONE THAT NO LIGHT WILL SHINE ON!",
		"HURT ME MOOORRREEE!", "IMPRESSIVE!",
		"MY POWER IS ABSOLUTE!", "SHOW ME YOUR MOTIVATION!",
		"I'LL CUT YOU IN TWO!", "I'M FUCKING INVINCIBLE!",
		"I'M LIGHTNING! THE RAIN TRANSFORMED!")
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/suit.dm
> +													"Это просто был ветер, да?")
```suggestion
					var/sounds = pick(
						'sound/ambience/ambifailure.ogg',
						'sound/ambience/ambigen5.ogg',
						'sound/machines/ventcrawl.ogg',
						'sound/effects/noise_scan.ogg',
						'sound/effects/footstep/wood1.ogg',
						'sound/effects/footstep/wood2.ogg',
						'sound/effects/footstep/wood3.ogg',
						'sound/effects/footstep/wood4.ogg',
						'sound/effects/footstep/wood5.ogg')
					var/random_danger_text = pick( "У вас по коже пробежали мурашки...", "Такое чувство, что на вас кто-то смотрит...", "Кажется вы врезались во что-то!")
					var/random_subtle_text = pick( "Вам кажется вы слышали шаги...", "Что то мелькнуло у вас перед глазами...", "Это просто был ветер, да?")
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/suit.dm
> +				//Эффекты призванные "Намекнуть", что рядом есть ниндзя
Думаю лучше будет сделать все эти проверки в отдельный прок который вызывается прямо здесь
```suggestion
				stealth_noise_check(stealth_ambient_chance) 
```
 что-то такого типо

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/suit.dm
> +	if(!IS_SPACE_NINJA(ninja) && !anyone)
```suggestion
	if(!isninja(ninja) && !anyone)
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/ninja_explosive.dm
> +	if(!IS_SPACE_NINJA(ninja))
```suggestion
	if(!isninja(ninja))
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/ninja_explosive.dm
> +	if(detonation_objective && IS_SPACE_NINJA(user))
```suggestion
	if(detonation_objective && isninja(user))
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/machinery/ninja_mindscan_machine.dm
> +	if(!IS_SPACE_NINJA(user))
```suggestion
	if(!isninja(user))
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/machinery/ninja_mindscan_machine.dm
> +	if(!IS_SPACE_NINJA(user))
```suggestion
	if(!isninja(user))
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_chameleon.dm
> +		for(i in 1 to 7)
так много магических букв

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/suit.dm
> +		return TRUE
```suggestion
	switch(action)
		if(/datum/action/item_action/ninja_autodust)
			ninja_toggle_autodust()
			return TRUE
		if(/datum/action/item_action/ninjastatus)
			ninjastatus()
			return TRUE
		if(/datum/action/item_action/ninjaboost)
			ninjaboost()
			return TRUE
		if(/datum/action/item_action/ninjaheal)
			ninjaheal()
			return TRUE
		if(/datum/action/item_action/ninjastar)
			ninjastar()
			return TRUE
		if(/datum/action/item_action/toggle_shuriken_fire_mode)
			toggle_shuriken_fire_mode()
			return TRUE

	//Всё что ниже этой проверки, будет подвержено общему кулдауну костюма вызываемым некоторыми способностями
	if(s_coold > 0)
		to_chat(ninja, span_warning("<b>ERROR</b>: suit is on cooldown."))
		return FALSE

	switch(action)
		if(/datum/action/item_action/ninja_clones)
			spawn_ninja_clones()
			return TRUE
		if(/datum/action/item_action/ninjapulse)
			ninjapulse()
			return TRUE
		if(/datum/action/item_action/ninjanet)
			ninjanet()
			return TRUE
		if(/datum/action/item_action/ninja_sword_recall)
			ninja_sword_recall()
			return TRUE
		if(/datum/action/item_action/ninja_stealth)
			toggle_stealth()
			return TRUE
		if(/datum/action/item_action/ninja_chameleon)
			toggle_chameleon_scanner_mode()
			return TRUE
		if(/datum/action/item_action/ninja_smoke_bomb)
			prime_smoke()
			return TRUE
		if(/datum/action/item_action/ninja_caltrops)
			scatter_caltrops()
			return TRUE
		if(/datum/action/item_action/johyo)
			toggle_harpoon()
			return TRUE
		if(/datum/action/item_action/ninja_emergency_blink)
			emergency_blink()
			return TRUE
		if(/datum/action/item_action/ninja_spirit_form)
			if(!is_teleport_allowed(ninja.z))	//Дублирую и тут, потому что спамом абилки можно на доли секунды врубить её и пройти сквозь стену
				to_chat(ninja, span_warning("This place forcibly stabilizes your body somehow! You can't use \"Spirit Form\" there!"))
				return FALSE
			toggle_spirit_form()
			return TRUE
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_adrenaline.dm
> +	s_coold = 30
```suggestion
	s_coold = 3 SECONDS
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_caltrops.dm
> +		s_coold = 10
```suggestion
		s_coold = 1 SECONDS
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_clone.dm
> +		s_coold = 10
```suggestion
		s_coold = 1 SECONDS
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_emergency_blink.dm
> +		s_coold = 10
```suggestion
		s_coold = 1 SECONDS
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_empulse.dm
> +	s_coold = 40
```suggestion
	s_coold = 4 SECONDS
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_healing_chems.dm
> +	s_coold = 30
```suggestion
	s_coold = 3 SECONDS
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_johyo.dm
> +		my_suit.s_coold = 50
```suggestion
		my_suit.s_coold = 5 SECONDS
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_smoke_bomb.dm
> +		s_coold = 30
```suggestion
		s_coold = 3 SECONDS
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_sword_recall.dm
> +		s_coold = 5	//0.5 секунд задержки, чтобы избежать спама возврата
```suggestion
		s_coold = 0.5 SECONDS //0.5 секунд задержки, чтобы избежать спама возврата
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/ninja/suit/uniform.dm
> +/obj/item/clothing/under/ninja
пижама

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/projectiles/gun.dm
> +	var/ninja_weapon = FALSE 			//Оружия со значением TRUE обходят ограничение ниндзя на использование пушек
Не знаю, лучше просто проверять в art_marts по типу пушки(это /obj/item/gun/energy/shuriken_emitter, /obj/item/gun/magic/johyo и всё), хотя может админам будет прикольно давать возможность использовать и другие пушки

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/projectiles/projectile/energy.dm
>  	stutter = 1
```suggestion
```

2022-08-30 12:42 UTC, BeebBeebBoob commented on code/modules/projectiles/projectile/energy.dm
> +*/
```suggestion
```
мне гитхаб почему-то не разрешает в одно предложение сделать

2022-08-30 12:44 UTC, BeebBeebBoob commented
@VasilevAY @larentoun  @PhantornRU 
![image](https://user-images.githubusercontent.com/32985153/187439701-751d1531-6f64-456f-ab6d-beb91f400ede.png)

2022-08-30 12:49 UTC, larentoun commented
> @VasilevAY @larentoun @PhantornRU ![image](https://user-images.githubusercontent.com/32985153/187439701-751d1531-6f64-456f-ab6d-beb91f400ede.png)

Я то че, я клоун, не запретили ставить галочку рандомным челам.

2022-08-30 12:50 UTC, PhantornRU commented
Мы мамкины тестеры на локалках

2022-08-30 12:53 UTC, Zipliks commented
Про span.dm
У нас принято капсом писать все макросы, зря откатил

2022-08-30 12:58 UTC, Vallat commented
> @VasilevAY @larentoun @PhantornRU ![image](https://user-images.githubusercontent.com/32985153/187439701-751d1531-6f64-456f-ab6d-beb91f400ede.png)

Это ты еще процентов 30 только покрыл от всего, что тут стоило бы поменять))

2022-08-30 12:58 UTC, BeebBeebBoob commented
> Про span.dm У нас принято капсом писать все макросы, зря откатил

Лучше изначально сделать отдельный ПР для span либо продолжить жить по старинке со span class

Иначе будет микс который не круто будет выглядеть и читаться.
Типо вон в том месте span() а в другом <span>

2022-08-30 12:58 UTC, larentoun commented
> Про span.dm У нас принято капсом писать все макросы, зря откатил

Это с ТГ

2022-08-30 13:25 UTC, VasilevAY commented
> > @VasilevAY @larentoun @PhantornRU ![image](https://user-images.githubusercontent.com/32985153/187439701-751d1531-6f64-456f-ab6d-beb91f400ede.png)
> 
> Это ты еще процентов 30 только покрыл от всего, что тут стоило бы поменять))

О, жду твоего ревью очень. Будешь его делать?

2022-08-30 13:53 UTC, Furukia commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +/obj/item/tank/emergency_oxygen
Откуда копия ля... Надо проверить, что ты имеешь ввиду с этой фигнёй. я вроде не делала копий обычных emergency_oxygen - это может быть вообще не связано с моим коммитом. Чекну в общем позже

2022-08-30 13:54 UTC, Furukia commented on code/game/objects/structures/morgue.dm
> +	to_chat(CM, span_alert("You attempt to slide yourself out of \the [src]..."))
Добавила спаны. У нас они были всего пару раз и капсом. Заменила все капсы на не капсы. Поэтому это и тут

2022-08-30 13:57 UTC, Furukia commented on code/game/objects/structures/mineral_doors.dm
> +/obj/structure/mineral_door/wood/paperframe
Рецепты можно добавить и отдельно. Если прям так хочется. но да. Админ/мапер онли штука

2022-08-30 14:12 UTC, Furukia commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_chameleon.dm
> +	qdel(ninja.GetComponent(/datum/component/ninja_states_breaker))
Все компоненты ранее в коде убирали через qdel вместо RemoveComponent, что самое интересное. Я ещё с семоро на этот счёт уточняла и решили поступить как поступали раньше. Впрочем мне буквально всё равно как. Если и вправду лучше удалять так, то по хорошему стоит и все прошлые удаления компонентов под этот стандарт пихать. Потому что там сейчас только squeak компонент.

2022-08-30 14:15 UTC, Furukia commented on code/modules/ninja/suit/suit.dm
> +	/// Лист доступных спрайтов из 'icons/mob/ninja_previews.dmi' для tgui.
Ага. Круто. Я не буду переводить все комменты на английский.

2022-08-30 14:23 UTC, Vallat commented
> О, жду твоего ревью очень. Будешь его делать? @Vallat

Нет

2022-08-30 15:15 UTC, Furukia commented on code/datums/mind.dm
> +											"custom")
Ну не знаю. Читать столбиком как по мне гораздо лучше. А проверку ты нафига добавил? Часть из этих целей можно и для "не ниндзя" дать. Остальные имеют предупреждение. А ты запрещаешь этой проверкой выдать их тем, что не ниндзя. Если админы хотят выдать. Пусть. Не вижу смысл запрещать ту же кражу денег. Её любой может сделать

2022-08-31 01:45 UTC, Furukia commented on code/__DEFINES/dcs/signals.dm
> +	#define COMPONENT_SIMPLE_ANIMAL_NO_ATTACK (1<<0)
Ничего не знаю. Делала так же как было с другими сигналами в этом файле

2022-08-31 01:46 UTC, Furukia commented on code/_onclick/item_attack.dm
> +			if(!attempt_initiate_surgery(src, target, user,1))
Это дело не моё. Кому надо, поправят до однострочных вариантов

2022-08-31 01:47 UTC, Furukia commented on code/LINDA/LINDA_system.dm
> +	if(istype(mover) && mover.checkpass(PASSEVERYTHINGELSE))
тут поправлю

2022-08-31 01:51 UTC, Furukia commented on code/__DEFINES/span.dm
> +// Старые капсом написанные SPAN_WARNING() и т.д. удалены и заменены в файлах где применялись, на аналоги ниже. без КАПСА!
![tumblr_41b99d10caaa658e7a37ac8ef01151ac_1efedd63_400](https://user-images.githubusercontent.com/67807868/187575132-eaa1f389-bc4e-4be9-98d1-26eb69b4cc79.png)
Ага, как скажешь.

2022-08-31 01:54 UTC, Furukia commented on code/__HELPERS/maths.dm
> +///Calculate the angle between two points and the west|east coordinate
раз ты настаиваешь перенесу

2022-08-31 01:56 UTC, Furukia commented on code/__DEFINES/dcs/signals.dm
> +///from base of atom/attackby(): (/obj/item, /mob/living, params)
Пока я работала и познавала сигналы, я этот сигнал добавила, но в итоге нигде не использовала. Его техникали можно и удалить, но думаю лучше оставить на всякий. Я перенесу твой вариант нейминга. в код.

2022-08-31 01:58 UTC, Furukia commented on code/datums/action.dm
> +	var/action_initialisation_text = null	//Space ninja abilities only
вкусовщина

2022-08-31 02:27 UTC, Furukia commented on code/datums/helper_datums/icon_snapshot.dm
> +	var/examine_text
зачем?

2022-08-31 02:33 UTC, Furukia commented on code/modules/ninja/__ninjaDefines.dm
> +#define IS_SPACE_NINJA(ninja) (isninja(ninja))
Перемещу

2022-08-31 02:34 UTC, Furukia commented on code/datums/mind.dm
> +	var/datum/ninja/ninja				//ninja holder
Не не не. Я не буду переписывать половину кода ради того чтобы сделать это как антаг датум. Этим можно заняться позже - отдельно. Но сейчас у меня написано по аналогии с вампом и генкой и пока оно останется так.

2022-08-31 02:36 UTC, Furukia commented on code/modules/mob/living/silicon/robot/robot.dm
> +	var/module_override_protected = FALSE // Флаг запрещающий Ниндзя взломать этого киборга и сделать из него своего.
Добавлю destroyer боргу. остальным не стану. И что, что ерт/дед? Не админский же.

2022-08-31 02:38 UTC, Furukia commented on code/game/gamemodes/objective.dm
> +			log_debug("Ninja_Objectives_Log: Удаляем цели на защищаемого у убийц.")
Логи останутся. По причине возможных проблем с целями, что вскроются уже на тестах. И логи станут моим спасением в попытке понять, что лять пошло не так. Когда я буду это чинить. Уберём логи, когда будем уверены в стабильности работа кода ниндзи, целей и т.д.

2022-08-31 02:39 UTC, Furukia commented on code/game/gamemodes/objective.dm
> +	var/check_cryo = TRUE
добавлю

2022-08-31 02:43 UTC, Furukia commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +
Я посмотрела насчёт дубликатов. И я честно хз откуда взялись такие типы и главное - почему гит решил, что их написала я. Но я предпочту их не трогать. Их можно удалить отдельным ПР-ом от ниндзя. Главное убедиться что они нигде не используются в коде.

2022-08-31 02:47 UTC, Furukia commented on code/modules/ninja/__ninjaDefines.dm
> +#define IS_SPACE_NINJA(ninja) (isninja(ninja))
Перенос куска кода с ТГ. Тут если подумать - ты прав. Я уберу дефайн

2022-08-31 02:49 UTC, Furukia commented on code/modules/ninja/Ninja_Readme.dm
> -// TODO
перенесу

2022-08-31 02:55 UTC, Furukia commented on code/__DEFINES/dcs/signals.dm
> +///from base of atom/attackby(): (/obj/item, /mob/living, params)
Поправочка. Поиск по коду меня наебал. Этот сигнал я таки использовала. Я уберу его где он не нужен и переименую.

2022-08-31 02:57 UTC, Furukia commented on code/__DEFINES/dcs/signals.dm
> +///from base of atom/attackby(): (/obj/item, /mob/living, params)
А вообще странный сигнал какой то вышел. Просто делает то же, что и сигнал ниже. Что я ля накодила ранее... XD

2022-08-31 03:04 UTC, Furukia commented on code/game/gamemodes/nuclear/pinpointer.dm
> +		var/closest_distance = 1000
неее

2022-08-31 03:05 UTC, Furukia commented on code/modules/ninja/suit/ninjaDrainAct.dm
> +	if(area && istype(area, /area/engine/engineering))
Добавлю

2022-08-31 03:20 UTC, Furukia commented on code/modules/ninja/suit/ninjaDrainAct.dm
> +/obj/machinery/power/apc/ninjadrain_act(obj/item/clothing/suit/space/space_ninja/ninja_suit, mob/living/carbon/human/ninja, obj/item/clothing/gloves/space_ninja/ninja_gloves)
ок

2022-08-31 03:23 UTC, Furukia commented on code/modules/ninja/suit/ninjaDrainAct.dm
> +		// Ровно разместить полоски в чате самой игры не выйдет увы...
![BxM4WW2awR8](https://user-images.githubusercontent.com/67807868/187585600-9441f81f-92ff-46a6-ad71-f6f4a67cf855.jpg)
Ой да там в чат один раз это выведет. Если часто будут говорить, что выглядит не очень. Заменю. А пока нормааааально.

2022-08-31 03:52 UTC, Furukia commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_suit_initialisation.dm
> +))
пожалуй

2022-08-31 04:04 UTC, Furukia commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_chameleon.dm
> +		for(i in 1 to 7)
![AstolfoStickers_17](https://user-images.githubusercontent.com/67807868/187590203-0d6429fd-dfb7-44a4-91e7-41812de369a9.png)

2022-08-31 04:14 UTC, Furukia commented on code/modules/ninja/suit/uniform.dm
> +/obj/item/clothing/under/ninja
![Menhera-chan_178](https://user-images.githubusercontent.com/67807868/187591448-d51088f9-3c6f-4a63-9aa2-195caf655fa4.png)

2022-08-31 04:49 UTC, Den109G commented on code/modules/ninja/suit/ninjaDrainAct.dm
> +		emag_act()
А нужно ли снова писать акт для аирлока, если аирлок и так находится в дверях (`/obj/machinery/door`)?
Просто и тут и там код одинаковый.

2022-08-31 05:02 UTC, Furukia commented on code/modules/ninja/suit/ninjaDrainAct.dm
> +		emag_act()
А ля. Короче раньше в коде была цель на емаг толпы дверей. Но позже я решила что эта цель с тг - говно и убрала её и её следы, НО! Я как то упустила что из-за этого разный код дверей - стал одинаковым. Я уберу лишнее.

2022-08-31 05:10 UTC, Furukia commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_chameleon.dm
> +	qdel(ninja.GetComponent(/datum/component/ninja_states_breaker))
Вот об этом вопросе мне бы хотелось расспросить как следует чуть позже. Потому что мне интересно на самом деле понять как правильнее и почему.

2022-08-31 09:43 UTC, Den109G commented on tgui/packages/tgui/interfaces/SpiderOS.js
> +              \nПользуясь встроенным контроллером шатла, вы всегда сможете призвать его к себе и вернуться назад. \
Наверное лучше сейчас это поменять, а то никто потом не исправит.
```suggestion
              \nПользуясь встроенным контроллером шаттла, вы всегда сможете призвать его к себе и вернуться назад. \
```

2022-08-31 12:10 UTC, AddRaiser commented on code/LINDA/LINDA_system.dm
> +	return istype(mover) && mover.checkpass(PASS_OTHER_THINGS) ? TRUE : (!density || !height)
Не, если уж в одну строчку, то вот это все еще плохо

return (istype(mover) && mover.checkpass(PASS_OTHER_THINGS)) || !density || !height

(Я просто дурак и забыл, как именно предлагать правку кода сразу)

2022-08-31 12:26 UTC, Den109G commented on code/LINDA/LINDA_system.dm
> +	return istype(mover) && mover.checkpass(PASS_OTHER_THINGS) ? TRUE : (!density || !height)
![image](https://user-images.githubusercontent.com/87372121/187677932-7fc5b999-0648-47c6-bf8e-352e273de7fd.png)
Гит подсказывает Ctrl+G

2022-08-31 12:34 UTC, Den109G commented on code/game/gamemodes/spaceninja/space_ninja.dm
> +	var/no_guns_message = "Технологии моего клана в разы превосходят, это жалкое подобие оружия! Я отказываюсь этим пользоваться!"
![image](https://user-images.githubusercontent.com/87372121/187679329-d5d9194e-b37b-4621-90c3-dfc4a8294c0f.png)

2022-08-31 13:00 UTC, Den109G commented on code/game/gamemodes/spaceninja/ninja/drain_act/cable.dm
> +
Скопипастино с `code/modules/power/cable.dm`
```suggestion
var/turf/T = get_turf(src)
	if(T.transparent_floor || T.intact)
		to_chat(user, "<span class='danger'>You can't interact with something that's under the floor!</span>")
		return INVALID_DRAIN
```
Должно помочь с тем багом.

2022-08-31 18:29 UTC, Furukia commented on code/modules/ninja/suit/ninja_equipment_actions/ninja_chameleon.dm
> +	qdel(ninja.GetComponent(/datum/component/ninja_states_breaker))
@BeebBeebBoob Ты читал Destroy у компонентов вообще? Там почти одно и то же. Только PreTransfer() в твоём случае ещё вызывается. Который мною не используется. В общем это изменение по факту и не нужно

2022-09-05 21:05 UTC, semoro reviewed
Часть ревью первая

2022-09-05 21:05 UTC, semoro commented on code/_onclick/item_attack.dm
> +/obj/item/proc/attack(mob/living/target, mob/living/user, def_zone)
Пожалуйста не переименовывай в несвязанных коммитах, потом сложно понять будет зачем это было изменено

2022-09-05 21:05 UTC, semoro commented on code/datums/action.dm
> +	var/action_initialisation_text = null	//Space ninja abilities only
Зачем это в базовом экшене?

2022-09-05 21:05 UTC, semoro commented on paradise.dme
> +#include "_maps\cyberiad.dm"
Пожалуйста не переключай карту тут

2022-09-05 21:05 UTC, semoro commented on code/modules/ninja/suit/suit_attackby.dm
> +		else if(uranium_stack.amount >= a_transfer  && heal_available != TRUE)
Так и задумано что костюм заряжается в два действия?

2022-09-05 21:05 UTC, semoro commented on code/modules/ninja/components/ninja_states_breaker.dm
> +/*
Кажется лишний код закоммеченный

2022-09-05 21:05 UTC, semoro commented on code/modules/mob/living/silicon/robot/robot.dm
> +/mob/living/silicon/robot/proc/spawn_syndicate_borgs(var/robot_to_spawn, turf/T)
Изменения тут не относятся к этому ПР-у

2022-09-05 21:05 UTC, semoro commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +	desc = "Used for \"emergencies,\" it actually contains a fair amount of oxygen. Looks kinda cool!"
`Used for \"emergencies\", it actually contains a fair amount of oxygen. Looks kinda cool!`

2022-09-05 21:05 UTC, semoro commented on tgui/packages/tgui/styles/components/Tooltip.scss
> +$color-title: #ffffff !default;
Где используются эти параметры?

2022-09-05 21:05 UTC, semoro commented on code/modules/mining/equipment/survival_pod.dm
> -						/obj/item/katana/energy,
Мне кажется это какой-то неожиданный сайд эффект, хотя я не знаю что там с балансом было, но думаю  шахтеры могут не обрадоваться

2022-09-05 21:05 UTC, semoro commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +/obj/item/tank/emergency_oxygen
А зачем нам копия emergency oxygen?

2022-09-05 21:05 UTC, semoro commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +	desc = "Used for emergencies. Contains very little oxygen, so try to conserve it until you actually need it. Looks kinda cool!"
Почему сообщения отличаются? 
В `emergency_oxygen/double/ninja` 'emergencies' написано в кавычках

2022-09-05 21:05 UTC, semoro commented on code/game/objects/items/weapons/explosives.dm
> +	var/boom_sizes = list(0, 0, 3)
лучше сделать отдельные переменные уже в таком случае

2022-09-06 05:59 UTC, Furukia commented on code/_onclick/item_attack.dm
> +/obj/item/proc/attack(mob/living/target, mob/living/user, def_zone)
Ещё валлат мне в своё время настаивал избавляться от однобуквенных переменных давая им более понятные наименования. Но я учту твой комментарий и в дальнейшем не буду менять переменные в подобных, сторонних проках...

2022-09-06 06:00 UTC, Furukia commented on code/datums/action.dm
> +	var/action_initialisation_text = null	//Space ninja abilities only
Дело в том, что как минимум экшнов 15-20 ею пользуются. Легче обеспечить наследование чем на каждый из таких создавать свой var

2022-09-06 06:02 UTC, Furukia commented on paradise.dme
> +#include "_maps\cyberiad.dm"
Верну в норму со следующим коммитом. Впрочем у этого переключения карты смешная история. Давным-давно там стояла кибериада. Потом кто-то так же как я сделал коммит, но с дельтой и вот я переключая для тестов на кибериаду, забыла переключится обратно...

2022-09-06 06:10 UTC, Furukia commented on code/modules/ninja/suit/suit_attackby.dm
> +		else if(uranium_stack.amount >= a_transfer  && heal_available != TRUE)
У костюма есть две способности. Адреналин и лечение. Они отдельны друг от друга и имеют лишь 1 заряд. Заряд у обоих регенится с помощью урана этим кодом. Обе способности в обычных реалиях нельзя взять вместе. Поэтому уран потратится лишь в одном из if-ов.

а proc - toggle_ninja_action_active - ответственен за смену иконки способности на анимированный активный вариант.

2022-09-06 06:11 UTC, Furukia commented on code/modules/ninja/components/ninja_states_breaker.dm
> +/*
уберём

2022-09-06 06:15 UTC, Furukia commented on code/modules/mob/living/silicon/robot/robot.dm
> +/mob/living/silicon/robot/proc/spawn_syndicate_borgs(var/robot_to_spawn, turf/T)
А вот это я как то упустила... Между делом сделала изменения пока работала над ниндзя боргом, но потом вырезала код для него отсюда и сделала проще, сделав его совершенно новым видом саботёр борга. А эти мелкие правки - остались... Могу в целом и убрать их в отдельный коммит

2022-09-06 06:16 UTC, Furukia commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +	desc = "Used for \"emergencies,\" it actually contains a fair amount of oxygen. Looks kinda cool!"
Запятую перемещу...

2022-09-06 06:19 UTC, Furukia commented on tgui/packages/tgui/styles/components/Tooltip.scss
> +$color-title: #ffffff !default;
Упс... Забыла их убрать. Пыталась добавить заголовку в тултипе окраску и подчёркивание но не разобралась как и обошлась просто наличием заголовка... Уберу

2022-09-06 06:27 UTC, Furukia commented on code/modules/mining/equipment/survival_pod.dm
> -						/obj/item/katana/energy,
Я посмотрела подробнее, что это за штука. Этот генератор создаёт пустышку со скином предмета. Она кладётся в кейс на люксовой капсуле шахтёров. Так как старой катаны в принципе больше не существует - я могу туда пихнуть катану ниндзя. Всё равно будет пустышкой, аналогом.

2022-09-06 06:42 UTC, Furukia commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +/obj/item/tank/emergency_oxygen
Понятия не имею. Это не мой код, который гитхаб решил отметить как мой. Поиск показывает что этот тип баллона уникален. Я подозреваю, что это как то связано с этим пр-ом #997 
![image](https://user-images.githubusercontent.com/67807868/188563876-76fb1988-c897-4e6a-861a-23cf52f0e650.png)

UPD: Я тут глянула сам пр пупса... Этот тип там удалялся. Видимо во время конфликтов ребейза он вернулся уже ко мне... Грейт... Пофикшу.

2022-09-06 06:46 UTC, Furukia commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +	desc = "Used for emergencies. Contains very little oxygen, so try to conserve it until you actually need it. Looks kinda cool!"
поправлю

2022-09-06 06:47 UTC, Furukia commented on code/game/objects/items/weapons/explosives.dm
> +	var/boom_sizes = list(0, 0, 3)
А мне кажется через лист удобнее... Но я сделаю ладно.

2022-09-06 07:51 UTC, Furukia commented
> Часть ревью первая

Внесла правки. Стоит ли мне ждать вторую часть ревью?) 
![file_109358297](https://user-images.githubusercontent.com/67807868/188577809-40bd2f73-ecad-47f1-b29c-954872fcb9bf.png)

2022-09-07 22:52 UTC, semoro requested changes
Часть вторая ревью UwU

2022-09-07 22:52 UTC, semoro commented on code/datums/action.dm
> +	var/action_initialisation_text = null	//Space ninja abilities only
А можно сделать промежуточный тип, например `/datum/action/item_action/ninja_action` ?

2022-09-07 22:52 UTC, semoro commented on code/game/atoms.dm
> +	var/drain_act_protected = FALSE
А зачем казалось бы такое специальное прям в базовый атом?

2022-09-07 22:52 UTC, semoro commented on code/modules/mob/living/silicon/robot/robot.dm
> -						<b>Вас построили на ННКСС 'Тайпан' Помогайте персоналу станции и исполняйте их приказы. \
Тут кажется всё ещё табуляция отличается :(

2022-09-07 22:52 UTC, semoro commented on tgui/packages/tgui/styles/components/Tooltip.scss
> +    white-space: pre;
Замечу, что такое изменение будет иметь последствия для всех tooltip-ов в игре вообще, а именно включит для них whitespace preserve, что может попортить другие места где они используются
Альтернативным решением твой проблемы было бы использовать `<br>` в качестве разделителя между title и text

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +	occupant.loc = pick(GLOB.ninja_teleport)
телепортацию надо делать через forceMove, менять loc напрямую скорее всего не стоит

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +	occupant = null
Рекомендую выставлять occupant на null сразу после телепорта во избежание ситуации когда из-за рантайма в функциях выше ссылка не сбросилась

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +		if("test")
OwO?

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +	if(findtext("[possible_occupant.key]","@",1,2))
А зачем это нужно?

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +	if(..(user))
Кажется можно сделать проще и просто передать ниндзю в scan_occupant, а не сохранять его через attack_hand

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +		objective.scans_to_win = max(initial(objective.scans_to_win), round(GLOB.human_list.len/12))
Количество scans_to_win обновляется каждый раз, что вообще означает это число и почему human_list.len / 12?

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_teleporter.dm
> +				user.loc.loc.Exited(user)
Телепорт надо бы делать через forceMove, или есть причина почему тут так?

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +	for(var/datum/dna2/record/ninja_dna_record in records)
Мы каждый тик obj/machinery будем делать эту операцию, может быть небыстро

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +		if(!(ninja))
А что это значит и зачем нужно?

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +	var/mob/living/carbon/human/ninja
Кажется это можно сделать просто переменной внутри `revive_ninja`, тоже самое относится и к `clonemind`, т.к тебе надо передать в `CALLBACK` используй `addtimer(CALLBACK(src, .proc/force_ninja_out, ninja), 150)`

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +		detonation_objective = locate(/datum/objective/plant_explosive) in user.mind.objectives
А что случится если у нас будет более одного detonation objective?

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +		new_c4.detonation_objective = detonation_objective
А зачем тут переносить objective? вроде бы оно заново прочитается

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +	if(!check_loc(detonator)) // if its moved, deactivate the c4
А если detonator вдруг null?

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +	var/mob/living/carbon/human/detonator
Это точно weakref?

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/ninja_shuttle.dm
> +	bubble_icon = "syndibot"
А что это за такая иконка?

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/suit/glasses.dm
> +	var/obj/item/clothing/mask/gas/space_ninja/n_mask
А зачем тут ссылка на маску?

2022-09-07 22:52 UTC, semoro commented on code/game/gamemodes/spaceninja/ninja/suit/ninja_equipment_actions/ninja_clone.dm
> +		playsound(ninja, 'sound/effects/clone jutsu.ogg', 50, TRUE)
Пожалуйста названия файла без пробела

2022-09-08 17:45 UTC, Furukia commented on code/game/atoms.dm
> +	var/drain_act_protected = FALSE
Потому, что с помощью перчаток, ниндзя взаимодействует с множеством разных объектов, разных типов. Хотя сейчас там исключительно mob и obj. Но мне кажется сделать флаг защищающий от такого взаимодействия для потенциально любого объекта которому добавлено или может быть добавлено такое взаимодействие в будущем - не самая плохая идея. Плюс это даёт возможность админам и мапперам поменяв флаг - защитить АПЦ, СМЕСЫ и что угодно ещё от взломов ниндзя. 

Если же этот флаг отдельно добавлять каждому объекту - теряется эта гибкость. Да и никогда не знаешь может у нас потом ниндзя сможет какие-то особые стены взламывать и в список добавится и turf

Кстати это натолкнуло меня на мысль убрать проверку на z-lvl у дверей и просто двери в зоне ниндзя - защитить этим флагом...

2022-09-08 17:49 UTC, Furukia commented on tgui/packages/tgui/styles/components/Tooltip.scss
> +    white-space: pre;
Я специально проверяла множество других интерфейсов и искала тултипы. Все работают как и раньше. Само разделение заголовка и текста происходит в другом файле, посредством \n

2022-09-08 18:46 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +	if(findtext("[possible_occupant.key]","@",1,2))
Скопированный с клонёрки код для оповещения админа, что его тело поместили в эту машину пока он в агосте.

2022-09-08 18:49 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_teleporter.dm
> +				user.loc.loc.Exited(user)
Этот код я не меняла и просто перенесла клонёрку с одного места в другое. Перепишу

2022-09-08 18:58 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +	if(..(user))
Если просто убрать ниндзя. пропадёт валидация того, что цель записанная в скан машине- принадлежит тому самому ниндзя. Представь гипотетически что у нас два ниндзя с одной целью. Скан машина должна проверить есть ли у неё цель и совпадает ли записанный ниндзя с тем кто к ней обратился. Ибо если совпал - цель принадлежит тому ниндзя. Иначе же, цель записанная в скан машине не корректна для этого ниндзя и надо перезаписать для соответствия действительности.

2022-09-08 19:02 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +		objective.scans_to_win = max(initial(objective.scans_to_win), round(GLOB.human_list.len/12))
scans_to_win - сколько сканов нужно, чтобы выполнилась цель у ниндзя, если ему так и не удалось найти нужного человека.
human_list - потому что лист всех мобов огромен и выдаёт слишком большие цифры
/12 - потому, что я стремилась к формуле при которой примерно на 100 человек будет требоваться где-то 8 тел просканировать.

2022-09-08 19:05 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +		objective.scans_to_win = max(initial(objective.scans_to_win), round(GLOB.human_list.len/12))
К слову обновляется оно лишь когда регистрируется ниндзя в машине. Если ниндзя один - на каждую машину он лишь 1 раз обновит цифру. Если же ниндзя много, цифра будет обновляться когда они по очереди юзают машину. Большой проблемы в обновлении не вижу. Но можно сделать и чтобы обновлялась лишь раз... Но мне хочется чтобы она обновлялась именно машиной. Ибо тогда вместо раундстарт подсчёта, будет более реальный подсчёт людей на станции на момент когда ниндзя доберётся до машины.

2022-09-08 19:36 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +	for(var/datum/dna2/record/ninja_dna_record in records)
Ты про влияние на скорость игры? Я не очень уверена как тут поступить в таком случае. По факту он скипает весь этап процессинга если нет ни одной записи с данными ниндзя для его скана.

2022-09-08 19:42 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +		if(!(ninja))
Проверка есть ли у нас тело ниндзя в машине. Если есть - значит не надо заново запускать код. Впрочем я тут подумала вынести эту проверку НАД самим циклом, чтобы не пробегать его постоянно хотя бы если у нас есть тело.

2022-09-08 19:43 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +	var/mob/living/carbon/human/ninja
хмм...

2022-09-08 19:45 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +	var/mob/living/carbon/human/ninja
clonemind - проверяется так же в scan_mob()

2022-09-08 19:48 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +	var/mob/living/carbon/human/ninja
Так же как и тело ниндзя по факту проверяется в нескольких проках сразу. Не очень уверена, что есть смысл раскидывать его как локальную переменную каждому проку. Впрочем, если смысл есть. Расскажи подробнее почему и я сделаю.
![file_109357304](https://user-images.githubusercontent.com/67807868/189212571-1242266e-88b4-42b4-a164-1ba13d9b97e0.png)

2022-09-08 20:55 UTC, Furukia commented on code/modules/mob/living/silicon/robot/robot.dm
> -						<b>Вас построили на ННКСС 'Тайпан' Помогайте персоналу станции и исполняйте их приказы. \
поправлю

2022-09-08 20:56 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +	occupant.loc = pick(GLOB.ninja_teleport)
поправлю

2022-09-08 20:56 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +	occupant = null
ок

2022-09-08 20:56 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +		if("test")
тест удалю...

2022-09-08 20:57 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +	if(..(user))
Пока не меняю ничего тут.

2022-09-08 20:57 UTC, Furukia commented on code/game/atoms.dm
> +	var/drain_act_protected = FALSE
Пока не меняю ничего тут.

2022-09-08 20:57 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_mindscan_machine.dm
> +		objective.scans_to_win = max(initial(objective.scans_to_win), round(GLOB.human_list.len/12))
Пока не меняю ничего тут.

2022-09-08 20:59 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +		if(!(ninja))
Перенесу if на строку выше в году капельки эффективности.

2022-09-08 20:59 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +	var/mob/living/carbon/human/ninja
Пока не меняю ничего тут.

2022-09-08 21:37 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +		detonation_objective = locate(/datum/objective/plant_explosive) in user.mind.objectives
По идее просто первая найденная такая целька выдастся. Обычно когда создаётся бомба - обджектив записывается в бомбу там же где создаётся бомба. По факту искореняя такую проблему. Впрочем я тут поняла, что в другом коде выдачи цели через админ кнопки у меня стоит ограничение не спавнящее бомбу, если уже есть бомба. Пожалуй я его уберу. Чтобы могли создать много целей на подрыв - админ кнопками. 

Без админ кнопок - больше одной цели на подрыв, ниндзя не получит.

2022-09-08 21:51 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +		new_c4.detonation_objective = detonation_objective
Да она возьмётся заново в коде check_loc, но тот код - скорее аварийная попытка починить бомбу, если у неё нету цели. В общем - считаю лучше вручную передать, а не прибегать к аварийке.

2022-09-08 21:54 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +	if(!check_loc(detonator)) // if its moved, deactivate the c4
Перемещу проверку на детонатора и цель выше этой проверки. Странно что она лежит ниже...

2022-09-08 21:56 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +	var/mob/living/carbon/human/detonator
Ну... Тут мне нечего добавить. Код переносился с ТГ и модифицировался, но коммент остался как есть. Честно понятия не имею. Я просто уберу комментарий вызывающий путаницу.

2022-09-08 21:59 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/ninja_shuttle.dm
> +	bubble_icon = "syndibot"
Когда компьютер говорит что-то, например "ШАТЛ ВЫЛЕТЕЛ ТУДА ТО". У него появляется иконка как около моба когда он пишет текст. Это скин этой иконки.

2022-09-08 22:00 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/suit/glasses.dm
> +	var/obj/item/clothing/mask/gas/space_ninja/n_mask
Очки при смене режима обновляют скин как себе, так и маске. Это помогает сб да и самому ниндзя видеть на кукле в каком режиме визор ниндзя.

2022-09-08 22:00 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/suit/glasses.dm
> +	var/obj/item/clothing/mask/gas/space_ninja/n_mask
И выглядит стильно, да.

2022-09-08 22:01 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/suit/ninja_equipment_actions/ninja_clone.dm
> +		playsound(ninja, 'sound/effects/clone jutsu.ogg', 50, TRUE)
Окей

2022-09-08 22:33 UTC, Furukia commented
> Часть вторая ревью UwU

Жду третью часть. Ну и надо бы наверное обсудить, те вещи которые я не закрыла. Дабы понять - менять ли их или лучше не стоит.
![file_109358318](https://user-images.githubusercontent.com/67807868/189237451-a001647a-f82d-40ce-bbce-feee30fd2c1a.png)

2022-09-08 22:34 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/machinery/ninja_cloning.dm
> +	for(var/datum/dna2/record/ninja_dna_record in records)
Перенесла со строчки ниже if на строку выше в угоду капельки эффективности.

2022-09-09 18:50 UTC, Bizzonium commented
Мержится на прайм для игрового теста. Жду дальнейшие правки и фиксы по мере нахождения.

2022-09-09 18:52 UTC, Furukia commented
> Мержится на прайм для игрового теста. Жду дальнейшие правки и фиксы по мере нахождения.

Добавь так же в конфиги. Thank you.
PROBABILITY SPACE-NINJA 2
MINPLAYERS SPACE-NINJA 25

2022-09-09 19:00 UTC, merged