Feat: Разум для обезьян
ss220-space/Paradise pull request #1276
Opened 2022-08-31 12:20 UTC by PhantornRU

## What Does This PR Do
- Зелье разума дает разум обезьянам и прицепляет их к хозяину
- Обезьяны ограничены в умственных способностях, когда они становятся разумными через зелья.
- Низшие РАЗУМНЫЕ формы получили возможность понимать человеческую речь
- Зелья разума на животных, теперь вносят памятки в их имена кому они служат
- Становление петов теперь логируется, кто их сделал.
- Превращение магом в мартышку - позволяет помнить прошлую жизнь.
- Небольшой рефактор и вынос макак и низших форм в отдельный файл.

## Why It's Good For The Game
- Новые возможности для РП и путей выполнения задач со стороны Антагов. Но они по прежнему не могут лазать по вентиляциям с предметами.
- Ксенобиология теперь может делать не только рабов-големов, но и мартых.
- Мартыхи имеют хозяина и не могут по своей воле дебоширить.
- Ape. Together. Strong.
- Можно устраивать обезьяньи нелегальные подпольные бои.

## Images of changes
![image](https://user-images.githubusercontent.com/41479614/187676760-5a01bf9e-9a50-43a5-a93b-30a900fd4f78.png)
Было также протестировано с разными клиентами на локалке, но скриншоты к сожалению не сделал. Всё стабильно работает.

2022-08-31 18:26 UTC, larentoun commented on code/modules/mob/living/carbon/human/species/monkey.dm
> +	language = "Galactic Common"	//бореры теперь "не забывают" всегалактический, а разумные мартышки понимают что им говорят. Они по прежнему общаются на обезьянем/фарванском
POG

2022-08-31 18:28 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +		var/mob/living/simple_animal/SM = M
Это SuperMonkey, или SimpleMob? КЫК

2022-08-31 18:30 UTC, larentoun requested changes

2022-08-31 18:30 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(candidates.len)
Ну ПУПС, есть же невероятное length()

2022-08-31 18:30 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +		var/mob/living/simple_animal/SM = M
А все-таки ревью оставлю, что за SM то? SuperMonkey? SimpleMob не подходит

2022-08-31 18:30 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +		var/mob/living/carbon/human/monkey/LF = M
LesserForm? LowFricks?

2022-08-31 18:30 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(candidates.len)
length()

2022-09-01 01:46 UTC, PhantornRU commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(candidates.len)
Оставил оригинальный код pepeChill, чтобы не было разнобойности

2022-09-01 01:46 UTC, PhantornRU commented on code/modules/research/xenobiology/xenobiology.dm
> +		var/mob/living/carbon/human/monkey/LF = M
LesserForm

2022-09-01 01:47 UTC, PhantornRU commented on code/modules/research/xenobiology/xenobiology.dm
> +		var/mob/living/simple_animal/SM = M
Это и есть SimpleMob

2022-09-01 13:47 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +		var/mob/living/simple_animal/SM = M
А, точно, я то думала это уже для макак

2022-09-01 15:52 UTC, PhantornRU commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(candidates.len)
Это проверка на "не нулевость". len для этого и нужна, она возвращает значение FALSE при NULL.
length() в данном случае будет делать тоже самое, только больше буковок будет написано. Оба эти значения возвращают нули, если списки будут пусты. Если нет, то продолжают работу.
поэтому шо так, шо так. Но в нашем случае в ДМе принято использоваться именно что .len
Да и мне так удобнее сразу у объекты вызывать нужные внутренние функции, а не притягивать сторонние функции.

2022-09-01 15:52 UTC, PhantornRU commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(candidates.len)
Это проверка на "не нулевость". len для этого и нужна, она возвращает значение FALSE при NULL.
length() в данном случае будет делать тоже самое, только больше буковок будет написано. Оба эти значения возвращают нули, если списки будут пусты. Если нет, то продолжают работу.
поэтому шо так, шо так. Но в нашем случае в ДМе принято использоваться именно что .len
Да и мне так удобнее сразу у объекты вызывать нужные внутренние функции, а не притягивать сторонние функции.

2022-09-01 15:59 UTC, PhantornRU commented
@Bizzonium Авоут был пройден.
https://discord.com/channels/617003227182792704/755125334097133628/1014916202784620694

2022-09-01 16:00 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(candidates.len)
Валлат (как и ТГшники) переехали на length(). Считается новым стандартом

2022-09-21 14:30 UTC, larentoun requested changes

2022-09-21 14:30 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/slime.dm
> +	var/rename = FALSE //если слайм был заранее переименован
лучше как глагол, "renamed"

2022-09-23 00:29 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/slime/slime.dm
> +	var/rename = FALSE //если слайм был заранее переименован
точно-точно

2022-09-23 00:33 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/slime/slime.dm
> +	var/rename = FALSE //если слайм был заранее переименован
Переименовал

2022-09-23 09:27 UTC, larentoun requested changes

2022-09-23 09:27 UTC, larentoun commented on code/modules/mob/living/carbon/human/species/monkey.dm
> +	//no_equip = null
Аа? Зачем этот коммент?

2022-09-23 09:27 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(candidates.len)
Тут вполне вероятна возможность рантайма в виде `null.len`, замени на length()

2022-09-23 09:27 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +			..()
Точно не нужен `return ..()`?

2022-09-23 09:27 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(candidates.len)
Опасность `null.len`

2022-09-23 09:27 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(candidates.len)
![image](https://user-images.githubusercontent.com/31931237/191931012-d8d5ee6c-cc84-4c12-9ff7-6ee5f19dfac0.png)
Если что, `.len` дает рантайм, если ему дают нулл. Поэтому я говорю использовать `length()`
![image](https://user-images.githubusercontent.com/31931237/191931168-497fbe66-4d59-41f4-8db5-7c72cce65c54.png)

2022-09-23 09:27 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +			..()
Точно не нужен `return ..()`?

2022-09-23 10:42 UTC, PhantornRU commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(candidates.len)
Ты прав, ты прав

2022-09-23 11:23 UTC, PhantornRU commented on code/modules/research/xenobiology/xenobiology.dm
> +			..()
тогда уж . = ..()
Но это оригинальный код. Здесь нужно же просто глухое проигрывание

2022-09-23 11:24 UTC, PhantornRU commented on code/modules/research/xenobiology/xenobiology.dm
> +			..()
Внёс правку на . = ..()

2022-09-23 11:29 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +			..()
> тогда уж . = ..() Но это оригинальный код. Здесь нужно же просто глухое проигрывание

Ну, я не читала, откуда оно берет ноги, просто спрашиваю)

2022-09-23 11:30 UTC, larentoun approved these changes

2022-09-26 14:27 UTC, PhantornRU commented
@Dimach а этот еще более древнее

2022-09-27 10:43 UTC, PhantornRU commented
@Dimach мерж конфликт решен

2022-09-28 02:03 UTC, PhantornRU commented
@Dimach конфликт вновь решен

2022-10-01 10:27 UTC, PhantornRU commented
Интересный факт, прошел целый месяц ожидания мержа разума для манки.

2022-10-02 20:27 UTC, larentoun commented
Интересный факт, снова конфликты

2022-10-03 05:16 UTC, PhantornRU commented
> Интересный факт, снова конфликты

:(

2022-10-04 04:32 UTC, merged