Port: Trans-Solar Federation
ss220-space/Paradise pull request #1277
Opened 2022-08-31 13:49 UTC by frikadeliSpaghetti

Порт солдатов и генерала ТСФ с оффов. Перенес всё их снаряжение к нам.
Добавил иконку для сб худа новую. Перенес шапки, одежду, рюкзаки и риги. В игре всё неплохо выглядит. Осталось подождать пока одобрят.
![solgov](https://user-images.githubusercontent.com/48985748/187693573-c36bec7c-6a31-4653-94e4-17209d03ee4f.png)

2022-09-07 05:20 UTC, BeebBeebBoob reviewed
Предполагаю что делать по карте ничего не будешь? Ни базы своей вот у СолГов ни возможность админам спавниться из лобби за него.

2022-09-07 05:20 UTC, BeebBeebBoob commented on code/modules/newscaster/obj/newscaster.dm
> +			/datum/job/ntspecops/solgovspecops,
А я вот боюсь что будут проблемы везде где ты так сделал.
Не знаю под чистую скопировал смотреть как это подтип того что уже подтип страшна

```suggestion
			/datum/job/solgovspecops,
```

2022-09-10 12:49 UTC, frikadeliSpaghetti commented on code/modules/newscaster/obj/newscaster.dm
> +			/datum/job/ntspecops/solgovspecops,
Это у оффов так. У них проблем не возникло, у нас тоже не должно

2022-09-11 12:19 UTC, BeebBeebBoob requested changes
Также "Не относится к ПР." некоторые dmi изменения и .ogg

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/datums/ai_law_sets.dm
> -	default = TRUE
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/datums/ai_law_sets.dm
> -	default = TRUE
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/game/turfs/simulated.dm
> -	var/mob/living/simple_animal/hulk/Hulk = A
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/game/turfs/simulated.dm
> +	if(istype(A, /mob/living/simple_animal/hostile/shitcur_goblin))
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/modules/admin/admin_verbs.dm
> +		ptypes += "Shitcurity Goblin"
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/modules/admin/admin_verbs.dm
> +			logmsg = "shitcurity goblin"
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/modules/admin/topic.dm
> -
Не относится к ПР.
Да, потому что даже отступы могут быть полезны когда работают другие кодеры и это может вызвать у других конфликты. Вот твой ПР это про СолГов.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/modules/mob/living/silicon/ai/say.dm
> +		addtimer(CALLBACK(GLOBAL_PROC, .proc/play_vox_word, word, src.z, null), i, TIMER_CLIENT_TIME)
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/modules/mob/living/silicon/pai/pai.dm
> +		"Espeon" = "pAIkemon_Espeon"
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
> +
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/modules/mob/living/simple_animal/hostile/shitcur_goblin.dm
> +/mob/living/simple_animal/hostile/shitcur_goblin
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/modules/ruins/objects_and_mobs/necropolis_gate.dm
> +	var/legion_triggered = FALSE
Не относится к ПР.

2022-09-11 12:19 UTC, BeebBeebBoob commented on code/modules/ruins/objects_and_mobs/necropolis_gate.dm
> +	GLOB.necropolis_gate.legion_triggered = TRUE
Не относится к ПР.

2022-09-11 12:20 UTC, BeebBeebBoob commented
icons/mob/shitkur_v6.dmi (0)
icons/obj/objects.dmi (0)
icons/mob/inhands/items_righthand.dmi (0)
icons/mob/head.dmi (0) (там ratge и другие)
icons/mob/inhands/items_lefthand.dmi (0)
icons/mob/pai.dmi (0)

2022-09-11 12:44 UTC, frikadeliSpaghetti commented
Пересоздам лучше

2022-09-11 12:44 UTC, closed without merging