Headcrab rework
ss220-space/Paradise pull request #1278
Opened 2022-08-31 16:50 UTC by Robustin4

## What Does This PR Do
Реворк хедкрабов. Теперь они что-то вроде мидраунд антагонистов, гоняют по вентам, их логова теперь спавнятся по всей станции, можно брать под контроль, макаки теперь тоже могут быть зомби (баг был у меня только или всегда он был). ((в коде лежат еще два хедкраба, но для них нет спрайтов, да и я их сделал))

## Why It's Good For The Game
Новая угроза станции.

2022-08-31 18:23 UTC, larentoun requested changes

2022-08-31 18:23 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +	var/c = rand(2,4)
Что за невероятное "c"

2022-08-31 18:23 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +		var/turf/simulated/floor/T = pick(availableareas)
Что за невероятное "T"

2022-08-31 18:23 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +		for(var/obj/structure/spawner/headcrab/he in world)
he-who?

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +			to_chat(src, "Maybe you will try to kill humans for bodys for your little brothers?")
bodys -> bodies

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		var/datum/mind/M = create_headcrab_mind(candidate.ckey)
Невероятное M, почему не user, к примеру

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/proc/create_headcrab_mind(key)
А точно нужен глобальный прок для этого?

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(is_zombie)
А почему бы не убирать этот прок у зомби?

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +
Лишние пробелы можно было бы и убрать

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(!ai)
AI, в плане, станционный? Если ИИ игровой, то почему бы не дать просто проверку на клиента?

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		var/turf/T2 = get_turf(src) //как тебе такое, волмат? двухбуквенная переменная!
Очень не очень

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		if(istype(loc, /turf))
isturf()

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +			for(var/obj/machinery/atmospherics/unary/vent_pump/v in view(4,src))
Внизу ты же сделал temp_vent, почему тут просто невероятная v?

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +				visible_message("<B>[src] scrambles into the ventilation ducts!</B>", \
Точно visible, а не audible?

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	obj_damage += 40
+=? Точно следует добавлять это условие? Хедкраб помогает ручками ломать объекты?

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	to_chat(src, "No ventcrawling now (if you are not monkey and etc). But more health.")
Можно было добавить с условием с проверкой на ventrcrawling

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	obj_damage += 40
тоже самое, что выше

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(. && neurotoxin_per_jump > 0 && iscarbon(target) && target.reagents && !is_zombie)
Так neurotoxin_per_jump используется только тут, верно? Зачем ее пихать в hostile/headcrab, а не только в hostile/headcrab/poison?

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		for(var/mob/living/carbon/human/H in oview(src, 4)) //Only for carbons on poison headcrab jumping distance
Как много внизу однобуквенных переменных. Кто кого убивает? Кто жертва, кто нападающий?

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	desc = "A strange parasitic creature that would like to connect with your brain stem through your upper body. It's looks like, that it can shock you."
It's looks like -> It looks like

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
А это точно нужно, если в начале уже есть .=..()?

2022-08-31 18:23 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	return ..()
нет новой строки в конце файла, и зачем return ..()?

2022-08-31 18:47 UTC, Robustin4 commented
Ладно, спасибо, вправлю код, когда будет время.

2022-09-01 01:24 UTC, PhantornRU commented
Не называй так коммиты. Можешь хоть сотню повторов того чего делаешь вписывать. Но хуевые названия коммитов - признак плохого тона.
![image](https://user-images.githubusercontent.com/41479614/187812467-ed58685b-05ee-4541-a9b5-b07b2c36e3d8.png)

2022-09-01 15:45 UTC, PhantornRU commented
@Robustin4 то что ты сделал по запросам - внизу нажимаешь:
![image](https://user-images.githubusercontent.com/41479614/187956846-21152ccb-15db-4b4b-b381-45dbe88a82b8.png)

2022-09-01 22:18 UTC, larentoun requested changes

2022-09-01 22:18 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		if(src.poison_headcrabs != 0 && src.is_zombie) //игрок кидаться может всегда, а ИИ лишь с шансом.
Проверка is_zombie выше уже есть

2022-09-05 02:11 UTC, PhantornRU reviewed
Ну йобобаны.  Ну непонятно ж из таких коммитов что было сделано.
![image](https://user-images.githubusercontent.com/41479614/188346528-3b7c36f0-0401-41b4-958f-0a1e3b9b46a2.png)

2022-09-07 16:21 UTC, larentoun requested changes

2022-09-07 16:21 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	ranged_message = "бросается"
Перевод запрещен

2022-09-07 16:21 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		ranged_message = "блюет"
Перевод запрещен

2022-09-07 16:21 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	visible_message("<span class='danger'><b>[src]</b> [ranged_message] на [A]!</span>")
Перевод запрещен, особенно без склонений!

2022-09-07 16:21 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	headcrab.revive_cooldown += 30
end of line есть?

2022-09-07 16:56 UTC, larentoun requested changes

2022-09-07 16:56 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		ranged_message = "puking"
pukes?

2022-09-07 17:04 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		ranged_message = "puking"
![image](https://user-images.githubusercontent.com/111193615/188937772-7c598d73-728b-4a67-b3c9-1d72f23cbd2c.png)

2022-09-10 19:14 UTC, larentoun requested changes

2022-09-10 19:14 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +	while(turfs.len > 0 && how_many_capsules > 0)
length(turfs) использовать лучше

2022-09-10 19:14 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +		//explosion(where_capsule, 0.2, 0.2,0.2) // взрыв все ломает. пожалуй откажемся
А вы зачем ставите деци-значения, если это радиус в тайлах?

2022-09-10 19:14 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +			var/mob/M = P
Можно было и нормальное название переменной

2022-09-10 19:14 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +/datum/event/crabmissiles/proc/headcrabs_release(var/mob/living/simple_animal/hostile/headcrab/headcrab_type, var/obj/structure/crabmissile/capsule, var/randomized_headcrabs/*, var/admin_log*/)
Зачем оставлять комментированный код?

2022-09-10 19:14 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +	//выдает ошибку про координаты. отказался.
Опять, ненужный комментированный код

2022-09-10 19:14 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +		sleep(40)
А не хотите использовать addtimer. Они более оптимизированы

2022-09-10 19:14 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +		new/obj/structure/spawner/headcrab/(nest_position)
А тут точно нормально описан new?

2022-09-10 19:14 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +	//GLOB.event_announcement.Announce("Внимание, [station_name()]. Было зафиксировано приближение к вам [how_many_capsules == 1 ? "[how_many_capsules]" : " "] [how_many_capsules == 1 ? "капсулы" : "кап
Комментированный код

2022-09-10 19:14 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +#undef HEADCRAB_SPAWNER
Убрал EOL? Или как?

2022-09-10 19:14 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	var/is_gonarch = 1 // кажется уже какой-то спагетти код, прямо как писал американец ниже.
TRUE/FALSE может лучше?

2022-09-10 19:14 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	attacktext = "пронзает"
Перевод запрещен

2022-09-10 19:14 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		TOOL_DISMANTLE_SUCCESS_MESSAGE
EOL есть?

2022-09-10 19:28 UTC, Robustin4 commented on code/modules/events/headcrabs.dm
> +		//explosion(where_capsule, 0.2, 0.2,0.2) // взрыв все ломает. пожалуй откажемся
не разбираюсь в взрывах.

2022-09-10 19:29 UTC, Robustin4 commented on code/modules/events/headcrabs.dm
> +/datum/event/crabmissiles/proc/headcrabs_release(var/mob/living/simple_animal/hostile/headcrab/headcrab_type, var/obj/structure/crabmissile/capsule, var/randomized_headcrabs/*, var/admin_log*/)
да так, на будущее

2022-09-10 19:30 UTC, Robustin4 commented on code/modules/events/headcrabs.dm
> +#undef HEADCRAB_SPAWNER
почему-то ругается

2022-09-10 19:31 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	attacktext = "пронзает"
странно, хедкрабы attacktext хедкрабов переведен, почему бы не продолжить традицию?

2022-09-10 19:31 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		TOOL_DISMANTLE_SUCCESS_MESSAGE
есть

2022-09-10 19:41 UTC, Robustin4 commented on code/modules/events/headcrabs.dm
> +		sleep(40)
я не совсем понимаю принцип его работы

2022-09-10 19:46 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	attacktext = "пронзает"
Отмени перевод

2022-09-10 19:46 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +		//explosion(where_capsule, 0.2, 0.2,0.2) // взрыв все ломает. пожалуй откажемся
Ну и ладненько. Просто на будущее - цифорки это в тайлах. Радиус гиба, сильный, слабый.

2022-09-10 19:47 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +		sleep(40)
Вызывает прок через время

2022-09-10 19:59 UTC, Robustin4 commented on code/modules/events/headcrabs.dm
> +		sleep(40)
я не понял как же его вызвать необходимое количество раз...

2022-09-10 21:07 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +		new /obj/structure/spawner/headcrab/(nest_position)
Компилится то проект? По-моему не должно быть `/` в headcrab/(nest_position)

2022-09-10 21:07 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	attacktext = "pierces" //по просьбе ларентоун отменил перевод. вообще не логично, это я создал этого моба, и я по-русски написал его аттак текст. где перевод? я вообще мог подшутить и оставить насле
Я писала про то, чтобы откатывать перевод (еще неделю назад, наверное, когда там ревью были), и там вроде откатывал?

2022-09-10 21:08 UTC, Robustin4 commented on code/modules/events/headcrabs.dm
> +		new /obj/structure/spawner/headcrab/(nest_position)
компилируется.

2022-09-10 21:10 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	attacktext = "pierces" //по просьбе ларентоун отменил перевод. вообще не логично, это я создал этого моба, и я по-русски написал его аттак текст. где перевод? я вообще мог подшутить и оставить насле
Перевод запрещен. Ладно.

2022-09-16 15:21 UTC, larentoun commented
О, тебе линтеры включили. Почитай, там две ошибки

2022-09-16 18:09 UTC, Robustin4 commented
И как решить этот линтер? Я же с базой данных никак не контактировал...

2022-09-16 20:44 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		ranged_cooldown_time = 666
Минута? Ничего не перепутал?

2022-09-16 20:45 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		C.adjustStaminaLoss(5) //stuncrab
5 урона по стамине до 100 нужных?

2022-09-16 21:50 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		C.adjustStaminaLoss(2) //stuncrab
Я про то, что нужно 100 стамина урона, чтобы довести до стаминакрита... А приписка stuncrab говорит о том, что он должен быть эффективным станящим, нет? 50 ударов по стамине, ух

2022-09-16 22:10 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		C.adjustStaminaLoss(2) //stuncrab
Ну если я поставлю большое значение - дисбаланс
Что нибудь придумаю.

2022-09-16 22:13 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		C.adjustStaminaLoss(2) //stuncrab
У нас в среднем 3-4 удара на стан (3 без брони, 4 с броней), плюс-минус 35 урона по стамине.

2022-09-16 22:14 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		C.adjustStaminaLoss(2) //stuncrab
Ну это уже решать тебе/через педальсостав/по желанию левой пятки, но я всё еще прослежу, чтобы не было слишком сильно/слабо

2022-09-29 18:00 UTC, larentoun requested changes

2022-09-29 18:00 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +var/global/hctypes = "/mob/living/simple_animal/hostile/headcrab, /mob/living/simple_animal/hostile/headcrab/fast, /mob/living/simple_animal/hostile/headcrab/poison"
Глобальные переменные определяются через GLOB.

2022-09-29 18:04 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +var/global/hctypes = "/mob/living/simple_animal/hostile/headcrab, /mob/living/simple_animal/hostile/headcrab/fast, /mob/living/simple_animal/hostile/headcrab/poison"
а что не так через var/global/ ?

2022-09-29 18:54 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +var/global/hctypes = "/mob/living/simple_animal/hostile/headcrab, /mob/living/simple_animal/hostile/headcrab/fast, /mob/living/simple_animal/hostile/headcrab/poison"
> а что не так через var/global/ ?

var/global/ это не глобальная переменная. Советую почитать contributing.md

2022-10-03 17:33 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	var/mob/living/simple_animal/hostile/headcrab/headcrabb = new src(death_loc) //уподобление оригиналу, этот вид хедкраба должен быть убит вне тела.
headcrab`b`?

2022-10-14 20:52 UTC, larentoun requested changes

2022-10-14 20:52 UTC, larentoun commented on code/datums/ruins/lavaland.dm
> +	//always_place = TRUE // tests
Надеюсь, потом уберешь

2022-10-14 20:52 UTC, larentoun commented on code/game/objects/items/devices/scanners.dm
> +	if(H.reagents.has_reagent("headcrab_neurotoxin"))
А нам точно такое нужно? Это же просто токсин, нет?

2022-10-14 20:52 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +	if(!candidates.len)
```suggestion
	if(!length(candidates))
```

2022-10-14 20:52 UTC, larentoun commented on code/modules/events/headcrabs.dm
> +==================================
Можно убрать?

2022-10-14 20:52 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/mob/living/simple_animal/hostile/headcrab/Move(atom/newloc, dir, step_x, step_y)
А зачем пустой прок?

2022-10-14 20:52 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	to_chat(src, "<span class=notice'>You are [infest ? "toggled" : "disabled" ] infestation of body.</span>")
```suggestion
	to_chat(src, "<span class=notice'>You have [infest ? "toggled" : "disabled" ] infestation of body.</span>")
```

2022-10-14 20:52 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
Уверен, что не нужно возвращать?

2022-10-14 20:52 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	src.verbs += /mob/living/verb/pulled
А ты его где-то меняешь? Ответь тут

2022-10-14 20:52 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(ismonkeybasic(H) || isfarwa(H) || iswolpin(H) || isneara(H) || isstok(H))
Не нужно сравнение с `host_species`? Если не нужно, зачем тебе переменная `host_species`?

2022-10-14 20:52 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
>  		victim.adjustToxLoss(rand(2,8))
Что за `victim`?

2022-10-14 20:52 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	var/newname = "fast [name]"
А переменная точно нужна?

2022-10-14 20:52 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	damage_coeff = list(BRUTE = 0.88, BURN = 0.88, TOX = 1, CLONE = 1, STAMINA = 0, OXY = 1)
Уточнять `= 1` обязательно?

2022-10-14 20:52 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance))
У тебя дважды может эмоция проиграться. Сделай список и из него `pick()`

2022-10-14 20:52 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance))
Тут вообще ужас всё, что ниже. Подсмотри, как у зависимостей шанс работает и проки на различные эффекты

2022-10-14 21:42 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/mob/living/simple_animal/hostile/headcrab/Move(atom/newloc, dir, step_x, step_y)
Судя по твоему фиксу хождения серого паука ужаса по диагонали через стекла - этот прок нужен

2022-10-14 21:42 UTC, Robustin4 commented on code/modules/events/headcrabs.dm
> +==================================
Как будет время за компьютером

2022-10-14 21:43 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	src.verbs += /mob/living/verb/pulled
Кого? Где?

2022-10-14 21:43 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(ismonkeybasic(H) || isfarwa(H) || iswolpin(H) || isneara(H) || isstok(H))
Для иконок. С host_species что то не работало

2022-10-14 21:43 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
>  		victim.adjustToxLoss(rand(2,8))
Жертва

2022-10-14 21:43 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	var/newname = "fast [name]"
Да.

2022-10-14 21:44 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	damage_coeff = list(BRUTE = 0.88, BURN = 0.88, TOX = 1, CLONE = 1, STAMINA = 0, OXY = 1)
Из-за этого краб становится неуязвимым к другим источникам урона

2022-10-14 21:44 UTC, Robustin4 commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance))
И так сойдёт

2022-10-14 21:44 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
Ну без возвращения нормально работает

2022-10-14 22:34 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	src.verbs += /mob/living/verb/pulled
`src.verbs += /mob/living/verb/pulled`

2022-10-15 14:55 UTC, Robustin4 commented on code/datums/ruins/lavaland.dm
> +	//always_place = TRUE // tests
я тестировал ранее, потом закомментировал, думаю убирать ничего не надо

2022-10-15 14:56 UTC, Robustin4 commented on code/game/objects/items/devices/scanners.dm
> +	if(H.reagents.has_reagent("headcrab_neurotoxin"))
Идем к оригиналу: этот нейротоксин понижал здоровье героя до 10 или 1, затем вводилось противоядие, думаю медсканер не так уж и далеко уйдет от костюма Гордона, причем токсин довольно опасен

2022-10-15 14:57 UTC, Robustin4 commented on code/modules/events/headcrabs.dm
> +	if(!candidates.len)
Не вижу разницы, но сделаю

2022-10-15 14:59 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	src.verbs += /mob/living/verb/pulled
/mob/living/simple_animal/hostile/headcrab/New()

 ...
 
 	if(!is_zombie)
		verbs -= /mob/living/verb/pulled

2022-10-15 20:10 UTC, larentoun commented on code/datums/ruins/lavaland.dm
> +	//always_place = TRUE // tests
Лишние комментарии в коде - плохо. Кому надо, тот сам вернет

2022-10-15 20:11 UTC, larentoun commented on code/game/objects/items/devices/scanners.dm
> +	if(H.reagents.has_reagent("headcrab_neurotoxin"))
Может оформишь его как вирус, как вариант? Как раз поддержка есть всего этого.

2022-10-15 20:13 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/mob/living/simple_animal/hostile/headcrab/Move(atom/newloc, dir, step_x, step_y)
А, ну, если у хостайлов/симплов прок Мува имеет другие переменные, тогда могло быть и ладно, НО!
![image](https://user-images.githubusercontent.com/31931237/196005899-54082109-6b22-43be-ae93-6c6ef17dbc1e.png)
Я глянул - у хостайлов ровно такой же прок. Вывод: по идее лишнее и ничего не меняет

2022-10-15 20:15 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
Глянул в коде, ты обязан вернуть родителя, так как он используется как минимум в калькуляции урона

2022-10-15 20:16 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(ismonkeybasic(H) || isfarwa(H) || iswolpin(H) || isneara(H) || isstok(H))
Тогда убери `host_species`

2022-10-15 20:16 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
>  		victim.adjustToxLoss(rand(2,8))
Бл- Кхм... Зачем она тут, почему у две разные переменные означают одно и тоже?

2022-10-15 20:18 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	damage_coeff = list(BRUTE = 0.88, BURN = 0.88, TOX = 1, CLONE = 1, STAMINA = 0, OXY = 1)
А, ну да, всё верно.
Тебе стоило сделать
```suggestion
	damage_coeff[BRUTE] = 0.88
	damage_coeff[BURN] = 0.88
```

2022-10-15 20:19 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance))
> И так сойдёт

Не сойдет, просто тяжести зафиксируй

2022-10-15 20:20 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance) + 3.2)
Что за невероятные 3.2? У тебя 100% будут играться эмоции

2022-10-15 20:33 UTC, Robustin4 commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance) + 3.2)
а вот такие, 6.8 + 3.2

2022-10-15 21:23 UTC, Robustin4 commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance))
что как

2022-10-15 21:24 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
>  		victim.adjustToxLoss(rand(2,8))
А хрен его знает, поправлю, когда будет возможность.

2022-10-15 21:25 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(ismonkeybasic(H) || isfarwa(H) || iswolpin(H) || isneara(H) || isstok(H))
Проверка иконок зомби все равно требует host_species. Оставляем.

2022-10-15 21:25 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
Ладно, выпущу его с родительского собрания

2022-10-15 21:26 UTC, Robustin4 commented on code/datums/ruins/lavaland.dm
> +	//always_place = TRUE // tests
ладна

2022-10-15 21:26 UTC, Robustin4 commented on code/game/objects/items/devices/scanners.dm
> +	if(H.reagents.has_reagent("headcrab_neurotoxin"))
ммммм хороша идея

2022-10-15 21:45 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance) + 3.2)
Ты знаешь, как работает условие if?

2022-10-15 21:46 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance))
Я же сказал - посмотри пример с зависимостей

2022-10-16 12:04 UTC, Robustin4 commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance) + 3.2)
Ну дааааааа

2022-10-16 12:04 UTC, Robustin4 commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +	if(prob(chance))
Ладно

2022-10-16 14:48 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
>  		victim.adjustToxLoss(rand(2,8))
А, понял в чем причина твоего негодования... Ну... Э.. Мне с target я хоть уверен, что нейротоксин будет в организме карбона, victim меня раньше подводил

2022-10-16 14:50 UTC, Robustin4 commented on code/game/objects/items/devices/scanners.dm
> +	if(H.reagents.has_reagent("headcrab_neurotoxin"))
Вот только вирусом... Он будет постоянным, а у нас нейротоксин, чье действие можно легко остановить, и лишь когда он в организме.

2022-10-16 14:58 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	damage_coeff = list(BRUTE = 0.88, BURN = 0.88, TOX = 1, CLONE = 1, STAMINA = 0, OXY = 1)
code\modules\mob\living\simple_animal\hostile\headcrab.dm:667:error: damage_coeff: left-hand side must be an object variable

2022-10-17 19:51 UTC, larentoun requested changes

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/mob/living/simple_animal/hostile/headcrab/attack_hand(mob/living/carbon/human/M as mob)
as mob не нужен

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
Зачем ты дважды вызываешь родителя?

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +
лишний пробел

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
зачем ты дважды вызываешь родителя

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/obj/item/reagent_containers/food/snacks/headcrab/attack(mob/M, mob/user, def_zone)
Что за `mob/M`?

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
Уверен, что сначала нужно вызвать родителя?

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +			to_chat(user, "<span class='notice'>His armor was breaked! Time to eat!</span>")
```suggestion
			to_chat(user, "<span class='notice'>His armor is now broken! Time to eat!</span>")
```

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
Точно нужно вызывать родителя сначала?

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		to_chat(M, "<span class='notice'>Strange... Headcrab tastes not like crab...</span>")
```suggestion
		to_chat(M, "<span class='notice'>Strange... Headcrabs don't taste like crabs...</span>")
```

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +
Лишний пробел?

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	var/obj/item/reagent_containers/food/snacks/headcrab/H = new /obj/item/reagent_containers/food/snacks/headcrab(loc)
Ты уже прописал путь, просто `= new(loc)`

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		desc += " Eating and/or cooking this - a very bad idea."
```suggestion
		desc += "It is a very bad idea to eat or cook this."
```

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(istype(src, /mob/living/simple_animal/hostile/headcrab) && src.stat == DEAD && istype(I, /obj/item/storage/bag/trash/))
```suggestion
	if(istype(src, /mob/living/simple_animal/hostile/headcrab) && src.stat == DEAD && istype(I, /obj/item/storage/bag/trash))
```

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(istype(src, /mob/living/simple_animal/hostile/headcrab) && src.stat == DEAD && istype(I, /obj/item/storage/bag/trash/))
Ты себе разве не делал дефайна `isheadcrab`?

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
Уверен, что в начале нужно это?

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/mob/living/carbon/attackby(obj/item/I, mob/user, params)
Объясни логику. Если карбона ударили чем-то, И если этот карбон хедкраб...?????

2022-10-17 19:51 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		return
Уверен, что не нужно возвращать функцию родителя?

2022-10-18 15:14 UTC, larentoun requested changes

2022-10-18 15:14 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +			number = rand(1,6)
Я либо слепой, либо не вижу, где оно используется

2022-10-18 15:17 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +			number = rand(1,6)
playsound(user.loc, "sound/effects/bone_break[number].ogg", 25, TRUE, ignore_walls = FALSE, is_global = null)

2022-10-18 15:18 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/mob/living/carbon/attackby(obj/item/I, mob/user, params)
Карбон ударил хедкраба мешком для мусора - хедкраб в этом мешке для мусора

2022-10-18 15:18 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	..()
Да.

2022-10-18 15:19 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(istype(src, /mob/living/simple_animal/hostile/headcrab) && src.stat == DEAD && istype(I, /obj/item/storage/bag/trash/))
Нет.

2022-10-18 15:21 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/obj/item/reagent_containers/food/snacks/headcrab/attack(mob/M, mob/user, def_zone)
Судя по логике, M это тот, кого кормят. Больше идей не имею. Остальное к писарю легаси кода

2022-10-18 15:32 UTC, Robustin4 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(istype(src, /mob/living/simple_animal/hostile/headcrab) && src.stat == DEAD && istype(I, /obj/item/storage/bag/trash/))
если я уберу "/" то не будет проверка также и на другие виды мешков для мусора - блюспейсовый и киборгский

2022-10-18 16:28 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(istype(src, /mob/living/simple_animal/hostile/headcrab) && src.stat == DEAD && istype(I, /obj/item/storage/bag/trash/))
> если я уберу "/" то не будет проверка также и на другие виды мешков для мусора - блюспейсовый и киборгский

В плане? Не совсем понял тебя

2022-10-18 16:28 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/mob/living/carbon/attackby(obj/item/I, mob/user, params)
> Карбон ударил хедкраба мешком для мусора - хедкраб в этом мешке для мусора

Так тут логика "когда ударили карбона айтемом I"

2022-10-18 16:31 UTC, larentoun requested changes

2022-10-18 16:31 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
Лишние пробелы то убирай

2022-10-18 16:31 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
Лишние пробелы

2022-10-18 16:31 UTC, larentoun commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/obj/item/reagent_containers/food/snacks/headcrab/attack(mob/M, mob/user, def_zone)
> Судя по логике, M это тот, кого кормят. Больше идей не имею. Остальное к писарю легаси кода

Поменял бы тогда. Погоди, ты сам не понимаешь, что делаешь?

2024-02-12 20:59 UTC, closed without merging