Feat: Borer Buff(MedHud, separeted SalGlu)
ss220-space/Paradise pull request #1300
Opened 2022-09-03 22:22 UTC by BeebBeebBoob

## What Does This PR Do

Дать борерам, медхуд(когда внутри кого-то), способность на подобии медицинского сканнера(также только если внутри кого-то).
Уменьшить стоимость всех химикатов с 30 до 20 кроме флиптониум и мета(которые по 50)
Заменить Saline-Glucose Solution на kelotane(От ожогов) и bicardine(от брута) стоимость которых будут по 30 и железо(для крови) по 40.

## Why It's Good For The Game

Бореры будут полезны для своего носителя, понимая его тело ещё лучше. Нежели наугад через Examine что есть урон или в какой ситуации носитель.(космос, побили или паук прыскнул токсины)

## Changelog
:cl:
add: Med hud and med scan to borer while inside a host
tweak: SalGlu on kelotane(30chemuse) and bicaridine(30 chemuse) and iron(40 chemuse)
tweak: Decreases value of chems from 30 to 20
fix: action icon for making borer chems
/:cl:

2022-09-03 22:33 UTC, larentoun commented
Добавить бы еще возможность отхила внутри хозяина, а то странная ситуация, что если борера как-то ударили, то хозяину нужно будет его перевязать, хех

2022-09-03 22:35 UTC, larentoun requested changes

2022-09-03 22:35 UTC, larentoun commented on code/game/gamemodes/miniantags/borer/borer_chemicals.dm
> +	chemname = "bicaridines"
"bicaridine"

2022-09-03 22:36 UTC, larentoun commented
Почему бы не дать встроенный медхуд бореру, а не каждый раз включать/выключать?

2022-09-04 09:02 UTC, BeebBeebBoob commented on code/game/gamemodes/miniantags/borer/borer_chemicals.dm
> +	chemname = "bicaridines"
```suggestion
	chemname = "bicaridine"
```
Делать так надо если просишь изменения.
 Уф хорошо что заметил, спасибон

2022-09-04 09:03 UTC, BeebBeebBoob commented
> Добавить бы еще возможность отхила внутри хозяина, а то странная ситуация, что если борера как-то ударили, то хозяину нужно будет его перевязать, хех

Ну... Пока он внутри то всегда в безопасности так что хз

2022-09-04 09:06 UTC, BeebBeebBoob commented
> Почему бы не дать встроенный медхуд бореру, а не каждый раз включать/выключать?

Потому что даётся тогда когда он в кого-то сидит. Да, может убирать медхуд у борера когда он овладевает ибо медхуд у борера на как и клиента.

2022-09-04 10:21 UTC, larentoun commented
> > Добавить бы еще возможность отхила внутри хозяина, а то странная ситуация, что если борера как-то ударили, то хозяину нужно будет его перевязать, хех
> 
> Ну... Пока он внутри то всегда в безопасности так что хз

Он может просто раненный уже залезть и всё, с красным экраном жить не очень

2022-09-04 10:22 UTC, larentoun commented
> > Почему бы не дать встроенный медхуд бореру, а не каждый раз включать/выключать?
> 
> Потому что даётся тогда когда он в кого-то сидит. Да, может убирать медхуд у борера когда он овладевает ибо медхуд у борера на как и клиента.

Не, я про то, чтобы он был как у, например, терроров - всегда включен. Игромеханически не сильно влияет на то, что борер имеет медхуд вне хозяина

2022-09-10 16:04 UTC, closed without merging