FEAT: Revolution change (не мерджить)
ss220-space/Paradise pull request #1301
Opened 2022-09-04 10:20 UTC by VasilevAY

1. Теперь иконка революционера видна только главам революции
2. Добавлена возможность выходить из революции (при этом, вернуться больше нельзя, так как вы предали)

2022-09-04 10:27 UTC, larentoun requested changes

2022-09-04 10:27 UTC, larentoun commented on code/game/gamemodes/revolution/revolution.dm
> +	var/list/datum/mind/black_list_revolutionaries = list()
Я бы заменил на banned_revolutionaries

2022-09-04 10:27 UTC, larentoun commented on code/game/gamemodes/revolution/revolution.dm
> +/datum/action/innate/revolution_quit
Перенести функционал кнопки наверх, ровно после функционала кнопки хедревы

2022-09-04 10:27 UTC, larentoun commented on code/game/gamemodes/revolution/revolution.dm
> +	var/confirm = alert(usr,"Would you like quit from revolution? You cant became after confirmed","Quiting revolution","Yes","No")
```suggestion
	var/confirm = alert(usr, "Would you like to quit the Revolution? You won't be able to join the Revolution again!","Quit the Revolution","Yes","No")
```

2022-09-04 10:27 UTC, larentoun commented on code/game/gamemodes/revolution/revolution.dm
> +	name = "Recruitment"
```suggestion
	name = "Quit the Revolution"
```

2022-09-04 10:27 UTC, larentoun commented on code/game/gamemodes/revolution/revolution.dm
> +	log_admin("[key_name(usr)] quit the revolution.", usr)
```suggestion
	log_admin("[key_name(usr)] quitted the revolution voluntarily.", usr)
```

2022-09-04 12:43 UTC, dj-34 commented on code/game/gamemodes/revolution/revolution.dm
> +	log_admin("[key_name(usr)] quit the revolution.", usr)
```suggestion
	log_admin("[key_name(usr)] left the revolution.", usr)
```

2022-09-04 14:24 UTC, larentoun commented on code/game/gamemodes/revolution/revolution.dm
> +	log_admin("[key_name(usr)] quit the revolution.", usr)
Даже лучше

2022-09-04 14:27 UTC, frikadeliSpaghetti commented
Хэдреве о предателях ничего писать не будет?

2022-09-04 15:28 UTC, VasilevAY commented
> Хэдреве о предателях ничего писать не будет?

Нет, однако при попытке пригласить в революцию ему будет выпадать соответсвующее сообщение

2022-09-04 15:34 UTC, VasilevAY commented on code/game/gamemodes/revolution/revolution.dm
> +	var/list/datum/mind/black_list_revolutionaries = list()
подправил

2022-09-04 15:34 UTC, VasilevAY commented on code/game/gamemodes/revolution/revolution.dm
> +/datum/action/innate/revolution_quit
Подправил

2022-09-17 01:17 UTC, Dimach commented
Вы можете создавать драфт вместо того чтобы писать в названии "не мержить", и вообще голосовалка не прошла, наверно можно закрывать

2022-10-26 03:19 UTC, closed without merging