FEAT: Одежда для обезьян
ss220-space/Paradise pull request #1302
Opened 2022-09-04 14:07 UTC by PhantornRU

Авоуты пройдены:
https://discord.com/channels/617003227182792704/755125334097133628/1015906731173351465
https://discord.com/channels/617003227182792704/755125334097133628/1015906833807974410

## What Does This PR Do
Добавляет подогнанную под размеры обезьян одежду:
- Верхнюю одежду, кроме РИГов
- Униформу, комбезы
- Костюмы
- Наушники/радио
- Очки
- Шлема (теперь они правильно вставлены)
- Шея (плащи, накидки)
- Маски, сигары

Добавлено и подогнано практически всё что имеется в самом билде.

Также попутно добавлены карманы, слоты под ID и под PDA.

Обувь слетает с 50% шансом, этот коммит находится в ПРе:
https://github.com/ss220-space/Paradise/pull/1276

## Why It's Good For The Game
Обезьян можно кастомизировать под свой вкус, так как практически вся одежда теперь надевается на низшие формы карбонов.

## Images of changes
![image](https://user-images.githubusercontent.com/41479614/188317296-0a2f738b-7c62-4438-a2df-58a58ade70a4.png)
![image](https://user-images.githubusercontent.com/41479614/188317302-d998635f-7783-4ef3-8ad3-c420d9c34270.png)![image](https://user-images.githubusercontent.com/41479614/188317310-c58e87e0-a60e-4b3b-82a6-12da40c2b923.png)![image](https://user-images.githubusercontent.com/41479614/188317315-dc7fd01d-2c80-400e-b7b5-080f63a35857.png)![image](https://user-images.githubusercontent.com/41479614/188317319-03f30cf6-8b5d-4424-be8d-9045722f06c4.png)![image](https://user-images.githubusercontent.com/41479614/188317325-e13f8fc1-a4e3-44df-af16-64ecb95cd6b8.png)![image](https://user-images.githubusercontent.com/41479614/188317368-acb4bdfb-4178-4c0d-ad70-abfd89b7757f.png)![image](https://user-images.githubusercontent.com/41479614/188317393-ec744aa5-3329-479e-ba98-e2846cdaa307.png)![image](https://user-images.githubusercontent.com/41479614/188317412-9dd17592-693f-4439-965b-e6909b7e946d.png)![image](https://user-images.githubusercontent.com/41479614/188317438-73aa88e9-75f0-4eb4-a15e-282a44fa2a17.png)![image](https://user-images.githubusercontent.com/41479614/188317443-55c6dd51-b492-40da-9d01-5aa968c63d2b.png)![image](https://user-images.githubusercontent.com/41479614/188317460-aede1ccc-6987-44d1-995a-48a167ce49bc.png)![image](https://user-images.githubusercontent.com/41479614/188317462-ce2bae3f-332a-463e-b324-4d6199deb6c6.png)![image](https://user-images.githubusercontent.com/41479614/188317495-36c8b1ef-9c03-4c71-b373-a6d072c2f9ed.png)![image](https://user-images.githubusercontent.com/41479614/188317509-ae92ac53-e054-405a-a78f-3b4fa40a2234.png)![image](https://user-images.githubusercontent.com/41479614/188317514-a980cc3a-7956-4773-9fdc-f38578f0a594.png)![image](https://user-images.githubusercontent.com/41479614/188317522-8187918f-e22f-4b5d-a0a6-06f6c69512c9.png)![image](https://user-images.githubusercontent.com/41479614/188317550-8c8bc94a-3428-4c24-8fe3-75107223eaa0.png)![image](https://user-images.githubusercontent.com/41479614/188317552-a65f8659-4305-4997-abf2-fb1ee48d4a29.png)![image](https://user-images.githubusercontent.com/41479614/188317576-0263c633-aa3b-40d0-84bf-2e53953a8f61.png)

2022-09-06 08:09 UTC, BeebBeebBoob requested changes

2022-09-06 08:09 UTC, BeebBeebBoob commented on code/modules/clothing/clothing.dm
> +	log_admin("Пройдено 5")
А?

2022-09-06 08:09 UTC, BeebBeebBoob commented on code/modules/clothing/clothing.dm
> +//  clothing
```suggestion
// Under clothing
```

2022-09-06 08:09 UTC, BeebBeebBoob commented on code/modules/clothing/under/jobs/civilian.dm
> -
Я надеюсь этим удалением ничего не сломал и рантаймы не полетят

2022-09-06 09:03 UTC, PhantornRU commented on code/modules/clothing/clothing.dm
> +	log_admin("Пройдено 5")
упс, я думал все дебаги своих шагов выпилил

2022-09-06 09:25 UTC, PhantornRU commented on code/modules/clothing/under/jobs/civilian.dm
> -
Та откуда рантаймы? Это просто отрисовка униформы обнуляется. А если ты дальше пройдешь внутрь /under - то увидишь что там и так должно было быть обнуление. Просто кто-то что-то хотел вписать и забыл убрать. А так как у нас теперь одежда определяется по установленным спрайтам для специй, аля обезьян, в under, то мы выпиливаем, чтобы под них это тоже впадало.
![image](https://user-images.githubusercontent.com/41479614/188598931-924d456f-4c91-4547-a065-58539b4138ec.png)

2022-09-06 09:29 UTC, PhantornRU commented on code/modules/clothing/clothing.dm
> +//  clothing
Занес, хотя и не имеет смысла

2022-09-06 09:29 UTC, BeebBeebBoob approved these changes

2022-09-26 14:27 UTC, PhantornRU commented
@Dimach Еще этот надобно бы. А то ему тоже скоро месяц исполнится xD

2022-09-26 14:41 UTC, merged