Spread Infestation Rework
ss220-space/Paradise pull request #1304
Opened 2022-09-04 16:54 UTC by Robustin4

Да. Пауки теперь быстро вырастают и опрадывают цену, имеют новый спрайт, являются отдельным симплмобом, враждебен ко всем, кроме других гигантских пауков.

## What Does This PR Do
Реворк над Распротранением заразы. Раньше это был спавн двух ядовитых спайдерлингов за 45 химикатов (что довольно много). Теперь это быстрорастующие самостоятельные симплмобы с спрайтом, прямо как на иконочке)

## Why It's Good For The Game
Распространение заразы не так бесполезно.

p.s. я чую множество претензий по поводу баланса.

2022-09-06 08:03 UTC, BeebBeebBoob requested changes

2022-09-06 08:03 UTC, BeebBeebBoob commented on code/game/gamemodes/changeling/powers/spiders.dm
> +#define SPINNING_COCOON 4
Все дефайны идут в самый верх, как и  андеф в самый вниз. Это порядок кода и часть контрибуции.

2022-09-06 08:03 UTC, BeebBeebBoob commented on code/game/gamemodes/changeling/powers/spiders.dm
> +	attacktext = "срывает плоть с"
Это же практически будет писать каждый раз, когда паук будет бить. Точно задумано что каждый раз будет только срывать? Все же паук и он кусает...

2022-09-06 08:03 UTC, BeebBeebBoob commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +#undef SPINNING_COCOON
А?

2022-09-06 08:03 UTC, BeebBeebBoob commented on code/game/objects/effects/spiders.dm
> +	var/changeling = FALSE
Только вот это нигде не используется. Нет, в коде чуть внизу да. Но нигде не устанавливается что это паучки от генокрада.
Так ещё ты уже в способности генокрада установил это.

2022-09-06 08:03 UTC, BeebBeebBoob commented on code/game/gamemodes/changeling/powers/spiders.dm
> +#define SPINNING_COCOON 4
Или лучше ВЗЯТЬ И ПЕРЕНЕСТИ весь этот код про паука моба в code/modules/mob/living/simple_animal/hostile/giant_spider.dm в самый конец строчек

2022-09-06 12:53 UTC, BeebBeebBoob commented
Ну довольно красиво и definы. 
Ну вот осталось глянуть в этом файле code/game/objects/effects/spiders.dm

2022-09-06 14:25 UTC, Den109G commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +#undef SPINNING_COCOON
![image](https://user-images.githubusercontent.com/87372121/188660663-b4e6d62b-0f0e-4832-8a63-82057b68e9b7.png)
Ругается, что новой строки нет.

2022-09-06 14:28 UTC, Den109G commented on code/game/gamemodes/changeling/powers/spiders.dm
> +	return 1
![image](https://user-images.githubusercontent.com/87372121/188661301-3765c57f-5e22-4340-a105-f58aaf8a714b.png)
Тоже ругается на нехватку строк.

2022-09-26 15:51 UTC, Dimach commented
Где воут на бафф?

2022-09-26 16:01 UTC, Robustin4 commented
Это просто реворк и я просто оставил это тут. Может сделаю предложение.

2024-02-12 20:59 UTC, closed without merging