Ребаланс глоушрумов
ss220-space/Paradise pull request #1312
Opened 2022-09-06 16:26 UTC by Zipliks

## What Does This PR Do
Частичный порт глоушрумов с /tg/

Изменения:
- Грибы не растут через 3 тайла, только в пределах 1 соседнего.
- Скорость распространения грибов изменена до ~42 секунд (каждый гриб даёт потомство раз в ~42 с.).
- Грибы можно срезать косой (как телескопической, так и обычной) в области 3х3.
- Любое острое оружие и оружие с типом урона `BURN` наносит х4 урона грибам (косы наносят х10).
- Спустя время грибы сгнивают, самовычищаясь с карты. Время гниения зависит от "здоровья" гриба.
- Характеристики растущих на полу грибов можно узнать через `Seed Analyzer`.
- Каждый гриб имеет 5 попыток на размножение, после чего прекращает любые попытки.

## Why It's Good For The Game
Сделано по просьбе автора [предложки](https://discord.com/channels/617003227182792704/755125334097133628/996877311213314138)
- Грибы больше не засрут всю станцию из-за одного ботаника.
- Тени всё ещё способны уничтожать грибы 3х3 раз в N секунд своей способностью.
- Больше работы траллам, потому что грибы растут чуть быстрее и ковром.
- Меньше страданий серверу (но это не точно).
- Если траллы захотят косы, есть причина пойти получить по башке в карго.
- Скорость распространения грибов станет проще регулировать.

## Images of changes

## Changelog
:cl:
add: Glowshrooms will now decay preventing from overtaking the entire station by a random shroom cluster
tweak: Tweaked glowhsrooms spread speed
/:cl:

2022-09-08 16:41 UTC, larentoun requested changes

2022-09-08 16:41 UTC, larentoun commented on code/game/objects/effects/glowshroom.dm
> +	var/floor = FALSE
isfloorturf?

2022-09-08 16:41 UTC, larentoun commented on code/game/objects/effects/glowshroom.dm
> +	. += "This is a [generation]\th generation [name]!"
notice span class

2022-09-08 16:41 UTC, larentoun commented on code/game/objects/effects/glowshroom.dm
> +	if(istype(analyzer, /obj/item/plant_analyzer))
раз мы делаем прям для obj/item/analyzer, могли бы уже туда вставить /obj/item/plant_analyzer, и делать просто проверку на тип

2022-09-08 16:41 UTC, larentoun commented on code/game/objects/effects/glowshroom.dm
>  			floor = 1
Если все же решишь оставить var/floor, то давай внятные значения (TRUE/FALSE)

2022-09-08 16:46 UTC, Zipliks commented on code/game/objects/effects/glowshroom.dm
> +	if(istype(analyzer, /obj/item/plant_analyzer))
Речь про...?
```c
//Way to check glowshroom stats using plant analyzer
/obj/structure/glowshroom/attackby(obj/item/plant_analyzer, mob/living/user, params)
	if(istype(/obj/item/plant_analyzer))
		// Hacky I guess
		return myseed.attackby(plant_analyzer, user, params)
	return ..()
```

2022-09-08 18:15 UTC, larentoun commented on code/game/objects/effects/glowshroom.dm
> +	for(var/turf/simulated/floor/earth in view(1, src))
А, earth это переменная пола. Тю-ты... Запутало меня, значит, желательно поменять переменную, наверное

2022-09-08 18:15 UTC, larentoun commented on code/game/objects/effects/glowshroom.dm
> +	var/is_floor_turf = FALSE
Я про то, что можно обойтись без этой переменной, если она учавствует лишь пару раз, и использовать макрос isfloorturf(loc). Тут уже зависит от того, как часто

2022-09-08 18:29 UTC, Zipliks commented on code/game/objects/effects/glowshroom.dm
> +	for(var/turf/simulated/floor/earth in view(1, src))
Так могу просто обозвать `/floor/floor`

2022-09-09 05:40 UTC, Vallat requested changes

2022-09-09 05:40 UTC, Vallat commented on code/game/objects/effects/glowshroom.dm
> +	if(!is_floor_turf)
Не особо нравится мне то, что `is_floor_turf` вычисляется в `calc_dir()` который вызывается аргументом к `setDir`. Трудночитаемо. Возможно, стоит этот момент переделать?

2022-09-09 05:40 UTC, Vallat commented on code/game/objects/effects/glowshroom.dm
> +	for(var/turf/simulated/floor/earth in view(1, src))
`view(1)` даст во всех случаях квадрат 3 на 3 турфа. В таком случае лучше использовать `RANGE_TURFS`
```suggestion
	for(var/turf/simulated/floor/earth in RANGE_TURFS(1, src))
```

2022-09-09 05:40 UTC, Vallat commented on code/game/objects/effects/glowshroom.dm
> +		if(prob(chance_generation))
Можно и даже нужно переделать под `early return` (в случае с циклом думаю понимаешь, что не `return`, а `continue`)

2022-09-09 05:40 UTC, Vallat commented on code/game/objects/effects/glowshroom.dm
> +	for(var/i = 1, i <= 16, i <<= 1)
Сомнительный цикл канеш для прохода по всем дирам, лучше уж переделать под что-то типа
`for(var/dir_to_check in GLOB.cardinals)`

2022-09-09 05:40 UTC, Vallat commented on code/game/objects/effects/glowshroom.dm
> +/obj/structure/glowshroom/attacked_by(obj/item/tool, mob/living/user)
Используй `attackby`, он в коде применяется гораздо чаще и имеет тот же функционал. Не забудь вернуть `TRUE` или `FALSE` в случае успеха/неудачи атаки.
P.S. для чего конкретно был нужен `attacked_by` - до сих пор неизвестно

2022-09-09 12:23 UTC, Zipliks commented on code/game/objects/effects/glowshroom.dm
> +	for(var/turf/simulated/floor/earth in view(1, src))
Так квадрат 3х3 и нужен
Если речь о том, что при RANGE_TURF будет исключён центральный турф, то это и правда лучше

2022-09-09 12:42 UTC, Vallat commented on code/game/objects/effects/glowshroom.dm
> +	for(var/turf/simulated/floor/earth in view(1, src))
Не будет исключен, это просто более быстрая функция. Ощутимо более быстрая.

2022-09-10 22:13 UTC, larentoun approved these changes

2022-09-11 19:58 UTC, larentoun commented on code/game/objects/effects/glowshroom.dm
> +			break
А зачем тогда цикл, если ты его сразу же прерываешь?

2022-09-11 20:00 UTC, Zipliks commented on code/game/objects/effects/glowshroom.dm
> +			break
> А зачем тогда цикл, если ты его сразу же прерываешь?

А я без понятия, сейчас и его уберу
Там в целом вся эта конструкция бесполезна

2022-09-12 04:42 UTC, Vallat approved these changes

2022-10-01 19:26 UTC, merged