Tweak: Урезание Тайпану возможности слушать важные каналы.
ss220-space/Paradise pull request #1315
Opened 2022-09-07 01:28 UTC by Zigamus

## What Does This PR Do

Урезание возможности слышать каналы СБ, Командования и жучка у тайпановцев

![image](https://user-images.githubusercontent.com/59314481/188768596-99af7378-0f7f-418c-856e-10b26edfd9a8.png)

## Images of changes

![image](https://user-images.githubusercontent.com/59314481/188768614-395d7feb-e0b1-45dd-87b0-e26425ad95ea.png)
![image](https://user-images.githubusercontent.com/59314481/188768617-b8f70150-9c84-42d8-8434-eebaa087a310.png)
![image](https://user-images.githubusercontent.com/59314481/188768632-889ee292-2c5d-478e-8c4c-a48cbb4c6146.png)

## Changelog
:cl:
tweak: Урезание возможности слышать каналы СБ, Командования и жучка у тайпановцев
/:cl:

2022-09-07 04:46 UTC, Vallat requested changes

2022-09-07 04:46 UTC, Vallat commented on code/game/objects/items/devices/radio/radio.dm
> +	else if((syndiekey && !(freq in SSradio.syndicate_blacklist) && !istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan)) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && !(fre
```suggestion
	else if(syndiekey && !((freq in SSradio.syndicate_blacklist) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && (freq in SSradio.taipan_blacklist))))
```

2022-09-07 04:48 UTC, Vallat commented on code/controllers/subsystem/radio.dm
> +	var/list/taipan_blacklist = list(SPY_SPIDER_FREQ, SEC_FREQ, SEC_I_FREQ, ERT_FREQ, COMM_FREQ) //list of frequencies Taipan headset can't hear
И тогда это можно будет оставить в таком виде
```suggestion
	var/list/taipan_blacklist = list(SEC_FREQ, SEC_I_FREQ, ERT_FREQ, COMM_FREQ) //list of frequencies Taipan headset can't hear
```

2022-09-07 06:14 UTC, Zigamus commented on code/game/objects/items/devices/radio/radio.dm
> +	else if((syndiekey && !(freq in SSradio.syndicate_blacklist) && !istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan)) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && !(fre
1. else if(syndiekey && !((freq in SSradio.syndicate_blacklist) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && **!**(freq in SSradio.taipan_blacklist)))) 
2. Тогда не выйдет настраивать исключения отдельно, то есть будет сложнее делать новые твики. Если Максим через неделю скажет отобрать только у агентов слышать канал дезсквада, то энивей придется идти к более гибкому варианту.

2022-09-07 08:54 UTC, Vallat commented on code/game/objects/items/devices/radio/radio.dm
> +	else if((syndiekey && !(freq in SSradio.syndicate_blacklist) && !istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan)) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && !(fre
Так я буквально твой код переписал под меньшее число проверок, не более. Новые твики точно так же делаются. У тайпановцев и до этого доступа к каналу с жучком не было, как и не будет сейчас.

2022-09-07 13:33 UTC, Zigamus commented on code/game/objects/items/devices/radio/radio.dm
> +	else if((syndiekey && !(freq in SSradio.syndicate_blacklist) && !istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan)) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && !(fre
> буквально твой код переписал под меньшее число проверок, не более

> Но, дополнительно

2022-09-07 13:47 UTC, Vallat commented on code/game/objects/items/devices/radio/radio.dm
> +	else if((syndiekey && !(freq in SSradio.syndicate_blacklist) && !istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan)) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && !(fre
Ты либо читаешь не так, либо я некорректно изъясняюсь. В любом случае, ты по коду должен всё и так четко видеть, если же нет, то тут уже туше.
Еще раз, это код с той же задуманной логикой, что ты и описал, однако он уже учитывает запрет синдикатовских наушников к каналу паучков без необходимости дублирования проверки на тайпановский наушник.
Я до тебя не докапываюсь как-то, я просто доработал этот кусок. Если хочешь докопов - можем поговорить о том, что делать подобный функционал через проверки на тип - плохой тон.

2022-09-07 14:04 UTC, Zigamus commented on code/game/objects/items/devices/radio/radio.dm
> +	else if((syndiekey && !(freq in SSradio.syndicate_blacklist) && !istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan)) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && !(fre
> Ты либо читаешь не так
Я всё прекрасно читаю и я сразу ответил, что два разных листа задумано так, чтоб можно было их отдельно менеджить и не писать эту же проверку опять тогда, когда нужно будет отобрать еще один канал только у агентов.

> делать подобный функционал через проверки на тип - плохой тон.
![image](https://user-images.githubusercontent.com/59314481/188898503-7dc3789a-8c09-4929-bc77-fed6cc2f0bd7.png)

2022-09-07 14:19 UTC, Vallat commented on code/game/objects/items/devices/radio/radio.dm
> +	else if((syndiekey && !(freq in SSradio.syndicate_blacklist) && !istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan)) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && !(fre
Первый лист задумывался изначально как лист не для агентов, а для синдиката в целом, так как он и завязан на переменную `syndiekey`. Если ты хочешь делать два разных листа для агентов и для тайпана, прошу - разделяй это нормально и не делай привязку к типу объекта, о чем я написал выше. Это всё прекрасно менеджится через переменные. И именно поэтому я и написал, что делать подобный функционал через проверки на тип - плохо.

Однако, ты это как-то воспринимаешь в перевратом виде, приводя мне поиск по количеству изтайпов. Зачем? Не понимаю. Я вкурсе, что делает эта функция и когда она применяется. Сейчас не та ситуация.

2022-09-07 20:54 UTC, Zigamus commented on code/game/objects/items/devices/radio/radio.dm
> +	else if((syndiekey && !(freq in SSradio.syndicate_blacklist) && !istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan)) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && !(fre
![image](https://user-images.githubusercontent.com/59314481/188976766-fe063409-c61c-4111-8360-57259dd6eb63.png)
А вот тут именно та, в чем отличия?

2022-09-08 04:14 UTC, Vallat commented on code/game/objects/items/devices/radio/radio.dm
> +	else if((syndiekey && !(freq in SSradio.syndicate_blacklist) && !istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan)) || (istype(syndiekey, /obj/item/encryptionkey/syndicate/taipan) && !(fre
Ну, в том, что писалось это еще Фурукай без понимания, что так делать не совсем верно.
Я думаю, ты со мной согласишься, что выносить широкий функционал на привязку к типам в конкретных - плохо и несёт за собой лишь проблемы при будущем расширении кода. Лучше же завязывать это всё либо на отдельных переменных, либо на функциях. Я смотрю, ты уже исправил всё на отлично. Спасибо 👍 
Мы же не хотим потом иметь нечто подобное?
![image](https://user-images.githubusercontent.com/10997188/189032617-97b6a5b1-3450-4ca3-be0f-8457660f0391.png)

2022-09-08 04:16 UTC, Vallat approved these changes

2022-09-09 18:49 UTC, merged