FEAT: Шляпы для силиконов
ss220-space/Paradise pull request #1318
Opened 2022-09-07 14:02 UTC by PhantornRU

## What Does This PR Do
Силиконы теперь умеют носить шапочки.

Изменения:
- У каждого силикона и модуля имеются свои оффсеты и правила
- Хуманизированные силиконы могут носить шлема
- Головной убор надевается в слот головы
- HELP-intent с шляпой в руке - надевает её на силикона.
- GRAB-intent с пустой рукой - снимает с силикона шляпу.
- ГИБ и деконструкт - роняет головной убор
- Смена модуля - изменяет ОФФсет под текущий модуль
- Готовые борги с модулями (синди, дезсквад, дестроеры) сразу имеют нужные оффсеты и правила.
- Дроны могут носить головной убор
- Дроны теряют головной убор когда залезают в вентиляцию
- ИИ может носить не-шлемовые головные уборы
- Новые силиконы сразу корректно инициализируются, из-за чего можно создать сразу боргов со шляпами, если то требуется.

ПИИ ущемлены и не умеют носить шапки, так как у них имеются разные состояния анимации, а мне лень ими заниматься. 

## Why It's Good For The Game
Ассистенты и экипаж получают возможности угнетать силиконов, у которых нет ручек снять шляпы.

## Images of changes
### Разные модули:
![image](https://user-images.githubusercontent.com/41479614/188896565-b8f47a7b-9d65-46f5-aab9-00bd6eb394ef.png)
Скриншот чутка устарел. Коробочные борги во второй колонне были поправлены.

### Залезание дрона со шляпой в вентиляцию и её потеря
![image](https://user-images.githubusercontent.com/41479614/188897387-ee5f5b49-3acc-4077-9c8b-e4e760d3380a.png)
![image](https://user-images.githubusercontent.com/41479614/188897438-f740460c-ad65-43d6-9c3d-dff6ef8df166.png)
![image](https://user-images.githubusercontent.com/41479614/188897513-8891db3a-0350-4c84-b369-1f354f2818f7.png)

### Написание в чате производимых действий
![image](https://user-images.githubusercontent.com/41479614/188897764-20f0f8b5-6d59-4012-b0c2-6ac91c3cbf5a.png)

2022-09-08 12:02 UTC, PhantornRU commented
Авоут пройден. Шапочкам быть:
https://discord.com/channels/617003227182792704/755125334097133628/1017403660633919560

2022-09-08 14:27 UTC, helper-2 commented
Мне кажется или на скрине у некоторых боргов шляпа смещена? На Кенте и Хирурге это точно заметно.

2022-09-08 14:28 UTC, helper-2 commented
> Мне кажется или на скрине у некоторых боргов шляпа смещена? На Кенте и Хирурге это точно заметно.

А да, не прочитал поправку под скрином. 
Moi izvinenia

2022-09-11 09:55 UTC, PhantornRU commented
Борги теперь кувырком могут снять шляпу.

2022-09-19 02:30 UTC, Dimach requested changes

2022-09-19 02:30 UTC, Dimach commented on code/modules/mob/living/carbon/carbon.dm
> +				unEquip(S.inventory_head)
А если никакой шляпы не было надето тоже будет писать про опрокинул шляпу?

2022-09-19 05:23 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +			if(issilicon(src))
```suggestion
			if(issilicon(src) && S.inventory_head)
```

2022-09-19 05:23 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +				unEquip(S.inventory_head)
Внёс проверку на наличие шапки

2022-09-21 02:00 UTC, Dimach approved these changes

2022-09-24 17:27 UTC, merged