Настольный звонок
ss220-space/Paradise pull request #1324
Opened 2022-09-11 17:07 UTC by Zipliks

## What Does This PR Do
Портирует `desk_bell` с оффов, включая спрайт

## Why It's Good For The Game
Можно позвонить, а не спамить СКМ, тыкая пальцем в работников отдела. Чуть больше РП?
Возможно, добавит веселья клоуну

## Images of changes
![image](https://user-images.githubusercontent.com/4831847/189540051-9869f8e1-ea90-4be9-a6b4-dfda1d81066f.png)

## Changelog
:cl:
add: Added desk bell
/:cl:

2022-09-11 22:17 UTC, larentoun approved these changes

2022-09-11 23:02 UTC, dj-34 requested changes
![image](https://user-images.githubusercontent.com/20109643/189552683-62eec41e-4381-4ffe-ab57-4695470a0774.png)

2022-09-12 02:14 UTC, dj-34 approved these changes

2022-09-12 10:12 UTC, larentoun commented
Интересна, а чего линтер не заметил ошибку компиляции, он же сам тоже компилит проект

2022-09-12 10:17 UTC, larentoun commented
А, там была все же ошибка, не углядела, мда

2022-09-12 10:32 UTC, PhantornRU commented
Эх, если бы по ним можно было б еще бегать и крафтить их...
А то вдруг какой асистос себе сопрет.

2022-09-12 11:46 UTC, zipliks commented
> Эх, если бы по ним можно было б еще бегать и крафтить их...
> А то вдруг какой асистос себе сопрет.

Они добавлены в автолат
Даже в коммите указано

2022-09-17 01:03 UTC, Dimach approved these changes

2022-09-26 14:45 UTC, merged