Fix: R&D (Delta/Kerberos) [TEST MERGE]
ss220-space/Paradise pull request #1327
Opened 2022-09-12 09:58 UTC by ItsMeJaba

# Исправляет косяки пра #1266:
* Восстановлена труба в коридоре R&D
* Легкое размакаронивание труб и проводов
* Камера в стене приемной вышла из стены
* Исправлен проход в робототехнике
* Изменено освещение в пользу меньшего потребления и кол-ва ламп при том же уровне освещения
* Косметическая перестановка объектов на стенах в пользу доступности и удобства

# Изменено:
* Исправлен доступ к окошку на КПП командования в прибытии
* В тоннели под робототехникой добавлен "разобранный" зарядник боргов

* Перенос с оффов фикса https://github.com/ParadiseSS13/Paradise/pull/17249 на 2 строчки, которые исправляют рандомное положение декалей на полу

![f1](https://user-images.githubusercontent.com/91949115/189625165-8f6b38ec-002c-472b-aa7a-e4dd827ffd4f.png)

2022-09-13 05:50 UTC, dj-34 requested changes

2022-09-13 05:50 UTC, dj-34 commented on code/game/objects/effects/decals/warning_stripes.dm
> +	var/image/I = image(icon, icon_state = icon_state, dir = dir)
Лучше откатить и загрузить отдельным фиксом.

2022-09-14 10:20 UTC, ItsMeJaba commented on code/game/objects/effects/decals/warning_stripes.dm
> +	var/image/I = image(icon, icon_state = icon_state, dir = dir)
Согласен, вечером поправлю и скину в запросы в 2 пра

2022-09-14 16:32 UTC, ItsMeJaba commented on code/game/objects/effects/decals/warning_stripes.dm
> +	var/image/I = image(icon, icon_state = icon_state, dir = dir)
Разделил

2022-09-19 08:01 UTC, dikers93 approved these changes

2022-09-20 18:21 UTC, ItsMeJaba commented
Перетянул эти фиксы в #1094 для упрощения работы с версиями карты. Теперь достаточно замержить единственный пр  почти 2-х месячной давности на тестовую ветвь.

2022-09-20 18:21 UTC, closed without merging