Fix: Hyperglycaemic shock rework
ss220-space/Paradise pull request #1337
Opened 2022-09-15 07:56 UTC by Honker9999999

## What Does This PR Do

Изменяет механику гиперклекимии (передозировку сахара), а именно:
С 80+ сахара -
Первые 8 циклов (~10 секунд) - сообщения в чат+урон в 0.25 токсинов ИЛИ с шансом в 50% 0.5 токсинов
9-15 (~7-8 секунд) - более намекающие сообщения в чат, урон в 1 токс+с шансом в 25% урон 0.25 урон почкам и печени
16-И до бесконечности, в случае наличия 120+ сахара - паралич и вырубание, как сейчас, 1.5 токсинов ИЛИ с шансом в 50% 2.5 урона токсинами, с шансом в 50% 1 урон почкам и печени.
При введении инсулина третья стадия будет иметь значительно урезанный эффект, а именно:
1 токсин-урон за тик, с шансом в 25% - стан на 2 тика, 25% 0.25 урона для почек и печени.
Если будет больше 80, но меньше 120 - урон в 1 токсин/1.5 с шансом в 50%, 0.5 по почкам и печени с 25%-м шансом. С шансом в 25% - паралич и стан на два тика.

## Why It's Good For The Game

Нерф имбанутой механики
## Changelog
:cl:
fix: фикс гиперклекимии
/:cl:

2022-09-15 08:12 UTC, BeebBeebBoob requested changes
А не легче сменить с 200 на 80 и все что после else просунуть в od process?

2022-09-15 08:42 UTC, PhantornRU approved these changes
Наконец-то фикс которого бы заслуживаем

Хотя на пробники 25% выдачи текста странно смотрю. Но почему бы и да.
Главное что органам наносится урон.

2022-09-15 08:57 UTC, Honker9999999 commented
> А не легче сменить с 200 на 80 и все что после else просунуть в od process?

Это дабы позитивные эффекты сахара не прокались, ибо сейчас прокаются и передоз, и обычная херня, если я понял о чем ты.

2022-09-15 09:26 UTC, BeebBeebBoob commented
Ну лучше просунуть всё таки, плюс ты можешь использовать переменную `overdosed` boolean (true или false) которая сама собой указывает достиг реагент передоза или нет, и ты можешь добавить в 
```
		if(prob(25) && !overdosed)
			update_flags |= M.AdjustParalysis(-1, FALSE)
			update_flags |= M.AdjustStunned(-1, FALSE)
			update_flags |= M.AdjustWeakened(-1, FALSE)
		if(prob(4) && !overdosed)
			M.reagents.add_reagent("epinephrine", 1.2)
```
И всё равно перекинуть в прок overdose_process()
А вот `to_chat(M, pick("<span class='warning'>Я чуствую себя не очень.</span>", "<span class='warning'>Я чуствую неприятные ощущения в нижней части тела.</span>", "<span class='warning'>Я чуствую неприятные ощущения в своих почках.</span>"))` в overdose_start()

2022-09-15 09:32 UTC, BeebBeebBoob commented
И ещё будут выпадать ошибки если не будет либо liver либо kidneys 
`null.receive_damage(0.25)`

2022-09-15 09:33 UTC, BeebBeebBoob commented
```
/datum/reagent/consumable/sugar/on_mob_life(mob/living/M)
	var/update_flags = STATUS_UPDATE_NONE
	M.AdjustDrowsy(-5)
	if(current_cycle >= 90)
		M.AdjustJitter(2)
	if(prob(25) && !overdosed)
		update_flags |= M.AdjustParalysis(-1, FALSE)
		update_flags |= M.AdjustStunned(-1, FALSE)
		update_flags |= M.AdjustWeakened(-1, FALSE)
	if(prob(4) && !overdosed)
		M.reagents.add_reagent("epinephrine", 1.2)

/datum/reagent/consumable/sugar/overdose_start(mob/living/M)
	to_chat(M, pick("<span class='warning'>Я чуствую себя не очень.</span>", "<span class='warning'>Я чуствую неприятные ощущения в нижней части тела.</span>", "<span class='warning'>Я чуствую неприятные ощущения в своих почках.</span>"))
	..()

/datum/reagent/consumable/sugar/overdose_process(mob/living/M, severity)
	var/obj/item/organ/internal/liver/L = M.get_int_organ(/obj/item/organ/internal/liver)
	var/obj/item/organ/internal/kidneys/K = M.get_int_organ(/obj/item/organ/internal/kidneys)
	switch(current_cycle)
		if(1 to 8)
			if(prob(50))
				M.adjustToxLoss(0.5)
			else
				M.adjustToxLoss(0.25)
		if(9 to 15)
			if(prob(25))
				to_chat(M, pick("<span class='warning'>Я чуствую сильный голод!</span>", "<span class='warning'>У меня будто перед глазами туман!</span>"))
			if(prob(25))
				L.receive_damage(1)
				K.receive_damage(0.25)
			M.adjustToxLoss(1)
		if(16 to INFINITY)
			if(volume <= 119)
				if(prob(50))
					M.adjustToxLoss(1.5)
				else
					M.adjustToxLoss(1)
				if(prob(25))
					L.receive_damage(0.25)
					K.receive_damage(0.25)
				if(prob(25))
					update_flags |= M.AdjustStunned(2, FALSE)
					update_flags |= M.AdjustParalysis(2, FALSE)
			if((volume > 119) && !("insulin" in M.reagents))
				update_flags |= M.Paralyse(3, FALSE)
				update_flags |= M.Weaken(4, FALSE)
				if(prob(50))
					M.adjustToxLoss(2.5)
				else
					M.adjustToxLoss(1.5)
				if(prob(50))
					L.receive_damage(1)
					K.receive_damage(1)
			else
				M.adjustToxLoss(1)
				if(prob(25))
					update_flags |= M.AdjustStunned(2, FALSE)
				if(prob(25))
					L.receive_damage(0.25)
					K.receive_damage(0.25)
	return list(effect, update_flags)
```

2022-09-15 09:34 UTC, BeebBeebBoob commented
и вот ещё 
`overdose_threshold = 80 // Hyperglycaemic shock`

2022-09-15 09:40 UTC, Honker9999999 commented
> Ну лучше просунуть всё таки, плюс ты можешь использовать переменную `overdosed` boolean (true или false) которая сама собой указывает достиг реагент передоза или нет, и ты можешь добавить в
> 
> ```
> 		if(prob(25) && !overdosed)
> 			update_flags |= M.AdjustParalysis(-1, FALSE)
> 			update_flags |= M.AdjustStunned(-1, FALSE)
> 			update_flags |= M.AdjustWeakened(-1, FALSE)
> 		if(prob(4) && !overdosed)
> 			M.reagents.add_reagent("epinephrine", 1.2)
> ```
> 
> И всё равно перекинуть в прок overdose_process() А вот `to_chat(M, pick("<span class='warning'>Я чуствую себя не очень.</span>", "<span class='warning'>Я чуствую неприятные ощущения в нижней части тела.</span>", "<span class='warning'>Я чуствую неприятные ощущения в своих почках.</span>"))` в overdose_start()

Просто хз надо ли это как таковое. По кол-ву текста это выйдет даже больше, читаемость кода вроде бы такая-же.

2022-09-15 09:49 UTC, BeebBeebBoob commented
это да но по сути и логике кода, ты просто берёшь и выкидываешь смысл overdose делая его в обычной версии прока(которая не передозировка).
Вся проверка на количество реагентов(80) уже прописано в общей проверке реагентов от оффов и не надо будет добавлять if(volume) и else.
Поэтому я предлагаю и прошу сделать так, как было задумано главным источником кода.

2022-09-15 09:51 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/food.dm
>  	return ..() | update_flags
```suggestion
	M.AdjustDrowsy(-5)
	if(current_cycle >= 90)
		M.AdjustJitter(2)
	if(prob(25) && !overdosed)
		update_flags |= M.AdjustParalysis(-1, FALSE)
		update_flags |= M.AdjustStunned(-1, FALSE)
		update_flags |= M.AdjustWeakened(-1, FALSE)
	if(prob(4) && !overdosed)
		M.reagents.add_reagent("epinephrine", 1.2)

/datum/reagent/consumable/sugar/overdose_start(mob/living/M)
	to_chat(M, pick("<span class='warning'>Я чуствую себя не очень.</span>", "<span class='warning'>Я чуствую неприятные ощущения в нижней части тела.</span>", "<span class='warning'>Я чуствую неприятные ощущения в своих почках.</span>"))
	..()

/datum/reagent/consumable/sugar/overdose_process(mob/living/M, severity)
	var/obj/item/organ/internal/liver/L = M.get_int_organ(/obj/item/organ/internal/liver)
	var/obj/item/organ/internal/kidneys/K = M.get_int_organ(/obj/item/organ/internal/kidneys)
	switch(current_cycle)
		if(1 to 8)
			if(prob(50))
				M.adjustToxLoss(0.5)
			else
				M.adjustToxLoss(0.25)
		if(9 to 15)
			if(prob(25))
				to_chat(M, pick("<span class='warning'>Я чуствую сильный голод!</span>", "<span class='warning'>У меня будто перед глазами туман!</span>"))
			if(prob(25))
				L.receive_damage(1)
				K.receive_damage(0.25)
			M.adjustToxLoss(1)
		if(16 to INFINITY)
			if(volume <= 119)
				if(prob(50))
					M.adjustToxLoss(1.5)
				else
					M.adjustToxLoss(1)
				if(prob(25))
					L.receive_damage(0.25)
					K.receive_damage(0.25)
				if(prob(25))
					update_flags |= M.AdjustStunned(2, FALSE)
					update_flags |= M.AdjustParalysis(2, FALSE)
			if((volume > 119) && !("insulin" in M.reagents))
				update_flags |= M.Paralyse(3, FALSE)
				update_flags |= M.Weaken(4, FALSE)
				if(prob(50))
					M.adjustToxLoss(2.5)
				else
					M.adjustToxLoss(1.5)
				if(prob(50))
					L.receive_damage(1)
					K.receive_damage(1)
			else
				M.adjustToxLoss(1)
				if(prob(25))
					update_flags |= M.AdjustStunned(2, FALSE)
				if(prob(25))
					L.receive_damage(0.25)
					K.receive_damage(0.25)
	return list(0, update_flags)
```

2022-09-15 09:55 UTC, Honker9999999 commented on code/modules/reagents/chemistry/reagents/food.dm
>  	return ..() | update_flags
Как говорил главный источник кода:
هذا الكتاب ، الذي لا شك فيه ، هو دليل أكيد لتقوى الله

الذين يؤمنون بالخفيات ، يصلون وينفقون مما أعطيناهم ،

الذين يؤمنون بما نزل عليك وما نزل من قبلك ويقتنعون بالآخرة.

إنهم يتبعون التوجيه الصحيح من ربهم وهم ناجحون.

إن الكافرين لا يأبهون أن تنذرهم أم لا. ما زالوا لا يؤمنون.

2022-09-15 10:01 UTC, BeebBeebBoob requested changes

2022-09-15 10:01 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/food.dm
>  /datum/reagent/consumable/sugar/overdose_process(mob/living/M, severity)
и ты кстати можешь использовать `severity` которая определяется по такой формуле
```
R.volume >= R.overdose_threshold * 2 ? 2 : 1
```

2022-09-15 10:01 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/food.dm
>  		M.reagents.add_reagent("epinephrine", 1.2)
```suggestion
		M.reagents.add_reagent("epinephrine", 1.2)
		return ..() | update_flags
```

2022-09-15 10:01 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/food.dm
>  	nutriment_factor = 5 * REAGENTS_METABOLISM
```suggestion
	nutriment_factor = 5 * REAGENTS_METABOLISM
	overdose_threshold = 80 // Hyperglycaemic shock
```

2022-09-15 10:02 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/food.dm
>  /datum/reagent/consumable/sugar/overdose_process(mob/living/M, severity)
в overdose_process()

2022-09-15 10:09 UTC, Honker9999999 commented on code/modules/reagents/chemistry/reagents/food.dm
>  /datum/reagent/consumable/sugar/overdose_process(mob/living/M, severity)
Знаю, но он просто не особо полезный и по сути нигде и не используется, кроме этого же сахара (вроде бы)

2022-09-17 15:57 UTC, larentoun requested changes

2022-09-17 15:57 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/food.dm
> +	var/obj/item/organ/internal/kidneys/K = M.get_int_organ(/obj/item/organ/internal/kidneys)
Нет проверки, что L или K - нуллы, а они используются впереди.

2022-09-17 15:57 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/food.dm
> +					update_flags |= M.AdjustStunned(2, FALSE)
Ты не задал переменную update_flags

2022-09-17 21:25 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/food.dm
> +					update_flags |= M.AdjustStunned(2, FALSE)
это я профукал. щас ...

2022-09-17 21:28 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/food.dm
>  /datum/reagent/consumable/sugar/overdose_process(mob/living/M, severity)
```suggestion
/datum/reagent/consumable/sugar/overdose_process(mob/living/M, severity)
	var/update_flags = STATUS_UPDATE_NONE
```

2024-02-12 20:59 UTC, closed without merging