feat: tgui multitool menu
ss220-space/Paradise pull request #1339
Opened 2022-09-15 11:41 UTC by yosoyrebelde

## What Does This PR Do
Добавлен tgui интерфейс мультитула.

Заменены интерфейсы меню мультитула для:
/obj/machinery/atmospherics/unary/vent_pump
/obj/machinery/atmospherics/unary/vent_scrubber
/obj/machinery/atmospherics/unary/outlet_injector
/obj/machinery/atmospherics/binary/dp_vent_pump (хотя это бесполезно, она на данный момент никуда не подключается)
/obj/machinery/air_sensor
/obj/machinery/computer/general_air_control
/obj/machinery/computer/general_air_control/large_tank_control
/obj/machinery/mass_driver
/obj/machinery/driver_button (вырезана возможность устанавливать logic connection, причина: фича неактуальна)

Вырезаны интерфейсы меню мультитула (причина: фича неактуальна):
/obj/machinery/light_switch
/obj/machinery/power/emitter
/obj/machinery/meter
/obj/machinery/atmospherics/binary/valve/digital

Другие изменения:
Что-либо настроить через меню мультитула можно только если у игрока есть доступ инженера или главы.
Пофикшено подключение vent_pump к large_tank_control, теперь всё линкуется без проблем.

## Why It's Good For The Game
Новый интерфейсик красивее, чем старый.
Будет проще добавлять новые линк-менюшки.

## Images of changes
Выглядит как-то так
![mtool_expl_final](https://user-images.githubusercontent.com/79848183/190392792-554d03c4-f2f0-4a02-bcea-54011180d938.jpg)

## Changelog
:cl:
add: tgui multitool menu
fix: link between vent_pump and large_tank_control
/:cl:

2022-09-15 11:56 UTC, dj-34 commented
Помоему слишком выкручена контрастность у кнопок, или проблема в самом скриншоте?

Для примера скину другой интерфейс
![image](https://user-images.githubusercontent.com/20109643/190397213-4e87a78f-22b4-440f-ab29-ebc869b1b08b.png)

2022-09-15 12:01 UTC, yosoyrebelde commented
> Помоему слишком выкручена контрастность у кнопок, или проблема в самом скриншоте?
Это не контрастность, просто другой цвет.

2022-09-15 12:46 UTC, BeebBeebBoob commented
Кек

2022-09-15 12:50 UTC, BeebBeebBoob commented
А..
Проверка на доступ как-то не вижу. Либо поиск не пробивает место где это прописано. оно в js?
Ибо я вижу что добавлено, но к примеру в каком либо interact нету

2022-09-15 12:55 UTC, BeebBeebBoob commented
А нет, он уже прописан но не тобой видимо :Starage:

2022-09-15 13:09 UTC, yosoyrebelde commented
> А.. Проверка на доступ как-то не вижу. Либо поиск не пробивает место где это прописано. оно в js? Ибо я вижу что добавлено, но к примеру в каком либо interact нету

get_menu_id возвращает "access_denied", если нет доступа, и потом в js рисуется надпись "access denied".
И в ui_act ещё одна проверка, не даёт без доступа нажать на кнопочки "добавить/удалить из буфера".
![accden](https://user-images.githubusercontent.com/79848183/190411645-c330d9fc-3532-42db-b9ce-94fde4bb70e3.jpg)

2022-09-15 13:11 UTC, BeebBeebBoob requested changes

2022-09-15 13:11 UTC, BeebBeebBoob commented on code/game/objects/objs.dm
> +	var/datum/multitool_menu/multitool_menu
Меня это настораживает что оно именно здесь, а нельзя ли в obj/machinary?

2022-09-15 13:11 UTC, BeebBeebBoob commented on code/game/objects/objs.dm
> +	return
Не видел что есть машинарии который не идёт по obj/machinary и использует этот прок.
Считаю что не будет проблем если перетащить все и вся про это в obj/machinary

2022-09-15 13:19 UTC, yosoyrebelde commented on code/game/objects/objs.dm
> +	return
> Не видел что есть машинарии который не идёт по obj/machinary и использует этот прок. Считаю что не будет проблем если перетащить все и вся про это в obj/machinary

Оно делалось именно в /obj с рассчетом на то, что могут понадобиться менюшки не только для machinery.
Например, для obj/structure/door_assembly или /obj/item/airlock_electronics для привязки аирлоков к кнопочкам.

2022-09-15 13:29 UTC, BeebBeebBoob commented on code/game/objects/objs.dm
> +	return
Это да, но все таки этого нету в этом пре и по сути у каждого объекта будет плюс один пустой и без задач переменная multitool_menu. Если кто-то решится так сделать то он вернёт назад в /obj.

2022-09-15 14:01 UTC, yosoyrebelde commented on code/game/objects/objs.dm
> +	return
Сделано.

2022-09-17 15:38 UTC, larentoun requested changes
В целом, очень неплохо. Функциональность не проверяла, позже может проверю

2022-09-17 15:38 UTC, larentoun commented on code/modules/power/singularity/emitter.dm
> +	req_access_txt = "11"
Почему бы не использовать макрос ACCESS_ENGINE_EQUIP?

2022-09-17 15:38 UTC, larentoun commented on code/modules/power/singularity/emitter.dm
>  	if(istype(W, /obj/item/wrench))
Пока ты тут, мог бы вынести в прок wrench_act()

2022-09-17 15:38 UTC, larentoun commented on code/datums/multitool_menu.dm
> +	if(!(user && istype(user)))
istype(user) уже проверяет на то, есть ли user, и является ли он нужным типом (в данном случае, mob)

2022-09-17 15:38 UTC, larentoun commented on code/datums/multitool_menu.dm
> +	if(!(my_multitool && istype(my_multitool)))
istype(my_multitool) уже проверяет на то, есть ли my_multitool, и является ли он нужным типом (в данном случае, obj/item/multitool)

2022-09-17 15:38 UTC, larentoun commented on code/datums/multitool_menu.dm
> +/datum/multitool_menu/proc/notify_if_it_is_not_ok_to_apply_changes(mob/user)
Слишком длинное название

2022-09-17 15:38 UTC, larentoun commented on code/datums/multitool_menu.dm
> +	if(!is_the_tag_unique(new_tag, my_holder.frequency))
Обычно в названия функций/переменных не задают артикли (the, a, an...)

2022-09-17 15:38 UTC, larentoun commented on code/datums/multitool_menu.dm
> +			if(!sensors.len)
Нынче модно использовать length() вместо .len, так как он менее уязвим к нуллам и немногим быстрее

2022-09-17 15:38 UTC, larentoun commented on code/game/machinery/atmo_control.dm
>  	if(istype(I, /obj/item/multitool))
У нас же вроде есть multitool_act()?

2022-09-17 15:38 UTC, larentoun commented on code/game/machinery/atmo_control.dm
>  	if(istype(I, /obj/item/multitool))
multitool_act()?

2022-09-17 15:38 UTC, larentoun commented on code/game/machinery/atmo_control.dm
> +		//update_multitool_menu(user)
Зачем оставлять закомменченный код? Ну и multitool_act()

2022-09-17 15:38 UTC, larentoun commented on code/game/machinery/atmoalter/meter.dm
>  	if(!istype(W, /obj/item/wrench))
wrench_act()

2022-09-17 15:38 UTC, larentoun commented on code/game/machinery/buttons.dm
>  	if(istype(W, /obj/item/wrench))
wrench_act()

2022-09-17 15:38 UTC, larentoun commented on code/game/machinery/buttons.dm
>  	if(istype(W, /obj/item/multitool))
multitool_act()

2022-09-17 15:38 UTC, larentoun commented on code/game/machinery/mass_driver.dm
>  	if(istype(W, /obj/item/multitool))
multitool_act()

2022-09-17 15:38 UTC, larentoun commented on code/game/machinery/mass_driver.dm
>  	if(istype(W, /obj/item/screwdriver))
screwdriver_act()

2022-09-17 15:41 UTC, larentoun commented
Ну и реши конфликты, обнови тгуи бандл

2022-09-17 16:22 UTC, yosoyrebelde commented on code/modules/power/singularity/emitter.dm
> +	req_access_txt = "11"
Потому что так список req_access будет создан только тогда, когда он понадобится.

2022-09-17 16:31 UTC, larentoun commented on code/modules/power/singularity/emitter.dm
> +	req_access_txt = "11"
Так я имею ввиду макрос, чтобы заменить волшебное число "11" на [ACCESS_ENGINE_EQUIP], что более читаемо

2022-09-24 14:53 UTC, larentoun requested changes

2022-09-24 14:53 UTC, larentoun commented on code/ATMOSPHERICS/components/unary_devices/outlet_injector.dm
>  	if(istype(W, /obj/item/wrench))
Можно было бы поменять на wrench_act() за одно, никто кроме тебя сюда не вернется в близлежащее время

2022-09-24 14:53 UTC, larentoun commented on code/ATMOSPHERICS/components/unary_devices/vent_pump.dm
>  	if(istype(W, /obj/item/wrench))
wrench_act()

2022-09-24 14:53 UTC, larentoun commented on code/ATMOSPHERICS/components/unary_devices/vent_scrubber.dm
>  	if(istype(W, /obj/item/wrench))
wrench_act()

2022-09-24 14:53 UTC, larentoun commented on code/modules/power/singularity/emitter.dm
>  	if(istype(W, /obj/item/card/id) || istype(W, /obj/item/pda))
W.GetID() - недавно обновленная функция, которая позволяет читать ИД карту с любого места.
Также новый макрос ispda()

```suggestion
	if(W.GetID() || ispda(W))
```

2022-09-24 15:32 UTC, yosoyrebelde commented on code/ATMOSPHERICS/components/unary_devices/outlet_injector.dm
>  	if(istype(W, /obj/item/wrench))
Там только одна проверка и вызов attackby родителя, конкретно в /obj/machinery/atmospherics всё остальное прописано. Так что не получится только здесь заменить, нужно будет менять в /obj/machinery/atmospherics и в каждой штуке, которая от неё наследуется.
А ПР так-то не про рефактор всей атмосферной машинерии.

2022-09-24 15:32 UTC, yosoyrebelde commented on code/ATMOSPHERICS/components/unary_devices/vent_pump.dm
>  	if(istype(W, /obj/item/wrench))
Аналогично.

2022-09-24 15:32 UTC, yosoyrebelde commented on code/ATMOSPHERICS/components/unary_devices/vent_scrubber.dm
>  	if(istype(W, /obj/item/wrench))
Аналогично.

2022-09-24 16:44 UTC, larentoun commented on code/ATMOSPHERICS/components/unary_devices/outlet_injector.dm
>  	if(istype(W, /obj/item/wrench))
Жаль

2022-09-24 16:44 UTC, larentoun approved these changes

2022-10-03 13:42 UTC, merged