feat: Ученики мага при ХАЙПОПе
ss220-space/Paradise pull request #1344
Opened 2022-09-17 12:43 UTC by PhantornRU

Авоут пройден и одобрен:
https://discord.com/channels/617003227182792704/755125334097133628/1020299400708366356

## What Does This PR Do
- Добавление учеников к гейм-моду мага при ХАЙПОПЕ.
- Ученики появляются раундстартово и получают цель на защиту учителя. Если учитель меняет имя, имя меняется на цели.
- Ученики по прежнему не могут трогать учительские вещи.
- В антаг-панеле, персонажу можно выдать роль мага или роль ученика. Только что-то одно.
- При выдаче ролей ученика, он подстраивается под свой лодаут.
- Добавление отдельного фиолетового магического учебника для ученика мага, позволяющего выбирать наборы заклинаний.
- Внесение учеников в разные "мероприятия".
- Небольшой рефактор контрактов для более удобного наследования и переделывания.
- Расширение магического автомата, чтобы ученики тоже могли переодеться.  Добавление магических вещей, ранее не участвующих ни в чем и просто висящие в билде без дела.
- Одежда в магическом автомате с 1 штуки повышена до 5 штук.
- Фикс ЭПИЧЕСКИХ пятюнь которые вызывали некорректные ЭПИЧЕСКИЕ взрывы. Дополнение их учениками.

После 50 человек, каждые 25 человек, вместе с магом будут также появляться его ученики (выбираются из лобби, как и маг).
Напомню, ученики имеют 1 свиток телепорта и 1 из 4-х наборов заклинаний.

### Пропорции:
<49 - 1 маг, 0 учеников
50-74 - 1 маг, 1 ученик
75-99 - 1 маг, 2 ученика
100< - 1 маг, 3 ученика

## Why It's Good For The Game
- Теперь погибший маг на хайпопе от толпы асистух/СБух - не означает эксту
- Люди теперь больше приспособлены к магам, так как больше за них играют.

## Images of changes

![image](https://user-images.githubusercontent.com/41479614/190857280-c8c46fee-d219-445a-b533-ae30a2fc647e.png)
![image](https://user-images.githubusercontent.com/41479614/190857318-f84a17f9-9e27-4c00-ab8d-0056b328b808.png)
![image](https://user-images.githubusercontent.com/41479614/190857378-001b3535-d833-4b08-8935-45d07b20cb07.png)

2022-09-17 15:54 UTC, larentoun requested changes

2022-09-17 15:54 UTC, larentoun commented on code/datums/mind.dm
> +		. += "<b><font color='red'>WIZARD APPRENTICE</font></b>|<a href='?src=[UID()];wizard=clear'>no</a>"
Я так понимаю, span class не работает?

2022-09-17 15:54 UTC, larentoun commented on code/datums/mind.dm
> +		if(objectives.len==0)
Ну, можно было бы проверять на наличие длины, а не ее равность нулю

2022-09-17 15:54 UTC, larentoun commented on code/datums/mind.dm
> +					to_chat(current, "<span class='warning'><FONT size = 3><B>You have been brainwashed! You are no longer a apprentice wizard!</B></FONT></span>")
Почему бы не использовать danger вместо warning? Насколько я помню, он как раз увеличивает размер текста

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	if(!istype(teacher, /mob/living/carbon/human))
ishuman()

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	var/mob/living/carbon/human/teacher = usr
А проверка на то, что он хуман не нужна, точно?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	if(loc == teacher || (in_range(src, teacher) && istype(loc, /turf)))
isturf()

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				to_chat(teacher, "You already used this contract!")
Span class notice/warning?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +			to_chat(teacher, "apprentice waiting...")
Span class notice?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +			if(candidates.len)
Все еще рекомендую length(), на случай, если candidates будет null

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				var/mob/living/carbon/human/apprentice = new/mob/living/carbon/human(teacher.loc)
Может лучше в турфе тичера, а не в локе? А если он в мехе, шкафу, роде и тд?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				to_chat(apprentice, "<B>You are the [teacher.real_name]'s apprentice! You are bound by magic contract to follow [teacher.p_their()] orders and help [teacher.p_them()] in accomplishing their goals
Span class, тот же danger?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				new_objective.owner = apprentice:mind
Уверен ли ты, что хочешь использовать : вместо .

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				to_chat(teacher, "Unable to reach your apprentice! You can either attack the spellbook with the contract to refund your points, or wait and try again later.")
Span class?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	if(!istype(apprentice, /mob/living/carbon/human))
ishuman()

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	var/mob/living/carbon/human/apprentice = usr
Точно уверен, что всегда будет хуманом?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	if(loc == apprentice || (in_range(src, apprentice) && istype(loc, /turf)))
isturf()

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				to_chat(apprentice, "Учебник уже был вами изучен!")
span class?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +/obj/item/contract/proc/school_href_choose(href_list, var/mob/living/carbon/human/teacher, var/mob/living/carbon/human/apprentice)
можно без var/

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				to_chat(teacher, "<B>Your service has not gone unrewarded, however. Studying under [teacher.real_name], you have learned powerful, destructive spells. You are able to cast magic missile and fireb
span class?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				to_chat(teacher, "<B>Your service has not gone unrewarded, however. Studying under [teacher.real_name], you have learned reality bending mobility spells. You are able to cast teleport and etherea
span class?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				to_chat(teacher, "<B>Your service has not gone unrewarded, however. Studying under [teacher.real_name], you have learned livesaving survival spells. You are able to cast charge and forcewall.")
span class?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				to_chat(teacher, "<B>Your service has not gone unrewarded, however. Studying under [teacher.real_name], you have learned stealthy, robeless spells. You are able to cast knock and mindswap.")
span class?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	return "<B>You have already summoned your apprentice.</B><BR>"
span class?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	return "<B>Вами уже был изучен учебник.</B><BR>"
span class?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	return dat
span class?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	return dat
span class?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/wizard.dm
> +			if(possible_wizards.len==0)
Можно просто проверку на длину, а не сравнивать с нулем

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/wizard.dm
> +	if(isplasmaman(wizard_mob))
На воксов проверка не нужна?

2022-09-17 15:54 UTC, larentoun commented on code/game/gamemodes/wizard/wizard.dm
> +	to_chat(wizard_mob, "Вы найдёте набор из доступных закинаний в вашем магическом учебнике.")
span calss

2022-09-17 15:54 UTC, larentoun commented on data/mode.txt
> +secret
:XMM:

2022-09-18 08:31 UTC, PhantornRU commented on code/datums/mind.dm
> +					to_chat(current, "<span class='warning'><FONT size = 3><B>You have been brainwashed! You are no longer a apprentice wizard!</B></FONT></span>")
То что было изначально в коде, то и оставил, дабы не было возмущений о "НИЕЕЕТ, ТЫ ПЕРЕДЕЛАЛ НЕ ПО ПРЕДЛОЖКЕ" и мгновенного отката.

2022-09-18 13:15 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +	var/mob/living/carbon/human/teacher = usr
А как ты заюзаешь предмет в руке, не будучи хуманом?

2022-09-18 13:16 UTC, PhantornRU commented on code/datums/mind.dm
> +		. += "<b><font color='red'>WIZARD APPRENTICE</font></b>|<a href='?src=[UID()];wizard=clear'>no</a>"
Он выдает не совсем то что хотелось бы видеть + это оригинальный код. Оставлено во избежании изменений в шрифтах и жалоб.

2022-09-18 13:18 UTC, PhantornRU commented on code/datums/mind.dm
> +		if(objectives.len==0)
нужно провести рефактор всех упоминаний. Я не могу провести рефактор в данном ПРе для всех таких проверок, необходим отдельный ПР.
Иначе меня опять будут ругать что всё в одном смешиваю.

2022-09-18 13:19 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +	if(!istype(teacher, /mob/living/carbon/human))
Поправлено

2022-09-18 13:20 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +	if(loc == teacher || (in_range(src, teacher) && istype(loc, /turf)))
Исправлено

2022-09-18 13:21 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +			if(candidates.len)
заменил

2022-09-18 13:23 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +				var/mob/living/carbon/human/apprentice = new/mob/living/carbon/human(teacher.loc)
Свиток юзается в Wizard's Den. Там есть только 1 шкаф. Но даже в шкафе он корректно ставит.
В роде нельзя заюзать свиток.
Магу нельзя в мехов.

+ это оригинальный код, не трогал его.

2022-09-18 13:24 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +				new_objective.owner = apprentice:mind
Это оригинальный код. Я вообще без понятия что оно делает. В другом месте я это выпилил. Тут код оставлен.

2022-09-18 13:26 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +	if(!istype(apprentice, /mob/living/carbon/human))
Исправлено

2022-09-18 13:26 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +	var/mob/living/carbon/human/apprentice = usr
Ты не сможешь использовать книжку в другом облике

2022-09-18 13:28 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +	if(loc == apprentice || (in_range(src, apprentice) && istype(loc, /turf)))
Исправлено

2022-09-18 13:28 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +/obj/item/contract/proc/school_href_choose(href_list, var/mob/living/carbon/human/teacher, var/mob/living/carbon/human/apprentice)
действительно. Поправил.

2022-09-18 13:30 UTC, PhantornRU commented on code/game/gamemodes/wizard/wizard.dm
> +			if(possible_wizards.len==0)
Исправил

2022-09-18 13:36 UTC, PhantornRU commented on code/game/gamemodes/wizard/wizard.dm
> +	if(isplasmaman(wizard_mob))
Внёс для воксов

2022-09-18 13:36 UTC, PhantornRU commented on data/mode.txt
> +secret
блят откуда, я ж убирал >:C

2022-09-18 14:55 UTC, larentoun commented on code/datums/mind.dm
> +		if(objectives.len==0)
Не пинают за рефакторы

2022-09-18 15:12 UTC, larentoun commented on code/datums/mind.dm
> +					to_chat(current, "<span class='warning'><FONT size = 3><B>You have been brainwashed! You are no longer a apprentice wizard!</B></FONT></span>")
Не стоит добавлять фичи, да. Но код-стандарты никто не отменял

2022-09-18 15:12 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	var/mob/living/carbon/human/teacher = usr
Возможно педальская магия. В любом случае, желательно сначала делать на тип перед тем, как приравнивать к этому типу

2022-09-18 15:13 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				var/mob/living/carbon/human/apprentice = new/mob/living/carbon/human(teacher.loc)
Всё же лучше добавить защиту от дурака, а то появятся магические мехи и всё, капут

2022-09-18 15:14 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +				new_objective.owner = apprentice:mind
Ошибки с `:` буду замечены только в рантайме. Следовало изучить этот вопрос. Советую сменить на `.` для большей надежности.

2022-09-18 15:14 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	var/mob/living/carbon/human/apprentice = usr
Руки есть не только у хуманов

2022-09-19 11:13 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +	var/mob/living/carbon/human/teacher = usr
![image](https://user-images.githubusercontent.com/41479614/191005420-9091ef32-51f6-4421-8dd8-2e68e032e87e.png)

Так я так и так проверку на потом выношу. Её же достаточно всегда бывает.

2022-09-19 11:15 UTC, PhantornRU commented on code/datums/mind.dm
> +					to_chat(current, "<span class='warning'><FONT size = 3><B>You have been brainwashed! You are no longer a apprentice wizard!</B></FONT></span>")
И то верно. Тогда Впишу спан классы.

2022-09-19 11:15 UTC, PhantornRU commented on code/datums/mind.dm
> +		if(objectives.len==0)
И то верно. Тогда Впишу спан классы и проведу небольшие рефакторы.

2022-09-19 11:49 UTC, PhantornRU commented on code/datums/mind.dm
> +		. += "<b><font color='red'>WIZARD APPRENTICE</font></b>|<a href='?src=[UID()];wizard=clear'>no</a>"
Заменен на спан

2022-09-19 11:49 UTC, PhantornRU commented on code/datums/mind.dm
> +		if(objectives.len==0)
Внесена проверка от длины

2022-09-19 12:00 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +				to_chat(apprentice, "<B>You are the [teacher.real_name]'s apprentice! You are bound by magic contract to follow [teacher.p_their()] orders and help [teacher.p_them()] in accomplishing their goals
Нотис вставил.

2022-09-19 12:01 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +				new_objective.owner = apprentice:mind
исправил

2022-09-19 12:02 UTC, PhantornRU commented on code/game/gamemodes/wizard/apprentice.dm
> +	var/mob/living/carbon/human/apprentice = usr
Для тех у кого ручки - всеравно нельзя пользоваться.
![image](https://user-images.githubusercontent.com/41479614/191012749-76a05bf0-9e8f-4fbe-ab6e-959d7f6bf815.png)

2022-09-19 12:42 UTC, PhantornRU commented
@larentoun внёс спан классы, отрефакторил всё-таки обжективы.

А еще красивый пикч добавил :)))

2022-09-19 18:12 UTC, larentoun requested changes
Ну, вроде последнее

2022-09-19 18:12 UTC, larentoun commented on code/datums/mind.dm
> +		if(!length(objectives.len))
Аа... Эээ... А зачем дважды длина?)
Хватило бы просто length(objectives), так как objectives задается ведь как лист

Ну и далее тоже пофиксить этот прикол, на каждый оставлять не буду коммент

2022-09-19 18:12 UTC, larentoun commented on code/game/gamemodes/wizard/apprentice.dm
> +	var/mob/living/carbon/human/teacher = usr
А, ну, я бы тогда проверку хумана просто выше бы переставила

2022-09-20 01:30 UTC, PhantornRU commented on code/datums/mind.dm
> +		if(!length(objectives.len))
Действительно, очепятался, заменил

2022-09-20 01:33 UTC, PhantornRU commented on code/datums/mind.dm
> +		if(!length(objectives.len))
Done

2022-09-20 10:52 UTC, larentoun approved these changes
Ну, на мой скромный взгляд, вроде нормально

2022-10-14 08:26 UTC, merged