Очередной катч на ниндзя и сканер для сб
ss220-space/Paradise pull request #1349
Opened 2022-09-19 15:24 UTC by Furukia

## What Does This PR Do
* Добавлен радио канал Клана паука и встроен в наушник ниндзя и его борга.
* Добавлена возможность телепортировать с собой катаной людей которых ниндзя тащит за собой (Не граб) по аналогии с палочкой телепорта культистов
* Для СБ добавлен Специальный сканер для обнаружение невидимых. Производится в рнд. Требуемые технологии: "combat" = 4, "magnets" = 7, "biotech" = 7
* Потенциально убран баг не дававший иногда гринтексту ниндзя появиться.
![Сканер](https://user-images.githubusercontent.com/67807868/191053708-6e458289-cbcc-42c6-9365-a3181d523bc5.gif)
![2022-09-19_13-26-30](https://user-images.githubusercontent.com/67807868/191053749-1cd68942-5542-461d-b9d0-72a0c6a43a80.png)

2022-09-19 17:35 UTC, Den109G commented on code/game/gamemodes/spaceninja/ninja/suit/headset.dm
> +	set_frequency(NINJA_FREQ)
А обязательно при инициализации прок делать, а не в самом предмете указать `frequency =`?

2022-09-19 18:40 UTC, larentoun requested changes

2022-09-19 18:40 UTC, larentoun commented on code/datums/dash_weapon.dm
> +		if(pulled_mob && istype(pulled_mob))
Разве istype() уже не проверяет на нулл?

2022-09-19 18:40 UTC, larentoun commented on code/game/gamemodes/spaceninja/space_ninja.dm
> +			if(ninja_datum && istype(ninja_datum)) // Защита от рантаймов в случае если по какой то причине он не прочитает датум
istype() уже проверяет на нулл

2022-09-19 18:40 UTC, larentoun commented on code/game/objects/items/devices/scanners.dm
> +		for(var/mob/living/in_turf_mob in scan_turf.contents)
Нету ли способа лучше, чем искать содержимое турфа? Уже предвижу ситуации, где насрано под 100 бананов в один тайл, и на каждый делать проверку istype()

2022-09-20 04:24 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/suit/headset.dm
> +	set_frequency(NINJA_FREQ)
В самом коде прока set_frequency происходит больше, чем просто замена параметра. Мне кажется так правильнее.

2022-09-20 04:26 UTC, Furukia commented on code/game/objects/items/devices/scanners.dm
> +		for(var/mob/living/in_turf_mob in scan_turf.contents)
Если есть, я буду рада его услышать.

2022-09-20 04:26 UTC, Furukia commented on code/game/gamemodes/spaceninja/space_ninja.dm
> +			if(ninja_datum && istype(ninja_datum)) // Защита от рантаймов в случае если по какой то причине он не прочитает датум
Поправлю

2022-09-20 04:26 UTC, Furukia commented on code/datums/dash_weapon.dm
> +		if(pulled_mob && istype(pulled_mob))
Поправлю

2022-09-20 05:42 UTC, Den109G commented on code/game/gamemodes/spaceninja/ninja/suit/suit.dm
> +	if(ninja.alpha != 255 || ninja.alpha != 64)
Одного `.alpha != 255` не хватает? Или вообще убрать проверку на alpha?
Пока что, предлагаю объединить оба варианта.
```suggestion
	if(ninja.alpha)
```
Просто сейчас эта проверка постоянно будет проходить, независимо какая альфа у ниндзи, что теряет смысл в этом if-е (Будет 255 - левое условие вернёт FALSE, но правое вернёт TRUE. Будет 64 - левое вернёт TRUE, а правое FALSE. Будет любое другое значение - оба вернут TRUE. Зачем усложнять?).

2022-09-20 06:30 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/suit/suit.dm
> +	if(ninja.alpha != 255 || ninja.alpha != 64)
Не хватает. Есть шанс, что багнется альфа от формы духа тоже.  Представь. У тебя проверяется в целом наличие альфы. Ты в форме духа с альфой 64 прошёл мимо сканера. Сканер тебе повысил её до 255. ты вырубил форму духа. Сканер вернул её тебе до 64. Это не инвиз, но ты уже прозрачен, что баг.

А по поводу просто альфу в писать. Если у тебя проверка на наличие альфы, а инвиз её сбрасывает в ноль, но у тебя её нет. т.е. ты не входишь в `if`. А значит при баге с инвизом, ты не пофиксишь его автоматом... Так как баг выкрутит её в 0 на постоянку. Если же сделать инвертировано, с `!alpha`, то при приколе со спирит формой, ты не пофиксишь её баг, так как там уже 64.

Короче говоря проверки на две точные альфы, нужны потому, что это нормальные варианты альфы для ниндзя. Остальные - отклонение и уже идёт проверка, допустимо ли отклонение через `if(!stealth && !spirited)` где стелс - допускает его, а спиритед там на всякий случай, если вдруг с ним тоже, что-то пойдёт не так, но прошлая проверка почему то будет пройдена. (Никогда не знаешь...)

2022-09-20 06:37 UTC, Vallat commented
Печально, что код подобного качества попадает в билд и уважаемым СА абсолютно плевать на это. Такими темпами, технический долг достигнет невообразимых масштабов куда быстрее и уже в скором времени билд будет проще выкинуть на помойку истории, вместе со всеми вложенными в него усилиями, чем рефакторить всё это. ☹️

2022-09-20 06:51 UTC, Furukia commented
> Печально, что код подобного качества попадает в билд и уважаемым СА абсолютно плевать на это. Такими темпами, технический долг достигнет невообразимых масштабов куда быстрее и уже в скором времени билд будет проще выкинуть на помойку истории, вместе со всеми вложенными в него усилиями, чем рефакторить всё это. ☹️

Если тебя так сильно не устраивает код, у тебя есть все возможность сделать ревью, указать на ошибки и объяснить что тебя не устраивает человеку в спокойной и вежливой манере. Но вместо этого ты пишешь подобные сообщения. Не показывая ничего кроме пассивной агрессии.

2022-09-20 07:30 UTC, Vallat commented
> Если тебя так сильно не устраивает код, у тебя есть все возможность сделать ревью, указать на ошибки и объяснить что тебя не устраивает человеку в спокойной и вежливой манере. Но вместо этого ты пишешь подобные сообщения. Не показывая ничего кроме пассивной агрессии.

Это не агрессия, это просто небольшой выплеск моего недовольства, не более. Ревью я теперь делаю только по личным запросам с помощью разобраться в коде, но у тебя в принципе еще год назад уже были "высокие познания в бьенде", так что вряд ли тебе нужна какая-то помощь, вон, идентичные тебе люди накодили целый фарвеб. И работает ведь! Круто, правда?
Честно - просто грустно наблюдать за этим, если можно так выразиться, пиром во время чумы. Курс на потопление был заложен и менять его никто не собирается, люди только рады тому, что "фичи пиляца". А уж с каким качеством - никого не волнует.

2022-09-20 07:51 UTC, Furukia commented
> > Если тебя так сильно не устраивает код, у тебя есть все возможность сделать ревью, указать на ошибки и объяснить что тебя не устраивает человеку в спокойной и вежливой манере. Но вместо этого ты пишешь подобные сообщения. Не показывая ничего кроме пассивной агрессии.
> 
> Это не агрессия, это просто небольшой выплеск моего недовольства, не более. Ревью я теперь делаю только по личным запросам с помощью разобраться в коде, но у тебя в принципе еще год назад уже были "высокие познания в бьенде", так что вряд ли тебе нужна какая-то помощь, вон, идентичные тебе люди накодили целый фарвеб. И работает ведь! Круто, правда? Честно - просто грустно наблюдать за этим, если можно так выразиться, пиром во время чумы. Курс на потопление был заложен и менять его никто не собирается, люди только рады тому, что "фичи пиляца". А уж с каким качеством - никого не волнует.

Было бы тебе приятно обращаться за помощью к человеку, который ведёт себя в разговорах с тобой вот так? Я обращалась за помощью когда надо к Семоро, пару раз к Азизу, сама стараюсь делать свой код лучше, хоть и всё ещё совершаю много ошибок, будь то по невнимательности или неопытности, спору нет. Но я не вижу никакой пользы в этой напыщенности и агрессии идущей от тебя в мою сторону, в сторону кода, в сторону билда. Она не несёт ничего. Никакой пользы. Она не делает код лучше, она не помогает билду. Она лишь способствует потоплению.

Я никогда не говорила что у меня высокие познания в бьёнде. И уж тем более не превозносила себя перед другими из-за моих "фич". Да они сделали меня заметной. Фичи такого масштаба всегда замечают, это факт и тут ничего не поделать. Я занимаюсь всем этим добровольно, вкладывая душу в то что я делаю. Осваивая многое в процессе. Правлю ошибки и т.д. Я могла бы тоже забить на всё болт, просто скопипастить ниндзя с того же ТГ или Оникса без изменений. Вместо тайпана, тупо вставить говно-карту с оффов пары с коробкой в астероиде. 

Ко мне часто предъявляют претензии потому, что я редко делаю баг фиксы в чужом коде, редко рефакторю его и т.д. Но, чему я поражаюсь, так это тому, что у нас многие другие разработчики тоже этим не занимаются и их никого на это не мотивируют. Зато добрая половина предъяв летят в мою сторону. С язвой и токсом. Просто потому, что я занималась приятными мне "фичами" тратя на это месяцы реальной жизни. И их заметили. Вместо того чтобы заниматься рефактором кода, на который и у других то разрабов редко есть силы, время или желание.

2022-09-20 08:23 UTC, PhantornRU commented
Ну не ругайтися.
Парадайз - это испытательный ядерный полигон. Мы просто проверяем на нём новые механики. А потом магическим образом перейдём на новый билд и точно-точно не будет больше говнокодить, когда будем переносить новые механики! :)

2022-09-20 08:25 UTC, Gaxeer commented
> Ну не ругайтися. Парадайз - это испытательный ядерный полигон. Мы просто проверяем на нём новые механики. А потом магическим образом перейдём на новый билд и точно-точно не будет больше говнокодить, когда будем переносить новые механики! :)

По щелчку пальцев

2022-09-20 08:26 UTC, Gaxeer commented
> > > Если тебя так сильно не устраивает код, у тебя есть все возможность сделать ревью, указать на ошибки и объяснить что тебя не устраивает человеку в спокойной и вежливой манере. Но вместо этого ты пишешь подобные сообщения. Не показывая ничего кроме пассивной агрессии.
> > 
> > 
> > Это не агрессия, это просто небольшой выплеск моего недовольства, не более. Ревью я теперь делаю только по личным запросам с помощью разобраться в коде, но у тебя в принципе еще год назад уже были "высокие познания в бьенде", так что вряд ли тебе нужна какая-то помощь, вон, идентичные тебе люди накодили целый фарвеб. И работает ведь! Круто, правда? Честно - просто грустно наблюдать за этим, если можно так выразиться, пиром во время чумы. Курс на потопление был заложен и менять его никто не собирается, люди только рады тому, что "фичи пиляца". А уж с каким качеством - никого не волнует.
> 
> Было бы тебе приятно обращаться за помощью к человеку, который ведёт себя в разговорах с тобой вот так? Я обращалась за помощью когда надо к Семоро, пару раз к Азизу, сама стараюсь делать свой код лучше, хоть и всё ещё совершаю много ошибок, будь то по невнимательности или неопытности, спору нет. Но я не вижу никакой пользы в этой напыщенности и агрессии идущей от тебя в мою сторону, в сторону кода, в сторону билда. Она не несёт ничего. Никакой пользы. Она не делает код лучше, она не помогает билду. Она лишь способствует потоплению.
> 
> Я никогда не говорила что у меня высокие познания в бьёнде. И уж тем более не превозносила себя перед другими из-за моих "фич". Да они сделали меня заметной. Фичи такого масштаба всегда замечают, это факт и тут ничего не поделать. Я занимаюсь всем этим добровольно, вкладывая душу в то что я делаю. Осваивая многое в процессе. Правлю ошибки и т.д. Я могла бы тоже забить на всё болт, просто скопипастить ниндзя с того же ТГ или Оникса без изменений. Вместо тайпана, тупо вставить говно-карту с оффов пары с коробкой в астероиде.
> 
> Ко мне часто предъявляют претензии потому, что я редко делаю баг фиксы в чужом коде, редко рефакторю его и т.д. Но, чему я поражаюсь, так это тому, что у нас многие другие разработчики тоже этим не занимаются и их никого на это не мотивируют. Зато добрая половина предъяв летят в мою сторону. С язвой и токсом. Просто потому, что я занималась приятными мне "фичами" тратя на это месяцы реальной жизни. И их заметили. Вместо того чтобы заниматься рефактором кода, на который и у других то разрабов редко есть силы, время или желание.

Ты просто критику не воспринимаешь. Вот и все. И пытаешься высосать из пальца подтверждения своей правоты.

2022-09-20 08:26 UTC, PhantornRU commented
Именно так. Дружба - это творожок чудо и магия.

2022-09-20 08:27 UTC, Vallat commented
Ну давай поговорим начистоту, пора уже наверное начать высказывать всё, что на уме.

> Было бы тебе приятно обращаться за помощью к человеку, который ведёт себя в разговорах с тобой вот так? 

Напомнить, с чего всё началось? Быть может дело не только во мне, не думаешь? С большинством людей я всё же общаюсь вполне нормально 😉 

> Но я не вижу никакой пользы в этой напыщенности и агрессии идущей от тебя в мою сторону, в сторону кода, в сторону билда. Она не несёт ничего. Никакой пользы. Она не делает код лучше, она не помогает билду. Она лишь способствует потоплению.

Прости, но это не мой выбор. Я уже пытался что-либо изменить на пользу билда, меня весьма грубо заткнули. Чтож поделать, поэтому я и работаю теперь только с конкретными людьми. А насчет некой "агрессии" в твою сторону - у меня есть причины для личной неприязни. Увы, ничего не поделать, ты вряд ли изменишься. 

> Я никогда не говорила что у меня высокие познания в бьёнде. И уж тем более не превозносила себя перед другими из-за моих "фич". 

А, да? Жаль у меня сейчас нет доступа к дискорду, я бы обязательно ткнул тебя носом в твои же сообщения. Но я всё же не единственный человек, который почему-то запомнил, что ты такое писал :)
А нет, скриншотик таки нашелся. Если тогда у тебя уже был средне-высокий уровень, то сейчас, после стольких месяцев разработки крутых фич, небось уже почти гуру 🤡 
![image](https://user-images.githubusercontent.com/10997188/191207041-a6837d2e-529c-48d3-a837-4426a88e410b.png)


> Да они сделали меня заметной. Фичи такого масштаба всегда замечают, это факт и тут ничего не поделать. 

Да, ты прав, фичи такого масштаба всегда замечают. Замечают с двух сторон, с хорошей и плохой. Ты же игнорируешь последнюю в большинстве случаев, иначе бы тот же Тайпан уже удалили по твоей же инициативе.

> Я могла бы тоже забить на всё болт, просто скопипастить ниндзя с того же ТГ или Оникса без изменений. Вместо тайпана, тупо вставить говно-карту с оффов пары с коробкой в астероиде.

Для игроков и игры в целом именно так было бы лучше. Было бы лучше дать им уже сбалансированные и обкатанные фичи, чем без навыков и опыта пытаться срисовать и изобрести велосипед, что в итоге в перспективу выливается лишь в бОльшие проблемы.

> Ко мне часто предъявляют претензии потому, что я редко делаю баг фиксы в чужом коде, редко рефакторю его и т.д. Но, чему я поражаюсь, так это тому, что у нас многие другие разработчики тоже этим не занимаются и их никого на это не мотивируют. Зато добрая половина предъяв летят в мою сторону. С язвой и токсом. 

А знаешь, почему ты этого не делаешь? Потому что ты не можешь. Навыка не хватает, как и силы духа признать этого. Ну и ты точно не позиционируешь себя как **опытного разработчика**, правда-правда. Обрати хоть раз внимание на себя и подумай, откуда такое отношение - это не все вокруг язвы токсичные, которые твой труд не ценят 😉 

> Просто потому, что я занималась приятными мне "фичами" тратя на это месяцы реальной жизни. И их заметили. 

Один человек потратит на написание пейзажа Волги неделю и создаст произведение искусства. Другой человек потратит на написание того же пейзажа пол года и у него выйдет мазня без какого-либо смысла. Каждому из них его дело приятно, но второй же просит к себе внимания больше, ведь "он же старался" и "его картину выставили на общее обозрение".

2022-09-20 09:21 UTC, Furukia commented
> Напомнить, с чего всё началось? Быть может дело не только во мне, не думаешь? С большинством людей я всё же общаюсь вполне нормально 😉 

Оно и видно...

> Прости, но это не мой выбор. Я уже пытался что-либо изменить на пользу билда, меня весьма грубо заткнули. Чтож поделать, поэтому я и работаю теперь только с конкретными людьми. А насчет некой "агрессии" в твою сторону - у меня есть причины для личной неприязни. Увы, ничего не поделать, ты вряд ли изменишься.

Проще говоря, ты сдался и пошёл по пути разрушения. Не знаю где там тебя грубо заткнули, или это ты так припоминаешь как ты забил на правила дискорд сервера за что и получил кляп, а потом и вылетел за продолжение этой мазни. А на тему личного хейта. Если ты как человек позволяешь личной неприязни диктовать, как в рабочих вопросах относиться к другому человеку... Могу лишь посочувствовать. Я способна меняться, веришь ты или нет. Я меняю своё мнение и позицию, способна признать неправоту в аргументированных и конструктивных спорах, но я не собираюсь подстраиваться под подобное отношение и терпеть его. 

> А, да? Жаль у меня сейчас нет доступа к дискорду, я бы обязательно ткнул тебя носом в твои же сообщения. Но я всё же не единственный человек, который почему-то запомнил, что ты такое писал :)
А нет, один скриншотик таки нашелся. Если тогда у тебя уже был средне-высокий уровень, то сейчас, после стольких месяцев разработки крутых фич, небось уже почти гуру 🤡

И часто ты судишь людей по тому, что они писали месяцы или годы назад? Скриншотик я смотрю кстати свеженький, даже аватарка нынешняя, как мило. Злопамятность так и прёт. О нет, новенький разработчик поверил в свои силы и один раз написал, что его уровень средне-высокий. Прошлая я и нынешняя я - разные люди. И я удивлена, что такие очевидные вещи надо разжёвывать.

> Да, ты прав, фичи такого масштаба всегда замечают. Замечают с двух сторон, с хорошей и плохой. Ты же игнорируешь последнюю в большинстве случаев, иначе бы тот же Тайпан уже удалили по твоей же инициативе.

Терпеть не могу подход "Мне не нравится - удали нахой" Я не игнорирую плохие стороны. Я уделяю им внимание. Собираю целые блокноты с багами и когда есть время фикшу. У меня ещё есть куча других дел, личная жизнь, учёба и т.д. Так что извини, что не сделала всё отполированным до блеска сразу. А извиняться за то, что я не удаляю свой труд я не собираюсь.

> Для игроков и игры в целом именно так было бы лучше. Было бы лучше дать им уже сбалансированные и обкатанные фичи, чем без навыков и опыта пытаться срисовать и изобрести велосипед, что в итоге в перспективу выливается лишь в бОльшие проблемы.

🤡 Сбалансированные и отлаженные фичи. Ну ну. Всё же сразу должно быть обнаружено и отбаланшено. Кого волнует, что были и дооолгие плейтесты и куча других вещей. Куча проблем была найдена и пофикшена. Но предстваляешь как бывает. Когда тайпан был выкачен через месяца 3-4 тестов на мейны, резко появились проблемы которые просто не предвидели. И всё. Тайпан хуйня. Удаляй. 
Ты сам разработчик довольно большого проекта и по идее должен понимать, что не всё идёт по ровной белой дорожке и порой возникают ухабы и чёрные полосы. И то что у меня ухабы к сожалению были больше привычных тебе, не значит, что надо теперь всё нахуй бросить. Нет спасибо.

> А знаешь, почему ты этого не делаешь? Потому что ты не можешь. Навыка не хватает, как и силы духа признать этого. Ну и ты точно не позиционируешь себя как опытного разработчика, правда-правда. Обрати хоть раз внимание на себя и подумай, откуда такое отношение - это не все вокруг язвы токсичные, которые твой труд не ценят 😉

А когда я говорила, что у меня его хватает? Я делаю то, на что способна. И насколько могу повышаю свой навык. У меня есть желание заняться парой старых багов и неприятных вещей которые в нашем билде меня и не только давно калят. Но не поверишь, моя главная проблема - это время. И я своё время ценю. Кроме кодинга есть у меня в жизни и другие забавы и дела. А ещё есть такая штука - желание. И желания взять весь билд и переворотить стилистику всего кода у меня нет. Потому что я знаю, что это так же займёт дохуя времени которого у меня сейчас нет. Но почему то, опять же, это требуют с меня. Когда большинство разрабов - сидит на жопе ровно, пилят мелкие, не такие заметные, как мои - фичи и предьявляют другим. Я не спорю. Есть те кто сидят и стараются, чистя код и улучшая. Но их меньшинство. 

> Один человек потратит на написание пейзажа Волги неделю и создаст произведение искусства. Другой человек потратит на написание того же пейзажа пол года и у него выйдет мазня без какого-либо смысла. Каждому из них его дело приятно, но второй же просит к себе внимания больше, ведь "он же старался" и "его картину выставили на общее обозрение". А есть ли у второго человека на это право, как думаешь?

Оба человека имеют право на внимание. Возможно у второго человека и получилась мазня. А возможно это новый пикассо. И нет. Я не сравниваю себя с пикассо и другими гениями прошлого. Я лишь говорю, что все имеют право хотеть положительного внимания и стараться его получить. Я считаю, что я не прошу больше внимания чем другие. Если уж честно, я даже хочу меньше внимания, потому что оно банально мешает ибо меня из-за него какого то чёрта пытаются выставить охуенным кодером. А я блять прекрасно знаю что это не так. Я не охуенный кодер. 
Если сравниваешь меня со вторым художником, то мой путь как художника долог и тернист. Да я рисую картины мазню, но я их не бросаю. Я продолжаю их улучшать и дорабатывать. В своём темпе. И то что мой темп, не подходит под ваши вкусы, и вместо того чтобы помочь, дать совет, указать на ошибки, вы предпочитаете обосрать, осудить и осмеять. То пусть всё тонет. Зато это будет дно чистого пруда, а не поверхность токсичного моря.

2022-09-20 10:45 UTC, larentoun commented on code/game/objects/items/devices/scanners.dm
> +		for(var/mob/living/in_turf_mob in scan_turf.contents)
viewers()?

2022-09-20 10:46 UTC, Furukia commented on code/game/objects/items/devices/scanners.dm
> +		for(var/mob/living/in_turf_mob in scan_turf.contents)
Могу позже через них попробовать тогда.

2022-09-20 10:48 UTC, larentoun commented
Полностью поддерживаю Валлата в том, что тебе нужно было просто скопировать сбалансированным и обкатанным годами ниндзю, а не создавать другие проблемы

2022-09-20 11:04 UTC, Honker9999999 commented
> Для игроков и игры в целом именно так было бы лучше. Было бы лучше дать им уже сбалансированные и обкатанные фичи, чем без навыков и опыта пытаться срисовать и изобрести велосипед, что в итоге в перспективу выливается лишь в бОльшие проблемы.

Возможно я и не прав, и бла-бла-бла, но... Разве это не даст в итоге застой и невозможность обучения хороших кодеров? Невозможно научиться чему-то большему, не делая амбициозных проектов, на шажок выше твоих текущих возможностей в чем-либо. Да, возможно пытаясь сделать их хорошо и получишь в итоге возможно не совсем то, что планировалось, но по крайней мере - опыт работы с таковым?

2022-09-20 11:07 UTC, larentoun commented
> > Для игроков и игры в целом именно так было бы лучше. Было бы лучше дать им уже сбалансированные и обкатанные фичи, чем без навыков и опыта пытаться срисовать и изобрести велосипед, что в итоге в перспективу выливается лишь в бОльшие проблемы.
> 
> Возможно я и не прав, и бла-бла-бла, но... Разве это не даст в итоге застой и невозможность обучения хороших кодеров? Невозможно научиться чему-то большему, не делая амбициозных проектов, на шажок выше твоих текущих возможностей в чем-либо. Да, возможно пытаясь сделать их хорошо и получишь в итоге возможно не совсем то, что планировалось, но по крайней мере - опыт работы с таковым?

А никто и не говорит, что переносить легко/плохо. Даже просто перенос уже даст опыта, так как билды различаются

2022-09-20 11:09 UTC, Honker9999999 commented
> А никто и не говорит, что переносить легко/плохо. Даже просто перенос уже даст опыта, так как билды различаются

Вряд ли перенос даст опыт работы с созданием новых режимов, балансировки всех предметов режима и так далее.

2022-09-20 11:17 UTC, Jordanstolethepreciousslam commented
> Вряд ли перенос даст опыт работы с созданием новых режимов, балансировки всех предметов режима и так далее.

Вообще валлат ведет речь о качестве кода. Его переносом можно повысить. Опыт геймдизайна же ты вряд ли получишь вслепую пиля фичи.

2022-09-20 11:22 UTC, Honker9999999 commented
> Вообще валлат ведет речь о качестве кода. Его переносом можно повысить. Опыт геймдизайна же ты вряд ли получишь вслепую пиля фичи.

Примерно так и работает обучение, не? Но не суть. 
Где конкретно плохой код - не было указано, или я не увидел. Ни примера, только демагогия с обеих сторон. Валлат хотя и опытный кодер и не верить ему сложно, но мне мама говорила без пруфов никому не верить, так что эые. Да, есть ошибки и в некоторых случаях не нужная хрень, но, собственно, вряд ли перенос поможет обучиться их избегать, хотя это мое личное имхо как человека, с кодингом связанным очень и очень слабо.

2022-09-20 11:30 UTC, larentoun commented
> > Вообще валлат ведет речь о качестве кода. Его переносом можно повысить. Опыт геймдизайна же ты вряд ли получишь вслепую пиля фичи.
> 
> Примерно так и работает обучение, не? Но не суть. Где конкретно плохой код - не было указано, или я не увидел. Ни примера, только демагогия с обеих сторон. Валлат хотя и опытный кодер и не верить ему сложно, но мне мама говорила без пруфов никому не верить, так что эые. Да, есть ошибки и в некоторых случаях не нужная хрень, но, собственно, вряд ли перенос поможет обучиться их избегать, хотя это мое личное имхо как человека, с кодингом связанным очень и очень слабо.

Тут достаточно долгая история. Вкратце, Фура отвечала Валлату что-то вроде "мне похуй" на его замечания.

2022-09-20 11:52 UTC, Vallat commented
> Возможно я и не прав, и бла-бла-бла, но... Разве это не даст в итоге застой и невозможность обучения хороших кодеров? Невозможно научиться чему-то большему, не делая амбициозных проектов, на шажок выше твоих текущих возможностей в чем-либо. Да, возможно пытаясь сделать их хорошо и получишь в итоге возможно не совсем то, что планировалось, но по крайней мере - опыт работы с таковым?

Нет, не даст. Берясь за амбициозные проекты не имея ни малейшего опыта ты лишь усложнишь работу себе и тем людям, что будут тебя проверять. Ты будешь делать глупые ошибки раз за разом закрепляя их, так как не наработана база. Код будет работать, ведь ты десять часов тратишь на пару строчек перебирая различные варианты их написания, однако, это не делает код качественнее и не даёт тебе понимания как делать правильно.
Есть люди, которые способны в самообучение, в поиск информации, в анализ того, что они делают и так далее. На самом деле банально навык поиска информации по тому же рефу нужен. Однако, это всё не про фурукай. Ведь раз за разом всё те же грабли. Зачем я объяснял раз за разом разницу между `..()` и `. = ..()`? Пихнём одно туда другое сюда и заебись, вроде работает же с виду! Объясните мне, что может быть у человека в голове, когда он в рамках пяти строчек для сравнения переменной с числом использует, собственно, число, а для присвоения этого числа переменной - дефайн с этим числом?
И такого в каждом ПРе хоть отбавляй, правда. Указывай на ошибки, не указывай, что горохом об стену.

2022-09-20 13:05 UTC, Den109G commented on code/game/gamemodes/spaceninja/ninja/suit/suit.dm
> +	if(ninja.alpha != 255 || ninja.alpha != 64)
Всё равно, эти две проверки странно выглядят. Я уже в скобках описал почему.

2022-09-21 05:09 UTC, Furukia commented
> Есть люди, которые способны в самообучение, в поиск информации, в анализ того, что они делают и так далее. На самом деле банально навык поиска информации по тому же рефу нужен. Однако, это всё не про фурукай.

Видимо зря я в референс смотрела по поводу и без, изучала сигналы чтобы оптимизировать код спадания инвиза, вместо блять пихания напрямую проверок в функции атаки и т.д. Искала способ правильно пихать батарейку в апц, потому, что раньше вообще создавала новую и копировала свойство, а потом познала, что есть такая функция как forceMove() и куча других примеров. Но ты не видишь мой прогресс. Ты видишь лишь мои ошибки.

> Зачем я объяснял раз за разом разницу между ..() и . = ..()?

Я даже специально пошла и полазила в дискорде. Да ты объяснял. Не мне. Но почему то ждёшь, что я должна увидеть объяснения, что ты выдавал другому человеку, и начать делать правильно.
> Объясните мне, что может быть у человека в голове, когда он в рамках пяти строчек для сравнения переменной с числом использует, собственно, число, а для присвоения этого числа переменной - дефайн с этим числом?

Банальная невнимательность? Кода много, дефайн мог вообще позже появиться и я его допустим заменяла везде где раньше просто было число? Одно место пропустила. Вот трагедия. Пиздец прям. Но конечно же прямо мне где эта проблема, ты не покажешь. 
>Там, вон, в прошлом ПРе вместо clamp() тернарники, блять, засунул! 

То же самое. Ты мне ничего не рассказывал, не учил, не объяснял, но ждёшь, что я резко прозрею и сделаю как надо в каком то определённым случае.

> Указывай на ошибки, не указывай, что горохом об стену.

У меня точно такое же ощущение от общения с тобой. Сломанный телефон, ей богу. Что то не нравится в коде? Объясни, поправь, подскажи. Но нет. Ты объяснял куче других людей. И ждёшь что я пойду, прочту все твои 55452 сообщения в дискорде и изучу всё, что ты людям рассказывал. Познаю ебучий дзен бьёнда и перестану магическим образом делать ошибки. Так вот. Магии не бывает. И если ты не хочешь объяснять людям где и почему они не правы.  То хотя бы не трать время на разжигание очередных срачей. 
![Menhera-chan_125](https://user-images.githubusercontent.com/67807868/191418492-46b98f16-a469-47a1-81b3-57145fcdf089.png)

2022-09-21 14:32 UTC, larentoun commented
>>Там, вон, в прошлом ПРе вместо clamp() тернарники, блять, засунул!

>То же самое. Ты мне ничего не рассказывал, не учил, не объяснял, но ждёшь, что я резко прозрею и сделаю как надо в каком то определённым случае.

Так clamp() это база...

2022-09-21 14:36 UTC, Den109G commented
Так. Уже надо менять тему.
Кхм.
А чего тут 300к изменений?

2022-09-21 14:40 UTC, Furukia commented
> Так. Уже надо менять тему. Кхм. А чего тут 300к изменений?

Весёлые форс пуши. Надо (Опять!) звать димача и просить помочь починить это. Не могу даже изменения в код вносить пока у меня насрано всем подряд в ветке. И я к тому же не очень понимаю как с такой ситуацией правильно бороться.

2022-09-22 10:04 UTC, Den109G commented
Так. Пока ПР открыт.
Можешь сказать хоть один пример по `if(ninja.alpha != 255 || ninja.alpha != 64)`, когда эта проверка вернёт `FALSE`?
Просто сейчас она должна возвращать всегда TRUE ибо..... Ну, значение никогда не может быть и 255 и 64 одновременно.

2022-09-22 11:20 UTC, Honker9999999 commented
> Можешь сказать хоть один пример по `if(ninja.alpha != 255 || ninja.alpha != 64)`, когда эта проверка вернёт `FALSE`? Просто сейчас она должна возвращать всегда TRUE ибо..... Ну, значение никогда не может быть и 255 и 64 одновременно.
> 
> Просто смысла не вижу её оставлять, если это тоже что и `if(TRUE)`.

В случае применения `if(TRUE)` оно вернет `FALSE` если альфа будет нулевой. Не то что бы был ингейм пример того, как это может выйти, по крайней мере я не знаю, но это по сути будет проверкой на такие случаи, иначе альфа такой и останется, но вопрос насчет того, нужно ли это хороший конечно.

2022-09-22 11:42 UTC, Furukia commented
> Так. Пока ПР открыт. Можешь сказать хоть один пример по `if(ninja.alpha != 255 || ninja.alpha != 64)`, когда эта проверка вернёт `FALSE`? Просто сейчас она должна возвращать всегда TRUE ибо..... Ну, значение никогда не может быть и 255 и 64 одновременно.
> 
> Просто смысла не вижу её оставлять, если это тоже что и `if(TRUE)`.

Эх.  У ниндзя есть три состояния альфы. 1-ое стандарт - 255. 2-ое форма духа - 64. 3-е инвиз - 0.
Теперь причины того почему такая проверка с примерами.
1) Багуется инвиз. Ниндзя входит в инвиз, проходит мимо сканера. пока сканер его просветил вырубает инвиз. Сканер выставляет ему альфу на ноль. Альфа в ноль != ни 255, ни 64. Значит мы входит и проверяем уже врублен ли инвиз. И если нет - чиним альфу.
2) Багуется форма духа. Принцип появления бага такой же. но если сделать проверку без этого if-а возможны проблемы. Если не проверять альфу, можно сохранить например вечный инвиз, пока активна форма духа(В текущих реалиях это недолго, но это так или иначе жирное преимущество). Если же проверять только инфиз - альфа от формы духа потеряет силу и всегда будет 255.

Задумка if-а такова, что при альфе не равной 255 или 64 мы в него входим. И уже там проверяем инвиз/форма духа. Если же она равна хоть одному из этих двух параметров не входим... Он нужен, чтобы не совершать ненужных проверок при естественной для ниндзя альфе, не дающей преимущества. 

И кстати я поняла в чём сейчас конкретно моя проблема... И откуда растут ноги у твоих предьяв к альфе. Я дура и вписала вместо`&&` `|| ` Но уверенно считала, что оно работает как с И... Тут уже момент моего абсурда и невнимательности.  Я это поправлю. И пару лишних раз протестирую пожалуй, что всё работает как надо

2022-09-22 11:44 UTC, Furukia commented
> > Так. Пока ПР открыт. Можешь сказать хоть один пример по `if(ninja.alpha != 255 || ninja.alpha != 64)`, когда эта проверка вернёт `FALSE`? Просто сейчас она должна возвращать всегда TRUE ибо..... Ну, значение никогда не может быть и 255 и 64 одновременно.
> > Просто смысла не вижу её оставлять, если это тоже что и `if(TRUE)`.
> 
> Эх. У ниндзя есть три состояния альфы. 1-ое стандарт - 255. 2-ое форма духа - 64. 3-е инвиз - 0. Теперь причины того почему такая проверка с примерами.
> 
> 1. Багуется инвиз. Ниндзя входит в инвиз, проходит мимо сканера. пока сканер его просветил вырубает инвиз. Сканер выставляет ему альфу на ноль. Альфа в ноль != ни 255, ни 64. Значит мы входит и проверяем уже врублен ли инвиз. И если нет - чиним альфу.
> 2. Багуется форма духа. Принцип появления бага такой же. но если сделать проверку без этого if-а возможны проблемы. Если не проверять альфу, можно сохранить например вечный инвиз, пока активна форма духа(В текущих реалиях это недолго, но это так или иначе жирное преимущество). Если же проверять только инфиз - альфа от формы духа потеряет силу и всегда будет 255.
> 
> Задумка if-а такова, что при альфе не равной 255 или 64 мы в него входим. И уже там проверяем инвиз/форма духа. Если же она равна хоть одному из этих двух параметров не входим... Он нужен, чтобы не совершать ненужных проверок при естественной для ниндзя альфе, не дающей преимущества.
> 
> И кстати я поняла в чём сейчас конкретно моя проблема... И откуда растут ноги у твоих предьяв к альфе. Я дура и вписала вместо`&&` `|| ` Но уверенно считала, что оно работает как с И... Тут уже момент моего абсурда и невнимательности. Я это поправлю. И пару лишних раз протестирую пожалуй, что всё работает как надо

А и да. Мне не подходит вариант `if(alpha)` или более наглядно `if(true)` по причине, того, что багнуться может не только на 0-ле но и с формой духа и её 64, если её не учесть, ниндзя будет бегать без формы духа, но прозрачный как призрак.

2022-09-22 11:47 UTC, Den109G commented
Ну терь ясно. Просто не тот знак поставила.
Как и говорила, в полудрёме писала. 
Ничего, бывает. Все мы ошибаемся.

2022-09-22 13:01 UTC, Furukia commented
> Ну терь ясно. Просто не тот знак поставила. Как и говорила, в полудрёме писала. Ничего, бывает. Все мы ошибаемся.

Тесты показали, что при замене на && Форма духа таки багует...
Пока планирую сделать такой вариант
`if(ninja.alpha == 0 || ninja.alpha == 64)`

2022-09-22 18:28 UTC, larentoun commented
> > Так. Пока ПР открыт. Можешь сказать хоть один пример по `if(ninja.alpha != 255 || ninja.alpha != 64)`, когда эта проверка вернёт `FALSE`? Просто сейчас она должна возвращать всегда TRUE ибо..... Ну, значение никогда не может быть и 255 и 64 одновременно.
> > Просто смысла не вижу её оставлять, если это тоже что и `if(TRUE)`.
> 
> Эх. У ниндзя есть три состояния альфы. 1-ое стандарт - 255. 2-ое форма духа - 64. 3-е инвиз - 0. Теперь причины того почему такая проверка с примерами.
> 
> 1. Багуется инвиз. Ниндзя входит в инвиз, проходит мимо сканера. пока сканер его просветил вырубает инвиз. Сканер выставляет ему альфу на ноль. Альфа в ноль != ни 255, ни 64. Значит мы входит и проверяем уже врублен ли инвиз. И если нет - чиним альфу.
> 2. Багуется форма духа. Принцип появления бага такой же. но если сделать проверку без этого if-а возможны проблемы. Если не проверять альфу, можно сохранить например вечный инвиз, пока активна форма духа(В текущих реалиях это недолго, но это так или иначе жирное преимущество). Если же проверять только инфиз - альфа от формы духа потеряет силу и всегда будет 255.
> 
> Задумка if-а такова, что при альфе не равной 255 или 64 мы в него входим. И уже там проверяем инвиз/форма духа. Если же она равна хоть одному из этих двух параметров не входим... Он нужен, чтобы не совершать ненужных проверок при естественной для ниндзя альфе, не дающей преимущества.
> 
> И кстати я поняла в чём сейчас конкретно моя проблема... И откуда растут ноги у твоих предьяв к альфе. Я дура и вписала вместо`&&` `|| ` Но уверенно считала, что оно работает как с И... Тут уже момент моего абсурда и невнимательности. Я это поправлю. И пару лишних раз протестирую пожалуй, что всё работает как надо

Убери тогда еще, пожалуйста, магические цифры и используй макросы

2022-09-22 18:58 UTC, Furukia commented
> > > Так. Пока ПР открыт. Можешь сказать хоть один пример по `if(ninja.alpha != 255 || ninja.alpha != 64)`, когда эта проверка вернёт `FALSE`? Просто сейчас она должна возвращать всегда TRUE ибо..... Ну, значение никогда не может быть и 255 и 64 одновременно.
> > > Просто смысла не вижу её оставлять, если это тоже что и `if(TRUE)`.
> > 
> > 
> > Эх. У ниндзя есть три состояния альфы. 1-ое стандарт - 255. 2-ое форма духа - 64. 3-е инвиз - 0. Теперь причины того почему такая проверка с примерами.
> > 
> > 1. Багуется инвиз. Ниндзя входит в инвиз, проходит мимо сканера. пока сканер его просветил вырубает инвиз. Сканер выставляет ему альфу на ноль. Альфа в ноль != ни 255, ни 64. Значит мы входит и проверяем уже врублен ли инвиз. И если нет - чиним альфу.
> > 2. Багуется форма духа. Принцип появления бага такой же. но если сделать проверку без этого if-а возможны проблемы. Если не проверять альфу, можно сохранить например вечный инвиз, пока активна форма духа(В текущих реалиях это недолго, но это так или иначе жирное преимущество). Если же проверять только инфиз - альфа от формы духа потеряет силу и всегда будет 255.
> > 
> > Задумка if-а такова, что при альфе не равной 255 или 64 мы в него входим. И уже там проверяем инвиз/форма духа. Если же она равна хоть одному из этих двух параметров не входим... Он нужен, чтобы не совершать ненужных проверок при естественной для ниндзя альфе, не дающей преимущества.
> > И кстати я поняла в чём сейчас конкретно моя проблема... И откуда растут ноги у твоих предьяв к альфе. Я дура и вписала вместо`&&` `|| ` Но уверенно считала, что оно работает как с И... Тут уже момент моего абсурда и невнимательности. Я это поправлю. И пару лишних раз протестирую пожалуй, что всё работает как надо
> 
> Убери тогда еще, пожалуйста, магические цифры и используй макросы

Если ты считаешь, что я знаю, что и где ты хочешь чтобы я заменила. Ты ошибаешься. Тыкни где.

2022-09-22 23:14 UTC, larentoun commented
> > Убери тогда еще, пожалуйста, магические цифры и используй макросы
> 
> Если ты считаешь, что я знаю, что и где ты хочешь чтобы я заменила. Ты ошибаешься. Тыкни где.

255 и 64. Что это.

2022-09-23 06:41 UTC, Furukia commented
> > > Убери тогда еще, пожалуйста, магические цифры и используй макросы
> > 
> > 
> > Если ты считаешь, что я знаю, что и где ты хочешь чтобы я заменила. Ты ошибаешься. Тыкни где.
> 
> 255 и 64. Что это.

Цифры
![file_109360091](https://user-images.githubusercontent.com/67807868/191904335-9b1e2750-9f37-4e3d-9d14-346869bbd407.png)

А если серьёзно. Почему чтобы понять, что вы хотите дефайны(Вы же их хотите?) для разных значений альфы. Мне приходится гадать и переспрашивать. Ну реально, разве так сложно сразу написать. "Пожалуйста замени цифры альфы на дефайны, чтобы сразу было понятно, что это такое и/или чтобы было удобно заменять и т.д. и т.п.", но я читаю про "магические цифры и макросы" Ни о каких именно цифрах речь, ни зачем их заменять, и на какие ещё макросы. Ничерта не понятно, но очень интересно.

2022-09-23 06:42 UTC, Furukia commented
Сделаю дефайны для альфы позже.

2022-09-23 06:44 UTC, BeebBeebBoob commented
Хонк. Хонк. .github/CONTRIBUTING.MD. Хонк. хонк.

2022-09-23 07:36 UTC, Den109G commented
Не хонкай. Забираешь мою работу. 😠

2022-09-23 09:14 UTC, larentoun commented
> > > > Убери тогда еще, пожалуйста, магические цифры и используй макросы
> > > 
> > > 
> > > Если ты считаешь, что я знаю, что и где ты хочешь чтобы я заменила. Ты ошибаешься. Тыкни где.
> > 
> > 
> > 255 и 64. Что это.
> 
> Цифры ![file_109360091](https://user-images.githubusercontent.com/67807868/191904335-9b1e2750-9f37-4e3d-9d14-346869bbd407.png)
> 
> А если серьёзно. Почему чтобы понять, что вы хотите дефайны(Вы же их хотите?) для разных значений альфы. Мне приходится гадать и переспрашивать. Ну реально, разве так сложно сразу написать. "Пожалуйста замени цифры альфы на дефайны, чтобы сразу было понятно, что это такое и/или чтобы было удобно заменять и т.д. и т.п.", но я читаю про "магические цифры и макросы" Ни о каких именно цифрах речь, ни зачем их заменять, и на какие ещё макросы. Ничерта не понятно, но очень интересно.

Так я же с цитатой ответила. Можно было бы бросить взгляд и поискать любые числа...

2022-09-23 09:36 UTC, larentoun requested changes

2022-09-23 09:36 UTC, larentoun commented on code/datums/dash_weapon.dm
> +//			user.start_pulling(pulled_mob) // Не работает, как задумано... Персонаж просто не берёт другого в пул после телепортации. Пока оставлю так
Лишний комментарий?

2022-09-23 09:36 UTC, larentoun commented on code/game/gamemodes/spaceninja/ninja/ninja_borg_module.dm
> +	..()
Уверена, что не нужно задавать значение `.`?

2022-09-23 09:36 UTC, larentoun commented on code/game/gamemodes/spaceninja/ninja/suit/headset.dm
> +	..()
Уверена, что не нужно задавать значение `.`?

2022-09-23 09:36 UTC, larentoun commented on code/game/gamemodes/spaceninja/space_ninja.dm
> +	if(possible_ninjas.len == 0)
Ты уверена, что `possible_ninjas` не будет нуллом? Замени на `length()`
Лишняя проверка на равность нулю в условии...

2022-09-23 09:36 UTC, larentoun commented on code/game/gamemodes/spaceninja/space_ninja.dm
>  	if(GLOB.ninjastart.len == 0)
Спаси от рантайма, используй `length()`

2022-09-23 09:36 UTC, larentoun commented on code/game/objects/items/devices/scanners.dm
> +	var/list/mobs_in_range = viewers(scan_range, src.loc)
Не лучше ли брать турф? Будет ли корректно работать, если сканнер у кого-то/в шкафу/в мехе/где-то еще, что `.loc` не вернет турф? Тут неуверена

2022-09-23 13:13 UTC, Furukia commented on code/datums/dash_weapon.dm
> +//			user.start_pulling(pulled_mob) // Не работает, как задумано... Персонаж просто не берёт другого в пул после телепортации. Пока оставлю так
Оставила, чтобы потом попробовать снова реализовать автозахват пулящегося обратно в пулл после телепорта

2022-09-23 13:14 UTC, Furukia commented on code/game/gamemodes/spaceninja/ninja/ninja_borg_module.dm
> +	..()
Я хотела позже пробежаться ПО ВСЕМ файлам что шли с изначальным и не только ПР-ом ниндзя и в СЛЕДУЮЩЕМ патче уже обработать все эти наследования

2022-09-24 15:54 UTC, Furukia commented on code/game/objects/items/devices/scanners.dm
> +	var/list/mobs_in_range = viewers(scan_range, src.loc)
На тестах всё прекрасно работало. Мне в общем то всё равно. Если хочешь замену на get_turf, заменю.

2022-09-24 16:46 UTC, larentoun approved these changes

2022-09-24 17:16 UTC, Furukia commented
Что то я забыла о дефайнах. Сделала короче только что.

2022-09-24 17:24 UTC, merged