FEAT: Несокрушимый стержень сильнее ломает станцию
ss220-space/Paradise pull request #1421
Opened 2022-10-08 00:54 UTC by Artemonim

## What Does This PR Do
Перенос [#17675](https://github.com/ParadiseSS13/Paradise/pull/17675)

## Why It's Good For The Game

## Images of changes

## Changelog
:cl:
tweak: Теперь несокрушимый стержень имеет 40% шанс проломить пол под собой, что создаёт множество разгерметизаций по всей станции (по всему маршруту стержня)
/:cl:

2022-10-08 01:42 UTC, PhantornRU commented
Трём нефритовый стержень

FEAT OFFICIAL: если шо

2022-10-08 08:48 UTC, larentoun commented
Пиздец, гребанный свет. Не забывайте, что у нас, в отличии от оффов, немного по другому работает атмос

2022-10-08 08:51 UTC, larentoun requested changes
А что насчет магов? Тоже будут всю станцию убивать?

2022-10-08 08:51 UTC, larentoun commented on code/modules/events/immovable_rod.dm
>  	if(istype(clong, /turf) || istype(clong, /obj))
Раз занялся рефактором, можно было бы и тут поменять на
```suggestion
	if(isturf(clong) || isobj(clong))
```

2022-10-08 08:51 UTC, larentoun commented on code/modules/events/immovable_rod.dm
>  	else if(istype(clong, /mob))
```suggestion
	else if(ismob(clong))
```

2022-10-08 08:51 UTC, larentoun commented on code/modules/events/immovable_rod.dm
>  		if(istype(clong, /mob/living/carbon/human))
```suggestion
		if(ishuman(clong))
```

2022-10-10 15:18 UTC, larentoun requested changes

2022-10-10 15:18 UTC, larentoun commented on code/modules/events/immovable_rod.dm
> +	// Chance to expose the tile to space is like 60% of this value.
Incorrect comment

2022-10-13 11:41 UTC, Artemonim commented
[Отклонено в А-воут](https://discord.com/channels/617003227182792704/755125334097133628/1030078314511073280 )

2022-10-13 11:41 UTC, closed without merging