FEAT: Добавление дополнительной одежды для ЦК + Supreme
ss220-space/Paradise pull request #1427
Opened 2022-10-08 16:30 UTC by PhantornRU

Авоут пройден и одобрен:
https://discord.com/channels/617003227182792704/755125334097133628/1027541933628858510

## What Does This PR Do

- ntsc_cap - фуражка суприм коммандера, статы как у берета СОО, лежит в файлах
- ntsc_uniform - форма суприм коммандера, статы как у формы СОО, лежит в файлах
- centcom_bat - бита ОЦК (хоумран бита с возможностью складываться), должна быть в сложенном (centcom_bat_0) и разложенном (centcom_bat_1) вариантах, приложена сверху
- srt_bat - бита СРТ (по сути та же бита ОЦК но рескин), должна быть в сложенном (srt_bat_0) и разложенном (srt_bat_1) вариантах
- Полевой плащ центрального командования
- Фикс ЦК берета в шкафу (не отображался спрайт)
- Добавление униформы в шкафы офицеров флота на ЦК
- Добавление бит в педальские шкафы СРТ, ЦК (НЕ ЕРТ!!!)
- Добавление бит в админ руму
- Новый эквипмент для спавна: Supreme Commander
- Новый эквипмент для спавна: офицер центрального командования для полевого выхода.

## Why It's Good For The Game
- Дополнительная одежда для суровых дядек с ЦК
- Теперь СООшники не едут лично с битами на станцию, подвергая себя риску и понтуясь своими крутыми пиджаками со статами как у ригов дезсквада. Вместо них могут лететь СУПРИМ КОМАНДОЗ.
- Бита, достойная самого представителя ЦК.
- Суприм командер выглядит как суровый дядька
- Доступная одежда и биты для триалов

2022-10-08 16:35 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	desc = "Выдвижная тактическая бита Центрального Командования Nanotrasen. В официальных документах эта бита проходит под элегантным названием \"Высокоскоростная система доставки СРП\". Выдаваясь толь
Для длинного описания можно использовать `description_info`. Попробуем возродить переменную

2022-10-08 16:38 UTC, larentoun requested changes

2022-10-08 16:38 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	var/force_off = 10
зачем отдельно, когда можно оставить только `force_on`?

2022-10-08 16:38 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	var/item_state_off = "centcom_bat_0"
Ммм, нельзя было использовать как-то по другому? К примеру, если включена, в конце вставлять `1`

2022-10-08 16:38 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	var/static/list/attack_verb_off
Опять же, зачем то дублируешь

2022-10-08 16:38 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	force = on ? force_on : force_off
вместо `force_off` можно было бы использовать `initial(force)`

2022-10-08 16:38 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		force = force_off //not so robust now
`initial(force)`, лучше переделать

2022-10-11 07:07 UTC, PhantornRU commented on code/game/objects/items/weapons/weaponry.dm
> +	var/item_state_off = "centcom_bat_0"
у нас так работают всякие телескопички и прочее. Это общепринятый формат наименования спрайтов. да и... разница мелкая, так читабельнее и проще.

2022-10-11 07:12 UTC, PhantornRU commented on code/game/objects/items/weapons/weaponry.dm
> +	var/force_off = 10
Чтобы была возможность ебнуть свернутой тактической битой.

2022-10-11 07:17 UTC, PhantornRU commented on code/game/objects/items/weapons/weaponry.dm
> +	force = on ? force_on : force_off
![image](https://user-images.githubusercontent.com/41479614/195021201-1d336bf6-6572-46b7-bf1e-db2d6e20798a.png)
Ты имеешь ввиду так?

2022-10-11 13:11 UTC, larentoun requested changes
Видимо, за ручку надо

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	force = on ? initial(force_on) : initial(force_off)
Эээ, а зачем тут `initial(force_off)`, если `force_off` не меняется?

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	force = on ? initial(force_on) : initial(force_off)
Глянь тот же энергомеч

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		force = initial(force_on) //stunbaton damage
Тоже бред какой-то

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		force = initial(force_off) //not so robust now
Бред

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	var/force_off = 10
Видимо, нужно за ручку вести.
```suggestion
	force = 10
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	var/item_state_off = "centcom_bat_0"
```suggestion
	item_state = "centcom_bat_0"
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	var/icon_state_off = "centcom_bat_0"
```suggestion
	icon_state = "centcom_bat_0"
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	var/static/list/attack_verb_off
```suggestion
	attack_verb = list("hit", "poked")
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	var/static/list/attack_verb_on
```suggestion
	var/list/attack_verb_on = list("smacked", "struck", "cracked", "beaten")
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	if(!attack_verb_off)
```suggestion

```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		attack_verb_off = list("hit", "poked")
```suggestion

```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		attack_verb_on = list("smacked", "struck", "cracked", "beaten")
```suggestion

```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	icon_state = on ? icon_state_on : icon_state_off
```suggestion
	icon_state = on ? icon_state_on : initial(icon_state)
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	force = on ? initial(force_on) : initial(force_off)
```suggestion
	force = on ? force_on : initial(force)
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	attack_verb = on ? attack_verb_on : attack_verb_off
```suggestion
	attack_verb = on ? attack_verb_on : initial(attack_verb)
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	item_state_off = "srt_bat_0"
```suggestion

```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	icon_state_off = "srt_bat_0"
```suggestion
	icon_state = "srt_bat_0"
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	icon_state = on ? icon_state_on : icon_state_off
```suggestion
	icon_state = on ? icon_state_on : initial(icon_state)
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		force = initial(force_on) //stunbaton damage
```suggestion
		force = force_on
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		item_state = item_state_off
```suggestion
		item_state = initial(item_state)
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		force = initial(force_off) //not so robust now
```suggestion
		force = initial(force)
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		attack_verb = attack_verb_off
```suggestion
		attack_verb = initial(attack_verb)
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		homerun_ready = 0
```suggestion
		homerun_ready = FALSE
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		homerun_able = 0
```suggestion
		homerun_able = FALSE
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +		homerun_able = 1
```suggestion
		homerun_able = TRUE
```

2022-10-11 13:11 UTC, larentoun commented on code/game/objects/items/weapons/weaponry.dm
> +	item_state = "centcom_bat_0"
```suggestion

```

2022-10-17 07:21 UTC, PhantornRU commented
Путем решения конфликта ко мне залетел "пустой коммит" который удалил все ранние коммиты и не давал себя ревертнуть, так как он являлся "пустым коммитом". Ведь нельзя же удалить то чего нет? Но при этом оно удалило всё что могло, но не показывало это.
Я нихуя не понял, но путем ребейза кажется починил...

2022-10-17 07:21 UTC, PhantornRU commented
@Dimach merge conflict решен. Бубен сломался

2022-10-17 08:10 UTC, larentoun approved these changes

2022-10-17 10:08 UTC, merged