FEAT + FIX: Разум для животных, фикс памяти пауков, имен хозяина.
ss220-space/Paradise pull request #1462
Opened 2022-10-17 10:02 UTC by PhantornRU

Ссылка на пройденный Авоут:
https://discord.com/channels/617003227182792704/755125334097133628/1028566644588548196

## What Does This PR Do
Добавить возможность наделять разумом животных, за которых УЖЕ играет игрок с помощью того же зелья разума (Sentience Potion).

При использовании зелья, игроку на фауне будет предлагаться выбор, выпить его или нет.

## Why It's Good For The Game
Плюсы:
- Возможность продолжать РП за ту же зверюшку без танцев с бубном
- Немного логики в работу зелья
- Больше играбельности фауны станции :uwuthinking:

Минусы:
- Мышь может сказать Ихихи и пойти материть повара вместо благодарности:Ratge:
- Шлепа будет собирать отряды для совершения военных преступлений :RoflCat:

2022-10-17 11:14 UTC, BeebBeebBoob commented on code/modules/research/xenobiology/xenobiology.dm
> +			add_game_logs("стал питомцем игрока [key_name(user)]", SM)
```suggestion
			add_game_logs("стал питомцем игрока [key_name_log(user)]", SM)
```

2022-10-17 11:15 UTC, BeebBeebBoob approved these changes

2022-10-17 12:39 UTC, PhantornRU commented on code/modules/research/xenobiology/xenobiology.dm
> +			if (!SM.master_commander)
```suggestion
			if (SM.master_commander)
```

2022-10-18 09:28 UTC, larentoun requested changes

2022-10-18 09:28 UTC, larentoun commented on code/game/objects/effects/spiders.dm
> +			S.new_mind_memory = "<B>Ваш хозяин [master_commander.name], выполняйте [genderize_ru(master_commander.gender, "его", "её", "этого", "их")] цели любой ценой!</B>"
А проверка не нужна на то, что вообще мастер-коммандер есть?

2022-10-18 09:28 UTC, larentoun commented on code/modules/research/xenobiology/xenobiology.dm
> +			being_used = 1
Магические числа бы убрать

2022-10-18 10:58 UTC, PhantornRU commented on code/modules/research/xenobiology/xenobiology.dm
> +			being_used = 1
Заменил, проверку внёс.

2022-10-18 12:40 UTC, larentoun approved these changes

2022-10-20 09:56 UTC, PhantornRU commented
Интересный факт. У этого ПРа нету интересных фактов.

2022-10-21 18:12 UTC, Dimach commented on code/game/objects/effects/spiders.dm
> +	var/new_mind_memory = "Я свободный паук."
У тебя тут формулировка от первого лица а на 80 строке от имени наратора. Коль скоро добавляешь тут перевод то пусть он хоть в рамках твоего же кода по стилю совпадает (либо везде от первого либо везде от наратора)

2022-10-22 07:38 UTC, PhantornRU commented on code/game/objects/effects/spiders.dm
> +	var/new_mind_memory = "Я свободный паук."
Поправил формулировки

2022-10-22 14:27 UTC, merged