feat: Повязки на глаза с ХУДом.
ss220-space/Paradise pull request #1463
Opened 2022-10-17 13:29 UTC by frikadeliSpaghetti

Рескин обычного худа. Также будет в лодауте.
![diagpatch](https://user-images.githubusercontent.com/48985748/196189714-a1b66ef2-59e4-4b9d-9e4a-07c93ffb5839.png)
![medpatch](https://user-images.githubusercontent.com/48985748/196189717-d5930ee6-83bf-41e1-933a-c38365436990.png)
![secpatch](https://user-images.githubusercontent.com/48985748/196189719-3f22650e-2ab4-4342-a958-bf09c0176872.png)
![skillspatch](https://user-images.githubusercontent.com/48985748/196189723-6b67e9e7-864b-4475-a066-07aa3a3b9fd3.png)

2022-10-18 05:14 UTC, BeebBeebBoob commented
Они закрывать кровавые/траллы глаза как понимаю будет закрывать глаза?
Или там `tint` решает хмм

2022-10-18 05:27 UTC, Den109G commented
Да даже монокль из автомата скрывает культ глаза.

2022-10-18 05:32 UTC, BeebBeebBoob commented
И всё же, это по сути недочёт который стоит исправить тогда.

2022-10-18 09:29 UTC, larentoun requested changes

2022-10-18 09:29 UTC, larentoun commented on code/modules/client/preference/loadout/loadout_glasses.dm
> +	path = /obj/item/clothing/glasses/hud/hydroponic/patch
Пахнет баффом, так как не на всех картах раундстартом даются очки ботаника

2022-10-18 09:29 UTC, larentoun commented on code/modules/clothing/glasses/hud.dm
> +	prescription_upgradable = 0
Есть разные версии апргейдов? Если нет, почему бы не заменить на `FALSE`?

2022-10-18 09:30 UTC, larentoun commented
> И всё же, это по сути недочёт который стоит исправить тогда.

Не должен исправляться этим ПРом, по идее. Нужно код смотреть и все очки починить

2022-10-18 12:41 UTC, larentoun approved these changes
Хызы, стоит ли ботаникам давать доступ к гидрохудам, на коробке их нет в ящике

2022-10-21 18:23 UTC, merged

2022-10-21 18:46 UTC, dj-34 commented
@Dimach оно не прошло даже #предложения-свыше Pog

2022-10-22 14:46 UTC, Dimach commented
Черт..

2022-10-22 14:47 UTC, frikadeliSpaghetti commented
Притворитесь, что ничего не было, а повязки существовали всегда