Набор для починки роботов нюкерам/ССТ
ss220-space/Paradise pull request #1469
Opened 2022-10-18 13:17 UTC by Ykipss

## What Does This PR Do
Добавляет нюкерам и ССТ возможность купить набор для починки роботов. В него входят:
Броня, Актуатор, Радио, Бинарная коммуникация, Камера, Модуль диагностики, Нанопаста, Ключ шифрования синдиката, борг анализатор и бумага с инструкцией по починке борга.
## Why It's Good For The Game
Нюкеры теперь получат возможность чинить своих роботов.

## картинОчка
![image](https://user-images.githubusercontent.com/109545437/196440008-ec7a8b90-fa2c-41a7-bf53-79ce331ba82f.png)

2022-10-20 00:29 UTC, larentoun requested changes

2022-10-20 00:29 UTC, larentoun commented on code/datums/uplink_item.dm
> +	/datum/uplink_item/bundles_TC/cyborg_maint
Прочитай линтер

2022-10-20 00:29 UTC, larentoun commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	var/obj/item/paper/P = new /obj/item/paper(src)
Ты путь уже задал, можно просто `new (src)`

2022-10-20 00:29 UTC, larentoun commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	"}
Обязательно приписывать везде `юнита`?

2022-10-21 10:31 UTC, Ykipss commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	"}
Текст не мой, а Renascitur#5399 , я просто добавил каламбур с пончинкой : )

2022-10-21 10:32 UTC, Ykipss commented on code/datums/uplink_item.dm
> +	/datum/uplink_item/bundles_TC/cyborg_maint
Э-э-э.. Чё прочитать?

2022-10-21 14:01 UTC, larentoun commented on code/datums/uplink_item.dm
> +	/datum/uplink_item/bundles_TC/cyborg_maint
Линтер, у тебя прямо в `Files changed` на гитхабе пишет ошибку

2022-10-21 23:23 UTC, Dimach commented on code/datums/uplink_item.dm
> +	/datum/uplink_item/bundles_TC/cyborg_maint
У тебя тип (/datum/uplink_item/bundles_TC/cyborg_maint) имеет один таб вправо, а должен начинаться на нулевом символе

2022-10-21 23:23 UTC, Dimach commented on code/datums/uplink_item.dm
> +	/datum/uplink_item/bundles_TC/cyborg_maint
```suggestion
/datum/uplink_item/bundles_TC/cyborg_maint
```

2022-10-21 23:27 UTC, Dimach commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	"}
А мне текст нравится, подробно довольно расписано, уточнения лишними не бывают в таких инструкциях

2022-10-24 18:15 UTC, Dimach commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	var/obj/item/paper/P = new /obj/item/paper(src)
```suggestion
	var/obj/item/paper/P = new (src)
```

2022-10-24 23:30 UTC, merged