Добавление стойки для оружия
ss220-space/Paradise pull request #1471
Opened 2022-10-20 19:16 UTC by MataVsn

Авоут пройден - https://discord.com/channels/617003227182792704/755125334097133628/1032201321446649866
Добавление новых стоек для оружия, с заменой обычных, на которых лежит оружие, в бриге.  На стойку поставить можно только оружие. Создается из частей для стойки оружия, которые создаются из одного металла.
![image](https://user-images.githubusercontent.com/113342160/197037907-a87b3baf-4878-49d8-b35e-dd3feace4f5c.png)
![image](https://user-images.githubusercontent.com/113342160/197037938-f7573721-29c4-48ef-9922-772e514449b6.png)

2022-10-21 06:51 UTC, dj-34 requested changes
Код я не проверял, проверил работоспособность в игре.

1. После деконстракта и собирания стойки обратно, оружие перестает ставиться на ЛЮБУЮ стойку. Выплевывается как вещь, которая не является оружием.
2. Скорее всего "выплевывать" не-оружие не лучший способ - я подумал что каску, которую я хотел туда поставить, просто пропала (оказывается она появилась у меня под ногами). Можно просто не позволять этого делать, с сообщением, мол "оно туда не помещается".

2022-10-21 08:47 UTC, MataVsn commented
> 

Все исправил.

2022-10-21 14:10 UTC, larentoun requested changes

2022-10-21 14:10 UTC, larentoun commented on code/game/objects/structures/tables_racks.dm
> +/obj/item/gun/
```suggestion
/obj/item/gun
```

2022-10-21 14:10 UTC, larentoun commented on code/game/objects/structures/tables_racks.dm
> +/obj/structure/rack/gunrack/attackby(obj/item/W, mob/user, params)
Что насчет того, чтобы вызывать радиальное меню, чтобы избавиться от пискель-хантинга?

2022-10-21 14:10 UTC, larentoun commented on code/game/objects/structures/tables_racks.dm
> +/obj/item/gun/proc/remove_from_rack()
На Move() не хочешь добавить, чтобы при пулле нормально работало?

2022-10-21 14:10 UTC, larentoun commented on code/game/objects/structures/tables_racks.dm
> +		var/obj/structure/rack/GR = new /obj/structure/rack/gunrack(user.loc)
Почему решили не так сделать?
```suggestion
		var/obj/structure/rack/gunrack/GR = new (user.loc)
```

2022-10-21 14:10 UTC, larentoun commented on code/game/objects/structures/tables_racks.dm
> +/obj/item/gun/proc/remove_from_rack()
Ну и при разных сменах давления и прочего

2022-10-21 14:14 UTC, dj-34 approved these changes
Свой рефактор я отправил PR'ом автору в ветку - его дело вмерживать, или нет. 
В целом код рабочий, багов более не нашёл. За качество кода не отвечаю, но есть претензии, которые я отправил в рефакторе.

2022-10-22 09:12 UTC, BeebBeebBoob requested changes

2022-10-22 09:12 UTC, BeebBeebBoob commented on code/game/objects/structures/tables_racks.dm
> +	var/on_rack = FALSE
Мне это не нравится

2022-10-22 09:12 UTC, BeebBeebBoob commented on code/game/objects/structures/tables_racks.dm
> +/obj/structure/rack/gunrack/attackby(obj/item/W, mob/user, params)
Я вот думал что как раз радиальное неплохо было бы чем вот такие манипуляции.
Да, придется повозиться как работать с иконками но не будет таких... Костылей

2022-10-22 09:12 UTC, BeebBeebBoob commented on code/game/objects/structures/tables_racks.dm
> +	if(isrobot(user))
```suggestion
	if(!ishuman(user))
```
Или симпл мобы тоже могут взаимодействовать?

2022-10-22 09:12 UTC, BeebBeebBoob commented on code/game/objects/structures/tables_racks.dm
> +		return
Смысл два раза проверять
У тебя уже есть в /deconstruct

2022-10-22 11:54 UTC, larentoun commented on code/game/objects/structures/tables_racks.dm
> +	var/on_rack = FALSE
А как еще? На каждый `Move()` делать проверку?

2022-10-23 14:08 UTC, MataVsn commented on code/game/objects/structures/tables_racks.dm
> +	if(isrobot(user))
Стоит такая же проверка как у и обычной стойки, но тыоё слово закон

2022-10-23 14:09 UTC, MataVsn commented on code/game/objects/structures/tables_racks.dm
> +/obj/structure/rack/gunrack/attackby(obj/item/W, mob/user, params)
Вы думаете над тем, как исправить костыль, когда перемещаешь со стойки оружие пуллом?

2022-10-25 22:33 UTC, merged