FEAT: New pain hunter objective and protect objective
ss220-space/Paradise pull request #1472
Opened 2022-10-21 07:04 UTC by PhantornRU

Авоуты пройдены:
PAIN HUNTER: https://discord.com/channels/617003227182792704/755125334097133628/1032312972862820382
PROTECT: https://discord.com/channels/617003227182792704/755125334097133628/1032313248541835325

## What Does This PR Do
Антагонист (а конкретно тритор), получают 2 дополнительные цели.
1. PROTECT - защитить случайную цель, на которую ведут охоту другие триторы.
2. PAIN HUNTER - нанести BRUTE/BURN количество урона игроку. Цель должна выжить.
Новый тип задач, нацеленный на нанесении ущерба игроку. Игроку не обязательно убивать свою цель для его выполнения. Он может даже обыграть это по РП. Те же потасовки в баре или хирургические вмешательства. Как правило это задачи от синдиката, нацеленные на то, чтобы "преподать урок" от заказчика, дабы цель страдала.
Все цели должны выжить к концу раунда.
В notes можно будет глянуть степень выполнения. Цель предназначена для неоднократного нападения на цель.
Тип урона и количество выбирается случайно.

В обеих целях цель должна выжить, в противном случае она не будет засчитана.

## Why It's Good For The Game
- Новые цели, нацеленные не только на убийства.
- Разнообразия геймплея, не заставляющие антага дейстовать только жестко.
- Возможности для хитростей и разнообразия РП. (да-да, как будто антаги и до этого РПшили)
- Не сложные цели по механикам, не требующие огромных строчек кода.

## Images of changes
![image](https://user-images.githubusercontent.com/41479614/197133718-61ca2184-a5f0-4e91-814b-7c6c531583da.png)

2022-10-27 08:13 UTC, PhantornRU commented
Прошла неделя, йа-ху

2022-11-09 15:55 UTC, PhantornRU commented
@Dimach у меня тут месяц уже валяется ПР. Аж успел конфликт словить когда ты вливал фикс на цельки)

2022-11-12 05:52 UTC, Dimach commented on code/game/gamemodes/objective.dm
> +	if(length(SSticker.mode.victims) > 0)
А почему тут нет никакой рандомизации, он тупо берет первую попавшуюся жертву? Сделай лучше через pick

2022-11-12 05:54 UTC, Dimach commented on code/game/gamemodes/objective.dm
> +		SSticker.mode.victims.Remove(victim)
Мне не нравиться что ты удаляешь тут цель на защиту. Если добавишь рандомизацию внизу то двум агентам может выпасть цель на защиту одного человека что неплохо

2022-11-12 06:04 UTC, Dimach requested changes

2022-11-12 06:04 UTC, Dimach commented on code/game/gamemodes/objective.dm
> +		SSticker.mode.victims.Add(target)
Что произойдет если в раунде 2 антага с целью на одного игрока? Он 2 раза добавится в список?

2022-11-12 06:04 UTC, Dimach commented on code/game/gamemodes/traitor/hunter_target.dm
> +	SSticker.mode.victims.Remove(target)
А почему тут ты удаляешь, а в других целях нет?

2022-11-12 06:04 UTC, Dimach commented on code/game/gamemodes/traitor/hunter_target.dm
> +			damage_explain = "грубого"
Ушибы/ожоги/отравления. Что такое жженый урон kekw

2022-11-12 06:04 UTC, Dimach commented on code/modules/antagonists/traitor/datum_traitor.dm
> +	if(prob(20))
Цель на протект МАЛФУ?? При том что у него "никто не должен выжить"?

2022-11-12 06:04 UTC, Dimach commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	if(mind && length(mind.target_hunters))
А можно было там обойтись без вот этих target_hunters а просто в момент нанесения урона проверять что у этого человека есть целька на нанесение урона?

2022-11-12 06:21 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	if(mind && length(mind.target_hunters))
у этого человека может быть несколько "охотников НА него". Наносимый урон должен проверяться на разум охотника из списка

2022-11-12 10:34 UTC, PhantornRU commented on code/modules/antagonists/traitor/datum_traitor.dm
> +	if(prob(20))
Ну так да, сбой в программе же. +РП и меньше думсдея.

Но ладно. Уберу коль сбой в программе слишком сбоичен)

2022-11-12 13:21 UTC, PhantornRU commented
Так, ну вроде всё. Убрал тот мусорный hunter_target

2022-11-13 08:40 UTC, Dimach commented on code/game/gamemodes/objective.dm
> +	if(length(SSticker.mode.victims) > 0)
```suggestion
	if(length(SSticker.mode.victims))
```

2022-11-13 08:41 UTC, Dimach commented on code/game/gamemodes/objective.dm
> +		var/datum/mind/victim = pick(SSticker.mode.victims)
Нет проверки на повторы

2022-11-13 08:47 UTC, Dimach commented on code/game/gamemodes/traitor/pain_hunter.dm
> +	explanation_text = "Преподать урок и лично нанести [target.current.real_name], [target.assigned_role], не менее [damage_need] [damage_explain()] урона. Цель должна выжить. \nТекущий урон: [damage_ta
Как то это ООЦшно очень.. Почему бы не написать "Нанести не менее Х единиц ожогов/ушибов/отравления. Прогресс У/Х". Мне не очень нравиться терминолоия "нанести урон" во вполне себе ИЦшных нотесах

2022-11-13 08:49 UTC, Dimach commented on code/game/gamemodes/traitor/pain_hunter.dm
> +		damage_need = damage_procent - damage_procent % 50	//Вычитаем для красивых ровных чисел.
Что тут за математическая магия? Почему бы просто не написать damage_need = rand(3, 12) * 50

2022-11-13 08:50 UTC, Dimach commented on code/game/gamemodes/traitor/pain_hunter.dm
> +		damage_need = damage_procent - damage_procent % 50	//Вычитаем для красивых ровных чисел.
И коменты тоже..

2022-11-13 08:52 UTC, Dimach commented on code/datums/mind.dm
>  						new_objective.explanation_text = "[description] [new_target:real_name], the [new_target:mind:assigned_role]."
Там строчкой выше не хватает дескрипшена для pain hunter, при выдаче через TP он будет без описания. И выбирать тип урона тоже бы хотелось

2022-11-13 09:07 UTC, PhantornRU commented on code/game/gamemodes/objective.dm
> +		var/datum/mind/victim = pick(SSticker.mode.victims)
Проверка на повторы была до этого. Теперь сделал проще. 
![image](https://user-images.githubusercontent.com/41479614/201514203-d77c0748-6520-4c79-9783-c42af8329811.png)

2022-11-13 09:08 UTC, PhantornRU commented on code/game/gamemodes/traitor/pain_hunter.dm
> +	explanation_text = "Преподать урок и лично нанести [target.current.real_name], [target.assigned_role], не менее [damage_need] [damage_explain()] урона. Цель должна выжить. \nТекущий урон: [damage_ta
Да, так будет звучать лучше, исправлю

2022-11-13 09:11 UTC, PhantornRU commented on code/game/gamemodes/traitor/pain_hunter.dm
> +	explanation_text = "Преподать урок и лично нанести [target.current.real_name], [target.assigned_role], не менее [damage_need] [damage_explain()] урона. Цель должна выжить. \nТекущий урон: [damage_ta
Касаемо "отравления", оставлю всё-таки "токсинов". Так как у нас отравы не только токсинный урон могут наносить и игрок может буквально не совсем корректно понять как ему нанести токсинный урон. У нас даже на википедии оффициально называется "токсины".

2022-11-13 09:16 UTC, Dimach commented on code/game/gamemodes/objective.dm
> +		var/datum/mind/victim = pick(SSticker.mode.victims)
А что будет если у игрока уже есть цель а протект, и выпадет тот же игрок? Делай копию SSticker.mode.victims, убирай оттуда овнера и тех на кого уже есть цельки, потом пикай. И вообще тут имхо не нужен отдельный прок, прям в файнд тагрет это все можно написать

2022-11-13 09:57 UTC, PhantornRU commented on code/game/gamemodes/objective.dm
> +		var/datum/mind/victim = pick(SSticker.mode.victims)
Да, прок убрал, действительно стал лишним когда я кучу всего до этого убрал. Внес проверки и повыпиливал действующие протекты

2022-11-13 10:38 UTC, Dimach commented on code/game/gamemodes/objective.dm
> +	for(var/datum/objective/protect/objective in GLOB.all_objectives)
А где проверка на то что у этого же тритора могут быть цельки на этого же игрока?

2022-11-13 10:38 UTC, Dimach commented on code/game/gamemodes/objective.dm
> +	if (!victim)
Не надо тут этих сложных конструкций, просто if(!length(temp_victims), а там ниже pick

2022-11-13 10:45 UTC, PhantornRU commented on code/game/gamemodes/objective.dm
> +	for(var/datum/objective/protect/objective in GLOB.all_objectives)
![image](https://user-images.githubusercontent.com/41479614/201517657-fbeef947-d48c-4b9c-b3be-b960bdf5ec7c.png)
Так вот эта проверка. Мы просто удаляем все цели которые встречаются у других игроков и потом, если список "опустел" и мы не смогли пикнуть случайную цель из списка, то "..()" находим случайную цель

2022-11-13 10:48 UTC, PhantornRU commented on code/game/gamemodes/objective.dm
> +	if (!victim)
Из одной строки в 3. Когда она все еще читаема была

2022-11-13 11:03 UTC, PhantornRU commented on code/game/gamemodes/objective.dm
> +	for(var/datum/objective/protect/objective in GLOB.all_objectives)
Так, внёс доп. проверки шоб не было цельки в списке

2022-11-13 11:09 UTC, Dimach commented on code/game/gamemodes/objective.dm
> +	for(var/datum/objective/protect/objective in GLOB.all_objectives)
А это зачем? Пусть двум тритора падает цель на защиту одного и того же. Веселее же

2022-11-13 11:10 UTC, Dimach commented on code/game/gamemodes/objective.dm
> +	if (!victim)
Зачем усложнять то так, перенеси в ифку просто

2022-11-13 11:11 UTC, PhantornRU commented on code/game/gamemodes/objective.dm
> +	for(var/datum/objective/protect/objective in GLOB.all_objectives)
Да разве? Слишком много внимания тогда будет одному человеку, когда есть другие игроки

2022-11-13 11:11 UTC, PhantornRU commented on code/game/gamemodes/objective.dm
> +	if (!victim)
а блят, точно. Туплю.

2022-11-13 15:11 UTC, merged