Tweak: мелкий перевод (тестовый)
ss220-space/Paradise pull request #1479
Opened 2022-10-22 12:32 UTC by Teningur

2022-10-22 12:48 UTC, larentoun requested changes

2022-10-22 12:48 UTC, larentoun commented on code/game/gamemodes/nuclear/nuclear_challenge.dm
> +	var/are_you_sure = alert(user, "Тщательно проконсультируйтесь со своей командой, прежде чем объявлять войну [station_name()]. Вы уверены, что хотите предупредить вражеский экипаж? У вас есть [-round
Не учел то, что эти переменные используются. Ты сломал код, поздравляю

2022-10-22 12:48 UTC, larentoun commented on code/game/gamemodes/nuclear/nuclear_challenge.dm
> +	var/war_declaration = "[user.real_name] объяви[genderize_ru(user.gender,"л","ла","ло","ли")] о намерении полностью уничтожить [station_name()] с помощью ядерного устройства, и бросает вызов экипажу.
`бросает` не гендеризировано

2022-10-22 12:48 UTC, larentoun commented on code/modules/response_team/ert.dm
> +		ert_gender_prefs.Add(input_async(M, "Пожалуйста, выберите пол (10 секунд):", list("Мужской", "Женский")))
Ты сломал пол у ЕРТовцев

2022-10-22 12:56 UTC, dj-34 commented on code/game/gamemodes/nuclear/nuclear_challenge.dm
> +	to_chat(user, "Вы привлекли внимание влиятельных сил в Синдикате. Ваша команда получила бонусный пакет телекристаллов. Вас ждёт великая награда, если вы выполните задание.")
```suggestion
	to_chat(user, "Вы привлекли внимание влиятельных сил в Синдикате. Ваша команда получила бонусный пакет телекристаллов. Вас ждёт щедрая награда, если вы выполните задание.")
```

2022-10-22 12:56 UTC, dj-34 commented on code/game/gamemodes/nuclear/nuclear_challenge.dm
> +		to_chat(user, "Если подумать, элемент неожиданности всё же не так плох.")
```suggestion
		to_chat(user, "Если подумать, элемент неожиданности всё же не так уж и плох.")
```

2022-10-22 12:56 UTC, dj-34 commented on code/game/gamemodes/nuclear/nuclear_challenge.dm
> +			to_chat(user, "Шаттл тронулся с места! Вы утратили право объявить войну.")
```suggestion
			to_chat(user, "Шаттл тронулся с места! Вы утратили право на объявление войны.")
```

2022-10-22 12:56 UTC, dj-34 commented on code/game/gamemodes/nuclear/nuclear_challenge.dm
> +		to_chat(user, "Чтобы использовать это, вы должны находиться на своей базе".")
```suggestion
		to_chat(user, "Чтобы использовать это, вы должны находиться на своей базе.")
```

2022-10-22 12:56 UTC, dj-34 commented on code/modules/response_team/ert.dm
> +	GLOB.event_announcement.Announce("[station_name()], мы, к сожалению, не можем отправить к вам отряд быстрого реагирования в данный момент.", "ОБР недоступен")
```suggestion
	GLOB.event_announcement.Announce("[station_name()], мы, к сожалению, не можем отправить к вам Отряд Быстрого Реагирования в данный момент.", "ОБР недоступен")
```

2022-10-22 12:56 UTC, dj-34 commented on code/modules/response_team/ert.dm
> +	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляем команду высококвалифицированных ассистентов, чтобы помочь(?) вам. Будьте наготове.", "ОБР в пути")
```suggestion
	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляем команду высококвалифицированных ассистентов, чтобы помочь(?) вам. Ожидайте.", "ОБР в пути")
```

2022-10-22 12:56 UTC, dj-34 commented on code/modules/response_team/ert.dm
> +	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляём отряд быстрого реагирования с кодом «Амбер». Ожидайте.", "ОБР в пути")
```suggestion
	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляём Отряд Быстрого Реагирования с кодом «AMBER». Ожидайте.", "ОБР в пути")
```

2022-10-22 12:56 UTC, dj-34 commented on code/modules/response_team/ert.dm
> +	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляем отряд быстрого реагирования с кодом «Ред». Ожидайте.", "ОБР в пути")
```suggestion
	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляем Отряд Быстрого Реагирования с кодом «RED». Ожидайте.", "ОБР в пути")
```

2022-10-22 12:56 UTC, dj-34 commented on code/modules/response_team/ert.dm
> +	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляем элитный отряд быстрого реагирования с кодом «Гамма». Ожидайте.", "ОБР в пути")
```suggestion
	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляем элитный Отряд Быстрого Реагирования с кодом «GAMMA». Ожидайте.", "ОБР в пути")
```

2022-10-22 12:56 UTC, dj-34 commented on code/modules/tgui/modules/ert_manager.dm
> +			GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы пытаемся собрать отряд быстрого реагирования. Ожидайте.", "АКТИВИРОВАН ПРОТОКОЛ ОБР")
```suggestion
			GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы пытаемся сформировать Отряд Быстрого Реагирования. Ожидайте.", "АКТИВИРОВАН ПРОТОКОЛ ОБР")
```

2022-10-22 12:58 UTC, dj-34 commented on code/game/gamemodes/nuclear/nuclear_challenge.dm
> +	var/war_declaration = "[user.real_name] объяви[genderize_ru(user.gender,"л","ла","ло","ли")] о намерении полностью уничтожить [station_name()] с помощью ядерного устройства, и бросает вызов экипажу.
> `бросает` не гендеризировано

Он бросает
Она бросает
Оно бросает
Шо тут не так?

2022-10-22 13:05 UTC, larentoun commented on code/game/gamemodes/nuclear/nuclear_challenge.dm
> +	var/war_declaration = "[user.real_name] объяви[genderize_ru(user.gender,"л","ла","ло","ли")] о намерении полностью уничтожить [station_name()] с помощью ядерного устройства, и бросает вызов экипажу.
Тогда плюролизация

2022-10-22 13:08 UTC, Teningur commented on code/modules/response_team/ert.dm
> +	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляём отряд быстрого реагирования с кодом «Амбер». Ожидайте.", "ОБР в пути")
точно стоит писать на латинице? на кириллице меньше шансов, что ттс зажуёт слова или неправильно их прочитает

2022-10-22 13:10 UTC, dj-34 commented on code/modules/response_team/ert.dm
> +	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляём отряд быстрого реагирования с кодом «Амбер». Ожидайте.", "ОБР в пути")
> точно стоит писать на латинице? на кириллице меньше шансов, что ттс зажуёт слова или неправильно их прочитает

Это нужно с админами обсуждать, а вообще что на латинице, что на кириллице он будет "AMBER" читать одинаково (по идеи). Возможны мелкие незаметные искажения в ТТСе.

2022-10-22 13:13 UTC, Teningur commented on code/modules/response_team/ert.dm
> +	GLOB.event_announcement.Announce("Внимание, [station_name()]. Мы отправляём отряд быстрого реагирования с кодом «Амбер». Ожидайте.", "ОБР в пути")
> 

Я с вики сверялся, там отряды указаны как Амбер, Ред и Гамма прям кириллицей, этим руководствовался.

2022-10-22 20:53 UTC, dikers93 commented
я напомню что мы переводим только, повторюсь что нам разрешили перевести только анонсы и цели антоганистов, ни про какие менюшки управления не ишлось

2022-10-22 22:05 UTC, Teningur commented
Я понимаю, я вообще драфтовый ПР запулил просто чтобы функционал гитхаба протестить, не уверен, что тут хоть что-то примется.

2022-10-27 08:15 UTC, PhantornRU commented
@Teningur выцепи переводы анонсов и антажьих целей отдельно, после чего их уже будут ревьювить.

2022-11-04 05:36 UTC, closed without merging