Feat: Taipan roles spawn features + automatic blocking for reappearing characters
ss220-space/Paradise pull request #1530
Opened 2022-10-29 16:37 UTC by UEDCommander

Вносит следующие изменения в механику спавна персонажей:
- Если данное имя персонажа когда-либо входило в раунд стандартным путем или через Тайпан, повторно войти в раунд с персонажем того же имени будет невозможно - даже если персонаж ушел в крио или был гибнут.
- Админские команды из плеер панели обходят это ограничение.
- При спавне на Тайпане игроку предоставляется возможность загрузить персонажа, которого он выбрал перед входом в Observe из слота, либо использовать стандартный генератор.
- Если персонаж с тем же именем, что и у выбранного в слоте персонажа, уже входил в раунд ранее, то вышеописанный выбор не дается и игрок будет вынужден использовать стандартный генератор.

2022-10-30 01:18 UTC, Den109G commented on code/_globalvars/lists/mobs.dm
> +GLOBAL_LIST_EMPTY(human_names_list)			//List of names for all humans that have ever entered the round
![image](https://user-images.githubusercontent.com/87372121/198858327-59e8d4da-27d8-44ea-bc1f-736f92de3286.png)
Просто в конце Enter нажми.
А то жалуется гит.

2022-10-30 01:20 UTC, Den109G commented on code/modules/mob/new_player/new_player.dm
> +				to_chat (usr, "<span class='danger'>There is a character that already exists with the same name: <b>[C]</b>, please join with a different one.</span>")
Уверен что убирание `.real_name` не повлияет ни на что?

2022-10-30 09:37 UTC, UEDCommander commented on code/modules/mob/new_player/new_player.dm
> +				to_chat (usr, "<span class='danger'>There is a character that already exists with the same name: <b>[C]</b>, please join with a different one.</span>")
Да, потому что эта переменная теперь берет значения из GLOB.human_names_list, в который записываются имена сами по себе, в отличии от GLOB.mob_list, в который записывались сами мобы

2022-10-30 12:18 UTC, UEDCommander commented on code/_globalvars/lists/mobs.dm
> +GLOBAL_LIST_EMPTY(human_names_list)			//List of names for all humans that have ever entered the round
Угу

2022-10-30 12:39 UTC, Furukia requested changes

2022-10-30 12:39 UTC, Furukia commented on code/modules/awaymissions/corpse.dm
> +	var/mob/plr = null
Что такое plr? Можно назвать переменную так, чтобы не возникало вопроса, что это и зачем оно нужно? Или хотя бы оставить комментарий.

2022-10-30 12:39 UTC, Furukia commented on code/modules/awaymissions/corpse.dm
> +		for (var/C in GLOB.human_names_list)
```suggestion
		for(var/C in GLOB.human_names_list)
```

2022-10-30 12:39 UTC, Furukia commented on code/modules/awaymissions/corpse.dm
> +		for (var/C in GLOB.human_names_list)
Лучше в целях соблюдение единого стиля, не оставлять пробелы между if/for/while и т.д. со скобками.

2022-10-30 13:17 UTC, UEDCommander commented on code/modules/awaymissions/corpse.dm
> +	var/mob/plr = null
Угу, добавил

2022-11-04 23:53 UTC, UEDCommander commented
А, да, и авоут мы прошли, так что больше не драфт

![image](https://user-images.githubusercontent.com/52104104/200090605-89045a20-54c3-4ba6-b09d-de7f5d016072.png)

2022-11-05 01:13 UTC, Dimach commented
Смотри линтер, у тебя не прошли тесты

2022-11-05 05:43 UTC, UEDCommander commented
Последняя перегрузка заныкалась, будем искать

2022-11-06 16:17 UTC, UEDCommander commented
Нашлась

2022-11-09 05:32 UTC, Dimach approved these changes

2022-11-10 02:09 UTC, merged