feat: new ammo for det's revolver
ss220-space/Paradise pull request #1543
Opened 2022-11-02 11:15 UTC by frikadeliSpaghetti

Удалил возможность усилить револьвер дека. Добавил ему летальные патроны с 25 брута.

2022-11-06 12:28 UTC, larentoun requested changes

2022-11-06 12:28 UTC, larentoun commented on code/modules/projectiles/ammunition/boxes.dm
> +	materials = list(MAT_METAL = 1000)
Оставляй без изменений. Это цена за пустой спидлоадер.

2022-11-06 12:28 UTC, larentoun commented on code/modules/projectiles/ammunition/boxes.dm
> +	materials = list(MAT_METAL = 2000)
Тут можешь не писать цену, так как она будет наследоваться.

2022-11-06 12:28 UTC, larentoun commented on code/modules/research/designs/autolathe_designs.dm
> +	materials = list(MAT_METAL = 2900)
2000 + 650*6 = 5900

2022-11-06 12:28 UTC, larentoun commented on code/modules/research/designs/autolathe_designs.dm
> +	materials = list(MAT_METAL = 5900)
2000 + 1100*6 = 8600 (если цена 1100 за пульку)

2022-11-06 12:28 UTC, larentoun commented on code/modules/projectiles/ammunition/ammo_casings.dm
> +	materials = list(MAT_METAL = 1100)
midbullet3 стоит 1500. Почему скидка на револьвер?

2022-11-06 12:28 UTC, larentoun commented on code/modules/research/designs/autolathe_designs.dm
> +	category = list("initial", "Security")
Летальные должны быть скрыты за взломанным автолатом
```suggestion
	category = list("hacked", "Security")
```

2022-11-06 12:28 UTC, larentoun commented on code/modules/research/designs/autolathe_designs.dm
> +	name = "Speed Loader (.38 Rubber)"
```suggestion
	name = "Speed Loader (.38 rubber)"
```

2022-11-06 12:28 UTC, larentoun commented on code/modules/research/designs/autolathe_designs.dm
> +	name = "Speed Loader (.38 Lethal)"
```suggestion
	name = "Speed Loader (.38)"
```

2022-11-06 13:44 UTC, larentoun commented on code/modules/projectiles/ammunition/boxes.dm
> +	materials = list(MAT_METAL = 1000)
Я имел ввиду, спидлоадеры по задумке стоят 2000. Скидка по какому случаю?

2022-11-06 15:09 UTC, frikadeliSpaghetti commented on code/modules/projectiles/ammunition/boxes.dm
> +	materials = list(MAT_METAL = 1000)
Новый год скоро

2022-11-22 12:19 UTC, Dimach commented
Воут не прошел, закрываем?

2022-11-22 12:47 UTC, closed without merging