Фиксы для Mixing Bowl
ss220-space/Paradise pull request #1550
Opened 2022-11-03 23:11 UTC by PavelPoltavets

Баг-репорты:
https://discord.com/channels/617003227182792704/617004034405957642/1037091814869565503
https://discord.com/channels/617003227182792704/617004034405957642/1035555268559376485

## What Does This PR Do
В миску для смешивания теперь можно наливать жидкости для готовки.
Теперь можно вытащить предметы с миски для готовки.
Графическая меню миски теперь обновляется при манипуляции с ингредиентами в ней

2022-11-04 08:33 UTC, PavelPoltavets commented
так... появился баг что гуишка открывается принудительно когда кладешь в миску предметы...

2022-11-05 01:47 UTC, PavelPoltavets commented
Пофикшено...

2022-11-06 12:48 UTC, larentoun requested changes

2022-11-06 12:48 UTC, larentoun commented on code/game/objects/items/mixing_bowl.dm
> +			return 0
У нас может ретурниться что-то кроме 0/1? Если нет, ретурни `FALSE`/`TRUE`

2022-11-07 16:14 UTC, PavelPoltavets commented on code/game/objects/items/mixing_bowl.dm
> +			return 0
В этом классе по идее вообще без разницы что ретюрнить. 
Да и FALSE/TRUE в данном случае логически не объяснены. Ибо 1 - не вызывать метод afterattack(), а 0 - вызывать...
(судя по коменту в каком то там другом файле)

2022-11-08 17:37 UTC, larentoun commented on code/game/objects/items/mixing_bowl.dm
> +			return 0
В любом случае, чем меньше магических чисел - тем лучше. Хоть дефайны делай локальные

2022-11-10 02:13 UTC, merged