FIX: Запрет стягивать шапки боргов гостам и отображение надетой шапки в EXAMINE
ss220-space/Paradise pull request #1556
Opened 2022-11-05 16:51 UTC by PhantornRU

## What Does This PR Do
Запрет стягивать шапки боргов гостам и отображение надетой шапки в EXAMINE

## Why It's Good For The Game
Госты не смогут стягивать шапки с голов юнитов
Игроки видят шапки надетые на юнитах в описании

2022-11-06 05:44 UTC, Den109G commented
Вырезают фичи.
4891

2022-11-06 05:50 UTC, BeebBeebBoob commented
Гостам :KEKW:

2022-11-06 05:53 UTC, BeebBeebBoob commented
Я надеюсь пупс сделал проверку Всех изменений в этом ПРе так как тут видно четко что тут не только фикс а пару других приколов как имена.

2022-11-06 06:07 UTC, PhantornRU commented
>  тут не только фикс а пару других приколов как имена.

Да, добавляю вытягивание .name, шоб он не вставлял артикль THE. Ну а вдруг у нас когда-то перевод будет?

А еще да, вырезаем фичи воздействия гостов на шапки. Ке-ке-ке

2022-11-06 07:11 UTC, Honker9999999 commented
> А еще да, вырезаем фичи воздействия гостов на шапки. Ке-ке-ке

Теперь нельзя будет снять котоушки и всем гостчатом осуждать? Осуждаю

2022-11-06 12:46 UTC, larentoun requested changes

2022-11-06 12:46 UTC, larentoun commented on code/modules/mob/living/silicon/silicon_hat.dm
> +	if(!(iscarbon(usr) || isrobot(usr)) || usr.incapacitated() || !Adjacent(usr))
Ты уверен, что хочешь оставить `!(iscarbon(usr) || isrobot(usr))`? Если это робот, то это равносильственно тому, что это не карбон...

2022-11-06 23:32 UTC, PhantornRU commented on code/modules/mob/living/silicon/silicon_hat.dm
> +	if(!(iscarbon(usr) || isrobot(usr)) || usr.incapacitated() || !Adjacent(usr))
Да это я просто скопипастил код у Йана. Но да, можно выпилить

2022-11-06 23:32 UTC, PhantornRU commented on code/modules/mob/living/silicon/silicon_hat.dm
> +	if(!(iscarbon(usr) || isrobot(usr)) || usr.incapacitated() || !Adjacent(usr))
```suggestion
	if(!(iscarbon(usr) || usr.incapacitated() || !Adjacent(usr))
```

2022-11-09 05:26 UTC, Dimach approved these changes

2022-11-10 02:08 UTC, merged