Add: new unathi sounds and emotes
ss220-space/Paradise pull request #1570
Opened 2022-11-09 22:00 UTC by captainnelly

## What Does This PR Do
Добавляем унатхам новые звуки для некоторых эмоций, и новые эмоции, + фикс повышенного урона унатхам, который кто-то давно случайно сделал.

## Why It's Good For The Game
Предложка -> https://discord.com/channels/617003227182792704/755125334097133628/1043780560406970378

## Images of changes
https://www.youtube.com/watch?v=UyU-5AuzqCM

## Changelog
:cl:
add: new unathi sounds and emotes
/:cl:

2022-11-20 15:06 UTC, PhantornRU requested changes

2022-11-20 15:06 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/unathi.dm
> -	brute_mod = 1.05
Рано брут_мод трогаешь. Его лучше в отдельном ПРе и с пройденным Авоутом на изменение механик.

2022-11-20 15:16 UTC, captainnelly commented on code/modules/mob/living/carbon/human/species/unathi.dm
> -	brute_mod = 1.05
Это просто фикс бага, кто-то случайно его изменил, и теперь унатхи получают на 5% больше брута

2022-11-21 01:27 UTC, Dimach commented
Смотри линтер, у тебя странное что-то написано

2022-11-21 03:13 UTC, MataVsn approved these changes

2022-11-21 07:21 UTC, PhantornRU approved these changes

2022-11-21 07:21 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/unathi.dm
> -	brute_mod = 1.05
тогда всё ок

2022-11-22 11:53 UTC, merged