Mothsupremacy
ss220-space/Paradise pull request #1585
Opened 2022-11-14 12:38 UTC by MataVsn

## What Does This PR Do
Портирование молей с оффов. Оригинал -  https://github.com/ParadiseSS13/Paradise/pull/17000
![image](https://user-images.githubusercontent.com/113342160/201660946-47cd1620-eb3a-4e42-9e0f-f3eba92d5926.png)
![image](https://user-images.githubusercontent.com/113342160/201660963-4ab52b80-f377-4b96-bcea-696ec7a50a77.png)
С адаптацией под наш код, с добавлением крыльев как отдельны орган.
![image](https://user-images.githubusercontent.com/113342160/201661198-464dd875-3fc7-4b07-80ff-f5f87315f5ab.png)

Крылья позволяют игнорировать отсутствие гравитации, при присутствии атмосферы, или переломы, если крылья не сожжены. Сжигаются крылья из-за воздействия огня, с помощью кокона они могут их восстановить (не отрастить заново).  Низшая форма отсутствует, возможно будущее добавление.

Добавлены звуки молей: смеха, чихания, кашля, хихикания и крика.

2022-11-14 15:58 UTC, PhantornRU commented
Одевал молей в одежду? Всё корректно у нас отображается с гуманоидными? У ОФФов там есть куча вторичных фиксов и ПРов по молям. А также ПР на новый облик для молей.

Если нет, то лучше тогда скомуниздить тот ПР с новыми обликами

2022-11-14 16:00 UTC, PhantornRU commented on code/__HELPERS/mobs.dm
> +		valid_body_accessories += null
Немного не понял зачем null к списку добавлять... Разве он null значение добавляет?

2022-11-14 16:00 UTC, PhantornRU commented on code/__HELPERS/mobs.dm
> +			valid_body_accessories += name
Может лучше как для списка:
valid_body_accessories.Add(name)

2022-11-14 16:03 UTC, PhantornRU commented on code/game/dna/dna2.dm
> +				new_dna.UI[b]=UI[b]
```suggestion
				new_dna.UI[b] = UI[b]
```

2022-11-14 16:07 UTC, PhantornRU commented on code/game/dna/dna2_helpers.dm
> +		available += head_accessory
.Add() ?

Хоть разницы с += и нету, но если ты будешь в будущем убирать из списка, то лучше будет использовать .Remove(), а такая стандартизация поможет по привычке писать Add/Remove

Вон, как в методичке:
Процедуры Add и Remove ведут себя соответственно как операторы += и -= . Единственное отличие состоит в том, что функция Remove возвращает 1, если какие-либо значения действительно были удалены, и 0, если нет.
http://www.byond.com/docs/guide/chap10.html#10.4.3

2022-11-14 16:09 UTC, PhantornRU commented on code/modules/client/preference/preferences.dm
> +						possible_body_accessories -= "None" // in case an admin is viewing it
.Add()
.Remove()

2022-11-14 16:12 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/human_interaction.dm
> +						H.custom_emote(message = "<span class='danger'>отрыва[pluralize_ru(H.gender,"ет","ют")] [P] крылья!</span>")
Чьи крылья? "Отрывают крылья Васи Бзззыковича."
Я б конечно еще рекомендовал добавлять .name для корректностей. Но в нашем случае это не особо важно, так как никаких частиц "А" и "THE" не добавляются, ведь это не предмет.
Снизу точно также нужно поменять
```suggestion
						H.custom_emote(message = "<span class='danger'>отрыва[pluralize_ru(H.gender,"ет","ют")] крылья [P]!</span>")
```

2022-11-14 16:12 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/_species.dm
> +
```suggestion
```

2022-11-14 16:13 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/moth.dm
> +
```suggestion
```

2022-11-14 16:14 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/moth.dm
> +
Это спеки. Точно ли тут нужны пробелы?  Лучше их тогда разместить перед ВСЕМИ спеками. Например после:
get_species_runechat_color
или
 handle_reagents
 
 Чтобы отделить "блоки"
```suggestion
```

2022-11-14 16:14 UTC, MataVsn commented on code/modules/mob/living/carbon/human/species/moth.dm
> +
Хорошо пупсик

2022-11-14 16:16 UTC, PhantornRU commented on code/modules/mob/mob_movement.dm
> +	var/next_in_line
var/next_zone?

2022-11-14 16:17 UTC, PhantornRU commented on goon/browserassets/css/browserOutput.css
> +.mind_control			{color: #A00D6F; font-size: 3; font-weight: bold; font-style: italic;}
```suggestion
.mind_control				{color: #A00D6F; font-size: 3; font-weight: bold; font-style: italic;}
```

2022-11-14 16:17 UTC, PhantornRU requested changes
Чутка просмотрел

2022-11-15 16:53 UTC, larentoun requested changes

2022-11-15 16:53 UTC, larentoun commented on code/__DEFINES/dcs/signals.dm
> +//sent from living mobs when they are ahealed
```suggestion
///sent from living mobs when they are ahealed
```

2022-11-15 16:55 UTC, larentoun commented on code/modules/client/preference/loadout/loadout_general.dm
>  	path = /obj/item/toy/carpplushie
Хм, а чего карповая игрушка особенная?

2022-11-15 16:56 UTC, larentoun commented on code/modules/mob/language.dm
> +	syllables = list("år", "i", "går", "sek", "mo", "ff", "ok", "gj", "ø", "gå", "la", "le",
Надо перевести, чтобы ТТСка понимала

2022-11-15 17:05 UTC, larentoun commented on code/modules/mob/living/carbon/human/body_accessories.dm
> +/datum/body_accessory/wing/plain
А это обязательно?

2022-11-15 17:06 UTC, larentoun commented on code/modules/mob/living/carbon/human/emote.dm
> +			message = "<B>[src]</B> flutters [p_their()] wings."
А чего тут на английском, а сверху на русском? Определитесь

2022-11-15 17:06 UTC, larentoun commented on code/modules/mob/living/carbon/human/emote.dm
> +			var/emotelist = "airguitar, blink(s), blink(s)_r, blush(es), bow(s)-none/mob, burp(s), choke(s), chuckle(s), clap(s), collapse(s), cough(s), cry, cries, custom, dance, dap(s)-none/mob," \
Куда подсказку забрали?

2022-11-15 17:10 UTC, larentoun commented on code/modules/surgery/organs/subtypes/moth.dm
> +/obj/item/organ/external/wing/nian
```suggestion

/obj/item/organ/external/wing/nian
```

2022-11-15 17:11 UTC, larentoun commented on code/modules/surgery/organs/subtypes/standard.dm
> +	if(!H)
Нет проверки, что это хуман

2022-11-16 06:38 UTC, PhantornRU commented on code/modules/tgui/modules/appearance_changer.dm
> +	return owner && (flags & APPEARANCE_BODY_ACCESSORY) && owner.bodypart_tail & HAS_BODY_ACCESSORY && check_rights(R_ADMIN, 0, owner)
```suggestion
	return owner && (flags & APPEARANCE_BODY_ACCESSORY) && owner.bodypart_tail && HAS_BODY_ACCESSORY && check_rights(R_ADMIN, 0, owner)
```

2022-11-16 06:40 UTC, PhantornRU approved these changes

2022-11-18 18:35 UTC, Dimach commented on code/__HELPERS/mobs.dm
> +/proc/random_body_accessory(species = "Vulpkanin", is_optional = TRUE)
Правильнее написать тут is_optional = FALSE, поскольку в противном случае тот код что юзал этот метод раньше сломается, ведь нулл он раньше не возвращал

2022-11-18 18:44 UTC, Dimach commented on code/game/dna/dna2_helpers.dm
> +				H.bodypart_wing?.body_accessory = body_acc
Присваивать один и тот же бодиакк и в хвост и в крылья?? Это точно должно так работать?

2022-11-18 19:06 UTC, Dimach commented
Вопрос, вульпа/таяра не могут махать хвостом в риге, а моль может махать крыльями, как это работает?

2022-11-18 19:15 UTC, frikadeliSpaghetti commented
> Вопрос, вульпа/таяра не могут махать хвостом в риге, а моль может махать крыльями, как это работает?

Вульпа вроде машет и в риге, но из-за особенности ригов этого не видно

2022-11-18 19:19 UTC, MataVsn commented
> Вопрос, вульпа/таяра не могут махать хвостом в риге, а моль может махать крыльями, как это работает?

Как выше описали, у нас нет анимации крыльев, чисто эмоут, а у хвостов он есть, но из-за наложения иконки рига, анимация не происходит. Анимацию крыльев в дальнейшем хочу попробовать добавить, как и спрайты ригов у молей

2022-11-18 19:46 UTC, Dimach commented
Хотелось бы превратить этот баг с лисутвующей анимацией в фичу, и прямо запрещать махать хвостами/крыльями в ригах. Кроме того у молей по идее и возможность летать должна пропадать, если моль в риге.
А ещё я там где-то видел проверку что если надета одежда которая закрывает хвост то прерывать обработку эмоута...

2022-11-18 19:54 UTC, MataVsn commented
> Хотелось бы превратить этот баг с лисутвующей анимацией в фичу, и прямо запрещать махать хвостами/крыльями в ригах. Кроме того у молей по идее и возможность летать должна пропадать, если моль в риге. А ещё я там где-то видел проверку что если надета одежда которая закрывает хвост то прерывать обработку эмоута...

![image](https://user-images.githubusercontent.com/113342160/202790853-12b80981-9e21-489b-9202-7a417940297a.png)
из ригов торчат крылья и следственно работать будут

2022-11-18 19:59 UTC, Dimach commented
Скинь скрин моли в риге.
Я закину этот ПР в тестмерж, он довольно крупный, недельку на Клео помаринуется

2022-11-18 20:01 UTC, MataVsn commented
> Скинь скрин моли в риге. Я закину этот ПР в тестмерж, он довольно крупный, недельку на Клео помаринуется

![image](https://user-images.githubusercontent.com/113342160/202792323-98e07084-3876-4e9f-8c04-0362cd01f2e2.png)
Так сейчас на клео и веге больше народу чем на мейне, есть ли смысл?

2022-11-18 20:25 UTC, Dimach commented
Смысл в том что если будет какой нибудь кретический баг (а в то что их точно не будет я не верю) не ломать основные сервера. Изменение крупное, что-то может сломаться. Там нормально изменение между ветками перенесется, в тестмерде сейчас из изменений только ттс

2022-11-18 20:31 UTC, MataVsn commented
> 
:feelsbaad:

2022-11-19 20:14 UTC, BeebBeebBoob commented on code/modules/mob/living/carbon/human/species/moth.dm
> +		message_admins("[key_name_admin(H)] weaved [src] at [AREACOORD(H)].")
Нам админам это не надо знать. 
```suggestion
		add_game_logs("weaved [src] at [AREACOORD(H)].", H)
```

2022-11-24 02:45 UTC, merged