НерфСтанов
ss220-space/Paradise pull request #161
Opened 2021-07-18 19:09 UTC by Jordanstolethepreciousslam

Этот патч ставит однокнопочные станы туда, где им самое место.

т.е у параши.
-Большинству источников станов в игре урезано время стана до минимума и добавлен стамина урон. Теперь захват живьем можно совершить только либо через граб, либо через дисейблер, либо через продолжительный массаж станами(7 для тазеров, 10 для станбатонов)

-Это изменение нивелирует станлоки как явление, за исключением стан оружия ближнего боя, которое всё еще может станлочить несмотря на то что стана не хватит на наручники)
Сильный нерф станпрода. Его стандартного зарядка не хватит для стамина крита. Только с использованием граба(или гарроты) можно захватить цель. 

-Также подверглись изменению наручники(надеваются дольше на 50%), флеш гранаты и часть наркотиков(дают больше регена стамины).
Изменению также подверглась подавляющая часть источников стана у антагонистов. Энерго арбалет, снайперские пули, mind batterer, Заклинания вампиров и тенеморфов,

Кроме того усилен бакшот и ослаблены резиновые пули и дробь для дробовика.
Уменьшено время случайных станов в ближнем бою для безоружного и не очень боя.
Уменьшен стан с большинства источников подскальзывания.
Увеличен урон самодельного арбалета для соответствия урону самодельной пневмопушке.
ЦНС ребутер теперь восстанавливает стамину если её суммарный урон выше 70.

2021-07-18 19:15 UTC, Jordanstolethepreciousslam commented
Ах да, еще понерфлены Ксеноморфы. Их дизарм теперь станит с 40% шансом на 1 тик вместо 100% шанса на 5 тиков

2021-07-18 21:33 UTC, Sykybekk commented
Это просто ахуенно

2021-07-18 22:11 UTC, Jordanstolethepreciousslam commented
Чуть конкретнее
-Тазеры, энергоарбалеты и иже с ними станят от 0.1 до 1 секунды  вместо прошлых 9 и наносят 15 стамина урона(30 у энерго арбалета)  
Мили(станпалки) станят на 2 цикла( от секунды до двух с половиной) и наносят 10 стамина урона. Исключением является только телескопичка с 80% шансом станящая на один цикл(от 0.1 секунд до 1), и с 20% на два.
Глейры станят на 3 цикла(около 4.5 секунд)
Вопли оглушают на 1-2 цикла
Случайные станы с мили ударов не стан оружия урезаны вполовину. с 4 циклов( 6 секунд) до 2( 3 секунды).
Флешбенги урезаны примерно наполовину.
подскальзывания урезаны наполовину (с 4 до 2 циклов)

Суть изменений. Больше нельзя захватить цель живым в два клика(один тазером, второй наручниками)
Либо заламывать цель грабом оглушая дубинкой, либо тратить время и заряд оружия накапливая стамина урон на цели(либо рискнуть и стрелять вдвойне эффективным по стамине, но не станящим дисейблером), либо использовать резиновые патроны. Либо стрелять леталом (щиткур mode/on).
Короче летал теперь действительно простой выбор а захват живьем требует определенной сноровки.

2021-07-19 07:47 UTC, tizer7 commented
жестковато однако. фактически, то что раньше называли станом - данный ПР умножает на 0. хотя мне нравится - больше горящих жоп щиткуров.
у ксено случайный диапазон стамина урона от 10 до 20 за удар, с шансом стамина урона 100%, я правильно понял?

2021-07-19 08:20 UTC, PhantornRU commented
Это охуенно

2021-07-19 08:49 UTC, keIgaras commented
выглядит как буквально новый гемплей, заебись

2021-07-19 09:26 UTC, AttHawk commented
дизеблеру бы поднять стаминаурон до 35, а так выглядит страшно, но интересно, будем посмотреть примут ли это и как оно будет играться

2021-07-19 12:59 UTC, HMBGERDO commented
Вампир? Пошёл нахуй, вампир, ты теперь ничего не можешь.
СБ это не сильно изменит, они также будут сильнее всех из-за дизейблеров.
Тазеры не будут иметь смысла вообще, потому что 40 стамина урона против 10, что лучше? 
Станбатоны больше не имеют смысла, потому что цель встанет между ударами и убежит, соси хуй. 
Связать кого-то? Теперь это пиздец задачка, удачи хлопчик.

Короче если добавлять, то только в тестовом режиме на короткий период времени не на мейн сервер.

2021-07-19 13:00 UTC, HMBGERDO commented
а, и еще, карп теперь самый сильный в игре, кстати, с вот этим ПРом

2021-07-19 13:21 UTC, rebel228 commented
Мнение руководства сервера можно услышать по поводу этого ПРа, или уже всё решено и просто интересно узнается мнение коммьюнити?

2021-07-19 13:50 UTC, Bizzonium commented
@rebel228 ничего ещё не решено. Опробовать можно тут [byond://play.ss220.space:7720](byond://play.ss220.space:7720)

2021-07-19 14:15 UTC, Jordanstolethepreciousslam commented
> Вампир? Пошёл нахуй, вампир, ты теперь ничего не можешь.
> СБ это не сильно изменит, они также будут сильнее всех из-за дизейблеров.
> Тазеры не будут иметь смысла вообще, потому что 40 стамина урона против 10, что лучше?
> Станбатоны больше не имеют смысла, потому что цель встанет между ударами и убежит, соси хуй.
> Связать кого-то? Теперь это пиздец задачка, удачи хлопчик.
> 
> Короче если добавлять, то только в тестовом режиме на короткий период времени не на мейн сервер.

Дисейблер кладет в стаминакрит с 3 выстрелов а 3 секунды недостаточно чтобы нанести второй удар станбатоном. Дальше не читал. Ты точно про наш билд?

2021-07-19 15:32 UTC, Jordanstolethepreciousslam commented
Текущие выявленные проблемынуждающиеся в решении на 19.07.2021
-Глейр тенеморфов. Поднять время стана(и заодно время наручников) дабы можно было грабать чела но не связывать за время глейра. Вернуть старую немоту. Либо иное решение которое даст вампиру возможность пленить голыми руками но не за пару кликов. Короче переработать.
-Глейр вампира. То же самое что и с глейром тенеморфом. Хотя и можно использовать бутылки, станпрод или перчатки, возможно стоит сделать возможным захват живьем с одними наручниками и голыми руками. Короче переработать.
-Станы культяпок нуждаются в переработке
-Энергопотребление киборга
-снизить урон дизейблера с 30 до 20. У него выше скорострельность, так что пускай кладет в стаминакрит за 5 попаданий.
-Урезать станы со взломанного дефиба
-Урезать немного стан бипски 
-Проверить код на баг с вечным станом в грабе.

2021-07-19 23:45 UTC, OpsCoretango commented
у нас есть система болих?
т. е от чркзвычайной боли чел валится или не может двигатся.

2021-07-20 09:04 UTC, Jordanstolethepreciousslam commented
-Тазеры теперь наносят 25 стамина урона(4 попадания до стаминакрита)
-Дисйблеры наносят 33 стамина урона(те же 4 попадания до стамина крита)
-Станбатоны наносят на 50% больше стамина урона (стамина крит за 7 ударов)
-Повышен шанс стана телескопички на 2 тика вместо одного (с 20% до 50%)
=разные значения урона(при одинаковых количествах попаданий до стаминакрита) будут иначе воздействовать на цели под наркотой(регенерирующей выносливость)
-Все апгрейды грабов ускорены на 10%
-Станы от дефибов порезаны
-Станбатоны наносят на 50% больше стамина урона (стамина крит за 7 ударов)
-Мут от глейра шэдоулинга возвращен к старым значениям.
-Потребление энергии дисейблером борга уменьшено с 250 до 175
-Изменены значения восстановления стамины у некоторых наркотиков и химикатов
-Бипски понерфлен. Роняет на полсекунды и дает стаминакрит за 3 удара. Sleep tight comrade.
-Глейры теперь роняют на достаточное время для связывания, но любые простые общедоступные химикаты уменьшающие стан имеют шанс сократить время стана до безопасных значений(никотин, эпинефрин и прочие)
-Твикнуты следущие химикаты: Кровь Земли, Аранесп, Стимуляторный агент(адренал тритора), метамфетамин, эфедрин, эпинефрин

2021-07-21 11:05 UTC, Bizzonium commented
Обновил тестовый сервер, после рестарта применятся изменения

2021-07-21 14:36 UTC, Jordanstolethepreciousslam commented
-Переработаны глейры вампира и тенеморфа. Они теперь станят на 3 секунды, но накладывают эффект который уложит цель в стамина крит через 4-5 секунд. Самое то чтобы подергатся перед смертью.
-Уменьшена цена в крови для следущих абилок вампира.
--Теневой шаг(30-->15)
--Заражение(100-->50)
--Летучие мыши(75-->50)

2021-07-21 14:36 UTC, Jordanstolethepreciousslam commented
-Увеличен стамина урон от трейторского арбалета(30-->55) позволяя стамина крит с 2 попаданий

2021-07-21 14:39 UTC, Jordanstolethepreciousslam commented
В поисках решения для балансировки карпа-наркомана я совсем забыл о том что я - непризнанный гений уровня Кодзимы.
Совсем недавно я бафал самодельные арбалеты и удавки. Самодельный арбалет и пневмопушка не стреляют прожектайлами, а значит игнорируют блок карпа. Такимм образом карп убивается копьями, стеклом и прочим метательным мусором.

2021-07-21 14:39 UTC, Jordanstolethepreciousslam commented
![image](https://user-images.githubusercontent.com/78968085/126507611-30ca8d9a-110b-4d77-ac35-50512336a845.png)

2021-07-21 15:09 UTC, FlyingFloor commented
Может я не прав, конечно, но чисто по тексту это очень сильно бафнет антагов. Инста-стан на 3 секунды, а потом ещё и стамина-крит. А чтобы уронить его, нужно ударить его 7 раз батоном, а ему нужно один раз бахнуть тебя глейром/два раза из арбалета. Как по задумке это должно баланситься? СБ/кекепаж должны на антага стаей накидываться чтобы у них хотя бы малейший шанс был? Или просто переходим к использованию летала до крита, а потом уже разбираться что антаг натворил?

2021-07-22 10:34 UTC, Jordanstolethepreciousslam commented
> Кажется, что в этом билде станбатоны вообще не нужны будут.

Батоны кладут в стан сразу. Отличие в том что этот стан слишком короткий для наручников но достаточен чтобы ударить снова. А вот стаминакрит уже достаточен для наручников

2021-07-27 14:52 UTC, Jordanstolethepreciousslam commented
-Гипноз вампира теперь усыпляет цель становясь таким образом действительно осмысленной абилкой. Время применения увеличено.
-Триторский арбалет теперь станит как батон, но стаминакрит с 3 попаданий

2021-08-08 14:33 UTC, Jordanstolethepreciousslam commented
Ы

2021-09-14 15:11 UTC, Ohar commented
С принятием ЭТОГО задержание преустпников на СБ превратится из «доминатор — наручники» в гачимучи с хватанием за попец и мацанием сосочков.
 СРП СБ точно придётся переписывать.

2021-09-14 19:14 UTC, Jordanstolethepreciousslam commented
> С принятием ЭТОГО задержание преступников на СБ превратится из «доминатор → наручники» в гачимучи с хватанием за попец и мацанием сосочков. Вы правда этого хотите?
> 
> Ну и СРП СБ точно придётся переписывать.

Как и должно быть. Задержание живьем сложнее убийства. А нелетальное оружие не должно быть в разы эффективнее летала. 

Переписывать СРП? Каво? У нас сейчас вполне прописаны ограничение на летал и они даже подразумевают что леталить проще чем убивать ТОЛЬКО ВОТ В НАШЕМ БИЛДЕ ЭТО НЕ ТАК)0)0)))).
Да им сейчас его надо переписать, запретив тазеры нахуй с поднятием кода чтобы противостояние не превращалось в ебаный цирк когда тритор использует крупнокалиберную револьвер будучи одетым в  элитный хардсьют синдиката а против него выходит челик с ТАЗЕРОМ и курткой на голую жопу и БУКВАЛЬНО ебет и сушит потом что ВООРУЖЕН ЛУЧШЕ чем тритор.

2021-09-15 09:24 UTC, blind0 commented
абсолютно точно ЗА, станы в текущем их виде слишком имбалансные и нелогичные.

2021-11-02 12:40 UTC, Jordanstolethepreciousslam commented
Полный чейнджлог на 02.11.2021
	Экипировка станции
		Нелетальное
			Дефибриляторы
				Оглушение при использовании уменьшено с 5 до 2
			Телескопический батон
				Оглушение уменьшено с 6 до 2 тиков
				Шанс в 25% при ударе оглушить на 3 тика.
			Светошумовые гранаты
				Максимальное оглушение уменьшено с 10 до 4 тиков.
			Наручники
				Время надевания увеличено с 3 до 5 секунд.
			Болы
				Увеличено время требуемое для снятия энерго-болы с 2 до 4 секунд.
				Увеличено время требуемое для снятия обычной болы с 3.5 до 6 секунд.
				Скорость полета бол утроена.
			Скользкие поверхности
				Оглушение от подскальзывания на скользких поверхностях снижено с 4 до 2 тиков.
			Станбатон
				Оглушение уменьшено с 7 тиков до 2.
				Теперь наносит 20 урона выносливости при ударе.
				Потребление заряда при ударе уменьшено с 1000 до 400.
			Станпрод
				Оглушение уменьшено с 5 до 2 тиков.
			Бипски
				Оглушение уменьшено с 5 до 2 тиков.
				Наносит 45 урона выносливости при ударе.
			Захваты
				Заполнение шкалы захвата теперь на 10% быстрее.
				Оглушение от удушающего захвата уменьшено с 5 до 2 тиков.
			ПДА клоуна
				Оглушение снижено с 8 до 5 тиков.
			Электрод
				Снижено потребление энергии этим снарядом для большинства оружия.
				Оглушение уменьшено с 5 до 1 тика.(Даже не стан а просто разоружение)
				Теперь наносит 25 урона выносливости при попадании.(4 до стамина крита)
			Парализатор
				Урон выносливости увеличен до 33.(4 до стамина крита)
			Оглушающий слаг
				Урон выносливости мнижен с 80 до 66.
			ТазерСлаг
				Оглушение уменьшено с 5  тиков до 1.
				Теперь наносит 25 урона выносливости.

	Летальное
		Случайное оглушение в ближнем бою для всех источников уменьшено с 4 тиков до 2(включает в себя как дизармы так и оглушения от двойного светового меча).
			Самодельный арбалет
				Урон повышен с 25 до 33.
				Добавлено 15 бронепробития. 
			LWAP
				Оглушение уменьшено с 5 до 2 тиков
				Теперь наносит 40 урона выносливости
			Режим казни Доминатора
				Урон увеличен с 40 до 50.
				Урон выносливости увеличен до 33.
			Картечь(buckshot)
				Урон увеличен с 12.5 до 14
				Бронепробитие увеличено с -30 до -20.
			Самодельная картечь
				Урон увеличен с 6 до 8
			Метеоритная пуля
				Оглушение уменьшено с 8 тиков до 2.

	Разное
		Никотин
			Шанс снижения стана уменьшен с 50% до 25%
			Восстановление выносливости удвоено.
		Метамфетамин
			Лечение оглушения уменьшено с 2.5 в тик до 2.
			Теперь восстанавливает 7 выносливости в тик.
		Аранесп
			Восстановление выносливости уменьшено с 40 до 9.
		Ультра смазка
			Восстановление выносливости увеличено с 2 до 7.
		Эфедрин
			Восстановление выносливости утроено.
		Кровь земли
			Восстановление выносливости снижено с 30 до 9.
		CNS Rebooter
			Оглушение при воздействии ЭМИ уменьшено с 5 тиков до 2.
			Более не снимает оглушение
			Теперь восстанавливает 9 выносливости в тик если суммарный урон выносливости превышает 60.

	Экипировка антагонистов
		Нелетальное
			Mind Batterer
				Разброс оглушения снижен с 4-7 тиков до 1-3.
				Теперь наносит случайный урон выносливости с разбросом 20-60.
			Ксеноморфы
				Шанс оглушения дизармом ксеноморфа уменьшен со 100% до 40%.
				Время оглушения уменьшено до 1 тика
				Теперь наносит от 10 до 20 урона выносливости при ударе.
			Пальцевый пистолет мима
				Оглушение уменьшено с 3 до 1 тика.
			Банановый посох
				Оглушение снижено с 5 тиков до 2.

		Летальное
			Энергетический топор
				Оглушение уменьшено с 4 до 3 тиков.
			Бензопила
				Оглушение уменьшено с 4 тиков до 1.
			Мьёльнир
				Оглушение уменьшено с 3 до 2 тиков
			Снайперская винтовка
				Оглушение уменьшено с 5 до 2 тиков.
			Плевок нейротоксином
				Оглушение снижено с 5 тиков до 1.
				Урон повышен с 5 до 33.
			Энергетический арбалет
				Оглушение снижено с 5 тиков до 2.
				Теперь наносит 40 урона выносливости.

		Способности
			Тенелинг
				Glare 
					Оглушение в упор уменьшено с 10 тиков до 2.
					Теперь наносит 70 урона выносливости
					Добавлен эффект DOT который наносит по 10 урона выносливости в течение 5 тиков
				Icy veins
					Оглушение уменьшено с 2 тиков до 1.
				Blindness smoke
					Оглушение уменьшено с 3 тиков до 2
			Вампир
				Glare
					Оглушение в упор уменьшено с 5 тиков до 2.
					Теперь наносит 70 урона выносливости
					Добавлен эффект DOT который наносит по 10 урона выносливости в течение 5 тиков
				Rejuvenate
					Мгновенное восстановление выносливости снижено с 75 до 60
					Теперь лечит по 10 урона выносливости в течение 5 тиков с момента применения.
				Hypnotize
					Время применения увеличено с 5 до 6 секунд.
					Более не оглушает
					Накладывает сон на 20 тиков.
				Deseased touch
					Стоимость в крови уменьшена со 100 до 50.
				Chiropteran Screech
					Оглушение уменьшено с 4 до 2 тиков.
					Наносит 60 урона выносливости.
				Summon Bats
					Стоимость в крови уменьшена с 75 до 50.
				Shadowstep
					Стоимость в крови уменьшена с 30 до 15.
			Предатель
				Адреналиновый имплант
					Восстановление выносливости увеличено в 5 раз.

2021-11-02 12:42 UTC, Jordanstolethepreciousslam commented
[Changelog.txt](https://github.com/ss220-space/Paradise/files/7460705/Changelog.txt)

2021-11-02 12:43 UTC, Jordanstolethepreciousslam commented
Читабельный вариант по ссылке

2021-11-02 12:52 UTC, Jordanstolethepreciousslam commented
Спорим без merge конфликтов не обойдется?

2021-11-02 16:18 UTC, Gnatr commented
ЦНС который регенит стамину, эми теперь обязательна будет что ли

2021-11-02 16:33 UTC, azorko9695 commented
Выглядит как что-то интересное и стоящее попытки
За

2021-11-05 20:48 UTC, Vallat requested changes
На твики не смотрел, так как не занимаюсь балансом, но некоторые изменения механик надо доработать

2021-11-05 20:48 UTC, Vallat commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			sleep(35)
Если у нас несколько целей, то с таким кодом стамина будет уменьшатся не у всех одновременно, а у каждого последовательно за другим. Т.е. каждый следующий человек будет ждать по 17.5 секунд пока его стамина не начнет уменьшаться. Решаем "асинхронностью"
```suggestion
		spawn for(var/i = 1 to 5)
			target.adjustStaminaLoss(10)
			sleep(35)
```

2021-11-05 20:48 UTC, Vallat commented on code/modules/mob/living/carbon/human/human_defense.dm
> +					visible_message("<span class='danger'>[M] has tackled down [src]!</span>")
Попытку уронить надо тоже логировать, иначе в 60% случаев мы просто исключаем логирование взаимодействия между мобами

```suggestion
				src.adjustStaminaLoss(rand(10,20))
				if(prob(40))
					apply_effect(1, WEAKEN, run_armor_check(affecting, "melee"))
					add_attack_logs(M, src, "Alien tackled")
					visible_message("<span class='danger'>[M] has tackled down [src]!</span>")
				else
					visible_message("<span class='danger'>[M] tried to tackle down [src]!</span>")
					add_attack_logs(M, src, "Alien tried to tackle")
```

2021-11-13 14:46 UTC, Jordanstolethepreciousslam commented
[Changelog.txt](https://github.com/ss220-space/Paradise/files/7532256/Changelog.txt)

2021-11-13 14:48 UTC, YaPajiloiKotik commented
ахуенно пиздец как ахуенно оооооо заебись азиз бог и жордан тоже оооо

2021-11-16 12:36 UTC, Jordanstolethepreciousslam commented
[Changelog.txt](https://github.com/ss220-space/Paradise/files/7546279/Changelog.txt)

2022-01-06 21:55 UTC, Jordanstolethepreciousslam commented
[Changelog.txt](https://github.com/ss220-space/Paradise/files/7824919/Changelog.txt)

2022-01-13 17:04 UTC, Jordanstolethepreciousslam commented
[Uploading Changelog.txt…]()

2022-01-13 17:05 UTC, Jordanstolethepreciousslam commented
[Changelog.txt](https://github.com/ss220-space/Paradise/files/7864569/Changelog.txt)

2022-01-23 15:42 UTC, Jordanstolethepreciousslam commented
[Changelog.txt](https://github.com/ss220-space/Paradise/files/7920767/Changelog.txt)

2022-01-27 05:29 UTC, SergeyPomelov commented
1. Чейнджлог не полный сильно такое чувство. Нерф мыла нашёл только по коду.
2. Банальное падение на воде теперь сравнимо со смазкой или я пропустил нерф воды?

2022-02-05 22:00 UTC, merged

2022-02-06 13:22 UTC, Jordanstolethepreciousslam commented
[Changelog.txt](https://github.com/ss220-space/Paradise/files/8010257/Changelog.txt)

2022-02-07 03:36 UTC, Kirozet commented
проблема: вампир при выбитой стамине восстанавливается одной кнопкой за 20 крови и вгоняет в пермастанкрит другой кнопкой за 0 крови. Поймать вампиров с каким-то опытом игры и прожимания кнопок теперь попросту невозможно даже отрядом в два-три человека. Если он хоть немножко крови набрал, то его уже не поймать. КД глейра, учитывая что он не требует ресурсов, слишком низкое для такого бонуса как станкрит через 5-6 секунд.

2022-02-11 21:23 UTC, Kupelan commented
Я наверное опоздал с предложениями, но не лучше бы было усложнить всё в сторону реализма, а не усложнить механику игры, сделать из тазера аналог реальному с 1-2 зарядами, для станции ну пусть с тремя максимум, ведь попасть тоже нужно уметь, батонам оставить урон стамине и микростан, тут идея хорошая, в этом есть логика. Фактически у нового и уже более менее опытного игрока и так под контролем много кнопок и всяческих хоткеев ко всему, но тут попробуй среагируй на каждое противодействия игрока-антагониста, при условии, что в интересах обоих надавать друг другу по щам, а на антагонисте всегда, как правило играют поопытнее. В общем, тазеру надо вернуть тазер, я считаю, иначе логика отдела СБ немного улетучивается вместе с понятным геймплеем. Просто игра на СБ или антаге превратиться в потную катку после которой хочется отдохнуть.