Иконка у паука при таскании by Элл Гууд
ss220-space/Paradise pull request #1643
Opened 2022-11-26 12:15 UTC by PhantornRU

## What Does This PR Do
Пауки террора, большие пауки, Аранеус теперь при таскании имеют иконку "таскания" от Элл Гууд'а
![image](https://user-images.githubusercontent.com/41479614/204088411-00077c5e-1f4d-4bb2-9528-bb9eb5c68cc3.png)

2022-11-27 09:19 UTC, dj-34 requested changes
![image](https://user-images.githubusercontent.com/20109643/204127772-dddd2f38-9abe-493d-89c7-5adee6aa2415.png)

2022-11-28 15:14 UTC, Dimach commented
Линтер..

2022-11-30 01:58 UTC, PhantornRU commented on code/_onclick/hud/other_mobs.dm
> +	if(client && !hud_used)
```suggestion
	if(client & !hud_used)
```

2022-11-30 01:58 UTC, PhantornRU commented on code/_onclick/hud/other_mobs.dm
> +	if(client && !hud_used)
```suggestion
	if(client & !hud_used)
```

2022-11-30 01:59 UTC, PhantornRU commented on code/_onclick/hud/other_mobs.dm
> +	if(client && !hud_used)
```suggestion
	if(client & !hud_used)
```

2022-11-30 02:00 UTC, PhantornRU commented
@Dimach поправлено

2022-11-30 15:39 UTC, Dimach commented
Все равно линтер kekw

2022-11-30 15:39 UTC, Dimach commented
Вам тесты для чего сделаны

2022-11-30 15:49 UTC, PhantornRU commented on code/_onclick/hud/other_mobs.dm
> +/mob/living/simple_animal/hostile/retaliate/araneus
```suggestion
/mob/living/simple_animal/hostile/retaliate/araneus/create_mob_hud()
```

2022-12-01 07:43 UTC, dj-34 approved these changes

2022-12-01 23:57 UTC, merged