fix: update mob icon when painting/unpainting equipped items
ss220-space/Paradise pull request #1672
Opened 2022-12-01 16:17 UTC by yosoyrebelde

## What Does This PR Do
Иконка человечка теперь обновляется при покраске надетых предметов.
Иконки действий (e.g. "toggle helmet") также обновляются.
Пшикалкой с клинером теперь можно пшикнуть на надетый предмет (в том числе на шлем рига, что круто, так как сейчас нет способа очистить этот шлем). А также можно пшикнуть на предмет внутри сумки или просто на предмет лежащий не дальше соседнего тайла. При этом реагенты попадут только на кликнутый предмет.

## Images of changes
https://user-images.githubusercontent.com/79848183/205101583-222a2219-adb5-4465-8cb6-2331293f734e.mp4

## Changelog
:cl:
fix: update mob icon when painting equipped items
tweak: cleaner can be used on equipped items
/:cl:

2022-12-01 17:32 UTC, PhantornRU requested changes

2022-12-01 17:32 UTC, PhantornRU commented on code/datums/components/paintable.dm
> +	A.add_atom_colour(colour, WASHABLE_COLOUR_PRIORITY)
A.add_atom_colour(colour, WASHABLE_COLOUR_PRIORITY)
WASHABLE еще используется для крови, если не ошибаюсь.
Проверь как оно теперь работает с кровью. Ибо раньше перекрашенный риг можно было загрязнить кровью.
Возможно кровавый риг просто снесет краску. Поэтому FIXED и используется.

2022-12-01 17:51 UTC, yosoyrebelde commented on code/datums/components/paintable.dm
> +	A.add_atom_colour(colour, WASHABLE_COLOUR_PRIORITY)
WASHABLE нигде не используется. Кровь это не цвет атома, а отдельный оверлей. На перекрашенные вещи кровь наносится без проблем.

2022-12-02 02:11 UTC, Dimach commented on code/game/objects/items.dm
> +/obj/item/update_atom_colour()
color а не colour

2022-12-02 08:28 UTC, yosoyrebelde commented on code/game/objects/items.dm
> +/obj/item/update_atom_colour()
Название не моё, я просто переопределил функцию ¯\_(ツ)_/¯

2022-12-02 11:47 UTC, PhantornRU commented
Кстати смотрел баг почему коляски не ускоряется при красном зелье?

2022-12-02 12:07 UTC, yosoyrebelde commented
> Кстати смотрел баг почему коляски не ускоряется при красном зелье?

Полагаю, просто в коде не прописано, что они должны ускоряться. Зельки что-то делают только с obj/item и /obj/vehicle, а wheelchair это /obj/structure.

2022-12-02 15:48 UTC, Dimach commented on code/game/objects/items.dm
> +/obj/item/update_atom_colour()
Понял, значит вопрос снимается

2022-12-06 10:44 UTC, merged