Добавлен реконнект к WL после смерти
ss220-space/Paradise pull request #1704
Opened 2022-12-09 17:00 UTC by TrashDoxx

## Список изменений
• Смерть на основных серверах билда **Paradise** теперь реконнектит клиента к WL-серверу.

## Причины для ввода
• Мёртвые игроки на мёртвом сервере это чертовски органично.

2022-12-09 17:02 UTC, TrashDoxx commented
Фича была протестирована на локальном сервере. Работает безотказно.

2022-12-09 18:38 UTC, BeebBeebBoob commented
Боже

2022-12-09 18:48 UTC, BeebBeebBoob commented on code/modules/mob/living/death.dm
> +	client << link("byond://ru.game.ss220.space:7723")
Это будет вызывать рантаймы если в мобе не будет клиента.
Пример мартышка умер. Рантайм

2022-12-09 18:48 UTC, BeebBeebBoob approved these changes

2022-12-09 18:48 UTC, BeebBeebBoob requested changes
Короче рантаймы клиентов :P

2022-12-09 18:55 UTC, TrashDoxx commented on code/modules/mob/living/death.dm
> +	client << link("byond://ru.game.ss220.space:7723")
Сейчас поправлю.

2022-12-09 18:58 UTC, TrashDoxx commented
Насколько я понимаю, теперь ошибок во время исполнения кода быть не должно. Сейчас протестирую.

2022-12-09 19:20 UTC, TrashDoxx commented
Да, теперь всё так, как и планировалось.

2022-12-09 19:50 UTC, BeebBeebBoob approved these changes

2022-12-09 20:53 UTC, Bizzonium commented
Это не будет работать

2022-12-09 20:53 UTC, closed without merging

2022-12-09 22:22 UTC, TrashDoxx commented
Оно работает. Я проверял.

2022-12-10 05:21 UTC, Den109G commented
На что ВЛщики не пойдут, чтобы поднять онлайн. Чисто трупов на сервер кидать.