Slowing down movemnent when pushing/pulling something
ss220-space/Paradise pull request #1759
Opened 2022-12-18 11:43 UTC by AddRaiser

2022-12-18 15:52 UTC, Vallat requested changes

2022-12-18 15:52 UTC, Vallat commented on code/modules/mob/mob_movement.dm
> +
Уверен, что нам **нужно** каждый шаг дополнительно еще и здесь проходиться по всем атомам на турфе, куда мы собираемся ступить? Очень неэффективный способ добавлять делей, особенно с учетом того, что есть, собственно, функция толкания предмета, в которой и можно было бы добавлять делей к муву у толкнувшего

2022-12-18 15:52 UTC, Vallat commented on code/game/atoms_movable.dm
> +	var/slow_down_pull_push = TRUE
Уверен, что переменная должна быть булевой? Возможно стоит использовать числовое значение и использовать его как коэффициент замедления

2022-12-19 06:03 UTC, Vallat requested changes

2022-12-19 06:03 UTC, Vallat commented on code/modules/mob/living/living.dm
> +		new_delay = AM.get_pull_push_speed_modifier() * client.current_move_delay
Абсолютно бессмысленное разделение с проверкой
```suggestion
	var/new_delay = AM.get_pull_push_speed_modifier(client.current_move_delay) * client.current_move_delay
```

2022-12-19 06:03 UTC, Vallat commented on code/modules/mob/living/living.dm
> +	glide_for(client.current_move_delay)
Не надо обращаться к другой переменной когда есть локальная 🤓 
```suggestion
	glide_for(new_delay)
```

2022-12-19 06:03 UTC, Vallat commented on code/modules/mob/mob_movement.dm
> +			current_move_delay *= mob.pulling.get_pull_push_speed_modifier()
Тоже самое
```suggestion
		current_move_delay *= mob.pulling.get_pull_push_speed_modifier(current_move_delay)
```

2022-12-19 13:54 UTC, dj-34 commented
Юнит тест срёт рантаймами

2022-12-20 09:11 UTC, PhantornRU commented on code/modules/mob/living/living.dm
> +		return pull_push_speed_modifier * 1.2
Сюда не хватает добавить +0,2 дебафф за таскание толстого человека FAT (ген/нажирание)

2022-12-20 10:08 UTC, PhantornRU commented
Что насчет отсутствия гравитации?

2023-01-11 13:34 UTC, closed without merging