Реворк унатхов
ss220-space/Paradise pull request #1764
Opened 2022-12-19 17:33 UTC by captainnelly

## Описание

## Ссылка на предложение/Причина создания ПР

2022-12-20 08:54 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +				to_chat(H, "<span class='danger'>Слишком холодно, я сейчас усну...</span>")
А ты проверил, он не будет постоянно спамить это сообщение?
Может всё-таки лучше prob(5) выставить?

2022-12-20 08:55 UTC, PhantornRU commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	metabolization_rate = 1 * REAGENTS_METABOLISM
```suggestion
	metabolization_rate = REAGENTS_METABOLISM
```

2022-12-20 08:56 UTC, PhantornRU requested changes
Мелкие правки

2022-12-21 00:51 UTC, Den109G commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +
Уверен что оно не сломает ничего? Ты не пробовал хирургическим путём убрать глаза?

2022-12-21 10:51 UTC, captainnelly commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +				to_chat(H, "<span class='danger'>Слишком холодно, я сейчас усну...</span>")
Проверил. Там температура очень быстро понижается, т.е шаги большие, поэтому с мелкими значениями оно в чат не писало. Но можно чутка понизить, впринципе.

2022-12-21 10:53 UTC, captainnelly commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +
А, это я забыл убрать. Кое-что пытался сделать еще.

2022-12-24 06:45 UTC, Dimach commented on code/game/objects/items/stacks/medical.dm
> +		for(var/obj/item/carried_item in H.contents)
А не приведет ли это к тому что если игрок просто держит риг в руках на него нельзя будет применить медицину?

2022-12-24 06:47 UTC, Dimach commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +	if(H.reagents.get_reagent_amount("zessulblood") < 5)          //естественно генерируемое вещество, повышает болевой порог на 20 единиц и исцеляет
Коментарии на английский перепиши

2022-12-24 06:50 UTC, Dimach commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +		to_chat(H, "<span class='green'>[pick("Добро пожаловать в мои объятия, дитя...", "Это была славная охота, унатх.", "Мы не забудем о тебе...", "Я не смогла тебе помочь, прости...", "Как же тепло в е
Эшволкер подтип унати, ему тоже при смерти будет писать про Хисош что абсурдно. Как минимум поправь это, но я вообще не уверен что это прям хорошая идея при смерти писать игроку в чат что-то, он можнт быть из внеклановых не-религиозных унати

2022-12-24 14:14 UTC, captainnelly commented on code/game/objects/items/stacks/medical.dm
> +		for(var/obj/item/carried_item in H.contents)
Бля, приводит. Щас подумаем как починить

2022-12-24 14:40 UTC, captainnelly commented
@Dimach 
Я всё починил.

2022-12-25 06:40 UTC, larentoun commented on code/game/objects/items/stacks/medical.dm
> +				to_chat(user, "<span class='danger'>This can't be used on hardusits!</span>")
```suggestion
				to_chat(user, "<span class='danger'>This can't be used on hardsuits!</span>")
```

2022-12-25 06:40 UTC, larentoun commented on code/game/objects/items/stacks/medical.dm
> +		if(istype(H.head, /obj/item/clothing/head/helmet/space))
А что, в реворк унатхов входит нерф лечения в хардсьютах, или я что-то не понимаю?

2022-12-26 11:06 UTC, merged