Bar Update
ss220-space/Paradise pull request #1781
Opened 2022-12-25 17:11 UTC by sexyOleg

## Описание
Добавляет целых 8 новых видов алкоголя, и 57 разных коктейлей. Добавление системы звука при использовании шейкера

## Ссылка на предложение/Причина создания ПР
Подождём когда это одобрят на всех инстанциях.

## Демонстрация изменений
![drinks](https://user-images.githubusercontent.com/120050929/209475684-7fbe44fc-a6fa-4479-a839-c2bd9c35f45f.png)

https://docs.google.com/document/d/e/2PACX-1vTIyvxbs7Is--WDrJcoYHD8zlWxden2KOOtPQio4o4GaOcAuiyN1QQsy1-sRPLGwLQ67BSBrkMiDd1s/pub

2022-12-25 17:21 UTC, Den109G commented on code/modules/reagents/chemistry/recipes/drinks.dm
> +	id = "aperol"
Фича?

2022-12-25 17:33 UTC, sexyOleg commented on code/modules/reagents/chemistry/recipes/drinks.dm
> +	id = "aperol"
Мда, ну, кривые ручки

2022-12-27 05:44 UTC, Vallat requested changes

2022-12-27 05:44 UTC, Vallat commented on code/modules/reagents/chemistry/reagents/alcohol.dm
> +	..()
```suggestion
/datum/reagent/consumable/ethanol/alcomender/reaction_mob(mob/living/M, method=REAGENT_INGEST, volume, show_message = TRUE)
	if(!iscarbon(M))
		return
	if(method == REAGENT_INGEST)
		M.adjustFireLoss(-volume)
		if(show_message)
			to_chat(M, "<span class='notice'>Strong alcohol moisturizes the skin.</span>")
	return ..()
```

2022-12-27 05:44 UTC, Vallat commented on code/modules/reagents/chemistry/recipes/drinks.dm
> +	mix_sound = 'sound/goonstation/misc/drinkfizz.ogg'
Не логичнее ли будет вынести все "алкогольные" химические реакции под одного родителя и прописать переменные с одинаковым значением уже в нём? В данном случае это переменная `mix_sound`

2023-01-17 17:33 UTC, closed without merging