FEAT: New Goal - Bluespace Rift Scanner
ss220-space/Paradise pull request #1830
Opened 2023-01-05 17:36 UTC by PhantornRU

## Описание
Новая цель - Сканирование Блюспейс Разломов
```
Научно-исследовательская станция расположена на месте дислокации блюспейс разлома.
Задача станции изучить все аномалии производимые разломом с сбором данных. 
Собранные данные отправятся на изучение центральным научно-исследовательским отделом Нанотрейзен.
```
![image](https://user-images.githubusercontent.com/41479614/210837943-859cbda9-0c2c-43f0-b596-80f1d27208a4.png)

Один из серверов должен полностью изучить разломы, чтобы цель считалась засчитанной.
В протолате и в принтере плат добавлены новые платы и T-ray сканнеры.

### Объекты:
#### Блюспейс разломы:
1. Блюспейс разлом - обычный разлом средней мощности. Умеренная скорость.
2. Блюспейс Разлом - разлом большой величины и мощности. Медленный
3. Блюспейс Туманность - крайне опасный огромный разлом. Крайне медленный.
4. Разлом-Близнец - появляется сразу в 2-х экземплярах. Аномалии исходящие от одного разлома, исходят и от другого. Небольшого размера.
5. Блюспейс Трещина - малый разлом в 4-х экземплярах. Быстрый. Наименее опасный в критических зонах.
![image](https://user-images.githubusercontent.com/41479614/210843628-a156c9dc-f927-49eb-81ab-2040745e8296.png)

Если не сканировать разломы - они безвредны. При сканировании начинается процесс создания событий и аномалий со случайными эффектами и непредсказуемыми результатами.

Разломы смещаются исключительно в безопасные места на станции и их невозможно остановить или замедлить.

В директивах с ЦК указывается какой разлом предстоит изучить и просканировать:
![image](https://user-images.githubusercontent.com/41479614/210843945-89357096-d38a-4593-8ea5-8acab090d7fb.png)

#### Сервер:
![image](https://user-images.githubusercontent.com/41479614/210842133-97565953-7e02-4cd1-bde1-9d2197d331da.png)
Хранилище данных. Собирает данные со всех сканнеров, позволяет контролировать количество очков собранных всеми сканерами.
При наличии нескольких сканнеров, очки исследования делятся между ними при получении.
Шкала результата - шкала выбирающая максимальное значение из всех серверов.

При достижении заполненной шкалы - выдает награду 1 раз за одну цель.
При достижении заполненной шкалы стимуляции - позволяет "попытать удачу" и сыграть в рулетку с разломом, где с 50% шансом выпадет либо случайный предмет, либо аномалия. Выпадение происходит в самом блюспейс разломе.

##### Интерфейс:
![image](https://user-images.githubusercontent.com/41479614/210836642-965e77bc-f575-4344-9eda-6d1b8a6bd4ce.png)

Статусы серверов:
![image](https://user-images.githubusercontent.com/41479614/210844360-b69637e7-b57b-47eb-a279-0bc0b151630d.png)

#### Сканнеры:
Виды сканеров:
1. Динамичный сканер - переносный и удобный сканер, который возможно свободно перемещать при откручивании и прикручивании пола. Малое время для устойчивости в критической зоне, малый радиус сканирования.
![image](https://user-images.githubusercontent.com/41479614/210842228-46302a01-f836-4c8f-83e9-a658f1bb1d55.png)

2. Статичный сканер - дорогой статичный сканер, требующий постоянного подключения к сети. Большой радиус сканирования и продолжительное время устойчивости в критической зоне.
Статичный сканер вращается при отсутствии разлома в зоне его досягаемости. И поворачивает свой сканер при нахождении разлома.
![image](https://user-images.githubusercontent.com/41479614/210842284-5abf4486-6d56-4e6f-ae71-06991bd16ff1.png)

Все сканнеры перед работой необходимо активировать рукой. 

При нахождении в критических зонах - случаются перегрузки, за время которых нужно успеть отключить сканнер. Если не успеть его отключить - произойдет критический ивент и он взорвется, из-за чего его придется повторно ремонтировать.

Сканнеры позволяют получать очки изучения. 
Чем дольше они работают и чем ближе находятся - тем больше очков и тем больше шансов вызвать случайное событие у разлома с другими аномалиями.
ЕМП/Емаг переписывают протоколы безопасности сканнеров, из-за чего критической зоной становится зона вне радиуса сканирования разлома, а бывшая критическая зона - становится допустимой территорией для сканирования.

#### T-Ray сканнеры:
Сканнеры с увеличенной длительностью импульса или расстояния. Изучаются вместе с открытием технологий в протолате.
1. Обычный
2. Увеличенная дальность
3. Увеличенная продолжительность импульса
4. Дальность и импульс.
5. Научный T-ray сканнер с еще большим увеличением. Открывается на 8-м уровне технологии магнетизма.
6. Экспериментальный T-ray сканнер. Хайриск. Находится у РД в шкафу. Не изучаемый и нельзя разобрать.
![image](https://user-images.githubusercontent.com/41479614/210842922-491f78e3-de71-4158-af6a-47b77882358e.png)

## Ссылка на предложение/Причина создания ПР
Авоут пройден. Дополнительная информация и детали в посте в Авоуте или АРАБской.
https://discord.com/channels/617003227182792704/755125334097133628/1048958642294100140

## Демонстрация изменений
![image](https://user-images.githubusercontent.com/41479614/210836906-897a5ea2-7b7e-4d77-9192-c955ece7e18d.png)

2023-01-05 17:37 UTC, PhantornRU commented
Завтра пофикшу перекрашивание разлома. А то чего-т он поломалься.
А также оторву гостам руки чтобы они больше не могли жмякать кнопочки на сервере.

2023-01-06 00:30 UTC, Den109G commented
Это что, теперь можно потрогать паралакс?

2023-01-06 13:39 UTC, Den109G commented on code/modules/station_goals/brs/brs_rift.dm
> +	color = temp_colour
А просто `color = rand_hex_color()`?

2023-01-06 14:10 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_rift.dm
> +	color = temp_colour
имеет смысл, но ничего не поменяет по сути дела. Шо так шо так один и тот же цвет перекрашивается.

2023-01-06 15:24 UTC, BeebBeebBoob requested changes

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/__DEFINES/rift.dm
> +// Тип разлома
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/__DEFINES/rift.dm
> +// Тип ивента
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/__DEFINES/sight.dm
> +#define INVISIBILITY_ANOMALY 40	//значение видимости аномалии/разлома гостами и сканерами
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/game/gamemodes/steal_items.dm
> +	protected_jobs = list("Research Director")
Это не входило в сделку предожки

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/game/objects/items/devices/scanners.dm
> +/obj/item/t_scanner/experimental	//хайриск который нельзя разобрать, так как эта хуйня изобретена ну сами знаете кем.
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/grenades/clusterbuster.dm
> +/obj/item/grenade/clusterbuster/eng_tools
Смысл?

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/research/designs/equipment_designs.dm
> +	req_tech = list("magnets" = 7, "biotech" = 7, "engineering" = 3)
Это входило в сделку?

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs.dm
> +// Цель для исследования аномального блюспейс разлома с созданием портативных и статичных сканеров
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_event_container.dm
> +//Выбор локального ивента
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_event_container.dm
> +//Выбор локального связанного ивента
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_event_container.dm
> +//Телепорты в небольшом радиусе
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_event_container.dm
> +			investigate_log("teleported reshuffle [key_name_log(H)] and [key_name_log(temp_object)]", INVESTIGATE_TELEPORTATION)
```suggestion
			investigate_log("switched places [key_name_log(H)][COORD(H)] and [key_name_log(temp_object)][COORD(temp_object)]", INVESTIGATE_TELEPORTATION)
```
И не объект, а моб

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_event_container.dm
> +		explosion(O.loc, 0, 1, fs, 2*fs, flame_range = 3*fs, cause = O)	//Вставлять O.loc???
Смысл переменной? 
Суй сразу туда его, убирай
А O.loc на O

```suggestion
		explosion(O, 0, 1, force_sized, 2*force_sized, flame_range = 3*force_sized, cause = O)
```

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_event_container.dm
> +		empulse(O.loc, fs, 2*fs, TRUE, name)
```suggestion
		empulse(O, force_sized, 2*force_sized, TRUE, name)
```

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_event_container.dm
> +//Выбираем гранату и сразу же её подрываем, тем самым "воруя" её эффект хе-хе-хе
Молодец. А потом будешь объяснять людям почему аномалия кидается гранатами.
Не говоря что ты весь код разломал на несколько функции

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_event_container.dm
> +//Выбираем гранату и сразу же её подрываем, тем самым "воруя" её эффект хе-хе-хе
Хотя я хз. Там же задержка перед взрывом. Но это самый ужасный костыль.

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_event_container.dm
> +//рандомизация днк
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_event_container.dm
> +//Рандомизация расы и её преференса
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_reward.dm
> +//================ Объекты ================
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_reward.dm
> +//блюспейс толкан
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_reward.dm
> +	icon_state = "bluespace_toilet00-NT"
А вот честно. Нету что либо получше чем сортирный юмор?
Пупс, давай как адекват, придумай нормальную награду. К примеру универсальный телепортер или возможность как-то стабилизировать аномалии. Чтобы интересно и без юмора на уровне туалетного

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_reward.dm
> +/obj/structure/toilet/bluespace/proc/teleport(var/range_dist = 1)
Мог просто teleport() без единицы

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_reward.dm
> +		//Игрушки которые ты скорее всего никогда не получишь и ненужная мелочевка
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_reward.dm
> +		//Игрушки
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_reward.dm
> +		//Тип предмета, его вес
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_reward.dm
> +		//Не самые ценные вещи по прежнему могут выпасть, хоть и с небольшим шансом суммы их всех:
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_reward.dm
> +		//Магические вещи блюспейса с наиминимальнейшим шансом для появления
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_reward.dm
> +		//Бабки, бабки, сука, бабки!
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +//Блюспейс разлом для создания веселья и беготни на станции
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +	//для отображения T-ray сканнера
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +	var/event_chance = 100	//Шанс появления ивентов для избегания флуда ивентами
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +	to_chat(user, "<span class='danger'>Невозможно взаимодействовать с разломом!</span>")
Ломом по разлому
Разлом:

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +//Работа с весами в контейнерах
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +//Портативный сканер 1х1
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +	var/static/gid = 0
?????

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +	//деление очков на все сервера
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +	//Прохождение критического порога
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +		icon_state = prefix
Мои глаза. Убери лестницу.

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +//Взаимодействия, разбор
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +//Выдвижение и задвижение д.сканнера, активация ст.сканнера
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +//Перезапись протоколов безопасности.
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +		to_chat(user, "<span class='warning'>@?%!№@Протоколы безопасности сканнера перезаписаны@?%!№@</span>")
-_-

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +		rewrite_protocol()
Емаг лох

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +		rewrite_protocol()
И сканнер тоже лох

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +// Составные компоненты
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +//Статичный сканер 3х3
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +	max_range = 50	//максимальное расстояния для исследований
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +// Составные компоненты
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_server.dm
> +//Сервер для контроля спутников
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_server.dm
> +//Сервер для контроля спутников
Стоп спутников???

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_server.dm
> +//==========Взаимодействия========
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_server.dm
> +// Составные компоненты
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_server.dm
> +//Перезапись протоколов безопасности.
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_server.dm
> +		rewrite_protocol()
Емаг и защита от Эми лохи

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_server.dm
> +//Интерфейс
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_server.dm
> +				playsound(loc, 'sound/machines/buzz-two.ogg', 100, 1)
На английском

2023-01-06 15:24 UTC, BeebBeebBoob commented
Я пока что на телефоне просмотрел.

2023-01-06 21:36 UTC, BeebBeebBoob requested changes

2023-01-06 21:36 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +	transform = matrix(force_sized, 0, 0, 0, force_sized, 0) //+ перекрас?
А может без transform?
Сделаешь нормальные спрайты, ибо смотря на тех размытых слаймов... кошмар

2023-01-06 21:36 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +	transform = matrix(force_sized, 0, 0, 0, force_sized, 0) //+ перекрас?
Это также будет понятно людям и приятнее.

2023-01-06 21:36 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +
```suggestion
//For admins
```
Иначе по другому не объяснит смысл существование данных подтипов

2023-01-06 21:36 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +/obj/brs_rift/twin/t_static	//Для тестов и баловства
На английском

2023-01-06 21:36 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +	color = temp_colour
@Den109G имел смысл если не юзалось в строке 248

2023-01-06 21:36 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_rift.dm
> +/obj/brs_rift/proc/make_related_list(var/n = 1, var/type_rift)
Что за n?

2023-01-06 21:36 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +	var/min_dist = max_range*2
а не max_dist?
смотря по строке 217 и 218
```
var/temp_range = max_range + rift.force_sized
if (dist <= temp_range && dist <= min_dist)
```
Да при этом, в чём смысл если мы и так проверяем до max_range плюс размер rift. максимальный rift 9 что меньше сканера на 10
/shrug
достаточно проверка что rift в пределах сканера плюс его размера.

Пример:
Сканер = 10
Рифт = 9
Дистанция = 14 для примера
if( 14 <= 19 и 14 <= 10*2) 
/shrug

2023-01-06 21:36 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +/obj/machinery/brs_scanner/s_static
```suggestion
/obj/machinery/brs_scanner/static
```
brs scanner scanner static

2023-01-06 21:36 UTC, BeebBeebBoob commented on code/modules/station_goals/brs/brs_scanner.dm
> +		else	//При ЕМАГе, возможно сканирование в любом радиусе. Вне его - критическая зона
На английском

2023-01-07 04:42 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_event_container.dm
> +//Выбираем гранату и сразу же её подрываем, тем самым "воруя" её эффект хе-хе-хе
Там нет задержки перед взрывом. Там мгновенный активатор

2023-01-07 04:42 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_event_container.dm
> +		empulse(O.loc, fs, 2*fs, TRUE, name)
Для более понятного кода - лучше оставить fs чтобы строчки не было на пол экрана. Это не в одном месте так.

2023-01-07 04:43 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_event_container.dm
> +		explosion(O.loc, 0, 1, fs, 2*fs, flame_range = 3*fs, cause = O)	//Вставлять O.loc???
Если совать просто O, он в некоторых моментах не может получить TURF и просто ломается, не воспроизводя функцию. Я ж изначально так и делал

2023-01-07 04:43 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_event_container.dm
> +		explosion(O.loc, 0, 1, fs, 2*fs, flame_range = 3*fs, cause = O)	//Вставлять O.loc???
```suggestion
		var/fs = force_sized
		explosion(O.loc, 0, 1, fs, 2*fs, flame_range = 3*fs, cause = O)
```

2023-01-07 04:44 UTC, PhantornRU commented on code/game/objects/items/devices/scanners.dm
> +/obj/item/t_scanner/experimental	//хайриск который нельзя разобрать, так как эта хуйня изобретена ну сами знаете кем.
зачем? В этом коде аглоязычники никогда рыться не будут. Это исключительно для нас фича.

2023-01-07 04:45 UTC, PhantornRU commented on code/game/objects/items/weapons/grenades/clusterbuster.dm
> +/obj/item/grenade/clusterbuster/eng_tools
фикс мелкий.

2023-01-07 04:46 UTC, PhantornRU commented on code/modules/research/designs/equipment_designs.dm
> +	req_tech = list("magnets" = 7, "biotech" = 7, "engineering" = 3)
Подтягивание под общие стандарты технологий и T-ray сканнера. Боевые технологии вообще никак не связаны с обнаружением. Биотеч - да. Комбат - нет.

2023-01-07 04:49 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_reward.dm
> +	icon_state = "bluespace_toilet00-NT"
В том-то и дело, что это цель для всей станции. И кроме как технологий всей станции ничего и не нужно. Иначе это поспособствует только игре одного человека, забравшим себе условный телепортер.
Плюс дополнительная награда в виде технологий открывает возможность печати научных T-рей сканнеров и высокобюджетных блюспейс технологий (которые отсутствуют, но которые якобы нельзя в нормальной игре получить). И буквально, из-за педальского отношения в отказе выдавать игрокам "что-то ПГшное", в ходе совещания, пришел к этому абсурду.

Стабилизация разлома тоже не имеет смысла, т.к. достаточно её не сканировать, чтобы она не спавнила аномалии.

Поэтому только такое. Максимально не нужное и шуточное.

2023-01-07 04:50 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_reward.dm
> +/obj/structure/toilet/bluespace/proc/teleport(var/range_dist = 1)
не мог, оно не только там используется, при разрушении там дистанция вроде под 9.

2023-01-07 04:52 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_scanner.dm
> +	var/static/gid = 0
Статичный тип данных.
Если вкратце, общая переменная для всех объектов, позволяющая нормально выдавать уникальный ID в моем проке.

2023-01-07 04:53 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_scanner.dm
> +		icon_state = prefix
как именно? Елочка вполне неплохо смотрится.

Свитч здесь не вариант, а каждый раз проверять или return'ать - не самое лучшее решение и только увеличит количество строк.

2023-01-07 04:54 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_scanner.dm
> +		rewrite_protocol()
Ибо нехуй держать сканнер под разломом, который пускает ЕМП ивент из-за другого сканнера неподалеку :))

2023-01-07 04:55 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_server.dm
> +//Сервер для контроля спутников
```suggestion
//Сервер для контроля сканнеров и наблюдения за выполнением цели
```

2023-01-07 04:56 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_scanner.dm
> +/obj/machinery/brs_scanner/s_static
static - тип данных.

2023-01-07 04:58 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_rift.dm
> +	transform = matrix(force_sized, 0, 0, 0, force_sized, 0) //+ перекрас?
на спрайты спрайтер нужен. А у нас лапки. Вдовесок они полупрозрачные и не видимы невооруженным глазом. Размытость в итоге только в плюс с сливанием при прозрачности играет.

2023-01-07 04:58 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_rift.dm
> +	transform = matrix(force_sized, 0, 0, 0, force_sized, 0) //+ перекрас?
![image](https://user-images.githubusercontent.com/41479614/211131865-591c157a-1947-491f-90f2-19f7c961693d.png)

2023-01-07 05:00 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_rift.dm
> +/obj/brs_rift/proc/make_related_list(var/n = 1, var/type_rift)
```suggestion
/obj/brs_rift/proc/make_related_list(var/num = 1, var/type_rift)
```

2023-01-07 05:00 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_rift.dm
> +	if(n <= 1)
```suggestion
	if(num <= 1)
```

2023-01-07 05:00 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_rift.dm
> +			if (length(rift.related_rifts_list) >= n)
```suggestion
			if (length(rift.related_rifts_list) >= num)
```

2023-01-07 05:01 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_rift.dm
> +			if(length(temp_list) >= n)
```suggestion
			if(length(temp_list) >= num)
```

2023-01-07 05:09 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_scanner.dm
> +	var/min_dist = max_range*2
И по итогу сломаем логику и добавим баг, т.к. нам не нужно max_range каждый раз умножать на 2, а только 1 самый первый раз. В дальнейшем он приобретает дистанцию.
```
if (dist <= temp_range && dist <= min_dist)
	min_rift = rift
	min_dist = dist
```

2023-01-07 05:20 UTC, PhantornRU commented
@BeebBeebBoob к чему делать комментарии на английском на русскоязычном проекте с русскоязычными разработчиками, в код которого полезут именно русскоязычные кодеры?
У нас нету англиков. А заставлять переводить русскоязычные комментарии на английский для наших же русскоязычного проекта, откуда фичи никуда не утекут и никогда не будут использоваться англиками - определенно странно.
Делаем мы всё же для себя. Иначе вернемся в эру переводов с наполеоновскими планами мультиязычности, где мультиязычность ну абсолютно никому не нужна.

А кодировка буквально не успеет испортиться к моменту всяких переездов с поломкой символов, т.к. потенциально мы всеравно будем двигаться на тот же СС14 через годик с лишним.

Уж кого, но я против перевода комментариев на английский. Это полностью наша разработанная фича и в неё будут рыться наши разрабы и сам я. И другие разрабы, и я, не должен/не должны сидеть и думать какую хуйню я там напереводил чтобы повторно напереводить обратно, чтобы понять что куда идет.

С названиями объектов, переменных - я согласен. Но они и так на английском. А комментарии на то и комментарии. Они исходят от того кто их пишет. И я лично не говорю в повседневности на английском. Мне это было бы крайне неудобно. Особенно если в будущем я вдруг соберусь расширять эту цель.

2023-01-08 14:54 UTC, dikers93 commented
> @BeebBeebBoob к чему делать комментарии на английском на русскоязычном проекте с русскоязычными разработчиками, в код которого полезут именно русскоязычные кодеры? У нас нету англиков. А заставлять переводить русскоязычные комментарии на английский для наших же русскоязычного проекта, откуда фичи никуда не утекут и никогда не будут использоваться англиками - определенно странно. Делаем мы всё же для себя. Иначе вернемся в эру переводов с наполеоновскими планами мультиязычности, где мультиязычность ну абсолютно никому не нужна.
> 
> А кодировка буквально не успеет испортиться к моменту всяких переездов с поломкой символов, т.к. потенциально мы всеравно будем двигаться на тот же СС14 через годик с лишним.
> 
> Уж кого, но я против перевода комментариев на английский. Это полностью наша разработанная фича и в неё будут рыться наши разрабы и сам я. И другие разрабы, и я, не должен/не должны сидеть и думать какую хуйню я там напереводил чтобы повторно напереводить обратно, чтобы понять что куда идет.
> 
> С названиями объектов, переменных - я согласен. Но они и так на английском. А комментарии на то и комментарии. Они исходят от того кто их пишет. И я лично не говорю в повседневности на английском. Мне это было бы крайне неудобно. Особенно если в будущем я вдруг соберусь расширять эту цель.

Это все хочет не бип, а димач с Азизом, попросту не пропускают руские такие подсказки

2023-01-17 04:58 UTC, PhantornRU commented
Я сломался и всё-таки сделал переводы комментариев :(

2023-01-17 05:02 UTC, PhantornRU commented on code/game/gamemodes/steal_items.dm
> +	protected_jobs = list("Research Director")
Убрал

2023-01-17 05:04 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_event_container.dm
> +			investigate_log("teleported reshuffle [key_name_log(H)] and [key_name_log(temp_object)]", INVESTIGATE_TELEPORTATION)
Поправил

2023-01-17 05:48 UTC, Dimach commented on code/modules/research/designs/equipment_designs.dm
> +	name = "Расширенный Т-сканнер"
Так, это конечно все волшебно но тебя ученые просто возненавидят за то что при поиске в менюхе протолата надо будет переключать раскладку, сделай хотя бы в нём на английском все

2023-01-17 05:49 UTC, Dimach commented on code/modules/research/designs/machine_designs.dm
> +	name = "Machine Design (Сервер сканирирования разлома)"
Тоже самое что выше

2023-01-17 05:51 UTC, Dimach commented on code/modules/station_goals/brs/brs_event_container.dm
> +			gr = new /obj/item/grenade/smokebomb(new_loc)
А почему бы эти тайппасы просто в list не сложить, и обращаться к ним по индексу?

2023-01-18 06:29 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_event_container.dm
> +			gr = new /obj/item/grenade/smokebomb(new_loc)
А ведь действительно!  Так и сделаю.

2023-01-18 06:30 UTC, PhantornRU commented on code/modules/research/designs/equipment_designs.dm
> +	name = "Расширенный Т-сканнер"
Ок, названия на английский переделаю

2023-01-18 07:21 UTC, PhantornRU commented on code/modules/station_goals/brs/brs_event_container.dm
> +			gr = new /obj/item/grenade/smokebomb(new_loc)
Вынес в отдельный список

2023-01-21 15:47 UTC, PhantornRU commented
@Dimach залил пак фиксов-времянок. Убрал из ротации, оставил для щитспавнов. Лучше побыстрее закинуть, чтобы оно в ротации не выпадало. То что щас на Тестмердже слишком жесткое для людей оказалось. Поэтому пускай пока под присмотрами педалей теперь только ставится. После того как окончу тестирования и завершения цельки уже буду выкатывать. Мож через полмесяца-месяц, как время выйдет, ибо до 10-го у меня щас завал будет небольшой.

2023-01-22 13:25 UTC, PhantornRU commented
Вкратце о цели:
![image](https://user-images.githubusercontent.com/41479614/213918224-2b0d2aa3-aaed-4a85-bd12-855319dc97e5.png)

2023-01-31 02:55 UTC, PhantornRU commented
ПР закрыт, так как я больше не собираюсь кодить для Парадайза.

2023-01-31 02:55 UTC, closed without merging

2023-01-31 02:56 UTC, PhantornRU commented
Жалко конечно что на этот ПР потратил кучу времени и новогодние праздники. Но если кто-то захочет продолжить - я буду не против. Но никто не захочет. Кодить для парадайза уж явно не стоит для сохранения своих нервов и достоинства.