feat: Пеплоходцы и риги
ss220-space/Paradise pull request #1841
Opened 2023-01-08 16:32 UTC by frikadeliSpaghetti

## Описание

Пеплоходцы больше не могут носить РИГи, костюмы ЕВА. При попытке поднять риг он улетит в случайном направлении на 2-5 тайлов.
## Ссылка на предложение/Причина создания ПР

Авоут пройден давно.
https://discord.com/channels/617003227182792704/755125334097133628/1043845128802021447
## Демонстрация изменений

2023-01-08 18:33 UTC, definitelynotspaghetti commented
![bleh](https://user-images.githubusercontent.com/48985748/211212811-538d7e62-ed9f-4c92-bddb-806fa72d3721.jpg)

2023-01-08 22:21 UTC, Jerrody commented
Можно я не буду это комментировать?

2023-01-09 07:51 UTC, Honker9999999 commented
Я, офк, не разраб и не контрибубор, но по моему отлетание на 2-4 тайла излишне и по предложке не прошло.

"Запретить кодом/механом возможность Пеплоходцам надевать на себя **любые** типы ригов(хардсьютов) и костюмов ВКД(В простонародье именуемые Евой) по аналогии с запретом, присутствующим на КА/ЕКА. 
Запрет заключается в невозможности Пеплоходцу нацепить на себя риг/костюм ВКД. "

2023-01-09 08:25 UTC, Honker9999999 requested changes
Добавь проверку на стан/паралич/отсутствие рук у эша. На данный момент `/obj/item/clothing/suit/equipped` проигрывается в том числе если одежду надел кто-то иной, из-за чего выходит что эш каким-то образом откинет скаф даже если он в стане/имеет отрезанные руки или вообще умер.
Кроме того, ты забыл` ..()`, из-за чего родительский код equipped не проигрывается, что потенциально сломает прятание хвостов при одевании скафандров вообще у всех.

2023-01-09 10:42 UTC, closed without merging

2023-01-09 10:44 UTC, Honker9999999 commented
Чзх тут только что произошла

2023-01-09 10:47 UTC, frikadeliSpaghetti commented
ничего