Новая озвучка объявлений и немного перевода.
ss220-space/Paradise pull request #199
Opened 2021-07-23 18:54 UTC by Danefalt

## Что делает этот ПР
Полная переработка звуков для объявлений. Так же есть часть перевода объявлений, однако оставшиеся часть не переведена. Впрочем, перевод не получили в основном очень редко использующиеся вещи, и их я буду переводить с будущими ПРами.

## Почему это хорошо для игры
Более красивые для ушей объявления, а перевод позволит новичкам легче понимать ситуацию.

2021-07-23 19:08 UTC, dj-34 commented
Замени sound_AI_welcome.ogg, у нас не станция "Exodus".

2021-07-25 11:50 UTC, Honker9999999 commented
> Замени sound_AI_welcome.ogg, у нас не станция "Exodus".

Не только. Там везде где есть название станции "Исход".

2021-07-25 12:36 UTC, Frostillikus21 commented
Будет довольно круто, ибо писк после приорити анонса откровенно достал и порой уши болят от них. Как и от повышений кода.

2021-07-25 12:37 UTC, Danefalt commented
Касательно недочётов: 
Гравиген ещё не получил своих аннонсов
У отбытия шаттла вообще нет кода для аннонса, и он выдаёт обычный писк
У запроса ОБР пока обычный писк
Ещё сейчас нет кода для аннонса выстрела с БСА (И не будет, пока я не найду саунд самого выстрела)
Ещё (возможно) часть малоиспользуемых вещей не получило своих анносов.
Вообщем, пишите мне если найдутся проблемы после принятия ПРа. Я уже работаю над первым патчем.

2021-07-25 13:59 UTC, dj-34 commented on code/modules/events/apc_overload.dm
> +	GLOB.event_announcement.Announce("Зафиксирована неизвестная активность в энергосети станции [station_name()]. В качестве меры предосторожности, питание на станции было временно отключено.", "КРИТИЧЕ
Оверлоуд APC = неизвестная активность? Что-то тут не так.

2021-07-25 14:12 UTC, dj-34 requested changes
Предложения

2021-07-25 14:12 UTC, dj-34 commented on code/modules/response_team/ert.dm
Возможно стоит сделать названия ERT по другому.
Я бы не переводил ERT в ОБР, а названия сделал бы по примеру:
отряд ERT "ГАММА", отряд ERT "КРАСНЫЙ", отряд ERT "ЯНТАРЬ"/"ЖЕЛТЫЙ".

2021-07-25 14:12 UTC, dj-34 commented on code/modules/station_goals/station_goal.dm
> +	GLOB.priority_announcement.Announce("Получена приоритетная деректива NanoTrasen. Детали проекта  \"[name]\" поступают.", "Поступает Приоритетное Сообщение", 'sound/AI/announces/commandreport.ogg')
Получена приоритетная деректива NanoTrasen \"[name]\", детали проекта высланы.

2021-07-25 14:12 UTC, dj-34 commented on code/modules/events/apc_short.dm
> +		GLOB.event_announcement.Announce("Все СПИНы [station_name()] были запитанны. Мы приносим извинения, за принесённые неудобства.", "Питание восстановлено", new_sound = 'sound/AI/event/poweron.ogg')
Нет слова "запитанны", можно написать "перезаряжены"/"заряжены".

2021-07-25 14:12 UTC, dj-34 commented on code/modules/events/apc_short.dm
> +		GLOB.event_announcement.Announce("Питание восстановлено для станции [station_name()]. Мы приносим извинения, за принесённые неудобства.", "Питание восстановлено", new_sound = 'sound/AI/event/powero
Питание на станции [station_name()] восстановлено.

2021-07-25 14:12 UTC, dj-34 commented on code/modules/events/apc_short.dm
> +		GLOB.event_announcement.Announce("Зафиксирована неизвестная активность в энергосети станции [station_name()]. В качестве меры предосторожности, питание на станции было временно отключено.", "КРИТИЧ
Все еще не понятно почему перегрузки и замыкания APC обозначаются как "неизвестная активность".

2021-07-25 14:12 UTC, dj-34 commented on code/modules/events/apc_overload.dm
> +	GLOB.event_announcement.Announce("Зафиксирована неизвестная активность в энергосети станции [station_name()]. В качестве меры предосторожности, питание на станции было временно отключено.", "КРИТИЧЕ
Оверлоуд APC = неизвестная активность? Что-то тут не так.

2021-07-25 14:12 UTC, dj-34 commented on code/game/gamemodes/blob/blob.dm
> +			GLOB.event_announcement.Announce("Подтвержденна биоугроза пятого уровня на станции [station_name()]. Персонал должен сдержать угрозу. Протоколы изоляции экипажа станции были активированны.", "БИОУ
Возможно "пятого" можно написать большими буквами, дабы выделить уровень опасности среди текста.

2021-07-25 16:33 UTC, Danefalt commented on code/modules/response_team/ert.dm
Перевод есть, так почему им не пользоваться?

2021-07-25 16:33 UTC, Danefalt commented on code/modules/station_goals/station_goal.dm
> +	GLOB.priority_announcement.Announce("Получена приоритетная деректива NanoTrasen. Детали проекта  \"[name]\" поступают.", "Поступает Приоритетное Сообщение", 'sound/AI/announces/commandreport.ogg')
Будет исправлено

2021-07-25 16:33 UTC, Danefalt commented on code/modules/events/apc_short.dm
> +		GLOB.event_announcement.Announce("Все СПИНы [station_name()] были запитанны. Мы приносим извинения, за принесённые неудобства.", "Питание восстановлено", new_sound = 'sound/AI/event/poweron.ogg')
Угу

2021-07-25 16:34 UTC, Danefalt commented on code/modules/events/apc_short.dm
> +		GLOB.event_announcement.Announce("Зафиксирована неизвестная активность в энергосети станции [station_name()]. В качестве меры предосторожности, питание на станции было временно отключено.", "КРИТИЧ
Слушай озвучку. Будет странно если озвучка и аннонс не совпадают.

2021-07-25 16:34 UTC, Danefalt commented on code/modules/events/apc_overload.dm
> +	GLOB.event_announcement.Announce("Зафиксирована неизвестная активность в энергосети станции [station_name()]. В качестве меры предосторожности, питание на станции было временно отключено.", "КРИТИЧЕ
Тот же ответ что и выше

2021-07-25 16:34 UTC, Danefalt commented on code/game/gamemodes/blob/blob.dm
> +			GLOB.event_announcement.Announce("Подтвержденна биоугроза пятого уровня на станции [station_name()]. Персонал должен сдержать угрозу. Протоколы изоляции экипажа станции были активированны.", "БИОУ
Why not?

2021-07-25 20:49 UTC, Danefalt commented
Не мержите пока, я заканчиваю первый патч

2021-07-29 10:15 UTC, Danefalt commented
Мержить можно.
P.S. Аннонсы для гравигена и консоли запросов я не завезла. Потому что аннонсы для гравигена я не могу нормально перевести, а у консоли запросов я вообще не могу найти нужный код. Да и впринципе это не так важно, так что ВОЗМОЖНО патчи на это будут выходить уже с новыми ПРами.

2021-07-29 19:13 UTC, DayBreakerBrony commented on code/game/gamemodes/blob/blob.dm
> +			GLOB.event_announcement.Announce("Подтвержденна биоугроза пятого уровня на станции [station_name()]. Персонал должен сдержать угрозу. Протоколы изоляции экипажа станции были активированны.", "БИОУ
Подтверждена с одной "н", это наречие

2021-07-29 19:13 UTC, DayBreakerBrony commented on code/game/gamemodes/shadowling/shadowling.dm
> +			GLOB.command_announcement.Announce("Высокое скопление психической блюспейс энергии обнаружено на сканерах дальнего действия. Вознесение тенеморфов неизбежно. Остановите это любой ценой!", "Дела Це
Может быть "остановите ЕГО?" у нас слова "остановите это" звучит как кринжовый машинный перевод.

2021-07-29 19:13 UTC, DayBreakerBrony commented on code/modules/events/anomaly_vortex.dm
> +	GLOB.event_announcement.Announce("На сканерах дальнего действия обнаружена вихрева аномалия высокой интенсивности. Предполагаемая локация: [impact_area.name]", "ВНИМАНИЕ: АНОМАЛИЯ", new_sound = 'sou
вихрева. вихреваЯ? наверное.

2021-07-29 19:13 UTC, DayBreakerBrony commented on code/modules/events/blob.dm
> +		GLOB.event_announcement.Announce("Вспышка биологической угрозы 5-го уровня зафиксирована на борту станции [station_name()]. Всему персоналу надлежит сдержать ее распространение любой ценой! Протоко
Мне кажется правильнее будет построить предложение так:
"Зафиксирована вспышка биологической угрозы 5-ого уровня на борту станции [station_name()]."

2021-07-29 19:13 UTC, DayBreakerBrony commented on code/modules/events/disease_outbreak.dm
> +	GLOB.event_announcement.Announce("Вспышка вирусной угрозы 7-го уровня зафиксирована на борту станции [station_name()]. Всему персоналу надлежит сдержать ее распространение.", "ВНИМАНИЕ: БИОЛОГИЧЕСКА
ио же самое, что  про другую вспышку

2021-07-29 19:13 UTC, DayBreakerBrony commented on code/modules/events/meteors.dm
> +			GLOB.event_announcement.Announce("Зафиксировано движение астероидов на встречном со станцией курсе.", "ВНИМАНИЕ: АСТЕРОИДЫ", new_sound = pick('sound/AI/event/meteors.ogg','sound/AI/event/meteors2.
предлагаю "на встречном курсе со станцией" . и переписать так же обычные метеориты

2021-07-29 19:13 UTC, DayBreakerBrony commented on code/modules/response_team/ert.dm
> +	GLOB.event_announcement.Announce("Внимание, поступил запрос отряда быстрого реагирования со станции [station_name()]. К сожалению, мы не сможем вам помочь в этот раз.", "ОБР не доступно", new_sound
"недоступно" слитно

2021-07-29 19:13 UTC, DayBreakerBrony commented on code/modules/security_levels/security_levels.dm
> +				GLOB.security_announcement_down.Announce("Все угрозы для станции устранены. Все оружие должно быть в кобуре, и законы о конфиденциальности вновь полностью соблюдаются.","ВНИМАНИЕ! Уровень угрозы
"все угрозы для станции" < "все угрозы станции"
лишнее для? наверное. душу.

2021-07-29 19:13 UTC, DayBreakerBrony commented on code/modules/security_levels/security_levels.dm
> +				GLOB.security_announcement_down.Announce("Все угрозы для станции устранены. Все оружие должно быть в кобуре, и законы о конфиденциальности вновь полностью соблюдаются.","ВНИМАНИЕ! Уровень угрозы
к тому же "законы о конфиденциальности вновь должны соблюдаться"

2021-07-29 19:15 UTC, Danefalt commented on code/game/gamemodes/shadowling/shadowling.dm
> +			GLOB.command_announcement.Announce("Высокое скопление психической блюспейс энергии обнаружено на сканерах дальнего действия. Вознесение тенеморфов неизбежно. Остановите это любой ценой!", "Дела Це
Событие - оно. Это не мужской род. Хотя...

2021-07-29 19:16 UTC, Danefalt commented on code/modules/events/anomaly_vortex.dm
> +	GLOB.event_announcement.Announce("На сканерах дальнего действия обнаружена вихрева аномалия высокой интенсивности. Предполагаемая локация: [impact_area.name]", "ВНИМАНИЕ: АНОМАЛИЯ", new_sound = 'sou
Это я не трогала. Не веришь, проверь текущий код на станции. Вопросы к тем кто делал перевод ранее

2021-07-29 19:16 UTC, Danefalt commented on code/modules/events/blob.dm
> +		GLOB.event_announcement.Announce("Вспышка биологической угрозы 5-го уровня зафиксирована на борту станции [station_name()]. Всему персоналу надлежит сдержать ее распространение любой ценой! Протоко
Вопрос к тем, кто переводил до меня

2021-07-29 19:17 UTC, Danefalt commented on code/modules/events/disease_outbreak.dm
> +	GLOB.event_announcement.Announce("Вспышка вирусной угрозы 7-го уровня зафиксирована на борту станции [station_name()]. Всему персоналу надлежит сдержать ее распространение.", "ВНИМАНИЕ: БИОЛОГИЧЕСКА
Тоже самое что и про другую вспышку

2021-07-29 19:17 UTC, Danefalt commented on code/modules/events/meteors.dm
> +			GLOB.event_announcement.Announce("Зафиксировано движение астероидов на встречном со станцией курсе.", "ВНИМАНИЕ: АСТЕРОИДЫ", new_sound = pick('sound/AI/event/meteors.ogg','sound/AI/event/meteors2.
Видишь изменения в переводе? А их нет. Это текущий перевод который уже есть на станции.

2021-07-29 19:18 UTC, Danefalt commented on code/modules/response_team/ert.dm
> +	GLOB.event_announcement.Announce("Внимание, поступил запрос отряда быстрого реагирования со станции [station_name()]. К сожалению, мы не сможем вам помочь в этот раз.", "ОБР не доступно", new_sound
С новыми патчами

2021-07-29 19:18 UTC, Danefalt commented on code/modules/security_levels/security_levels.dm
> +				GLOB.security_announcement_down.Announce("Все угрозы для станции устранены. Все оружие должно быть в кобуре, и законы о конфиденциальности вновь полностью соблюдаются.","ВНИМАНИЕ! Уровень угрозы
Уже существующий перевод.

2021-07-29 19:19 UTC, DayBreakerBrony commented on code/modules/events/blob.dm
> +		GLOB.event_announcement.Announce("Вспышка биологической угрозы 5-го уровня зафиксирована на борту станции [station_name()]. Всему персоналу надлежит сдержать ее распространение любой ценой! Протоко
и убрать бы восклицание из объявления. ну, это лично моё мнение

2021-07-30 10:46 UTC, ImJustKisik commented on code/game/gamemodes/shadowling/shadowling.dm
> +			GLOB.command_announcement.Announce("Высокое скопление психической блюспейс энергии обнаружено на сканерах дальнего действия. Вознесение тенеморфов неизбежно. Остановите это любой ценой!", "Дела Це
Higher Dimensional это не Высшие Измерения, а многомерные миры. 
Cuz'  Higher-dimensional algebra = многомерная алгебра, а не Алгебра Высших Измерений

2021-08-02 14:39 UTC, semoro commented on code/modules/events/apc_short.dm
> +		GLOB.event_announcement.Announce("Все СПИНы [station_name()] были заряжены. Мы приносим извинения, за принесённые неудобства.", "Питание восстановлено", new_sound = 'sound/AI/event/poweron.ogg')
А можно расшифровку? Просто SMES - Superconducting Magnetic Energy Storage

2021-08-02 14:40 UTC, semoro commented on code/modules/events/communications_blackout.dm
> +		GLOB.event_announcement.Announce("#4nd%;f4y6,>?%-БЗЗЗЗЗЗЗMCi46:5.;@63-БЗЗЗЗЗ", "ИоноcфеfZ\\kg5_0-БЗЗЗЗ", new_sound = 'sound/AI/announces/commsblackout.ogg')
А почему здесь более не используется случайный алерт?

2021-08-02 14:42 UTC, semoro commented on code/modules/response_team/ert.dm
Я за желтый здесь наверное

2021-08-02 14:46 UTC, Danefalt commented on code/modules/events/apc_short.dm
> +		GLOB.event_announcement.Announce("Все СПИНы [station_name()] были заряжены. Мы приносим извинения, за принесённые неудобства.", "Питание восстановлено", new_sound = 'sound/AI/event/poweron.ogg')
Сверх-проводной индуктивный накопитель

2021-08-02 14:47 UTC, Danefalt commented on code/modules/events/communications_blackout.dm
> +		GLOB.event_announcement.Announce("#4nd%;f4y6,>?%-БЗЗЗЗЗЗЗMCi46:5.;@63-БЗЗЗЗЗ", "ИоноcфеfZ\\kg5_0-БЗЗЗЗ", new_sound = 'sound/AI/announces/commsblackout.ogg')
Я просто не знаю как написать код для него, по этому пока так. Думаю исправлять в будущем.

2021-08-02 14:49 UTC, Danefalt commented on code/modules/events/apc_short.dm
> +		GLOB.event_announcement.Announce("Все СПИНы [station_name()] были заряжены. Мы приносим извинения, за принесённые неудобства.", "Питание восстановлено", new_sound = 'sound/AI/event/poweron.ogg')
Это ИРЛ расшифровка кста, перевод SMES на русский звучит именно так. И смесы кстати и есть ИРЛ штука.

2021-11-10 09:27 UTC, Ohar commented on code/game/gamemodes/miniantags/bot_swarm/swarmer_event.dm
> +		GLOB.event_announcement.Announce("Новый отчёт был загружен и распечатан на всех консолях коммуникаций..", "Входящее Секретное Сообщение", 'sound/AI/announces/commandreport.ogg')
Две точки «коммуникаций..»

2023-03-29 04:14 UTC, closed without merging