Robot transform animation
ss220-space/Paradise pull request #2026
Opened 2023-02-10 02:08 UTC by LiquidPotroh

## Описание
Добавляет анимации выбора модуля боргам, а так же анимации спавна синдиборгов, гамма-ерт борга и дедсквад борга.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1071095453543841912

## Демонстрация изменений
https://user-images.githubusercontent.com/100733800/217981928-4f5dcee7-b36b-46e4-9d43-5a6da819606e.mp4

2023-02-13 22:34 UTC, TrashDoxx commented
Откуда спизжено?

2023-02-13 22:34 UTC, TrashDoxx commented
Не помню, в какой билдуле я это видел.

2023-02-14 07:19 UTC, LiquidPotroh commented
@TrashDoxx код свой, анимация кажется со скайрата, у зюзи спроси

2023-02-14 13:48 UTC, TrashDoxx commented
> @TrashDoxx код свой, анимация кажется со скайрата, у зюзи спроси

Понял. Ну я про анимации говорил.

2023-02-14 13:53 UTC, TrashDoxx commented
Глянул на чистом TG, анимации там лет 5 уже присутствуют. Ну в общем, лучше указать, откуда порт спрайтов.

2023-02-14 14:42 UTC, TrashDoxx requested changes
Очень маленькое ревью.

2023-02-14 14:42 UTC, TrashDoxx commented on code/modules/mob/living/silicon/robot/robot.dm
> +	SetLockdown(1)
```suggestion
	SetLockdown(TRUE)
```
И хорошо бы саму процедуру подредачить на TRUE / FALSE.

2023-02-14 14:42 UTC, TrashDoxx commented on code/modules/mob/living/silicon/robot/robot.dm
> +	to_chat(src, "<span class='notice'>Your icon has been set[default?" by default":""]. You now require a reset module to change it.</span>")
Жесть, ни разу я не видел, чтобы тернарник в строку пихали.

2023-02-14 14:42 UTC, TrashDoxx commented on code/modules/mob/living/silicon/robot/robot.dm
> +	addtimer(CALLBACK(src, /mob/living/silicon/robot/.proc/complete_loading), 50)
Для читабельности используют дефайны SECONDS и MINUTES.
```suggestion
	addtimer(CALLBACK(src, /mob/living/silicon/robot/.proc/complete_loading), 5 SECONDS)
```

А вообще, тут бы переписать на:
`addtimer(CALLBACK(src, PROC_REF(complete_loading)), 5 SECONDS)`
Но насколько я помню, в этом репозитории это ещё не реализовано.

2023-02-14 14:42 UTC, TrashDoxx commented on code/modules/mob/living/silicon/robot/robot.dm
> +	SetLockdown(0)
```suggestion
	SetLockdown(FALSE)
```
И хорошо бы саму процедуру подредачить на TRUE / FALSE.

2023-02-14 14:46 UTC, TrashDoxx requested changes

2023-02-14 14:46 UTC, TrashDoxx commented on code/modules/mob/living/silicon/robot/robot.dm
> +		playsound(src.loc, pick('sound/items/drill_use.ogg', 'sound/items/jaws_cut.ogg', 'sound/items/jaws_pry.ogg', 'sound/items/welder.ogg', 'sound/items/ratchet.ogg'), 50, TRUE, -1)
```suggestion
		playsound(loc, pick('sound/items/drill_use.ogg', 'sound/items/jaws_cut.ogg', 'sound/items/jaws_pry.ogg', 'sound/items/welder.ogg', 'sound/items/ratchet.ogg'), 50, TRUE, -1)
```
Использование `src.loc` тут никакого импакта не вносит, с тем же успехом можно использовать просто `loc`.

2023-02-20 19:36 UTC, LiquidPotroh commented on code/modules/mob/living/silicon/robot/robot.dm
> +	to_chat(src, "<span class='notice'>Your icon has been set[default?" by default":""]. You now require a reset module to change it.</span>")
вайнот собственно?

2023-02-21 12:36 UTC, TrashDoxx commented on code/modules/mob/living/silicon/robot/robot.dm
> +	to_chat(src, "<span class='notice'>Your icon has been set[default?" by default":""]. You now require a reset module to change it.</span>")
Да я, собственно, ничего против не имею. Разве что это малочитабельно, но сойдёт.

2023-02-24 16:02 UTC, merged