feat: new space ruin
ss220-space/Paradise pull request #2041
Opened 2023-02-12 10:48 UTC by Petruha-Petruha

Уже прошедшая предложку космическая руина с ксеноморфами.

Co-Authored-By: dikers93 <97447484+dikers93@users.noreply.github.com>

## Описание
Добавляет новую космическую руину с ксеноморфами.

## Ссылка на предложение/Причина создания ПР
Прошедшая предложка лет 50 назад
https://discord.com/channels/617003227182792704/1031959291743191050/1031959291743191050

2023-02-17 10:19 UTC, SAADf603 requested changes
Engi - проводка не доходит до АЦП
Dorms - Переместить грибок от аираларма и огнетушителя, лампу на нижних окнах переместить на левую стену около телевизора, мусорку на тайл выше, цветок у мусорке на тайл ниже, удалить настенный маячок, наномед переместить от фальшивой стены, но не на окно
Entrance - стеклянную дверь переименовать на стандартую, зарядник на столе поместить выше, весит в воздухе, паутину в буфере входа убрать, иначе будет висеть в воздухе при открытии
Baracks - удалить маяк
Gym - душ на 6-8 пикселей правее, а не в проход
Admirals office - принтер поставить на стол вместо ящика, сейф переместить правее а не на тайл терминала АЦП
Med- вы камеры не настроили они в сети станции и исследований, а не СССП. Хотите с ккербероса за ксенами подглядывать? Огнетушитель убрать от грибов на стене, или наоборот. Все шаттеры лучше закрыть.
Out - под мусорку и вентиляюцию на юге поставить плейты вместо латисов, на востоке под гирдеры тоже, чуть ниже гирдеров справа лишняя камера

2023-02-19 07:57 UTC, SAADf603 commented
Потекли рантаймы по трубам..
Runtime in code/ATMOSPHERICS/datum_pipeline.dm,60: /obj/machinery/atmospherics/pipe/simple/hidden/cyan [[0x2021abb]] added to a pipenet while still having one (/datum/pipeline) (pipes leading to the same spot stacking in one turf). Nearby: 179, 201, 10.

2023-02-19 08:09 UTC, Den109G commented
Я не уверен, что файл сохранён в нужном формате, но да ладно.

2023-02-19 08:25 UTC, SAADf603 requested changes
006:016 две помпы на одном тайле, 011:005 грибок на АЦП, 017:010 удалить огнетушитель, 016:011 оба выключателя на два тайла выше.
В дормах сделать перестановку, изменить нетворк телевизора на list("USSP_LAB").
Настроить у ВСЕХ АЦП dir.
![Безымянный](https://user-images.githubusercontent.com/110329212/219936909-ad17b553-104d-4cbf-bc5c-02cd63f70986.png)

2023-02-24 10:16 UTC, SAADf603 approved these changes
@Dimach одобрено. 
Есть пара совсем незначительных моментов, которые следовало бы исправить, если бы это была не заброшенная СССП лаборатория, так что не баг, а фича

2023-02-24 15:59 UTC, merged