(feat)Cloth code rework
ss220-space/Paradise pull request #2080
Opened 2023-02-20 20:15 UTC by EnderMen3132

## Описание

реворк кода для изменения пути спрайтов и добавления в него строчки кода с временем одевания и раздевания вещи (по умолчанию стоит на 0 тобишь неактивна и не затрагивает обываетелей) 

## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/1030133547509485708
## Демонстрация изменений

2023-02-20 21:44 UTC, Furukia approved these changes
Глянула код и указала на проблемы. Разбирали их в дискорде на полигоне.

2023-02-21 23:59 UTC, TrashDoxx commented
Аа, ээ, а зачем?

2023-02-22 06:53 UTC, Den109G commented
Быстро пробежался по изменениям.
Пропали спрайты на голове у:
```
/obj/item/trash/fried_vox
/obj/item/nullrod/fedora
/obj/item/storage/bag/plasticbag
/obj/item/reagent_containers/food/snacks/grown/poppy
/obj/item/reagent_containers/food/snacks/grown/moonlight
/obj/item/reagent_containers/food/snacks/grown/harebell
/obj/item/grown/sunflower
Все /obj/item/holder (то есть у мышей, дронов и т.д. на голове пропали иконки)
/obj/item/reagent_containers/glass/bucket
```

Пропали спрайты на спине у:
```
Всех разновидностях нуллрода, что крепятся на спину
/obj/item/melee/energy_katana
/obj/item/toddler
/obj/item/radio/electropack
/obj/item/chrono_eraser
/obj/item/defibrillator
/obj/item/shield/riot
/obj/item/melee/baton/cattleprod
/obj/item/twohanded/fireaxe
Любой баллон
/obj/item/watertank
/obj/item/twohanded/bostaff
/obj/item/twohanded/kinetic_crusher
/obj/item/hierophant_club
/obj/item/lava_staff
/obj/item/shared_storage
/obj/item/gun/energy/lasercannon
/obj/item/gun/energy/pulse
/obj/item/gun/energy/ionrifle
/obj/item/gun/energy/temperature
/obj/item/gun/energy/sniperrifle
Любой /obj/item/gun/magic/staff
/obj/item/gun/projectile/revolver/doublebarrel
/obj/item/gun/projectile/shotgun
/obj/item/gun/projectile/automatic/sniper_rifle
```

И в придачу оно фигово работает с теми предметами, что можно повесить на много слотов (к примеру если починишь энерго катану, то заметишь, что повесив на пояс она будет отображаться на спине, т.к. только один файл использует для отображения)

2023-02-22 06:58 UTC, Den109G commented
Хорошие намерения, да. Но не понятно зачем.
Да и ещё зачем-то симпл мобам дали изменения, хотя они никак не используются для спрайтов на карбоне.

2023-02-22 07:08 UTC, PhantornRU requested changes

2023-02-22 07:08 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	onmob_icon = 'icons/mob/head.dmi'
Не пихай это в моба. Пихай это в holder.dm. Это предмет который и является удержанием моба. Не издевайся над мышками.

2023-02-22 12:25 UTC, EnderMen3132 commented
щас буду делать исправления

2023-02-22 16:21 UTC, Den109G commented on code/game/objects/items.dm
> +	onmob_icon = 'icons/mob/back.dmi'
А почему не сразу `var/onmob_icon = 'icons/mob/back.dmi'`?

2023-02-22 16:21 UTC, EnderMen3132 commented on code/game/objects/items.dm
> +	onmob_icon = 'icons/mob/back.dmi'
решил так сделать

2023-02-22 16:22 UTC, EnderMen3132 commented on code/game/objects/items.dm
> +	onmob_icon = 'icons/mob/back.dmi'
пытался исправить проблему с тем что предметы на 2 слота не меняют спрайт но чёт задушился

2023-02-26 18:34 UTC, closed without merging