Blueshield's monitor
ss220-space/Paradise pull request #2083
Opened 2023-02-21 09:59 UTC by Shakalchik

## Описание
Добавляет Блющилду свой крю монитор. Он находится в его шкафу, заместо обычного монитора. Этот предмет нельзя создать, не исчезает от ухода в крио.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1077288858930126969 (Авоут пройден, ссылка сразу на него)

## Демонстрация изменений
![image](https://user-images.githubusercontent.com/66063344/220311466-5ee8390b-844f-44da-b24a-9f8e8b90a475.png)
![image](https://user-images.githubusercontent.com/66063344/220311520-169c403b-59dc-4481-993a-45d84096e756.png)

2023-02-22 00:03 UTC, TrashDoxx requested changes
У тебя класс / объект наследуется, зачем ты дублируешь переменные...

Нужно переделать.

2023-02-22 00:12 UTC, TrashDoxx commented
А, тут и проки по сути...

2023-02-22 00:19 UTC, TrashDoxx commented
Ладно, я разобрался, что ты делаешь. Что могло быть проще, если бы я видел описание PR'а. Ревью всё ещё в силе. JS трогать не стану, потому не ало в нём совершенно. Но подход с фактически полным дублированием кода выглядит странновато даже без малейшего понимания языка.

2023-02-22 00:21 UTC, TrashDoxx commented
Хотя тут корректно говорить не о языке, а о реализации TGUI, конечно.

2023-02-22 00:25 UTC, TrashDoxx reviewed
Ещё бы отрефакторить код по-минимуму. Ну хотя бы Initialize вместо New. Но я уж не смею просить о такой услуге.

2023-02-24 10:22 UTC, SAADf603 requested changes
У вас Суд сломался. Возьмите актуальную карту, замените на неё ту, что в ветке ПРа, и снова добавьте.

2023-02-24 14:28 UTC, closed without merging