FEAT: Updated fax panel
ss220-space/Paradise pull request #2087
Opened 2023-02-21 23:35 UTC by UEDCommander

Переделанные факсы, выдаваемые факс-панелью, под приведенный на скриншоте ниже формат. Основными преимуществами данной формы являются:
- Больше похоже на формы, используемые при написании факса от ЦК вручную;
- Имеется указание времени отправки;
- Имеется подпись, состоящая из случайных имени и фамилии, генерирующихся один раз на весь раунд (таким образом, несколько отправленных факсов в одном раунде будут иметь одну и ту же подпись).

![image](https://user-images.githubusercontent.com/52104104/220482852-94d3ef3c-21a5-44ad-a63e-5b91ee6c2434.png)

Авоут я вам не покажу, у вас документов нет 🐀

2023-02-22 00:22 UTC, TrashDoxx commented
Жесть намержил, сейчас гляну.

2023-02-22 00:28 UTC, TrashDoxx requested changes
`New ---> Initialize`

2023-02-22 14:30 UTC, MataVsn commented
19 коммитов ради двух изменённых файлов. Oh shiet

2023-02-22 16:24 UTC, Den109G commented
Вижу что 13 строк прибавили, 4 отняли.
Как раз и получается. Каждый коммит на одну строчку.
+2 коммита на ребейз.

2023-02-22 17:39 UTC, UEDCommander commented
> 19 коммитов ради двух изменённых файлов. Oh shiet

Скажем так - мои бранчи имеют некоторое количество хаоса

2023-02-23 20:57 UTC, TrashDoxx requested changes

2023-02-23 20:57 UTC, TrashDoxx commented on code/modules/paperwork/paper.dm
> +/obj/item/paper/central_command/Initialize()
```suggestion
/obj/item/paper/central_command/Initialize(mapload)
```

2023-02-24 15:46 UTC, Dimach commented on code/_globalvars/misc.dm
> +GLOBAL_VAR(genname) //Имя, которое будет проставляться на бумаге по стандарту. Используется для факс-панели.
```suggestion
GLOBAL_VAR(genname) //Nanotrasen officer name for fax send via fax panel, randoms every round
```

2023-02-24 15:52 UTC, merged