Монитор для БШ
ss220-space/Paradise pull request #2100
Opened 2023-02-24 14:54 UTC by Shakalchik

## Описание
Убирает из шкафа БШ обычный монитор, добавляет новый монитор, с собственным спрайтом. Он показывает только глав в отдельной вкладке. Прежняя вкладка со всеми остается. На карте глав отображает квадратом, вместо круга.
(Ревью уже было, я пересоздал ПР, ибо там были проблемы)

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1077288858930126969 (Авоут пройден)

## Демонстрация изменений
![image](https://user-images.githubusercontent.com/66063344/221209358-8e03fcb0-3698-437b-9be5-fc6d019025b7.png)
![image](https://user-images.githubusercontent.com/66063344/221209364-56510a10-5936-47b7-9cdd-7f3e5741af3b.png)

2023-02-24 18:47 UTC, TrashDoxx commented
А как насчёт такой хайповой идеи?
![image](https://user-images.githubusercontent.com/67621641/221265765-e58405a5-919d-44cb-b30b-65e0c8f2dff4.png)

2023-02-24 18:50 UTC, TrashDoxx requested changes

2023-02-24 18:50 UTC, TrashDoxx commented on code/game/objects/items/devices/sensor_device.dm
> +	..()
```suggestion
/obj/item/sensor_device/command/Initialize(mapload)
	. = ..()
```

2023-02-24 19:04 UTC, Shakalchik commented
> А как насчёт такой хайповой идеи? ![image](https://user-images.githubusercontent.com/67621641/221265765-e58405a5-919d-44cb-b30b-65e0c8f2dff4.png)

Я так понял, ты про это дублирование?

2023-02-24 19:31 UTC, TrashDoxx commented
> Я так понял, ты про это дублирование?

Ага. Но ты не всё сделал.

2023-02-24 19:38 UTC, Shakalchik commented
> > Я так понял, ты про это дублирование?
> 
> Ага. Но ты не всё сделал.

А где еще... Я просто совсем скилл ишуе как ты понял

2023-02-25 20:27 UTC, SAADf603 approved these changes
Всё, что не касается js в порядке. JS надо проверить дополнительно.

2023-03-02 12:59 UTC, lebedev commented on code/modules/tgui/modules/crew_monitor.dm
> +	return data
А датумы можно наследовать? Типа вместо `/datum/ui_module/c_crew_monitor` сделать `/datum/ui_module/crew_monitor/command`, чтоб он `ui_data` переиспользовал

2023-03-02 15:36 UTC, Shakalchik commented on code/modules/tgui/modules/crew_monitor.dm
> +	return data
Летят ошибки, видимо нельзя.

2023-03-02 17:00 UTC, lebedev commented on tgui/packages/tgui/interfaces/CrewMonitor.js
> +const CrewMonitorTable = ({ crewData, isCommand, context }) => {
`isCommand` не используется. Грохай.

2023-03-02 17:04 UTC, lebedev approved these changes
По JS-коду замечаний нет

2023-03-03 07:23 UTC, Rerik007 commented on code/modules/tgui/modules/crew_monitor.dm
> +	ui = SStgui.try_update_ui(user, src, ui_key, ui, force_open)
Да, тут можно убрать лишние датумы c_crew, просто введя в базовый /crew_monitor какую нибудь var/этомониторБЩ, и проверяя его в обычной уи дате.
Ну и соответственно нужно также задавать смену этого параметра у монитора БЩ. При инициализации  в sensor_device.dm например. И убрав все упоминания c_crew_monitor.
Что-то типо такого: 
![Снимок экрана 2023-03-03 101230](https://user-images.githubusercontent.com/120549107/222657159-1c835df2-896c-4c4b-9576-b52ff9cb8e4e.png)
Это позволило бы убрать дублирование ui_interact и ui_data  в этом файле.

2023-03-04 12:56 UTC, Shakalchik commented on code/modules/tgui/modules/crew_monitor.dm
> +	ui = SStgui.try_update_ui(user, src, ui_key, ui, force_open)
Сделано с твоей помощью, спасибо за потраченое время

2023-03-04 12:58 UTC, Rerik007 commented on code/game/objects/items/devices/sensor_device.dm
> +	crew_monitor.ui_interact(user, ui_key, ui, force_open)
```suggestion
	crew_monitor.with_command = TRUE
```
Сокращаем ещё. 🙃  ui_interact такой же как в обычном, его убираем. crew_monitor создаётся в обычном.

2023-03-04 19:48 UTC, closed without merging