Feat: Space Battle rework
ss220-space/Paradise pull request #2200
Opened 2023-03-04 19:23 UTC by ItsMeJaba

## Описание
Изначальный план был в ребалансе объема лута, что выносят из данного гейта со способностью снарядить всю свою братию культистов/революционеров и т.п. Но внешний вид и наполнение данного гейта меня совсем не устроил, поэтому я выкатываю данный реворк.

## Ссылка на предложение/Причина создания ПР
На данный момент в драфте для удобства работы, проверки и тестирования. По готовности пойдет по общей системе.

## Демонстрация изменений
# Было:
![2023 03 01-00 16 33](https://user-images.githubusercontent.com/91949115/222921905-60944059-a9a9-42ad-ab13-b2aaea83e7cb.png)
# Стало:
![2023 03 04-22 57 38](https://user-images.githubusercontent.com/91949115/222921914-225f4b0f-d7b8-445d-be6f-364c13a3e458.png)

## Что изменилось:

-  Ребаланс лута: добавлена рандомизация содержимого карманов и сумок некоторых трупов. Противники теперь не оставляют тело после себя, рассыпаясь в пыль и так же с некоторым шансом могут оставить соответствующие предметы:

   * Корабельные офицеры (СБ) - вооружение: 70% энфорсер+магазин, 20% ВТ+магазин, 10% дробовик+коробка бакшотов
   * Все синдикатовцы (Самое неприятное, что может попасть на станцию):
           2% - Сигареты синдиката, синдидонккпокет, ID-карта синдиката
    * Мобы в бладригах - 5% на выпадение хардсьюта
    * Дальние мобы - 1% C20r, 3% обойма C20r, 5% стечкин (патроны выпадают от 1 до 3 достаточно часто)
    * Ближние мобы - 1% есворд, 2% энергощит
    * Дроны синдиката - 100% выпадение одной платы с любой(кроме абдукторов) технологией уровня 1-4, синдикатовские технологии максимум 3

-  Добавлены маркеры-спавнеры (выглядят как мины с восклицательным знаком на рендере)
     Привязанные id маркеры спавнят на маркерах с изображением противника новых мобов, что добавляет немного больше динамики. На время тестирования маркеры вызывают у игрока над головой восклицательный знак как если бы он сидел в коробке и её открыли (отсылка на MGS), также по выходу из тестирования спрайты будут перенесены к другим спавнерам, что готовит Момо.

 - Ребаланс противников
   * Уровень здоровья снижен с 300-400 до адекватных 100 у всех синдикатовцев, кроме "босса" на мостике.
   * Т.к. шансы на выпадения серьезного лута и максимальная планка здоровья снизились, произошла компенсация количеством:
     Было:                                       Стало:                                    Может заспавниться:
     1 босс-командир                    1 босс-командир                  -
     23 ближника                           25 ближника                         +12
     18 дальников                          44 дальника                          +7
     8 ближников в бладригах      8 ближников в бладриге     +12
     21 дальник в бладриге           37 дальников в бладриге    +30
                                                      76 дронов                             +69

- Переработка основного крейсера
   * Изменение общего оснащение помещений
   * Добавлен единственный ценный риг - СБ
   * Добавлена возможность собрать под
   * Удалены все спавнеры лута уровня дигла по 50 брута
   * Все ПНВ заменены на мезоны, единственные ПНВ на корабле - шлемы, что дают меньше обзора, чем фонарик
   * Добавлены записки: предсмертная механика, офицера в туалете; распоряжения НТ на мостике; фрагмент бортового журнала.
   * Бортовые турели теперь зависят от питания
  
- Переработка всех трех кораблей синдиката
   * Левый(имеет точку появления): гарантированный бладриг, акселераторную пушку, ПНВ
   * Центральный: гарантированный бладриг, пару лазерных винтовок, гарантировнный есворд(грифски)
   * Правый: шкафомех, 7 мимиков(серые ящики) 

- Добавлен корабль-якорь у двигателя крейсера
  *  Гарантированный атмос голопроектор, приличные объемы плазмы

- Карго-корабль (у самого правого  края)
  * Abandoned crate
  * Кларк + бур, гидравлическая клешня

- Амогусы
  * Нижний удален
  * Верхний стал захоронением hive-ботов, большая часть находится по периметру внутри камня.

 - Метеориты и другие булдыги на карте
  * Значительно снижено количество камня с повышенным шансом руды
  * Постарался снизить шансы спавна пещер с грибами за счет установки других типов камня
  
- Справа снизу добавлена отсылка - медведь Винни

2023-03-05 08:00 UTC, Den109G commented
СМище.... Надеюсь оно не бахает сразу.

2023-03-13 14:35 UTC, Herobrine998 commented
Автор же понимает, что если реворк не пройдет голосовач, то он потратит время в пустую?

2023-04-27 10:53 UTC, Legendaxe requested changes
Вызов родительского Initialize необходим для того что бы твои переменные с потенциальным лутом были обработаны и заполнены перед тем как ты пытаешься получить из них данные.

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	/var/SynRange //Лут с дальников
```suggestion
	var/SynRange //Лут с дальников
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	/var/SynMelee //Лут с милишников
```suggestion
	var/SynMelee //Лут с милишников
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	/var/SynSpace //Выпадение бладрига
```suggestion
	var/SynSpace //Выпадение бладрига
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	/var/synmobdrop //Обычный лут, дропается со всех
```suggestion
	var/synmobdrop //Обычный лут, дропается со всех
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	loot = list(/obj/effect/decal/cleanable/ash, synmobdrop, SynMelee)
```suggestion
	. = ..()
	loot = list(/obj/effect/decal/cleanable/ash, synmobdrop, SynMelee)
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	return ..()
```suggestion
	return .
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	loot = list(/obj/effect/decal/cleanable/ash, synmobdrop, SynMelee, SynSpace)
```suggestion
	. = ..()
	loot = list(/obj/effect/decal/cleanable/ash, synmobdrop, SynMelee, SynSpace)
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	return ..()
```suggestion
	return .
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	loot = list(/obj/effect/decal/cleanable/ash, synmobdrop, SynRange)
```suggestion
	. = ..()
	loot = list(/obj/effect/decal/cleanable/ash, synmobdrop, SynRange)
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	return ..()
```suggestion
	return .
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	loot = list(/obj/effect/decal/cleanable/ash, synmobdrop, SynRange, SynSpace)
```suggestion
	. = ..()
	loot = list(/obj/effect/decal/cleanable/ash, synmobdrop, SynRange, SynSpace)
```

2023-04-27 10:53 UTC, Legendaxe commented on code/modules/awaymissions/mission_code/spacebattle.dm
> +	return ..()
```suggestion
	return .
```

2023-05-01 08:38 UTC, merged