Кислота
ss220-space/Paradise pull request #2303
Opened 2023-03-14 02:04 UTC by OrdinaryBarbarian

Переработка фторсерной кислоты и крапивы согласно пройденому авоуту: https://discord.com/channels/617003227182792704/755125334097133628/1061712987137769512

2023-03-14 07:21 UTC, VasilevAY commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +				H.adjustFireLoss(clamp(volume * 2, 8, 80));
Если не секрет, то откуда берутся эти цифры и что они означают? Хоть какой-то бы комментарий

2023-03-14 07:24 UTC, VasilevAY commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +					E.receive_damage((clamp(volume * 2, 8, 80)) * damage_coef / H.bodyparts.len)
и тут то же самое. Откуда цифры, как они считаются? Я понимаю, что это коэффициенты, но почему так?

2023-03-14 12:17 UTC, OrdinaryBarbarian commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +				H.adjustFireLoss(clamp(volume * 2, 8, 80));
Это уже существующий ПР, который не был залит, а его автор не имел желания сам его перезаливать. Мне как новичку тыкнули на это и сказали "вот работа - делай".

2023-03-15 11:57 UTC, larentoun requested changes

2023-03-15 11:57 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +					E.receive_damage((clamp(volume * 2, 8, 80)) * damage_coef / H.bodyparts.len)
Я правильно понимаю, что тебе фторсорка наносит брут урон, а не берн?

2023-03-15 11:57 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +			if(volume >= 0)
Даже самая милиписичечная 0.4 реагента заставляют кричать и получать урон? Ох, жди абузов, друг

2023-03-15 11:57 UTC, larentoun commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +				H.adjustFireLoss(clamp(volume * 2, 8, 80));
Ты сделал патч из фторсорки ваншотом, держу в курсе.

2023-03-16 10:53 UTC, VasilevAY commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +				H.adjustFireLoss(clamp(volume * 2, 8, 80));
> Это уже существующий ПР, который не был залит, а его автор не имел желания сам его перезаливать. Мне как новичку тыкнули на это и сказали "вот работа - делай".

имеет смысл разобраться

2023-05-10 11:54 UTC, ErdGinalD commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +				H.adjustFireLoss(clamp(volume * 2, 8, 80));
патч серной сильнее, не пофиг ли? патчи уже давно пофиксили

2023-05-10 12:11 UTC, ErdGinalD commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +			if(volume >= 0)
серная уже есть. Она сильнее.

2023-05-10 12:17 UTC, ErdGinalD commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +					E.receive_damage((clamp(volume * 2, 8, 80)) * damage_coef / H.bodyparts.len)
она наносит ожоги.

2024-02-12 20:58 UTC, closed without merging