Map: Cere-station
ss220-space/Paradise pull request #2308
Opened 2023-03-14 16:24 UTC by BeebBeebBoob

## Описание

Новая станция, которая не будет в ротации.
Оригинал: https://github.com/ParadiseSS13/Paradise/pull/19951
Автор: [S34NW](https://github.com/S34NW)
Редактор: [BeebBeebBoob](https://github.com/BeebBeebBoob)

- 7 Астероидов(8 считая спутник) на каждым из которых свой отдел. 
- Разделённая система питания на под-сети. (СМ -> Смесы -> Станция -> Смес  -> Астероид)
- Новый вид астероидных камней. Cold asteroid rock, как обычный камень не сломать можно только с помощью алмазных инструментов(проставлены по периметры, дабы остановить массовые разгермы)
- Мусорные трубы вне станции, перелетают прямо в космосе.
- Квантум пады в 4 уголках карты для быстрого перемещения.

## Ссылка на предложение/Причина создания ПР

Пока что проходит, поэтому драфт.

## Демонстрация изменений

[Сама карта в оригинальном размере](https://media.discordapp.net/attachments/1084571675829469274/1085234656061956116/cerestation-1.png)

Мини-версия карты
![Farragus_nanomap_z1](https://user-images.githubusercontent.com/32985153/225069325-2e8dc171-cb0b-4996-9a88-78936d81faba.png)

2023-03-14 17:28 UTC, dj-34 commented
линтер

2023-03-14 23:00 UTC, dj-34 commented
Карта же типа, готова?... Почему трубы не проведены?
![image](https://user-images.githubusercontent.com/20109643/225160658-e0d6a76b-3b10-4819-91b8-ce9ff4aa3df5.png)

2023-03-15 21:00 UTC, BeebBeebBoob commented
Не отображаются

2023-03-15 21:00 UTC, BeebBeebBoob commented
Ты думаешь я настолько сыро выдвину такую карту? Нееееее

2023-03-16 09:06 UTC, SAADf603 commented on code/modules/map_fluff/maps.dm
> +	var/admin_only = FALSE
почему?

2023-03-16 10:42 UTC, BeebBeebBoob commented on code/modules/map_fluff/maps.dm
> +	var/admin_only = FALSE
Требование в предложке

2023-03-16 10:43 UTC, BeebBeebBoob commented on code/modules/map_fluff/maps.dm
> +	var/admin_only = FALSE
А ты про переменную? Хардкод плохо.

2023-03-16 11:19 UTC, SAADf603 requested changes
Крупные недочёты обязательны к устранению, мелкие по нахождению. 

Крупные:  Машинерия на породе, знаки в решётках, атмос трубы в стенах выходов в космос, беда с трубами в серверах РнД и токсинах, удалить nearstation, все доступы в ```req_access```
Мелкие: Автомат в шаттле? Трубы под консолями? КМ спавнится с главами, а НТР нет, наложение машинерии на знаки, лампы над спавнерами решёток, мешанина из стен укрелённые/обычные в техах
Беды с зонами:
![Безымянный](https://user-images.githubusercontent.com/110329212/225592345-a019fde6-91fb-4297-96a4-a0efaff4e70d.png)
![Безымянный](https://user-images.githubusercontent.com/110329212/225597557-91c8d9cc-5804-41c9-b5ef-c3efa649bd75.png)
![Безымянный](https://user-images.githubusercontent.com/110329212/225597824-225960b9-3486-4631-8ce7-36e0feed9427.png)

2023-03-16 13:28 UTC, BeebBeebBoob commented
Фиксы учтены кроме последнего. Правый красный кружок. Там конечно должно быть залито зоной коридора, но там камни, а не стены, что делает его зоной unexplored. Лучше так.

2023-03-16 15:34 UTC, ROPY28 commented
Камера некорректно поставлена, название карты в углу спутано
![камера отображается некорректно, название кибериада почему то](https://user-images.githubusercontent.com/118102885/225668507-d460a858-8311-44e9-b88f-bcd9c4757a06.png)

2023-03-18 11:13 UTC, PhantornRU commented
Просьба как замержишь - меня пингануть. Я гляну по животным и целям вора и выкачу обнову сверху.
Например сейчас отсутствуют уникальные статуи. Всякие фигурки. Потом просто их раскидаю по тем же местам что и на Дельте.

2023-03-18 13:06 UTC, SAADf603 requested changes
![Безымянный](https://user-images.githubusercontent.com/110329212/226104378-ffa95292-f047-49e5-a0da-5dc581340b95.png)
![1](https://user-images.githubusercontent.com/110329212/226108014-1e0a54e8-fe83-4854-b8c9-2ce9cd1497d1.png)
![2](https://user-images.githubusercontent.com/110329212/226108019-ce003508-c71b-4c87-bbed-cc27da3d5fdd.png)
![3](https://user-images.githubusercontent.com/110329212/226108022-bdffe3a0-b122-4504-87d0-ad5eef8747ee.png)
![4](https://user-images.githubusercontent.com/110329212/226108024-6d15a0bd-d149-4745-83cf-1610420798cd.png)
![5](https://user-images.githubusercontent.com/110329212/226108028-78d979b6-2c0c-4985-b305-afdb0b2da3ab.png)
![6](https://user-images.githubusercontent.com/110329212/226108032-42946e12-0d78-483c-9398-9607c7085f45.png)
![7](https://user-images.githubusercontent.com/110329212/226108039-eb580f04-b9e4-4d27-937c-f8351f9338ea.png)
![8](https://user-images.githubusercontent.com/110329212/226108041-8c56d625-782b-4563-ac2c-6d4be710b9cb.png)
![Безымянный](https://user-images.githubusercontent.com/110329212/226108044-491f15fa-0270-49d8-ac97-dbefe55af5f2.png)
У ГСБ нет сейфа с уникой, у глав нет никаких листков с паролями. В рендер включены лендмарки, которые были исключены из списка скрытия что бы что?

2023-03-18 15:25 UTC, BeebBeebBoob commented
> У ГСБ нет сейфа с уникой, у глав нет никаких листков с паролями. В рендер включены лендмарки, которые были исключены из списка скрытия что бы что?
Чтобы они не показывались для игроков которые смотрят наши карты через вебсайт AA07

2023-03-18 15:44 UTC, SAADf603 commented
> Чтобы они не показывались для игроков которые смотрят наши карты через вебсайт AA07

Ну не просто же так я сделала их красивыми и симпатичными, и СПЕЦИАЛЬНО убрала из этого списка.

2023-03-18 16:01 UTC, BeebBeebBoob commented
> > Чтобы они не показывались для игроков которые смотрят наши карты через вебсайт AA07
> 
> Ну не просто же так я сделала их красивыми и симпатичными, и СПЕЦИАЛЬНО убрала из этого списка.

Такие же настройки и у ТГ. И у оффов. И у других билдов.

2023-03-21 16:39 UTC, BeebBeebBoob commented
Bump

2023-03-22 10:43 UTC, BeebBeebBoob commented
Bump2

2023-03-22 10:54 UTC, Den109G approved these changes
Counter-Bumb

2023-03-22 15:39 UTC, Dimach commented
Не используй в карте req_access_txt и req_one_access_txt. Эти штуки плохо работают с новым мапридером и идут на удаление. Намени их на req_access (list) и eq_one_access (list)

2023-03-22 15:54 UTC, BeebBeebBoob commented
Я от них как раз таки избавился.

2023-03-22 15:58 UTC, Dimach commented
![image](https://user-images.githubusercontent.com/1918858/226964457-57450ed3-625a-41ae-9ddb-d665020b48c9.png)

2023-03-22 16:01 UTC, BeebBeebBoob commented
Признаюсь. Не все. Но большую часть! :)

2023-03-22 16:09 UTC, merged

2023-03-25 09:00 UTC, ROPY28 commented
![NSS Cyberiad 2023-03-25 115946](https://user-images.githubusercontent.com/118102885/227707751-741224f7-2213-4901-bc6c-11b49c5f7ef1.png)
в верхних дормах на входе  нету стенки