Fix: TTS: Возврат локализации речи слаймов и общения с ними
ss220-space/Paradise pull request #2312
Opened 2023-03-14 21:53 UTC by Ohar

## Описание
— Переводит фразы слаймов на русский язык
— Переводит речевые глаголы слаймов на русский язык
— Позволяет слаймам понимать команды на русском языке

## Ссылка на предложение/Причина создания ПР
Слаймы говорят и озвучиваются, значит нужна локализация, ибо TTS

## Демонстрация изменений
Возврат старой локализации, [подробно описанной в прошлом году](https://github.com/ss220-space/Paradise/pull/933).

2023-03-15 11:41 UTC, larentoun requested changes
1. Как мне кажется, использование `моя` вместо `я` будет немного менее связно звучать, что хорошо для слизней. `Моя следовать за Рихтериара` против `Я следовать за Рихтериара`, но тут, наверное, вкусовщина

2. Надо, чтобы слизнь повторял команды, когда их задают. `Сидеть!`,  в ответ `Моя сидеть...`, не `Моя стоять...` и другие вариации. Это довольно просто сделать.

2023-03-15 11:41 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = "Да… Я [pick("идти…", "следовать…", "ползти…")] за [who]…"
`Я` с маленькой

2023-03-15 11:41 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = pick("Да…", "Вести…", "Идти…", "Следовать…", "Ползти…")
Тут скорее не `Вести`, а `Веди`; не `Следовать`, а `Следую`.
Тут подверждение того, что слизнь ползет за тобой

2023-03-15 11:41 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = "Нет… Я [pick("идти…", "следовать…", "ползти…")] за [Leader]…"
`Я` с маленькой

2023-03-15 11:41 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = pick("Нет…", "Я не идти")
Тут скорее не про движение, а про следование. `"Я не следовать"`?

Троеточие после действия?

2023-03-15 11:41 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +							to_say = "Да… я [pick("стоп", "стоять")]…"
Как тут "стоп" получилось?

2023-03-15 11:41 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +							to_say = "Нет… [pick("всё равно", "буду", "хочу")] идти…"
С заглавных букв

Не логичнее ли будет `"продолжать следовать"`, а то все остальное слишком хорошо звучит для слайма

2023-03-15 11:41 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = "Да… я [pick("ждать", "стоять")]…"
```suggestion
						to_say = "Да… Я [pick("ждать", "стоять")]…"
```

2023-03-15 11:41 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = "Нет… [pick("всё равно", "буду", "хочу")] [pick("идти", "ходить", "следовать")]…"
С заглавных букв

Не логичнее ли будет `"продолжать следовать"`, а то все остальное слишком хорошо звучит для слайма

2023-03-15 11:41 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +					to_say = pick("НАПАCТЬ", "УБИТЬ") + "!?!?"
Откуда тут "УБИТЬ" выскочило?

2023-03-16 11:02 UTC, VasilevAY commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = "Нет… Я [pick("идти…", "следовать…", "ползти…")] за [Leader]…"
> `Я` с маленькой

и там, и тут почему "Я" - с маленькой? Новое же предложение после троеточия

2023-03-16 13:53 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = "Нет… Я [pick("идти…", "следовать…", "ползти…")] за [Leader]…"
> > `Я` с маленькой
> 
> и там, и тут почему "Я" - с маленькой? Новое же предложение после троеточия

Сам вот пошел вспоминать правила языка, это продолжение прошлого предложения до троеточия, потому пишется с малой

2023-03-21 15:05 UTC, Ohar commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = "Да… Я [pick("идти…", "следовать…", "ползти…")] за [who]…"
@larentoun Нет, тут многоточие — знак конца предложения

> …в русском языке многоточие употребляют <…> Для обозначения пауз при неожиданном переходе от одной мысли к другой, между законченными предложениями. Например: _„Дубровский молчал… Вдруг он поднял голову, глаза его засверкали, он топнул ногою, оттолкнул секретаря… (А. С. Пушкин «Дубровский“)_. © [Википедия](https://ru.wikipedia.org/wiki/Многоточие#Русский_язык)»

2023-03-21 15:05 UTC, Ohar commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = "Нет… Я [pick("идти…", "следовать…", "ползти…")] за [Leader]…"
@larentoun Нет, тут многоточие — знак конца предложения

> …в русском языке многоточие употребляют <…> Для обозначения пауз при неожиданном переходе от одной мысли к другой, между законченными предложениями. Например: _„Дубровский молчал… Вдруг он поднял голову, глаза его засверкали, он топнул ногою, оттолкнул секретаря… (А. С. Пушкин «Дубровский“)_. © [Википедия](https://ru.wikipedia.org/wiki/Многоточие#Русский_язык)»

2023-03-21 15:06 UTC, Ohar commented on code/modules/mob/living/simple_animal/slime/life.dm
> +							to_say = "Нет… [pick("всё равно", "буду", "хочу")] идти…"
Вот как раз _«продолжать следовать»_ — крайне сложная словасеная конструкция для слайма, КМК

2023-03-21 15:08 UTC, Ohar commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = "Нет… [pick("всё равно", "буду", "хочу")] [pick("идти", "ходить", "следовать")]…"
Вот как раз _«продолжать следовать»_ — крайне сложная словесная конструкция для слайма, КМК

2023-03-21 15:09 UTC, Ohar commented on code/modules/mob/living/simple_animal/slime/life.dm
> +					to_say = pick("НАПАCТЬ", "УБИТЬ") + "!?!?"
А что ты предлагаешь? Оставить только «НАПАСТЬ»?
Эту команду можно дать только указав целью моба, поэтому «УБИТЬ» вполне уместно, КМК.

2023-03-21 15:31 UTC, Ohar commented
@larentoun Поменял «Я» → «Моя», и правда очень хорошая идея.

Насчёт повтора команды: не могу придумать реализацию.

2023-03-21 16:25 UTC, larentoun commented
> @larentoun Поменял «Я» → «Моя», и правда очень хорошая идея.
> 
> Насчёт повтора команды: не могу придумать реализацию.

Можно немного застримлайнить код. Вместо кучи проверок `findtext`, вызывать одну функцию, которая будет принимать как раз-таки список нужных команд.

К примеру, ./proc/listen_command(var/list/commands), она возвращает значение, которое нашло, либо `FALSE`.

2023-03-21 16:30 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +			if(findtext(phrase, "hello") || findtext(phrase, "hi") || findtext_char(phrase, "привет") || findtext_char(phrase, "здравствуй"))
Сразу на примере можно тут.
```suggestion
            var/list/commands = list("hello", "hi", "привет", "здравствуй")
            to_say = listen_command(phrase, commands))
			if(to_say)
			    (делаем код)
```
И так далее. Проверяем новый `to_say`, вместо бесконечных `else if`

2023-03-21 16:31 UTC, larentoun commented on code/modules/mob/living/simple_animal/slime/life.dm
> +			if(findtext(phrase, "hello") || findtext(phrase, "hi") || findtext_char(phrase, "привет") || findtext_char(phrase, "здравствуй"))
Ну или любую другую подобную реализацию

2024-02-12 20:58 UTC, closed without merging