Риг бригмедику
ss220-space/Paradise pull request #2321
Opened 2023-03-15 21:27 UTC by captainnelly

## Описание
Добавляет новый риг бригмедика в билд, а также этот риг в кабинет бригмеда(Только на дельте)

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1085213263429652480

2023-03-16 05:41 UTC, SAADf603 requested changes
Не пойдёт. 
Во-первых должен быть ограждён от обычных СБух по типу старого расположения ригов в медбее. Во-вторых ты поставил риг в зону, где происходят операции, а не в кабинет. В-третьих ты закрыл доступ к АЦП. В-четвёртых ты сделал это столиком, который должен стоять в правой части лазарета. В-пятых зачем бригмеду магбуты СБ? В-шестых капитаннэле :skull: 
Ожидаю увидеть это:
![Безымянный](https://user-images.githubusercontent.com/110329212/225525345-6c972ce1-caba-4528-bdbd-7c33cd448d77.png)

2023-03-16 19:44 UTC, captainnelly commented
> Не пойдёт. Во-первых должен быть ограждён от обычных СБух по типу старого расположения ригов в медбее. Во-вторых ты поставил риг в зону, где происходят операции, а не в кабинет. В-третьих ты закрыл доступ к АЦП. В-четвёртых ты сделал это столиком, который должен стоять в правой части лазарета. В-пятых зачем бригмеду магбуты СБ? В-шестых капитаннэле 💀 Ожидаю увидеть это: ![Безымянный](https://user-images.githubusercontent.com/110329212/225525345-6c972ce1-caba-4528-bdbd-7c33cd448d77.png)

Столы не закрывают доступ к АПЦ ведь, в рнд на стойке такое

2023-03-17 06:46 UTC, ItsMeJaba commented
> Не пойдёт. 
> Во-первых должен быть ограждён от обычных СБух по типу старого расположения ригов в медбее. Во-вторых ты поставил риг в зону, где происходят операции, а не в кабинет. В-третьих ты закрыл доступ к АЦП. В-четвёртых ты сделал это столиком, который должен стоять в правой части лазарета. В-пятых зачем бригмеду магбуты СБ? В-шестых капитаннэле :skull: 
> Ожидаю увидеть это:
> ![Безымянный](https://user-images.githubusercontent.com/110329212/225525345-6c972ce1-caba-4528-bdbd-7c33cd448d77.png)
> 

А нахрена ССУ, на котором можно выставить доступ закрывать еще одним аквариумом?

2023-03-20 16:51 UTC, captainnelly commented
Исправил

2023-03-20 20:55 UTC, SAADf603 approved these changes
Everything is good here :cemkaBoi:

2023-03-29 19:55 UTC, closed without merging