FEAT: Silent emotes for mime
ss220-space/Paradise pull request #2338
Opened 2023-03-17 05:39 UTC by LiquidPotroh

## Описание
Заменяет звуковые расовые эмоуты на беззвучные аналоги или полностью запрещает мимам их воспроизводить, если они являются полностью звуковыми. (Придумаете, что долен делать мим вместо "издаёт раздраженный жужжащий звук" - милости прошу)

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1085853377751154798

2023-03-17 12:11 UTC, lebedev requested changes
Было бы неплохо в соответствующих местах добавить запятых.
`делает вид что` -> `делает вид, что`

2023-03-17 17:57 UTC, LiquidPotroh commented
@lebedev готово

2023-03-17 18:00 UTC, lebedev approved these changes

2023-03-21 02:35 UTC, LiquidPotroh commented
@Dimach и тут

2023-03-21 07:11 UTC, merged