Feat: Clumsy table climbs
ss220-space/Paradise pull request #2353
Opened 2023-03-20 05:49 UTC by Vladisvell

## Описание

Обновление, добавляющее опрокидывание предметов со стола в попытках на него залезть, потанцевать или кинуть на него кого-либо.

## Ссылка на предложение/Причина создания ПР

(тут должна быть ссылка на авоут, ждем-с)

## Демонстрация изменений

![rolling stones2](https://user-images.githubusercontent.com/73733747/226257368-7fd93fc8-1855-4167-8714-0f5e9e327ccb.gif)
![dance dance](https://user-images.githubusercontent.com/73733747/226257252-1022879e-0fca-44b9-9a0e-eefed52f3d57.gif)
![Bowling_2](https://user-images.githubusercontent.com/73733747/226257186-aacf182c-9ce3-4aa2-a397-790d7ff6a426.gif)

2023-03-20 07:11 UTC, PhantornRU commented on code/game/objects/structures.dm
> +	slopchance = clamp(slopchance,0,100)
```suggestion
	slopchance = clamp(slopchance, 0, 100)
```

2023-03-20 07:15 UTC, PhantornRU commented on code/game/objects/structures.dm
> +			if(MOB_SIZE_TINY) slopchance = 10
Может лучше модификаторы сделать?
Сначала смотрим размер. От него определяем текущий slopchance. 10, 20, 80, 100.
После чего "ishuman(user)" с проверками на ДНК и Мимность, где будет +20 или -30 поверх этого шанса.
Ну и далее если оно "вдруг" перейдет границы, как я и говорил, кламп его уравняет.

2023-03-20 07:20 UTC, PhantornRU commented on code/game/objects/structures.dm
> +				break
Не согласен немного с таким решением, но допустим.

Твоим решением выходит что он выбирает 15 предметов и после чего шансы на их использование. Из-за чего итого предметов откинутых может быть всего 5 штук, когда стол завален 100 штук предметов.

Я бы рекомендовал сделать счетчик, который будет проверять шанс сразу в этом проке, и если он прошел, то добавлять его в список. И когда в списке их будет 15 штук - прерывать его. Тогда не смотря на 100 штук предметов, у нас будет повышенный шанс отбросить сразу много предметов в хламе, а не 1 случайный, и при этом сохранится оптимизация.

И уже после ко всем атомам применять откидывания.

Кароче. Вынеси `if(prob(slopchance))` из 123-й строки в эту выборку в ~117 строку.

2023-03-20 07:21 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +			for(var/obj/structure/table in range(0, target))
а почему не locate() для обнаружения стола на тюрфе под целью? Я ж скидывал пример

2023-03-20 07:22 UTC, PhantornRU commented on code/modules/mob/living/carbon/carbon.dm
> +				var/mob/living/carbon/victim = thrown_thing
У нас метают не только карбонов, но и животных.
Странно будет если брошенная свинья аккуратно встанет на стол.

2023-03-20 07:22 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/emote.dm
> +				for(var/obj/structure/table in range(0))
locate?

2023-03-20 07:23 UTC, PhantornRU commented on code/game/objects/structures.dm
> +
```suggestion
```
лишние пустые строки

2023-03-20 07:24 UTC, PhantornRU requested changes
Мне нравится, но нужно поправить некоторые моменты.

2023-03-20 07:25 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/emote.dm
> +				for(var/obj/structure/table in range(0))
и кстати. У тебя точно выделяется table? Ибо ты задаешь что это переменная var, но не задаешь как эта переменная используется. Вот поэтому я и говорил тебе про locate.
А то так получается что ты работаешь ВООБЩЕ СО ВСЕМИ СТРУКТУРАМИ.
Т.е. я думаю если ты будешь находиться на какой-нибудь статуе клоуна, то при танцах тоже всё разметаешь в сторону.

2023-03-20 08:00 UTC, Vladisvell commented on code/game/objects/structures.dm
> +	slopchance = clamp(slopchance,0,100)
сделано

2023-03-20 08:00 UTC, Vladisvell commented on code/game/objects/structures.dm
> +			if(MOB_SIZE_TINY) slopchance = 10
Изменено в следующем коммите

2023-03-20 08:00 UTC, Vladisvell commented on code/game/objects/structures.dm
> +				break
Сделано

2023-03-20 08:01 UTC, Vladisvell commented on code/modules/mob/living/carbon/carbon.dm
> +			for(var/obj/structure/table in range(0, target))
Сделано

2023-03-20 08:01 UTC, Vladisvell commented on code/modules/mob/living/carbon/carbon.dm
> +				var/mob/living/carbon/victim = thrown_thing
Поменял на isliving

2023-03-20 08:01 UTC, Vladisvell commented on code/modules/mob/living/carbon/human/emote.dm
> +				for(var/obj/structure/table in range(0))
Сделано

2023-03-20 08:01 UTC, Vladisvell commented on code/game/objects/structures.dm
> +
Сделано

2023-03-20 08:14 UTC, PhantornRU approved these changes
Ну сё, в продакшн

2023-03-20 08:14 UTC, PhantornRU commented on code/game/objects/structures.dm
> +	slopchance = clamp(slopchance, 0, 100)
Маленький шанс все же должен остаться. А то он просто так переберет 100 условных предметов и ни один из них не пройдет.
```suggestion
	slopchance = clamp(slopchance, 1, 100)
```

2023-03-20 08:14 UTC, PhantornRU commented on code/game/objects/structures.dm
> +		man = user
Выше лучше замени на данную конструкцию. А то лишняя строка на тратится буквально ни на что:
`		var/mob/living/carbon/human/man = user`

2023-03-20 08:23 UTC, Vladisvell commented on code/game/objects/structures.dm
> +	slopchance = clamp(slopchance, 0, 100)
йеп

2023-03-20 08:23 UTC, Vladisvell commented on code/game/objects/structures.dm
> +		man = user
Готово

2023-03-20 09:41 UTC, lebedev requested changes

2023-03-20 09:41 UTC, lebedev commented on code/game/objects/structures.dm
> +					break
Чтоб считалось реже.
```suggestion
					if(thrownatoms.len >= max_throws_count)
						break
```

2023-03-20 09:41 UTC, lebedev commented on code/game/objects/structures.dm
> +			if(!(AM == user || AM.anchored || isliving(AM)))
Так как юзер живой, можно упростить проверку. И раскрыть `!`
```suggestion
			if(!AM.anchored && !isliving(AM))
```

2023-03-20 09:41 UTC, lebedev commented on code/game/objects/structures.dm
> +			slopchance -= 30
Мимование - свойство разума, а ген неуклюжести - свойство куклы. Бездушный труп клоуна, кинутый на стол, должен все равно все раскидывать. Плюс `active_genes` есть у `/mob`, проверка на гуманность избыточна.
```suggestion
	if(/datum/dna/gene/disability/clumsy in user.active_genes)
		slopchance += 20
	if(user.mind?.miming)
		slopchance -= 30
```

2023-03-20 09:41 UTC, lebedev commented on code/modules/mob/living/carbon/carbon.dm
> +			var/obj/structure/table = locate(/obj/structure/table) in target.loc
Если локейтится такой же тип, который у переменной, то можно упростить
```suggestion
			var/obj/structure/table = locate() in target.loc
```

2023-03-20 10:05 UTC, Vladisvell commented on code/game/objects/structures.dm
> +			if(!(AM == user || AM.anchored || isliving(AM)))
Сделал

2023-03-20 10:05 UTC, Vladisvell commented on code/game/objects/structures.dm
> +			slopchance -= 30
Сделал

2023-03-20 10:05 UTC, Vladisvell commented on code/modules/mob/living/carbon/carbon.dm
> +			var/obj/structure/table = locate(/obj/structure/table) in target.loc
Сделано

2023-03-20 10:32 UTC, lebedev approved these changes

2023-03-21 04:48 UTC, PhantornRU commented
Авоуты пройдены, ждем залива. PepeChill

2023-03-21 07:16 UTC, merged