FEAT: Улучшение сервис борго
ss220-space/Paradise pull request #2390
Opened 2023-03-21 21:26 UTC by ErdGinalD

Что нового:
- Уменьшена цена на генерацию еды на 25%, так как это просто неадекватное количество энергии.
- Улучшен шейкер, теперь он может выливать нормальные порции напитков.
- Подтянуты до актуала все возможные виды генерации напитков в пуле шейкера, которые не обновлялись почти 5 лет. Все еще не генерирует яды и наркотики, а очень жаль.
- Добавлен ЕФТОПС для отыгрыша на Корпорате, а так же фотоаппарат для мгновенной генерации фото. Теперь вас могут запечатлеть на фото и выложить в паблике "Прошмандовки НТ".
- Так как я говнокодер, добавлен манипулятор, который может держать карты для оплаты на ЕФТОПСе, фотографии, бумагу и картридж подзарядки фотоаппарата. Это все разом покроет все нужды борга для нормальной работы с новыми предметами + наконец-то можно будет будить бухариков. РП!

- Раздатчики бухла и соды теперь актуализированы до пула бармена, который так же не был в обновлении свыше 4 лет. Теперь борг может налить шампанского, ура!
- Добавлена колода карт и призовой билетик в установщик всячины для повышения интеракций с борго. Спамить билетиками не получится, борго так же не может подобрать гриппером билетик, чтобы не было соблазна фармить на мотоцикл вместо своей прямой работы.
- Раздатчик всячины и еды поделен на два отдельных раздатчика: еды и всячины. Это сделано для удобства работы борго.
- В раздатчик еды добавлены суши, Чимичанга(содержит малое количество омнизина) и знаменитый карп Адмирала Ямомото. Это всё мясные блюда для кормежки тоерб.
- Не добавлена игрушка чтобы никто не чувствовал себя одиноким. У нас суровая игра про 2д космонавтиков. Однако, для повышения РП добавлена возможность хваталке переносить игрушки. Потому что это мило и ни на что не повлияет.
- Синтезатор оказался рабочим а я просто глухоматью который это не слышал, поэтому нет изменений в этом плане.

В целом борго приобрел кучу QoL и теперь может быть достойным модулем для развлечения экипажа.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1087700013943099392

2023-03-21 21:32 UTC, Den109G commented on code/game/objects/items/weapons/RSF.dm
> +	opacity = 0
Зачем мы прописываем непрозрачность предмету?

2023-03-21 21:34 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +	opacity = 0
копипаста с оригинала, бездумно и беспощадно чтобы не сломать ничего

2023-03-21 21:35 UTC, Den109G commented on code/modules/food_and_drinks/drinks/drinks.dm
> -	amount_per_transfer_from_this = 10
А тут что случилось? Про этот момент написано в ПРе? Лучше прямо так и написать, а не "нормальные порции". Для меня нормой считается 1ю, к примеру.

2023-03-21 21:36 UTC, ErdGinalD commented on code/modules/food_and_drinks/drinks/drinks.dm
> -	amount_per_transfer_from_this = 10
да, написано, что шейкер будет разливать как любой другой контейнер, то есть 1, 5, 10, 15, 20, 50.

2023-03-21 21:36 UTC, Den109G commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	M.matter = 30
```suggestion
	T.matter = 30
```?
Так хотел скопировать же?

2023-03-21 21:36 UTC, larentoun requested changes

2023-03-21 21:36 UTC, larentoun commented on code/_globalvars/lists/reagents.dm
> +					"gibbfloats","pumpkinjuice","blumpkinjuice","grapesoda","icecoco","alcohol_free_beer")) //holy fuck why so many
Ух, мать, конечно, такое сложно будет потом поддерживать. Сделайте функцию, чтобы она заполнялась один раз. Реализация есть на ТГ, к примеру, у серебряного слайма.

2023-03-21 21:36 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +/obj/item/rff
Нельзя было ли наследоваться от `rsf`, и просто иметь другой список выдаваемых реагентов?

2023-03-21 21:36 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +/obj/item/rff/afterattack(atom/A, mob/user as mob, proximity)
Мда, повторение кода свыше. Используй наследование!

2023-03-21 21:36 UTC, larentoun commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +	can_hold = list(/obj/item/card,
Насколько понимаю, забираешь карту у экипажа для оплаты?

Попробуй использовать у EFTPOS прок afterattack, чтобы он проверял карту на руках у "цели"-клиента.

2023-03-21 21:36 UTC, larentoun commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +		H = target
```suggestion
		var/mob/living/carbon/human/H = target
```
Лучше бы здесь инициилизировал переменную.

2023-03-21 21:36 UTC, ErdGinalD commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	M.matter = 30
да, но выдало ошибку при тупо копипасте, так что M поменял на Т чтобы не ругалось.

2023-03-21 21:37 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +/obj/item/rff
изначальный план был в этом, но там просто к уже имеющемуся пулу прилипал новый, так что проще было сделать его отдельно.

2023-03-21 21:38 UTC, ErdGinalD commented on code/_globalvars/lists/reagents.dm
> +					"gibbfloats","pumpkinjuice","blumpkinjuice","grapesoda","icecoco","alcohol_free_beer")) //holy fuck why so many
после этого ПРа будет фикс который решит все разом, это уже обсуждалось в дискорде

2023-03-21 21:38 UTC, Den109G commented on code/modules/food_and_drinks/drinks/drinks.dm
> -	amount_per_transfer_from_this = 10
Так за это отвечает possible_transfer_amounts , а не эта строка?

2023-03-21 21:39 UTC, larentoun commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +/obj/item/gripper/service/afterattack(atom/target, mob/living/user, proximity, params)
Если это копипаста с гриппера медборга, то лучше, по-моему, либо наследоваться от нее, либо дать всем грипперам этот функционал и по какой-нибудь булевой переменной разрешать это.

2023-03-21 21:40 UTC, ErdGinalD commented on code/modules/food_and_drinks/drinks/drinks.dm
> -	amount_per_transfer_from_this = 10
эта строка переписывает изначальные настройки трансфера, так что убрав её будет взята родная настройка, которая как раз и составляет указанные настройки

2023-03-21 21:40 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +/obj/item/rff
Так просто опустоши старый, в чем проблема?

2023-03-21 21:41 UTC, Den109G commented
Линтер ругается на кириллицу.

2023-03-21 21:46 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +/obj/item/rff/afterattack(atom/A, mob/user as mob, proximity)
наследование сломало все! так что будет так!

2023-03-21 21:47 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +/obj/item/rff
проблема в реализации, я умею только копировать и цифры менять. Я такие функции не знаю

2023-03-21 21:51 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +/obj/item/rff/afterattack(atom/A, mob/user as mob, proximity)
Что именно сломало?

2023-03-21 22:01 UTC, ErdGinalD commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +	can_hold = list(/obj/item/card,
Гриппер будет полностью удовлетворять все потребности новых интеракций, дополнительные действия не считаю нужным добавлять. Оно работает - значит оно работает

2023-03-21 22:12 UTC, larentoun requested changes

2023-03-21 22:12 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +	desc = "A RFF. It currently holds [matter]/30 fabrication-units."
Так, я либо глупый, либо не понимаю.
Почему изменение описание в `New()`? Я бы понял, если бы оно дополняло прошлое описание, а так, не понимаю.

2023-03-21 22:12 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +	configured_items[++configured_items.len] = list("Chinese noodles", 3000, /obj/item/reagent_containers/food/snacks/chinese/newdles)
Все же, советую наследоваться от `rsf` во избежании копипасты кода. Настоятельно советую.
```suggestion
    configured_items = list()
	configured_items[++configured_items.len] = list("Chinese noodles", 3000, /obj/item/reagent_containers/food/snacks/chinese/newdles)
```

2023-03-21 22:12 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +		desc = "A RSF. It currently holds [matter]/30 fabrication-units."
Чтобы в наследовании не было приколов, используй имя объекта, а не вот это вот.
```suggestion
		desc = "A [src]. It currently holds [matter]/30 fabrication-units."
```
Также, у тебя тут ошибка. Код RFF, а описание RSF. Не порядок. Проблема, опять же, из-за копипасты кода!

2023-03-21 22:14 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +	desc = "A RFF. It currently holds [matter]/30 fabrication-units."
жестокая и беспощадная копипаста

2023-03-21 22:15 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +	desc = "A RFF. It currently holds [matter]/30 fabrication-units."
сейчас исправлю

2023-03-22 09:50 UTC, lebedev requested changes

2023-03-22 09:50 UTC, lebedev commented on code/modules/economy/EFTPOS.dm
> +	desc = "Swipe crew ID card to pay taxes."
```suggestion
	desc = "Swipe a crew ID card to pay taxes."
```

2023-03-22 09:50 UTC, lebedev commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +	desc = "A grasping tool used to take IDs for pay taxes and wake up drunken crewmates"
```suggestion
	desc = "A grasping tool used to take IDs for paying taxes and waking up drunken crewmates"
```

2023-03-22 09:50 UTC, lebedev commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	var/obj/item/gripper/G = locate(/obj/item/gripper/service) in modules
```suggestion
	var/obj/item/gripper/service/G = locate() in modules
```

2023-03-22 19:03 UTC, lebedev approved these changes
👍

2023-03-22 19:28 UTC, larentoun requested changes

2023-03-22 19:28 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
>  	var/list/configured_items = list()
А теперь вопрос Пупса Фреско. Почему мы заполняем лист в New(), а не задаем его изначально?

2023-03-22 19:28 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +		to_chat(user, "The [name_short] can only create service items on tables, or floors.")
Какой-нибудь span_notice(), может? Чистый белый текст устарело.

2023-03-22 19:29 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
>  	var/list/configured_items = list()
Чтобы для дочернего класса не создавался родительский лист

2023-03-22 19:30 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
>  	var/list/configured_items = list()
Дочерний класс у тебя один, и он меняет лист.

2023-03-22 19:30 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +		to_chat(user, "The [name_short] can only create service items on tables, or floors.")
Хорошее предожение, пиши предложку

2023-03-22 19:31 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +	desc = initial(desc) + " Currently set to dispense '[configured_items[mode][1]]'."
Зачем изменяем описание предмета, если можно просто дополнить /examine()?

2023-03-22 19:32 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +		desc = "A [name_short]. It currently holds [matter]/30 fabrication-units."
Зачем изменяем описание предмета, если можно просто дополнить /examine()?

2023-03-22 19:34 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +		to_chat(user, "The [name_short] can only create service items on tables, or floors.")
Ты уже изменяешь, если изменяешь, то качественно, соответствующе нашим стандартам качества.

2023-03-22 19:40 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +		to_chat(user, "The [name_short] can only create service items on tables, or floors.")
Наш стандарт качества "Если оно работает - оно работает", я и моя шиза не знают что тебе ответить на твои резонные замечания, так как не знают другие варианты реализации, даже несмотря на span_notice(), значения которых мне не известны.

2023-03-22 19:41 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +	desc = initial(desc) + " Currently set to dispense '[configured_items[mode][1]]'."
Я не знаю как это сделать, так как раньше с этим не связывался, можешь показать пример?

2023-03-22 19:42 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +		desc = "A [name_short]. It currently holds [matter]/30 fabrication-units."
Через /examine это и правда будет выглядеть интереснее, но я не знаю как это реализовать. Есть пример для копирки?

2023-03-22 19:49 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +	desc = initial(desc) + " Currently set to dispense '[configured_items[mode][1]]'."
Пример можешь взять у любого `/examine(` прока, к примеру, у RCD

2023-03-22 19:50 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +		to_chat(user, "The [name_short] can only create service items on tables, or floors.")
> Наш стандарт качества "Если оно работает - оно работает", я и моя шиза не знают что тебе ответить на твои резонные замечания, так как не знают другие варианты реализации, даже несмотря на span_notice(), значения которых мне не известны.

Так я как раз-таки даже подсказал решение в этом случае...

2023-03-22 19:53 UTC, ErdGinalD commented on code/game/objects/items/weapons/RSF.dm
> +	desc = initial(desc) + " Currently set to dispense '[configured_items[mode][1]]'."
Моих текущих навыков не хватит это сделать, поэтому я с радостью приму помощь в этом нелегком деле

2023-03-22 19:55 UTC, larentoun commented on code/game/objects/items/weapons/RSF.dm
> +	desc = initial(desc) + " Currently set to dispense '[configured_items[mode][1]]'."
https://discord.com/channels/617003227182792704/734823601110515882/1088189003712446464

2023-03-23 14:14 UTC, larentoun commented on code/modules/reagents/reagent_containers.dm
> +	if((!ishuman(usr) || usr.incapacitated()) && !isrobot(usr))
Ты убрал всем роботам эту возможность. Точно все правильно?

2023-03-23 15:40 UTC, Vladisvell commented on code/modules/reagents/reagent_containers.dm
> +	if((!ishuman(usr) || usr.incapacitated()) && !isrobot(usr))
Так наоборот же, у роботов это условие и не будет соблюдаться, а выполнение продолжится дальше. Проверено на локалке.

2023-03-23 15:49 UTC, larentoun commented on code/modules/reagents/reagent_containers.dm
> +	if((!ishuman(usr) || usr.incapacitated()) && !isrobot(usr))
В каком плане?
Если у нас это делает синт, что значит isrobot(), то будет всегда идти оно в return.

Я просто не совсем понимаю, что я должен увидеть правильным действием. Роботы не должны иметь способности это делать?

2023-03-23 16:07 UTC, Vladisvell commented on code/modules/reagents/reagent_containers.dm
> +	if((!ishuman(usr) || usr.incapacitated()) && !isrobot(usr))
Так isrobot() тут проверяется на ложность, а не на истинность
Они должны иметь возможность регулировать уровень забора жидкости из контейнера.

2023-03-23 16:12 UTC, larentoun commented on code/modules/reagents/reagent_containers.dm
> +	if((!ishuman(usr) || usr.incapacitated()) && !isrobot(usr))
Силикон на isrobot() возвращает TRUE.
!isrobot(), соответственно, возвращает FALSE.

if(ANY && FALSE) => FALSE

2023-03-23 16:22 UTC, Vladisvell commented on code/modules/reagents/reagent_containers.dm
> +	if((!ishuman(usr) || usr.incapacitated()) && !isrobot(usr))
Это означает, что условие не выполняется и игра не будет сообщать роботу о том, что он не может использовать руки.

2023-03-23 16:28 UTC, larentoun commented on code/modules/reagents/reagent_containers.dm
> +	if((!ishuman(usr) || usr.incapacitated()) && !isrobot(usr))
А, всё, чего-то я сильно тупанул, думал, что логика сюда должна идти для роботов.

2023-03-23 17:08 UTC, larentoun requested changes

2023-03-23 17:08 UTC, larentoun commented on code/game/objects/items/random_items.dm
> +	var/list/special_drinks = list(/datum/reagent/pancuronium, /datum/reagent/lsd,/datum/reagent/medicine/omnizine, /datum/reagent/blood)
Почему в New()?

2023-03-23 17:08 UTC, larentoun commented on code/game/objects/items/random_items.dm
> +	var/R = /datum/reagent/
Ты хотел `var/datum/reagent/R`?

2023-03-23 17:08 UTC, larentoun commented on code/game/objects/items/random_items.dm
> +	if (prob(50 * special_drinks.len / (special_drinks.len + GLOB.drinks.len)))
length() немногим лучше, чем `.len`, а также безопасен, если лист - пустой. На будущее, как минимум.

Что значит `50`?

2023-03-23 17:33 UTC, Vladisvell commented on code/game/objects/items/random_items.dm
> +	if (prob(50 * special_drinks.len / (special_drinks.len + GLOB.drinks.len)))
Изначально с шансом 50% выбиралось, будет ли осуществлен выбор напитков с **учётом** особых напитков.
Сейчас сделано аналогично, просто записано через формулу классической теории вероятности.

2023-03-23 18:03 UTC, larentoun commented on code/game/objects/items/random_items.dm
> +	if (prob(50 * special_drinks.len / (special_drinks.len + GLOB.drinks.len)))
Будущее поколение не будет вникать в это. Если уж хотел формулу, то вынес бы ее макросом в хелперы и использовал бы ее, чтобы люди понимали, что за формула.

2023-03-23 22:09 UTC, lebedev requested changes

2023-03-23 22:09 UTC, lebedev commented on code/modules/reagents/reagent_containers.dm
> +	if(!usr.Adjacent(src) || !isliving(usr) || usr.incapacitated())
Это условие сейчас проходит и ИИ, и пИИ, и ксеносы. Им будет выдаваться окошко с выбором. Давай здесь сделаем ограничение только на гуманоидов и роботов.
```suggestion
	if(!usr.Adjacent(src) || !(ishuman(usr) || isrobot(usr)) || usr.incapacitated())
```

2023-03-23 22:09 UTC, lebedev commented on code/modules/reagents/reagent_containers.dm
> +	if((!ishuman(usr) || usr.incapacitated()) && !isrobot(usr))
Гуманоид или робот, прошедшие проверку на +25 строке, не могут перестать быть гуманоидом и роботом соответственно, но могут к моменту после выбора оказаться оглушенными. Поэтому избыточные проверки можно удалить.
```suggestion
	if(usr.incapacitated())
```

2023-03-25 23:54 UTC, Dimach commented on code/game/objects/items/random_items.dm
>  /obj/item/reagent_containers/food/drinks/bottle/random_drink/New()
Заменить New на Initial ОБЯЗАТЕЛЬНО иначе при использовании этой бутылки на картах могут лететь рантаймы

2023-03-25 23:55 UTC, Dimach commented on code/game/objects/items/random_items.dm
> +	var/datum/reagent/reagent = R
Зачем если уже есть переменная R?

2023-03-26 11:17 UTC, ErdGinalD commented on code/game/objects/items/random_items.dm
>  /obj/item/reagent_containers/food/drinks/bottle/random_drink/New()
готово

2023-03-26 11:20 UTC, ErdGinalD commented on code/game/objects/items/random_items.dm
> +	var/datum/reagent/reagent = R
При его уборке произошла ошибка в коде, так что видимо нужная тема. Оставляю. 
![image](https://user-images.githubusercontent.com/114731039/227772241-db29c55d-e92e-4e3a-8cfb-f0144725b45a.png)

2023-03-26 11:39 UTC, lebedev requested changes

2023-03-26 11:39 UTC, lebedev commented on code/game/objects/items/random_items.dm
> +	var/datum/reagent/reagent = R
Удали эту строку. А на строке, где стала возникать ошибка, вместо `reagent` используй `R`.

2023-03-26 12:55 UTC, lebedev requested changes

2023-03-26 12:55 UTC, lebedev commented on code/game/objects/items/random_items.dm
>  	..()
В отличие от `New`, `Initialize` должно обязательно возвращать значение, чтоб ничего не сломалось. Так что:
```suggestion
	. = ..()
```

2023-03-26 12:58 UTC, lebedev commented on code/game/objects/items/random_items.dm
> +	var/datum/reagent/reagent = R
@ErdGinalD ^

2023-03-28 00:28 UTC, merged