Fix: Doshi Co icon_state logic
ss220-space/Paradise pull request #2395
Opened 2023-03-22 16:37 UTC by SAADf603

## Описание
Меняет логику иконок у доширака на более понятную и простую. Она позволит в будущем сделать все снеки такими.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/1087735820422742076

2023-03-22 17:08 UTC, larentoun commented on code/modules/food_and_drinks/food/foods/junkfood.dm
> +/obj/item/reagent_containers/food/snacks/doshik/New()
Ошибка линтера, почитай

2023-03-22 17:09 UTC, larentoun commented on code/modules/food_and_drinks/food/foods/junkfood.dm
> +/obj/item/reagent_containers/food/snacks/doshik_spicy/New()
тоже прочитай линтер

2023-03-22 17:10 UTC, larentoun commented on code/modules/food_and_drinks/food/snacks.dm
> -		update_icon()
Почему обновление иконки не идет в update_icon()? Что спровоцировало на такое решение?

2023-03-22 17:10 UTC, larentoun commented on code/modules/food_and_drinks/food/snacks.dm
> +	var/opened = TRUE // FALSE if it needed to be opened first
Зачем менять название переменной? Она и так была рабочей.

2023-03-23 15:52 UTC, SAADf603 commented on code/modules/food_and_drinks/food/snacks.dm
> +	var/opened = TRUE // FALSE if it needed to be opened first
Для понимания общей логики. Кроме дошика нет закрытых предмметов, хотя чипсы и батончики должны быть. Потомкам, которые захотят это реализовать будет проще ориентироваться.

2023-03-23 15:53 UTC, larentoun commented on code/modules/food_and_drinks/food/snacks.dm
> +	if(!opened)
А где вызов ..(), если оно закрыто?

2023-03-23 15:55 UTC, larentoun commented on code/modules/food_and_drinks/food/snacks.dm
> +	var/opened = TRUE // FALSE if it needed to be opened first
Тогда уж в коде условий используй чаще `opened`, чем `!opened`. Как раз-таки `closed` был бы лучше в том контексте.

2023-03-23 15:56 UTC, SAADf603 commented on code/modules/food_and_drinks/food/snacks.dm
> +	if(!opened)
> А где вызов ..(), если оно закрыто?

следующие 2 строки
```	else
		return ..()```

2023-03-23 16:03 UTC, larentoun commented on code/modules/food_and_drinks/food/snacks.dm
> +	if(!opened)
Так. Как работает условие `if`?

2023-03-23 16:11 UTC, larentoun commented on code/modules/food_and_drinks/food/snacks.dm
> -		return ..()
А теперь где здесь потерялось...

2023-03-23 19:17 UTC, lebedev requested changes

2023-03-23 19:17 UTC, lebedev commented on code/modules/food_and_drinks/food/snacks.dm
> +		return ..()
```suggestion
	if(!opened)
		update_icon()
	..()
```

2023-03-23 19:20 UTC, lebedev approved these changes
lgtm

2023-03-23 20:15 UTC, larentoun commented on code/modules/food_and_drinks/food/snacks.dm
> +		return ..()
Можно лишь при условии `if` выполнять что-то, и потом сразу после него вызывать `. = ..()

```
		if(!opened)
			update_icon()
		..()
```

Типо такого

2023-03-23 20:16 UTC, larentoun commented on code/modules/food_and_drinks/food/snacks.dm
> +		return ..()
А еще вопрос, почему бы сразу не просто
```
update_icon()
. = ..()
```
Без всяких проверок?

2023-03-23 20:43 UTC, lebedev commented on code/modules/food_and_drinks/food/snacks.dm
> +		return ..()
> А еще вопрос, почему бы сразу не просто
> 
> ```
> update_icon()
> . = ..()
> ```
> 
> Без всяких проверок?

@larentoun какие у тебя мысли, почему этот предложенный код субоптимальней текущего?

2023-03-24 23:00 UTC, merged