(Cyberiad/Коробка/Кибериада) Преработка всего сервисного отдела и дорм.
ss220-space/Paradise pull request #2408
Opened 2023-03-23 22:18 UTC by Aylong220

## Описание
**Ботаника**
-Добавлены створки.
-Добавлен холодильник возле стойки.
**Кухня**
-Добавлено 2 настенных аквариума.
**Бар**
-Прощайте стулья, привет удобные диваны.
-Дверь отныне двойная.
-Бармену добавлены файрлоки.
**Дормы**
Коридоры стали шире.
**Клоунская и мимская**
-Теперь они вертикальные.
**Туалет**
-Добавлена дополнительная кабинка.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/930740675350233098

## Демонстрация изменений
![HydroKitchen](https://user-images.githubusercontent.com/69762909/227376955-e1b9b954-eb88-46c5-9473-dbf248ca4cd5.png)
![BarToilet](https://user-images.githubusercontent.com/69762909/227376980-f64cc545-9c04-481e-b757-55bd27dc09f6.png)
![Dormitoriers](https://user-images.githubusercontent.com/69762909/227376989-51a2505b-210d-4ac5-9a7c-576853093bcb.png)

2023-03-23 22:38 UTC, dj-34 requested changes
Накакал трубой с initilize_directions замени на трубу без неё

![image](https://user-images.githubusercontent.com/20109643/227378575-5f4b7449-d346-4981-9bd1-59082d285373.png)

Накакал дубликатами с разницой в 1 пиксель, замени на те, которых больше на карте (pixel_y 24)

![image](https://user-images.githubusercontent.com/20109643/227378918-3f8f8b53-d710-4aa0-8c08-6993fe5c31dc.png)

Вот это похоже я забыл, тоже замени на south fire alarm

![image](https://user-images.githubusercontent.com/20109643/227379032-1ee85ed3-1351-4275-90dd-22166827cfab.png)

Очень-очень много неверных дубликатов, заменяй на те, которые должны быть

![image](https://user-images.githubusercontent.com/20109643/227379117-cf08c96f-79e8-480a-b73f-308d954ad4f6.png)

Опять накакал дубликатами

![image](https://user-images.githubusercontent.com/20109643/227379473-6c9c1fed-3eed-489c-aaf1-301ea2698a02.png)

Не верный старт цивилиана, видимо копировал из старой версии карт

![image](https://user-images.githubusercontent.com/20109643/227379717-1b0d8c41-7a50-46e8-80a6-0b8c749e1934.png)

Дубликаты

![image](https://user-images.githubusercontent.com/20109643/227379745-de535622-7999-400c-9cdf-4b8fd47853e7.png)

2023-03-23 22:51 UTC, dj-34 commented
UPD: dir 6 не использовать на камерах, есть dir 2

2023-03-23 23:17 UTC, dj-34 approved these changes

2023-03-28 23:27 UTC, Dimach commented
Что за бардак в ченжах? 33 файла изменены, при этом они вообще никак к ПРу не относятся

2023-03-29 01:32 UTC, Aylong220 commented
> Что за бардак в ченжах? 33 файла изменены, при этом они вообще никак к ПРу не относятся

Облажался пока изучал гитхаб, в целом такого больше не должно повториться, спасибо что заметил. ПР закрываю, я понял где ошибся, в будущем постараюсь не допустить такого ужаса.

2023-03-29 01:32 UTC, closed without merging