FIX: Clockwork cult items
ss220-space/Paradise pull request #2431
Opened 2023-03-25 09:07 UTC by Gottfrei

## Описание

Множество различных исправлений для улучшения жизни культяпок:

- больше невозможно безнаказанно использовать предметы культа или бить культистов их же оружием
- если копьё, молот или меч были брошены и попали в культиста, они НЕ нанесут урона, а культист поймает оружие в руку
- всеми зачарованиями теперь могут пользоваться исключительно культисты
- робу культа теперь могут носить только культисты
- ботинки культа теперь имеют солидную защиту
- soul vessel теперь работает на все гуманоидные расы
- soul vessel теперь может захватывать душу из роботических, позитронных и обычных мозгов
- soul vessel более НЕ могут применять НЕ культисты

## Ссылка на предложение/Причина создания ПР

По поводу всех изменений общался с BeebBeebBoob, он предложил залить это как багфикс

2023-03-25 13:29 UTC, larentoun requested changes
Мне как-то не сильно нравится, что тут куча мала из предметов культа и взаимодействий ММИ и мозгов с... Предметами культа. В два разных файла было бы круто, конечно, все равно под это папку выделили уже.

2023-03-25 13:29 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	if(isliving(hit_atom))
Не нравятся мне пирамидки, и в нашем код-стандарте не одобряется.

Ты мог просто проверить на `if(!isliving(hit_atom))` и вернуть ..()

2023-03-25 13:29 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			if(!living.restrained() && living.put_in_active_hand(src))
Мне кажется, что ты тут хотел, чтобы эти проверки шли вместе?
Если он `restrained()`, он все равно сделает `put_in_active_hand(src)`, разве не так?

2023-03-25 13:29 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
>  	if(!isclocker(user))
Можно было тут один уровень лесенок убрать через ретурн

2023-03-25 13:29 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +/obj/item/twohanded/clock_hammer/throw_impact(atom/hit_atom, datum/thrownthing/throwingdatum)
Лесенки

2023-03-25 13:29 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			if(!living.restrained() && living.put_in_active_hand(src))
Тот же вопрос с `put_in_active_hand(src)`, что и выше

2023-03-25 13:29 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
>  			add_attack_logs(user, target, "Crushed with [src]")
А если это просто симпл-моб - ничего не происходит?

2023-03-25 13:29 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +/obj/item/melee/clock_sword/throw_impact(atom/hit_atom, datum/thrownthing/throwingdatum)
Лесенки

2023-03-25 13:29 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			if(!living.restrained() && living.put_in_active_hand(src))
Тот же вопрос, что и выше с `put_in_active_hand(src)`

2023-03-25 13:29 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +/obj/item/melee/clock_sword/attack(mob/living/M, mob/living/user, def_zone)
Лесенки

2023-03-25 13:29 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	else if(istype(O, /obj/item/storage/bible) && istype(src, /obj/item/mmi/robotic_brain/clockwork) && !isclocker(user) && user.mind.isholy)
Точно ли нужны элс ифы, если у тебя выше всё равно конечный результат - ретурн?

2023-03-26 00:28 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	if(isliving(hit_atom))
сделано.

2023-03-26 00:29 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			if(!living.restrained() && living.put_in_active_hand(src))
здесь проверка с действием, впрочем мы уже это осбудили.

2023-03-26 00:29 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
>  	if(!isclocker(user))
сделано.

2023-03-26 00:30 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +/obj/item/twohanded/clock_hammer/throw_impact(atom/hit_atom, datum/thrownthing/throwingdatum)
пофикшено.

2023-03-26 00:30 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			if(!living.restrained() && living.put_in_active_hand(src))
уже обсудили.

2023-03-26 00:30 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
>  			add_attack_logs(user, target, "Crushed with [src]")
добавил действие для симпл мобов.

2023-03-26 00:30 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +/obj/item/melee/clock_sword/throw_impact(atom/hit_atom, datum/thrownthing/throwingdatum)
пофикшено.

2023-03-26 00:31 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			if(!living.restrained() && living.put_in_active_hand(src))
уже обсудили.

2023-03-26 00:31 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +/obj/item/melee/clock_sword/attack(mob/living/M, mob/living/user, def_zone)
пофикшено.

2023-03-26 00:31 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	else if(istype(O, /obj/item/storage/bible) && istype(src, /obj/item/mmi/robotic_brain/clockwork) && !isclocker(user) && user.mind.isholy)
пофикшено.

2023-03-26 00:44 UTC, Gottfrei commented
> Мне как-то не сильно нравится, что тут куча мала из предметов культа и взаимодействий ММИ и мозгов с... Предметами культа. В два разных файла было бы круто, конечно, все равно под это папку выделили уже.

отделил soul vessel со всеми его функциями от основных предметов.

2023-03-26 00:59 UTC, larentoun requested changes
Посмотри, как работает `attack`, и работает ли оно у тебя корректно

2023-03-26 00:59 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			if(living.mind && living.mind.isholy)
Можно было бы заменить на `if(living.mind?.isholy)`, тот же самый код только компактнее.

Я сначала не сразу понял, что наш `living` - карбон. Может, лучше ее назвать `carbon`?

2023-03-26 00:59 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			if(living.mind && living.mind.isholy)
Там выше у копья тоже самое

2023-03-26 00:59 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		var/wforce = rand(force_unwielded, force_wielded)
А почему у нас урон рандомизируется?

2023-03-26 00:59 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
```suggestion
	. = ..()
```

Я не уверен, что ретурна не должно быть. А если не уверен, то ретурни хоть что-нибудь.

В этом случае, если конкретно не задан ретурн, то вернёт `.`, которую мы тут зададим в начале.

Используй `..()` тогда и только тогда, когда 100% уверен, что прок ничего не должен возвращать. Можешь даже везде, где менял, поменять `..()` на `. = ..()`

2023-03-26 00:59 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
Тот же комментарий, что и сверху
```suggestion
	. = ..()
```

2023-03-26 00:59 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +	..()
```suggestion
	. = ..()
```

Также, где произошла неудача, делай `return FALSE`, а не пустой `return`

2023-03-26 00:59 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +	return
Тоже, возвращай не пустой ретурн, а `return FALSE`, везде выше.

2023-03-26 00:59 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +	return
Тут тоже неуверен насчет пустого ретурна.

2023-03-26 01:05 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		var/wforce = rand(force_unwielded, force_wielded)
это наказание, оно не фиксированное.

2023-03-26 01:14 UTC, Gottfrei commented
> Посмотри, как работает `attack`, и работает ли оно у тебя корректно

атака работает адекватно, проверено тестами и такой же функционал используется у культа крови.

2023-03-26 01:34 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
аналогичный функционал у наказания при атаке оружием культа крови.

2023-03-26 05:35 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			if(living.mind && living.mind.isholy)
сделано.

2023-03-26 05:36 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
впрочем добавил везде.

2023-03-26 05:36 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
добавил.

2023-03-26 05:36 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +	..()
сделано.

2023-03-26 05:36 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +	return
сделано.

2023-03-26 05:37 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +	return
сделано.

2023-03-26 11:00 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork.dm
> +		else if(istype(M.current, /mob/living/simple_animal/hostile/clockwork/marauder) && isclocker(M.current))
У нас только марадеры считаются констрактами?

2023-03-26 11:08 UTC, larentoun requested changes
На мой уже замыленный вгляд, осталось только вот это.

2023-03-26 11:08 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +/obj/item/mmi/robotic_brain/attackby(obj/item/O, mob/user)
Лучше везде, где у нас `return` провальный - пиши `return FALSE`. Видимо, это все оставшиеся, что просто `return`.

ДМ, по идее, хоть и будет потом умно считать `null` как `0`/`FALSE`, но будущее поколение поймет, что будет логика для `TRUE`.

2023-03-26 11:08 UTC, larentoun commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +/obj/item/organ/internal/brain/attackby(obj/item/O, mob/user)
Лучше везде, где у нас `return` провальный - пиши `return FALSE`. Видимо, это все оставшиеся, что просто `return`.

ДМ, по идее, хоть и будет потом умно считать `null` как `0`/`FALSE`, но будущее поколение поймет, что будет логика для `TRUE`.

2023-03-26 12:41 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork.dm
> +		else if(istype(M.current, /mob/living/simple_animal/hostile/clockwork/marauder) && isclocker(M.current))
у культа Ратвара, до этого момента, вообще не было конструктов. лул

2023-03-26 13:35 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +/obj/item/mmi/robotic_brain/attackby(obj/item/O, mob/user)
пощади!

2023-03-27 16:01 UTC, larentoun approved these changes
На мой взгляд, вроде нормально. Глаза замыленны, чтобы заметить что-то еще

2023-03-27 16:15 UTC, Gottfrei commented
> На мой взгляд, вроде нормально. Глаза замыленны, чтобы заметить что-то еще

я тут ещё добавил фикс для ратавровского апгрейда киборгов, он раньше не работал адекватно, если у киборга уже имелся модуль латунника

2023-03-30 17:05 UTC, Rerik007 commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +		if(istype(victim_brain, /obj/item/mmi/robotic_brain))
```suggestion
		if(istype(victim_brain, /obj/item/organ/internal/brain))
```
Если правильно понимаю, тут задумывалось именно это. А если органические ничего не дают, то удалить этот иф.

2023-03-30 17:05 UTC, Rerik007 commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +				break
Хм. Раньше в этих строках отбрасывались безмайндовые. Теперь нет. Точно нужно чтобы пунпуна можно было законвертить?
Фарм кубиков будет, что как по мне такое себе. Если нужно чтобы первый манд конвертился - убери 3 строки ниже.

2023-03-30 17:05 UTC, Rerik007 commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +	if(istype(O, /obj/item/storage/bible) && istype(src, /obj/item/mmi/robotic_brain/clockwork) && !isclocker(user) && user.mind.isholy)
Вообще, лучше эти проверки разделить на /obj/item/mmi/robotic_brain/attackby и /obj/item/mmi/robotic_brain/clockwork/attackby . Не очень хорошо вызывать такое в родительском. Впрочем это вопрос красоты, как я понимаю.

2023-03-30 18:12 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +		if(istype(victim_brain, /obj/item/mmi/robotic_brain))
Пофиксил. Забавно то, что в игре, при тестах, оно всё равно работало на мозги органические.

2023-03-30 18:12 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +				break
да, это я погорячился.

2023-03-30 18:12 UTC, Gottfrei commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +	if(istype(O, /obj/item/storage/bible) && istype(src, /obj/item/mmi/robotic_brain/clockwork) && !isclocker(user) && user.mind.isholy)
согласен.

2023-03-30 18:56 UTC, Rerik007 reviewed
Немного предложений для красоты, остальное уже проверено.

2023-03-30 18:56 UTC, Rerik007 commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +			if(ghost.mind && ghost.mind.current == M && ghost.client)
```suggestion
			if(ghost.mind?.current == M && ghost.client)
```
Для красоты так бы.

2023-03-30 18:56 UTC, Rerik007 commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +	var/time = 40
```suggestion
	var/time = 4 SECONDS
```
Тоже для красоты бы. Обычно понятнее так, для тех кто не знает о тиках и т.п.

2023-03-30 18:56 UTC, Rerik007 commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +		time = 90
```suggestion
		time = 9 SECONDS
```

2023-03-30 18:56 UTC, Rerik007 commented on code/game/gamemodes/clockwork/clockwork_soulvessel.dm
> +		if(do_after(user, 40, target = src))
```suggestion
		if(do_after(user, 4 SECONDS, target = src))
```

2023-03-30 19:05 UTC, Rerik007 approved these changes

2023-03-30 21:04 UTC, Gottfrei commented
> Немного предложений для красоты, остальное уже проверено.

Добавил, благодарю.

2023-03-31 06:33 UTC, BeebBeebBoob approved these changes

2023-04-01 14:26 UTC, merged