Fix: TTS, Локализация озвучки и описания действий секбота и ED
ss220-space/Paradise pull request #2499
Opened 2023-03-29 21:17 UTC by Ohar

## Описание
Локализует речь и действия секботов и ED, дабы они нормально озвучивались TTS и писали свои действия в чат.

## Ссылка на предложение/Причина создания ПР
Это правка озвучки и действий

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +			speak("Угрозы вторжения [threatlevel]-го уровня!")
ТТС это будет читать как "Угрозы вторжения два-го уровня!" /  "Угрозы вторжения один-го уровня!"
```suggestion
			speak("Угрозы вторжения [threatlevel] уровня!")
```

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +			visible_message("<b>[src]</b> указывает на [C.name]!")
Это не TTS

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +	visible_message("<span class='userdanger'>[src] взрывается!</span>")
И это тоже не ТТС

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +		speak("[arrest_type ? "Задерживаю" : "Арестовываю"] <b>[C]</b>, мерз[genderize_ru(C.gender,"авца","авку","ость","авцев")] [threat]-го уровня опасности, в «[location]».", radio_channel)
Вообще, лучше так, но если будет спам, то может звучать кринжово, впрочем "Арестовываю" по мне тоже такое себе, в ином случаи предложил бы "Арестую" - на слух удобнее, имхо.
```suggestion
		speak("[arrest_type ? "Провожу задержание" : "Провожу арест"] <b>[C]</b>, мерз[genderize_ru(C.gender,"авца","авку","ость","авцев")] [threat] уровня опасности, в «[location]».", radio_channel)
```

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +							"<span class='userdanger'>[src] оглушает вас!</span>")
Не ТТС

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +						"<span class='userdanger'>[src] пытается заковать вас в стяжки!</span>")
Не ТТС

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +						"<span class='userdanger'>[src] пытается заковать вас в стяжки!</span>")
Не ТТС

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +		speak("[arrest_type ? "Задерживаю" : "Арестовываю"] <b>[C]</b>, мерз[genderize_ru(C.gender,"авца","авку","ость","авцев")] [threat]-го уровня опасности, в «[location]».", radio_channel)
Тоже самое что и в первом варианте

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +							"<span class='userdanger'>[src] [harmbaton ? "лупцует" : "оглушает"] вас!</span>")
Не ТТС, и... "лупцует"? :kekwat:

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +			visible_message("<b>[src]</b> указывает на [C.name]!")
Не ТТС

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +	visible_message("<span class='userdanger'>[src] взрывается!</span>")
Не ТТС

2023-03-30 00:56 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +			speak("Угрозы вторжения [threatlevel]-го уровня!")
Почему "УгрозЫ", а не "УгрозА"?
```suggestion
			speak("Угроза вторжения [threatlevel] уровня!")
```

2023-03-30 00:57 UTC, dj-34 commented
^ "Не ТТС", значит что подобные фразы в большинстве своём не переведены, и будет разнобойница из говна и палок

2023-03-30 05:03 UTC, NightDawnFox commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +			speak("Угрозы вторжения [threatlevel]-го уровня!")
А может лучше построить предложение, бросив код уровня в конец?
Условное "Угроза вторжения уровня семь/угроза вторжения уровня два" звучит как-то приятнее чем предложенные "два-го" и "два уровня"
```suggestion
			speak("Угроза вторжения уровня [threatlevel]!")
```

2023-03-30 12:04 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +			speak("Угрозы вторжения [threatlevel]-го уровня!")
звучит как идея

2023-03-30 16:37 UTC, Ohar commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +		speak("[arrest_type ? "Задерживаю" : "Арестовываю"] <b>[C]</b>, мерз[genderize_ru(C.gender,"авца","авку","ость","авцев")] [threat]-го уровня опасности, в «[location]».", radio_channel)
Хороший вариант, поправил

2023-03-30 17:33 UTC, Ohar commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +							"<span class='userdanger'>[src] оглушает вас!</span>")
Убрал

2023-03-30 17:33 UTC, Ohar commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +		speak("[arrest_type ? "Задерживаю" : "Арестовываю"] <b>[C]</b>, мерз[genderize_ru(C.gender,"авца","авку","ость","авцев")] [threat]-го уровня опасности, в «[location]».", radio_channel)
Поправил

2023-03-30 17:33 UTC, Ohar commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +							"<span class='userdanger'>[src] [harmbaton ? "лупцует" : "оглушает"] вас!</span>")
Вернул

2023-03-30 17:33 UTC, Ohar commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +			visible_message("<b>[src]</b> указывает на [C.name]!")
Вернул

2023-03-30 17:34 UTC, Ohar commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +	visible_message("<span class='userdanger'>[src] взрывается!</span>")
Вернул

2023-03-30 17:34 UTC, Ohar commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +						"<span class='userdanger'>[src] пытается заковать вас в стяжки!</span>")
Вернул

2023-03-30 17:34 UTC, Ohar commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +						"<span class='userdanger'>[src] пытается заковать вас в стяжки!</span>")
Вернул

2023-03-30 17:34 UTC, Ohar commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +	visible_message("<span class='userdanger'>[src] взрывается!</span>")
Вернул

2023-03-30 17:35 UTC, Ohar commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +			visible_message("<b>[src]</b> указывает на [C.name]!")
Вернул

2023-03-31 08:23 UTC, Den109G commented
У ботов же и так отключен TTS из-за их внутриигровой озвучки. Там почти каждое действие сопровождается с аудиофайлом, что никак не связан с TTS.

2023-04-01 00:21 UTC, Ohar commented
@Den109G У секботов и ED — нет, не отключен, они говорят именно через TTS

2023-04-01 00:22 UTC, Ohar commented
@dj-34 Все правки внёс

2023-04-01 01:14 UTC, Den109G commented
> @Den109G У секботов и ED — нет, не отключен, они говорят именно через TTS

Тогда убирай TTS, ибо я не вижу чтобы у них включали.
![image](https://user-images.githubusercontent.com/87372121/229258510-1b4f81fc-f2d5-4a56-91e5-b3e5a63586ba.png)
![image](https://user-images.githubusercontent.com/87372121/229258524-b0e4a2af-9ebb-4787-9a37-d8906a3a7d54.png)
![image](https://user-images.githubusercontent.com/87372121/229258535-a9064b4f-f69c-4697-b640-e393cf77888a.png)

2023-04-01 06:20 UTC, dj-34 approved these changes

2023-04-11 06:57 UTC, Ohar commented
@Den109G Добавил им нормальные голоса

2023-04-11 06:58 UTC, Ohar commented
@Bizzonium Можно вливать

2023-04-11 08:21 UTC, Den109G commented
Скачал билд. Проверил без озвучки. Проигрывается аудиофайл.
Уверен что не будет наслоения ТТСа и аудиофайла?
@Ohar 

https://user-images.githubusercontent.com/87372121/231100320-9a79daed-9e3f-40f6-8f67-a62f480c2b1e.mp4

2023-04-11 08:24 UTC, Den109G commented
Азиз, ради бога, не заливай никуда. Тут переводят даже не смотря никуда.

2023-04-11 08:31 UTC, Den109G requested changes
Разобраться почему вообще у ботов отключили ТТС.

2024-02-12 20:58 UTC, closed without merging