FEAT: add paper shredders and office toys on map
ss220-space/Paradise pull request #2542
Opened 2023-04-01 18:33 UTC by ArtemDerp

## Описание

Добавляет на основные карты шредер [#2452](https://github.com/ss220-space/Paradise/pull/2452) и офисные игрушки в виде лут спавнера [#2442](https://github.com/ss220-space/Paradise/pull/2442)
## Ссылка на предложение/Причина создания ПР

Необходимость добавить новый не создаваемый контент на карту
## Демонстрация изменений

![image](https://user-images.githubusercontent.com/87157426/229308399-c5609d10-f0d7-4c19-bcbf-56613893c458.png)

2023-04-01 18:53 UTC, dj-34 commented
Кибериада

Факс досягаемый?
![image](https://user-images.githubusercontent.com/20109643/229308909-f4287acd-0f74-49f4-b446-3f88df667e04.png)

Пол под измельчителем должен быть деревянный
![image](https://user-images.githubusercontent.com/20109643/229308953-37cc22bd-e97d-470c-bf69-3b0ecb18a12d.png)

Чё за кнопка появилась у капитана?
![image](https://user-images.githubusercontent.com/20109643/229309032-89b7e210-06cd-4790-8531-21e47e335861.png)

Слишком много цветов на квадратный метр, был всего-лишь 1, стало 3
![image](https://user-images.githubusercontent.com/20109643/229309053-a2cc6bab-9ea8-4eb8-8bbd-1418eb72f2d6.png)

Офисный предмет у ГСБ - лишнее, имхо
![image](https://user-images.githubusercontent.com/20109643/229309130-d711c0b7-905f-47a4-a836-861ce482b20e.png)

2023-04-01 19:26 UTC, ArtemDerp commented
@dj-34 
факс у авд передвинул
![image](https://user-images.githubusercontent.com/87157426/229310334-1d9bf84a-4413-4e54-b383-becaefcabcf9.png)

пол деревянный поставил

кнопка всегда была, но на соседнем столе и под стопкой бумаг - она открывает дверь в каюту

цветы расставил для сохранения симметричности помещений. могу их убрать
![image](https://user-images.githubusercontent.com/87157426/229310051-ed016a00-73d1-4a02-92f5-6747cc78d041.png)

2023-04-01 19:29 UTC, dj-34 commented
> цветы расставил для сохранения симметричности помещений. могу их убрать ![image](https://user-images.githubusercontent.com/87157426/229310051-ed016a00-73d1-4a02-92f5-6747cc78d041.png)

Цветы цветами, но ты тогда раз уж ради симметрии, убери 1 цветок справа

2023-04-05 20:54 UTC, SAADf603 requested changes
[Первое](https://discord.com/channels/617003227182792704/943940908162875473/1092343253963124756). Второе: почему ПР на добавление предметов идёт отдельно от предметов? [Третье](![Безымянный](https://user-images.githubusercontent.com/110329212/230206686-44c5a691-1f4b-4c0c-9609-b87a82b07008.png)). [Четвёртое](![1](https://user-images.githubusercontent.com/110329212/230208909-1626a3a1-8009-44dc-ac60-8db719510f22.png)). И после этого я продолжать не хочу. Офис СЕ ещё ладно, но офис ГСБ выходит за рамки. Переделывай на актуальных картах.

2023-04-21 13:57 UTC, closed without merging