FEAT: Добавление фишек для покера
ss220-space/Paradise pull request #2577
Opened 2023-04-04 09:58 UTC by FindingHeMo

## Описание
Добавление фишек для покера. Фишки будут расположены в баре на обоих картах и в заброшенном казино на Дельте. Также будет возможность покупать фишки за кредиты в автомате около карго (в котором флаги продаются). Фишки будут с механикой стакания, от количества фишек будет меняться спрайт (как с деньгами)

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1092568051918045184

## Демонстрация изменений

![Screenshot_5 (3)](https://user-images.githubusercontent.com/67709054/229756975-529a0810-ec2a-47d6-8488-af5a2045cad2.png)

2023-04-05 21:01 UTC, SAADf603 requested changes
Добавь фишки на цере.

2023-04-06 05:31 UTC, FindingHeMo commented
> Добавь фишки на цере.

Не вижу особого смысла. Церу редко включают, да и бар там постоянно пустует. В любом случае их можно будет купить в автомате около карго

2023-04-07 15:49 UTC, FindingHeMo commented
@Dimach  рассмотришь ПР?

2023-04-07 17:59 UTC, SAADf603 commented
> > Добавь фишки на цере.
> 
> Не вижу особого смысла. Церу редко включают, да и бар там постоянно пустует. В любом случае их можно будет купить в автомате около карго

Это не просьба, это требование. Мы работаем СО ВСЕМИ картами.

2023-04-07 18:01 UTC, FindingHeMo commented
> > > Добавь фишки на цере.
> > 
> > 
> > Не вижу особого смысла. Церу редко включают, да и бар там постоянно пустует. В любом случае их можно будет купить в автомате около карго
> 
> Это не просьба, это требование. Мы работаем СО ВСЕМИ картами.

ок, добавлю

2023-04-07 18:42 UTC, SAADf603 approved these changes
Everything is ok

2023-04-07 19:24 UTC, merged