Xenomorph Up
ss220-space/Paradise pull request #2818
Opened 2023-05-09 06:41 UTC by LiquidPotroh

## Описание
Ап и переработка кода ксеносов в соответствии с предложкой. 
Больше никаких константных уронов для всех каст по определённому типу цели. (Например, было 15 брута по мехам, вне зависимости ни от чего у любых ксеносов). Все циферки урона, бронепробития, урона по объктам, стаминаурона, времени открывания шлюзов и др. регулируются прямо в коде соответствующей касты ксеносов, а не разбросаны по прокам attack_alien по всему коду. Так что дальнейшие правки в балансе потребуют всего лишь поменять одну циферку.

Чуть более подробные изменения:

### Ксеноморф как базис всех видов:
- Урон обычной атаки = 20
- Бронепробитие повышено с 10 до 20, так же учитывается во многих местах, где не учитывалось раньше.
- Дизарм теперь не наносит 10-20 стамины а стабильно 20.
- Изменены модификаторы брутберна с 1/2 до 0.75/1.25.
- Теперь нахождение в желудке станит людей внутри.
- Урон объектам = 40.
- Добавлен пассивный реген в 1 хп.
- Увеличена регенерацию на траве в 1.5 раза с 5 до 7.5.
- Спавн травы теперь имеет КД 10 секунд.

### Охотник:
- Ускорено поглощение на 1 секунду.
- Шанс заблокировать прыжок равен шансу блока щита

### Дрон:
- Может проламывать заваренные вентиляции изнутри.
- Открывает двери мгновенно.

### Часовой:
- Урон обычной атаки 20 => 25
- Урон по объектам 40 => 60.
- Разархивирована эволюцию до преторианца. Стоимость 500 плазмы.
- Может проламывать заваренные вентиляции изнутри.
- Открывает двери мгновенно.
- Corrossive Acid стоимость 200 => 150. Удвоена сила кислоты.

### Преторианец:
- Урон обычной атаки 25 => 30
- Урон по объектам 60 => 80.
- Бронепробитие 20 => 30
- Возможность ломать стены (не мгновенно)
- Не может лазать по вентиляциям.
- Открывает двери мгновенно.
- Corrossive Acid стоимость 150 => 100. Удвоена сила кислоты.

### Королева:
- Спаун травы бесплатный.
- Моделька заменена на большую.
- Характеристики урона, как у преторианца
- Открывает двери мгновенно.
-  Corrossive Acid стоимость 100 => 50. Сила кислоты увеличена в 5 раз (всё ещё быстрее ломать постройки руками).
- Урон дизармом 20 => 34.
- Ломает укреплённые стены мгновенно.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1097298098029596702

2023-05-09 13:01 UTC, Gottfrei requested changes
наводим красоту

2023-05-09 13:01 UTC, Gottfrei commented on code/game/machinery/doors/airlock.dm
> +	var/time_to_open = 2
```suggestion
	var/time_to_open = 0.2 SECONDS
```

2023-05-09 13:01 UTC, Gottfrei commented on code/game/machinery/doors/airlock.dm
> +		if(time_to_open > 30)
```suggestion
		if(time_to_open > 3 SECONDS)
```

2023-05-09 13:01 UTC, Gottfrei commented on code/game/objects/structures/aliens.dm
> +			damage = max_integrity/ALIEN_RESIN_BRUTE_MOD
непонятно что за каста "d" и "q" сходу. я понимаю что такие касты были раньше, но было бы неплохо поменять их названия.

2023-05-09 13:01 UTC, Gottfrei commented on code/game/turfs/simulated/walls.dm
> +				return
```suggestion
		if(A.environment_smash & ENVIRONMENT_SMASH_RWALLS)
			dismantle_wall(1)
			to_chat(A, "<span class='info'>You smash through the wall.</span>")
			return
		if(A.environment_smash & ENVIRONMENT_SMASH_WALLS)
			to_chat(A, text("<span class='notice'>You smash against the wall.</span>"))
			take_damage(A.obj_damage)
			return
```

2023-05-09 13:01 UTC, Gottfrei commented on code/modules/mob/living/carbon/alien/alien.dm
> +	var/devour_time = 30
```suggestion
	var/devour_time = 3 SECONDS
```

2023-05-09 13:01 UTC, Gottfrei commented on code/modules/mob/living/carbon/alien/alien.dm
> +	var/time_to_open_doors = 50
```suggestion
	var/time_to_open_doors = 5 SECONDS
```

2023-05-09 13:01 UTC, Gottfrei commented on code/modules/mob/living/carbon/alien/alien.dm
> +		return ..(amount * 0.75)
константы урона, от огня/брута, лучше бы вынести в дефайны

2023-05-09 13:01 UTC, Gottfrei commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
> +	charge_max = 100
```suggestion
	charge_max = 10 SECONDS
```

2023-05-09 13:01 UTC, Gottfrei commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
> +	if(do_after(host, 40, target = (pump_target? pump_target.loc : scrubber_target.loc)))
```suggestion
	if(do_after(host, 4 SECONDS, target = (pump_target? pump_target.loc : scrubber_target.loc)))
```

2023-05-09 13:01 UTC, Gottfrei commented on code/modules/mob/living/carbon/alien/humanoid/caste/drone.dm
> +	time_to_open_doors = 2
```suggestion
	time_to_open_doors = 0.2 SECONDS
```

2023-05-09 13:01 UTC, Gottfrei commented on code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
> +	devour_time = 20
```suggestion
	devour_time = 2 SECONDS
```

2023-05-09 13:01 UTC, Gottfrei commented on code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm
> +	time_to_open_doors = 2
```suggestion
	time_to_open_doors = 0.2 SECONDS
```

2023-05-09 13:01 UTC, Gottfrei commented on code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm
> +	time_to_open_doors = 2
```suggestion
	time_to_open_doors = 0.2 SECONDS
```

2023-05-09 13:01 UTC, Gottfrei commented on code/modules/mob/living/carbon/alien/humanoid/queen.dm
> +	time_to_open_doors = 2
```suggestion
	time_to_open_doors = 0.2 SECONDS
```

2023-05-09 15:39 UTC, LiquidPotroh commented on code/game/objects/structures/aliens.dm
> +			damage = max_integrity/ALIEN_RESIN_BRUTE_MOD
Буквы используются для подставления названий спрайтов, не особо хочется шариться по всем спрайтам ксеносов и исправлять их названия на читаемые, поэтому просто оставлю поясняющий коммент

2023-05-09 16:56 UTC, Gottfrei approved these changes
ну на первый взгляд всё хорошо. тестил, кстати? kekw

2023-05-09 17:22 UTC, LiquidPotroh commented
До твоего ревью тестил все новые механики, после него - только запускаемость

2023-05-09 18:01 UTC, Rerik007 reviewed
![image](https://github.com/ss220-space/Paradise/assets/120549107/08c09c1d-aa3e-4017-ac53-ee9f737591d1)
У армблейда вот это бы убрать. А то теперь ломаться будет. Забавно что так делали когда-то.

2023-05-10 09:08 UTC, LiquidPotroh commented
@Rerik007 обожаю код парадиза

2023-05-13 06:34 UTC, LiquidPotroh commented
@Dimach тут всё готово, жду ревью или мерджа

2023-05-17 22:44 UTC, merged