bugfix + tweak
ss220-space/Paradise pull request #294
Opened 2021-08-23 13:01 UTC by botka4aet

:cl:
## What Does This PR Do
- fix: https://github.com/ss220-space/Paradise/issues/285
- fix: https://github.com/ss220-space/Paradise/issues/266 (мой косяк)
- tweak: Для исследования ядер аномалий необходимо улучшить Destructive Analyzer
- tweak: На технологических дисках теперь указывается записанная наука(Так же, как и на дисках с токсинами)

/:cl:

2021-08-24 15:40 UTC, Bizzonium commented
Что ты тут поменял? Нет ли возможности вручную изменить файл, чтоб не было проблемы с diff?
![image](https://user-images.githubusercontent.com/8555356/130647020-b4bda39d-342f-4b22-9766-0e7054372af7.png)

2021-08-24 15:51 UTC, botka4aet commented
Я вручную и менял
Изменения:
![image](https://user-images.githubusercontent.com/11385249/130648804-bece9380-f58f-4527-a6ed-395143bb6d83.png)

2021-08-24 16:30 UTC, Bizzonium requested changes

2021-08-24 16:30 UTC, Bizzonium commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='warning'>Установлен нетехнологичный предмет!</span>")
```suggestion
			to_chat(user, "<span class='warning'>Предмет не имеет технологичное происхождение!</span>")
```

2021-08-24 16:30 UTC, Bizzonium commented on code/modules/research/destructive_analyzer.dm
> +		to_chat(user, "<span class='warning'>[src.name] сперва необходимо подключить к консоли!</span>")
```suggestion
		to_chat(user, "<span class='warning'>[src.name] сперва требуется подключить к R&D консоли!</span>")
```

2021-08-24 16:30 UTC, Bizzonium commented on code/modules/research/destructive_analyzer.dm
> +	desc = "Изучайте науку, ломая вещи!"
```suggestion
	desc = "Изучайте науку, разрушая предметы!"
```

2021-08-24 19:10 UTC, Bizzonium commented
Надо конфликт с z2 разрешить

2021-08-24 20:54 UTC, botka4aet commented
Собственно я сейчас скачал текущую карту мастера220 - он все равно выдает изменения.
В самом файле необходимо заменить clownstears на soup/clownstears в двух строках.

2021-08-24 21:36 UTC, Bizzonium commented
Надо делать rebase похоже и дропать коммиты некоторые, что вызывают конфликты

2021-08-25 00:56 UTC, dj-34 commented
Ты прогонял карту через map conflict fixer и map merge?...
В \tools

2021-08-25 01:01 UTC, dj-34 commented
Я бы еще на твоем месте пересоздал бранч и выбрал бы коммиты которые нужны, ибо тут куча коммитов из твоих предыдущих PR'ов, грязновато в общем

2021-08-25 07:42 UTC, closed without merging