add: mantis blade
ss220-space/Paradise pull request #2990
Opened 2023-06-14 02:11 UTC by WolfLox

## Описание

Добавляет импланты скрытого клинка компаний Горлекс и Shellguard. Для звуков доставания и убирания оных были сделаны замены, звуки доставания теперь задаются переменной. Также изменилась логика по вставке имплантов в конечности. Ранее стоял запрет на установку двух одинаковых имплантов в разные руки. Для реализации установки имплантов были сделаны изменения в коде операций, для горлексовских имплантов были добавлены одноразовые автоимплантёры, для установки клинков без участия хирургов. Автоимплантеры сгорают после использования или при попытке извлечения импланта из них посредством отвёртки. Имланты могут быть получены через аплинк(Горлекс) в составе набора за 13 ТК, или в РНД в вариации Shellguard. 
Импланты горлекса: 20 урона на клинок + 30 пробития + 30 шанс блока
Импланты шелгуард: 15 урона + 20 пробития + 20 шанс блока
Клинки имеют механику двойного удара. При интенте харма и наличии клинков в обеих руках производится удар двумя клинками. Удар второго клинка имеет небольшую задержку для наглядности.
В случае разряда эми убираются и могут вновь достаны через 10 секунд.
Оба клинка видны на всех сканерах как hidden blade implant
В РНД клинок находится в одном разделе с прочими имплантами(мед), закрыт за 7 материалы, 7 комбаты, 7 биотех и 6 дата и стоит 5000 метала, 3000 титана и 3000 алмазов.

## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/755125334097133628/1112724538451558410
https://discord.com/channels/617003227182792704/755125334097133628/1112724621465231411

## Демонстрация изменений

![image](https://github.com/ss220-space/Paradise/assets/108519426/bbf34cf7-0c2d-4058-ac7d-c1a68c9ac41f)
![image](https://github.com/ss220-space/Paradise/assets/108519426/fac09c7e-1a6a-49df-9eb4-f4b9198707d1)
![image](https://github.com/ss220-space/Paradise/assets/108519426/3c09aedb-dd27-4c07-9357-4c151b00b935)
![image](https://github.com/ss220-space/Paradise/assets/108519426/74b2f05f-ce2f-4391-b2b3-c64b5e9da2e7)

2023-06-14 06:30 UTC, Gottfrei requested changes
Пара исправлений.

2023-06-14 06:30 UTC, Gottfrei commented on code/modules/surgery/organs/autoimplanter.dm
> +	user.drop_item_ground()
```suggestion
	user.drop_from_active_hand()
```
Этот прок требует указания предмета, если нужно просто убрать предмет из активной руки, следует использовать drop_from_active_hand()

2023-06-14 06:30 UTC, Gottfrei commented on code/modules/surgery/organs/autoimplanter.dm
> +		user.drop_item_ground()
```suggestion
		user.temporarily_remove_item_from_inventory(src, force = TRUE)
```
А здесь лучше использовать этот прок, если далее последует qdel. Или вообще его убрать.

2023-06-14 07:34 UTC, Gottfrei commented on code/game/objects/items/weapons/whetstone.dm
> +
```suggestion
	if(istype(I, /obj/item/melee/mantisblade))
		to_chat(user,  SPAN_WARNING("[I] уже остр, и не может быть заточен ещё сильнее!"))
		return
```
дублирование кода.

2023-06-14 22:56 UTC, WolfLox commented on code/game/objects/items/weapons/whetstone.dm
> +
Странно... Сейчас исправлю

2023-06-15 07:49 UTC, Gottfrei approved these changes
Ну вроде как всё остальное в порядке.

2023-06-15 10:52 UTC, merged