Улучшения хранилища боргов + Переработка гипоспрея боргов, и улучшение для него
ss220-space/Paradise pull request #300
Opened 2021-08-27 15:30 UTC by AnywayFarus

Итого, сам предложил, сам узнал что уже предлагали и сам сделал.

Список изменений:

1. В гипоспрее борга появился маннитол
2. Выбор реагента в гипоспрее борга теперь через radial_menu.
3. Добавлено два улучшение и их производство в фабрикаторе
   - Улучшение емкости хранилища, теперь вмещает в три раза больше медикаментов(burn/brute kit, nanopaste, splints)
   - Улучшение гипоспрея борга, путем замены угля на ДТПА, добавление перфы, окулина и каломели

Требуются явные ремарки в цене производства, технологиях для возможности производства, и вероятно в самих реагентах

Гигантское спасибо Vallat'у, за ответы на важные вопросы.

2021-08-27 15:59 UTC, AnywayFarus commented
добавить перфу но давать в количестве пяти.. а что, звучит как план

2021-08-27 16:09 UTC, Vallat requested changes
За исключением одного спорного момента, в плане кода всё хорошо

2021-08-27 16:09 UTC, Vallat commented on code/game/objects/items/robot/robot_upgrades.dm
> +		qdel(H)
Может ли быть несколько `obj/item/reagent_containers/borghypo` в модулях? Если нет, то лучше цикл заменить
```suggestion
	var/obj/item/reagent_containers/borghypo/H = locate() in R.module.modules
	if(H)
		R.module.modules.Remove(H)
		qdel(H)
```
Если же их много, добавить вот это
```suggestion
	for(var/obj/item/reagent_containers/borghypo/H in R.module.modules)
		R.module.modules.Remove(H)
		qdel(H)
```

2021-08-27 16:32 UTC, AttHawk commented
Я бы переименовал "medical storage increaser" в "Medical storage of holding" или "Bluespace storage module"
Во втором случае было бы очень здорово сделать его общим со всеми боргами, которые используют внутренние хранилища, а именно инженерный (который жутко страдает от запаса проводов в 60) и общего назначения (который никто не берет, но про него тоже не надо бы забывать 🤖 )

2021-08-27 17:01 UTC, botka4aet commented
Ну ES.recharge_rate *= 3 явно лишнее. Ты хранилище увеличиваешь, а не скорость его заполнения. Можно сделать альтернативу хранилищу, которая будет повышать скорость. Но воткнуть можно будет что-то одно.
Ориджинал тех тоже понизить до 4 и 5 соответственно. Или напечатал плату, сразу ее разобрал и уже 8 тех без всяких аномалий.
borg_upgrade_hypospray - лучше серебро+золото+уран+плазма+алмазы по 1000
Ну это личное мнение

2021-08-28 02:05 UTC, AnywayFarus commented
> Ну ES.recharge_rate *= 3 явно лишнее. Ты хранилище увеличиваешь, а не скорость его заполнения. Можно сделать альтернативу хранилищу, которая будет повышать скорость. Но воткнуть можно будет что-то одно.

Это всё взаимосвязанно, можно конечно попустить до двух, но когда у тебя мелкое хранилище, допустим секунд десять провести в заряднике, но стоя в три раза больше ну ради бинтов, хз, такой се кайф.

2021-08-28 02:07 UTC, AnywayFarus commented
> Я бы переименовал "medical storage increaser" в "Medical storage of holding" или "Bluespace storage module"
> Во втором случае было бы очень здорово сделать его общим со всеми боргами, которые используют внутренние хранилища, а именно инженерный (который жутко страдает от запаса проводов в 60) и общего назначения (который никто не берет, но про него тоже не надо бы забывать 🤖 )

насчет названия мейби. А вот про улучшение всех хранилищ, не знаю, у меня можно сказать был грант лишь на мед борга.

2021-08-30 13:38 UTC, AnywayFarus commented
а нахрена я замерджил, ну, надеюсь сработает

2021-09-02 12:12 UTC, Bizzonium requested changes

2021-09-02 12:12 UTC, Bizzonium commented on code/game/objects/items/robot/robot_upgrades.dm
> +	for(var/datum/robot_energy_storage/ES in M.storages)
А если вынуть апргейд, разве не останутся новые значения и не будет ли апргейд стакаться с каждой установкой и снятием апгрейдом? Ещё надо уточнить путь к ES - var/datum/robot_energy_storage/medical/ES, либо как-то сделать универсальный улучшатель хранилищ сразу на все хранилища.

2021-09-02 12:12 UTC, Bizzonium commented on code/modules/research/designs/mechfabricator_designs.dm
> +	req_tech = list("bluespace" = 5, "materials" = 7, "engineering" = 5)
```suggestion
	req_tech = list(TECH_BLUESPACE = 5, TECH_MATERIAL = 7, TECH_ENGINEERING = 5)
```

2021-09-02 12:12 UTC, Bizzonium commented on code/modules/research/designs/mechfabricator_designs.dm
> +	req_tech = list("biotech" = 7, "materials" = 7)
```suggestion
	req_tech = list(TECH_BIO = 7, TECH_MATERIAL = 7)
```

2021-09-02 18:59 UTC, AnywayFarus commented on code/game/objects/items/robot/robot_upgrades.dm
> +	for(var/datum/robot_energy_storage/ES in M.storages)
а его разве можно вынуть?
а так, в 407 - ищем в мед. модуле борга, а далее в его хранилище же. Универсальное не входит в одобренное предложение, других не трогал.

2021-09-02 19:12 UTC, AnywayFarus commented on code/game/objects/items/robot/robot_upgrades.dm
> +	for(var/datum/robot_energy_storage/ES in M.storages)
В общем, даже зашел на локалку, проверил. Многократное увеличение невозможно, ведь единственный способ(как мне казалось) избавиться от апгрейда, это сбросить модуль платой Reset, но в итоге он не удаляет из борга апгрейды, однако их эффекты сбрасывает. Как итог: Мед.борг с этим апгрейдом при сбросе модуля теряет своё хранилище, и в добавок не может поставить этот апгрейд повторно.

2021-09-02 19:35 UTC, Bizzonium commented on code/game/objects/items/robot/robot_upgrades.dm
> +	for(var/datum/robot_energy_storage/ES in M.storages)
Даю добро на универсальный апргрейд на блюспейс хранилище. А по поводу сброса, странная тема, надо изучать

2021-09-05 13:00 UTC, merged