Rework: PowerFist 2.0
ss220-space/Paradise pull request #3033
Opened 2023-06-19 09:31 UTC by NotFeldera

## Описание
В пневматический кулак теперь можно поместить батарейку или любой иной источник питания (овощная батарейка или жёлтый экстракт слайма).

Что это даёт: При ударе, вся ёмкость батареи расходуется ровно на первый удар, помимо имеющегося урона 12/24/36, пневмокулак теперь ещё даёт и сильное ЭМИ (но только по самой цели удара и по вещам, которые на ней экипированы, HИКАКОГО ЭМИ-взрыва).

Если заряд батареи (не макс. ёмкость, именно заряд) составлял более 15.000 Ватт, дополнительно по цели проходит стан+ожоговый урон. Дополнительный ожоговый урон скалируется и вычисляется по формуле расходуемый заряд/1250. Если удар наносится по экзокостюму, то гарантированно провоцирует одну из двух аварий — "Внутреннее воспламенение (Internal Fire)" или "Сбой калибровки (Calibration Failure)".

После выполненного удара, заряд батареи всегда сбрасывается до 0 Ватт, батарею можно удалить нажатием на пневмокулак (Z).
Эффект от ЭМИ, как и сброс заряда, производится только после удара по: куклам, боргам, экзокостюмам, симпл мобам. (это не будет ЭМИ-фонарик 2.0)
Стоимость предмета в аплинке не меняется.

## Ссылка на предложение/Причина создания ПР
Согласно прошедшей предложке: https://discord.com/channels/617003227182792704/755125334097133628/1113287577605251095

2023-06-20 20:21 UTC, Dimach commented
А зачем ты переформатировал весь файл на пробелы вместо табуляций?

2023-06-21 06:25 UTC, NotFeldera commented
> А зачем ты переформатировал весь файл на пробелы вместо табуляций?

Тех. неполадки при кодинге. При перекачивании файла, табуляция сказала "https://youtu.be/ph8BNjhuIr8".

2023-07-01 19:57 UTC, Dimach commented on code/game/objects/items/weapons/powerfist.dm
> +	if(cell.charge > 0 && cell)
```suggestion
	if(cell && cell.charge > 0)
```

2023-07-01 19:58 UTC, Dimach commented on code/game/objects/items/weapons/powerfist.dm
> +/obj/item/melee/powerfist/afterattack(atom/A as obj|mob, mob/user, proximity)
```suggestion
/obj/item/melee/powerfist/afterattack(atom/movable/A, mob/user, proximity)
```

2023-07-01 20:29 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +	to_chat(user, "<span class='notice'>You remove a cell from [src].</span>")
```suggestion
	if(cell)
		cell.forceMove_turf()
		cell = null
		to_chat(user, span_notice("You remove a cell from [src]."))
```
Мы должны сперва проверить есть ли внутри батарейка, иначе будут рантаймы. также стоит использовать макросы спанов, для читаемости кода. Плюс можешь добавить сообщение, когда внутри нет батарейки, а ещё лучше добавить наследование, если оно возможно.

2023-07-01 20:31 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +		user.put_in_hands(tank)
```suggestion
		tank.forceMove_turf()
		user.put_in_hands(tank, ignore_anim = FALSE)
```
здесь изменения не требуются.

2023-07-01 20:36 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +	if(cell && cell.charge > 0)
```suggestion
	if(cell?.charge > 0)
```

2023-07-01 20:37 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +	if(!proximity) return
```suggestion
	if(!proximity)
		return
```

2023-07-01 20:40 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +	if(!ismob(A))
если у нас атака никогда не сработает на моба, то следует соблюдать правило ранних возвратов

2023-07-01 20:41 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +		else if(!ismob(A))
у нас уже была проверка на моба ранее.

2023-07-01 20:51 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +		thetank.forceMove(src)
```suggestion
```
мы уже сделали форсмув в src выше:
```dm
if(!user.drop_transfer_item_to_loc(thetank, src))
```

2023-07-02 14:26 UTC, Gottfrei requested changes
ну это всё что я заметил, на данный момент.

также нужно поменять спаны (<span class=''">) на макросы, везде, где я этого не сделал, для читаемости кода.

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +			. += "<span class='notice'>[bicon(tank)] It has [tank] mounted onto it.</span>"
```suggestion
			. += span_notice("[bicon(tank)] It has [tank] mounted onto it.")
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +			. += "<span class='notice'>[bicon(cell)]The fist is charged for [cell.charge] W.</span>"
```suggestion
			. += span_notice("[bicon(cell)]The fist is charged for [cell.charge] W.")
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +	else . += "<span class='notice'>You'll need to get closer to see any more.</span>"
```suggestion
	else . += span_notice("You'll need to get closer to see any more.")
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> -	return ..()
у нас отсутствует наследование, если предмет не соответствует ни баллону, ни батарейке, оно должно вызываться, как было ранее.

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
>  			updateTank(W, 0, user)
```suggestion
			updateTank(W, FALSE, user)
```
это булевое значение, для такого предусмотрены TRUE / FALSE. причем для читаемости кода желательно указывать и название параметра в проке.
```dm
updateTank(W, removing = FALSE, user)
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +			updateCell(W, 0, user)
```suggestion
			updateCell(W, FALSE, user)
```
то же что и выше.

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +	updateCell(cell, 1, user)
```suggestion
	updateCell(cell, TRUE, user)
```
то же что и выше.

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +/obj/item/melee/powerfist/proc/updateCell(obj/item/stock_parts/cell/thecell, removing = 0, mob/living/carbon/human/user)
```suggestion
/obj/item/melee/powerfist/proc/updateCell(obj/item/stock_parts/cell/thecell, removing = FALSE, mob/living/carbon/human/user)
```
то же что и выше.

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +			to_chat(user, "<span class='notice'>[src] already has a cell.</span>")
```suggestion
			to_chat(user, span_notice("[src] already has a cell."))
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +			to_chat(user, "<span class='notice'>[src] currently has no cell inside.</span>")
```suggestion
			to_chat(user, span_notice("[src] currently has no cell inside."))
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +		to_chat(user, "<span class='notice'>You detach [thecell] from [src].</span>")
```suggestion
		to_chat(user, span_notice("You detach [thecell] from [src]."))
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +	if(!removing)
```suggestion
	else
```
у нас есть только TRUE или FALSE, никаких других значений не предвидится.

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +			to_chat(user, "<span class='warning'>[src] already has a cell.</span>")
```suggestion
			to_chat(user, span_warning("[src] already has a cell."))
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +		to_chat(user, "<span class='notice'>You insert [thecell] in to [src].</span>")
```suggestion
		to_chat(user,  span_notice("You insert [thecell] in to [src]."))
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +/obj/item/melee/powerfist/attack()
```suggestion
```
если будет браться базовый прок attack за основу, то упоминать его не нужно.

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +		return
```suggestion
	if(!proximity)
		return
	if(QDELETED(target))
		return
	if(!isobj(target) && !isliving(target))
		return
```
неверное построение логики, мы должны всегда проверять на то, что цель рядом. причём судя по коду далее нас интересуют не все мобы, а только living, для этого используется другая проверка.

также следует добавить проверку на QDELETED, потому что в цепочке атаки наша цель могла быть удалена, по какой-то из причин.

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +	if(ismob(target))
```suggestion
	if(isliving(target))
```
то же, что и в проверке выше.

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +			"<span class='userdanger'>You cry out in pain as [user]'s punch flings you backwards!</span>")
```suggestion
		mobtarget.visible_message(span_danger("[user]'s powerfist lets out a loud hiss as [user.p_they()] punch[user.p_es()] [mobtarget.name]!"), \
			span_userdanger("You cry out in pain as [user]'s punch flings you backwards!"))
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +			cell.charge = 0
```suggestion
			cell.use(cell.maxcharge)
```
для траты энергии из батарейки есть специальный прок.

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +		target.visible_message("<span class='danger'>As [user]'s powerfist comes into contact with an [target.name], you see how it remain cracked at the point of impact!</span>")
```suggestion
		target.visible_message(span_danger("As [user]'s powerfist comes into contact with an [target.name], you see how it remain cracked at the point of impact!"))
```

2023-07-02 14:26 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +			cell.charge = 0
```suggestion
			cell.use(cell.maxcharge)
```

2023-07-03 15:01 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
> +			updateCell(W, FALSE, user)
всё ещё отсутствует наследование, если наш предмет был проатакован чем угодно, кроме батарейки или баллона его нужно вызвать.
```dm
return ..()
```

2023-07-03 15:04 UTC, Gottfrei commented on code/game/objects/items/weapons/powerfist.dm
>  /obj/item/melee/powerfist/afterattack(atom/target as mob|obj, mob/living/user, proximity)
убери это ` as mob|obj` - легаси код.

2023-07-03 17:53 UTC, Dimach commented on code/game/objects/items/weapons/powerfist.dm
> +/obj/item/melee/powerfist/afterattack(atom/target as mob|obj, mob/living/user, proximity)
```suggestion
/obj/item/melee/powerfist/afterattack(atom/movable/target, mob/living/user, proximity)
```

2023-07-03 17:56 UTC, Dimach commented on code/game/objects/items/weapons/powerfist.dm
> +			updateCell(W, FALSE, user)
```suggestion
			updateCell(W, FALSE, user)
	else
		return ..()
```

2023-07-03 18:03 UTC, Dimach commented on code/game/objects/items/weapons/powerfist.dm
> +/obj/item/melee/powerfist/afterattack(atom/movable/target, mob/living/user, proximity)
```suggestion
/obj/item/melee/powerfist/afterattack(atom/target, mob/living/user, proximity)
```

2023-07-03 18:03 UTC, Dimach commented on code/game/objects/items/weapons/powerfist.dm
> +			updateCell(W, FALSE, user)
```suggestion
		updateCell(W, FALSE, user)
```

2023-07-03 18:04 UTC, Dimach commented on code/game/objects/items/weapons/powerfist.dm
>  			return
```suggestion
		return
```

2023-07-03 18:04 UTC, Dimach commented on code/game/objects/items/weapons/powerfist.dm
> +	else if(istype(W, /obj/item/stock_parts/cell))
```suggestion
	if(istype(W, /obj/item/stock_parts/cell))
```

2023-07-03 18:05 UTC, Dimach commented on code/game/objects/items/weapons/powerfist.dm
> +		return ..()
```suggestion
		return
	return ..()
```

2023-07-03 18:14 UTC, merged