FEAT: More flammable matches
ss220-space/Paradise pull request #3057
Opened 2023-06-22 05:34 UTC by ErdGinalD

Теперь спички поджигаются об КПБ, ИИ, киборгов, дронов, любую броню, любые шлема.

Плитки пола были написаны в рофельном угаре, а потому в сделку не входят по просьбе автора.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1120914460236857394

## Демонстрация изменений

2023-07-01 16:40 UTC, larentoun requested changes

2023-07-01 16:40 UTC, larentoun commented on code/modules/clothing/head/helmet.dm
> +	return
Смысл ретурнить ничего?

2023-07-01 16:40 UTC, larentoun commented on code/modules/clothing/suits/armor.dm
> +	return
Смысл ретурнить ничего?

К тому же, следует возвращать родителя в `attackby`, к примеру, `. = ..()`

2023-07-01 17:09 UTC, larentoun commented
Почему ты только изменяешь то, что говорят, не додумывая.

Ты изменил два прока `attackby`, я в одном из них указал ошибку, во втором ты решил забить?

2023-07-01 17:11 UTC, ErdGinalD commented
> Почему ты только изменяешь то, что говорят, не додумывая.
> 
> Ты изменил два прока `attackby`, я в одном из них указал ошибку, во втором ты решил забить?

2023-07-01 17:13 UTC, ErdGinalD commented
> Почему ты только изменяешь то, что говорят, не додумывая.
> 
> Ты изменил два прока `attackby`, я в одном из них указал ошибку, во втором ты решил забить?

я не просто слепой, я еще и хронический пофигист, а оба этих свойства дают печальный результат. Спасибо что следишь, у меня внимания не хватает, ровно как и критического мышления.

2023-07-01 20:08 UTC, Rerik007 commented on code/game/objects/items/weapons/lighters.dm
> +	else if(isliving(M))
Лучше это оставить как раньше, иначе не будет больше поджигания сигар в чужих ртах (кто бы этим не пользовался)
```suggestion
	if(!isliving(M))
```
Кстати, не стоит ли перенести это поджигание в конец, после сигар? Хотя с другой стороны наверное логично что облитый бензином КПБ загорается от провода регорящей спичкой в хелпе.

2023-07-02 09:38 UTC, ErdGinalD commented on code/game/objects/items/weapons/lighters.dm
> +	else if(isliving(M))
ну, спичка от кпб теперь поджигается, и даже дамажит кпб ожогами, так что наверное логично, что если на кпб бензин, он будет загораться

2023-09-08 05:58 UTC, closed without merging