Syndicate Bloodhound now have self-repair and thermals
ss220-space/Paradise pull request #3106
Opened 2023-06-30 16:35 UTC by dobryninss

Авоут пройден. https://discord.com/channels/617003227182792704/755125334097133628/1124306762271572049

## What Does This PR Do
Добавляет ассаултборгу синдиката селф-репаир и термалы.

## Why It's Good For The Game
- Ассаулт борг теперь менее бесполезен.

## Changelog
:cl:
Добавляет ассаултборг селф-репаир и термалы.
/:cl:

## Описание

## Ссылка на предложение/Причина создания ПР

## Демонстрация изменений

2023-06-30 17:14 UTC, Vladisvell commented on code/modules/mob/living/silicon/robot/syndicate.dm
> +	if(designation != "Syndicate Medical" && designation != "Spider Clan") // По предложке только ассаултборгу даем
Здесь есть пара моментов:
1. Проверка на designation выглядит костыльно и может не учитывать моментов в будущем, если кто-нибудь захочет ввести нового синдиборга. Также у борга саботёра будут эти улучшения, что лучше обозначить в _его_ init, а не по умолчанию.
2. Одно (простое) из возможных решений - сделать сравнение designation по "Syndicate Assault" в этой и следующей проверке. `if(designation == "Syndicate Assault")`
3. Второе решение (чуть сложнее), сделать подтип от /mob/living/silicon/robot/syndicate/ , который будет наследовать всё поля и внести в его init выдачу термалов и селфрепаира. Но, придётся поменять связанный с этим используемый код, например заказа нюкоборгов. Это отдельный рефактор, который можно сделать уже в другом ПРе

2023-06-30 17:14 UTC, Vladisvell commented on code/modules/mob/living/silicon/robot/syndicate.dm
> -	var/obj/item/borg/upgrade/selfrepair/SR = new /obj/item/borg/upgrade/selfrepair(src)
Здесь стоит вернуть удаленную выдачу возможностей боргу, т.к всё как раз работает корректно здесь благодаря наследованию.

2023-07-01 16:38 UTC, larentoun requested changes

2023-07-01 16:38 UTC, larentoun commented on code/modules/mob/living/silicon/robot/syndicate.dm
> +	if(designation != "Syndicate Medical" && designation != "Spider Clan") // По предложке только ассаултборгу даем
Тут как раз и надо делать в наследовании, а не вот эти проверки. И то, скорее, при смене модуля. Проки на это должны быть

2024-01-23 12:09 UTC, closed without merging