Fix: spider bomb planting.
ss220-space/Paradise pull request #3112
Opened 2023-07-01 11:31 UTC by Daeberdir

## Описание
Дополнительная проверка на локацию цели для плентинга бомбы ниндзи.

## Причина создания ПР
Сейчас проверка бомбы учитывает только её локацию при взрыве и локацию ниндзи при плентинге. В итоге ниндзя, находясь на краю нужной зоны, может плентить вне этой зоны, что приводит к ошибкам и иногда даже может заруинить цель, ведь новая бомба появляется хуй пойми где. Фикс фиксит, хоть и по 2головьему.

2023-07-01 16:29 UTC, larentoun requested changes

2023-07-01 16:29 UTC, larentoun commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +	if(armed)
Выше ведь уже проверял на `armed`?

2023-07-01 16:29 UTC, larentoun commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +	if(!check_loc(ninja, FALSE, AM))
Что за `AM`? Поменяй на что-то, что более понятно, да тот же `target`

2023-07-01 16:29 UTC, larentoun commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +/obj/item/grenade/plastic/c4/ninja/proc/check_loc(mob/user, armed, atom/movable/plant)
Я бы переименовал `plant` на что-то чуть более явное, как `plant_location` или `target`

2023-07-02 06:00 UTC, Daeberdir commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +	if(!check_loc(ninja, FALSE, AM))
AM - Atom Movable, как я понял. Это просто было там с самого начала и, по всей видимости, Фуру было удобно именно такое значение. Пока лучше не менять.

2023-07-02 06:04 UTC, Daeberdir commented on code/game/gamemodes/spaceninja/ninja/ninja_explosive.dm
> +/obj/item/grenade/plastic/c4/ninja/proc/check_loc(mob/user, armed, atom/movable/plant)
`target` не пойдёт, ибо там дальше уже есть значение с таким названием и оно используется для места **подрыва** бимбы. Впринципе, вначале именно таргетом я это и сделал, но оно начало давать сбои, ибо не находило место подрыва и фините ля комедиа.

2023-07-03 18:27 UTC, merged