UP: Rescue jaw
ss220-space/Paradise pull request #3116
Opened 2023-07-01 14:46 UTC by ErdGinalD

## Описание
Теперь спасательная клешня меха открывает дверь быстрее чем клешня жизни.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1124465737570992138

## Демонстрация изменений

2023-07-01 16:10 UTC, larentoun requested changes

2023-07-01 16:10 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +				var/result = do_after(user, 50 * gettoolspeedmod(user), target = src)
```suggestion
				var/result = do_after(user, 5 SECONDS * gettoolspeedmod(user), target = src)
```

2023-07-01 16:10 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +					to_chat(user, "<span class='warning'>Despite your attempts, [src] refuses to open.</span>")
```suggestion
					to_chat(user, span_warning("Despite your attempts, [src] refuses to open"))
```

2023-07-01 16:10 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +				if(density && !open(TRUE))
1. density ты уже сверху проверил
2. пирамида слишком глубокая

2023-07-01 16:10 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +			var/result = do_after(user, 40 * gettoolspeedmod(user), target = src) // faster because of ITS A MECH
```suggestion
			var/result = do_after(user, 4 SECONDS * gettoolspeedmod(user), target = src) // faster because of ITS A MECH
```

2023-07-01 16:10 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +			prying_so_hard = TRUE //so you dont pry the door when you are already trying to pry it
Это зачем вообще нужно?
do_after_once() существует

2023-07-01 16:10 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +		var/result = do_after(user, 50 * gettoolspeedmod(user), target = src)
```suggestion
		var/result = do_after(user, 5 SECONDS * gettoolspeedmod(user), target = src)
```

2023-07-01 16:10 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
>  		prying_so_hard = TRUE
do_after_once()

2023-07-01 16:12 UTC, ErdGinalD commented on code/game/machinery/doors/airlock.dm
> +			prying_so_hard = TRUE //so you dont pry the door when you are already trying to pry it
это копипаста кода пожарного топора

2023-07-01 16:17 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +			prying_so_hard = TRUE //so you dont pry the door when you are already trying to pry it
> это копипаста кода пожарного топора

Сделай тогда и там лучше

2023-07-01 16:45 UTC, larentoun requested changes

2023-07-01 16:45 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
>  				if(shock(user, 100))
Пирамидка классная, да

2023-07-01 16:45 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +				var/result = do_after_once(user, 5 SECONDS * gettoolspeedmod(user), target = src)
Можно отказаться от переменной `result` и просто сделать иф `if(do_after_once())`

2023-07-01 16:45 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +		if(density)
Опять, же, пирамидка.

2023-07-01 16:45 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +			var/result = do_after_once(user, 4 SECONDS * gettoolspeedmod(user), target = src) // faster because of ITS A MECH
тоже самое, что и сверху

2023-07-01 16:45 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +					to_chat(user, "<span class='warning'>Despite your attempts, [src] refuses to open.</span>")
А чего это не залил?

2023-07-01 16:45 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
>  			else
лишний елс?

2023-07-01 16:45 UTC, larentoun commented on code/game/machinery/doors/airlock.dm
> +	var/result = do_after_once(user, 5 SECONDS * gettoolspeedmod(user), target = src)
как и выше

2023-07-01 16:54 UTC, ErdGinalD commented on code/game/machinery/doors/airlock.dm
>  				if(shock(user, 100))
ну щито поделать, тут вопросы уже к целой страничке

2023-07-01 16:54 UTC, ErdGinalD commented on code/game/machinery/doors/airlock.dm
>  			else
без понятия.

2023-07-02 14:52 UTC, Dimach commented on code/game/machinery/doors/airlock.dm
> +				close(FALSE)
```suggestion
				close(TRUE)
```

2023-07-02 14:56 UTC, Dimach commented on code/game/machinery/doors/airlock.dm
> +		if(F.wielded && density)
Довольно странно то что тебе будет писать что топор нужно держать двумя руками если фаерлок уже открыт

2023-07-02 14:57 UTC, ErdGinalD commented on code/game/machinery/doors/airlock.dm
> +		if(F.wielded && density)
"поубирай лесенки" говорили они, "лесенки плохо" утверждают они.. а потом приходят и говорят все хуйня верни как было. Ларен, блять..

2023-07-02 14:58 UTC, Dimach commented on code/game/machinery/doors/airlock.dm
> +				to_chat(user, "<span class='warning'>Despite your attempts, [src] refuses to open.</span>")
Это предупреждение писалось если open вернул FALSE, а не если игрок сбросил do_after_once например двинувшись с места. Тут можно переписать следующим образом
if(do_after_once(user, 5 SECONDS * gettoolspeedmod(user), target = src) && !open(TRUE) && density)
    to_chat(span_warning("Despite your attempts, [src] refuses to open."))

2023-07-02 15:04 UTC, Dimach commented on code/game/machinery/doors/airlock.dm
> +		if(F.wielded && density)
Он имел в виду не это. Я понял что он от тебя хотел
Вместо конструкции
if(some)
   if(some_2)
     do_some()
он хочет чтобы ты написал
if(!some)
   return
if(!some_2)
  return
do_some()

Но вообще тут весь прок написан через жопу с повторяющимися проверками

2023-07-02 15:05 UTC, ErdGinalD commented on code/game/machinery/doors/airlock.dm
> +		if(F.wielded && density)
ОАО "Та за що", компания и сюда пустила свои корни

2023-07-02 15:08 UTC, Dimach commented on code/game/machinery/doors/airlock.dm
> +			to_chat(user, "<span class='warning'>Despite your attempts, [src] refuses to open.</span>")
```suggestion
	if(do_after_once(user, 5 SECONDS * gettoolspeedmod(user), target = src) && !open(TRUE) && density)
		to_chat(user, "<span class='warning'>Despite your attempts, [src] refuses to open.</span>")
```

2023-07-02 16:21 UTC, merged