CereImprovement-pt7
ss220-space/Paradise pull request #3456
Opened 2023-08-31 19:45 UTC by aeternaclose

## Описание
**_Вкратце переделка сервиса цере и фикс поломанных спрайтов дивана(Спасибо Элл Гуду)._**

## Ссылка на предложение/Причина создания ПР
_**Очередная обнова цере.**_
![image](https://github.com/ss220-space/Paradise/assets/127967350/86364cbe-cb21-4c34-afe3-907b7298275c)

## Демонстрация изменений
![serviscere](https://github.com/ss220-space/Paradise/assets/127967350/63ba2b29-7f1b-4c2f-a22b-62f0555af31a)

2023-09-02 11:31 UTC, SAADf603 requested changes
![2023-09-02 19 28 20](https://github.com/ss220-space/Paradise/assets/110329212/0b7f2f41-cae6-4641-9bde-826abdd5150d)
1) трубу мусорки у барбера вынести из-под окна
2) интерком на тайл ниже, что бы не было наложения
3) трубы сдвинуть на тайл вправо

2023-09-06 15:10 UTC, SAADf603 approved these changes
Спустя 3 дня наконец-то смогла добиться удаление проклятой картинки из описания ПРа.

Ну и карту поправили, да. Теперь хорошо

2023-09-06 17:37 UTC, aeternaclose commented
> Спустя 3 дня наконец-то смогла добиться удаление проклятой картинки из описания ПРа.
> 
> Ну и карту поправили, да. Теперь хорошо

![image](https://github.com/ss220-space/Paradise/assets/127967350/97e993f8-9ac9-46e9-a71c-b844daed7ed0)

2023-09-07 09:52 UTC, aeternaclose commented
@Dimach Мержани пожалуйста.

2023-09-07 18:59 UTC, merged