Доработка инвентаря SeedExtractor и итерфейс на TGUI
ss220-space/Paradise pull request #39
Opened 2021-06-15 17:57 UTC by PsychoTheWeasel

## What Does This PR Do
Исправляет проблемы с хранением семян в экстракторе и добавляет новый интерфейс

## Why It's Good For The Game
Изначально экстрактор семян хранит семена в группах по виду растения и основным характеристикам, при этом в одной группе могут находиться семена с разными генами веществ/черт/уязвимостью к сорнякам, если совпадает их вид и основные характеристики. В результате без дополнительной проверки не понять что именно за семечко из экстрактора вытащили.

Данный ПР расширяет систему хранения до группировки семян с учетом всех генов. И дает стильный интерфейс в комплекте для навигации по всему этому разнообразию.

## Images of changes
![изображение](https://user-images.githubusercontent.com/85953769/122100278-33a96b00-ce3d-11eb-99bb-f8f338db1034.png)

## Changelog
:cl:
add: Новый интерфейс экстрактора семян
tweak: Доработано хранение семян в экстракторе с учетом генов веществ/черт
/:cl:

2021-06-30 19:22 UTC, Bizzonium requested changes
Забыл кнопку сабмит нажать((

2021-06-30 19:22 UTC, Bizzonium commented on code/modules/hydroponics/seed_extractor.dm
> +/proc/generate_seedId(obj/item/seeds/O) //Генерация строки-идентификатора для поиска
Мне не нравится, что эта функция в слишком широком scope. Перенести бы на `/obj/machinery/seed_extractor`

2021-06-30 19:22 UTC, Bizzonium commented on code/modules/hydroponics/seed_extractor.dm
> +/proc/generate_seedId(obj/item/seeds/O) //Генерация строки-идентификатора для поиска
```suggestion
/obj/machinery/seed_extractor/proc/generate_seedId(obj/item/seeds/O) //Генерация строки-идентификатора для поиска
```

2021-06-30 19:22 UTC, Bizzonium commented on code/modules/hydroponics/seed_extractor.dm
> +/proc/generate_strainText(obj/item/seeds/O) //Генерация отображаемого текста описания
```suggestion
/obj/machinery/seed_extractor/proc/generate_strainText(obj/item/seeds/O) //Генерация отображаемого текста описания
```

2021-06-30 19:22 UTC, Bizzonium commented on code/modules/hydroponics/seed_extractor.dm
> +	. = 1
```suggestion
	. = TRUE
```

2021-06-30 19:22 UTC, Bizzonium commented on code/modules/hydroponics/seed_extractor.dm
> +			return 0
```suggestion
			return FALSE
```

2021-07-01 14:32 UTC, PsychoTheWeasel commented on code/modules/hydroponics/seed_extractor.dm
> +/proc/generate_seedId(obj/item/seeds/O) //Генерация строки-идентификатора для поиска
Ок. Придется тогда и место вызова перенести. Из текущего с таким scope не увидит.

2021-07-02 15:32 UTC, merged