add: Central Command rework
ss220-space/Paradise pull request #3900
Opened 2023-11-18 15:55 UTC by ItsMeJaba

## Ссылка на предложение/Причина создания ПР

## Описание
Изменение и рокировка в нижней половине ЦК
![2023-11-18 20 25 56](https://github.com/ss220-space/Paradise/assets/91949115/8007ce3a-a985-48e9-9b59-42168d8262ba)

# ОБР
* Оружейная ОБР вытянута в единый коридор
![image](https://github.com/ss220-space/Paradise/assets/91949115/2069495b-96b9-4f1c-aa13-b31e2fbe25b3)

* Брифинговая ОБР стала более открытой и удобной, как для передвижения, так и в плане организации мест
![image](https://github.com/ss220-space/Paradise/assets/91949115/c1189e0c-6e56-4baf-9771-a3bba447852e)

* Создан "Плац" с карантинной карантинной блокировкой (выступающие стены являются рескином шаттеров, которые скрывают турели)
![image](https://github.com/ss220-space/Paradise/assets/91949115/3f55e101-c9e2-4221-ba7d-0db05cc436f7)

* Медицинский блок был расширен, возвращена машина клонирования.
![image](https://github.com/ss220-space/Paradise/assets/91949115/25b23635-dfdc-48ae-a899-1ef7d8825579)

* Добавлена "жилая" зона ОБР
![image](https://github.com/ss220-space/Paradise/assets/91949115/6f1fe250-aa81-4c38-a74a-87fac1c44129)

* Добавлен одноразовый дроппод НТ.
Не содержит турелей и других опасных элементов, просто падающая с потолка бандура
![image](https://github.com/ss220-space/Paradise/assets/91949115/51b759e2-8a65-4f55-9a8e-1416d1a007fc)

# Отдел снабжения ЦК
![image](https://github.com/ss220-space/Paradise/assets/91949115/05b92d25-df1c-4cc4-96fb-d9ef5e5a194a)

* Гамма оружейная смещена в отдел снабжения
* Подставка под медали была изменена на вендомат со спрайтом кейса для медалей капитана
* Добавлены вендоматы со снаряжением медиков, инженерным и уборщика. (Имеют в себе все снаряжение, что не лежит на подставках и коробки с соответствующими хардсьютами)
* Доабвлен вендомат с коробками, содержащие полный набор ЕРТ Эмбер и Ред, а также карточки с самозаписью
* Добавлен вендомат с ресурсами
* Все снаряжение и мехи, что занимали северную "стоянку" помещены в вендоматы
* Добавлен вендомат с пресетами ящиков и сумок.
Имеет 3 вида ящиков: доставка НТ, СБ, оружейный
Наборы: подавления бунтов, на случай военных действий, пауков террора, блоба, лозы и строительного ивента

# Архив
![image](https://github.com/ss220-space/Paradise/assets/91949115/5f4dc6a6-f85f-4e82-b3bd-1d67ad36d3dc)

* Имеет своего архивариуса - мимика с фракцией НТ (НЕ АГРЕССИВЕН)
* Помимо рандомных постеров и книг содержит несколько бумаг со старыми мемами, объединенные тематикой факсов и офисной рутины ЦК

# Шаттлы
16 версий ferry шаттлов
![2023-11-18 20 50 06](https://github.com/ss220-space/Paradise/assets/91949115/ce101598-ea46-4794-9d02-21543e38aa93)

3 версии admin шаттлов
![Безымянный](https://github.com/ss220-space/Paradise/assets/91949115/c280715a-783b-4bfe-a7ed-1360a60b3341)
![2023-11-18 20 52 08](https://github.com/ss220-space/Paradise/assets/91949115/8dba44d4-8086-4a49-b32b-adcdcf0fc966)

2023-11-20 16:13 UTC, Etrnlmelancholy commented
Нужны турели как на старом цк об которые экипаж может убиваться

2023-11-21 10:26 UTC, ReloadKey commented
На обновления ЦК уже очередь, дождитесь всех мержей чтоли или поговорите с димачом.
Также не могу найти эту отсылку, зачем удалили?
![image](https://github.com/ss220-space/Paradise/assets/126337700/fd1ee691-2c47-43d6-b34f-74698da6fea4)

2023-11-21 10:36 UTC, definitelynotspaghetti commented
Поебень о которой два-три человека могут знать это не отсылка, а хуета

> На обновления ЦК уже очередь, дождитесь всех мержей чтоли или поговорите с димачом. Также не могу найти эту отсылку, зачем удалили? ![image](https://user-images.githubusercontent.com/126337700/284545502-fd1ee691-2c47-43d6-b34f-74698da6fea4.png)

2023-11-24 21:16 UTC, ReloadKey commented
> Поебень о которой два-три человека могут знать это не отсылка, а хуета
> 
> > На обновления ЦК уже очередь, дождитесь всех мержей чтоли или поговорите с димачом. Также не могу найти эту отсылку, зачем удалили? ![image](https://user-images.githubusercontent.com/126337700/284545502-fd1ee691-2c47-43d6-b34f-74698da6fea4.png)

Имейте уважение к авторам реворков, челяди...

2024-01-15 20:45 UTC, Den109G commented on code/game/machinery/doors/shutters.dm
> +	name = "reinforsed wall"
```suggestion
	name = "reinforced wall"
```
**GRAMMAR POLICE**
*ouy'er
Если конечно же оно не должно выглядеть как фейковая-фейковая стена.

2024-01-15 21:35 UTC, Den109G commented on _maps/map_files/generic/CentComm.dmm
> +	products = list(/obj/item/grenade/flashbangs=4,/obj/item/flash=5,/obj/item/flashlight/seclite=4,/obj/item/restraints/legcuffs/bola/energy=8,/obj/item/ammo_box/shotgun=4,/obj/item/ammo_box/shotgun/bu
```suggestion
	products = list(/obj/item/storage/box/flashbangs=4,/obj/item/flash=5,/obj/item/flashlight/seclite=4,/obj/item/restraints/legcuffs/bola/energy=8,/obj/item/ammo_box/shotgun=4,/obj/item/ammo_box/shotgun/buck=4,/obj/item/ammo_box/shotgun/rubbershot=4,/obj/item/ammo_casing/shotgun/stunslug=35,/obj/item/ammo_casing/shotgun/ion=14,/obj/item/ammo_casing/shotgun/laserslug=35,/obj/item/ammo_box/speedloader/shotgun=8,/obj/item/ammo_box/magazine/lr30mag=12,/obj/item/ammo_box/magazine/enforcer=18,/obj/item/ammo_box/magazine/enforcer/lethal=28,/obj/item/ammo_box/magazine/sp8=8,/obj/item/ammo_box/magazine/laser=12,/obj/item/ammo_box/magazine/wt550m9=20,/obj/item/ammo_box/magazine/m556=12,/obj/item/ammo_box/a40mm=4,/obj/item/ammo_box/c46x30mm=8,/obj/item/ammo_box/inc46x30mm=4,/obj/item/ammo_box/tox46x30mm=4,/obj/item/ammo_box/ap46x30mm=4,/obj/item/ammo_box/laserammobox=4);
```
`/item/grenade/flashbangs` нету в билде. Есть коробка с этими гренами.

2024-02-13 04:31 UTC, PinnoQYow commented
Шаттерсы под чьим доступом? На нынешнем ЦК можно спокойненько на Эмбере залутать админскую карточку в шкафу, вырезав шлюз, а потом с её помощью и гибпушку в офисе ОСО.
![image](https://github.com/ss220-space/Paradise/assets/155892633/3d130493-7da6-4290-bd01-3838aefd91b8)

2024-02-13 14:16 UTC, ItsMeJaba commented
> Шаттерсы под чьим доступом? На нынешнем ЦК можно спокойненько на Эмбере залутать админскую карточку в шкафу, вырезав шлюз, а потом с её помощью и гибпушку в офисе ОСО. ![image](https://private-user-images.githubusercontent.com/155892633/304294201-3d130493-7da6-4290-bd01-3838aefd91b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzMzNDUsIm5iZiI6MTcwNzgzMzA0NSwicGF0aCI6Ii8xNTU4OTI2MzMvMzA0Mjk0MjAxLTNkMTMwNDkzLTdkYTYtNDI5MC1iZDAxLTM4MzhhZWZkOTFiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNDA0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTQ3MjI3ZTIxNDQyN2FiZjMzZTVlNjI2YWRjZGI2MzA2YzZjOGNhNDI5NzQ3MjYwNmI3MmJiMTI4MWJiNDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OJnyoMzw4JmVpjhrin_by8-98NusRLE7MOIJQ2KWuLw)

req_access = list(114) - доступ ЦКшных ролей, такой же как и на всех остальных дверях в офисы, т.е. не ЕРТшный (109/111). Это шаттерсы специально от говнистостых

2024-02-13 14:56 UTC, SAADf603 commented
ревью через час

2024-02-17 14:34 UTC, SAADf603 approved these changes, later dismissed

2024-02-20 11:39 UTC, TrashDoxx commented
Накладываю вето.

2024-02-20 12:59 UTC, ItsMeJaba commented
> Накладываю вето.

Пральна, у меня последний коммит не залит с дофиксами

2024-02-20 13:04 UTC, TrashDoxx commented
> Пральна, у меня последний коммит не залит с дофиксами

Пингани, как зальёшь.

2024-02-21 12:56 UTC, TrashDoxx commented
Снимаю вето. @Dimach Мержи, это баг-фикс.

2024-03-04 16:23 UTC, SAADf603 requested changes
Ссылка на ревью: https://discord.com/channels/617003227182792704/943940908162875473/1214227998388002816

2024-07-12 08:56 UTC, Vladisvell submitted a review, later dismissed
Ты не ты когда ты
mapper_angry.ogg
mapper_annoyed.ogg
mapper_death.ogg
mapper_disappointed.ogg
mapper_scream.ogg

2024-07-12 09:08 UTC, NightDawnFox submitted a review, later dismissed
Ждет мерджа с момента Nov 18, 2023

2024-07-26 16:48 UTC, merged