add: Skills HUD and Science implants
ss220-space/Paradise pull request #3937
Opened 2023-11-26 12:15 UTC by Mindfri

## Описание

Добавляет два новых импланта с Skills HUD'ом и Science. Импланты можно напечатать в протолате и мехфабе. Так же импланты будут лежать в шкафах глав. Science - СМО и РД, Skills HUD - все главы, исключая ГСБ.
## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/755125334097133628/1171850370109157437
## Демонстрация изменений

2023-11-26 19:46 UTC, TrashDoxx commented
![image](https://github.com/ss220-space/Paradise/assets/67621641/ab60d33e-09e6-4f69-9aac-571f9be12e3e)

Чувак, ну у тебя буквально смежные блоки кода есть для сравнения.

2023-11-26 19:51 UTC, TrashDoxx commented
https://www.byond.com/docs/ref/index.html#/proc/for/list

2023-11-26 19:51 UTC, TrashDoxx commented
Почитай и проблема решится сама собой, как только поймёшь принцип работы.

2023-11-27 13:38 UTC, TrashDoxx commented
У тебя по прежнему код не работает так, как нужно. Ты если единичку любому другому импланту пропишешь, оно работать не будет. Ты или класс переменной в цикле смени на родительский, или избавься от переменной scan_items, если функционал твоего объекта должен быть уникальным, потому как она тут лишняя будет.

2023-12-05 06:23 UTC, Daeberdir requested changes
Про-дол-жа-ем.

2023-12-05 06:23 UTC, Daeberdir commented on code/modules/mob/living/carbon/human/human.dm
> +	for(var/obj/item/organ/internal/cyberimp/eyes/science/F in internal_organs)
```suggestion
	for(var/obj/item/organ/internal/cyberimp/eyes/F in internal_organs)
```
Какой смысл проверять только наличие определённого импланта, если ты сделал для различия отдельную переменную в самих глазных имплантах?

2023-12-05 06:23 UTC, Daeberdir commented on code/modules/surgery/organs/augments_eyes.dm
> +	var/scan_items = 0
`scan_items` стоит заменить на `scan_reagents`, чтобы не путалось. Ведь это только часть со сканированием реагентов.

2023-12-05 06:23 UTC, Daeberdir commented on code/modules/surgery/organs/augments_eyes.dm
Далее тебе ещё нужно, чтобы худ видел техи предметов ведь. Это либо нужно `actions_types = list(/datum/action/item_action/organ_action/"твой новый экшн")` и создать новую штуку, которая будет работать аналогично версии из научных очков, либо `insert() remove()` проки заставлять выдавать персонажу "видимость технологий" или как её там. Проблема будет в `/datum/action/item_action/toggle_research_scanner`, который напрочь убирает "видимость технологий" при снятии или переключении очков. Давай-давай, работай дальше.

2024-02-12 20:57 UTC, closed without merging