tweak: wallmount nanomed rebalance
ss220-space/Paradise pull request #3991
Opened 2023-12-04 12:21 UTC by timchigaming

## Описание
Меняет содержимое наномедов станции и синдиката на:
**Было:**
2 bruise packs
2 ointment
5 epi medipens
1 health analyzed

**Стало:**
2 bruise packs
2 ointment
2 epi medipens
2 charcoal medipens
1 salbutamol medipens
1 health analyzer

Плюс перевод рекламы
## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/1178076568652873818

2023-12-08 05:35 UTC, LiquidPotroh commented on code/game/machinery/vending.dm
> +	armor = list(melee = 50, bullet = 20, laser = 20, energy = 20, bomb = 0, bio = 0, rad = 0, fire = 100, acid = 70)
Просто сотри строчку, чем придумывать какие то непонятные цифры. У машинерии прописан свой армор, тут не должно отличаться по идее.

2023-12-09 07:44 UTC, Daeberdir requested changes
Просто так из ниоткуда ребаланс? Ну пусть будет, наверное?

2023-12-09 07:44 UTC, Daeberdir commented on code/game/machinery/vending.dm
> +	ads_list = list("Иди и спаси несколько жизней!","Лучшее снаряжение для вашего медотдела","Только лучшие инструменты","Натуральные химикаты!","Эта штука спасает жизни","Может сами примете?","Пинг!")
```suggestion
	ads_list = list("Бегом спасать жизни!","Лучшее снаряжение для вашего медблока.","Только лучшие инструменты.","Натуральные химикаты!","Эта штука спасает жизни.","Не хотите пробник?")
```
Не теряй точки. И если уж это перевод (ну нифига себе), то пусть будет **переводом**.  "Перевод" ниже тоже стоит поправить.

2023-12-09 08:00 UTC, Daeberdir commented
А, и ещё. Если уж теперь уголь появляется в наномеде в виде инжекторов, то стоит шприцы с углём убрать из списка контрабандных товаров наномеда?

2024-01-26 11:27 UTC, closed without merging