add: cargo quest console etc
ss220-space/Paradise pull request #4047
Opened 2023-12-11 10:13 UTC by Rerik007

## Описание
Несколько изменяет систему накопления очков в карго почти полностью в соответвии с https://shorturl.at/qsNTW
Основное изменение в том карго не даются очки за диски, теперь техникам нужно выполнять "заказы" с ЦК для их получения. Пассивное накопление очков снижено в 2 раза.
Также добавлены немного новой одежды каргоотделу.
Каргоотдел Тайпана не менялся.

## Ссылка на предложение/Причина создания ПР
Аголосование: https://discord.com/channels/617003227182792704/755125334097133628/1152299299808477265

## Демонстрация изменений
![image](https://github.com/ss220-space/Paradise/assets/120549107/b0e84273-526c-4840-a620-b4ff3ab52cc1)

![image](https://github.com/ss220-space/Paradise/assets/120549107/5fae72b5-3d0e-4205-8eea-c2ca6a9e5754)

2023-12-12 01:34 UTC, Gaxeer commented
@SuhEugene интерфейс достойный. Мне нравится

2023-12-12 08:45 UTC, PhantornRU commented
Интерфейс красивый

2023-12-13 11:09 UTC, PiotrTheTchaikowsky commented
Карго апдейт из риал

2023-12-14 20:16 UTC, TrashDoxx commented
Ну, задумка неплохая на удивление. Правда вот нахуя нужно бессмысленное карго в игре, я за 2.5 года так и не понял. Самая чайная роль, на которой при этом играет какое-то быдло почти всегда.

2023-12-14 20:17 UTC, TrashDoxx commented
Пассивное накопление очков бы вырезать совсем.

2023-12-24 05:37 UTC, BeebBeebBoob requested changes
ПР4ВОСУД13 ПРО1СХОД1Т Д4Ж3 В КОД3 >:]

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/_globalvars/lists/misc.dm
> +GLOBAL_LIST_EMPTY(cargo_announcers)
добавьте коммент что это означает :)

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/controllers/subsystem/non-firing/cargo_quests.dm
> +	..()
```suggestion
/datum/quest_difficulty
	var/diff_flag
	var/weight
	var/min_quest_time = 0
	var/max_quest_time = 0

/datum/quest_difficulty/proc/generate_timer(datum/cargo_quests_storage/q_storage)
	q_storage.time_start = world.time
	q_storage.quest_check_timer = addtimer(CALLBACK(SScargo_quests, TYPE_PROC_REF(/datum/controller/subsystem/cargo_quests, remove_quest), q_storage.UID()), q_storage.quest_time, TIMER_STOPPABLE)
	q_storage.fast_check_timer = addtimer(VARSET_CALLBACK(q_storage, fast_failed, TRUE), 0.4 * q_storage.quest_time, TIMER_STOPPABLE)
	q_storage.quest_time = rand(min_quest_time, max_quest_time) MINUTES

/datum/quest_difficulty/easy
	diff_flag = QUEST_DIFFICULTY_EASY
	weight = 45
	min_quest_time = 15
	max_quest_time = 25

/datum/quest_difficulty/normal
	diff_flag = QUEST_DIFFICULTY_NORMAL
	weight = 35
	min_quest_time = 20
	max_quest_time = 30

/datum/quest_difficulty/hard
	diff_flag = QUEST_DIFFICULTY_HARD
	weight = 15
	min_quest_time = 30
	max_quest_time = 40

/datum/quest_difficulty/very_hard
	diff_flag = QUEST_DIFFICULTY_VERY_HARD
	weight = 5
	min_quest_time = 30
	max_quest_time = 60
```
Лучше убрать нули, которые я поставил для дефолта, дабы рантайм вызывался и лупил.

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/game/objects/items/devices/radio/headset.dm
> +	desc = "An cheap model of working modular intercom headset for a cargo, that fits over the head. Takes encryption keys. Don`t Protects ears from flashbangs and loud noises."
```suggestion
	desc = "A cheap model of working modular intercom headset for a cargo, that fits over the head. Takes encryption keys. Won't protect ears from flashbangs and loud noises."
```

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	content_mob = /mob/living/simple_animal/slime
О_о ЧЗХ
Ксенобиологи обосрались что пришлось заказать слайма???????????????

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/game/objects/structures/noticeboard.dm
>  /obj/structure/noticeboard
в этом коде неразумно прописано работа с бумагами. Не сужу автора, а тот кто до этого писал этот код. 
Пункт 71 и 82 там лучше уточнить что мы работаем именно с obj/item/paper
Благо 96 правильна

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/modules/economy/quests/_base_quests.dm
> +		reward *= 2
Мда....
Представь ебало тех у которых появляется квест, а потом кэп типа "КРАСНЫЙ", а вот бонус за код уже не будет.
Тут стоит пересмотреть этот фактор ;)

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/modules/economy/quests/_base_quests.dm
> +			description = replacetext(description, "\improper", "")
Точно ли что там игра не желает убирать это сам?

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/modules/economy/quests/_base_quests.dm
> +	var/datum/customer/customer
Sus
`var/datum/quest_customer/customer`

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/modules/economy/quests/_base_quests.dm
> +		reward = 1
Стрёмно что могут выйти float-числа из виду умножении на дробные. /shrug

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/modules/economy/quests/quest_console.dm
> +	data["moving"] = SSshuttle.supply.mode != SHUTTLE_IDLE
```suggestion
	data["quests"] += quest_storages
	data["moving"] = SSshuttle.supply.mode != SHUTTLE_IDLE
```

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/modules/economy/quests/quest_console.dm
> +
```suggestion
		idname = user.real_name
		idrank = isAI(user) ? "AI" : "Robot"

```
:) ??
Хотя там есть дроны и пИИ.... Но я не думаю что они будут способны

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/modules/economy/quests/quest_console.dm
> +	)
`./strings/quest_workers.json` может быть?...

2023-12-24 05:37 UTC, BeebBeebBoob commented on code/modules/hydroponics/grown/apple.dm
> +	name = "pack of a strange apple seeds"
Может так и было задумано, чтобы ботаники орали ибо посадили не те яблоки

2023-12-24 05:37 UTC, BeebBeebBoob commented on tgui/packages/tgui/interfaces/DestinationTagger.js
> +      case 2:
Волшебные цифры БЛЕХХ
Зовите DIM-911-ACH на суд!

2023-12-24 05:37 UTC, BeebBeebBoob commented on tgui/packages/tgui/interfaces/DestinationTagger.js
> +      title="TagMaster 3.0"
```suggestion
      title="TagMaster 4.0"
```
:)

2023-12-24 11:57 UTC, Rerik007 commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	content_mob = /mob/living/simple_animal/slime
Да, как я понимаю иногда это нужно. Хотя наверное будет очень редко, впрочем как и все заказы животных в карго.

2023-12-24 11:58 UTC, Rerik007 commented on code/game/objects/structures/noticeboard.dm
>  /obj/structure/noticeboard
Окей, я попробовал сделать это получше.

2023-12-24 11:58 UTC, Rerik007 commented on code/modules/economy/quests/_base_quests.dm
> +		reward *= 2
Насколько я знаю снижать код с гамм может лишь офицер ЦК, или что ты имеешь ввиду?

2023-12-24 11:59 UTC, Rerik007 commented on code/modules/economy/quests/_base_quests.dm
> +		reward = 1
Тогда сделал округление

2023-12-24 12:00 UTC, Rerik007 commented on code/modules/hydroponics/grown/apple.dm
> +	name = "pack of a strange apple seeds"
Хм, просто проблема в том что в квестах берётся стартовое имя, чтобы было понятно сделал так. Не думаю что это помешает, эти яблоки не делали на моей памяти.

2023-12-25 06:38 UTC, BeebBeebBoob commented on code/modules/economy/quests/_base_quests.dm
> +		reward *= 2
А бля. Я подумал что там >=
XDDDD

2023-12-25 06:40 UTC, BeebBeebBoob commented on code/modules/hydroponics/grown/apple.dm
> +	name = "pack of a strange apple seeds"
/shrug
Будем считать как скрытый бафф ботаникам

2023-12-25 06:52 UTC, BeebBeebBoob approved these changes
Я восхищён. Я может что нибудь мог упустить, но прошёлся по всему что было прописано 👍

2023-12-26 20:17 UTC, SuhEugene commented on tgui/packages/tgui/interfaces/DestinationTagger.js
> +      title="TagMaster 3.0"
Так то не 4.0, а 3.1 тогда уж, не?

2024-01-21 22:22 UTC, merged