ННКСС (Научно Наблюдательная Космическая Станция Синдиката) "Тайпан"
ss220-space/Paradise pull request #409
Opened 2021-10-21 04:55 UTC by Furukia

Синдибаза "Тайпан" и всё что было сделано с ней или для неё.

## What Does This PR Do

Добавлена локация ННКСС (Научно Наблюдательная Космическая Станция Синдиката) "Тайпан"

•	Спавнится в космосе ВСЕГДА, как и астероид синдиката из-за своих объёмов вместе с метеоритами занимает почти весь уровень, но всё ещё позволяет другим случайным объектам сравнится в космосе на одном с ней уровне как обычно. 

На станции 11 спаунов

•	Офицер Телекоммуникаций - По совместительству один из двух руководящих ролей. Его задача наблюдать за станцией НТ через телекамеры. Руководить станцией в случае любого рода боевой ситуации и охранять секретные документы синдиката в хранилище и оружейную. Он единственный имеет доступ к вышеназванным зонам и Телепортной.
•	Директор Исследований - Второй глава на станции. Его задача похожа на задачу стандартного директора исследований НТ. Следить чтобы учёные делали свою работу и не взорвали свою же станцию. Так же на его плечи ложится задача сделать, что-либо для синдиката, если они решат заказать у станции что-нибудь. Единственный обладает доступом к серверу, удобно расположенному прямо под его кабинетом.
•	5 Слотов для Учёных - Они обладают доступом в рнд, медбей, вирусологию, ботанику и в инженерию (Вдруг захотят поэкспериментировать с газами). Их задача это любого рода исследования био и химоружия, генов и так далее. Им нельзя строить ИИ! Им можно строить боргов только с разрешения администрации! Возможно, если того захочет народ, я пороюсь в коде и постараюсь создать версию робомозга и мми для боргов, которые не будут привязываться к консоли боргов НТ. Но пока так!
•	2 Слота для Грузчиков - Они обладают доступом в первую очередь к карго. Их работа покупка, одобрение/отказ и продажа товаров через телепады в карго. А также доставка этих товаров тем, кто их закажет. Их карго отличается от НТ, и торговля ведётся на "Чёрном рынке" за кредиты. Так же у них немного отличается список товаров, и некоторые товары являются "краденными", что значит ящики могут иметь замок с особым доступом. Нет, Синдикат не просит прощения за неудобства.
•	1 Слот для Повара - Он обладает доступом на кухню, в бар и в ботанику. Работает, так сказать, за троих. Но ничего не мешает ему попросить учёных, которые увлеклись ботаникой вырастить чего-нибудь и для него.
•	1 Слот для Атмос Инженера - Он, так сказать, совмещает в себе работу атмосферника и инженера. Обладает доступом в Инженерный. Его задача настроить стоящий в атмосе Термоэлектрогенератор и чинить станцию в случае любого рода поломок или неизбежных взрывов.

**Считается, что все работники станции обучены обращению с оружием!
Секретность и целостность этой станции является приоритетом для агентов станции. Это значит, что любого рода помощь агентам и особенно не агентам ставящая под угрозу вашу секретность запрещена без одобрения администрации!**

Для карго реализованы специальные синдипады и консоль для взаимодействия с чёрным рынком! Работают с помощью редспейса! Игнорируют любого рода блокировки телепортации! 

•	Стандартно синдипады телепортируют только посылки! Трупы и живые организмы они не станут телепортировать. Админ может изменить это поставив флаг allow_humans на TRUE у телепада отправляющего посылки.
•	Синдипады используют систему ID адресов и работают в одном из двух режимов (Получение посылок и их отправка)
•	Отвёртка откроет панель телепада, открытая панель позволяет настраивать их другими инструментами или разобрать их с помощью лома.
•	Настройка через кусачки приведёт к попытке привязать синдипад к консоли заказов
•	Настройка через мультитул переключит режим работы синдипада и попросит вас ввести ID для этого телепада или ID телепада "цели" для отправки посылок.
•	Если синдипад не привязан к консоли он работает через прямую активацию по клику на него. Иначе при попытке клика он потребует применять консоль для его активации
•	Синдипады состоят из следующих компонентов:
o	Плата Синдипада
o	1 Телекристалл
o	Конденсатор
o	Манипулятор
o	1 Кусок Кабеля
•	Синдипады могут быть улучшены стандартной заменой компонентов, что сократит время для их активации и их кулдаун, как личный, так и в консоли!

Консоль заказов.

•	В целом работает почти так же, как консоль в обычном карго. Но использует телепады вместо шатла и кредиты вместо очков. 
•	Для консоли был создан уникальный интерфейс (Все те файлы в папочке TGUI важны!) Если с ним возникнут проблемы пожалуйста сообщите мне.
•	Кредиты можно внести в консоль простым кликом по ней деньгами. Их так же можно снять с консоли с помощью специальной кнопки. У админов есть секретная кнопка для их добавления (или уменьшения если прописать там минус перед суммой). Кнопка добавлена дабы админы могли заплатить за заказанные ими товары у станции или просто поощрить за работу. 
•	Список товаров в консоли отличается наличием множества контрабанды и другими ценами за товары в кредитах вместо очков. Для справедливых цен мне необходимы отзывы игроков, поэтому все цены что вы видите там сейчас, подлежат возможным изменениям, как и сам список товаров.

Другие мелочи:

•	Для карго был создан специальный синдиящик, который нельзя взломать емагом и который не удаляется вместе с содержимым при телепорте, а отправляется прямо на телепад к админам на синдибазе в снегах. (Ах да, поставила там два телепада. Если, что передвинете их или ещё чего)
•	Для станции так же было реализовано несколько уникальных синдикатовских видов дверей. Они все прочнее своих нт аналогов на 50 единиц и делаются из пластитана. Но в связи с отсутствием многих зон, которые есть у нт, были реализованы аналоги не для всех дверей. Возможно, потом я заспрайчу и добавлю оставшиеся аналоги для любителей строить такие двери на обычной станции.
•	Были добавлены уникальные доступы для профессий на станции. А также все эти доступы были учтены и добавлены в карту админского офицера синдиката.
•	Немного был переделан код астероида синдиката. Если точнее, то код компьютера телепортера. Переделанный код был скопирован с официального парадайза, и он просто убирает ограничение, из-за которого компьютер не работал в других зонах, кроме зоны астероида.
•	Немного переделан код серверов рнд, для того чтобы создать возможность синдикату иметь независимую сеть в которой не видно серверов НТ, так же как НТ не видит сервера синдиката. Это всё ещё не мешает големам воровать уровни исследований у НТ и реализовано через простой флаг для проверок.
•	Спавнеры после появления игрока, заменяются на крио капсулу со скином синдиката.
•	Автомат "Синди Робо-ДеЛюкс!" стоящий около пыточной и содержащий детали для боргов и 2 синдикатских мми. 
•	Логотип синдиката в центре базы.
•      Уникальный Генерал Синди (Грифски с личностью) Умеет отличать синдикатовцев от прочих личностей. Делает он это смотря на две вещи. Фракцию "syndicate" встроенную в персонажа и на наличие карты агента. Если нет хотя бы одного из этого списка, он начинает бить. Об "арестах" он кричит в канал синдиката.

## Why It's Good For The Game

Желаемая игроками и прошедшая админское голосование гост роль станции синдиката. Уникальный контент которому (я надеюсь) обзавидуется оригинальный Paradise!

## Images of changes

ННКСС "Тайпан"

![syndiebase](https://user-images.githubusercontent.com/67807868/143624011-6193884c-2d03-4968-a976-70fa5b4a44a9.png)

2021-11-17 16:52 UTC, Vallat requested changes
Просмотреть все предложенные изменения, поменять многие названия переменных на более осмысленные (заменить всякие `k`, `j`, `m` на `iterator` или хотя бы `i`, расписать `amt` до `amount` и т.д., символы бесплатные). Пояснить многие моменты по типу непонятной логики и использования `:`

2021-11-17 16:52 UTC, Vallat commented on code/controllers/subsystem/nightshift.dm
> +		if(is_station_level(APC.z) || istype(APCAREA, /area/syndicate/unpowered/syndicate_space_base))
Правда ли это хорошая идея синхронизировать тип освещения (ночное/дневное) между синдистанцией и обычной? Не дать ли синдистанции по умолчанию дневной свет и пусть они сами переключают APCшки как хотят?

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +	reqform.info += "STAMP BELOW TO APPROVE THIS REQUISITION:<br>"
Вместо множественных += всё это можно внести в блок {" ... "}

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +	return reqform
Зачем нужно возвращать `reqform` если это никак не используется?

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +		Crate:req_access = list(text2num(object.access))
Для чего здесь двоеточие? Зачем игнорирование рантайм эррора? Убрать.

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +	var/atom/Crate = new object.containertype(_loc)
Название переменной должно быть с маленькой буквы

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +	slip.info +="CONTENTS:<br><ul>"
Вместо множественных += всё это можно внести в блок {" ... "}

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +	var/packagesAmt = data_storage.shoppinglist.len + ((errors & MANIFEST_ERROR_COUNT) ? rand(1,2) : 0) // пометка ошибки возможной
"Пометка ошибки возможной"? Недописанная фраза или смысл в том, что тут возможна ошибка в количестве содержимого поставки?

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +			for(var/j=1, j<=SO.num_contained, j++)
```suggestion
		if(length(object.contains))
			for(var/j in 1 to SO.num_contained)
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +			A:amount = object.amount
Запрещенный символ в виде двоеточия, убрать

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +	return Crate
Для чего возврат, если он не используется?

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +	for(var/obj/machinery/syndiepad/P in cargoarea)
Проходить по содержимому зоны - ужасно. В идеале постарайся придумать другой способ

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +		telepads_status = "Pads not linked!"
Максимально неправильно написанная проверка на то, пустые ли листы. Я несколько минут пытался понять, что это вообще и для какой цели существует
```suggestion
	if (length(receiving_pads) && length(linked_pads))
		telepads_status = "Pads ready"
	else
		to_chat(usr, "<span class='warning'>Synchronization failure! There's no pads in [cargoarea]!</span>")
		telepads_status = "Pads not linked!"
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +		return wait_time
А если не на кулдауне то вернёт что, null? А обработает ли код это?

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +		syndie_supply_packs["[SP.type]"] = SP
```suggestion
	for(var/typepath in subtypesof(/datum/syndie_supply_packs))
		var/datum/syndie_supply_packs/SP = typepath
		if(initial(SP.name) == "HEADER")		// To filter out group headers
			continue
		syndie_supply_packs["[typepath ]"] = new SP
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +	if(!data_storage.shoppinglist.len)
```suggestion
	if(!length(data_storage.shoppinglist))
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +		return 2
Зачем оно возвращает двойку?

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +		spawnTurfs += get_turf(recievingPads[j])
```suggestion
	for(var/j in 1 to length(recievingPads))
		spawnTurfs += get_turf(recievingPads[j])
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +			playsound(get_turf(recievingPads[i]), 'sound/weapons/emitter2.ogg', 25, 1, extrarange = 3, falloff = 5)
```suggestion
		for(var/i in 1 to length(recievingPads))
			recievingPads[i].use_power(10000 / recievingPads[i].power_efficiency)
			flick("sqpad-beam", recievingPads[i])
			playsound(get_turf(recievingPads[i]), 'sound/weapons/emitter2.ogg', 25, 1, extrarange = 3, falloff = 5)
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +	for(var/k = 1; k <= DSLP.len; k++)
```suggestion
	for(var/k in 1 to length(DSLP))
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +			if(istype(MA, /mob/dead) || istype(MA, /mob/living)) // Если окажется что на паде труп или человек, то это защитит его от уничтожения
`/mob/dead` это не труп, это обсервер.
`/mob/living` это не человек, это живое существо
Для проверки на то труп ли это есть переменная `stat` у всех живых мобов

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +					data_storage.sold_atoms += " [thing:name]"
Убрать двоеточие и из-за этого переписать логику всего этого цикла

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +									denied = 1
```suggestion
						var/slip_stamped_len = length(slip.stamped)
						if(slip_stamped_len) //yes, the clown stamp will work. clown is the highest authority on the station, it makes sense
							// Did they mark it as erroneous?
							var/denied = 0
							for(var/i in 1 to slip_stamped_len)
								if(slip.stamped[i] == /obj/item/stamp/denied)
									denied = 1
									break
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +						if(S.rarity == 0) // Mundane species
```suggestion
						if(!S.rarity) // Mundane species
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +		return ..()
```suggestion
/obj/machinery/computer/syndie_supplycomp/attackby(obj/item/I, mob/user, params)
	if(!powered())
		return 0
	if(istype(I, /obj/item/stack/spacecash))
		//consume the money
		var/obj/item/stack/spacecash/C = I
		playsound(loc, pick('sound/items/polaroid1.ogg', 'sound/items/polaroid2.ogg'), 50, TRUE)
		data_storage.cash += C.amount
		to_chat(user, "<span class='info'>You insert [C] into [src].</span>")
		var/mob/living/carbon/human/H = user
		var/name = H.get_authentification_name()
		data_storage.blackmarket_message += "<span class='good'>+[C.amount]</span>: [name] adds credits to the console.<br>"
		SStgui.update_uis(src)
		C.use(C.amount)
		return 1
	return ..()
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +			requests_list.Add(list(list("ordernum" = SO.ordernum, "supply_type" = SO.object.name, "orderedby" = SO.orderedby, "comment" = SO.comment, "command1" = list("confirmorder" = SO.ordernum), "command2
```suggestion
	for(var/datum/syndie_supply_order/SO as anything in data_storage.requestlist)
		if(!SO.comment)
			SO.comment = "No comment."
		requests_list += list(list("ordernum" = SO.ordernum, "supply_type" = SO.object.name, "orderedby" = SO.orderedby, "comment" = SO.comment, "command1" = list("confirmorder" = SO.ordernum), "command2" = list("rreq" = SO.ordernum)))
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +			orders_list.Add(list(list("ordernum" = SO.ordernum, "supply_type" = SO.object.name, "orderedby" = SO.orderedby, "comment" = SO.comment)))
```suggestion
	for(var/datum/syndie_supply_order/SO as anything in data_storage.shoppinglist)
		orders_list += list(list("ordernum" = SO.ordernum, "supply_type" = SO.object.name, "orderedby" = SO.orderedby, "comment" = SO.comment))
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +				if(data_storage == null)
```suggestion
				if(!data_storage)
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +				if(data_storage.linked_pads == list())
Проверка на лист или проверка на пустой лист? В чем логика данного действия? Исходя из комментария, должна быть проверка на то, не пустой ли лист
```suggestion
				if(length(data_storage.linked_pads))
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +					data_storage.is_cooldown = TRUE
```suggestion
				for(var/i in 1 tp length(DSLP))
					DSLP[i].checks(usr)
				data_storage.last_teleport = world.time
				data_storage.is_cooldown = TRUE
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +			for(var/i = 1; i <= amount; i++)
```suggestion
			for(var/i in 1 to amount)
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +			for(var/i=1, i<=data_storage.requestlist.len, i++)
```suggestion
			for(var/i in 1 to length(data_storage.requestlist))
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +			for(var/i=1, i<=data_storage.requestlist.len, i++)
```suggestion
			for(var/i in 1 to length(data_storage.requestlist))
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +					withdraw_cash(round(cash_sum), usr)
```suggestion
			if(cash_sum <= 0 || (!is_public && !is_authorized(usr)) || ..()))
				return
			withdraw_cash(round(cash_sum), usr)
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +		return
Бесполезные проверки, такая ситуация не возникнет

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/portable_turret.dm
> +
```suggestion
	if(faction == "syndicate" && istype(L.get_id_card(), /obj/item/card/id/syndicate)
		return TURRET_NOT_TARGET

```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/syndiepad.dm
> +	RefreshParts()
```suggestion
/obj/machinery/syndiepad/Initialize()
	..()
	component_parts = list()
	component_parts += new /obj/item/circuitboard/quantumpad/syndiepad(null)
	component_parts += new /obj/item/stack/telecrystal(null)
	component_parts += new /obj/item/stock_parts/capacitor(null)
	component_parts += new /obj/item/stock_parts/manipulator(null)
	component_parts += new /obj/item/stack/cable_coil(null, 1)

	RefreshParts()
	return INITIALIZE_HINT_LATELOAD

/obj/machinery/syndiepad/LateInitialize()
	pad_sync()
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/syndiepad.dm
> +			break
```suggestion
		var/obj/effect/abstract/syndie_data_storage/S = locate() in myArea
		S?.sync()
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/syndiepad.dm
> +					break
```suggestion
		if(console_link)
			if(alert("Отвязать телепад от консоли?",, "Да", "Нет") == "Нет")
				return
			console_link = FALSE
			var/obj/effect/abstract/syndie_data_storage/S = locate() in myArea
			S?.sync()
		else if(!console_link)
			if(alert("Привязать телепад к консоли?",, "Да", "Нет") == "Нет")
				return
			console_link = TRUE
			var/obj/effect/abstract/syndie_data_storage/S = locate() in myArea
			S?.sync()
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/syndiepad.dm
> +		return
```suggestion
	receive = !receive 
	if(receive)
		to_chat(user, "<span class='notice'>Включен режим получения посылок.</span>")
		var/new_id = input("Задайте ID этому телепаду для получения им посылок")
		if(new_id)
			id = new_id
		linked_pad = null
		target_id = null
	else
		to_chat(user, "<span class='notice'>Включен режим отправки посылок.</span>")
		var/new_target_id = input("Задайте ID телепада на который будут приходить посылки.")
		if(new_target_id && new_target_id != id)
			target_id = new_target_id
		linked_pad = null
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/syndiepad.dm
> +				break
```suggestion
	for(var/obj/machinery/syndiepad/S in GLOB.machines)
		if(S.console_link) //Мы не хотим привязываться к другим привязанным к консоли телепадам
			continue
		if(!S.id)
			continue
		if(S == src)
			continue
		if(S.id == target_id)
			linked_pad = S
			break
```

2021-11-17 16:52 UTC, Vallat commented on code/game/machinery/syndiepad.dm
> +					to_chat(user, "<span class='warning'>Error: '[ROI]' was not teleported! You cannot teleport dead bodies! It's gross!</span>")
Действительно ли мы хотим говорить что мы не смогли телепортировать **призрака**?

2021-11-17 16:52 UTC, Vallat commented on code/game/objects/effects/decals/syndie_logo_decals.dm
> +	icon_state = "logo19"
**КОД ЭТО НЕ БАЗА ДАННЫХ**!!! Удалить всё к чертям, оставить только `/obj/effect/decal/syndie_logo` и РАССТАВЛЯТЬ НА КАРТЕ ЧЕРЕЗ ИНСТАНСЫ ОБЪЕКТА

2021-11-17 16:52 UTC, Vallat commented on code/game/objects/items/robot/robot_parts.dm
> +			if(M.syndicate == 1)
```suggestion
			if(M.syndicate)
```

2021-11-17 16:52 UTC, Vallat commented on code/game/objects/items/robot/robot_parts.dm
> +			forced_ai = null
Не нужно

2021-11-17 16:52 UTC, Vallat commented on code/game/objects/items/stacks/sheets/mineral.dm
> +	))
Давать возможность создавать синдидвери **всем** - плохая идея

2021-11-17 16:52 UTC, Vallat commented on code/game/objects/structures/crates_lockers/crates.dm
> +	if(locked == 1 && broken == 0)
```suggestion
	if(locked && !broken)
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/silicon/robot/robot.dm
> +	if(mmi != null && mmi.syndicate == 1)
```suggestion
	if(mmi?.syndicate)
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/silicon/robot/robot.dm
> +			qdel(src)
Weird flex but okay
```suggestion
		if("Syndicate Saboteur")
			spawn_syndicate_borgs(src, "Saboteur", get_turf(src))
			qdel(src)
			return

		if("Syndicate Medical")
			spawn_syndicate_borgs(src, "Medical", get_turf(src))
			qdel(src)
			return

		if("Syndicate Bloodhound")
			spawn_syndicate_borgs(src, "Bloodhound", get_turf(src))
			qdel(src)
			return
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +	spawn(2)
Бесполезно без выделения области видимости под spawn() отдельным отступом, смысл не ясен. Удалить

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +				threatlevel = 0
```suggestion
		if(idcheck && istype(C.get_id_card(), /obj/item/card/id/syndicate))
			threatlevel = 0
		else if(!("syndicate" in C.faction))
			threatlevel = 20
		else
			threatlevel = C.assess_threat(src)
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +		regenerate_icons()
Зачем?

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +		return
```suggestion
	if(!force && act == "hiss" && handle_emote_CD())
		return
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +				custom_emote(1, "hisses angrily!")
```suggestion
	if(!M || stat)
		return
	if(change > 0)
		new /obj/effect/temp_visual/heart(loc)
		custom_emote(1, "hisses happily!")
	else
		custom_emote(1, "hisses angrily!")
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +	set_light(0)
Зачем?

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +	if(inventory_head && inventory_head.snake_fashion)
```suggestion
	if(inventory_head?.snake_fashion)
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +		if(health <= 0 || src.rest) //труп или отдыхает
```suggestion
		if(stat || src.rest) //без сознания или отдыхает
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +			if(health <= 0)
```suggestion
			if(stat)
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/ruins/syndicate_space_base.dm
> +		var/new_gender = input("Please select gender.") in list("Male","Female")
```suggestion
		var/new_gender = alert("Please select gender.",, "Male","Female")
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/ruins/syndicate_space_base.dm
> +		var/new_name = input("Enter your name:")
```suggestion
		var/new_name = input("Enter your name:") as text
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/ruins/syndicate_space_base.dm
> +		mob_name = new_name
```suggestion
		if(new_name)
			mob_name = new_name
```

2021-11-17 16:52 UTC, Vallat commented on code/modules/ruins/syndicate_space_base.dm
> +				H.equip_to_slot(I, slot_wear_id) // По непонятной мне причине другие методы считают что персонаж не может надеть предметы. Поэтому надеваем насильно!
Weird flex but okay

2021-11-17 17:32 UTC, Furukia commented on code/game/machinery/syndiepad.dm
> +				break
На 146-ой строчке стоит оставить проверку и на себя тоже. Ибо иначе с админского непривязанного к консоли телепада нельзя будет послать посылку в карго 
`if(src.console_link && S.console_link)` 
Важно чтобы он не привязывался к другим привязанным телепадам, только если он сам привязан.

2021-11-17 18:00 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +	var/packagesAmt = data_storage.shoppinglist.len + ((errors & MANIFEST_ERROR_COUNT) ? rand(1,2) : 0) // пометка ошибки возможной
Это я писала себе заметки когда искала причину бага. Забыла убрать эту заметку.

2021-11-17 19:19 UTC, Furukia commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +	set_light(0)
Зачем эмоции? Или зачем` set_light(0)`? Эмоции потому что надо! `set_light` потому что в оригинальном коде для корги, у корги есть риги и когда он их напяливает он начинает светиться, появляется бездыханность(ген) и защита от давления. А тут код это всё сбрасывает. У змеи конечно нет ригов. Эти куски кода в целом можно закомментировать пока змейке ещё и риг или что то подобное не подвезут. Пусть останутся на всякий.

2021-11-18 06:43 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +	reqform.info += "STAMP BELOW TO APPROVE THIS REQUISITION:<br>"
Сделано

2021-11-18 06:44 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +	return reqform
return убран

2021-11-18 06:46 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +		Crate:req_access = list(text2num(object.access))
Это и другие двоеточия как оказалось были важны и были скопированы с оригинального карго. Мне пришлось выкручиваться когда я их убирала. Не знаю нормален ли метод который я применила для этого или нет. Но теперь там нет двоеточий и вроде всё работает без рантаймов и ошибок.

2021-11-18 06:46 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +	var/atom/Crate = new object.containertype(_loc)
Сделано

2021-11-18 06:46 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +	slip.info +="CONTENTS:<br><ul>"
Сделано

2021-11-18 06:47 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +	var/packagesAmt = data_storage.shoppinglist.len + ((errors & MANIFEST_ERROR_COUNT) ? rand(1,2) : 0) // пометка ошибки возможной
Заметка убрана дабы не смущать людей больше

2021-11-18 06:47 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +	return Crate
Убран

2021-11-18 06:48 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +	for(var/obj/machinery/syndiepad/P in cargoarea)
Пока не сообразила метода получше...

2021-11-18 06:50 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +		return wait_time
Этот код вроде как в принципе не вызывается если мы не на кулдауне. Хотя я после целой ночи кодинга могу немного тупить. Позже перепроверю что да как тут

2021-11-18 06:51 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +		return 2
Хер знает. Оно вроде и в обычном карго возвращало двойку. А я и не приметила. Убрала двойку

2021-11-18 06:52 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +			if(istype(MA, /mob/dead) || istype(MA, /mob/living)) // Если окажется что на паде труп или человек, то это защитит его от уничтожения
Проверка stat у атома MA как оказалось дело тоже болезненное и пришлось искать пути как это сделать без всяких двоеточий. Вроде нашла.

2021-11-18 06:53 UTC, Furukia commented on code/game/machinery/computer/syndie_cargo.dm
> +		return
Убрано

2021-11-18 06:53 UTC, Furukia commented on code/game/machinery/syndiepad.dm
> +					to_chat(user, "<span class='warning'>Error: '[ROI]' was not teleported! You cannot teleport dead bodies! It's gross!</span>")
Убрано

2021-11-18 06:54 UTC, Furukia commented on code/game/objects/effects/decals/syndie_logo_decals.dm
> +	icon_state = "logo19"
Кхе кхе. Понято, принято, поправлено до 6 строчек. Сделано в карте через инстансы.

2021-11-18 06:54 UTC, Furukia commented on code/game/objects/items/robot/robot_parts.dm
> +			forced_ai = null
Убрано

2021-11-18 06:57 UTC, Furukia commented on code/game/objects/items/stacks/sheets/mineral.dm
> +	))
Я считаю иначе. Эти двери прочнее всего на 50 единиц и для создания требуют пластитан, а не простой металл. Больше косметики для любителей строить штуки на обычной станции это не так уж и плохо учитывая, что двери в целом вообще никак кроме немного повышенной прочности на баланс и подобное не влияют. Это всё таки двери, а не какие-нибудь пушки.

2021-11-18 06:59 UTC, Furukia commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +	spawn(2)
spawn(2) это копипаст с обычного грифски. Вроде он и при удалении этой строчки прекрасно работает. Так что я удалила её у своей версии, но обычного не трогала.

2021-11-18 06:59 UTC, Furukia commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +		regenerate_icons()
Остаток с того бага с летающими шляпами, не заметила и не удалила. Теперь удалено.

2021-11-18 07:01 UTC, Furukia commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +	set_light(0)
`set_light(0)` и ещё пару строчек снизу были закомменчены поскольку пока не нужны, но я их оставила на всякий. Никогда не знаешь когда синдизмее подвезут риг или аналог.

2021-11-18 07:01 UTC, Furukia commented on code/modules/ruins/syndicate_space_base.dm
> +				H.equip_to_slot(I, slot_wear_id) // По непонятной мне причине другие методы считают что персонаж не может надеть предметы. Поэтому надеваем насильно!
¯\_(ツ)_/¯

2021-11-18 07:06 UTC, Furukia commented on code/controllers/subsystem/nightshift.dm
> +		if(is_station_level(APC.z) || istype(APCAREA, /area/syndicate/unpowered/syndicate_space_base))
Это очень важно для уюта и атмосферы. Всё таки это локация на которой свой экипаж играет свою смену. А ходить и тыкать каждую апк запарно. Делать какую-нибудь кнопку для переключения всех апк на синдистанции в ночной режим, тоже такое себе. Хотя в начале у меня была такая идея... Но простая синхронизация ночного режима это как по мне лучшее решение.

2021-12-04 08:11 UTC, Vallat requested changes

2021-12-04 08:11 UTC, Vallat commented on code/__HELPERS/mobs.dm
> +			break
```suggestion
/proc/get_mob_in_atom_without_warning(atom/A)
	if(!istype(A))
		return null
	if(ismob(A))
		return A

	return locate(/mob) in A
```

2021-12-04 08:11 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +		return wait_time
Всё еще актуален вопрос по поводу того, что при вызове функции нет возврата конкретного значения по умолчанию

2021-12-04 08:11 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +				data_storage.blackmarket_message += "<span class='bad'>[money2add]</span>: Don't anger us anymore! You won't be able to get away with such a little tax again.<br>"
Очень странный код. А если я добавлю -999999999? Должны ли быть какие-то рамки инпута и если да, то почему их нет?

2021-12-04 08:11 UTC, Vallat commented on code/game/objects/objs.dm
> +			break
```suggestion
/proc/get_obj_in_atom_without_warning(atom/A)
	if(!istype(A))
		return null
	if(isobj(A))
		return A

	return locate(/obj) in A
```

2021-12-04 08:11 UTC, Vallat commented on code/modules/mob/living/simple_animal/friendly/snake.dm
> +	return armorval * 0.5
```suggestion
/mob/living/simple_animal/hostile/retaliate/poison/snake/rouge/getarmor(def_zone, type)
	var/armorval = inventory_head?.armor.getRating(type)
	if(!def_zone)
		armorval *= 0.5
	else if(def_zone != "head")
		armorval = 0
	return armorval 
```

2021-12-04 18:24 UTC, Vallat requested changes

2021-12-04 18:24 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +		return QDEL_HINT_LETMELIVE
Так намного лучше
```suggestion
/datum/syndie_data_storage/Destroy(force)
	if(!force)
		return QDEL_HINT_LETMELIVE
	GLOB.data_storages -= src
	linked_pads = null
	receiving_pads = null
	shoppinglist = null
	syndie_supply_packs = null
	discoveredPlants = null
	techLevels = null
	researchDesigns = null
	return ..()
```

2021-12-04 18:24 UTC, Vallat commented on code/game/machinery/syndiepad.dm
> +			continue
```suggestion
	var/area/src_area = get_area(src)
	for(var/obj/machinery/computer/syndie_supplycomp/SC in GLOB.syndie_cargo_consoles)
		if(get_area(SC) != src_area)
			continue
```

2021-12-04 18:30 UTC, Vallat approved these changes

2022-01-07 06:02 UTC, BeebBeebBoob commented
![image](https://user-images.githubusercontent.com/32985153/148499370-818fd9e0-bfd7-4f4c-906f-923eae3e0e9f.png)
Прям по непонятной причине тут бьёт током если идти на стенку.

2022-01-07 06:31 UTC, Den109G commented
Это из-за фулл-тайл окон. Почему-то, игра не думает что они есть, и просто бьёт, из-за решётки под напряжением.

2022-01-07 08:05 UTC, Den109G commented
Дополню сообщение выше.
![image](https://user-images.githubusercontent.com/87372121/148512001-e396d514-c1d0-48dc-8c6e-256d8a7d8214.png)
И тут в ботанике бьёшься током. Предположу, что проблема не в карте, а в окнах.

2022-01-07 17:55 UTC, BeebBeebBoob commented
![image](https://user-images.githubusercontent.com/32985153/148586034-34fcc11f-2701-4693-a86f-786c72661c2f.png)
Уже пошли мемы про синдибазу и их приколов. Кстати вирусология как я понял никому не доступна! Даже учёным а это.. обидно и плохо.

2022-01-08 05:00 UTC, carlsmei commented
**Баг**

Хочешь поднять кредитов в карго? Тебе нужны хотя бы 3000 чёртовых кредитов. Ладно, ближе к сути, чтобы получать большое количество **ДЕНЯК**, можно просто покупать ящик плазмы и, надо же, отправлять обратно. Профит неплохой выходит.

![изображение](https://user-images.githubusercontent.com/47307437/148632169-a9cc74b9-28b5-4ad4-8c91-33332dcffe6a.png)

2022-01-08 05:52 UTC, carlsmei commented
В добавок к верхнему сообщению от меня

Деньги также можно получать через, КАЗАЛОСЬ БЫ, сервисного борга, у которого есть возможность печатать 10 кредитов буквально из жопы.

Так выглядит майнинг-станция по добыче кредитов
![изображение](https://goose.durka.xyz/f/cc2c8717-a23b-4b1c-99d8-844ca8c03cbc.png)

![изображение](https://user-images.githubusercontent.com/47307437/148633275-7c12246e-4e6d-43cc-9628-9c7fa5529d7e.png)

2022-01-08 05:57 UTC, BeebBeebBoob commented
> Деньги также можно получать через, КАЗАЛОСЬ БЫ, сервисного борга, у которого есть возможность печатать 10 кредитов буквально из жопы.
Это вообще пойдёт под другой ПР и это будет БОЛЬШОЙ ПР ибо это надо целую экономику менять. На самом парадизе экономика просто смешно. Часть либо бесплатное часть платное. У нас полу-коммунизм так сказать. На самом оффе в гитхаб тупо говорят что система экономики самый старый код и самый ужасный.

2022-01-08 06:19 UTC, BeebBeebBoob commented
https://github.com/ss220-space/Paradise/blob/d93505df67673cb69fc8c311743a8cd2bf38607e/code/datums/syndiesupplypacks.dm#L1302-L1307

тут лучше тогда поменять на 30000 ибо плазма штука стоит 500 и просто выходит что ящик стоит 6 плазмы.

2022-01-08 13:08 UTC, AugustBebel commented
ТГ придэ, порядок наведэ. Фиксить парадизы на лету это сизифов труд.

2022-01-08 15:47 UTC, Furukia commented
> **Баг**
> 
> Хочешь поднять кредитов в карго? Тебе нужны хотя бы 3000 чёртовых кредитов. Ладно, ближе к сути, чтобы получать большое количество **ДЕНЯК**, можно просто покупать ящик плазмы и, надо же, отправлять обратно. Профит неплохой выходит.
> 
> ![изображение](https://user-images.githubusercontent.com/47307437/148632169-a9cc74b9-28b5-4ad4-8c91-33332dcffe6a.png)

Ля. Я же вроде специально смотрела чтобы этого не случилось. Как же я так в расчётах ошиблась...
![7221-menhera-embarassed](https://user-images.githubusercontent.com/67807868/148650598-8fbaddea-3074-4b0b-a50c-00809cd46430.png)

2022-01-11 19:02 UTC, Den109G commented
Повар всё ещё спавниться с прошлым наушником. Немного неприятно, но не критично.

2022-01-13 07:15 UTC, PunishedHideo commented
Что-то на чёрном рынке оружие никакое не продаётся, кредиты не дают, странный какой то чёрный рынок...
Функция продажи оружия там вообще есть?

2022-01-13 08:06 UTC, Den109G commented
Нету функции продажи оружия, как и у обычного карго.
![image](https://user-images.githubusercontent.com/87372121/149290084-99bce629-0363-406c-96d6-21b3ec39c7be.png)
![image](https://user-images.githubusercontent.com/87372121/149290182-a5bd11cf-60b6-4e05-91e9-b3248ba7aa9e.png)
Карго синди принимает только: плазму, секретные документы НТ, технологии, семена растений, дизайны, манифесты от заказов и ящики.

2022-01-20 08:55 UTC, Den109G commented
Думаю стоит поменять ПДА у РД и Офицера. Точнее - убрать картридж.
Сейчас и так много грифозных вещей можно сделать на Тайпане, даже взорвать ПДА почти раундстартом. Это не очень классно, как по мне. Начинается раунд, а ты уже без ноги и уже стоит Красный Код.
Само предложение -
Добавить в `pdas.dm` эти строчки:
```
/obj/item/pda/syndicate/(nobomb, к примеру)
	default_cartridge = null
```
Или
```
/obj/item/pda/taipan
	name = "Secret PDA"
	icon_state = "pda-syndi"
	owner = "Дядя Петя"
	
obj/item/pda/taipan/New()
	..()
	var/datum/data/pda/app/messenger/M = find_program(/datum/data/pda/app/messenger)
	if(M)
		M.m_hidden = 1
```

2022-02-17 07:47 UTC, Den109G commented
Предложение по фиксу РнД Тайпана -
Добавить в rdconsole.dm в эти строки
```
...
	if(is_taipan(z))
		syndicate = 1
		req_access = list(ACCESS_SYNDICATE_SCIENTIST)
...
```
Значение, что у сервера Тайпана (23 или 0027). То есть вот так должен выглядеть код, что подключит консоль к серверу Тайпана:
```
if(is_taipan(z))
		syndicate = 1
		req_access = list(ACCESS_SYNDICATE_SCIENTIST)
		id = 23
```

Если нужно чтобы Тайпан мог скачивать данные НТ - Нужно добавить в лист ID серверов 1 (консоль РнД НТ)
![image](https://user-images.githubusercontent.com/87372121/154429198-b25522b6-c09d-44f4-9d82-932b3838e979.png)
(0027 превращается в игре в 23, так что маленькие изменения)

2022-04-01 23:26 UTC, merged