add: new sprites for reinforcing explorer suits
ss220-space/Paradise pull request #4093
Opened 2023-12-20 18:31 UTC by NightDawnFox

## Описание
Добавляет шахтерским ЕВА-костюмам спрайты для каждого этапа улучшения, как это сделано для шахтерских хардсъютов. Аналогично добавляет их шлему плазматика-шахтера

## Ссылка на предложение/Причина создания ПР
QoL, вроде..

## Демонстрация изменений
![image](https://github.com/ss220-space/Paradise/assets/116907157/0a119f9c-748b-4620-81e1-fcd635c2fd52)
![image](https://github.com/ss220-space/Paradise/assets/116907157/f880022a-b1cd-409d-a23b-cb404536aae7)
![image](https://github.com/ss220-space/Paradise/assets/116907157/1a0c30e5-5fbb-47d1-90f0-3b7b91d18da8)

2023-12-20 19:51 UTC, FanTik-Ratge commented
в стиле парадиза 👍

2023-12-20 21:35 UTC, Daeberdir requested changes
### ЗЮЗЯ АЛЯРМ 
![cat-cats](https://github.com/ss220-space/Paradise/assets/115735095/d223d3fd-6da9-496a-9ce9-489e4248e1d8)

2023-12-20 21:35 UTC, Daeberdir commented on code/modules/mining/equipment/explorer_gear.dm
> +	nohood_state = "explorer"
Под нож.

2023-12-20 21:35 UTC, Daeberdir commented on code/modules/mining/equipment/explorer_gear.dm
> +		icon_state = "[nohood_state]"
Вот эту всю хрень под нож.

2023-12-20 21:35 UTC, Daeberdir commented on code/modules/clothing/suits/hood.dm
> +				icon_state = "[nohood_state]_hood"
```suggestion
				icon_state = "[item_color]_hood"
```

2023-12-20 21:35 UTC, Daeberdir commented on code/modules/clothing/suits/hood.dm
> +	icon_state = nohood_state
```suggestion
	icon_state = item_color
```

2023-12-20 21:35 UTC, Daeberdir commented on code/modules/clothing/suits/hood.dm
> +	nohood_state = initial(icon_state)
```suggestion
	item_color = initial(icon_state)
```

2023-12-20 21:35 UTC, Daeberdir commented on code/modules/clothing/suits/hood.dm
> +	var/nohood_state
Вы-ре-за-ем.

2023-12-20 21:35 UTC, Daeberdir commented on code/game/objects/items/stacks/sheets/leather.dm
> +
Вот это всё .... просто убирай в ноль.

2023-12-20 21:35 UTC, Daeberdir commented on code/game/objects/items/stacks/sheets/leather.dm
> +
А потом заменяй на:
````
			if(is_type_in_typecache(target, goliath_platable_armor_with_icon_typecache))
				switch(C.armor.getRating("melee"))
					if(40, 50)
						C.icon_state = "[initial(C.icon_state)]_reinf"
						C.item_color = "[initial(C.icon_state)]_reinf"
					if(60)
						C.icon_state = "[initial(C.icon_state)]_reinf_full"
						C.item_color = "[initial(C.icon_state)]_reinf_full"
````

2023-12-21 13:30 UTC, NightDawnFox commented on code/game/objects/items/stacks/sheets/leather.dm
> +
хорошо, мам..

2023-12-24 04:14 UTC, merged