add: New vampire's sucking animation
ss220-space/Paradise pull request #4098
Opened 2023-12-21 05:54 UTC by LiquidPotroh

## Описание
Новая анимация сосания для вампира

## Ссылка на предложение/Причина создания ПР
Где то там в процессе

## Демонстрация изменений
Да че такой мелкий размер файлов, гитхаб? Впрочем всё равно не прошло пока что

2023-12-24 04:26 UTC, BeebBeebBoob requested changes
Sanitize

2023-12-24 04:26 UTC, BeebBeebBoob commented on code/modules/antagonists/vampire/vampire_datum.dm
```suggestion
#define GRAB_NECK_TIME_MOD 0.3
#define STATE_CLOSING_IN 1
#define STATE_GRABBING 2
#define STATE_SUCKING 3

```

2023-12-24 04:26 UTC, BeebBeebBoob commented on code/modules/antagonists/vampire/vampire_datum.dm
> +			if(1)
```suggestion
			if(STATE_CLOSING_IN)
```

2023-12-24 04:26 UTC, BeebBeebBoob commented on code/modules/antagonists/vampire/vampire_datum.dm
> +			if(2)
```suggestion
			if(STATE_GRABBING)
```

2023-12-24 04:26 UTC, BeebBeebBoob commented on code/modules/antagonists/vampire/vampire_datum.dm
> +			if(3)
```suggestion
			if(STATE_SUCKING)
```

2023-12-24 04:26 UTC, BeebBeebBoob commented on code/modules/antagonists/vampire/vampire_datum.dm
> +#undef GRAB_NECK_TIME_MOD
```suggestion
#undef GRAB_NECK_TIME_MOD
#undef STATE_CLOSING_IN
#undef STATE_GRABBING
#undef STATE_SUCKING
```

2024-01-02 21:13 UTC, LiquidPotroh commented
@Dimach прошло если что

2024-01-10 10:17 UTC, merged