Happy new year mf
ss220-space/Paradise pull request #4130
Opened 2023-12-25 23:32 UTC by ArtemDerp

## Описание

## Ссылка на предложение/Причина создания ПР

## Демонстрация изменений

![image](https://github.com/ss220-space/Paradise/assets/87157426/17edf4a7-d4b9-45a7-9312-0057107cd855)

2023-12-26 15:37 UTC, SAADf603 requested changes
Все гейты отключить на время празднования. Критических замечаний по коду нет. Цифорки баланса поправить быстро, тем более, что некоторые уже стали слабее изначальной задумки.

2023-12-26 15:37 UTC, SAADf603 commented on code/modules/awaymissions/zlevel.dm
> +			var/zlev = GLOB.space_manager.add_new_zlevel(AWAY_MISSION, linkage = UNAFFECTED, traits = list(AWAY_LEVEL,BLOCK_TELEPORT, HAS_WEATHER))
:face_with_raised_eyebrow:

2023-12-26 15:37 UTC, SAADf603 commented on code/modules/mob/living/simple_animal/hostile/rat.dm
> +	attacktext = "кромсает"
ну как бы....

2023-12-26 15:37 UTC, SAADf603 commented on config/example/away_mission_config.txt
> -#!!IMPORTANT NOTES FOR HOSTING AWAY MISSIONS!!:
:nerd:

2023-12-26 15:37 UTC, SAADf603 commented on config/example/away_mission_config.txt
> +#_maps/map_files/RandomZLevels/undergroundoutpost45.dmm
Предлагаю отключить ВСЕ гейты кроме злого санты на время праздника
Скорее даже настаиваю на этом

2023-12-26 16:04 UTC, Etrnlmelancholy commented
no you are mf 

happy new year tho

2023-12-26 16:17 UTC, Vladisvell commented on config/example/away_mission_config.txt
> +#_maps/map_files/RandomZLevels/undergroundoutpost45.dmm
Сделать принудительную генерацию гейта можно будет после мержа https://github.com/ss220-space/Paradise/pull/4116 или попросив Азиза поменять конфигурацию на время.
Не одобряю изменение конфига, это не нужно.

2023-12-26 16:17 UTC, Vladisvell commented on config/example/away_mission_config.txt
> -#!!IMPORTANT NOTES FOR HOSTING AWAY MISSIONS!!:
Не одобряю изменение конфига, см https://github.com/ss220-space/Paradise/pull/4130#discussion_r1436525000

2023-12-26 16:19 UTC, Vladisvell commented on code/modules/vehicle/gigadrill.dm
> +#define DRILL_TIME 2
????

2023-12-26 16:22 UTC, Vladisvell commented on code/modules/awaymissions/mission_code/evil_santa.dm
> +				P.open()
Судя по коду, раз в три секунды будет открываться одна дверь.
Это нормально?

2023-12-26 17:40 UTC, BeebBeebBoob commented on code/modules/mob/living/simple_animal/hostile/rat.dm
> +	layer = 3.1
У нас в коде есть дефайны лееров. Просьба назначить корректную

2023-12-26 17:40 UTC, BeebBeebBoob commented on config/example/away_mission_config.txt
> +#_maps/map_files/RandomZLevels/undergroundoutpost45.dmm
Солидарен. Ревертни изменение конфигов. Проси Азиза

2023-12-28 19:21 UTC, Vladisvell reviewed
До мержа https://github.com/ss220-space/Paradise/pull/4132 не мёржить.
После мержа и исправления нижеуказанных комментариев провести ребейз

2023-12-28 19:21 UTC, Vladisvell commented on code/game/area/vision_reset_areas.dm
> +	return ..()
убрать после мержа https://github.com/ss220-space/Paradise/pull/4132

2023-12-28 19:21 UTC, Vladisvell commented on code/game/atoms_movable.dm
убрать тут изменения, решено в https://github.com/ss220-space/Paradise/pull/4132

2023-12-28 19:21 UTC, Vladisvell commented on code/modules/awaymissions/gateway.dm
убрать тут изменения после мержа https://github.com/ss220-space/Paradise/pull/4132

2023-12-28 19:21 UTC, Vladisvell commented on code/modules/awaymissions/mission_code/evil_santa.dm
после мержа https://github.com/ss220-space/Paradise/pull/4132 и удаления вышеуказанных изменений провести Rebase ветки для того чтобы этот код работал

2023-12-28 19:21 UTC, Vladisvell commented on code/modules/awaymissions/zlevel.dm
> +			var/zlev = GLOB.space_manager.add_new_zlevel(AWAY_MISSION, linkage = UNAFFECTED, traits = list(AWAY_LEVEL,BLOCK_TELEPORT, HAS_WEATHER))
тут я тоже не понял, на все гейты будет прокать погода или погда будет прокать и её эффекта не будет если нет зоны?

2023-12-28 19:21 UTC, Vladisvell commented on code/modules/projectiles/projectile/special.dm
>  	return 1
а это зачем?

2023-12-28 21:34 UTC, aeternaclose approved these changes
**_Отсмотрел, потестил. Всё в поряде._**

2023-12-31 06:43 UTC, merged