add: makeshift MOD-revolver.
ss220-space/Paradise pull request #4131
Opened 2023-12-26 02:31 UTC by Daeberdir

## Описание
- Добавляет новый тип самодельных патронов для револьвера - "Фосфорные пули". Крафт аналогичный уже имеющемуся револьверному патрону, но с добавлением пяти юнитов фосфора. При попадании куда либо, пуля создаёт искры и слабую вспышку, не имеющую дебафов.
- Добавляет два новых предмета: "Самодельное револьверное дуло"; "Стальное револьверное дуло". Самодельная версия появляется только при создании самодельного револьвера, при применении для стрельбы из револьвера теперь имеет 20% на осечку. Стальная версия появляется только в техах с весом 2, не имеет шансов на осечку при стрельбе из револьвера.
- Делает самодельный револьверный барабан "доступным для щупанья" и добавляет стальную версию. Самодельный барабан может быть напечатан во взломанном автолате за 6к металла. Стальная версия вмещает 6 патронов + имеет возможность вмещать .38 калибр, помимо самодельных пулек. Стальной барабан спавнится на Дельте в сейфе в заброшенной детективской.
- Самодельный револьвер теперь собирается раскрученным и без своего барабана. Пока револьвер раскручен, с него можно кликом пустой руки снимать детали (барабан и дуло) и устанавливать новые кликом этими самыми деталями о револьверу. Револьвер можно скрутить и раскрутить отвёрткой после прогрессбара в 8 секунд (крутые отвёртки быстрее), если все детали у револьвера присутствуют.
- Обновляет спрайты самодельного револьверного спидлоадера и самодельного револьвера. Переводит их на систему оверлеев.

## Ссылки на предложения
https://discord.com/channels/617003227182792704/755125334097133628/1178738864941187134
https://discord.com/channels/617003227182792704/755125334097133628/1178738907492401224

## Демонстрация изменений

https://github.com/ss220-space/Paradise/assets/115735095/38556fc0-2902-4bd3-a5b2-55c69a8ea1dc

https://github.com/ss220-space/Paradise/assets/115735095/40bb3723-48f4-4330-bfa4-065c35e19916

2023-12-26 15:14 UTC, SAADf603 commented on code/game/objects/effects/spawners/lootdrop.dm
> +				"" = 61
Хочу понять, почему и зачем это было сделано. Есть понимание что это, зачем это нужно? (спойлер в предложках об этом нет ни слова, даже не открывая их)

2023-12-26 15:54 UTC, Daeberdir commented on code/game/objects/effects/spawners/lootdrop.dm
> +				"" = 61
> Хочу понять, почему и зачем это было сделано. Есть понимание что это, зачем это нужно? (спойлер в предложках об этом нет ни слова, даже не открывая их)

Автор єтого участка кода просил манипулировать этим "пустым" числом при добавлении нового "веса" внутрь спавнера.
![изображение](https://github.com/ss220-space/Paradise/assets/115735095/949b639d-7fd7-4f10-9bee-e2442638dafd)

2024-02-03 03:46 UTC, pilygun commented
@Dimach Деньги уплачены ждем мержа

2024-02-15 04:47 UTC, BeebBeebBoob requested changes

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/ammunition/magazines.dm
>  /obj/item/ammo_box/magazine/internal/cylinder/improvisedrevolver
```suggestion
/obj/item/ammo_box/magazine/internal/cylinder/improvised
```
видимо прошлые разрабы добавляя, решил лишний `revolver` приписать хотя и так понятно по cylinder для чего это

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/ammunition/magazines.dm
> +/obj/item/ammo_box/magazine/internal/cylinder/improvisedrevolver/Initialize(mapload)
```suggestion
/obj/item/ammo_box/magazine/internal/cylinder/improvised/Initialize(mapload)
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on _maps/map_files/Delta/delta.dmm
> +/obj/item/ammo_box/magazine/internal/cylinder/improvisedrevolver/steel,
```suggestion
/obj/item/ammo_box/magazine/internal/cylinder/improvised/steel,
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/game/objects/effects/spawners/lootdrop.dm
> +				/obj/item/ammo_box/magazine/internal/cylinder/improvisedrevolver/steel = 2,
```suggestion
				/obj/item/ammo_box/magazine/internal/cylinder/improvised/steel = 2,
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/chrono_eraser.dm
> +	nodamage = TRUE
Допустим....
Хотя это никак не связано с ПРом. :)

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/ammunition/boxes.dm
> +		overlays += new_ammo_icon
Тебе Zwei пальцы откусит за такое, за его страдания над рефактором иконок.
Посмотри закрепы в нашем канале. Там он подробно и чётко расписал как надо. Совет: update_overlays()

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/ammunition/magazines.dm
> -	icon_state = "cats_mag_slug"
💋

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/projectile/revolver.dm
>  /obj/item/gun/projectile/revolver/improvisedrevolver
```suggestion
/obj/item/gun/projectile/revolver/improvised
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/projectile/revolver.dm
> +/obj/item/gun/projectile/revolver/improvisedrevolver/New()
```suggestion
/obj/item/gun/projectile/revolver/improvised/New()
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/projectile/revolver.dm
>  /obj/item/gun/projectile/revolver/improvisedrevolver/afterattack(atom/target, mob/living/user, flag, params)
```suggestion
/obj/item/gun/projectile/revolver/improvised/afterattack(atom/target, mob/living/user, flag, params)
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/projectile/revolver.dm
> +/obj/item/gun/projectile/revolver/improvisedrevolver/proc/radial_menu(mob/user)
```suggestion
/obj/item/gun/projectile/revolver/improvised/proc/radial_menu(mob/user)
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/projectile/revolver.dm
> +/obj/item/gun/projectile/revolver/improvisedrevolver/attack_hand(mob/user)
```suggestion
/obj/item/gun/projectile/revolver/improvised/attack_hand(mob/user)
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/projectile/revolver.dm
> +/obj/item/gun/projectile/revolver/improvisedrevolver/screwdriver_act(mob/user, obj/item/I)
```suggestion
/obj/item/gun/projectile/revolver/improvised/screwdriver_act(mob/user, obj/item/I)
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/projectile/revolver.dm
> +/obj/item/gun/projectile/revolver/improvisedrevolver/attackby(obj/item/A, mob/user, params)
```suggestion
/obj/item/gun/projectile/revolver/improvised/attackby(obj/item/A, mob/user, params)
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/projectile/revolver.dm
> +/obj/item/gun/projectile/revolver/improvisedrevolver/attackby(obj/item/A, mob/user, params)
Также глянь в других местах на всякий

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/ammunition/magazines.dm
> +/obj/item/ammo_box/magazine/internal/cylinder/improvisedrevolver/ammo_suitability(obj/item/ammo_casing/bullet)
```suggestion
/obj/item/ammo_box/magazine/internal/cylinder/improvised/ammo_suitability(obj/item/ammo_casing/bullet)
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/ammunition/magazines.dm
> +/obj/item/ammo_box/magazine/internal/cylinder/improvisedrevolver/steel
```suggestion
/obj/item/ammo_box/magazine/internal/cylinder/improvised/steel
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/projectile/revolver.dm
> +		if(istype(A, /obj/item/ammo_box/magazine/internal/cylinder/improvisedrevolver))
```suggestion
		if(istype(A, /obj/item/ammo_box/magazine/internal/cylinder/improvised))
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on code/modules/research/designs/autolathe_designs.dm
> +	build_path = /obj/item/ammo_box/magazine/internal/cylinder/improvisedrevolver
```suggestion
	build_path = /obj/item/ammo_box/magazine/internal/cylinder/improvised
```

2024-02-15 04:47 UTC, BeebBeebBoob commented on icons/mob/inhands/guns_righthand.dmi
Ты видимо сделал нуллевой спрайт... Это может быть плохо если будет появляется не там где надо.
![image](https://github.com/ss220-space/Paradise/assets/32985153/1968c2d7-1562-4916-bf85-860bbe5bfea2)

2024-02-15 04:47 UTC, BeebBeebBoob commented on icons/mob/inhands/guns_lefthand.dmi
![image](https://github.com/ss220-space/Paradise/assets/32985153/5d700f51-4672-4635-890e-4bb9720b3f3e)
Палка???

2024-02-15 04:50 UTC, Daeberdir commented on icons/mob/inhands/guns_lefthand.dmi
С иконками это всё проделки батника, который должен конфликты решать. В последний раз он повёл себя "странным образом". Как появится время, всё поправлю.

2024-02-15 10:13 UTC, Daeberdir commented on code/modules/projectiles/ammunition/boxes.dm
> +		overlays += new_ammo_icon
> Тебе Zwei пальцы откусит за такое, за его страдания над рефактором иконок. Посмотри закрепы в нашем канале. Там он подробно и чётко расписал как надо. Совет: update_overlays()

Да, знаю, проходили. Тупо забыл про это место, щяс буду актуализировать.

2024-02-17 06:13 UTC, BeebBeebBoob submitted a review, later dismissed

2024-02-21 12:24 UTC, merged