add: UnusualVision protection for all gates areas
ss220-space/Paradise pull request #4158
Opened 2023-12-30 18:20 UTC by aeternaclose

## Описание
**Сделал всем зонам всех гейтов защиту от нестандартного зрения.**

## Причина создания ПР
**Чтоб не абузили**

## Демонстрация изменений
![Screenshot 2023-12-28 232752](https://github.com/ss220-space/Paradise/assets/127967350/21d98560-3195-4a49-a8f1-e9ae5c0ebf89)

2024-01-04 08:22 UTC, SAADf603 approved these changes

2024-02-16 13:29 UTC, Vladisvell approved these changes

2024-02-16 14:49 UTC, Vladisvell requested changes
Уделить внимание замечаниям (в дискорде)

2024-02-17 23:52 UTC, BeebBeebBoob commented
Можешь пояснить что ты изменил?

2024-02-18 11:40 UTC, aeternaclose commented
> Можешь пояснить что ты изменил?

https://github.com/ss220-space/Paradise/pull/4132

2024-03-11 21:55 UTC, BeebBeebBoob commented
DNM ибо там через компоненты или как желал димач

2024-05-10 05:57 UTC, aeternaclose commented
Буду переделывать полностью.

2024-05-10 05:57 UTC, closed without merging