tweak: Progress Bar And Chatmessage Update
ss220-space/Paradise pull request #4160
Opened 2023-12-30 22:09 UTC by Gottfrei

## Описание
Немного дописанный код рунчата, теперь он будет брать во внимание переменную maptext и использовать её в качестве оффсета для сообщения.

Переписан код прогрессбара на более современный и добавлено больше его состояний в .dmi файл.

2024-02-16 13:23 UTC, Vladisvell requested changes

2024-02-16 13:23 UTC, Vladisvell commented on code/datums/progressbar.dm
> +	RegisterSignal(user, COMSIG_MOB_LOGIN, PROC_REF(on_user_login))
У нас не имплементировано использование этих сигналов

2024-02-18 14:55 UTC, Vladisvell approved these changes

2024-02-18 14:55 UTC, Vladisvell approved these changes
(На тестмёрж)

2024-03-08 05:41 UTC, BeebBeebBoob approved these changes

2024-03-08 05:55 UTC, merged