feat: Добавление бодрина (pemoline)
ss220-space/Paradise pull request #4165
Opened 2023-12-31 16:08 UTC by Darkest08

## Описание
Создаёт новый реагент pemoline, ускоряющий работу с инструментами, в связи с этим пришлось добавить переменную в mob_defines подробности можете прочитать в коммитах

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1189270199816425594
https://discord.com/channels/617003227182792704/755125334097133628/1189270346419937473

2024-01-02 09:40 UTC, Rerik007 reviewed
Лучше использовать дефайны для спанов. И ещё пара моментов 👀

2024-01-02 09:40 UTC, Rerik007 commented on code/modules/mob/mob_defines.dm
> +	var/toolspeedincrease = 0 //Mob's speed increase additive modifier
```suggestion
	///Mob's toolspeed increase additive modifier
	var/toolspeedincrease = 0
```
? Как по мне так получше.

2024-01-02 09:40 UTC, Rerik007 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	if (H.can_heartattack())
```suggestion
	if(istype(H) && H.can_heartattack())
```
У нас могут добавиться реагенты и не в хумана, поэтому лучше проверять что это правда он, чтобы не рантаймило лишний раз. У on_mob_delete лучше сделать также.

2024-01-02 09:40 UTC, Rerik007 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	return
```suggestion
		to_chat(H, span_notice("You feel fast."))
		H.toolspeedincrease = speed_increase
```
Лучше использовать дефайны для спанов. У on_mob_delete лучше сделать также. И в овердозе также.

2024-01-02 09:40 UTC, Rerik007 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	to_chat(H, "<span class='notice'>[gettoolspeedmod(H)]</span>")
В чат каждые пару секунд будут даваться цифорки, это точно нужно или после дебага осталось?

2024-01-02 09:40 UTC, Rerik007 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	if (H.toolspeedincrease > speed_increase_overdose && H.reagents.get_reagent_amount("pemoline") < overdose_threshold)
Как я понимаю этот if для снятия эффекта овердоза?
Если да, то лучше так, а то условие не выполнится в текущих реалиях.
```suggestion
	if (H.toolspeedincrease > speed_increase && H.reagents.get_reagent_amount("pemoline") < overdose_threshold)
```
Во вторых как по мне лучше бы создать overdose_end прок, по аналогии с overdose_start/ и вынести эту часть туда.

2024-01-02 13:11 UTC, Darkest08 commented on code/modules/mob/mob_defines.dm
> +	var/toolspeedincrease = 0 //Mob's speed increase additive modifier
Как по мне, старый вариант более в стилистике остального кода

2024-01-02 14:30 UTC, Rerik007 commented on code/modules/mob/mob_defines.dm
> +	var/toolspeedincrease = 0 //Mob's speed increase additive modifier
Ну это скорее для автодока нужно, чтобы показывало, что за переменная без необходимости перехода к ней.
![image](https://github.com/ss220-space/Paradise/assets/120549107/b5b07577-96d0-4118-a8e3-074054f9c7c6)

2024-01-02 14:40 UTC, Gottfrei commented on code/modules/mob/mob_defines.dm
> +	var/toolspeedincrease = 0 //Mob's speed increase additive modifier
вообще-то обязательно. не нужно плодить легаси код.

2024-01-02 18:36 UTC, Rerik007 requested changes
Ещё несколько маленьких вещей.

2024-01-02 18:36 UTC, Rerik007 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +		to_chat(H, span_notice("notice'>You feel realy fast."))
```suggestion
		to_chat(H, span_notice("You feel really fast."))
```

2024-01-02 18:36 UTC, Rerik007 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +		to_chat(H, span_notice("You no longer feelw fast."))
```suggestion
		to_chat(H, span_notice("You no longer feel fast."))
```

2024-01-02 18:36 UTC, Rerik007 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	var/update_flags = STATUS_UPDATE_NONE
```suggestion
```
update_flags не используется здесь, оно не обязательно.

2024-01-02 18:36 UTC, Rerik007 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	return ..() | update_flags
```suggestion
	return ..() 
```

2024-01-02 18:36 UTC, Rerik007 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +			H.visible_message("<span class='warning'>[H] falls unconsciousness.</span>")
```suggestion
			H.visible_message(span_warning("[H] falls unconsciousness.")) 
```

2024-01-02 18:36 UTC, Rerik007 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +			H.visible_message("<span class='warning'>[H] suddenly cluches [H.p_their()] heart!</span>")
```suggestion
			H.visible_message(span_warning("[H] suddenly cluches [H.p_their()] heart!")) 
```

2024-02-16 13:27 UTC, Vladisvell approved these changes

2024-02-17 23:39 UTC, BeebBeebBoob requested changes
Также
> Зависимость невозможно вылечить в слипере, вылечивается только ожиданием, когда Пемолина нет в крови - одна стадия за минуту.
Но зачем его лечить, если можно просто принять еще дозу? 

Мы совсем позабыли. Но я лучше закрою глаза на это. Я не хочу видеть специальный проверку прок на что вот "Если именно ЭТОТ реагент, то игнорировать на ускорение избавления от зависимости"

2024-02-17 23:39 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +		H.toolspeedincrease = speed_increase
```suggestion
/datum/reagent/medicine/pemoline/on_mob_add(mob/living/M)
	to_chat(M, span_notice("You feel fast."))
	M.toolspeedincrease = speed_increase
```

2024-02-17 23:39 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	return
Если твой пациент не может принимать сердечный приступ, то при окончании пемолина в организме, скорость не измениться.
```suggestion
/datum/reagent/medicine/pemoline/on_mob_delete(mob/living/M)
	to_chat(M, span_notice("You no longer feel fast."))
	M.toolspeedincrease = 0
	return
```

2024-02-17 23:39 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	return ..()
```suggestion
/datum/reagent/medicine/pemoline/on_mob_life(mob/living/M)
	if(M.reagents.get_reagent_amount("pemoline") < overdose_threshold && overdosed)
		if (M.toolspeedincrease > speed_increase)
			H.toolspeedincrease = speed_increase
			to_chat(H, span_notice("You no longer feel so fast."))
	return ..() 
```
Можно вообще добавить прок /overdose_end дабы не ебаться, ну да ладно. Пока что там и то, только для одного химиката

2024-02-17 23:39 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	return
```suggestion
/datum/reagent/medicine/pemoline/overdose_start(mob/living/M)
	if (M.toolspeedincrease < speed_increase_overdose)
		M.toolspeedincrease = speed_increase_overdose
		to_chat(M, span_notice("You feel really fast."))
	return
```
Непонятен смысл указания что это хуман, если ты засунул toolspeedincrease для всех мобов.

2024-02-17 23:39 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +			update_flags |= H.adjustHeartLoss(1, FALSE)
Лучше `undergoing_cardiac_arrest` т.к. он проверяет на то, сдохло сердце уже или нет.  + `set_heartattack` уже имеет проверку `can_heartattack`(наличие генов)
```suggestion
	if(effect <= 2 && !H.undergoing_cardiac_arrest()))
		H.visible_message(span_warning("[H] falls unconsciousness.")) 
		H.emote("scream")
		update_flags |= H.set_heartattack(TRUE)
	else if(effect <= 5)
		H.visible_message(span_warning("[H] suddenly cluches [H.p_their()] heart!")) 
		H.emote("scream")
		update_flags |= H.adjustHeartLoss(1, FALSE)
```
> 5% шанс на появление сердечной недостаточности 

Я не знаю Шеф но мне кажется на совсем то что нужно(`H.adjustHeartLoss(1, FALSE)`)

2024-02-29 20:05 UTC, closed without merging