add: colorized suspenders + security belt shoulder system
ss220-space/Paradise pull request #4184
Opened 2024-01-03 19:40 UTC by Etrnlmelancholy

## Описание
Добавляет возможность красить подтяжки в абсолютно любые цвета, доступные в баллончике с краской. Помещает её в лодаут за 1 поинт.
Добавляет РПСку для службы безопасности, обеспечивая +слот в suit storage, но без брони. Так же помещает её в лодаут за 1 поинт с рестриктом как у остального общего сбшного шмотья + в вендор. 

Спасибо Владисвеллу за код покраски ведер, Родену за помощь, Петру Чайковскому за белые спрайты для подтяжек и UMG Agent "Spoon" за спрайт РПСки. 
## Ссылка на предложение/Причина создания ПР
[We apologize to nobody](https://discord.com/channels/617003227182792704/755125334097133628/1190763824425488404)
[The 4 Skins - Evil](https://discord.com/channels/617003227182792704/755125334097133628/1190763622113214594)

## Демонстрация изменений
![image](https://github.com/ss220-space/Paradise/assets/103588397/95260750-efe3-4cc6-a7c9-265eeff8276f)
![image](https://github.com/ss220-space/Paradise/assets/103588397/34669c95-33e8-4913-a34d-dd7d91567b36)

2024-01-15 21:28 UTC, NightDawnFox requested changes
Сделать по аналогии с ведром? Держи.

2024-01-15 21:28 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +			update_icon()
```suggestion
			update_icon(UPDATE_OVERLAYS)
```

2024-01-15 21:28 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +/obj/item/clothing/suit/suspenders/update_icon()
```suggestion
/obj/item/clothing/suit/suspenders/update_overlays()
```

2024-01-15 21:28 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +	overlays.Cut()
```suggestion

```

2024-01-15 21:28 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +		overlays += suspenders_overlay
```suggestion
		+= suspenders_overlay
```

2024-01-15 21:28 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +		var/mutable_appearance/suspenders_clips = mutable_appearance(icon='icons/obj/clothing/belts.dmi', icon_state = "suspenders_clips")
```suggestion
		
```

2024-01-15 21:28 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +		suspenders_clips.appearance_flags |= RESET_COLOR
```suggestion
		
```

2024-01-15 21:28 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +		overlays += suspenders_clips
```suggestion
	
```

2024-01-15 21:40 UTC, NightDawnFox requested changes

2024-01-15 21:40 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +		+= suspenders_overlay
```suggestion
		. += suspenders_overlay
				var/mutable_appearance/suspenders_clips = mutable_appearance(icon='icons/obj/clothing/belts.dmi', icon_state = "suspenders_clips", appearance_flags = RESET_COLOR)
		. += suspenders_clips
```

2024-01-15 21:40 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +
```suggestion
```

2024-01-15 21:40 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +
```suggestion
```

2024-01-15 21:40 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +
```suggestion
```

2024-01-15 21:40 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +
```suggestion
```

2024-01-15 21:40 UTC, NightDawnFox commented on code/modules/clothing/suits/jobs.dm
> +
```suggestion
```

2024-01-15 21:44 UTC, NightDawnFox commented
Как же *неприятно* что-то пытаться делать через браузерный гитхаб, жесть просто

2024-01-15 21:50 UTC, ROdenFL commented
> Как же _неприятно_ что-то пытаться делать через браузерный гитхаб, жесть просто

терпи (ла)

2024-01-19 00:31 UTC, TrashDoxx commented
@Dimach Мержи эту хуйню, чего ждём.

2024-01-19 00:34 UTC, TrashDoxx commented
Деньги уплачены, клиентура ждёт.

2024-01-20 14:42 UTC, merged