refactor: two-character keys for languages.
ss220-space/Paradise pull request #4215
Opened 2024-01-14 20:19 UTC by Daeberdir

## Описание
Немного рефакторит систему языков:
- Заставляет весь код манипуляции с языками работать не на названиях языков, а на их "ключах" (которые теперь на дефайнах для удобства).
- Все ключи языков переведены на двухсимвольные значения по типу `"un"` для языка унати.
- Пофикшен баг того, что можно было "вслух" говорить хайвмайндом, если иметь хайвмайнд дефолтным языком и пытаться ввести вначале сообщения префикс языка, который персонаж не знает.
- Ещё из важных изменений (или лучше сказать вынужденых) - теперь, чтобы душить радиоканалы эмоутами, нужно вписывать знак восклицания перед каналом связи, а не после него. Пример: "!;зевает."
- А, ну и ещё теперь можно ввести префикс языка как до префикса радиоканала, так и после.

## Ссылка на предложение
https://discord.com/channels/617003227182792704/755125334097133628/1182693322066772038

## По непонятным моментам
Всё переведено на ключи с названий по причине того, что названия часто используют спецсимволы, так что мы не можем, например, дать возможность выбирать в префах "Sinta'unathi" в качестве вторичного языка и не можем напрямую через `AdvancedCallProc` выдать мобу этот же "Sinta'unathi".

2024-01-15 17:17 UTC, ArtemDerp commented on code/__DEFINES/language.dm
> +#define LANGUAGE_HIVE_TERRORSPIDER	"sp"
```suggestion
#define LANGUAGE_HIVE_TERRORSPIDER	"ts"
```

2024-01-15 17:18 UTC, ArtemDerp commented on code/modules/mob/language.dm
> +	key = "sp"
```suggestion
	key = "ts"
```

2024-02-13 17:01 UTC, ArtemDerp commented
@Vladisvell @BeebBeebBoob @SAADf603 вот бы аппрув увидеть

2024-02-14 07:30 UTC, BeebBeebBoob commented on code/modules/client/preference/preferences.dm
> +						species = prev_species
Надо?

2024-02-14 07:30 UTC, BeebBeebBoob commented on code/modules/mob/language.dm
> +	var/english_names = 0						// Do we want English names by default, no matter what?
Можешь сделать так
```
/// Коммент в переменной
var/a = 1
```
Так будет показывать что значит переменная в VSC и без столь больших отделений в виде пробелов

2024-02-15 01:21 UTC, Daeberdir commented on code/modules/client/preference/preferences.dm
> +						species = prev_species
Надо, это багфикс. Если открыть выбор расы в префах и выбрать ничего, то оно поставит `species = null` и потом будет нещадно рантаймить при нажатии на другие кнопки.

2024-02-15 01:23 UTC, Daeberdir commented on code/modules/mob/language.dm
> +	var/english_names = 0						// Do we want English names by default, no matter what?
Можно. Сделаю.

2024-02-17 03:07 UTC, LiquidPotroh commented
Ух, вот бы ещё какой нибудь красивый кодер в объединении с не менее красивым лороведом разделил языки по тому, может ли на них говорить только определённая раса из за физеологических особенностей(например язык кидан, у них там движения усиками часть языка), или же его можно выучить и другим(синтаунати). И привязать к майнду все те, что не привязаны к расе. Чтобы например при пересадке такие языки сохранялись. И в обратную сторону, чтобы люди не узнавали синтаунати, если их мозг вдруг очутился в ящере. 
Это же так просто будет сделать в свежеотрефакторенном коде, да?)

2024-02-18 10:54 UTC, BeebBeebBoob submitted a review, later dismissed

2024-02-18 14:42 UTC, Vladisvell requested changes

2024-02-18 14:42 UTC, Vladisvell commented on code/datums/datumvars.dm
> +				new_languages |= language
Судя по коду тут нет ориентации на существующие языки у моба
Тогда может лучше сделать кэширование, сделав переменную new_languages статической?

2024-02-18 14:42 UTC, Vladisvell commented on code/modules/client/preference/preferences_mysql.dm
> -	if(isnull(language)) language = "None"
Что теперь происходит в случае, если у нас language null'овый?

2024-02-18 14:42 UTC, Vladisvell commented on code/modules/mob/living/carbon/human/species/_species.dm
> +	var/scream_verb = "крич%(ит,ат)%"				// Special symbols used to apply correct gender. See [/proc/genderize_decode] for more info.
Заметка: в редакторе выглядит нормально 
![изображение](https://github.com/ss220-space/Paradise/assets/73733747/fd081066-c2b4-403a-b619-dd3c1d96cedb)

2024-02-20 22:25 UTC, Daeberdir commented on code/datums/datumvars.dm
> +				new_languages |= language
Совет пригодился, но в другом месте. Тут списка больше нет.

2024-02-20 22:26 UTC, Daeberdir commented on code/modules/client/preference/preferences_mysql.dm
> -	if(isnull(language)) language = "None"
Всё тоже, что и было, строчка вернулась на место.

2024-02-21 14:35 UTC, Dimach commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +	secondary_langs = list()
```suggestion
```

2024-02-21 14:35 UTC, Dimach commented on code/modules/mob/living/carbon/human/species/tajaran.dm
> +	secondary_langs = list()
```suggestion
```

2024-02-21 14:39 UTC, merged