[NOT READY]Add: Multi-Z Support
ss220-space/Paradise pull request #4216
Opened 2024-01-15 08:32 UTC by BeebBeebBoob

## Описание

Поддержка Мульти-Z. Шаг ближе к ТрамСтанции.

## Ссылка на предложение/Причина создания ПР

¯\_(ツ)_/¯

## Демонстрация изменений

Пока что нет ибо ещё в бета тесте. Багов полно, рантаймов тоже... Смотреть на свой страх и риск.
На данный момент создание мульти-з станции есть, переходы за живого тоже. Остаётся только убить довольно огромное количество багов(перемещение призраками, свет, СВЕТ, загрузка лавы и тайпана не работает, удаление турфов рантайм и т.д.)

2024-01-15 14:24 UTC, SAADf603 commented
Кошмар
Я отказываюсь воспринимать данную информацию

2024-01-15 15:48 UTC, VasilevAY commented
Кабанчиком бы кто-то ревью 200 тыс.строчек сделал

2024-01-15 16:30 UTC, Etrnlmelancholy commented
Говно, переделывай

2024-01-15 16:31 UTC, Etrnlmelancholy commented
> Кабанчиком бы кто-то ревью 200 тыс.строчек сделал

Сделал

2024-01-15 16:43 UTC, TrashDoxx commented
> Кабанчиком бы кто-то ревью 200 тыс.строчек сделал

198 из которых карта.

2024-01-15 17:08 UTC, BeebBeebBoob commented
Мой ход? Круть. Тогда я воспользуюсь заклинанием 2 уровня "Скрытый мап в коде" используя свою 4 ячейку заклинании, что увеличивает мой код с 2к строк, до 202к строк и в итоге я смогу набрать аж до 6к8 урона. Кидаю кубики.. с преимуществом так как противник заставлен врасплох!... Охуеть 20, Крит! Ну ща посмотрим на эти сочные 12к8...

2024-01-15 23:55 UTC, BeebBeebBoob reviewed
XP

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/__HELPERS/game.dm
> +	if(istype(new_turf))
`if(new_turf && !new_turf.density)`

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/_onclick/hud/plane_master.dm
> +	appearance_flags = PLANE_MASTER
Эт нихрена не используется нигде. Исправить

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/controllers/subsystem/non-firing/mapping.dm
> +	var/lavaland_z_level = GLOB.space_manager.add_new_zlevel(MINING, linkage = UNAFFECTED, traits = list(ORE_LEVEL, REACHABLE, STATION_CONTACT, HAS_WEATHER, AI_OK, ZTRAIT_BASETURF = /turf/simulated/floo
Проверить Лаваленд и тайпан что они вообще загружается. Перед этим исправив рантайм на `turfs/turf.dm /Destroy`

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/controllers/subsystem/throwing.dm
> +		T?.zFall(thrownthing)
Кидая вещи, вещица почему-то летела дальше когда "падала" вниз чем изначальный пункт назначения. Кинул на 1 клетку вниз перед собой, он летит, падает и летит вплоть до стенки.
Вероятно код падает его, меняя z уровень и чудом ломает датум броска. Датум бросок просто /shrug и говорит предмету лететь до конца.
P.S. может переместить это после окончание броска где-то?

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/datums/elements/turf_transparency.dm
> +/datum/element/turf_z_transparency/Attach(datum/target, is_openspace = FALSE)
Я хз но оно типо нормально работает?... Но оно точно не работает с floor/transparent/glass. Стекло просто тупо невидимое(хоть оно там есть).
P.S. floor/transparent/glass сам что-то шаманит с иконками? черкает свою иконку ибо старый код?

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/atoms_movable.dm
> +/atom/movable/proc/check_pulling(only_pulling = FALSE, z_allowed = FALSE)
Это я называю прок-балласт. Он в коде не используется от слова совсем. Вся пулль хрень происходит у mob/living и это отвратительно. Не говоря что там обычный и грабные пуллы они как один целый ребёнок, только с двумя головами. Кошмар.
P.S. Пересмотреть этот прок и его потенциал??

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/atoms_movable.dm
> +	var/currently_z_moving
Я бы задебагал до чистоты эту переменную, дабы случаем код не решит "забыть" его поменять.
P.S. срать об этом в дебагер при каждом изменении? set_currently_z_moving в помощь

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/turfs/turf.dm
> +/turf/proc/zFall(atom/movable/falling, levels = 1, force = FALSE, falling_from_move = FALSE)
Целуй в зад этому проку

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/turfs/turf.dm
> +		SEND_SIGNAL(T, COMSIG_TURF_MULTIZ_NEW, src, UP)
Меня это пугает. Меня пугает что оно будет вызывать рантайм из-за попыток GET_TURF_ABOVE(src) на проверку список. 
P.S. вероятно я обосрался что не расширил multiz_level список до всех зон, дабы он не вызывал index out of list.

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/turfs/turf.dm
> +		V.multiz_turf_del(src, UP)
Fuck как сверху. Опять рантайм на get_turf_above в проверках списка вне границ

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/atoms_movable.dm
> +/atom/movable/proc/zMove(dir, turf/target, z_move_flags = ZMOVE_FLIGHT_FLAGS)
Этот прок буквально покрыли резиной, смазкой и другими вещами защиты, чтобы кекодеры или сам код не обосрался в попытках недотащить что либо в аргументы. Упаси.

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/atoms_movable.dm
> +		. |= pulling
Машины, пуллинги и другие хрени. Но есть чувство что оно не всегда работает как надо.

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/machinery/computer/camera_advanced.dm
> +	button_icon_state = "move_up"
Проверить каждую камеру. Проверить что они вообще РАБОТАЮТ. Дать ответ :)

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/objects/effects/decals/Cleanable/misc.dm
> +	turf_loc_check = FALSE
Это фунгус. Фунгусу можно на стенку, другим нельзя на стенку. :)

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/objects/effects/effects.dm
> +		return INITIALIZE_HINT_QDEL
Я бы наверное оставил бы сюда ошибку аля "Маппер. Ты обосрался. Но не волнуйся, я удалил твоё чудо в воздухе/в стенке"

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/objects/structures/ladders.dm
>  /obj/structure/ladder/LateInitialize()
Надо проверить jacob лестницу...

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/turfs/simulated/floor/transparent.dm
>  	icon_state = "" //Prevents default icon appearing behind the glass
Может из-за этого он не хочет показывать себя...

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/turfs/simulated/openspace.dm
> +	if(!GET_TURF_BELOW(src))
Я думаю он даже не дойдёт до строчки низ и сразу крашнет инициализацию

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/turfs/simulated/openspace.dm
> +/turf/simulated/openspace/proc/on_atom_created(datum/source, atom/created_atom)
Проверить спавн плюшек на открытом месте.

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/turfs/simulated/openspace.dm
> +		zFall(movable, falling_from_move = TRUE)
Я вот думаю. Может спец проверку сделать, что там ничего под ним нету? Точнее дать возможность ходить в открытом пространстве по "крыше" стенки внизу. Мне напомнило айсбокс, где я мог бегать минералами которые не вскопали. 
P.S. Мы бля превращаемся в DF https://dwarffortresswiki.org/images/4/4d/DF2014_Terraform.png АХХАХАХААХ (Где ты вскапываешь только тайл, но под низ нет ещё. Хотя в DF на памяти на даёт право на такое, нооо думаю можно обмануть систему)

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/modules/mob/dead/observer/observer_movement.dm
> +	return ..()
Я хз но при попытках двигаться по Z, призрака посылают в нуллевую точку. 
P.S. Посмотреть как живые передвигаются, ибо у них всё нормуль

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/atoms_movable.dm
> +/atom/movable/proc/can_z_move(direction, turf/start, turf/destination, z_move_flags = ZMOVE_FLIGHT_FLAGS, mob/living/rider)
Добавь /obj/can_z_move() с проверками что прикручен или невозможно перемещать или может вес там + лампы падают.

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/objects/structures/stairs.dm
> +/obj/structure/stairs_frame
Проверить что он нормально создаёт лестницы, а не божественное удаление турфов или проходы в нуллевую.

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/turfs/simulated/openspace.dm
> +		return
Мне надо реально решить проблемы с постройками на открытом пространстве. Ну или нахрен удалить CanCoverUp и CanBuildHere...

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/game/turfs/simulated/openspace.dm
> +// PARACODE
Это часть нашего парадизовского которое я отобрал у simulated/floor. Не орите

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/modules/awaymissions/maploader/reader.dm
> +							continue // Beware of runtimes. Beware of trying to add content on non-existed z level.
Если чудом код достиг этого пункта, то надеюсь что у нас есть готовые пустые уровни иначе готовься к спаму рантаймом о недоступности

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/modules/mob/living/living.dm
> +	if(((istajaran(src) && functional_legs) || cat) && !lying && can_help_themselves)
по поводу таяр я как-то sus.... Хотя если они крупные, то пусть взамен стана просто получат побольше урона, мини-коты и животные-коты не получат такого прикола.

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/modules/mob/living/living.dm
> +currently_z_moving
FUCK

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/modules/mob/living/living.dm
> +				dest = get_step(pulling, get_dir(pulling, dest))
Всё ещё сосёт. Я вот реально должен сломать себе голову чтобы оно заработало.

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/modules/mob/living/living.dm
> +				dest = get_step(pulling, get_dir(pulling, dest))
Дружбан прошлый постой. Есть три способа в которых pulling надо передвинуть по moveZ
1. Тот кто тащит перемещается через Move Up или Move Down 
2. Тот кто тащит использовал /ladder
3. Тот кто тащит переместился через /stairs
Может просто перехватывать и дотаскивать в тех местах?

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/modules/mob/living/silicon/ai/freelook/eye.dm
> +		to_chat(src, span_notice("You move down."))
Проверить.

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/modules/power/supermatter/supermatter.dm
> +	. |= FALL_STOP_INTERCEPTING | FALL_INTERCEPTED
Оно не сработало когда я упал прям на СМ.

2024-01-15 23:55 UTC, BeebBeebBoob commented on code/modules/surgery/organs/blood.dm
> +		return
Это надо кстати допилить и в других местах, чтобы не было приколов аля "кровь левитирует".

2024-01-16 00:16 UTC, BeebBeebBoob commented
Был конфликт: [refactor: Icon Updates Rework Part1](https://github.com/ss220-space/Paradise/commit/fd2a97e295bd9152139ddd30bbef821e697cb1f2)
Решён

2024-01-16 04:59 UTC, Den109G commented on code/game/objects/structures/ladders.dm
>  /obj/structure/ladder/LateInitialize()
https://github.com/ss220-space/Paradise/assets/87372121/b56f15f0-e999-4f49-8aa8-54c9c32ba817

Лестница работает как лестница, правда пробивает всё.

2024-01-16 05:04 UTC, Den109G commented on code/modules/mob/dead/observer/observer_movement.dm
> +	return ..()
`/mob/dead/can_z_move(` просто возвращает TRUE, в это же время, у живых или атомов возвращает `destination = get_step_multiz(start, direction)`

2024-01-16 05:17 UTC, Den109G commented on code/game/objects/structures/stairs.dm
> +/obj/structure/stairs_frame
Оно создаёт лестницы(?) (не сжирая ресурсы), но они всегда смотрят на `2` и очень не ясно как по ним перемещаться. Хожу по ним - ничего не случается. У них есть `/datum/element/connect_loc`

https://github.com/ss220-space/Paradise/assets/87372121/057e69a7-a549-44a7-b254-e211bc7929ae

2024-01-16 05:20 UTC, Den109G commented on code/modules/mob/living/living.dm
> +	if(((istajaran(src) && functional_legs) || cat) && !lying && can_help_themselves)
Таярам дай и больше урона и больше стана. Они космо-коты, они не знают как приЗЕМЛЯтся.

2024-01-16 05:28 UTC, Den109G commented on code/modules/mob/living/silicon/ai/freelook/eye.dm
> +		to_chat(src, span_notice("You move down."))
Работает?

[Ссылка на видео.](https://discord.com/channels/617003227182792704/734823601110515882/1196686633546829975) В конце не мог вверх-вниз управлять камерой. Рантаймов нет. Гравитация действует на глаз ИИ.

2024-01-16 06:20 UTC, BeebBeebBoob commented on code/game/atoms_movable.dm
> +/atom/movable/proc/can_z_move(direction, turf/start, turf/destination, z_move_flags = ZMOVE_FLIGHT_FLAGS, mob/living/rider)
P.S. добавить доп коммент что это дичь возвращает таргет либо возвращает FALSE. Хотя там и так записано но пох

2024-01-16 20:44 UTC, BeebBeebBoob reviewed
Больше комментов для себя

2024-01-16 20:44 UTC, BeebBeebBoob commented on code/game/atoms_movable.dm
> +	if(!(z_move_flags & ZMOVE_IGNORE_OBSTACLES) && !(start.zPassOut(src, direction, destination) && destination.zPassIn(src, direction, start)))
`(!(z_move_flags & ZMOVE_ALLOW_ANCHORED) && anchored))`

2024-01-16 20:44 UTC, BeebBeebBoob commented on code/game/turfs/simulated/openspace.dm
> +	return FALSE
```suggestion
/turf/simulated/openspace/zPassIn(direction)
	if(direction == DOWN)
		for(var/obj/contained_object in contents)
			if(contained_object.obj_flags & BLOCK_Z_IN_DOWN)
				return FALSE
		return TRUE
	if(direction == UP)
		for(var/obj/contained_object in contents)
			if(contained_object.obj_flags & BLOCK_Z_IN_UP)
				return FALSE
		return TRUE
	return FALSE
```

2024-01-16 20:44 UTC, BeebBeebBoob commented on code/game/turfs/simulated/openspace.dm
> +	return FALSE
```suggestion
/turf/simulated/openspace/zPassOut(direction)
	if(direction == DOWN)
		for(var/obj/contained_object in contents)
			if(contained_object.obj_flags & BLOCK_Z_OUT_DOWN)
				return FALSE
		return TRUE
	if(direction == UP)
		for(var/obj/contained_object in contents)
			if(contained_object.obj_flags & BLOCK_Z_OUT_UP)
				return FALSE
		return TRUE
	return FALSE
```

2024-01-16 20:44 UTC, BeebBeebBoob commented on code/game/turfs/turf.dm
> +	return FALSE
добавить проверку на density, мы не хотим приколов работая со стенками, путая их с полом

2024-01-16 20:44 UTC, BeebBeebBoob commented on code/game/turfs/turf.dm
> +	return FALSE
```suggestion
//The zpass procs exist to be overriden, not directly called
//use can_z_pass for that
///If we'd allow anything to travel into us
/turf/proc/zPassIn(direction)
	return FALSE

///If we'd allow anything to travel out of us
/turf/proc/zPassOut(direction)
	return FALSE
```

А проверки засунуть в /turf/simulated с density
Не забудь также для отдельного тупого turf/space прописать как прописано с openspace

2024-01-16 20:47 UTC, BeebBeebBoob commented on code/game/objects/structures/ladders.dm
>  /obj/structure/ladder/LateInitialize()
Оно должно пробивать. Это лестница против физики и логики. Мне главное чтобы оно просто работало ок с моим чудом о MultiZ

2024-01-16 20:48 UTC, BeebBeebBoob commented on code/game/turfs/simulated/floor/transparent.dm
>  	icon_state = "" //Prevents default icon appearing behind the glass
Дурак, ты с плейном должен был побаловаться

2024-01-16 20:57 UTC, BeebBeebBoob commented on code/modules/mob/living/living.dm
> +	if(((istajaran(src) && functional_legs) || cat) && !lying && can_help_themselves)
P.S. ломает только колени, но и ботинки(foot)

2024-01-19 21:58 UTC, BeebBeebBoob commented
+3797 -1838 строк... Найс. Остался Атмос, ещё полно фиксов, несколько иконок и я думаю можно пускать людей в пропасть.
БашняСтанция, я иду!

2024-01-20 18:02 UTC, BeebBeebBoob commented
Блин! Моё царство нарушено! Будь проклят этот мерж конфликт!

2024-01-21 02:11 UTC, TrashDoxx commented
> Блин! Моё царство нарушено! Будь проклят этот мерж конфликт!

Жесть ты шизик. Вот что хоумстак с людьми делает.

2024-01-21 23:44 UTC, BeebBeebBoob commented
Готово. Если будут конфликты с другими ПРами, решу без проблем.

2024-01-23 10:29 UTC, PhantornRU commented
Психопат! В хорошем смысле

2024-01-23 10:52 UTC, BeebBeebBoob commented
Rebase это кайф.

2024-01-27 11:01 UTC, BeebBeebBoob commented
Я слегка обосрался и оставил кусочки моей новой карты здесь. Оно всё равно не будет в ротации, но зато админам будет весело на нём(может).

2024-01-27 12:20 UTC, Den109G commented
dear God, please add sound effect as mob falls through grille it would be so funny (making a thread with videos of play-testing)

https://github.com/ss220-space/Paradise/assets/87372121/2efbc2f8-7c45-43d6-88e9-554e6c8c0837

2024-01-27 12:22 UTC, Den109G commented
some weird rabbit-jump physics

https://github.com/ss220-space/Paradise/assets/87372121/1b4b4f52-2043-41c5-b44c-f334dcc1aede

2024-01-27 12:25 UTC, Den109G commented
Новая страта как искать фальш стены, ценой своих ног.

https://github.com/ss220-space/Paradise/assets/87372121/df7f23f9-a1ff-4db8-85b9-aaadf55287ae

2024-01-27 12:44 UTC, Den109G commented
Призраки не Супермены. Верно. Но, по моему скромному знанию паранормальных явлений, они должны мочь лететь вниз/через пол.
(Проверял как газ вообще распространяется. Вроде бы нормально)

https://github.com/ss220-space/Paradise/assets/87372121/a20f2035-e5aa-4f7f-bcc8-c8c05cc2cfd0

2024-01-27 14:27 UTC, Den109G commented
Телекинез кидает вещи дальше, если объект на нижнем уровне.

https://github.com/ss220-space/Paradise/assets/87372121/1365627b-496a-4355-b9db-f4becab9cd1e

Телекинез может.... C другого этажа ударить по челу на том этаже, где стоит?

https://github.com/ss220-space/Paradise/assets/87372121/e2690122-40e1-42ee-a890-e190cae2ef36

https://github.com/ss220-space/Paradise/assets/87372121/afd669ca-edb5-43d6-b0b6-86f804fa817c

2024-01-27 14:37 UTC, Den109G commented
WANTED: tajaran "Long Paws"
DEAD OR ALIVE
Stole a cap's spare, while he was drunk

https://github.com/ss220-space/Paradise/assets/87372121/a62fb71a-b103-4ac3-b353-448d37c2a5c9

2024-01-27 15:33 UTC, Den109G commented
~~Движок звуков решил выйти за грань нашего понимания. В теории, может софтлокать игру.
Я это только встречал на Мульти-З. На основной ветке - такого ещё не случалось.~~
В 2568 году учёные доказали, что кроме двух осей координат X и Y есть ещё и третья координата - W. И так, компания NanoTrahen Energy on plasma изобрела катушки, что порабощает людей, используя инфракрасные звуки. И так в мире сломались все уши.

https://github.com/ss220-space/Paradise/assets/87372121/5c102870-a991-409f-8853-ed468c1bafa7

2024-01-27 20:28 UTC, BeebBeebBoob commented
+ от @Den109G из дискорда:
хелп/харм интент на лестницу пофиксить надо, (if harm do this)
пофиксить падение при обновлении obj_flags(точнее при разборе палок)

Уже проблемы(выше по видео):
Урон при падении на грилль? (ZMOVE_INTERCEPT)
Ген прыжка (Забрать flying на последний шаг, дабы турф openspace правильно обработал zFall() )
Фальш стены дать obj_flags ( z move in и z move out, уже на моём компе сделано)
Призраки должны летать также вниз (обосрался при коде. Говно убрал)
Вообще Нахрен Перелопатить Взаимодействие с турфами ниже. Особенно телекинез и возможность брать вещи с помощью Look Up и Look Down. (Обновить проверку на Is Adjecent для саппорта Multi Z)

2024-01-28 00:16 UTC, BeebBeebBoob commented
Себе:
[сюда](https://github.com/ss220-space/Paradise/blob/master/code/_onclick/adjacent.dm#L34)
```
	if(get_dist(src, T0) > 1 || z != T0.z) //too far
		return FALSE
```

2024-01-28 04:01 UTC, Den109G commented
> Урон при падении на грилль? (ZMOVE_INTERCEPT)

Просто та же причина что и у фальш стены. Ходишь по стене - и вдруг бац, падаешь между прутей. Как к видео оставил приписку: со звуком было бы смешней.

2024-01-29 04:22 UTC, BeebBeebBoob commented
Todo: пофиксить блюр

2024-01-29 17:45 UTC, TrashDoxx commented
Давай-давай, пили мульти-левел, нам Церу маппить надо.

2024-02-02 04:04 UTC, BeebBeebBoob commented
Уходит в драфт. Мне не нравиться инициализация атмоса.

2024-02-02 11:00 UTC, BeebBeebBoob commented
Перевернул атмос. Атмосу понравилось.... 😊 Снова готов для мержа.

2024-02-06 17:52 UTC, BeebBeebBoob commented
Бля. Ну... "Conflicting files tgui/packages/tgui/public/tgui.bundle.js" ...
Я эт не могу исправить сорянб :clueless:

2024-02-10 01:21 UTC, BeebBeebBoob commented on code/game/objects/explosion.dm
> +			floor_block[z0] = epicenter.explosion_vertical_block
Понять, я правильно чёрт возьми нормально сделал взрыв Multi-Z или нет. Последний раз когда я проверял то оно мне выдавало рантаймы на эту строку. ХМММ

2024-02-10 06:18 UTC, BeebBeebBoob commented on code/game/objects/explosion.dm
> +			floor_block[z0] = epicenter.explosion_vertical_block
Себе также. Подправить isinspace() прок

2024-02-12 04:09 UTC, BeebBeebBoob commented
WHAT THE FUCK>>>>>>>>>>>

2024-02-13 02:36 UTC, BeebBeebBoob commented on code/game/objects/structures/tables_racks.dm
> +	if(M.has_gravity() && M.mob_size > MOB_SIZE_SMALL)
Uuuh Fuck

2024-02-13 02:54 UTC, BeebBeebBoob commented on code/game/atoms_movable.dm
> +	if((z_move_flags & ZMOVE_CAN_FLY_CHECKS) && !flyoting && has_gravity(start))
Обновить после #4249 
```suggestion
	if(z_move_flags & ZMOVE_FALL_CHECKS && (throwing || (movement_type & (FLYING|FLOATING)) || !has_gravity(start)))
		return FALSE
	if(z_move_flags & ZMOVE_CAN_FLY_CHECKS && !(movement_type & (FLYING|FLOATING)) && has_gravity(start))
```

2024-02-21 00:25 UTC, BeebBeebBoob commented
ПР не запушится сама! ТОЛКАЕМ

2024-02-21 10:00 UTC, Etrnlmelancholy commented
Заводи жигуль, а не болтай! Мы толкаем пока

2024-02-21 11:07 UTC, ArtemDerp commented
/me тужится, пыжится и толкает мултижигуль

2024-02-22 19:19 UTC, SAADf603 requested changes
На данный момент это единственные замечания. Фраза "ты не супермен" - выглядит достаточно неуместно к попыткам попасть на уровень ниже.

2024-02-22 19:19 UTC, SAADf603 commented on code/modules/mob/mob_movement.dm
> +			to_chat(src, "<span class='notice'>You are not Superman.<span>")
```suggestion
			to_chat(src, "<span class='warning'>There's nowhere to go in that direction!</span>"))
```

2024-02-22 19:19 UTC, SAADf603 commented on code/game/atoms_movable.dm
> +				to_chat(src, "<span class='notice'>You are not Superman.<span>")
```suggestion
				to_chat(src, "<span class='warning'>There's nowhere to go in that direction!</span>")
```

2024-02-24 11:09 UTC, BeebBeebBoob commented on code/modules/mob/mob_movement.dm
> +			to_chat(src, "<span class='notice'>You are not Superman.<span>")
You are not Superman - Это когда сверху есть пространство но гравитация махает пальцем. Ты не супермен. Ты не умеешь летать.

2024-02-24 11:09 UTC, BeebBeebBoob commented on code/game/atoms_movable.dm
> +				to_chat(src, "<span class='notice'>You are not Superman.<span>")
Пару строк выше: to_chat(rider, "<span class='notice'>[src] is is not capable of flight.<span>")
:D

2024-04-03 09:03 UTC, SAADf603 submitted a review, later dismissed

2024-04-09 08:57 UTC, Dimach approved these changes

2024-04-09 09:26 UTC, SAADf603 approved these changes

2024-04-09 09:39 UTC, Bizzonium approved these changes

2024-04-09 09:43 UTC, merged