bugfix: invincibility machinepersons to neurotoxin spit
ss220-space/Paradise pull request #4225
Opened 2024-01-16 15:47 UTC by LiquidPotroh

## Описание
КПБ уязвимы к нейротоксину ксеноморфов, как и задумывалось.

2024-02-15 04:27 UTC, BeebBeebBoob requested changes

2024-02-15 04:27 UTC, BeebBeebBoob commented on code/datums/spells/alien_spells/neurotoxin_spit.dm
> +	return TRUE
Два раза установка charge_check? 
думаю /Click() оверрайда достаточно в этом месте.
И да... Не будет ли бага что ксеноморф станет пулемёт если ему будет похуй на КД??
Можно попросить как это будет выглядет этот QoL ибо я не понял также 58-59
```dm
else
		targeting.InterceptClickOn(user, params, target, src)
```

2024-02-15 04:27 UTC, BeebBeebBoob commented on code/datums/spells/alien_spells/neurotoxin_spit.dm
> +/obj/effect/proc_holder/spell/alien_spell/neurotoxin/can_cast(mob/user, charge_check = FALSE, show_message)
Перенеси до /cast(
аля сперва проверка до каста, потом сам каст и после /after_cast(

2024-02-15 04:45 UTC, LiquidPotroh commented on code/datums/spells/alien_spells/neurotoxin_spit.dm
> +	return TRUE
Два раза как раз для того, чтобы не стрелял как из пулемёта. Кликнуть по спелу можно, выбрав или отменив его, но стрелять нельзя. Там какая то странноватая система с этим, более красивого решения я в ней не нашёл.
Переопределение InterceptClickOn для того, чтобы в родительском методе не вызывалось user.changeNext_click(). Оно тупо блочит выбор спела или ещё каких действий на 0.6с, что даже больше чем кд плевалки. Скорострельность это никак не увеличит. Видос щас запилю пожалуй.

2024-02-15 05:10 UTC, BeebBeebBoob commented on code/datums/spells/alien_spells/neurotoxin_spit.dm
> +/obj/effect/proc_holder/spell/alien_spell/neurotoxin/can_cast(mob/user, charge_check = FALSE, show_message)
хотя пох. Не страшно

2024-02-15 05:14 UTC, BeebBeebBoob commented on code/modules/mob/living/living_defense.dm
>  			check_projectile_dismemberment(P, def_zone)
```suggestion
	if(!P.nodamage)
		apply_damage(P.damage, P.damage_type, def_zone, armor)
		if(P.dismemberment)
			check_projectile_dismemberment(P, def_zone)
	return P.on_hit(src, armor, def_zone)
```

2024-02-15 05:23 UTC, BeebBeebBoob approved these changes

2024-02-17 19:25 UTC, SAADf603 approved these changes

2024-02-17 19:27 UTC, Vladisvell approved these changes

2024-02-18 00:08 UTC, merged