add: new torch recipes
ss220-space/Paradise pull request #4246
Opened 2024-01-20 22:15 UTC by ArtemDerp

## Описание

Добавлены 2 новых рецепта факела: само поджигающийся (флаер) и "племенной", которому нужен горящий предмет (свеча)
Небольшой рефактор свечки
## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/755125334097133628/1197922378899013742

2024-01-22 04:39 UTC, Den109G commented on code/modules/hydroponics/grown/towercap.dm
> -		if(leaf.dry)
А зачем убрали? Этого в предложке не было.

2024-01-22 04:45 UTC, Den109G commented on code/game/objects/items/candle.dm
> +	name = "Torch"
```suggestion
	name = "torch"
```

2024-01-22 04:45 UTC, Den109G commented on code/game/objects/items/trash.dm
> +	name = "Burnt torch"
```suggestion
	name = "burnt torch"
```

2024-01-22 04:46 UTC, Den109G commented on code/game/objects/items/candle.dm
> +	name = "Torch"
Ещё странно, что со стороны игроков, этот факел почти один в один похож на другой факел. Только этот факел нельзя использовать в хирургии, пока другой - можно.

2024-01-22 04:47 UTC, Den109G commented
Нёрфают эшей под видом QoL. ache

2024-02-09 20:36 UTC, Vladisvell requested changes
Замечания по коду

2024-02-09 20:36 UTC, Vladisvell commented on code/modules/hydroponics/grown/towercap.dm
> -			to_chat(usr, span_warning("You must dry this first!"))
Удаления крафта факела из тауэр-кэпов не было в предложке

2024-02-09 20:36 UTC, Vladisvell commented on code/game/objects/items/candle.dm
> +		T.hotspot_expose(700, 5)
Почти что копипаста родительского прока process (/obj/item/candle/process)
![изображение](https://github.com/ss220-space/Paradise/assets/73733747/e51e66f9-2051-4fe7-9a1f-0f2675991d60)

2024-12-27 18:28 UTC, closed without merging