add: new species meat
ss220-space/Paradise pull request #4259
Opened 2024-01-22 22:59 UTC by ArtemDerp

## Описание

Добавляет расам уникальное мясо
Убирает наименование мяса по его "владельцу" при гибе; дек может опознать мясо по ДНК
Убирает гуманоидные ошметки после гиббера у кпб и прочих
## Ссылка на предложение/Причина создания ПР

## Демонстрация изменений

![image](https://github.com/ss220-space/Paradise/assets/87157426/1c8e66e6-01d1-42cc-a790-1b9512147297)
![image](https://github.com/ss220-space/Paradise/assets/87157426/ab7b21b6-ab09-4b46-82f0-9d942c1e777e)
![image](https://github.com/ss220-space/Paradise/assets/87157426/08a1ff6b-ddf2-497b-a1dd-e8188fbe77b0)

2024-01-24 22:24 UTC, BeebBeebBoob approved these changes, later dismissed

2024-02-10 18:21 UTC, Vladisvell requested changes

2024-02-10 18:21 UTC, Vladisvell commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	icon_state = pick(type1, type2)
Это что?

2024-02-10 18:21 UTC, Vladisvell commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	icon_state = pick(type1, type2)
и это что?

2024-02-10 18:24 UTC, ArtemDerp commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	icon_state = pick(type1, type2)
у греев разноцветное мясо

2024-02-10 18:24 UTC, ArtemDerp commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	icon_state = pick(type1, type2)
у драсков разноцветное мясо

2024-02-10 18:40 UTC, Vladisvell approved these changes
На тестмерж

2024-02-12 19:41 UTC, merged