ref
ss220-space/Paradise pull request #4269
Opened 2024-01-24 17:16 UTC by SAADf603

## Описание
украли

## Ссылка на предложение/Причина создания ПР
нет

## Демонстрация изменений
не будет

2024-01-24 21:52 UTC, BeebBeebBoob requested changes
Глянь

2024-01-24 21:52 UTC, BeebBeebBoob commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
```suggestion
	. = ..()
	START_PROCESSING(SStransit_tube, src)
```

2024-01-24 21:52 UTC, BeebBeebBoob commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
> +	STOP_PROCESSING(transit_tube, src)
```suggestion
	STOP_PROCESSING(SStransit_tube, src)
```

2024-01-26 05:56 UTC, SAADf603 commented
Умные трубы настолько умнее меня, что выдают ошибку, когда глупенький маппер пытается направить на север под, который должен идти на юг... Вечером исправлю
спасибо родительскому проку при инициализации и бибу

2024-01-26 16:05 UTC, SAADf603 reviewed
Пришлось вставить назначение направления в инициализацю, что бы не выдавало рантайм

2024-01-27 21:27 UTC, BeebBeebBoob requested changes

2024-01-27 21:27 UTC, BeebBeebBoob commented on code/__DEFINES/directions.dm
> +//#define SOUTHWEST 10
Уже есть в code/_DEFINES/misc.dm
Удали тогда оттуда
И добавь заранее 
//#define UP 16
//#define DOWN 32

Или на добавляй. Я потом тогда добавлю

2024-01-27 21:27 UTC, BeebBeebBoob commented on code/controllers/subsystem/processing/transittube.dm
> +	cpu_display = SS_CPUDISPLAY_HIGH
Эм....

2024-01-27 21:27 UTC, BeebBeebBoob commented on code/controllers/subsystem/processing/transittube.dm
> +	cpu_display = SS_CPUDISPLAY_HIGH
Бери SS_CPUDISPLAY_DEFAULT
Эти трубы не сжирают как сжирают рунчат или мобы

2024-01-27 21:27 UTC, BeebBeebBoob commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
> +	if(!isnull(current_tube))
```suggestion
	if(current_tube) 
```
Что за дичь там оффы прописали и приняли? Ну типо. Не, не нулль? Не есть_нулль?

2024-01-27 21:27 UTC, BeebBeebBoob commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
> +	START_PROCESSING(SStransit_tube, src)
Ок смотри.
У нас спавниться на турфе и ему надо засунуться в трубу.
Для этого он вызывает pick(tube.directions()) и устанавливает себе тот, в который направлена сама труба, если маппер ленивая жопа.
После идёт вызов follow_tube()
Там мы ищем нашу трубу в котором мы находимся и мы также заверяем что впереди этой трубы есть выход
`if(tube.has_exit(dir))` на 155
Там и начинается процессинг перемещения трубы

2024-01-27 21:27 UTC, BeebBeebBoob commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
> +		return dir
```suggestion
	for(var/obj/structure/transit_tube/tube in loc)
		setDir(pick(tube.directions()))
		return dir
```
Попробуй это. Возможно в прошлый раз когда я тебе предложил процессинг туда засунуть, твоя труба чудом некорректно меняла направление.

2024-02-16 11:28 UTC, closed without merging