EX666_Cafeteria_RnD_Delta
ss220-space/Paradise pull request #4285
Opened 2024-01-27 06:36 UTC by mrWhiteFox365

## Описание
Обновить затхлый кафетерий, в который ходят, только из-за того что там удобно прятаться и доступа в тех. тоннели.
- Кафетерий и заброшенный телепортная поменяны местами;
- Теперь ученые на сойке могут быстрее добраться до техов;
- Добавлены новые шкафы у серверов НИО;
- В кафетерий добавлены парочка новых вкусностей;
Теперь в кафетерий видно что происходит, благодаря окнам и остекленному шлюзу.

## Ссылка на предложение/Причина создания ПР

## Демонстрация изменений
![Изменения1](https://github.com/ss220-space/Paradise/assets/145965244/5a6e854a-6368-43dc-9444-eba86c17ab79)
![Изменения2](https://github.com/ss220-space/Paradise/assets/145965244/a9412b92-b7ab-41de-8d51-5e160645a2a1)

2024-01-27 06:40 UTC, mrWhiteFox365 commented
> ## Описание
> 
> Обновить затхлый кафетерий, в который ходят, только из-за того что там удобно прятаться и доступа в тех. тоннели.
> 
>     * Кафетерий и заброшенный телепортная поменяны местами;
> 
>     * Теперь ученые на сойке могут быстрее добраться до техов;
> 
>     * В кафетерий добавлены парочка новых вкусностей;
>       Теперь в кафетерий видно что происходит, благодаря окнам и остекленному шлюзу.
> 
> 
> ## Ссылка на предложение/Причина создания ПР
> ## Демонстрация изменений
> 
> ![Изменения1](https://private-user-images.githubusercontent.com/145965244/300160131-5a6e854a-6368-43dc-9444-eba86c17ab79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzc3MjAsIm5iZiI6MTcwNjMzNzQyMCwicGF0aCI6Ii8xNDU5NjUyNDQvMzAwMTYwMTMxLTVhNmU4NTRhLTYzNjgtNDNkYy05NDQ0LWViYTg2YzE3YWI3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QwNjM3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTliMTQ3NTE2NjUyMWJlMjJiZTVlODc5NDFiZGUxYjg0NDk1YzJlNWU2OTNiYjhkNDg5MDQ0YmRmZGYzMTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6FpKP4qkI04Lt6XkxnBypInrhZqxjs0ZD2hKrIg2F6Y) ![Изменения2](https://private-user-images.githubusercontent.com/145965244/300160145-a9412b92-b7ab-41de-8d51-5e160645a2a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzc3MjAsIm5iZiI6MTcwNjMzNzQyMCwicGF0aCI6Ii8xNDU5NjUyNDQvMzAwMTYwMTQ1LWE5NDEyYjkyLWI3YWItNDFkZS04ZDUxLTVlMTYwNjQ1YTJhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QwNjM3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTM4MzI0OWIwZTRiYzVlNWVmYTJiM2VmMDU0ZDkwOTg2ZWRiOTRmOGRhM2U2YTVmM2UwZjQwZDk3M2RiOTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3V8-NUGNI0Up5YOeVQ-ADF6G6GeW2dNrKdib1uiFiwk)

2024-01-27 21:33 UTC, BeebBeebBoob commented
![image](https://github.com/ss220-space/Paradise/assets/32985153/b86e4010-11ad-4dbf-a66f-63aabcb7ba15)
Ты изменяешь большее чем изначально добавлял.
Плоха.
Сделай так:
1. Скачай карту отсюда, неизменённую версию.
2. В свой SDMM скопирую область того что ты изменил и вставь в скачанную версию. Главное чтобы ты копировал все, включая там зону(я забываю иногда когда копирую)
3. Замени этим свою карту в твоей папке.
4. Пулл и обнова сюда

2024-01-28 02:52 UTC, mrWhiteFox365 commented
> ![image](https://private-user-images.githubusercontent.com/32985153/300217422-b86e4010-11ad-4dbf-a66f-63aabcb7ba15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTA1MTMsIm5iZiI6MTcwNjQxMDIxMywicGF0aCI6Ii8zMjk4NTE1My8zMDAyMTc0MjItYjg2ZTQwMTAtMTFhZC00ZGJmLWE2NmYtNjNhYWJjYjdiYTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAyNTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YWJkYjFlZjU5Yzk5NDgyZTg0ZmE1OWZiNmFmNDNkMDE2ZjI5NmFkNTQwY2Y3M2FiNGM0NjNlZjJhNDEwZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zSoTXKq9XTvNqF_4hCqLHUECHvXNf5o1i7HRTSHy2GM) Ты изменяешь большее чем изначально добавлял. Плоха. Сделай так:
> 
>     1. Скачай карту отсюда, неизменённую версию.
> 
>     2. В свой SDMM скопирую область того что ты изменил и вставь в скачанную версию. Главное чтобы ты копировал все, включая там зону(я забываю иногда когда копирую)
> 
>     3. Замени этим свою карту в твоей папке.
> 
>     4. Пулл и обнова сюда

То есть мне надо скачать с ГитХаба оригинальную карту, и в нее занести изменения?

2024-01-28 02:53 UTC, mrWhiteFox365 commented
> ![image](https://private-user-images.githubusercontent.com/32985153/300217422-b86e4010-11ad-4dbf-a66f-63aabcb7ba15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTA1MTMsIm5iZiI6MTcwNjQxMDIxMywicGF0aCI6Ii8zMjk4NTE1My8zMDAyMTc0MjItYjg2ZTQwMTAtMTFhZC00ZGJmLWE2NmYtNjNhYWJjYjdiYTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAyNTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YWJkYjFlZjU5Yzk5NDgyZTg0ZmE1OWZiNmFmNDNkMDE2ZjI5NmFkNTQwY2Y3M2FiNGM0NjNlZjJhNDEwZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zSoTXKq9XTvNqF_4hCqLHUECHvXNf5o1i7HRTSHy2GM) Ты изменяешь большее чем изначально добавлял. Плоха. Сделай так:
> 
>     1. Скачай карту отсюда, неизменённую версию.
> 
>     2. В свой SDMM скопирую область того что ты изменил и вставь в скачанную версию. Главное чтобы ты копировал все, включая там зону(я забываю иногда когда копирую)
> 
>     3. Замени этим свою карту в твоей папке.
> 
>     4. Пулл и обнова сюда

Карта недавно обновлялась погляжу, делал до внесения изменений.
То есть мне надо скачать с ГитХаба оригинальную карту и внести изменения?

2024-01-28 03:02 UTC, mrWhiteFox365 commented
> Карта недавно обновлялась погляжу, делал до внесения изменений. То есть мне надо скачать с ГитХаба оригинальную карту и внести изменения?

![Без имени](https://github.com/ss220-space/Paradise/assets/145965244/51d59faa-0f88-4daa-91b5-51cb31bae578)

Попробовал я твой способ, и понял - МНЕ ТЕПЕРЬ ПРИДЕТСЯ ВЕСЬ РЕПОЗИТОРИЙ ОБНОВЛЯТЬ, пизда!!!

2024-01-28 04:14 UTC, BeebBeebBoob commented
Ты сохрани свою измененную версию отдельно от репозитория и плюс новую скачанную. 
Обнови и засунь свою старую плюс новую. Оба открой. Из старой скопирую своё изменение в новую и потом сохрани новую. Старую оставь на пожарный отдельно от изменений. Делай коммит.

2024-01-28 09:39 UTC, mrWhiteFox365 commented
Вообщем, достал старую отдельно, обновил, теперь она не открывается.

![Без имени](https://github.com/ss220-space/Paradise/assets/145965244/daa6a514-1bb6-4716-85d8-237c2a3a3286)

2024-01-28 10:04 UTC, mrWhiteFox365 commented
Нифига не получается как бы не колдовал, когда открывается одна карта, не открывается другая. И наоборот...

2024-01-28 12:15 UTC, mrWhiteFox365 commented
> Нифига не получается как бы не колдовал, когда открывается одна карта, не открывается другая. И наоборот... Открываются только на оригинальной ветке master220

Ура, мердж конфликт побежден. Да здравствует обнова.

2024-01-28 14:10 UTC, SAADf603 requested changes
1) Заменить стеклянную дверь на непрозрачную 
![image](https://github.com/ss220-space/Paradise/assets/110329212/c21d2b8f-9dba-4a96-b5fd-2d456ff85df0)
2) Удалить лишний провод 
![image](https://github.com/ss220-space/Paradise/assets/110329212/cd29cd00-e913-4a86-94cd-0181d92948b2)
3) Нет обводки голопада
![image](https://github.com/ss220-space/Paradise/assets/110329212/d39f241c-b627-413a-827c-36b69001bb32)

2024-01-28 14:25 UTC, SAADf603 requested changes
4) Две лампы слишком близко
![image](https://github.com/ss220-space/Paradise/assets/110329212/178bdc95-921e-4c8c-8598-21740dfb7e9f)
5) Вернуть на место
![image](https://github.com/ss220-space/Paradise/assets/110329212/c870bab7-bea7-4409-bf8d-0d8c2142c877)
6) Стены заменить на укреплённые 
![image](https://github.com/ss220-space/Paradise/assets/110329212/cdc3fd74-bf1e-4d64-94ed-d44c0c20d0d3)

2024-01-30 04:39 UTC, mrWhiteFox365 commented
>     6. Стены заменить на укреплённые
>        ![image](https://private-user-images.githubusercontent.com/110329212/300269598-cdc3fd74-bf1e-4d64-94ed-d44c0c20d0d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODk4NDMsIm5iZiI6MTcwNjU4OTU0MywicGF0aCI6Ii8xMTAzMjkyMTIvMzAwMjY5NTk4LWNkYzNmZDc0LWJmMWUtNGQ2NC05NGVkLWQ0NGMwYzIwZDBkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwNDM5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDg1OWYyY2Y4YzA1NTgxOWUzZWU1OWI5OTgwNDk1NjE2ZWFmYTFmZDQzZWVmMDdmZmRlMGFhYmIzMTZkNzU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0aqAS1FaDPTFxDZUr4Wjy-fhdDrMgQ0itf7VlyS3mfQ)

Готово.

2024-02-01 15:47 UTC, SAADf603 submitted a review, later dismissed

2024-02-08 01:50 UTC, ArtemDerp commented
@SAADf603 жаб жабыч, рано вы апрув кинули 
как посылку в робо отправить? clueless
![StrongDMM-2024-02-08 04 45 54](https://github.com/ss220-space/Paradise/assets/87157426/31c6a8fc-c33a-4d79-900c-5bb957a099a9)

2024-02-08 01:57 UTC, TrashDoxx commented
Накладываю вето.

2024-02-08 03:18 UTC, mrWhiteFox365 commented
> @SAADf603 жаб жабыч, рано вы апрув кинули как посылку в робо отправить? clueless

Все, вправил. Проверяй.

2024-02-08 14:07 UTC, mrWhiteFox365 commented
> Накладываю вето.

Всё, пофиксил, снимай вето и вперед, пока не обновился повторно.
![Без имени](https://github.com/ss220-space/Paradise/assets/145965244/f7da6499-1b23-4359-8358-7ef98c56235d)

2024-02-09 15:46 UTC, TrashDoxx commented
> Всё, пофиксил, снимай вето и вперед, пока не обновился повторно.

Снимаю вето. Можно мержить.

2024-02-10 18:11 UTC, SAADf603 approved these changes, later dismissed

2024-02-16 13:43 UTC, Vladisvell approved these changes

2024-02-17 04:56 UTC, SAADf603 approved these changes

2024-02-17 09:06 UTC, BeebBeebBoob approved these changes

2024-02-17 09:10 UTC, merged