bugfix: critter crates allow animals to live inside safely
ss220-space/Paradise pull request #4287
Opened 2024-01-27 14:11 UTC by PavelPoltavets

## Описание
Позволяет безопасно транспортировать животных в ящиках для животных (НЕ переносках) не позволяя животному задохнуться или умереть от температуры
##Причина создания ПР
Как в описания под ящиком и сказано 
"A crate designed for safe transport of animals..." (Ящик спроэктированый для безопасной транспортировки животных)
и без этого ПР ящик этого не делает...

2024-01-27 14:56 UTC, Gottfrei commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	var/minbodytemp_buf
это нужно хранить не в животном, а в ящике, в списке ассоциативном.

2024-01-27 17:56 UTC, BeebBeebBoob requested changes

2024-01-27 17:56 UTC, BeebBeebBoob commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +		M.minbodytemp = 0
Я думаю это уже обсуждалось насколько это костыльно. А что если клетку чудом сломают и тогда мы получим животное которому больше не грозит космос.
var/gas_mixture/air в руки и переделывать иначе это кошмар.
Я и так ору что этот ящик нельзя уничтожить взрывом(разбомбил всю станцию. Выжили холодильник и это чудо ящик животных.)
пупсо костыльность стонкс

2024-01-27 21:41 UTC, PavelPoltavets commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +		M.minbodytemp = 0
> Я думаю это уже обсуждалось насколько это костыльно. А что если клетку чудом сломают и тогда мы получим животное которому больше не грозит космос. var/gas_mixture/air в руки и переделывать иначе это кошмар. Я и так ору что этот ящик нельзя уничтожить взрывом(разбомбил всю станцию. Выжили холодильник и это чудо ящик животных.) пупсо костыльность стонкс

это же не open() метод, а dump_contents() который отвечает за выпадение с шкафа так что если он не сработает мобы тупо не выпадут и тогда без разницы если моб сможет дышать безопасно ведь его не будет существовать в мире...

2024-01-27 21:47 UTC, BeebBeebBoob commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +		M.minbodytemp = 0
Здесь ты прав. И всё же факт что это сделано подобным образом очень смехотворно.
Я же показал что можно тупо сделать /gas_mixture/air
дать ему воздух
и при обработке мобами воздух, не тратить сам воздух.
И не надо будет присваивать столь подобные костыльные методы.

2024-01-27 21:55 UTC, PavelPoltavets commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	var/minbodytemp_buf
по погике да... но принято такое решение чтоб экономить память на связи листа + меньше кода из-за отсуствия работы с листом,  да и моб в двух таких ящиках сидеть одновременно явно не может... 
по твоему мне все-равно лучше переписать под лист?

2024-01-27 22:00 UTC, PavelPoltavets commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +		M.minbodytemp = 0
как по мне var/gas_mixture/air это кошмар...
у нас мобы умирают если каким либо образом оказываются в подах или мехах и не всегда важно в космосе мех или под, или нет... да и юз var/gas_mixture/air по сути позволит и людям в ящике сейвиться (а это по идее не то что этот ящик должен делать, НАВЕРНОЕ....)

2024-01-27 22:23 UTC, BeebBeebBoob commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +		M.minbodytemp = 0
> как по мне var/gas_mixture/air это кошмар...

Добро пожаловать в кодинг. Ты либо пишешь для себя, в своём удобном стиле, где ты разрешаешь себе хоть миллионы костылей. Либо пишешь в группе других кодеров, где нужно уметь писать не только для себя, но и для других адекватно.
Я единственный кто указывает, что исправлять подобное таким образом, плохо. Может кто-то другой также меня поддержит в этом плане.
> у нас мобы умирают если каким либо образом оказываются в подах или мехах и не всегда важно в космосе мех или под

Если это реально правда что простые мобы подыхают в поде, то надо тогда это решать в первую очередь!

>  да и юз var/gas_mixture/air по сути позволит и людям в ящике сейвиться

Ну да, позволит. Я не вижу в этом какой либо проблемы, что человек решит спрятаться в ящике животных.
Мы тогда просто сделаем так, что в итоге воздух закончиться. И это не только не даст возможность людям спасаться в ящике, но и враждебным животным(если им кто-то закроет ящик).

И ещё кое-что
```
	var/mutations_buf
	var/atmos_requirements_buf
	var/minbodytemp_buf
```
Вот просто нет. Честно. Делать три целых новых перемен лишь только его использовать в особом случае с ящиками животных, это абсурд. 
Вот делай var/datum/gas_mixture/air и всё, либо оставь этот баг в покое.

Я в дискорде тебе написал как правильно обработать этот ящик с помощью /datum/gas_mixture/air
У меня единственное заключение что ты спустил рукава и сказал "И так сойдёт". Плохо.

2024-01-27 23:26 UTC, Gottfrei commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	var/minbodytemp_buf
по-моему, это всё нужно удалить и написать нормальную реализацию атмосферы в ящике. но возвращаясь к тому что есть, забивать дерево переменных, у каждого моба в игре, тремя дополнительными использующимися раз в никогда, точно хуже, чем список.

2024-01-30 08:32 UTC, Gottfrei commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	updateEnv()
а зачем здесь эти проверки?

2024-01-30 08:35 UTC, Gottfrei commented on code/modules/mob/living/living.dm
> +	return environment.temperature
ты сейчас сломал систему по которой всегда возвращается температура T0C, в случае если аргумент environment не получен.

2024-01-30 10:15 UTC, PavelPoltavets commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	updateEnv()
> а зачем здесь эти проверки? как и те что ниже в коде.

чтоб воздух превращался в карбондеоксид в случае если туда залезет человек что дышать умеет... чтоб люди не залазили в коробку для животных...

2024-01-30 10:23 UTC, PavelPoltavets commented on code/modules/mob/living/living.dm
> +	return environment.temperature
тоесть такой код вернет T0C если environment = null?
proc/get_temperature(datum/gas_mixture/environment)
  var/loc_temp = T0C
  loc_temp = environment.temperature
  return loc_temp
  
  оно ж явно кинет ексепшн если будет случай что ты описал, а там такой код и был...

2024-01-30 10:25 UTC, PavelPoltavets commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	updateEnv()
чтоб люди не дышали воздухом в коробках предназначеным для животных -_-

2024-01-30 11:08 UTC, Gottfrei commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	updateEnv()
а что есть проблема в том, что хуманы там будут дышать? вообще если прямо совсем по хорошему сделать, можно добавить специальный ксилородный баллон в яшик (можно маленького размера), от которого и будет происходить дыхание существа. ну также возможность этот баллон менять инструментами.

2024-01-30 11:15 UTC, PavelPoltavets commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	updateEnv()
ну может кто то другой мне мук с gas_mixture хватило...

2024-02-16 13:32 UTC, Vladisvell submitted a review, later dismissed

2024-02-17 05:09 UTC, BeebBeebBoob requested changes

2024-02-17 05:09 UTC, BeebBeebBoob commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	updateEnv()
А тебе точно надо каждый раз обновлять воздух? 
Ты нигде не прописал что ты меняешь воздух, так что смысл повторно устанавливать и не изменённые переменные не требуется.

2024-02-17 05:09 UTC, BeebBeebBoob commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	updateEnv()
Также
```suggestion
/obj/structure/closet/critter/assume_air(datum/gas_mixture/giver)
	return null
```

2024-02-17 05:09 UTC, BeebBeebBoob commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	return env
```suggestion
/obj/structure/closet/critter/remove_air(amount)
	return env
```

2024-02-17 05:09 UTC, BeebBeebBoob commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	updateEnv()
```suggestion
/obj/structure/closet/critter/return_air()
	return env
```

2024-02-19 05:06 UTC, PavelPoltavets commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	updateEnv()
> А тебе точно надо каждый раз обновлять воздух? Ты нигде не прописал что ты меняешь воздух, так что смысл повторно устанавливать и не изменённые переменные не требуется.

дыхание у гуманоидов превращают воздух в СО2. апдейт нужен чтоб воздух восстановить когда человек покинет коробку.

2024-03-05 09:39 UTC, PavelPoltavets commented on code/game/objects/structures/crates_lockers/crittercrate.dm
> +	updateEnv()
Счастлив теперь?

2024-03-06 22:02 UTC, BeebBeebBoob approved these changes

2024-03-09 07:25 UTC, Vladisvell approved these changes

2024-03-09 07:29 UTC, merged