bugfix: changed inflatable box weight class
ss220-space/Paradise pull request #4298
Opened 2024-01-28 19:22 UTC by ArtemDerp

## Описание

Увеличен размер кейса для надувных дверей. Закрыт абуз дополнительных слотов через этот кейс. Кейс все еще вмещает в себя не только барьеры.
## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/1201236462935478312

2024-01-29 01:41 UTC, LiquidPotroh commented
Удоляй, фича

2024-01-29 20:41 UTC, Herobrine998 commented
Ошибок в коде нету, почему решили что баг не понятно

2024-01-29 21:06 UTC, NightDawnFox commented
Пришли охранители манча, которые соревнуются на скорость добычи этого контейнера, чтобы хранить там тонны говна. Всё правильно делаешь.

2024-01-30 06:53 UTC, SAADf603 requested changes

2024-01-30 06:53 UTC, SAADf603 commented on code/game/objects/structures/inflatable.dm
> +	w_class = WEIGHT_CLASS_BULKY
```suggestion
	w_class = WEIGHT_CLASS_NORMAL
	can_hold = list(
	/obj/item/inflatable
	)
```

2024-01-30 06:53 UTC, SAADf603 commented on code/game/objects/structures/inflatable.dm
> +	w_class = WEIGHT_CLASS_BULKY
это в разы лучше того, что бы делать чемоданчик размером с корпус от меха

2024-02-13 16:21 UTC, closed without merging