add: stok resprite
ss220-space/Paradise pull request #4322
Opened 2024-01-31 14:50 UTC by ArtemDerp

## Описание

Оранжевые стоки заменены на зеленых с хвостом
## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/755125334097133628/1202254653757333537
## Демонстрация изменений

![image](https://github.com/ss220-space/Paradise/assets/87157426/2091f631-05d6-4924-9172-f70b0bf2a5c7)

2024-02-09 20:21 UTC, Vladisvell approved these changes

2024-02-11 08:28 UTC, SAADf603 approved these changes

2024-02-15 00:19 UTC, BeebBeebBoob requested changes

2024-02-15 00:19 UTC, BeebBeebBoob commented on icons/obj/objects.dmi
Удалить _old иконку.

2024-02-15 01:10 UTC, BeebBeebBoob approved these changes

2024-02-15 01:20 UTC, merged