Обновление теты
ss220-space/Paradise pull request #4346
Opened 2024-02-03 03:12 UTC by Rafnik02

Немного обновлена тета

## Описание

## Ссылка на предложение/Причина создания ПР

 https://discord.com/channels/617003227182792704/755125334097133628/1202349334532993074 

## Демонстрация изменений
![Desktop Screenshot 2024 01 24 - 19 50 15 77](https://github.com/ss220-space/Paradise/assets/141545822/5b8d08d9-a944-46cd-896e-1892ec0d025b)

2024-02-03 03:36 UTC, pilygun commented
Долгожданное обновление теты "Две блевоты и стул" апдейт

2024-02-03 04:17 UTC, Rafnik02 commented
> Долгожданное обновление теты "Две блевоты и стул" апдейт

Мы дождались

2024-02-03 04:47 UTC, SAADf603 commented
маппер наебал бригадира на раздатчик. обновление отменяется

2024-02-03 05:23 UTC, TrashDoxx commented
Накладываю вето.

2024-02-03 05:48 UTC, Rafnik02 commented
> маппер наебал бригадира на раздатчик. обновление отменяется

Как? Я не добавлял его.

2024-02-03 05:48 UTC, Rafnik02 commented
> маппер наебал бригадира на раздатчик. обновление отменяется

Это старый скрин. Просто не тот скриншот вставил

2024-02-03 05:55 UTC, SAADf603 commented
> > маппер наебал бригадира на раздатчик. обновление отменяется
> 
> Это старый скрин. Просто не тот скриншот вставил

![image](https://github.com/ss220-space/Paradise/assets/110329212/f6486122-911b-455b-a5db-ed0f118c7212)
Это в смысле теттовцы настолько бомжи, что у них теперь не должно быть семян, помимо винограда, вообще?

2024-02-03 05:57 UTC, Rafnik02 commented
> > > маппер наебал бригадира на раздатчик. обновление отменяется
> > 
> > 
> > Это старый скрин. Просто не тот скриншот вставил
> 
> ![image](https://private-user-images.githubusercontent.com/110329212/302016099-f6486122-911b-455b-a5db-ed0f118c7212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NDAwNDIsIm5iZiI6MTcwNjkzOTc0MiwicGF0aCI6Ii8xMTAzMjkyMTIvMzAyMDE2MDk5LWY2NDg2MTIyLTkxMWItNDU1Yi1hNWRiLWVkMGYxMThjNzIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwNTU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWE2NjczNTc4ZDQ5ODYyYTUwNDYxNjZjZmE3ZmE2MzIxOTJlNWUzZTIyMWQ5M2Q1NWEwZDNjMDQ4MmZlYjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-t_kOGbnFuZBcKfbvCO7QrWVru_5uERBC3vbbHsSeSI) Это в смысле теттовцы настолько бомжи, что у них теперь не должно быть семян, помимо винограда, вообще?

Вы две недели назад говорили, что раздатчик семян не нужен. Ну ладно, добавлю его

2024-02-03 05:58 UTC, SAADf603 commented
![image](https://github.com/ss220-space/Paradise/assets/110329212/c390b267-ef18-4aa2-9446-c6cc35c1425a)
Писали, что добавлен. А по итогу не добавлен, а в тупую убран и даже не заменён на коробку с семенами......

2024-02-03 05:58 UTC, NightDawnFox commented
> > > > маппер наебал бригадира на раздатчик. обновление отменяется
> > > 
> > > 
> > > Это старый скрин. Просто не тот скриншот вставил
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/110329212/302016099-f6486122-911b-455b-a5db-ed0f118c7212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NDAwNDIsIm5iZiI6MTcwNjkzOTc0MiwicGF0aCI6Ii8xMTAzMjkyMTIvMzAyMDE2MDk5LWY2NDg2MTIyLTkxMWItNDU1Yi1hNWRiLWVkMGYxMThjNzIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwNTU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWE2NjczNTc4ZDQ5ODYyYTUwNDYxNjZjZmE3ZmE2MzIxOTJlNWUzZTIyMWQ5M2Q1NWEwZDNjMDQ4MmZlYjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-t_kOGbnFuZBcKfbvCO7QrWVru_5uERBC3vbbHsSeSI) Это в смысле теттовцы настолько бомжи, что у них теперь не должно быть семян, помимо винограда, вообще?
> 
> Вы две недели назад говорили, что раздатчик семян не нужен. Ну ладно, добавлю его

Ну так это было 2 недели назад! А сегодня это сегодня.

2024-02-03 05:59 UTC, SAADf603 commented
> > > > > маппер наебал бригадира на раздатчик. обновление отменяется
> > > > 
> > > > 
> > > > Это старый скрин. Просто не тот скриншот вставил
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/110329212/302016099-f6486122-911b-455b-a5db-ed0f118c7212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NDAwNDIsIm5iZiI6MTcwNjkzOTc0MiwicGF0aCI6Ii8xMTAzMjkyMTIvMzAyMDE2MDk5LWY2NDg2MTIyLTkxMWItNDU1Yi1hNWRiLWVkMGYxMThjNzIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwNTU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWE2NjczNTc4ZDQ5ODYyYTUwNDYxNjZjZmE3ZmE2MzIxOTJlNWUzZTIyMWQ5M2Q1NWEwZDNjMDQ4MmZlYjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-t_kOGbnFuZBcKfbvCO7QrWVru_5uERBC3vbbHsSeSI) Это в смысле теттовцы настолько бомжи, что у них теперь не должно быть семян, помимо винограда, вообще?
> > 
> > 
> > Вы две недели назад говорили, что раздатчик семян не нужен. Ну ладно, добавлю его
> 
> Ну так это было 2 недели назад! А сегодня это сегодня.


social schizophrenia

2024-02-03 06:59 UTC, ItsMeJaba commented
> > > > > > маппер наебал бригадира на раздатчик. обновление отменяется
> > > > > 
> > > > > 
> > > > > Это старый скрин. Просто не тот скриншот вставил
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/110329212/302016099-f6486122-911b-455b-a5db-ed0f118c7212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NDAwNDIsIm5iZiI6MTcwNjkzOTc0MiwicGF0aCI6Ii8xMTAzMjkyMTIvMzAyMDE2MDk5LWY2NDg2MTIyLTkxMWItNDU1Yi1hNWRiLWVkMGYxMThjNzIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwNTU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWE2NjczNTc4ZDQ5ODYyYTUwNDYxNjZjZmE3ZmE2MzIxOTJlNWUzZTIyMWQ5M2Q1NWEwZDNjMDQ4MmZlYjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-t_kOGbnFuZBcKfbvCO7QrWVru_5uERBC3vbbHsSeSI) Это в смысле теттовцы настолько бомжи, что у них теперь не должно быть семян, помимо винограда, вообще?
> > > 
> > > 
> > > Вы две недели назад говорили, что раздатчик семян не нужен. Ну ладно, добавлю его
> > 
> > 
> > Ну так это было 2 недели назад! А сегодня это сегодня.
> 
> social schizophrenia

А какого там вообще раздатчик оказался? На кой настолько оказуаливать один из основных дрочей Тетты, если в этом дроче и суть роли?

2024-02-03 07:13 UTC, pilygun commented
Ребят Тета роль хуйни, дайте им вендор семян. На баланс и логику не повлияет. Предложки не требует ибо все напишут за пизда, да блять уже написали. Меняйте как Qol

2024-02-03 08:27 UTC, Rafnik02 commented
> ![image](https://private-user-images.githubusercontent.com/110329212/302016485-c390b267-ef18-4aa2-9446-c6cc35c1425a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NDAyMDAsIm5iZiI6MTcwNjkzOTkwMCwicGF0aCI6Ii8xMTAzMjkyMTIvMzAyMDE2NDg1LWMzOTBiMjY3LWVmMTgtNGFhMi05NDQ2LWM2Y2MzNWMxNDI1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwNTU4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWExYzcxY2JlNDEzODU1YWZkMzRjZDM5MDg2ZmNmZTI3OTc1ODE4YzE3YjA5ZDkyNDUzNDY4Y2E3YjUxYzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xifJc0DqFdXTbj1m5-66fNYkveEPx1eSloWNC9Xgse0) Писали, что добавлен. А по итогу не добавлен, а в тупую убран и даже не заменён на коробку с семенами......

Заменил на ящик с семянами. Конечно там не все, но базовые есть.

2024-02-03 09:57 UTC, BeebBeebBoob commented
> Предложение: Немного обновить тету.
> - Изменена кухня, сделавший её удобнее.
> - Добавлено в ботанику один тайл фунгуса
> - Добавлен синий скафандр рядом с красным в инженерии
> - Добавлены солнцезащитные очки, классическая бита(деревянная) на посту СБ.

Rafnik, делай за что голосовали. Обманывая людей, ты теряешь доверие к тебе и твоим ПРам. 
![image](https://github.com/ss220-space/Paradise/assets/32985153/117ad3af-e7c0-4935-946b-691daffc5304)
По MapDiffBotу видно что ты убрал раздатчик, заменив ящиком. Про это не было прописано в твоём ПРе. Тетовцы будут негодовать.
Иначе я тогда вот пойду, сделаю там ПР на бафф СБ, а вместе с этим удалю бригмеда и подпилота, заменив именами подпрофесси для СБ и врачей аля "Недо-бригмед" и "Недо-космоСБ".

2024-02-03 10:23 UTC, Rafnik02 commented
> > Предложение: Немного обновить тету.
> > 
> > * Изменена кухня, сделавший её удобнее.
> > * Добавлено в ботанику один тайл фунгуса
> > * Добавлен синий скафандр рядом с красным в инженерии
> > * Добавлены солнцезащитные очки, классическая бита(деревянная) на посту СБ.
> 
> Rafnik, делай за что голосовали. Обманывая людей, ты теряешь доверие к тебе и твоим ПРам. ![image](https://private-user-images.githubusercontent.com/32985153/302027749-117ad3af-e7c0-4935-946b-691daffc5304.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTQ1NzQsIm5iZiI6MTcwNjk1NDI3NCwicGF0aCI6Ii8zMjk4NTE1My8zMDIwMjc3NDktMTE3YWQzYWYtZTdjMC00OTM1LTk0NmItNjkxZGFmZmM1MzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDA5NTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YjMyYjQwNjRjMjZjZWJmMmU2ZjBjZmQxYjAzZTczZjc1MTAzOGM5ZmNhZGNjZDFhYzViNDRhMzgxNWVlYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6P3cSKegZeIwPTED8L1A8Xq2TWf3h8-nwWoazK0BqRE) По MapDiffBotу видно что ты убрал раздатчик, заменив ящиком. Про это не было прописано в твоём ПРе. Тетовцы будут негодовать. Иначе я тогда вот пойду, сделаю там ПР на бафф СБ, а вместе с этим удалю бригмеда и подпилота, заменив именами подпрофесси для СБ и врачей аля "Недо-бригмед" и "Недо-космоСБ".

Я делал предложку до обновы Зюзи. Так что, пускай он сам добавляет позже, если надо будет

2024-02-03 12:50 UTC, Rafnik02 commented
а долго ли ждать мерджа?

2024-02-03 14:59 UTC, ArtemDerp commented
> а долго ли ждать мерджа?

3 года :clueless:

2024-02-03 15:27 UTC, LiquidPotroh commented
Мой дед ждал мерджа, и вы подождете

2024-02-03 16:33 UTC, pilygun commented
> Мой дед ждал мерджа, и вы подождете

Скока там димач мержил вайтлист для ножевой кобуры? 3-4 месяца? Короче крепись мужик ждать долго, или нет хз, но там дохуя ПРов в очереди

2024-02-10 17:36 UTC, SAADf603 requested changes
Будем основываться на ТЗ, с которым я согласилась.
![image](https://github.com/ss220-space/Paradise/assets/110329212/7541b101-6588-43a3-95e1-294c5377982f)

Не вижу в ТЗ этого:
![image](https://github.com/ss220-space/Paradise/assets/110329212/1f1d6401-b94e-4249-b394-92ec5823059b)

Почему-то вижу это:
![image](https://github.com/ss220-space/Paradise/assets/110329212/68b78fe7-a3f4-4cde-be77-03420605a5ee)

Помимо этого, фунгус должен располагаться ИСКЛЮЧИТЕЛЬНО на стенах.

2024-02-11 06:33 UTC, Rafnik02 commented
> Будем основываться на ТЗ, с которым я согласилась. ![image](https://private-user-images.githubusercontent.com/110329212/303855190-7541b101-6588-43a3-95e1-294c5377982f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzMzNDcsIm5iZiI6MTcwNzYzMzA0NywicGF0aCI6Ii8xMTAzMjkyMTIvMzAzODU1MTkwLTc1NDFiMTAxLTY1ODgtNDNhMy05NWUxLTI5NGM1Mzc3OTgyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwNjMwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDNkYjUzNDMyMGNiMzVhZmUzNGM3OGNkYzNkNzRiNGU2ZThkODE0ZDViODhjMjRkYjc3NDc4Zjk4ZTAyMzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cA5mR5wj73mi9kji3ReVcCXiiUWr49gLXO82akf3sp4)
> 
> Не вижу в ТЗ этого: ![image](https://private-user-images.githubusercontent.com/110329212/303855251-1f1d6401-b94e-4249-b394-92ec5823059b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzMzNDcsIm5iZiI6MTcwNzYzMzA0NywicGF0aCI6Ii8xMTAzMjkyMTIvMzAzODU1MjUxLTFmMWQ2NDAxLWI5NGUtNDI0OS1iMzk0LTkyZWM1ODIzMDU5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwNjMwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWRmYzQzZjU1OWRhODY2NjY3ZThmM2ZjZjRiNDgwNjA1OTk5Y2M5MzYxOGYwNzA5NmFlODU3MzRkYWFlYjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EjVgvlWm7NVX3F8gFXgAbj2vnvsoa1FW6gLcKV8G0y4)
> 
> Почему-то вижу это: ![image](https://private-user-images.githubusercontent.com/110329212/303855322-68b78fe7-a3f4-4cde-be77-03420605a5ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzMzNDcsIm5iZiI6MTcwNzYzMzA0NywicGF0aCI6Ii8xMTAzMjkyMTIvMzAzODU1MzIyLTY4Yjc4ZmU3LWEzZjQtNGNkZS1iZTc3LTAzNDIwNjA1YTVlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwNjMwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzM1NjI1NzExOGZhODJjMWY2NGU5MWMwZDM4MThkODBmNDdlNjU3ZjA2OWM1ZDFlOWIzOWRkZDU3NWNjNDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.85YwzxFyXu76EL9_g4Qd5zPQ88HXiw8Vevf3v97QG5E)
> 
> Помимо этого, фунгус должен располагаться ИСКЛЮЧИТЕЛЬНО на стенах.
1. Швабру уберу
2. Семена верну
3. Фунгус переставлю на стену

2024-02-19 13:42 UTC, Rafnik02 commented
теперь я верю, что надо ждать год для мерджа

2024-02-21 10:28 UTC, SAADf603 approved these changes

2024-02-21 11:35 UTC, merged