experiment: dark theme, colors, font-awesome, blob update
ss220-space/Paradise pull request #4354
Opened 2024-02-04 16:47 UTC by ROdenFL

## Описание
Обновление font-awesome
Доделаная темная тема
Смена некоторых цветов темной темы
Обновление цвета сообщений блоба

## Ссылка на предложение/Причина создания ПР
Обновление спорно встреченного ранее пра

## Демонстрация изменений

2024-02-09 21:02 UTC, Vladisvell requested changes
В целом изменения хорошие, нужно оценивать на тестмерже

2024-02-09 21:02 UTC, Vladisvell commented on code/game/gamemodes/blob/blobs/blob_mobs.dm
> +	var/rendered = "<i><span class='blob'>Blob Telepathy,<span> <span class='name'>[name]([overmind])</span> states, <span class='blob'>\"[message]\"</span></i>"
Незакрытый спан?

2024-02-09 21:52 UTC, ROdenFL commented on code/game/gamemodes/blob/blobs/blob_mobs.dm
> +	var/rendered = "<i><span class='blob'>Blob Telepathy,<span> <span class='name'>[name]([overmind])</span> states, <span class='blob'>\"[message]\"</span></i>"
Слеш забыл

2024-02-09 22:00 UTC, ArtemDerp commented on code/game/gamemodes/blob/blobs/blob_mobs.dm
> +	var/rendered = "<i><span class='blob'>Blob Telepathy,<span> <span class='name'>[name]([overmind])</span> states, <span class='blob'>\"[message]\"</span></i>"
```suggestion
	var/rendered = "<i><span class='blob'>Blob Telepathy,</span> <span class='name'>[name]([overmind])</span> states, <span class='blob'>\"[message]\"</span></i>"
```
возвращаю слеш

2024-02-10 00:32 UTC, BeebBeebBoob commented on goon/browserassets/css/browserOutput-dark.css
> +/* .proradio				{color: #b84f92;} */
Почему?

2024-02-10 05:35 UTC, ROdenFL commented on goon/browserassets/css/browserOutput-dark.css
> +/* .proradio				{color: #b84f92;} */
Комментирование делает так что цвет дерётся из светлой темы

2024-02-10 15:46 UTC, Vladisvell submitted a review, later dismissed

2024-02-12 01:15 UTC, ROdenFL commented on code/modules/client/client_procs.dm
> +   winset(src, "rpane.webmap", "background-color=none;text-color=#000000")
```suggestion
	winset(src, "rpane.webmap", "background-color=none;text-color=#000000")
```

2024-02-12 01:20 UTC, ROdenFL commented on code/modules/client/client_procs.dm
> +	winset(src, "rpane.forumb", "background-color=#494949;text-color=#a4bad6")
```suggestion
```

2024-02-12 15:50 UTC, ROdenFL commented
@Vladisvell нажмите кнопочку аппруве

2024-02-16 13:46 UTC, Vladisvell approved these changes

2024-02-17 04:33 UTC, BeebBeebBoob approved these changes

2024-02-17 06:53 UTC, SAADf603 approved these changes

2024-02-17 06:57 UTC, merged