Позволяет выгружать из БРПЕДА части нужного качества
ss220-space/Paradise pull request #436
Opened 2021-11-07 12:26 UTC by botka4aet

## What Does This PR Do
Позволяет установить уровень выгрузки для БРПЕДА в 4 режиме.
Все предметы с таким уровнем и ниже будут выгружены при использовании БРПЕДА в руке

## Why It's Good For The Game
Позволяет выгружать устаревшие модули не по одному, а целой пачкой.

## Changelog
:cl:
add: Позволяет выгружать из БРПЕДА части нужного качества
/:cl:

2021-11-08 22:11 UTC, Bizzonium commented on code/game/objects/items/weapons/stock_parts.dm
> +	if(usr.a_intent == INTENT_HARM) //Меняем режим выгрузки
что-то мне не нравится использование `usr`

2021-11-08 22:12 UTC, Bizzonium commented on code/game/objects/items/weapons/stock_parts.dm
> +		to_chat(usr, "<span class='notice'>[src.name] будет выгружать предметы рангом [empty_mode] и ниже.</span>")
здесь тоже `usr`

2021-11-08 22:12 UTC, Bizzonium commented on code/game/objects/items/weapons/stock_parts.dm
> +		hide_from(usr)
И тут `usr`

2021-11-12 17:33 UTC, Bizzonium requested changes
йо, прочитай комменты

2021-12-16 01:27 UTC, botka4aet commented
А, я слепой

2021-12-16 02:42 UTC, closed without merging