refactor: Service unit really service
ss220-space/Paradise pull request #4361
Opened 2024-02-06 16:15 UTC by RuinaRuiner

## Описание
- Рефактор сервисного юнита и добавление ему инструментов для ботаники и приготовления еды
- Добавлен новый ручной раздатчик - кухонный, в нем есть специи для некоторых блюд, по типу соли, перца , кетчупа и трав.
- Добавлено улучшение для юнита, которое заменяет ему ведро на бс бикер.
- Добавлен в рецепт улучшения, который можно создать в конструкторе мехов

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1204317095106707496

## Демонстрация изменений
https://cdn.discordapp.com/attachments/1204118788757393529/1204445671344701450/image.png?ex=65d4c271&is=65c24d71&hm=265e7d6aa4c88a337486d481e25d523fef892af07f21cf24f98a23e07ced77a3&
https://cdn.discordapp.com/attachments/1204118788757393529/1204446146593038419/image.png?ex=65d4c2e2&is=65c24de2&hm=2a67d70cfc1fb8d55bb770ab43d1d5a9e11da919df9d19f4920ae00ce48fc379&
https://cdn.discordapp.com/attachments/1204118788757393529/1204453236107509760/image.png?ex=65d4c97d&is=65c2547d&hm=2bf1464c6db5098bd0b2bf51a943dec7b00989e0ce6fe67b2677c5265501baef&

2024-02-06 17:52 UTC, Vladisvell requested changes

2024-02-06 17:52 UTC, Vladisvell commented on code/modules/research/designs/mechfabricator_designs.dm
>  /datum/design/borg_upgrade_abductor_engi
добавь пустые строки для отделения датумов

2024-02-06 17:55 UTC, RuinaRuiner commented on code/modules/research/designs/mechfabricator_designs.dm
>  /datum/design/borg_upgrade_abductor_engi
Оки, спасибо за заметку

2024-02-07 06:56 UTC, Vladisvell requested changes
Минорные замечания

2024-02-07 06:56 UTC, Vladisvell commented on code/modules/research/designs/mechfabricator_designs.dm
> +/datum/design/service_bs_beaker
```suggestion
	category = list("Cyborg Upgrade Modules")

/datum/design/service_bs_beaker
```

2024-02-07 06:56 UTC, Vladisvell commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +/obj/item/robot_module/butler/respawn_consumable(mob/living/silicon/robot/R)
```suggestion

/obj/item/robot_module/butler/respawn_consumable(mob/living/silicon/robot/R)
```

2024-02-07 06:56 UTC, Vladisvell commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/item/borg/upgrade/bs_beaker/deactivate(mob/living/silicon/robot/robot, mob/user)
```suggestion

/obj/item/borg/upgrade/bs_beaker/deactivate(mob/living/silicon/robot/robot, mob/user)
```

2024-02-07 06:56 UTC, Vladisvell commented on code/game/objects/items/robot/robot_upgrades.dm
> +
```suggestion
```

2024-02-07 06:56 UTC, Vladisvell commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	..()
```suggestion
	..()

```

2024-02-07 06:56 UTC, Vladisvell commented on code/modules/research/designs/mechfabricator_designs.dm
> +	name = "Cyborg Service Upgrade"
```suggestion
	name = "Cyborg Service Upgrade (Bluespace Beaker)"
```

2024-02-10 15:47 UTC, RuinaRuiner commented on code/game/objects/items/robot/robot_upgrades.dm
> +
Спасибо за критику, буду ждать мерджа и еще критики

2024-02-23 12:05 UTC, RuinaRuiner commented
> Минорные замечания

Можешь пожалуйста подсказать, почему конфликт, либо я в глаза долблюсь либо хз

2024-02-29 07:03 UTC, Vladisvell submitted a review, later dismissed

2024-03-02 11:52 UTC, BeebBeebBoob commented on code/game/objects/items/robot/robot_upgrades.dm
> -
wtf

2024-03-02 12:16 UTC, BeebBeebBoob requested changes

2024-03-02 12:16 UTC, BeebBeebBoob commented on code/modules/research/designs/mechfabricator_designs.dm
> +/datum/design/service_bs_beaker
Всё ещё не решено.

2024-03-08 05:35 UTC, BeebBeebBoob approved these changes

2024-03-09 07:24 UTC, Vladisvell approved these changes

2024-03-09 07:29 UTC, merged