add: Adidas Uniforms
ss220-space/Paradise pull request #4381
Opened 2024-02-09 14:59 UTC by Gottfrei

## Описание
В вендомат AutoDrobe и лоадаут добавлена спортивная униформа, в стилистике "Адидас" . 4 вариации цвета: красная, синяя, белая, чёрная.

Чёрный и белый цвет требует первый уровень подписки, для выбора в лоадауте.

Подходит для всех рас, даже макак. Сугубо косметическая одежда, без плюсов и минусов.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1187683815792054332

2024-02-09 20:50 UTC, Vladisvell approved these changes

2024-02-10 18:04 UTC, SAADf603 requested changes
Ну что я могу сказать...
![image](https://github.com/ss220-space/Paradise/assets/110329212/5251ef2b-b916-404a-ad1f-4f1752c4cab7)

Опять вульпинканский БЕНИС точит
![image](https://github.com/ss220-space/Paradise/assets/110329212/d3e26bc1-7f01-4622-b78e-a125f4f5c060)
Хоть убей, но колет глаз. Добавь пару проклятых пикселей. 
Во всём остальном хорошо.

2024-02-10 18:04 UTC, SAADf603 commented on code/game/machinery/vending.dm
> +					/obj/item/clothing/under/orangehawaiianshirt = 1,
ПУПС БЛЯТЬ????
![image](https://github.com/ss220-space/Paradise/assets/110329212/56e5a60b-67d8-4761-bd62-f44f7bcfcf27)

2024-02-10 18:06 UTC, SAADf603 commented
> Ну что я могу сказать... ![image](https://private-user-images.githubusercontent.com/110329212/303856544-5251ef2b-b916-404a-ad1f-4f1752c4cab7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODg1OTksIm5iZiI6MTcwNzU4ODI5OSwicGF0aCI6Ii8xMTAzMjkyMTIvMzAzODU2NTQ0LTUyNTFlZjJiLWI5MTYtNDA0YS1hZDFmLTRmMTc1MmM0Y2FiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxODA0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2ExMTU4Yzk2ZTA1NDA3OTUxNWI2OGM1ZWUyNWI3YWIwZjhlZDEyOGUyNGJjN2ZhZWNkNGVlZGU2MjYyZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jahh6QRLrdhUwSLPYsj2t1ua1UIKGIAYEH9drmK8y0Q)
> 
> Опять вульпинканский БЕНИС точит ![image](https://private-user-images.githubusercontent.com/110329212/303856593-d3e26bc1-7f01-4622-b78e-a125f4f5c060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODg1OTksIm5iZiI6MTcwNzU4ODI5OSwicGF0aCI6Ii8xMTAzMjkyMTIvMzAzODU2NTkzLWQzZTI2YmMxLTdmMDEtNDYyMi1iNzhlLWExMjVmNGY1YzA2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxODA0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjdiZWQ4YWNhZmRmM2Y4NjgyZmVmMTAxNjBjY2FiZTA5ZjRmYTczYmZiZjBlOTdmNmRmMmFhMTkwNWRkNTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fVwmJsikfVfNKgPxGRjUORS-yqOiGBSae_mXj5YQvFM) Хоть убей, но колет глаз. Добавь пару проклятых пикселей. Во всём остальном хорошо.

Подразумеваю добавить пикселей всем хвостатым, у которых виден БЕНИС

2024-02-10 18:15 UTC, Gottfrei commented
@SAADf603 лучше пиши автору предложки, если дело касается спрайтов. не зря же мы оставляем ссылки на результаты воутов.

2024-02-12 20:00 UTC, merged