add: Added a popup window with suggested version
ss220-space/Paradise pull request #4386
Opened 2024-02-10 13:00 UTC by Den109G

## Описание
Переводит строчку "Обновите БЬЁНД" если версия БЬЁНДА устарела.
Добавляет окно с этим же предупреждением пользователю.
Добавляет define для версии 511 бьёнда. И меняет его там, где использовалось просто число.

## Ссылка на предложение/Причина создания ПР
[Ссылка](https://discord.com/channels/617003227182792704/734823601110515882/1205847017520111687)

## Демонстрация изменений

![Screenshot (12933)](https://github.com/ss220-space/Paradise/assets/87372121/90b0b077-28c9-46a9-962c-027d9ef9834c)
Или [видео](https://discord.com/channels/617003227182792704/734823601110515882/1205859079977963530)

2024-02-10 13:51 UTC, Den109G commented
А нужно ли в конфиг переносить это...

2024-02-10 14:06 UTC, Rerik007 reviewed
Kotvslyapi

2024-02-10 14:06 UTC, Rerik007 commented on code/modules/client/client_procs.dm
> +	var/msg = {"<meta charset="UTF-8">"}
Через лист получше насколько я знаю, [kotvslyapi](https://github.com/ParadiseSS13/Paradise/blob/master/.github/CONTRIBUTING.md#do-not-use-list-operators-in-strings)
```suggestion
	var/list/msg = list({"<meta charset="UTF-8">"})
```

2024-02-10 14:06 UTC, Rerik007 commented on code/modules/client/client_procs.dm
> +	msg += "Это может привести к проблемам, таким как к неправильному отображением вещей или лагам." + "<br><br>"
брбр
```suggestion
	msg += "Это может привести к проблемам, таким как к неправильному отображением вещей или лагам.<br><br>"
```

2024-02-10 14:06 UTC, Rerik007 commented on code/modules/client/client_procs.dm
> +	src << browse(msg, "window=warning_popup")
```suggestion
	src << browse(msg.Join(""), "window=warning_popup")
```

2024-02-10 14:06 UTC, Rerik007 commented on code/modules/client/client_procs.dm
> +	to_chat(src, "<span class='userdanger'>Ваш клеинт BYOND (версия: [byond_version].[byond_build]) устарел. Это может вызвать лаги. Мы крайне рекомендуем скачать последнюю версию с <a href='https://www
```suggestion
	to_chat(src, span_userdanger("Ваш клиент BYOND (версия: [byond_version].[byond_build]) устарел. Это может вызвать лаги. Мы крайне рекомендуем скачать последнюю версию с <a href='https://www.byond.com/download/'>byond.com</a> Прежде чем играть. Также можете обновиться через приложение BYOND."))
```
Раз уж мы здесь

2024-02-10 16:58 UTC, SAADf603 requested changes
Мелочи, конечно, но суть в том, что бы даже самый ленивый пользователь был замотивирован скачать последнюю версию.

2024-02-10 16:58 UTC, SAADf603 commented on code/modules/client/client_procs.dm
> +	msg += "<b>Ваша версия BYOND может быть устарела:</b><br>"
Я караульный и люблю буквы. Если такое сообщение появляется у пользователя, значит его бьенда не возможно, а точно устарела.

2024-02-10 16:58 UTC, SAADf603 commented on code/modules/client/client_procs.dm
> +	msg += "Посетите <a href=\"https://secure.byond.com/download\">сайт BYOND</a>, чтобы получить последнюю версию.<br>"
скачать

2024-02-10 17:11 UTC, Den109G commented on code/modules/client/client_procs.dm
> +	msg += "Посетите <a href=\"https://secure.byond.com/download\">сайт BYOND</a>, чтобы получить последнюю версию.<br>"
Поправил.

2024-02-11 00:51 UTC, BeebBeebBoob approved these changes

2024-02-11 06:12 UTC, SAADf603 approved these changes
👍🏻

2024-02-12 00:23 UTC, merged