airlock electronics null fix
ss220-space/Paradise pull request #4397
Opened 2024-02-11 20:39 UTC by ARZUMATA

## Описание

При активации UI настройки платы шлюза иногда появляется ошибка ntos.

При разборе аирлока с общим доступом, в момент "типа вытаскивания платы", создается с нуля плата аирлока с дефолтным selected_accesses.

Потом в эту плату записываются данные доступа с аирлока из req_access переменной, которая на таких аирлоках = null.

Если аирлок с настроенным доступом, то проблем нет, т.к. данные имеются и записываются корректно.

Соответственно плата сама по себе рабочая, но в момент ее настройки, GUI обращается в уже несуществующие данные в selected_accesses и выбрасывает ошибку.

Теперь в случае разбора или уничтожения аирлока общего доступа, создаваемая плата имеет пустой список как и положено, а список создается по необходимости.
см. https://github.com/ss220-space/Paradise/pull/4313

Справка:
selected_accesses - доступы выбранные на плате и они записываются в req_access на аирлоке когда она вставляется.
req_access - данные на аирлоке и при вытаскивании записываются в selected_accesses на плате.

## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/1206012302051254272

## Демонстрация изменений

2024-02-12 10:02 UTC, BeebBeebBoob requested changes

2024-02-12 10:02 UTC, BeebBeebBoob commented on code/game/machinery/doors/airlock.dm
> +
Это делается одной строчкой тогда. Референс: https://www.byond.com/docs/ref/#/operator/%3f
```suggestion
			ae.selected_accesses = length(req_access) ? req_access  : list()
```

2024-02-12 10:04 UTC, BeebBeebBoob commented
На всякий поменял тайтл на корректную. У нас в #обучающий.. есть закрепка со всеми тегами перед  названием ПРа, дабы чейнжлог в игре правильно показывал иконку.

2024-02-16 02:01 UTC, BeebBeebBoob approved these changes, later dismissed
Ок но такие жирные комменты ради объяснение одного мелкого багфикса не нужно. Максимум одна строчка и то в той же строке после багфиксе аля
`фикс чего-то // это фиксит вот то говно`

2024-02-16 14:53 UTC, Vladisvell approved these changes

2024-02-17 19:22 UTC, SAADf603 approved these changes

2024-02-17 19:33 UTC, BeebBeebBoob approved these changes

2024-02-17 19:38 UTC, merged