refactor: Update CONTRIBUTING.md
ss220-space/Paradise pull request #4402
Opened 2024-02-12 10:30 UTC by BeebBeebBoob

## Описание

При необходимости, можно было бы указывать на контрибутинг.мд
Чисто обновление Changelog.

## Ссылка на предложение/Причина создания ПР

![image](https://github.com/ss220-space/Paradise/assets/32985153/394b14ad-a65a-4a5f-a6d9-766bbc3ad1ff)

2024-02-12 16:39 UTC, SAADf603 requested changes
мапперы (я) оскорблены отсутствуем тэга REMAP

2024-02-12 20:17 UTC, BeebBeebBoob commented
Потому что в коде нету remap
Вот те фулл
```
const icons = {
  add: { icon: 'check-circle', color: 'green' },
  admin: { icon: 'user-shield', color: 'purple' },
  balance: { icon: 'balance-scale-right', color: 'yellow' },
  bugfix: { icon: 'bug', color: 'green' },
  code_imp: { icon: 'code', color: 'green' },
  config: { icon: 'cogs', color: 'purple' },
  expansion: { icon: 'check-circle', color: 'green' },
  experiment: { icon: 'radiation', color: 'yellow' },
  image: { icon: 'image', color: 'green' },
  imageadd: { icon: 'tg-image-plus', color: 'green' },
  imagedel: { icon: 'tg-image-minus', color: 'red' },
  qol: { icon: 'hand-holding-heart', color: 'green' },
  refactor: { icon: 'tools', color: 'green' },
  rscadd: { icon: 'check-circle', color: 'green' },
  rscdel: { icon: 'times-circle', color: 'red' },
  server: { icon: 'server', color: 'purple' },
  sound: { icon: 'volume-high', color: 'green' },
  soundadd: { icon: 'tg-sound-plus', color: 'green' },
  sounddel: { icon: 'tg-sound-minus', color: 'red' },
  spellcheck: { icon: 'spell-check', color: 'green' },
  tgs: { icon: 'toolbox', color: 'purple' },
  tweak: { icon: 'wrench', color: 'green' },
  unknown: { icon: 'info-circle', color: 'label' },
  wip: { icon: 'hammer', color: 'orange' },
};
```

2024-02-14 21:36 UTC, ROdenFL commented
> Потому что в коде нету remap
> Вот те фулл
> ```
> const icons = {
>   add: { icon: 'check-circle', color: 'green' },
>   admin: { icon: 'user-shield', color: 'purple' },
>   balance: { icon: 'balance-scale-right', color: 'yellow' },
>   bugfix: { icon: 'bug', color: 'green' },
>   code_imp: { icon: 'code', color: 'green' },
>   config: { icon: 'cogs', color: 'purple' },
>   expansion: { icon: 'check-circle', color: 'green' },
>   experiment: { icon: 'radiation', color: 'yellow' },
>   image: { icon: 'image', color: 'green' },
>   imageadd: { icon: 'tg-image-plus', color: 'green' },
>   imagedel: { icon: 'tg-image-minus', color: 'red' },
>   qol: { icon: 'hand-holding-heart', color: 'green' },
>   refactor: { icon: 'tools', color: 'green' },
>   rscadd: { icon: 'check-circle', color: 'green' },
>   rscdel: { icon: 'times-circle', color: 'red' },
>   server: { icon: 'server', color: 'purple' },
>   sound: { icon: 'volume-high', color: 'green' },
>   soundadd: { icon: 'tg-sound-plus', color: 'green' },
>   sounddel: { icon: 'tg-sound-minus', color: 'red' },
>   spellcheck: { icon: 'spell-check', color: 'green' },
>   tgs: { icon: 'toolbox', color: 'purple' },
>   tweak: { icon: 'wrench', color: 'green' },
>   unknown: { icon: 'info-circle', color: 'label' },
>   wip: { icon: 'hammer', color: 'orange' },
> };
> ```

Тк допиши

2024-02-14 22:21 UTC, BeebBeebBoob commented
Нет ибо не входит в основу этого ПРа

2024-02-14 23:24 UTC, merged

2024-02-15 07:09 UTC, ROdenFL commented
> Нет ибо не входит в основу этого ПРа

Душный