add: crayfish update
ss220-space/Paradise pull request #4404
Opened 2024-02-12 14:43 UTC by RuinaRuiner

УРА РАКИ!

## Описание
Теперь экипаж может кушать раков, выращивать раков, пить пиво в закуску с раками, покупать раков, обненивать раков на пиво, а так же готовить раков!

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1205841878314913822

2024-02-12 15:24 UTC, Gottfrei commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "Supply of lobsters from Mr. Cheng. Crayfish instead of lobsters, super discount, great rating!"
```suggestion
	desc = "Supply of lobsters from Mr. Chang. Crayfish instead of lobsters, super discount, great rating!"
```
опечатка.

2024-02-12 15:26 UTC, Gottfrei commented on code/game/objects/items/weapons/storage/boxes.dm
> +		/obj/item/reagent_containers/food/drinks/cans/beer)
лучше объединить в один лист с вложенными пресетами, если так уж не хочется рандомить.

2024-02-12 15:26 UTC, RuinaRuiner commented on code/game/objects/items/weapons/storage/boxes.dm
> +		/obj/item/reagent_containers/food/drinks/cans/beer)
Лист с листами?

2024-02-12 15:27 UTC, Gottfrei commented on code/modules/food_and_drinks/food/foods/seafood.dm
> +	desc = "A fillet of raw salmon."
это не лосось.

2024-02-12 15:27 UTC, Gottfrei commented on code/modules/food_and_drinks/food/foods/seafood.dm
> +	desc = "A fillet of raw salmon."
аналогично.

2024-02-12 15:28 UTC, Gottfrei commented on code/modules/food_and_drinks/food/foods/seafood.dm
> +	desc = "A fillet of raw salmon."
и здесь.

2024-02-12 15:28 UTC, Gottfrei commented on code/modules/food_and_drinks/food/foods/seafood.dm
> +	desc = "A fillet of raw salmon."
последний лосось.

2024-02-12 15:29 UTC, Gottfrei commented on code/game/objects/items/weapons/storage/boxes.dm
> +		/obj/item/reagent_containers/food/drinks/cans/beer)
да, чтобы была одна переменная, а не три.

2024-02-12 15:45 UTC, RuinaRuiner commented on code/game/objects/items/weapons/storage/boxes.dm
> +		/obj/item/reagent_containers/food/drinks/cans/beer)
Спасибо, поправилю

2024-02-12 15:49 UTC, Gottfrei commented on code/game/objects/items/weapons/storage/boxes.dm
> +	var/list/preset = pick(presets[0], presets[1], presets[2])
```suggestion
	var/list/preset = pick(presets)
```
здесь не обязательно указывать элементы листа.

2024-02-12 22:08 UTC, BeebBeebBoob requested changes

2024-02-12 22:08 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/storage/boxes.dm
> +	var/static/list/presets = list(
Что это

2024-02-12 22:08 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/storage/boxes.dm
> +		new item(src)
```suggestion
/obj/item/storage/box/crayfish_bucket/populate_contents()
	var/big_ones = rand(2, 4)
	var/small_ones = 5 - big_ones
	for(var/i in 1 to big_ones)
		new /obj/item/reagent_containers/food/snacks/crayfish_big(src)
	for(var/i in 1 to small_ones)
		new /obj/item/reagent_containers/food/snacks/crayfish_small(src)
	new /obj/item/reagent_containers/food/drinks/cans/beer(src)
```

2024-02-12 22:08 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/storage/boxes.dm
> +			/obj/item/reagent_containers/food/drinks/cans/beer))
```suggestion
```

2024-02-12 22:08 UTC, BeebBeebBoob commented on code/modules/food_and_drinks/recipes/recipes_microwave.dm
> +/datum/recipe/microwave/crayfish_1
```suggestion

/datum/recipe/microwave/crayfish_1
```
Делите код ....

2024-02-14 21:31 UTC, BeebBeebBoob reviewed
Всё ок, осталось только конфликт решить и всё

2024-02-15 05:22 UTC, RuinaRuiner commented
> Всё ок, осталось только конфликт решить и всё

Я смотрю и не вижу конфликта в спрайтах, хотя там спрайт ведерка есть

2024-02-15 10:46 UTC, BeebBeebBoob commented
> Я смотрю и не вижу конфликта в спрайтах, хотя там спрайт ведерка есть

![image](https://github.com/ss220-space/Paradise/assets/32985153/25f05a98-1c35-45f3-84ad-96eb6132bc26)
`/icons/obj/food/food.dmi`
Скачай файл отсюда и сверь со своей версией и ты поймёшь.

2024-02-17 07:59 UTC, RuinaRuiner commented
> > Я смотрю и не вижу конфликта в спрайтах, хотя там спрайт ведерка есть
> 
> ![image](https://private-user-images.githubusercontent.com/32985153/305043707-25f05a98-1c35-45f3-84ad-96eb6132bc26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTY5NzUsIm5iZiI6MTcwODE1NjY3NSwicGF0aCI6Ii8zMjk4NTE1My8zMDUwNDM3MDctMjVmMDVhOTgtMWMzNS00NWYzLTg0YWQtOTZlYjYxMzJiYzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA3NTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhM2NkMDk2YzViMTlkZTQzYzg1NjYzMjQ5NjFjZjczNDY5OWE1MGJmMjdiZGY5Y2Q1YmMyMmIyNDU4ZjIwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vHTYNlse-7u3V1uzfJN5gcXy4he94aylDacCCshaAhE) `/icons/obj/food/food.dmi` Скачай файл отсюда и сверь со своей версией и ты поймёшь.

![image](https://github.com/ss220-space/Paradise/assets/121757203/4f15d1b9-6619-41c3-b8ad-f8e6cfb67b1c)
![image](https://github.com/ss220-space/Paradise/assets/121757203/6eb2347c-dc95-4fb7-88e0-f074e07f8529)
![image](https://github.com/ss220-space/Paradise/assets/121757203/1e687028-d4be-4f36-ae57-a0e415a3db4d)
Так что тут не так? До сих пор не вижу

2024-03-13 13:39 UTC, closed without merging