tweak: IV bags can inject opened limbs of PIERCEIMMUNE races
ss220-space/Paradise pull request #4411
Opened 2024-02-13 00:22 UTC by LiquidPotroh

## Описание
Добавляет возможность прокалывать кожу рас с трейтом PIERCEIMMUNE при операции по манипуляции с органами после действий скальпель, гемостат, ретрактор. При завершении операции капельница будет вытыкаться. Вкалывать можно только в ту часть, которая была вскрыта. 

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1206566252613599284

## Демонстрация изменений
https://youtu.be/EbEI42erPBw

2024-02-14 21:29 UTC, BeebBeebBoob approved these changes, later dismissed

2024-02-14 21:29 UTC, BeebBeebBoob commented on code/modules/mob/living/carbon/human/human.dm
> +	// affecting.open = 2 after scalpel->hemostat->retractor, sorry im too lazy to rewrite defines in all places where it is used
```suggestion
	// affecting.open = 2 after scalpel->hemostat->retractor
```

2024-02-14 21:29 UTC, BeebBeebBoob commented on code/modules/mob/living/carbon/human/human.dm
> +	// affecting.open = 2 after scalpel->hemostat->retractor, sorry im too lazy to rewrite defines in all places where it is used
вообще это плохо что здесь волшебное число, но хотя бы с комментом.

2024-02-14 21:29 UTC, BeebBeebBoob commented on code/modules/reagents/reagent_containers/iv_bag.dm
> +	if((PIERCEIMMUNE in injection_target.dna.species.species_traits) && injection_limb.open < 2)
```suggestion
	// injection_limb.open = 2 after scalpel->hemostat->retractor
	if((PIERCEIMMUNE in injection_target.dna.species.species_traits) && injection_limb.open < 2)
```

2024-02-15 02:07 UTC, LiquidPotroh commented on code/modules/mob/living/carbon/human/human.dm
> +	// affecting.open = 2 after scalpel->hemostat->retractor, sorry im too lazy to rewrite defines in all places where it is used
Да они там везде в хирургии)

2024-02-15 02:08 UTC, LiquidPotroh commented on code/modules/mob/living/carbon/human/human.dm
> +	// affecting.open = 2 after scalpel->hemostat->retractor, sorry im too lazy to rewrite defines in all places where it is used
Будут рефакторить хирургию - исправят

2024-02-15 03:52 UTC, BeebBeebBoob requested changes

2024-02-15 03:52 UTC, BeebBeebBoob commented on code/modules/reagents/reagent_containers/iv_bag.dm
> +/obj/item/reagent_containers/iv_bag/proc/begin_processing(mob/living/carbon/human/target, zone)
Ты забыл переменную zone на 126 строке :D
```DM
            begin_processing(L, def_zone)
```

2024-02-16 00:59 UTC, LiquidPotroh commented on code/modules/reagents/reagent_containers/iv_bag.dm
> +/obj/item/reagent_containers/iv_bag/proc/begin_processing(mob/living/carbon/human/target, zone)
да в смысле я забыл. Оно так уже 9000 лет

2024-02-16 00:59 UTC, LiquidPotroh commented on code/modules/reagents/reagent_containers/iv_bag.dm
> +/obj/item/reagent_containers/iv_bag/proc/begin_processing(mob/living/carbon/human/target, zone)
а ой..

2024-02-18 11:37 UTC, BeebBeebBoob approved these changes

2024-03-09 07:26 UTC, Vladisvell approved these changes

2024-03-09 07:30 UTC, merged