bugfix: t-ray scanner can make you invisibility
ss220-space/Paradise pull request #4414
Opened 2024-02-13 08:18 UTC by Rerik007

## Описание
Восстановленная версия https://github.com/ss220-space/Paradise/pull/2471
Если коротко, то теперь т-рей сканнеры будут отправлять вам картинки объектов, а не изменять альфу этих обьектов, показывая их. Также теперь ниндзю можно искать только с помощью сканера сб. Показ аномалий работает.

## Ссылка на предложение/Причина создания ПР
Закрывает багрепорт: https://discord.com/channels/617003227182792704/1206697800260395069

2024-02-13 14:01 UTC, Den109G commented on code/game/objects/items/devices/scanners.dm
> +	for(var/obj/in_turf_object in orange(distance, viewer))
разве оно будет показывать мобов как и раньше?
Там же не только ниндзя, но и другие.

2024-02-13 14:03 UTC, Rerik007 commented on code/game/objects/items/devices/scanners.dm
> +	for(var/obj/in_turf_object in orange(distance, viewer))
>  Также теперь ниндзю можно искать только с помощью сканера сб
Не должно. Теперь будут брать из рнд сканеры тогда.

2024-02-13 14:07 UTC, Den109G commented on code/game/objects/items/devices/scanners.dm
> +	for(var/obj/in_turf_object in orange(distance, viewer))
> Не должно. Теперь будут брать из рнд сканеры тогда.

А сканер СБ вызывает бесконечную невидимость у этих мобов?

2024-02-13 14:11 UTC, Den109G commented on code/game/objects/items/devices/scanners.dm
> +	for(var/obj/in_turf_object in orange(distance, viewer))
Просто этот фикс больше походит как на вырезание никому неизвестной фичи. В то время когда проблему не тронули.

2024-02-13 14:14 UTC, Rerik007 commented on code/game/objects/items/devices/scanners.dm
> +	for(var/obj/in_turf_object in orange(distance, viewer))
> А сканер СБ вызывает бесконечную невидимость у этих мобов?

Да, и правда. Окей, попробую посмотреть, возможно правда придётся изменить работу сканера сб...

2024-02-13 15:51 UTC, Rerik007 commented on code/game/objects/items/devices/scanners.dm
> +	for(var/obj/in_turf_object in orange(distance, viewer))
Ускорил скан сб, уменьшив у него продолжительность картинки. Вернул мобов обратно к т-реям, если игрокам не будет нравиться эффект мобов, вырежем у треев наверное.

2024-02-14 00:06 UTC, Den109G commented on code/game/objects/items/devices/scanners.dm
> -	pulse_duration = 30
а почему длина у СБ сканера уменьшилась на 66%? ache

2024-02-14 06:56 UTC, Rerik007 commented on code/game/objects/items/devices/scanners.dm
> -	pulse_duration = 30
Потому что частота увеличилась в 2 раза, ты же сам сказал что не очень выглядело с длинным эффектом.

2024-02-14 21:19 UTC, BeebBeebBoob commented on code/game/objects/items/devices/scanners.dm
> +/obj/item/t_scanner/proc/toggle_on()
```suggestion
/obj/item/t_scanner/proc/toggle_mode()
```

2024-02-14 21:19 UTC, BeebBeebBoob commented on code/game/objects/items/devices/scanners.dm
> +	toggle_on()
```suggestion
	toggle_mode()
```
Мы же переключаем режимы, а не "включение" :)

2024-02-14 21:19 UTC, BeebBeebBoob commented on code/game/objects/items/devices/scanners.dm
> +	pulse_duration = 10
Лучше бы вообще заменить всё на `1 SECONDS` и т.д. а не `10`

2024-02-14 21:19 UTC, BeebBeebBoob commented on code/game/objects/items/devices/scanners.dm
> +			if(in_turf_object.invisibility != INVISIBILITY_MAXIMUM || in_turf_object.invisibility != INVISIBILITY_ANOMALY)
Себе
`#define INVISIBILITY_ABSTRACT 101`
`#define INVISIBILITY_MAXIMUM 100`

2024-02-14 21:20 UTC, BeebBeebBoob commented
`bugfix: t-ray scanner can make you invisibility` >> `bugfix: t-ray scanner can make you invisible`

2024-02-14 21:31 UTC, Rerik007 commented on code/game/objects/items/devices/scanners.dm
> +	pulse_duration = 10
Сделано 🙃

2024-02-15 00:22 UTC, BeebBeebBoob approved these changes, later dismissed

2024-02-16 13:57 UTC, Vladisvell approved these changes, later dismissed

2024-02-17 16:13 UTC, SAADf603 requested changes
1. Сканер СБ
В общем-то работает.
2. T-ray сканеры
Не работают ВООБЩЕ. (видео не прилагается)
![image](https://github.com/ss220-space/Paradise/assets/110329212/4aeaceba-bbff-450a-85a5-3356b49e2fe8)
3. Сканер руд.
Поскольку частота пульсов увеличилась, а отображение руд не уменьшилось, теперь руду видно просто постоянно, что не ОК

2024-02-17 16:13 UTC, SAADf603 commented on code/game/objects/items/devices/scanners.dm
> +	if(!ismob(viewer) || !viewer.client)
Теперь если условного шатхёра убили, то он уже не клиент, а поэтому активный сканер в его руках не прекращает процесс, а просто не работает. То же самое если выронить сканер из рук.

2024-02-17 16:13 UTC, SAADf603 commented on code/modules/assembly/infrared.dm
> +		invisibility = 0
Нет, FALSE

2024-02-17 16:13 UTC, SAADf603 commented on code/ATMOSPHERICS/pipes/manifold.dm
>  /obj/machinery/atmospherics/pipe/manifold/hide(var/i)
А здесь почему (var/i)????

2024-02-17 16:32 UTC, Rerik007 commented on code/ATMOSPHERICS/pipes/manifold.dm
>  /obj/machinery/atmospherics/pipe/manifold/hide(var/i)
Так было... Исправлю. 👍

2024-02-17 16:32 UTC, Rerik007 commented on code/modules/assembly/infrared.dm
> +		invisibility = 0
Не, invisibility может быть от 0 до 101(у нас), а не TRUE/FALSE, поэтому окей)

2024-02-17 16:34 UTC, Rerik007 commented on code/game/objects/items/devices/scanners.dm
> +	if(!ismob(viewer) || !viewer.client)
? в этом нет ничего плохого. Всё окей. нам же некому отправлять картинки.

2024-02-17 16:35 UTC, Rerik007 commented
> 2. T-ray сканеры
>    Не работают ВООБЩЕ. (видео не прилагается)

Исправил. Спасибо! Я пропустил это когда менял это в последнем коммите. Теперь всё должно работать.

2024-02-17 17:21 UTC, SAADf603 approved these changes

2024-02-18 10:34 UTC, Vladisvell approved these changes
На тестмерж

2024-02-18 10:38 UTC, merged