rework: NULL crate
ss220-space/Paradise pull request #4422
Opened 2024-02-13 17:31 UTC by ROdenFL

## Описание
Реворк нулл крейтов + поддержка покупки ящиков за кредиты

## Ссылка на предложение/Причина создания ПР

## Демонстрация изменений

2024-02-14 20:58 UTC, BeebBeebBoob requested changes

2024-02-14 20:58 UTC, BeebBeebBoob commented on code/controllers/subsystem/shuttles.dm
> +
Мне не нравиться что мы повторяем из глобальных варов сюда в систему.
Можно пожалуйста убрать это отсюда и просто использовать что ниже написано
```
var/datum/money_account/cargo_money_account = GLOB.department_accounts["Cargo"]
if(credits_cost && cargo_money_account.money <= credits_cost)
```
![image](https://github.com/ss220-space/Paradise/assets/32985153/0761b3d9-a9f7-481f-b76f-d478ecadf820)

2024-02-14 21:30 UTC, ROdenFL commented on code/controllers/subsystem/shuttles.dm
> +
Хуй знает, полностью не согласен, если мы подразумеваем возможность покупки вещей за кредиты, то создание каждый раз одной и той же константы банально тупо, нахождение в сабсистеме переменной которая с ней напрямую связана не такое плохое решение

2024-02-14 21:32 UTC, ROdenFL commented on code/controllers/subsystem/shuttles.dm
> +
На скрине который ты скинул, нужно наоборот думаю переписать под получение значения из сабсистемы

2024-02-15 02:42 UTC, BeebBeebBoob commented on code/controllers/subsystem/shuttles.dm
> +
В сабсистеме шатлов?
Предлагаю сделать тогда отдельную систему "Экономика" дабы не ебаться, почему в шаттлах находиться экономика.
Да, будет ещё целая новая супер малая система и это не страшно. Главное порядок.

2024-02-15 07:03 UTC, ROdenFL commented on code/controllers/subsystem/shuttles.dm
> +
Тоже звучит как хуйня

2024-02-15 07:05 UTC, ROdenFL commented on code/controllers/subsystem/shuttles.dm
> +
Ошибка если и есть, то не в том что я в сабсистемы переменную добавил, а в том что я в остальных местах под неё ничего не переписал

2024-02-15 08:17 UTC, BeebBeebBoob commented on code/controllers/subsystem/shuttles.dm
> +
Ладно похуй. Пусть так будет.

2024-02-15 08:18 UTC, BeebBeebBoob approved these changes

2024-02-18 04:04 UTC, merged