refactor: surgery's code polishing, few fixes and tweaks
ss220-space/Paradise pull request #4436
Opened 2024-02-15 11:04 UTC by Rerik007

## Описание
Делает код хирургии более приятным. Переносит с оффов их систему с хирургическими операциями. А именно теперь появляется возможность необязательных или разветвлённых шагов в операциях.

2024-02-16 14:20 UTC, Vladisvell requested changes
Ещё чуть чуть и на тестмёрж

2024-02-16 14:20 UTC, Vladisvell commented on code/__HELPERS/tool_helpers.dm
> +	)
Я не уверен, будет ли тут создаваться каждый раз список при попытке прогнать эту инструкцию.
Может лучше вынести в статик?

2024-02-16 14:20 UTC, Vladisvell commented on code/_onclick/item_attack.dm
> +		return TRUE
Увы, у нас нет прока pre_attack() для предметов

2024-02-16 14:20 UTC, Vladisvell commented on code/modules/surgery/bones.dm
> -	time = 10
Случайно задел при портировании? (время операции подскочило до двух секунд)

2024-02-16 14:36 UTC, Rerik007 commented on code/_onclick/item_attack.dm
> +		return TRUE
Исправил на pre_attackby()

2024-02-16 14:39 UTC, Rerik007 commented on code/__HELPERS/tool_helpers.dm
> +	)
Вообще, этот прок, как и прок выше не вызываются(не до не сейчас)... Я переделал этот лист в  глобал лист, который используется в дебажном имсе. Не знаю, стоит ли оставлять этот прок?

2024-02-18 10:32 UTC, Vladisvell submitted a review, later dismissed

2024-03-17 17:07 UTC, ArtemDerp commented
@Gottfrei @BeebBeebBoob вот бы сюда кто заглянул 🧐

2024-03-17 17:12 UTC, BeebBeebBoob commented
Трындец да тут не один день займёт на просмотр и проверок

2024-03-30 21:00 UTC, Gottfrei commented on code/datums/components/surgery_initiator.dm
> +	return !surgery.ignore_clothes && !get_location_accessible(target, target.zone_selected)
почему при проверке доступности зоны мы отправляем зону, выбранную оперируемым, а не тем, кто проводит операцию?

2024-03-30 21:04 UTC, Gottfrei commented on code/datums/components/surgery_initiator.dm
> +		return
что здесь вообще происходит?

2024-03-30 21:05 UTC, Gottfrei commented on code/datums/components/surgery_initiator.dm
> +	)
спаны надо бы везде сделать макросные.

2024-03-31 06:59 UTC, Rerik007 commented on code/datums/components/surgery_initiator.dm
> +		return
Если хирургия требует конечность и её нет (1 == 1), мы пишем `The patient has no zone`
Если хирургия не требует конечность и она есть (0 == 0) мы пишем `The patient has zone`

2024-03-31 06:59 UTC, Rerik007 commented on code/datums/components/surgery_initiator.dm
> +	return !surgery.ignore_clothes && !get_location_accessible(target, target.zone_selected)
прав

2024-03-31 06:59 UTC, Rerik007 commented on code/datums/components/surgery_initiator.dm
> +	)
о нет....
Я попробую

2024-04-06 19:39 UTC, Gottfrei approved these changes, later dismissed

2024-04-07 13:51 UTC, Vladisvell approved these changes, later dismissed

2024-04-12 10:51 UTC, Gottfrei approved these changes

2024-04-12 16:00 UTC, Vladisvell approved these changes

2024-04-12 16:13 UTC, merged