bugfix: Autopsy scanner can scan different "Unknown" bodies.
ss220-space/Paradise pull request #4442
Opened 2024-02-16 08:50 UTC by Daeberdir

## Описание
Сканер коронера различает тела не по их именам, давно уже пора было.

## Ссылка на баг-репорт
https://discord.com/channels/617003227182792704/1207959282927276032

2024-02-16 17:19 UTC, BeebBeebBoob submitted a review, later dismissed

2024-02-16 17:21 UTC, LiquidPotroh commented
А чё бы не дать ему возможность использовать real_name из ДНК? Почему это вообще только функция детективского сканера. Оставить только высосанным генкой невозможность получения имени.

2024-02-16 17:42 UTC, BeebBeebBoob commented
Даже real_name могут совпасть и не будет давать возможность  провести

2024-02-18 03:57 UTC, Dimach requested changes
Опасно оставлять в сканере ссылку на моба, тут лучше использовать UID чтобы не увеличивать рефкаунтер (да я понимаю что одно единственное тело которое до конца не удалится в раунде не так критично, но все же)

2024-02-18 11:37 UTC, BeebBeebBoob approved these changes

2024-02-20 14:13 UTC, merged