add: pAI GPS
ss220-space/Paradise pull request #4444
Opened 2024-02-16 16:29 UTC by Samirakis

## Описание
Добавляет пИИ модуль GPS с апгрейдом, стоимость модуля: 10 памяти. 
Так же добавил функционал нерабочей админкнопке "Make pAI" в меню "Player Panel", с возможностью спавнить не только пии, но и спии

## Ссылка на предложение/Причина создания ПР
Прошедшая предложка на добавление GPS для пИИ: https://discord.com/channels/617003227182792704/755125334097133628/1208044696874520666

## Демонстрация изменений
![image](https://github.com/ss220-space/Paradise/assets/156955117/efa4e977-d98b-42cd-bd2e-df829dd42901)

2024-02-16 17:17 UTC, BeebBeebBoob requested changes

2024-02-16 17:17 UTC, BeebBeebBoob commented on code/modules/admin/topic.dm
> +		if(!check_rights(R_SPAWN))	return
```suggestion
		if(!check_rights(R_SPAWN))
			return
```

2024-02-16 17:40 UTC, BeebBeebBoob approved these changes, later dismissed

2024-02-17 06:26 UTC, Rerik007 reviewed
Пару моментов

2024-02-17 06:26 UTC, Rerik007 commented on code/modules/admin/topic.dm
> +		var/mob/living/carbon/human/H = locate(href_list["makePAI"])
в make pai кнопке вроде уид используется а не реф
```suggestion
		var/mob/living/carbon/human/H = locateUID(href_list["makePAI"])
```

2024-02-17 06:26 UTC, Rerik007 commented on code/modules/mob/transform_procs.dm
> +/mob/living/carbon/human/proc/paize(var/name, var/bespai)
```suggestion
/mob/living/carbon/human/proc/paize(name, bespai)
```
bespai

2024-02-17 06:26 UTC, Rerik007 commented on code/modules/mob/transform_procs.dm
> +	invisibility = 101
```suggestion
	notransform = TRUE
	canmove = FALSE
	icon = null
	invisibility = INVISIBILITY_ABSTRACT
```
для кросоты

2024-02-17 06:26 UTC, Rerik007 commented on code/modules/mob/transform_procs.dm
> +	return
Прок же и так возвращает нулл, нет?
```suggestion
	INVOKE_ASYNC(GLOBAL_PROC, /proc/qdel, src)
```
в любом случае вот так получше..

2024-02-17 06:26 UTC, Rerik007 commented on code/modules/mob/living/silicon/pai/software/pai_apps.dm
> +	invisibility = 100
```suggestion
	invisibility = INVISIBILITY_ABSTRACT
```

2024-02-17 09:40 UTC, Samirakis commented on code/modules/mob/living/silicon/pai/software/pai_apps.dm
> +	invisibility = 100
![catrose](https://github.com/ss220-space/Paradise/assets/156955117/e43654e2-a7f6-4dc2-b97d-de860228b4b5)
Спасибо

2024-02-17 09:47 UTC, Samirakis commented
![catrose](https://github.com/ss220-space/Paradise/assets/156955117/0f951225-5ffd-4876-8f21-e931576c29bc)

2024-02-17 09:55 UTC, Rerik007 reviewed
Мне всё нравится 🎺

2024-02-17 09:55 UTC, Rerik007 commented on code/modules/mob/transform_procs.dm
> +		do_unEquip(W)
```suggestion
		drop_item_ground(W)
```
Последняя вещь.

2024-02-17 23:49 UTC, BeebBeebBoob approved these changes

2024-03-04 13:25 UTC, closed without merging