Biohazard bodybags
ss220-space/Paradise pull request #4465
Opened 2024-02-18 18:24 UTC by VasilevAY

## Описание
Добавлены спрайты мешка для трупов с биологической угрозой
Добавлены коробки с мешками для трупов с биологической угрозой
Добавлены новые коробки на карту Delta

## Ссылка на предложение/Причина создания ПР
Теперь можно отделить трупы, представляющие угрозы (фонящие, трупы, которые заражены и тд) от остальных трупов

## Демонстрация изменений
![image](https://github.com/ss220-space/Paradise/assets/98010665/bef10bef-c1c1-4baf-8e62-4f996411bed2)

2024-02-18 18:25 UTC, VasilevAY commented
Нет конфликта

2024-02-18 18:28 UTC, VasilevAY commented
Апрувы ну-ка быстренько ГАПу наставили

2024-02-18 19:12 UTC, NightDawnFox commented
Если мы поставим тебе аппрувы, то оно полетит сразу в игру. А ПО ПРАВИЛАМ ПРЕДЛОЖЕК, ТЕБЕ НУЖНО ПОДОЖДАТЬ НЕДЕЛЮ

2024-02-18 19:14 UTC, ROdenFL commented
> Если мы поставим тебе аппрувы, то оно полетит сразу в игру. А ПО ПРАВИЛАМ ПРЕДЛОЖЕК, ТЕБЕ НУЖНО ПОДОЖДАТЬ НЕДЕЛЮ

Мораль, удаляем предложат и  авоут

2024-02-21 10:22 UTC, SAADf603 approved these changes

2024-02-21 10:25 UTC, SAADf603 requested changes
white a minute
![image](https://github.com/ss220-space/Paradise/assets/110329212/de914735-f8ee-4942-8275-eb1fdf3146fa)
Т-рищ ГАП, коробки на место верни

2024-02-22 14:38 UTC, VasilevAY commented
> wait a minute ![image](https://private-user-images.githubusercontent.com/110329212/306587241-de914735-f8ee-4942-8275-eb1fdf3146fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTI3ODgsIm5iZiI6MTcwODYxMjQ4OCwicGF0aCI6Ii8xMTAzMjkyMTIvMzA2NTg3MjQxLWRlOTE0NzM1LWY4ZWUtNDk0Mi04Mjc1LWViMWZkZjMxNDZmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxNDM0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGRlNmVkODczMGY1OTM4OWRmOTdmOWE5YmM1ZmI3ZDJjZWQ0ZWJjYjI0ZDIyZmVhNGQ5NGFiYjBiZjhlZmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-JBD-t8XwpXeP_7is8EisxM7Sl27Tx6RmX1V2c0fGXI) Т-рищ ГАП, коробки на место верни

Вернул

2024-02-22 15:26 UTC, SAADf603 requested changes
Теперь зачем-то добавил лишнюю
![image](https://github.com/ss220-space/Paradise/assets/110329212/89f77a03-d7a9-449b-b0ff-e685d85725d7)
![image](https://github.com/ss220-space/Paradise/assets/110329212/e7b805b0-bc79-42be-af43-f79bbe80717c)

2024-02-22 21:25 UTC, SAADf603 submitted a review, later dismissed

2024-02-25 21:49 UTC, VasilevAY commented
https://discord.com/channels/617003227182792704/1210232064943591445/1211320626837716992
Авоут пройден

2024-02-29 20:26 UTC, BeebBeebBoob requested changes

2024-02-29 20:26 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/storage/boxes.dm
> +	icon_state = "biohazard bodybags"
```suggestion
	icon_state = "biohazard_bodybags"
```

2024-02-29 20:26 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/storage/boxes.dm
> +	icon_state = "biohazard bodybags"
Также в иконке подправить.

2024-03-02 14:38 UTC, SAADf603 approved these changes

2024-03-03 16:08 UTC, merged