tweak: more cargo tweaks
ss220-space/Paradise pull request #4530
Opened 2024-02-29 14:18 UTC by Rerik007

## Описание
Повышает награду за целый заказ. Снижает цену на капсулы и инжектор лазаря. убирает мясопшеницу из сложных заказов.

2024-03-02 11:39 UTC, BeebBeebBoob requested changes

2024-03-02 11:39 UTC, BeebBeebBoob commented on code/modules/economy/quests/_base_quests.dm
> +			customer.set_sale(modificator = 1)
Прости но ты можешь так сделать ибо Не (Негативная переменная) как мыло в глазах.
```suggestion
		if(fast_failed)
			customer.set_sale(modificator = 1)
		else
			customer.set_sale(modificator = 2)
```

2024-03-02 11:39 UTC, BeebBeebBoob commented on code/modules/economy/quests/centcomm_departaments.dm
> +	src.modificator = modificator
```suggestion
	modificator = new_modificator
```
Может быть?

2024-03-02 11:41 UTC, Rerik007 commented on code/modules/economy/quests/centcomm_departaments.dm
> +	src.modificator = modificator
Не знаю... Вообще в тг гайде написано делать именно `src.var = var` и в последнее время я делал именно так. Но как лучше?

2024-03-02 11:46 UTC, BeebBeebBoob commented on code/modules/economy/quests/centcomm_departaments.dm
> +	src.modificator = modificator
Ок.

2024-03-02 11:47 UTC, BeebBeebBoob approved these changes

2024-03-04 15:54 UTC, pilygun commented
надо бы еще добавить "Бесконечный лазарь" Которым можно бесконечно поднимать убитую фауну. Очков так за 3000-4000. МБ предложку сделаю со спрайтами

2024-03-08 03:06 UTC, Vladisvell approved these changes

2024-03-08 03:11 UTC, merged