bugfix: Correct Syndicate Animals Spawn
ss220-space/Paradise pull request #4539
Opened 2024-03-01 11:03 UTC by Gottfrei

## Описание
Исправление моей оплошности.

2024-03-01 17:03 UTC, Vladisvell approved these changes

2024-03-01 21:58 UTC, BeebBeebBoob approved these changes

2024-03-01 22:02 UTC, BeebBeebBoob requested changes
GAMEMODE_IS_NUCLEAR это у тебя не числа а проверка на режим! Зачем ты его выводишь??

2024-03-02 00:23 UTC, Gottfrei commented
> GAMEMODE_IS_NUCLEAR это у тебя не числа а проверка на режим! Зачем ты его выводишь??

какие числа о чём речь вообще? данный макрос выводит логическое значение от оператора &&, что нам и требуется для понимания можно ли заходить за животное из тайпкэша выше.

2024-03-02 06:51 UTC, BeebBeebBoob approved these changes
Я еблан. Понял почему так.

2024-03-02 06:56 UTC, merged

2024-03-02 07:03 UTC, aeternaclose commented
> Я еблан. Понял почему так.

![image](https://github.com/ss220-space/Paradise/assets/127967350/e5abee8a-d165-46c6-a72f-d7bf0713b731)