enhanced-medical-gripper
ss220-space/Paradise pull request #456
Opened 2021-11-16 12:04 UTC by Elisei24

## What Does This PR Do
Позволяет медборгам с помощью гриппера держать пакеты с кровью и пересаживать органы

## Why It's Good For The Game
Улучшенный функционал мед. борга, позволяет выполнять жизненно важные действия, всё ещё не позволяет боргу выполнять в одиночку другие менее важные для жизни пациента операции (установка имплантов) ради баланса.

## Images of changes

## Changelog

2021-11-16 19:01 UTC, Vallat requested changes

2021-11-16 19:01 UTC, Vallat commented on code/modules/mob/living/carbon/carbon_defense.dm
> +				if(S.next_step(user, src, user.get_active_hand()))
Здесь это изменение не нужно, attack_hand() вызывается только тогда, когда клик идет **пустой** рукой

2021-11-16 19:01 UTC, Vallat commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +			return
Не в том блоке return
```suggestion
		return
```

2021-11-16 19:01 UTC, Vallat commented on code/modules/surgery/helpers.dm
> +							procedure.next_step(user, M, user.get_active_hand())
Нам не нужно получать предмет в руке, если этим предметом уже является передаваемая внутрь функции переменная "I"
```suggestion
							procedure.next_step(user, M, I)
```

2021-11-19 09:55 UTC, Elisei24 commented on code/modules/mob/living/carbon/carbon_defense.dm
> +				if(S.next_step(user, src, user.get_active_hand()))
Благодарю за исправления, посмотрел на локальном, всё хорошо работает.

2021-11-24 17:45 UTC, merged