bugfix: infinity wild west reinforcements.
ss220-space/Paradise pull request #4580
Opened 2024-03-06 14:23 UTC by Daeberdir

## Описание
+1-1 Проверка на то, что коммуникационный девайс Синдиката уже был использован после выбора инпута.

## Ссылка на баг-репорты

https://discord.com/channels/617003227182792704/1214496830788735007
https://discord.com/channels/617003227182792704/1209939282752708678

2024-03-07 17:57 UTC, BeebBeebBoob commented on code/modules/antagonists/traitor/datum_traitor.dm
> +
К чему это?

2024-03-08 02:39 UTC, Vladisvell requested changes
Упрощенное решение проблемы

2024-03-08 02:39 UTC, Vladisvell commented on code/modules/awaymissions/mission_code/wildwest.dm
> +	if(istraitor(user))
```suggestion
	if(user.mind?.has_antag_datum(/datum/antagonist/traitor))
```

2024-03-08 02:39 UTC, Vladisvell commented on code/modules/antagonists/traitor/datum_traitor.dm
> +
```suggestion
```

2024-03-08 02:41 UTC, Vladisvell approved these changes

2024-03-08 05:08 UTC, BeebBeebBoob approved these changes

2024-03-08 05:12 UTC, merged