bugfix: Cafeteria_RnD_Delta scrubber
ss220-space/Paradise pull request #4589
Opened 2024-03-08 04:50 UTC by mrWhiteFox365

## Описание
Замена голимого скрабера без настроек, на скрабер с настройками заводскими

## Ссылка на предложение/Причина создания ПР
Не доглядел.

## Демонстрация изменений
До: 
![изображение](https://github.com/ss220-space/Paradise/assets/145965244/5daa279e-05e0-4c6c-88b6-bb61e2f9b868)

После: 
![Без имени](https://github.com/ss220-space/Paradise/assets/145965244/68b799d5-5406-472b-b4d6-53cd7d295daa)

2024-03-08 11:23 UTC, SAADf603 submitted a review, later dismissed

2024-03-09 04:22 UTC, BeebBeebBoob commented on _maps/map_files/Delta/delta.dmm
> +	},
https://github.com/ss220-space/Paradise/blob/9bb1eab0c6dda8d0ebbf7ca5489d7da778488c3c/code/ATMOSPHERICS/components/unary_devices/vent_scrubber.dm#L41-L44
Это шутка
Я бы сделал suggestion чтобы поменять сыро, но там редактор карт может просто взять уже готовый тайл и заменить, удалив этот `"fvB"`

2024-03-09 07:39 UTC, Vladisvell requested changes
Поменяй скраббер на /obj/machinery/atmospherics/unary/vent_scrubber/on, заместо его ручного редактирования

2024-03-17 01:23 UTC, BeebBeebBoob approved these changes

2024-03-19 07:39 UTC, Rerik007 approved these changes

2024-03-19 10:56 UTC, SAADf603 approved these changes

2024-03-19 22:53 UTC, merged