bugfix: IV bags can't transfer reagents
ss220-space/Paradise pull request #4607
Opened 2024-03-10 15:09 UTC by LiquidPotroh

## Описание

## Ссылка на предложение/Причина создания ПР

## Демонстрация изменений

2024-03-10 20:06 UTC, Rerik007 commented on code/modules/reagents/reagent_containers/iv_bag.dm
> +	if(target.is_refillable() && is_drainable()) // Transferring from IV bag to other containers
Если я правильно понимаю здесь также нужна проверка на proximity. 
```suggestion
	if(!proximity)
		return
	if(target.is_refillable() && is_drainable()) // Transferring from IV bag to other containers
```

2024-03-10 22:40 UTC, BeebBeebBoob requested changes

2024-03-10 22:40 UTC, BeebBeebBoob commented on code/modules/reagents/reagent_containers/iv_bag.dm
> +	if(target.is_refillable() && is_drainable()) // Transferring from IV bag to other containers
^^^

2024-03-11 08:01 UTC, Rerik007 approved these changes

2024-03-11 09:24 UTC, Vladisvell approved these changes

2024-03-11 10:27 UTC, BeebBeebBoob approved these changes

2024-03-11 10:32 UTC, merged