add: SM is love
ss220-space/Paradise pull request #4615
Opened 2024-03-11 18:03 UTC by Samirakis

## Описание
Нукли теперь не боятся СМ. Могут его почухать. Один раз даже реджувнуться, но только один. 
Подробнее в прошедшей предложке:

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1199645942018740314

## Демонстрация изменений
![image](https://github.com/ss220-space/Paradise/assets/156955117/4397fc9f-2eff-4175-8c92-00bdf9122263)

2024-03-11 18:56 UTC, BeebBeebBoob commented
Ха-ха смешная картинка, но прошу использовать "Демонстрация изменений" по назначению.

2024-03-11 19:08 UTC, BeebBeebBoob requested changes

2024-03-11 19:08 UTC, BeebBeebBoob commented on code/modules/mob/living/carbon/human/species/nucleation.dm
> +	var/SM_touched = FALSE
```suggestion
	var/touched_supermatter = FALSE
```
Мы капс-буквы используем только для однобуквенных перемен. В остальных случаях с нижнего регистра.

2024-03-11 19:08 UTC, BeebBeebBoob commented on code/modules/power/supermatter/supermatter.dm
> +		to_chat(user, span_userdanger("The wave of warm energy is overwhelming you. You feel calm."))
```suggestion
/obj/machinery/power/supermatter_shard/proc/nuclear_touch(var/mob/living/user)
	var/datum/species/nucleation/nuclear = user.dna.species
	if(nuclear.touched_supermatter== FALSE)
		user.revive()
		nuclear.touched_supermatter = TRUE
		to_chat(user, span_userdanger("The wave of warm energy is overwhelming you. You feel calm."))
```
to_chat(user, span_userdanger("The wave of warm energy is overwhelming you. You feel calm.")) - Не вижу логики что это опасно, это больше как положительный эффект. Можно и лучше было бы span info юзануть но пусть так.

2024-03-11 19:08 UTC, BeebBeebBoob commented on code/modules/power/supermatter/supermatter.dm
> +		new /obj/effect/temp_visual/heart(loc)
wtf

2024-03-11 19:08 UTC, BeebBeebBoob commented on code/modules/power/supermatter/supermatter.dm
> +		nucle_touch(user)
```suggestion
		nuclear_touch(user)
```

2024-03-11 19:08 UTC, BeebBeebBoob commented on code/modules/power/supermatter/supermatter.dm
> +		return
> Щепка от СМ (от цели на кражу СМ) остается без изменений и гибает при поднятии не щипцами, как любую другую расу, просто потому что адепты баланса сегодня не в духе.

Если не убрать ретурн то нукля может спокойно лапать СМ. Пока что узнаю у эши по поводу этого.

2024-03-11 19:08 UTC, BeebBeebBoob commented on code/modules/power/supermatter/supermatter.dm
> +		nucle_touch(moving_atom)
```suggestion
		nuclear_touch(moving_atom)
```

2024-03-11 19:08 UTC, BeebBeebBoob commented on code/modules/power/supermatter/supermatter.dm
> +	else if(istype(moving_atom, /mob/living))
```suggestion
	if(isliving(moving_atom))
```
У тебя сверху return, зачем нам else?

2024-03-11 19:12 UTC, Samirakis commented on code/modules/power/supermatter/supermatter.dm
> +		to_chat(user, span_userdanger("The wave of warm energy is overwhelming you. You feel calm."))
Про userdanger - воля автора Eshi

2024-03-11 19:15 UTC, BeebBeebBoob commented on code/modules/power/supermatter/supermatter.dm
> +	if(nuclear.touched_supermatter== FALSE)
```suggestion
	if(nuclear.touched_supermatter == FALSE)
```
fuck.

2024-03-11 19:16 UTC, BeebBeebBoob approved these changes

2024-03-12 10:00 UTC, Gottfrei approved these changes

2024-03-12 12:30 UTC, merged