bugfix: court extra pipes removed
ss220-space/Paradise pull request #4631
Opened 2024-03-14 13:53 UTC by ArtemDerp

## Описание

В суде убраны лишние трубы и поправлена проводка

## Ссылка на предложение/Причина создания ПР

![image](https://github.com/ss220-space/Paradise/assets/87157426/b7d12f36-b965-41b2-90bd-bcee7c8733ca)

https://github.com/ss220-space/Paradise/issues/2832

2024-03-14 13:58 UTC, ROdenFL commented
Дерп, там это у дверей доступ неправильный, почини заодно

2024-03-14 13:59 UTC, ROdenFL commented
Если починишь, скажи владису закрыть соответствующий ишуй

2024-03-14 14:43 UTC, SAADf603 requested changes
Багрепорт: в суде лишняя труба
Багфикс: шяс я доведу этот суд до ума УОХ

2024-03-14 14:43 UTC, SAADf603 commented on _maps/map_files/Delta/delta.dmm
> +	req_access = list(63,42)
Дерп, а ты знаешь у кого есть 42 доступ? Знаешь почему НИГДЕ на картах его нет?

2024-03-14 17:22 UTC, ROdenFL commented on _maps/map_files/Delta/delta.dmm
> +	req_access = list(63,42)
> Дерп, а ты знаешь у кого есть 42 доступ? Знаешь почему НИГДЕ на картах его нет?

ну, он есть у тех у кого он должен быть?

2024-03-14 17:23 UTC, ROdenFL commented on _maps/map_files/Delta/delta.dmm
> +	req_access = list(63,42)
> Дерп, а ты знаешь у кого есть 42 доступ? Знаешь почему НИГДЕ на картах его нет?

он у процедурного, он у хопа, нтра, кепа, он у сб
почему же его нет на картах?

2024-03-15 09:42 UTC, SAADf603 commented
Сам ты жаба

2024-03-15 09:46 UTC, ROdenFL commented
> Сам ты жаба

 gagaga

2024-03-15 10:08 UTC, Etrnlmelancholy commented
> Сам ты жаба

Лан все тише, жаба

2024-03-15 13:23 UTC, ItsMeJaba commented
Жаба на месте. Фиксирую полумеры, тут явно нужен реворк с захватом раздевалки дорм и переустройством техов рядом с сб, иначе никак

2024-03-16 08:33 UTC, SAADf603 approved these changes

2024-03-17 11:54 UTC, ArtemDerp commented
@Gottfrei @Vladisvell @Rerik007 тыкните апруве

2024-03-17 12:34 UTC, Gottfrei approved these changes

2024-03-17 12:39 UTC, merged