add: Drum Kit
ss220-space/Paradise pull request #4632
Opened 2024-03-14 16:12 UTC by xTrogwaRx

## Описание
Добавлена барабанная установка.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1217189181470543973

## Демонстрация изменений
https://github.com/ss220-space/Paradise/assets/25286304/debba802-cdc4-41c3-8116-f680919be48a

2024-03-18 13:57 UTC, Rerik007 commented on code/modules/instruments/objs/structures/drumkit.dm
> +	parent_type = /obj/structure/musician // TODO: Can't edit maps right now due to a freeze, remove and update path when it's done
Мап фриза нет, не мог бы ты убрать это?
```suggestion
/obj/structure/musician/drumkit
```
Ну и так везде обновить пути. С пианино вообще желательно тоже как нибудь убрать, но это впрочем не относится к пру.

2024-03-19 09:02 UTC, Rerik007 submitted a review, later dismissed

2024-03-19 09:52 UTC, SAADf603 requested changes
[ревью](https://discord.com/channels/617003227182792704/734823601110515882/1219582424124751903)

2024-03-19 12:20 UTC, Rerik007 approved these changes

2024-03-19 16:36 UTC, SAADf603 approved these changes

2024-03-19 17:18 UTC, merged