Перевод
ss220-space/Paradise pull request #477
Opened 2021-11-23 07:14 UTC by Dexersoul

Перевод окна входа в игру и создание персонажа... предметы только аксессуары... пока что

2021-11-23 07:21 UTC, dj-34 commented on code/modules/client/preference/preferences.dm
> +	HTML += ShowDisabilityState(user, DISABILITY_FLAG_LISP, "Лисп")
Шепелявость

2021-11-23 07:22 UTC, dj-34 commented on code/modules/mob/new_player/new_player.dm
> +		output += "<br /><small>Вы <b>[client.skip_antag ? "не притендуете" : "притендуете"]</b> на роль антагониста.</small></p>"
прЕтендуете

2021-11-23 10:37 UTC, Dexersoul commented on code/modules/client/preference/preferences.dm
> +	HTML += ShowDisabilityState(user, DISABILITY_FLAG_LISP, "Лисп")
> 

обновлю в следующем переводе. Спасибо! =)

2021-11-23 10:38 UTC, Dexersoul commented on code/modules/mob/new_player/new_player.dm
> +		output += "<br /><small>Вы <b>[client.skip_antag ? "не притендуете" : "притендуете"]</b> на роль антагониста.</small></p>"
> прЕтендуете

Исправлено. Прошу прощения.. это прошлый файл... в следующем тот закину

2021-11-25 08:48 UTC, Vallat requested changes

2021-11-25 08:48 UTC, Vallat commented on code/modules/client/preference/preferences.dm
> +			if(jobban_isbanned(user, "Записи"))
"Records" не нужно переводить, сломает проверку.

2021-11-25 08:48 UTC, Vallat commented on code/modules/client/preference/preferences.dm
> +							to_chat(user, "<font color='red'>Ваше имя должно содержать не менее 2 и не более [MAX_NAME_LEN] символов. Оно может содержать только символы A-Z, a-z, -, ' и .</font>")
Добавь тогда уж, что может содержать еще и символы А-Я, а-я. Либо переписать, что может содержать символы латинского и русского алфавитов

2021-11-25 08:48 UTC, Vallat commented on code/modules/client/preference/preferences.dm
> +					var/new_relation = input(user, "Выберите свое отношение к NT. Обратите внимание, что это отражает то, что другие могут узнать о вашем персонаже, изучив вашу биографию, а не то, что ваш персонаж
Ломает проверку на 113 строчке в функции get_suspect() в файле gamemodes.dm. Либо не переводить, либо там менять проверку тоже

2021-11-25 08:48 UTC, Vallat commented on code/modules/client/preference/preferences.dm
> +						var/newgender = input(user, "Выберите пол:") as null|anything in list("Мужской", "Женский", "Безполый")
Перевод сделал, а под код ниже не адаптировал, из-за чего смена пола фактически его менять никак не будет. Доделать

2022-04-27 21:44 UTC, closed without merging