add: Cerestation virology lab space optimization and small map tweaks.
ss220-space/Paradise pull request #4793
Opened 2024-04-03 18:15 UTC by Daeberdir

## Описание
- Оптимизация пространства вирологии Фаррагуса для двух вирологов.
- Техи виро больше не окружают само виро, а отграничивают его от меда.
- Исправление мельчайших проёбов зон, декалей, etc.
- Убран прилипающий к руке шеймбреро из космоса. Ему на замену у СЗ соляр закинут коллекционный шлем ЕРТ командира и плакат с ним же.

## Причина создания ПР
Сквик попросил.

## Демонстрация изменений
![fafafafafafaf](https://github.com/ss220-space/Paradise/assets/115735095/fde69ef3-719a-4cd2-a0e1-23f9680f50ab)

2024-04-17 16:06 UTC, aeternaclose requested changes
Тарищ, зачем pai вендомант украли? Верните на место, это собственность корпорации.

2024-04-21 11:49 UTC, aeternaclose submitted a review, later dismissed

2024-04-21 16:46 UTC, Daeberdir commented
В этом ПРе ничего не произошло 21.04.24.

2024-04-21 16:55 UTC, closed without merging

2024-04-21 17:46 UTC, LiquidPotroh commented
Ба за