feat: Training base. DO NOT MERGE
ss220-space/Paradise pull request #483
Opened 2021-11-27 15:31 UTC by AddRaiser

## What Does This PR Do

Система для обучения игроков + уже готовое базовое обучение новичков

2021-11-27 16:10 UTC, Vallat requested changes
Во всем файле training_master.dm нормально прописать пути к функциям

2021-11-27 16:10 UTC, Vallat commented on code/modules/mob/living/carbon/human/training/human_training.dm
> +		. = ..()
У нас строгое указывание пути
```suggestion
/mob/living/carbon/human/human_training/Initialize(mapload, datum/species/new_species)
	training_master = new(locate(20, world.maxy - 20, 1), src)
	. = ..()
```

2021-11-27 16:10 UTC, Vallat commented on code/modules/mob/living/carbon/human/training/human_training.dm
> +		training_master = new(locate(20, world.maxy - 20, 1), src)
В идеале привязка должна быть не по координатам, а по ландмаркам. И к ландмаркам этим нужно привязать занят ли данный трейнинг рум или нет. Ну и вынести собственно привязку к training_master и ландмарку в спавн, где и будет это всё происходит вместе со спавном моба

2021-12-03 16:28 UTC, AddRaiser commented on code/modules/mob/living/carbon/human/training/human_training.dm
> +		training_master = new(locate(20, world.maxy - 20, 1), src)
Мне не нравится идея с ландмарками, так что я просто сделал нормальный алгоритм создания комнат

2022-05-24 10:12 UTC, closed without merging