fix: changeling can not humanize if monkeyized using DNA-Injector #458
ss220-space/Paradise pull request #485
Opened 2021-12-02 14:31 UTC by ARZUMATA

## What Does This PR Do

**humanform.dm:**

- Больше не просит превратиться в человека и др, если вы НЕ находитесь в их меньшей форме.
- Абилка больше не удаляется при использовании (она постоянна и требуется для исправления бага).
- Удален код "SelectDNA", так как он дублирует метод select_dna в transform.dm.

**lesserform.dm:**

- Дает абилку "Human form" сразу при покупке, а не при активации.
(теперь ее можно было использовать, если обезьяна превратится в человека с помощью инжектора ДНК).
- Удалена лишняя переменная "var/mob/living/carbon/human/H = user", так как можно использовать "var/mob/living/carbon/human/user" напрямую.

**transform_procs.dm:**

- Метод monkeyize теперь проверяет, существует ли вообще блок monkey, чтобы избежать вызова "genemutcheck", когда это не требуется.
- Добавлен метод humanize, а также проверки is_monkeized и is_humanized для дальнейшего использования позже.

**transform.dm:**

- Диалог выбора ДНК теперь показывает отсортированный список.

## Why It's Good For The Game

Исправление бага, когда генокрад не превращается в макаку, после укола DNA инджектором. (т.к. Lesserform не использовалась, то humanform абилка не добавляется).

Небольшой рефактор для читаемости и качества кода.

## Changelog
:cl:
fix: changeling can not humanize if monkeyized using DNA-Injector #458
/:cl:

2021-12-02 18:56 UTC, Vallat requested changes

2021-12-02 18:56 UTC, Vallat commented on code/modules/mob/transform_procs.dm
> +	var/mob/H = src
Зачем здесь это? Моб это родитель хумана, у него и так есть переменная `dna`

2021-12-02 18:56 UTC, Vallat commented on code/modules/mob/transform_procs.dm
> +	var/mob/H = src
Тоже самое и здесь, непонятно зачем оно нужно.

2021-12-02 18:56 UTC, Vallat commented on code/modules/mob/transform_procs.dm
> +	var/mob/H = src
И здесь тоже

2021-12-02 21:26 UTC, ARZUMATA commented on code/modules/mob/transform_procs.dm
> +	var/mob/H = src
`var/mob/H = src`
вот это?

если да, то я сделал это по аналогии с уже имеющейся 
`/mob/living/carbon/human/proc/monkeyize()`

получается, что этот метод тоже сделан неверно и можно сразу указывать src.dna.GetSEState и т.д.
если так - тогда сделаю правки и исправлю все 4 метода

2021-12-03 05:44 UTC, Vallat commented on code/modules/mob/transform_procs.dm
> +	var/mob/H = src
Получается что сделан неверно. 'src' тоже опускается в данном случае
Код для `monkeyize()`, например, должен выглядеть вот так
```
/mob/living/carbon/human/proc/monkeyize()
	dna.SetSEState(GLOB.monkeyblock, TRUE)
	genemutcheck(src, GLOB.monkeyblock, null, MUTCHK_FORCED)
```

2021-12-03 11:54 UTC, ARZUMATA commented on code/modules/mob/transform_procs.dm
> +	var/mob/H = src
Да, теперь и код стал чище, спасибо.
Но я разве что добавлю `if (!dna.GetSEState(GLOB.monkeyblock))`
При отладке, эта проверка занимает меньше времени, чем сразу выставлять SetSEState и вызывать genemutcheck.
Т.е. метод будет быстрее возвращать если вызван уже на моба с включенным блоком.

2021-12-03 15:47 UTC, Vallat approved these changes

2021-12-03 15:47 UTC, Vallat commented on code/modules/mob/transform_procs.dm
> +	return TRUE
Можно было бы заменить вот так, но в целом сойдет
```suggestion
	return !dna.GetSEState(GLOB.monkeyblock)
```

2021-12-03 20:36 UTC, ARZUMATA commented on code/modules/mob/transform_procs.dm
> +	return TRUE
так и сделаю

2021-12-04 17:42 UTC, merged