Add: gold Desert Eagle to badassery
ss220-space/Paradise pull request #4917
Opened 2024-04-19 20:32 UTC by Shakalchik

## Описание
Добавляет золотой дигл за 50 ТК и патроны к нему по 5 ТК в раздел badassery аплинка агентов. Для крутых агентов, которые убивают на стиле. Согласно предложке.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1230845218308231218

## Демонстрация изменений
![image](https://github.com/ss220-space/Paradise/assets/66063344/f4c75b0e-20fe-4e3c-a04b-8a651ef449ea)

2024-04-19 20:58 UTC, Shakalchik commented
Упс, я там коммит насрал не туда))

2024-04-20 15:26 UTC, Rerik007 submitted a review, later dismissed

2024-04-20 17:20 UTC, Daeberdir requested changes

2024-04-20 17:20 UTC, Daeberdir commented on code/datums/uplink_item.dm
> +	desc = "A badass gold plated desert eagle folded over a million times by superior martian gunsmiths. Uses .50 AE ammo. Kill with style"
```suggestion
	desc = "A badass gold plated Desert Eagle folded over a million times by superior martian gunsmiths. Uses .50 AE ammo. Kill with style."
```
Определись, с большой должно быть название дигла или с маленькой.

2024-04-20 17:21 UTC, Shakalchik commented on code/datums/uplink_item.dm
> +	desc = "A badass gold plated desert eagle folded over a million times by superior martian gunsmiths. Uses .50 AE ammo. Kill with style"
Пусть будет с большой, а так скопировал с аплинка нуклиров, тогда и там менять?

2024-04-20 19:47 UTC, Daeberdir commented on code/datums/uplink_item.dm
> +	desc = "A badass gold plated desert eagle folded over a million times by superior martian gunsmiths. Uses .50 AE ammo. Kill with style"
![Screenshot_20240420-224102_GitHub.jpg](https://github.com/ss220-space/Paradise/assets/115735095/b5d39006-5467-474b-826c-8aba8fd9431f)

У тебя был просто уже был вариант, где дигл был прописан с большой в дескрипшине обоймы, так что я именно использовал слово "выбери". Либо во всех дескрипшинах с маленькой, либо с большой. Я не говорю, что это обязательная заморочка, но внутренний перфекционист убивает.

2024-04-21 19:59 UTC, Daeberdir commented on code/datums/uplink_item.dm
> +	desc = "A badass gold plated Desert Eagle folded over a million times by superior martian gunsmiths. Uses .50 AE ammo. Kill with style."
```suggestion
	desc = "A badass gold plated Desert Eagle folded over a million times by superior martian gunsmiths. Uses .50AE ammo. Kill with style."
```
Окей. Тогда тут есть ещё, где вылизать.

2024-04-21 19:59 UTC, Daeberdir commented on code/datums/uplink_item.dm
> +/datum/uplink_item/badass/deagle_mag
Тут уже есть магазины для дигла по 5ТК на строчке 1064 (`/datum/uplink_item/ammo/deagle`), так что тебе нужно не добавлять копию этого датума, а стереть там строчку `uplinktypes = list(UPLINK_TYPE_NUCLEAR, UPLINK_TYPE_SST)` и всё на этом. Перемещение боеприпасов из раздела... боеприпасов просто не имеет смысла.

2024-04-21 20:16 UTC, Daeberdir commented on code/datums/uplink_item.dm
> -	uplinktypes = list(UPLINK_TYPE_NUCLEAR, UPLINK_TYPE_SST)
Промазал 🤣 
Отдохни, потом ещё раз попробуй 1064 строчку найти.

2024-04-22 07:45 UTC, Gottfrei approved these changes, later dismissed

2024-04-22 10:33 UTC, Daeberdir approved these changes, later dismissed

2024-04-22 10:42 UTC, Rerik007 approved these changes, later dismissed

2024-04-22 10:47 UTC, Gottfrei commented on code/datums/uplink_item.dm
> +	surplus = 0
то есть теперь мы сперва заносим патроны только в аплинк нюкеров, а затем исключаем из аплинка нюкеров. так?

2024-04-22 10:51 UTC, Gottfrei commented on code/datums/uplink_item.dm
> +	excludefrom = list(UPLINK_TYPE_NUCLEAR, UPLINK_TYPE_SST)
```suggestion
	uplinktypes = list(UPLINK_TYPE_TRAITOR)
```

2024-04-22 10:52 UTC, Gottfrei commented on code/datums/uplink_item.dm
> +	excludefrom = list(UPLINK_TYPE_NUCLEAR, UPLINK_TYPE_SST)
но вообще зачем нам этот отдельный аплинк айтем, просто добавь трейторский тип аплинка в позицию выше. плюс там же выше можешь поставить нулевой шанс на сюрплюс - у оперативников их попросту нет.

2024-04-22 10:57 UTC, Shakalchik commented on code/datums/uplink_item.dm
> +	excludefrom = list(UPLINK_TYPE_NUCLEAR, UPLINK_TYPE_SST)
Точно-ли лучше отличающийся от других вариант и еще аплинка инфильтратора тут нет

2024-04-22 11:04 UTC, Shakalchik commented on code/datums/uplink_item.dm
> +	excludefrom = list(UPLINK_TYPE_NUCLEAR, UPLINK_TYPE_SST)
А, у оперов то нет сурплюса, тогда нет смысла в моем, сейчас

> но вообще зачем нам этот отдельный аплинк айтем, просто добавь трейторский тип аплинка в позицию выше. плюс там же выше можешь поставить нулевой шанс на сюрплюс - у оперативников их попросту нет.

2024-04-22 13:11 UTC, Daeberdir approved these changes

2024-04-22 13:53 UTC, Gottfrei approved these changes

2024-04-22 13:58 UTC, merged