tweak: Nanocalcium fixes bones and bleedings faster
ss220-space/Paradise pull request #4950
Opened 2024-04-22 15:17 UTC by Ksaikok46

## Описание
Нанокальций стал чинить сломанные кости и внутренние кровотечения в 2 раза быстрее, количество вещества в шприце также уменьшилось в 2 раза.
**Было:**
Шприц вкалывал 30 юнитов нанокальция, которые полностью усваиваются за 60 циклов, лечение переломов/внутряков начиналось на 45 цикле с шансом 25% в цикл.
**Стало:**
Шприц вкалывает 15 юнитов нанокальция, которые полностью усваиваются за 30 циклов, лечение переломов/внутряков начинается на 23 цикле с шансом 50% в цикл. 

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1231376084096778301

2024-04-22 15:38 UTC, Gottfrei commented on code/modules/reagents/chemistry/reagents/medicine.dm
>  						I.heal_internal_damage(4)
а почему лечение и урон ниже не проскалировал?

2024-04-22 15:49 UTC, Ksaikok46 commented on code/modules/reagents/chemistry/reagents/medicine.dm
>  						I.heal_internal_damage(4)
> а почему лечение и урон ниже не проскалировал?

посовещался с автором предложки, но если думаешь что лучше проскалировать, то могу сделать
![image](https://github.com/ss220-space/Paradise/assets/139886553/f2b6a7c4-3ae3-47e5-aa2d-801bd68f6c68)

2024-04-22 16:06 UTC, Gottfrei commented on code/modules/reagents/chemistry/reagents/medicine.dm
>  						I.heal_internal_damage(4)
просто я не вижу никаких упоминаний в ТЗ. раз мы всё скалируем, то пускай будет всё.

2024-04-22 16:50 UTC, Daeberdir commented
Зажлобил 1 лишний цикл, жесть 😿

2024-04-22 19:33 UTC, Gottfrei submitted a review, later dismissed

2024-04-23 18:09 UTC, Daeberdir requested changes

2024-04-23 18:09 UTC, Daeberdir commented on code/modules/reagents/chemistry/reagents/medicine.dm
>  			if(has_stimulant == TRUE)
```suggestion
			if(has_stimulant)
```
Небольшое прихорашивание.

2024-04-23 18:09 UTC, Daeberdir commented on code/modules/reagents/chemistry/reagents/medicine.dm
>  			if(has_stimulant == TRUE)
```suggestion
			if(has_stimulant)
```

2024-04-23 18:09 UTC, Daeberdir commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	taste_description = "1 minute of suffering"
```suggestion
	taste_description = "minute of suffering"
```
Вот тут не уверен, как ему лучше выглядеть, но мне бы так больше понравилось без единички.

2024-04-23 18:09 UTC, Daeberdir commented on code/modules/reagents/chemistry/reagents/medicine.dm
>  			for(var/datum/reagent/R in M.reagents.reagent_list)
```suggestion
			if(has_stimulant)
				for(var/datum/reagent/R in M.reagents.reagent_list)
```
Тут прогонку по списку реагентов второй раз стоит пропустить, если в первый раз ничего интересного в них не нашлось.
Но там чуть ниже уже сам протабулируй.

2024-04-23 19:21 UTC, Daeberdir approved these changes

2024-04-24 08:27 UTC, Gottfrei approved these changes

2024-04-24 08:32 UTC, merged