bugfix: Flags Inv Fixes
ss220-space/Paradise pull request #4954
Opened 2024-04-23 16:56 UTC by Gottfrei

## Описание
Фикс нескольких флагов, влияющих на отображение у шлемов и масок.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/1232347299678519456

2024-04-23 17:23 UTC, Daeberdir requested changes

2024-04-23 17:23 UTC, Daeberdir commented on code/modules/clothing/head/jobs.dm
>  /obj/item/clothing/head/hooded/chaplain_hood/no_name
![image](https://github.com/ss220-space/Paradise/assets/115735095/3b217ab5-2d71-4a79-835c-8ce9482aabdb)
Вместо прочерка бы наследование родителя.

2024-04-23 17:23 UTC, Daeberdir commented on code/modules/clothing/head/helmet.dm
>  	flags = null
```suggestion
	flags = NONE
```
Чтоб потом не возвращаться...

2024-04-23 18:21 UTC, Daeberdir approved these changes

2024-04-24 08:51 UTC, Rerik007 approved these changes

2024-04-24 09:07 UTC, merged