tweak: [Перевод] Update quest workers
ss220-space/Paradise pull request #4959
Opened 2024-04-24 09:26 UTC by pilygun

## Описание
Перевод текста за хорошее/плохое выполнение поставок карго. Все сделано по ТЗ карго апдейта корнеплода. Никакой отсебятины. Все скопировано и вставлено как в ТЗ корнеплода, даже знаки пунктуации те же.
Приятно когда хвалят на родном языке, неприятно когда на нем ругают.
Баланс соблюден.

## Ссылка на предложение/Причина создания ПР
https://drive.google.com/drive/folders/1JqgX020enj67P8kOXCYUc7oWKvfmhPcs

https://discord.com/channels/617003227182792704/618952559607939072/1149697180941156482
https://discord.com/channels/617003227182792704/618952559607939072/1149695750280843285

## Демонстрация изменений
![image](https://github.com/ss220-space/Paradise/assets/42041683/34ae6e92-3659-4922-99ac-ec7f478a57c9)

2024-04-24 10:06 UTC, NightDawnFox commented on strings/quest_workers.json
> +		"Посылка прошла мимо нас и отправилась на корпоратив высшего офицерского состава флота. Ой-ой. ",
```suggestion
		"Посылка прошла мимо нас и отправилась на корпоратив высшего офицерского состава флота. Ой-ёй. ",
```

2024-04-24 10:06 UTC, NightDawnFox commented on strings/quest_workers.json
> +		"Посылка прошла мимо нас и отправилась на корпоратив высшего офицерского состава флота. Ой-ой. ",
И никак иначе.

2024-04-24 13:04 UTC, Daeberdir requested changes

2024-04-24 13:04 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Мужики спасибо, а то так работать не хотелось.",
```suggestion
		"Мужики, спасибо, а то так работать не хотелось.",
```
Много запятых потерял.

2024-04-24 13:04 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Кстати, а правда, что у вас там со скреллками можно познакомиться?? ",
```suggestion
		"Можете рассчитывать на поблажки, хорошо потрудились.",
		"Умеете же, когда хотите.",
		"Кстати, а правда, что у вас там со скреллками можно познакомиться?",
```
И вот пробелы бы лишние постирать...

2024-04-24 13:04 UTC, Daeberdir commented on strings/quest_workers.json
> -		"Amount discrepancy, I have to cut a part your pay. ",
А это куда подевалось?

2024-04-24 13:06 UTC, pilygun commented on strings/quest_workers.json
> -		"Amount discrepancy, I have to cut a part your pay. ",
> А это куда подевалось?

Так рядом же 
Или я чего то не вижу

2024-04-24 13:14 UTC, Daeberdir commented on strings/quest_workers.json
> -		"Amount discrepancy, I have to cut a part your pay. ",
> Так рядом же Или я чего то не вижу
![image](https://github.com/ss220-space/Paradise/assets/115735095/765be641-a62f-4444-9266-0fa0c750bb23)
110 строчку **я** не вижу.

2024-04-24 15:35 UTC, pilygun commented on strings/quest_workers.json
> -		"Amount discrepancy, I have to cut a part your pay. ",
> ![image](https://private-user-images.githubusercontent.com/115735095/325232956-765be641-a62f-4444-9266-0fa0c750bb23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzMyMzQsIm5iZiI6MTcxMzk3MjkzNCwicGF0aCI6Ii8xMTU3MzUwOTUvMzI1MjMyOTU2LTc2NWJlNjQxLWE2MmYtNDQ0NC05MjY2LTBmYTBjNzUwYmIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNTM1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTAwZDM3NTQxNmQzMDI3Mjc3NmE1ZjA2YTdlMzQ0NDA5N2I4Mzk0YTI4OGU4MjIwYmQ4NGZmMWY0ZDlkYTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0BgtGhDZOTVRCqHqWTHnPjrtg2OHQipfkgaJAqG6LHo) 110 строчку **я** не вижу.

Ага нашел вернул

2024-04-24 19:52 UTC, Rerik007 reviewed
Мои старенькие некрасивые пробелы. Не мог бы ты их убрать в паре мест?

2024-04-24 19:52 UTC, Rerik007 commented on strings/quest_workers.json
> +		"У вас там одни мартышки что ли в снабжении? ",
```suggestion
		"У вас там одни мартышки что ли в снабжении?",
```

2024-04-24 19:52 UTC, Rerik007 commented on strings/quest_workers.json
> +		"Чего-то не хватает, непорядок." ,
```suggestion
		"Чего-то не хватает, непорядок.",
```

2024-04-24 19:52 UTC, Rerik007 commented on strings/quest_workers.json
> +		"От лица отдела выражаю огромную благодарность за труды." ,
```suggestion
		"От лица отдела выражаю огромную благодарность за труды.",
```

2024-04-24 19:52 UTC, Rerik007 commented on strings/quest_workers.json
> +		"В следующий раз поторопитесь, едва успели. ",
```suggestion
		"В следующий раз поторопитесь, едва успели.",
```

2024-04-25 19:08 UTC, Rerik007 approved these changes, later dismissed

2024-04-27 13:08 UTC, Gottfrei submitted a review, later dismissed

2024-04-27 13:10 UTC, Daeberdir commented
Ладно. Please, stand by.

2024-04-27 13:27 UTC, Daeberdir requested changes

2024-04-27 13:27 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Сначала четвёртый отдел, потом ревизоры, а теперь ещё и вы? Мне семью кормить надо, хотя вам то какое дело.",
```suggestion
		"Сначала четвёртый отдел, потом ревизоры, а теперь ещё и вы? Мне семью кормить надо, хотя ВАМ то какое дело.",
```
Тут необязательное, но в оригинале было вполне уместно.

2024-04-27 13:27 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Всё пришло что заказывали, класс.",
```suggestion
		"Всё пришло, что заказывали, класс.",
```

2024-04-27 13:27 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Хорошая работа парни, очень помогли. Если что будет нужно у нас, скажите, что вы от Грэга.",
```suggestion
		"Хорошая работа, парни, очень помогли. Если что будет нужно у нас, скажите, что вы от Грэга.",
```

2024-04-27 13:27 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Я отрапортую куда надо что вы нам очень помогли сегодня.",
```suggestion
		"Я отрапортую куда надо, что вы нам очень помогли сегодня.",
```

2024-04-27 13:27 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Реально хорошо справились, молодцы парни.",
```suggestion
		"Реально хорошо справились, молодцы, парни.",
```

2024-04-27 13:27 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Во вы лютые, а можно к вам на работу?",
```suggestion
		"Во вы ЛЮТЫЕ, а можно к вам на работу?",
```
Тоже не обязательно, но в оригинале это хорошо смотрелось.

2024-04-27 13:27 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Вычет за отсутствие комплекта. Следите, что вы отправляете.",
```suggestion
		"Вычет за отсутствие комплекта. Следите за тем, что вы отправляете.",
```

2024-04-27 13:27 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Ну пока посылка ехала, она уже оказалась не нужна."
```suggestion
		"Ну, пока посылка ехала, она уже оказалась не нужна."
```

2024-04-27 13:27 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Мужики вы обсчитались.",
```suggestion
		"Мужики, вы обсчитались.",
```

2024-04-27 13:27 UTC, Daeberdir commented on strings/quest_workers.json
> +		"Не то количество какое надо.",
```suggestion
		"Не то количество, какое надо.",
```

2024-04-27 14:29 UTC, Daeberdir approved these changes

2024-04-27 15:05 UTC, Gottfrei approved these changes

2024-04-27 15:10 UTC, merged