refactor: No Transform Trait
ss220-space/Paradise pull request #4961
Opened 2024-04-24 15:59 UTC by Gottfrei

## Описание
Переменная notransform перекочевала в трейт TRAIT_NO_TRANSFORM, что позволяет использовать её более гибко.

2024-04-25 08:49 UTC, Daeberdir requested changes

2024-04-25 08:49 UTC, Daeberdir commented on code/datums/spells/devil.dm
> +	if(HAS_TRAIT(src, TRAIT_NO_TRANSFORM))
```suggestion
	if(HAS_TRAIT_FROM(src, TRAIT_NO_TRANSFORM, UNIQUE_TRAIT_SOURCE(spell)))
```
Кажется, тут промах.

2024-04-25 08:49 UTC, Daeberdir commented on code/datums/diseases/viruses/transformation.dm
> +		ADD_TRAIT(affected_mob, TRAIT_NO_TRANSFORM, UNIQUE_TRAIT_SOURCE(src))
```suggestion
		ADD_TRAIT(affected_mob, TRAIT_NO_TRANSFORM, PERMANENT_TRANSFORMATION_TRAIT)
```

2024-04-25 08:49 UTC, Daeberdir commented on code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +			ADD_TRAIT(user, TRAIT_NO_TRANSFORM, UNIQUE_TRAIT_SOURCE(src))
```suggestion
			ADD_TRAIT(user, TRAIT_NO_TRANSFORM, PERMANENT_TRANSFORMATION_TRAIT)
```

2024-04-25 09:20 UTC, Gottfrei commented on code/datums/spells/devil.dm
> +	if(HAS_TRAIT(src, TRAIT_NO_TRANSFORM))
в данном случае нас интересует любой ноутрансформ.

2024-04-25 09:43 UTC, Daeberdir commented on code/datums/spells/devil.dm
> +	if(HAS_TRAIT(src, TRAIT_NO_TRANSFORM))
Мгм... тогда не стоит добавлять в вар `spell` в прок.

2024-04-25 10:04 UTC, Gottfrei commented on code/datums/spells/devil.dm
> +	if(HAS_TRAIT(src, TRAIT_NO_TRANSFORM))
пускай будет уже, по аналогии с infernalphaseout

2024-04-25 10:27 UTC, Daeberdir commented on code/datums/spells/devil.dm
> +	if(HAS_TRAIT(src, TRAIT_NO_TRANSFORM))
Это отвлекает. Ладно.
Ещё вопрос. `"temporary_transformation"` - это какое-то запланированное улучшение для проков смены расы?

2024-04-25 10:34 UTC, Daeberdir approved these changes, later dismissed

2024-04-25 10:35 UTC, Gottfrei commented on code/datums/spells/devil.dm
> +	if(HAS_TRAIT(src, TRAIT_NO_TRANSFORM))
да, это будет у мартышек, когда мой код генов зальют.

2024-05-10 07:15 UTC, Rerik007 submitted a review, later dismissed

2024-05-10 08:30 UTC, Daeberdir approved these changes

2024-05-10 08:34 UTC, Rerik007 approved these changes

2024-05-10 15:50 UTC, merged