balance: Cargo quests, garbage disposal and price balance
ss220-space/Paradise pull request #4968
Opened 2024-04-25 17:58 UTC by pilygun

## Описание
Из заказов на поставки карго удалены трофеи с крашера (Только мега фауна), а так же удален полностью лут с тендрилов - причина, трофеи не продают из за слишком высокой ценности и многие из них в еденичном экземпляре. А лут с тендрилов слишком рандомный для карго.

Редкие семена перенесены в тир очень сложных заказов и увеличена награда за выполнение в 2 раза.

Сложные напитки и еда так же были апнуты по КП за выполнения. Некоторые были преренесены с тира легких поставок на средние

Я долго обговаривал пару минорных изменений карго квестов с Человеком и геймдизайнером, и уже был готов просить рерика закодить. Как вдруг понял что я могу сделать это и сам.

## Ссылка на предложение/Причина создания ПР
![image](https://github.com/ss220-space/Paradise/assets/42041683/3d996ff4-091f-432d-990f-726ff9807c0b)

2024-04-25 19:01 UTC, Rerik007 approved these changes

2024-04-25 19:03 UTC, Rerik007 requested changes
Хотя не заметил. Сделай чтобы в майнинг категории в категории normal было 4 вещи или распредели их из неё.

2024-04-26 08:40 UTC, Rerik007 approved these changes

2024-04-27 13:03 UTC, Gottfrei approved these changes

2024-04-27 13:08 UTC, merged