Feat: Overpriced marines cigarettes
ss220-space/Paradise pull request #498
Opened 2021-12-07 07:45 UTC by RenovatedAtol

## What Does This PR Do

PR Добавляет сигареты с тгмс по сумасшедшей цене и вендор с новыми сигаретами.
![image](https://user-images.githubusercontent.com/81752268/144986427-5371e265-1aff-4ee4-a92b-fee598c20d5a.png)

В одной пачке 18 сигарет, на всю станцию один автомат (Как идея на будущее добавить один автомат в переговорку глав или переместить к бармену)
![image](https://user-images.githubusercontent.com/81752268/144986518-27299373-271c-44ec-bd3e-916d1908b350.png)

Если автомат взломать, можно получить две пачки сигарет с медицинской травой (как у психиатора)
![image](https://user-images.githubusercontent.com/81752268/144987351-5b602796-2cb9-4426-a27a-06b47a5c1784.png)

Место спавна автомата на дельте:
![image](https://user-images.githubusercontent.com/81752268/144987448-722f100e-7ab4-4296-83e3-807add6150a5.png)

Место спавна автомата на коробке:
![image](https://user-images.githubusercontent.com/81752268/144987528-662bad49-c8ef-46c8-9817-bb625816f23b.png)

## Why It's Good For The Game

PR обновляет и утилизирует неиспользуемую модельку вендора с флагом США

PR добавляет больше функций для денег, теперь каждый куряга захочет получить себе пачку раритеных сигарет, а также добавляет возможности для спекуляции

## Changelog
:cl:
add: Added new vendor
add: Added new cigarettes
add: Added new spawn places for vendors

/:cl:

2021-12-07 09:24 UTC, Vallat approved these changes
Сквошнуть коммиты и нормально

2021-12-07 10:44 UTC, BeebBeebBoob commented
Они уникальные что обидно. Добавить опцию для платы вендоров и в карго наполнитель чтобы можно было собрать.

2021-12-07 10:50 UTC, RenovatedAtol commented
> Они уникальные что обидно. Добавить опцию для платы вендоров и в карго наполнитель чтобы можно было собрать.

Так ведь в этом и смысл, чтоб это был раритетный и дефицитный товар

Я изначально думал оставить дефолтный сигаретный рефил, но потом вспомнил, что это ведь импортные маринские сигареты и убрал его

2021-12-15 09:11 UTC, Bizzonium requested changes

2021-12-15 09:11 UTC, Bizzonium commented on code/game/objects/items/weapons/storage/fancy.dm
> +	storage_slots = 18
```suggestion
```

2021-12-15 09:11 UTC, Bizzonium commented on code/game/objects/items/weapons/storage/fancy.dm
> +	max_combined_w_class = 18
```suggestion
```

2021-12-15 10:31 UTC, RenovatedAtol commented on code/game/objects/items/weapons/storage/fancy.dm
> +	storage_slots = 18
Не очень хочется удалять основную фичу ради чего всё делалось
Также если изменить размер пачки, придётся переделывать спрайты сигарет, иначе автомат будет выдывать пачки с полупустым спрайтом

2022-06-17 11:40 UTC, closed without merging