Fix: Disappearing zippo
ss220-space/Paradise pull request #510
Opened 2021-12-11 13:46 UTC by RenovatedAtol

## What Does This PR Do

PR фиксит баг с пропаданием кастомных зиппо из рук персонажа после их включения-выключения

## Changelog
fix: disappearing zippo bug

/:cl:

2021-12-11 14:01 UTC, Vallat approved these changes

2021-12-15 09:32 UTC, Bizzonium requested changes

2021-12-15 09:32 UTC, Bizzonium commented on code/game/objects/items/weapons/lighters.dm
> +	//item_state = icon_on
```suggestion
```

2021-12-15 09:32 UTC, Bizzonium commented on code/game/objects/items/weapons/lighters.dm
> +	//item_state = icon_off
```suggestion
```

2021-12-15 09:32 UTC, Bizzonium approved these changes

2021-12-15 09:32 UTC, merged