fix: Make radio great again in tcomms blackout
ss220-space/Paradise pull request #513
Opened 2021-12-12 21:55 UTC by BeebBeebBoob

## What Does This PR Do

Фиксит давно старое радио в ручках и интеркомчики дабы они снова звенели во время аномалии ионосферки.
Спасибо людям из оффов( https://github.com/ParadiseSS13/Paradise/pull/17208 ) мы смогли вернуть радио И интеркомы в рабочее состояние!

## Why It's Good For The Game

Радио и интеркомы снова имеют смысл! И даже большой!

## Images of changes

![image](https://user-images.githubusercontent.com/32985153/145731045-07ce9c4c-bfa4-4ee8-a54e-f2615aacc1e0.png)

## Changelog
:cl:
fix: fixes radio during tcomms blackout
/:cl:

2021-12-13 06:00 UTC, Vallat requested changes

2021-12-13 06:00 UTC, Vallat commented on code/game/machinery/tcomms/_base.dm
> -	if(tcm?.connection?.frequency != display_freq)
Вот это вот менять не нужно

2021-12-13 09:21 UTC, BeebBeebBoob commented on code/game/machinery/tcomms/_base.dm
> -	if(tcm?.connection?.frequency != display_freq)
Случайно проехался тут но не пойму почему нельзя?

2021-12-14 04:33 UTC, Vallat approved these changes

2021-12-15 09:36 UTC, merged