add: head internal damage when mouthshooting
ss220-space/Paradise pull request #5147
Opened 2024-06-02 23:15 UTC by UberHelmsman

Shooting in the mouth changes projectile damage type depending on the main damage type (BURN -> BURNSUICIDE). Each new damage type deals damage including damage to internal organs.

## Описание
Теперь при стрельбе в рот брут, бёрн или клон уроном также наносится урон внутренним органам головы в размере x5 от изначального урона.

## Ссылка на предложение/Причина создания ПР
ПР для обзора и багфиксов, предложка попозже

## Демонстрация изменений

2024-06-02 23:23 UTC, UberHelmsman commented
какая то хуйня сломалась

2024-06-02 23:32 UTC, UberHelmsman commented
похоже, что сломалось что то из мульти зет, причем не пойму почему. В /datum/element/falling_hazard/proc/fall_onto_stuff вызывается poor_target.apply_damage(fall_damage * levels, def_zone = BODY_ZONE_HEAD), которую я меняю. Только по идее мои изменения никак не должны это ломать. Подожду ревью, надеюсь умные люди подскажут что нибудь

2024-06-05 11:45 UTC, UberHelmsman commented
все окончательно сломалось

2024-06-27 19:17 UTC, UberHelmsman commented
я не понимаю за что мердж конфликт если честно. Я вообще не понимаю, как мердж конфликт выставляется, но там просто ему не нравятся добавленные строчки, хотя оно не должно ломаться.

2024-06-27 19:56 UTC, UberHelmsman commented
алло а мы обновлять проверки будем нет

2024-06-27 20:58 UTC, UberHelmsman commented
Ну вердикт: хуй знает. Я не представляю, почему оно ломается. Если поставлю бйонд, попробую запустить на локалке и посмотреть, сломается или нет. Если нет - надеюсь предусмотрена такая процедура посылания проверок нахер.

2024-12-27 12:13 UTC, Antoonij requested changes
1. Нам точно не нужны новые типы урона 
2. в самом хендле суицида у оружия можно сделать прок, какой нибудь after_suicide(),
который мы будем вызывать после process_fire() (636 строка), в нем будем наносить урон органам, а также вызывать апплай демедж, передавая тип урона снаряда.

2024-12-27 18:28 UTC, closed without merging