refactor/tweak: Blob gamemode+event fix and rework
ss220-space/Paradise pull request #5312
Opened 2024-06-29 20:40 UTC by dageavtobusnick

## Описание
**Краткий список изменений:**

**Старт режима:**

- Ивент и режим теперь отличаются только стартом и носителем.
- Условия старта режима не меняются:
- - Режим стартует при 30 готовых игроках, с шансом как у нюки.
- - Выбирается по одному игроку за каждые 30 человек.
- Ивент стартует без геймпленых изменений.

**Нулевая стадия:**

- Время до вылупления блоба теперь составляет 10-15 минут (режим) или 1-3 минуты (ивент).
- Добавлены сообщения о состоянии зараженного: "Вы чувствуете усталость и раздутость", "Вы чувствуете, что вот-вот лопнете".
- Если зараженный находится за пределами станции, ему дается предупреждение и минута на возвращение.
- Цели зараженных блобом:
- - Найти укромное место на станции.
- - Набрать критическую массу (350 тайлов + 350 за каждое ядро блоба).

**Стадии угрозы:**

- Первая стадия: при достижении 20% критической массы приходит оповещение о возможной угрозе 5-го уровня, вводится карантин.
- Вторая стадия: при достижении 30% критической массы происходит глобальное оповещение и смена кода на ГАММА.
- Третья стадия: при достижении 80% критической массы приходит оповещение с приказом взвести боеголовку.

**Финал:**

- При достижении критической массы начинается споровая буря (30 секунд - 1 минута), после которой выводится сообщение о потере станции.
- Полная победа блоба: достигнута критическая масса и завершение раунда.
- Частичная победа блоба: взведена боеголовка до набора критической массы.
- Полная победа экипажа: уничтожение ядер блоба до достижения критической массы.
- Ничья: экипаж эвакуировался до первого сообщения без локдауна, блоб не достиг критической массы.

**Гринтекст:**

Отображение исхода режима, целей блобов и вылупившихся блобов, а так же офспрингов и блобернаутов.
Дополнительные моменты:

- Увеличение необходимой критической массы на 350 за каждого нового блоба.
- Зараженные могут отправлять телепатические сообщения другим зараженным.
- В HUD добавлен индикатор времени до вылупления.

**Админские кнопки:**

- Возможность заражать блобом большинство живых мобов, кроме определенных исключений.
- Настройка времени до вылупления, предупреждения о нахождении за пределами станции и замена зараженного игрока.
- Опции для снятия роли зараженного, лопания игрока, зараженного блобом, и отправки предупреждений блобам.

**Мыши, зараженные блобом:**

Мыши, зараженные блобом, предлагают призракам возможность управления при спавне.

Подробный список изменений: https://docs.google.com/document/d/1lCTCMYiI23y4XAv-qVmG-O_PQiovuDgpz5iYG0-n8vQ/edit?usp=sharing

Так же переведены способности блоба, описания и названия его реагентов, уведомление о получении роли зараженного, help text блоба, а так же сообщения о нем на консоли связи. 

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1257605286798164028

2024-07-01 10:48 UTC, Den109G commented on code/datums/weather/weather_types/blob_storm.dm
> +//Radiation storms occur when the station passes through an irradiated area, and irradiate anyone not standing in protected areas (maintenance, emergency storage, etc.)
Комментарий не соответствует файлу.

2024-07-01 10:48 UTC, Den109G commented on code/game/gamemodes/blob/blob.dm
> +			if(length(BLOB_RESTRICTED_JOBS) && (player.mind.assigned_role in BLOB_RESTRICTED_JOBS))
Почему мы не используем переменную режима `restricted_jobs`?

2024-07-01 10:48 UTC, Den109G commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Производит узел за 60 ресурсов.<br>Узлы будут расширяться и активировать ближайшие ресурсные и фабрики блобы."
Какой-то непостоянный перевод. Лучше постоянно называть вещи своими именами. Если в одном случае перевёл "resource blob" как "ресурсную плитку", то лучше продолжать так переводить и в остальных случаях.
```suggestion
	desc = "Производит узел за 60 ресурсов.<br>Узлы будут расширяться и активировать ближайшие ресурсные плитки и фабрики."
```

2024-07-01 10:48 UTC, Den109G commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Обменивает местами узел и ваше ядро за 80 ресурсов."
Странный перевод. "Обменивать" - это отдавать Х и получать У. А узел и ядро и так у блоба. Лучше на "менять место" заменить.
```suggestion
	desc = "Меняет местами узел и ваше ядро за 80 ресурсов."
```

2024-07-01 12:31 UTC, dageavtobusnick commented on code/game/gamemodes/blob/blob.dm
> +			if(length(BLOB_RESTRICTED_JOBS) && (player.mind.assigned_role in BLOB_RESTRICTED_JOBS))
Потому что это прок типа /datum/game_mode, а не /datum/game_mode/blob. Он может вызываться в разных режимах, в которых у него будет разное значение.

2024-07-01 12:39 UTC, dageavtobusnick commented on code/datums/weather/weather_types/blob_storm.dm
> +//Radiation storms occur when the station passes through an irradiated area, and irradiate anyone not standing in protected areas (maintenance, emergency storage, etc.)
Поправил

2024-07-01 12:49 UTC, dageavtobusnick commented on code/game/gamemodes/blob/blob.dm
> +			if(length(BLOB_RESTRICTED_JOBS) && (player.mind.assigned_role in BLOB_RESTRICTED_JOBS))
Но проблему увидел. Поправил через переменную `blob_restricted_jobs`

2024-07-01 12:50 UTC, Den109G commented on code/game/gamemodes/blob/blob.dm
> +			if(length(BLOB_RESTRICTED_JOBS) && (player.mind.assigned_role in BLOB_RESTRICTED_JOBS))
> Потому что это прок типа /datum/game_mode, а не /datum/game_mode/blob. Он может вызываться в разных режимах, в которых у него будет разное значение.

Можно тогда использовать `/datum/game_mode/blob::restricted_jobs`, вместо дефайна.

2024-07-01 13:01 UTC, dageavtobusnick commented on code/game/gamemodes/blob/blob.dm
> +			if(length(BLOB_RESTRICTED_JOBS) && (player.mind.assigned_role in BLOB_RESTRICTED_JOBS))
Поправил

2024-07-10 02:33 UTC, Gottfrei commented on code/__DEFINES/blob.dm
> +#define SECOND_STAGE_WARN span_userdanger("Вы чувствуете, что вот-вот лопнете</span>")
```suggestion
#define FIRST_STAGE_WARN span_userdanger("Вы чувствуете усталость и раздутость.")
#define SECOND_STAGE_WARN span_userdanger("Вы чувствуете, что вот-вот лопнете.")
```

2024-07-10 02:36 UTC, Gottfrei commented on code/datums/mind.dm
> +				if(!burst_time || current.stat == DEAD)
```suggestion
				var/burst_time = input(usr, "Введите время до вылупления","Time:", TIME_TO_BURST_ADDED_HIGHT) as num
				var/need_new_blob = alert(usr,"Нужно ли выбирать блоба из экипажа в случае попытки вылупления за пределами станции?", "", "Да", "Нет") == "Нет"
				var/start_process = alert(usr,"Начинать отсчет до момента вылупления?", "", "Да", "Нет") == "Да"
				if(isnull(burst_time) || current.stat == DEAD)
```
иначе не будет возможности отменить.

2024-07-10 02:37 UTC, Gottfrei commented on code/datums/mind.dm
> +				if(!burst_time || current.stat == DEAD)
также хорошей идеей будет проверить не удалён ли вообще моб, после всех этих слипов.

2024-07-10 15:44 UTC, dageavtobusnick commented on code/datums/mind.dm
> +				if(!burst_time || current.stat == DEAD)
> также хорошей идеей будет проверить не удалён ли вообще моб, после всех этих слипов.

Добавил проверки.

2024-07-12 07:42 UTC, Gottfrei commented on code/modules/mob/living/living_infected_blob_mobs.dm
> +  return !(dna.species.name in BLOB_RESTRICTED_SPECIES)
здесь похоже используются пробелы вместо табов у отступов.

2024-07-12 07:43 UTC, Gottfrei commented on code/modules/mob/living/living_infected_blob_mobs.dm
> +	var/dusted = FALSE
нужно перенести в leaving_defines и добавить комментарии для автодока.

2024-07-12 07:47 UTC, Gottfrei commented on code/modules/antagonists/blob/blob_infected_datum.dm
> +	var/player_message
автодок.

2024-07-12 07:52 UTC, Gottfrei commented on code/datums/mind.dm
> +				if(isnull(burst_time) || current.stat == DEAD || !current)
```suggestion
				if(isnull(burst_time) || QDELETED(current) || current.stat == DEAD)
```
иначе будет рантайм при проверке статуса у отсутствующего моба.

2024-07-12 07:56 UTC, Vladisvell commented on code/game/gamemodes/blob/blob.dm
> +	cores_to_spawn = max(round(num_players() / players_per_core, 1), 1)
Есть момент, что это будет учитывать количество игроков на гост-рольках. С другой стороны, до старта раунда попасть никто не может.

2024-07-12 08:03 UTC, Vladisvell commented on code/modules/mob/living/living_infected_blob_mobs.dm
> +  return !(dna.species.name in BLOB_RESTRICTED_SPECIES)
+

2024-07-12 08:04 UTC, Vladisvell requested changes
Удели внимание замечаниям от Zwei. А так выглядит круто, ждем на серверах

2024-07-12 08:23 UTC, dageavtobusnick commented on code/game/gamemodes/blob/blob.dm
> +	cores_to_spawn = max(round(num_players() / players_per_core, 1), 1)
Ну num_players() используется во многих режимах для определения количества игроков реди.

2024-07-12 15:53 UTC, dageavtobusnick commented on code/modules/mob/living/living_infected_blob_mobs.dm
> +	var/dusted = FALSE
Перенес и добавил

2024-07-12 15:54 UTC, dageavtobusnick commented on code/modules/antagonists/blob/blob_infected_datum.dm
> +	var/player_message
Добавил

2024-07-12 15:56 UTC, dageavtobusnick commented on code/game/gamemodes/blob/blob.dm
> +	cores_to_spawn = max(round(num_players() / players_per_core, 1), 1)
И вроде как проблем нету с этим в других режимах, ведь, как ты и сказал, попасть в мира до старта раунда могут разве что админы.

2024-07-12 15:56 UTC, dageavtobusnick commented on code/modules/mob/living/living_infected_blob_mobs.dm
> +  return !(dna.species.name in BLOB_RESTRICTED_SPECIES)
Исправил

2024-07-13 14:09 UTC, Vladisvell approved these changes

2024-07-14 04:38 UTC, Gottfrei approved these changes

2024-07-14 04:43 UTC, merged