add: Removed most of Object verbs for optimization
ss220-space/Paradise pull request #5325
Opened 2024-07-02 16:30 UTC by Vladisvell

## Описание

ПР убирает большинство verb'ов объектов для оптимизации клиентской стороны билда
## Ссылка на предложение/Причина создания ПР

Спам вербами залагивает клиент

2024-07-02 18:52 UTC, Gottfrei approved these changes, later dismissed

2024-07-03 09:40 UTC, BeebBeebBoob requested changes

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/game/machinery/OpTable.dm
> +/*NO MORE VERB SPAM SHIT UNTIL IT LAGS
Удали просто

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
> +	//verbs -= /mob/living/verb/pulled NO MORE VERB SPAM SHIT UNTIL IT LAGS
```suggestion
```

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/game/objects/items/devices/flashlight.dm
> +/*NO MORE VERB SPAM SHIT UNTIL IT LAGS
Удали просто

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
> +/* NO MORE VERB SPAM SHIT UNTIL IT LAGS
Удали просто

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/game/objects/structures/crates_lockers/crates.dm
> +/* NO MORE VERB SPAM SHIT UNTIL IT LAGS
Удали просто

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +/* NO MORE VERB SPAM SHIT UNTIL IT LAGS
Удали просто

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/game/objects/structures/window.dm
> +/* NO MORE VERB SPAM SHIT UNTIL IT LAGS
Удали просто

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/modules/mining/lavaland/loot/colossus_loot.dm
> +	//verbs -= /mob/living/verb/pulled NO MORE VERB SPAM SHIT UNTIL IT LAGS
```suggestion
```

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/modules/mining/lavaland/loot/colossus_loot.dm
> +		//holder_animal.verbs -= /mob/living/verb/pulled NO MORE VERB SPAM SHIT UNTIL IT LAGS
```suggestion
```

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/modules/mob/living/living.dm
> +//NO MORE VERB SPAM SHIT UNTIL IT LAGS (made it proc instead of verb)
```suggestion
```
Требования в этом комменте нету

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/modules/mob/living/living.dm
> +//prev definition /mob/living/verb/pulled(atom/movable/to_pull as mob|obj in oview(1))
```suggestion
```

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/modules/mob/living/living.dm
```suggestion
```

2024-07-03 09:40 UTC, BeebBeebBoob commented on code/modules/newscaster/obj/newscaster.dm
> +/* NO MORE VERB SPAM SHIT UNTIL IT LAGS
Удали просто

2024-07-03 15:43 UTC, merged