add: His Grace now opens his mouth when he is hungry.
ss220-space/Paradise pull request #5331
Opened 2024-07-04 02:55 UTC by Rafnik02

## Описание
 Теперь Его величество при голодание открывает ротик. 
1 стадия спрайт ванила
2 стадия спрайт ванила
3 стадия, до того как Ваша светлость схавает обладателя, анимация приоткрытым ртом.
4 стадия до смерти от поедания начальством, раба божьего, анимация с открытым ртом.

## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/755125334097133628/1258173982054678680

## Демонстрация изменений

2024-07-04 08:28 UTC, Daeberdir requested changes
Pepege, delay cherez `update_icon()` thanks.

2024-07-04 14:01 UTC, Rafnik02 commented
> Pepege, delay cherez `update_icon()` thanks.

Твой метод не работает, и спрайт не меняется

2024-07-04 14:24 UTC, Den109G commented on code/game/objects/items/weapons/storage/artistic_toolbox.dm
> +				progenitor.icon_state = "green3"
Вместо этого, обновляй иконку ящика как в остальном коде сделано.
Как-нибудь -
```
/obj/item/storage/toolbox/green/memetic/update_icon_state()
   icon_state = "green[hunger_message_level <= 2 ? "" : hunger_message_level - 1]"
```
```
/datum/disease/memetic_madness/stage_act()
      switch(progenitor.hunger)
			if(10 to 60)
				progenitor.hunger_message_level = 2
		    if(121 to 210)
				progenitor.hunger_message_level = 3
			....
			progenitor.update_icon(UPDATE_ICON_STATE)
```

2024-07-04 14:28 UTC, Den109G commented on code/game/objects/items/weapons/storage/artistic_toolbox.dm
> +				progenitor.icon_state = "green3"
Ну и да. Немного странно как по мне, что голодные сообщения идут отдельно от голодного спрайта.

2024-07-04 15:23 UTC, Rafnik02 commented on code/game/objects/items/weapons/storage/artistic_toolbox.dm
> +				progenitor.icon_state = "green3"
а это не то же самое, что я сделал?

2024-07-04 17:48 UTC, Den109G commented on code/game/objects/items/weapons/storage/artistic_toolbox.dm
> +				progenitor.icon_state = "green3"
> а это не то же самое, что я сделал?

Нет. Твой код не вызывает `update_icon(`, что вызывает свои сигналы для правильной работы других систем.

2024-07-10 02:29 UTC, Gottfrei submitted a review, later dismissed

2024-07-12 08:39 UTC, Daeberdir approved these changes
Вот теперь круто.

2024-07-14 07:36 UTC, Gottfrei approved these changes

2024-07-14 07:41 UTC, merged