Перевод названий и описаний оружия
ss220-space/Paradise pull request #543
Opened 2021-12-30 03:53 UTC by Ohar

## Changelog
:cl:
tweak: Переведены названия и описания шахтёрских КА, их модификаций, и ряда лазеров и тазеров
/:cl:

2022-03-10 05:30 UTC, Vallat approved these changes

2022-03-10 14:07 UTC, TrashDoxx commented on code/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	name = "Протокинетический акселератор"
```suggestion
	name = "Протокинетический акселератор"
```

2022-03-10 14:24 UTC, TrashDoxx requested changes

2022-03-10 14:24 UTC, TrashDoxx commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Модифицированная версия базового лазерного карабина. Стреляет менее концентрированными лучами и предназначено для тренировок."
```suggestion
	desc = "Модифицированная версия базового лазерного карабина. Стреляет менее концентрированными лучами и предназначена для тренировок."
```

2022-03-10 14:24 UTC, TrashDoxx commented on code/modules/projectiles/guns/energy/laser.dm
> +	name ="Ретро лазерный карабин"
```suggestion
	name ="Устаревший лазерный карабин"
```

2022-03-10 14:24 UTC, TrashDoxx commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Устаревшая модель базового лазерного карабин, больше не используемая охранными и военными силами NanoTrasen. Тем не менее, он всё же обладает приличной убойной силой, что, вместе с простотой
```suggestion
	desc = "Устаревшая модель базового лазерного карабина, больше не используемая охранными и военными силами NanoTrasen. Тем не менее, он всё же обладает приличной убойной силой, что, вместе с простотой обслуживания, делает эту модель любимым оружием пиратов и прочих преступников."
```

2022-03-10 14:24 UTC, TrashDoxx commented on code/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	desc = "Синдикатовская модификация, увеличивающая урон от выстрелов кинетического акселератора в средах с высоким давлением."
```suggestion
	desc = "Модификация, разработанная Синдикатом для увеличения урона от выстрелов кинетического акселератора в среде с высоким давлением."
```

2022-03-10 14:24 UTC, TrashDoxx commented on code/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	desc = "Синдикатовская модификация, увеличивающая урон от выстрелов кинетического акселератора в средах с высоким давлением."
```suggestion
	desc = "Модификация, разработанная Синдикатом для увеличения урона от выстрелов кинетического акселератора в среде с высоким давлением."
```

2022-03-10 14:24 UTC, TrashDoxx commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Небольшой энергопистолет со встроенным фонариком. У него два режима: оглушающий и летальный."
```suggestion
	name = "Миниатюрный энергетический пистолет"
	desc = "Небольшой энергетический пистолет со встроенным фонариком. У него два режима: оглушающий и летальный."
```

2022-03-10 14:24 UTC, TrashDoxx commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Это дорогая, современная версия антикварного лазерного пистолета. У этого оружия есть несколько уникальных режимов ведения огня, но нет возможности самостоятельно перезаряжаться с течением в
```suggestion
	name = "\improper Многофазный энергетический пистолет X-01"
	desc = "Это дорогая, современная версия старинного лазерного пистолета. У этого оружия есть несколько уникальных режимов ведения огня, но нет возможности самостоятельно перезаряжаться с течением времени."
```

2022-03-10 15:14 UTC, TrashDoxx approved these changes

2022-03-12 06:44 UTC, botPurple requested changes
Далеко не всё лазерное оружие переведено. будет вызывать осуждение и кринж, когда будет **You fire Лазерный карабин!** или **That's Лазерный карабин. It is a normal-sized item.** или **Флор Фомичёв fires Лазерный карабин!**

2022-03-12 06:44 UTC, botPurple commented on code/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	name = "Протокинетический ускоритель"
Требует обновления вики

2022-03-12 06:44 UTC, botPurple commented on code/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	name = "Кристалл кражи жизни"
"кражи" на "похищения"

2022-03-12 06:44 UTC, botPurple commented on code/modules/projectiles/guns/energy/laser.dm
> +	name = "Старинный лазерный пистолет"
Не понимаю чем тебе не понравилось слово "Антикварный". Перевод потерял смысл английской версии из-за этого

2023-07-27 17:22 UTC, closed without merging