Feat: New station goal "BFL"
ss220-space/Paradise pull request #550
Opened 2022-01-02 13:51 UTC by RenovatedAtol

## What Does This PR Do
Новая цель станции "BFL"
На лаваленде была замечена огромная расщелина с плазмой, цель: найти расщелину, построить установку для добычи плазмы из расщелины
Если спрайтеры изменят спрайт расщелины, то она будет заменена, пока что есть.
![image](https://user-images.githubusercontent.com/81752268/147877877-cfdcdf7c-e67b-4755-b246-9d8a3180bdf9.png)

Установка состоит из трёх частей: Emitter, Receiver, Lens
Emitter устанавливается на станции и выпускает огромный лазер в сторону ресивера
![image](https://user-images.githubusercontent.com/81752268/147877918-e21188a7-2510-4818-acdc-8e93aef33622.png)
Receiver устанавливается на самой расщелине (не забудьте линзу)
Линза устанавливается receiver. Будьте осторожны с линзой, она очень хрупкая.
![image](https://user-images.githubusercontent.com/81752268/147877715-b7370137-ecb8-4231-a590-558a76e3e6a6.png)

После успешной установки конструкции, из расщелины выкапывается одна плазменная руда раз в тик, собирать её придётся вручную из ресивера

При неправильной установке конструкции... Советую бежать с лаваленда
![image](https://user-images.githubusercontent.com/81752268/147877750-885f05f8-bb51-4d54-bb26-01a671542463.png)

Для выполнения цели, станции придётся заказать посылку "Mission goal" за 2500 очков карго и установить её содержимое в любом месте на станции

## Changelog
:cl:
add: New station goal "BFL"
/:cl:

2022-01-03 12:15 UTC, Vallat requested changes

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +	for(var/obj/structure/toilet/golden_toilet/B)
![image](https://user-images.githubusercontent.com/10997188/147927679-aaa4df5f-e73c-4265-b7ae-a5e1d47c21f2.png)

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +		return
```suggestion
	switch(response)
		if("deactivate")
			if(emag)
				visible_message("E.r$%^0r")
			else
				emitter_deactivate()
		if("activate")
			if(world.time - start_time > 30 SECONDS)
				emitter_activate()
				start_time = world.time
			else
				visible_message("Error, emitter is still cooling down")
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +	for(var/obj/machinery/bfl_receiver/T as anything in block(locate(1, 1, 3), locate(world.maxx, world.maxy, 3)))
```suggestion
	for(var/turf/T as anything in block(locate(1, 1, 3), locate(world.maxx, world.maxy, 3)))
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +		//better to be safe then sorry
```suggestion
		//better to be safe than sorry
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +/obj/machinery/bfl_emitter/New()
```suggestion
/obj/machinery/bfl_emitter/Initialize()
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +		return
```suggestion
	switch(response)
		if("deactivate")
			receiver_deactivate()
		if("activate")
			receiver_activate()
		if("empty ore storage")
			var/turf/location = get_step(src, SOUTH)
			internal.empty_storage(location)
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +			return
```suggestion
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +			ore_type = 0 //sosi bibu
```suggestion
	else if(istype(turf_under, /turf/simulated/floor/plating/asteroid/basalt/lava_land_surface))
		ore_type = 1 //sand
	else
		ore_type = 0 //sosi bibu
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +	var/state = FALSE
Объявление новых переменных лучше перенести вниз, после уже существующих

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +	var/ore_type = FALSE
Объявление новых переменных лучше перенести вниз, после уже существующих

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +	var/list/obj/structure/fillers = list()
Объявление новых переменных лучше перенести вниз, после уже существующих

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +/obj/machinery/bfl_lens/New()
```suggestion
/obj/machinery/bfl_lens/Initialize()
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +	. = ..()
Мув может вызваться но не совершиться, надо проверять
```suggestion
	. = ..()
	if(!.)
		return
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +	.=..()
```suggestion
	. = ..()
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +	.=..()
```suggestion
	. = ..()
```

2022-01-03 12:15 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +	.=..(loc, starting_energy, temp)
```suggestion
	. = ..(loc, starting_energy, temp)
```

2022-01-03 13:11 UTC, RenovatedAtol commented on code/modules/station_goals/bfl.dm
> +	var/list/obj/structure/fillers = list()
done

2022-01-03 13:11 UTC, RenovatedAtol commented on code/modules/station_goals/bfl.dm
> +	var/ore_type = FALSE
done

2022-01-05 06:53 UTC, Vallat requested changes

2022-01-05 06:53 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +			if(world.time - start_time > 30 SECONDS)
```suggestion
			if(world.time - deactivate_time > 30 SECONDS)
```

2022-01-05 06:53 UTC, Vallat commented on code/modules/station_goals/bfl.dm
> +	.=..()
```suggestion
/obj/machinery/bfl_receiver/Initialize()
	. = ..()
```

2022-01-05 15:21 UTC, RenovatedAtol commented on code/modules/station_goals/bfl.dm
> +	.=..()
Мне казалось я поменял все new() на intialize уже, видимо пропустил

2022-01-10 19:00 UTC, semoro commented
Правки

- Линза должна кластся на бок при anchored = 0
- Ресивер должен открываться/закрываться ломом
- Когда ресивер открыт в него можно упасть
- Забирать руду можно только из закрытого ресивера
- Ограничить количество руды 1000 штук
- Отображать количество руды фиолетовыми лампами (50 штук)
- Убрать красные лампы при закрытом ресивере

2022-01-14 17:46 UTC, semoro commented on code/modules/station_goals/bfl.dm
> +		if("connect to network")
Вызывай connect_to_network в activate и убери вообще эту кнопку

2022-01-14 18:23 UTC, semoro commented on code/modules/station_goals/bfl.dm
> +	name = "BFL Emitter"
Добавь что открывать/закрывать ломом в описание

2022-01-14 18:24 UTC, semoro commented on code/modules/station_goals/bfl.dm
> +	name = "BFL Receiver (Machine Board)"
Добавь в описание что машину нужно распологать по центру расщелины

2022-01-14 18:25 UTC, semoro commented on code/modules/station_goals/bfl.dm
> +	name = "BFL Emitter (Machine Board)"
Добавь в описание как надо располагать машину

2022-01-21 12:45 UTC, merged

2022-01-23 14:58 UTC, AttHawk commented
Очень режет глаз возможный спавн в сплошной породе, получается ровный квардрат с расщелиной в центре, ему бы сделать что-то неправльной формы, чтобы выглядело нерукотворно
![image](https://user-images.githubusercontent.com/85886313/150684609-f7aff0da-b23f-4b91-916d-382b00280357.png)