DNR Status and minor refactors
ss220-space/Paradise pull request #558
Opened 2022-01-08 05:37 UTC by BeebBeebBoob

## What Does This PR Do

Добавляет возможность на статус DNR и сокращает часть кода scanner(точнее код healthscan который выводит скан в чат и о боже код отвечающий за окошко для health analyzer и код сканнер к примеру для призрака были совсем разные а теперь оба одинаковые)

## Why It's Good For The Game

Теперь если человек прям умер и не хочет больше играть то он может поставить статус DNR. И рефактор.

## Images of changes

![image](https://user-images.githubusercontent.com/32985153/148632861-8a561b4e-696e-4a31-abdd-dae5a13ff1ef.png)
![image](https://user-images.githubusercontent.com/32985153/148632866-c76a4038-ab69-4273-ac46-2fdc533242b2.png)
![image](https://user-images.githubusercontent.com/32985153/148632868-efb2394b-58b7-4d21-9bfb-8ef87ec829a8.png)
(странный реагент не поможет!)
## Changelog
:cl:
add: DNR status
tweak: shorten healthscan proc that ghosts and pda scanner uses
/:cl:

2022-01-08 20:15 UTC, Vallat requested changes
Код посмотрел, комментарии оставил. Про грамматику промолчу, тут пусть ответственные за переводы смотрят, но она тоже хромает.

2022-01-08 20:15 UTC, Vallat commented on code/game/gamemodes/wizard/soulstone.dm
> +						get_cult_ghost(T, user, get_new_player = !T.ghost_can_reenter())
Именованный аргумент тут необязателен
```suggestion
						get_cult_ghost(T, user, !T.ghost_can_reenter())
```

2022-01-08 20:15 UTC, Vallat commented on code/game/objects/items/devices/scanners.dm
> +		scanner.window_height = 85
В чем смысл этого изменения, если де-факто ничего не меняется?

2022-01-08 20:15 UTC, Vallat commented on code/game/objects/items/devices/scanners.dm
> +		if(tdelta < DEFIB_TIME_LIMIT && !DNR)
DEFIB_TIME_LIMIT не изменялся, почему убрал умножение на 10?

2022-01-08 20:15 UTC, Vallat commented on code/modules/mob/dead/observer/observer.dm
> +	if(choice == "Да")
```suggestion
	if(alert(src, "Если вы включите это, ваше тело не смогут больше возродить до конца раунда.", "Вы уверены?", "Да", "Нет") == "Да")
```

2022-01-08 20:15 UTC, Vallat commented on code/modules/mob/mob_helpers.dm
> +	return TRUE
```suggestion
	return ghost?.can_reenter_corpse
```

2022-01-08 20:15 UTC, Vallat commented on code/game/objects/items/devices/scanners.dm
> +	//У нас просто в коде было две одинаковых WTF
Такой комментарий можно и не оставлять

2022-01-08 20:15 UTC, Vallat commented on code/game/data_huds.dm
> +			revivable = TRUE
```suggestion
		var/revivable = timeofdeath && (round(world.time - timeofdeath) < DEFIB_TIME_LIMIT)
		if(!ghost_can_reenter()) // DNR or AntagHUD
			revivable = FALSE
```

2022-01-08 20:57 UTC, BeebBeebBoob commented on code/game/objects/items/devices/scanners.dm
> +		if(tdelta < DEFIB_TIME_LIMIT && !DNR)
Потому что не сканнере все равно будет показывать что дефиб возможен хотя это не правда. Прочекни другие строки особенно тот который я заменил healthscan. Я ещё поверить не могу что никто баг про это не написал.

2022-01-08 21:01 UTC, BeebBeebBoob commented on code/game/objects/items/devices/scanners.dm
> +		scanner.window_height = 85
Забыл отменить. Когда тестил ПДА сканнер мне выдавало ошибку.

2022-01-08 21:24 UTC, BeebBeebBoob commented on code/game/objects/items/devices/scanners.dm
> +		if(tdelta < DEFIB_TIME_LIMIT && !DNR)
Мы дефиб можем сделать только до 5 минут а не 50 минут.

2022-01-14 05:37 UTC, Vallat commented on code/game/objects/items/devices/scanners.dm
> +			. += "Общий статус: <span class='danger'>МЕРТВ <b>\[DNR]</b></span>"
Здесь действительно будет выводиться "Общий статус: МЕРТВ **[1]**"? В чем смысл этой единицы?

2022-01-14 10:15 UTC, BeebBeebBoob commented on code/game/objects/items/devices/scanners.dm
> +			. += "Общий статус: <span class='danger'>МЕРТВ <b>\[DNR]</b></span>"
Обсудили в дискорде 👍 .

2022-01-14 11:26 UTC, Vallat approved these changes

2022-01-15 17:57 UTC, merged