Feat: new clown's toy "signmarer"
ss220-space/Paradise pull request #566
Opened 2022-01-11 14:52 UTC by RenovatedAtol

## What Does This PR Do
Sprite and idea by ElGood
Добавляет новую игрушку для клоуна. Signmarer

Гибрид лазерной указки и инструмента создающего голобарьеры.
Имеет все свойства указки (можно посветить в глаза человеку, роботу и в камеру), но в добавок можно создать голографическое мыло

При емаге указки создаётся мыло блокирующее путь, но оно всё также ломается от одного пинка.
## Images of changes
https://user-images.githubusercontent.com/81752268/148964438-9eee53f0-2917-49aa-b033-137780586189.mp4

## Changelog
:cl:
add: new clown toy "signmarer"
/:cl:

2022-01-12 06:25 UTC, dj-34 commented
Шо за "Signmarer" такое? Такого слова в английском не существует.
Мб Signmaker?

2022-01-12 06:38 UTC, Vallat requested changes

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +/obj/item/signmarer/proc/icon_flick()
Должны ли мы ждать выполнение этой функции? Если нет, поставь waitfor = FALSE

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +	var/attack_made = FALSE
Для чего служит эта переменная?

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +			if(prob(20))
Шанс на ослепление находится вне блока с проверкой на то, что ты целишься в глаза. Выходит, что ты можешь ослепить человека, посветив ему в ногу

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +			if(prob(20))
Здесь вообще нет проверки на то, куда человек светит лазером. Просто светишь в робота и слепишь его

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +			..()
Зачем вызов родителя **здесь**? Зачем он вообще нужен в функции процессинга? И самая функция построена лесенкой, переделай под читаемый вид

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +/obj/item/signmarer/proc/clear_holosign()
Добавить проверку на отсутствие sign, убрать эти проверки в местах, где функция вызывается

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +			qdel(found_holosoap)
Зачем вообще иметь возможность деактивировать **чужую** голограмму?

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +	sign = new holosign_type(get_turf(target), src)
Зачем здесь передается ссылка на текущий объект в качестве второго аргумента, если нет перегрузки конструктора под это?

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +	armor = list("melee" = 0, "bullet" = 50, "laser" = 50, "energy" = 50, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 20, "acid" = 20)
Зачем голограмме броня, особенно учитывая её хп в единичку?

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +			playsound(loc, 'sound/items/squeaktoy.ogg', 80, TRUE)
Эта функция проигрывает звук когда голограмму бьют или когда **ей** бьют?

2022-01-12 06:38 UTC, Vallat commented on code/game/objects/items/devices/signmarer.dm
> +	take_damage(5 , BRUTE, "melee", 1)
При получении урона голограмма удалится? Если да, то как об этом узнает объект, создавший эту голограмму?

2022-01-12 09:50 UTC, Vallat requested changes

2022-01-12 09:50 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +	icon_state = "signmarer_clown_on"
Между свойствами функции и самой функцией должен быть логический отступ
```suggestion
	set waitfor = FALSE
	
	icon_state = "signmarer_clown_on"
```

2022-01-12 09:50 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +		recharge_locked = 0
Новое добавление в процессинг происходит после каждой разрядки, а вот удаления из процессинга нет. Как так?
```suggestion
	var/recharge_chance = 20 - recharge_locked*5
	if(!prob(recharge_chance))
		return
	energy = min(max_energy, energy++)
	if(energy == max_energy)
		recharging = FALSE
		recharge_locked = FALSE
		return PROCESS_KILL
```

2022-01-12 09:50 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +	update_icon()
Из всего кода выше можно и **нужно** вынести вот это, так как во-первых это дублирующийся код, во-вторых при клике по обычному турфу у тебя не тратится ни энергия, ни фликает иконка
```suggestion
	energy = max(0, energy--)
	icon_flick()
	update_icon()
```

2022-01-12 09:50 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +			recharging = 1
```suggestion
			recharging = TRUE
```

2022-01-12 09:50 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +			recharge_locked = 1
```suggestion
			recharge_locked = TRUE
```

2022-01-12 09:50 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +			clear_holosign()
```suggestion
		if(found_holosoap == sign)
			to_chat(user, "<span class='notice'>You use [src] to deactivate [sign].</span>")
			clear_holosign()
```

2022-01-12 09:50 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +	playsound(src, 'sound/machines/click.ogg', 20, 1)
Вынести воспроизведение звука до проверки на `found_holosoap`

2022-01-12 09:50 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +	_projector.clear_holosign()
Произойдет повторный вызов qdel(), так делать нельзя. Просто отчищай ссылку на объект

2022-01-12 15:03 UTC, RenovatedAtol commented on code/game/objects/items/devices/signmarer.dm
> +	sign = new holosign_type(get_turf(target), src)
Раньше конструктор был перегружен для двух операторов, но потом я это удалил. А передачу второй переменной я не убрал.

2022-01-12 15:03 UTC, RenovatedAtol commented on code/game/objects/items/devices/signmarer.dm
> +	armor = list("melee" = 0, "bullet" = 50, "laser" = 50, "energy" = 50, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 20, "acid" = 20)
а ведь и правда. Наверно это было сделано у обычной голограммы для наследников.

2022-01-12 15:03 UTC, RenovatedAtol commented on code/game/objects/items/devices/signmarer.dm
> +			qdel(found_holosoap)
скорее сделано для удаления багнутой своей голограммы, чем чужой голоограммы

2022-01-12 15:03 UTC, RenovatedAtol commented on code/game/objects/items/devices/signmarer.dm
> +	var/attack_made = FALSE
чтоб не вызывать 2 раза laser_act()
При attack и afterattack

2022-01-12 15:03 UTC, RenovatedAtol commented on code/game/objects/items/devices/signmarer.dm
> +	take_damage(5 , BRUTE, "melee", 1)
Никак, но при создании новой голограммы, сломанная голограмма удалится

2022-01-12 15:03 UTC, RenovatedAtol commented on code/game/objects/items/devices/signmaker.dm
> +	playsound(src, 'sound/machines/click.ogg', 20, 1)
Так это ведь звук для создания новой голограммы, а не удаления старой

2022-01-12 15:03 UTC, RenovatedAtol commented on code/game/objects/items/devices/signmaker.dm
> +	update_icon()
Вообще при появлении голограммы иконка меняется на включенную, она фликать не должна

А ещё это так и задумано что энергия при голограмме не тратится, энергия тратится только когда в глаза светишь

2022-01-14 05:29 UTC, Vallat requested changes
Все те сообщения на английском, что ты писал сам, либо пиши на русском, либо переводи через переводчик. Пометь как "Resolved" комменты в предыдущих ревью. Подметил еще пару моментов, но в целом уже нормально

2022-01-14 05:29 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +//signmaker always on if hologram exists, always off if hologram doesn't exists
Лучше перепиши это на русский или воспользуйся переводчиком чтобы донести свою мысль на английском

2022-01-14 05:29 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +		return
Если проверять на viewers то возможно(?) срабатывание по камерам. В любом случае, лучше проверять то, над чем совершается действие, а не то, что совершает действие
```suggestion
	if( !(target in view(user)))
		return
```

2022-01-14 05:29 UTC, Vallat commented on code/game/objects/items/devices/signmaker.dm
> +	_projector.sign = null
```suggestion
	var/obj/item/signmaker/projector = null

/obj/structure/holosoap/Initialize(mapload, new_projector)
	. = ..()
	projector = new_projector

/obj/structure/holosoap/Destroy()
	projector.sign = null
```

2022-01-20 07:10 UTC, Vallat approved these changes

2022-01-20 15:08 UTC, merged