add: Borer ranks
ss220-space/Paradise pull request #5696
Opened 2024-08-10 18:03 UTC by Antoonij

## Описание
новый БОРЕР датум, новые ранги и эффекты от них

## Ссылка на предложение/Причина создания ПР
пока что пвоут с фулл описанием -  https://discord.com/channels/617003227182792704/618952559607939072/1271860491379281951

2024-08-20 13:31 UTC, Gottfrei commented on code/game/gamemodes/miniantags/borer/borer_datum.dm
> +/datum/borer_datum
у нас уже есть антаг датумы, зачем придумывать велосипед?

2024-08-20 14:33 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer_datum.dm
> +/datum/borer_datum
Сделаю

2024-08-20 16:30 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer_datum.dm
> +/datum/borer_datum
Сделал, но опять же антаг датум некрасиво будет выглядеть, ибо его основные функции завязаны на взаимодействии с майндом и от функций борер датума мы никак не избавимся, некоторые штуки же без майнда должны даваться

2024-08-20 17:27 UTC, Gottfrei commented on code/game/gamemodes/miniantags/borer/borer_datum.dm
> +/datum/borer_datum
ну так переноси всё это внутрь датума, а по дефолту червь ничего не будет уметь.

2024-08-20 17:29 UTC, Gottfrei commented on code/game/gamemodes/miniantags/borer/borer_datum.dm
> +
а вот ранги вполне могут быть своим отдельным датумом.

2024-08-20 17:32 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer_datum.dm
> +
Все эти фичи должны быть на одном, смысл нам делать отдельный процессинг для рангов

2024-08-20 18:25 UTC, Gottfrei commented on code/game/gamemodes/miniantags/borer/borer_datum.dm
> +
тебе нужно чтобы ранги заменяли друг друга, наслаивая свои фичи. и они уж точно НЕ являются отдельными антагонистами.

2024-08-20 18:26 UTC, Gottfrei commented on code/game/gamemodes/miniantags/borer/borer_datum.dm
> +
антагонист только один - борер, всё остальное навешиваешь через переменные. к примеру ты можешь сделать аналог сабкласса вампиров и работать с датумом так.

2024-08-21 20:30 UTC, Vladisvell commented
Раздели, пожалуйста, ПРы по смыслу и добавь соответствующих описаний. Это достаточно некомфортно ревьювить в условиях 10 предложек и отсутствующем описании.

2024-08-21 20:30 UTC, Vladisvell requested changes
Обратись к комментарию выше

2024-08-22 06:03 UTC, closed without merging