Локализация записок USSP
ss220-space/Paradise pull request #572
Opened 2022-01-12 21:38 UTC by dikers93

## What Does This PR Do
локализация

## Why It's Good For The Game
 более сильнее возможно влиться в атмосферу игры, лучшее понимание происходящего

2022-01-14 05:52 UTC, Vallat commented
> более сильнее возможно влиться в атмосферу игры, лучшее понимание происходящего

Прочитав это предложение я сразу засомневался в том, что человек, не сумевший грамотно оформить такую простую мысль, оформит качественный перевод. Прочитав пару этих самых переводов мои сомнения лишь подтвердились. Я не какой-то там лингвист или гуру русского с английским языков, но "тунгускай" (_а это обычная водка, можно было и догадаться, текст то про русских_), "​​без скафандра в открытый космос", "забыли о своем истинном наследии в пользу" и прочий абсолютно дословный перевод очень сильно бьет по глазам, а это я лишь две записки прочитал. 
Перевод плох. Просто забить в переводчик огромный текст и поменять пару слов обратно на английский это не перевод, это халтура на пять минут, которую лично мне даже демонстрировать было бы стыдно

2022-01-14 15:41 UTC, Ohar commented
Да, над текстом надо бы сильно поработать

2022-01-16 14:17 UTC, dikers93 commented
Вот так лучше? 
28 августа 25:32 Наш пост прослушивания передал несколько тревожных сообщений об активности TSF в секторе.  Хотя перехваченные сообщения говорят о том, что это просто исследовательская работа, я не могу отделаться от ощущения, что эти упрямые ублюдки наконец-то нас догнали.  Капитан уверяет меня, что волноваться не о чем, но мне трудно воспринимать всерьез человека, параноидально относящегося к двери душа с электроприводом.  Офицер связи Восток
"личный журнал";

"любовное письмо";

Моему дорогому Сергею, я никогда не забуду те ночи, которые мы провели на Лебеде, или все те времена, когда ты возил меня на своем 2452 Vincent.  То, как ты смотрел на меня той ночью, это была ночь, когда я понял, что у нас с тобой одна душа.  Я знаю, они заставили тебя продать своего Винсента, когда тебя переназначили, но я не мог допустить, чтобы такая прекрасная вещь ржавела.  Я сделал приготовления, и он здесь, ждет вас.  Я вложил ключи.  Пожалуйста, пусть они всегда служат напоминанием о нашей любви и поводом вернуться.  Я умоляю тебя, не позволяй нашей любви тихо уйти в ночь.
"Ключ Винсента под номером '52";

 Записка испачкана чернильными пятнами, сильный и дрожащий почерк, нацарапанный по ней, едва различим.  Восток перестал стучать в дверь час назад.  он должен искать что-то, чтобы попытаться заставить его.  Я до сих пор не знаю, что произошло, но уже прошло шесть часов.  Руки не перестают трястись, даже сигареты не помогают.  Восток, если тебе удастся войти и я потеряю сознание, мои лекарства в морозилке рядом с моим столом.  Пожалуйста.  Я рассчитываю на вас.";
 " Нарядная записка"

 "Этот проклятый душ станет моей смертью. Я вижу, как Восток смотрит на меня, когда я говорю об этом, как его глаза весело ухмыляются. Только сегодня утром, клянусь, эта чертова штука пыталась запереть  Мне пришлось сломать ручную разблокировку, чтобы выбраться, Восток чуть не обосрался, он так смеялся. Ну, посмотрим, сколько он будет смеяться, когда я напишу комиссару Григорию о его наглости; единственный  то, чем он будет офицером, это туалет!
"журнал капитана"

 Рекомендуемая партия Товарищ Бляцкий Подписавший офицер: Микаил Гогочев Капитан, я понимаю характер этой просьбы, которая кажется мне странной, но, пожалуйста, выслушайте меня.  Товарищ Бляцкий хоть и малюсенький бот, но как железный кулак самого комиссара Григора!  Он на днях выгнал из брига этого бесполезного ублюдка Тоттого, вы бы видели, как этот пьяница хныкал!  Как собака с поджатым хвостом.  В любом случае, я отвлекся!  Если кто и достоин признания, так это наш неусыпный и любимый Бляцкий, истинный поборник УССП.  Если вы желаете, быть может, воочию увидеть его бдительность и самоотверженность, что ж!  Вам нужно только прийти, чтобы осмотреть арсенал.  Товарищ Бляцкий ждет вашего решения.";
"рекомендация к похвале"

Я ЗНАЮ, ЭТО ТЫ УКРАЛ МОЕ СЧАСТЛИВОЕ БЕЛЬЕ.  Клянусь, если я увижу твою тощую крысиную шею, я буду выкручивать ее, пока ты не станешь синим!  НИКТО!  НИКТО НЕ ПРИКОСЕТСЯ К СЧАСТЛИВОМУ БЕЛЬЮ БОРИСА БЕЗ ПОСЛЕДСТВИЙ!
"СЛУШАЙ СЮДА СУКА"

 Это примечание было стерто всевозможными грубыми рисунками, которые слишком мерзки, чтобы дать им правильное описание.  Тотстой, я знаю, что это ты поишь моих кошек алкоголем, мне все равно, какие у тебя причины, но ты мешаешь важным исследованиям.  Это пятый кот, которого мне пришлось заменить в этом месяце из-за твоего грубого чувства юмора, и я поговорю с шефом Бораховым, если ты не прекратишь.  Николай Картов, заместитель научного сотрудника";
"Немедленно воздержаться!"

 21 августа - Превосходнейший комиссар Григорий 22 августа - Никто 23 августа - Никто 24 августа - Никто 25 августа - Зачем я вообще заморачиваюсь?  26 августа - Никто 27 августа -";
"журнал посетителей"

Мы, наконец, догадались, Катерина больше не будет смотреть мимо меня в пользу другой компании!  Эксперимент 432-А показывает невероятную скорость клеточной регенерации, и я утверждаю, что мы, наконец, преодолели великую границу между жизнью и смертью — настоящее биологическое бессмертие!  Конечно, агрессивное поведение — это нежелательный побочный эффект, но это всего лишь кошка.  Я уверен, что нескольких кошачьих лакомств с седативными добавками будет достаточно, чтобы подготовиться к вскрытию
"Эксперимент 432-А"

 Это уже пятый раз за этот месяц, когда мне пришлось заменить кабель к чертовой цепи блокировки.  Достаточно плохо, что конденсатор постоянно выходит из строя, и проклятым системам требуется почти неделя, чтобы включиться и перезагрузиться, но теперь у меня есть капитан, дышащий мне в затылок из-за его дурацкого душа и комиссара Григора.  Микаил рассказывал мне, что лицо мужчины так покраснело, когда вспыхнул свет, что можно было увидеть, как он светится в темноте.  Если бы он подумал, что это плохо, ну, если бы я не установил блокировку в столовой, мы бы неделю сидели в темноте.  Раствен говорит, что мы должны получить новую партию кабелей, хотя я не уверен, что у нас когда-нибудь будет достаточно запасов, чтобы обеспечить нормальное функционирование этого места.";
 название "отчет о техническом обслуживании"

 info «Отец Грегор, вы должны простить меня, но я не могу получить ваш заказ на одну из тех «перевертышей вуали», как вы просили. Я, по общему признанию, не уверен, что вы планировали с ней делать, дело духовенства  не мое, но Восток поспешил отменить ваш заказ после того, как мы потеряли последнюю партию.Мальчики все еще не оправились от головной боли с прошлого раза, а Хома жалуется, что видит синие огоньки всякий раз, когда закрывает глаза. Я  Не из тех, кто сомневается в человеке божьем, но умоляю вас, пожалуйста, не пытайтесь больше заказывать эти артефакты, они прокляты, и всякие демоны, кажется, следуют за ними по пятам Андрей Восточович, техник-снабженец
 имя "Мои извинения, отец"

 На правом поле бумаги нацарапано примитивное изображение плачущего яйца, на которое наступил сапог.  Вахвахва!  Настоящий яйцеголовый!  Мне плевать на твоих котов или на "сенс", если ты напишешь Шефу, я расскажу этой суке Катерине о твоем увлечении мальчиком.  Кроме того, почему вы подписываете имя на бумаге?  Я рядом, ублюдок, я знаю, что записка для мальчика твоя, как только я ее увижу.  Ты пишешь девчачье письмо, как будто я твой любовник, может, если бы ты меньше времени проводил в углу с кошкой, ты был бы настоящим мужчиной?  Конечно, ты все равно будешь выглядеть верблюжьим дерьмом, прилипшим к сапогу Тостого!
"дорогой малыш"

2022-01-16 14:26 UTC, dikers93 commented
> Да, над текстом надо бы сильно поработать

Вот так лучше?



28 августа 25:32 Наш пост прослушивания передал несколько тревожных сообщений об активности TSF в секторе. Хотя перехваченные сообщения говорят о том, что это просто исследовательская работа, я не могу отделаться от ощущения, что эти упрямые ублюдки наконец-то нас догнали. Капитан уверяет меня, что волноваться не о чем, но мне трудно воспринимать всерьез человека, параноидально относящегося к двери душа с электроприводом. Офицер связи Восток
"личный журнал";

"любовное письмо";

Моему дорогому Сергею, я никогда не забуду те ночи, которые мы провели на Лебеде, или все те времена, когда ты возил меня на своем 2452 Vincent. То, как ты смотрел на меня той ночью, это была ночь, когда я понял, что у нас с тобой одна душа. Я знаю, они заставили тебя продать своего Винсента, когда тебя переназначили, но я не мог допустить, чтобы такая прекрасная вещь ржавела. Я сделал приготовления, и он здесь, ждет вас. Я вложил ключи. Пожалуйста, пусть они всегда служат напоминанием о нашей любви и поводом вернуться. Я умоляю тебя, не позволяй нашей любви тихо уйти в ночь.
"Ключ Винсента под номером '52";

Записка испачкана чернильными пятнами, сильный и дрожащий почерк, нацарапанный по ней, едва различим. Восток перестал стучать в дверь час назад. он должен искать что-то, чтобы попытаться заставить его. Я до сих пор не знаю, что произошло, но уже прошло шесть часов. Руки не перестают трястись, даже сигареты не помогают. Восток, если тебе удастся войти и я потеряю сознание, мои лекарства в морозилке рядом с моим столом. Пожалуйста. Я рассчитываю на вас.";
" Нарядная записка"

"Этот проклятый душ станет моей смертью. Я вижу, как Восток смотрит на меня, когда я говорю об этом, как его глаза весело ухмыляются. Только сегодня утром, клянусь, эта чертова штука пыталась запереть Мне пришлось сломать ручную разблокировку, чтобы выбраться, Восток чуть не обосрался, он так смеялся. Ну, посмотрим, сколько он будет смеяться, когда я напишу комиссару Григорию о его наглости; единственный то, чем он будет офицером, это туалет!
"журнал капитана"

Рекомендуемая партия Товарищ Бляцкий Подписавший офицер: Микаил Гогочев Капитан, я понимаю характер этой просьбы, которая кажется мне странной, но, пожалуйста, выслушайте меня. Товарищ Бляцкий хоть и малюсенький бот, но как железный кулак самого комиссара Григора! Он на днях выгнал из брига этого бесполезного ублюдка Тоттого, вы бы видели, как этот пьяница хныкал! Как собака с поджатым хвостом. В любом случае, я отвлекся! Если кто и достоин признания, так это наш неусыпный и любимый Бляцкий, истинный поборник УССП. Если вы желаете, быть может, воочию увидеть его бдительность и самоотверженность, что ж! Вам нужно только прийти, чтобы осмотреть арсенал. Товарищ Бляцкий ждет вашего решения.";
"рекомендация к похвале"

Я ЗНАЮ, ЭТО ТЫ УКРАЛ МОЕ СЧАСТЛИВОЕ БЕЛЬЕ. Клянусь, если я увижу твою тощую крысиную шею, я буду выкручивать ее, пока ты не станешь синим! НИКТО! НИКТО НЕ ПРИКОСЕТСЯ К СЧАСТЛИВОМУ БЕЛЬЮ БОРИСА БЕЗ ПОСЛЕДСТВИЙ!
"СЛУШАЙ СЮДА СУКА"

Это примечание было стерто всевозможными грубыми рисунками, которые слишком мерзки, чтобы дать им правильное описание. Тотстой, я знаю, что это ты поишь моих кошек алкоголем, мне все равно, какие у тебя причины, но ты мешаешь важным исследованиям. Это пятый кот, которого мне пришлось заменить в этом месяце из-за твоего грубого чувства юмора, и я поговорю с шефом Бораховым, если ты не прекратишь. Николай Картов, заместитель научного сотрудника";
"Немедленно воздержаться!"

21 августа - Превосходнейший комиссар Григорий 22 августа - Никто 23 августа - Никто 24 августа - Никто 25 августа - Зачем я вообще заморачиваюсь? 26 августа - Никто 27 августа -";
"журнал посетителей"

Мы, наконец, догадались, Катерина больше не будет смотреть мимо меня в пользу другой компании! Эксперимент 432-А показывает невероятную скорость клеточной регенерации, и я утверждаю, что мы, наконец, преодолели великую границу между жизнью и смертью — настоящее биологическое бессмертие! Конечно, агрессивное поведение — это нежелательный побочный эффект, но это всего лишь кошка. Я уверен, что нескольких кошачьих лакомств с седативными добавками будет достаточно, чтобы подготовиться к вскрытию
"Эксперимент 432-А"

Это уже пятый раз за этот месяц, когда мне пришлось заменить кабель к чертовой цепи блокировки. Достаточно плохо, что конденсатор постоянно выходит из строя, и проклятым системам требуется почти неделя, чтобы включиться и перезагрузиться, но теперь у меня есть капитан, дышащий мне в затылок из-за его дурацкого душа и комиссара Григора. Микаил рассказывал мне, что лицо мужчины так покраснело, когда вспыхнул свет, что можно было увидеть, как он светится в темноте. Если бы он подумал, что это плохо, ну, если бы я не установил блокировку в столовой, мы бы неделю сидели в темноте. Раствен говорит, что мы должны получить новую партию кабелей, хотя я не уверен, что у нас когда-нибудь будет достаточно запасов, чтобы обеспечить нормальное функционирование этого места.";
название "отчет о техническом обслуживании"

info «Отец Грегор, вы должны простить меня, но я не могу получить ваш заказ на одну из тех «перевертышей вуали», как вы просили. Я, по общему признанию, не уверен, что вы планировали с ней делать, дело духовенства не мое, но Восток поспешил отменить ваш заказ после того, как мы потеряли последнюю партию.Мальчики все еще не оправились от головной боли с прошлого раза, а Хома жалуется, что видит синие огоньки всякий раз, когда закрывает глаза. Я Не из тех, кто сомневается в человеке божьем, но умоляю вас, пожалуйста, не пытайтесь больше заказывать эти артефакты, они прокляты, и всякие демоны, кажется, следуют за ними по пятам Андрей Восточович, техник-снабженец
имя "Мои извинения, отец"

На правом поле бумаги нацарапано примитивное изображение плачущего яйца, на которое наступил сапог. Вахвахва! Настоящий яйцеголовый! Мне плевать на твоих котов или на "сенс", если ты напишешь Шефу, я расскажу этой суке Катерине о твоем увлечении мальчиком. Кроме того, почему вы подписываете имя на бумаге? Я рядом, ублюдок, я знаю, что записка для мальчика твоя, как только я ее увижу. Ты пишешь девчачье письмо, как будто я твой любовник, может, если бы ты меньше времени проводил в углу с кошкой, ты был бы настоящим мужчиной? Конечно, ты все равно будешь выглядеть верблюжьим дерьмом, прилипшим к сапогу Тостого!
"дорогой малыш"

2022-01-17 11:05 UTC, Vallat requested changes
На исправление всего меня не хватило

2022-01-17 11:05 UTC, Vallat commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<i>Я никогда не забуду те ночи, которые мы провели на Cygni, и все те времена, когда ты возил меня на своем 2452 Винсенте. По тому, как ты посмотрел на меня той ночью, я поняла, что мы с тоб
```suggestion
	info = "<i>Я никогда не забуду те ночи, которые мы провели на Cygni, и все те времена, когда ты возил меня на своем 2452 Винсенте. По тому, как ты посмотрел на меня той ночью, я поняла, что мы с тобой родные души.<br><br>Я знаю, что они заставили тебя продать свой Винсент, когда тебя переназначили, но я не могла позволить что бы такая красивая вещь ржавела. Я договорилась, и он здесь, ждет тебя.<br><br>Ключи я приложила. Пожалуйста, пусть они всегда служат напоминанием о нашей любви и поводом вернуться. Я умоляю тебя, не позволяй нашей любви тихо уйти в ночь.</i>"
```

2022-01-17 11:05 UTC, Vallat commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<i>Записка испачкана чернильными пятнами, сильный и дрожащий почерк, нацарапанный по ней, едва различим.</i><br><br>Восток перестал стучать в дверь час назад, он должен попататься спасти нас
```suggestion
	info = "<i>Записка испачкана чернильными пятнами, сильный и дрожащий почерк, коим она нацарапана, едва различим.</i><br><br>Восток перестал долбить в дверь час назад, должно быть он пытается найти что-то, чем можно её открыть. Я до сих пор не знаю, что произошло, но я здесь торчу уже шесть часов.<br><br>Мои руки не перестают трястись, даже сигареты не помогают.<br><br>Восток, если тебе всё же удалось войти, а я лежу без сознания, лекарства находятся в морозилке рядом с моим столом. Пожалуйста. Я на тебя рассчитываю.";
```

2022-01-17 11:05 UTC, Vallat commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "Этот проклятый душ станет моей смертью. Я вижу, как Восток смотрит на меня, когда я говорю о нем, как его глаза весело ухмыляются. Только сегодня утром, клянусь, эта чертова штука пыталась з
```suggestion
	info = "Этот проклятый душ станет моей смертью. Я вижу, как Восток смотрит на меня, когда я говорю об этом, как его глаза весело ухмыляются. Только сегодня утром, клянусь, эта чертова штука попыталась запереть меня! Мне пришлось сломать замок, чтобы выбраться, а Восток чуть не обосрался со смеху, когда об этом узнал.<br><br>Ну, посмотрим, долго ли он будет смеяться, когда я напишу комиссару Григору о его дерзости; единственное, чем он тогда будет заниматься, это драить туалет!";
```

2022-01-17 11:05 UTC, Vallat commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<b>Рекомендованая команда</b> Товарищ Бляцкий<br><b>Подпись Офицера:</b>  Микаил Гогочев<hr><small>Капитан,<br><br>Я понимаю характер этой просьбы, которая мне кажется странной, но выслушайт
```suggestion
	info = "<b>Рекомендованный:</b> Товарищ Бляцкий<br><b>Подпись Офицера:</b>  Микаил Гогочев<hr><small>Капитан,<br><br>Я понимаю, что моя просьба может показаться странной, но выслушайте меня, пожалуйста: товарищ Бляцкий хоть и бот, но ведёт себя как железный кулак самого комиссара Григора! Буквально на днях он выгнал из брига этого бесполезного ублюдка Тоцтоя, вы бы видели, как этот пьяница хныкал! Как собака с поджатым хвостом.<br><br>В любом случае, я отвлекся! Если кто и достоин признания, так это наш неусыпный и любимый Бляцкий, истинный чемпион СССП.<br><br> Если вы желаете, быть может, воочию увидеть его бдительность и самоотверженность, что ж! Вам нужно только прийти и осмотреть арсенал. Товарищ Бляцкий ждет вашего решения.";
```

2022-01-17 11:05 UTC, Vallat commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<i>Эта заметка зарисовано всевозможными грубыми рисунками, которые слишком мерзки, чтобы дать им описание.</i><br><small>Тоцтой,<br><br>Я знаю, что это ты поишь моих кошек алкоголем, мне все
```suggestion
	info = "<i>Эта заметка зарисована всевозможными грубыми рисунками, которые слишком мерзки, чтобы дать им описание.</i><br><small>Тоцтой,<br><br>Я знаю, что это ты поишь моих кошек алкоголем, мне все равно, какие у тебя причины, но ты мешаешь важным исследованиям. Это пятый кот, которого мне пришлось заменить в этом месяце из-за твоего грубого чувства юмора, и я буду говорить с шефом Бораховым, если ты не прекратишь.<br><br>- <i>Николай Картов</i>, Лаборант";
```

2022-01-17 11:05 UTC, Vallat commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	name = "Моментальный отказ!"
```suggestion
	name = "Прекрати уже!"
```

2022-01-17 11:05 UTC, Vallat commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "Август 21 - Самый Превосходный Комиссар Григор<br>Август 22 - Никто<br>Август 23 - Никто<br>Август 24 - Никто<br>Август 25 - Почему я даже беспокоюсь?<br>Август 26 - Никто<br>Август 27 -";
```suggestion
	info = "Август 21 - Его Превосходительство Комиссар Григор<br>Август 22 - Никто<br>Август 23 - Никто<br>Август 24 - Никто<br>Август 25 - Чем я вообще занимаюсь?<br>Август 26 - Никто<br>Август 27 -";
```

2022-01-17 11:05 UTC, Vallat commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "Наконец-то мы наткнулись на это, Катерина больше не будет смотреть мимо меня в пользу другой компании! Эксперимент 432-A показывает невероятную скорость клеточной регенерации, и я утверждаю,
```suggestion
	info = "Наконец-то мы наткнулись на это, Катерина больше не будет смотреть мимо меня в пользу другой компании! Эксперимент 432-A показывает невероятную скорость клеточной регенерации, и я утверждаю, что мы, наконец, преодолели великую границу между жизнью и смертью — настоящее биологическое бессмертие!<br><br>Конечно, агрессивное поведение — неуместный побочный эффект, но в конце концов это всего лишь кошка. Я уверен, что нескольких кошачьих лакомств с седативными добавками будет достаточно, чтобы подготовиться к вскрытию .";
```

2022-01-17 11:05 UTC, Vallat commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "Это уже пятый раз за месяц, когда мне приходится заменять кабель к чертовой цепи блокировки. Это плохо, конденсатор постоянно выходит из строя, а чертовым системам требуется почти неделя для
```suggestion
	info = "Это уже пятый раз за месяц, когда мне приходится заменять кабель к чертовой цепи блокировки. Всё довольно плохо, конденсатор постоянно выходит из строя, а чертовым системам требуется почти неделя для цикла перезагрузки, так еще и капитан теперь дышит мне в спину из-за его дурацкого душа и комиссара Григора. Микаил говорил мне, что морда кэпа так покраснела, когда вспыхнул свет, что можно было увидеть, как он светится в темноте.<br><br>Если он думал, что это было ужасно, что ж,  если бы я не перегрузил системы в столовой, мы бы неделю сидели в темноте.<br><br>Раствэн говорит, что мы должны получить новую партию кабелей, хотя я не уверен, что у нас когда-нибудь будет достаточно припасов, чтобы это место функционировало должным образом.";
```

2022-01-17 14:32 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<b>Август 28, 2532</b><hr><small>Наш пост прослушивания передал несколько тревожных сообщений об активности TSF в секторе. Хотя перехваченные сообщения говорят о том, что это просто исследов
> об активности TSF

об активности ТСФ

2022-01-17 14:46 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<i>Я никогда не забуду те ночи, которые мы провели на Cygni, и все те времена, когда ты возил меня на своем 2452 Винсенте. По тому, как ты посмотрел на меня той ночью, я поняла, что мы с тоб
> мы провели на Cygni

мы провели на Лебеде

> они заставили тебя продать своего Винсента, когда тебя переназначили

при переводе тебя заставили продать Винсент

> но я не мог позволить что бы такая красивая вещь ржавела

но я не могла позволить такой красивой вещи ржаветь

> Я договорилася, и он здесь

Я позаботилась об этом, и теперь он тут

>тихо уйти в ночь

тихо угаснуть

2022-01-17 14:52 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<i>Записка испачкана чернильными пятнами, сильный и дрожащий почерк, нацарапанный по ней, едва различим.</i><br><br>Восток перестал стучать в дверь час назад, он должен попататься спасти нас
> испачкана чернильными пятнами, сильный и дрожащий почерк, нацарапанный по ней, едва различим

испачкана чернилами. Поверх неё сильной дрожащей рукой нацарапа едва различимая надпись

> должен попататься спасти нас

должен попытаться нас спасти

> Я до сих пор не знаю, что произошло, но уже прошло шесть часов

Я всё ещё не знаю, что произошло, хотя прошло шесть часов

> Мои руки не перестают трястись

У меня до сих пор трясутся руки

> если тебе удастся войти и я потеряю сознание

если ты сможешь войти, а я буду без сознания

2022-01-17 14:59 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "Этот проклятый душ станет моей смертью. Я вижу, как Восток смотрит на меня, когда я говорю о нем, как его глаза весело ухмыляются. Только сегодня утром, клянусь, эта чертова штука пыталась з
> Этот проклятый душ станет моей смертью

Этот сраный душ меня убьёт

> когда я говорю о нем, как его глаза весело ухмыляются

когда я говорю об этои. Он насмешливо ухмыляется

> чертова штука пыталась запереть меня.

чертова хреновина пыталась меня запереть!

> Восток чуть не обосрался от смеха, когда он это увидел и я ему расказал про это

а Восток чуть не обосрался со смеху!

> единственное, чем он тогда будет заниматься, это драить туалет!

туалет — единственное, за что после этого он будет отвечать!

2022-01-17 14:59 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	name = "капитанский журнал"
Бортовой журнал

2022-01-17 15:08 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<b>Рекомендованая команда</b> Товарищ Бляцкий<br><b>Подпись Офицера:</b>  Микаил Гогочев<hr><small>Капитан,<br><br>Я понимаю характер этой просьбы, которая мне кажется странной, но выслушайт
> Товарищ Бляцкий

Товарищ Блядски

> Микаил Гогочев

Михаил Гогочев

> товарищ Бляцки

Товарищ Блядски

> ублюдка Тоттого, вы бы видели, как этот пьяница хныкал! Как собака с поджатым хвостом.

ублюдка Толстого, вы бы слышали, как этот пьяница скулил, поджав хвост!

>неусыпный и любимый Бляцкий, истинный чемпион USSP

всегда бдительный любимый Блядски, истинный чемпион СССП

> Товарищ Бляцкий

Товарищ Блядски

2022-01-17 15:09 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	name = "рекомендации для похвалы"
Рекомендация поощрения

2022-01-17 15:14 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<i>Эта заметка зарисовано всевозможными грубыми рисунками, которые слишком мерзки, чтобы дать им описание.</i><br><small>Тоцтой,<br><br>Я знаю, что это ты поишь моих кошек алкоголем, мне все
> Тоцтой

Тотстой

> ты поишь моих кошек алкоголем

вы спаиваете моих кошек

>шефом Бораховым

шефом Борачовым

>Deputy Researcher

Младший научный сотрудник

2022-01-17 15:14 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	name = "Моментальный отказ!"
Немедленно прекратите!

2022-01-17 15:15 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "Август 21 - Самый Превосходный Комиссар Григор<br>Август 22 - Никто<br>Август 23 - Никто<br>Август 24 - Никто<br>Август 25 - Почему я даже беспокоюсь?<br>Август 26 - Никто<br>Август 27 -";
> Самый Превосходный

Великолепнейший

>Почему я даже беспокоюсь?

Почему мне не плевать?

2022-01-17 15:24 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "Это уже пятый раз за месяц, когда мне приходится заменять кабель к чертовой цепи блокировки. Это плохо, конденсатор постоянно выходит из строя, а чертовым системам требуется почти неделя для
> кабель к чертовой цепи блокировки

проводку системы блокировки

>постоянно выходит из строя

постоянно перегорает

> но теперь капитан дышит мне в спину из-за его дурацкого душаи комиссара Григора

а теперь ещё и капитан дышит мне в затылок со своим дурацким душем и комиссаром Григором

> Микаил

Михаил

> что лицо этого человека так покраснело, когда вспыхнул свет, что 

его рожа так покраснела, что, когда мигнул свет, 

> Если бы он думал это было плохо, ну, если бы я не установил блокировку

Он думает что всё плохо, но, если бы я не переставил провода

2022-01-17 15:26 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	name = "Мои извинения, отец"
Отце, примите мои извинения

2022-01-17 15:35 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<i>Примитивное изображение плачущего яйца, на которое наступил сапог, нацарапано на правом поле листа.</i><br><br>Вхахахахаха! Вахвахва! Настоящий яйцеголовый! Да насрать на твоих котов или
> или на 'syence'

или на «навуку»

>о твоем увлечении к твему маленькому парню

о том что ты втюрился как сопляк

>Кроме того, почему ты подписываешься на бумаге? Я рядом, ублюдок, я знаю, что записка твоя для твоего парня

Зачем ты вообще подписываешь записки? Я сижу за соседней дверью, уебан. Я знаю, что эти каракули твои сразу как только их увижу.

> был бы настоящим мужчиной

был бы настоящим мужиком

> сапогу Тоттого

сапогу Тотстого

2022-01-17 15:38 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "<i>Эта записка была перечеркнута столько раз, что трудно разобрать ее содержание.</i><br><small>Катерина,<br><br><s>Глаза твои как бриллианты,<br>Добыты с недр Cygni-A.<br>Мое сердце тоскует
> Добыты с недр Cygni-A

Добытые в недрах Лебедя Прайм

>Бля блять нет это плохо

Это пиздец как плохо

2022-01-17 15:54 UTC, Ohar requested changes
Отметил места, которые стоило бы поправить

2022-01-17 15:54 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	name = "любовная поэма"
Любовные стихи

2022-01-17 15:54 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "Блять, сука. Блять. Я знал, что эта миссия была ошибкой, что этот идиот Томас был убит каким-то разъяренным русским роботом-охранником в оружейной, а лейтенант вбежал на станцию, как идиот,
> стыковочный рычаг USSP

стыковочный шлюз СССП

>​​без него. В любом случае, без ригов выходить в открытый космос?

​​без скафандра

> выйти в откртый космос с горячим кофе и раслабиться

выпорхнуть в космос, попивая кофеёк

2022-01-17 15:54 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "Я беспокоюсь о Тотстой. Его уже пятый раз за эту неделю отправляют в вытрезвитель, и сколько бы я ни приходил к нему, он может найти Бога только на дне стакана Тунгуской.<br><brВсе это пьянс
> о Тотстой

о Тотстом

> стакана Тунгуской

стакана Тунгуски

> <brВсе это пьянство, я ненавижу плохо думать о USSP, но, не тратя денег на такие мелочи, разве мы не так же плохи, как TSF?

`<br>`Столько пьянства… Я ненавижу плохо думать о СССП, но, не заботясь об этом, разве мы оказываемся такими же плохими, как ТСФ?

> свое истинное наследие в пользу Galactic Common

свой родной язык и перешли на общегалактический

> Такая снисходительность, такая забывчивость. , это не может быть хорошо для духов, не говоря уже о душе

> Такая расхлябанность, такая забывчивость… Это плохо как для спирта, так и для души

2022-01-17 15:54 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	info = "Идиот ублюдок Тотстой нашел мою кнопку. Тупой пьяный пытался положить сдачу в автомат для бесплатных сигарет и уронил ее. Глядь, тупица решает поискать под автоматом свои драгоценные рубли.<
> Идиот ублюдок

Тупой мудак

>Тупой пьяный

Сраный алкаш

> сумела

удалось

2022-01-17 15:54 UTC, Ohar commented on _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
> +	name = "потертая бумага"
Скомканная бумажка

2022-03-20 11:09 UTC, Ohar approved these changes

2022-03-22 17:23 UTC, merged