Расовые диеты by FlattestGuitar
ss220-space/Paradise pull request #576
Opened 2022-01-15 15:08 UTC by Jordanstolethepreciousslam

Присваивает большинству блюд на станции одну из нескольких категорий
Meat - Мясо
Vegetables - Овощи
Raw - Необработанная пища
Junkfood - Фастфуд
Grain - Злаки
Fruit - Фрукты
Dairy - Молочные продукты
Fried -  Жареная пища
Alcohol - Алкоголь
Sugar - Сладости
Egg - Яйца
Toxic - Токсичные продукты
Gross - Мусор(сомнительная еда по типу жареных пауков, эктоплазмы и мяса ксеноморфов)

Поедание неправильного типа пищи будет приводить к тошноте и даже "замыливанию" зрения. Поедание любимой пищи отменяет этот эффект, так что блюда содержащие продукты разных типов всё еще могут потреблятся с минимальным риском.

Таяран - любят мясо, сырую пищу и молочные продукты. Не любят овощи, фрукты и злаки.
Вульпканин - любят мясо, сырую пищу, молочные продукты и мусор. Не любят фрукты, овощи и злаки.
Унати - Любят мясо. Не любят  фрукты, овощи и злаки.
Кидан- Любят алкоголь, сладкую пищу, фрукты и мусор. Не любят жареную пищу и молочные продукты
Воксы - любят мясо, фрукты и злаки. Не любят жареную пищу и молочные продукты
Скреллы - Любят фрукты и овощи. Ненавидят мясо.
Люди - Любят сладости и жареную пищу. Не имеют нелюбимой пищи.
Слаймолюди - любят мясо и токсичную пищу. Не любят жареное и сладкое.
Плазмолюди - любят мясо и злаки. Не любят молочные продукты, фрукты и овощи
Дионы - любят овощи и фрукты. Не любят мясо.
Серые - любят овощи, злаки и мясо. Не любят сладкое и жареное.
Драски - любят молочные продукты. Не любят сладкое.

2022-01-16 06:16 UTC, Vallat requested changes

2022-01-16 06:16 UTC, Vallat commented on code/modules/food_and_drinks/food.dm
> +	if(last_check_time + 50 < world.time)
Давайте начнем переходить на читаемые макросы для указания времени
```suggestion
	if(last_check_time + 5 SECONDS < world.time)
```

2022-01-16 06:16 UTC, Vallat commented on code/modules/mob/living/carbon/human/species/_species.dm
> +	var/a = "a"					 // the "a" or "an" in "a Vulpkanin" or "an Abductor", use with singular version
Может лучше `var/article`? А вообще в бьенде есть текстовый макрос `\a` для таких вещей, новая переменная не нужна

2022-01-20 09:51 UTC, Vallat approved these changes

2022-01-21 08:45 UTC, Jordanstolethepreciousslam commented
https://discord.com/channels/617003227182792704/755125334097133628/910821071899475988

Голосовач

2022-05-13 21:36 UTC, Zigamus commented on code/modules/food_and_drinks/food.dm
> +	if(last_check_time + 5 SECONDS < world.time)
![image](https://user-images.githubusercontent.com/59314481/168392685-43563154-c590-4578-a118-46f3b24c7e30.png)

2022-05-19 17:02 UTC, Bizzonium commented on code/modules/food_and_drinks/food.dm
> +	if(last_check_time + 5 SECONDS < world.time)
@Jordanstolethepreciousslam фиксы будут?

2022-05-19 22:58 UTC, Jordanstolethepreciousslam commented on code/modules/food_and_drinks/food.dm
> +	if(last_check_time + 5 SECONDS < world.time)
Фиксить что? Даже если это так и работает то по словам же автора 

> Eating disliked foods will lead to nausea and general unpleasantness. Eating liked foods cancels that

Вот и думай intended этот механ или нет. Да и не хочу я в чужой код лезть вообще

2022-05-29 16:17 UTC, merged