Feat: Решетка на балках
ss220-space/Paradise pull request #582
Opened 2022-01-19 12:48 UTC by Kirozet

## What Does This PR Do

Позволяет возможность ставить сетку из прутьев на балки в космосе.
## Why It's Good For The Game

## Images of changes

## Changelog
:cl:
add: Добавлена возможность собирать решетку из прутьев не только на полу, но и в космосе, но только на балках и дочерних структурах.
/:cl:

2022-01-19 12:50 UTC, Kirozet commented
в коммитах latice с одной буквой t, но в коде всё нормально. Я просто тапочек и уже утомился заполняя это коммиты

2022-01-20 04:04 UTC, Vallat requested changes

2022-01-20 04:04 UTC, Vallat commented on code/game/objects/items/stacks/stack.dm
> +				return FALSE
```suggestion
			if(!R.on_lattice)
				to_chat(usr, "<span class='warning'>\The [R.title] must be constructed on the floor!</span>")
				return FALSE
			if(!(locate(/obj/structure/lattice) in usr.drop_location()))
				to_chat(usr, "<span class='warning'>\The [R.title] must be constructed on the floor or lattice!</span>")
				return FALSE
```

2022-01-20 07:14 UTC, Kirozet commented on code/game/objects/items/stacks/stack.dm
> +				return FALSE
?? Будет выводиться `to_chat(usr, "<span class='warning'>\The [R.title] must be constructed on the floor or lattice!</span>")`  даже если в крафте не стоит `on_lattice = 1` и постройка на балках не подразумевается

2022-01-20 07:17 UTC, Vallat commented on code/game/objects/items/stacks/stack.dm
> +				return FALSE
Не будет, в этом случае оно завершится после первого условия `if(!R.on_lattice)` и выведет `to_chat(usr, "<span class='warning'>\The [R.title] must be constructed on the floor!</span>")`

2022-01-20 07:23 UTC, Kirozet commented on code/game/objects/items/stacks/stack.dm
> +				return FALSE
понял, но... смысл если результат один?

2022-01-20 07:29 UTC, Vallat commented on code/game/objects/items/stacks/stack.dm
> +				return FALSE
Избавление от ненужных проверок, более чистый и логически понятный код. Мы теперь сначала проверяем находимся ли мы на полу, если нет, проверяем можем ли мы строиться на прутьях, если можем, то проверяем уже наличие этих прутьев.

2022-01-20 07:42 UTC, Vallat approved these changes

2022-01-20 14:45 UTC, merged