Add: Обновления призового автомата дормиториев
ss220-space/Paradise pull request #5829
Opened 2024-08-30 17:18 UTC by pilygun

## Описание
Из призового автомата был удален мусор по типу фигурок, петрока и прочего
Снижена цена на завышенные по стоимости предметы.
Добавлены новые позиции
* Донк софт энфорсер
* Донк софт дробовик
* Космический байк

Переделан игрушечный арбалет. Донк софт арбалет вынесен в щитспавн.
Новый игрушечный арбалет оглушает на 0.1 секунду и очень похож на настоящий энерго арбалет. Но безвредный с увеличенным КД между выстрелов в 4 раза.

+ Вольный перевод с шутками актуальное для нашего комьюнити))))))
## Ссылка на предложение/Причина создания ПР
в процессе

## Демонстрация изменений
![image](https://github.com/user-attachments/assets/f030945b-25db-4d09-acc4-92529629fcaa)
![image](https://github.com/user-attachments/assets/6d1ebeea-31dd-4a17-935a-b735331c82cc)

2024-08-30 17:30 UTC, zuhariii commented on code/modules/arcade/prize_datums.dm
> +	desc = "Кто-нибудь хочет сыграть дурака на 52 карты?"
сыграть В дурака

2024-08-30 17:33 UTC, pilygun commented on code/modules/arcade/prize_datums.dm
> +	desc = "Кто-нибудь хочет сыграть дурака на 52 карты?"
Букаву забыл, щя пофиксим

2024-08-30 20:35 UTC, Den109G commented on code/modules/arcade/prize_datums.dm
> +	desc = "Я прикупил огромный байк...."
Вроде так больше правильно.
```suggestion
	desc = "Я прикупил огромный байк..."
```

2024-08-30 20:39 UTC, Den109G commented on code/modules/projectiles/projectile/energy.dm
> +	damage_type = TOX
Уверен, что не хочешь поменять тип урона на что-то более подходящее игрушке? В игре есть способы менять количества урона у пуль, и потому советую за этим следить.
```suggestion
	damage_type = STAMINA
```

2024-08-31 00:11 UTC, Den109G commented on code/modules/projectiles/projectile/energy.dm
> +	damage_type = TOX
Или вообще `nodamage = TRUE` прописать.

2024-08-31 13:47 UTC, Bizzonium commented on code/modules/arcade/prize_datums.dm
> +	desc = "Воздушный шарик для создание водяных бомбочек!."
Звучит не очень. Мб что-то типа "Воздушный шарик, наполненный водой, для бросков по людям."

2024-08-31 13:47 UTC, Bizzonium commented on code/modules/arcade/prize_datums.dm
> +	desc = "Выглядит как настоящая Сингулярность!"
Выглядит прям как Сингулярность!

2024-08-31 18:49 UTC, pilygun commented on code/modules/arcade/prize_datums.dm
> +	desc = "Воздушный шарик для создание водяных бомбочек!."
Ну изначально водой он не наполнен)

2024-09-04 18:22 UTC, pilygun commented
Воут пройден
https://discord.com/channels/617003227182792704/755125334097133628/1280955940685873225

2024-09-07 06:30 UTC, ROdenFL commented on code/modules/arcade/prize_datums.dm
> +	desc = "Наклейка которое сделает любую ID карту похожей на ID заключенного."
Звучит пиздато канешн. Запятую забыл и род не тот у местоимения.

2024-09-07 06:30 UTC, ROdenFL commented on code/modules/arcade/prize_datums.dm
> +	desc = "Наклейка которое сделает любую ID серебряной."
То же самое

2024-09-07 06:30 UTC, ROdenFL commented on code/modules/arcade/prize_datums.dm
>  	name = "Centcomm ID Sticker"
Ух

2024-09-07 06:30 UTC, ROdenFL commented on code/modules/arcade/prize_datums.dm
> +	desc = "Ты, наверно, думаешь, что тебе выпало .357 карат невезения?"
Карат?

2024-09-08 14:46 UTC, pilygun commented on code/modules/arcade/prize_datums.dm
> +	desc = "Ты, наверно, думаешь, что тебе выпало .357 карат невезения?"
![image](https://github.com/user-attachments/assets/2ec8b946-5d22-4d0d-8f00-0c34d0b09b5f)

2024-09-18 16:25 UTC, pilygun commented
вот би апрувы....

2024-09-21 14:45 UTC, Daeberdir requested changes

2024-09-21 14:45 UTC, Daeberdir commented on code/modules/arcade/prize_datums.dm
> +	desc = "Полноразмерна модель бензопилы, основанная на той Техасской космо-резне бензопилой.."
```suggestion
	desc = "Полноразмерная модель бензопилы, основанная на той самой Техасской космо-резне бензопилой."
```

2024-09-21 14:45 UTC, Daeberdir commented on code/modules/arcade/prize_datums.dm
> +	desc = "Помните: Герои не становятся ГРИФонами!"
```suggestion
	desc = "Помните: герои не становятся ГРИФонами!"
```

2024-09-21 14:48 UTC, Daeberdir approved these changes

2024-09-28 17:20 UTC, NightDawnFox approved these changes

2024-09-28 17:33 UTC, merged