Refactor: Eatable component & stacks are now eatable & species special diet.
ss220-space/Paradise pull request #5843
Opened 2024-09-01 17:39 UTC by Antoonij

## Описание
eat_items ЛИКВИДИРОВАН до уровня хелпер проков, все остальное перенесено в компонент.
Типы предметов, которые могут быть съедены - определяются в специальной диете.
Предметы-стаки кушаются нормально.
## Ссылка на предложение/Причина создания ПР
Это пупуфактор.

## Тесты
локалка

2024-09-02 11:25 UTC, ROdenFL requested changes
он знает что нужно исправить

2024-09-02 12:04 UTC, ROdenFL submitted a review, later dismissed
нужен тм

2024-09-02 17:01 UTC, Gottfrei commented on code/datums/components/eatable.dm
> +/datum/component/eatable
это должен быть элемент. компонент нужен, когда необходимо хранить стейты.

2024-09-02 17:07 UTC, Gottfrei commented on code/game/objects/items/devices/autopsy.dm
> +		. |= ATTACK_CHAIN_BLOCKED_ALL
ну и что здесь происходит? съел предмет, он удалился, и атака продолжается как не бывало

2024-09-02 17:10 UTC, Gottfrei commented
подводя итоги: тебе нужно удалить все эти невнятные отправки сигналов, где не нужно, создать элемент, вместо компонента, и слушать pre_attackby.

2024-09-02 17:25 UTC, Gottfrei commented on code/datums/components/eatable.dm
> +/datum/component/eatable
хотя нет, здесь наоборот нужно перенести "уровень покусанности", вместо переменной у предмета в переменную компонента. и смотреть на нёё при экзамине.

2024-09-02 20:19 UTC, Gottfrei commented
я там дописал тебе ранее. если мы храним стейты, а в нашем случае это количество укусов предмета, то нужно использовать как раз таки компонент.

2024-09-03 05:17 UTC, Antoonij commented
> я там дописал тебе ранее. если мы храним стейты, а в нашем случае это количество укусов предмета, то нужно использовать как раз таки компонент. элемент же не может хранить стейты.
> 
![1633928119867_big](https://github.com/user-attachments/assets/c9c10a38-15fe-437a-8956-a037f9d7a6c8)

> ну и как я уже сказал ранее, тебе здесь нужно работать с сигналом pre_attackby

Все сделал

2024-09-03 08:29 UTC, Gottfrei commented on code/datums/components/eatable.dm
> +	var/mob/living/carbon/human/human = user
с чего ты взял что это обязательно будет хуман?

2024-09-03 08:30 UTC, Gottfrei commented on code/datums/components/eatable.dm
> +		examine_list += "Вкуснятина! [item.is_only_grab_intent ? "\nНужно аккуратно есть." : ""]"
is_only_grab_intent должно быть переменной компонента и параметром при его инициализации.

2024-09-03 08:44 UTC, Antoonij commented on code/datums/components/eatable.dm
> +		examine_list += "Вкуснятина! [item.is_only_grab_intent ? "\nНужно аккуратно есть." : ""]"
Может сразу тогда все варки от предмета сдублировать в компонент и получить их при ините?

2024-09-03 09:43 UTC, Gottfrei commented on code/datums/components/eatable.dm
> +		examine_list += "Вкуснятина! [item.is_only_grab_intent ? "\nНужно аккуратно есть." : ""]"
именно так и нужно сделать.

2024-09-03 12:56 UTC, ROdenFL commented on code/datums/components/eatable.dm
> +	is_only_grab_intent = item.is_only_grab_intent
я думаю оно должно через аргументы в initialize идти...

2024-09-03 20:07 UTC, Gottfrei commented on code/datums/components/eatable.dm
> +	var/is_only_grab_intent //Grab if help_intent was used
автодок должен быть сверху и начинаться с трёх слэшей.

2024-09-03 20:09 UTC, Gottfrei commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
все эти переменные должны быть убраны.

2024-09-03 20:10 UTC, Gottfrei commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
единственное, что можно оставить - это material_type.

2024-09-03 20:25 UTC, ROdenFL commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
Ты хочешь превратить это в миллион кастомных добавлений компонентов?

2024-09-03 20:30 UTC, ROdenFL commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
Чет хуйня, имхо, нынешний вариант получше будет

2024-09-03 20:38 UTC, Gottfrei commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
не будет. компонент должен быть автономным.

2024-09-03 20:44 UTC, ROdenFL commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
Компонент то автономен, это просто более простой вариант записи этого компонента. Я понимаю чем тебе не нравился вариант, где он в New черпал данные из item.переменная, но тут всё относительно по-человечески

2024-09-03 20:45 UTC, ROdenFL commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
И в чем вообще тогда смысл переменной материал тайп если она только для диет

2024-09-03 20:47 UTC, Gottfrei commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
в том, что тип материала можно использовать и за пределами компонента, для других взаимодействий, в отличии от других переменных.

2024-09-03 20:48 UTC, Gottfrei commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
по-хорошему, можно сделать материалы битфлагами и добавлять их предметам.

2024-09-03 20:48 UTC, ROdenFL commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
Ну да, так много вариантов где можно использовать: мыльный, технологический и тканевый

2024-09-03 20:49 UTC, ROdenFL commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
На счёт флагов согласен, получше бы выглядело

2024-09-03 20:51 UTC, ROdenFL commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
Я не вижу смысла убирать переменные, тк не вижу адекватного способа оформления данной вещицы. Это только усложнит возможность сделать не съедобными дочерние предметы или изменить их свойства

2024-09-04 19:44 UTC, ROdenFL commented
Бля, а выглядит даже очень хорошо

2024-09-04 19:45 UTC, ROdenFL commented
Мог бы ты ещё это тестить, цены бы тебе не было

2024-09-04 19:46 UTC, Antoonij commented
В одно мгновение 250 строк превратились в 1400, :pizdec:

2024-09-04 19:48 UTC, ROdenFL approved these changes, later dismissed
Я ду нот мерге звея убирать не буду, но апрув оставлю, мне нынешний вариант очень заходит

2024-09-04 19:49 UTC, ROdenFL commented
> В одно мгновение 250 строк превратились в 1400, :pizdec:
Зато как красиво

2024-09-05 10:49 UTC, Gottfrei commented on code/game/objects/items.dm
> +	var/is_eatable = FALSE // If true - it will grant component/eatable in Initialize() and make item eatable.
нам не нужна эта перемнная.

2024-09-06 01:35 UTC, ROdenFL submitted a review, later dismissed

2024-09-06 17:03 UTC, Gottfrei commented on code/datums/components/eatable.dm
> +	if(!istype(target))
все проки работающие от сигналов должны начинаться с SIGNAL_HANDLER

2024-09-06 17:05 UTC, Gottfrei commented on code/datums/components/eatable.dm
> +	if(!istype(target))
ну и последнее в чём я не уверен, это стоит ли оставлять материалы как переменную предмета в том виде как это есть сейчас. технически это может быть полезно для других взаимодействий, но для этого нужно будет присваивать флаги материалы фактически всем предметам в игре. так что пожалуй лучше переместить данный аттрибут в инициализацию компонента.

2024-09-06 17:20 UTC, ROdenFL commented on code/datums/components/eatable.dm
> +	if(!istype(target))
ну вообще, так то мало смысла в надписи "это ткань" если рядом нету "вкуснятина"

2024-09-06 17:27 UTC, Antoonij commented on code/datums/components/eatable.dm
> +	if(!istype(target))
Это вынудит в будущем все это дело модифицировать, что бы нам без итебл компонента было получение типа материала в экзамайне. Взгляни на те моменты, где eatable компонент не выдается, а класс материала у них остается, а мы его в экзамайне не получим. Пиздец? Пиздец.

2024-09-07 13:39 UTC, ROdenFL commented
А есть вариант сделать переменную или вид материала, который бы позволил кому угодно съесть то, чему выдан компонент?

2024-09-07 13:41 UTC, ROdenFL commented
Для щитспавн или мап мемов подойдет

2024-09-07 14:14 UTC, ROdenFL commented
От дефайнов смысла нету поидее. FULL и ALL не имеют смысла пока у тебя существует пунктик с обязательностью существования диеты. Либо я неправильно помню код.

2024-09-07 14:15 UTC, Antoonij commented
FULL или ALL выдавай в спец диету хуманам и они смогут жрать все. Я не вижу смысла дополнительно чекать на эти дефайны

2024-09-07 14:31 UTC, ROdenFL commented
> FULL или ALL выдавай в спец диету хуманам и они смогут жрать все. Я не вижу смысла дополнительно чекать на эти дефайны

Да тут вероятно если делать то гораздо сложнее. Удали дефайны фулл и олл. То что у тебя материалы теперь битфлаги оставь - норм тема. Если захочется или приспичит сам подумаю как сделать. Пока идей хорошей реализации нету

2024-09-07 14:46 UTC, ROdenFL commented on code/datums/components/eatable.dm
> +		return FALSE
```suggestion
	if(!(material_type & target.dna.species.special_diet) && !(material_type & MATERIAL_CLASS_ALLEAT))
		return FALSE
```
вообще можно было бы сделать по глупому чтото типа такого. но это канешн смешное малясь

2024-09-07 15:19 UTC, ROdenFL approved these changes, later dismissed

2024-09-07 15:21 UTC, ROdenFL commented
Вообще, было бы прикольно сделать особое ингейм меню присвоения предметам компонентов с описанием каждого параметра. Было бы думаю забавно. Было бы достаточно удобна и забавно.

2024-09-07 16:47 UTC, Gottfrei commented on code/datums/components/eatable.dm
> +/datum/component/eatable/proc/pre_try_eat_item(datum/source, mob/living/carbon/human/target, mob/user)
твой прок ничего не возвращает, в случае успеха.

2024-09-07 19:02 UTC, ROdenFL commented on code/datums/components/eatable.dm
> +/datum/component/eatable/proc/pre_try_eat_item(datum/source, mob/living/carbon/human/target, mob/user)
ну, результат этого прока нигде и не используется

2024-09-07 19:46 UTC, ROdenFL commented
короче
как звей апрувнет ебни мне пингас, а то я уже трижды тут дисмиснут был :arolf:

2024-09-09 14:32 UTC, ROdenFL commented
@Gottfrei

2024-09-10 11:59 UTC, ROdenFL approved these changes, later dismissed

2024-09-11 12:10 UTC, merged