translation: brig cells and computer
ss220-space/Paradise pull request #5857
Opened 2024-09-04 15:23 UTC by syndicatecat

## Описание

Перевод камер заключённых в бриге, их оповещений, фраз и компьютера для управления ими.

## Ссылка на предложение/Причина создания ПР

Перевод

## Демонстрация изменений

![image](https://github.com/user-attachments/assets/3b2c3e33-2bfa-4f4c-9ec0-33995bd60d62)
![image](https://github.com/user-attachments/assets/020ffb59-f41c-4c6a-88fc-1671734c4e0f)

2024-09-06 01:47 UTC, ROdenFL reviewed
Я бы для русского отдельный хелпер сделал

2024-09-06 02:19 UTC, ROdenFL reviewed
А на кой переводить тех. переменные?

2024-09-06 02:30 UTC, zuhariii commented
41-46?

2024-09-06 02:32 UTC, zuhariii commented
Или 154?

2024-09-06 03:56 UTC, ROdenFL commented
Это
> 41-46?

2024-09-06 19:10 UTC, zuhariii commented
теперь точно всё

2024-09-06 19:12 UTC, zuhariii commented
> Я бы для русского отдельный хелпер сделал

сложно

2024-09-06 19:12 UTC, zuhariii commented
я так не умею

2024-09-06 19:13 UTC, zuhariii commented
точнее пытался, не получилось

2024-09-07 06:17 UTC, ROdenFL commented
Ты берёшь копипастишь прок который у тебя сейчас и называешь его название_прока_rus и возвращаешь старый прок под старым названием. И в своём первом используешь rus версию
> точнее пытался, не получилось

2024-09-07 12:38 UTC, zuhariii commented
> Ты берёшь копипастишь прок который у тебя сейчас и называешь его название_прока_rus и возвращаешь старый прок под старым названием. И в своём пре используешь rus версию
> 
> > точнее пытался, не получилось

я так делал и оно криво работало, по этому решил сделать так, как есть сейчас

2024-09-15 19:23 UTC, zuhariii commented
@Daeberdir

2024-09-15 19:23 UTC, zuhariii commented
Надо что-то делать

2024-09-15 19:23 UTC, zuhariii commented
Наверное

2024-09-15 19:23 UTC, zuhariii commented
Возможно

2024-09-18 16:12 UTC, zuhariii commented
ой

2024-09-29 22:06 UTC, Daeberdir reviewed
Если коротко, то перевод нужно допиливать. Сильно допиливать.

2024-09-30 14:35 UTC, Den109G requested changes
С переводом помогут локализаторы. А пока - ждём пока перевод пройдёт оповещения-переводов.

2024-11-13 15:03 UTC, pilygun reviewed
Исправь мерж конфликты и то что я написал. Ну и можно мержить :)

2024-11-13 15:03 UTC, pilygun commented on code/game/machinery/doors/brigdoors.dm
> +		P.info =  "<center><b>[id] - Запись Службы Безопасности</b></center><br><hr><br>"
Записи. Во множественном числе

2024-11-13 15:03 UTC, pilygun commented on code/game/machinery/doors/brigdoors.dm
> +						<small><b>Запись сгенерирована в:</b>		[station_time_timestamp()]<br>
Запись создана в

2024-11-13 15:03 UTC, pilygun commented on code/game/machinery/doors/brigdoors.dm
> +	Сотрудник: [usr.name].[R ? "" : " Отсутствует запись об заключённом, требуется обновление вручную."]"
"Отсутствуют записи"

2024-11-13 15:04 UTC, pilygun commented on code/game/machinery/doors/brigdoors.dm
> +						<small>Лог был создан автоматически, путём активации таймера камеры.</small>"}
Записи бы созданы

2024-11-21 19:23 UTC, zuhariii commented
> Исправь мерж конфликты и то что я написал. Ну и можно мержить :)

вроде что-то сделал, но чёт проверки не идут дальше и всё ещё requested changes, хотя они есть

2024-11-25 16:22 UTC, zuhariii commented
@pilygun

2024-11-27 14:36 UTC, pilygun approved these changes

2024-11-27 17:20 UTC, zuhariii commented
даже это не спасает от таблички changes requested

2024-12-03 07:07 UTC, syndicatecat reviewed
.

2024-12-03 16:04 UTC, closed without merging