fix: Запрет на постройку на клетках поля сдерживания
ss220-space/Paradise pull request #587
Opened 2022-01-20 23:05 UTC by Kirozet

## What Does This PR Do

https://github.com/ss220-space/Paradise/issues/581
Вводится запрет на постройку структур с помощью RCD на клетках поля сдерживания
## Why It's Good For The Game

## Images of changes

## Changelog
:cl:
add:
При попытке построить что-либо на клетке поля сдерживания будет выводиться сообщение о невозможности постройки.
Строить что-либо в полях сдерживания с помощью RCD, соответственно, теперь тоже нельзя.
fix: 
Введены проверки на наличие объектов поля сдерживания на клетках постройки.

/:cl:

<!-- You can use multiple of the same prefix (they're only used for the icon ingame) and delete the unneeded ones. Despite some of the tags, changelogs should generally represent how a player might be affected by the changes rather than a summary of the PR's contents. --
![unknown](https://user-images.githubusercontent.com/96671463/150436136-56121d45-1a80-4dc5-8474-4b28db67b36f.png)
>

2022-01-20 23:10 UTC, Bizzonium commented on code/game/objects/items/weapons/RCD.dm
> +
убери лишнюю строку

2022-01-20 23:14 UTC, Kirozet commented on code/game/objects/items/weapons/RCD.dm
> +
Она не лишняя, она отвечает за проверку на турф космоса или нахождения балок на турфе для постройки пола. В принципе можно убрать проверку на наличие балок, т.к. балки сами по себе могут находиться только на турфе космоса, но, в принципе, так было, так можно и оставить.. :PepeChill:

2022-01-20 23:16 UTC, Kirozet commented on code/game/objects/items/weapons/RCD.dm
> +
иначе рцд начнёт строить пол где угодно и даже вместо стенок(а для этого есть деконструкшн мод)

2022-01-21 03:28 UTC, Vallat commented on code/game/objects/items/weapons/RCD.dm
> +
Так тут имеется ввиду лишняя пустая строка после объявления функции, а не строка с проверкой

2022-01-21 03:34 UTC, Vallat requested changes

2022-01-21 03:34 UTC, Vallat commented on code/game/objects/items/weapons/RCD.dm
> +		if(locate(/obj/machinery/field) in AT )
Мы уже совершили проверку что это турф, смысла в получении турфа от турфа нет
```suggestion
		if(locate(/obj/machinery/field) in A)
```

2022-01-21 03:34 UTC, Vallat commented on code/game/objects/items/weapons/RCD.dm
>  				AT.ChangeTurf(/turf/simulated/wall)
Возвращаем то, что было и улучшаем читаемость
```suggestion
				var/turf/turf_to_change = A
				turf_to_change.ChangeTurf(/turf/simulated/wall)
```

2022-01-21 03:34 UTC, Vallat commented on code/game/objects/items/weapons/RCD.dm
> +		if(locate(/obj/machinery/field) in AT )
Тоже самое, мы и так уже знаем, что A это турф
```suggestion
		if(locate(/obj/machinery/field) in A)
```

2022-01-21 03:34 UTC, Vallat commented on code/game/objects/items/weapons/RCD.dm
> +		if(locate(/obj/machinery/field) in AT )
```suggestion
		if(locate(/obj/machinery/field) in A)
```

2022-01-21 03:34 UTC, Vallat commented on code/game/objects/items/weapons/RCD.dm
>  		AT.ChangeTurf(/turf/simulated/floor/plating) // Platings go under windows.
```suggestion
		var/turf/turf_to_change = A
		turf_to_change.ChangeTurf(/turf/simulated/floor/plating) // Platings go under windows.
```

2022-01-21 08:38 UTC, Kirozet commented on code/game/objects/items/weapons/RCD.dm
> +
351-
351+
же 
@Vallat

2022-01-21 16:43 UTC, Vallat approved these changes

2022-01-21 19:49 UTC, merged