WIP: ashwalkers ritual
ss220-space/Paradise pull request #5875
Opened 2024-09-08 11:01 UTC by Antoonij

## Описание
WIP, но датум ритуала, что привязывается к предметы и при тыке  по нему и удовлетворении условий - откроется меню ритуалов, а их самих пока что нет roflcat

## Ссылка на предложение/Причина создания ПР
WIP

## Тесты
никаких

2024-09-09 14:31 UTC, ROdenFL commented
тебе бы экзампл ритуала сделать, а то тяжко понимать

2024-09-11 05:51 UTC, ROdenFL commented
А  ты тестить всё так же не можешь?

2024-09-22 17:24 UTC, Vladisvell requested changes
Code review на связи, прошу обратить внимание на комментарии

2024-09-22 17:24 UTC, Vladisvell commented on code/datums/components/ritual_object.dm
> +/datum/component/ritual_object/proc/attackby(obj/obj, mob/user, params)
Концептуально здесь проводится же только атака предметом, думаю стоит поставить здесь obj/item/item, чем obj/obj

2024-09-22 17:24 UTC, Vladisvell commented on code/datums/components/ritual_object.dm
> +		return
Поставь по пустой строке после этих ретурнов для читаемости

2024-09-22 17:24 UTC, Vladisvell commented on code/datums/components/ritual_object.dm
> +/datum/component/ritual_object/proc/open_ritual_ui(obj/obj, mob/living/carbon/human/human)
Здесь аналогично комментарию выше, сделать заместо obj/obj obj/item/item для отображения что это предмет, а не объект

2024-09-22 17:24 UTC, Vladisvell commented on code/datums/components/ritual_object.dm
> +	var/tgui_menu = tgui_input_list(human, "выберите ритуал", "Ритуалы", rituals_list)
```suggestion
	var/tgui_menu = tgui_input_list(human, "Выберите ритуал", "Ритуалы", rituals_list)
```

2024-09-22 17:24 UTC, Vladisvell commented on code/datums/components/ritual_object.dm
> +	var/tgui_menu = tgui_input_list(human, "выберите ритуал", "Ритуалы", rituals_list)
Думаю tgui_menu стоит переименовать в chosen_ritual, чтобы отображать, что ты выбираешь не меню, а ритуал

2024-09-22 17:24 UTC, Vladisvell commented on code/datums/components/ritual_object.dm
> +	return rituals_list
После инструкций if-continue и LAZYADD поставь по пустой строке, чтобы улучшить читаемость кода

2024-09-22 17:24 UTC, Vladisvell commented on code/datums/status_effects/debuffs.dm
> +		return FALSE
Здесь тоже по пустой строке после ретурнов для читабельности

2024-09-22 17:24 UTC, Vladisvell commented on code/datums/status_effects/debuffs.dm
> +	return ..()
Сюда тоже пустую строку после `new_owner.damage_coeff[thing] *= modifier`

2024-09-22 17:24 UTC, Vladisvell commented on code/datums/status_effects/debuffs.dm
> +	return ..()
Аналогично, пустую строку после `new_owner.damage_coeff[thing] /= modifier`

2024-09-22 17:24 UTC, Vladisvell commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	icon_state = "ancient_goliath_tentacle"
Этого стейта не существует, или я его не нашёл, возможно забыл докинуть

2024-09-22 17:24 UTC, Vladisvell commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "cause kinetic crusher to deal 50% more damage if target has more than 90% HP"
```suggestion
	return "causes kinetic crusher to deal 50% more damage if target has more than 90% HP"
```

2024-09-22 17:24 UTC, Vladisvell commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		return
После ретурнов по пустой строке для читаемости

2024-09-22 17:24 UTC, Vladisvell commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "cause fauna to get 10% more damage after mark destroyed for 2 seconds"
```suggestion
	return "causes fauna to get 10% more damage after mark destroyed for 2 seconds"
```

2024-09-22 17:24 UTC, Vladisvell commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "cause fauna to deal 10% less damage when marked"
```suggestion
	return "causes fauna to deal 10% less damage when marked"
```

2024-09-22 17:24 UTC, Vladisvell commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		return
Пустые строки после return для читаемости кода

2024-09-22 17:24 UTC, Vladisvell commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		return
Здесь аналогично, пустую строку после ретурна для читаемости кода

2024-09-22 17:46 UTC, Vladisvell requested changes, later dismissed
Замечания по стилистике кода

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
После qdel надо удалять предмет из списка. Лучше заместо `for(var/thing as anything in used_things)` сделать `for(var/obj/item/thing in used_things)` с последующим qdel.

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return do_ritual(obj, invoker)
Пустые строки после ретурнов для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Пустые строки после этих двух первых ретурнов для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +		LAZYADD(invokers, human)
После continue поставить по пустой строке для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +				continue
По пустой строке после continue для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +				continue
После continue поставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +		to_chat(invoker, span_warning("только шаман может выполнить данный ритуал!"))
```suggestion
		to_chat(invoker, span_warning("Только шаман может выполнить данный ритуал!"))
```

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +			to_chat(invoker, "требуется [LAZYLEN(extra_shaman_invokers) - LAZYLEN(shaman_invokers)] шаман[(LAZYLEN(extra_shaman_invokers) - LAZYLEN(shaman_invokers)) > 1 ? "ов": ""] для начала ритуала.]")
```suggestion
			to_chat(invoker, "Требуется [LAZYLEN(extra_shaman_invokers) - LAZYLEN(shaman_invokers)] шаман[(LAZYLEN(extra_shaman_invokers) - LAZYLEN(shaman_invokers)) > 1 ? "ов": ""] для начала ритуала.]")
```

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +		living.gib()
Пустую строку после `living.gib()` для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +			return FALSE
После ретурнов поставь пустые строки для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
После return и LAZYADD добавь пустые строки

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	message_admins("[key_name(human)] accomplished mindtransfer ritual on [key_name(invoker)]")
После ретурнов по пустой строке для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +		new /obj/item/organ/internal/legion_tumour(invoker)
Пустую строку для читаемости после new

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +		return
Пустую строку для читаемости после return

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +		return FALSE
По пустой строке после ретурнов для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return RITUAL_SUCCESSFUL
После LAZYADD и двух ретурнов добавь по пустой строке для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +		return
Здесь пустую строку после return для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Здесь пустую строку для читаемости после human.gib()

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
После двух return FALSE поставь по пустой строке для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return RITUAL_SUCCESSFUL
Поставь пустую строку после return RITUAL_FAILED_ON_PROCEED для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +		return
После LAZYADD и return поставь по пустой строке для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщению выше, поставь пустую строку

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщению выше, поставь пустые строки после ретурнов

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Пустые строки после LAZYADD, return, human.force_gene_block(pick(GLOB.bad_blocks), TRUE) для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщению выше, поставь пустую строку

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщению выше, поставь пустые строки

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return RITUAL_SUCCESSFUL
Аналогично сообщению выше, поставь пустые строки после continue и disease.cure()

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщению выше, поставь пустые строки после continue и human.adjustBrainLoss(20)

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщению выше, поставь пустую строку

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщению выше, поставь пустые строки после return FALSE в обоих случаях

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return RITUAL_SUCCESSFUL
Аналогично сообщению выше, поставь пустые строки для отделения блоков if и for друг от друга

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +		return
Аналогично сообщению выше, поставь пустые строки после блока for и последнего if

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщению выше, поставь пустую строку

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +			to_chat(invoker, "существа должны быть мертвы.")
```suggestion
			to_chat(invoker, "Существа должны быть мертвы.")
```

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return RITUAL_SUCCESSFUL
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return RITUAL_SUCCESSFUL
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return RITUAL_SUCCESSFUL
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return TRUE
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +		return RITUAL_FAILED_ON_PROCEED // no mercy guys. But you got friendly creature
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-09-22 17:46 UTC, Vladisvell commented on code/datums/rituals.dm
> +	return
Аналогично сообщениям выше, после блоков if и for надо ставить пустую строку для читаемости

2024-10-05 17:33 UTC, Bizzonium commented
обновил

2024-10-10 13:20 UTC, pilygun commented
Вопрос дня, а где остальные спрайты?

2024-10-18 17:31 UTC, pilygun commented
ждем ДЕПЛОООООООООООЙ

2024-11-04 16:31 UTC, pilygun commented
ЧОООО ТЕСТ МЕРГЕ НИХУЯ СЕБЕ

2024-11-04 16:31 UTC, pilygun commented
А бля это не сурвивал
отмена радоваться ПРы перепутал

2024-11-04 17:26 UTC, Vladisvell approved these changes

2024-11-04 17:27 UTC, merged