Lavaland minor things
ss220-space/Paradise pull request #5893
Opened 2024-09-10 14:45 UTC by MeowEmiya

## Описание

Спрайты от @pilygun, часть кода спизжена у @NightDawnFox 

Потом

## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/755125334097133628/1196063680702451793

## Демонстрация изменений

Потом

2024-09-10 16:39 UTC, Daeberdir commented
Вот бы ещё коммиты адекватно называть 🐱 ☕

2024-09-16 12:56 UTC, NightDawnFox commented on code/game/objects/items/devices/scanners.dm
> +		to_chat(user, span_notice("Установить невозможно."))
Может лучше на балуун заменить?

2024-09-16 12:58 UTC, NightDawnFox commented on code/game/objects/items/tent.dm
> +/obj/structure/tent/verb/move_inside()
Вербы мы вроде больше не используем

2024-09-21 17:34 UTC, Den109G commented on code/modules/clothing/suits/armor.dm
> +	armor = list("melee" = 35, "bullet" = 10, "laser" = 25, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 80, "acid" = 60) //a fair alternative to bone armor, requiring alternative material
Используй дефайны для брони.
```suggestion
	armor = list(MELEE = 35, BULLET = 10, LASER = 25, ENERGY = 10, BOMB = 25, BIO = 0, RAD = 0, FIRE = 80, ACID = 60) //a fair alternative to bone armor, requiring alternative materials and gaining a suit slot
```

2024-09-27 12:22 UTC, MeowEmiya commented
Блять?

2024-09-27 12:28 UTC, Etrnlmelancholy commented
Ахуеть ватер кодит

2024-09-27 12:33 UTC, Explosi00N commented
*Вы получили внимание Эксплоужена*

2024-10-01 11:40 UTC, pilygun commented
Как же он сурвайвал апдейтит

2024-10-01 13:19 UTC, Den109G commented on code/modules/projectiles/guns/projectile/bow.dm
> +		if(LAZYLEN(nemesis_factions))
Лучше использовать дефайн и соединить проверки, чтобы избежать лестниц.
```suggestion
	if(ismob(H) && LAZYLEN(nemesis_factions))
```

2024-10-01 13:19 UTC, Den109G commented on code/game/objects/items/stacks/sheets/leather.dm
> +		var/obj/item/stack/sheet/hairlesshide/hide = new(drop_location(), amount + amount + amount)
Легче читать "Три раза количества", а не складывать это.
```suggestion
		var/obj/item/stack/sheet/hairlesshide/hide = new(drop_location(), 3 * amount)
```

2024-10-03 19:16 UTC, MeowEmiya commented
Мерж конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мержк конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мержк конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мержк конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мержк конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мержк конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мерж конфликт мержк конфликт мерж конфликт

2024-10-03 20:04 UTC, Den109G commented on code/game/objects/items/tent.dm
> +		usr.balloon_alert(usr, "The tent is already occupied!")
Баллун алёрты мы пишем с маленькой буквы.
```suggestion
		usr.balloon_alert(usr, "tent is occupied!")
```

2024-10-03 20:04 UTC, Den109G commented on code/game/objects/items/tent.dm
> +		user.balloon_alert(user, "The tent is already occupied!")
```suggestion
		user.balloon_alert(user, "tent is occupied!")
```

2024-10-03 20:04 UTC, Den109G commented on code/game/objects/items/tent.dm
> +		usr.balloon_alert(usr, "The tent is already occupied!")
```suggestion
		usr.balloon_alert(usr, "tent is occupied!")
```

2024-10-03 20:04 UTC, Den109G commented on code/game/objects/items/devices/scanners.dm
> +		user.balloon_alert(user, "Установить невозможно.")
И с маленькой буквы.
```suggestion
		user.balloon_alert(user, "установить невозможно.")
```

2024-10-03 20:04 UTC, Den109G commented on code/game/objects/items/tent.dm
> +		grabber.balloon_alert(grabber, "[src] is already occupied!")
С `[src]` это получается большой алёрт.
```suggestion
		grabber.balloon_alert(grabber, "tent is occupied!")
```

2024-10-04 20:29 UTC, MeowEmiya commented
![1](https://github.com/user-attachments/assets/774dcade-6b43-41e4-aebf-946bfc9c88c4)

2024-10-04 20:33 UTC, NightDawnFox commented on code/game/objects/items/tent.dm
> +		usr.balloon_alert(usr, "The tent is already occupied!")
и вообще мы баллууны пишем только на русском.

2024-10-05 04:20 UTC, NightDawnFox commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +		to_chat(M, "<span class='notice'>Ваша кожа покрывается кровавыми волдырями.</span>")
```suggestion
		to_chat(M, span_warning("Ваша кожа покрывается кровавыми волдырями."))
```

2024-10-05 04:21 UTC, NightDawnFox commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	visible_message("<span class='notice'>[src] finishes cooking!</span>")
```suggestion
	visible_message(span_notice("[src] finishes cooking!"))
```

2024-10-05 04:21 UTC, NightDawnFox commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	visible_message("<span class='notice'>[src] finishes cooking!</span>")
```suggestion
	visible_message(span_notice("[src] finishes cooking!"))
```

2024-10-05 04:22 UTC, NightDawnFox commented on code/modules/clothing/gloves/miscellaneous.dm
> +		target.visible_message("<span class='danger'>[user] smash [target] with weaver gloves!</span>")
```suggestion
		target.visible_message(span_danger("[user] smash [target] with weaver gloves!"))
```

2024-10-05 04:23 UTC, NightDawnFox commented on code/game/objects/items/tent.dm
> +		visible_message("[user] starts climbing into the tent.")
может спан какой-то, чтобы не было белого текста?

2024-10-05 16:56 UTC, NightDawnFox approved these changes, later dismissed
Мне всё нравится. Критических проблем не заметил

2024-10-07 17:59 UTC, NightDawnFox commented
Если что, я спросил у Азиза, твой ПР будет замерджен (или брошен в тестмердж) сразу после эши апдейта антония.
Еще недельку ПОТЕРПЕТЬ

2024-10-08 13:51 UTC, pilygun commented
Я такой человек который сначала терпит, терпит, терпит. А вотом как возьмет и снова терпит, терпит, терпит...

2024-10-08 18:33 UTC, MeowEmiya commented
Терпим терпим

2024-10-18 12:59 UTC, Antoonij commented on code/game/objects/items/devices/scanners.dm
> +		user.balloon_alert(user, "установить невозможно.")
Так ли много смысла в вызове этого балуналерта, если ничего не произошло? Также если не вернуть битфлаг, то произойдет CRASH.

2024-10-18 12:59 UTC, Antoonij commented on code/modules/projectiles/guns/projectile/bow.dm
> +				break
лесенку тут нужно убрать, сразу ретарни если не моб и нету немезис фракшенс. В форе континью, если фракция не в списке.

2024-10-18 12:59 UTC, Antoonij commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
> +		return
```suggestion
	if(primitive)
		return
		
```
пустые строки после ретарнов

2024-10-18 12:59 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +
```suggestion
	if(usr.default_can_use_topic(src) != UI_INTERACTIVE)
		return
		
	if(usr.incapacitated() || HAS_TRAIT(usr, TRAIT_HANDS_BLOCKED))
		return

```
Пустые строки после ретарнов

2024-10-18 12:59 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +		return
```suggestion
	if(!ishuman(usr) || usr.incapacitated() || HAS_TRAIT(usr, TRAIT_HANDS_BLOCKED) || usr.buckled)
		return
		
	if(occupant)
		usr.balloon_alert(usr, "палатка занята!")
		return
		
```
пустые строки после ретарнов

2024-10-18 12:59 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +		return
```suggestion
	if(occupant)
		user.balloon_alert(user, "палатка занята!")
		return
		
	if(!L)
		return
```
Пустая строка после ретарнов

2024-10-18 12:59 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +	INVOKE_ASYNC(src, PROC_REF(put_in), L, user)
```suggestion
	if(O.loc == user)
		return
		
	if(user.incapacitated() || HAS_TRAIT(user, TRAIT_HANDS_BLOCKED))
		return
		
	if(get_dist(user, src) > 1 || get_dist(user, O) > 1 || user.contents.Find(src))
		return
		
	if(!ismob(O))
		return
		
	if(isanimal(O) || issilicon(O))
		return
		
	if(!ishuman(user) && !isrobot(user))
		return
		
	if(!user.loc)
		return
		
	if(!istype(user.loc, /turf) || !istype(O.loc, /turf))
		return
		
	if(occupant)
		usr.balloon_alert(usr, "палатка занята!")
		return TRUE
		
	var/mob/living/L = O
	if(!istype(L) || L.buckled)
		return
		
	if(L == user)
		visible_message(span_notice("[user] starts climbing into the tent."))
	else
		visible_message(span_notice("[user] starts putting [L.name] into the tent."))
		
	. = TRUE
	INVOKE_ASYNC(src, PROC_REF(put_in), L, user)
```
пустые строки после ретарнов, истайп на силикона заменен на исхелпер, также отсутствие стоит проверять через !объект. Если бы он имел к примеру отрицательное число, то использовать isnull(объект)

2024-10-18 12:59 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +			return FALSE
пустая строка после ретарна

2024-10-18 12:59 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +	return TRUE
```suggestion
	. = FALSE
	if(!istype(the_folder))
		return
		
	if(LAZYLEN(contents))
		return
		
	return TRUE
```
Пустые строки после ретарнов, также стоит использовать LAZYLEN

2024-10-18 12:59 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +		return .
пустая строка после ретарна

2024-10-18 12:59 UTC, Antoonij commented on code/modules/mining/lavaland/ash_flora.dm
> +			return ATTACK_CHAIN_PROCEED
пустая строка после ретарна

2024-10-18 12:59 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +		return
Пустая строка после ретарна

2024-10-18 12:59 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +	return ..()
```suggestion
	for(var/mob/M in contents)
		M.forceMove(get_turf(src))
		REMOVE_TRAIT(M, TRAIT_ASHSTORM_IMMUNE, "ash")
		
	return ..()
```
Пустая строка после конструкции for

2024-10-18 13:13 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +	INVOKE_ASYNC(src, PROC_REF(put_in), L, user)
и далее пересмотри логику сам. Ты не пропускаешь силиконов моментом ранее, но потом проверяешь на робота..

2024-10-27 06:39 UTC, Antoonij commented on code/modules/clothing/gloves/miscellaneous.dm
> +	if(!(user.a_intent == INTENT_HARM) || !proximity || isturf(A))
```suggestion
	if(user.a_intent != INTENT_HARM || !proximity || isturf(A))
```
Лучше использовать !=

2024-10-27 06:39 UTC, Antoonij commented on code/modules/crafting/recipes.dm
> +	alert_admins_on_craft = TRUE
```suggestion
/datum/crafting_recipe/bonfire/coaltree
	name = "Bonfire (coaltree)"
	reqs = list(/obj/item/reagent_containers/food/snacks/grown/ash_flora/coaltree_log = 5)
```
Делай ООПшно,  а не плоди нужду в повторениях

2024-10-27 06:39 UTC, Antoonij commented on code/game/objects/items/devices/scanners.dm
> +	return ..()
```suggestion
	return ATTACK_CHAIN_BLOCKED_ALL
```
Сразу и ретарни без вызовов родителя. А то если в будущем придумают еще улучшения на сканер - они будут применимы

2024-11-04 16:34 UTC, pilygun commented
@Bizzonium Давай уже выводи из тест мержа эш апдейт и ставь в тест мерг этот ПР, ждем уже очь долго

2024-11-04 16:35 UTC, pilygun commented
бля мерж конфликт появился @MeowEmiya  чоп чоп

2024-11-09 22:41 UTC, LiquidPotroh commented on code/game/objects/items/weapons/weaponry.dm
> +/obj/item/primitive_kolotushka/afterattack(mob/living/target, mob/living/user, params, def_zone, skip_attack_anim = FALSE)
```suggestion
/obj/item/primitive_kolotushka/afterattack(atom/target, mob/user, proximity, params, status)
	if(!isliving(target) || !proximity || user.incapacitated() || HAS_TRAIT(user, TRAIT_HANDS_BLOCKED))
		return
```

2024-11-09 23:01 UTC, LiquidPotroh commented on code/game/objects/items/weapons/weaponry.dm
> +		target.apply_damage(stamina_damage, STAMINA)
```suggestion
		target.apply_damage(stamina_damage, STAMINA, blocked = getarmor(zone_selected, STAMINA))
```

2024-11-11 16:59 UTC, Vladisvell reviewed
![изображение](https://github.com/user-attachments/assets/d115077e-1e1b-4a51-95c8-bdbe655a83de)
sus

2024-12-18 18:57 UTC, Vladisvell requested changes
![изображение](https://github.com/user-attachments/assets/8e008df7-1584-4b53-a6b0-e02d2bd31b42)
metal-rod это ж заряд для арбалета самодельного, зачем ему спрайт стрелы?

2024-12-19 16:46 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +		deploy_tent(user, get_turf(src))
добро отсюда вынести в отдельный прок

2024-12-19 16:46 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +	if(!istype(occupant, /datum/species/unathi/draconid))
перейти на исхелпер

2024-12-19 16:46 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +	if(!do_after(grabber, 2 SECONDS, target) || !target || !grabber || grabber.pulling != target || !grabber.Adjacent(src))
```suggestion
	if(!do_after(grabber, 2 SECONDS, target) || !grabber.pulling != target)
```
Пулл проверять - есть толк, а вот за нас все остальное проверит дуафтер

2024-12-19 16:46 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +	var/mob/target = grabbed_thing
```suggestion
/obj/structure/tent/grab_attack(mob/living/grabber, mob/target)
	. = TRUE
	
	if(grabber.grab_state < GRAB_AGGRESSIVE || !istype(target))
		return .

```
оптимизируем это дело, язык нам позволяет менять параметры таким образом.

2024-12-23 16:35 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +	if(!isdraconid(occupant))
Нет, это так не делается. В будущем могут быть еще расы, у которых будет трейт. Нужно проверять это дело так:
if(HAS_TRAIT(моб, трейтэшшторм, UNIQUE_TRAIT_SOURCE(src))) - это надежнее. Также используй юник трейт сурс вместо "ash", ибо нигде более кроме палатки это не используется.
И пройдись по всем местам, где снимаешь трейт и вставь такой чек.

2024-12-23 16:39 UTC, Antoonij commented on code/game/objects/items/tent.dm
> +	return attack_hand(user)
зачем палатке вообще реагировать на атаку ии, так еще и вызываем тут атаку рукой?

2024-12-29 22:35 UTC, BeebBeebBoob commented on code/game/objects/items/tent.dm
> +/obj/structure/tent/verb/move_inside()
Не используем, меняем на `/CtrlClick()` или `/AltClick()`

2024-12-29 22:35 UTC, BeebBeebBoob commented on code/game/objects/items/tent.dm
> +/obj/structure/tent/verb/eject()
Верб меняем

2024-12-29 22:37 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/weaponry.dm
> +/obj/item/kolotushka
Боже, русское прописанное на английском. Если будет возможность, то стоит заменить на адекватное. Дубина из кости? пусть `/obj/item/bone_club`

2024-12-29 22:44 UTC, BeebBeebBoob commented
Долго тестмержиться, даём свободу другим ПРам, есть вещи и детали которые надо доделать

2025-01-16 13:58 UTC, MeowEmiya commented
Я кончил

2025-01-16 15:42 UTC, PlayerUnknown14 commented
Мёрж запрещаю, пока не отсмотрю локализацию.

2025-01-22 09:21 UTC, PlayerUnknown14 requested changes
1) Все `obj` должны иметь `name` на английском, описание на русском и прописанные `ru_names`.
2) Кодстайл: `name`, ниже `desc`, ниже `ru_names`.
3) Все `to_chat` и подобные сообщения для игрока должны быть на русском. Названия `obj` в них должны быть прописаны не через `name` или `src`, а через прок `declent_ru`.

2025-01-22 14:54 UTC, NightDawnFox commented
Оно никогда не уйдет в релиз

2025-01-23 08:11 UTC, BeebBeebBoob commented
Я думал умер пр

2025-01-31 09:31 UTC, MeowEmiya commented
Да не умер он в конце мерж конфликта!!!!!

2025-02-02 10:07 UTC, BeebBeebBoob requested changes

2025-02-02 10:07 UTC, BeebBeebBoob commented on code/game/objects/items/devices/scanners.dm
> +	icon_state = "Gem_analyzer"
```suggestion
	icon_state = "gem_analyzer"
```
Да, даже один символ.

2025-02-02 10:07 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/weaponry.dm
> +/obj/item/nutcracker
```suggestion
/obj/item/melee/nutcracker
```
Можно считать как оружие
Меняя, надо и иконки оружия переместить в другой файл-спрайт `melee_lefthand.dmi` из `item_lefthand.dmi`

2025-02-04 04:31 UTC, PlayerUnknown14 requested changes

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/game/objects/items/devices/scanners.dm
> +	desc = "Необычный самоцвет в форме сердца."
```suggestion
	desc = "Необычный самоцвет в форме сердца. Позволяет пользователю ощущать раны и болезни других существу на метафизическом уровне. Магия, не иначе."
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/weaponry.dm
> +	desc = "Простейшая дубина из кости, воплощает в себе силу природы и первобытную мощь."
```suggestion
	desc = "Простейшая дубина из кости. Воплощение силы первобытного разума и природной мощи. Настоящая классика."
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/weaponry.dm
> +		PREPOSITIONAL = "колотушке"
"костяная дубина"

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/weaponry.dm
> +	icon_state = "nutcracker"
```suggestion
	)
	gender = FEMALE
	icon_state = "nutcracker"
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/game/objects/structures/watercloset.dm
> +		to_chat(l_target, span_warning("You've been drenched in water!"))
```suggestion
		to_chat(l_target, span_warning("Вы насквозь промокли!"))
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/clothing/gloves/miscellaneous.dm
> +	desc = "Серые перчатки без кончиков пальцев, сделанные из шкуры мертвого паукообразного, найденного на Лаваленде. Улучшает способности владельца к обезоруживанию."
```suggestion
	desc = "Серые беспалые перчатки, сделанные из шкуры мёртвого паукообразного, найденного на Лаваленде. Лёгкие и удобные, они позволяют владельцу драться эффективнее в рукопашном бою."
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/clothing/gloves/miscellaneous.dm
> +		target.visible_message(span_danger("[user] сокрушает [target] [declent_ru(INSTRUMENTAL)]!"))
```suggestion
		target.visible_message(span_danger("[user] сокруша[pluralize(user.gender, "ет", "ют")] [target] [declent_ru(INSTRUMENTAL)]!"))
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	desc = "Кусок мяса"
```suggestion
	desc = "Кусок сырого мяса. Большинство гуманоидов не стало бы есть его в сыром виде."
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +		PREPOSITIONAL = "мясе"
"кусок мяса"

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +		to_chat(user, span_warning("Вы не можете порезать [declent_ru(NOMINATIVE)] [ismob(loc) ? "в инвентаре" : "в [loc]"]."))
```suggestion
		to_chat(user, span_warning("Вы не можете порезать [declent_ru(ACCUSATIVE)] [ismob(loc) ? "в инвентаре" : "в [loc.declent_ru(PREPOSITIONAL)]"]."))
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +		to_chat(user, span_warning("Вы не можете порезать [declent_ru(NOMINATIVE)] тут! Вам нужен стол или хотя-бы поднос, чтобы сделать это."))
```suggestion
		to_chat(user, span_warning("Вы не можете порезать [declent_ru(ACCUSATIVE)] тут, поверхность слишком неудобная!"))
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +			span_notice("[user] режет мясо тонкими полосками."),
pluralize_ru

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +			span_notice("Вы порезали мясо тонкими полосками."),
```suggestion
			span_notice("Вы режете мясо тонкими полосками."),
```
Время только настоящее.

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	desc = "Хорошо прожаренный стейк."
```suggestion
	desc = "Хорошо прожаренный стейк. Отличный источник белков и жиров."
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	desc = "Все еще дергающаяся лапка гигантского паука. Ты ведь не будешь это жрать, правда?"
```suggestion
	desc = "Всё ещё дёргающаяся лапка гигантского паука. Вы ведь не будете это есть, правда?"
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	)
```suggestion
	)
	gender = FEMALE
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	visible_message(span_notice("[declent_ru(NOMINATIVE)] приготовилась!"))
```suggestion
	visible_message(span_notice("[capitalize(declent_ru(NOMINATIVE))] приготовилась!"))
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	visible_message(span_notice("[src] finishes cooking!"))
Перевести аналогично выше.

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	)
гендер

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
> +	desc = "Самодельная сушилка, используется для сушки кожи и еды."
```suggestion
	desc = "Примитивная самодельная сушилка, предназначенная для просушки растительных продуктов, еды и кожи."
```
Выше описание у обычной сушилки двоится, удали строчку и пропиши там же гендер.

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/mining/lavaland/ash_flora.dm
> +	desc = "Небольшое мрачное дерево, растущее на просторах такой же мрачной планеты."
ру неймы, гендер.

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/mining/lavaland/ash_flora.dm
> +			to_chat(user, span_warning("You cannot chop [src] [ismob(loc) ? "in inventory" : "in [loc]"]."))
Перевести.

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/mining/lavaland/ash_flora.dm
> +		PREPOSITIONAL = "семенах угледрева"
"пачка семян угледрева", гендер

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/projectile/bow.dm
> +	desc = "Примитивный лук с тетивой сделанной из жилы. Обычно используется племенными охотниками и воинами. Из-за специфической конструкции лука, можно стрелять только костяными стрелами."
```suggestion
	desc = "Примитивный лук с тетивой, сделанной из жилы. Обычно используется племенными охотниками и воинами. Из-за специфической конструкции лука из него можно стрелять только костяными стрелами."
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/projectile/bow.dm
> +	desc = "Резать, резать, резать!"
Что-то другое придумай.

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/projectile/bow.dm
> +	)
гендер

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	description = "Экстракт полученный из угледрева, выводит из организма токсины ценой больших мучений."
```suggestion
	description = "Экстракт, полученный из угледрева. Выводит из организма вредные токсины, но имеет ряд побочных эффектов."
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	taste_description = "ash"
```suggestion
	taste_description = "пепла"
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +	name = "Coaltree extract"
```suggestion
	name = "Экстракт Угледрева"
```

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/surgery/tools.dm
> +	desc = "Расшираяет штуки."
Бери за основу описание стандартных инструментов и допиши что-то про самодельность, примитивность и материалы.
Аналогично инструменты ниже.

2025-02-04 04:31 UTC, PlayerUnknown14 commented on code/modules/surgery/tools.dm
> +	)
гендер

2025-02-05 17:46 UTC, MeowEmiya commented
Уооооох блять

2025-02-08 11:30 UTC, BeebBeebBoob commented
переводы доделать

2025-02-12 10:57 UTC, PlayerUnknown14 requested changes

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/game/objects/items/devices/scanners.dm
> +	desc = "Необычный самоцвет в форме сердца. Позволяет пользователю ощущать раны и болезни других существу на метафизическом уровне. Магия, не иначе."
```suggestion
	desc = "Необычный самоцвет в форме сердца. Позволяет пользователю ощущать раны и болезни других существ на метафизическом уровне. Магия, не иначе."
```

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +			span_notice("[user] реж[pluralize_ru(user.gender,"ет","ут")] мясо тонкими полосками."),
```suggestion
			span_notice("[user] реж[pluralize_ru(user.gender, "ет", "ут")] мясо тонкими полосками."),
```
Кодстайл, ниже аналогично.

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	visible_message(span_notice("[declent_ru(NOMINATIVE)] приготовилось!"))
```suggestion
	visible_message(span_notice("[capitalize(declent_ru(NOMINATIVE))] приготовился!"))
```

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	tastes = list("паутины" = 1, "жутких движений" = 1)
```suggestion
	tastes = list("паутины" = 1, "слабых подёргиваний во рту" = 1)
```

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	visible_message(span_notice("[src] finishes cooking!"))
.

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	desc = "Кусок мяса голиафа. Сейчас не очень съедобно, но в лаве оно готовится отлично."
```suggestion
	desc = "Восхитительный стейк из мяса голиафа, прожаренный прямо в лаве. Так первобытно."

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +	tastes = list("мяса" = 1)
```suggestion
	tastes = list("нежного мяса" = 1)
```

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/modules/mining/lavaland/ash_flora.dm
> +	harvested_name = "coaltree stump"
Прописать `ru_names` сюда, аналогично с изменённым названием на английском.

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/projectile/bow.dm
> +	desc = "Послушай, ты не мог бы положить это яблоко себе на голову?"
Хорошо.

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/projectile/bow.dm
> +	gender = MALE
Если гендер аналогичен гендеру родителя, то зачем его прописывать снова, если он наследуется?
Аналогично убрать у наследуемых стрел ниже.
```suggestion
```

2025-02-12 10:57 UTC, PlayerUnknown14 commented on code/modules/surgery/tools.dm
> +	gender = MALE
Лучше прописать у родительских объектов, а не у наследуемых.

2025-02-12 10:59 UTC, PlayerUnknown14 commented
Блядские код суггесты снова всё сломали. Ладно, автор поправит сам.

2025-02-17 08:54 UTC, PlayerUnknown14 approved these changes, later dismissed

2025-02-17 10:10 UTC, BeebBeebBoob requested changes
Проверял на мобиле

2025-02-17 10:10 UTC, BeebBeebBoob commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
> +	if(drying)//no need to update unless something got dried
```suggestion
	if(!drying)//no need to update if we don't dry
		return
```

2025-02-17 10:10 UTC, BeebBeebBoob commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
> +	var/drying_timer = 1
```suggestion
	var/drying_timer = 0
```

2025-02-17 10:10 UTC, BeebBeebBoob commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
> +	update_icon(UPDATE_OVERLAYS)
``` suggestion
if(drying_timer)
	drying_timer--
	if(!drying_timer) //if it went to zero, dry and reset
		drying_timer = initial(drying_timer)
		if(rack_dry())
			update_icon(UPDATE_OVERLAYS)
else // no timer
	if(rack_dry())
		update_icon(UPDATE_OVERLAYS)
```

2025-02-17 10:10 UTC, BeebBeebBoob commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	butcher_results = list(/obj/item/reagent_containers/food/snacks/monstermeat/goliath= 2, /obj/item/stack/sheet/animalhide/goliath_hide = 2, /obj/item/stack/sheet/bone = 2)
```suggestion
	butcher_results = list(/obj/item/reagent_containers/food/snacks/monstermeat/goliath = 2, /obj/item/stack/sheet/animalhide/goliath_hide = 2, /obj/item/stack/sheet/bone = 2)
```

2025-02-17 10:10 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/projectile/bow.dm
> +	var/nemesis_faction = FALSE
?? А это зачем?

2025-02-17 10:10 UTC, BeebBeebBoob commented on code/modules/surgery/tools.dm
> +	throwforce = 9.0
```suggestion
	force = 15
	sharp = 1
	w_class = WEIGHT_CLASS_NORMAL
	throwforce = 9
```

2025-02-17 10:42 UTC, MeowEmiya commented on code/modules/projectiles/guns/projectile/bow.dm
> +	var/nemesis_faction = FALSE
Надо

2025-02-17 23:05 UTC, merged

2025-02-18 11:15 UTC, MeowEmiya commented
Наконец, я свободен