Астероид прослушки Ми-13
ss220-space/Paradise pull request #590
Opened 2022-01-21 22:33 UTC by Jalesen

## What Does This PR Do
Замена оригинального астероида прослушки на новый со своим геймплеем, и обязанностями.

## Why It's Good For The Game
Некоторые трейторы-механики или простые цивилы идут в исследователи, чтобы залутать на астероиде лёгкую карту агента, также как и другие антагонисты, как культисты и т.д. используют это место как свою базу. Так почему бы не дать госту стать секретным агентом коммуникаций Ми-13?

## Images of changes

![rend](https://user-images.githubusercontent.com/87149132/150608185-78b2f444-1906-4ff0-a99c-d6dcf0916abb.png)
![image](https://user-images.githubusercontent.com/87149132/150608844-5e1f1221-1168-4821-b9db-e89dee7788cc.png)
![image](https://user-images.githubusercontent.com/87149132/150608919-c2227801-3fd5-454d-97f4-356b048cab71.png)

## Changelog
:cl:
add: Добавлен астероид прослушки, а также код для него. (Как по мне 5 поинтов бюджета косморуин приемлемая цена за целую гостроль, плюс за контент внутри)
del: Закомменчен код оригинального астероида коммуникаций
/:cl:

2022-01-21 23:44 UTC, Furukia requested changes
Вот пару важный изменений по коду. Карту может потом гляну...

2022-01-21 23:44 UTC, Furukia commented on code/modules/ruins/lavalandruin_code/syndicate_base.dm
> +		/obj/item/storage/box/survival_syndi
Помещение коробки напрямую в рюкзак не будет работать. Для коробки есть отдельное хранилище box. Из которого потом по коду оно заносится в рюкзак. Т.е. надо писать: `box = /obj/item/storage/box/survival_syndi`

2022-01-21 23:44 UTC, Furukia commented on code/modules/ruins/lavalandruin_code/syndicate_base.dm
> +	if(prob(0)) //only has a 10% chance of existing, otherwise it'll just be a NPC syndie.
Если при спавне астероида там всегда гост спавн, зачем вообще эта проверка? Тем более с нулевым шансом. Удалить.

2022-01-22 09:29 UTC, Vallat commented on code/modules/ruins/lavalandruin_code/syndicate_base.dm
> +		/obj/item/storage/box/survival_syndi
Будет оно работать

2022-01-22 10:24 UTC, Furukia commented on code/modules/ruins/lavalandruin_code/syndicate_base.dm
> +		/obj/item/storage/box/survival_syndi
На моём опыте не работало. Я для этого пол кода просмотрела и увидела. что там есть отдельный параметр для коробки через который уже работает

2022-01-27 08:49 UTC, closed without merging

2022-01-27 08:51 UTC, Jalesen commented
Как никак это была проба пера, и я не расстроен, что предложение заброковали. Спасибо фурукай и жену за помощь с кодом.