qol: recharge spell million istypes removal
ss220-space/Paradise pull request #5915
Opened 2024-09-16 06:39 UTC by Antoonij

## Описание
теперь ооп

## Ссылка на предложение/Причина создания ПР
qol, но возможно не совсем правильно понял старое поведение

## Тесты
не могу, но я верю в то, что это будет работать (вин 7 момент)

2024-10-05 23:00 UTC, Daeberdir requested changes

2024-10-05 23:00 UTC, Daeberdir commented on code/datums/spells/charge.dm
> +			to_chat(user, span_notice("[charged_item] suddenly feels very warm!"))
Свитч на два значения не особо резонно. Медленнее ифок, но там достаточно просто `if(charge_result & RECHARGE_BURNOUT) -> burnut_code; else -> success_code`. Сами битфлаги именно |= добавлять, а не возвращать их поодиночно. Избавиться от битфлага "ноуэффект" и проверяй просто неналичие битфлага "успех".

2024-10-05 23:00 UTC, Daeberdir commented on code/datums/spells/charge.dm
> +	var/list/hand_items = list(living.get_active_hand(), living.get_inactive_hand())
Лучше искать эти предметы после того, как мы уверены, что они нам нужны. То есть, после того, как мы не зарядим то, что тащим за собой.

2024-10-05 23:22 UTC, Daeberdir commented on code/datums/spells/charge.dm
> +			to_chat(user, span_notice("[charged_item] suddenly feels very warm!"))
А ещё надпись об "нереактинге" изменить бы... на надпись об реактинге, но "явно каком-то не таком".

2024-10-06 00:08 UTC, Den109G commented on code/game/atoms.dm
> +	return RECHARGE_NO_EFFECT
А разве тут нет эффекта? Вроде батарейки мы зарядили.

2024-10-10 12:05 UTC, Daeberdir approved these changes
Теперь это всё имеет смысл.

2024-10-10 16:37 UTC, Den109G approved these changes
Выглядит хорошо.

2024-10-10 16:42 UTC, merged