refactor: godmode
ss220-space/Paradise pull request #5920
Opened 2024-09-18 16:20 UTC by Antoonij

## Описание
Режим бога переезжает в трейт для более приятной работы с ним, освобождая место для статус эффектов kotvshlyapi

## Ссылка на предложение/Причина создания ПР
могу дать на эшапдейт, но в этом смысла нет

## Тесты
не нужны

2024-09-18 18:19 UTC, Den109G commented on code/_globalvars/traits.dm
> +		"TRAIT_GODMODE" = TRAIT_GODMODE,
По алфавиту поставь (как просит комментарий выше)

2024-09-21 18:13 UTC, Den109G approved these changes, later dismissed
Good refactor. Выглядит всё работоспособным.

2024-09-22 04:44 UTC, Daeberdir requested changes

2024-09-22 04:44 UTC, Daeberdir commented on code/datums/spells/shapeshift.dm
> +		if(HAS_TRAIT(mob, TRAIT_GODMODE))
В этом месте часом не нужно проверять на то, что у нашего мобчика годмод именно от сурса?

2024-09-22 04:44 UTC, Daeberdir commented on code/game/objects/items/weapons/anomaly_extract.dm
> +	ADD_TRAIT(user, TRAIT_GODMODE, UNIQUE_TRAIT_SOURCE(src))
В чём суть разделения на оригинальное тело и юзера в этом месте, если они становятся равны парой строчек выше?

2024-09-22 04:44 UTC, Daeberdir commented on code/modules/antagonists/vampire/vampire_powers/bestia_powers.dm
> +	vampire_animal.add_traits(list(TRAIT_NO_TRANSFORM, TRAIT_GODMODE), UNIQUE_TRAIT_SOURCE(src))
Вот тут вот, собственно, пример, откуда Потрох брал код для шейпшифта в слайма, если ко мне доверия нет.

2024-09-22 04:44 UTC, Daeberdir commented on code/modules/power/tesla/energy_ball.dm
> +	if(isliving(atom))
Вот бы тут убрали лесенку, раз уж проверки на ливинг и карбона друг другу не мешают...

2024-09-22 04:44 UTC, Daeberdir commented on code/modules/mob/living/simple_animal/hulk.dm
> +		REMOVE_TRAIT(mob, TRAIT_GODMODE, UNIQUE_TRAIT_SOURCE(src))
No. Nonononononononononon
![807297fb65313b9a680076438faf539d](https://github.com/user-attachments/assets/d30e760f-1500-4d72-91ca-a3c69091b8d3)

2024-09-22 04:44 UTC, Daeberdir commented on code/modules/mob/living/simple_animal/hulk.dm
> +		REMOVE_TRAIT(mob, TRAIT_GODMODE, UNIQUE_TRAIT_SOURCE(src))
Вот тут уже нужно прописывать свои источники трейта по типу "халковый трейт", потому-что ниже ты забиваешь его от уникального сурса в виде спелла.

2024-09-22 17:20 UTC, Daeberdir approved these changes
Теперь должно работать хорошо.

2024-09-22 19:26 UTC, Den109G approved these changes

2024-09-22 19:31 UTC, merged