refactor: Handle random events in life cycle
ss220-space/Paradise pull request #5931
Opened 2024-09-23 06:37 UTC by Antoonij

## Описаниe
Взял с тг и улучшил под наш билд. Теперь рвота вызывается статус эффектом, который происходит в SetToxLoss и AdjustToxLoss, когда достигаются условия дефайна

## Ссылка на предложение/Причина создания ПР
всегда должен быть тот, кто делает 100 страниц рефакторов

## Тесты
не могу catrose

2024-10-06 00:28 UTC, Den109G commented on code/modules/mob/living/carbon/carbon.dm
> +	if((nutrition < lost_nutrition) && (!(mode & VOMIT_BLOOD)))
Думаешь стоит до конца выкачивать жертву? Я всегда думал, что там "подушка" в 100-ю, как раз чтобы постоянная рвота не могла убить сама по себе.

2024-10-06 17:31 UTC, Den109G submitted a review, later dismissed
Выглядит хорошо.

2024-10-08 20:34 UTC, Daeberdir requested changes

2024-10-08 20:34 UTC, Daeberdir commented on code/modules/mob/living/carbon/carbon.dm
> +	if((nutrition < 100 || nutrition < lost_nutrition) && (!(mode & VOMIT_BLOOD)))
```suggestion
	if(nutrition < lost_nutrition && (!(mode & VOMIT_BLOOD)))
```

2024-10-08 20:34 UTC, Daeberdir commented on code/modules/mob/living/carbon/carbon.dm
> +	for(var/i = 0 to distance)
```suggestion
	for(var/i = 0 to min(distance, round(nutrition / lost_nutrition, 1)))
```

2024-10-08 20:34 UTC, Daeberdir commented on code/modules/mob/living/carbon/carbon.dm
> +	playsound(get_turf(src), 'sound/effects/splat.ogg', 50, 1)
```suggestion
	playsound(get_turf(src), 'sound/effects/splat.ogg', 50, TRUE)
```

2024-10-08 20:34 UTC, Daeberdir commented on code/__DEFINES/mobs.dm
> +#define VOMIT_TOXIN 			(1<<0)
Так, как у нас не произошло внедрения в прок рвоты "фальш рвоты", то думаю, что нам стоит отказаться совсем от флага токсинной рвоты (которая нутриментная, дада) и перейти на простую проверку не нуля `lost_nutrition`.

2024-10-08 22:28 UTC, Den109G submitted a review, later dismissed

2024-10-08 22:52 UTC, Daeberdir approved these changes
Теперь оно работает, с подушкой безопасности и прочей дрянью без лишней дряни.

2024-10-08 22:57 UTC, Den109G approved these changes

2024-10-08 23:04 UTC, merged