Syndicate affiliates 2.0
ss220-space/Paradise pull request #5932
Opened 2024-09-23 07:39 UTC by Anorak2024

## Описание
Подрядчики :badguy:

## Ссылка на предложение
Пока голосование не прошло

## Демонстрация изменений

## Тесты

2024-09-24 08:13 UTC, ROdenFL commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	new_item.can_discount = FALSE
Че за костыль

2024-09-24 08:16 UTC, ROdenFL commented
Хоть написал чей код используешь

2024-09-24 08:59 UTC, Anorak2024 commented
> Хоть написал чей код используешь

Теперь написал

2024-09-24 09:00 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	new_item.can_discount = FALSE
Я джун, мне можно

2024-09-24 09:01 UTC, ROdenFL commented
> > Хоть написал чей код используешь
> 
> Теперь написал

Собаку перед ником поставь

2024-09-24 09:40 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	new_item.can_discount = FALSE
Не такой уж и плохой вариант. В первойм не вижу проблемы. Оно взято из твоего кода, но вынесено в функцию.

На счет второго, надо же чтобы определенные предметы выдаваись в зависимости от целей, а не в зависимости от подрядчика. Предлагаешь сделать определенные готовые не падающие аплинк итемы и добавлять их?

2024-09-24 13:06 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	new_item.can_discount = FALSE
Сделал предметы для целей отдельными аплинк итемами, которые пихаются только в админский аплинк. В целях сделал добавление этих предметов в аплинк при выпадении целей требующих эти предметы.

2024-09-24 13:44 UTC, ROdenFL commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	new_item.can_discount = FALSE
> Не такой уж и плохой вариант. В первойм не вижу проблемы. Оно взято из твоего кода, но вынесено в функцию.
> 
> На счет второго, надо же чтобы определенные предметы выдаваись в зависимости от целей, а не в зависимости от подрядчика. Предлагаешь сделать определенные готовые не падающие аплинк итемы и добавлять их?

Мне просто кажется, что им бы не аплинк итемс попадать, а в отдельную вкладку в разделе аффилиатов

2024-09-24 21:33 UTC, Ssheya reviewed
Немного насрал по русскому языку.

2024-09-24 21:33 UTC, Ssheya commented on code/datums/uplink_item.dm
> +	desc = "Высокотехнологичное устройство для взлома мехов разработанное Cybersun Industries. При взломе меха, мгновенно сбивает все блокировки и выкидывает текущего пилота."
Высокотехнологичное устройство для взлома мехов, разработанное Cybersun Industries. При взломе меха мгновенно сбивает все блокировки и выкидывает текущего пилота.
учимся русская языка

2024-09-24 21:33 UTC, Ssheya commented on code/datums/uplink_item.dm
> +	desc = "Высокотехнологичное устройство для взлома боргов разработанное Cybersun Industries. При взломе борга, ставит ему прошивку борга Синдиката с нулевым законом на подчинение взломавшему. Устройс
Высокотехнологичное устройство для взлома боргов, разработанное Cybersun Industries. При взломе борга ставит ему прошивку борга Синдиката с нулевым законом на подчинение взломавшему. Устройство одноразовое.
продолжаем учиться

2024-09-24 21:33 UTC, Ssheya commented on code/datums/uplink_item.dm
> +	desc = "Специальный SSD накопитель предназначеный для кражи технологий с серверов R&D. При успешной краже, технологии сбросятся. При разборке данного предмета, все технологии с него будут восстановл
Специальный SSD накопитель, предназначеный для кражи технологий с серверов R&D. При успешной краже технологии сбросятся. При разборке данного предмета, все технологии с него будут восстановлены.
всё ещё учимся

2024-09-24 21:33 UTC, Ssheya commented on code/datums/uplink_item.dm
> +	desc = "Высокотехнологичный, разработанный Cybersun Industries имплант, необратимо изменяющий мозг цели, делая ее лояльной Синдикату."
Высокотехнологичный, разработанный Cybersun Industries, имплант, необратимо изменяющий мозг цели, делая ее лояльной Синдикату.
люблю причастные обороты

2024-09-24 21:33 UTC, Ssheya commented on code/datums/uplink_item.dm
> +	desc = "Инжектор с дорогой и сложной в производстве сывороткой открытой Hematogenic Industries. При введении гуманойду, запускает сложные "
Инжектор с дорогой и сложной в производстве сывороткой, открытой Hematogenic Industries. При введении гуманойду запускает сложные
опять запятые, и что оно запускает?

2024-09-24 21:33 UTC, Ssheya commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Украдите [req_techs] уровней технологий просканировав сервера R&D при помощи Фирменного SSD, который вы можете приобрести во вкладке \"Affiliate specific\"."
Украдите [req_techs] уровней технологий, просканировав сервера R&D при помощи Фирменного SSD, который вы можете приобрести во вкладке \"Affiliate specific\"

2024-09-24 21:33 UTC, Ssheya commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Implant the [target.current.real_name], [target.assigned_role] with a modified mindslave implant. You can find it in uplink in \"Affiliate specific\""
Про то что разные языки везде промолчу. 
Implant [target.current.real_name], the [target.assigned_role] with a modified mindslave implant. You can find it in uplink in \"Affiliate specific\"

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/gorlex.dm
> +			Как вам стоит работать: вам выдело 30 минут на подготовку, далее\n\
вам выделено

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/gorlex.dm
> +			Вам предоставлен код от системы самоуничтожения станции, а также система отслеживания диска ядерной аутенфикации;\n\
ядерной аутентификации

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/gorlex.dm
> +			После выполнения всех поставленных задач незамедлительно уничтожьте главную улику указывающую на причастность Gorlex Maraduers. \n\
улику, указывающую

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +	desc = "Вы один из представителей \"большой фармы\" Hematogenic Industries, ваш наниматель \n\
большой фирмы

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +			Но в замен Корпорация предлагает вам опробовать её передовую разработку Hemophagus Essence Auto Injector."
взамен

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +			Как вам стоит работать: действуйте на свое усмотрение, главное не забывайте про фармакологическую этику - не навреди Корпорации. \n\
усмотрение, главное, не забывайте

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +	desc = "Инжектор странной формы, с неестественно двигающейся алой жидкостью внутри. На боку едва заметная гравировка \"Hematogenic Industries\". Конкретно на этом инжекторе установлена блокировка не
блокировка, не позволяющая

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/mi13.dm
> +			Вы были внедрены в труктуру NanoTrasen для поиска и получения секретных сведений; однако возможно, что придется испачкать перчатки в крови. \n\
в структуру

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/tiger.dm
> +			Как вам стоит работать: не раскрывайте свое присутсвие и присутствие генокрада, позаботьтесь о его успешном внидрении. \n\
внедрении

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/tiger.dm
> +	desc = "Looks like something moving inside it"
something is moving

2024-09-24 21:33 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/tiger.dm
> +	desc = "Looks like something moving inside it"
something is moving

2024-09-24 21:33 UTC, Ssheya commented on tgui/packages/tgui/interfaces/Uplink.js
> +        '  Cybersun Industries - одна из ведущих корпораций представляющая второй по мощи исследовательский центр в этой части вселенной.\n' +
корпораций, представляющая

2024-09-24 21:33 UTC, Ssheya commented on tgui/packages/tgui/interfaces/Uplink.js
> +        +'Gorlex занимается в заказными убийствами, налётами, рейдами и террористическими актами.\n' +
занимается заказными

2024-09-24 21:33 UTC, Ssheya commented on tgui/packages/tgui/interfaces/Uplink.js
> +        +'Ответственны за подготовку всех подразделений Группы Атом, SSD, кроме команд саботажа.\n' +
SSD? может SST?

2024-09-24 21:33 UTC, Ssheya commented on tgui/packages/tgui/interfaces/Uplink.js
> +        +'Агенты MI13, крайне быстры, точны, и элегантны. Многие замечают, что они подражают структуре секретных агентств 20 века.\n' +
агенты MI13 крайне быстры, точны и элегантны

2024-09-24 21:33 UTC, Ssheya commented on tgui/packages/tgui/interfaces/Uplink.js
> +        '  Tiger Cooperative - Группа религиозных фундаменталистов, поклоняющихся генокрадам.\n' +
почему тут Группа с большой, в других местах после тире всё с маленькой буквы?

2024-09-24 21:33 UTC, Ssheya commented on tgui/packages/tgui/interfaces/Uplink.js
> +        +'Высшей благодатью для всех членов Tiger Cooperatived, является поглощение их тела генокрадом, и становления чем-то… Большим…\n' +
членов TC является поглощение их тела генокрадом и становление

2024-09-24 21:33 UTC, Ssheya commented on tgui/packages/tgui/interfaces/Uplink.js
> +        +'Eё открытия и продукция в области медицины, спасают сотни жизней по всей Галактике\n' +
области медицины спасают сотни

2024-09-24 21:33 UTC, Ssheya commented on tgui/packages/tgui/interfaces/Uplink.js
> +        +'Hematogenic Industries мелькала в большом количесвте скандалов связанных с Гематофагами и пропажей нанятых Воксов.\n' +
большом количестве скандалов

2024-09-24 21:34 UTC, Ssheya commented
а теперь после того как насрал пойду спать

2024-09-25 05:38 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	desc = "Высокотехнологичное устройство для взлома мехов разработанное Cybersun Industries. При взломе меха, мгновенно сбивает все блокировки и выкидывает текущего пилота."
🤓

2024-09-25 05:41 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	desc = "Высокотехнологичное устройство для взлома боргов разработанное Cybersun Industries. При взломе борга, ставит ему прошивку борга Синдиката с нулевым законом на подчинение взломавшему. Устройс
🤓

2024-09-25 05:44 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	desc = "Специальный SSD накопитель предназначеный для кражи технологий с серверов R&D. При успешной краже, технологии сбросятся. При разборке данного предмета, все технологии с него будут восстановл
🤓

2024-09-25 05:47 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	desc = "Высокотехнологичный, разработанный Cybersun Industries имплант, необратимо изменяющий мозг цели, делая ее лояльной Синдикату."
не люблю причастные обороты

2024-09-25 05:50 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	desc = "Инжектор с дорогой и сложной в производстве сывороткой открытой Hematogenic Industries. При введении гуманойду, запускает сложные "
desc = "Инжектор с дорогой и сложной в производстве сывороткой, открытой Hematogenic Industries. При введении гуманойду запускает сложные, процессы делающие гуманойда вампиром."

2024-09-25 05:51 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	desc = "Инжектор с дорогой и сложной в производстве сывороткой открытой Hematogenic Industries. При введении гуманойду, запускает сложные "
Без запятой, хз почему я ее там поставил

2024-09-25 05:51 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	desc = "Инжектор с дорогой и сложной в производстве сывороткой открытой Hematogenic Industries. При введении гуманойду, запускает сложные "
Точнее нет. Запятую вперед через слово.

2024-09-25 05:54 UTC, Anorak2024 commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Implant the [target.current.real_name], [target.assigned_role] with a modified mindslave implant. You can find it in uplink in \"Affiliate specific\""
Разные языки потому-что фразы частично на английском, частично на русском - харам.

2024-09-25 05:58 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +	desc = "Вы один из представителей \"большой фармы\" Hematogenic Industries, ваш наниматель \n\
В мою защиту, ошибки в этих описаниях из старого кода подрядчиков.

2024-09-25 06:00 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/tiger.dm
> +	desc = "Looks like something moving inside it"
Тоже из старого кода

2024-09-25 06:02 UTC, Anorak2024 commented on tgui/packages/tgui/interfaces/Uplink.js
> +        +'Ответственны за подготовку всех подразделений Группы Атом, SSD, кроме команд саботажа.\n' +
А хз, я лазал по вики разных серверов и копипастил круто выглядящие фразы, ща уже не смогу найти где это было. убрал ", SSD".

2024-09-25 06:05 UTC, Anorak2024 commented on tgui/packages/tgui/interfaces/Uplink.js
> +        +'Агенты MI13, крайне быстры, точны, и элегантны. Многие замечают, что они подражают структуре секретных агентств 20 века.\n' +
Перечитал, решил что слишком глупо звучит, поставил "Агенты MI13 обычно не действуют открыто.".

2024-09-25 06:05 UTC, Anorak2024 commented on tgui/packages/tgui/interfaces/Uplink.js
> +        '  Tiger Cooperative - Группа религиозных фундаменталистов, поклоняющихся генокрадам.\n' +
Кажется тоже с какой-то вики скопировал и перевел

2024-09-25 06:06 UTC, Anorak2024 commented on tgui/packages/tgui/interfaces/Uplink.js
> +        +'Высшей благодатью для всех членов Tiger Cooperatived, является поглощение их тела генокрадом, и становления чем-то… Большим…\n' +
Это скопипастил из ТЗ

2024-09-25 06:07 UTC, Anorak2024 commented on tgui/packages/tgui/interfaces/Uplink.js
> +        +'Eё открытия и продукция в области медицины, спасают сотни жизней по всей Галактике\n' +
Тоже копипаста с ТЗ

2024-09-25 06:45 UTC, Ssheya commented
Сам такой

2024-09-25 13:39 UTC, Ssheya reviewed
русский язык

2024-09-25 13:39 UTC, Ssheya commented on code/datums/uplink_item.dm
> +	desc = "Большой шприц, специально разработаный для быстрого сбора больших объемов крови. Можно исспользовать только на гуманойдах обладающих душой. Из-за высокой скорости сбора крови, обычно значите
на гуманоидах обладающих

2024-09-25 13:39 UTC, Ssheya commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Набрать кровь у нескольких разумных гуманойдов."
разумных гуманоидов

2024-09-25 13:39 UTC, Ssheya commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Соберите [req_blood_samples] образцов крови у [req_blood_samples] различных разумных гуманойдов."
разумных гуманоидов

2024-09-25 13:42 UTC, Ssheya reviewed
ещё капля русского могучего

2024-09-25 13:42 UTC, Ssheya commented on code/datums/uplink_item.dm
> +	desc = "Инжектор с дорогой и сложной в производстве сывороткой, открытой Hematogenic Industries. При введении гуманойду запускает сложные процессы, делающие гуманойда вампиром."
гуманоиду, гуманоида

2024-09-25 13:43 UTC, Ssheya commented
🤓

2024-09-26 21:59 UTC, Ssheya reviewed
Великий, могучий, русский язык.

2024-09-26 21:59 UTC, Ssheya commented on code/datums/uplink_item.dm
> +	desc = "Инжектор вводящий в цель модифицированное яйцо генокрада. После введения зародыш вступает в близкий симбиоз с телом носителя наделяя того способностями генокрадов."
Инжектор, вводящий в цель модифицированное яйцо генокрада. После введения зародыш вступает в близкий симбиоз с телом носителя, наделяя того способностями генокрадов.

2024-09-26 21:59 UTC, Ssheya commented on code/datums/uplink_item.dm
> +	desc = "Инжектор вводящий в цель модифицированное яйцо генокрада. После введения зародыш вступает в близкий симбиоз с телом носителя наделяя того способностями генокрадов."
Инжектор, вводящий в цель модифицированное яйцо генокрада. После введения зародыш вступает в близкий симбиоз с телом носителя, наделяя того способностями генокрадов.

2024-09-26 21:59 UTC, Ssheya commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Проследите чтобы к концу смены количество живых бореров было по меньшей мере [req]."
Проследите, чтобы к концу

2024-09-26 21:59 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/tiger.dm
> +	desc = "Кажется внутри что-то двигается. На боку этикетка \"Tiger Cooperative\""
Кажется, внутри

2024-09-26 21:59 UTC, Ssheya commented on code/game/gamemodes/objective.dm
> +/datum/objective/maroon/agent/find_target(list/target_blacklist) // Blueshield. If there are no suitable blueshields, take a random crew member.
а че за марун кстати?

2024-09-27 05:46 UTC, Anorak2024 commented on code/game/gamemodes/objective.dm
> +/datum/objective/maroon/agent/find_target(list/target_blacklist) // Blueshield. If there are no suitable blueshields, take a random crew member.
На коммент не смотри, я его случайно перенес когда копипастил. Обычный марун это не дать сбежать.  Конкретно этот - не дать сбежать агенту.

2024-09-27 20:49 UTC, Vladisvell requested changes
Замечания по стилю кода

2024-09-27 20:49 UTC, Vladisvell commented on code/game/gamemodes/malfunction/Malf_Modules.dm
>  	sleep(100)
Поставь пустые строки после блоков for для читаемости кода

2024-09-27 20:49 UTC, Vladisvell commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	to_chat(src, span_warning("[master_name] - ваш мастер. Выполняйте приказы мастера. Помогите мастеру выполнить цели либой ценой!"))
Аналогично комментарию выше, после блоков if ставь пустую строку для читаемости

2024-09-27 20:49 UTC, Vladisvell commented on code/game/gamemodes/objective.dm
> +		possible_targets |= possible_target
Пустую строку после continue для читаемости

2024-09-27 20:49 UTC, Vladisvell commented on code/game/gamemodes/objective.dm
> +	return FALSE
Поставь пустые строки после блоков for и if для читаемости кода

2024-09-27 20:49 UTC, Vladisvell commented on code/game/gamemodes/objective.dm
> +	return target
Пустая строка после блока if

2024-09-27 20:49 UTC, Vladisvell commented on code/game/gamemodes/objective.dm
> +	return minds.len >= req_blood_samples
Пустая строка после блока if и for

2024-09-27 20:49 UTC, Vladisvell commented on code/game/gamemodes/objective.dm
> +	return target
Пустая строка после блока if

2024-09-27 20:49 UTC, Vladisvell commented on code/game/gamemodes/objective.dm
> +		possible_targets |= possible_target
Пустая строка после блока if

2024-09-27 20:49 UTC, Vladisvell commented on code/game/gamemodes/objective.dm
> +		possible_targets |= possible_target
Пустая строка после блока if

2024-09-27 20:49 UTC, Vladisvell commented on code/game/gamemodes/objective.dm
> +	return target
Пустая строка после блока if

2024-09-27 20:49 UTC, Vladisvell commented on code/game/objects/items/devices/uplinks.dm
> +				continue
Здесь и выше по проку - пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	for(var/objective in objectives)
Пустая строка после блока if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	var/datum/antagonist/traitor/traitor = mind?.has_antag_datum(/datum/antagonist/traitor)
Пустая строка после блока if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/contractor.dm
> +	traitor.old_give_objectives()
Пустая строка после блока if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/cybersun.dm
> +		return
Пустая строка после блока if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/cybersun.dm
> +			investigate_log("[key_name_log(user)] deleted all technology on this server.", INVESTIGATE_RESEARCH)
Пустая строка после блоков if и for

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/cybersun.dm
> +			investigate_log("[key_name_log(user)] deleted all technology on this console.", INVESTIGATE_RESEARCH)
Пустая строка после блоков if и for

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/cybersun.dm
> +			investigate_log("[key_name_log(user)] deleted all technology on this fabricator.", INVESTIGATE_RESEARCH)
Пустая строка после блоков if и for

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/cybersun.dm
> +		return
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/cybersun.dm
> +	for(var/datum/objective/new_mini_traitor/objective in T.objectives)
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/gorlex.dm
> +		return
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +		inject(user, H)
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +				return
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +				return
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +	return TRUE
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +	var/mob/living/carbon/human/H = target
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +		var/obj/item/organ/external/bodypart = pick(target.bodyparts)
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/hematogenic.dm
> +		return
Пустая строка после блока if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/self.dm
> +	if (names.len > 3)
Пустая строка после блока for

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/self.dm
> +		return
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/self.dm
> +		silicon.clear_zeroth_law()
Пустая строка после блоков if

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/self.dm
> +			objective.already_free += silicon.mind
Пустая строка после блоков if и for

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/affiliates/tiger.dm
> +		return
Пустая строка после блоков if и for

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/antagonists/traitor/datum_traitor.dm
> +			continue
Пустая строка после блоков if и for

2024-09-27 20:49 UTC, Vladisvell commented on code/modules/research/rdconsole.dm
>  	var/pointless = FALSE
Пустая строка после блоков if и for

2024-09-27 21:45 UTC, DefaultMihail commented
Некоево "Мииш" призвали без пинга, а пришел я Badguy
Если голосование не прошло то хотяб ссылку на предложение, а то я не ебу что за реворк и что трогали
По "Syndicate affiliates" нахожу только ссылки на этот пулл

2024-09-28 04:56 UTC, Anorak2024 commented
> Некоево "Мииш" призвали без пинга, а пришел я Badguy Если голосование не прошло то хотяб ссылку на предложение, а то я не ебу что за реворк и что трогали По "Syndicate affiliates" нахожу только ссылки на этот пулл

Оно рошло недавно, прост я ссылку забыл добавить. Если коротко - разные фракции нанимателей в синдикате, со своими целями и механами. В ПРе куча чего отличается от ТЗ и если это работает лучше, то так и задумано.

2024-09-28 13:08 UTC, DefaultMihail commented
Проверял на [Anorak2024:syndicate_affiliates_2.0](https://github.com/Anorak2024/Paradise/tree/syndicate_affiliates_2.0)
Не проверял засчитывание выполненный целей/выдачу целей/специфичные для расс вещи(и так насрано достаточно + впадлу).

QA "Срать вечно" вещает:
1. При выдаче трейторки с определённым подрядчиком, если назать отмена, то будет трейтор с Unknown(минор, это в админ панели)
 1.1. Там же traitor with CONCRET affiliate, что за бетон и что он там делает? Гугл переводчик сила, школа - 💀. Используйтё лучше DeepL, там конкретный становится не бетоном, а specific.
2. После выбора подрядчика через кнопку, кнопка остаётся
3. (Вкусовщина) Насрали текстом в выборе подрядчиков, тяжело будет понять плюсы/минусы того или иного подрядчика. В аплинке так же насрано
4. Нет иконок у многих подрядчиков. 
5. У MI13:
 5.1. По ТЗ доступна к покупке только сидни ева - ноуп, можно купить всё, ограничена только вкладка из п.1 ТЗ,
 5.2. По ТЗ имеют 50ТК, при выборе через кнопку и через панель - 20ТК
 5.3. По ТЗ(снизу требования к разработке) противоречим 5.1 "Невозможно купить Syndicate Hardsuit." - его там реально нет, но ТЗ говна получается
6. Cybersun Industries:
 6.1. Текст скидок кривой и выбивается (Актуально для всех подрядчиков, где выдаются скидки):
![изображение](https://github.com/user-attachments/assets/7e403d0c-eb9c-47e7-95d4-d951804b44fe)
 6.2. Invasive Beacon даёт 6 Data 3 Bio(должно было быть Magnets) 1 Illegal
7. Hematogenic Industries:
 7.1. Экстракт стоит 74ТК, по ТЗ - 0ТК. В том же ТЗ цена 60ТК. Чё за хуйня?
 7.2. Цели после становлением вампиром не изменяются, при использовании на другую куклу не добавляются, получается вампир с пустыми целями
 7.3. Никаких стадий превращения не замечено
8. Gorlex Marauders:
 8.1. Таймер на 20 минут работает не от начала раунда, а с момента выбора
 8.2. Не видят других оперативников Gorlex, худа нет 
9. SELF:
 9.1. При использовании на киборге синего емага законы становятся пустыми, а не предопределёнными
 9.2. Ничего не мешает юзать емаг/плату
10. Tiger Cooperative:
 10.1. Могут купить дигл
 10.2. Могут пользоваться любым дальнобойным оружеем
 10.3. Скидки не обнаружены
 10.4. Где egg implanter?
 
![изображение](https://github.com/user-attachments/assets/0aa6a6fe-c8c1-4cd7-a194-bbeb5bb1f5ba)

2024-09-30 07:51 UTC, ROdenFL commented
Нахуя вы Аплинк перевели, изверги

2024-09-30 08:13 UTC, NightDawnFox commented
Тебя забыли спросить, иди на оффпару кодь

2024-09-30 14:32 UTC, Den109G requested changes
Раз перевод - лучше через семь кругов перевода проходить.

2024-10-01 09:32 UTC, Anorak2024 commented
Ну, раз уж плашку повесили, терять нечего

2024-10-02 13:40 UTC, Den109G commented on code/datums/uplink_item.dm
> +			Оснащен самозаряжающимся ручным пулеметом, гранатометом, лазерным мечом, электронным прицелом, точечным указателем, вспышкой и ломом."
emag ->электронный прицел?

2024-10-02 13:40 UTC, Den109G commented on code/datums/uplink_item.dm
> +			Оснащен нанитовым гипоспреем, медицинским лучевым ружьем, боевым дефибриллятором, полным хирургическим набором, включающим энергетическую пилу, электромагнитный прицел, точечный указатель и вспышк
emag ->электро**магнит**ный прицел?

2024-10-02 13:40 UTC, Den109G commented on code/datums/uplink_item.dm
> +	cost = 30 // No brainrot allowed
Вот вообще не знаю, к чему это коммент. Сперва это было для мета комментарий для игроков, что капаются в коде, ибо он стоил почти весь аплинк. Потом поменяли цену, поменяв и коммент на юмористический.
Лучше убрать. Имхо - он не нужен.
```suggestion
	cost = 30
```

2024-10-02 13:40 UTC, Den109G commented on code/datums/uplink_item.dm
> +	desc = "Криптографический секвенсор, также известный как ЕМАГ, представляет собой небольшую карту, разблокирующую скрытые функции \
В переводе `cmag`-а, симаг оставил своё английское название, а тут поменялся.
Будет приписка для людей, что это добрый Emag? Или перевод затронет все сокращения, то будь кмаг, иль емаг?

2024-10-02 13:40 UTC, Den109G commented on code/datums/uplink_item.dm
> +	name = "Полностью укомплектованный тулбокс"
Может так? Я больше лагеря "лучше переводить полностью" и так кажется лучше для будущего перевода.
```suggestion
	name = "Полностью укомплектованный ящик с инструментами"
```

2024-10-02 13:40 UTC, Den109G commented on code/datums/uplink_item.dm
> +	name = "Большой Ящик Снабжения Синдиката"
По хорошему, определится бы как вещи в аплинке будут называться.
Или Каждое Слово Станет Именем Собственным,
Или только первая буква заглавная, только настоящие имена собственные будут с большой, как Игорь.

2024-10-02 13:40 UTC, Den109G commented on code/datums/uplink_item.dm
> +	name = "Персональный Искусственный Интеллект Синдиката (СПИИ)"
Поскольку слово Синдикат переехало в конец названия - и сокращение стоит доперевести.
```suggestion
	name = "Персональный Искусственный Интеллект Синдиката (ПИИС)"
```

2024-10-02 14:43 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	name = "Полностью укомплектованный тулбокс"
Предлагаю компромис, тулбоксы меняем, а хардсьюты оставляем. Идет?

2024-10-02 14:46 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	desc = "Криптографический секвенсор, также известный как ЕМАГ, представляет собой небольшую карту, разблокирующую скрытые функции \
Пусть будет emag. Так проще.

2024-10-02 14:48 UTC, Den109G commented on code/datums/uplink_item.dm
> +	name = "Полностью укомплектованный тулбокс"
Я не глав редактор, и не локализатор на русский. Но хардсьют для переводов тоже с моей стороны сомнителен.

2024-10-02 14:48 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +			Оснащен нанитовым гипоспреем, медицинским лучевым ружьем, боевым дефибриллятором, полным хирургическим набором, включающим энергетическую пилу, электромагнитный прицел, точечный указатель и вспышк
Упс

2024-10-02 14:50 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +			Оснащен самозаряжающимся ручным пулеметом, гранатометом, лазерным мечом, электронным прицелом, точечным указателем, вспышкой и ломом."
Тут еще "точечный указатель".

2024-10-02 14:57 UTC, ROdenFL commented on code/datums/uplink_item.dm
> +	name = "Персональный Искусственный Интеллект Синдиката (СПИИ)"
ПИИСдец

2024-10-02 16:48 UTC, Anorak2024 commented
> Проверял на [Anorak2024:syndicate_affiliates_2.0](https://github.com/Anorak2024/Paradise/tree/syndicate_affiliates_2.0) Не проверял засчитывание выполненный целей/выдачу целей/специфичные для расс вещи(и так насрано достаточно + впадлу).
> 
> QA "Срать вечно" вещает:
> 
> 1. При выдаче трейторки с определённым подрядчиком, если назать отмена, то будет трейтор с Unknown(минор, это в админ панели)
>    1.1. Там же traitor with CONCRET affiliate, что за бетон и что он там делает? Гугл переводчик сила, школа - 💀. Используйтё лучше DeepL, там конкретный становится не бетоном, а specific.
> 2. После выбора подрядчика через кнопку, кнопка остаётся
> 3. (Вкусовщина) Насрали текстом в выборе подрядчиков, тяжело будет понять плюсы/минусы того или иного подрядчика. В аплинке так же насрано
> 4. Нет иконок у многих подрядчиков.
> 5. У MI13:
>    5.1. По ТЗ доступна к покупке только сидни ева - ноуп, можно купить всё, ограничена только вкладка из п.1 ТЗ,
>    5.2. По ТЗ имеют 50ТК, при выборе через кнопку и через панель - 20ТК
>    5.3. По ТЗ(снизу требования к разработке) противоречим 5.1 "Невозможно купить Syndicate Hardsuit." - его там реально нет, но ТЗ говна получается
> 6. Cybersun Industries:
>    6.1. Текст скидок кривой и выбивается (Актуально для всех подрядчиков, где выдаются скидки):
>    ![изображение](https://private-user-images.githubusercontent.com/39703183/371754675-7e403d0c-eb9c-47e7-95d4-d951804b44fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODQ2NDMsIm5iZiI6MTcyNzg4NDM0MywicGF0aCI6Ii8zOTcwMzE4My8zNzE3NTQ2NzUtN2U0MDNkMGMtZWI5Yy00N2U3LTk1ZDQtZDk1MTgwNGI0NGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE1NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZjliZWJhNjNmZmU3ZWE2YzNhYzU1NmExZGJhNDk5Y2I5YzIzMmZjZjgyN2EyMTUyNDA3YzEwN2JhYzVmNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BgDT06couhiJ5vsaaNKqzv3yrKnivCvvpUuUw9xeV64)
>    6.2. Invasive Beacon даёт 6 Data 3 Bio(должно было быть Magnets) 1 Illegal
> 7. Hematogenic Industries:
>    7.1. Экстракт стоит 74ТК, по ТЗ - 0ТК. В том же ТЗ цена 60ТК. Чё за хуйня?
>    7.2. Цели после становлением вампиром не изменяются, при использовании на другую куклу не добавляются, получается вампир с пустыми целями
>    7.3. Никаких стадий превращения не замечено
> 8. Gorlex Marauders:
>    8.1. Таймер на 20 минут работает не от начала раунда, а с момента выбора
>    8.2. Не видят других оперативников Gorlex, худа нет
> 9. SELF:
>    9.1. При использовании на киборге синего емага законы становятся пустыми, а не предопределёнными
>    9.2. Ничего не мешает юзать емаг/плату
> 10. Tiger Cooperative:
>     10.1. Могут купить дигл
>     10.2. Могут пользоваться любым дальнобойным оружеем
>     10.3. Скидки не обнаружены
>     10.4. Где egg implanter?
> 
> ![изображение](https://private-user-images.githubusercontent.com/39703183/371759129-0aa6a6fe-c8c1-4cd7-a194-bbeb5bb1f5ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODQ2NDMsIm5iZiI6MTcyNzg4NDM0MywicGF0aCI6Ii8zOTcwMzE4My8zNzE3NTkxMjktMGFhNmE2ZmUtYzhjMS00Y2Q3LWExOTQtYmJlYjViYjFmNWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE1NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMGVlZjIwMzBmYTlhOTcxNGE2M2MxMGZkNGY1NjA2MDBmYzZmM2I0Mzk5NmQ1NDA5MjcwNGUyOTJlYjY2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8kNhhdDkdv2le2M00PLECnpMAHtzuwkx-Ic7hirXJSg)

1. Была частично фича. Если не выбрать самому, выбирался старый тритор, но сделал чтоб шла отмена выбора.
1.1 Поменял
2. Пофиксил
3. В выборе оставил плюсы, минусы и типовые цели.
4. Теперь иконок нет у всех подрячиков)))0)
5.1/5.2 Думаю что автор имел ввиду что из ригов доступна только синдиева. Оно щас так.
5.3. Фича, 50 ТК + бонд - много.
6.1 Больше не кривой
6.2 Исправил
7.1 Там тип обычный 74 (цена выше чем в ТЗ и это по плану), а так-же есть нужный для цели, который стоит 0.
7.2 Ща появляются.
7.3 Фича, решил что если сделать, будет чисто афк стояние минут 5 в дормах.
8.1 Вроде исправил
8.2 Пофиг, потом сделаю. Точно и смотрящий и тот на кого смотрят были горлексами с выданным аплинком?
9.1 Фича, странно освобождать борга от законов, только чтобы дать ему другие. С новым сводом законов он не мог пойти в рабство при желании, а ведь это его выбор.
9.2 Вроде пофиксил
10.1 Больше не могут. Какой-то гений поместил дигл в раздел бесполезного.
10.2 Ща вроде не могут
10.3 Теперь есть
10.4 Есть

2024-10-02 17:10 UTC, DefaultMihail commented
На выходных только смогу глянуть, если ещё будет актуально(если не замёрджат) и если ещё нужно

2024-10-02 17:11 UTC, Anorak2024 commented
> На выходных только смогу глянуть, если ещё будет актуально(если не замёрджат) и если ещё нужно

Совсем не срочно и замержат не скоро.

2024-10-07 20:17 UTC, closed without merging