bugfix: detective's access to the shuttle
ss220-space/Paradise pull request #5936
Opened 2024-09-23 18:05 UTC by syndicatecat

## Описание

Позволяет детективу открывать шлюзы к шаттлу в отбытии и шлюзы отсека службы безопасности на шаттле

## Ссылка на предложение/Причина создания ПР

bugfix

2024-09-24 18:56 UTC, Daeberdir requested changes
По пути `_maps\map_files\shuttles\...` стоит всем файлам с `emergency_`  в начале провести аналогичные изменения.

2024-09-26 19:25 UTC, zuhariii commented
> По пути `_maps\map_files\shuttles\...` стоит всем файлам с `emergency_` в начале провести аналогичные изменения.

готово

2024-09-26 23:57 UTC, Daeberdir approved these changes
Туда должен иметь доступ как детектив, так и бригмед.

2024-09-27 05:33 UTC, NightDawnFox approved these changes

2024-09-27 05:37 UTC, merged