add: Add surgery sounds
ss220-space/Paradise pull request #5937
Opened 2024-09-23 22:08 UTC by chomasuke

## Описание
Добавил звуки для хирургических операций.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1281883093078376489

## Демонстрация изменений

https://github.com/user-attachments/assets/e34e0cf0-4269-40ff-8a6b-63c5c767b488

## Тесты
Запускал локалочку, слушал. С модификаторами на скорость проведения операций звучит тоже нормально.
Запускал две локалочки. Через стены не слышно, звук затихает с расстоянием.

2024-09-26 14:05 UTC, chomasuke commented
![photo_2024-09-26_17-04-03](https://github.com/user-attachments/assets/4a609da6-566c-45e6-9cee-8d447f62bed4)

2024-09-27 14:17 UTC, chomasuke commented
![image_2024-09-27_06-52-41](https://github.com/user-attachments/assets/7435c889-e01a-4e71-8c0f-ca296a33f6cf)

2024-09-27 15:26 UTC, Den109G requested changes

2024-09-27 15:26 UTC, Den109G commented on code/modules/surgery/encased.dm
> +		TOOL_SAW				= 'sound/surgery/saw1.ogg',
Удали все эти табы между равно у всех переменных.
```suggestion
		TOOL_SAW = 'sound/surgery/saw1.ogg',
```

2024-09-27 15:26 UTC, Den109G commented on code/modules/surgery/organs_internal.dm
> +
Удали эти странные пустые строки между переменными.

2024-09-27 17:15 UTC, Daeberdir commented on code/modules/surgery/surgery.dm
> +
```suggestion
/datum/surgery_step/proc/play_begin_sound(mob/living/user, mob/living/carbon/human/target, obj/item/tool)
	if(!begin_sound)
		return

	var/sound_file_use
	if(islist(begin_sound))
		for(var/typepath in begin_sound)
			if(istype(tool, typepath) || tool.tool_behaviour == typepath)
				sound_file_use = begin_sound[typepath]
				break
	else
		sound_file_use = begin_sound

	playsound(target, sound_file_use, 75, TRUE, falloff_exponent = 9, falloff_distance = 1, ignore_walls = FALSE)


```
Пропуски между блоками ифов и форов можно использовать для улучшения читабельности.

2024-09-27 17:15 UTC, Daeberdir commented on code/modules/surgery/surgery.dm
> +	var/fail_sound
В автодоке стоит уточнить, что оно может быть листом. И то, что в листе важна последовательность, так как там хранятся и пути, и `tool_behavior`.

2024-09-27 17:15 UTC, Daeberdir commented on code/modules/surgery/encased.dm
> +		/obj/item/wirecutters = 'sound/surgery/scalpel1.ogg',
```suggestion
		TOOL_WIRECUTTER = 'sound/surgery/scalpel1.ogg',
```

2024-09-27 21:39 UTC, Daeberdir approved these changes
Было бы ещё круто использовать ТГшные названия функций и переменных, раз оттуда скопировано. Это увеличило бы совместимость, а значит и стягивание других обновлений.

2024-09-28 17:31 UTC, Den109G approved these changes
По предложке.

2024-09-28 17:38 UTC, merged