add: fake blindfold
ss220-space/Paradise pull request #5943
Opened 2024-09-25 16:25 UTC by Ssheya

## Описание
Добавляет thin blindfold
Выглядит как обычная повязка на глаза, НО является чистой косметикой: не отключает вампирский глеер, не закрывает обзор, ничего не делает, просто круто выглядит

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1288211086511706162

## Тесты
Никак, верю своим навыкам делать ctrl+c ctrl+v :catrose:

2024-09-25 16:27 UTC, Ssheya commented
почему у него както чтото делается в файлах которые не менял....

2024-09-25 16:28 UTC, Ssheya commented
во, кайф

2024-09-25 16:32 UTC, Pelmenik123 commented
Переделывай, уложись в 1 строку

2024-09-25 16:45 UTC, Den109G requested changes

2024-09-25 16:45 UTC, Den109G commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/sunglasses/blindfold/fake
Эта повязка блочит способности вампира/имеет другие механические применения. Не по предложке.

2024-09-25 16:48 UTC, Ssheya commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/sunglasses/blindfold/fake
> Эта повязка блочит способности вампира. Не по предложке.

ладно на выходных или завтра чекну, пока кину драфт :pizdec:

2024-09-25 17:09 UTC, Pelmenik123 commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/sunglasses/blindfold/fake
ден как же ты быстро убил его 10 строчек

2024-09-26 07:50 UTC, Ssheya commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/sunglasses/blindfold/fake
> ден как же ты быстро убил его 10 строчек

XD

2024-09-26 07:56 UTC, Ssheya commented
> Переделывай, уложись в 1 строку

Сам

2024-09-26 09:00 UTC, Den109G approved these changes
По предложке. Всё вроде работает как надо.

2024-09-27 05:32 UTC, NightDawnFox approved these changes

2024-09-27 05:37 UTC, merged