add: Security tactical flashlight
ss220-space/Paradise pull request #5948
Opened 2024-09-26 14:43 UTC by PlayerUnknown14

## Описание
Добавлен "Security tactical flashlight" - тактический фонарик для СБ, надевается в слот уха, можно взять в СБ вендоре.

Показатели идентичны обычному фонарику, способности тенелингов и прочее исправно работают.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1263219513286070324

## Демонстрация изменений

## Тесты
Смотрел спрайты на локалке, юзал на фонарь абилку теней, покупал фонарь в SecTech'е.

2024-09-26 22:02 UTC, Ssheya commented
честно с учётом сколько у нас сб, и что всего один секмат, я бы увеличил их количество, вещь крутая

2024-09-27 00:29 UTC, PlayerUnknown14 commented
> честно с учётом сколько у нас сб, и что всего один секмат, я бы увеличил их количество, вещь крутая

Если под секматом ты имел ввиду автомат с экипировкой СБ, то их в бриге 2. 4 фонаря на отдел - достаточно (так решил Кисик).

2024-09-27 05:29 UTC, NightDawnFox approved these changes, later dismissed

2024-09-27 12:45 UTC, Daeberdir requested changes
Попробуй сделать наложение оверлея а-ля "света" на слое шапки.

2024-09-27 13:10 UTC, NightDawnFox commented
Да зачем, это же с нуля спрайты рисовать, как минимум

2024-09-27 13:23 UTC, PlayerUnknown14 commented
> Попробуй сделать наложение оверлея а-ля "света" на слое шапки.

Для этого спрайты нужно трогать или я что-то не понимаю?

2024-09-27 17:00 UTC, Daeberdir commented
> Да зачем, это же с нуля спрайты рисовать, как минимум

Мне бы не хотелось, как игроку, видеть в раунде исполнение без нормального оверлея света. Если хотите вводить так - то бе меня.

2024-10-16 04:35 UTC, PlayerUnknown14 commented
Ревью бы...

2024-10-16 06:34 UTC, Den109G commented
`change request` реши.

2024-10-16 11:02 UTC, PlayerUnknown14 commented
> `change request` реши.

Скорее всего я туплю, но я не смог найти, как принять/отказаться от изменений. Всё перерыл, нужную кнопку не нашёл.

2024-10-16 17:40 UTC, Den109G commented
Сделай то, что написано в Change Request. Или скажи, почему нельзя такое сделать. Пока это не решено, мы не можем замержить этот ПР.

2024-11-07 04:42 UTC, PlayerUnknown14 commented
> d

Отказано, т.к. Сплит не хочет перерисовывать спрайты, оставляю текущие.

2024-11-11 16:37 UTC, merged