add: Capitalism
ss220-space/Paradise pull request #5958
Opened 2024-09-28 20:29 UTC by Pelmenik123

## Описание

Добавляет зарплаты, изменяет оплату карго и вобще делает все во класс

## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/755125334097133628/1281882574330789959

## Демонстрация изменений

Добавляет новую подсистему капитализма, добавляет доп проки для убоства, все подробно в комментариях

## Тесты

Ну... побегал потыкал заказы повыпонял.

2024-09-28 20:40 UTC, Pelmenik123 commented
Никаких конфликтов, каеф

2024-09-28 20:54 UTC, NightDawnFox commented on code/controllers/subsystem/capitalism.dm
> +#define TEN_THOUSAND_CREDITS 10000 //Хз честно как иначе назвать roflcat
меняй все комментарии на английском. Русские комментарии у нас неприемлемы и являются остатком двух-трехлетней давности. Или ошибками

2024-09-28 20:55 UTC, NightDawnFox commented on code/controllers/subsystem/capitalism.dm
> +	offline_implications = "Выплаты зарплат приостановлены, по идеи выплаты за задания карго не сломаются. Награда за цель не выплачивается. Немедленных действий не требуется."
```suggestion
	offline_implications = "Выплаты зарплат приостановлены, по идее выплаты за задания карго не сломаются. Награда за цель не выплачивается. Немедленных действий не требуется."
```

2024-09-28 20:58 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +#define TEN_THOUSAND_CREDITS 10000 //Хз честно как иначе назвать roflcat
((((((

2024-09-28 21:02 UTC, NightDawnFox commented on code/game/gamemodes/scoreboard.dm
> +	<U>Капитализм статистика</U><br>
название не очень

2024-09-28 21:02 UTC, Den109G requested changes

2024-09-28 21:02 UTC, Den109G commented on code/controllers/subsystem/capitalism.dm
> +	//А зачем я табы сделал....
Тот же вопрос. Почему не пробелы?

2024-09-28 21:02 UTC, Den109G commented on code/controllers/subsystem/capitalism.dm
> +		set_security_level(SEC_LEVEL_EPSILON)
Простите, а где в ТЗ код Эпсилон хотя бы упомянут?

2024-09-28 21:02 UTC, Den109G commented on code/controllers/subsystem/capitalism.dm
> +#define TEN_THOUSAND_CREDITS 10000 //Хз честно как иначе назвать roflcat
Может что-то "`CREDITS_TO_STOP_DEFAUL`"?

2024-09-28 21:02 UTC, Den109G commented on code/controllers/subsystem/capitalism.dm
> +/datum/controller/subsystem/capitalism/proc/default_annonce(var/status)
Зачем мы вообще передаём переменную? Разве нельзя это сделать на `default_status`?
```dm
if(default_status)
   to_chat(world, "Денег малА")
else
   GLOB.priority_announcement.Announce("Всё ок")
```

2024-09-28 21:02 UTC, Den109G commented on code/controllers/subsystem/non-firing/cargo_quests.dm
> +//ДАЛЬШЕ БОГА НЕТ
Комменты прошу на английском.

2024-09-28 21:02 UTC, Den109G commented on code/controllers/subsystem/non-firing/cargo_quests.dm
Зачем нам пробелы между переменными одного квеста? Ко всем изменениям относится.
```suggestion
```

2024-09-28 21:02 UTC, Den109G commented on code/controllers/subsystem/capitalism.dm
> +#define TEN_THOUSAND_CREDITS 10000 //Хз честно как иначе назвать roflcat
А и да. `#undef` если нигде не используется после.

2024-09-28 21:02 UTC, Den109G commented on code/game/jobs/job/job.dm
> +	//legacy_system
If we don't use it - why leave it? Ну и из-за коммента кажется что всё до `//////////` - это остатки прошлого.

2024-09-28 21:02 UTC, Den109G commented on code/modules/economy/Accounts.dm
> +		GLOB.trull_account.owner_name = "Account of the personnel department of the Central Command"
Если это ЦК - так и надо писать. Не на всех картах кораблик является ЦК.
Убери `trull_account` тролля и поставь `CC_account`

2024-09-28 21:02 UTC, Den109G commented on code/modules/economy/Accounts_DB.dm
>  	if(!GLOB.current_date_string)
По хорошему, и это перенести в сабсистему, раз говоришь что выполнил просьбу АА. `date system breaks` если нет этой консоли.

2024-09-28 21:02 UTC, Den109G commented on code/modules/economy/quests/thing_quests.dm
> +//Оставь надежду надежду всяк сюда входящий
Этот комментарий повторяется десять раз. Код выглядит углажено, что не так?

2024-09-28 21:03 UTC, Pelmenik123 commented on code/game/gamemodes/scoreboard.dm
> +	<U>Капитализм статистика</U><br>
Аминь, да будет Статистика финансов

2024-09-28 21:03 UTC, NightDawnFox commented on code/game/jobs/job/engineering.dm
> +	salary = 300
Почему ты ввел дефайн для зарплаты ассистентам, но не сделал то же самое для остальных профессий?

2024-09-28 21:04 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +/datum/controller/subsystem/capitalism/proc/default_annonce(var/status)
Ладно это было решение шизы

2024-09-28 21:04 UTC, Pelmenik123 commented on code/game/jobs/job/job.dm
> +	//legacy_system
Ладно заменю на start_legact end_legacy

2024-09-28 21:05 UTC, Pelmenik123 commented on code/modules/economy/Accounts.dm
> +		GLOB.trull_account.owner_name = "Account of the personnel department of the Central Command"
Это вобще никто не увидит

2024-09-28 21:06 UTC, Pelmenik123 commented on code/modules/economy/quests/thing_quests.dm
> +//Оставь надежду надежду всяк сюда входящий
Я сильно запутался когда хотел полностью поменять выплаты, не осилил, умер

2024-09-28 21:06 UTC, Pelmenik123 commented on code/game/jobs/job/engineering.dm
> +	salary = 300
Просьба от https://discord.com/channels/617003227182792704/734823601110515882/1289658495892717588

2024-09-28 21:07 UTC, Pelmenik123 commented on code/modules/economy/Accounts_DB.dm
>  	if(!GLOB.current_date_string)
Продублирую и в саб систему

2024-09-28 21:07 UTC, Den109G commented on code/game/jobs/job/job.dm
> +	//legacy_system
Зачем вообще оставлять, если не используется? Если используется - это не legacy.

2024-09-28 21:07 UTC, Pelmenik123 commented on code/controllers/subsystem/non-firing/cargo_quests.dm
> +//ДАЛЬШЕ БОГА НЕТ
Рофло коменты оставлю на русском

2024-09-28 21:07 UTC, Den109G commented on code/modules/economy/Accounts.dm
> +		GLOB.trull_account.owner_name = "Account of the personnel department of the Central Command"
Я увидел. Чини.

2024-09-28 21:07 UTC, NightDawnFox commented on code/game/gamemodes/scoreboard.dm
> +	<U>Капитализм статистика</U><br>
Может Финансовая статистка?

2024-09-28 21:08 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +#define TEN_THOUSAND_CREDITS 10000 //Хз честно как иначе назвать roflcat
Не совсем так... 10000 это просто рандомное число с потолка. Заменю на Extra_money

2024-09-28 21:08 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +		set_security_level(SEC_LEVEL_EPSILON)
Нигде, выпадение невозможно

2024-09-28 21:08 UTC, NightDawnFox commented on code/controllers/subsystem/capitalism.dm
> +		set_security_level(SEC_LEVEL_EPSILON)
технически эта часть кода вообще работать не будет из-за того, что по измененному ТЗ деньги берутся из воздуха и дефолта вообще не будет

2024-09-28 21:09 UTC, Den109G commented on code/modules/economy/quests/thing_quests.dm
> +//Оставь надежду надежду всяк сюда входящий
Лучше убрать, раз всё работает как нужно и без костылей.

2024-09-28 21:09 UTC, NightDawnFox commented on code/controllers/subsystem/non-firing/cargo_quests.dm
> +//ДАЛЬШЕ БОГА НЕТ
Нет, не оставишь. Рофлокомменты либо на английский, либо удаляем. За приколы ломаем колени.

2024-09-28 21:16 UTC, Den109G commented on code/controllers/subsystem/capitalism.dm
> +		set_security_level(SEC_LEVEL_EPSILON)
> Нигде, выпадение невозможно

~~А тогда зачем...~~
Закомменть весь связанный код, если он не должен работать.

2024-09-28 22:17 UTC, Pelmenik123 commented
Это немного, но это честная работа

2024-09-29 09:12 UTC, DefaultMihail commented
QA приключение на 5 минут:
1. При зачислении ЗП она не снимается со счёта станции, она идёт с "Account of the personnel department of the Central Command" а не с "NSS Kerberos Station Account"
2. При спауне нет кошелька с наличкой
3. Дефолт не обнаружен, снял все деньги со счёта станции и дождался пополнения ЗП
4. Постоил днк хранилище и получил на инженерах за постройку целое ничего

2024-09-29 10:25 UTC, Pelmenik123 commented
с днк действительно баг, остальное фича

2024-09-29 10:59 UTC, Den109G commented on code/game/jobs/job/job.dm
> +	//legacy_system_end
Я по коду вижу, что эти переменные не используются. Удали.

2024-09-29 11:27 UTC, Pelmenik123 reviewed
Сделал что ден говорил

2024-09-29 11:27 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +	//А зачем я табы сделал....
поправлю

2024-09-29 11:27 UTC, Pelmenik123 commented on code/game/gamemodes/scoreboard.dm
> +	<U>Капитализм статистика</U><br>
Ладно

2024-09-29 11:27 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +		set_security_level(SEC_LEVEL_EPSILON)
Берутся из воздуха на время тестов

2024-09-29 11:27 UTC, Pelmenik123 commented on code/game/jobs/job/job.dm
> +	//legacy_system
Я не хотел искать используется это где то или нет
Поэтому оставил чтобы не было ошибок

2024-09-29 11:27 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +		set_security_level(SEC_LEVEL_EPSILON)
ну блина(((((

2024-09-29 11:27 UTC, Pelmenik123 commented on code/controllers/subsystem/non-firing/cargo_quests.dm
хотел выделить типо какое важное значение БАУНТИ

2024-09-29 11:35 UTC, FanTik-Ratge commented
Срать вечно 🐀🤙

2024-09-29 11:50 UTC, Den109G commented on code/modules/economy/quests/_base_quests.dm
> +	var/linked_deportament = "Cargo" 	//Указывается ключ депортамента чтобы брать его из глобального списка, нет я не сделаю загрузку в new, боюсь чет сломать
Полиция словаря. Нет депорта.
```suggestion
	var/linked_departament = "Cargo" 	//Указывается ключ депортамента чтобы брать его из глобального списка, нет я не сделаю загрузку в new, боюсь чет сломать
```

2024-09-29 12:27 UTC, Den109G commented on code/controllers/subsystem/capitalism.dm
> +			if(payment_account.charge(account.linked_job.salary, account, "Выплата зарплаты персоналу.", "Nanotrasen personal deportament" , payment_account.owner_name, payment_account.owner_name , payment_ac
Deportment - личность. Department - отдел.
```suggestion
			if(payment_account.charge(account.linked_job.salary, account, "Выплата зарплаты персоналу.", "Nanotrasen personal departament" , payment_account.owner_name, payment_account.owner_name , payment_account.owner_name))
```

2024-09-29 12:27 UTC, Den109G commented on code/controllers/subsystem/capitalism.dm
> +/datum/controller/subsystem/capitalism/proc/smart_deportament_payment(var/list/keys_deportament, var/money)
```suggestion
/datum/controller/subsystem/capitalism/proc/smart_departament_payment(var/list/keys_departament, var/money)
```

2024-09-29 12:27 UTC, Den109G commented on code/modules/economy/quests/centcomm_departaments.dm
> +	var/list/linked_deportaments = list() //HEHE HI HA
```suggestion
	var/list/linked_departaments = list() //HEHE HI HA
```

2024-09-29 12:39 UTC, DefaultMihail commented on code/controllers/subsystem/capitalism.dm
> +		if(goal.check_completion() && !(goal in complited_goals))
Ты проверяшь тут ВЫПОЛНЕНИЕ цели, а не её постройку. На примере того же ДНК, он ставит check_completion, только когда днк заполнено.

2024-09-29 12:52 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +		if(goal.check_completion() && !(goal in complited_goals))
пупупу, тогда прийдется отдельный прок писать, пусть будет фича

2024-09-29 12:57 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +		if(goal.check_completion() && !(goal in complited_goals))
фича

2024-09-29 12:58 UTC, Pelmenik123 commented
Жду апрув день 1

2024-09-29 14:04 UTC, Vladisvell commented on code/controllers/subsystem/capitalism.dm
> +				return FALSE
зачем

так

много

пустых строк

2024-09-29 14:05 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +				return FALSE
я художник я так вижу

2024-09-29 14:07 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +				return FALSE
привычка разбивать так на "блоки кода"

2024-09-29 14:07 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +				return FALSE
+ так легче находить и каши не будет

2024-09-29 14:37 UTC, FanTik-Ratge commented
Спрайты не в стиле парадиза 🐀👑

2024-09-29 14:40 UTC, Pelmenik123 commented
фантик это френдли фаер, ты себе в колено выстрелил

2024-09-29 14:42 UTC, Pelmenik123 commented
Ден умоляю, дай мне этот апрув. Мержани его на мейны сразу

2024-09-29 16:02 UTC, Pelmenik123 commented
гооол

2024-09-30 09:27 UTC, Den109G commented on code/controllers/subsystem/capitalism.dm
> +	//А зачем я табы сделал....
Не поправил.

2024-09-30 09:31 UTC, Den109G commented on code/modules/economy/quests/quest_console.dm
> +//Abandon hope, everyone who enters here
Не вижу смысла в комментарии. Особенно раз ничего в нём не менял.
```suggestion
```

2024-09-30 09:32 UTC, Den109G commented on code/modules/shuttle/supply.dm
> +						SScapitalism.base_account.credit(7000, "Благодарность за вклад в науку.", "Nanotreisen Institute terminal#[rand(111,333)]", "Nanotreisen Institute")
```suggestion
						SScapitalism.base_account.credit(7000, "Благодарность за вклад в науку.", "Nanotrasen Institute terminal#[rand(111,333)]", "Nanotrasen Institute")
```

2024-09-30 14:30 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +	//А зачем я табы сделал....
врешь не уйдешь, правил это

2024-10-01 17:43 UTC, Den109G submitted a review, later dismissed
Всё по ТЗ. Вопросы решены. Автор ПРа, перестань писать каждый час об этом.

2024-10-01 18:31 UTC, Pelmenik123 commented
:catrose:

2024-10-01 19:51 UTC, Den109G commented on code/game/objects/items/weapons/cash.dm
> +/obj/item/stack/spacecash/magic_linked/New(loc, amt = 150)
Нет причин это в `/New` делать.
```suggestion
/obj/item/stack/spacecash/magic_linked/Initialize(mapload, new_amount, merge = TRUE))
```

2024-10-01 19:52 UTC, Pelmenik123 commented on code/game/objects/items/weapons/cash.dm
> +/obj/item/stack/spacecash/magic_linked/New(loc, amt = 150)
я копирывал это с USSP кредит

2024-10-01 20:03 UTC, Pelmenik123 commented
Готово

2024-10-01 20:38 UTC, Pelmenik123 commented
Протестил все работает

2024-10-02 06:44 UTC, ROdenFL commented on code/controllers/subsystem/capitalism.dm
> +	offline_implications = "Выплаты зарплат приостановлены, по идее выплаты за задания карго не сломаются. Награда за цель не выплачивается. Немедленных действий не требуется."
Сидят мужик и читают, что по идее не сломается 😊

2024-10-02 12:35 UTC, Pelmenik123 commented on code/controllers/subsystem/capitalism.dm
> +	offline_implications = "Выплаты зарплат приостановлены, по идее выплаты за задания карго не сломаются. Награда за цель не выплачивается. Немедленных действий не требуется."
ну если сабсистему не удалит то не сломается

2024-10-05 12:53 UTC, merged