add: RD doll
ss220-space/Paradise pull request #5963
Opened 2024-09-30 15:44 UTC by lolybomb

## Описание

Добавляем новую игрушку в игру и лодаут
## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/755125334097133628/1290312210131980339
## Демонстрация изменений

![image](https://github.com/user-attachments/assets/63f035b7-2b6e-4d0f-bf30-32314ea87b75)

2024-09-30 18:50 UTC, Daeberdir requested changes

2024-09-30 18:50 UTC, Daeberdir commented on code/game/objects/items/toys.dm
> +	used += 1
Лучше ткнуть это под проверку на то, что эта пременная меньше сотни, чтобы оно не дёргало число, когда это уже не нужно.
`used += 1` замени на просто `used++`
Плюс назвать её более логически. "Усталость" может?

2024-09-30 18:50 UTC, Daeberdir commented on code/game/objects/items/toys.dm
> +		"Я будто на слаймовой батарейке!Ха!","Обожааааю слаймов!Блеп!",
```suggestion
		"Я будто на слаймовой батарейке! Ха!","Обожа-а-а-аю слаймов! Блеп!",
```

2024-09-30 18:50 UTC, Daeberdir commented on code/game/objects/items/toys.dm
> +		desc = "Это уставшая кукла РД."
Тут мы вызываем `update_appearance()` с `UPDATE_DESC|UPDATE_ICON_STATE`, а саму смену иконки и описания записываем в вызываемые этим проки `update_desc()` и `update_icon_state()`.

2024-09-30 18:50 UTC, Daeberdir commented on code/game/objects/items/toys.dm
> +		var/angrytext = pick("Твой мозг стоило бы поместить в машину...", "Пиздец, дела хуевей некуда..",
```suggestion
		var/angrytext = pick("Твой мозг стоило бы поместить в машину...", "Чёрт, дела хуже некуда...",
```
Без лишней вульгарности. Мы же культурные люди.

2024-09-30 18:50 UTC, Daeberdir commented on code/game/objects/items/toys.dm
> +		"Толпятся перед стойкой как насекомые...", "Мне нужно добавить лишь один закон чтобы все закончилось..",
```suggestion
		"Толпятся перед стойкой, будто насекомые...", "Мне нужно добавить лишь один закон, чтобы все закончилось...",
```

2024-09-30 18:50 UTC, Daeberdir commented on code/game/objects/items/toys.dm
> +		"Полигон не единственное место куда можно отправить бомбу...", "Выдави из себя что-то кроме УВЫ, ничтожество...")
```suggestion
		"Полигон не единственное место, куда можно отправить бомбу...", "Выдави из себя что-то кроме \"УВЫ\", ничтожество...")
```
Стоит выделить нетспик из остальной речи.

2024-09-30 18:50 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_plushie.dm
> +	display_name = "Это обычная кукла РД"
```suggestion
	display_name = "RD doll"
```

2024-09-30 19:49 UTC, Daeberdir commented on code/game/objects/items/toys.dm
> +
```suggestion
/obj/item/toy/plushie/rdplushie/attack_self(mob/user)
	. = ..()

	if(. || !COOLDOWN_FINISHED(src, cooldown))
		return .

	var/message
	if(tired < 100)
		tired++
		playsound(user, 'sound/items/greetings-emote.ogg', 30, TRUE)
		message = pick("Слава науке!", "Сделаем пару роботов?!",
		"Я будто на слаймовой батарейке! Ха!","Обожааааю слаймов! Блеп!",
		"Я запрограммировала роботов звать меня мамой!", "Знаешь анекдот про ядро ИИ, смазку и гуся?")

	else
		update_appearance(UPDATE_DESC|UPDATE_ICON_STATE)
		playsound(user, 'sound/items/shyness-emote.ogg', 30, TRUE)
		message = pick("Твой мозг стоило бы поместить в машину...", "Чёрт, дела хуже некуда...",
		"Толпятся перед стойкой, будто насекомые...", "Мне нужно добавить лишь один закон, чтобы все закончилось..",
		"Ты думаешь, что умный, пользователь. Но ты предсказуем. Я знаю каждый твой шаг еще до того, как ты о нем подумаешь.",
		"Полигон не единственное место куда можно отправить бомбу...", "Выдави из себя что-то кроме \"УВЫ\", ничтожество...")

	user.visible_message(span_notice(message))
	COOLDOWN_START(src, cooldown, 3 SECONDS)

```
Теперь для красоты. После блоков ифа, фора, вайл и прочей дряни стоит сделать строчку-пропуск, это улучшает читабельность. Ниже проделай аналогично.

2024-09-30 20:16 UTC, Daeberdir approved these changes
Допустим.

2024-10-01 12:49 UTC, NightDawnFox approved these changes

2024-10-01 12:56 UTC, merged