QOL: Перевод sleeping carp
ss220-space/Paradise pull request #5967
Opened 2024-10-01 17:42 UTC by pilygun

## Описание

Ну короче взяли просроченную предложку на откат карпа и откатили вместе с переводом.
Не круто, не красиво. На мои замечания забили хуй.
Так что я перевел карп обратно, ибо у нового карпа проблема с ТТСом из за инглиша.
Добавил чутка от себя смешнявок в переводе.
Описание комбух карпа взял с вики, их писал Ден так что все вопросы к нему :achE: 
Ну а все остальное по старому капру.

## Ссылка на предложение/Причина создания ПР

Квалити оф квалити

## Тесты

Мало времени было, не протестировал

2024-10-01 17:46 UTC, Den109G requested changes
Переводы должны проходить оповещение-переводов.

2024-10-01 18:08 UTC, pilygun commented
> Переводы должны проходить оповещение-переводов.

Никаких ограничений по времени в оповещениях перевода не вижу. Так что могу сказать что прошло 
![image](https://github.com/user-attachments/assets/14659bea-8fab-4bbe-830d-be921443966f)

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +	explaination_text = "Пинает оппонента в спину, заставляя его лежать от боли."
🤣 Лежим от боли.

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +						  "<span class='userdanger'>[user] ударяет вас в спину, заставляя споткнуться и упасть!</span>")
Спаны перепиши на дефайны.

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +	explaination_text = "Вы прыгаете на оппонента локтём ударяя по спине. Нанося приличный урон, и если враг в критическом состоянии - мгновенно убиваете его."
```suggestion
	explaination_text = "Вы прыгаете на лежачего оппонента, ударяя локтем по спине. Наносит приличный урон и мгновенно убивает жертву, если она находится в критическом состоянии."
```

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +			user.say(pick("БАНЗАЙ!", "КИЯЯЯЯ!", "Я ХОЧУ ПИЦЦЫ!", "ТЫ МЕНЯ НЕ УВИДИШЬ!", "МОЕ ВРЕМЯ СЕЙЧАС!", "КОВАБАНГА!"))
Нет, не хочешь пиццы.
Ты не видишь меня.
Сейчас моё время.
Кавабанга.
![image](https://github.com/user-attachments/assets/97a1ed09-b61a-4dfd-ad0e-61f048bca25d)

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/combos/sleeping_carp/head_kick.dm
> +	explaination_text = "Пинает оппонента в голову, нанося приличный урон и заставляя выбросить вещь из активной руки."
```suggestion
	explaination_text = "Пинает оппонента в голову, нанося ему приличный урон и заставляя его выбросить вещь из активной руки."
```

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/combos/sleeping_carp/stomach_knee.dm
> +	explaination_text = "Заводит ваше колено в живот оппонента, заставляя его лежать от боли и неровно дышать"
Точку в конец. Лежим от боли. "Вы пинаете оппонента по животу".

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/combos/sleeping_carp/wrist_wrench.dm
> +	explaination_text = "Сворачивает запястье оппоненту, заставляя выбросить вещь из активной руки."
```suggestion
	explaination_text = "Сворачивает запястье оппоненту, заставляя его выбросить вещь из активной руки."
```

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/combos/sleeping_carp/wrist_wrench.dm
> +			user.say(pick("КРУТИМ ЗАПЯТЬЕ!", "ВЕДИ СЕБЯ КАК МУЖЧИНА СОСУНОК!", "НЕ ПОЗОРЬСЯ!", "ВУХАХАХА!", "И ГДЕ ТВОЙ СТАНБАТОН?", "НЕ НАДО ДЯДЯ!"))
Надо.

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/martial.dm
> +			to_chat(user, "<span class ='warning'>Жажда крови отвлекает вас слишком сильно, чтобы вы могли сосредоточиться на содержимом свитка!</span>")
```suggestion
			to_chat(user, span_warning("Ваши мысли полностью окутаны жаждой крови, вы не в состоянии сосредоточиться на содержимом свитка!"))
```
Или типо того.

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/martial.dm
> +		to_chat(user, span_warning("Вы понимаете, что узнали все из Учения Карпа и решили не читать этот свиток."))
```suggestion
		to_chat(user, span_warning("Вы понимаете, что узнали всё из Учения Карпа и его дальнейшее изучение бессмысленно."))
```

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/martial.dm
> +	to_chat(user, "<span class='sciradio'>Вы изучили древнее боевое искусство Спящего карпа! \
Спящего Карпа

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/sleeping_carp.dm
> +	no_guns_message = "Будь как карп. Карпы не стреляют из пушек. CARP!"
Не стоит убирать смысловую часть о клане Карпа и чести.

2024-10-01 20:31 UTC, Daeberdir commented on code/modules/martial_arts/sleeping_carp.dm
> +		A.say(pick("КУАХ!", "ХАЙЯ!", "КУОХ!", "ХУ!", "КИЯ!", "ХУХ!", "БУЙЯ!", "ХЛЫСТ ПРАВНИКА!", "УДАР КАРПА!"))
Хлыст плавника?

2024-10-05 07:37 UTC, PiotrTheTchaikowsky commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +			user.say(pick("БАНЗАЙ!", "КИЯЯЯЯ!", "Я ХОЧУ ПИЦЦЫ!", "ТЫ МЕНЯ НЕ УВИДИШЬ!", "МОЕ ВРЕМЯ СЕЙЧАС!", "КОВАБАНГА!"))
кавабунга

2024-10-29 19:07 UTC, pilygun commented
Не забыл доделаю чуть поже

2024-10-31 15:07 UTC, pilygun commented on code/modules/martial_arts/combos/sleeping_carp/wrist_wrench.dm
> +			user.say(pick("КРУТИМ ЗАПЯТЬЕ!", "ВЕДИ СЕБЯ КАК МУЖЧИНА СОСУНОК!", "НЕ ПОЗОРЬСЯ!", "ВУХАХАХА!", "И ГДЕ ТВОЙ СТАНБАТОН?", "НЕ НАДО ДЯДЯ!"))
Бля это отсылка на папича, за нее порвать готов

2024-10-31 15:07 UTC, pilygun commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +			user.say(pick("БАНЗАЙ!", "КИЯЯЯЯ!", "Я ХОЧУ ПИЦЦЫ!", "ТЫ МЕНЯ НЕ УВИДИШЬ!", "МОЕ ВРЕМЯ СЕЙЧАС!", "КОВАБАНГА!"))
Мое время сейчас это отсылка на американского рестлера, а я хочу пиццы старый мем, который был в старом карпе

2024-10-31 15:07 UTC, pilygun commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +						  "<span class='userdanger'>[user] ударяет вас в спину, заставляя споткнуться и упасть!</span>")
каво?

2024-10-31 15:43 UTC, Daeberdir commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +						  "<span class='userdanger'>[user] ударяет вас в спину, заставляя споткнуться и упасть!</span>")
```suggestion
		target.visible_message(span_warning("[user] пинает [target] в спину!"), \
						  span_userdanger("[user] ударяет вас в спину, заставляя споткнуться и упасть!"))
```

2024-11-15 13:16 UTC, pilygun commented
@Daeberdir @Vladisvell

2024-11-15 15:24 UTC, Den109G commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +		target.visible_message(span_warning("[user] пинает [target] в спину!"), \
`genderize_ru()` использовать?

2024-11-16 04:17 UTC, pilygun commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +		target.visible_message(span_warning("[user] пинает [target] в спину!"), \
надо надо
щя поправим

2024-12-30 21:01 UTC, pilygun commented
![ваня](https://github.com/user-attachments/assets/c1689f05-f77d-4357-bfe6-82925ae89ee7)

2024-12-30 21:01 UTC, closed without merging