add: welder sword
ss220-space/Paradise pull request #5976
Opened 2024-10-04 15:05 UTC by dageavtobusnick

## Описание
Добавляет аналог есворда и даблы в виде welder sword.
welder sword
одноручное
урон в активном состоянии 30 ожогов
в неактивном 3 брута
запас топлива 50
блок 50
техи: combat=3;magnets=4;plasmatech=5
double-bladed welding sword
двуручное при активации
урон в активном состоянии 40 ожогов
в неактивном 5 брута
запас топлива 70
блок 75
техи: combat=5;magnets=5;plasmatech=6;
не отражает лазеры
Оба меча тратят единицу топлива при ударе, а так же тратят его со временем во включенном состоянии. Заправляются от фуелтанка, как сварка.
При объединении 2-x одноручных мечей получается двухклинковый вариант.
Спрайты предоставил: @radio_aktivny_chel

## Ссылка на предложение/Причина создания ПР
Щитспавн оружие. Предлога не нужна.

## Демонстрация изменений
![1](https://github.com/user-attachments/assets/18119241-213e-4140-9cff-15b9482a11e6)
![2](https://github.com/user-attachments/assets/8feff6e3-3c87-406c-9a92-82c1897bfbea)
![3](https://github.com/user-attachments/assets/dd87854e-1f1e-401e-85a4-d3ca9f6aed82)

## Тесты
Запустил. Выдал себе несколько мечей. И двойной и одинарный вариант работают, как задумано. Работа сварок и фуелтанка из-за правок не сломалась.

2024-10-04 18:57 UTC, Den109G commented on code/modules/reagents/reagent_dispenser.dm
> +	if(damage_type == BURN && damage_amount > 0)
А как это связано с мечом?

2024-10-04 19:44 UTC, dageavtobusnick commented on code/modules/reagents/reagent_dispenser.dm
> +	if(damage_type == BURN && damage_amount > 0)
Меч не может подрывать фуелтанки(потому что если сделать так, что может, он начнет исполнять функции сварки, чего быть не должно), при том, что он буквально переделанная сварка из-за того, что подрыв происходит либо через снаряд, либо через welder_act. Тут я сделал менее костыльный способ, чем welder_act, и подрыв вызывается любым берн уроном, что логично, ибо он взрывоопасен.
Об этом изменении написано в описании ПР-а.

2024-10-05 07:35 UTC, PiotrTheTchaikowsky commented
Жаль что никто никогда не увидит это оружие из за щитспавна и боязни админов двигаться

2024-10-05 08:01 UTC, dageavtobusnick commented
> Жаль что никто никогда не увидит это оружие из за щитспавна и боязни админов двигаться

Увы.

2024-10-05 11:40 UTC, Den109G commented on code/modules/reagents/reagent_dispenser.dm
> +	if(damage_type == BURN && damage_amount > 0)
Да вижу что об этом написано. На изменение поведения фуелтанка лучше писать отдельно предложку. Если просто нужно чтобы фуелтанк бабахал от меча - надо писать это исключение в attackby .

2024-10-05 15:39 UTC, dageavtobusnick commented on code/modules/reagents/reagent_dispenser.dm
> +	if(damage_type == BURN && damage_amount > 0)
Заменил на attackby.

2024-12-31 13:59 UTC, dageavtobusnick commented
@BeebBeebBoob Можно ревью или мерж этого несчастного ПР-а? С начала октября висит без каких-либо замечаний.

2025-01-01 10:14 UTC, PlayerUnknown14 requested changes
Буквы подредачить.

2025-01-01 10:14 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, span_notice("[src] is out of fuel!"))
```suggestion
		balloon_alert(user, "нет топлива!")
```

2025-01-01 10:14 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, span_notice("You switch on [src]."))
```suggestion
		balloon_alert(user, "включено")
```

2025-01-01 10:14 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, span_notice("You switch off [src]."))
```suggestion
		balloon_alert(user, "выключено")
```

2025-01-01 10:14 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/cigs.dm
> +			light(span_notice("[user] casually lights the [name] with [I], what a badass."))
```suggestion
			light(span_notice("[user] непринуждённо зажига[pluralize_ru(user, "ет", "ют")] [declent_ru(ACCUSATIVE)] с помощью [I.declent_ru(GENITIVE)]. Чёрт, как же он[genderize_ru(user.gender, "", "а", "о", "и")] крут[genderize_ru(user.gender, "", "а", "о", "ы")]."))
```

2025-01-01 10:14 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/welder_sword.dm
> +	desc = "Аналог энергетического меча, изготовленный из сварки неизвестным мастером из Грейтайда. Он имеет аналогичные характеристики, но наносит ожоги вместо травм в активном состоянии. Во время атак
```suggestion
	desc = "Сварочный аппарат, кустарно модифицированный каким-то умельцем. Судя по всему, автор этого творения черпал вдохновение от энергетических мечей."
	ru_names = list(
		NOMINATIVE = "сварочный меч",
		GENITIVE = "сварочного меча",
		DATIVE = "сварочному мечу",
		ACCUSATIVE = "сварочный меч",
		INSTRUMENTAL = "сварочным мечом",
		PREPOSITIONAL = "сварочном мече"
	)
```
OOC информация в описании предмета - кринге.

2025-01-01 10:14 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/welder_sword.dm
> +			to_chat(user, span_warning("You try to attach the end of sword to... itself. You're not very smart, are you?"))
```suggestion
			to_chat(user, span_warning("Вы пытаетесь приделать конец меча к... мечу. Это было очень глупо."))
```

2025-01-01 10:14 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/welder_sword.dm
> +		to_chat(user,  span_notice("You attach the ends of the two welder swords, making a single double-bladed weapon! You're cool."))
```suggestion
		balloon_alert(user, "скреплено вместе")
```

2025-01-01 10:14 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/welder_sword.dm
> +	desc = "Оружие, полученное путем объединения двух мечей из сварки в один. В отличие от двухклинкового энергетического меча, не способен отражать лазеры. Во время атаки расходует сварочное топливо."
```suggestion
	desc = "Оружие, полученное путем объединения двух мечей из сварки в один. В отличие от двухклинкового энергетического меча, не способен отражать лазеры. Во время атаки расходует сварочное топливо."
	desc = "Два кустарно модифицированных сварочных аппарата, скреплённых вместе, образуя некое подобие двойного энергетического меча. Настоящее чудо ассистентской мысли."
	ru_names = list(
		NOMINATIVE = "двойной сварочный меч",
		GENITIVE = "двойного сварочного меча",
		DATIVE = "двойному сварочному мечу",
		ACCUSATIVE = "двойной сварочный меч",
		INSTRUMENTAL = "двойным сварочным мечом",
		PREPOSITIONAL = "двойном сварочном мече"
	)
```

2025-01-01 11:00 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/welder_sword.dm
>  	desc = "Оружие, полученное путем объединения двух мечей из сварки в один. В отличие от двухклинкового энергетического меча, не способен отражать лазеры. Во время атаки расходует сварочное топливо."
2 описания, верхнее удали.

2025-01-01 11:07 UTC, PlayerUnknown14 approved these changes
Буквы нраица.

2025-01-01 18:13 UTC, BeebBeebBoob approved these changes

2025-01-02 09:38 UTC, merged