Цифорки
ss220-space/Paradise pull request #5984
Opened 2024-10-05 20:25 UTC by FlitchTime

## Описание
Изменение награды за заказы с реагентами для карго

## Ссылка на предложение/Причина создания ПР
Предложка:
https://discord.com/channels/617003227182792704/755125334097133628/1286740723617759262
Док с ценами:
https://docs.google.com/document/d/1u5AwtpZN5tOhRdX5BPms1WPAlrLVWi-Osnp8uW-zC9U/edit?usp=sharing

## Демонстрация изменений
![image](https://github.com/user-attachments/assets/5cb419a3-eefd-4f82-8469-c797bdb649e7)

## Тесты
Покрутил заказы карго на локалке, всё было окей

2024-10-05 20:38 UTC, Den109G requested changes

2024-10-05 20:38 UTC, Den109G commented on code/modules/economy/quests/reagents_quests.dm
> +			// Чисто с ботаники
Комменты перепиши на английский.

2024-10-05 22:50 UTC, FlitchTime commented on code/modules/economy/quests/reagents_quests.dm
> +			// Чисто с ботаники
Уж не знаю зачем, но ладно. Заодно вспомнил про перетасовку списков

2024-10-06 00:28 UTC, Daeberdir commented on code/modules/economy/quests/reagents_quests.dm
> +			"fliptonium" = list("volume" = 10, "reward" = 450),
![image](https://github.com/user-attachments/assets/bb7f0852-36ee-4b9c-ac9c-627d7654e5d9)

2024-10-06 09:44 UTC, FlitchTime commented on code/modules/economy/quests/reagents_quests.dm
> +			"fliptonium" = list("volume" = 10, "reward" = 450),
Поправил

2024-10-06 17:21 UTC, Den109G approved these changes
Выглядит нормально.

2024-10-07 06:06 UTC, Daeberdir approved these changes

2024-10-07 06:11 UTC, merged