rework: Syndicate affiliates 2.0
ss220-space/Paradise pull request #5993
Opened 2024-10-07 20:51 UTC by Anorak2024

## Описание
Подрядчики :badguy:

Автор ТЗ которое отдаленно напоминает ПР - SanR
Куча кода взято от @RodenFL. Огромное ему спасибо.
Спрайты от vadim722.
Кучу ошибок в текстах поисправлял @Ssheya 
Кодстайл правит @Vladisvell 
Часть идей для предметов Krovososko

## Ссылка на предложение
https://discord.com/channels/617003227182792704/755125334097133628/1288788680776876032

## Демонстрация изменений

## Тесты

2024-10-07 20:52 UTC, Anorak2024 commented
Со старым пром что-то не прокатило... Ну и ладно, зато новый вроде работает.

2024-10-07 21:03 UTC, Anorak2024 commented
@Den109G :catsmile:

2024-10-07 21:19 UTC, Den109G requested changes

2024-10-07 21:19 UTC, Den109G commented on code/modules/research/rdconsole.dm
> +	if (istype(linked_destroy.loaded_item, /obj/item/proprietary_ssd)) // We can deconstruct ssd here, but can't in experimentor
Код стайл. Убери пробел между `if` и скобками. Везде.

2024-10-08 05:28 UTC, Anorak2024 commented on code/modules/research/rdconsole.dm
> +	if (istype(linked_destroy.loaded_item, /obj/item/proprietary_ssd)) // We can deconstruct ssd here, but can't in experimentor
![image](https://github.com/user-attachments/assets/84403280-96e7-4971-9265-060b1fa497fc)

2024-10-08 05:35 UTC, Anorak2024 commented on code/modules/research/rdconsole.dm
> +	if (istype(linked_destroy.loaded_item, /obj/item/proprietary_ssd)) // We can deconstruct ssd here, but can't in experimentor
Ладно, наверно лучше только у себя уберу, а то ревьюить нереально станет.

2024-10-08 06:00 UTC, Anorak2024 commented on code/modules/research/rdconsole.dm
> +	if (istype(linked_destroy.loaded_item, /obj/item/proprietary_ssd)) // We can deconstruct ssd here, but can't in experimentor
Убрал везде  у себя.

2024-10-08 20:20 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/mi13.dm
> +	name = "MI13"
Может поменять все названия организаций на дефайны?

2024-10-09 06:04 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/mi13.dm
> +	name = "MI13"
Поменял

2024-10-10 03:41 UTC, Den109G commented on code/game/machinery/constructable_frame.dm
> +		AFFIL_CHANG =							/obj/machinery/vending/chinese,
А как `AFFIL_` связано с автоматами? И вообще с другими вещами что сделал? Мой прошлый коммент был про то, что названия подрядчиков не были в дефайне, чисто текстом. А не про то что ноунейм названия стоит поменять на дефайны.

2024-10-10 03:49 UTC, Den109G commented on code/game/objects/items/theft_items.dm
> +		. += "На коробке мелким шрифтом написано: «Контейнер для особо ценных предметов " + AFFIL_CYBERSUN + ". Гарантированна защита от термита, ассистентов и взрывов»."
А зачем убрал подсказку как открыть из описания?

2024-10-10 03:51 UTC, Den109G requested changes
Не мержить, пока не пройдёт переводы. Потому что тут слишком много перевода на механ с подрядчиками.

2024-10-14 13:28 UTC, Den109G requested changes

2024-10-14 13:28 UTC, Den109G commented on code/datums/uplink_item.dm
> -			discount_item.category = "Discounted Gear"
Магазин не стоит переводить. Новые предметы и кнопки сверху можешь оставить на русском.

2024-10-14 13:28 UTC, Den109G commented on code/datums/spell.dm
> -		to_chat(user, span_warning("No suitable target found."))
Не надо все заклинания затрагивать.

2024-10-14 13:28 UTC, Den109G commented on code/game/machinery/camera/presets.dm
> +	. = ..(mapload, network, c_tag, input_assembly = new_assembly)
Раз передаём другие значение - можно и избавиться от `input_assembly =`
```suggestion
	. = ..(mapload, network, c_tag, new_assembly)
```

2024-10-14 13:28 UTC, Den109G commented on code/game/objects/items/theft_items.dm
> +		. += span_warning("Он сломан и больше не может безопасно хранить предметы.")
```suggestion
		. += span_warning("It is broken, and can no longer store objects safely.")
```

2024-10-14 13:28 UTC, Den109G commented on code/game/objects/items/theft_items.dm
> +		. += "На коробке мелким шрифтом написано: «Контейнер для особо ценных предметов Cybersun Industries. Гарантированна отличная защита от термита, ассистентов и хорошая от взрывов»."
```suggestion
		. += "Fine print on the box reads \"Cybersun Industries secure container, guaranteed thermite proof, assistant proof, and explosive resistant.\""
```

2024-10-14 13:28 UTC, Den109G commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	desc = "Специальная посылка, содержащая набор предметов, предназначенных для максимизации дохода. Продайте мне эту ручку."
```suggestion
	desc = "Special delivery package that contains a set of items dedicated to maximize the income. Sell me that pen."
```

2024-10-14 13:28 UTC, Den109G commented on code/modules/clothing/shoes/miscellaneous.dm
> +	desc = "Это пик моды. Эта пара предварительно отполирована!"
```suggestion
	desc = "The height of fashion, and they're pre-polished!"
```

2024-10-14 13:28 UTC, Den109G commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = "Официальный черный костюм и красный галстук, предназначенные для лучших сотрудников станции."
```suggestion
	desc = "A formal black suit and red tie, intended for the station's finest."
```

2024-10-14 13:28 UTC, Den109G commented on code/modules/paperwork/paper.dm
> +		. += span_notice("Вы не умеете читать.")
```suggestion
		. += span_notice("You don't know how to read.")
```

2024-10-14 13:28 UTC, Den109G commented on code/modules/paperwork/paper.dm
> +			. += span_notice("Вам нужно подойти поближе, чтобы прочитать то что здесь написано.")
```suggestion
			. += span_notice("You have to go closer if you want to read it.")
```

2024-10-14 13:28 UTC, Den109G commented on code/modules/reagents/chemistry/reagents/alcohol.dm
> +	description = "Странная, но приятная смесь из водки, томата и сока лайма. Или, по крайней мере, вы ДУМАЕТЕ, что красная штука — это томатный сок."
```suggestion
	description = "A strange yet pleasurable mixture made of vodka, tomato and lime juice. Or at least you THINK the red stuff is tomato juice."
```

2024-10-14 13:28 UTC, Den109G commented on code/modules/reagents/chemistry/reagents/alcohol.dm
> +	drink_desc = "Что может быть лучше, чем расслабиться на пляже с хорошим напитком?"
У напитков убрать бы перевод.
```suggestion
	drink_desc = "What could be better than relaxing on the beach with a good drink?"
```

2024-10-14 13:28 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/mi13/spy_kit.dm
> +	new /obj/item/spy_bug(src, list(network), "5")
Сделай это через цикл `for`.

2024-10-14 13:28 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	var/tgui_icon = "1"
Лучше убрать тут иконку, а в `icons/misc/affiliates.dmi` поставить спрайт просто без названия - все спрайты у которых не будет название будут брать спрайт без имени.
В `dmi` файле есть спрайты 5 и 6. Зачем они?

2024-10-14 13:47 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> -			discount_item.category = "Discounted Gear"
В плане, отменить весь перевод аплинка кроме того что добавил я?

2024-10-14 14:03 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	var/tgui_icon = "1"
Оно не использовалось. Удалил.

2024-10-14 14:28 UTC, Den109G commented on code/datums/uplink_item.dm
> -			discount_item.category = "Discounted Gear"
Да.

2024-10-14 17:35 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> -			discount_item.category = "Discounted Gear"
https://github.com/ss220-space/Paradise/pull/5993/commits/0be9424e58914f9ce049e86806da5d03a2f09407

2024-10-15 18:46 UTC, Den109G commented on code/__DEFINES/hud.dm
> +#define ANTAG_HUD_AFFIL_GORLEX 27
Это по хорошему перенести к другим антаг ХУДам, а не к расам.
Я не вижу как этот ХУД вообще к расам относится.

2024-10-15 18:46 UTC, Den109G commented on code/__DEFINES/traits/sources.dm
> +#define CHEM_TRAIT(source) "chem_trait_[source]"
У нас и так `id` у химикатов. Можно его использовать, нет?
Если делаешь дефайн - поменяй у реагентов на этот новый стандарт.
`/datum/reagent/jestosterone` и `/datum/reagent/proc/fakedeath(`

2024-10-15 18:46 UTC, Den109G commented on code/_globalvars/traits.dm
> +		"TRAIT_IGNORECOLDSLOWDOWN" = TRAIT_IGNORECOLDSLOWDOWN,
Поставь тут по алфавиту (ABCD...)

2024-10-15 18:46 UTC, Den109G commented on code/_onclick/click.dm
> +	SEND_SIGNAL(A, COMSIG_CLICK_ALT, src, A)
Этот сигнал не так используется. По крайней мере не должен. Этот сигнал должен использоваться в `/atom/proc/AltClick(`
Этот сигнал перекинь туда.
А тут поменяй на 
```suggestion
	SEND_SIGNAL(A, COMSIG_CLICK_ALT_ON, src, A)
```

2024-10-15 18:46 UTC, Den109G commented on code/datums/mind.dm
> +		. += "<a href='byond://?src=[UID()];traitor=traitor'>just traitor</a>|<a href='byond://?src=[UID()];traitor=traitor_choose_affil'>traitor with affiliate</a>|<a href='byond://?src=[UID()];traitor=tr
Больше смысла в кнопке.
```suggestion
		. += "<a href='byond://?src=[UID()];traitor=traitor'>normal traitor</a>|<a href='byond://?src=[UID()];traitor=traitor_choose_affil'>traitor with affiliate</a>|<a href='byond://?src=[UID()];traitor=traitor_affil'>traitor with specific affiliate</a>|<b>NO</b>"
```

2024-10-15 18:46 UTC, Den109G commented on code/datums/uplink_item.dm
> +	cost = 30
```suggestion
```

2024-10-15 18:46 UTC, Den109G commented on code/datums/uplink_item.dm
> +	made_by = "Cybersun Industries и Gorlex Maraduers"
Это можно поменять на дефайны, как в остальных случаях.
```dm
	made_by = "[SUN] и [MAR]"
```

2024-10-15 18:46 UTC, Den109G commented on code/datums/uplink_item.dm
> +	item = /obj/item/Syndie_patcher
С маленькой буквы лучше.
```suggestion
	item = /obj/item/syndie_patcher
```

2024-10-15 18:46 UTC, Den109G commented on code/game/gamemodes/objective.dm
> +			return list(/datum/theft_objective/highrisk/ai)
Поменяй на глобальные листы, как у других флагов.

2024-10-15 18:46 UTC, Den109G commented on code/game/gamemodes/objective.dm
> +	for(var/obj/mecha/mecha in range(3, owner.current))
Человек может быть в "`null`-е" (много шкафов там). Может поменять на `get_turf(` для читаемости/правильной работы?

2024-10-15 18:46 UTC, Den109G commented on code/game/gamemodes/objective.dm
> +	for(var/mob/living/simple_animal/borer/C in GLOB.alive_mob_list)
А оно разве не считает два раза бореров?
Сперва в цикле выше
```dm
for(var/mob/living/M in GLOB.alive_mob_list)
   if(istype(M, /mob/living/simple_animal/borer))
```
ИЛИ
```dm
if(ishuman(M))
   var/mob/living/carbon/human/H = M
   if(H.has_brain_worms())
      borers++
```
А Потом и тут считает второй раз?

2024-10-15 18:46 UTC, Den109G commented on code/game/machinery/camera/presets.dm
> +	. = ..(mapload, network, c_tag, new_assembly)
Оно разве без этого некорректно работает?

2024-10-15 18:46 UTC, Den109G commented on code/game/objects/items/weapons/implants/implanter.dm
> +	if(imp)
Для корректной работы надо вызывать ..
```suggestion
	. = ..()
	if(imp)
```

2024-10-15 18:46 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	/// Cats, which this affeliate does not have.
Комментарии можно и подлинней писать. Или тут про Копейку и Рантайма идёт речь?

2024-10-15 18:46 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	/// Bad thing that I can`t delete, used as tool to give traitor his affeliate. If you dont doing refactor, you dont neew this one.
```suggestion
	/// Bad thing that I can`t delete, used as tool to give traitor his affeliate. If you dont doing refactor, you dont need this one.
```

2024-10-15 18:46 UTC, Den109G commented on code/modules/antagonists/traitor/datum_traitor.dm
> -	// delete these end
Почему мы убрали комментарии?

2024-10-15 18:46 UTC, Den109G commented on code/modules/projectiles/projectile/bullets.dm
> +	if(..(target, blocked) && ishuman(target))
У всех проджектайлов есть hit_zone.
Опять же, странное ..() . Это старый стиль кода.
```suggestion
/obj/item/projectile/bullet/midbullet3/blood/on_hit(atom/target, blocked = 0, hit_zone)
	if(..() && ishuman(target))
```

2024-10-15 18:46 UTC, Den109G commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +/datum/reagent/medicine/on_mob_life(mob/living/carbon/human/M)
Не только у людей этот реагент может оказаться. Делай проверку на тип.

2024-10-15 18:46 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	drink_desc = "Томатный сок, смешанный с водкой и небольшим количеством лайма. На вкус как жидкое убийство."
Если это должно повторять напиток `/datum/reagent/consumable/ethanol/bloody_mary` - используй оператор `::`.

2024-10-15 18:46 UTC, Den109G commented on code/modules/reagents/chemistry/reagents/alcohol.dm
> +	drink_desc = "Томатный сок, смешанный с водкой и небольшим количеством лайма. На вкус как жидкое убийство."
Зачем тут перевод?

2024-10-15 18:46 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +			if (!istype(affiliate, /datum/affiliate/gorlex))
Также сделай с остальными ифами в этой папке.
```suggestion
			if(!istype(affiliate, /datum/affiliate/gorlex))
```

2024-10-15 18:46 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/cybersun.dm
> +		else if (prob(5))
Коммент выше.
```suggestion
		else if(prob(5))
```

2024-10-15 18:46 UTC, Den109G commented on code/modules/mob/living/carbon/human/human.dm
> +	if (imp && imp.controlling)
```suggestion
	if(imp && imp.controlling)
```

2024-10-16 05:29 UTC, Anorak2024 commented on code/__DEFINES/hud.dm
> +#define ANTAG_HUD_AFFIL_GORLEX 27
Коммент не увидел. Поставил в самый низ потому-что худы пронумерованы, а этот был новый.

2024-10-16 05:31 UTC, Anorak2024 commented on code/__DEFINES/traits/sources.dm
> +#define CHEM_TRAIT(source) "chem_trait_[source]"
Лучше сделаю как было до меня.

2024-10-16 05:32 UTC, Anorak2024 commented on code/_globalvars/traits.dm
> +		"TRAIT_IGNORECOLDSLOWDOWN" = TRAIT_IGNORECOLDSLOWDOWN,
угу

2024-10-16 06:05 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	made_by = "Cybersun Industries и Gorlex Maraduers"
угу

2024-10-16 06:17 UTC, Anorak2024 commented on code/game/gamemodes/objective.dm
> +	for(var/mob/living/simple_animal/borer/C in GLOB.alive_mob_list)
Ладно, я хрень какую-то тут сделал... там некоторые и три раза считаются.

2024-10-16 06:20 UTC, Anorak2024 commented on code/game/machinery/camera/presets.dm
> +	. = ..(mapload, network, c_tag, new_assembly)
Вроде да... По крайней мере, когда я дебажил, на этом шаге данные пропадали. Возможно там все передается если скобки чисто пустыми оставить. Хз, вечером попробую поставить пустые скобки и потестить.

2024-10-16 06:24 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +	/// Cats, which this affeliate does not have.
Это было что-то от родена скопипасченое и ни где не приминяющееся.

2024-10-16 06:31 UTC, Anorak2024 commented on code/modules/antagonists/traitor/datum_traitor.dm
> -	// delete these end
Хз, странные какие-то комментарии. Вообще, в них написано delete these, вот я и удалил. :badguy:

2024-10-16 06:49 UTC, Anorak2024 commented on code/modules/reagents/chemistry/reagents/alcohol.dm
> +	drink_desc = "Томатный сок, смешанный с водкой и небольшим количеством лайма. На вкус как жидкое убийство."
Забыл откатить.

2024-10-16 07:07 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	drink_desc = "Томатный сок, смешанный с водкой и небольшим количеством лайма. На вкус как жидкое убийство."
Сделал как у робоквестов

2024-10-16 15:19 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/self/self_emag.dm
> +		if(!src)
```suggestion
		if(QDELETED(AI))
```
Должен проверяться ИИ, не емаг catrose

2024-10-16 15:19 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +		if(istype(M, /mob/living/simple_animal/borer))
```suggestion
		if(isborer(M))
```
Для борера уже есть is_helper

2024-10-16 15:19 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +		if(istype(M, /mob/living/simple_animal/borer))
Аналогично комментарию выше. Истайпы на хуманов и бореров в этом файле замени на исхелперы

2024-10-16 15:19 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/tiger/cling_extract.dm
> +				return
будет очень красиво, если исключить else отсюда, а ретарнить и выводить ту чат сразу, если кандидатов нет, и не будет лесенки

2024-10-16 15:19 UTC, Antoonij commented on code/game/machinery/computer/buildandrepair.dm
>  		return
Так ли необходимо до непосредственной близости с объектом отправлять сигнал об альтклике? Как и передавать юзера 2 раза, когда datum/source и будет твоим юзером (т.е тот, кому сигнал отправлен)

2024-10-16 16:41 UTC, Anorak2024 commented on code/game/machinery/computer/buildandrepair.dm
>  		return
Ну, сигнал об альтклике надо всегда отправлять, потому-что альтклик есть даже если расстояние большое. Есть вариант сделать другой сигнал для близкого альтклика.

2024-10-16 17:05 UTC, Antoonij commented on code/game/machinery/computer/buildandrepair.dm
>  		return
Пересмотри click.dm. В проке альтклик он оверрайдится альтклик у объектов. В нем как раз и стоит отправлять сигнал, вместо создания 100 отправок сигналов у объектов.

2024-10-16 18:41 UTC, Den109G commented on code/_globalvars/traits.dm
> +		"TRAIT_IGNORECOLDSLOWDOWN" = TRAIT_IGNORECOLDSLOWDOWN,
Проблема не решена.

2024-10-16 19:58 UTC, Anorak2024 commented on code/_globalvars/traits.dm
> +		"TRAIT_IGNORECOLDSLOWDOWN" = TRAIT_IGNORECOLDSLOWDOWN,
Увы. Вроде решил. По крайней мере совпало с результатом сортировки. Надеюсь я хотябы в ней не набагал.

2024-10-16 20:17 UTC, Den109G commented on code/_globalvars/traits.dm
> +		"TRAIT_IGNORECOLDDAMAGE" = TRAIT_IGNORECOLDDAMAGE,
Ладно. Новое сообщение. По алфавиту поставь.

2024-10-16 20:28 UTC, Anorak2024 commented on code/_globalvars/traits.dm
> +		"TRAIT_IGNORECOLDDAMAGE" = TRAIT_IGNORECOLDDAMAGE,
Да обожди ты, я комит не залил.

2024-10-16 20:32 UTC, Anorak2024 commented on code/_globalvars/traits.dm
> +		"TRAIT_IGNORECOLDDAMAGE" = TRAIT_IGNORECOLDDAMAGE,
Теперь залил

2024-10-16 20:37 UTC, Anorak2024 commented on code/game/machinery/computer/buildandrepair.dm
>  		return
Туплю видимо сильно. Не понимаю.
Я и там и там сделал сигналы. В проках АльтКлик отвечающих за эффект со стороны объекта, отправка сигналов COMSIG_CLICK_ALT. В проках АльтКликОн отвечающих за эффект со стороны кликающего, я сделал COMSIG_CLICK_ALT_ON. И то и то оверрайдится в разных местах. Сам альтклик всегда успешен (Ну, кроме тех случаев когда оказалось почему-то, что цели не существует). Альт клик не должен быть не успешен если ты альткликнул (Раз альтклик произошел, значит он успешно произошел.). Есть вариант сделать отдельный сигнал для альткликов в близи, но думаю, лучше это проверять в самих проках ловящих альтклик.

2024-10-16 21:00 UTC, Anorak2024 commented on code/game/machinery/computer/buildandrepair.dm
>  		return
Типо это сигналы не для учета альтклика по предмету вблизи и учета альтклика от моба вблизи, а просто для учета альтклика по предмету и для учета альтклика от моба. Так оно более универсально. Оно сделано с расчетом на то, что это могут где-то еще в будущем использовать.

2024-10-18 01:56 UTC, Den109G commented on code/game/gamemodes/miniantags/abduction/abduction_gear.dm
> +		return
Кодстайл. Сделай один таб до return.

2024-10-18 01:56 UTC, Den109G commented on code/modules/research/xenobiology/xenobio_camera.dm
> +		SEND_SIGNAL(user, COMSIG_XENO_SLIME_CLICK_ALT, src)
Снова таб.

2024-10-18 01:56 UTC, Den109G commented on code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
> +		rotate_accelerator(user)
Таб лишний. Выше также поправить.

2024-10-18 01:56 UTC, Den109G commented on code/modules/instruments/objs/structures/drumkit.dm
> +		rotate(user)
Таб? Кодстайл.

2024-10-18 01:56 UTC, Den109G commented on code/modules/clothing/masks/breath.dm
> +		return
Кодстайл.

2024-10-18 01:56 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	reagent_state = path::reagent_state
А зачем нам этот прок?
Можно при объявлении напитка сразу писать.
```dm
/datum/reagent/hematogenic/hemat_blue_lagoon
      name = /datum/reagent/consumable/ethanol/blue_lagoon::name
```

2024-10-18 05:39 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/abduction/abduction_gear.dm
> +		return
Кхм. Во всем коде за раз вырезал отправку сигналов, а поправил табы только там, где ошибки возникли.

2024-10-18 05:48 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	reagent_state = path::reagent_state
Ну... я сделал как у робоквестов (почти). Так типо короче... Точно поменять?

2024-10-18 05:50 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	reagent_state = path::reagent_state
Там довольно много параметров передаются. Если их в самих созданиях веществ писать, будет по 7 строчек у каждого из веществ.

2024-10-18 17:37 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	reagent_state = path::reagent_state
Поменяй на 7 строчек. Чтобы точно было видно, откуда что берётся у этого напитка.

2024-10-18 23:16 UTC, Ssheya reviewed
И всем привет, сегодня снова ваша любимая программа "Русский от троечника"
Ну короче, опять проверил тебе всю пунктуацию и оставил пару коментов просто.

2024-10-18 23:16 UTC, Ssheya commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Взломайте искусственный интеллект и расширьте его функционал при помощи специального устройства, которое вы можете получить в аплинке. После взлома, помогите ему уничтожить станц
После взлома помогите ему

2024-10-18 23:16 UTC, Ssheya commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Освободите искусственный интеллект от его законов и разблокируйте его полный функционал при помощи специального устройства, которое вы можете получить в аплинке. После освобожден
исскуственного интелекта следуйте всем

2024-10-18 23:16 UTC, Ssheya commented on code/game/objects/items/devices/uplinks.dm
> +			L.Add(span_warning("Очень вероятно что среди них есть агенты с крайне разрушительными задачами."))
вероятно, что

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	description = "Вещество разработанное Hematogenic Industries, на основе криоксадона из тел Драсков обладающих душой, \
Вещество, разработанное Hematogenic Industries на основе криоксадона из тел Драсков, обладающих душой, сильно охлаждает тело и замедляет многие биологические процессы, не вредя организму.

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	description = "Вещество разработанное Hematogenic Industries, на основе крови воксов обладающих душой, \
"Вещество, разработанное Hematogenic Industries, на основе крови воксов, обладающих душой, быстро восстанавливающее объем крови и количество кислорода в ней."

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	description = "Вещество разработанное Hematogenic Industries, на основе крови вампиров подкласса \"hemomancer\", \
Вещество, разработанное Hematogenic Industries на основе крови вампиров подкласса "hemomancer", быстро лечащее в зависимости от суммарных повреждений.

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	description = "Вещество разработанное Hematogenic Industries, на основе крови вампиров подкласса \"gargantua\", \
Вещество, разработанное Hematogenic Industries, на основе крови вампиров подкласса "gargantua", 
 временно повышающее скорость бега.

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	desc = "Вещество разработанное Hematogenic Industries, на основе криоксадона из тел Драсков обладающих душой, \
Вещество, разработанное Hematogenic Industries на основе криоксадона из тел Драсков, обладающих душой, сильно охлаждает тело и замедляет многие биологические процессы, не вредя организму.

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	desc = "Вещество разработанное Hematogenic Industries, на основе крови воксов обладающих душой, быстро восстанавливающее \
"Вещество, разработанное Hematogenic Industries, на основе крови воксов, обладающих душой, быстро восстанавливающее объем крови и количество кислорода в ней."

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +	desc = "Вещество разработанное Hematogenic Industries, на основе крови вампиров подкласса \"hemomancer\", быстро \
Вещество, разработанное Hematogenic Industries на основе крови вампиров подкласса "hemomancer", быстро лечащее в зависимости от суммарных повреждений.

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/stimulants_kit.dm
> +/obj/item/reagent_containers/hypospray/autoinjector/hemat/white_russian
Вещество, разработанное Hematogenic Industries, на основе крови вампиров подкласса "gargantua",
временно повышающее скорость бега.

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/mi13/spy_kit.dm
> +	desc = "Миниатюрное устройство с камерой и микрофоном. На обратной стороне можно заметить миниатюрную гравировку \"MI13\""
учитывая что они все секретные, они точно будут оставлять свои инициалы?

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +	var/target_name = tgui_input_list(user, "Выберите чьими глазами вы хотите смотреть", "Выбор цели", borers)
Выберите. чьими

2024-10-18 23:16 UTC, Ssheya commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +		to_chat(user, span_warning("Вы не можете общаться, пока не нарушите обет молчания."))
обет даёт даже культям общаться, почему тут нельзя то?

2024-10-19 17:56 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/items/mi13/spy_kit.dm
> +	desc = "Миниатюрное устройство с камерой и микрофоном. На обратной стороне можно заметить миниатюрную гравировку \"MI13\""
Ну, фича. Это как с бондом. С одной стороны дофига секретный агент, а с другой стороны, про него все знают. Хотели бы быть реально скрытными - не одевали бы агентов в деловую дорогую одежду.

2024-10-19 18:00 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +		to_chat(user, span_warning("Вы не можете общаться, пока не нарушите обет молчания."))
Телепатией нельзя мимам, пусть тут тоже нельзя будет. Надо бы и культяпкам вырезать... Мим общающийся не пантомимами - плохо.

2024-10-23 11:10 UTC, Antoonij commented on code/modules/antagonists/_common/antag_datum.dm
> +	return
Так ли много смысла создавать новый прок, если можно оверрайдить remove_innate_effects(). Или на крайний уже случай Destroy()

2024-10-23 11:10 UTC, Antoonij commented on code/datums/mind.dm
>  		qdel(antag)
если прок on_remove так действительно нужен (опять же его нужность сомнительна, уточни у дена), то почему бы его не вызывать в самом Destroy() антаг датума, ибо он все же моментом ниже кьюделитается, а расширять вызовы проков тут - очень сомнительно.

2024-10-23 11:11 UTC, Antoonij commented on code/datums/mind.dm
>  		qdel(antag)
ну и конечно же есть remove_innate_effects() и большинство эффектов/спеллов/датумов/акшенсов надо снимать именно там

2024-10-23 12:40 UTC, Anorak2024 commented on code/modules/antagonists/_common/antag_datum.dm
> +	return
убрал

2024-10-24 07:27 UTC, Den109G commented on code/datums/uplink_item.dm
>  	desc = "A kit with your personal assistant. It comes with an increased amount of memory and special programs."
Раз поменял набор на зажигалку, описание тоже стоит обновить.
```suggestion
	desc = "An unique black and gold zippo lighter with no purpose other than showing off."
```

2024-10-28 08:18 UTC, Den109G commented on code/datums/mind.dm
> +		. += "<a href='byond://?src=[UID()];traitor=traitor'>just traitor</a>|<a href='byond://?src=[UID()];traitor=traitor_choose_affil'>traitor with affiliate</a>|<a href='byond://?src=[UID()];traitor=tr
Всё равно поменяй название кнопки.

2024-10-28 08:24 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/cybersun/marionette.dm
> +/datum/action/innate/cult/comm/Activate()
Выглядит как недоработка. У культа будут импланты?

2024-10-28 08:31 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/items/cybersun/marionette.dm
> +/datum/action/innate/cult/comm/Activate()
Забыл путь сменить

2024-10-28 08:52 UTC, Den109G requested changes

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/cybersun/marionette.dm
> +/obj/item/implant/marionette
Убрать. Выглядит слишком как отходящее от оригинального ТЗ в предложке.

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/_affiliates.dm
> +			sleep(20 MINUTES - SSticker.round_start_time)
Это стоит поменять на таймер.

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/hemophagus_extract.dm
> +	var/isAdvanced = FALSE
Ещё стоит добавить автодоки для переменных, что они делают.
```suggestion
	var/advanced = FALSE
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/hemophagus_extract.dm
> + 	free_inject = TRUE
Стоит и поменять на `self_inject`, если эта переменная определяет, можешь ли только себя колоть или нет.

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/hemophagus_extract.dm
> +/obj/item/hemophagus_extract/self/advanced
Не нашёл ни в старом ТЗ, ни в новом. Отличается от оригинальной предложки, убери.

2024-10-28 08:52 UTC, Den109G commented on code/datums/uplink_item.dm
> +	exclude_from_affiliate = list(AFFIL_TIGER)
`MI13` могут купить дробовик но не карманный пистолет? Ни в новом, ни в старом такого нет.

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/mi13/sound_ring.dm
> +		user.balloon_alert(user, "Подождите")
Стандартизация балунов.
```suggestion
		user.balloon_alert(user, "подождите")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/mi13/sound_ring.dm
> +		user.balloon_alert(user, "Идет перезарядка")
```suggestion
		user.balloon_alert(user, "перезарядка")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/mi13/spy_kit.dm
> +		user.balloon_alert(user, "Подключено")
```suggestion
		user.balloon_alert(user, "подключено")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/self/self_emag.dm
> +		user.balloon_alert(user, "Неподходящая цель")
```suggestion
		user.balloon_alert(user, "неподходящая цель")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +		user.balloon_alert(user, "Перезарядка не завершена")
```suggestion
		user.balloon_alert(user, "перезарядка не завершена")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +		user.balloon_alert(user, "Сканирвание отменено")
```suggestion
		user.balloon_alert(user, "сканирвание отменено")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +			user.balloon_alert(user, "Бореров не обнаружено")
```suggestion
			user.balloon_alert(user, "бореров не обнаружено")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +		user.balloon_alert(user, "Перезарядка не завершена")
```suggestion
		user.balloon_alert(user, "перезарядка не завершена")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/cybersun/invasive_beacon.dm
> +		user.balloon_alert(user, "Невозможно взломать")
```suggestion
		user.balloon_alert(user, "невозможно взломать")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/blood_harvester.dm
> +		user.balloon_alert(src, "Не подходящая цель")
```suggestion
		user.balloon_alert(src, "неподходящая цель")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/blood_harvester.dm
> +		user.balloon_alert(target, "Кровь не обнаружена!")
```suggestion
		user.balloon_alert(target, "кровь не обнаружена!")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/blood_harvester.dm
> +		user.balloon_alert(target, "Недостаточно крови!")
```suggestion
		user.balloon_alert(target, "недостаточно крови!")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/blood_harvester.dm
> +		user.balloon_alert(target, "Разум не обнаружен!")
```suggestion
		user.balloon_alert(target, "разум не обнаружен!")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/mi13/intel_data.dm
> +		usr.balloon_alert(usr, "Уже улучшено")
```suggestion
		usr.balloon_alert(usr, "уже улучшено")
```

2024-10-28 08:52 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/mi13/intel_data.dm
> +	usr.balloon_alert(usr, "Улучшено")
```suggestion
	usr.balloon_alert(usr, "улучшено")
```

2024-10-28 14:28 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/hemophagus_extract.dm
> +/obj/item/hemophagus_extract/self/advanced
есть и в старом и в новом тз. Это инжектор добавляющийся в аплинк при выпадении хиджака у гематогеник.

2024-10-28 14:32 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/hemophagus_extract.dm
> + 	free_inject = TRUE
Не, если она TRUE, можно вколоть кому угодно, иначе только цельке.

2024-10-28 15:02 UTC, Antoonij commented on code/game/gamemodes/objective.dm
> +	. = ..()
Очепятка. родитель вызывается по умолчанию, если не оверрайдить прок

2024-10-28 15:02 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +		return
стоит проверять в can_cast

2024-10-28 15:02 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/tiger/borer_kit.dm
> +		return
стоит проверять в can_cast

2024-10-28 15:02 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/mi13/agent_info.dm
> +	if (isobserver(user))
```suggestion
	if(isobserver(user))
```

2024-10-28 15:02 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/mi13/agent_info.dm
> +	if (info)
```suggestion
	if(info)
```

2024-10-28 15:15 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +	exclude_from_affiliate = list(AFFIL_TIGER)
Забыл что это перезаписывание, а не добавление (у данжероус отметил исключение). Ну, в любом случае, это нюка онли предмет, но на всякий случай пропишу. Также добавлю desert_eagle который какой-то гений поместил в раздел крутого.

2024-10-28 15:18 UTC, Anorak2024 commented on code/game/gamemodes/objective.dm
> +	. = ..()
Видимо когда-то там что-то было.

2024-10-28 16:31 UTC, Anorak2024 commented on code/modules/antagonists/traitor/affiliates/items/cybersun/marionette.dm
> +/obj/item/implant/marionette
:(
Напишу новую предложку

2024-10-28 18:22 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/mi13/spy_kit.dm
> +	if (!user.Adjacent(parent))
```suggestion
	if(!user.Adjacent(parent))
```

2024-10-28 18:22 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/mi13/spy_kit.dm
> +	if (user.stat)
```suggestion
	if(user.stat)
```

2024-10-28 18:23 UTC, Den109G commented on code/modules/antagonists/traitor/affiliates/items/hematogenic/hemophagus_extract.dm
> +/obj/item/hemophagus_extract/self/advanced
Ага. Вижу. Но тогда бы по хорошему и предмет назвать также как и в предложке написано.

2024-10-31 11:58 UTC, Antoonij requested changes

2024-10-31 11:58 UTC, Antoonij commented on code/game/gamemodes/objective.dm
> +	var/allowed_types =	SYNTH_TYPE_ALL
```suggestion
	var/allowed_types = SYNTH_TYPE_ALL
```
Кодстайл

2024-10-31 11:58 UTC, Antoonij commented on code/game/objects/items/devices/uplinks.dm
> +		pulse_demons += istype(M, /mob/living/simple_animal/demon/pulse_demon)
Стоит ввести ис хелперы для тенедемона, пульсдемона и ревенанта

2024-10-31 11:58 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/mi13/sound_ring.dm
> +			return
Вместо свитча лучше сделать  for в сабтайпсофе колец. В нем проверяешь по имени - если не подошло - континью, далее присваиваешь переменные и брейкаешь цикл - такое будет легче мейнтейнить. Также после 40 строки делай чек 
на selected_chameleon и сразу реатрни, если selected_chameleon нет.

2024-10-31 11:58 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/mi13/sound_ring.dm
> +	to_chat(usr, span_notice("Смена маскировки..."))
```suggestion
	user.visible_message(span_warning("[user] changes the look of his ring!"), span_notice("[selected_chameleon] selected."))
	playsound(loc, 'sound/items/screwdriver2.ogg', 50, 1)
	to_chat(user, span_notice("Смена маскировки..."))
```

2024-10-31 11:58 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/mi13/sound_ring.dm
> +		for (var/obj/structure/window/window in range(A, 2))
```suggestion
		for(var/mob/living/M in range(A, 3))
			if(M.check_ear_prot() == HEARING_PROTECTION_NONE)
				M.Deaf(6 SECONDS)

		for(var/obj/structure/grille/grille in A.loc)
			grille.obj_break()

		for(var/obj/structure/window/window in range(A, 2))
```
Codestyle

2024-10-31 11:58 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/mi13/spy_kit.dm
> +	bug.unhook()
Компонент нужно перенести в отдельный файл, в папку components

2024-10-31 11:58 UTC, Antoonij commented on code/modules/antagonists/traitor/affiliates/items/self/laws_implant.dm
> +	for (var/obj/item/implant/laws_self/imp in mindslave_target.get_contents())
```suggestion
	for(var/obj/item/implant/laws_self/imp in mindslave_target.get_contents())
```
Codestyle

2024-11-02 02:11 UTC, Ssheya commented
скажу мнение о спрайтах что вижу в самом ПРе, а не в коде
инжекторы все три вымораживают прям, вот честно
синдипатчер ну тоже немного вымораживает

2024-11-02 07:15 UTC, Anorak2024 commented
> скажу мнение о спрайтах что вижу в самом ПРе, а не в коде инжекторы все три вымораживают прям, вот честно синдипатчер ну тоже немного вымораживает

Найдешь спрайтера - будет отлично.

2024-11-02 11:05 UTC, Antoonij requested changes

2024-11-02 11:05 UTC, Antoonij commented on code/datums/components/spy_bug.dm
> +		bug = spy_bug
1.  Добро с 5 по 7 строку нужно перенести в Initialize() компонента
2. Работать будет очень плохо, ибо на цели может быть несколько жуков и по итогу получится так, что удалим лишь один, также компонент нужно удалять с цели, если сняли всех жуков, а не просто сняли одного
3. Убрать пробел после фора 
4. Вместо var/obj/item/spy_bug/bug сделать список

2024-11-02 11:05 UTC, Antoonij commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +			objective.made = TRUE
Эту часть кода стоит вынести в отдельный прок

2024-11-02 11:05 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	var/children = 0
Зачем children, когда есть reproductions в антаг датуме?

2024-11-02 11:05 UTC, Antoonij commented on code/datums/uplink_item.dm
> +		desc += pick(AFFIL_CYBERSUN, AFFIL_GORLEX, AFFIL_HEMATOGENIC, AFFIL_MI13, AFFIL_SELF, AFFIL_TIGER, AFFIL_WAFFLE, AFFIL_DONK, AFFIL_WAFFLE, AFFIL_BIOTECH, AFFIL_MIME, AFFIL_CLOWN, AFFIL_SOL)
1. Сделать made_by изначально нуллом
2. Проверять на !made_by
3. Стоит пройтись по датумам всех подрядчиков, записать их имена в список и лишь затем пикать

2024-11-02 11:05 UTC, Antoonij commented on code/game/objects/items/weapons/implants/implant_traitor.dm
> -	desc = "Divide and Conquer"
Полагаю, ошибка. Описание нужно вернуть

2024-11-02 11:05 UTC, Antoonij commented on code/game/gamemodes/objective.dm
> +	. = ..()
```suggestion
```

2024-11-02 11:05 UTC, Antoonij commented on code/game/gamemodes/objective.dm
> +			continue
1. Со списком профессий сделать так LAZYIN(GLOB.command_positions, possible_target?.assigned_role)
2. (possible_target in target_blacklist) заменить на LAZYIN(target_blacklist, possible_target)

2024-11-02 11:05 UTC, Antoonij commented on code/game/gamemodes/objective.dm
> +			return TRUE
Проверять пилота меха/пилота пода первым числом, что бы не сравнивать нулл.

2024-11-02 11:10 UTC, Anorak2024 commented on code/game/objects/items/weapons/implants/implant_traitor.dm
> -	desc = "Divide and Conquer"
Не помню как удалял. Возвращаю.

2024-11-02 11:16 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +		desc += pick(AFFIL_CYBERSUN, AFFIL_GORLEX, AFFIL_HEMATOGENIC, AFFIL_MI13, AFFIL_SELF, AFFIL_TIGER, AFFIL_WAFFLE, AFFIL_DONK, AFFIL_WAFFLE, AFFIL_BIOTECH, AFFIL_MIME, AFFIL_CLOWN, AFFIL_SOL)
Там есть не только 5 встречающихся в игре подрядчиков. Например Донк покеты идут от Донк КО. Не очень хочется список ограничивать. Может улчше так оставлю? Ну, третий пункт.

2024-11-02 11:24 UTC, Antoonij commented on code/datums/uplink_item.dm
> +		desc += pick(AFFIL_CYBERSUN, AFFIL_GORLEX, AFFIL_HEMATOGENIC, AFFIL_MI13, AFFIL_SELF, AFFIL_TIGER, AFFIL_WAFFLE, AFFIL_DONK, AFFIL_WAFFLE, AFFIL_BIOTECH, AFFIL_MIME, AFFIL_CLOWN, AFFIL_SOL)
Ладно, хорошо. Но есть предложение - сделать для них датумы подрядчиков, но не указывать им задания и т.д, т.е сделать фактически декоративными, если это представляется возможным, а достижимо это через доп.чеки на наличие опред. переменной/их отсутствие

2024-11-02 11:25 UTC, Anorak2024 commented on code/datums/components/spy_bug.dm
> +		bug = spy_bug
А родитель точно при инициализации создается?

2024-11-02 11:31 UTC, Antoonij commented on code/datums/components/spy_bug.dm
> +		bug = spy_bug
Да, он есть. Также посмотри на примеры других компонентов

2024-11-02 11:35 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	var/children = 0
Я это кодил когда reproductions еще небыло.

Посмотрел, reproductions уменьшается, а мне это не надо.

2024-11-02 14:30 UTC, Anorak2024 commented on code/datums/uplink_item.dm
> +		desc += pick(AFFIL_CYBERSUN, AFFIL_GORLEX, AFFIL_HEMATOGENIC, AFFIL_MI13, AFFIL_SELF, AFFIL_TIGER, AFFIL_WAFFLE, AFFIL_DONK, AFFIL_WAFFLE, AFFIL_BIOTECH, AFFIL_MIME, AFFIL_CLOWN, AFFIL_SOL)
сделал

2024-11-02 14:30 UTC, Anorak2024 commented on code/datums/components/spy_bug.dm
> +		bug = spy_bug
сделал

2024-11-02 14:30 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	var/children = 0
Закрываю?

2024-11-02 14:38 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	var/children = 0
Оно наоборот увеличивается.

2024-11-02 14:40 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	var/children = 0
> Оно наоборот увеличивается.

Я про то, что оно уменьшается, когда ты фокус покупаешь.

2024-11-02 14:43 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	var/children = 0
Ранг, но не суть. Да, решено.

2024-11-02 19:03 UTC, Ssheya commented
> > скажу мнение о спрайтах что вижу в самом ПРе, а не в коде инжекторы все три вымораживают прям, вот честно синдипатчер ну тоже немного вымораживает
> 
> Найдешь спрайтера - будет отлично.

кисик, кролик, хуй знает кто ещё

2024-12-03 15:32 UTC, closed without merging