Add: Disease - Babylonian Fever
ss220-space/Paradise pull request #5997
Opened 2024-10-08 13:54 UTC by timchigaming

## Описание

### Добавляем НОВЫЙ!! вирус
> Что же делает этот вирус?

1. Заставляет забыть носителя ВСЕ языки на время пока он не вылечится от заразы.
2. Возвращает все языки обратно когда излечивается.
3. Лечится митоколидом + маннитолом

> Но что если кукла изучит новые языки во время работы вируса?

- Он сохранит его в список, очистит список языков куклы и вернёт свежеизученные языки после излечения.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/1256557228807295038/1258174752145539206

## Демонстрация изменений

https://github.com/user-attachments/assets/d3f880f6-2209-438b-ab3f-69421cb90956

## Тесты
Всё работает отлажено, _теперь_.

2024-10-08 14:03 UTC, Den109G commented on code/datums/diseases/viruses/babylon_feve.dm
> +					"Двести... двадцать..."
Проставь `\` на конце строк, чтобы программа понимала, что это всё один лист.
```suggestion
					"Двести... двадцать..."\
```

2024-10-08 14:13 UTC, Den109G commented on code/datums/diseases/viruses/babylon_feve.dm
> +			stored_languages += affected_mob.languages.Copy()
Такая проверка на языки может привести к языкам дубликатам, что засорит чат игрокам.

2024-10-08 14:17 UTC, Den109G approved these changes

2024-10-08 14:17 UTC, Den109G commented on code/datums/diseases/viruses/babylon_feve.dm
> +	affected_mob.languages.Cut()
Это надо поменять на `remove_language`

2024-10-08 14:17 UTC, Den109G commented on code/datums/diseases/viruses/babylon_feve.dm
> +			affected_mob.languages = stored_languages.Copy()
А это - на `add_language`.

2024-10-08 14:18 UTC, Den109G requested changes
Выше оставил замечания, что надо менять.

2024-10-08 14:51 UTC, Den109G commented on code/datums/diseases/viruses/babylon_feve.dm
> +	if(stage == 1 && !stored_languages.len && affected_mob.languages)
Эта проверка особа не нужна. Если она находится вне свитча, потому что болезнь может перейти сразу на вторую стадию, то ставить проверку на первую стадию особо не имеет смысла.

2024-10-08 14:53 UTC, Den109G commented
Как в #5332 написали, проверять каждую **секунду** что у больного появились языки - not good. Лучше поменять на сигналы, чтобы вирус не крашил кадры в секунду у сервера, если заболело 3 человека.

2024-10-08 19:46 UTC, Den109G commented on code/datums/diseases/viruses/babylon_feve.dm
> +/datum/disease/virus/babylonian_fever/cure()
Надо прописать аргументы у прока.
```suggestion
/datum/disease/virus/babylonian_fever/cure((id = type, need_immunity = TRUE))
```

2024-10-08 20:22 UTC, LiquidPotroh commented on code/datums/diseases/viruses/babylon_feve.dm
> +	affected_mob = disease.affected_mob
перевожу что у тебя тут написано:
Есть моб Петя, у него вирус А, он заражает моба М, создаём новый экземпляр вируса Б, заражаем им моба Б. Меняем у вируса А ссылку на заражённого моба на М, вместо пети. Теперь у моба М целых 2 копии вируса! (если бы не встроенные проверки на дурака разумеется).
Аффектед моб присваивается в ..(). Удали

2024-10-08 20:38 UTC, timchigaming commented on code/datums/diseases/viruses/babylon_feve.dm
> +	affected_mob = disease.affected_mob
Да, но... нет, 
![GVELxlvFY1](https://github.com/user-attachments/assets/cf2e9bb7-e191-47a7-956b-000b6b047431)
оно бы жаловалось рантаймом.

2024-10-09 07:47 UTC, LiquidPotroh commented on code/datums/diseases/viruses/babylon_feve.dm
> +	affected_mob = disease.affected_mob
Потому что в регистерсигнал надо тоже к дизиз.аффектедмобу привязывать. 
И убери уже двойные скобки в cure(), не видишь, линтер ругается

2024-10-10 16:34 UTC, Den109G commented on code/modules/mining/lavaland/loot/tendril_loot.dm
> +		user.visible_message("<span class='notice'>[user] suddenly stops, releasing the [src]</span>")
Это поменять на дефайн.
```suggestion
		user.visible_message(span_notice("[user] suddenly stops, releasing the [src]"))
```

2024-10-10 17:47 UTC, Daeberdir commented on code/datums/diseases/viruses/babylon_fever.dm
> +	REMOVE_TRAIT(affected_mob, TRAIT_NO_BABEL, UNIQUE_TRAIT_SOURCE(disease))
```suggestion
	REMOVE_TRAIT(affected_mob, TRAIT_NO_BABEL, UNIQUE_TRAIT_SOURCE(src))
```

2024-10-11 05:35 UTC, Daeberdir commented on code/__DEFINES/mobs.dm
> +
```suggestion
```
В твоём случае всё же не нужно, так как альтернативные исходы обработки языков через болезнь не предусмотрены.

2024-10-13 10:26 UTC, Daeberdir approved these changes
Теперь это будет работать.

2024-10-13 10:29 UTC, Den109G approved these changes
Выглядит хорошо со стороны кода.

2024-10-13 11:38 UTC, merged