feat: Повязки на глаза с ХУДом.
ss220-space/Paradise pull request #6010
Opened 2024-10-11 07:05 UTC by Etrnlmelancholy

## Описание

Рескин обычного худа. Также будет в лодауте.

## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/755125334097133628/1294162246301388853

2024-10-14 02:53 UTC, Daeberdir requested changes
Меланхолик из кодинг.

2024-10-14 02:53 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_glasses.dm
> +	allowed_roles = list("Head of Security", "Warden", "Security Officer", "Security Pod Pilot", "Internal Affairs Agent","Magistrate")
Для АВД делай отдельный "рид онли".

2024-10-14 02:53 UTC, Daeberdir commented on code/modules/clothing/glasses/hud.dm
> +	name = "medical HUD eyepatch"
```suggestion
	name = "\improper Medical HUD Eyepatch"
```
И для остальных также.

2024-10-14 02:53 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_glasses.dm
> +	allowed_roles = list("Head of Security", "Warden", "Security Officer", "Security Pod Pilot", "Internal Affairs Agent","Magistrate")
Забыл детектива.

2024-10-14 02:53 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_glasses.dm
> +	allowed_roles = list("Chief Medical Officer", "Medical Doctor", "Chemist", "Psychiatrist", "Paramedic", "Virologist", "Coroner")
Забыл бригмеда.

2024-10-14 02:53 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_glasses.dm
> +	allowed_roles = list("Head of Personnel", "Captain")
```suggestion
	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_HOP)
```
И так для всех.

2024-10-15 09:22 UTC, Daeberdir approved these changes

2024-10-15 17:46 UTC, Den109G approved these changes

2024-10-15 17:52 UTC, merged