add: midround space wizards!
ss220-space/Paradise pull request #6023
Opened 2024-10-14 17:44 UTC by NightDawnFox

## Описание
В случае, если на станции больше 10 живых игроков, то в качестве мажорного ивента начинают роллиться космические маги. Подсчет - один маг за каждые 30 человек. При триггере ивента блокируется возможность использовать часть заклинаний, привязанных к режиму "рагин магес".

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1225661296423473152

## Тесты
>запустил локалку
>вызвал ивент, проверил как подсчитывается количество игроков
>закомментил ту часть, где ивент не запускается, если меньше 10 игроков и перезапустил локалку
>заспавнился за мага и проверил книгу заклинаний

2024-10-14 17:46 UTC, Vladisvell commented
code/modules/events/wizards.dm:36:error: GLOB.wizard_events_triggered: undefined var
code/game/gamemodes/wizard/spellbook.dm:756:error: GLOB.wizard_events_triggered: undefined var

2024-10-14 17:49 UTC, NightDawnFox commented
> code/modules/events/wizards.dm:36:error: GLOB.wizard_events_triggered: undefined var code/game/gamemodes/wizard/spellbook.dm:756:error: GLOB.wizard_events_triggered: undefined var

я заметил, да.

2024-10-15 06:29 UTC, Daeberdir requested changes

2024-10-15 06:29 UTC, Daeberdir commented on code/modules/events/wizards.dm
> +#define CREW_REQUIREMENT 30
Чтобы не путать никого нужно назвать второй дефайн соответствующе. По типу крю_пер_визард.

2024-10-15 06:29 UTC, Daeberdir commented on code/modules/events/wizards.dm
> +	return min(round(num_station_players() / CREW_REQUIREMENT) + 1) //every mage each 30 crew
Странная математика. Оно точно сработает? Не стоит ли попробовать `return floor(num_station_players() / CREW_REQUIREMENT) || 1` или что-то в таком духе. Чтобы оно точно считало одного мага за 30 игроков, но **почему-то** всё же спавнило от десятки экипажников.

2024-10-15 06:29 UTC, Daeberdir commented on code/modules/events/wizards.dm
> +		log_and_message_admins("Warning: Could not spawn any mobs for event Headslug Infestation. Reason - not enough players.")
Хэдслаг инфестатион.

2024-10-15 06:29 UTC, Daeberdir commented on code/modules/events/wizards.dm
> +		EC.next_event_time = world.time + (60 * 10)
```suggestion
		EC.next_event_time = world.time + (60 SECONDS)
```

2024-10-15 06:29 UTC, Daeberdir commented on code/modules/events/wizards.dm
> +		log_and_message_admins("Warning: Could not spawn any mobs for event Headslug Infestation. Reason - not enough candidates.")
Хэдслаг инфестатион.

2024-10-15 06:29 UTC, Daeberdir commented on code/modules/events/wizards.dm
> +		EC.next_event_time = world.time + (60 * 10)
```suggestion
		EC.next_event_time = world.time + (60 SECONDS)
```

2024-10-15 06:30 UTC, Daeberdir commented
Ещё будет круто, если мы не будем мержить что-либо по протухшей предложке.

2024-10-15 07:53 UTC, Daeberdir commented on code/modules/events/wizards.dm
> +
```suggestion
	if(mages_number < 1)
		log_and_message_admins("Warning: Could not spawn any mobs for event Wizard Raid. Reason - not enough players.")
		var/datum/event_container/EC = SSevents.event_containers[EVENT_LEVEL_MAJOR]
		EC.next_event_time = world.time + (60 SECONDS)
		return

```
Тут стоит, чтобы оно не давало гостам алерт регистрации. Ниже на проверку числа кандидатов тоже можно, но смысла мало.

2024-11-06 07:43 UTC, Antoonij commented on code/modules/events/wizards.dm
> +
раз уж нет кандидатов, то в конце твоих манипуляций с кулдауном нужно поставить return

2024-11-06 07:43 UTC, Antoonij commented on code/modules/events/wizards.dm
> +			log_game("Spawned [new_character] (ckey: [new_character.key]) as midround Wizard.")
учитывая прошлый комментарий - это легче и лучше будет переписать на for

2024-11-06 07:47 UTC, Antoonij commented on code/modules/events/wizards.dm
> +			var/mob/living/carbon/human/new_character= makeBody(new_mage)
```suggestion
			var/mob/living/carbon/human/new_character = makeBody(new_mage)
```

2025-01-04 12:12 UTC, closed without merging