add: blueshield sunglasses
ss220-space/Paradise pull request #6044
Opened 2024-10-18 21:07 UTC by Ssheya

## Описание
Заменяет выданные ЦК бщ и СРТ очки с мед худа и сб худа на новые бщ очки, которые имеют три режима(сб, мед и обычные солнечные)
Режимы меняются через способность и Z

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1295397940487000158

## Тесты
Я верю изменённому коду [DATA CORRUPTED].

2024-10-18 21:07 UTC, Ssheya commented
а схуяли тут нова блять

2024-10-18 21:11 UTC, Ssheya commented
короче, моя часть кода тут работает, я не ебу что тут нова делает, если надо удалите какнибудь пж. :pizdec:

2024-10-18 21:17 UTC, Ssheya commented
о

2024-10-18 21:19 UTC, Den109G commented on code/modules/clothing/glasses/hud.dm
> +	else if (HUDType == DATA_HUD_SECURITY_ADVANCED)
```suggestion
	else if(HUDType == DATA_HUD_SECURITY_ADVANCED)
```

2024-10-18 21:19 UTC, Den109G commented on code/modules/clothing/glasses/hud.dm
> +	if (HUDType)
```suggestion
	if(HUDType)
```

2024-10-19 05:19 UTC, Antoonij commented on code/modules/clothing/glasses/hud.dm
> +	if(user && !can_use(user))
```suggestion
	if(!can_use(user))
```
Проверка на юзера тут не нужна, он у тебя не пропадет в течении 0.00001 секунд после активации очков

2024-10-19 05:19 UTC, Antoonij commented on code/modules/clothing/glasses/hud.dm
> +		update_equipped_item(update_speedmods = FALSE)
Стоит сделать свитч на HUDtype, а не расширять что сейчас, что в будущем else ifалку

2024-10-19 05:19 UTC, Antoonij commented on code/modules/clothing/glasses/hud.dm
> +		update_equipped_item(update_speedmods = FALSE)
затем вынеси update_equipped_item ниже свитча. По сути мы всегда обновим худ, а повторять прок 100 раз - не вариант

2024-10-19 05:30 UTC, Antoonij commented on code/modules/clothing/glasses/hud.dm
> +		icon_state = "sunhud"
айкон стейты должны обновляться в проке update_icon_state(), а как сделаешь свитч на HUDtype - после него вызываешь update_icon(UPDATE_ICON_STATE)

2024-10-19 11:32 UTC, Ssheya commented on code/modules/clothing/glasses/hud.dm
> +		update_equipped_item(update_speedmods = FALSE)
а по русски?

2024-10-19 11:33 UTC, Ssheya commented on code/modules/clothing/glasses/hud.dm
> +		update_equipped_item(update_speedmods = FALSE)
плюс понимаешь, если будут какимто боком ещё такие очки, то я не ебу как написать этот прок чтобы его можно было использовать вездле

2024-10-19 11:33 UTC, Ssheya commented on code/modules/clothing/glasses/hud.dm
> +		icon_state = "sunhud"
> айкон стейты должны обновляться в проке update_icon_state(), в нем в зависимости от типа худов назначаешь иконку. А как сделаешь свитч на HUDtype - после него вызываешь update_icon(UPDATE_ICON_STATE)

я проверил функционал и всё работало

2024-10-19 11:33 UTC, Ssheya commented on code/modules/clothing/glasses/hud.dm
> +		icon_state = "sunhud"
точно надо менять?

2024-10-19 11:39 UTC, Antoonij commented on code/modules/clothing/glasses/hud.dm
> +		icon_state = "sunhud"
Стоит. Так легче будет тебе и всем. Насчет прошлой проблемы - делаешь
switch(HUDType)
   if(DATA_HUD_SECURITY_ADVANCED)
       HUDType = DATA_HUD_MEDICAL_ADVANCED
       и что у тебя там дальше
   if(DATA_HUD_MEDICAL_ADVANCED)
       HUDType = DATA_HUD_SECURITY_ADVANCED
Суть ты понял, надеюсь

2024-10-19 11:51 UTC, Antoonij commented on code/modules/clothing/glasses/hud.dm
> +		icon_state = "sunhud"
Приблизительно так оно должно и выглядеть, потом сам сделаешь update_icon_state()
![image](https://github.com/user-attachments/assets/27efcf80-2ae4-4489-89e0-0fbf5c02cf4a)

2024-10-19 15:50 UTC, Daeberdir requested changes
Во-первых, айкон стейты не используй от других очков. Либо сделай свои (и лучше с помощью оверлеев), либо не меняй их вообще. Во-вторых, сделай модульно. Очки со списком других очков, из которых твои очки будут копировать значения худов. В-третьих, для БЩ третьим вариантом делай скиллхуды, чтобы ПР не протеворечил причинам ввода в предложке.

2024-10-20 17:41 UTC, Ssheya commented
> Во-первых, айкон стейты не используй от других очков. Либо сделай свои (и лучше с помощью оверлеев), либо не меняй их вообще. Во-вторых, сделай модульно. Очки со списком других очков, из которых твои очки будут копировать значения худов. В-третьих, для БЩ третьим вариантом делай скиллхуды, чтобы ПР не протеворечил причинам ввода в предложке.

у меня в предложке не упоминается режим скилов roflcat

2024-10-22 07:46 UTC, Daeberdir commented
> у меня в предложке не упоминается режим скилов roflcat

Ответ аналогичный ПРу с удочкой. У тебя в предложке упоминается в причинах ввода, что очки должны заменить те, которые на данный момент в пользовании у БЩ. Так что стоит делать, следуя геймдизайнерской мысли.

2024-10-31 15:16 UTC, pilygun commented on code/modules/clothing/glasses/hud.dm
> +	desc = "A HUD with multiple functions."
описание предметов должны быть на русском языке

2024-12-31 13:30 UTC, BeebBeebBoob requested changes

2024-12-31 13:30 UTC, BeebBeebBoob commented on code/modules/clothing/glasses/hud.dm
> +		H.add_hud_to(user)
attack_self это когда чел жмёт по предмету в руке.
Сняв очки и нажав, у его чудом будет худ при том что очки не на глазах и он потом может выкинуть и ходить с халявным худом. 
```suggestion
```

2024-12-31 13:30 UTC, BeebBeebBoob commented on code/modules/clothing/glasses/hud.dm
> +	if(HUDType)
```suggestion
	if(HUDType)
```
Не вижу смысла держать отдельный новый целый прок которая нигде больше не используется.
Пусть снимает очки, тыкает и назад

ЛИБО, делай целую новый UI кнопку дабы менять очки когда у чела на глазах и тогда огромный QoL иначе чёт не то. И если будешь делать кнопку то используй `reload_huds()`

2024-12-31 19:43 UTC, Ssheya commented
@BeebBeebBoob замерджил реквесты, пока что кожу другое, потом мб уже и допилю эти очки, если на данный момент нравится-можешь мержить, остальное кину как QoL уже к ним

2025-01-01 09:21 UTC, PlayerUnknown14 requested changes
Буквы поменять.

2025-01-01 09:21 UTC, PlayerUnknown14 commented on code/modules/clothing/glasses/hud.dm
> +	name = "blueshield HUD glasses"
```suggestion
	name = "multi-mode HUD glasses"
```

2025-01-01 09:21 UTC, PlayerUnknown14 commented on code/modules/clothing/glasses/hud.dm
> +	desc = "Солнечные очки с многорежимным проекционным дисплеем."
```suggestion
	desc = "Солнечные очки с многорежимным проекционным дисплеем."
	ru_names = list(
		NOMINATIVE = "много-режимные HUD-очки",
		GENITIVE = "много-режимных HUD-очков",
		DATIVE = "много-режимным HUD-очкам",
		ACCUSATIVE = "много-режимные HUD-очки",
		INSTRUMENTAL = "много-режимными HUD-очками",
		PREPOSITIONAL = "много-режимных HUD-очках"
	)
```

2025-01-01 09:21 UTC, PlayerUnknown14 commented on code/modules/clothing/glasses/hud.dm
> +
```suggestion
    balloon_alert(user, "режим переключён")
```

2025-01-02 06:23 UTC, PlayerUnknown14 submitted a review, later dismissed
Русификация одобрена.

2025-01-02 07:58 UTC, BeebBeebBoob commented
Линтер не прошла

2025-01-02 12:39 UTC, Ssheya commented
> Линтер не прошла

нихуя не понял и как фиксить хз

2025-01-02 12:41 UTC, Ssheya commented
![image](https://github.com/user-attachments/assets/02944a2e-d855-4b30-a2fc-b4d8978d0a74)
![image](https://github.com/user-attachments/assets/49030eef-fef6-49ac-b38b-1b4fc12bd404)
где....

2025-01-02 13:25 UTC, Etrnlmelancholy commented
Че широкая такая в линтеры не входит епт

2025-01-02 14:42 UTC, dageavtobusnick commented
> нихуя не понял и как фиксить хз

У тебя после добавления балун алерта все поломалось. Мб дело в отступах.

2025-01-02 18:12 UTC, Ssheya commented
> > нихуя не понял и как фиксить хз
> 
> У тебя после добавления балун алерта все поломалось. Мб дело в отступах.

я её добавил через коммит саггестион, вопросы к @PlayerUnknown14

2025-01-03 04:08 UTC, PlayerUnknown14 approved these changes
Локализация устраивает.

2025-01-04 12:10 UTC, merged