add: ol' reliable craftable
ss220-space/Paradise pull request #6045
Opened 2024-10-18 21:30 UTC by Ssheya

## Описание
Добавление крафта удочки в протолаты РНД с соответствующим технологиями:
Material Research 5
Biologie Research 6
Ingenring Research 4
Plasma Research 6
Отдел: Equipment
С требованиями в материалах:
15 000 титана(7.5 листов),10 000 металл(5 листов),2 500 серебра(1.25 листов),2 500 алмазов(1.25 листов).
Для облегчения жизни парамедикам/шахтёрам

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/1291762866940285039/1293180899004907592

## Тесты
Не делал, верю что работает.

2024-10-19 16:01 UTC, Daeberdir requested changes
Перетащи в раздел шахтёрских приколов.

2024-10-20 17:39 UTC, Ssheya commented
> Перетащи в раздел шахтёрских приколов.

в предлоги тут, а не у них, УВЫ

2024-10-22 07:43 UTC, Daeberdir commented
Г**ноТЗ не причина идти против геймдизайна. Даже в таких мелочах. Делай адекватно. Если будут возмущаться - разработка решит вопрос.

2024-11-02 02:01 UTC, Daeberdir approved these changes, later dismissed

2024-11-02 06:06 UTC, Antoonij approved these changes, later dismissed
Теперь выглядит хорошо.

2024-11-02 19:02 UTC, Ssheya commented
> Теперь выглядит хорошо.

ну ты бы хоть кинул в мердж очередь

2024-11-03 09:04 UTC, Daeberdir commented
У нас права сломались кидать в очередь. Сейчас из ревьюверов только Владисвель с Бибом могут.

2024-11-03 10:21 UTC, Ssheya commented
> У нас права сломались кидать в очередь. Сейчас из ревьюверов только Владисвель с Бибом могут.

Круто

2024-11-05 12:59 UTC, merged