add: no lockboxes on taipan
ss220-space/Paradise pull request #6049
Opened 2024-10-18 22:39 UTC by Ssheya

## Описание
На тайпане теперь нет локкейсов в протолате/мех фабах

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/1293861087250350142/1295292799687720991

## Тесты
Ну на локалке потестил, работает.

2024-10-18 22:39 UTC, Ssheya commented
да бля сюда и поясы полезли...

2024-10-19 15:55 UTC, Daeberdir requested changes
Хотя-бы выведи проверку из цикла...

2024-10-20 17:38 UTC, Ssheya commented
> Хотя-бы выведи проверку из цикла...

а по русски

2024-10-20 18:44 UTC, Den109G commented on code/modules/research/rdconsole.dm
> +				if(being_built.locked && !is_taipan(z))
`is_taipan(` находится в цикле. И при каждом прохождении цикла эта проверка свершается.
Убери из под цикла `for(`. Напиши выше for-а эту проверку и запиши в какую-то переменную и её используй в цикле.

2024-11-02 02:02 UTC, Ssheya commented
@Daeberdir @Den109G короче залил какуюто хуйню и в моих глазах 5-ти часово утренних оно работать должно, но оно не работает. help
если точнее то оно вообще теперь не делает локбоксы

2024-11-02 02:03 UTC, Ssheya commented
хотя стоп бля...

2024-11-02 02:04 UTC, Ssheya commented
щас пробую вот эту вторую версию, если не работает я хуй его знает

2024-11-02 02:15 UTC, Ssheya commented
нет, не работает, теперь всё нахуй в локбоксах(звучит хайпово)
нужна пмщь

2024-11-02 02:24 UTC, Daeberdir reviewed
Протестируй.

2024-11-02 02:24 UTC, Daeberdir commented on code/modules/research/rdconsole.dm
> +
```suggestion
```

2024-11-02 02:24 UTC, Daeberdir commented on code/modules/research/rdconsole.dm
> +				locked = FALSE
```suggestion
			var/locked = being_built.locked || !is_taipan(z)
```

2024-11-02 02:40 UTC, Ssheya commented on code/modules/research/rdconsole.dm
> +				locked = FALSE
> 

хуй. не сработало

2024-11-02 07:16 UTC, Den109G commented on code/modules/research/rdconsole.dm
> +				locked = FALSE
А если не залоченные кейсы пытаться печатать (на Тайпане и на не-Тайпане)?

2024-11-02 07:19 UTC, Den109G commented on code/modules/research/rdconsole.dm
> +	var/locked = FALSE
Стоит убрать у консоли переменную (раз напечатал нелегал - или будет остальное в локбоксах печататься, или надо обнулять переменную).
Если эта переменная только для прока - то в проке и объявляй переменную.
```suggestion
```

2024-11-02 15:41 UTC, Ssheya commented on code/modules/research/rdconsole.dm
> +	var/locked = FALSE
> Стоит убрать у консоли переменную (раз напечатал нелегал - или будет остальное в локбоксах печататься, или надо обнулять переменную). Если эта переменная только для прока - то в проке и объявляй переменную.

уже, как минимум в моём коде. В моём щас то что сверху даебердир предложил. Всё ещё нифига не работает

2024-11-02 15:41 UTC, Ssheya commented on code/modules/research/rdconsole.dm
> +				locked = FALSE
> А если не залоченные кейсы пытаться печатать (на Тайпане и на не-Тайпане)?

предполагаю что точно также будет, пока не могу чекнуть

2024-11-03 09:13 UTC, Daeberdir commented on code/modules/research/rdconsole.dm
> +	var/locked = FALSE
Щяс.

2024-11-03 09:55 UTC, Daeberdir approved these changes
Пойдёт. Хоть мне и всегда не нравилось то, что тайпанские приколы работают от тайпанского уровня, а не каких-то локальных штук.

2024-11-03 09:55 UTC, Den109G approved these changes
Выглядит хорошо.

2024-11-03 10:20 UTC, Ssheya commented
> Пойдёт. Хоть мне и всегда не нравилось то, что тайпанские приколы работают от тайпанского уровня, а не каких-то локальных штук.

Проверял на работу?

2024-11-05 13:16 UTC, merged