tweak: fart deletion
ss220-space/Paradise pull request #6060
Opened 2024-10-22 13:16 UTC by Baldek0

## Описание

Удаление эмоции пердежа. Удаляется у всех, удаляется из всех возможных мест, за её удалением чистится и код, который станет совершенно неиспользуемым. 

## Ссылка на предложение/Причина создания ПР

(https://discord.com/channels/617003227182792704/755125334097133628/1296718317834469448)

## Демонстрация изменений

## Тесты
Запустил локалку, посмотрел на панельку эмоций - она чиста. Сделал *fart - его не распознало. Парадиз свободен.

2024-10-24 09:32 UTC, LiquidPotroh commented
Вето

2024-10-24 09:34 UTC, LiquidPotroh commented
Ну и как бы не соответствует ТЗ

2024-10-24 09:51 UTC, PlayerUnknown14 commented
Так в предлоге написано про удаление с панели, а не удаление вообще. 
Вето на пердёж, получается.

2024-10-24 09:54 UTC, Baldek0 commented
в предлоге написано удалить у всех, остальное - не часть тз.

2024-10-24 09:55 UTC, Baldek0 commented
если бы у бобов реально было что-то, связанное с пердежом, я бы это оставил. А так, его только с панельки и вызова через чат сделать и можно, так что это буквально чистка кода.

2024-10-24 11:58 UTC, lolybomb commented
Ты как бы уточнил, что именно с панельки удаляешь. А ты полностью вырезаешь по итогу

2024-10-24 12:03 UTC, Baldek0 commented
Я уточнил, что не буду трогать взаимодействия с бобами. Когда я уже потом посмотрел, что в коде такового нет и не было - я решил, что оставлять в коде неиспользуемый мусор не нужно.

2024-10-24 15:16 UTC, lolybomb commented
В смысле неиспользуемый? Ты удалил взаемодействие пердежа и библии

2024-10-24 15:27 UTC, Baldek0 commented
Ну... да? Нет возможности пердеть, значит нет возможности пердеть на библию. Нет возможности пердеть на библию, значит код, который за это отвечает, не используется. Код не используется, значит код мусорный. Вроде, достаточно простая цепочка размышлений.

2024-10-25 08:17 UTC, Den109G requested changes

2024-10-25 08:17 UTC, Den109G commented on code/game/objects/items/weapons/storage/bible.dm
> -/obj/item/storage/bible/fart_act(mob/living/user)
Не по предложке. В предложке написано выпилить из панельки, а не вообще весь функционал вырезать.

2024-10-25 08:39 UTC, Den109G commented on code/game/objects/items/weapons/storage/bible.dm
> -/obj/item/storage/bible/fart_act(mob/living/user)
Ну и да. Чтобы осталось только у бобов - пропиши `only_unintentional` у пердежа, чтобы игрок не мог через `say` вызвать это.

2024-10-25 11:45 UTC, Baldek0 commented on code/game/objects/items/weapons/storage/bible.dm
> -/obj/item/storage/bible/fart_act(mob/living/user)
Надо же, как активны попытки цепляться за мусор. Ладно, пусть мусор остаётся. Пропишу.

2024-10-25 16:25 UTC, Daeberdir requested changes
Рассмотр можно лениво начинать, когда бобам будет добавлено взаимодействие с эмоутом.

2024-10-26 04:16 UTC, Den109G commented on code/game/objects/items/weapons/storage/bible.dm
> -/obj/item/storage/bible/fart_act(mob/living/user)
> Надо же, как активны попытки цепляться за мусор. Ладно, пусть мусор остаётся. Пропишу.

Просто надо админам оставить возможность так казнить людей. Как ты и написал в предложке.

2024-10-26 08:39 UTC, Baldek0 commented on code/game/objects/items/weapons/storage/bible.dm
> -/obj/item/storage/bible/fart_act(mob/living/user)
> Просто надо админам оставить возможность так казнить людей. Как ты и написал в предложке.

А, вот про админов я и правда забыл. Ну, собственно, вернул.

2024-12-31 13:31 UTC, merged

2024-12-31 13:51 UTC, PlayerUnknown14 commented
Это такой конец