tweak: M90 instead riot shotguns in ERT armory
ss220-space/Paradise pull request #6062
Opened 2024-10-23 08:10 UTC by Mahimka42

## Описание
Меняет служебные дробовики на М90 в оружейной ЕРТ

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/1269912125606723594/1271068409404063866

## Тесты
Все работает.

2024-10-23 19:43 UTC, Daeberdir requested changes
![image](https://github.com/user-attachments/assets/8f05a9ad-76c1-40e0-9362-e6ca9f7b9580)
Раскидай по икс-игреку.

2024-10-26 14:32 UTC, Daeberdir approved these changes, later dismissed
![imag312412e](https://github.com/user-attachments/assets/556dcc10-7fa0-4e97-8eb5-1dfd15f818ae)

2024-10-26 15:06 UTC, Daeberdir approved these changes
От так лучше.

2024-10-26 15:11 UTC, Den109G approved these changes
Одобряю со стороны таяры2.

2024-10-26 15:17 UTC, merged