add/bugfix: earrings
ss220-space/Paradise pull request #6066
Opened 2024-10-23 19:55 UTC by lolybomb

## Описание
**Big kisik update**

Добавлем модные сережки в билд, а также фиксим наушники

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1231376328213921813

## Демонстрация изменений
![image](https://github.com/user-attachments/assets/49122e65-76be-4137-bbe6-9d3174e5bcd8)

2024-10-23 19:58 UTC, lolybomb commented
Бляяяять, я проебался. Какого хуя paradise.dme изменился

2024-10-23 20:04 UTC, lolybomb commented
Похуй закрою и пересоздам по нормальному

2024-10-25 16:39 UTC, Daeberdir requested changes
![image](https://github.com/user-attachments/assets/0bc8d024-abb0-4adc-81d1-521742948347)
С такими приколами на другие билды.

2024-10-27 15:50 UTC, Bizzonium commented
> С такими приколами на другие билды.
а что не так?

2024-10-27 16:48 UTC, Bizzonium commented
![image](https://github.com/user-attachments/assets/09e4dce7-fc97-4cf3-81a1-b89e2552a876)

2024-10-27 16:49 UTC, merged