tweak: new cinematics for gods and delete soul devoured check
ss220-space/Paradise pull request #6067
Opened 2024-10-24 06:08 UTC by FlitchTime

## Описание
Добавлены синематик обезвреживания нюки для Ратвара
Добавлены синематик в космосе для Ратвара
Добавлены синематик в космосе для Рипера
Добавлены синематик в космосе для Кхарина
Удалил проверку на пожирание душ, т.к. она у 3 из 4 богов была тупиковой, а у последнего синематик с победой я не увидел из-за какого-то бага ¯\_(ツ)_/¯

## Ссылка на предложение/Причина создания ПР
Я просто потратил ночь на синематики (⊙_⊙;)

## Демонстрация изменений
![Narsie](https://github.com/user-attachments/assets/3025d63d-ddec-4f3d-a63a-e44527ea398e)
![Kharin](https://github.com/user-attachments/assets/4bde7cc0-d632-43d7-b8ae-9325801770a8)
![Reaper](https://github.com/user-attachments/assets/a1f626a5-0ced-4db5-8df4-c22f8547a164)
![Ratvarit](https://github.com/user-attachments/assets/2c71e17d-fe6c-417e-bab1-a56789cf45b8)

## Тесты
Запустил локалку, заспавнил бога, посмотрел мульт, повторил с остальными

2024-10-24 07:14 UTC, Den109G commented on code/game/gamemodes/game_mode.dm
> +	if (R)
```suggestion
	if(R)
```

2024-10-24 07:14 UTC, Den109G commented on code/game/gamemodes/game_mode.dm
> +	if (N)
```suggestion
	if(N)
```

2024-10-24 07:14 UTC, Den109G commented on code/game/gamemodes/game_mode.dm
> +			play_cinematic(/datum/cinematic/cult_arm_kharin, world)
Если хочешь тут делать мультики, то это на свитч надо переписать.
```dm
var/datum/cinematic/cinema
switch(SSticker.cultdat.name)
   if("Cult of Kha'Rin")
      cinema = /datum/cinematic/cult_arm_kharin
   if("Cult of Mortality")
      cinema = /datum/cinematic/cult_arm_reaper
 и дальше код что везде повторяется.
 ```
 Но по хорошему, надо завезти новую переменную под мультики.
 Как-нибудь:
 ```dm
 /datum/cult_info
    var/datum/cinematic/end_screen = /datum/cinematic/cult_arm_kharin
 ```

2024-10-24 07:23 UTC, Den109G commented on code/datums/cinematics/narsie_summon.dm
> +	screen.icon_state = "summary_cult"
А почему мультик "провала культа", когда бог умер, показывает бога живого и здорового? Даже когда через 5 секунд идёт его убийство (`sound/misc/demon_dies.ogg`)?

2024-10-24 13:46 UTC, FlitchTime commented on code/datums/cinematics/narsie_summon.dm
> +	screen.icon_state = "summary_cult"
> А почему мультик "провала культа", когда бог умер, показывает бога живого и здорового? Даже когда через 5 секунд идёт его убийство (`sound/misc/demon_dies.ogg`)?

Поправил if и вернул station_intact

2024-10-29 23:04 UTC, Daeberdir requested changes

2024-10-29 23:04 UTC, Daeberdir commented on code/game/gamemodes/game_mode.dm
> +	GLOB.priority_announcement.Announce("Обнаружена угроза класса 'Разрушитель миров'. Моделирование пути решения угрозы начато, ожидайте", "Отдел Центрального Командования по делам высших измерений", '
"Решение угрозы" звучит странно, попробуй "Моделирование пути (устранения угрозы / противостояния угрозе / решения кризиса) начато, ожидайте."
И точку пашто угнал?

2024-10-29 23:04 UTC, Daeberdir commented on code/game/gamemodes/game_mode.dm
> +	GLOB.priority_announcement.Announce("Моделирование завершено. Всему живому персоналу: не допустите усиления угрозы любой ценой. Меры будут приняты в ближайщее время", "Отдел Центрального Командовани
ближай**ш**ее время **точка**

2024-10-29 23:04 UTC, Daeberdir commented on code/game/gamemodes/game_mode.dm
> +		return
1. Послушай совета Дена и прилепи это переменной у датума культа.
2. Удалённую часть нужно будет вернуть, чтобы не появились проблемы, когда бог скушивает слишком мало душ.
![image](https://github.com/user-attachments/assets/79d6494e-cbc4-4c02-a05f-c29707924a6b)

2024-10-29 23:04 UTC, Daeberdir commented on code/game/gamemodes/game_mode.dm
> -		if(N.soul_devoured > 20)
🙅🏻 
Nonononononononononononononononoononononono
Если оно почему-то где-то не работает, то твоя цель - исправить это, а не убивать.

2024-10-30 09:57 UTC, FlitchTime commented on code/game/gamemodes/game_mode.dm
> +		return
Переделал на switch, а в датумы сами уже когда-нибудь переносите

2024-10-30 09:59 UTC, FlitchTime commented on code/game/gamemodes/game_mode.dm
> -		if(N.soul_devoured > 20)
По предложению счётчика душ не было, а его работа вызывает вопросы. Зачем мне его оставлять?
https://discord.com/channels/617003227182792704/755125334097133628/1222102589185982527

2024-10-30 10:01 UTC, FlitchTime commented on code/game/gamemodes/game_mode.dm
> +			play_cinematic(/datum/cinematic/cult_arm_kharin, world)
@Den109G, норм?

2024-10-30 10:03 UTC, FlitchTime commented on code/game/gamemodes/game_mode.dm
> +	GLOB.priority_announcement.Announce("Моделирование завершено. Всему живому персоналу: не допустите усиления угрозы любой ценой. Меры будут приняты в ближайщее время", "Отдел Центрального Командовани
ТОЧКА

2024-10-30 10:03 UTC, FlitchTime commented on code/game/gamemodes/game_mode.dm
> +	GLOB.priority_announcement.Announce("Обнаружена угроза класса 'Разрушитель миров'. Моделирование пути решения угрозы начато, ожидайте", "Отдел Центрального Командования по делам высших измерений", '
Не угнал, а взял покататься

2024-10-30 13:56 UTC, Daeberdir commented on code/game/gamemodes/game_mode.dm
> -		if(N.soul_devoured > 20)
![image](https://github.com/user-attachments/assets/d0b3a91c-0c10-4a46-9f1e-399b4c666626) вот за этим.
И за тем, что изначальная задумка через "количество культистов" неиспользуема, ибо ровно после призыва любого бога количество культистов может за секунду увеличиться до общего числа гостов.
Текущее решение с пожиранием людей вполне правильное для культа, целью которого после призыва бога является "Накормить бога".
Так что чистим чистим.

2024-10-30 18:33 UTC, FlitchTime commented on code/game/gamemodes/game_mode.dm
> -		if(N.soul_devoured > 20)
Я другого мнения. Предложка была на одно, а по итогу сделали другое. Культу не увидеть "Бог_нейм has fallen. Никто не победил" это исключение, так что не надо говорить про "правильное для культа"

2024-10-31 07:12 UTC, Daeberdir commented on code/game/gamemodes/game_mode.dm
> -		if(N.soul_devoured > 20)
Okay then. В таком случае я попрошу вообще не задевать эту часть кода.

2024-11-02 06:19 UTC, Antoonij requested changes

2024-11-02 06:19 UTC, Antoonij commented on code/datums/cinematics/kharin_summon.dm
> +/datum/cinematic/cult_arm_kharin/play_cinematic()
```suggestion
/datum/cinematic/cult_arm_kharin

/datum/cinematic/cult_arm_kharin/play_cinematic()
```
Пустая строка после объявления для кодстайла

2024-11-02 06:19 UTC, Antoonij commented on code/datums/cinematics/kharin_summon.dm
> +/datum/cinematic/cult_fail_kharin/play_cinematic()
```suggestion
/datum/cinematic/cult_fail_kharin

/datum/cinematic/cult_fail_kharin/play_cinematic()
```
Пустая строка после объявления для кодстайла

2024-11-02 06:19 UTC, Antoonij commented on code/datums/cinematics/ratvar_summon.dm
> +/datum/cinematic/cult_arm_ratvar/play_cinematic()
```suggestion
/datum/cinematic/cult_arm_ratvar

/datum/cinematic/cult_arm_ratvar/play_cinematic()
```
Пустая строка после объявления для кодстайла

2024-11-02 06:19 UTC, Antoonij commented on code/datums/cinematics/ratvar_summon.dm
> +/datum/cinematic/cult_fail_ratvar/play_cinematic()
```suggestion
/datum/cinematic/cult_fail_ratvar

/datum/cinematic/cult_fail_ratvar/play_cinematic()
```
Пустая строка после объявления для кодстайла

2024-11-02 06:19 UTC, Antoonij commented on code/datums/cinematics/reaper_summon.dm
> +/datum/cinematic/cult_arm_reaper/play_cinematic()
```suggestion
/datum/cinematic/cult_arm_reaper

/datum/cinematic/cult_arm_reaper/play_cinematic()
```
Пустая строка после объявления для кодстайла

2024-11-02 06:19 UTC, Antoonij commented on code/datums/cinematics/reaper_summon.dm
> +/datum/cinematic/cult_fail_reaper/play_cinematic()
```suggestion
/datum/cinematic/cult_fail_reaper

/datum/cinematic/cult_fail_reaper/play_cinematic()
```
Пустая строка после объявления для кодстайла

2024-11-02 06:19 UTC, Antoonij commented on code/game/gamemodes/game_mode.dm
> +		return
Код опять повторяется, в данном моменте уже у ратвара. Ретарн с 746 строки, 751 убрать, синематик у ратвара также поместить в переменную. В самый низ прока поместить чек if(cinematic) и под ним уже проигрывать синематик в переменной, спать 15 секунд и устанавливать форс ендинг на тру

2024-11-02 06:19 UTC, Antoonij commented on code/game/gamemodes/game_mode.dm
> +		var/datum/cinematic/cinema
var/datum/cinematic/cinema вынести выше  чека переменной N, в следующем комментарии будем избегать повторений.

2024-11-02 07:22 UTC, FlitchTime commented on code/datums/cinematics/kharin_summon.dm
> +/datum/cinematic/cult_arm_kharin/play_cinematic()
Одни против пробелов и отступлений, другие за. Увы, но делать не буду

2024-11-02 07:22 UTC, FlitchTime commented on code/datums/cinematics/ratvar_summon.dm
> +/datum/cinematic/cult_arm_ratvar/play_cinematic()
Одни против пробелов и отступлений, другие за. Увы, но делать не буду

2024-11-02 07:22 UTC, FlitchTime commented on code/datums/cinematics/reaper_summon.dm
> +/datum/cinematic/cult_arm_reaper/play_cinematic()
Одни против пробелов и отступлений, другие за. Увы, но делать не буду

2024-11-02 07:25 UTC, FlitchTime commented on code/game/gamemodes/game_mode.dm
> +		return
Ратвар написан не также, как кровавики, так что увы. Либо расписывай, либо говнокод оставляем

2024-11-02 07:25 UTC, FlitchTime commented on code/game/gamemodes/game_mode.dm
> +		var/datum/cinematic/cinema
Он его не видит в таком случае и кидает ошибку

2024-11-02 07:26 UTC, FlitchTime commented on code/datums/cinematics/kharin_summon.dm
> +/datum/cinematic/cult_fail_kharin/play_cinematic()
Одни против пробелов и отступлений, другие за. Увы, но делать не буду

2024-11-02 07:47 UTC, Antoonij approved these changes
Теперь выглядит хорошо

2024-11-03 09:46 UTC, Daeberdir commented on code/datums/cinematics/kharin_summon.dm
> +/datum/cinematic/cult_arm_kharin
```suggestion
```

2024-11-03 09:46 UTC, Daeberdir commented on code/datums/cinematics/kharin_summon.dm
> +/datum/cinematic/cult_fail_kharin
```suggestion
```

2024-11-03 09:46 UTC, Daeberdir commented on code/datums/cinematics/ratvar_summon.dm
> +/datum/cinematic/cult_arm_ratvar
```suggestion
```

2024-11-03 09:46 UTC, Daeberdir commented on code/datums/cinematics/ratvar_summon.dm
> +/datum/cinematic/cult_fail_ratvar
```suggestion
```

2024-11-03 09:46 UTC, Daeberdir commented on code/datums/cinematics/reaper_summon.dm
> +/datum/cinematic/cult_arm_reaper
```suggestion
```

2024-11-03 09:47 UTC, Daeberdir commented on code/datums/cinematics/reaper_summon.dm
> +/datum/cinematic/cult_fail_reaper
```suggestion
```

2024-11-03 09:47 UTC, FlitchTime commented
> Вижу, что вопрос с souls devoured не был решен. Нужно вернуть

Забавно, что ты это написал после того, как Влад проверку вернул

2024-11-03 09:51 UTC, Antoonij requested changes
Вижу, что вопрос с souls devoured не был решен. Нужно вернуть

2024-11-03 10:11 UTC, Daeberdir commented on code/game/gamemodes/game_mode.dm
> +
```suggestion
/datum/game_mode/proc/apocalypse_cinema(obj/singularity/god/god)
	if(god.soul_devoured <= 17)
		return /datum/cinematic/nuke/self_destruct

	if(istype(god, /obj/singularity/god/narsie))
		return SSticker.cultdat.apocalypse_cinema

	if(istype(god, /obj/singularity/god/ratvar))
		return /datum/cinematic/cult_arm_ratvar

```

2024-11-03 12:56 UTC, merged