add: "gib me please" set up
ss220-space/Paradise pull request #6069
Opened 2024-10-24 07:44 UTC by Anorak2024

## Описание
Добавление настройки которая разрешает выводить вас из раунда без соответствующей цели. Инфа об этом видна при осмотре. Сделал чтоб это было видно только у людей и только при наличии assigned_role (т.е. без всяких макак и эшей). Переключение настройки логируется. 

## Ссылка на предложение
https://discord.com/channels/617003227182792704/755125334097133628/1298696519465172993

## Тесты
Ну, запустил, поосматривал куклу с разным состоянием этой настройки.

2024-10-26 04:57 UTC, Den109G commented on code/modules/client/client_defines.dm
> +	var/can_they_gib_me = FALSE
Переменная не используется. Комментарий к ней всё ещё уместен?

2024-10-26 05:10 UTC, Den109G commented on code/modules/mob/living/carbon/human/examine.dm
> +	if(client && mind && mind.assigned_role) // No ashes, monkeys etc
Если тут проверка на гост роль - то надо использовать проверку на гост роль.
```suggestion
	if(client && mind && !mind.offstation_role) // No ashwalkers, monkeys etc
```

2024-10-26 05:10 UTC, Den109G commented on code/modules/mob/living/carbon/human/examine.dm
> +		msg += "\n" + (user.client.prefs.toggles2 & PREFTOGGLE_2_GIB_WITHOUT_OBJECTIVE ? "Вы можете вывести этого игрока без игры не имея соответствующей цели." : ("Вы " + span_warning("НЕ") + " можете выв
Примерно так стоит поменять, чтобы избавиться от повторений. (Я не уверен насчёт текста, о чём там речь.)
Плюс стилизовать чтобы отличалось от других IC текстов.
Префы наверное не так работает. Пока в if-е идёт проверка у куклы, на которую смотрят (client) - тут идёт проверка префа человека который смотрит на куклу (user.client).
```suggestion
        var/permission_granted = user.client.prefs.toggles2 & PREFTOGGLE_2_GIB_WITHOUT_OBJECTIVE
		msg += "\n <div class='examine'><span class='info'> Вы[permission_granted ? "" : " [span_warning("НЕ")]"] можете вывести этого игрока из ролевой игры не имея соответствующей цели.</span></div>"
```

2024-10-26 06:25 UTC, Anorak2024 commented on code/modules/client/client_defines.dm
> +	var/can_they_gib_me = FALSE
Не уместен, как и сама переменная. Убрал.

2024-10-26 06:27 UTC, Anorak2024 commented on code/modules/mob/living/carbon/human/examine.dm
> +		msg += "\n" + (user.client.prefs.toggles2 & PREFTOGGLE_2_GIB_WITHOUT_OBJECTIVE ? "Вы можете вывести этого игрока без игры не имея соответствующей цели." : ("Вы " + span_warning("НЕ") + " можете выв
Угу, надо было без "user.". Сделал "...вывести этого игрока из игры..."

2024-10-26 13:40 UTC, Daeberdir commented on code/__DEFINES/preferences.dm
> +#define PREFTOGGLE_2_GIB_WITHOUT_OBJECTIVE			(1<<21) // 2097152
```suggestion
#define PREFTOGGLE_2_DISABLE_VOTE_POPUPS			(1<<14) // 16384
#define PREFTOGGLE_2_SWAP_INPUT_BUTTONS				(1<<15) // 32768
#define PREFTOGGLE_2_LARGE_INPUT_BUTTONS			(1<<16) // 65536
#define PREFTOGGLE_2_BIG_STRIP_MENU					(1<<17) // 131072
#define PREFTOGGLE_2_ENABLE_TGUI_SAY_LIGHT_MODE		(1<<18) // 262144
#define PREFTOGGLE_2_PIXELATED_MENU 				(1<<19) // 524288
#define PREFTOGGLE_2_DESC_TIPS						(1<<20) // 1048576
#define PREFTOGGLE_2_GIB_WITHOUT_OBJECTIVE			(1<<21) // 2097152
```
Табы, пожулайста...

2024-10-26 13:40 UTC, Daeberdir commented on code/__DEFINES/preferences.dm
>  #define TOGGLES_2_TOTAL								2097151 // If you add or remove a preference toggle above, make sure you update this define with the total value of the toggles combined.
Тут просьба корректировать значения при изменении значений верхних.

2024-10-26 13:40 UTC, Daeberdir commented on code/modules/client/preference/preferences_toggles.dm
> +    name = "Переключить разрешение выводить вас из раунда"
Очень. Долгое. Название...

2024-10-26 17:58 UTC, Daeberdir commented on code/modules/client/preference/preferences_toggles.dm
> +	log_admin("[user.ckey] " + (user.prefs.toggles2 & PREFTOGGLE_2_GIB_WITHOUT_OBJECTIVE ? "enabled" : "disabled") + " permission to take him/her out of the round.")
Последнее. Во-первых, это засрёт логи админам, если люди это будут дёргать. Во-вторых, админы бтв не смогут за этим следить, если за раунд человек не переключил этот преф. Вбей статус этого префа внутрь уже имеющегося лога из `/mob/living/death(gibbed)`. Там должен быть аттаклог типо "моб против моб (умер)", допиши туда проверку на наличие клиента и дополнение "разрешение на гиб: включено/выключено".

2024-10-26 19:19 UTC, Daeberdir submitted a review, later dismissed
Допустим. Пойдёт.

2024-10-26 19:20 UTC, Daeberdir commented
Но я напомню, что все видят названия коммитов.

2024-11-02 14:29 UTC, Antoonij requested changes

2024-11-02 14:29 UTC, Antoonij commented on code/modules/mob/living/carbon/human/examine.dm
> +
В предложке указано, что должны видеть только антагонисты, а в данном случае будут видеть все.  Следует проверять на special_role у майнда того, кто экзамайнил.

2024-11-02 15:01 UTC, Anorak2024 commented on code/modules/mob/living/carbon/human/examine.dm
> +
Не помню правда чтоб указывал такое в предложке.

2024-11-02 15:06 UTC, Anorak2024 commented
@Daeberdir
Сделал чтоб видели только антаги

2024-11-02 15:07 UTC, Antoonij approved these changes
![image](https://github.com/user-attachments/assets/8a537920-3e0e-47b2-939d-b26e00f794e6)
Вот теперь выглядит хорошо.

2024-11-02 19:20 UTC, merged