add: Heart hud glasses
ss220-space/Paradise pull request #6072
Opened 2024-10-24 10:28 UTC by lolybomb

## Описание

Добавляем дриповые очки

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1298693583586459749
## Демонстрация изменений
![image](https://github.com/user-attachments/assets/bf0b484b-3990-474d-8c7c-2471f41718c7)
![image](https://github.com/user-attachments/assets/9b9e1c4a-1227-4e80-ab58-d901b0b103ad)
![image](https://github.com/user-attachments/assets/004b9306-6852-453c-a375-28d94f6df94e)
![image](https://github.com/user-attachments/assets/ca4e1134-ed82-478b-972f-58d0a626818f)
![image](https://github.com/user-attachments/assets/0b3ac48f-c1f2-4212-8884-6ac75d565e74)
![image](https://github.com/user-attachments/assets/c3b97fb5-8ecb-406b-add0-17c699e868af)
![image](https://github.com/user-attachments/assets/b6bc8f8d-11cb-4fc8-8086-bc286e90ead1)
![image](https://github.com/user-attachments/assets/958d7ab1-cc58-43d1-ba7f-5a9f3d89865b)

2024-10-25 16:56 UTC, Daeberdir requested changes
Сделай перекрашиваемые очки отдельным обьектом, чтобы люди не портили твои очки с худами.

2024-10-25 16:56 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_CMO, JOB_TITLE_INTERN, JOB_TITLE_PARAMEDIC, JOB_TITLE_VIROLOGIST, JOB_TITLE_BLUESHIELD, JOB_TITLE_PSYCHIATRIST, JOB_TITLE_DOCTOR)
Ладно ещё БЩ, но капитан явно сомнительный во всех, кроме скиллхудов.

2024-10-25 16:56 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_SCIENTIST, JOB_TITLE_ROBOTICIST, JOB_TITLE_RD, JOB_TITLE_GENETICIST, JOB_TITLE_CHEMIST)
У тебя есть вариант сделать "пивной" вариант для бармена.

2024-10-25 16:56 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_CMO, JOB_TITLE_INTERN, JOB_TITLE_PARAMEDIC, JOB_TITLE_VIROLOGIST, JOB_TITLE_BLUESHIELD, JOB_TITLE_PSYCHIATRIST, JOB_TITLE_DOCTOR)
Забыл коронера. Он тоже медик.

2024-10-25 16:56 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	display_name = "Heart Medical Glasses"
Сердечковые Диагностические Глассесы

2024-10-25 16:56 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CHIEF, JOB_TITLE_ENGINEER, JOB_TITLE_ATMOSTECH, JOB_TITLE_MECHANIC, JOB_TITLE_QUARTERMASTER, JOB_TITLE_MINER, JOB_TITLE_CAPTAIN)
Стажёра забыл.

2024-10-25 16:56 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_SCIENTIST, JOB_TITLE_ROBOTICIST, JOB_TITLE_RD, JOB_TITLE_GENETICIST, JOB_TITLE_CHEMIST)
Студента забыл.

2024-10-25 16:56 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_REPRESENTATIVE, JOB_TITLE_BLUESHIELD, JOB_TITLE_HOP, JOB_TITLE_QUARTERMASTER, JOB_TITLE_JUDGE)
КМ и судья? :cats:

2024-10-25 16:56 UTC, Daeberdir commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_DETECTIVE, JOB_TITLE_PILOT, JOB_TITLE_HOS, JOB_TITLE_WARDEN, JOB_TITLE_BLUESHIELD, JOB_TITLE_JUDGE, JOB_TITLE_OFFICER)
Для АВД сделай рид-онли версию.

2024-10-25 16:56 UTC, Daeberdir commented on code/modules/clothing/glasses/hud.dm
> +	name = "Heart Medical Glasses"
Либо: 
```suggestion
	name = "\improper Heart Medical Glasses"
```
Либо:
```suggestion
	name = "heart medical glasses"
```
Первый вариант мне кажется правильнее.

2024-10-25 16:56 UTC, Daeberdir commented on code/modules/clothing/glasses/hud.dm
> +	prescription_upgradable = FALSE
```suggestion
```
Не дурить. Баги не создавать.

2024-10-26 06:35 UTC, lolybomb commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_CMO, JOB_TITLE_INTERN, JOB_TITLE_PARAMEDIC, JOB_TITLE_VIROLOGIST, JOB_TITLE_BLUESHIELD, JOB_TITLE_PSYCHIATRIST, JOB_TITLE_DOCTOR)
Так по тз было

2024-10-26 06:39 UTC, lolybomb commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_SCIENTIST, JOB_TITLE_ROBOTICIST, JOB_TITLE_RD, JOB_TITLE_GENETICIST, JOB_TITLE_CHEMIST)
По типу пивной? Там же у него отдельный спрайт как у простых сангласов

2024-10-26 06:55 UTC, lolybomb commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_SCIENTIST, JOB_TITLE_ROBOTICIST, JOB_TITLE_RD, JOB_TITLE_GENETICIST, JOB_TITLE_CHEMIST)
Я могу в принципе взять спрайт обычных очков с сердечками, если ты про это

2024-10-26 07:13 UTC, lolybomb commented on code/modules/client/preference/loadout/loadout_donor.dm
> +	allowed_roles = list(JOB_TITLE_CAPTAIN, JOB_TITLE_SCIENTIST, JOB_TITLE_ROBOTICIST, JOB_TITLE_RD, JOB_TITLE_GENETICIST, JOB_TITLE_CHEMIST)
Хотя не говно будет

2024-10-26 13:31 UTC, Daeberdir commented on code/modules/clothing/glasses/hud.dm
> +	name = "Heart Medical Glasses"
```suggestion
	name = "\improper Heart Medical Glasses"
```

2024-10-26 13:34 UTC, Daeberdir approved these changes
Теперь круто. Прикол с капитаном решится потом в следствии одного лодаутного прикола.

2024-10-27 15:49 UTC, Bizzonium commented
А что за прикол?

2024-10-29 00:19 UTC, Daeberdir commented
> А что за прикол?

Хочу не 50 разных датумов для каждой лодаутной шмотки, а один датум, который автоматом подберёт для нужной должности нужный подтип предмета.

2024-11-03 06:25 UTC, Den109G approved these changes
Со стороны кода вроде нет ошибок.

2024-11-15 12:45 UTC, pilygun commented
@Vladisvell Толкни

2024-11-15 16:18 UTC, merged