add: GSBussy doll
ss220-space/Paradise pull request #6104
Opened 2024-10-30 12:53 UTC by PlayerUnknown14

## Описание
Добавляет новую игрушку - "GSBussy doll". Уникальные реплики, анимация, можно получить за 3 тир в лодауте.

Автор спрайтов - Его Величество Split aka Кисик.

Позволил себе немного отойти от ТЗ в вопросе названия куклы и ещё паре моментов - Кисик дал добро.

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/618952559607939072/1296474691753476178

## Демонстрация изменений

## Тесты
Заспаунил куклу, потыкал её, потыкал её себе по голове, посмотрел на анимацию - работает!

2024-10-30 14:40 UTC, PlayerUnknown14 commented
**IconDiffBot2** _Queued — Waiting to run this check..._

2024-10-31 13:15 UTC, Antoonij requested changes

2024-10-31 13:15 UTC, Antoonij commented on code/game/objects/items/toys.dm
> +		COOLDOWN_START(src, cooldown, 3 SECONDS)
1. Стоит вынести месседж (и при объявлении месседжа сразу и пикать нужные фразы, раз уж у нас нет условий влияющих на смену фразы), плейсаунд, визибл месседж, старт кулдауна в отдельный прок и вызывать его в атаке и атак селфе. 
2. В функции attack кулдаун стартуем, а на него не проверяем. Так и было задумано?

2024-11-03 15:54 UTC, Antoonij approved these changes
Теперь выглядит хорошо.

2024-11-04 07:43 UTC, merged