add: grey rework
ss220-space/Paradise pull request #6108
Opened 2024-10-31 15:44 UTC by Samirakis

## Описание
Небольшой реворк греев, сделанный на основе двух предложек
Если постараться кратко, то:  добавлен "ретранслятор псионического голоса" греев, который заменяет старый дешифратор вингдингс, а так же голосовые связки греев. Добавлены чипы с языками для установки в него же. Прописан весь код для лёгкого добавления имплантов-переводчиков в игру, изменены некоторые цифры у греев, теперь греи получают стаминаурон от перетаскивания существ/объектов, лучше принимают импланты

Весь список изменений есть в предложках ниже

Автор всех спрайтов(discord): vitalya_kramsatel

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1291932121291817030
https://discord.com/channels/617003227182792704/755125334097133628/1291932183333830748

## Тесты
Много дней, проведённых на локалке в отлавливании багов. Тыкался долго, все найденные проблемы были устранены

2024-10-31 17:12 UTC, Antoonij requested changes

2024-10-31 17:12 UTC, Antoonij commented on code/datums/action.dm
> +	return TRUE
Trigger стоит поменять на /Activate(), убрать isAvailable

2024-10-31 17:12 UTC, Antoonij commented on code/datums/action.dm
> +		return
Стоит вызывать родителя, если в будущем будут что то менять для всех экшенс. Если не хочется, что бы вызывался attack_self у предмета в случае активации кнопочки - переведи переменную экшенса
 attack_self = FALSE

2024-10-31 17:12 UTC, Antoonij commented on code/game/objects/structures/watercloset.dm
> +		return
стоит ввести сигнал, к примеру COMSIG_SINK_ACT, чем расширять истайпы на расы

2024-10-31 17:12 UTC, Antoonij commented on code/modules/client/preference/loadout/loadout_racial.dm
> +		var/obj/item/translator_chip/chip = path
```suggestion
	for(var/obj/item/translator_chip/chip as anything in subtypesof(/obj/item/translator_chip))
```
Вполне можно сократить. Главное в таком случае не забывать делать игнорирование типа

2024-10-31 17:12 UTC, Antoonij commented on code/modules/mob/living/carbon/human/human_movement.dm
> +			if(pulling && istype(pulling, /mob/living))
```suggestion
			if(pulling && isliving(pulling))
```

2024-10-31 17:12 UTC, Antoonij commented on code/modules/mob/living/carbon/human/human_movement.dm
> +			if(pulling && !(small_pushed || (istype(pulling, /obj/item))))
```suggestion
			if(pulling && !(small_pushed || (isitem(pulling))))
```

2024-10-31 17:12 UTC, Antoonij commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				if(!(istype(now_pushing, /mob/living) && a_intent == INTENT_HELP))
```suggestion
				if(!(isliving(now_pushing) && a_intent == INTENT_HELP))
```

2024-10-31 17:12 UTC, Antoonij commented on code/modules/research/designs/medical_designs.dm
> +	desc = "Имлпант для перевода псионической речи греев в более понятные звуковые волны. Разработан специально для греев."
```suggestion
	desc = "Имплант для перевода псионической речи греев в более понятные звуковые волны. Разработан специально для греев."
```

2024-10-31 17:12 UTC, Antoonij commented on code/modules/surgery/organs/voice_translator.dm
> +		var/obj/item/translator_chip/chip = path
```suggestion
	for(var/obj/item/translator_chip/chip as anything in subtypesof(/obj/item/translator_chip))
```
Можно сократить.

2024-10-31 17:12 UTC, Antoonij commented on code/modules/surgery/organs/augments_internal.dm
> +/obj/item/organ/internal/cyberimp/chest/nutriment/insert(mob/living/carbon/human/target, special = ORGAN_MANIPULATION_DEFAULT)
```suggestion
/obj/item/organ/internal/cyberimp/chest/nutriment/plus/insert(mob/living/carbon/human/target, special = ORGAN_MANIPULATION_DEFAULT)
```
Ошибка. В Тз также изменения обычной помпы - нет, только плюс

2024-10-31 17:12 UTC, Antoonij commented on code/modules/surgery/organs/augments_internal.dm
> +/obj/item/organ/internal/cyberimp/chest/nutriment/remove(mob/living/carbon/human/target, special = ORGAN_MANIPULATION_DEFAULT)
```suggestion
/obj/item/organ/internal/cyberimp/chest/nutriment/plus/remove(mob/living/carbon/human/target, special = ORGAN_MANIPULATION_DEFAULT)
```
Также, как и комментарий выше

2024-10-31 17:12 UTC, Antoonij commented on code/modules/surgery/organs/voice_translator.dm
> +		var/obj/item/translator_chip/chip = path
```suggestion
	for(var/obj/item/translator_chip/chip as anything in subtypesof(/obj/item/translator_chip))
```
Стоит сократить

2024-10-31 17:12 UTC, Antoonij commented on code/modules/surgery/organs/voice_translator.dm
> +	stored_language = TRAIT_WINGDINGS //weird but works
А так ли стоит миксовать трейты с языками? Выглядит не очень.

2024-10-31 17:20 UTC, Samirakis commented on code/modules/surgery/organs/voice_translator.dm
> +	stored_language = TRAIT_WINGDINGS //weird but works
Спасибо за ревью. Я могу перенести трейт в отдельную переменную внутри чипа. Просто насколько это лучше(создавание переменной для целого одного случая) - хз. Если думаешь что лучше или есть другие идеи - сделаю, не вопрос.

2024-11-02 06:57 UTC, Antoonij commented on code/modules/surgery/organs/voice_translator.dm
> +		user.balloon_alert(user, "учучшение не подходит!")
```suggestion
		user.balloon_alert(user, "улучшение не подходит!")
```

2024-11-02 07:09 UTC, Antoonij approved these changes, later dismissed
Now it's looks more better

2024-11-12 17:00 UTC, Den109G commented on code/modules/surgery/organs/augments_internal.dm
> -/obj/item/organ/internal/cyberimp/brain/speech_translator/clown
А почему убран имплант, если в предложке нет такого?

2024-11-12 17:07 UTC, Samirakis commented on code/modules/surgery/organs/augments_internal.dm
> -/obj/item/organ/internal/cyberimp/brain/speech_translator/clown
Потому что весь функционал этого импланта перемещён в новые импланты-переводчики и даже больше, так что этот более не требуется от слова совсем

2024-11-12 17:44 UTC, Den109G commented on code/modules/surgery/organs/voice_translator.dm
> +		return check_install_chip(user, chip)
Установку чипа лучше в одноимённом проке делать, а не в проверке "можно ли установить".
```suggestion
		return install_chip(user, chip)
```

2024-11-12 17:44 UTC, Den109G commented on code/modules/surgery/organs/voice_translator.dm
> +/obj/item/organ/internal/cyberimp/mouth/translator/proc/install_chip(mob/living/user, obj/item/translator_chip/chip)
К комментарию выше - добавь сюда проверку, что можно установить чип.

2024-11-12 17:54 UTC, Samirakis commented on code/modules/surgery/organs/voice_translator.dm
> +		return check_install_chip(user, chip)
Придумал кое-чего, сейчас сделаю иначе, спасибо

2024-11-12 18:26 UTC, Samirakis commented on code/modules/surgery/organs/voice_translator.dm
> +		return check_install_chip(user, chip)
Сделал получше, можешь проверять

2024-11-12 19:56 UTC, Den109G commented on code/modules/surgery/organs/voice_translator.dm
> +		decoder.Grant(owner)
Может весь этот код в чип засунуть? А то только один чип использует эту переменную.
Как-нибудь:
```dm
/obj/item/translator_chip/proc/install(arguments)
   return
   
/obj/item/translator_chip/proc/remove(arguments)
   return
   
/obj/item/translator_chip/wingdings/install(arguments)
   give_gaster_blaster()
   return
   
/obj/item/translator_chip/wingdings/install(arguments)
   takeaway_gaster_blaster()
   return
```
Ну и там где `handle_wingdings_chip()` - поменять на `chip.install()`.

2024-11-12 19:56 UTC, Den109G commented on code/modules/surgery/organs/voice_translator.dm
> +	update_chip(available_languages[answer])
Выглядит костыльно. Почему просто не удалять этот "всех мастей" чип и давать нормальный, обычный?

2024-11-12 20:04 UTC, Samirakis commented on code/modules/surgery/organs/voice_translator.dm
> +		decoder.Grant(owner)
Проходил уже этот момент с Фондом. Прок update_chip, который юзается при активации НЕ раундстарт чипа, не меняет тип чипа, соответственно в таком случае получить дешифратор вингдингс станет невозможно, потому что chip/wingdings/install() не будет вызван, вместо него уткнёмся в chip/install()

2024-11-12 20:05 UTC, Samirakis commented on code/modules/surgery/organs/voice_translator.dm
> +	update_chip(available_languages[answer])
Удалять и пересоздавать не люблю, но вообще могу и так сделать

2024-11-13 08:50 UTC, Den109G commented on code/modules/surgery/organs/eyes.dm
> +#define EXAMINE_INSTANT	0 // 0 seconds
Это по хорошему в файл с дефайнами переписать. А то в этом файле не используется, сложно будет искать переменную.

2024-11-13 08:50 UTC, Den109G commented on code/__DEFINES/traits/declarations.dm
> +#define TRAIT_WEAK_PULLING "weak_pulling"
В `/code/_globvars/traits.dm` поставь все дефайны трейтов в список. Соблюдай алфавитный порядок.

2024-11-13 08:50 UTC, Den109G commented on code/modules/surgery/organs/augments_internal.dm
> -/obj/item/organ/internal/cyberimp/brain/speech_translator/clown
А клоунский имплант?

2024-11-13 08:50 UTC, Den109G commented on code/modules/surgery/organs/lungs.dm
> +		target.physiology.oxy_mod += 0.5
Есть способы, потерять трейт "улучшенные импланты" до извлечения органов (пр. генокрад, мутаген).
Поменяй проверку на `HAS_TRAIT_FROM(target, TRAIT_CYBER_IMPROVED, UNIQUE_TRAIT_SOURCE(src))` и давай эту черту при установке.

2025-01-01 13:05 UTC, PlayerUnknown14 requested changes
Доработать перевод.

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/mob/living/carbon/human/species/grey.dm
> +		to_chat(H, span_notice("В связи с Ваш[translator_pref ? "им недугом" : "ей ответственной работой"], у Вас уже есть установленный чип Вингдингс."))
```suggestion
		to_chat(H, span_notice("В связи с ваш[translator_pref ? "им недугом" : "ей ответственной работой"], у вас уже есть установленный чип Вингдингс."))
```
"Вы" пишем с маленькой.

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/research/designs/medical_designs.dm
> +	desc = "Имплант для перевода псионической речи греев в более понятные звуковые волны. Разработан специально для греев."
```suggestion
	desc = "Имплант для перевода псионической речи греев в более понятные для других гуманоидов звуковые волны. Разработан специально для греев."
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/autoimplanter.dm
> +		to_chat(user, span_warning("В устройстве уже установлен другой киберимплант."))
```suggestion
		balloon_alert(user, "слот для киберимпланта занят!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/autoimplanter.dm
> +	to_chat(user, span_notice("Вы установили [I.name] в автоимплантер."))
```suggestion
	balloon_alert(user, "киберимплант установлен")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +	)
```suggestion
	ru_names = list(
	    NOMINATIVE = "ретранслятор псионического голоса",
	    GENITIVE = "ретранслятора псионического голоса",
	    DATIVE = "ретранслятору псионического голоса",
	    ACCUSATIVE = "ретранслятор псионического голоса",
	    INSTRUMENTAL = "ретранслятором псионического голоса",
	    PREPOSITIONAL = "ретрансляторе псионического голоса",
	)
```
Перенести `ru_names` под `desc` здесь и ниже - кодстайл.

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +		user.balloon_alert(user, "закройте крышку переводчика!")
```suggestion
		balloon_alert(user, "крышка открыта!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +			user.balloon_alert(user, "модуль уже установлен!")
```suggestion
			balloon_alert(user, "уже установлено!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +		user.balloon_alert(user, "сначала открутите крышку!")
```suggestion
		balloon_alert(user, "крышка закручена!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +		user.balloon_alert(user, "устройство нельзя улучшить!")
```suggestion
		balloon_alert(user, "не подлежит улучшению!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +		user.balloon_alert(user, "улучшение не подходит!")
```suggestion
		balloon_alert(user, "несовместимо!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +	user.balloon_alert(user, "модуль расширения установлен!")
```suggestion
	balloon_alert(user, "установлено")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +		user.balloon_alert(user, "пусто!")
```suggestion
		balloon_alert(user, "пусто!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +			user.balloon_alert(user, "крышка закрыта!")
```suggestion
			balloon_alert(user, "крышка закрыта!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +			user.balloon_alert(user, "чип уже установлен!")
```suggestion
			balloon_alert(user, "уже установлено!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +	user.balloon_alert(user, "крышка [open ? "откручена" : "закручена"]")
```suggestion
	balloon_alert(user, "крышка [open ? "откручена" : "закручена"]")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +		user.balloon_alert(user, "нечего доставать!")
```suggestion
		balloon_alert(user, "нечего доставать!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +		user.balloon_alert(user, "сперва достаньте чипы!")
```suggestion
		balloon_alert(user, "мешают чипы!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +	user.balloon_alert(user, "улучшение извлечено")
```suggestion
	balloon_alert(user, "улучшение извлечено")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +	to_chat(owner, span_warning("[capitalize(declent_ru(NOMINATIVE))] временно вышел из строя от воздействия ЭМИ!"))
```suggestion
	to_chat(owner, span_warning("[capitalize(declent_ru(NOMINATIVE))] временно вышел из строя из-за воздействия ЭМИ!"))
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +		owner.balloon_alert(owner, "дешифратор не работает!")
```suggestion
		balloon_alert(owner, "дешифратор не работает!")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +	owner.balloon_alert(owner, "дешифратор [translator.can_wingdings ? "включен" : "выключен"]")
```suggestion
	balloon_alert(owner, "дешифратор [translator.can_wingdings ? "включён" : "выключен"]")
```

2025-01-01 13:05 UTC, PlayerUnknown14 commented on code/modules/surgery/organs_internal.dm
Хирургические операции перевести.

2025-01-01 13:19 UTC, Samirakis commented on code/modules/surgery/organs_internal.dm
Все операции переводить не буду. А по поводу перевода своей части - мне говорили так не делать: либо всё переводить, либо ничего. Если скажешь обратное - переведу надписи в своём коде

2025-01-01 13:22 UTC, Samirakis commented on code/modules/surgery/organs_internal.dm
По поводу убирания user.balloon_alert(user -> balloon_alert(user = этого не будет. Поскольку balloon_alert как прок существует на мобах, и вызвать его на переводчике просто невозможно, код не скомпилится.

2025-01-02 06:28 UTC, PlayerUnknown14 commented on code/modules/surgery/organs_internal.dm
Насчёт балунов понял, затупил.

Добавлять в игру новый контент на английском - плохо, т.к. создаёт ещё больше работы для локализаторов. Переводи свои операции, все не нужно.

2025-01-02 08:42 UTC, Samirakis commented on code/modules/surgery/organs_internal.dm
По поводу операций распишу точнее, чтобы ты лучше понимал, как там всё работает и смог решить однозначно:
Операция - последовательность шагов операции(например, надрез скальпелем, использование гемостата), сами шаги операции прописываются отдельно в коде и лишь вписываются для каждой операции. То есть для всех операций, использующих стандартный надрез скальпелем, используется один и тот же шаг надреза скальпеля

Я создал операцию, состоящую из 5-6 шагов, из этих шагов именно новых было написано 2 штуки. Если я сейчас переведу все 5-6 шагов у моей операции, то у нас появится ситуация, когда условное вскрытие груди будет переведено наполовину, ибо я переведу условно скальпель и гемостат, а вот ретрактор, пила итд останутся на  англ, из-за чего у многих операций начнут смешиваться языки

Именно по этой причине я не переводил операции в принципе, ибо это нужно делать комплексно сразу, как я считаю

Опять таки, решение за тобой. Если скажешь - я переведу все шаги, входящие в добавленную мной операцию (либо лишь те 2 новых шага(откручивание/закручивание крышки и манипуляция с чипами), если скажешь)

2025-01-02 09:32 UTC, PlayerUnknown14 commented on code/modules/surgery/organs_internal.dm
Понял-принял, оставляй так, потом локализаторы сядут и нормально все операции переведут.

2025-01-02 09:40 UTC, Samirakis commented on code/modules/surgery/organs_internal.dm
Хорошо. Всё остальное сделал, перечитай бегло если нужно. Спасибо за ревью!

2025-01-02 10:33 UTC, PlayerUnknown14 requested changes
Последние штрихи перевода.

2025-01-02 10:33 UTC, PlayerUnknown14 commented on code/modules/mob/living/carbon/human/species/grey.dm
> +			to_chat(H, span_danger("[water_damage > 30 ? "Вы чувствуете ужасающую боль по всему телу!" : "Вода жжёт вас!"]"))
```suggestion
			to_chat(H, span_danger("[water_damage > 30 ? "Вы чувствуете ужасающую боль после контакта с водой!" : "Вода жжёт вас!"]"))
```

2025-01-02 10:33 UTC, PlayerUnknown14 commented on code/modules/surgery/organs/voice_translator.dm
> +		)
```suggestion
	)
```

2025-01-02 11:43 UTC, PlayerUnknown14 submitted a review, later dismissed
Теперь с локализацией порядок.

2025-01-06 00:42 UTC, PlayerUnknown14 approved these changes

2025-01-06 18:29 UTC, merged