perevod: bots localization
ss220-space/Paradise pull request #6130
Opened 2024-11-05 12:35 UTC by PlayerUnknown14

## Описание
Перевод всех описаний, сообщений и интерфейса ботов, добавление балун-алёртов и QOL-улучшения по мелочи.
В данный момент готовы:
* Протобом (Protobot) - родитель для всех ботов
* Медбот (Medbot)
* Ремонтный бот (Floorbot)
* Охранный бот (Secbot aka Securitron) 

## Ссылка на предложение/Причина создания ПР
Локализация, с одобрения главлока - Вани.

## Демонстрация изменений
Интерфейс медбота:
![image](https://github.com/user-attachments/assets/a8a93c62-76ff-405a-84f0-88e7f215bc17)
Интерфейс флурбота:
![image](https://github.com/user-attachments/assets/5d11af65-2379-448b-9d32-98dec798b350)
Интерфейс секбота:
![image](https://github.com/user-attachments/assets/bb5e1470-f3bd-426f-9de3-44295593d2c8)

## Тесты
Запуск локалки, спаун ботов, тык-тык в интерфейс, тык-тык реплики - проблем не замечено.

2024-11-09 17:27 UTC, pilygun commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +				balloon_alert(user, "вам нужна робо-нога для продолжения сборки")
все балуны должны быть не длиннее 3 слов. Тут же довольно много всего понаписано лучше заменить на ту чат это и все что ниже связанное со сборкой. Можно добавить ДОПОЛНИТЕЛЬНО к этому тексту балун "неверная деталь" или типо того

2024-11-09 17:27 UTC, pilygun commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +		balloon_alert(user, "вы не можете завершить сборку [ismob(loc) ? "в инвентаре" : "здесь"]")
тоже самое + балуны не должны использовать трейты что бы экран сильно не захламлять. Только заранее написанные слова

2024-11-09 17:27 UTC, pilygun commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +				balloon_alert(user, "вы не можете завершить сборку [ismob(loc) ? "в инвентаре" : "здесь"]")
ну собственно да балунов у тебя слишком много и они тут не нужны. весь процесс сборки перевести в to_chat

2024-11-09 17:30 UTC, PlayerUnknown14 commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +				balloon_alert(user, "вам нужна робо-нога для продолжения сборки")
А разве балуны на 5 слов вместо 3 - есть проблема? Потестил, в игре нормас выглядит, экран не захламляется. Тоже думал на ту_чат вернуть, но конкретно с моментом про длину балунов не согласен.

2024-11-09 17:33 UTC, pilygun commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +				balloon_alert(user, "вам нужна робо-нога для продолжения сборки")
> А разве балуны на 5 слов вместо 3 - есть проблема? Потестил, в игре нормас выглядит, экран не захламляется. Тоже думал на ту_чат вернуть, но конкретно с моментом про длину балунов не согласен.

Скины кинь балунов глянуть

2024-11-09 17:33 UTC, pilygun commented
@Antoonij Глянь ПР, есть ли с стороны кода какие вопросы?

2024-11-10 03:33 UTC, PlayerUnknown14 commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +				balloon_alert(user, "вам нужна робо-нога для продолжения сборки")
Что-то такое.
![image](https://github.com/user-attachments/assets/89809b98-5b39-4e46-a5d1-314c8e696e2d)

2024-11-10 04:38 UTC, PlayerUnknown14 commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +				balloon_alert(user, "вы не можете завершить сборку [ismob(loc) ? "в инвентаре" : "здесь"]")
Поменял на ту_чат.

2024-11-10 04:38 UTC, PlayerUnknown14 commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +		balloon_alert(user, "вы не можете завершить сборку [ismob(loc) ? "в инвентаре" : "здесь"]")
Поменял на ту_чат.

2024-11-10 04:39 UTC, PlayerUnknown14 commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +				balloon_alert(user, "вам нужна робо-нога для продолжения сборки")
Сменил на ту_чат.

2024-11-13 09:49 UTC, Daeberdir commented on code/modules/mob/living/simple_animal/bot/syndicate.dm
> +	)
Сентри - "Вартовий". Сам бот ничего общего с турелями вообще не имеет... Это бот-часовой. Спрайт у него вообще похож на дарк гигакса.

2024-11-13 09:50 UTC, Daeberdir commented on code/modules/mob/living/simple_animal/bot/syndicate.dm
> +	window_name = "Интерфейс Бота Синдиката"
`desc = "Охранный робот Синдиката."`
Реши, боты это или роботы. Унифицируй названия.

2024-11-13 12:04 UTC, PlayerUnknown14 commented on code/modules/mob/living/simple_animal/bot/syndicate.dm
> +	)
Ошибка, поправил.

2024-11-13 12:04 UTC, PlayerUnknown14 commented on code/modules/mob/living/simple_animal/bot/syndicate.dm
> +	window_name = "Интерфейс Бота Синдиката"
Отныне у нас только роботы.

2024-11-13 14:26 UTC, pilygun approved these changes, later dismissed

2024-11-15 12:49 UTC, pilygun commented
@Vladisvell Все вроде сделано что хотели

2024-11-17 12:14 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/cleanbot.dm
> +		balloon_alert(user, "вы покрасили чистобота")
вот тут нужно использовать ru_name

2024-11-17 12:14 UTC, Antoonij commented on tgui/packages/tgui/interfaces/BotClean.js
> +          {locked ? 'разблокировать' : 'заблокировать'} этот интерфейс.
```suggestion
          Проведите своей ID-картой, чтобы
          {locked ? 'разблокировать' : 'заблокировать'} этот интерфейс.
```

2024-11-17 12:14 UTC, Antoonij commented on tgui/packages/tgui/interfaces/BotSecurity.js
> +          {locked ? 'разблокировать' : 'заблокировать'} этот интерфейс.
```suggestion
          Проведите своей ID-картой, чтобы
          {locked ? 'разблокировать' : 'заблокировать'} этот интерфейс.
```

2024-11-17 12:20 UTC, PlayerUnknown14 commented on code/modules/mob/living/simple_animal/bot/cleanbot.dm
> +		balloon_alert(user, "вы покрасили чистобота")
Не нужно.

2024-11-18 07:50 UTC, Antoonij requested changes

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +	visible_message("<span class='userdanger'>[capitalize(declent_ru(NOMINATIVE))] разлетается на части!</span>")
```suggestion
	visible_message(span_userdanger("[capitalize(declent_ru(NOMINATIVE))] разлетается на части!"))
```

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +			to_chat(user, span_notice("Вы прикрепили анализатор здовроья к аптечке."))
```suggestion
			to_chat(user, span_notice("Вы прикрепили анализатор здовровья к аптечке."))
```

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +		to_chat(user, span_notice("Вы вырезали дополнительные отверствия в заготовке охранного робота."))
```suggestion
		to_chat(user, span_notice("Вы вырезали дополнительные отверстия в заготовке охранного робота."))
```

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +		to_chat(user, span_notice("Вы заварили лишние отверствия в заготовке охранного робота."))
```suggestion
		to_chat(user, span_notice("Вы заварили лишние отверстия в заготовке охранного робота."))
```

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +		to_chat(user, span_notice("Вы заварили лишние отверствия в заготовке охранного робота."))
такого слова в языке нет

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +			to_chat(user, span_notice("Вы завершили сборку Генерала Грифски."))
Лучше вернуть часть тучата про военные преступления

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +		visible_message("[capitalize(declent_ru(NOMINATIVE))] не даёт дотронуться до себя [user]!")
лучше восстановить изначальный контекст, что отражается атака, а то будет выглядеть странно.

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/medbot.dm
> +			balloon_alert(usr, "ёмкость извлечена")
Часть кода с 268 по 270 поместить выше чем форсмув,  после балуналерта else, в самом else форсмув

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/mulebot.dm
> +		balloon_alert(user, "сначала откройте панель техобслуживания")
сократить, а то слишком длинный балуналерт

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/mulebot.dm
> +	balloon_alert(user, "вы вынули батарею из слота")
также сократить.  И пройдись по всем остальным, связанным с техобслуживанием

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +		to_chat(usr, "<span class='warning'>Интерфейс [declent_ru(GENITIVE)] не отвечает!</span>")
```suggestion
		to_chat(usr, span_warning("Интерфейс [declent_ru(GENITIVE)] не отвечает!"))
```

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/mulebot.dm
> +		balloon_alert(user, "вы [locked ? "заблокировали" : "разблокировали"] панель управления")
Сократить, можно убрать управления.

2024-11-18 07:50 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +	set name = "Переключить проблесковые маячки"
Имя верба не нужно переводить, лучше оставить английское (оно и короткое)

2024-11-21 06:39 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +			balloon_alert(usr, "вы слишком пацифистичны для этого!")
длинный баллун

2024-11-21 06:48 UTC, PlayerUnknown14 commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +			balloon_alert(usr, "вы слишком пацифистичны для этого!")
5 слов, не длинный.

2024-11-27 14:31 UTC, pilygun submitted a review, later dismissed

2024-11-27 14:51 UTC, Antoonij commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +	balloon_alert(user, "вы прикрепили сигнальное устройство к шлему")
```suggestion
	balloon_alert(user, "сигнальное устройство прикреплено")
```
Слишком длинный

2024-11-27 14:53 UTC, Antoonij approved these changes
Теперь выглядит хорошо

2024-12-02 12:01 UTC, pilygun approved these changes

2024-12-02 12:06 UTC, merged