add: New robust security backpack
ss220-space/Paradise pull request #6135
Opened 2024-11-06 09:22 UTC by Mahimka42

## Описание
Добавляет новый ультрамегакрутой рюкзак с мигалками

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/1264462031189311599/1265668941959794721

## Тесты
Все проверил, все работает.

2024-11-06 09:56 UTC, Antoonij requested changes

2024-11-06 09:56 UTC, Antoonij commented on code/game/objects/items/weapons/storage/backpack.dm
> +		sleep(1.5 SECONDS)
Неплохой такой цикл. Это нужно сделать через залупленный, останавливаемый таймер.

2024-11-10 15:00 UTC, Mahimka42 commented on code/game/objects/items/weapons/storage/backpack.dm
> +		sleep(1.5 SECONDS)
честно, я понятия не имею как это сделать. поэтому, могу ли я сделать костыль как с шлемом правосудия просто добавив таймер?

2024-11-10 15:01 UTC, Mahimka42 commented on code/game/objects/items/weapons/storage/backpack.dm
> +		sleep(1.5 SECONDS)
а нет, не могу

2024-11-10 15:09 UTC, Mahimka42 commented on code/game/objects/items/weapons/storage/backpack.dm
> +		sleep(1.5 SECONDS)
А можно вообще без этого? Шлем правосудия также работает

2024-11-10 16:15 UTC, Antoonij requested changes

2024-11-10 16:15 UTC, Antoonij commented on code/game/objects/items/weapons/storage/backpack.dm
> +		sleep(1.5 SECONDS)
Нет, снести изменения с последнего твоего коммита. While и sleep убрать.

Нужно делать следующее - в объявлении своего рюкзака сделать переменную к примеру var/timer

далее в проке turn_on() сделать так - 
timer = addtimer(CALLBACK(GLOBAL_PROC, /proc/playsound, loc, 'sound/items/weeoo1.ogg', 100, FALSE, 4), 1.5 SECONDS, TIMER_STOPPABLE | TIMER_DELETE_ME)

Далее в проке turn_off делаем чек, if(timer), в этом чеке делаем так:
deltimer(timer)
timer = null

2024-11-10 16:20 UTC, Mahimka42 commented on code/game/objects/items/weapons/storage/backpack.dm
> +		sleep(1.5 SECONDS)
понял

2024-11-10 16:25 UTC, Antoonij commented on code/game/objects/items/weapons/storage/backpack.dm
> +		sleep(1.5 SECONDS)
И небольшое дополнение. timer = addtimer(CALLBACK(GLOBAL_PROC, /proc/playsound, loc, 'sound/items/weeoo1.ogg', 100, FALSE, 4), 1.5 SECONDS, TIMER_STOPPABLE | TIMER_DELETE_ME | TIMER_LOOP) - т.е добавили битфлаг таймер луп и в проке turn_on присваивание переменной timer таймера нужно делать под чеком if(!timer)

2024-11-11 12:13 UTC, Mahimka42 commented on code/game/objects/items/weapons/storage/backpack.dm
> +		sleep(1.5 SECONDS)
все сделал как ты сказал. только я одного не понял. зачем? там типо задержка эта перед звуком сирены появилась еще.

https://github.com/user-attachments/assets/ef3b4cb0-48a3-4309-907f-a9e6eea54625

2024-11-11 13:06 UTC, Antoonij commented on code/game/objects/items/weapons/storage/backpack.dm
> +		sleep(1.5 SECONDS)
while и sleep  в этом случае использовать ни в коем случае нельзя. И я немного ошибся, сейчас сам уже доработаю на залупленую музыку и будет все в порядке.

2024-11-11 14:50 UTC, Antoonij approved these changes, later dismissed
Теперь, когда дело через саундлуп - выглядит хорошо.

2024-11-11 16:22 UTC, merged