qol: Sound for pacman
ss220-space/Paradise pull request #6149
Opened 2024-11-09 07:24 UTC by Rafnik02

## Описание

Добавляет новые звуки для пакманов:
Включение
Мид
Конец
## Ссылка на предложение/Причина создания ПР

Наверное не надо?

## Демонстрация изменений

https://github.com/user-attachments/assets/eebcf6d4-f91c-4fb3-92e7-9851e00e0baf

## Тесты

 
Зашёл в игру, нашёл пакман. Запитал пакман плазмой, включил пакман, послушал, выключил пакман.

2024-11-09 08:00 UTC, Vladisvell approved these changes, later dismissed
Звучит интересно

2024-11-09 12:23 UTC, Antoonij commented on code/modules/power/port_gen.dm
> +/obj/machinery/power/port_gen/Initialize()
```suggestion
/obj/machinery/power/port_gen/Initialize(mapload)
```

2024-11-09 15:35 UTC, Rafnik02 commented on code/modules/power/port_gen.dm
> +/obj/machinery/power/port_gen/Initialize()
А что это добавит?

2024-11-09 16:14 UTC, Antoonij commented on code/modules/power/port_gen.dm
> +/obj/machinery/power/port_gen/Initialize()
> А что это добавит?

Не стоит пропускать параметры функций

2024-11-09 16:15 UTC, Antoonij approved these changes

2024-11-09 16:41 UTC, Antoonij requested changes
Недосмотрел. Луп должен начинаться 1 раз и завершаться также 1 раз, этого не должно происходить постоянно в процессинге. Сделай начало лупа в моменте, где генератор включается, а где он выключается - остановить луп.

2024-12-30 11:52 UTC, BeebBeebBoob commented
И всё же... предложку стоит сделать

2024-12-30 20:58 UTC, pilygun approved these changes
Даже на это предложка была, просто автор не менял описание ПРа

2024-12-31 09:30 UTC, Rafnik02 commented
> Даже на это предложка была, просто автор не менял описание ПРа

Была, но мне сказали не надо. Так что я удалил предложку. Прошу не ссориться.

2025-01-05 10:50 UTC, merged