add: fishing
ss220-space/Paradise pull request #6150
Opened 2024-11-09 08:24 UTC by NightDawnFox

## Описание
Эмм ну я начинаю делать рыбалку. До завершения еще где-то дохуя, но чтобы не потерять, вкину.

## Ссылка на предложение/Причина создания ПР

## Демонстрация изменений

## Тесты

2025-02-06 15:40 UTC, NightDawnFox commented
@PiotrTheTchaikowsky как дела

2025-02-12 18:39 UTC, PiotrTheTchaikowsky commented
> @PiotrTheTchaikowsky как дела

Ой блять 
![Zorp](https://github.com/user-attachments/assets/d890a8fd-9821-4e8e-a1ac-e7976b21b8cc)

2025-02-12 18:55 UTC, NightDawnFox commented
> > @PiotrTheTchaikowsky как дела
> 
> Ой блять ![Zorp](https://private-user-images.githubusercontent.com/139582597/412565231-d890a8fd-9821-4e8e-a1ac-e7976b21b8cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkzODY3OTUsIm5iZiI6MTczOTM4NjQ5NSwicGF0aCI6Ii8xMzk1ODI1OTcvNDEyNTY1MjMxLWQ4OTBhOGZkLTk4MjEtNGU4ZS1hMWFjLWU3OTc2YjIxYjhjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxMlQxODU0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzVjZjIzYWE0NjVmNjlkMDg0NDM2MmE5ODFkY2QxOTVkN2ZmYzY1YWRmZjBmMjNkZmQyOWVkNTQzM2VhN2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6Llx2tlKvAdD_wu5CM93WTmQ3WO8cHejzr1DJ7gfMUw)

ты сам попросил пингануть тебя в ветке чтобы следить.

2025-02-20 13:44 UTC, SAADf603 approved these changes, later dismissed
maps cheked

2025-02-21 07:08 UTC, PlayerUnknown14 submitted a review, later dismissed

2025-02-21 07:09 UTC, PlayerUnknown14 commented
![image](https://github.com/user-attachments/assets/363960b1-6f67-46ca-bb60-a1062052ee21)

2025-02-21 09:34 UTC, BeebBeebBoob requested changes
Я ещё не закончил

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/game/objects/effects/spawners/random_spawners.dm
> +	name = "60pc scorched_skull"
не 40pc? `/obj/item/clothing/head/scorched_skull = 40`

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/datums/components/simple_fishing.dm
> +			catchable_fish += shore_fish
Для каждого тайла лавы, каждый новый инит с калькуляцией какие рыбы можно ловить... Плохая оптимизация.

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/datums/components/simple_fishing.dm
> +			catchable_fish += shore_fish
Я думаю можно и без компонента обойтись. Ловить можно только в лаве, поэтому просто дай прок на deep_water дабы указывать, какие тип рыб ты можешь ловить
```dm
lava/proc/get_fish()
	if(deep_water)
		return pick(GLOB.deep_fish) // На той стороне кода, пусть new ретурнатый тип
	else
		return pick(GLOB.shore_fish)
```

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	origin_tech = "materials=4;biotech=5"
Как-то жирно по тех?

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/fishing_rod.dm
> +		PREPOSITIONAL = "старой доброй удочке"
Старая добрая удочка но спрайт показывает его идеальное состояние. Может подправить и просто "Удчока"?

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/fishing_rod.dm
> +		PREPOSITIONAL = "удочке"
А вот здесь наоборот, старая удочка

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/fishing_rod.dm
> +	var/datum/component/simple_fishing/fish_component = target.GetComponent(/datum/component/simple_fishing)
Как я ранее писал про компонент, Тут можно проверку на лава турф, уточнение переменной deep_water а далее ловля рыбы

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/game/objects/items/weapons/whetstone.dm
> +	uses = -1
Уверен что это не будет абузным своровать на станцию?

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/game/objects/items.dm
> +	SEND_SIGNAL(src, COMSIG_ATOM_TEMPORARY_ANIMATION_START, 3)
Надо уточнить `COMSIG_ITEM_DROP_PRE_ANIMATE`

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/modules/mining/ash_walkers/ash_rune.dm
> +
Можно сюда переместить всё связанное с `ash_rune_centre` из 70 строки

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/modules/mining/ash_walkers/torch_holder.dm
> +					prot = (G.max_heat_protection_temperature > 360)
может fakel.get_heat()? У тёмных перчей 1500, а сам факел даёт 1000. Думаю разумнее так
+ это пример https://github.com/ss220-space/Paradise/blob/master220/code/game/machinery/doors/airlock_types.dm#L198
```suggestion
					prot = (G.max_heat_protection_temperature > fakel.get_heat())
```

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/modules/mining/ash_walkers/torch_holder.dm
> +/obj/machinery/torch_holder
машинарии?

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/modules/mob/living/carbon/human/species/unathi.dm
>  /datum/action/innate/anvil_finder
думаю и сам датум стоит переименовать

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/modules/mob/living/carbon/carbon.dm
> +		if(time_to_eat > 0 && !do_after(user, time_to_eat, max_interact_count = 1))
Наконец-то. Теперь нельзя просто засунуть целую пиццу в рот за секунду

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/modules/mob/living/simple_animal/hostile/mining/gutlunch.dm
> +		. += span_notice("[src]'s [udder.name] is currently has [udder.reagents.total_volume] units of milk in it")
По взгляду можно понять сколько внутри унции молока. Глаза бога в помойку

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/modules/mob/living/simple_animal/hostile/mining/gutlunch.dm
> +		. += span_notice("[src]'s [udder.name] is currently has [udder.reagents.total_volume] units of milk in it")
Если будет интерес, то можно примерно там на глаз дать

2025-02-21 09:34 UTC, BeebBeebBoob commented on code/modules/research/designs/mining_designs.dm
> +	materials = list(MAT_METAL = 1000, MAT_TITANIUM = 1500)
Очень дешёвый. 4X цена пожалуйста.

2025-02-21 09:48 UTC, NightDawnFox commented on code/game/objects/effects/spawners/random_spawners.dm
> +	name = "60pc scorched_skull"
Правка делалась впопыхах. Сейчас поправлю..

2025-02-21 09:49 UTC, NightDawnFox commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	origin_tech = "materials=4;biotech=5"
Да нет, это базовые технологии, закрываемые в первые 10 минут раунда. Такие же технологии дают внутренние органы, не вижу особых проблем. 
Особенно учитывая, что для получения этих зубов нужно убить минимум три или четыре голиафа (для лодки).

2025-02-21 09:53 UTC, NightDawnFox commented on code/game/objects/items/weapons/whetstone.dm
> +	uses = -1
я забыл поправить на конечное пользование (с соглашением со старыми авторами)

2025-02-21 10:10 UTC, NightDawnFox commented on code/modules/mob/living/simple_animal/hostile/mining/gutlunch.dm
> +		. += span_notice("[src]'s [udder.name] is currently has [udder.reagents.total_volume] units of milk in it")
Это больше QoL, потому что наугад с этим работать проблемно и не интересно. Их доить - и так непопулярное занятие.

2025-02-21 10:15 UTC, NightDawnFox commented on code/modules/mining/ash_walkers/torch_holder.dm
> +/obj/machinery/torch_holder
Ради системы процессинга сделал + делал, опираясь на код ламп, ибо в целом они похожи по принципу работы

2025-02-21 10:17 UTC, NightDawnFox commented on code/game/objects/items.dm
> +	SEND_SIGNAL(src, COMSIG_ATOM_TEMPORARY_ANIMATION_START, 3)
я не знаю что это...

2025-02-21 11:07 UTC, BeebBeebBoob commented on code/modules/mining/ash_walkers/torch_holder.dm
> +/obj/machinery/torch_holder
Ну... Т.к. там нету ничего активного кроме пассивного сгорания топлива, можно заменить на таймер.
Если заранее потушить, таймер удаляется и записывается сколько там осталось смотря на время старта и конца. Сам таймер это истечение топлива.
Машинарии просто не подходит + ты используешь процесс `SSobj` хотя у всех машинарии свой `SSmachines`
Ну очень не подходит под это
Прошу, переделай в `/obj/structure`, а с процессом по возможности как с компонентами дабы не жрал цпушку

2025-02-23 08:09 UTC, merged