add: Sound for SM and new spite и perevod. Make SM great again
ss220-space/Paradise pull request #6154
Opened 2024-11-10 15:17 UTC by Rafnik02

## Описание

Буду благодарен за помощь.

Добавляет около 40 новых звуков для окружения к СМу(ожидается)

Изменяет спрайты на новые.

Теперь у СМа будет гирлянда на новый год.

Переводит СМ
## Ссылка на предложение/Причина создания ПР

Ожидается

## Демонстрация изменений

![Снимок экрана 2024-11-09 232310](https://github.com/user-attachments/assets/d03c40ba-460c-48dd-b6a6-3f463809aea9)

## Тесты

Новый спрайт потестил. Спрайт гирлянд не знаю как.

2024-11-10 20:29 UTC, littleboobs commented on code/modules/power/supermatter/supermatter.dm
> +	desc = "Странный полупрозрачный и переливающийся кристалл, который выглядит так, будто когда-то был частью более крупной структуры. <span class='danger'>У вас начинает болеть голова, просто глядя на
```suggestion
	desc = "Странный полупрозрачный и переливающийся кристалл, который выглядит так, будто когда-то был частью более крупной структуры. span_danger(У вас начинает болеть голова, просто глядя на это.)"
```

2024-11-13 11:28 UTC, Rafnik02 commented on code/modules/power/supermatter/supermatter.dm
> +	desc = "Странный полупрозрачный и переливающийся кристалл, который выглядит так, будто когда-то был частью более крупной структуры. <span class='danger'>У вас начинает болеть голова, просто глядя на
мне кажется это работать не будет. Потому что тут дефайн как текст.

2024-11-13 15:15 UTC, Rafnik02 commented
да блять

2024-11-21 13:47 UTC, pilygun submitted a review, later dismissed
К переводу нареканий нет

2024-11-21 14:58 UTC, Antoonij requested changes

2024-11-21 14:58 UTC, Antoonij commented on code/modules/power/supermatter/supermatter_special_effects.dm
> +		return
переделать на кулдаун (см. COOLDOWN_DECLARE)

2024-11-21 14:58 UTC, Antoonij commented on code/modules/power/supermatter/supermatter.dm
> +			add_overlay(mutable_appearance(icon, "santa_hat_shard"))
оверлей шапки хранить в переменной, а не расширять истайпы

2024-11-21 14:58 UTC, Antoonij commented on code/__DEFINES/sound.dm
> +//Звуки окружения СМа
```suggestion
```
Комментарии на русском не стоит использовать

2024-11-21 14:58 UTC, Antoonij commented on code/modules/power/supermatter/supermatter.dm
> +	//Зацикленные звуки
Автодок начинается с 3 слешей, также должен быть отступ после последнего слеша
Русские комментарии в коде использовать не стоит

2024-11-21 14:58 UTC, Antoonij commented on code/modules/power/supermatter/supermatter.dm
> +	///cooldown tracker for accent sounds
```suggestion
	/// cooldown tracker for accent sounds
```

2024-11-21 14:58 UTC, Antoonij commented on code/modules/power/supermatter/supermatter_special_effects.dm
> +	//We play delam/neutral sounds at a rate determined by power and damage
```suggestion
	// We play delam/neutral sounds at a rate determined by power and damage
```

2024-11-21 14:58 UTC, Antoonij commented on code/modules/power/supermatter/supermatter.dm
> +	//Звуки окружения
```suggestion
```
Комментарии на русском использовать не стоит

2024-11-21 14:58 UTC, Antoonij commented on code/modules/power/supermatter/supermatter.dm
> +			. += emissive_appearance(icon, "holiday_lights_shard_e", src, alpha = src.alpha)
хранить оверлей в переменной, а не расширять истайпы

2024-11-21 15:18 UTC, Antoonij commented on code/modules/power/supermatter/supermatter.dm
> +	return NONE
```suggestion
```
Это тут не нужно. Тем более, если не вернуть битфлаги от атакчейна, то произойдет crash

2024-12-30 09:58 UTC, PlayerUnknown14 requested changes
Пара микроправок и будет класс.

2024-12-30 09:58 UTC, PlayerUnknown14 commented on code/modules/power/supermatter/supermatter.dm
> +	desc = "Странный полупрозрачный и переливающийся кристалл, который выглядит так, будто когда-то был частью более крупной структуры. <span class='danger'>У вас начинает болеть голова, просто глядя на
```suggestion
	desc = "Странный полупрозрачный, переливающийся на свету кристалл. Выглядит так, будто когда-то он был частью более крупной структуры." + span_danger("У вас начинает болеть голова от одного только взгляда на это.")
	ru_names = list(
		NOMINATIVE = "осколок суперматерии",
		GENITIVE = "осколка суперматерии",
		DATIVE = "осколку суперматерии",
		ACCUSATIVE = "осколок суперматерии",
		INSTRUMENTAL = "осколком суперматерии",
		PREPOSITIONAL = "осколке суперматерии"
	)
```

2024-12-30 09:58 UTC, PlayerUnknown14 commented on code/modules/power/supermatter/supermatter.dm
> +	desc = "Странный полупрозрачный и переливающийся кристалл."
```suggestion
	desc = "Странный полупрозрачный, переливающийся на свету кристалл."
	ru_names = list(
		NOMINATIVE = "кристалл суперматерии",
		GENITIVE = "кристалла суперматерии",
		DATIVE = "кристаллу суперматерии",
		ACCUSATIVE = "кристалл суперматерии",
		INSTRUMENTAL = "кристаллом суперматерии",
		PREPOSITIONAL = "кристалле суперматерии"
	)
```

2024-12-30 09:58 UTC, PlayerUnknown14 commented on code/modules/power/supermatter/supermatter.dm
> +		. += span_notice("Ослепительные огни, любовно обёрнутые вокруг основания, излучают одновременно праздничное настроение и настоящую радиацию, превращающие кристалл из потенциальной бомбы в новогодню
```suggestion
		. += span_notice("Ослепительные огни, любовно обёрнутые вокруг основания, излучают одновременно праздничное настроение и настоящую радиацию, превращая кристалл из потенциальной бомбы в новогоднюю ёлочку.")
```

2024-12-30 09:58 UTC, PlayerUnknown14 commented on code/modules/power/supermatter/supermatter.dm
> +	examine_list += span_info("На ней находится шапочка деда мороза. Как она попала, не став пылью, остаётся загадкой.")
```suggestion
	examine_list += span_info("На ней находится шапочка Деда Мороза. Как она туда попала, не став пылью, остаётся загадкой.")
```

2025-01-07 11:40 UTC, Rafnik02 commented
Я обязательно доделаю. Но не сейчас

2025-01-08 05:45 UTC, PlayerUnknown14 submitted a review, later dismissed
Локализация в поряде.

2025-03-31 07:53 UTC, closed without merging