add:  New tactical blueshield spray
ss220-space/Paradise pull request #6162
Opened 2024-11-11 15:52 UTC by Mahimka42

## Описание
добавляет новый ультра крутой спрей блющилда

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/617003227182792704/1219014729742159952/1304390766243614780

## Демонстрация изменений
![image](https://github.com/user-attachments/assets/49c574b0-10e1-451e-ac94-64d3c7f7c02c)
![image](https://github.com/user-attachments/assets/6889ff31-aed7-454b-8756-a89d0afa71d8)
![image](https://github.com/user-attachments/assets/ab42317f-ff5a-43ea-aa9a-cca4e4c1143f)

## Тесты
Все видно на скриншотах. Все на своих местах, все работает.

2024-11-11 16:04 UTC, Antoonij commented on code/modules/reagents/reagent_containers/spray.dm
> +    desc = "Бутылочка из прочнейшего темно-синего пластика, распылитель черного цвета украшен тактическим снаряжением, разработана уборочно-силовыми структурами Нанотрейзен для ЗАЧИСТКИ и контроля гр
```suggestion
    desc = "Бутылочка из прочнейшего тёмно-синего пластика, распылитель чёрного цвета украшен тактическим снаряжением, разработана уборочно-силовыми структурами Нанотрейзен для ЗАЧИСТКИ и контроля грязи в помещениях."
```
2 ё и точка в конце деска. Также посоветоваться с локализаторами и улучшить деск.

2024-11-12 15:53 UTC, pilygun submitted a review, later dismissed
К локализации вопросов нету, описание смешнявое

2024-11-17 16:33 UTC, Daeberdir requested changes
Спрайту клинера и спрайту клинера в руках сделать адекватный спрайт. Тоесть, сделать его спреем в уникальной раскраске, но не более. Версию с обвесами можешь оставить, если она будет только в щитспавне. Сам спрей можешь добавить ЕРТшникам и ЦКшный уборочным вендоматам, если уж это по вашему "разработка для уборочно-силовых структур".

2024-11-17 16:33 UTC, Daeberdir commented on code/modules/reagents/reagent_containers/spray.dm
> +    item_state = "cleaner_tactic"
Сделай одно название обоим спрайтам. Так проще будет их в дальнейшем находить.

2024-11-17 16:33 UTC, Daeberdir commented on code/modules/reagents/reagent_containers/spray.dm
> +    desc = "Бутылочка из прочнейшего тёмно-синего пластика, распылитель чёрного цвета украшен тактическим снаряжением, разработана уборочно-силовыми структурами Нанотрейзен для ЗАЧИСТКИ и контроля гр
Тактический клинер звучит ужасно. Переделать. Описание аналогично. Это клинер в чёрно-синей раскраске.

2024-11-17 16:34 UTC, Daeberdir commented
Плюс к этому. С Новы убрать, чтобы не мешать Пиро патчить мапу.

2024-11-17 16:59 UTC, WolfLox commented
Лучше перенести спавн в /obj/structure/closet/secure_closet/blueshield/populate_contents()
Так не нужно будет размещать объект на всех карт. И позволит избежать конфликтов с патчами карт.

2024-11-17 17:00 UTC, Etrnlmelancholy commented
Лампа прав

2024-11-17 17:06 UTC, LiquidPotroh commented
Хз, красивше, когда на столике такое стоит

2024-11-17 17:20 UTC, WolfLox commented
> Спрайту клинера и спрайту клинера в руках сделать адекватный спрайт. Тоесть, сделать его спреем в уникальной раскраске, но не более. Версию с обвесами можешь оставить, если она будет только в щитспавне. Сам спрей можешь добавить ЕРТшникам и ЦКшный уборочным вендоматам, если уж это по вашему "разработка для уборочно-силовых структур".

Почему ты об этом пишешь здесь, а не непосредственно в ветке голосования? У тебя было право проголосовать против и предложка не прошла бы.

2024-11-18 08:14 UTC, Mahimka42 commented
вот как оно выглядит @Vladisvell 
https://github.com/user-attachments/assets/d8bbd9e2-e174-463c-b5d2-7cc29bc6aaca

2024-11-18 13:02 UTC, Vladisvell approved these changes
угарен

2024-11-18 13:02 UTC, merged