Feat: Переработка кошельков
ss220-space/Paradise pull request #617
Opened 2022-01-27 20:49 UTC by Kirozet

## What Does This PR Do

Изменяет иконки бумажников, добавляет отображение ID карт поверх бумажников при наличии.
Бумажник с ID картой почти полностью работает как ID карта.

С кодом помогал(а): Furukai
Иконки рисовал: Surrender(Jack Seligon#4013 discord)

## Images of changes

![image](https://user-images.githubusercontent.com/96671463/151440891-c5a3ce6a-0793-4f8a-a9e9-aa040d0fd69f.png)

## Changelog
:cl:
add: 
Новые иконки бумажников
При нахождении бумажника в слоте ID карты, при наличии ID карты в нём, он полностью работает как ID карта.
На иконке бумажника появляется иконка, соответствующая ID карте в нём.
При наличии нескольких карт выбирается самая первая в бумажнике.
Бумажник, при наличии карты корректно отображается на security HUD и skill HUD очках.
/:cl:

2022-01-28 07:53 UTC, Vallat requested changes

2022-01-28 07:53 UTC, Vallat commented on code/game/data_huds.dm
> +			holder.icon_state = "hudunknown"
```suggestion
	if(wear_id && (!istype(wear_id, /obj/item/storage) || (locate(/obj/item/card/id) in wear_id))
		holder.icon_state = "hud[ckey(wear_id.GetJobName())]"
	else
		holder.icon_state = "hudunknown"
```

2022-01-28 07:53 UTC, Vallat commented on code/game/jobs/access.dm
> +		rankName = WI.front_id.rank
буквы бесплатные а `front_id` может быть нуллом
```suggestion
		var/obj/item/storage/wallet/wallet = src
		assignmentName = wallet.front_id?.assignment
		rankName = wallet.front_id?.rank
```

2022-01-28 07:53 UTC, Vallat commented on code/game/objects/items/weapons/storage/wallets.dm
> +	return FALSE
`item_state`, как оказалось, вообще не нужен
```suggestion
	front_id = locate(/obj/item/card/id) in contents
	if(!front_id)
		name = "[item_color] leather wallet"
		return FALSE
	name = "[item_color] leather wallet with [front_id] on the front"
	return TRUE
```

2022-01-28 07:53 UTC, Vallat commented on code/game/objects/items/weapons/storage/wallets.dm
> +	var/obj/item/storage/wallet/walletid_icon_state = null
Зачем переменной, несущей в себе `icon_state`, объектный путь? Да и в целом смысл от этой переменной, если у нас и так есть `front_id` и мы можем получать `icon_state` от него?
UPD: оказывается это для оверлея иконстейт, господи, ужас. Меняем на это:
```suggestion
	var/image/front_id_overlay = null
```

2022-01-28 07:53 UTC, Vallat commented on code/game/objects/items/weapons/storage/wallets.dm
> +	var/obj/item/storage/wallet/wallet = null
В чем смысл этой переменной? Ссылка на самого себя? Она даже не используется нигде
```suggestion
```

2022-01-28 07:53 UTC, Vallat commented on code/game/objects/items/weapons/storage/wallets.dm
> +			H.sec_hud_set_ID()
```suggestion
	overlays -= front_id_overlay
	
	if(!front_id)
		front_id_overlay = null
		return
	
	var/front_id_icon_state = front_id.icon_state
	if (copytext(front_id_icon_state,1,4) == "ERT")
		front_id_icon_state = "ERT"
	else if(!front_id_icon_state in icon_states(src.icon))
		front_id_icon_state = "id"
	
	front_id_overlay = image(src.icon, front_id_icon_state)
	overlays += front_id_overlay
	
	if(!ishuman(loc))
		return
	var/mob/living/carbon/human/H = loc
	if(H.wear_id == src)
		H.sec_hud_set_ID()
```

2022-01-28 07:53 UTC, Vallat commented on code/game/objects/items/weapons/storage/wallets.dm
> +	wallet = null
```suggestion
```

2022-01-28 07:53 UTC, Vallat commented on code/modules/mob/living/carbon/human/human.dm
> +			return if_no_id
```suggestion
		return if_no_id
```

2022-01-28 07:53 UTC, Vallat commented on code/modules/mob/living/carbon/human/human.dm
> +		if(wallet.front_id && istype(wallet.front_id, /obj/item/card/id))
```suggestion
		if(istype(wallet.front_id, /obj/item/card/id))
```

2022-01-28 07:53 UTC, Vallat commented on code/modules/mob/living/carbon/human/human.dm
> +		if(wallet.front_id && istype(wallet.front_id, /obj/item/card/id))
```suggestion
		if(istype(wallet.front_id, /obj/item/card/id))
```

2022-01-28 07:53 UTC, Vallat commented on code/modules/mob/living/carbon/human/human.dm
> +	else if(istype(wallet)) . = wallet.front_id.registered_name
```suggestion
	else if(istype(wallet)) . = wallet.front_id ? wallet.front_id.registered_name : if_no_id
```

2022-01-28 07:53 UTC, Vallat commented on code/modules/mob/living/carbon/human/human.dm
> +		if(wallet.front_id && istype(wallet.front_id, /obj/item/card/id))
```suggestion
		if(istype(wallet.front_id, /obj/item/card/id))
```

2022-01-28 07:53 UTC, Vallat commented on code/game/objects/items/weapons/storage/wallets.dm
> +	item_state = null
```suggestion
	item_state = "brown_wallet"
```

2022-01-29 00:12 UTC, Kirozet commented on code/game/data_huds.dm
> +			holder.icon_state = "hudunknown"
(locate(/obj/item/card/id) in wear_id)
Ты уверен что оно будет искать в содержимом wear_id а не в самой переменной? потому что в переменной объект кошелька, а не лист его содержимого

2022-01-29 00:16 UTC, Kirozet commented on code/game/jobs/access.dm
> +		rankName = WI.front_id.rank
ладно

2022-01-29 00:55 UTC, Kirozet commented on code/game/objects/items/weapons/storage/wallets.dm
> +			H.sec_hud_set_ID()
уже объявлена переменная для прока в самом объекте, но объявляем новую в 70 строке.
why?

2022-01-29 01:16 UTC, Kirozet commented on code/game/objects/items/weapons/storage/wallets.dm
> +	item_state = null
задаем item_state, но в следующем коммите отказываемся от него?

2022-01-29 04:57 UTC, Vallat commented on code/game/data_huds.dm
> +			holder.icon_state = "hudunknown"
Если бы я был не уверен, я бы не писал. Для такой информации есть документация http://www.byond.com/docs/ref/index.html#/proc/locate

2022-01-29 04:59 UTC, Vallat commented on code/game/objects/items/weapons/storage/wallets.dm
> +	item_state = null
Чего? Ты вообще пытался понять для чего `item_state` нужен? Нам его изменять не нужно, но задать следует и я именно это и сделал

2022-01-29 06:33 UTC, Vallat commented on code/game/objects/items/weapons/storage/wallets.dm
> +			H.sec_hud_set_ID()
Потому что тебе не нужно объявлять переменную, которая используется только в рамках одной функции и не несет информации, которая выходит за пределы жизни этой функции, у объекта. Тебе нужно объявлять её локально в рамках этой функции

2022-01-30 06:53 UTC, Vallat requested changes
Убрать ненужные вещи и нормально

2022-01-30 06:53 UTC, Vallat commented on code/game/objects/items/weapons/storage/wallets.dm
> +//	update_icon()
```suggestion
```

2022-01-30 06:53 UTC, Vallat commented on code/game/objects/items/weapons/storage/wallets.dm
> +	front_id_overlay = null
```suggestion
```

2022-01-30 09:14 UTC, Vallat approved these changes

2022-02-01 07:20 UTC, Gaxeer approved these changes

2022-02-05 19:51 UTC, merged