qol: Unified Blood Adjust
ss220-space/Paradise pull request #6180
Opened 2024-11-15 10:52 UTC by Antoonij

## Описание
изменение крови теперь более контролируемо
также это нужно для реализации https://github.com/ss220-space/Paradise/pull/6179

## Ссылка на предложение/Причина создания ПР
нет

## Тесты
не нужны

2024-11-15 15:01 UTC, pilygun commented on code/game/gamemodes/miniantags/abduction/gland.dm
> +	span_userdanger("Blood pours from your skin!"))
переведи раз затронул)

2024-12-30 11:41 UTC, BeebBeebBoob commented
переименуй с `/AdjustBloodLoss()` на `/AdjustBlood()` и инветируй потерю и получение крови
т.е. потеря 10 ед. не
`AdjustBloodLoss(10)`, а `AdjustBlood(-10)` 
где слово Adjust - регулировать, подправить, а когда команда adjustbloodloss используется не только как удаление крови, но и также удаление. 
Это как команда `adjustHealth()` или `adjust_clockwork_power()`

2024-12-30 22:23 UTC, BeebBeebBoob requested changes

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/game/gamemodes/miniantags/abduction/gland.dm
> +	owner.setBlood(max(owner.blood_volume - 20, 0))
```suggestion
	owner.AdjustBlood(-20)
```
А в AdjustBlood есть ограничитель `max(vol, 0)`

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/antagonists/vampire/vampire_datum.dm
> +				target.setBlood(max(target.blood_volume - 25, 0))
```suggestion
				target.AdjustBlood(-25)
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/antagonists/vampire/vampire_datum.dm
> +		target.setBlood(max(target.blood_volume - 25, 0))
```suggestion
		target.AdjustBlood(-25)
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/antagonists/vampire/vampire_powers/bestia_powers.dm
> +		l_target.setBlood(max(l_target.blood_volume - blood_amt, 0))	// -5 blood MAX
```suggestion
		l_target.AdjustBlood(-blood_amt)	// -5 blood MAX
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/antagonists/vampire/vampire_powers/bestia_powers.dm
> +		l_target.setBlood(max(l_target.blood_volume - blood_amt, 0))	// -5 blood MAX
```suggestion
		l_target.AdjustBlood(-blood_amt)	// -5 blood MAX
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/antagonists/vampire/vampire_powers/bestia_powers.dm
> +		l_target.setBlood(max(l_target.blood_volume - blood_amt, 0))	// -5 blood MAX
```suggestion
		l_target.AdjustBlood(-blood_amt)	// -5 blood MAX
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/paperwork/contract.dm
> +			user.setBlood(max(0, user.blood_volume - 100))
```suggestion
			user.AdjustBlood(-100)
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/paperwork/contract.dm
> +			user.setBlood(max(0, user.blood_volume - 100))
```suggestion
			user.AdjustBlood(-100)
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +			M.setBlood(max(M.blood_volume - rand(1, 2), 0))
```suggestion
			M.AdjustBlood(-rand(1, 2))
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +			M.setBlood(max(M.blood_volume - rand(5, 10), 0))
```suggestion
			M.setBlood(max(M.blood_volume - rand(5, 10), 0))
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +			M.setBlood(max(M.blood_volume - rand(1, 2), 0))
```suggestion
			M.AdjustBlood(-rand(1, 2))
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +			M.setBlood(max(M.blood_volume - rand(5, 10), 0))
```suggestion
			M.AdjustBlood(-rand(5, 10))
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/surgery/organs/blood.dm
> +	setBlood(max(blood_volume - amt, 0))
```suggestion
	AdjustBlood(-amt)
```

2024-12-30 22:23 UTC, BeebBeebBoob commented on code/modules/surgery/organs/blood.dm
> +	setBlood(max(blood_volume - amt, 0))
```suggestion
	AdjustBlood(-amt)
```

2024-12-31 13:00 UTC, merged