add: Aphasia disability
ss220-space/Paradise pull request #6181
Opened 2024-11-15 15:00 UTC by KefirTT

## Описание

Добавляет в билд ~~Абхазию~~ афазию как дизабилку, которую можно выбить в генетике или выбрать при создании персонажа. Афазия не позволяет говорить на общегалактическом языке, однако все еще дает возможность понимать его.

## Ссылка на предложение/Причина создания ПР

https://discord.com/channels/617003227182792704/755125334097133628/1305227174768414780

## Демонстрация изменений

![Без имени-1](https://github.com/user-attachments/assets/789530bc-f4f1-4ec7-bb82-575d02afbcd9) 
Сверху - от лица таяры, снизу - от лица хумана

## Тесты

все проверил, на слово поверьте пж

2024-11-16 09:38 UTC, Antoonij commented on code/game/dna/genes/disabilities.dm
> +/datum/dna/gene/disability/aphasia/deactivate(mob/living/H, flags)
```suggestion
/datum/dna/gene/disability/aphasia/deactivate(mob/living/carbon/human/H, flags)
```
Ошибка, я полагаю.

2024-11-16 09:38 UTC, Antoonij commented on code/game/dna/genes/disabilities.dm
> +		H.dna.species.default_language = LANGUAGE_GALACTIC_COMMON
```suggestion
		H.dna.species.default_language = initial(H.dna.species.default_language)
```
А вот тут стоит брать начальное значение от расы, что бы не было проблем, если дефолт язык у расы другой.

2024-11-16 09:38 UTC, Antoonij commented on code/game/dna/genes/disabilities.dm
> +	H.dna.species.default_language = H.dna.species.language
присваивание дефолт ленгвич нужно делать под чеком на дефолт ленгвич == галактик коммон, иначе столкнемся с проблемами у рас с кастомным дефолт ленгвичем.

2024-11-16 09:38 UTC, Antoonij commented on code/game/dna/genes/disabilities.dm
> +		return
1. Перенести это добро в can_activate()
2. Сделать в гене список-блеклист из типов рас, по нему сверять.

2024-11-16 09:38 UTC, Antoonij commented on code/game/dna/genes/disabilities.dm
> +		H.add_language("Galactic Common", TRUE)
```suggestion
	if(H.remove_language(LANGUAGE_GALACTIC_COMMON))
		H.add_language(LANGUAGE_GALACTIC_COMMON, TRUE)
```
Перейти на дефайны.

2024-11-16 13:15 UTC, Antoonij commented on code/modules/mob/mob_defines.dm
> +	var/list/datum/language/languages_only_listen // For understanding the language without ability to speak. Still can speak if lang is in /languages list
Автодок начинается с 3 слешей и находится над переменной

2024-11-16 13:50 UTC, Antoonij commented on code/game/dna/genes/disabilities.dm
> +		H.dna.species.default_language = initial(H.dna.species.default_language)
Я изучил вопрос получше. Дефолт ленгвич нам менять все же не имеет смысла. Поэтому код на 419, 411 412 строке придется убрать.

Также нужно это дело дополнить сигналами, которые идут в хумана от прока add_language, что бы предотвратить изучение общегалактического языка.

2024-11-16 13:53 UTC, Antoonij commented on code/game/dna/genes/disabilities.dm
> +		H.dna.species.default_language = initial(H.dna.species.default_language)
Если с сигналами не работал - то могу докодить уже это дело.

2024-11-16 14:03 UTC, KefirTT commented on code/game/dna/genes/disabilities.dm
> +		H.dna.species.default_language = initial(H.dna.species.default_language)
не шарю за сигналы, лучше ты докодь

2024-11-16 16:05 UTC, Antoonij submitted a review, later dismissed

2024-11-18 10:05 UTC, Antoonij reviewed
Все же, нуждается в доработке. 
1. Привести это в единый вид (датум набора языков, как на тг)
2. Починить получение дефолтного языка (кукла может продолжать говорить, даже если язык не находится в списке, а просто является дефолтным)

2025-01-01 09:09 UTC, PlayerUnknown14 requested changes
Йеп.

2025-01-01 09:09 UTC, PlayerUnknown14 commented on code/game/dna/genes/disabilities.dm
> +	desc = "Цель теряет возможность говорить на своем основном языке."
```suggestion
	desc = "Субъект теряет возможность говорить на своём основном языке."
```

2025-01-02 13:44 UTC, Antoonij approved these changes
теперь выглядит и работает хорошо, без лишних рефакторов языков.
![image](https://github.com/user-attachments/assets/4bea5382-d22a-43c5-8d12-811627caaa24)

2025-01-03 04:07 UTC, PlayerUnknown14 approved these changes
Йеп.

2025-01-03 04:12 UTC, merged