Перевод интерфейса
ss220-space/Paradise pull request #6188
Opened 2024-11-16 17:38 UTC by Insurgent679

## Описание

## Ссылка на предложение/Причина создания ПР

## Демонстрация изменений

## Тесты

2024-11-16 21:30 UTC, Den109G commented on interface/interface.dm
> +		if(query == "Домашняя страница")
У нас нет домашней страницы.
Источник - https://wiki.ss220.space/index.php/Заглавная_страница

2024-11-16 21:34 UTC, Den109G commented on interface/interface.dm
> +		if(query == "Домашняя страница")
Я думаю, у нас когда говорят "домашная страница" больше думают про персональный сайт, по тип страницы ВК.

2024-11-17 02:36 UTC, Insurgent679 commented on interface/interface.dm
> +		if(query == "Домашняя страница")
Угу, поправил.

2024-11-17 08:07 UTC, PlayerUnknown14 reviewed
В основном хорошо, есть над чем поработать.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/craft.dm
> +		ui = new(user, src, "Персональный крафт", "Меню для крафта")
* `"PersonalCrafting"` здесь - название файла с TGUI интерфейсом, это системное, не переводим.


`"Меню для крафта" - "Меню создания"`

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/craft.dm
> +				stack_trace("части [part_path] пропали без вести")
Сообщения пишем с заглавной буквы.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/craft.dm
> +				stack_trace("Во время крафта [recipe], некоторые из [thing] пропали без вести (Нужно ещё [needed_amount])!")
`"крафт"` - `"создание"` здесь и далее.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/craft.dm
> +				stack_trace("Во время крафта [recipe], некоторые из [thing] пропали без вести (Нужно ещё [needed_amount])!")
.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/craft.dm
> +					stack_trace("Во время крафта [recipe], [thing] пропали без вести!")
.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/craft.dm
> +	var/datum/tgui/ui = SStgui.get_open_ui(user, src, "Главное")
`"main"` - системное. Здесь и далее не переводим.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/craft.dm
> +		if("Создать")
Не переводим.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/craft.dm
> +			var/datum/crafting_recipe/TR = locate(params["Создать"]) in GLOB.crafting_recipes
.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/craft.dm
> +				to_chat(usr, "<span class='warning'>Строительство провалилось[fail_msg]</span>")
`"Строительство" - "Создание"`

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +	desc = "Прототип модульной ствольной коробки и спускового механизма для огнестрельного оружия."
Добавить `ru_names`

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +	desc = "Классический приклад винтовки, который одновременно служит рукояткой, грубо вырезан из дерева."
.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +	desc = "Грубо сделанный револьверный ствол."
.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +	desc = "Ствол пистолета из высококачественной тяжелой стали для повышения устойчивости."
.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +	desc = "Длинная труба, прикрепленная к ствольной коробке огнестрельного оружия. Кажется, что штифты расшатаны."
.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +		to_chat(user, "Вы прикрепляете ствол дробовика к ствольной коробке. Кажется, что штифты ослаблены.")
Снизу добавить балун-алёрт: `balloon_alert(user, "деталь установлена")`. Использовать этот балун здесь и далее в процессе создания.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +	to_chat(user, span_notice("Вы вкручиваете штифты на место, закрепляя трубу на приемнике."))
Балун

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +	desc = "Длинная труба, прикрепленная к спусковому механизму."
ё*

`ru_names`.

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +	desc = "Дробовик в сборе со ствольной коробкой и незакрепленным деревянным прикладом. Вы не сможете выстрелить из него без того, чтобы приклад не отвалился."
Аналогично выше.

`"из него без того, чтобы приклад не отвалился." "из него так, чтобы приклад не отвалился."`

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +			to_chat(user, span_warning("Вам понадобится не менее пяти футов оберточной бумаги, чтобы закрепить заготовку."))
Добавить: `balloon_alert(user, "недостаточно материала!")`

`"футов" - "мотков"`

2024-11-17 08:07 UTC, PlayerUnknown14 commented on code/modules/crafting/guncrafting.dm
> +		to_chat(user, span_notice("Вы обвязываете оберточной бумагой приклад и ствол, чтобы закрепить его."))
ё*

Добавить: `balloon_alert(user, "заготовка закреплена")`

2024-11-17 08:07 UTC, PlayerUnknown14 commented on interface/skin.dmf
> +		name = "&Сохраните скриншот как..."
`"скриншот" - "снимок экрана"`

2024-11-17 08:07 UTC, PlayerUnknown14 commented on interface/skin.dmf
>  		name = "&Fit Viewport"
`"&Fit Viewport" - "&Настроить обзор"`

2024-11-17 10:15 UTC, Insurgent679 commented
Фиксанул ошибки.

2024-11-17 10:46 UTC, Antoonij requested changes

2024-11-17 10:46 UTC, Antoonij commented on code/modules/crafting/craft.dm
> +				stack_trace("Во время создания [recipe], некоторые из [thing] пропали без вести (Нужно ещё [needed_amount])!")
Логирование ошибок переводить нельзя

2024-11-17 10:46 UTC, Antoonij commented on code/modules/crafting/craft.dm
> +				stack_trace("Во время создания [recipe], некоторые из [thing] пропали без вести (Нужно ещё [needed_amount])!")
Логирование ошибок переводить нельзя

2024-11-17 10:46 UTC, Antoonij commented on code/modules/crafting/craft.dm
> +				stack_trace("Части [part_path] пропали без вести")
Логирование ошибок переводить нельзя

2024-11-17 10:46 UTC, Antoonij commented on code/modules/crafting/craft.dm
> +					stack_trace("Во время создания [recipe], [thing] пропали без вести!")
Логирование ошибок переводить нельзя

2024-11-17 11:46 UTC, Insurgent679 commented on code/modules/crafting/craft.dm
> +					stack_trace("Во время создания [recipe], [thing] пропали без вести!")
В смысле логирование ошибок проводить нельзя? Вернуть как было что-ли?

2024-11-17 11:51 UTC, Antoonij commented on code/modules/crafting/craft.dm
> +					stack_trace("Во время создания [recipe], [thing] пропали без вести!")
> В смысле логирование ошибок проводить нельзя? Вернуть как было что-ли?

Именно. Текст в стактрейсах, крашах, рантаймах переводить нельзя

2024-11-17 15:10 UTC, Insurgent679 commented on code/modules/crafting/craft.dm
> +					stack_trace("Во время создания [recipe], [thing] пропали без вести!")
готово

2024-11-18 17:46 UTC, littleboobs reviewed
это исправить и норм

2024-11-18 17:46 UTC, littleboobs commented on code/modules/crafting/guncrafting.dm
> +	to_chat(user, span_notice("Вы вкручиваете штифты на место, закрепляя трубу на приемнике."))
балуны нужны как раз для того, чтобы чат разгрузить, а тут получается, что балун добавляем, тучат не убираем, либо то, либо другое и везде снизу тоже самое

2024-11-18 17:46 UTC, littleboobs commented on code/modules/crafting/guncrafting.dm
> +		to_chat(user, span_notice("Приклад крепится к ствольной коробке."))
балун и тучат

2024-11-18 17:46 UTC, littleboobs commented on code/modules/crafting/guncrafting.dm
> +			to_chat(user, span_warning("Вам понадобится не менее пяти мотков оберточной бумаги, чтобы закрепить заготовку."))
балун и тучат

2024-11-18 17:46 UTC, littleboobs commented on interface/interface.dm
> +		to_chat(src, "<span class='danger'>URL-адрес Discord не задан в конфигурации сервера.</span>")
span_danger()

2024-11-18 17:46 UTC, littleboobs commented on interface/interface.dm
> +		to_chat(src, "<span class='danger'>URL-адрес GitHub не задан в конфигурации сервера.</span>")
span_danger()

2024-11-18 17:46 UTC, littleboobs commented on code/modules/crafting/guncrafting.dm
> +		to_chat(user, span_notice("Вы обвязываете оберточной бумагой приклад и ствол, чтобы закрепить его."))
балун и тучат

2024-11-18 17:46 UTC, littleboobs commented on interface/interface.dm
> +		to_chat(src, "<span class='danger'>URL-адрес донатов не задан в конфигурации сервера.</span>")
span_danger()

2025-01-19 04:03 UTC, PlayerUnknown14 commented
Полностью заброшено.

2025-01-20 03:08 UTC, closed without merging