Translation-engi-tools
ss220-space/Paradise pull request #6196
Opened 2024-11-19 10:15 UTC by Dimempers

Основной перевод всех инженерных инструментов вместе с суицидами и сообщениями.

## Описание
Основной перевод всех инженерных инструментов вместе с суицидами и сообщениями в чате.

## Причина создания ПР / Почему это хорошо для игры
Локализация игры

## Демонстрация изменений

## Тесты
Зашел на локалку, осмотрел перебрал все инструменты, все на русском, все чики пуки.

2024-11-19 11:41 UTC, PlayerUnknown14 reviewed
Дописать.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Небольшой лом. Этот удобный инструмент полезен для многих вещей, таких как поддевание напольной плитки или открытие дверей без электропитания."
`"дверей без электропитания" - "обесточенных шлюзов"`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	ru_names = list(NOMINATIVE = "корманный лом", GENITIVE = "корманного лома", DATIVE = "корманному лому", ACCUSATIVE = "корманный лом", INSTRUMENTAL = "корманным ломом", PREPOSITIONAL = "корманном лом
* Принято писать в таком виде, см. скриншот.
![image](https://github.com/user-attachments/assets/393de64f-5f19-47df-8d14-0682dba7e69c)


кАрманный*

Перемести выше под `desc`.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	ru_names = list(NOMINATIVE = "латунный лом", GENITIVE = "латунного лома", DATIVE = "латунному лому", ACCUSATIVE = "латунный лом", INSTRUMENTAL = "латунным ломом", PREPOSITIONAL = "латунном ломе")
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Латунный лом. На ощупь он слегка теплый."
* Пишем "ё", не заменяем на "е".


`"На ощупь он слегка теплый" - "Слегка тёплый на ощупь"`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	ru_names = list(NOMINATIVE = "инопланетный лом", GENITIVE = "инопланетного лома", DATIVE  = "инопланетному лому", ACCUSATIVE = "инопланетный лом", INSTRUMENTAL = "инопланетным ломом", PREPOSITIONAL
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Это большой лом. Он не поместится в кармане, потому что он слишком большой."
`"Он не поместится в кармане, потому что он слишком большой" - "Такой в карман не положить."`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	ru_names = list(NOMINATIVE = "большой лом", GENITIVE = "большого лома", DATIVE = "большому лому", ACCUSATIVE = "большой лом", INSTRUMENTAL = "большим ломом", PREPOSITIONAL = "большом ломе")
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Гидравлический лом, компактный, но мощный. Разработан для замены лома в строительных киборгах."
`"Разработан для замены лома в строительных киборгах" - "Аналог лома для строительных киборгов."`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	ru_names = list(NOMINATIVE = "гидравлический лом", GENITIVE = "гидравлического лома", DATIVE = "гидравлическому лому", ACCUSATIVE = "гидравлический лом", INSTRUMENTAL = "гидравлическим ломом", PREPO
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Набор челюстей жизни, магия науки сумела втиснуть его в устройство, достаточно маленькое, чтобы поместиться на поясе для инструментов. Он оснащен выдвигающейся головкой."
ё*

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Набор челюстей жизни, магия науки сумела втиснуть его в устройство, достаточно маленькое, чтобы поместиться на поясе для инструментов. Он оснащен выдвигающейся головкой."
Переместить сюда `ru_names`.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	to_chat(user, "<span class='notice'>Ты присоеденяешь режущую головку к [src.declent_ru(GENITIVE)].</span>")
* Обычные информационные сообщения пишем через "вы".
* `"<span class='...'>ТЕКСТ</span>"` заменяем на `span_...("ТЕКСТ")`

`"<span class='notice'>Ты присоеденяешь режущую головку к [src.declent_ru(GENITIVE)].</span>" - span_notice("Вы присоединяете режущую головку к [src.declent_ru(GENITIVE)].")`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/holotool.dm
> +	desc = "Высокоэкспериментальный голографический инструмент-проектор."
* Слова "Высокоэкспериментальный" в русском языке нет.


`"Высокоэкспериментальный" - "Экспериментальный"`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/holotool.dm
> +	ru_names = list(NOMINATIVE = "эксперементальный голо-тул", GENITIVE = "эксперементального голо-тула", DATIVE = "эксперементальному голо-тулу", ACCUSATIVE = "эксперементальный голо-тул", INSTRUMENTAL
Перенести выше, переписать.

Я бы писал `"голо-тул"` слитно, по аналогии со словом `"мультитул"`.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/holotool.dm
> +	. += span_notice("На данный момент установлен [current_tool ? current_tool.name : "'off'"] режим.")
`"На данный момент установлен off режим."` - Не доделано. Либо переписывать весь код голотула ниже, соотвественно переводя названия инструментов, либо эту строчку откатить и оставить уже другим переводчикам.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/multitool.dm
> +	ru_names = list(NOMINATIVE = "мультитул", GENITIVE = "мультитула", DATIVE = "мультитулу", ACCUSATIVE = "мультитул", INSTRUMENTAL = "мультитулом", PREPOSITIONAL = "мультитуле")
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/multitool.dm
> +	to_chat(user, "<span class='notice'>Ты загрузил [M] в внутренний буфер [src.declent_ru(GENITIVE)].</span>")
во внутренний*

Переписать на `span_notice`.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/multitool.dm
> +	desc = "Используется для пульсации проводов, чтобы проверить, какой из них следует разрезать. Не рекомендуется врачами. Имеет странную бирку с надписью  'Гриф в безопастности'" //What else should I
`'Гриф в безопастности' - 'Гриферить в удовольствие!'`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/multitool.dm
> +	ru_names = list(NOMINATIVE = "инопланетный мультитул", GENITIVE = "инопланетного мультитула", DATIVE = "инопланетному мультитулу", ACCUSATIVE = "инопланетный мультитул", INSTRUMENTAL = "инопланетным
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/multitool.dm
> +	ru_names = list(NOMINATIVE = "латунный мультитул", GENITIVE = "латунного мультитула", DATIVE = "латунному мультитулу", ACCUSATIVE = "латунный мультитул", INSTRUMENTAL = "латунным мультитулом", PREPO
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	desc = "С этим можно быть совершенно чокнутым."
* Непереводимая игра слов, пытаться перевести прямо - не вариант.


`"С этим можно быть совершенно чокнутым." - "Инструмент для откручивания и прикручивания различных предметов. Плохо сочетается с глазными яблоками."`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	ru_names = list(NOMINATIVE = "отвертка", GENITIVE = "отвертки", DATIVE = "отвертке", ACCUSATIVE = "отвертку", INSTRUMENTAL = "отверткой", PREPOSITIONAL = "отвертке")
ё*

Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	desc = "Отвертка с ультратонким наконечником."
ё*

Прописать `ru_names`.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	user.visible_message("<span class='suicide'>[user] кол[pluralize_ru(user.gender,"ет","ют")] [src.declent_ru(INSTRUMENTAL)] в [user.p_their()] [pick("temple", "heart")]! Похоже на то, что [user.p_the
`span_suicide`

`"[user] кол[pluralize_ru(user.gender,"ет","ют")] [src.declent_ru(INSTRUMENTAL)] в [user.p_their()] [pick("temple", "heart")]! Похоже на то, что [user.p_theyre()] пыта[pluralize_ru(user.gender,"ется","ются")] совершить самоубийство!" - "[user] кол[pluralize_ru(user.gender,"ет","ют")] себя [src.declent_ru(INSTRUMENTAL)] в [pick("висок", "сердце")]! Похоже на то, что [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[pluralize_ru(user.gender,"ет","ют")]ся совершить самоубийство!"`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
>  	icon_state = "screwdriver_brass"
`ru_names`

ё*

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	desc = "Ультразвуковая отвертка."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	user.visible_message("<span class='suicide'>[user] ставит [src.declent_ru(ACCUSATIVE)] к [genderize_ru(user.gender,"его","её","его","их")] виску. Похоже [genderize_ru(user.gender,"он","она","оно","о
Переписать аналогично этому сообщению выше.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	to_chat(user, "<span class='notice'>Ты присоеденяешь головку болтового сверла к [src.declent_ru(GENITIVE)].</span>")
Вы*

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	desc = "Электрическая отвертка, разработанная для точного и быстрого использования."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	ru_names = list(NOMINATIVE = "сварочный аппарат", GENITIVE = "сварочного аппарата", DATIVE = "сварочному аппарату", ACCUSATIVE = "сварочный аппарат", INSTRUMENTAL = "сварочным аппаратом", PREPOSITIO
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		. += "<span class='notice'>Он содержит [GET_FUEL] юнит/ов топлива из [maximum_fuel].</span>"
`"юнит/ов" - "u"`

`span_notice`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	user.visible_message("<span class='suicide'>[user] заварива[pluralize_ru(user.gender,"ет","ют")] себе все отверстия! Похоже [genderize_ru(user.gender,"он","она","оно","они")] пыта[pluralize_ru(user.
Аналогично выше.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, "<span class='warning'>[S] не могу положить [src.declent_ru(NOMINATIVE)] пока он горит!</span>")
`"Контейнер не могу положить сварочный аппарат пока он горит!"`

Переписать + `span_warning`.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, "<span class='notice'>Ты выключил [src.declent_ru(NOMINATIVE)].</span>")
Вы* здесь и далее.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +			to_chat(user, "<span class='notice'>[src.declent_ru(NOMINATIVE)] должен быть включен для выполнения этой задачи!</span>")
ё*

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, "<span class='notice'>[src.declent_ru(NOMINATIVE)] уже полон!</span>")
Если declent_ru используется в начале строки, то нам нужна заглавная буква.

`[src.declent_ru(NOMINATIVE)] - [capitalize(src.declent_ru(NOMINATIVE))]`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, "<span class='notice'>Ты заполнил [src.declent_ru(NOMINATIVE)] [amount_transferred] юнитами.</span>")
Аналогично выше.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, "<span class='warning'>В [A] недостатачно топлива для заполнения [src.declent_ru(GENITIVE)]!</span>")
Лучше перепиши на балун.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	desc = "Немного более крупный сварочный аппарат с большим баком."
`"Немного более крупный сварочный аппарат с большим баком." - "Сварочный аппарат, но с баком побольше."`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	desc = "Немного более крупный сварочный аппарат с большим баком."
`ru_names`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	desc = "Усовершенствованный сварочный аппарат, предназначенный для использования в роботизированных системах."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	desc = "Миниатюрный сварочный аппарат, используемый в экстренных случаях."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	desc = "Инопланетный сварочный инструмент. Какое бы топливо он ни использовал, оно никогда не кончается."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	desc = "Усовершенствованный сварочный аппарат на базе промышленного сварочного аппарата."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	desc = "Экспериментальный сварочный аппарат, способный самостоятельно вырабатывать топливо и менее вредный для глаз."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	desc = "Усовершенствованный сварочный аппарат, предназначенный для использования в роботизированных системах."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	desc = "Латунный сварочный аппарат, который, кажется, постоянно заправляется. Он слегка теплый на ощупь."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	desc = "Это перерезает провода."
`"Инструмент для перерезания различных материалов."`

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	ru_names = list(NOMINATIVE = "кусачки", GENITIVE = "кусачек", DATIVE = "кусачкам", ACCUSATIVE = "кусачки", INSTRUMENTAL = "кусачками", PREPOSITIONAL = "кусачках")
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +			span_notice("Ты перерезал [target]'s стяжки [src.declent_ru(INSTRUMENTAL)]!"),
Переписать.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	user.visible_message("<span class='suicide'>[user] перереза[pluralize_ru(user.gender,"ет","ют")] [genderize_ru(user.gender,"его","её","его","их")] артерии с помощью [src.declent_ru(GENITIVE)]! Кажет
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	desc = "Пара кусачек из латуни. Ручка на ощупь ледяная."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	desc = "Очень острые кусачки, изготовленные из серебристо-зеленого металла."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	desc = "Это перерезает провода."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	ru_names = list(NOMINATIVE = "челюсти жизни", GENITIVE = "челюстей жизни", DATIVE = "челюстям жизни", ACCUSATIVE = "челюсти жизни", INSTRUMENTAL = "челюстями жизни", PREPOSITIONAL = "челюстях жизни"
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	user.visible_message("<span class='suicide'>[user] обертывает [src.declent_ru(NOMINATIVE)] вокруг [genderize_ru(user.gender,"его","её","его","их")] шеи. Кажется, [genderize_ru(user.gender,"он","она"
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	to_chat(user, "<span class='notice'Ты присоеденяешь поддевающую головку к [src.declent_ru(DATIVE)].</span>")
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	user.visible_message("<span class='suicide'>[user] избивает себя до смерти [src.declent_ru(INSTRUMENTAL)]! Похоже, [genderize_ru(user.gender,"он","она","оно","они")] пыта[pluralize_ru(user.gender,"е
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	desc = "Продвинутый роботизированный гаечный ключ. Можно найти у строительных киборгов."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	desc = "Латунный ключ. Он слегка теплый на ощупь."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	desc = "Поляризованный ключ. Он заставляет все, что находится между губками, поворачиваться."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	desc = "Простая электрическая дрель с болтовым сверлом."
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	ru_names = list(NOMINATIVE = "ручная дрель", GENITIVE = "ручной дрели", DATIVE = "ручную дрель", ACCUSATIVE = "ручную дрель", INSTRUMENTAL = "ручной дрелью", PREPOSITIONAL = "ручной дрели")
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	to_chat(user, "<span class='notice'>Ты присоеденяешь головку отвертки к [src.declent_ru(GENITIVE)].</span>")
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	user.visible_message("<span class='suicide'>[user] нажимает [src.declent_ru(INSTRUMENTAL)] против [genderize_ru(user.gender,"его","её","его","их")] головы! Похоже, [genderize_ru(user.gender,"он","он
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	desc = "Медицинский ключ с общим (медицинским?) Использование. Можно найти в руке."
Переписать описание.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	ru_names = list(NOMINATIVE = "медецинский ключ", GENITIVE = "медецинского ключа", DATIVE = "медецинскому ключу", ACCUSATIVE = "медецинской ключ", INSTRUMENTAL = "медецинским ключем", PREPOSITIONAL =
Также.

2024-11-19 11:41 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	user.visible_message("<span class='suicide'>[user] молится медецинскому ключу чтобы он взял [genderize_ru(user.gender,"его","её","его","их")] душу. Похоже, [genderize_ru(user.gender,"он","она","оно"
Также.

2024-11-19 12:06 UTC, Antoonij commented on code/game/objects/items/tools/crowbar.dm
> +	to_chat(user, "<span class='notice'>Ты присоеденяешь режущую головку к [src.declent_ru(GENITIVE)].</span>")
```suggestion
	to_chat(user, span_notice("Ты присоединяешь режущую головку к [declent_ru(GENITIVE)]."))
```
src тут не нужен

2024-11-19 12:06 UTC, Antoonij commented on code/game/objects/items/tools/screwdriver.dm
> +	user.visible_message("<span class='suicide'>[user] ставит [src.declent_ru(ACCUSATIVE)] к [genderize_ru(user.gender,"его","её","его","их")] виску. Похоже [genderize_ru(user.gender,"он","она","оно","о
```suggestion
	user.visible_message(span_suicide("[user] ставит [declent_ru(ACCUSATIVE)] к [genderize_ru(user.gender, "его", "её", "его", "их")] виску. Похоже [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[pluralize_ru(user.gender, "ется", "ются")] совершить самоубийство!"))
```
Пробелы после запятых, src тут не нужен

2024-11-19 12:06 UTC, Antoonij commented on code/game/objects/items/tools/screwdriver.dm
> +	to_chat(user, "<span class='notice'>Ты присоеденяешь головку болтового сверла к [src.declent_ru(GENITIVE)].</span>")
```suggestion
	to_chat(user, span_notice("Вы присоединяете головку болтового сверла к [declent_ru(GENITIVE)]."))
```
src тут не нужен

2024-11-19 12:06 UTC, Antoonij commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, "<span class='warning'>[S] не могу положить [src.declent_ru(NOMINATIVE)] пока он горит!</span>")
```suggestion
		to_chat(user, span_warning("[S] не могу положить [declent_ru(NOMINATIVE)] пока он горит!"))
```
src тут не нужен

2024-11-19 12:06 UTC, Antoonij commented on code/game/objects/items/tools/screwdriver.dm
> +	to_chat(user, "<span class='notice'>Ты присоеденяешь головку болтового сверла к [src.declent_ru(GENITIVE)].</span>")
и далее посмотришь сам, где у тебя src.declent_ru, src. оттуда нужно убрать

2024-11-19 12:29 UTC, Dimempers commented on code/game/objects/items/tools/screwdriver.dm
> +	desc = "Отвертка с ультратонким наконечником."
Тут такое же самое название как и у оригинальной, можно просто скопировать ру нейм с оригинальной?

2024-11-20 13:52 UTC, PlayerUnknown14 reviewed
Заставляет задуматься...

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	desc = "Небольшой лом. Этот удобный инструмент полезен для многих вещей, таких как поддевание напольной плитки или открытие обесточеных шлюзов."
обесточеННых*

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	user.visible_message(span_suicide("[user] помеща[pluralize_ru(user.gender, "ет", "ют")] свою голову между лезвиями [declent_ru(GENITIVE)]. Похоже, [genderize_ru(user.gender, "он", "она", "оно", "они
"Похоже, что"

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/holotool.dm
> +	desc = "A highly experimental holographic tool projector."
Ты немного не в ту сторону переводишь.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/holotool.dm
> -	ru_names = list(NOMINATIVE = "эксперементальный голо-тул", GENITIVE = "эксперементального голо-тула", DATIVE = "эксперементальному голо-тулу", ACCUSATIVE = "эксперементальный голо-тул", INSTRUMENTAL
А тут удалил строчку вообще.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/holotool.dm
> +	. += (span_notice("It is currently set to [current_tool ? current_tool.name : "'off'"] mode."))
И тут.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/multitool.dm
> +	to_chat(user, span_notice("Ты загрузил [M] во внутренний буфер [declent_ru(GENITIVE)]."))
Во всех подобных сообщениях должно быть "вы".

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	user.visible_message(span_suicide("[user] став[pluralize_ru(user.gender, "ит", "ят")] [declent_ru(ACCUSATIVE)] к своему виску. Похоже [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[plur
`"ставит" - "приставляет"`

`"Похоже, что"`

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	to_chat(user, span_notice("Вы присоеденяете головку болтового сверла к [declent_ru(GENITIVE)]."))
Падеж здесь - дательный.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	desc = "Электрическая отвёртка, разработанная для точного и быстрого использования."
"Электрическая отвёртка" - "Отвёртка с электроприводом."

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, span_warning("[capitalize(declent_ru(NOMINATIVE))] невозможно положить пока он включен!"))
включЁн*

положить, пока

Падеж - винительный.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, span_notice("Вы выключили [declent_ru(NOMINATIVE)]."))
Падеж здесь и ниже - родительный.

А вообще, перенеси в балуны эти сообщения.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +			to_chat(user, span_notice("[capitalize(declent_ru(NOMINATIVE))] должен быть включён для выполнения этой задачи!"))
В балун.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +			to_chat(user, span_warning("Тебе нужно больше сварочного топлива в [declent_ru(PREPOSITIONAL)] для выполнения этой задачи!"))
В балун.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, span_notice("[capitalize(declent_ru(NOMINATIVE))] уже полон!"))
В балун.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, span_notice("Ты заполнил [declent_ru(NOMINATIVE)] [amount_transferred] u.</span>"))
.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		balloon_alert(user, span_warning("В [A] недостатачно топлива!</span>"))
.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +			PREPOSITIONAL = "встроенном сварачном аппарате"
сварАчном)))

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
>  	desc = "Усовершенствованный сварочный аппарат на базе промышленного сварочного аппарата."
`"Усовершенствованный сварочный аппарат на базе промышленного сварочного аппарата." - "Усовершенствованная версия промышленного сварочного аппарата. С баком побольше!"`

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +			PREPOSITIONAL = "встроенном сварачном аппарате"
сварАчном)))

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
>  		)
```
visible_message(span_notice("[user] перереза[pluralize_ru(user.gender, "ет", "ют")] стяжки [target] с помощью [declent_ru(GENITIVE)]!"))

balloon_alert(user, "стяжки перерезаны")
```

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	user.visible_message(span_suicide("[user] перереза[pluralize_ru(user.gender, "ет", "ют")] свои артерии с помощью [declent_ru(GENITIVE)]! Кажется, [genderize_ru(user.gender, "он", "она", "оно", "они"
Кажется, что

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
>  	desc = "Очень острые кусачки, изготовленные из серебристо-зеленого металла."
ё*

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	desc = "Инструмент для перерезания различных материалов."
```suggestion
	desc = "Инструмент для перерезания различных материалов. Специальная версия для роботизированных систем."
```

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	user.visible_message(span_suicide("[user] обёртывает [declent_ru(NOMINATIVE)] вокруг своей шеи. Кажется, [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[pluralize_ru(user.gender, "ет", "
```suggestion
	user.visible_message(span_suicide("[user] обёртыва[pluralize_ru(user.gender, "ет", "ют")] [declent_ru(ACCUSATIVE)] вокруг своей шеи. Кажется, что [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[pluralize_ru(user.gender, "ет", "ют")]ся отрубить себе голову!"))
```

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	to_chat(user, span_notice("Ты присоеденяешь поддевающую головку к [declent_ru(DATIVE)]."))
Вы*

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	user.visible_message(span_suicide("[user] избивает себя до смерти с помощью [declent_ru(GENITIVE)]! Похоже, [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[pluralize_ru(user.gender, "ет"
```suggestion
	user.visible_message(span_suicide("[user] избива[pluralize_ru(user.gender, "ет", "ют")] себя до смерти с помощью [declent_ru(GENITIVE)]! Похоже, что [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[pluralize_ru(user.gender, "ет", "ют")]ся совершить самоубийство!"))
```

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
>  	desc = "Латунный ключ. Он слегка теплый на ощупь."
ё*

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +		NOMINATIVE = "автоматической ключ",
```suggestion
		NOMINATIVE = "автоматический ключ",
```

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +		INSTRUMENTAL = "автоматическим ключем",
ключОм здесь и ниже.

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +		DATIVE = "ручную дрель",
```suggestion
		DATIVE = "ручной дрели",
```

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	to_chat(user, span_notice("Ты присоеденяешь головку отвертки к [declent_ru(GENITIVE)]."))
Вы*

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	user.visible_message(span_suicide("[user] нажимает [declent_ru(INSTRUMENTAL)] против своей головы! Похоже, [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[pluralize_ru(user.gender, "ет",
```suggestion
	user.visible_message(span_suicide("[user] закручива[pluralize_ru(user.gender, "ет", "ют")] [declent_ru(ACCUSATIVE)] против своей головы! Похоже, что [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[pluralize_ru(user.gender, "ет", "ют")]ся совершить самоубийство!"))
```

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	desc = "Медецинский гаечный ключ. Используется для закручивания или откручивания чего либо, а так же в медецине."
```suggestion
	desc = "Медецинский гаечный ключ. Используется для закручивания или откручивания чего либо. Не спрашивайте, что отличает эту модель от обычного ключа."
```

2024-11-20 13:52 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	user.visible_message(span_suicide("[user] молится медецинскому ключу чтобы он взял [genderize_ru(user.gender, "его", "её", "его", "их")] душу. Похоже, [genderize_ru(user.gender, "он", "она", "оно",
```suggestion
	user.visible_message(span_suicide("[user] молится [declent_ru(DATIVE)], чтобы он взял [genderize_ru(user.gender, "его", "её", "его", "их")] душу. Похоже, что [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[pluralize_ru(user.gender, "ет", "ют")]ся совершить самоубийство!"))
```

2024-11-20 15:39 UTC, Dimempers commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, span_notice("Вы выключили [declent_ru(NOMINATIVE)]."))
С родительным это будет "Вы выключили сварочного аппарата", переписал на винительный.

2024-11-21 09:26 UTC, Dimempers commented on code/game/objects/items/tools/holotool.dm
> +	. += (span_notice("It is currently set to [current_tool ? current_tool.name : "'off'"] mode."))
Оставил другим

2024-11-21 13:31 UTC, pilygun submitted a review, later dismissed
косяков не найдено

2024-11-21 14:48 UTC, Antoonij requested changes

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/weapons/RCD.dm
> +	. += span_notice("Мод: [mode].")
```suggestion
	. += span_notice("Режим: [mode].")
```
не переведено

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/weapons/RCD.dm
> +	to_chat(user, span_notice("You change [src]'s mode to '[choice]")) // Оставляю другим локализаторам на перевод
```suggestion
	to_chat(user, span_notice("You change [src]'s mode to '[choice]")) 
```
Комментарии на русском в коде не стоит использовать

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/weapons/RCL.dm
> +	to_chat(user, span_notice("Вы откручиваете сбоку винты панели, что позваляет вам отсоеденить её и снять провода."))
```suggestion
	to_chat(user, span_notice("Вы откручиваете сбоку винты панели, что позволяет вам отсоединить её и снять провода."))
```
позволяет, отсоединить

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/tools/wrench.dm
> +	)
Медицинский, а не медецинский

2024-11-21 14:48 UTC, Antoonij commented on code/modules/power/cable.dm
> +	desc = "Гибкий сверхпроводящий кабель для передачи электроэнергии в сложных условиях"
```suggestion
	desc = "Гибкий сверхпроводящий кабель для передачи электроэнергии в суровых условиях"
```
Дело вкуса, суровых получше звучит чем сложных.

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/tools/wirecutters.dm
> +	to_chat(user, span_notice("Вы присоеденяете поддевающую головку к [declent_ru(DATIVE)]."))
```suggestion
	to_chat(user, span_notice("Вы присоединяете поддевающую головку к [declent_ru(DATIVE)]."))
```

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/tools/welder.dm
> +	desc = "Сварочный аппарат, но с баком побольше."
```suggestion
	desc = "Сварочный аппарат с увеличенным объемом бака."
```

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/tools/welder.dm
> +			balloon_alert(user, ("Тебе нужно больше сварочного топлива в [declent_ru(PREPOSITIONAL)]!"))
длинный баллун алерт, сократить до 3-4 слов

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/tools/screwdriver.dm
> +	to_chat(user, span_notice("Вы присоеденяете головку болтового сверла к [declent_ru(DATIVE)]."))
```suggestion
	to_chat(user, span_notice("Вы присоединяете головку болтового сверла к [declent_ru(DATIVE)]."))
```

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/tools/multitool.dm
> +	desc = "Используется для пульсации проводов, чтобы проверить, какой из них следует разрезать. Не рекомендуется врачами. Имеет странную бирку с надписью  'Гриферить в удовольствие!'" //What else shou
```suggestion
	desc = "Используется для пульсации проводов, чтобы проверить, какой из них следует разрезать. Не рекомендуется врачами. Имеет странную бирку с надписью  'Гриферить в удовольствие!'" // What else should I say for a meme item?
```

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/tools/holotool.dm
> +	)
эксперИментальный, рунеймы также поменять

2024-11-21 14:48 UTC, Antoonij commented on code/game/objects/items/tools/crowbar.dm
> +	to_chat(user, span_notice("Вы присоеденяете режущую головку к [declent_ru(DATIVE)]."))
```suggestion
	to_chat(user, span_notice("Вы присоединяете режущую головку к [declent_ru(DATIVE)]."))
```

2024-12-12 11:26 UTC, PlayerUnknown14 reviewed
Далеко от идеала.

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/multitool.dm
> +	to_chat(user, span_notice("Вы загрузили [M] во внутренний буфер [declent_ru(GENITIVE)]."))
```suggestion
	to_chat(user, span_notice("Вы загрузили [M.declent_ru(ACCUSATIVE)] во внутренний буфер [declent_ru(GENITIVE)]."))
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		balloon_alert(user, ("Вы выключили сварочный аппарат."))
```suggestion
		balloon_alert(user, ("выключено"))
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		to_chat(user, span_warning("[capitalize(declent_ru(ACCUSATIVE))] невозможно положить, пока он включён!"))
```suggestion
		balloon_alert(user, "включено!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		balloon_alert(user, ("Вы включили сварочный аппарат."))
```suggestion
		balloon_alert(user, "выключено")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		balloon_alert(user, ("В сварочном аппарате закончилось топливо!"))
```suggestion
		balloon_alert(user, "закончилось топливо!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +			balloon_alert(user, ("Недостаточно топлива!"))
```suggestion
			balloon_alert(user, "недостаточно топлива!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +			balloon_alert(user, ("сварочный аппарат должен быть включён!"))
```suggestion
			balloon_alert(user, "выключено!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		balloon_alert(user, ("сварочный аппарат уже полон!"))
```suggestion
		balloon_alert(user, "топливный бак полон!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		balloon_alert(user, ("Ты заполнил сварочный аппарат [amount_transferred] u топлива."))
```suggestion
		balloon_alert(user, "заправлено")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +		balloon_alert(user, ("В [A] недостатачно топлива!"))
```suggestion
		balloon_alert(user, "недостаточно топлива!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/welder.dm
> +	desc = "Сварочный аппарат с увеличенным объемом бака."
```suggestion
	desc = "Сварочный аппарат с баком побольше."
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
>  		user.visible_message(
```suggestion
		visible_message("[user] перерезае[pluralize_ru(user.gender, "ет", "ют")] стяжки [target], используя [declent_ru(ACCUSATIVE)]!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
>  		)
```suggestion
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +			balloon_alert("стяжки перерезаны!"),
```suggestion
			balloon_alert(user, "стяжки перерезаны")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wirecutters.dm
> +	to_chat(user, span_notice("Вы присоединяете поддевающую головку к [declent_ru(DATIVE)]."))
```suggestion
	balloon_alert(user, "режим монтировки")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	to_chat(user, span_notice("Вы присоеденяете головку отвёртки к [declent_ru(DATIVE)]."))
```suggestion
	balloon_alert(user, "режим отвёртки")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/crowbar.dm
> +	to_chat(user, span_notice("Вы присоединяете режущую головку к [declent_ru(DATIVE)]."))
```suggestion
	balloon_alert(user, "режим кусачек")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/screwdriver.dm
> +	to_chat(user, span_notice("Вы присоединяете головку болтового сверла к [declent_ru(DATIVE)]."))
```suggestion
	balloon_alert(user, "режим гаечного ключа")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/tools/wrench.dm
> +	user.visible_message(span_suicide("[user] молится [declent_ru(DATIVE)] чтобы он взял [genderize_ru(user.gender, "его", "её", "его", "их")] душу. Похоже, что [genderize_ru(user.gender, "он", "она", "
```suggestion
	user.visible_message(span_suicide("[user] мол[pluralize_ru(user.gender, "ит", "ят")]ся [declent_ru(DATIVE)], чтобы он взял [genderize_ru(user.gender, "его", "её", "его", "их")] душу. Похоже, что [genderize_ru(user.gender, "он", "она", "оно", "они")] пыта[pluralize_ru(user.gender, "ет", "ют")]ся совершить самоубийство!"))
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCD.dm
> +	. += span_notice("Материя: [matter]/[max_matter] юнитов-материи.")
```suggestion
	. += span_notice("Материя: [matter]/[max_matter] единиц.")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCD.dm
> +		to_chat(user, span_notice("УБС не может принять больше юнитов-материи."))
```suggestion
		balloon_alert(user, "нет места!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCD.dm
> +		to_chat(user, span_warning("[rcd_ammo] is stuck to your hand!"))
```suggestion
		balloon_alert(user, "невозможно отцепить!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCD.dm
> +		to_chat(user, span_notice("Теперь в УБС [matter]/[max_matter] юнитов-материи."))
```suggestion
		balloon_alert(user, "картридж вставлен")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCD.dm
> +		to_chat(user, span_warning("Этот картридж материи несовместим с вашим УБС"))
```suggestion
		balloon_alert(user, "несовместимо!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCD.dm
> +	to_chat(user, span_notice("You change [src]'s mode to '[choice]"))
```suggestion
	to_chat(user, span_notice("Вы меняете режим [declent_ru(GENITIVE)] на [choice]."))
	balloon_alert(user, "режим изменён")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCD.dm
> +		to_chat(user, span_warning("Чтото мешает вам использовать [declent_ru(NOMINATIVE)] здесь..."))
```suggestion
		to_chat(user, span_warning("Что-то мешает вам использовать [declent_ru(ACCUSATIVE)] здесь."))
		balloon_alert(user, "невозможно!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCD.dm
> +	audible_message(span_danger("<b>[capitalize(declent_ru(ACCUSATIVE))] начинает громко вибрировать и жужжать!</b>"), span_danger("<b>[capitalize(declent_ru(ACCUSATIVE))] начинает сильно вибрировать!</
```suggestion
	audible_message(span_danger("<b>[capitalize(declent_ru(NOMINATIVE))] начинает громко вибрировать и жужжать!</b>"), span_danger("<b>[capitalize(declent_ru(NOMINATIVE))] начинает сильно вибрировать!</b>"))
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCD.dm
> +	desc = "Сильно спресованная материя в картриджи для УБС."
```suggestion
	desc = "Картридж для УБС, содержащий в себе спрессованную материю."
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCD.dm
> +		PREPOSITIONAL = "картридже материи"
```suggestion
		NOMINATIVE = "картридж УБС",
		GENITIVE = "картриджа УБС",
		DATIVE = "картриджу УБС",
		ACCUSATIVE = "картридж УБС",
		INSTRUMENTAL = "картриджем УБС",
		PREPOSITIONAL = "картридже УБС"
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCL.dm
> +			to_chat(user, span_notice("Вы загрузили провода в [declent_ru(ACCUSATIVE)]. В хранилище теперь [loaded.amount]."))
```suggestion
			balloon_alert(user, "провода загружены")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCL.dm
> +			balloon_alert(user, ("Хранилище проводов в [declent_ru(PREPOSITIONAL)] заполнено."))
```suggestion
			balloon_alert(user, "нет места!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCL.dm
> +		balloon_alert(user, ("Вы загрузили провода в [declent_ru(ACCUSATIVE)]."))
```suggestion
		balloon_alert(user, "провода загружены")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCL.dm
> +		to_chat(user, span_notice("Вы загрузили провода в [declent_ru(ACCUSATIVE)]. В хранилище теперь [loaded.amount]."))
```suggestion
		balloon_alert(user, "провода загружены")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCL.dm
> +	to_chat(user, span_notice("Вы откручиваете сбоку винты панели, что позволяет вам отсоединить её и снять провода."))
```suggestion
	balloon_alert("боковые винты откручены")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCL.dm
> +			to_chat(user, span_notice("Последний провод был размотан с [declent_ru(GENITIVE)]."))
```suggestion
			balloon_alert(user, "провода закончились!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/RCL.dm
> +		balloon_alert(user, ("[declent_ru(ACCUSATIVE)] пуст!"))
```suggestion
		balloon_alert(user, "провода отсутствуют!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/modules/power/cable.dm
> +	desc = "Гибкий сверхпроводящий кабель для передачи электроэнергии в суровых условиях"
```suggestion
	desc = "Гибкий сверхпроводящий кабель для передачи электроэнергии в самых суровых условиях"
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/modules/power/cable.dm
> +		to_chat(user, span_danger("Вы не можете взаимодействовать с тем, что находится под полом!"))
```suggestion
		balloon_alert(user, "невозможно!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/modules/power/cable.dm
> +			balloon_alert(user, ("Не хватает провода!"))
```suggestion
			balloon_alert(user, "недостаточно проводов!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/modules/power/cable.dm
> +			to_chat(user, span_warning("В [rcl.declent_ru(PREPOSITIONAL)] нет проводов!"))
```suggestion
			balloon_alert(user, "недостаточно проводов!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/modules/power/cable.dm
> +		to_chat(user, span_danger("Вы не можете взаимодействовать с тем, что находится под полом!"))
```suggestion
		balloon_alert(user, "невозможно!")
```

2024-12-12 11:26 UTC, PlayerUnknown14 commented on code/modules/power/cable.dm
> +	user.visible_message("[user] обрезал провода.", span_notice("Вы обрезали провода."))
```suggestion
	visible_message("[user] срезал[genderize_ru(user.gender, "", "а", "о", "и")] [declent_ru(ACCUSATIVE)].")
	balloon_alert(user, "провод срезан!")
```

2025-02-18 05:44 UTC, PlayerUnknown14 commented
Ой бля.

2025-02-18 05:44 UTC, closed without merging