tweak: Adds a refill canister for custom vendor
ss220-space/Paradise pull request #6202
Opened 2024-11-20 13:52 UTC by Mahimka42

## Описание
Добавляет канистру кастоммата в ассистентские.

## Причина создания ПР / Почему это хорошо для игры
https://discord.com/channels/617003227182792704/755125334097133628/1278225797471014963

## Тесты
Все просто отлично.

2024-11-21 07:05 UTC, Daeberdir requested changes
Попихай в ящики, подёргай пиксель икс-игреки. Не надо прятать вещи.

2024-12-27 15:22 UTC, SAADf603 commented
а чо оно две недели висит?

2024-12-27 15:29 UTC, SAADf603 approved these changes
Мапдифф бот + файл чжендед чек
аппрувед
единственное что я не понимаю, почему вендинги кастоматов добаляются отдельнм ПРом, но в ТЗ такое есть, так что пропускаем

2024-12-27 15:29 UTC, Antoonij approved these changes
со стороны кода проблем нет.

2024-12-27 15:35 UTC, merged