add: mecha cage, mecha alerts
ss220-space/Paradise pull request #6205
Opened 2024-11-20 23:45 UTC by NuSanya

## Описание

почему то был мёрж конфликт, не залили. предложка баунти, добавляет новый модуль и алёрты на мех

## Причина создания ПР / Почему это хорошо для игры

https://discord.com/channels/617003227182792704/755125334097133628/1284950351673430187

## Тесты

https://www.youtube.com/watch?v=nMl4fU3tho4
я не проверял сейчас, видео довольно старое

2024-11-20 23:53 UTC, NuSanya commented
мёрж конфликт не из-за моего кода, если правильно понимаю. при убирании кода из code/modules/antagonists/goon_vampire/goon_vampire_powers.dm остаётся конфликт.

2024-11-26 06:58 UTC, Antoonij requested changes

2024-11-26 06:58 UTC, Antoonij commented on code/_onclick/hud/alert.dm
> +//cage module
```suggestion
// MECH MODULES

// cage module
```
Codestyle

2024-11-26 06:58 UTC, Antoonij commented on code/game/mecha/equipment/tools/other_tools.dm
> +	return FALSE
такое добро нельзя держать в 1 проке, нужно разделить по прокам

2024-11-26 06:58 UTC, Antoonij commented on code/game/mecha/equipment/tools/other_tools.dm
> +	var/current_alert //wacky case
1. Тут лучше раписать автодок
2. Автодок начинается с 3 слешей и находится над переменной

2024-11-26 06:58 UTC, Antoonij commented on code/game/mecha/equipment/tools/other_tools.dm
> +//SCS-3 CAGE
```suggestion
// SCS-3 CAGE
```
codestyle

2024-11-26 06:58 UTC, Antoonij commented on code/game/mecha/equipment/tools/other_tools.dm
> +			stop_supressing(holding)
prisoner, holding, holding turf должны тут приводиться к нуллу

2024-11-26 06:58 UTC, Antoonij commented on code/game/mecha/equipment/tools/other_tools.dm
> +			H.throw_alert(alert_category, /atom/movable/screen/alert/mech_cage/three)
Тут происходит какой то пипец. Сделай ассоциативный список в самом мехакейдже с такими ключами, например STAGE_ZERO = /atom/movable/screen/alert/mech_cage/zero. Свитч тут снести, переделать прок на обращение к списку.

2024-11-26 06:58 UTC, Antoonij commented on code/game/mecha/equipment/tools/other_tools.dm
> +	current_alert = stage_number
название переменной current_alert не соответствует своему названию, а содержит в себе стадию. Изменить ее название.

2024-11-26 11:03 UTC, Antoonij commented on code/game/mecha/equipment/tools/other_tools.dm
> +				change_state("mecha_cage")
В данном PRе имеется огромное количество проблем, пока что в таком виде это не попадет в игру.

Передвижение заключенного можно отслеживать через сигналы, а не каждый тик в процессе

Хендкаффы также можно отслеживать через сигнал (правда новый придется сделать) и менять алерт в зависимости от того, анкаффнулся ли заключенный или нет. Это также не нужно проверять каждый тик в процессинге.

2024-11-26 13:17 UTC, NuSanya commented on code/game/mecha/equipment/tools/other_tools.dm
> +				change_state("mecha_cage")
Тяжело

2024-11-27 06:23 UTC, Antoonij commented on code/game/mecha/equipment/tools/other_tools.dm
> +			H.throw_alert(alert_category, /atom/movable/screen/alert/mech_cage/three)
Впрочем лучше сделай ассоциативный список, пожертвуем удобством

2024-11-27 06:27 UTC, Antoonij commented on code/game/mecha/equipment/tools/other_tools.dm
> +				change_state("mecha_cage")
Посмотри как работает RegisterSignal и SEND_SIGNAL. 

Нужно будет зарегистрировать сигнал COMSIG_MOVABLE_MOVED в моменте, когда заключенный присваивается, в сигнальном проке уже проверять как куда он двинулся.

Сначала потренируйся на этом, потом перейдешь к отправке сигналов на анкафф/хедкафф

2024-12-13 02:56 UTC, NuSanya commented on code/game/mecha/equipment/tools/other_tools.dm
> +			H.throw_alert(alert_category, /atom/movable/screen/alert/mech_cage/three)
сделал в итоге через subtypes

2024-12-31 05:08 UTC, PlayerUnknown14 requested changes
Запрещаю добавление в игру, пока весь добавляемый контент не будет предварительно русифицирован.

2024-12-31 06:21 UTC, NuSanya commented
переведено

2024-12-31 07:08 UTC, PlayerUnknown14 requested changes
Буквы - доработать.

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +	name = "Клетка SCS-3"
Названия не нужно переводить, пусть будет на английском.

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +	desc = "Модуль для экзокостюмов, используемый в задержании преступников."
```suggestion
	desc = "Модуль для экзокостюмов, используемый для задержании преступников."
	ru_names = list(
	    NOMINATIVE = "модуль \"Клетка SCS-3\"",
	    GENITIVE = "модуля \"Клетка SCS-3\"", 
	    DATIVE = "модулю \"Клетка SCS-3\"", 
	    ACCUSATIVE = "модуль \"Клетка SCS-3\"", 
	    INSTRUMENTAL = "модулем \"Клетка SCS-3\"", 
	    PREPOSITIONAL = "модулю \"Клетка SCS-3\""
	)
```

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +	occupant_message(span_notice("[target] не может быть удержа[genderize_ru(target.gender, "н", "на", "но", "ны")], так как [target] не находится в критическом состоянии"))
```suggestion
	occupant_message(span_notice("[target] не может быть удержа[genderize_ru(target.gender, "н", "на", "но", "ны")], так как [target] не наход[pluralize_ru(targer.gender, "ит", "ят")]ся в критическом состоянии."))
```

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +		occupant_message(span_notice("Ты перестаёшь удерживать [holding], и начинаешь удерживать [target]..."))
```suggestion
		occupant_message(span_notice("Вы перестаёте удерживать [holding] и начинаете удерживать [target]..."))
```
Ты -> Вы здесь и ниже.

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +		chassis.visible_message(span_warning("[chassis] перестаёт удерживать [holding] и сменяется на [target]."))
```suggestion
		chassis.visible_message(span_warning("[capitalize(chassis.declent_ru(NOMINATIVE))] перестаёт удерживать [holding] и начинает удерживать [target]."))
```

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +	occupant_message(span_notice("[target] успешно загруже[genderize_ru(target.gender, "н", "на", "но", "ны")]."))
```suggestion
	occupant_message(span_notice("[target] успешно помещ[genderize_ru(target.gender, "ён", "ена", "ено", "ены")] в клетку."))
```

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +	log_message("[prisoner] сбежа[genderize_ru(target.gender, "л", "ла", "ло", "лы")].")
Логи не переводим, они на английском.

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +	occupant_message("[prisoner] сбежа[genderize_ru(target.gender, "л", "ла", "ло", "лы")].")
Пропиши тут `span_warning` или типа того, чтобы текст выделялся.

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +		occupant_message(span_warning("[target] не помест[pluralize_ru(target.gender, "ится", "ятся")] в клетку, так как [target] прикова[genderize_ru(target.gender, "н", "нна", "нно", "нны")] к [target.bu
```suggestion
		occupant_message(span_warning("[target] не помест[pluralize_ru(target.gender, "ит", "ят")]ся в клетку, так как [target] прикова[genderize_ru(target.gender, "н", "на", "но", "ны")] к [target.buckled.declent_ru(DATIVE)]!"))
```

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +		occupant_message(span_warning("[target] не помест[pluralize_ru(target.gender, "ится", "ятся")] в клетку из-за прикованных к [genderize_ru(target.gender, "нему", "ней", "нему", "ним")] животным!"))
`has_buckled_mobs` относится только к слаймам, поэтому тут мы конкретно прописываем, что речь про них.

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +		occupant_message(span_warning("Невозможно отсоединить [src] - модуль работает!"))
```suggestion
		occupant_message(span_warning("Невозможно отсоединить [declent_ru(ACCUSATIVE)] - модуль работает!"))
```

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +	desc = "Сейчас кого-то своруют..."
Аналогично выше.

2024-12-31 07:08 UTC, PlayerUnknown14 commented on code/game/mecha/mecha.dm
>  			occupant_message(span_danger("Unable to move while in zoom mode."))
Здесь и выше перевести.

2025-01-05 09:30 UTC, PlayerUnknown14 requested changes
Почти.

2025-01-05 09:30 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +		chassis.visible_message(span_warning("[chassis] начинает удерживать [target]."))
Здесь и ниже прописать декленты, аналогично сообщению на 688 строке.

2025-01-05 09:30 UTC, PlayerUnknown14 commented on code/game/mecha/equipment/tools/other_tools.dm
> +	desc = "Сейчас кого-то своруют..."
Ру неймы.

2025-01-05 09:30 UTC, PlayerUnknown14 commented on code/game/mecha/mecha.dm
> +			occupant_message(span_notice("Ты перестаёшь удерживать [H.holding]."))
"Ты" нигде не прописываем в сообщениях.

2025-01-05 09:30 UTC, PlayerUnknown14 commented on code/modules/antagonists/changeling/powers/biodegrade.dm
> +		mech.visible_message(span_warning("Камера содержания [mech] начинает плавиться!"), \
Декленты

2025-01-12 01:23 UTC, closed without merging

2025-01-12 01:25 UTC, NuSanya commented
сделаю нормальный форк и пересоздам