Ремап Юридического отдела, декской и каталажек
ss220-space/Paradise pull request #6213
Opened 2024-11-22 18:22 UTC by Ravgolin

Перестройка Юр отдела и брига
Затрагивает:
Декскую, Каталажки, АВД рум, магистратскую, Суд.

Сам ремап значительно уменьшил Юридический отдел, в пользу места для зеков и техов. Из предметов ничего не поменялась кроме добавления в тюрмьу книг, книжных полок, штук для производство рыбо, и суши.
Также есть скрытый сейф в котором скрыт схрон неопасных химикатов. (но потазиум есть)

Так же  у схрона заготовлен рецепт ЛСД и дыма.

Впринципе Усё

2024-11-22 18:32 UTC, Ravgolin commented
так не понял в чём прекол, ноль ошибок в ДМ выдало, во падла.

2024-11-23 04:22 UTC, Den109G commented on _maps/map_files/Delta/delta.dmm
> +	id = "Cell 4","Cell 5","Cell 6","Cell 7";
Код не понимает что ты хочешь от него. Скорее всего, некорректно работает.

2024-11-23 06:08 UTC, SAADf603 commented on _maps/map_files/Delta/delta.dmm
> +	id = "Cell 4","Cell 5","Cell 6","Cell 7";
чзх
![image](https://github.com/user-attachments/assets/08c7026e-6edd-4c97-8781-b6ec6f400ca1)

2024-11-23 07:00 UTC, SAADf603 commented
Мгм, ага
![image](https://github.com/user-attachments/assets/fff58502-2816-4f64-b312-0a4098f91c59)

2024-11-23 07:41 UTC, SAADf603 requested changes
1) "Ебучий дым который всю камеру торкает" )))
Для начала было бы славно все бутылки убрать в напольный сейф(его нет), а бумагу на стол, иначе в бумаге есть смысл ровно на один ЕбУчИй))) раз, после которого игрок в тупую будет игнорить бумагу, ибо всё и так под рукой. 
2) Какой ещё нахуй "ебучий дым"? Вова Пуля, балять. Я понимаю, что "я художник, я так вижу, но это прям ЕбУчИй)) перебор
3) Концептуально отлично смотрящийся стол в стене
![image](https://github.com/user-attachments/assets/82a70338-9587-4c9d-a475-4f65ec75746a)
4) Вместо спавнера ивента грибка на стене поставлен сразу готовый гриб, что бы ЕбУчИе СБ))) даже расслабиться не могли, садя каторников в камеру "3456"
5) Камера 3456 концептуально отвратительна. Инстед оф быть "маленькой пермой" она будет просто выпускать одного преступника, а вместе с ним и всех прочих(нет не будет, двери не настроены). Офицерам нужно будет постоянно бегать и выпускать клоунов. А садить туда больше 2-ух человек на таймер просто бессмысленно, ибо двери не откроются, а выуживание одного из трёх - это всегда будет потасовка и жопаболь СБ. 
6) Полное непонимание как работают мониторы и двери камер. Таким образом мы имеем мониторы 12 и abcd в одной комнате, но что более уморительно монитор B открывает дверь камеры 2)))
![image](https://github.com/user-attachments/assets/33a41771-de64-4313-bdea-ae345181bfd0)
собсна в этом и ошибка файла
![image](https://github.com/user-attachments/assets/2c830ee4-9e73-410f-956c-98d8b10f1e03)
флешеры так не работают. так же а в чём концепт? любой монитор тригеррит все флешеры? 
7) Абсолютно не имеющий смысла карман, когда слева стоит окно, которое можно сломать и убежать сразу из общего коридора, игнорируя двери.
![image](https://github.com/user-attachments/assets/f47c8b6c-104d-4a07-a62e-b76e7da21b0b)
8) УгАрНаЯ мусорка для суицыда) 
![image](https://github.com/user-attachments/assets/a7773af8-d685-401c-bcda-7422268d71db)
9) Пропущен провод, видимо что бы сбегать игнорируя даже коридор СБ)
![image](https://github.com/user-attachments/assets/43392dbd-3ee2-45d4-b6ee-c6ff68ed8a65)
10) Техов дейстивтельно стало больше.  На одну не скрытую, глухую, никуда не ведущую коморку за счёт уменьшения суда.
![image](https://github.com/user-attachments/assets/766db009-31e3-44e4-8c05-a3b8d5587b6e)
Стоило ли оно того? Имхо нет. 

Я уверена, что есть что-то ещё, но этого для начала(или конца) я думаю достаточно. 

2 из 10

2024-11-23 12:21 UTC, Ravgolin commented on _maps/map_files/Delta/delta.dmm
> +	id = "Cell 4","Cell 5","Cell 6","Cell 7";
блин, а как сразу несколько id  в 1 объект вписать, по задумке есть 4 панели где указывают срок, а место в котором нужно юзать флешер одно, не плодить же 4 флешера на каждый id.
Есть корректный способ реализовать мою шнягу?

2024-11-23 12:26 UTC, Ravgolin commented
Ладно, мне сказали достаточно претензий, по которым данный концепт стоит изменить. Денёк-два на подумать и настрать турфами заново.

2024-11-23 16:44 UTC, Den109G commented on _maps/map_files/Delta/delta.dmm
> +	id = "Cell 4","Cell 5","Cell 6","Cell 7";
>Есть корректный способ реализовать мою шнягу?

Вписать в лист эти айди. Нет, не будет работать, ибо сейчас код работает по "1 кнока - 1 айди", и если ты впишешь в лист, то будет искать (условно) не 4 камеры (4,5,6,7), а одну камеру 4567. Надо менять тебе код.

2024-12-01 14:32 UTC, SAADf603 commented
![image](https://github.com/user-attachments/assets/b24861dc-93ac-42a6-9d56-0e015f80376c)

2024-12-23 11:03 UTC, SAADf603 commented
![image](https://github.com/user-attachments/assets/d3645c4d-a5c0-4e45-a720-fa6ba348e3df)

2025-01-05 19:41 UTC, closed without merging