Перевод способностей вампиров
ss220-space/Paradise pull request #622
Opened 2022-01-30 02:55 UTC by Ohar

## What Does This PR Do

Перевод всех способностей вампира

## Why It's Good For The Game

Улучшает погружение

## Changelog
:cl:
tweak: Перевод всех способностей вампира
/:cl:

2022-03-10 05:30 UTC, Vallat approved these changes

2022-03-10 14:04 UTC, TrashDoxx approved these changes

2022-03-12 06:23 UTC, botPurple requested changes
В своих лучших традициях, тебе нужно поработать над радикальностью перевода.

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Омоложение"
Не надо сильно придумывать своё, на википедии "Восстановление"

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +				to_chat(user, "<span class='warning'>Ваш пронзительный взгляд не смог вырубить [target].</span>")
Лучше использовать не "вырубить", а "оглушить"/"ошеломить"

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +				to_chat(user, "<span class='warning'>Ваш пронзающий взгляд вырубает [target].</span>")
Лучше использовать не "вырубить", а "оглушить"/"ошеломить"

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Заражающее касание (50)"
Требует обновление википедии на твой вариант

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Вы незаметно заражаете [target] заражающим касанием.</span>")
Чтобы убрать тавтологию, лучше заменить на "Вы незаметно инфицируете"

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Вспышка"
Хоть я и не фанат такого варианта перевода, но он лучше подходит, чем "Блик". Требуется обновить вики на твой вариант

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Оборотень (50)"
Замени на "Превращение"

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Визг рукокрылых (30)"
Научное название летучих мышей - Chiroptera. "Рукокрылы" звучит смешно и странно одновременно. Рекомендую изменить перевод тут и в других местах на "Ультразвуковой визг" из-за того, что летучие мыши издают ультразвук

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		log_runtime(EXCEPTION("При порабощении моба случилось что-то плохое. Атакующий: [user] [user.key] \ref[user]"), user)
"моба" на "существа"

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	serve_objective.explanation_text = "Вы были порабощены [user.real_name]. Выполняйте все [user.p_their()] приказы."
Я правильно понимаю, что тут ([user.p_their()]) будет "him" "her" "they"? Если да, то это кринж

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Плащ тьмы"
На иконке способности не плащ, поэтому лучше подойдет и по смыслу и по иконке "Покров тьмы"

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность Плащ тьмы, которая, будучи включённой, делает вас практически невидимыми под покровом тьмы"
"...вас практически невидимым в темноте"

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Дети ночи (50)"
Не понял от куда взялось такое название, если уверен, что хочешь его оставить - то обнови вики

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	desc = "Вы на короткое время превращаетесь в облачко тумана"
Уменьшительно ласкательная форма тут неуместна

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	desc = "Призовите смертоносных вампиров из синего космоса."
Никаких синих космосов. Блюспейс. Мы уже обсуждали эту тему и я не понимаю, почему ты игнорируешь остальных и настаиваешь только на своём варианте перевода.

2022-03-12 06:23 UTC, botPurple commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	to_chat(user, "<span class='warning'>Вы взываете по синему космосу, призывая больше вампирских духов себе на помощь!</span>")
Синий космос на блюспейс

2022-03-12 09:29 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Омоложение"
Поправил

2022-03-12 09:32 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +				to_chat(user, "<span class='warning'>Ваш пронзающий взгляд вырубает [target].</span>")
Да дело в том что он не оглушает (не глухота) и не ошеломляет (не как станбатон), он именно усыпляет.
Заменил на «завораживает».

2022-03-12 09:33 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Вы незаметно заражаете [target] заражающим касанием.</span>")
Поправил

2022-03-12 09:35 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Дети ночи (50)"
Половина способностей вампира — отсылки к [вампиру из D&D](http://dm-stuff.ru/creature-catalog/vampire), призыв летучих мышей в том числе.

2022-03-12 09:37 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	desc = "Вы на короткое время превращаетесь в облачко тумана"
Убрал

2022-03-12 09:38 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	desc = "Призовите смертоносных вампиров из синего космоса."
Да я тупо забыл про то что тут тоже был блюспейс

2022-03-12 09:48 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	to_chat(user, "<span class='warning'>Вы взываете по синему космосу, призывая больше вампирских духов себе на помощь!</span>")
Исправил, переформулировал

2022-03-12 09:49 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность Плащ тьмы, которая, будучи включённой, делает вас практически невидимыми под покровом тьмы"
Исправил

2022-03-12 09:50 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Заражающее касание (50)"
Поправил

2022-03-12 09:51 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +				to_chat(user, "<span class='warning'>Ваш пронзительный взгляд не смог вырубить [target].</span>")
Исправил

2022-03-12 09:52 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Вспышка"
Поправил

2022-03-12 09:53 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Оборотень (50)"
Заменил

2022-03-12 09:55 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Визг рукокрылых (30)"
Да, а [по-русски они именно рукокрылые](https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D0%BA%D0%BE%D0%BA%D1%80%D1%8B%D0%BB%D1%8B%D0%B5), не согласен с тобой.

2022-03-12 09:57 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		log_runtime(EXCEPTION("При порабощении моба случилось что-то плохое. Атакующий: [user] [user.key] \ref[user]"), user)
Именно «моба», это админские логи.

2022-03-12 09:58 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	serve_objective.explanation_text = "Вы были порабощены [user.real_name]. Выполняйте все [user.p_their()] приказы."
Кринж, согласен.
Но иначе пока что никак

2022-03-12 09:58 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	name = "Плащ тьмы"
Исправил

2022-03-12 20:20 UTC, Ohar commented
> В своих лучших традициях, тебе нужно поработать над радикальностью перевода.

Все вроде поправил

2022-03-18 18:54 UTC, Ohar commented
> В своих лучших традициях, тебе нужно поработать над радикальностью перевода.

@botPurple Вроде всё поправил

2022-03-19 00:43 UTC, Ohar commented
Добавил ещё перевод сообщений в чате
@BOTpurple#7181 Проведи ревью, пожалуйста

2022-04-07 18:22 UTC, botPurple approved these changes

2022-04-07 19:03 UTC, TrashDoxx requested changes
Доёбываюсь до мелочей, ряя.

2022-04-07 19:03 UTC, TrashDoxx commented on code/game/gamemodes/vampire/vampire.dm
> +Вы уязвимы перед святость и звёздным светом. Не выходите в космос, избегайте священника, церкви и, особенно, святой воды."}
```suggestion
Вы уязвимы перед святостью и звёздным светом. Не выходите в космос, избегайте священника, церкви и, особенно, святой воды."}
```

2022-04-07 19:03 UTC, TrashDoxx commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность навсегда обернуться другим обликом, тратя 50 крови."
Трижды пишем конкретные показатели, ну такое.
```suggestion
	gain_desc = "Вы получили способность навсегда обернуться другим обликом, затратив часть накопленной крови."
```

2022-04-07 19:03 UTC, TrashDoxx commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность Порабощение, которая тратит много крови, но позволяет вам поработить человека, который ещё никому не служит, на случайный период времени."
Везде с малой, тут с большой.
```suggestion
	gain_desc = "Вы получили способность порабощения, которая тратит много крови, но позволяет вам поработить человека, который ещё никому не служит, на случайный период времени."
```

2022-04-07 19:03 UTC, TrashDoxx commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность Покров тьмы, которая, будучи включённой, делает вас практически невидимыми в темноте"
```suggestion
	gain_desc = "Вы получили способность к маскировке, которая, будучи включённой, делает вас практически невидимым в темноте."
```

2022-04-07 19:03 UTC, TrashDoxx commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность шагать в тень, позволяющую вам, тратя кровь, исчезать в ближайшей тени."
```suggestion
	gain_desc = "Вы получили способность шага в тень, позволяющую вам, затратив часть крови, оказаться в ближайшей тени."
```

2022-04-07 19:12 UTC, TrashDoxx approved these changes
Замечательная работа.

2022-04-11 10:02 UTC, girafe969 requested changes
Я тут накалякал. В некоторых местах больше пища для размышлений, чем конкретные правки.

2022-04-11 10:02 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	desc = "Жуткая вспышка, ненадолго ошеломляющая всех людей вокруг"
Раз уж назвали вспышкой вместо взгляда (про игру слов на английском, думаю, все поняли), надо хотя бы в описании указать, что эта вспышка из глаз, так как это важно. Я бы оставил вариант из вики "Вы сверкаете глазами, ненадолго ошеломляя всех людей вокруг".

2022-04-11 10:02 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Вас ослепляет!</span>")
У вас на глазах повязка!

2022-04-11 10:02 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(target, "<span class='warning'>Вы ослеплены вспышкой [user].</span>")
тут тоже стоит добавить "из глаз". Это поможет понять ингейм, что надев повязку на глаза вампиру
 вспышка вам будет не страшна.

2022-04-11 10:02 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		user.visible_message("<span class='warning'>[user] кусает [target] в шею!</span>", "<span class='warning'>Вы кусаете в шею [target]и начинаете выкачивать силу.</span>")
Не выкачивать силу, а наоборот. Это обратный процесс. "и начинаете передачу сил" - нейтральный вариант, работающий в обе стороны

2022-04-11 10:02 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность к маскировке, которая, будучи включённой, делает вас практически невидимым в темноте."
Может, стоит более высокопарно перевести? "во тьме" вместо "в темноте"

2022-04-11 10:02 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность «Заражающее касание». Она позволит вам ослаблять тех, кого вы коснётесь до тех пор, пока их не вылечат."
Стоит привести все "Вы получили способность ... " к единому виду, а то у тебя где-то Название способности, где-то "Название способности", где-то название способности, где-то заменено название на схожие слова

2022-04-11 10:02 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			to_chat(user, "<span class='warning'>Вам кажется, что могильная лихорадка не подействовала на [target].</span>")
откуда взялась могильная лихорадка? До этого это название нигде не всплывало

2022-04-11 10:02 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	to_chat(user, "<span class='warning'>Ваш зов расходится в блюспейсе, на помощь созывая других вампирских духов!</span>")
Мелкий доеб. "созывая на помощь" звучит лучше

2022-04-11 13:57 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	desc = "Жуткая вспышка, ненадолго ошеломляющая всех людей вокруг"
Поправил

2022-04-11 13:57 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(user, "<span class='warning'>Вас ослепляет!</span>")
И верно.
Поправил

2022-04-11 13:57 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		to_chat(target, "<span class='warning'>Вы ослеплены вспышкой [user].</span>")
Поправил

2022-04-11 13:59 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		user.visible_message("<span class='warning'>[user] кусает [target] в шею!</span>", "<span class='warning'>Вы кусаете в шею [target]и начинаете выкачивать силу.</span>")
Почему? Это текст для вампира, когда он сосёт кровь. Он буквально выкачивает силу из жертвы.

2022-04-11 14:02 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		user.visible_message("<span class='warning'>[user] кусает [target] в шею!</span>", "<span class='warning'>Вы кусаете в шею [target]и начинаете выкачивать силу.</span>")
Поправил

2022-04-11 14:03 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность «Заражающее касание». Она позволит вам ослаблять тех, кого вы коснётесь до тех пор, пока их не вылечат."
Может и стоит но я делаю только перевод, а не улучшение.
Если начать улучшать, то тут можно надолго закопаться. Это надо делать потом, отдельно.

2022-04-11 14:05 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность к маскировке, которая, будучи включённой, делает вас практически невидимым в темноте."
Я так и сделал, но [Бот, наоборот, попросил поменять](https://github.com/ss220-space/Paradise/pull/622#discussion_r825254864).

2022-04-11 14:08 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			to_chat(user, "<span class='warning'>Вам кажется, что могильная лихорадка не подействовала на [target].</span>")
[Всплывало на вики](https://wiki.ss220.space/index.php/Руководство_по_вирусологии#Grave_Fever). 
Ну и в переводе болезней [она тоже будет так называться](https://github.com/ss220-space/Paradise/pull/685/files#diff-dd4ead50c8b0d7f00659c19432c680c8ab328148f7eb5a72f78c24da47cec5c4R2).

2022-04-11 14:09 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	to_chat(user, "<span class='warning'>Ваш зов расходится в блюспейсе, на помощь созывая других вампирских духов!</span>")
Нет, потому что это нарушает ритм белого стиха

2022-04-11 14:18 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность «Заражающее касание». Она позволит вам ослаблять тех, кого вы коснётесь до тех пор, пока их не вылечат."
Ну изначально на англе везде было "Вы получили способность Такую-то, которая..."
А в процессе перевода у тебя все пошло по пезде

2022-04-11 14:27 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			to_chat(user, "<span class='warning'>Вам кажется, что могильная лихорадка не подействовала на [target].</span>")
Но будучи вампиром, ты вообще можешь не знать что такое могильная лихорадка и что твоя способность ей заражает, так как нигде в описании способности этого нет

2022-04-11 14:39 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	to_chat(user, "<span class='warning'>Ваш зов расходится в блюспейсе, на помощь созывая других вампирских духов!</span>")
Ваш зов расходится в блуспейсе,
(-+-+---+-)
На помощь созывая других вампирских духов
(-+---+--+-+-+-)
В слове созывая ударение не на первом слоге)

2022-04-11 14:57 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	gain_desc = "Вы получили способность «Заражающее касание». Она позволит вам ослаблять тех, кого вы коснётесь до тех пор, пока их не вылечат."
Унифицировал чутка

2022-04-11 14:59 UTC, Ohar commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			to_chat(user, "<span class='warning'>Вам кажется, что могильная лихорадка не подействовала на [target].</span>")
Понял о чём ты. Заменил на «заражающее касание».

2022-04-11 15:33 UTC, girafe969 requested changes
Красиво делаешь, мелкие правки.

2022-04-11 15:33 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire.dm
> +				text += "[vampire.name] (тело было уничтожено"
[vampire.name] ( тут лишнее, оно уже есть в 85 строке

2022-04-11 15:33 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire.dm
> +				text += "[Mind.name] (тело было уничтожено"
То же что с 94 строкой, уже есть в 129

2022-04-11 15:33 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		gain_desc = "Вы получили способность [src]."
«[src]».

2022-04-11 15:33 UTC, girafe969 commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		gain_desc = "Вы получили способность [src]."
«[src]». Чтобы уже всё в один вид привести

2022-04-11 16:12 UTC, girafe969 approved these changes
Галка отдалась. Поздравим её и тебя

2022-04-23 14:32 UTC, merged