rework:borers punish host action
ss220-space/Paradise pull request #6228
Opened 2024-12-05 13:13 UTC by Anorak2024

## Описание
Улучшение способки агонии у бореров (та что во время контроля хоста)
Теперь будет тратить 70 химикатов
С каждым повышением ранга стоимость снижается на 10
Во время контроля сбрасывает прогресс бар хоста на сопротивление.
(Убрано во время гвоута. Нет в ПРе.)~Борер будет видеть прогресс бар резиста хоста.~
Вне контроля также можно будет применить НО уже будет ложить в стаминокрит а не сбрасывать что либо.
И всё также будет писать красные буковки в чат хосту.

## Причина создания ПР
https://discord.com/channels/617003227182792704/755125334097133628/1310947058915741759

## Тесты
Кастанул без химикатов. Написало что не хватает.
Кастанул вне контроля, хост упал в стаминакрит, химикаты потратились.
Кастанул во время контроля, во время сопротивления. Сопротивление сбросилось.

2024-12-05 14:33 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	adjustStaminaLoss(100)
1. Присваивание кастера можно делать через ? и :, вместо несколько ифов
2. это стоит сделать проком у самого экшенса, а не карбона

2024-12-05 16:29 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	adjustStaminaLoss(100)
Поправил

2024-12-07 07:07 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	return TRUE
Зачем это тут вместе с доп переменной, если сразу тут можно возвращать 
host_resisting 
и менять в экшене пуниша именно host_resisting, а не шулд стоп резист

2024-12-07 07:09 UTC, Antoonij commented on code/modules/antagonists/borer/borer_rank.dm
> +	var/rank
переменная с непонятным названием, может быть какой нибудь rank_ability_amplifier или что то подобное?

2024-12-07 15:45 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	return TRUE
поменял

2024-12-07 15:46 UTC, Anorak2024 commented on code/modules/antagonists/borer/borer_rank.dm
> +	var/rank
поменял

2024-12-07 16:25 UTC, Antoonij commented on code/modules/antagonists/borer/borer_action.dm
> +			вырывая беззвучный крик из глубин вашего разума!</FONT>"))
```suggestion
	borer.chemicals -= cost
	
	to_chat(owner, span_danger("Вы посылаете карающий всплеск психической агонии в мозг своего носителя."))
	to_chat(host, span_danger("<FONT size=3>Ужасная, жгучая агония пронзает вас насквозь, \
			вырывая беззвучный крик из глубин вашего разума!</FONT>"))
			
	if(borer.host_brain)
		borer.host_brain.host_resisting = FALSE
		return

```
codestyle optimize + по сути убираем лишний тучат путем перестановки в нужное место

2024-12-07 16:25 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	var/datum/action/innate/borer/torment/torment_when_controlling_action = new
уже в /datum/action/innate/borer/torment были покрыты 2 случая - поэтому смысла в новом экшене тормента - нет.

2024-12-07 16:30 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	var/datum/action/innate/borer/torment/torment_when_controlling_action = new
Там вторая не из-за разных случаев, а из-за того, что одним действием может владеть только одно существо (либо борер, либо хост под контролем борера). (По крайней мере я так понял.) Убрал второе действие сделав убирание владения этим действием перед выдачей заново.

2024-12-07 16:34 UTC, Antoonij commented on code/modules/antagonists/borer/borer_action.dm
> +		return
```suggestion
	var/mob/living/simple_animal/borer/borer = isborer(owner) ? owner : owner.has_brain_worms()
	var/mob/living/carbon/host = borer.host
	
	var/cost = 70 - (borer.antag_datum.borer_rank.rank_ability_amplifier * 10)
	
	if(borer.chemicals < cost)
		to_chat(owner, "Вам требуется [cost] химикатов для вызова психической агонии!")
		return
```
more codestyle + умножение в скобочках

2024-12-07 16:34 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Grant(src)
```suggestion
	torment_action.Remove(host)
```
очепятка, полагаю

2024-12-07 16:34 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Remove(src)
```suggestion
	torment_action.Grant(host)
```
также

2024-12-07 16:36 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Grant(src)
Нет, чуть выше расписал. Чтобы действие дать кому-то другому, надо его удалить у текущего владельца. До этого было два действия.

2024-12-07 16:36 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Remove(src)
аналогично

2024-12-07 16:38 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Grant(src)
В инфесте это все равно выдается и забирается у борера. В контроллинге выдаем уже этот экшен только хосту, иначе при контроле у борера не будет этой кнопки

2024-12-07 16:43 UTC, Antoonij submitted a review, later dismissed
теперь выглядит хорошо

2024-12-07 16:52 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Grant(src)
На локалке проверил, теперь при возвращении контроля нет действия агонии.

2024-12-07 16:53 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Grant(src)
Может вернем мой вариант, который скорее всего работает?

![image](https://github.com/user-attachments/assets/b1d97dd6-82f7-44ba-9586-14fac5fa5ffa)
Это как-то вообще не правильно выглядит.

2024-12-07 16:56 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Grant(src)
Вижу, недоглядел. Эти строки там по просту не нужны

2024-12-07 16:58 UTC, Anorak2024 commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Grant(src)
У меня уже раньше была выдача одного и того же действия и бореру и подконтрольному носителю. Оно не работало.

2024-12-07 17:06 UTC, Antoonij commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Grant(src)
Нет, проблема была в том, что мы не забирали способности у борера. Костыльное решение я не одобряю, поэтому доработал

2024-12-07 17:10 UTC, Antoonij approved these changes, later dismissed
Вот теперь - идеальна catsmile

2024-12-07 20:44 UTC, Daeberdir requested changes
Work in progress.

2024-12-11 15:32 UTC, Anorak2024 commented
@Antoonij, потестил. Ничего странного не заметил.

2024-12-11 18:33 UTC, pilygun commented
бл ну ебана бобана, способность то бесполезная, так еще и лоровед наныл на нерф что бы еще бесполезней была

2024-12-11 18:35 UTC, pilygun commented
Какие 70 химикатов? Ебанулись что ли. Даже на фул прокачке 50 химикатов это много. А учитывая что прогесбара не видно можно просто проебать в пустую химикаты. Кто вообще ведущему лоровуду слово давал, нахуй его слушали

2024-12-11 18:36 UTC, pilygun commented
Капулентий за 30 часто сложно юзнуть, а тут 70!!!! ну это вообще не в какие ворота

2024-12-12 15:07 UTC, Daeberdir commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	if(!do_after(src, delay, B.host, ALL, max_interact_count = 1))
`delay` переменная не имеет смысла.

2024-12-12 15:17 UTC, Daeberdir commented on code/game/gamemodes/miniantags/borer/borer.dm
> +	torment_action.Remove(src)
Тормент акшну стоит сделать третий отдельный прок, который будет вызываться только при залезании/вылезании в/из хоста.

2024-12-30 11:31 UTC, merged