add: Adds an immunity to gravity damage for 5 seconds after exhaustion
ss220-space/Paradise pull request #6243
Opened 2024-12-10 06:58 UTC by Vladisvell

## Описание

Дает иммунитет от стаминадамага от перехода из среды без гравитации в среду с гравитацией в течение пяти секунд после получения урона по стамине от перехода.
## Причина создания ПР / Почему это хорошо для игры
Шашечки в космосе
## Демонстрация изменений
https://github.com/user-attachments/assets/e892d808-af24-4db0-9c8e-c6126a3650c1

2024-12-10 07:47 UTC, Den109G commented on code/_globalvars/traits.dm
> +		"TRAIT_NO_GRAVITY_DAMAGE" = TRAIT_NO_GRAVITY_DAMAGE,
> USE ALPABETIC ORDER HERE! (please)
Поставь это возле у других `TRAIT_NO_`

2024-12-17 12:08 UTC, Antoonij requested changes

2024-12-17 12:08 UTC, Antoonij commented on code/modules/mob/living/carbon/human/human_movement.dm
> +	REMOVE_TRAIT(src, TRAIT_NO_GRAVITY_DAMAGE, "gravity_exhaustion")
всё это добро переписать с трейта на бафф + сигнал

2024-12-30 09:43 UTC, BeebBeebBoob commented on code/modules/mob/living/carbon/human/human_movement.dm
> +	REMOVE_TRAIT(src, TRAIT_NO_GRAVITY_DAMAGE, "gravity_exhaustion")
Варится долго, снял с тестмержов, этот вопрос стоит решить

2025-01-16 03:45 UTC, closed without merging