qol: kitchen and grinder machinery hotkeys
ss220-space/Paradise pull request #6245
Opened 2024-12-10 23:52 UTC by FlitchTime

## Описание
Добавил хоткеи для машинерии кухни и гриндера

## Причина создания ПР / Почему это хорошо для игры
Qol

## Демонстрация изменений
![Ксено](https://github.com/user-attachments/assets/dc7401cf-7249-46b1-8db2-79423398ed54)
А кухни не будет. Она больше 10 мб

## Тесты
Запустил локалку и потыкал в том числе в процессе работы машинерии

2024-12-11 06:29 UTC, Antoonij requested changes

2024-12-11 06:29 UTC, Antoonij commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +	dispose()
должна быть проверка на близость юзера к машинерии, что у него не заблокированы руки и кукла не incapacitated, иначе у нас будут мобы, которые включают эти машины за многомиллионное расстояние без учета их состояния

2024-12-11 06:29 UTC, Antoonij commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +	detach(user)
аналогично комментарию выше

2024-12-11 10:26 UTC, FlitchTime commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +	dispose()
Проверяй

2024-12-11 10:33 UTC, Antoonij commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +		return
```suggestion
/obj/machinery/kitchen_machine/AltClick(mob/living/carbon/human/human)
	if(!istype(human))
		return
	
	if(!Adjacent(human))
		return
		
	if(human.incapacitated() || HAS_TRAIT(human, TRAIT_HANDS_BLOCKED))
		return
		
	if(operating)
		return
		
```
Перестановка логической цепочки + сокращение + кодстайл в виде пустых строк после ретарнов. Сделай также и в остальных

2024-12-11 10:38 UTC, FlitchTime commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +		return
Зачем после ретёёрнов-то? Я не в погоне за +1 за каждую проверку

2024-12-11 10:40 UTC, Antoonij commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +		return
Таков кодстайл

2024-12-11 10:44 UTC, FlitchTime commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +		return
Не, не пон
![image](https://github.com/user-attachments/assets/a89c58d8-45e6-44b7-8945-b6ef425b24dd)

2024-12-11 10:45 UTC, FlitchTime commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +		return
Чекай. Кодстайл это ложь

2024-12-11 10:50 UTC, Antoonij commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +/obj/machinery/kitchen_machine/proc/dispose(mob/user)
в этом проке, на 494 строке выводится сообщение usr, надо использоваь уже моба в аргументе, иначе не будет сообщений при использовании альтклика, также в /Topic китчен машины надо будет передавать usr в cook и dispose как аргумент

2024-12-11 10:50 UTC, Antoonij commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
>  		if (usr.stat != 0)
сделать аналогично комментарию выше - использовать уже моба из аргумента, а не usr. В /Topic реагентгриндера также в этот прок передавать usr

2024-12-11 10:50 UTC, Antoonij commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +	dispose()
в диспоуз уже нужно передавать нашего моба

2024-12-11 10:52 UTC, Antoonij commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +		return
> Чекай. Кодстайл это ложь

Это обязательное требования для читаемости кода, также я вижу учтено не все то, что я писал

2024-12-11 11:12 UTC, FlitchTime commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +/obj/machinery/kitchen_machine/proc/dispose(mob/user)
"Надо использовать моба" объясни. Я твоя не понимать, а лучше напиши в пример

2024-12-11 11:14 UTC, FlitchTime commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +		return
Что я забыл тут?

2024-12-11 11:15 UTC, Antoonij commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +/obj/machinery/kitchen_machine/proc/dispose(mob/user)
в этом проке "моб в аргументе" - /obj/machinery/kitchen_machine/proc/dispose(mob/user) - user. Аргументы это то, что идет в скобках

2024-12-11 11:16 UTC, Antoonij commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +/obj/machinery/kitchen_machine/proc/dispose(mob/user)
а использование - в 494 строке вместо usr использовать user, т.е нашего моба в аргументе

2024-12-11 11:32 UTC, FlitchTime commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +/obj/machinery/kitchen_machine/proc/dispose(mob/user)
Чекай снова

2024-12-11 11:50 UTC, Antoonij commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +	beaker.loc = src.loc
```suggestion
	beaker.forceMove(get_turf(src))
```
А тут импрув через использование прока для перемещения объектов

2024-12-11 16:27 UTC, FlitchTime commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +	beaker.loc = src.loc
Так, мы уже в рефакторинг переходим или зачем мы сюда лезем?

2024-12-15 08:08 UTC, Antoonij approved these changes
Теперь пойдет. Хоткеи - полезная штука, не придется клацать в интерфейс.

2024-12-15 14:38 UTC, merged