qol: add check security verb for admins
ss220-space/Paradise pull request #6261
Opened 2024-12-20 22:33 UTC by FlitchTime

## Описание
Добавляем админский верб check security

## Причина создания ПР / Почему это хорошо для игры
[admin qol](https://discord.com/channels/617003227182792704/1319637392055074826)

## Демонстрация изменений
![image](https://github.com/user-attachments/assets/b0ee0d6f-14e9-475a-ac42-85e6976cb6aa)

## Тесты
Локалка

2024-12-21 14:43 UTC, Daeberdir commented on code/modules/admin/admin_verbs.dm
> +	log_admin("[key_name(usr)] checked secutiry")
security

Логирование точно нужно? Переспроси у одмэмов.

2024-12-21 14:45 UTC, Daeberdir commented on code/modules/admin/admin_verbs.dm
> +	SSblackbox.record_feedback("tally", "admin_verb", 1, "Check Secs") //If you are copy-pasting this, ensure the 4th parameter is unique to the new proc!
Секс чек 
![image](https://github.com/user-attachments/assets/0f4e14c8-0c78-41d6-ad15-1dc406bc90fe)

2024-12-21 14:46 UTC, Daeberdir commented on code/modules/admin/admin_verbs.dm
> +	return
Нету никакого смысла в пустом ретурне в конце функции. Она тут кончается в любом случае.
```suggestion
```

2024-12-21 14:50 UTC, Daeberdir commented on code/modules/admin/player_panel.dm
> +	return txt
```suggestion
			dat += check_role_table("ERT", SSticker.mode.ert, FALSE)

		usr << browse(dat, "window=roundstatus;size=600x800")

	else
		alert("The game hasn't started yet!")
```

2024-12-21 15:11 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +	logout_status = M.client ? "" : " <i>(logged out)</i>"
```suggestion
	var/logout_status = = M.client ? "" : " <i>(logged out)</i>"
```
можно сразу сделать так.

2024-12-21 15:11 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +		job = "Cyborg"
1. зачем нам такая излишняя деструктуризация
2. мобы попадающие сюда и должны быть только хуманами (get_all_sec() же возвращает майнды хуманов), зачем лишний раз это переобъявлять. 
3. 1 параметр функции поменять с mob/M на mob/living/carbon/human/human - с понятным названием.

2024-12-22 08:33 UTC, FlitchTime commented on code/modules/admin/admin_verbs.dm
> +	log_admin("[key_name(usr)] checked secutiry")
![image](https://github.com/user-attachments/assets/d593d0a3-7571-49aa-aa47-df85482e3f3b)

2024-12-22 08:34 UTC, FlitchTime commented on code/modules/admin/admin_verbs.dm
> +	SSblackbox.record_feedback("tally", "admin_verb", 1, "Check Secs") //If you are copy-pasting this, ensure the 4th parameter is unique to the new proc!
Да, я знал, что найдутся ценители

2024-12-22 08:34 UTC, FlitchTime commented on code/modules/admin/admin_verbs.dm
> +	return
Пон, уберу

2024-12-22 08:36 UTC, FlitchTime commented on code/modules/admin/player_panel.dm
> +	return txt
Она нужна, т.к. я свою check_security_line использую

2024-12-22 08:37 UTC, FlitchTime commented on code/modules/admin/player_panel.dm
> +	logout_status = M.client ? "" : " <i>(logged out)</i>"
Ок

2024-12-22 08:48 UTC, FlitchTime commented on code/modules/admin/player_panel.dm
> +		job = "Cyborg"
Не совсем понял 1-ый пункт, но изменил вроде, как ты хотел. Глянь короче

2024-12-22 09:16 UTC, Antoonij requested changes

2024-12-22 09:16 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +		job = "Cyborg"
зачем это тут? гет олл сек возвращает только майнды хуманов, из которых мы и извлекаем только хуманов. Убрать.

2024-12-22 09:16 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +		dname = human
зачем это тут?

2024-12-22 09:16 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +	return {"<tr><td><a href='byond://?src=[UID()];adminplayeropts=[human.UID()]'>[dname]</a>[logout_status]</td><td>[job][human.stat == 2 ? " <b><font color=red>(Dead)</font></b>" : "<font color=green>
```suggestion
	return {"<tr><td><a href='byond://?src=[UID()];adminplayeropts=[human.UID()]'>[dname]</a>[logout_status]</td><td>[job][human.stat == DEAD ? " <b><font color=red>(Dead)</font></b>" : "<font color=green> [human.health]%</font>"] <b>[area_name]</b> [coords[1]],[coords[2]],[coords[3]]</td><td><a href='byond://?src=[usr.UID()];priv_msg=[human.client?.ckey]'>PM</A> [ADMIN_FLW(human, "FLW")]</td>[close ? "</tr>" : ""]"}
```
статы DEAD, ALIVE и т.п - дефайны, а не магические числа, поэтому дефайны и используем

2024-12-22 09:16 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +	var/list/coords = ATOM_COORDS(GT)
ненужная, бесполезная деструктуризация с извлечением объектов, которые мы по итогу не используем, ибо:
в get_area_name можно сразу и передать хумана, оно вычислит его area и выдаст его нейм
в ATOM_COORDS также можно передать хумана, ибо у атомов есть .x .y .z
а dname и job просто убрать, вместо этого и использовать переменные хумана

2024-12-22 09:16 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +				dat += check_security_line(M)
```suggestion
		for(var/datum/mind/mind in SSticker.mode.get_all_sec())
			if(mind.current)
				dat += check_security_line(mind.current)
```
зачем опять что то деструктуризировать? Также используй нормальные названия для переменных

2024-12-22 09:16 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +	if(SSticker && SSticker.current_state >= GAME_STATE_PLAYING)
переделать на обратное условие, что бы сразу и ретарнуть, а не вставлять потом else

2024-12-22 09:16 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +		txt += check_role_table_row_sec(M.current, show_objectives)
```suggestion
	for(var/datum/mind/mind in members)
		txt += check_role_table_row_sec(mind.current, show_objectives)
```
Использовать нормальные, полные названия для переменных

2024-12-22 09:16 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +	if(!istype(M))
зачем это тут, если и передаются сюда только мобы?

2024-12-22 09:16 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +/datum/admins/proc/check_role_table_row_sec(mob/M, show_objectives)
также использовать нормальные названия для переменных. Моба в параметре переименовать на mob/mob

2024-12-22 09:24 UTC, FlitchTime commented on code/modules/admin/player_panel.dm
> +		job = "Cyborg"
Оно тут для ертшных боргов. Не убрать

2024-12-22 09:31 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +		job = "Cyborg"
Вижу. Также переименуй моба в параметре на mob/living/living. И это все еще нужно убрать, ибо у борга и так будет выставлена джобка

2024-12-22 09:33 UTC, FlitchTime commented on code/modules/admin/player_panel.dm
> +	var/list/coords = ATOM_COORDS(GT)
job для силиконов нужен ертшных, а остальное сделаю

2024-12-22 09:35 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +	var/list/coords = ATOM_COORDS(GT)
Нет, не нужен. Если job неправильно у них выдается - значит у них и нужно чинить, а не костылить тут

2024-12-22 09:37 UTC, FlitchTime commented on code/modules/admin/player_panel.dm
> +/datum/admins/proc/check_role_table_row_sec(mob/M, show_objectives)
Чекай

2024-12-22 09:37 UTC, FlitchTime commented on code/modules/admin/player_panel.dm
> +	if(!istype(M))
Забыл, щас сделаю

2024-12-22 09:38 UTC, FlitchTime commented on code/modules/admin/player_panel.dm
> +	if(SSticker && SSticker.current_state >= GAME_STATE_PLAYING)
Тоже потерял, щас добавлю

2024-12-22 09:47 UTC, Antoonij commented on code/modules/admin/player_panel.dm
> +		return
```suggestion
	if(!check_rights(R_ADMIN))
		return
		
	if(!SSticker || SSticker.current_state < GAME_STATE_PLAYING)
		return
```
более правильная логика

2024-12-22 10:32 UTC, FlitchTime commented on code/modules/admin/player_panel.dm
> +		job = "Cyborg"
living'у не выдаётся job'ка. Если я уже не попутал, то выдаётся она где-то с карбона или хумана. 
А ещё сидеть и ради одного верба вычищать потом этих киборгов из миллиона мест бред ёбанный.
Хочешь заняться рефактором делай его, а не пытайся меня на него вывести. Я джун, блять!

2024-12-27 17:48 UTC, merged