bugfix: vampires and changelings now can't learn cqc by upgrade implant + translation
ss220-space/Paradise pull request #6268
Opened 2024-12-24 18:18 UTC by dageavtobusnick

## Описание
Накладывает на изучение сикуси с помощью поварского импланта из аплинка те же ограничения  на изучающего, что и мануал.
Так же перевел информацию в связанных оповещениях и описаниях

## Причина создания ПР / Почему это хорошо для игры
багфикс+перевод

## Тесты
На локалке попытался вколоть имплант во всех 4-х ситуациях. Вкололся  с выдачей БИ только без ролей генки и вампа, а так же пацифизма.

2024-12-27 18:32 UTC, LiquidPotroh commented on code/modules/martial_arts/martial.dm
>  		else if(HAS_TRAIT(user, TRAIT_PACIFISM))
Почему вообще проверка на пацифизм в изучении? Она должна быть только в применении. Пацифизм вообще то и не должен запрещать половину приемов сикуси, как не запрещает тазер с батоном в хелпе.

2024-12-27 18:32 UTC, LiquidPotroh commented on code/modules/martial_arts/martial.dm
> +			to_chat(user, span_warning("Мы имплантируем себя, но наноботы не успевают достичь своей и разрушаются."))
Своей цели*

2024-12-27 18:32 UTC, LiquidPotroh commented on code/modules/martial_arts/martial.dm
> +			to_chat(user, span_warning("Мы имплантируете себя, но ваша кровь разрушает их до того, как они достигнут цели"))
Вы имплантируете*. Кто такие "их" в текущем контексте непонятно. Напиши наноботы чтоли или кто там.

2024-12-27 18:32 UTC, LiquidPotroh commented on code/modules/martial_arts/martial.dm
> +		else if(HAS_TRAIT(user, TRAIT_PACIFISM))
Опять же. Ненужная проверка. Пацифизм не должен мешать изучать. Только применять.

2024-12-27 18:50 UTC, dageavtobusnick commented on code/modules/martial_arts/martial.dm
>  		else if(HAS_TRAIT(user, TRAIT_PACIFISM))
Я без понятия, но тк она была в проверках сикуси, я ее перенес и в проверку импланта

2024-12-28 14:22 UTC, dageavtobusnick commented on code/modules/martial_arts/martial.dm
> +		else if(HAS_TRAIT(user, TRAIT_PACIFISM))
Но он мешает и в обычном сикуси. Меня просили перенести все проверки-ограничения -- я перенес все.

2024-12-28 14:22 UTC, dageavtobusnick commented on code/modules/martial_arts/martial.dm
> +			to_chat(user, span_warning("Мы имплантируете себя, но ваша кровь разрушает их до того, как они достигнут цели"))
поправил

2024-12-28 14:22 UTC, dageavtobusnick commented on code/modules/martial_arts/martial.dm
> +			to_chat(user, span_warning("Мы имплантируем себя, но наноботы не успевают достичь своей и разрушаются."))
поправил

2024-12-28 14:22 UTC, dageavtobusnick commented on code/modules/martial_arts/martial.dm
>  		else if(HAS_TRAIT(user, TRAIT_PACIFISM))
Проверка была изначально, значит видимо так задумано

2024-12-30 08:54 UTC, BeebBeebBoob commented
Это багфикс или перевод?

2024-12-30 09:10 UTC, PlayerUnknown14 requested changes
Перевод нужно доработать.

2024-12-30 09:10 UTC, PlayerUnknown14 commented on code/modules/martial_arts/martial.dm
> +	desc = "Небольшое чёрное руководство. Нарисованы инструкции по тактическому рукопашному бою."
```suggestion
	desc = "Небольшая книжка чёрного цвета. Это подробное руководство по тактике рукопашного боя."
		ru_names = list(
		NOMINATIVE = "старое руководство",
		GENITIVE = "старого руководства",
		DATIVE = "старому руководству",
		ACCUSATIVE = "старое руководство",
		INSTRUMENTAL = "старым руководством",
		PREPOSITIONAL = "старом руководстве"
	)
```

2024-12-30 09:10 UTC, PlayerUnknown14 commented on code/modules/martial_arts/martial.dm
> +			to_chat(user, span_warning("Мы пытаемся несколько раз, но просто не можем понять основы CQC!"))
```suggestion
			to_chat(user, span_warning("Как бы мы не пытались, у нас не получается понять даже основы CQC!"))
```

2024-12-30 09:10 UTC, PlayerUnknown14 commented on code/modules/martial_arts/martial.dm
> +			to_chat(user, span_warning("Твоя жажда крови отвлекает тебя от основ CQC!"))
```suggestion
			to_chat(user, span_warning("Ваша жажда крови отвлекает вас от изучения CQC!"))
```

2024-12-30 09:10 UTC, PlayerUnknown14 commented on code/modules/martial_arts/martial.dm
> +			to_chat(user, span_warning("От одной мысли о драке, не говоря уже о CQC, голова идёт кругом!"))
```suggestion
			to_chat(user, span_warning("От одной мысли о драке, не говоря уже о CQC, ваша голова идёт кругом!"))
```

2024-12-30 09:10 UTC, PlayerUnknown14 commented on code/modules/martial_arts/martial.dm
> +	to_chat(user, span_boldannounceic("Вы запоминаете основы CQC."))
```suggestion
	to_chat(user, span_boldannounceic("Вы быстро пробегаетесь глазами по страницам книги, запоминая основы CQC."))
```

2024-12-30 09:10 UTC, PlayerUnknown14 commented on code/modules/martial_arts/martial.dm
> +	visible_message(span_warning("[src] зловеще пищит, а через мгновение вспыхивает пламенем."))
```suggestion
	visible_message(span_warning("[declent_ru(NOMINATIVE)] зловеще пищит, после чего вспыхивает ярким пламенем!"))
```

2024-12-30 09:10 UTC, PlayerUnknown14 commented on code/modules/martial_arts/martial.dm
> +	desc = "Даёт вам вспомнить то, что вы всегда забываете"
```suggestion
	desc = "Небольшой шприц, содержащий в себе имплант. Даёт вам запомнить то, что вы всегда забываете."
		ru_names = list(
		NOMINATIVE = "имплант улучшения CQC",
		GENITIVE = "импланта улучшения CQC",
		DATIVE = "импланту улучшения CQC",
		ACCUSATIVE = "имплант улучшения CQC",
		INSTRUMENTAL = "имплантом улучшения CQC",
		PREPOSITIONAL = "импланте улучшения CQC"
	)
```

2024-12-30 09:10 UTC, PlayerUnknown14 commented on code/modules/martial_arts/martial.dm
> +		to_chat(user, span_notice("Вы имплантируете себя, но наноботы не могут найти свою цель. Вы чувствуете острую боль в голове!"))
```suggestion
		to_chat(user, span_notice("Вы имплантируете себя, но наноботы не могут найти свою цель. Вы чувствуете острую головную боль!"))
```

2024-12-30 09:10 UTC, PlayerUnknown14 commented on code/modules/martial_arts/martial.dm
> +		to_chat(user, span_warning("Мы имплантируете себя, но ваша кровь разрушает наноботов до того, как они достигнут цели"))
```suggestion
		to_chat(user, span_warning("Вы имплантируете себя, но ваша кровь разрушает наноботов быстрее, чем они достигают своей цели."))
```

2024-12-30 09:10 UTC, PlayerUnknown14 commented on code/modules/martial_arts/martial.dm
> +	visible_message(span_warning("[src] зловеще пищит, и через мгновение взрывается!"))
```suggestion
	visible_message(span_warning("[declent_ru(NOMINATIVE)] зловеще пищит, после чего взрывается!"))
```

2024-12-30 09:12 UTC, PlayerUnknown14 commented
И вообще, если это не просто багфикс, а ещё и перевод, то об этом нужно как минимум написать в названии, как максимум - пингануть меня для ревью.

2024-12-30 09:36 UTC, dageavtobusnick commented
> И вообще, если это не просто багфикс, а ещё и перевод, то об этом нужно как минимум написать в названии, как максимум - пингануть меня для ревью.

Понял

2024-12-30 09:38 UTC, dageavtobusnick commented
> Это багфикс или перевод?

Изначально багфикс. Но так как полез в сикуси мануалы, решил заодно и перевести.

2024-12-30 09:39 UTC, PlayerUnknown14 approved these changes

2024-12-30 10:52 UTC, merged