add: laser minigun
ss220-space/Paradise pull request #6279
Opened 2024-12-27 18:52 UTC by FlitchTime

## Описание
Добавляем печать лазерного минигана в рнд и в вендор гаммы обр
[Автор не захотел фиксить конфликты, а в остальном всё было готово](https://github.com/ss220-space/Paradise/pull/5177)

## Причина создания ПР / Почему это хорошо для игры
https://discord.com/channels/617003227182792704/755125334097133628/122493714001454702 (кого-то волнует протухание предложки при 14 за на голосовании за неё?)

## Демонстрация изменений
![image](https://github.com/user-attachments/assets/be2bb0a4-1710-4b4d-9616-2bbadb3f265c)

## Тесты
На локалке всё работает

2024-12-28 17:43 UTC, pilygun commented
Ахуеть ты слоняра, я лени не мог год заставить доделать миниган. Единственное проверь не вешается ли пулемет на слот пояса, не пулится ли он, и добавь на тандердром

2024-12-29 15:52 UTC, Antoonij requested changes

2024-12-29 15:52 UTC, Antoonij commented on code/game/objects/structures/crates_lockers/closets.dm
> +	return ..()
Нет, это не должно менять код шкафа таким образом. 
Это нужно переписать вот так:
у объектов будет прок, к примеру handle_storage_pulling(), в его объявлении вернем TRUE, а у минигана оверрайдим и возвращаем FALSE
а в can_be_pulled клосета уже используем цикл for, проходимся по всем объектам в нем, вызываем и проверяем что вернул handle_storage_pulling у каждого объекта, если где то фолс - вернем фолс.

2024-12-30 08:08 UTC, PlayerUnknown14 requested changes
Русифицировать и нормас.

2024-12-30 08:08 UTC, PlayerUnknown14 commented on code/game/objects/structures/crates_lockers/closets.dm
> +			to_chat(user, span_warning("[src.name] слишком тяжелый!"))
```suggestion
			to_chat(user, span_warning("[capitalize(declent_ru(NOMINATIVE))] слишком тяжёлый!"))
```

2024-12-30 08:08 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Self-rechargable monster made of advanced techonology's and crazy machine thinking."
```suggestion
	desc = "Огромный само-заряжающийся лазерный ручной пулемёт. Выдающийся экземпляр оружейного искусства, созданный с помощью передовых технологий."
		ru_names = list(
		NOMINATIVE = "лазерный пулемёт Гатлинга",
		GENITIVE = "лазерного пулемёта Гатлинга",
		DATIVE = "лазерному пулемёту Гатлинга",
		ACCUSATIVE = "лазерный пулемёт Гатлинга",
		INSTRUMENTAL = "лазерным пулемётом Гатлинга",
		PREPOSITIONAL = "лазерном пулемёте Гатлинга"
	)
```

2024-12-30 08:08 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	to_chat(user, span_warning("[name] слишком тяжелый!"))
```suggestion
	balloon_alert(user, "слишком тяжело!")
```

2024-12-30 08:08 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	. += span_notice("Вы видите заряд батареи на [charge_amount] [declension_ru(charge_amount, "залп", "залпа", "залпов")]")
```suggestion
	. += span_notice("Индикатор батареи сообщает: заряда хватит на [charge_amount] [declension_ru(charge_amount, "выстрел", "выстрела", "выстрелов")].")
```

2024-12-30 08:08 UTC, PlayerUnknown14 commented on code/modules/research/designs/weapon_designs.dm
> +	desc = "Self-rechargable monster made of advanced techonology's and crazy machine thinking."
```suggestion
	desc = "Огромный само-заряжающийся лазерный ручной пулемёт. Выдающийся экземпляр оружейного искусства, созданный с помощью передовых технологий."
```

2024-12-30 08:10 UTC, FlitchTime commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Self-rechargable monster made of advanced techonology's and crazy machine thinking."
Какой пулемёт?

2024-12-30 08:30 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Self-rechargable monster made of advanced techonology's and crazy machine thinking."
> Какой пулемёт?

Гатлинга, стало быть.

2024-12-30 08:58 UTC, BeebBeebBoob commented
Решить комменты, после можно будет мержить

2024-12-30 09:03 UTC, Antoonij commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	charge = 9000
этому тут не место, переместить в code/modules/power/cell.dm

2024-12-30 10:11 UTC, Antoonij commented on code/modules/research/rdconsole.dm
> +					L.w_class = being_built.w_class
```suggestion
					L.w_class = new_item.w_class > L.w_class ? new_item.w_class : L.w_class
```
эта проблема может быть решена таким образом, без ввода доп. переменных в дизайны
Если вес объекта больше, чем вес локбокса - используем вес объекта
если нет - локбокса.
также для применения данного решения var/w_class с класса obj/item надо перенести в класс obj и убрать var/w_class в дизайнах

2024-12-30 11:06 UTC, FlitchTime commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Self-rechargable monster made of advanced techonology's and crazy machine thinking."
Придумай чёт другое. Лазеромёт или что-то такое. Пулимёт всё таки кидает пули, а не лазеры

2024-12-31 16:26 UTC, Antoonij commented on code/modules/research/rdconsole.dm
> +					lockbox.w_class = lockbox.w_class < being_built.w_class ? being_built.w_class : lockbox.w_class
для реализации прошлого комментария - var/w_class нужно переместить с класса obj/item на obj

2024-12-31 16:41 UTC, FlitchTime commented on code/modules/research/rdconsole.dm
> +					lockbox.w_class = lockbox.w_class < being_built.w_class ? being_built.w_class : lockbox.w_class
Если реализовывать, как ты написал, то да. Если, как я, то нормально всё скомпилится и выдаётся нужный вес
![image](https://github.com/user-attachments/assets/3203b9a4-42a6-46f6-90ea-0948cab9e5b2)

2024-12-31 17:10 UTC, Antoonij commented on code/modules/research/rdconsole.dm
> +					lockbox.w_class = lockbox.w_class < being_built.w_class ? being_built.w_class : lockbox.w_class
реализовано неправильно. Это все делается для избавления от вкласса в дизайне, используй new_item.w_class и переноси var/w_class в класс obj из айтемов.

2024-12-31 19:24 UTC, FlitchTime commented on code/modules/research/rdconsole.dm
> +					lockbox.w_class = lockbox.w_class < being_built.w_class ? being_built.w_class : lockbox.w_class
Ещё что-то?

2025-01-01 08:23 UTC, Antoonij commented on code/modules/projectiles/guns/energy.dm
> +	var/recharge_rate = 100 //recharge rate if self-charging
автодок находится над переменной и начинается с  3 слешей

2025-01-01 08:23 UTC, Antoonij commented on code/modules/projectiles/guns/energy.dm
> +		cell.give(recharge_rate) //... to recharge the shot
```suggestion
		cell.give(recharge_rate) // to recharge the shot
```

2025-01-01 08:50 UTC, BeebBeebBoob commented on .gitignore
> +/paradise.rsc
Эмм?

2025-01-01 09:00 UTC, PlayerUnknown14 requested changes
Переделывай.

2025-01-01 09:00 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Само-заряжающийся монстр созданный с помощью передовых технологий и любителей пушек побольше."
```suggestion
	desc = "Само-заряжающийся монстр созданный с помощью передовых технологий и любителей пушек побольше."
```
Описание не описывает предмет в общем (большой пулемёт и всё такое) + мне формулировка не нравится. Лучше возьми мой вариант.

2025-01-01 09:00 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +		PREPOSITIONAL = "Гатлинг-лазере"
```suggestion
		NOMINATIVE = "Гатлинг-лазер",
		GENITIVE = "Гатлинг-лазера",
		DATIVE = "Гатлинг-лазеру",
		ACCUSATIVE = "Гатлинг-лазер",
		INSTRUMENTAL = "Гатлинг-лазером",
		PREPOSITIONAL = "Гатлинг-лазере"
```
Вообще мимо, я тебе прописал нормальные неймы, бери их.

2025-01-01 09:00 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	. += span_notice("Индикатор батареи сообщает: заряда хватит на [charge_amount] [declension_ru(charge_amount, "выстрел", "выстрела", "выстрелов")].")
```suggestion
	. += span_notice("Индикатор батареи сообщает: заряда хватит на <b>[charge_amount]</b> [declension_ru(charge_amount, "выстрел", "выстрела", "выстрелов")].")
```

2025-01-01 09:00 UTC, PlayerUnknown14 commented on code/modules/research/designs/weapon_designs.dm
> +	desc = "Само-заряжающийся монстр созданный с помощью передовых технологий и любителей пушек побольше."
Аналогично.

2025-01-01 09:17 UTC, BeebBeebBoob requested changes

2025-01-01 09:17 UTC, BeebBeebBoob commented on code/game/objects/items.dm
> -	var/w_class = WEIGHT_CLASS_NORMAL
Нету больше надобноссти в этом.

2025-01-01 09:17 UTC, BeebBeebBoob commented on code/game/objects/objs.dm
> +	var/w_class = WEIGHT_CLASS_NORMAL
вернуть бы назад

2025-01-01 09:17 UTC, BeebBeebBoob commented on code/modules/power/cell.dm
> +	charge = 9000
халявный заряд? У `cell/laser` только `maxcharge` изменён и изначально `charge = 0`

2025-01-01 09:17 UTC, BeebBeebBoob commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	. += span_notice("Индикатор батареи сообщает: заряда хватит на [charge_amount] [declension_ru(charge_amount, "выстрел", "выстрела", "выстрелов")].")
Вы забыли `e_cost` для `/obj/item/ammo_casing/energy/laser/light`
У вас один выстрел стоит 100, не 600.

2025-01-01 09:24 UTC, Antoonij commented on code/game/objects/objs.dm
> +	var/w_class = WEIGHT_CLASS_NORMAL
эта переменная может использоваться как репрезентация веса обьекта вообщем, нам не нужна такая строгая иерархия классов

2025-01-01 09:38 UTC, FlitchTime commented on code/modules/power/cell.dm
> +	charge = 9000
Батарейки вроде всегда заряженные спавнятся, но автор зачем-то поставил и здесь заряд. Уберу

2025-01-01 09:39 UTC, FlitchTime commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Само-заряжающийся монстр созданный с помощью передовых технологий и любителей пушек побольше."
В моём варианте не описывает или в твоём? Как по мне это вопрос вкусовщины и мой вариант ничуть не хуже

2025-01-01 09:39 UTC, FlitchTime commented on code/modules/projectiles/guns/energy/nuclear.dm
> +		PREPOSITIONAL = "Гатлинг-лазере"
А я тебе сразу сказал, что называть лазер пулемётом это странно.

2025-01-01 09:41 UTC, FlitchTime commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	. += span_notice("Индикатор батареи сообщает: заряда хватит на [charge_amount] [declension_ru(charge_amount, "выстрел", "выстрела", "выстрелов")].")
Не в стиле парадиза. Я могу укоротить сообщение, но это плохо выглядит

2025-01-01 09:50 UTC, FlitchTime commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	. += span_notice("Индикатор батареи сообщает: заряда хватит на [charge_amount] [declension_ru(charge_amount, "выстрел", "выстрела", "выстрелов")].")
Стрельба идёт по 6 снарядов за одно нажатие

2025-01-01 09:50 UTC, FlitchTime commented on code/game/objects/items.dm
> -	var/w_class = WEIGHT_CLASS_NORMAL
Как скажите, босс

2025-01-01 10:22 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Само-заряжающийся монстр созданный с помощью передовых технологий и любителей пушек побольше."
> В моём варианте не описывает или в твоём? Как по мне это вопрос вкусовщины и мой вариант ничуть не хуже

В твоём варианте как раз и не описывается. Вкусовщина, да, но я как главный по буквам буду настаивать на своём варианте.

2025-01-01 10:40 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +		PREPOSITIONAL = "Гатлинг-лазере"
> А я тебе сразу сказал, что называть лазер пулемётом это странно.

Предмет попадает под определение пулемёта (кроме пуль в названии, само собой), да и выглядит именно как оный. Ещё более странно называть эту огромную махину просто лазером и на кой-то хрен дописывать сюда Гатлинга. Название на английском переводится как "Лазерный пулемёт Гатлинга", потому на русском оно будет так и точка.

2025-01-01 10:41 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	. += span_notice("Индикатор батареи сообщает: заряда хватит на [charge_amount] [declension_ru(charge_amount, "выстрел", "выстрела", "выстрелов")].")
> Не в стиле парадиза. Я могу укоротить сообщение, но это плохо выглядит

Чё? Выделить число в описании жирным шрифтом это не в стиле парадиза? Дружище, в коде есть куча сообщений, где числа выделяются на фоне остального текста аналогичным образом. Не пойму тебя.

2025-01-01 10:57 UTC, FlitchTime commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Само-заряжающийся монстр созданный с помощью передовых технологий и любителей пушек побольше."
Если смотреть без вкусовщины, то единственное я в описании убрал "огромный". Я тоже умею стоять на своём

2025-01-01 11:15 UTC, FlitchTime commented on code/modules/projectiles/guns/energy/nuclear.dm
> +		PREPOSITIONAL = "Гатлинг-лазере"
Определение существует в реально мире, где лазеры полноценным оружем-то не стали, не то, чтобы говорить про скорострельные группы. Называю я его **Гатлинг-лазером** показывая его родство с группой пулемётов, но не указывая на пули в названии. С каких пор Laser gatling gun это Лазерный пулемёт Гатлинга? Пулемёты не заканчиваются на minigun'ах. Это как бы только парочка представителей оных. И я тоже умею стоять на своём, как осёл
![image](https://github.com/user-attachments/assets/2ce5956e-3d09-4bb9-9379-20ce6c7244a3)

2025-01-01 11:16 UTC, FlitchTime commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	. += span_notice("Индикатор батареи сообщает: заряда хватит на [charge_amount] [declension_ru(charge_amount, "выстрел", "выстрела", "выстрелов")].")
Сори, я подумал это перенос строки. Сделаю

2025-01-01 18:09 UTC, BeebBeebBoob submitted a review, later dismissed

2025-01-01 18:11 UTC, Antoonij commented on code/modules/research/rdconsole.dm
> +					var/obj/item/real_item = new being_built.build_path(src)
```suggestion
					var/obj/item/real_item = new_item
```
предмет уже создан, зачем создавать опять

2025-01-02 11:36 UTC, PlayerUnknown14 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Само-заряжающийся монстр созданный с помощью передовых технологий и любителей пушек побольше."
```suggestion
	desc = "Огромное лазерное орудие, обладающее выдающейся скорострельностью и поражающей силой. Говорят, что 12 секунд стрельбы из этой малышки обойдутся вам в 400 тысяч кредитов."
```
Без пулемётов и прочей фигни, пусть будет так. На русском оставляем `"Гатлинг-лазер"`, меня устраивает.

2025-01-02 16:26 UTC, FlitchTime commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Само-заряжающийся монстр созданный с помощью передовых технологий и любителей пушек побольше."
Одобрямс

2025-01-02 17:21 UTC, Antoonij approved these changes
пойдет, также магических чисел более нет

2025-01-03 04:07 UTC, PlayerUnknown14 approved these changes
Буквы мои буквы

2025-01-03 04:13 UTC, merged