QoL: kinetic crusher translation
ss220-space/Paradise pull request #6283
Opened 2024-12-29 15:34 UTC by Explosi00N

## Описание

Перевод кинетического крашера, трофеев и их описаний.

## Причина создания ПР / Почему это хорошо для игры

перевод

## Тесты

На локалке все работает.

2024-12-30 07:37 UTC, PlayerUnknown14 requested changes
Доработать.

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	desc = "Ранний дизайн прото-кинетического акселератора, лишь немногим отличающийся от кучи различных шахтёрских иструментов прибитых друг к другу, формирующих высокотехнологичный топор. \ Хоть это и
```suggestion
	desc = "Ранний дизайн прото-кинетического акселератора, лишь немногим отличающийся от кучи различных шахтёрских инструментов, прибитых друг к другу, формирующих высокотехнологичный топор. \
	Хоть это и является эффективным шахтёрским инструментом, для борьбы с местной фауной его могут использовать либо самые опытные, либо самые сумасшедшие шахтёры."
```

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	. += span_notice("Наносит <b>[force + detonation_damage + backstab_bonus]</b> урона вместо <b>[force + detonation_damage]</b>, если удар был нанесен в спину.")
```suggestion
	. += span_notice("Отметьте существо дестабилизирующим полем, затем нанесите удар в ближнем бою, чтобы нанести <b>[force + detonation_damage]</b> единиц[declension_ru(force + detonation_damage, "у", "ы", "")] урона.")
	. += span_notice("Наносит <b>[force + detonation_damage + backstab_bonus]</b> единиц[declension_ru(force + detonation_damage, "у", "ы", "")] урона вместо <b>[force + detonation_damage]</b>, если удар был нанесён в спину.")
```
Дописать ко всем "здоровья", "урона" и прочим подобным `единиц[declension_ru()]` здесь и ниже.

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		. += span_notice("К нему прикреплен [T], вызывая следующий эффект: [T.effect_desc()].")
```suggestion
		. += span_notice("К нему прикреплён[genderize.ru(T.gender, "", "а", "о", "ы")] [T.declent_ru(NOMINATIVE)], что вызывает следующий эффект: [T.effect_desc()].")
```
"он прикреплён, вызывая" - использование деепричастия с неглагольным сказуемым, ошибка.

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		var/warn_message = "[name] слишком тяжел, чтобы использовать его одной рукой."
```suggestion
		var/warn_message = "[declent_ru(NOMINATIVE)] слишком тяжёл, чтобы использовать его одной рукой."
```

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +			warn_message += "Вы роняете [name] на землю.."
```suggestion
			warn_message += "Вы роняете [declent_ru(ACCUSATIVE)] на землю."
```
Зачем прописывать `ru_names`, если всё равно используем англоязычное `name`?

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +			user.visible_message(span_warning("[user] делает рывок!"))
Гендерайзы прописать глаголам здесь и ниже.

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +			to_chat(user, span_warning("Что-то не дает вам совершить рывок!"))
е -> ё здесь и ниже.

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +			visible_message(span_notice("Похоже, что эта порода устойчива ко всем методам копания кроме кирок!"))
```suggestion
			visible_message(span_notice("Похоже, что эту породу возьмёт только кирка!"))
```

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	. += span_notice("Вызывает следующий эффект, пока прикреплен к крушителю: [effect_desc()].")
```suggestion
	. += span_notice("Когда прикреплено к крушителю, вызывает следующий эффект: [effect_desc()].")
```

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "прото-кинетический крушитель",
            GENITIVE = "прото-кинетического крушителя",
            DATIVE = "прото-кинетическому крушителю",
            ACCUSATIVE = "прото-кинетический крушитель",
            INSTRUMENTAL = "прото-кинетическим крушителем",
            PREPOSITIONAL = "прото-кинетическом крушителе"
	)
```
Табуляцию у `ru_names` сделать здесь и ниже.

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +			balloon_alert("слишком много трофеев!")
```suggestion
			balloon_alert(user, "нет места!")
```

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	balloon_alert(user, "трофей прикреплен")
```suggestion
	balloon_alert(user, "прикреплено")
```

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	desc = "Отрубленное щупальце голиафа. Может быть установлено как трофей крушителя."
```suggestion
	desc = "Отрубленное щупальце голиафа. Может быть установлено на крушитель в качестве трофея."
```
Вторую часть описания прописать аналогично здесь и ниже.

2024-12-30 07:37 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "Детонация метки дестабилизатора наносит на <b>[bonus_value]</b> больше урона за каждые <b>[missing_health_desc]</b> недостающего у вас здоровья"
```suggestion
	return "детонация метки дестабилизатора наносит на <b>[bonus_value]</b> единиц урона больше за каждые <b>[missing_health_desc]</b> единиц недостающего у вас здоровья"
```
Первая буква - строчная здесь и ниже.

2024-12-30 08:12 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		. += span_notice("К нему прикреплён[genderize.ru(T.gender, "", "а", "о", "ы")] [T.declent_ru(NOMINATIVE)], что вызывает следующий эффект: [T.effect_desc()].")
```suggestion
		. += span_notice("К нему прикреплён[genderize_ru(T.gender, "", "а", "о", "ы")] [T.declent_ru(NOMINATIVE)], что вызывает следующий эффект: [T.effect_desc()].")
```

2024-12-30 10:58 UTC, Explosi00N commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "Детонация метки дестабилизатора наносит на <b>[bonus_value]</b> больше урона за каждые <b>[missing_health_desc]</b> недостающего у вас здоровья"
Сделано

2024-12-30 10:58 UTC, Explosi00N commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	desc = "Отрубленное щупальце голиафа. Может быть установлено как трофей крушителя."
Сделано

2024-12-30 10:59 UTC, Explosi00N commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		. += span_notice("К нему прикреплён[genderize.ru(T.gender, "", "а", "о", "ы")] [T.declent_ru(NOMINATIVE)], что вызывает следующий эффект: [T.effect_desc()].")
Сделано

2024-12-30 11:00 UTC, Explosi00N commented on code/modules/mining/equipment/kinetic_crusher.dm
> +			to_chat(user, span_warning("Что-то не дает вам совершить рывок!"))
Сделано

2024-12-30 11:00 UTC, Explosi00N commented on code/modules/mining/equipment/kinetic_crusher.dm
> +			user.visible_message(span_warning("[user] делает рывок!"))
Сделано

2024-12-30 11:23 UTC, PlayerUnknown14 requested changes
Ищо.

2024-12-30 11:23 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "детонация метки дестабилизатора наносит на <b>[bonus_value]</b> единиц урона больше за каждые <b>[missing_health_desc]</b> единиц недостающего у вас здоровья"
единиц - `единиц[declension_ru()]`. Соотвественно, прописать подобную конструкцию КО ВСЕМ числам здесь и ниже.

2024-12-30 11:23 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	desc = "Все еще пылающее крыло магмакрылого наблюдателя. Может быть установлено на крушитель в качестве трофея."
е -> ё здесь и ниже.

2024-12-30 12:33 UTC, Explosi00N commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "детонация метки дестабилизатора наносит на <b>[bonus_value]</b> единиц урона больше за каждые <b>[missing_health_desc]</b> единиц недостающего у вас здоровья"
Должно работать

2024-12-30 12:42 UTC, Explosi00N commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	desc = "Все еще пылающее крыло магмакрылого наблюдателя. Может быть установлено на крушитель в качестве трофея."
надеемся и плачем что нашел всех ё

2024-12-31 03:22 UTC, PlayerUnknown14 requested changes
Пум-пурум.

2024-12-31 03:22 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	. += span_notice("Отмтьте существо дестабилизирующим полем, затем нанесите удар в ближнем бою, чтобы нанести <b>[force + detonation_damage]</b> единиц[declension_ru(force + detonation_damage, "у", "
```suggestion
	. += span_notice("Отметьте существо дестабилизирующим полем, затем нанесите удар в ближнем бою, чтобы нанести <b>[force + detonation_damage]</b> единиц[declension_ru(force + detonation_damage, "у", "ы", "")] урона")
```

2024-12-31 03:22 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "детонация метки дестабилизатора наносит на <b>[bonus_value]</b> единиц[declension_ru(bonus_value, "у", "ы", "")] урона больше за каждые <b>[missing_health_desc]</b> единиц[declension_ru(bonu
```suggestion
	return "детонация метки дестабилизатора наносит на <b>[bonus_value]</b> единиц[declension_ru(bonus_value, "у", "ы", "")] урона больше за каждые <b>[missing_health_desc]</b> единиц[declension_ru(missing_health_desc, "у", "ы", "")] недостающего у вас здоровья"
```

2024-12-31 03:22 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "удары в ближнем бою наносят на <b>[bonus_value]</b> больше  урона после атаки по противнику, с пределом в <b>[bonus_value * 10]</b> урона"
```suggestion
	return "удары в ближнем бою наносят на <b>[bonus_value]</b> единиц[declension_ru(bonus_value, "у", "ы", "")] урона больше после атаки по противнику, с пределом в <b>[bonus_value * 10]</b> единиц[declension_ru(bonus_value, "у", "ы", "")] урона"
```

2024-12-31 03:44 UTC, PlayerUnknown14 reviewed
Тяжело.

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	. += span_notice("Наносит <b>[force + detonation_damage + backstab_bonus]</b> единиц[declension_ru(force + detonation_damage, "у", "ы", "")] урона вместо <b>[force + detonation_damage]</b>, если уда
```suggestion
	. += span_notice("Наносит <b>[force + detonation_damage + backstab_bonus]</b> единиц[declension_ru(force + detonation_damage + backstab_bonus, "у", "ы", "")] урона вместо <b>[force + detonation_damage]</b>, если удар был нанесён в спину.")
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		. += span_notice("К нему прикреплён[genderize_ru(T.gender, "", "а", "о", "ы")] [T.declent_ru(NOMINATIVE)], что вызывает следующий эффект: [T.effect_desc()].")
```suggestion
		. += span_notice("К нему прикреплён[genderize_ru(T.gender, "", "а", "о", "ы")] <b>[T.declent_ru(NOMINATIVE)]</b>, что вызывает следующий эффект: [T.effect_desc()].")
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		var/warn_message = "[declent_ru(NOMINATIVE)] слишком тяжёл, чтобы использовать его одной рукой."
```suggestion
		var/warn_message = "[capitalize(declent_ru(NOMINATIVE))] слишком тяжёл, чтобы использовать его одной рукой."
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "детонация метки дестабилизатора не позволяет некоторым существам использовать дальнобойные атаки в течении <b>[bonus_value*0.1]</b> секунд"
```suggestion
	return "детонация метки дестабилизатора не позволяет некоторым существам использовать дальнобойные атаки в течении <b>[bonus_value * 0.1]</b> секунд[declension_ru(bonus_value * 0.1, "ы", "", "")]"
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "выстрел дестабилизатора перезаряжается на <b>[bonus_value*0.1]</b> секунды быстрее"
```suggestion
	return "выстрел дестабилизатора перезаряжается на <b>[bonus_value * 0.1]</b> секунд[declension_ru(bonus_value * 0.1, "у", "ы", "")] быстрее"
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "крушитель наносит на 50% больше урона, если у цели больше 90% здоровья."
```suggestion
	return "крушитель наносит на 50% больше урона, если у цели больше 90% здоровья"
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "щупальце голиафа",
            GENITIVE = "щупальца голиафа",
            DATIVE = "щупальцу голиафа",
            ACCUSATIVE = "щупальце голиафа",
            INSTRUMENTAL = "щупальцем голиафа",
            PREPOSITIONAL = "щупальце голиафа"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "крыло наблюдателя",
            GENITIVE = "крыла наблюдателя",
            DATIVE = "крылу наблюдателя",
            ACCUSATIVE = "крыло наблюдателя",
            INSTRUMENTAL = "крылом наблюдателя",
            PREPOSITIONAL = "крыле наблюдателя"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "крыло магмакрылого наблюдателя",
            GENITIVE = "крыла магмакрылого наблюдателя",
            DATIVE = "крылу магмакрылого наблюдателя",
            ACCUSATIVE = "крыло магмакрылого наблюдателя",
            INSTRUMENTAL = "крылом магмакрылого наблюдателя",
            PREPOSITIONAL = "крыле магмакрылого наблюдателя"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "крыло ледокрылого наблюдателя",
            GENITIVE = "крыла ледокрылого наблюдателя",
            DATIVE = "крылу ледокрылого наблюдателя",
            ACCUSATIVE = "крыло ледокрылого наблюдателя",
            INSTRUMENTAL = "крылом ледокрылого наблюдателя",
            PREPOSITIONAL = "крыле ледокрылого наблюдателя"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "череп легиона",
            GENITIVE = "черепа легиона",
            DATIVE = "черепу легиона",
            ACCUSATIVE = "череп легиона",
            INSTRUMENTAL = "черепом легиона",
            PREPOSITIONAL = "черепе легиона"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "огромное щупальце голиафа",
            GENITIVE = "огромного щупальца голиафа",
            DATIVE = "огромному щупальцу голиафа",
            ACCUSATIVE = "огромное щупальце голиафа",
            INSTRUMENTAL = "огромным щупальцем голиафа",
            PREPOSITIONAL = "огромном щупальце голиафа"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "отравленный клык",
            GENITIVE = "отравленного клыка",
            DATIVE = "отравленному клыку",
            ACCUSATIVE = "отравленный клык",
            INSTRUMENTAL = "отравленным клыком",
            PREPOSITIONAL = "отравленном клыке"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "фауна получает на 10% больше урона в течении 2 секунд после детонации"
```suggestion
	return "фауна получает на 10% больше урона в течении 2 секунд после детонации метки дестабилизатора"
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "морозная железа",
            GENITIVE = "морозной железы",
            DATIVE = "морозной железе",
            ACCUSATIVE = "морозную железу",
            INSTRUMENTAL = "морозной железой",
            PREPOSITIONAL = "морозной железе"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "глаз кровожадного шахтёра",
            GENITIVE = "глаза кровожадного шахтёра",
            DATIVE = "глазу кровожадного шахтёра",
            ACCUSATIVE = "глаз кровожадного шахтёра",
            INSTRUMENTAL = "глазом кровожадного шахтёра",
            PREPOSITIONAL = "глазе кровожадного шахтёра"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	desc = "Его зрачок раздроблен в кашу. Может быть установлено на крушитель в качестве трофея."
```suggestion
	desc = "Человеческий глаз с раздробленным в кашу зрачком. Может быть установлено на крушитель в качестве трофея."
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "детонация метки дестабилизатора дает вам иммунитет к оглушению и уменьшение получаемого урона на <b>90%</b>, на <b>1</b> секунду"
```suggestion
	return "детонация метки дестабилизатора даёт вам иммунитет к оглушению и уменьшение получаемого урона на <b>90%</b>, на <b>1</b> секунду"
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "детонация метки дестабилизатора взрывает врага, нанося <b>[bonus_value]</b> урона близлежащим врагам и отталкивая их"
```suggestion
	return "детонация метки дестабилизатора взрывает врага, нанося <b>[bonus_value]</b> 
единиц[declension_ru(bonus_value, "у", "ы", "")] урона близлежащим врагам и отталкивая их"
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	desc = "Набор окровавленных когтей, вырванных с руки огромного демона. Может быть установлено на крушитель в качестве трофея."
	ru_names = list(
            NOMINATIVE = "демонические когти",
            GENITIVE = "демонических когтей",
            DATIVE = "демоническим когтям",
            ACCUSATIVE = "демонические когти",
            INSTRUMENTAL = "демоническими когтями",
            PREPOSITIONAL = "демонических когтях"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	desc = "Бластерные трубки, взятые с руки колосса. Может быть установлено на крушитель в качестве трофея."
	ru_names = list(
            NOMINATIVE = "бластерные трубки",
            GENITIVE = "бластерных трубок",
            DATIVE = "бластерным трубкам",
            ACCUSATIVE = "бластерные трубки",
            INSTRUMENTAL = "бластерными трубками",
            PREPOSITIONAL = "бластерных трубках"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "выстрел дестабилизатора после детонации метки дестабилизатора наносит <b>[bonus_value]</b> единиц[declension_ru(bonus_value, "у", "ы", "")] урона, но двигается медленнее"
```suggestion
	return "следующий выстрел дестабилизатора после детонации метки дестабилизатора будет лететь медленнее, но нанесёт <b>[bonus_value]</b> единиц[declension_ru(bonus_value, "у", "ы", "")] урона"
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "талисман вихря",
            GENITIVE = "талисмана вихря",
            DATIVE = "талисману вихря",
            ACCUSATIVE = "талисман вихря",
            INSTRUMENTAL = "талисманом вихря",
            PREPOSITIONAL = "талисмане вихря"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "адаптивное ядро ИИ",
            GENITIVE = "адаптивного ядра ИИ",
            DATIVE = "адаптивному ядру ИИ",
            ACCUSATIVE = "адаптивное ядро ИИ",
            INSTRUMENTAL = "адаптивным ядром ИИ",
            PREPOSITIONAL = "адаптивном ядре ИИ"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	desc = "Устрашающий череп с горящими красными глазами. Может быть установлено на крушитель в качестве трофея."
	ru_names = list(
            NOMINATIVE = "усиленный череп легиона",
            GENITIVE = "усиленного черепа легиона",
            DATIVE = "усиленному черепу легиона",
            ACCUSATIVE = "усиленный череп легиона",
            INSTRUMENTAL = "усиленным черепом легиона",
            PREPOSITIONAL = "усиленном черепе легиона"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	return "детонация метки дестабилизатора позволяет вам сделать рывок на небольшую дистанцию в намерении помощи"
```suggestion
	return "детонация метки дестабилизатора позволяет вам сделать рывок на небольшую дистанцию, если выбрано намерение помощи"
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	ru_names = list(
            NOMINATIVE = "магмитовый прото-кинетический крушитель",
            GENITIVE = "магмитового прото-кинетического крушителя",
            DATIVE = "магмитовому прото-кинетическому крушителю",
            ACCUSATIVE = "магмитовый прото-кинетический крушитель",
            INSTRUMENTAL = "магмитовым прото-кинетическим крушителем",
            PREPOSITIONAL = "магмитовом прото-кинетическом крушителе"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	)
```suggestion
	desc = "Ранний дизайн прото-кинетического акселератора, теперь являющийся кучей различных шахтёрских иструментов приваренных друг к другу плазменным магмитом. Судя по всему, магмитовых деталей на улучшение его дестабилизатора было недостаточно."
	ru_names = list(
            NOMINATIVE = "незавершенный прото-кинетический крушитель",
            GENITIVE = "незавершенного прото-кинетического крушителя",
            DATIVE = "незавершенному прото-кинетическому крушителю",
            ACCUSATIVE = "незавершенный прото-кинетический крушитель",
            INSTRUMENTAL = "незавершенным прото-кинетическим крушителем",
            PREPOSITIONAL = "незавершенном прото-кинетическом крушителе"
	)
```

2024-12-31 03:44 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	. += span_notice("Возможно, вы можете применить еще немного магмитовых деталей чтобы полностью улучшить ваш крушитель.")
```suggestion
	. += span_notice("Возможно, вы можете применить еще немного магмитовых деталей, чтобы полностью улучшить ваш крушитель.")
```

2024-12-31 03:48 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +единиц[declension_ru(bonus_value, "у", "ы", "")] урона близлежащим врагам и отталкивая их"
```suggestion
	return "детонация метки дестабилизатора взрывает врага, нанося <b>[bonus_value]</b> единиц[declension_ru(bonus_value, "у", "ы", "")] урона близлежащим врагам и отталкивая их"
```

2024-12-31 03:54 UTC, PlayerUnknown14 submitted a review, later dismissed
Добро.

2024-12-31 03:55 UTC, PlayerUnknown14 submitted a review, later dismissed

2024-12-31 04:14 UTC, PlayerUnknown14 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +        PREPOSITIONAL = "хвостовом шипе"
```suggestion
            NOMINATIVE = "хвостновой шип",
            GENITIVE = "хвостового шипа",
            DATIVE = "хвостовому шипу",
            ACCUSATIVE = "хвостовой шип",
            INSTRUMENTAL = "хвостовым шипом",
            PREPOSITIONAL = "хвостовом шипе"
```

2024-12-31 04:15 UTC, PlayerUnknown14 approved these changes

2025-01-04 23:32 UTC, merged