add: Detective zippo
ss220-space/Paradise pull request #6284
Opened 2024-12-29 16:05 UTC by FlitchTime

## Описание
Создаём новую Зипку для детектива и суём её на основные карты в его кабинет

## Причина создания ПР / Почему это хорошо для игры
[Прикол](https://discord.com/channels/617003227182792704/1303777723663257630/1322753574685511684)

## Демонстрация изменений
![image](https://github.com/user-attachments/assets/be1f578f-51c3-4764-8575-3a57d2817f68)

## Тесты
Локалка

2024-12-29 16:24 UTC, Antoonij commented on code/game/objects/items/weapons/lighters.dm
> +	desc = "Лимитированная версия Зиппо для детектива. Кажется её доставили прямиком из нуарных фильмов"
```suggestion
	desc = "Лимитированная версия Зиппо для детектива. Кажется её доставили прямиком из нуарных фильмов."
```
Точка в конце деска, да. Без нее, что либо дополняющее деск будет выглядеть неправильно

2024-12-29 16:44 UTC, FlitchTime commented on code/game/objects/items/weapons/lighters.dm
> +	desc = "Лимитированная версия Зиппо для детектива. Кажется её доставили прямиком из нуарных фильмов"
.

2024-12-30 07:45 UTC, PlayerUnknown14 requested changes
Вето на ведро от главлока. Слегка поправить надобно.

2024-12-30 07:45 UTC, PlayerUnknown14 commented on code/game/objects/items/weapons/lighters.dm
> +	desc = "Лимитированная версия Зиппо для детектива. Кажется её доставили прямиком из нуарных фильмов."
```suggestion
	desc = "Лимитированная версия зажигалки Зиппо для детектива. Кажется, что её доставили прямиком из нуарных фильмов."
		ru_names = list(
		NOMINATIVE = "зажигалка Зиппо детектива",
		GENITIVE = "зажигалки Зиппо детектива",
		DATIVE = "зажигалке Зиппо детектива",
		ACCUSATIVE = "зажигалку Зиппо детектива",
		INSTRUMENTAL = "зажигалкой Зиппо детектива",
		PREPOSITIONAL = "зажигалке Зиппо детектива"
	)
```

2024-12-30 08:09 UTC, FlitchTime commented
Собираю апрувы, любой ценой, но бесплатно

2024-12-30 08:10 UTC, PlayerUnknown14 submitted a review, later dismissed
Апрув на ведро от главлока.

2024-12-30 11:02 UTC, BeebBeebBoob commented
Надо предложку делать

2024-12-30 20:55 UTC, pilygun commented
> Надо предложку делать

Дядя с головой все в порядке? Во первых на три из 6 ПРов на которые ты значок "[требует голосовалку" НА НИХ СУКА БЫЛА ПРЕДЛОЖКА, я помню за каждую голосовал блять. А даже если бы и не было, это настолько минорное изменение. Это действительно требует предложки? Это спрайт от ведущего спрайтера блять, они априори должны без предложек мержится, ибо это стандарт качества спрайтов. Ебана рот столько с цифровой бюрократией боролись, пытались отказаться от системы воутов, а бипу похуй. 
Чесно я немного хуею, я думал если в дискорде пиздец, то хотя бы на гитхабе все ок будет.

2024-12-30 20:55 UTC, pilygun approved these changes
предложка была

2024-12-30 21:13 UTC, BeebBeebBoob commented
Я когда проверял ПР, тут не было ссылки на предложку. Отсюда очевидный вывод: не было предложки.
Это не в моих интересах идти и искать на этот ПР предложку. Если вы не можете скопировать и вставить одну ссылку в описание, то вам стоит пересмотреть своё желание делать ПРы.

Даже столь мелкое и минорное добавление требует предложку. Да, люди настолько чувствительные что могут отказать тебе в добавлении какой либо косметики в игру. 

Напоследок, следи за порывами своих эмоции. Не нравиться - не ешь.

2024-12-30 21:15 UTC, merged

2024-12-31 07:41 UTC, pilygun commented
![8](https://github.com/user-attachments/assets/16a93f25-28b9-4076-802e-5d7a1dc2c16b)

2024-12-31 08:11 UTC, PiotrTheTchaikowsky commented
![image](https://github.com/user-attachments/assets/5b7bc30b-d1fb-4920-a5ae-629f8e43d5cd)