Minor Fixes
ss220-space/Paradise pull request #645
Opened 2022-02-09 20:46 UTC by TrashDoxx

## Почему это должно быть в игре
Ошибки это плохо. Не допускайте ошибок.

## Список изменений
* Маскировка под невидимые объекты и отсутствующие спрайты более недоступна.
* Кроме того, теперь невозможно вылезти из трубы, используя проектор.

2022-02-09 20:54 UTC, Vallat requested changes

2022-02-09 20:54 UTC, Vallat commented on code/game/objects/items/devices/chameleonproj.dm
> +		return
```suggestion
	if(target.alpha < 255)
		return
	if(!target.invisibility)
		return
```

2022-02-09 20:56 UTC, Vallat approved these changes

2022-02-09 21:10 UTC, merged

2022-04-12 05:06 UTC, dj-34 commented
https://github.com/ss220-space/Paradise/issues/679 , может кто-то подтвердить? Возможно проблема в этом коммите.