Локализация шведского акцента
ss220-space/Paradise pull request #647
Opened 2022-02-10 00:51 UTC by Ohar

## What Does This PR Do

## Why It's Good For The Game
Теперь шведский акцент работает с кириллицей, а не только добавляет борк-борк-борканье.

## Changelog
:cl:
tweak: Теперь шведский акцент работает с кириллицей, а не только добавляет борк-борк-борканье.
/:cl:

2022-02-10 07:52 UTC, Vallat requested changes
Все `replacetextEx()` заменить на `replacetextEx_char()` так как мы работаем с кириллицей

2022-02-11 05:25 UTC, Vallat approved these changes

2022-03-10 14:02 UTC, TrashDoxx approved these changes

2022-03-12 05:57 UTC, botPurple approved these changes
Требует обновления википедии в руководстве по генетике. А также, я бы рекомендовал перевести все сообщения при активации генов, чтобы не было такого, когда что-то переведено, а что-то нет.

2022-03-12 16:57 UTC, merged