Перевод окна статистики раунда
ss220-space/Paradise pull request #650
Opened 2022-02-11 15:41 UTC by Ohar

## Changelog
:cl:
tweak: Перевод окна статистики раунда
/:cl:

2022-02-20 15:22 UTC, Vallat approved these changes

2022-03-10 14:02 UTC, TrashDoxx approved these changes

2022-03-12 05:51 UTC, botPurple approved these changes
Проблемы со склонениями при подсчете очков. Но мне обещали, что их исправят когда-то в конце перевода всего парадайза 🤔

2022-03-15 17:06 UTC, Ohar commented
Склонения при подсчёте очков исправлены

2022-03-16 06:04 UTC, Vallat requested changes

2022-03-16 06:04 UTC, Vallat commented on code/__HELPERS/pronouns.dm
> +/datum/proc/declension_ru(num, single_name, double_name, multiple_name)
Очко очка, а функция не датумная
```suggestion
/proc/declension_ru(num, single_name, double_name, multiple_name)
```

2022-03-16 06:04 UTC, Vallat commented on code/__HELPERS/pronouns.dm
> +				return multiple_name
Чуть поменял саму функцию, так должно быть более читаемо
```suggestion
	if((num in 11 to 20) || (num > 9 && (num % 100) < 20))
		return multiple_name
	switch(num % 10)
		if(1)
			return single_name
		if(2,3,4)
			return double_name
	return multiple_name
```

2022-03-18 18:51 UTC, Ohar commented on code/__HELPERS/pronouns.dm
> +				return multiple_name
@Vallat [Поправил](https://github.com/ss220-space/Paradise/pull/650/commits/93d5d960d53fdb6741b569274d49963b67d56aa4)

2022-03-18 21:41 UTC, Vallat commented on code/__HELPERS/pronouns.dm
> +				return multiple_name
Плохо поправил, не сильно вникая я уже вижу что код нормально не покрывает интервал (4, 5). Если будет число 4,5 то функция вернёт множественное значение, а должна двойное

2022-03-19 00:56 UTC, Ohar commented on code/__HELPERS/pronouns.dm
> +				return multiple_name
@Vallat [Исправил обработку четвёрки](https://github.com/ss220-space/Paradise/pull/650/commits/4f2e3e94f9bb56c893fa7d3028b59afa68fb4db6)

2022-03-19 06:38 UTC, Vallat commented on code/__HELPERS/pronouns.dm
> +				return multiple_name
Не исправил, посмотри на мой код. У тебя отрезок от 2 до 5, а должно быть два интервала: от 0 до 1 и от 1 до 5. Т.е. фактически ты не покрываешь большую долю случаев. Рекомендую просто предложенный код использовать, в котором изначальная логика уже переписан и доработана.

2022-03-19 10:30 UTC, Ohar commented on code/__HELPERS/pronouns.dm
> +				return multiple_name
Эм, я проверил, [правка](https://github.com/ss220-space/Paradise/pull/650/commits/4f2e3e94f9bb56c893fa7d3028b59afa68fb4db6) была не нужна, код был правильный  😃 
![изображение](https://user-images.githubusercontent.com/3854741/159117453-2b677ecc-9b28-4768-b077-52486d03e04f.png)

2022-03-19 15:39 UTC, Ohar commented on code/__HELPERS/pronouns.dm
> +				return multiple_name
@Vallat 
Я думаю что склонять надо так, как если бы оно писалось прописью, иначе можно умереть нахуй.

- 0,1 — ноль целых, одна десятая окнА
- 2,2 — две целых, две десятых окнА
- 5,9 — пять целых, девять десятых окнА
- 11,4 — одиннадцать целых, четыре десятых окнА

То есть дробные всегда во множественном числе

[Добавил обработку исключений и проверку целочисленности](https://github.com/ss220-space/Paradise/pull/650/commits/eca4589ab414d0394bf2caf80f7cc7bb19fa9b6e). Дробные числа теперь всегда даю.т множественное число.

2022-03-19 15:45 UTC, Ohar commented
@Vallat 
Я думаю что склонять надо так, как если бы оно писалось прописью, иначе можно умереть нахуй.

- 0,1 — ноль целых, одна десятая окнА
- 2,2 — две целых, две десятых окнА
- 5,9 — пять целых, девять десятых окнА
- 11,4 — одиннадцать целых, четыре десятых окнА

То есть дробные **всегда в двойственном числе**

Добавил обработку исключений и проверку целочисленности.
Дробные числа теперь всегда дают двойственное число.

2022-03-19 16:00 UTC, Vallat requested changes

2022-03-19 16:00 UTC, Vallat commented on code/__HELPERS/pronouns.dm
> +		return ""
```suggestion
/proc/declension_ru(num, single_name, double_name, multiple_name)
	if(isnum(num) || round(num) != num)
		return double_name // fractional numbers
	if(((num % 10) == 1) && ((num % 100) != 11)) // 1, not 11
		return single_name
	if(((num % 10) in 2 to 4) && !((num % 100) in 12 to 14)) // 2, 3, 4, not 12, 13, 14
		return double_name
	return multiple_name // 5, 6, 7, 8, 9, 0
```

2022-03-19 16:03 UTC, Vallat approved these changes

2022-03-19 18:53 UTC, Bizzonium commented on code/game/gamemodes/scoreboard.dm
> +	<b>Добыто руды:</b> [GLOB.score_oremined] ([GLOB.score_oremined * 2] очк[declension_ru(GLOB.score_oremined * 2, "о", "а", "ов")])<br>"}
Не лучше ли полностью слова использовать? Легче читать и искать
```suggestion
	<b>Добыто руды:</b> [GLOB.score_oremined] ([GLOB.score_oremined * 2] [declension_ru(GLOB.score_oremined * 2, "очко", "очка", "очков")])<br>"}
```

2022-03-22 17:22 UTC, merged