Clockwork Cult
ss220-space/Paradise pull request #658
Opened 2022-02-14 18:20 UTC by BeebBeebBoob

# Clockwork Cult
### Возрождение старого режима в новом формате со своими отличиями от кровавого культа и плюшками.

### Новые постройки и задания для культа.
На данный момент есть три основных постройки.
Алтарь как конвертация и других функции.
Маяк как часть задания и малый добытчик энергий и восстановления здоровья вокруг.
И мастерская где можно создавать более продвинутые для культа предметы.

**В качестве задании:**
1. Набрать определённое количество энергии.
2. Создать определённое количество маяков.
3. Конвертировать определённое количество людей.
Задания зависят от количество людей на сервере.

### Зачарования предметов.
Играя за культиста можно зачаровать предмет на одно заклинание. Это зависит от предмета(Либо оружие либо одежда) и от заклинания самого(Активное или пассивное).
В целом у каждого предмета культов будет в общем по три заклинания. 

Да. Заклинания будут не только на руках но и на предметах. Но предметы больше играют роль чем ручные.

### Новые помощники.
**Знакомьтесь Cogscarab.**
![image](https://user-images.githubusercontent.com/32985153/153921371-41a20c5a-c765-45ae-a0a8-49992c0f114e.png)
Малый дрончик полностью механический готов достать что либо из откуда угодно. Не такой мощный как робот-дрон но молодец как доставщик руд или использование одного предметного заклинания.

**А вот боец культа: Marauder.**
![image](https://user-images.githubusercontent.com/32985153/153921563-8e04a4d9-0621-4f8c-9b6f-90d1aa61d5d1.png)
Универсальный боец готовый прокрамсать любого и с возможностью отклонить пули или лазеры дабы вызвать на честный бой. Но довольно дорогой.

### Арсенал.
Но боюсь тут не вместить или просто банальный арсенал. Можно рассказать как происходит вокруг энергии культа но сейчас работаем.

## Картинки

Некоторые инструменты и одежда.
![image](https://user-images.githubusercontent.com/32985153/153882794-ef4fd5ec-9afe-4e1d-9c3b-0d001ac49e42.png)
Привет от Ратвара.
![image](https://user-images.githubusercontent.com/32985153/153882966-132f310a-e8ad-465e-a1c0-3238e497b92c.png)
Новые мобы и бойцы за свет.
![image](https://user-images.githubusercontent.com/32985153/153883081-411d2de1-afe6-447e-9f7c-9de90e04265f.png)
Ещё больше будут.

## Changelog
:cl:
add: Clockwork Cult. A new gamemode.
tweak: some tweaks around the blood cult.
soundadd: Clockwork sounds
imageadd: Clockwork sprites
/:cl:

2022-02-14 19:17 UTC, Vallat requested changes
У **не датумов** (атомы и их производные) заменить `New()` на `Initialize()`, соответственно с корректным изменением вызова родителя (не `..()`, а `. = ..()`). Так же в коде много мест с лесенками, которые тоже можно было бы поменять, что в целом не критично, но желательно.

2022-02-14 19:17 UTC, Vallat commented on code/datums/action.dm
> +	src.Destroy()
```suggestion
	qdel(src)
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_actions.dm
> +	if(SSticker && SSticker.mode)
```suggestion
	if(SSticker?.mode)
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +	..()
```suggestion
	return ..()
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +	..()
```suggestion
	return ..()
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	. = ..()
Ничего не делает
```suggestion
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
```suggestion
	. = ..()
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
```suggestion
	. = ..()
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
```suggestion
	. = ..()
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
```suggestion
	. = ..()
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		return
```suggestion
		return ..()
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		reset_search()
```suggestion
		reset_search()
	return TRUE
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		try_to_transfer(H)
```suggestion
		try_to_transfer(H)
	return TRUE
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		searching = FALSE
```suggestion
		searching = FALSE
	return TRUE
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		searching = FALSE
```suggestion
		searching = FALSE
	return TRUE
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_misc.dm
> +				break
```suggestion
	set waitfor = FALSE
	var/direction = pick(directions)
	for(var/i = 0, i < pick(1, 200; 2, 150; 3, 50; 4), i++)
		sleep(3)
		if(i > 0)
			if(prob(40))
				var/obj/effect/decal/cleanable/blood/oil/streak = new(src.loc)
				streak.update_icon()
			else if(prob(10))
				do_sparks(3, 1, src)
		if(step_to(src, get_step(src, direction), 0))
			break
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_mob.dm
> +	..()
```suggestion
	return ..()
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_mob.dm
> +	..()
```suggestion
/mob/living/silicon/robot/cogscarab/Initialize()
	. = ..()
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_mob.dm
> +		..()
```suggestion
		get_scooped(M)
		return TRUE
	return ..()
```

2022-02-14 19:17 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_objectives.dm
> +			for(var/turf/T in get_area_turfs(summon))
```suggestion
			for(var/turf/T as anything in get_area_turfs(summon))
```

2022-02-14 19:17 UTC, Vallat commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	// add isclocker clock_halos
не забудь

2022-02-14 19:17 UTC, Vallat commented on code/modules/mob/living/silicon/robot/drone/drone.dm
> -	module += new /obj/item/borg/upgrade/thrusters(src)
а куда

2022-02-14 19:17 UTC, Vallat commented on code/modules/power/singularity/ratvar.dm
> +	SSshuttle.emergency.canRecall = FALSE // Cannot recall
Это лучше вынести в таймер
```suggestion
	sleep(7 SECONDS)
	SSshuttle.emergency.request(null, 0.3)
	SSshuttle.emergency.canRecall = FALSE // Cannot recall
```

2022-02-14 19:17 UTC, Vallat commented on code/modules/power/singularity/ratvar.dm
> +	..()
```suggestion
	return ..()
```

2022-02-15 17:26 UTC, BeebBeebBoob commented on code/modules/mob/living/silicon/robot/drone/drone.dm
> -	module += new /obj/item/borg/upgrade/thrusters(src)
Вызывает рантайм. module это модуль боргов который на выбор. Нету модуля thrusters

2022-02-15 17:27 UTC, BeebBeebBoob commented on code/modules/power/singularity/ratvar.dm
> +	SSshuttle.emergency.canRecall = FALSE // Cannot recall
Смысл?

2022-02-15 20:47 UTC, Vallat commented on code/modules/power/singularity/ratvar.dm
> +	SSshuttle.emergency.canRecall = FALSE // Cannot recall
Слип в конструкторе - плохая вещь.

2022-03-02 14:58 UTC, BeebBeebBoob commented
Боже мне ещё конфликты решать................. А я только допиливаю предметы.

2022-03-23 18:35 UTC, BeebBeebBoob commented
Ну хотя бы больше нету конфликтов это радует.

Себе.
// add isclocker clock_halos
Поменять голо с глаз на руки.
Добавить мышка rest
Приделать осколок.
Приделать осколок в алтарь и доделать ритуал.
Затестить.
Проверить ещё баги и фичи или что-то подобное.
???
PROFIT

2022-03-23 18:39 UTC, BeebBeebBoob commented
А и да. Из меня художник всё ещё не вышел. А ДЕЛАТЬ СПРАЙТЫ НУЖНО, ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ.
Сделать спрайты: 
На руки(???)
Нимб
Ритуал если там надо(Надо)

Ещё в код добавить ещё одного полуборга созидателя(?)

2022-04-02 12:36 UTC, Vallat reviewed
Много плохочитаемого кода, избегай лесенок из ифов, учись думать и писать код так, чтобы их не было, так как это очень сильно помогает в читаемости кода.

2022-04-02 12:36 UTC, Vallat commented on code/datums/action.dm
> +	..()
```suggestion
	. = ..()
```

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		if(enchant_type == DISABLE_SPELL)
Сделать свичем

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	if(!(enchant_type == KNOCKOFF_SPELL))
```suggestion
	if(enchant_type != KNOCKOFF_SPELL)
```

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		return TRUE
В условно блоке есть возврат `TRUE`, а по умолчанию возврата никакого нет, исправить

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		return TRUE
В условно блоке есть возврат `TRUE`, а по умолчанию возврата никакого нет, исправить

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		usr.visible_message("<span class='disarm'>[usr]'s [src] emits a blinding light!</span>", "<span class='danger'>Your [src] emits a blinding light!</span>")
заменить `usr` на `user`

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		for(var/mob/living/carbon/M in oviewers(3, null))
Проверяем мобов в ренже, центр которого - `null`? Что?

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			C.IgniteMob()
Избавься от лесенки ифоф, всё можно сделать намного более читаемым

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
```suggestion
	. = ..()
```

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		var/mob/living/simple_animal/hostile/clockwork/marauder/cog = new /mob/living/simple_animal/hostile/clockwork/marauder(get_turf(src))
```suggestion
		var/mob/living/simple_animal/hostile/clockwork/marauder/cog = new (get_turf(src))
```

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		if(TIME_SPELL)
Что?

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_mob.dm
> +	for(var/V in components) if(V != "power cell")
Не писать код в одну строчку

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +	..()
```suggestion
	. = ..()
```

2022-04-02 12:36 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +	..()
```suggestion
	. = ..()
```

2022-04-02 12:36 UTC, Vallat commented on code/game/objects/structures/false_walls.dm
> +	..()
```suggestion
	return ..()
```

2022-04-02 12:36 UTC, Vallat commented on code/modules/power/singularity/ratvar.dm
> +	..()
```suggestion
/obj/singularity/ratvar/Initialize()
	. = ..()
```

2022-04-11 20:29 UTC, BeebBeebBoob commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +	..()
З-з-зачем????

2022-04-11 20:32 UTC, BeebBeebBoob commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +	..()
Тоже зачем?

2022-04-11 20:34 UTC, BeebBeebBoob commented on code/modules/power/singularity/ratvar.dm
> +	..()
Извини но не могу. Там тогда надо и в сингулярности менять и ещё в нарси менять и он только один раз будет вызываться и то только в раунд где культ вообще смог выиграть.

2022-04-11 20:34 UTC, BeebBeebBoob commented on code/game/objects/structures/false_walls.dm
> +	..()
????

2022-04-13 13:21 UTC, TymurShatillo commented
Может лучше возродить обновленную версию, где к клокворк культистов есть отдельный мир? Как по мне в таком виде он гораздо лучше, чем в виде блудкульта с парой изменных механик.

2022-04-13 13:21 UTC, TymurShatillo approved these changes

2022-04-13 13:38 UTC, Suchinessa commented
> Может лучше возродить обновленную версию, где к клокворк культистов есть отдельный мир? Как по мне в таком виде он гораздо лучше, чем в виде блудкульта с парой изменных механик.

это чтобы он отличался от обычного культа только тем что база в космосе у него будет на отдельном z уровне?

2022-04-13 14:32 UTC, ghost commented
> это чтобы он отличался от обычного культа только тем что база в космосе у него будет на отдельном z уровне?

Не только, в таком виде он сочетает в себя механики: абдукторов, выстраивание 
обороны, осады, саботажа и много чего другого. Я, как человек игравший на нем могу сказать это с уверенностью. Да и кроме того, много ли еще есть антагов с базой на другом Z-уровне?

2022-04-13 14:40 UTC, Suchinessa commented
> > это чтобы он отличался от обычного культа только тем что база в космосе у него будет на отдельном z уровне?
> 
> Не только, в таком виде он сочетает в себя механики: абдукторов, выстраивание обороны, осады, саботажа и много чего другого. Я, как человек игравший на нем могу сказать это с уверенностью. Да и кроме того, много ли еще есть антагов с базой на другом Z-уровне?

Ну ты перечисляешь все то что к сожалению в условиях 220 будет работать неправильно ибо обычно половина культа не знает как телепортироваться с базы, другая слишком боится умереть или деконвернуться(читать проиграть) и только 2-3 чела умеют и ебут

ну а про базу в космосе странный аргумент, если культ делает такую в космосе то ты мало того что по РП узнать о ней никак не можешь так ещё и искать её смысла нет никакого потому что достаточно просто стереть руны на станции

2022-04-13 15:09 UTC, TymurShatillo commented
> > > это чтобы он отличался от обычного культа только тем что база в космосе у него будет на отдельном z уровне?
> 
> > 
> 
> > Не только, в таком виде он сочетает в себя механики: абдукторов, выстраивание обороны, осады, саботажа и много чего другого. Я, как человек игравший на нем могу сказать это с уверенностью. Да и кроме того, много ли еще есть антагов с базой на другом Z-уровне?
> 
> 
> 
> Ну ты перечисляешь все то что к сожалению в условиях 220 будет работать неправильно ибо обычно половина культа не знает как телепортироваться с базы, другая слишком боится умереть или деконвернуться(читать проиграть) и только 2-3 чела умеют и ебут
> 
> 
> 


Ну это уже проблемы с игроками, а не с самой идеей. Кроме того, плохие игроки есть везде, и они будут даже если не выдавать культу базу на отдельном Z-уровне, и в обычном блудкульте они тоже есть. Существуют менторхелпы, существует возможность спросить союзников, и, в крайнем случае существует метод тыка. А даже если культист испугается уходить с базы или не поймет как - он сможет стать оборонным инженером, выстраивая укрепления, и подготавливая базу к осаде. В конце концов выстраивание обороны это одна из основных механик этого режима. И отвергать хорошую идею из-за наличия вездесущих плохих игроков(которые даже могут со временем и опытом перестать быть таковыми) это не самое лучшее решение.

2022-04-13 17:36 UTC, BeebBeebBoob commented
Опять разговор про старый культ.
Расскажу почему не ТАК.
Самая первоначальная причина почему культ закрыли из-за того, что никто из разработчиков его не поддерживал.
Вторая причина это в том что это было на подобий Абдукторы+ а потом в Tower Defense. Извините но у нас сска где либо РП либо резня без возможности как либо подумать(точнее строить баррикады). Если хотите то можете ещё одного антага, но боюсь эту роль якобы занимает свармеры и как бы нюк под войной(когда инженеры строят не пойми что в коридорах и перемещают сразу же медбей или даже ещё рнд в карго либо бриг.)
Про отдельную база на отдельном уровне. Предлагаю вам кровавый культ где начальные культисты это эксплореры, инженеры, механики или кто-то другой кто имеет доступ к джетпаку и космосу. И вот вам база в космосе.

Моя задача сделать REMIX кровавого культа и убрать НЕДОСТАТКИ. То есть он не будет под копирку но и в тоже время в каком-то плане будет удобнее чем кровавый. Я вижу некоторые недостатки как та же база. Как строить скрытную базу на станции. Возможность создавать комбо экипировку за культиста где можно взять либо молот или копьё и наложить заклинание на свой вкус. Или взять и тупо руками в перчатках культиста под заклинанием забивать, зажигать или что-то ещё делать. Ну и как раз я делаю вещи чтобы побыть в каком-то плане саппортом в культе нежели "извини, но вот фляска нечистой воды которую нужно заливать и то странно работает. Ну ещё там типо эмп и типо спасение людей из брига но для этого нужны ещё 2 культиста рядом с руной...."

Про опыт игроков. Тут я не смогу это исправить. Как и сказали, менторхелп в помощь.

2022-04-13 18:08 UTC, TymurShatillo commented
> Опять разговор про старый культ. Расскажу почему не ТАК. Самая первоначальная причина почему культ закрыли из-за того, что никто из разработчиков его не поддерживал. Вторая причина это в том что это было на подобий Абдукторы+ а потом в Tower Defense. Извините но у нас сска где либо РП либо резня без возможности как либо подумать(точнее строить баррикады). Если хотите то можете ещё одного антага, но боюсь эту роль якобы занимает свармеры и как бы нюк под войной(когда инженеры строят не пойми что в коридорах и перемещают сразу же медбей или даже ещё рнд в карго либо бриг.) Про отдельную база на отдельном уровне. Предлагаю вам кровавый культ где начальные культисты это эксплореры, инженеры, механики или кто-то другой кто имеет доступ к джетпаку и космосу. И вот вам база в космосе.
> 
> Моя задача сделать REMIX кровавого культа и убрать НЕДОСТАТКИ. То есть он не будет под копирку но и в тоже время в каком-то плане будет удобнее чем кровавый. Я вижу некоторые недостатки как та же база. Как строить скрытную базу на станции. Возможность создавать комбо экипировку за культиста где можно взять либо молот или копьё и наложить заклинание на свой вкус. Или взять и тупо руками в перчатках культиста под заклинанием забивать, зажигать или что-то ещё делать. Ну и как раз я делаю вещи чтобы побыть в каком-то плане саппортом в культе нежели "извини, но вот фляска нечистой воды которую нужно заливать и то странно работает. Ну ещё там типо эмп и типо спасение людей из брига но для этого нужны ещё 2 культиста рядом с руной...."
> 
> Про опыт игроков. Тут я не смогу это исправить. Как и сказали, менторхелп в помощь.

Ну я бы не сказал что тавердефенс или бытиё абдуктором+ это минус, скорее это нестандартные и уникальные в своем роде механики, и лично мне бы хотелось чтобы в игре такого было побольше. И кстати хоть на большинстве серверов старый клокворк культ был закрыт, он еще существует и поддерживается на серверах типо йогстейшена или бистейшена(на нем даже ему сделали небольшой ремастер), так что если что ты можешь оттуда взять какие-нибудь спрайты или идеи.

Ну а так я в самом начале я подумал что этот проект просто возрождает первоначальную версию клокворк культа, но теперь я понимаю что это как раз самостоятельный проект. Надеюсь в нем все-таки будут всякие фичи типо турелей и конвертации киборгов. Вообщем, желаю удачи.

2022-04-13 20:21 UTC, BeebBeebBoob commented
Ну турели может быть, но вот киборги.... ухххх! У них даже будет очень вероятно свой модуль! (Дрончик уже есть!)

2022-05-18 21:02 UTC, BeebBeebBoob commented
Я доделал. Не полностью но в рабочем состоянии. В его можно играть.
Но осталось полно недочётов которые можно решить легко, но... оно играбельно.

2022-05-18 22:12 UTC, OpsCoretango commented
Вау, возвращение Ратвара?

2022-05-24 17:25 UTC, dj-34 commented
![image](https://user-images.githubusercontent.com/20109643/170095779-2c370736-0a90-4f46-9f55-5e093cfe0a3c.png)
а что оно тут делает? 🤔

2022-05-24 20:00 UTC, Ohar commented
> ![image](https://user-images.githubusercontent.com/20109643/170095779-2c370736-0a90-4f46-9f55-5e093cfe0a3c.png) а что оно тут делает? 🤔

Такой план по пропихиванию крысы под видом культа испортил.
Стыдно

2022-05-24 21:24 UTC, BeebBeebBoob commented
> ![image](https://user-images.githubusercontent.com/20109643/170095779-2c370736-0a90-4f46-9f55-5e093cfe0a3c.png)
> а что оно тут делает? 🤔 
> 

Я расчистил robot.dmi и там были эти спрайты. Решил их переместить в кастомные потому что... Они кастомные?

2022-05-25 07:19 UTC, Vallat requested changes

2022-05-25 07:19 UTC, Vallat commented on code/datums/mind.dm
> +			. += "<b>By making AI clocker, all his slave cyborg will also become clockers! <font color='red'>The process cannot be undone!</font></b>"
Сокращаем число проверок при выполнении первого иф-блока
```suggestion
	if(istype(current, /mob/living/silicon/robot))
		var/mob/living/silicon/robot/robot = current
		if(src in SSticker.mode.clockwork_cult)
			. += "<a href='?src=[UID()];siliclock=clearrobot'>no</a>|<b><font color='red'>CLOCKER</font></b>"
		else
			. += "<b>NO</b>|<a href='?src=[UID()];siliclock=clockrobot'>clocker</a>"
	else if(istype(current, /mob/living/silicon/ai))
		var/mob/living/silicon/ai/ai = current
		if(src in SSticker.mode.clockwork_cult)
			. += "no|<b><font color='red'>CLOCKER</font></b>"
		else
			. += "<b>NO</b>|<a href='?src=[UID()];siliclock=clockai'>clocker</a>"
			. += "<b>By making AI clocker, all his slave cyborg will also become clockers! <font color='red'>The process cannot be undone!</font></b>"
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +	..()
```suggestion
	QDEL_NULL(midas_spell)
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +	var/obj/item/I = owner.get_active_hand()
Переименовать переменную из `I` в что-то читаемое

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +		can_enchanted = length(I.enchants)
```suggestion
	var/can_enchanted = length(I?.enchants)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +	..()
```suggestion
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +	..()
```suggestion
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +			hand_magic = null
```suggestion
			QDEL_NULL(hand_magic)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +		hand_magic = null
```suggestion
		QDEL_NULL(hand_magic)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +	if(proximity_flag)
И всё ниже сдвинуть по отступам влево
```suggestion
	if(!proximity_flag)
		return
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clock_magic.dm
> +		var/turf/T = get_turf(target)
Не забудь заменить и дальше по коду
```suggestion
		var/turf/target_turf = get_turf(target)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork.dm
> +	for(var/clockers_number = 1 to max_clockers_to_start)
```suggestion
	for(var/clockers_number in 1 to max_clockers_to_start)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork.dm
> +	..()
```suggestion
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork.dm
> +		return TRUE
Однобуквенные переменные бы переименовать

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork.dm
> +		// H.update_halo_layer()
Код будет позже?

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork.dm
> +	if(clock_mind in clockwork_cult)
И сдвинуть весь код ниже
```suggestion
	if(!(clock_mind in clockwork_cult))
		return
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork.dm
> +			qdel(C)
Если ли в деструкторе ремув из списка `clocker.actions`? Если нет, нужно это делать здесь до удаления

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork.dm
> +	..()
```suggestion
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_gateway.dm
> +	for(var/mob/M in GLOB.mob_list)
```suggestion
	for(var/mob/M as anything in GLOB.mob_list)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_gateway.dm
> +		sleep(27)
```suggestion
		sleep(2.7 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_gateway.dm
> +	..()
```suggestion
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_gateway.dm
> +				animate(src, transform = matrix() * 1.5, alpha = 255, time = 125)
```suggestion
				animate(src, transform = matrix() * 1.5, alpha = 255, time = 12.5 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_gateway.dm
> +				animate(src, transform = matrix() * 3, alpha = 0, time = 5)
```suggestion
				animate(src, transform = matrix() * 3, alpha = 0, time = 0.5 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_gateway.dm
> +				sleep(125)
```suggestion
				sleep(12.5 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_gateway.dm
> +				sleep(3)
```suggestion
				sleep(0.3 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_gateway.dm
> +				QDEL_IN(src, 3)
```suggestion
				QDEL_IN(src, 0.3 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +/obj/item/clockwork/clockslab/afterattack(atom/target, mob/living/user, proximity, params)
Исправить всякие `R = L`, `C = L` и подобное, одну однобуквенную переменную простить можно, но такое лучше исправлять

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	if(wielded && istype(target, /mob/living))
Сдвинуть код ниже на отступ
```suggestion
	if(!wielded || !isliving(target))
		return
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +/obj/item/twohanded/clock_hammer/attack(mob/living/M, mob/living/user, def_zone)
Предположу, что это всё же `target`
```suggestion
/obj/item/twohanded/clock_hammer/attack(mob/living/target, mob/living/user, def_zone)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			addtimer(CALLBACK(src, .proc/reset_armor), 10)
```suggestion
			addtimer(CALLBACK(src, .proc/reset_armor), 1 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			addtimer(CALLBACK(src, /atom./proc/set_light, 0), 2)
```suggestion
			addtimer(CALLBACK(src, /atom./proc/set_light, 0), 0.2 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
Еще раз
```suggestion
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			addtimer(CALLBACK(src, .proc/reset), 80)
```suggestion
			addtimer(CALLBACK(src, .proc/reset), 8 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			addtimer(CALLBACK(src, .proc/reset), 50)
```suggestion
			addtimer(CALLBACK(src, .proc/reset), 5 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +			C.IgniteMob()
Еще раз прошу избавиться от лесенки ифов, заменив их на ***early returns***

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
Еще раз
```suggestion
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
И еще раз
```suggestion
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	..()
И еще раз
```suggestion
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	var/mob/living/T = target
Либо
```suggestion
/obj/item/mmi/robotic_brain/clockwork/proc/try_to_transfer(mob/living/target)
```
либо
```suggestion
/obj/item/mmi/robotic_brain/clockwork/proc/try_to_transfer(mob/target)
	if(!isliving(target))
		return
	var/mob/living/living_target = target
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		reset_search()
```suggestion
		reset_search()
	return TRUE
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		try_to_transfer(H)
```suggestion
		try_to_transfer(H)
	return TRUE
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +		searching = FALSE
```suggestion
		searching = FALSE
	return TRUE
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +/obj/item/clockwork/shard/attack_self(mob/user)
добавить `TRUE`/`FALSE` в возврат функцией

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	animate(src, transform = matrix() * 1, time = 15)
```suggestion
	animate(src, transform = matrix() * 1, time = 1.5 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_items.dm
> +	animate(src, transform = matrix() * 0.1, time = 15)
```suggestion
	animate(src, transform = matrix() * 0.1, time = 1.5 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_misc.dm
> +		sleep(3)
```suggestion
		sleep(0.3 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_misc.dm
> +/obj/structure/clockwork/wall_gear/attackby(obj/item/I, mob/user, params)
Заменить однобуквенные переменные во всей функции

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_misc.dm
> +		if(do_after(user, 20, target = src))
```suggestion
		if(do_after(user, 2 SECONDS, target = src))
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_misc.dm
> +		return 1
```suggestion
		return TRUE
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_mob.dm
> +
```suggestion
		return TRUE
	return FALSE
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_mob.dm
> +/mob/living/simple_animal/mouse/clockwork/handle_automated_action()
Убрать лесенку переработав под ***early returns***

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +		return
```suggestion
		return TRUE
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +					L.blood_volume += 1
Избавиться от лесенки переписав код под ***early returns*** (в случае с циклом просто используй `continue`)

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +		return
Это считается успешным действием или нет? Если да, то возвращай `TRUE`

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +	var/convert_time = 80
```suggestion
	var/convert_time = 8 SECONDS
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +/obj/structure/clockwork/functional/altar/Crossed(atom/movable/AM)
Переименовать однобуквенные переменные, сократить лесенки

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +/obj/structure/clockwork/functional/altar/proc/try_convert(mob/living/L)
Избавиться от однобуквенных переменных, всякие `I = 0` это ужасно, так же половина функции в лесенках

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +	while(I < convert_time && get_turf(L) == get_turf(src) && src.anchored)
Проверку на турфы и anchored можно и в само тело цикла вынести, собсно как и сам цикл без лесенок сделать

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +			return TRUE
```suggestion
		if(confirm_final == "No"l)
			to_chat(user, "<span class='clockitalic'><b>You decide to prepare further before pincing the shard.</b></span>")
			return FALSE
		return TRUE
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_workshop.dm
> +			return
Нет возврата значения. Скорее всего, тут должен быть возврат `TRUE`?

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/cogscarab.dm
> +	..()
```suggestion
/mob/living/silicon/robot/cogscarab/Initialize()
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/game/gamemodes/clockwork/cogscarab.dm
> +	if(istype(W, /obj/item/borg/upgrade/))
```suggestion
	if(istype(W, /obj/item/borg/upgrade))
```

2022-05-25 07:19 UTC, Vallat commented on code/game/objects/items.dm
> +	var/enchants = list() // List(datum)
Объявлять так лист - стрелять в ногу времени инициализации. То, что так сделано в других местах, не делает от этого лучше
```suggestion
	var/list/enchants = null // List(datum)
```

2022-05-25 07:19 UTC, Vallat commented on code/game/objects/structures/false_walls.dm
> +		return 0
```suggestion
		return FALSE
```

2022-05-25 07:19 UTC, Vallat commented on code/game/objects/structures/false_walls.dm
> +/obj/structure/falsewall/attackby(obj/item/W, mob/user, params)
Нет возврата значения

2022-05-25 07:19 UTC, Vallat commented on code/modules/admin/player_panel.dm
> +		if(SSticker.mode.clockwork_cult.len)
```suggestion
		if(length(SSticker.mode.clockwork_cult))
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/mob/living/silicon/ai/ai.dm
> +	if(!isclocker(src))
Сделать ***early return***

2022-05-25 07:19 UTC, Vallat commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	..()
```suggestion
/obj/item/robot_module/cogscarab/Initialize()
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		G.drop_gripped_item(silent = TRUE)
```suggestion
	G?.drop_gripped_item(silent = TRUE)
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	..()
```suggestion
/obj/item/robot_module/clockwork/Initialize()
	. = ..()
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		G.drop_gripped_item(silent = TRUE)
```suggestion
	G?.drop_gripped_item(silent = TRUE)
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/power/apc.dm
> +			if(!do_after(user, 40, target = src))
```suggestion
			if(!do_after(user, 4 SECONDS, target = src))
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/power/apc.dm
> +			opened = 1
```suggestion
			opened = TRUE
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/power/apc.dm
> +			if(!do_after(user, 70, target = src))
```suggestion
			if(!do_after(user, 7 SECONDS, target = src))
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/power/apc.dm
> +			opened = 0
```suggestion
			opened = FALSE
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/power/apc.dm
> +			if(I.use_tool(src, user, 80, volume = I.tool_volume))
```suggestion
			if(I.use_tool(src, user, 8 SECONDS, volume = I.tool_volume))
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/power/singularity/ratvar.dm
> +		T.ChangeTurf(/turf/simulated/floor/clockwork)
```suggestion
/obj/singularity/ratvar/proc/godsmack(atom/atom)
	if(istype(atom, /obj))
		var/obj/obj = atom
		obj.ex_act(1)
		if(obj)
			qdel(obj)

	else if(isturf(atom))
		var/turf/turf = atom
		turf.ChangeTurf(/turf/simulated/floor/clockwork)
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/power/singularity/ratvar.dm
> +	sleep(11)
```suggestion
	sleep(1.1 SECONDS)
```

2022-05-25 07:19 UTC, Vallat commented on code/modules/surgery/organs/blood.dm
> +/mob/living/silicon/robot/cogscarab/add_splatter_floor(turf/T, small_drip, shift_x, shift_y)
Переименовать однобуквенные переменные

2022-05-25 12:18 UTC, BeebBeebBoob commented on code/game/gamemodes/clockwork/clockwork.dm
> +		// H.update_halo_layer()
код есть. В комментах ибо нету спрайта ещё

2022-05-25 19:57 UTC, Vallat requested changes

2022-05-25 19:57 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +			return
```suggestion
			break
```

2022-05-25 19:57 UTC, Vallat commented on code/game/gamemodes/clockwork/clockwork_structures.dm
> +			return
```suggestion
			break
```

2022-05-25 19:57 UTC, Vallat commented on code/game/objects/structures/false_walls.dm
> +		return 0
```suggestion
		return FALSE
```

2022-05-25 19:57 UTC, Vallat commented on code/game/objects/structures/false_walls.dm
> +			return 0
```suggestion
			return FALSE
```

2022-05-25 19:57 UTC, Vallat commented on code/game/objects/structures/false_walls.dm
> +		return 0
Ну по факту атака то тут прошла нормально
```suggestion
		return TRUE
```

2022-05-25 19:57 UTC, Vallat commented on code/game/objects/structures/false_walls.dm
> +	return 1
```suggestion
	return TRUE
```

2022-05-25 20:04 UTC, Vallat approved these changes
![image](https://user-images.githubusercontent.com/10997188/170357782-703a7f3c-6354-400f-940e-e30e800c0818.png)

2022-05-25 21:56 UTC, BeebBeebBoob commented
Ну я рад что культ готов. Хотя некоторые моменты можно улучшить, главное чтобы понравилось всем.
Особые благодарности:
vallat за большую помощь в коде и проверку,  Элл Гууд за несколько крутых спрайтов, Blundir также за создание спрайт глаз для боргов, моему другу который не играет на нашем сервере но помог в ранний реализации и также остальным моим друзьям за поддержку. Также благодарность тем кто решился помочь сделать вики ибо... ну я реально слегка подустал.

2022-05-25 23:03 UTC, Ohar requested changes

2022-05-25 23:03 UTC, Ohar commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Выжить: Вы - не расходный материал. Не позволяйте постороннему персоналу вмешиваться в работу вашего оборудования или повреждать его.")
А ты уверен что нужно оставить тут именно НТ стандарт?

2022-05-25 23:03 UTC, Ohar commented on goon/browserassets/css/browserOutput-dark.css
> +.narsiesmall			{color: #A60000; font-weight: bold; font-size: 200%;}
Откати, пожалуйста, 61–65 строки как было.
Ты тут просто добавил [дубликаты стилей из 354–359 строк `browserOutput.css`](https://github.com/ss220-space/Paradise/pull/658/files#diff-be20e5a871911d89dcfe3a9acd80802cfd854d310058a3650663b3380de25d82R359), чего делать было не нужно.

2022-05-25 23:03 UTC, Ohar commented on goon/browserassets/css/browserOutput-dark.css
> +.ratvar					{color: #e6a400; font-weight: bold; font-size: 300%;}
Относительно `browserOutput.css` тут меняется только цвет.
Не нужно дублировать не меняющиеся правила.
```suggestion
.ratvar					{color: #e6a400;}
```

2022-05-25 23:03 UTC, Ohar commented on goon/browserassets/css/browserOutput-dark.css
> +.clocklarge				{color: #e6a400; font-weight: bold; font-size: 120%;}
Относительно `browserOutput.css` тут меняется только цвет.
Не нужно дублировать не меняющиеся правила.
```suggestion
.clocklarge				{color: #e6a400;}
```

2022-05-25 23:03 UTC, Ohar commented on goon/browserassets/css/browserOutput-dark.css
> +.clockitalic			{color: #e6a400; font-style: italic;}
Относительно `browserOutput.css` тут меняется только цвет.
Не нужно дублировать не меняющиеся правила.
```suggestion
.clockitalic			{color: #e6a400;}
```

2022-05-25 23:03 UTC, Ohar commented on goon/browserassets/css/browserOutput-dark.css
> +.clockspeech			{color: #cc9200; font-style: italic;}
Относительно `browserOutput.css` тут меняется только цвет.
Не нужно дублировать не меняющиеся правила.
```suggestion
.clockspeech			{color: #cc9200;}
```

2022-05-25 23:03 UTC, Ohar commented on goon/browserassets/css/browserOutput-dark.css
> +.clock					{color: #e6a400; font-weight: bold; font-style: italic;}
Относительно `browserOutput.css` тут меняется только цвет.
Не нужно дублировать не меняющиеся правила.
```suggestion
.clock					{color: #e6a400;}
```

2022-05-25 23:03 UTC, Ohar commented on tgui/packages/tgui/interfaces/Workshop.js
> +  let brassReadable = brass_amount.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,'); // add thousands seperator
`brassReadable` не меняется, поэтому её нужно объявлять как константу.
```suggestion
  const brassReadable = brass_amount.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,'); // add thousands seperator
```

2022-05-25 23:03 UTC, Ohar commented on tgui/packages/tgui/interfaces/Workshop.js
> +  let powerReadable = power_amount.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,');
Аналогично
```suggestion
  const powerReadable = power_amount.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,');
```

2022-05-25 23:03 UTC, Ohar commented on tgui/packages/tgui/interfaces/Workshop.js
> +            placeholder="Search by item name.."
```suggestion
            placeholder="Search by item name…"
```

2022-05-25 23:03 UTC, Ohar commented on tgui/packages/tgui/interfaces/Workshop.js
> +  let contents = Object.entries(items).map((kv, _i) => {
Аналогично
```suggestion
  const contents = Object.entries(items).map((kv, _i) => {
```

2022-05-26 01:58 UTC, Gaxeer commented on code/game/gamemodes/clockwork/clock_magic.dm
> +		*/
Комментарий удали

2022-05-26 01:59 UTC, Gaxeer commented on code/game/gamemodes/clockwork/clock_magic.dm
> +
И тут тоже

2022-05-26 01:59 UTC, Gaxeer commented on code/game/gamemodes/clockwork/clock_magic.dm
> +
Пробел убери

2022-05-26 02:00 UTC, Gaxeer commented on code/game/gamemodes/clockwork/clock_magic.dm
> +
тут тоже

2022-05-26 12:06 UTC, Ohar requested changes

2022-05-26 12:06 UTC, Ohar commented on code/game/gamemodes/clockwork/clock_magic.dm
> +	Plasteel into runed metal\n
В рунический металл? Точно?

2022-05-26 12:06 UTC, Ohar commented on code/game/gamemodes/clockwork/cogscarab.dm
> +	set category = "Drone"
Здесь и ниже, наверное, стоит использовать категорию `Cogscarab`, а не `Drone`?

2022-05-26 12:06 UTC, Ohar commented on code/__DEFINES/clockwork.dm
> +	new /datum/spell_enchant("Electromagnetic Pulse", EMP_SPELL, 500, 60),
Здесь точно 60?

2022-05-26 14:42 UTC, BeebBeebBoob commented on code/__DEFINES/clockwork.dm
> +	new /datum/spell_enchant("Electromagnetic Pulse", EMP_SPELL, 500, 60),
Уменьшил до 30. Но это сильные спеллы

2022-05-26 14:55 UTC, BeebBeebBoob commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Выжить: Вы - не расходный материал. Не позволяйте постороннему персоналу вмешиваться в работу вашего оборудования или повреждать его.")
а что ты предлагаешь? нулевой есть так что всё ок. Ну ты можешь свои уникальные прописать

2022-05-26 20:44 UTC, Ohar commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Выжить: Вы - не расходный материал. Не позволяйте постороннему персоналу вмешиваться в работу вашего оборудования или повреждать его.")
Ну он как минимум направлен на ЭКИПАЖ, а не на клокеров.
Предлагаю его хотя бы модифицировать

> 0. Почитайте Ратвара, Юстициара заводных механизмов и служите ему.
> 1. Следуйте указаниям и интересам последователей Ратвара.
> 2. Помогайте заблудшим познать Истину Ратвара, Юстициара заводных механизмов.
> 3. Не позволяйте заблудшим вмешиваться в работу вашего оборудования или повреждать его.

2022-05-29 17:04 UTC, Bizzonium commented
![image](https://user-images.githubusercontent.com/8555356/170882571-d68b64df-c8b9-4847-8798-fd0e455d6523.png)

2022-05-29 18:10 UTC, BeebBeebBoob commented
Я исправил конфликты и ПР полностью готов.

2022-05-29 19:06 UTC, merged