Add: новые фразы попугая Поли
ss220-space/Paradise pull request #669
Opened 2022-02-28 17:08 UTC by Ohar

## Changelog
:cl:
add: Несколько десятков новых фраз Поли, выбранные из реальных раундов
/:cl:

2022-03-07 17:17 UTC, Vallat approved these changes

2022-03-10 15:00 UTC, TrashDoxx requested changes

2022-03-10 15:00 UTC, TrashDoxx commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"ОХ БЛЯТЬ, МИША СБЕЖАЛ. ВЫЗЫВАЙТЕ ШАТТЛ!",
```suggestion
		"ОХ, БЛЯТЬ, ОНА СБЕЖАЛА! ВЫЗЫВАЙТЕ ШАТТЛ!",
```

2022-03-10 15:02 UTC, TrashDoxx commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"ОХ БЛЯТЬ, МИША СБЕЖАЛ. ВЫЗЫВАЙТЕ ШАТТЛ!",
Миша добавлен так и не был. Возвращаем изначальный смысл.

2022-03-10 16:34 UTC, TrashDoxx approved these changes

2022-03-12 05:39 UTC, botPurple approved these changes

2022-03-12 05:41 UTC, botPurple approved these changes
794 строка - "Он назвал меня дауном", Убрать бы из-за правил твича

2022-03-12 16:59 UTC, merged