TTS и Blindfold
ss220-space/Paradise pull request #676
Opened 2022-03-06 17:36 UTC by BeebBeebBoob

## What Does This PR Do

Добавляет возможность взять в лодаут новые вещи: повязка на глаза и TTS девайс.
Добавляет новый предмет TTS девайс

## Changelog
:cl:
add: TTS device and blindfold to loadout options. Also can be made in autolathe.
/:cl:

2022-03-07 17:15 UTC, Vallat requested changes

2022-03-07 17:15 UTC, Vallat commented on code/game/objects/items/devices/tts.dm
> +	desc = "A small device with a keyboard attached. Anything entered on the keyboard is played out the speaker. \n<span class='notice'>Alt-click the device to make it beep.</span> \n<span class='notice
Это можно было и не выносить в `Initialize()`, а просто оставить в `desc`

2022-03-07 17:15 UTC, Vallat commented on code/game/objects/items/devices/tts.dm
> +	atom_say("[input]")
```suggestion
	atom_say(input)
```

2022-03-07 17:15 UTC, Vallat commented on code/game/objects/items/devices/tts.dm
> +	input = null
Лишнее
```suggestion
```

2022-03-07 17:15 UTC, Vallat commented on code/game/objects/items/devices/tts.dm
> +		playsound(user, 'sound/machines/ping.ogg', 50, 1, -1)
Переделать в свич

2022-03-07 17:15 UTC, Vallat commented on code/game/objects/items/devices/tts.dm
> +		name = "[new_name]'s [initial(name)]"
```suggestion
	if(!new_name)
		return
	new_name = reject_bad_name(new_name)
	name = "[new_name]'s [initial(name)]"
```

2022-03-09 12:21 UTC, BeebBeebBoob commented on code/game/objects/items/devices/tts.dm
> +	desc = "A small device with a keyboard attached. Anything entered on the keyboard is played out the speaker. \n<span class='notice'>Alt-click the device to make it beep.</span> \n<span class='notice
Я не зря так сделал ибо текст слишком широкий когда в преференсах выбираешь поэтому так.

2022-03-09 12:39 UTC, Vallat approved these changes

2022-03-12 16:19 UTC, merged