Tweak: Перевод описаний болезней и вирусов
ss220-space/Paradise pull request #685
Opened 2022-03-09 20:28 UTC by Ohar

## Changelog
:cl:
tweak: Перевод описаний болезней и вирусов
/:cl:

2022-03-10 17:12 UTC, Jordanstolethepreciousslam commented on code/datums/diseases/advance/symptoms/damage_converter.dm
> +	name = "Компенсация токсинов"
Этот симптом не компенсирует токсины, наоборот, он компенсирует брут/берн токсина**ми**. Правильнее будет Токсическая компенсация или Компенсация токсинами.

2022-03-10 17:38 UTC, Jordanstolethepreciousslam commented on code/datums/diseases/advance/symptoms/choking.dm
> +				to_chat(M, "<span class='warning'>[pick("Вам становится трудно дышать.", "Ваше начинаете тяжело дышать.")]</span>")
Что

2022-03-10 17:43 UTC, Jordanstolethepreciousslam commented on code/datums/diseases/anxiety.dm
> +				to_chat(affected_mob, "<span class='danger'>Вы чувствуете, как у вас в животе порхают бабочек.</span>")
Кто порхает бабочек?

2022-03-12 08:21 UTC, Ohar commented on code/datums/diseases/advance/symptoms/choking.dm
> +				to_chat(M, "<span class='warning'>[pick("Вам становится трудно дышать.", "Ваше начинаете тяжело дышать.")]</span>")
@Jordanstolethepreciousslam Что «что»?

2022-03-12 08:45 UTC, Ohar commented on code/datums/diseases/advance/symptoms/damage_converter.dm
> +	name = "Компенсация токсинов"
Исправил

2022-03-12 08:46 UTC, Ohar commented on code/datums/diseases/anxiety.dm
> +				to_chat(affected_mob, "<span class='danger'>Вы чувствуете, как у вас в животе порхают бабочек.</span>")
Исправил

2022-03-12 19:21 UTC, Jordanstolethepreciousslam commented on code/datums/diseases/advance/symptoms/choking.dm
> +				to_chat(M, "<span class='warning'>[pick("Вам становится трудно дышать.", "Ваше начинаете тяжело дышать.")]</span>")
> Ваше начинаете тяжело дышать

2022-03-12 20:39 UTC, Jordanstolethepreciousslam commented on code/datums/diseases/advance/symptoms/choking.dm
> +				to_chat(M, "<span class='warning'>[pick("Вам становится трудно дышать.", "Ваше начинаете тяжело дышать.")]</span>")
@Ohar

2022-03-20 12:01 UTC, Ohar commented on code/datums/diseases/advance/symptoms/choking.dm
> +				to_chat(M, "<span class='warning'>[pick("Вам становится трудно дышать.", "Ваше начинаете тяжело дышать.")]</span>")
@Jordanstolethepreciousslam Поправил

2022-03-20 12:01 UTC, Ohar commented on code/datums/diseases/advance/symptoms/choking.dm
> +				to_chat(M, "<span class='warning'>[pick("Вам становится трудно дышать.", "Ваше начинаете тяжело дышать.")]</span>")
Поправил

2022-04-16 09:06 UTC, girafe969 requested changes
Короче меня достало, остановился на простуде9 , потом посмотрю чё там дальше. Не забудь обновить Вики под твои названия

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/_disease.dm
> +	var/agent = "некоторые микробы"
В русском так не говорится, в данном случае дословный перевод будет "какие-то микробы" или "сколько-то микробов". Можно оставить просто "микробы"

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/advance/advance.dm
>  	agent = "advance microbes"
Улучшенные/продвинутые микробы

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/beard.dm
> +					to_chat(H, "<span class='warning'>Вы чувствуете себя на 20% круче.</span>")
А почему только на 20%?)

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/cough.dm
> +				to_chat(M, "<span notice='warning'>[pick("Вы сглатываете лишнюю мокроту.", "Вы покашливаете.")]</span>")
Мокрота и так лишняя. Не лишняя слизь и секреции слизистых (mucus), которые, при излишнем образовании и отделении, называются мокротой (как я понял из 5 минут общения с гуглом)

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/deafness.dm
> +					to_chat(M, "<span class='userdanger'>Вы слышите потрескивание и нарастающий гул!</span>")
Насколько я знаю, ear pop это когда ухо закладывает, впервые слышу про треск.

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/fire.dm
> +				to_chat(M, "<span class='warning'>[pick("Вы чувствуете жар.", "У вас жар.", "Вы слышите потрескивающие звуки.", "Вы чувствуете запах дыма.")]</span>")
В русском мы всё же чаще чувствуем запах гари, чем запах дыма.

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/flesh_eating.dm
> +				to_chat(M, "<span class='warning'>[pick("Вы чувствуете резкую боль во всём теле.", "На вашей кожей внезапно проступают капельки крови.")]</span>")
На вашей коже

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/flesh_eating.dm
> +				to_chat(M, "<span class='userdanger'>[pick("Вы содрогаетесь от жуткой боли во всём теле.", "Ваше тело, кажется, пожирает само себя прямо внутри вас!", "ВАМ ОЧЕНЬ БОЛЬНО!")]</span>")
Ещё бы тело пожирало само себя снаружи вас, вообще фильм ужасов бы получился. В русском схожее значение имеет "Ваше тело будто выворачивает наизнанку", либо просто убрать "прямо внутри вас!"

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/hallucigen.dm
> +				to_chat(M, "<span class='warning'>[pick("Что-то мелькает на границе вашего периферийного зрения, и сразу исчезает.", "Вы слышите лёгкий шёпот из неопределённого источника.", "У вас болит голова."
Периферийное зрение и так на границе зрения, это тавтология. Лучше либо переделать, оставив периферийное зрение и убрав границу, либо просто убрать периферийного. 
"шепот из ниоткуда" не подойдёт? Как-то "неопределенного источника" выглядит громоздко

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/headache.dm
> +		to_chat(M, "<span class='warning'>[pick("У вас болит голова.", "Голова наливается тяжестью.")]</span>")
Голова или раскалывается, или кружится, или башка трещит, или виски стучат. Наливается тяжестью редко используют для описания мигрени

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/oxygen.dm
> +	name = "Автодыхание"
Не очень нравится это название, так как дыхание и так происходит автоматически на уровне рефлексов. Пока придумать альтернативу не могу, Самодыхание с Вики тоже звучит убого. Респирация это всё же немного не то же самое, что дыхание. Ещё подумаю, может что придет в голову

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/anxiety.dm
> +	cure_text = "Этанол"
Не стоит ли тут и в последующих местах добавить в скобках английское название лекарства? Или раз уж переводим, то всё?

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/appendicitis.dm
> +	desc = "Если не вылечить, то субъект будет слабеть и может начать постоянно блевать."
Блевать - разговорное слово. Использовать его в научном описании болезни неуместно. (Учитывая, что у тебя в том же предложении есть научное слово субъект)

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/brainrot.dm
> +	desc = "Эта болезнь разрушает клетки мозга, провоцируя воспаление мозга, его некроз и общую интоксикацию организма."
Убери тут про общую интоксикацию, это давно выпилили, но не поменяли описание. (Буквально в комменте ниже написано)

2022-04-16 09:06 UTC, girafe969 commented on code/datums/diseases/cold.dm
> +	cure_text = "Отдых + Spaceacillin"
А спейсацелин особенный? (Хотя вообще я бы перевел его как космоцелин, но на Вики так)

2022-04-16 19:06 UTC, Ohar commented on code/datums/diseases/advance/symptoms/beard.dm
> +					to_chat(H, "<span class='warning'>Вы чувствуете себя на 20% круче.</span>")
Потому что «20% cooler» это мем

2022-04-16 19:08 UTC, Ohar commented on code/datums/diseases/advance/symptoms/cough.dm
> +				to_chat(M, "<span notice='warning'>[pick("Вы сглатываете лишнюю мокроту.", "Вы покашливаете.")]</span>")
Если убрать «лишнюю», смысл немного изменится - не будет очевидно что происходит что-то ненормальное

2022-04-16 19:09 UTC, Ohar commented on code/datums/diseases/advance/advance.dm
>  	agent = "advance microbes"
Резонно

2022-04-16 19:11 UTC, Ohar commented on code/datums/diseases/advance/symptoms/deafness.dm
> +					to_chat(M, "<span class='userdanger'>Вы слышите потрескивание и нарастающий гул!</span>")
А ringing?
Но да, стоит переформулировать

2022-04-16 19:26 UTC, Ohar commented on code/datums/diseases/advance/symptoms/fire.dm
> +				to_chat(M, "<span class='warning'>[pick("Вы чувствуете жар.", "У вас жар.", "Вы слышите потрескивающие звуки.", "Вы чувствуете запах дыма.")]</span>")
Верно

2022-04-16 19:27 UTC, Ohar commented on code/datums/diseases/advance/symptoms/flesh_eating.dm
> +				to_chat(M, "<span class='warning'>[pick("Вы чувствуете резкую боль во всём теле.", "На вашей кожей внезапно проступают капельки крови.")]</span>")
Коже?

2022-04-16 19:30 UTC, Ohar commented on code/datums/diseases/advance/symptoms/flesh_eating.dm
> +				to_chat(M, "<span class='warning'>[pick("Вы чувствуете резкую боль во всём теле.", "На вашей кожей внезапно проступают капельки крови.")]</span>")
Поправлю

2022-04-16 19:31 UTC, Ohar commented on code/datums/diseases/advance/symptoms/flesh_eating.dm
> +				to_chat(M, "<span class='userdanger'>[pick("Вы содрогаетесь от жуткой боли во всём теле.", "Ваше тело, кажется, пожирает само себя прямо внутри вас!", "ВАМ ОЧЕНЬ БОЛЬНО!")]</span>")
Так там и есть ыиль ужасов по факту

2022-04-16 19:32 UTC, Ohar commented on code/datums/diseases/advance/symptoms/hallucigen.dm
> +				to_chat(M, "<span class='warning'>[pick("Что-то мелькает на границе вашего периферийного зрения, и сразу исчезает.", "Вы слышите лёгкий шёпот из неопределённого источника.", "У вас болит голова."
Ок, поменяю

2022-04-16 19:33 UTC, Ohar commented on code/datums/diseases/advance/symptoms/hallucigen.dm
> +				to_chat(M, "<span class='warning'>[pick("Что-то мелькает на границе вашего периферийного зрения, и сразу исчезает.", "Вы слышите лёгкий шёпот из неопределённого источника.", "У вас болит голова."
```suggestion
				to_chat(M, "<span class='warning'>[pick("Что-то мелькает на границе вашего зрения, и сразу исчезает.", "Вы слышите лёгкий шёпот непонятно откуда.", "У вас болит голова.")]</span>")
```

2022-04-16 19:34 UTC, Ohar commented on code/datums/diseases/advance/advance.dm
>  	agent = "advance microbes"
```suggestion
	agent = "улучшенные микробы"
```

2022-04-16 19:35 UTC, Ohar commented on code/datums/diseases/_disease.dm
> +	var/agent = "некоторые микробы"
```suggestion
	var/agent = "какие-то микробы"
```

2022-04-16 19:37 UTC, Ohar commented on code/datums/diseases/advance/symptoms/deafness.dm
> +					to_chat(M, "<span class='userdanger'>Вы слышите потрескивание и нарастающий гул!</span>")
```suggestion
					to_chat(M, "<span class='userdanger'>Вы слышите нарастающие гул и треск, от которых закладывает уши!</span>")
```

2022-04-16 19:38 UTC, Ohar commented on code/datums/diseases/advance/symptoms/fire.dm
> +				to_chat(M, "<span class='warning'>[pick("Вы чувствуете жар.", "У вас жар.", "Вы слышите потрескивающие звуки.", "Вы чувствуете запах дыма.")]</span>")
```suggestion
				to_chat(M, "<span class='warning'>[pick("Вы чувствуете жар.", "У вас жар.", "Вы слышите потрескивающие звуки.", "Вы чувствуете запах гари.")]</span>")
```

2022-04-16 19:39 UTC, Ohar commented on code/datums/diseases/appendicitis.dm
> +	desc = "Если не вылечить, то субъект будет слабеть и может начать постоянно блевать."
А что уместно?

2022-04-16 19:40 UTC, Ohar commented on code/datums/diseases/brainrot.dm
> +	desc = "Эта болезнь разрушает клетки мозга, провоцируя воспаление мозга, его некроз и общую интоксикацию организма."
```suggestion
	desc = "Эта болезнь разрушает клетки мозга, провоцируя его воспаление мозга и последующий некроз."
```

2022-04-16 22:49 UTC, girafe969 requested changes
Бобик сдох... Я вроде закончил, там дальше всякие левые файлы

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/beesease.dm
> +	agent = "Пчелиный вирус"
Может можно тут как-то сохранить научный окрас текста? Я понимаю, что на русском это семейство пчелиных, и у нас нет "завумного" названия для них, но хотелось бы как-то это обыграть

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/critical.dm
> +	spread_text = "Пациент в шоке"
Звезда в шоке!))
Пациент в состоянии шока/ в шоковом состоянии

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/critical.dm
> +					to_chat(affected_mob, "<span class='danger'>Вам становится катастрофически плохо!</span>")
Не становится, тут нет сравнения с тем, как было раньше

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/critical.dm
> +	spread_text = "У пациента сердечная недостаточность"
Сердечный приступ

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/critical.dm
> +					to_chat(affected_mob, "<span class='danger'>Ваше сердце колотится в груди!</span>")
Оно и так колотится в груди. Стоит добавить что-то вроде "бешено колотится", чтобы показать что это не нормально

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/critical.dm
> +					to_chat(affected_mob, "<span class='warning'>Вы чувствуете [pick("онемение", "замешательство", "головокружение", "lightheaded")].</span>")
Lightheaded на русском это что-то вроде "потемнение в глазах". Предобморочное состояние короче. Так как на английском lightheaded и dizzy - синонимы, чтобы не делать тут новую конструкцию lightheaded можно вообще убрать

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/dna_spread.dm
>  	severity = MEDIUM
Не убрал английское описание. Я бы перевел initial vector как "нулевого пациента" или "вектора инициализации" (если это отсылка на него).
Как я понял спустя полчаса общения с гуглом, скорее всего тут игра слов между initial patient (первый заразившийся каким-либо вирусом) и initialization vector (криптографическое понятие), как это правильно обыграть на русском я не уверен.

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/cough.dm
> +				to_chat(M, "<span notice='warning'>[pick("Вы сглатываете лишнюю мокроту.", "Вы покашливаете.")]</span>")
Можно использовать "подступившую". Так будет понятно, что её не было

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/flesh_eating.dm
> +				to_chat(M, "<span class='userdanger'>[pick("Вы содрогаетесь от жуткой боли во всём теле.", "Ваше тело, кажется, пожирает само себя прямо внутри вас!", "ВАМ ОЧЕНЬ БОЛЬНО!")]</span>")
Либо заменить прямо внутри вас на изнутри

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/appendicitis.dm
> +	desc = "Если не вылечить, то субъект будет слабеть и может начать постоянно блевать."
Субъект будет слабеть и часто испытывать рвотные позывы

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/fake_gbs.dm
> +	agent = "Гравитокинетический бипотенциал SADS−"
"бипотенциальный СВС-" (синдром внезапной смерти)

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/gbs.dm
> +	agent = "Гравитокинетический бипотенциал SADS+"
бипотенциальный СВС+

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/kingstons.dm
> +													"<span class='userdanger'>ВЫ ПРЕВРАТИЛИСЬ В ТАЯРАНА!</span>")
В таяру. Тайаран это название расы, таяра - представитель этой расы

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/kingstons.dm
> +	name = "[initial(chosentype.name_adjective_female)] [chosensuff]"
Я так понял, тут должно быть типа "Скреллская чума" на выходе? Чувствую, будет пиздец. Наверное, стоит пока что это не трогать.

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/kingstons.dm
> +														"<span class='userdanger'>Ваше тело мутирует в [initial(chosentype.name)]!</span>")
Тут тоже будет склонение, и на строке выше

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/kingstons.dm
> +					affected_mob.visible_message("<span class='danger'>Черты [affected_mob] становятся намного более кошачьими!</span>", \
Привет склонение имён по падежам, удачи тебе с этим)

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/lycancoughy.dm
> +				affected_mob.visible_message("<span class='danger'>[affected_mob] выкашливает [initial(puppypicked.name)]!</span>", \
"Павел Михайлов выкашливает fox".
Ниже всё так же

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/magnitis.dm
> +	agent = "Фуккос Миракос"
Это сто процентов игра слов. Miracos скорее всего от miraculous. Fukkos возможо от Fukko ( https://www.google.com/amp/s/www.urbandictionary.com/define.php%3fterm=Fukko&amp=true), хотя я не уверен. Дословно что-то типа Шлюхус Чудеснус/Необыкновеннус. Только это больше подражание латинскому, а в оригинале - испанскому

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/magnitis.dm
> +				to_chat(affected_mob, "<span class='danger'>Вы задаётесь вопросом о природе происходящих странностей.</span>")
Опять же отсылка на Miracos в агенте. "о природе чудес" (хотя звучит не очень)
Суть не в происходящих сейчас странностях (из-за вируса), а о странностях в целом. Если сможешь это по-другому сформулировать, будет круто

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/retrovirus.dm
> +	agent = "Вирус класса [pick("А","Б","В","Г","Д","Е")][pick("А","Б","В","Г","Д","Е")]-[rand(50,300)]"
Массив букв переводить не стоит, так как это отсылка на двоичную систему

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/transformation.dm
> +	agent = "Шалости"
"Шалости" недостаточно сленгово, как по мне. Я бы сделал "проделки педалей"

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/transformation.dm
> +				to_chat(affected_mob, "<span class='notice'>Ваша [pick("спина", "рука", "нога", "грудь", "голова")] чешется.</span>")
Скопируй лист из чесотки, эта болезнь пытается под неё маскироваться на ранних стадиях.
Ты вроде там ещё задницу добавлял и что-то ещё

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/transformation.dm
> +	stage2	= list("Ваши суставы теряют гибкость.", "<span class='danger'>Биg… буп…</span>")
Бип... Буп...

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/transformation.dm
> +	stage4	= list("<span class='danger'>Ваша кожа значительно твердеет.</span>", "<span class='danger'>Ваша кровь начинает кипеть!</span>", "<span class='danger'>Вы чувствуете… что-то… внутри себя.</spa
Кровь закипает

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/transformation.dm
> +	stage2	= list("Ваша кожа становится липкой.")
Слизкой

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/tuberculosis.dm
> +	desc = "Редкий высококонтагиозный вирулентный вирус. Существует несколько штаммов, которые, по слухам, были тщательно выращены и культивированы нелегальными специалистами по биологическому оружию. В
По слову истощение непонятно, что ты будешь более голодным. Лучше перевести дословно - потерю веса

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/tuberculosis.dm
> +				to_chat(affected_mob, "<span class='userdanger'>[pick("Ваше сердце начинает биться реже…", "Вы расслабляетесь и сердцебиение замедляется.")]</span>")
Тут не надо запятую? Я уже не в состоянии гуглить

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/tuberculosis.dm
> +				to_chat(affected_mob, "<span class='danger'>[pick("Вв чувствуете неприятный жар…", "Вам хочется расстегнуть комбинезон.", "Вам хочется снять одежду…")]</span>")
Вы, а не Вв

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/wizarditis.dm
> +	desc = "Поговаривают, что этот вирус — причина существования Федерации Космических Волшебников. Поражённые им субъекты выказывают признаки деменции, выкрикивают невразумительные предложения и несут
Спирт не бывает мужественным. И это вообще не спирт. Глоток крепкого мужского спиртного

2022-04-16 22:49 UTC, girafe969 commented on code/datums/diseases/wizarditis.dm
> +	agent = "Ринсвиндий обыкновенный"
Тоже неплохо бы было адаптировать. Rincé - это смывать, полоскать на французском, то же что rinse на англе. Вторая часть либо от wind (как wind of magic), либо window. Но мойщик окон на англе window washer, а не window rincer, поэтому всё же скорее всего это ветер. Только связать эти два слова в одно у меня не получается.

2022-04-16 23:12 UTC, girafe969 commented on code/datums/diseases/advance/symptoms/deafness.dm
> +					to_chat(M, "<span class='userdanger'>Вы слышите потрескивание и нарастающий гул!</span>")
Ringing это звон в ушах

2023-07-27 17:22 UTC, closed without merging