HulkFromTauCeti
ss220-space/Paradise pull request #69
Opened 2021-06-28 10:17 UTC by FatFatFat1

Перенос ПР на новый репозиторий

## What Does This PR Do

## Why It's Good For The Game

## Images of changes

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
fix: fixed a few things
wip: added a few works in progress
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
experiment: added an experimental thingy
/:cl:

2021-07-02 15:00 UTC, FatFatFat1 commented
Ну пожалуйста проверьте

2021-07-11 11:27 UTC, FatFatFat1 commented
══════════████████═════██████
═════════█░░░░░░░░██═██░░░░░░█
════════█░░░░░░░░░░░█░░░░░░░░░█
═══════█░░░░░░░███░░░█░░░░░░░░░█
═══════█░░░░███░░░███░█░░░████░█
══════█░░░██░░░░░░░░███░██░░░░██
═════█░░░░░░░░░░░░░░░░░█░░░░░░░░███
════█░░░░░░░░░░░░░██████░░░░░████░░█
════█░░░░░░░░░█████░░░████░░██░░██░░█
═══██░░░░░░░███░░░░░░░░░░█░░░░░░░░███
══█░░░░░░░░░░░░░░█████████░░█████████
═█░░░░░░░░░░█████═████══████═█████══█
═█░░░░░░░░░░█════█═███══█═══███═█═══█
█░░░░░░░░░░░░█═══████═████══██═██████
░░░░░░░░░░░░░█████████░░░████████░░░█
░░░░░░░░░░░░░░░░█░░░░░█░░░░░░░░░░░░█
░░░░░░░░░░░░░░░░░░░░██░░░░█░░░░░░██
░░░░░░░░░░░░░░░░░░██░░░░░░░███████
░░░░░░░░░░░░░░░░██░░░░░░░░░░█░░░░░█
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█
░░░░░░░░░░░█████████░░░░░░░░░░░░░░██
░░░░░░░░░░█▒▒▒▒▒▒▒▒███████████████▒▒█
░░░░░░░░░█▒▒███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█
░░░░░░░░░█▒▒▒▒▒▒▒▒▒█████████████████
░░░░░░░░░░████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█
░░░░░░░░░░░░░░░░░░██████████████████
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█
██░░░░░░░░░░░░░░░░░░░░░░░░░░░██
▓██░░░░░░░░░░░░░░░░░░░░░░░░██
▓▓▓███░░░░░░░░░░░░░░░░░░░░█
▓▓▓▓▓▓███░░░░░░░░░░░░░░░██
▓▓▓▓▓▓▓▓▓███████████████▓▓█
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█

2021-07-13 14:22 UTC, Vallat requested changes
В целом нормально, есть некоторые мелочи которые нужно поправить. Плюс, я бы добавил еще уникальных взаимодействий с алиенами и другими существами, по типу тех, что были. Например, откидывание чужих от себя, расплющивание смайлов и т.д.
Но вообще надо вынести на голосование это изменение и/или отдать на рассмотрение геймдизайнеру

2021-07-13 14:22 UTC, Vallat commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	return
```suggestion
/obj/effect/proc_holder/spell/aoe_turf/hulk/hulk_transform/cast(list/targets, mob/user = usr)
	if(HAS_TRAIT(user, TRAIT_PACIFISM))
		to_chat(user, "<span class='warning'>Not enough angry power")
		return
	if(istype(user,/mob/living/simple_animal/hulk))
		to_chat(user, "<span class='warning'>You are already hulk")
		return
	to_chat(user, "<span class='bold notice'>You can feel real POWER.</span>")
	if(istype(user.loc, /obj/machinery/dna_scannernew))
		var/obj/machinery/dna_scannernew/DSN = loc
		DSN.occupant = null
		DSN.icon_state = "scanner_0"
	var/mob/living/simple_animal/hulk/Monster
	if(CLUMSY in user.mutations)
		Monster = new /mob/living/simple_animal/hulk/clown_hulk(get_turf(user))
	else if(isunathi(user))
		Monster = new /mob/living/simple_animal/hulk/zilla(get_turf(user))
	else
		Monster = new /mob/living/simple_animal/hulk/human(get_turf(user))

	var/datum/effect_system/smoke_spread/smoke = new
	smoke.set_up(10, 0, user.loc)
	smoke.start()
	playsound(usr, 'sound/effects/bamf.ogg', CHANNEL_BUZZ)
	Monster.original_body = user
	user.forceMove(Monster)
	user.mind.transfer_to(Monster)
	Monster.say(pick("RAAAAAAAARGH!", "HNNNNNNNNNGGGGGGH!", "GWAAAAAAAARRRHHH!", "NNNNNNNNGGGGGGGGHH!", "AAAAAAARRRGH!" ))
	return
```
Заменить usr на user, иначе непонятно зачем было это переопределение в вызове функции

2021-07-13 14:22 UTC, Vallat commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	return
Здесь точно так же нужно заменить usr на user

2021-07-13 14:22 UTC, Vallat commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	return
И здесь тоже мы меняем usr на user

2021-07-13 14:22 UTC, Vallat commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	playsound(usr, 'sound/items/airhorn.ogg', CHANNEL_BUZZ)
А еще вот тут меняем usr на user

2021-07-13 14:22 UTC, Vallat commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	playsound(usr,pick('sound/spookoween/scary_clown_appear.ogg','sound/spookoween/scary_horn.ogg','sound/spookoween/scary_horn2.ogg','sound/spookoween/scary_horn3.ogg'),CHANNEL_BUZZ, 100)
И вот здесь меняем usr на user. Так же не уверен, баг это гитхаба или нет, но кажется у playsound поехала табуляция

2021-07-13 14:22 UTC, Vallat commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +		sleep(1)
Заменить usr на user

2021-07-13 14:22 UTC, Vallat commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	playsound(usr, 'sound/magic/fireball.ogg', CHANNEL_BUZZ)
Нужно поменять usr на user

2021-07-13 14:22 UTC, Vallat commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	user.newtonian_move(get_dir(U, T))
И тут тоже мы меняем usr на user, хотя где-то уже и правильно

2021-07-13 14:22 UTC, Vallat commented on code/modules/mob/living/simple_animal/hulk.dm
> +	qdel(src)
При смерти халка человеку, который в него превратился, ничего не будет? Странно немного

2021-07-13 14:29 UTC, FatFatFat1 commented on code/modules/mob/living/simple_animal/hulk.dm
> +	qdel(src)
153 строка - паралич от смерти

2021-07-14 15:13 UTC, FatFatFat1 commented
Видимо можно перекидывать ПР в Reviewer approved. Раз все готово

2021-07-19 13:43 UTC, Bizzonium requested changes
Также не хватает логгирования
Например:
`add_attack_logs(user, src, "Punched with hulk powers")`
`SEND_SIGNAL(src, COMSIG_ATOM_HULK_ATTACK, user)`

2021-07-19 13:43 UTC, Bizzonium commented on code/modules/mob/living/simple_animal/hulk.dm
> +	desc = "Big b>y"
Описание на гендерно-нейтральное

2021-07-19 13:43 UTC, Bizzonium commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	desc = ""
Не хватает описания всем спеллам

2021-07-19 16:22 UTC, FatFatFat1 commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	desc = ""
теперь хватает

2021-07-19 16:22 UTC, FatFatFat1 commented on code/modules/mob/living/simple_animal/hulk.dm
> +	desc = "Big b>y"
теперь нейтральное

2021-07-19 16:27 UTC, Bizzonium requested changes

2021-07-19 16:27 UTC, Bizzonium commented on code/modules/mob/living/simple_animal/hulk.dm
> +	desc = "Run"
```suggestion
	desc = "Huge and strong!"
```

2021-07-19 16:27 UTC, Bizzonium commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	desc = "Разбег.Чем он дольше,тем больнее будет,тем кто встанет у вас на пути."
```suggestion
	desc = "Разбег. Чем он дольше, тем больнее будет, тем кто встанет у вас на пути."
```

2021-07-19 16:27 UTC, Bizzonium commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	desc = "Прыжок.Можно легко сломать кому-нибудь кость,если попасть прямо в цель."
```suggestion
	desc = "Прыжок. Можно легко сломать кому-то кость при столкновении."
```

2021-07-19 16:27 UTC, Bizzonium commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	desc = "Ваш хонк заставляет ваших врагов пасть на пол и налить под себя смазку(от страха).На ваших братьях клоунах работает как лечение."
```suggestion
	desc = "Ваш хонк заставляет ваших врагов пасть на пол и налить под себя смазку (от страха). На ваших братьях-клоунах работает как лечение."
```

2021-07-19 16:27 UTC, Bizzonium commented on code/modules/mob/living/simple_animal/hulk_power.dm
> +	desc = "Пускает большое облако дыма,а так-же лечит вас.Хорошее решение если вам нужно отступить."
```suggestion
	desc = "Пускает большое облако дыма, а так-же лечит вас. Хорошее решение если вам нужно отступить."
```

2021-07-19 16:53 UTC, FatFatFat1 commented
Что-то еще?

2021-07-19 17:00 UTC, Bizzonium approved these changes
LGTM

2021-07-19 17:14 UTC, merged