Мелкие фиксы: Починка status у shock_kit и IED на капкане
ss220-space/Paradise pull request #727
Opened 2022-04-04 02:51 UTC by Den109G

## What Does This PR Do
Чинит код, который не работал.
shock_kit теперь нормально меняет свой статус, теперь можно сделать из него электрический стул, как и было задумано.
IED теперь корректно крепиться к капкану.

## Why It's Good For The Game
Можно будет собрать стул для казни, если прошлый сломается.
IED не будет вечно копиться в капкане, а будет использоваться по назначению.
Код будет работать.

## Changelog
:cl:
fix: shock_kit's status, now it works
fix: IED on beartraps now works!
/:cl:

2022-04-04 06:22 UTC, Vallat requested changes

2022-04-04 06:22 UTC, Vallat commented on code/modules/assembly/shock_kit.dm
> +		to_chat(user, "<span class='notice'>[src] is now ready!</span>")
```suggestion
	status = !status
	if(status)
		to_chat(user, "<span class='notice'>[src] is now ready to be attached to a chair!</span>")
	else
		to_chat(user, "<span class='notice'>[src] is now ready!</span>")
```

2022-04-04 08:14 UTC, Den109G commented
Да, че-то протупил тут. Спасибо.

2022-04-04 08:39 UTC, Vallat approved these changes

2022-04-07 00:15 UTC, TrashDoxx approved these changes

2022-04-07 17:25 UTC, merged