Жизни детективов важны
ss220-space/Paradise pull request #736
Opened 2022-04-07 19:44 UTC by captainnelly

## What Does This PR Do
Перчатки детектива теперь остаются в криохранилище

## Why It's Good For The Game
Предложка -> https://discord.com/channels/617003227182792704/755125334097133628/961708921242931220

## Changelog
:cl:
tweak: Forensic gloves now stays at cryonics like high risk items and guns
/:cl:

2022-04-07 19:59 UTC, TrashDoxx commented
Неправильно. Сейчас починю.

2022-04-07 20:02 UTC, TrashDoxx commented on code/game/machinery/cryopod.dm
> +		/obj/item/clothing/gloves/color/black/forensics
```suggestion
		/obj/item/clothing/gloves/color/black/forensics,
		/obj/item/clothing/gloves/color/black/krav_maga/sec,
		/obj/item/spacepod_key,
		/obj/item/nullrod,
		/obj/item/key
```

2022-04-07 20:07 UTC, TrashDoxx requested changes

2022-04-07 20:07 UTC, TrashDoxx commented on code/game/machinery/cryopod.dm
>  		/obj/item/spacepod_key,
```suggestion
		/obj/item/clothing/gloves/color/black/forensics,
		/obj/item/spacepod_key,
		/obj/item/nullrod,
		/obj/item/key
```

2022-04-07 20:26 UTC, captainnelly commented on code/game/machinery/cryopod.dm
>  		/obj/item/spacepod_key,
Шутник

2022-04-07 20:43 UTC, captainnelly commented
> Неправильно. Сейчас починю.

Бля, я принял..

2022-04-07 20:48 UTC, captainnelly commented
И хули там теперь дубликат ключа и нуллрода

2022-04-07 21:09 UTC, TrashDoxx commented
Ну, да, неудачно вышло.

2022-04-07 21:09 UTC, TrashDoxx commented
Я привык по одной строке править.

2022-04-07 21:09 UTC, TrashDoxx commented
В целом, мне абсолютно похуй.

2022-04-08 06:12 UTC, Vallat approved these changes

2022-04-12 14:59 UTC, merged