Ruin tweaks fixes reworks and etc
ss220-space/Paradise pull request #741
Opened 2022-04-09 10:06 UTC by snipersir

## What Does This PR Do

Сегодня на обозревание выкладываются коммиты со следующим содержимым:

* NT Medical Shuttle - whiteship.dmm - замена старого пустого шатла на шатл whiteship_box с билда TG с немного измененной структоурой, своими мелкими решениями, и иным лутом. Зоны посадки изменены под новый размер шатла.

* GAS THE LIZARDS - gasthelizards.dmm - бывшая скушная, убитая по функционалу структура-руина была пересобрана из своей версии и версии с другой сборки TG. Теперь это полноценное место для расправы над кем-либо, какими-либо жертвами, ну и конечно же ЛИЗАРДАМИ. Лут комбинирован, есть взломанный маяк и взломанный гиббер для полного веселья и в целом для пользования, карта ТОЛЬКО ДЛЯ ЭТОЙ структуры, она НЕ СБШНАЯ. Карта в космосе НЕ дублируется. Возможно потребуется поменять весы, но для популяризации сего заведения пока будет так.

* USSP station aka KC13(?) - ussp.dmm - изменено положение соляр, добавлен разбитый шатл в прибытие где ему и место, добавлена пушка в церковь за место того ущербного выхода, ИСПРАВЛЕНЫ нерабочие шлюзы станции (да-да, только теперь это выяснилось ибо не было репортов об это ранее), немного поменялась инженерка.

* Oldstation aka Charlie-Theta Station aka Theta Station - oldstation.dmm - косметические исправления и добавления, весы изменены с 3х на 4. Структура часто появляется для своего размера. Это попытка ребаланса количества структур в космосе.

* The Twin Nexus Hotel - spacehotelv1.dmm - исправлено имя мед бота, удалена телестанция (её начали абузить) и на её место установлен перманентный хаб.

* Punisment - punishment.dmm - исправлена записка.

## Why It's Good For The Game

Собственно продвигаем тему с космосом всё дальше, делаем его приятнее для посещения всеми космонавтами и в целом интереснее, исправляем косяки. Сообщайте про баги в дискорд мапперам, если таковые найдутся.

## Images of changes

Изменения Станции советов
![ussp_old](https://user-images.githubusercontent.com/25121334/162566916-2819d944-f9e6-418c-978c-e48932882963.png)
![ussp_rework1](https://user-images.githubusercontent.com/25121334/162567193-267b6f1d-8658-4cde-98d3-0e3d7cc0900a.png)

Изменения Мед шатла
![whiteship_old](https://user-images.githubusercontent.com/25121334/162566934-3195e714-d466-4511-b383-f33e99d19fe9.png)
![ws_rework1](https://user-images.githubusercontent.com/25121334/162567067-c214c1e7-e609-4913-9375-9d87538fa558.png)

Изменения GasTheLizards
![gtl_old_para](https://user-images.githubusercontent.com/25121334/162566992-09d3c5cd-a85d-4dec-85f6-60b4d4b8f915.png)
![gtl_old_tg](https://user-images.githubusercontent.com/25121334/162566996-46a10cd7-2660-47dd-9c92-83876fe64c6b.png)
![gtl_rework1](https://user-images.githubusercontent.com/25121334/162566997-df0ea9c8-40c6-40d4-9663-98fed44179bb.png)

2022-04-09 10:32 UTC, TrashDoxx approved these changes

2022-04-10 14:37 UTC, Vallat requested changes

2022-04-10 14:37 UTC, Vallat commented on code/game/objects/structures/watercloset.dm
> +			return
```suggestion
			break
```

2022-04-10 14:37 UTC, Vallat commented on code/game/objects/structures/watercloset.dm
> +/obj/structure/toilet/cancollectmapitems
Добавь комментарий зачем это вообще существует

2022-04-10 15:31 UTC, Vallat approved these changes

2022-04-11 09:05 UTC, Ohar approved these changes

2022-04-12 16:04 UTC, merged