Tweak: Improves Mentor/Admin Tickets
ss220-space/Paradise pull request #745
Opened 2022-04-09 16:23 UTC by TrashDoxx

## Список изменений
* Порезан излишний перевод согласно давнему опросу среди менторов.
* Исправлена часть локализации, поправлены ошибки.
* Окно для ввода MentorHelp отображает MentorHelp, как и подобает.
* Единовременная конвертация тикета сразу несколькими людьми теперь невозможна.
* Добавлен желтый статус 'CONVERTED', если тикет был конвертирован.

## Отображение изменений
Окно ввода:
![image](https://user-images.githubusercontent.com/67621641/162581084-1de3fd2d-1ee5-4a37-9fc7-9814a7ea898f.png)

Статус:
![image](https://user-images.githubusercontent.com/67621641/162581090-6a4c73cf-95ca-47d2-a1ee-5979ddcd78ae.png)

2022-04-09 16:24 UTC, TrashDoxx commented
Теперь всё в норме, насколько я вижу. Стоит перепроверить.

2022-04-10 06:01 UTC, Vallat approved these changes
Надеюсь ты перепроверил 👍

2022-04-11 08:11 UTC, Ohar commented
А зачем перевод порезан?

2022-04-11 08:50 UTC, TrashDoxx commented
> А зачем перевод порезан? Наоборот же хорошо что в этом кривущем интерфейсе хоть перевод помогает разобраться.

Он всратый. Менторы голосовали за возврат, но я тогда забил на это. Сейчас сделал.

2022-04-11 09:42 UTC, Ohar requested changes

2022-04-11 09:42 UTC, Ohar commented on code/controllers/subsystem/tickets/tickets.dm
> +				"<span class='boldmessage'>Пожалуйста, постарайтесь быть спокойным, ясным и описательным в тикетах, не предполагайте что администратор видел какие-либо связанные события, и четко укажите имена те
При обращении к пользователю стоит соблюдать гендерно-нейтральные формулировки.
```suggestion
				"<span class='boldmessage'>Пожалуйста, постарайтесь в тикетах вести себя спокойно, излагать проблему ясно и описательно. Не предполагайте что администратор видел какие-либо связанные события, и чётко укажите имена тех, о ком вы сообщаете. Если вы задали вопрос, то убедитесь, что из него понятно, о чём именно вы спрашиваете.</span>",
```

2022-04-11 09:42 UTC, Ohar commented on code/controllers/subsystem/tickets/tickets.dm
> +		message_staff("<span class='[span_class]'>Тикет [report] был открыт [TICKET_TIMEOUT / 600] минут. Меняю статус на просроченный.</span>")
```suggestion
		message_staff("<span class='[span_class]'>Тикет [report] был открыт [TICKET_TIMEOUT / 600] минут. Меняю статус на «Просрочен».</span>")
```

2022-04-11 09:42 UTC, Ohar commented on code/controllers/subsystem/tickets/tickets.dm
> +		to_chat(C.mob, "<span class='[span_class]'>Ваш [ticket_name] #[ticketNum] остаётся открытым! Зайдите в \"My tickets\" во вкладке Admin чтобы просмотреть.</span>")
```suggestion
		to_chat(C.mob, "<span class='[span_class]'>Ваш [ticket_name] #[ticketNum] остаётся открытым! Его можно найти в «My tickets» во вкладке «Admin».</span>")
```

2022-04-11 09:42 UTC, Ohar commented on code/controllers/subsystem/tickets/tickets.dm
> +		"Сообщите об ошибке" = "Чтобы сообщить об ошибке, пожалуйста перейдите на <a href='[config.githuburl]'>GitHub</a>. После, в 'Issues' и 'New Issue'. Затем заполните все поля и отправьте. Если раунд
Лучше сразу дать ссылку на форму, чем инструкции по её поиску.
```suggestion
		"Сообщите об ошибке" = "Чтобы сообщить об ошибке, пожалуйста перейдите на <a href='[config.githuburl]/issues/new/choose'>GitHub</a>. Заполните все поля и отправьте. Если раунд всё ещё идёт, либо сохраните в текстовый файл, либо подождите пока раунд не закончится.",
```

2022-04-11 09:42 UTC, Ohar commented on code/controllers/subsystem/tickets/tickets.dm
> +		"IC-Проблема" = "Это игровая (IC-In Character) ситуация и не будет обрабатываться администраторами. Вы можете поговорить со службой безопасности, АВД, главой отдела, представителем Nanotrasen, или
```suggestion
		"IC-проблема" = "Это игровая (In Character, проблема между персонажами, а не между игроками) ситуация. Она не обрабатывается администраторами. Вы можете поговорить со службой безопасности, АВД, главой отдела, представителем Nanotrasen, или обратиться в любой другой соответствующий орган, находящийся в настоящее время на станции.",
```

2022-04-11 09:42 UTC, Ohar commented on code/controllers/subsystem/tickets/tickets.dm
> +		"Соберись с мыслями" = "Соберись с мыслями",
```suggestion
		"Мужайся" = "Мужайся",
```

2022-04-11 09:42 UTC, Ohar commented on code/controllers/subsystem/tickets/tickets.dm
> +		if("Соберись с мыслями")
```suggestion
		if("Мужайся")
```

2022-04-12 18:05 UTC, TrashDoxx commented on code/controllers/subsystem/tickets/tickets.dm
> +				"<span class='boldmessage'>Пожалуйста, постарайтесь быть спокойным, ясным и описательным в тикетах, не предполагайте что администратор видел какие-либо связанные события, и четко укажите имена те
WOMAN MOMENT :trollface:

2022-04-12 18:39 UTC, TrashDoxx commented
@Ohar Подтвердил правки. Можешь перепроверить перевод, если есть желание.

2022-04-12 19:30 UTC, Ohar approved these changes

2022-05-02 10:41 UTC, merged