Перевод «Air Alarm»
ss220-space/Paradise pull request #752
Opened 2022-04-10 19:37 UTC by Ohar

В процессе…

## Changelog
:cl:
tweak: Перевод «Air Alarm»
/:cl:

Вливать после [перевода медикаментов и реагентов](https://github.com/ss220-space/Paradise/pull/748) — тут предполагается что газы и прочие реагенты уже переведены.

2022-04-19 08:13 UTC, girafe969 requested changes
Проверь чтобы нигде не всплывал английский текст в перемешку с русским (кроме названия зоны)

2022-04-19 08:13 UTC, girafe969 commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +	description = "Позволяет отключить предохранители на всех атмосферных панелях. После этого их можно будет переключить на режим «Потоп», отключающий вытяжки и проверку давления. \
Проверку давления вентиляций

2022-04-19 08:13 UTC, girafe969 commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +	Кто угодно может проверить интерфейс атмосферной панели заметить проблему."
И заметить проблему

2022-04-19 08:13 UTC, girafe969 commented on code/game/gamemodes/malfunction/Malf_Modules.dm
>  	unlock_text = "<span class='notice'>You remove the safety overrides on all air alarms, but you leave the confirm prompts open. You can hit 'Yes' at any time... you bastard.</span>"
Перевод не нужОн

2022-04-19 08:13 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +	alert_signal.data["type"] = "Атмосфера"
Ты нашел где это используется? В правильной форме слово сделал?

2022-04-19 08:13 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_SCRUBBING   = list("name"="Фильтрация",         "desc"="Выфильтровать загрязнения", "id" = AALARM_MODE_SCRUBBING),\
Лучше во всех режимах использовать глаголы в несовершенном виде третьем лице. Что делает система в этом режиме? Фильтрует загрязнения

2022-04-19 08:13 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_SIPHON	    = list("name"="Выкачка",            "desc"="Откачать воздух из помещения", "id" = AALARM_MODE_SIPHON),\
Откачка.

2022-04-19 08:13 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_REPLACEMENT = list("name"="Замена",             "desc"="Откачать весь воздух и закачать новый", "id" = AALARM_MODE_REPLACEMENT),\
Потерялось before. Не очевидно, что эти действия идут одно _после_ другого (мы ж для дибилов переводим)

2022-04-19 08:13 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +		AALARM_PRESET_HUMAN		= list("name"="Люди",     	 "desc"="Проверка содержания кислорода и азота", "id" = AALARM_PRESET_HUMAN),\
Проверяет. В следующей строке так же

2022-04-19 08:13 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +					var/newval = input("Введите [varname] для [env]", "Триггеры тревог", tlv.vars[varname]) as num|null
Какая тут красивая свистопляска получится, я уже предвкушаю

2022-04-19 08:13 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +						to_chat(user, "<span class='notice'>Вы [ locked ? "запираете" : "отпираете"] интерфейс воздушной сигнализации.</span>")
Так всё-таки сигнализации?

2022-04-19 08:13 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +	name = "публичная воздушная сигнализация" // all-access air alarm
Панель. В следующей тоже

2022-04-19 08:13 UTC, girafe969 commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +      areaStatus = "Оптимум";
Оптимум выглядит стрёмно. Или это только мне кажется?

2022-04-19 08:13 UTC, girafe969 commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +          <LabeledList.Item label="Оксид углерода">
Диоксид углерода

2022-04-19 08:13 UTC, girafe969 commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +        <Icon name="sign-out-alt" /> Вентиляция
Вентиляции

2022-04-19 08:13 UTC, girafe969 commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +              content={s.scrubbing === 0 ? "Откачка" : "Вытяжка"}
Откачка и Фильтрация

2022-04-19 08:13 UTC, girafe969 commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +          <LabeledList.Item label="Разброс">
Радиус/Дальность

2022-04-19 08:13 UTC, girafe969 commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +          После смены настроек система автоматически начнёт цикл удаления загрязнений.
Цикл будет не удаления загрязнений, а откачки -> заполнения. Режим который ты перевел как Замена

2022-05-08 23:56 UTC, closed without merging

2022-05-21 22:58 UTC, Ohar commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +	Кто угодно может проверить интерфейс атмосферной панели заметить проблему."
Исправлено

2022-05-21 22:59 UTC, Ohar commented on code/game/gamemodes/malfunction/Malf_Modules.dm
>  	unlock_text = "<span class='notice'>You remove the safety overrides on all air alarms, but you leave the confirm prompts open. You can hit 'Yes' at any time... you bastard.</span>"
Сделан, исправлен

2022-05-21 23:31 UTC, Ohar commented on code/game/machinery/alarm.dm
> +	alert_signal.data["type"] = "Атмосфера"
Вроде нигде. Строки тревог иначе формируются.
Вернул взад на всякий случай.

2022-05-21 23:33 UTC, Ohar commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_SCRUBBING   = list("name"="Фильтрация",         "desc"="Выфильтровать загрязнения", "id" = AALARM_MODE_SCRUBBING),\
Нет, не согласен. Это не одноразовая кнопка, это режим работы системы

2022-05-21 23:35 UTC, Ohar commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_SIPHON	    = list("name"="Выкачка",            "desc"="Откачать воздух из помещения", "id" = AALARM_MODE_SIPHON),\
Откачка уже как режим работы вентиляций, не стоит дублировать

2022-05-21 23:37 UTC, Ohar commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_REPLACEMENT = list("name"="Замена",             "desc"="Откачать весь воздух и закачать новый", "id" = AALARM_MODE_REPLACEMENT),\
Хорошее замечание, поправил

2022-05-21 23:37 UTC, Ohar commented on code/game/machinery/alarm.dm
> +		AALARM_PRESET_HUMAN		= list("name"="Люди",     	 "desc"="Проверка содержания кислорода и азота", "id" = AALARM_PRESET_HUMAN),\
Заменил на инфинитив «Проверять»

2022-05-21 23:38 UTC, Ohar commented on code/game/machinery/alarm.dm
> +					var/newval = input("Введите [varname] для [env]", "Триггеры тревог", tlv.vars[varname]) as num|null
Никакой, это обычнвй попап

2022-05-21 23:38 UTC, Ohar commented on code/game/machinery/alarm.dm
> +						to_chat(user, "<span class='notice'>Вы [ locked ? "запираете" : "отпираете"] интерфейс воздушной сигнализации.</span>")
Да, везде уже «сигнализация», как на вики

2022-05-21 23:39 UTC, Ohar commented on code/game/machinery/alarm.dm
> +	name = "публичная воздушная сигнализация" // all-access air alarm
Таки сигнализация

2022-05-21 23:39 UTC, Ohar commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +      areaStatus = "Оптимум";
Тебе кажется. Он нормально выглядит, это же технический термин на сложном приборе.

2022-05-21 23:40 UTC, Ohar commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +          <LabeledList.Item label="Оксид углерода">
Даже «Двуокись углерода» — по-русски этот газ традиционно так называется

2022-05-21 23:40 UTC, Ohar commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +        <Icon name="sign-out-alt" /> Вентиляция
Исправил, спасибо

2022-05-21 23:41 UTC, Ohar commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +              content={s.scrubbing === 0 ? "Откачка" : "Вытяжка"}
Почему фильтрация?

2022-05-21 23:43 UTC, Ohar commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +          <LabeledList.Item label="Разброс">
Да, спасибо

2022-05-22 00:08 UTC, Ohar commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +          После смены настроек система автоматически начнёт цикл удаления загрязнений.
Спасибо, поправил формулировку

2022-05-22 04:58 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_SCRUBBING   = list("name"="Фильтрация",         "desc"="Выфильтровать загрязнения", "id" = AALARM_MODE_SCRUBBING),\
Вот именно потому что это режим работы, тут и должен быть глагол _несовершенного_ вида. С текущим переводом это одноразовая кнопка

2022-05-22 05:00 UTC, girafe969 commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +              content={s.scrubbing === 0 ? "Откачка" : "Вытяжка"}
Потому что это более понятно передает назначение режима

2022-05-22 05:27 UTC, girafe969 commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +          После смены настроек система автоматически начнёт цикл удаления загрязнений.
Не хочу делать там ревью для одного коммента. Наиболее понятная формулировка будет "начнет цикл Замены для фильтрации загрязнений". Так мы даём понять, что включится именно режим Замены, а не какой-то другой режим, который заменяет воздух и фильтрует загрязнения

2022-05-22 06:13 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_SIPHON	    = list("name"="Выкачка",            "desc"="Откачать воздух из помещения", "id" = AALARM_MODE_SIPHON),\
Это одно и то же. Этот режим работы тревоги включает Откачку на всех скрабберах. Поэтому и стоит оставить одно название

2022-05-22 06:14 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_SIPHON	    = list("name"="Выкачка",            "desc"="Откачать воздух из помещения", "id" = AALARM_MODE_SIPHON),\
Плюс у тебя есть Экстренная откачка, которая этот же режим, но с увеличенной дальностью на вытяжках

2022-05-22 11:20 UTC, girafe969 commented on code/game/machinery/alarm.dm
> +		AALARM_PRESET_HUMAN		= list("name"="Люди",     	 "desc"="Проверка содержания кислорода и азота", "id" = AALARM_PRESET_HUMAN),\
В следующей строчке нужно "содержание", так как газ один

2022-05-22 11:23 UTC, Ohar commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_SCRUBBING   = list("name"="Фильтрация",         "desc"="Выфильтровать загрязнения", "id" = AALARM_MODE_SCRUBBING),\
Режим — это описание того, в каком состоянии сейчас система

Вот идёт Откачка.
Вот включается Фильтрация
Вот включилась Экстренная откачка.

Мне так кажется более правильны

2022-05-22 11:24 UTC, Ohar commented on tgui/packages/tgui/interfaces/AirAlarm.js
> +              content={s.scrubbing === 0 ? "Откачка" : "Вытяжка"}
Понял о чём ты, спасибо

2022-05-22 11:50 UTC, Ohar commented on code/game/machinery/alarm.dm
> +		AALARM_MODE_SCRUBBING   = list("name"="Фильтрация",         "desc"="Выфильтровать загрязнения", "id" = AALARM_MODE_SCRUBBING),\
Поправил

2022-05-22 11:51 UTC, Ohar commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +	description = "Позволяет отключить предохранители на всех атмосферных панелях. После этого их можно будет переключить на режим «Потоп», отключающий вытяжки и проверку давления. \
Поправил