Я тоRPEDа. И кухню улучшите пожалуйста.
ss220-space/Paradise pull request #762
Opened 2022-04-11 04:24 UTC by Zipliks

## What Does This PR Do
Вместо `Rapid Part Exchange Device` будет `Rapid Part Exchange Device (RPED)`

## Why It's Good For The Game
У БРПЕДа есть аббревиатура, он легко ищется в протолате по `RPED`.
Почему бы не добавить и младшему брату?

## Images of changes
![image](https://user-images.githubusercontent.com/4831847/162664680-3db8dacc-adfd-428b-9cc1-96a13b15e34a.png)
## Changelog
:cl:
tweak: tweaked RPED name in Protolathe UI
/:cl:

2022-04-11 08:32 UTC, Ohar requested changes

2022-04-11 08:32 UTC, Ohar commented on code/modules/hydroponics/plant_genes.dm
> +	name = "Gaseous Decomposition"
А почему заглавные буквы?
```suggestion
	name = "gaseous decomposition"
```

2022-04-11 12:52 UTC, Zipliks commented on code/modules/hydroponics/plant_genes.dm
> +	name = "Gaseous Decomposition"
Этот PR уже добавили
#734

2022-04-12 16:18 UTC, Vallat approved these changes

2022-04-20 05:58 UTC, closed without merging