Обновление интерфейса Chem Dispenser (DO NOT MERGE)
ss220-space/Paradise pull request #763
Opened 2022-04-11 04:38 UTC by Zipliks

## What Does This PR Do
Обновление интерфейса химических раздатчиков

## Why It's Good For The Game
Очень душно вливать по 50u в бикеры на 300u. Теперь можно вливать по 100u.

## Images of changes
![image](https://user-images.githubusercontent.com/4831847/162665871-5b21e75b-8e05-45d6-a45c-89faadf58a87.png)

## Changelog
:cl:
add: Added 100u dispense amount to `chem_dispenser`
tweak: Tweaked labels content align. It's centered now
tweak: Tweaked base ui width to properly fit additional dispense amount
/:cl:

2022-04-11 08:32 UTC, Ohar requested changes

2022-04-11 08:32 UTC, Ohar commented on code/modules/hydroponics/plant_genes.dm
> +	name = "Gaseous Decomposition"
А почему заглавные буквы?

```suggestion
	name = "gaseous decomposition"
```

2022-04-12 08:18 UTC, Den109G commented on code/modules/hydroponics/plant_genes.dm
> +	name = "Gaseous Decomposition"
Так везде же заглавные буквы, только у газа строчные. ХМММ

2022-04-12 08:22 UTC, Den109G commented on code/modules/hydroponics/plant_genes.dm
> +	name = "Gaseous Decomposition"
И ПР вообще не про это.

2022-04-12 14:35 UTC, Zipliks commented on code/modules/hydroponics/plant_genes.dm
> +	name = "Gaseous Decomposition"
Буквы уже приняты в #734 
Этот коммит тут потому что я косипоша и не сквошнул

2022-04-12 16:19 UTC, Vallat approved these changes

2022-04-12 17:22 UTC, merged