Корректировка логики распределения урона (тестовая, не мержить)
ss220-space/Paradise pull request #775
Opened 2022-04-13 17:46 UTC by larentoun

## What Does This PR Do

Корректировка логики распределения урона по телу. На текущий момент, урон может быть поглощен мертвыми внутренними органами (которые уже не могут получать больше урона) или же просто быть потерян в поиске подходящего соседа для распределения урона.

На текущий момент логика такая.
Если конечность получает полный урон, она заносится в ЧС. Урон распределяется между парентом (вышестоящей конечности) и чайлдом (нижестоящей конечности).
Если правая рука получила максимальный урон, она переносит оставшийся урон либо в торс, либо в лапку. Если урон уходит в лапку, то урон уже не может вернуться через руку в сторону торса. Таким образом, весь урон, который был свыше здоровья лапки попросту пропадает. Если в правую руку прилетел снаряд на 50 урона, урон с правой руки ушел на правую лапку, а на правой руке и правой лапке уже нет здоровья, то кукла не получит урона, так как у урона нет соседа.

Этот ПР меняет логику таким образом, что конечность заносится в ЧС только в том случае, если она конечная (лапки/хвост/голова), или если парент-конечность не имеет здоровья.

## Why It's Good For The Game

Больше летальности оружия и фикс бага, который уменьшал вероятную летальность.
Теперь куклам не так безразлично на то, что ее избивают минуту, так как урон "терялся".

## Images of changes

https://www.youtube.com/watch?v=vO6b0qvtWfA

## Changelog
:cl:
fix: Корректировка логики распределения урона
/:cl:

2022-05-02 14:44 UTC, larentoun commented
Предложка прошла, код с багом который не решается.
Если делать все правильно, то оружие дальнего боя ломается

Если последний выстрел наносит максимальный урон по хуману в упор, то баллистическое оружие (с патронами любое) ломается, и оно не может стрелять, пока не поменять режим стрельбы или с харма с двух рук не выстрелить.

А в остальных случаях, все оружие дальнего боя перестает "видеть" куклу, и снаряды пролетают мимо куклы

2022-05-02 17:22 UTC, Suchinessa commented
Зачем ты добавил режим прицеливания на пару :Starege:

2022-07-04 06:49 UTC, larentoun commented
Обновлена логика распределения. Теперь конечность заносится в ЧС, если она конечна, или если все ее дети в ЧС.
Также, распределение не происходит, если все конечности в ЧС - это убирает баг, при котором дальнобойное оружие ломалось при правильной логике.

2022-07-04 06:51 UTC, larentoun commented
Предложка пройдена: https://discord.com/channels/617003227182792704/755125334097133628/967757339832766494

2022-07-04 07:52 UTC, Vallat requested changes

2022-07-04 07:52 UTC, Vallat commented on code/modules/surgery/organs/organ_external.dm
>  			if(forbidden_limbs.len)
```suggestion
			if(length(forbidden_limbs))
```

2022-07-04 07:52 UTC, Vallat commented on code/modules/surgery/organs/organ_external.dm
> +			if(forbidden_limbs?.len == owner?.bodyparts_by_name.len)
```suggestion
			if(owner && (length(forbidden_limbs) == length(owner.bodyparts_by_name)))
```

2022-07-04 07:52 UTC, Vallat commented on code/modules/surgery/organs/organ_external.dm
> +			if(!possible_points.len && parent)
```suggestion
			if(parent && !length(possible_points))
```

2022-07-04 07:52 UTC, Vallat commented on code/modules/surgery/organs/organ_external.dm
> +			if(possible_points.len && can_distribute)
```suggestion
			if(can_distribute && length(possible_points))
```

2022-07-04 08:40 UTC, Vallat approved these changes

2022-07-04 10:40 UTC, larentoun commented
Сдвинул проверку на перелом/внутреннее кровотечение до применения урона (ранее был вдвойне уменьшен порог для этого при получении урона).

Проверка на перелом/внутреннее кровотечение теперь учитывает берн урон тоже. Ранее, если конечность имела полностью берн урон, то она не могла получить перелом/внутреннее кровотечение

2022-07-04 11:07 UTC, Vallat approved these changes

2022-07-18 13:17 UTC, merged