Тайпан v1.1
ss220-space/Paradise pull request #786
Opened 2022-04-16 19:47 UTC by Furukia

## Changelog
:cl:Список изменений:cl:

* Добавлены уникальные спрайты кружки, рига и энергоручки оффкома. (Спрайты от Blundir)
* Добавлен пульт управления дверями для телекоммщика
* В код добавлена версия Ровера с предзагруженным вооружением:
	- Тесла реле
	- Защита от снарядов
	- Пулемёт
* Добавлен апгрейд для боргов заменяющий их РЦД на синдиверсию. Можно достать только в синди фабрикаторе
* Теперь телепортер на синдиастероиде больше нельзя разобрать и его защита стала слабее. Тайпановский остался прежним.
* В карго добавлено логирование админской кнопки add_money
* Исправлена цена за продажу семян
* Брифкейс с аплинка теперь стоит 5 тк.
* Грифски стал менее терпим к ворам.
* Удалены 3 майндслейва в пыточной.
* Добавлены три "Нейрализатора" заместо майндслейвов. Нейрализаторы при применении на человека стирают ему память и дают цель напоминающую о том, что он не помнит о синдикате, тайпане и т.д. Если его применить на тайпане. (Советую применять перед тем как будете выкидывать людей в телепорт обратно на станцию.)
* Добавлен СМЕС для подзарядки АПК турелей. Чтобы если на тайпане кончится свет, туррели ещё могли его защитить какое то время.
* Фикс повторяющегося кода и замена основной частоты телекоммщику на частоту тайпана от Den109G
* Теперь Офком и РД выделяются в чате при включённой настройке "Выделять командование" на телекомах

2022-04-16 21:25 UTC, Gaxeer requested changes

2022-04-16 21:25 UTC, Gaxeer commented on code/game/machinery/suit_storage_unit.dm
> +	suit_type   	 = /obj/item/clothing/suit/space/hardsuit/syndi/elite/comms
Убери пробелы лишние, пожалуйста. Касается и строк ниже. Переменная(пробел)=(пробел)значение

2022-04-16 21:25 UTC, Gaxeer commented on code/game/objects/items/devices/memorizer.dm
> +					M.visible_message("<span class='disarm'>[M] gasps and shields [M.p_their()] eyes!</span>", "<span class='userdanger'>You gasp and shield your eyes!</span>")
Всё что было написано выше - на русском языуке. Я думаю это, и всё что написано ниже тоже стоит перевести

2022-04-16 21:25 UTC, Gaxeer commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/item/borg/upgrade/syndie_rcd
Раз пошла такая пьянка на перевод, то почему бы и тут не перевести?

2022-04-16 21:25 UTC, Gaxeer commented on code/game/objects/items/weapons/RCD.dm
> +	if(!borg_rcd)
Я не привык видеть такие конструкции в коде станции. По этому я бы переписал это таким образом:
```
if(!borg_rcd)
   if(matter < amount)
      return FALSE
   matter -= amount
   SStgui.update_uis(src)
   return TRUE

if(!isrobot(user))
   return FALSE

var/mob/living/silicon/robot/R = user
return R.cell.use(amount * power_use_multiplier)
```

2022-04-16 21:25 UTC, Gaxeer commented on code/game/objects/items/weapons/RCD.dm
> +	if(!borg_rcd)
То же самое

2022-04-16 21:25 UTC, Gaxeer commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +
убери пустую строку и замени 1 и 0 на TRUE и FALSE соответственно

2022-04-16 22:59 UTC, Furukia commented on code/game/machinery/suit_storage_unit.dm
> +	suit_type   	 = /obj/item/clothing/suit/space/hardsuit/syndi/elite/comms
Там сверху целая куча "лишних пробелов" в других хранилищах. По факту не вижу проблемы в них. Ну да ладно мне не сложно.

2022-04-16 23:06 UTC, Furukia commented on code/game/objects/items/devices/memorizer.dm
> +					M.visible_message("<span class='disarm'>[M] gasps and shields [M.p_their()] eyes!</span>", "<span class='userdanger'>You gasp and shield your eyes!</span>")
ок.

2022-04-16 23:08 UTC, Furukia commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/item/borg/upgrade/syndie_rcd
Потому что тогда по хорошему надо и другие платы переводить? Ибо одна плата апгрейда на русском, пока другая на английском, это такое себе?

2022-04-16 23:13 UTC, Furukia commented on code/game/objects/items/weapons/RCD.dm
> +	if(!borg_rcd)
Принято. Не сразу поняла зачем переделал. Потом дошло XD

2022-04-16 23:13 UTC, Furukia commented on code/game/objects/items/weapons/RCD.dm
> +	if(!borg_rcd)
Принято.

2022-04-16 23:15 UTC, Furukia commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +
Ок.

2022-04-17 06:26 UTC, Vallat requested changes

2022-04-17 06:26 UTC, Vallat commented on code/game/objects/items/devices/memorizer.dm
> +				overlays += "overcharge"
```suggestion
	if(!can_overcharge)
		return
	if(istype(W, /obj/item/screwdriver))
		battery_panel = !battery_panel 
		if(battery_panel)
			to_chat(user, "<span class='notice'>You open the battery compartment on the [src].</span>")
		else
			to_chat(user, "<span class='notice'>You close the battery compartment on the [src].</span>")
	else if(istype(W, /obj/item/stock_parts/cell))
		if(!battery_panel || overcharged)
			return
		to_chat(user, "<span class='notice'>You jam the cell into battery compartment on the [src].</span>")
		qdel(W)
		overcharged = TRUE
		overlays += "overcharge"
```

2022-04-17 06:26 UTC, Vallat commented on code/game/objects/items/devices/memorizer.dm
> +		times_used--
Подробнее объясни этот код. Здесь либо не нужен цикл, либо ему нужны слипы. Что вообще в целом это функция должна делать?

2022-04-17 06:26 UTC, Vallat commented on code/game/objects/items/devices/memorizer.dm
> +/obj/item/memorizer/proc/memorize_carbon(var/mob/living/carbon/M, var/mob/user = null, var/power = 5, targeted = 1)
```suggestion
/obj/item/memorizer/proc/memorize_carbon(mob/living/carbon/M, mob/user = null, power = 5, targeted = TRUE)
```

2022-04-17 06:26 UTC, Vallat commented on code/game/objects/items/devices/memorizer.dm
> +/obj/item/memorizer/proc/memorize_carbon(var/mob/living/carbon/M, var/mob/user = null, var/power = 5, targeted = 1)
Кто такой этот `M`? Почему нет проверки на этот `M`? Добавь в начало функции этот код, соответственно убрав отступы у всего что идёт после `if(user)`
```
if(!user || !M) // M заменить
	return
```

2022-04-17 06:26 UTC, Vallat commented on code/game/objects/items/devices/memorizer.dm
> +/obj/item/memorizer/syndicate/memorize_carbon(var/mob/living/carbon/M, var/mob/user = null, var/power = 5, targeted = 1)
Тоже самое и для этой функции

2022-04-17 06:26 UTC, Vallat commented on code/game/objects/items/robot/robot_upgrades.dm
> +	var/obj/item/rcd/borg/T = locate() in R.module.modules
Назови переменную нормально, пожалуйста. Хотя бы `borg_rcd`

2022-04-17 06:26 UTC, Vallat commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +	if(slot_item && istype(slot_item, /obj/item/reagent_containers/food/drinks/mug/comms))
```suggestion
/mob/living/simple_animal/bot/secbot/griefsky/syndicate/proc/check_for_mug(obj/item/slot_item)
	if(istype(slot_item, /obj/item/reagent_containers/food/drinks/mug/comms))
```

2022-04-19 06:32 UTC, Vallat requested changes
Заменить название переменной `Mob` на более читаемое, в дискорде всё расписал.

2022-04-23 14:50 UTC, Bizzonium commented
Конфликт появился

2022-04-23 15:39 UTC, Furukia commented
> Конфликт появился

Щас гляну и поправлю.

2022-04-23 15:47 UTC, Furukia commented
> Конфликт появился

Можешь мёрджить картинки и мои и чужие в файлике учтены.

2022-04-23 15:52 UTC, merged