Update Nuke Ops
ss220-space/Paradise pull request #788
Opened 2022-04-16 21:42 UTC by captainnelly

## What Does This PR Do
Крупная обнова для ядерных оперативников, ченжлоги длинные.

## Why It's Good For The Game
Предложка и ченджлоги - > https://discord.com/channels/617003227182792704/755125334097133628/963347566836191242

## Changelog
:cl:
add: NEW at nukies uplink: Rover, explosive sniper ammo, rebalanced medic kit, deagle, uzi, new ammo bags.
tweak: Balanced a lot of items cost at nuke uplink.
/:cl:

2022-04-16 21:42 UTC, captainnelly commented
ПОКА НЕ МЕРДЖИТЬ, НАДО КОЕ-ЧТО ПОДПРАВИТЬ

2022-04-16 21:52 UTC, captainnelly commented
Можно мерджить НО только после мерджа обновы от Фурукаи

2022-04-16 22:22 UTC, Den109G commented
![IMG_20220417_002031](https://user-images.githubusercontent.com/87372121/163693059-c4ba88e2-84ff-4b6a-ad20-ae7bffce6750.jpg)
firstaid/syndie
Тут разве нужно два (src)?

2022-04-16 22:26 UTC, captainnelly commented
> ![IMG_20220417_002031](https://user-images.githubusercontent.com/87372121/163693059-c4ba88e2-84ff-4b6a-ad20-ae7bffce6750.jpg) firstaid/syndie Тут разве нужно два (src)?

Исправил

2022-04-17 06:31 UTC, Vallat requested changes
Ручной дефибрилятор синдиката следует наследовать от уже существующего ручного дефибрилятора это раз. Два - изменения, которые я отметил через гитхаб.

2022-04-17 06:31 UTC, Vallat commented on code/game/objects/items/weapons/storage/backpack.dm
> +	..()
```suggestion
/obj/item/storage/backpack/duffel/syndie/ammo/lmg/Initialize()
	. = ..()
```

2022-04-17 06:31 UTC, Vallat commented on code/game/objects/items/weapons/storage/backpack.dm
> +	..()
```suggestion
/obj/item/storage/backpack/duffel/syndie/ammo/carbine/Initialize()
	. = ..()
	new /obj/item/ammo_box/a40mm(src)
```

2022-04-17 06:31 UTC, Vallat commented on code/game/objects/items/weapons/storage/backpack.dm
> +	..()
```suggestion
/obj/item/storage/backpack/duffel/syndie/ammo/uzi/Initialize()
	. = ..()
```

2022-04-17 06:31 UTC, Vallat commented on code/game/objects/items/weapons/storage/firstaid.dm
> +	..()
```suggestion
/obj/item/storage/firstaid/syndie/Initialize()
	. = ..()
```

2022-04-17 06:31 UTC, Vallat commented on code/modules/projectiles/guns/projectile/sniper.dm
> +/obj/item/projectile/bullet/sniper/explosive/on_hit(var/atom/target, blocked = 0, hit_zone)
```suggestion
/obj/item/projectile/bullet/sniper/explosive/on_hit(atom/target, blocked = 0, hit_zone)
```

2022-04-24 01:38 UTC, closed without merging