Охладитель/Нагреватель: перевод интерфейса
ss220-space/Paradise pull request #789
Opened 2022-04-16 21:57 UTC by Ohar

## Changelog
:cl:
tweak: Перевод интерфейса охладителя (GasFreezer)
/:cl:

## Скриншоты
![изображение](https://user-images.githubusercontent.com/3854741/162643417-8025c8c4-82d0-4a81-bd3e-65cd6feef79a.png)
![изображение](https://user-images.githubusercontent.com/3854741/162643424-d52d284f-7398-47a3-97c9-e2f1325364b5.png)

2022-04-17 06:33 UTC, Vallat approved these changes

2022-04-19 06:45 UTC, girafe969 requested changes
Хватит пихать всё подряд в ПРы

2022-04-19 06:45 UTC, girafe969 commented on code/game/machinery/Freezer.dm
> +		ui = new(user, src, ui_key, "GasFreezer", "Газонагревная система", 560, 200)
Газонагревательная. Холодильник же Газоохладительная, а не Газоохладная

2022-04-19 06:45 UTC, girafe969 commented on tgui/docs/tutorial-and-examples.md
> +            <LabeledList.Item label="Здоровье">
Что это и что это тут забыло?

2022-04-19 10:52 UTC, Ohar commented on code/game/machinery/Freezer.dm
> +		ui = new(user, src, ui_key, "GasFreezer", "Газонагревная система", 560, 200)
@girafe969 Нет, их две, обе делаются из одной платы. 
Одна — охладительная, вторая — нагревательная.

2022-04-19 10:53 UTC, Ohar commented on tgui/docs/tutorial-and-examples.md
> +            <LabeledList.Item label="Здоровье">
Косяк, исправил
```suggestion
            <LabeledList.Item label="Health">
```

2022-04-19 10:57 UTC, girafe969 commented on code/game/machinery/Freezer.dm
> +		ui = new(user, src, ui_key, "GasFreezer", "Газонагревная система", 560, 200)
Нагревательная, а у тебя нагревная

2022-04-19 11:00 UTC, Ohar commented on tgui/docs/tutorial-and-examples.md
> +        <LabeledList.Item label="Здоровье">
Правка ошибки
```suggestion
        <LabeledList.Item label="Health">
```

2022-04-19 11:01 UTC, Ohar commented on tgui/docs/tutorial-and-examples.md
> +            <LabeledList.Item label="Здоровье">
Правка ошибки
```suggestion
            <LabeledList.Item label="Health">
```

2022-04-19 11:03 UTC, Ohar commented on code/game/machinery/Freezer.dm
> +		ui = new(user, src, ui_key, "GasFreezer", "Газонагревная система", 560, 200)
```suggestion
		ui = new(user, src, ui_key, "GasFreezer", "Газонагревательная система", 560, 200)
```

2022-04-19 11:21 UTC, girafe969 approved these changes
Хорошая работа

2022-04-23 14:48 UTC, merged