Обезглавливание кидан
ss220-space/Paradise pull request #791
Opened 2022-04-17 16:21 UTC by LiquidPotroh

## What Does This PR Do
-Теперь обезглавливание кидан не смертельно. 
-Мозг перемещён в грудь. 
-При обезглавливании на цель накладываются эффекты слепоты, молчания, дезориентации и замедления, а так же наносится 60 урона мозгу. 
-Замена эмоутов, связанных с головой на другие. 

## Why It's Good For The Game
Уже прошло предложку: https://discord.com/channels/617003227182792704/755125334097133628/961708837210046534

## Видосик с демонстрацией
https://www.youtube.com/watch?v=u6n19MsEbaI

2022-04-17 16:34 UTC, LiquidPotroh commented
Первый раз залез в код пары, так что просьба тщательно проверить, что я всё не сломал

2022-04-18 01:41 UTC, Ohar commented on code/modules/mob/living/carbon/human/emote.dm
Зачем `m_type = 2` в обоих случаях?
Думаю, его стоит вынести вовне `if`

2022-04-18 01:43 UTC, Ohar requested changes
Нагавнякал замечание

2022-04-28 01:26 UTC, LiquidPotroh commented
Нашёл баг: при попытке присоединить другую голову с мозгом оперируемый умирает, а тот, чья голова присоединялась улетает в какой то астрал и получает черный экран без интерфейса. Наверно надо запретить присоединять киданам некиданскую голову, как это сделано у кпб. В общем, просьба не мерджить, пока не разберусь.

2022-04-28 12:46 UTC, LiquidPotroh commented
Пофиксил

2022-05-09 01:34 UTC, LiquidPotroh commented
@Bizzonium пр уже как 3 недели готов

2022-05-09 13:05 UTC, merged