Крематорий теперь корректно сжигает предметы
ss220-space/Paradise pull request #796
Opened 2022-04-20 06:41 UTC by Zipliks

## What Does This PR Do
Исправляет работу крематория церкви. Теперь адская печка адски сжигает всё внутри себя, вместе с мешком.
Раньше выплёвывал предметы наружу, т.к. мешок уничтожался и срабатывал `dump_content()`
А иногда и мешок не уничтожался.

## Why It's Good For The Game
Мешки для трупов и бумагу делали из жаростойкой ткани, собираемой с жопы огнеупорного осла на планете Негоритья. Теперь ослы кончились, крематорий сжигает всё, что попало внутрь, включая труп, мешок, осла, клоуна, капитана, мима, НТР, весь ЦК и код парадайза.

## Changelog
:cl: Luger
fix: fixed crematorium didn't delete items inside
/:cl:

2022-04-20 06:44 UTC, Vallat approved these changes

2022-04-24 17:34 UTC, Gaxeer requested changes

2022-04-24 17:34 UTC, Gaxeer commented on code/__DEFINES/span.dm
> +#define span_hear(str) ("<span class='hear'>" + str + "</span>")
насколько я знаю, дефайны принятно писать капсом SPAN_HEAR, ну или же можно просто HEAR, WARNING, ALERT. Но со спаном думаю лучше. SPAN_HEAR, SPAN_WARNING, SPAN_ALERT

2022-04-24 17:34 UTC, Gaxeer commented on code/game/atoms.dm
> +	var/flags_1 = NONE
почему _1?

2022-04-24 17:34 UTC, Gaxeer commented on code/game/objects/structures/morgue.dm
> +			if(entity == null)
if (!entity)

2022-04-24 17:34 UTC, Gaxeer commented on code/game/objects/structures/morgue.dm
> +			if(entity)
можно сделать else блок после

2022-04-24 17:34 UTC, Gaxeer commented on code/game/objects/structures/morgue.dm
>  		var/mob/living/C = src
я думаю стоит C заменить на creature? Или что тут имелось ввиду

2022-04-24 17:40 UTC, Zipliks commented on code/__DEFINES/span.dm
> +#define span_hear(str) ("<span class='hear'>" + str + "</span>")
Справебыдло, прост спаны в голове не как дефайны ощущались

2022-04-24 17:42 UTC, Zipliks commented on code/game/atoms.dm
> +	var/flags_1 = NONE
var/flags = NONE уже есть
Не уверен создаст ли это излишние конфликты или UB moments

2022-04-24 17:43 UTC, Zipliks commented on code/game/objects/structures/morgue.dm
> +			if(entity == null)
Строго говоря, я занимался только крематорием, весь остальной код меня мало интересовал. Поверхностый рефакторинг произошёл по причине "сука, как это читать".

2022-04-24 17:44 UTC, Zipliks commented on code/game/objects/structures/morgue.dm
> +			if(entity)
Причина та же, я не трогал эти куски кода, но могу и потрогать

2022-04-25 11:18 UTC, Vallat requested changes

2022-04-25 11:18 UTC, Vallat commented on code/game/atoms.dm
> +	var/flags_1 = NONE
Удалить, ты его нигде не используешь

2022-04-25 11:18 UTC, Vallat commented on code/__HELPERS/atoms.dm
> +		if(checked_atom.flags_1 & ignore_flag_1)
Обычный flags используй, либо удаляй ваще проверку на игнор флага. Не используется нигде

2022-04-25 11:18 UTC, Vallat commented on code/game/objects/structures/morgue.dm
> +			if(entity)
Нельзя тут else блок использовать

2022-04-25 11:18 UTC, Vallat commented on code/game/objects/structures/morgue.dm
> +		return
Насрано ретёрнами, они бесполезны, убери

2022-04-26 16:50 UTC, Vallat approved these changes

2022-05-06 17:00 UTC, Gaxeer requested changes

2022-05-06 17:03 UTC, Gaxeer commented on code/game/objects/structures/morgue.dm
> +	var/list/morgue_mob         = get_all_contents_type(/mob/living)
```suggestion
	var/list/morgue_content = get_all_contents() - src - connected
	var/list/morgue_mob = get_all_contents_type(/mob/living)
```

2022-05-06 17:06 UTC, Gaxeer approved these changes

2022-05-07 16:34 UTC, merged