Локализация уведомлений об освещении.
ss220-space/Paradise pull request #816
Opened 2022-04-26 11:19 UTC by MHSPlay

## What Does This PR Do

Локализирует уведомления об освещении.

## Why It's Good For The Game

Проще в понимании, о чём идёт речь.

## Images of changes

![image](https://user-images.githubusercontent.com/41786546/165287158-0119bc9e-c25b-49fa-8522-26a65a97d1bb.png)
![image](https://user-images.githubusercontent.com/41786546/165287249-9573eb47-b51a-40f3-ab99-575d07483881.png)
![image](https://user-images.githubusercontent.com/41786546/165288353-b411c1da-7c2e-4eab-b4b3-1dee11bc2a61.png)

## Changelog
:cl:
tweak: Локализация уведомлений об освещении.
/:cl:

2022-04-26 19:33 UTC, Ohar requested changes
Немного поправил формулировки

2022-04-26 19:33 UTC, Ohar commented on code/controllers/subsystem/nightshift.dm
> +	GLOB.priority_announcement.Announce(message, new_sound = 'sound/misc/notice2.ogg', new_title = "Автоматическое Объявление Системы Освещения")
На русском в заголовках начальные буквы слов не капитализируются
```suggestion
	GLOB.priority_announcement.Announce(message, new_sound = 'sound/misc/notice2.ogg', new_title = "Автоматическое оповещение системы освещения")
```

2022-04-26 19:33 UTC, Ohar commented on code/controllers/subsystem/nightshift.dm
> +				announce("Восстановление конфигурации ночного освещения к нормальной работе.")
```suggestion
				announce("Система ночного освещения снова работает в штатном режиме.")
```

2022-04-26 19:33 UTC, Ohar commented on code/controllers/subsystem/nightshift.dm
> +				announce("Отключение ночного освещения: Станция находится в чрезвычайном положении.")
Вики использует [формулировку «чрезвычайная ситуация»](https://wiki.ss220.space/index.php/Космический_Закон#Чрезвычайные_ситуации)
```suggestion
				announce("Система ночного освещения отключена: на станции чрезвычайная ситуация.")
```

2022-04-26 19:33 UTC, Ohar commented on code/controllers/subsystem/nightshift.dm
> +			announce("Доброе утро, экипаж. Поскольку сейчас дневное время, освещение на борту станции переведено в дневной режим.")
Старайся сохранять единообразие формулировок
```suggestion
			announce("Доброе утро, экипаж. В связи с наступлением дневного времени освещение на борту станции переведено в дневной режим.")
```

2022-04-26 19:33 UTC, Ohar commented on code/controllers/subsystem/nightshift.dm
> +			announce("Добрый вечер, экипаж. Для снижения энергопотребления и стимуляции циркадных ритмов некоторых видов, освещение на борту станции переведено в ночной режим.")
Запятая лишняя
```suggestion
			announce("Добрый вечер, экипаж. Для снижения энергопотребления и стимуляции циркадных ритмов некоторых видов освещение на борту станции переведено в ночной режим.")
```

2022-04-27 01:18 UTC, Ohar approved these changes

2022-04-28 05:31 UTC, Vallat approved these changes

2022-05-02 13:56 UTC, merged