Add: new items for blueshield closet
ss220-space/Paradise pull request #830
Opened 2022-04-28 12:37 UTC by captainnelly

## What Does This PR Do
Добавляет 3 новых предмета одежды в ящик блюшилда.

## Why It's Good For The Game
Предложка -> https://discord.com/channels/617003227182792704/755125334097133628/968516214613766195

## Changelog
:cl:
add: 3 new items for blueshield closet.
/:cl:

2022-04-28 12:44 UTC, Vallat approved these changes

2022-04-29 08:42 UTC, TrashDoxx requested changes

2022-04-29 08:42 UTC, TrashDoxx commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/clothing/mask/gas/sechailer(src)
```suggestion
	new /obj/item/clothing/mask/gas/sechailer(src)

```

2022-04-30 20:29 UTC, captainnelly commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/clothing/mask/gas/sechailer(src)
зачем?

2022-05-04 17:50 UTC, TrashDoxx commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/clothing/mask/gas/sechailer(src)
У тебя код слипся.

2022-05-04 21:33 UTC, captainnelly commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/clothing/mask/gas/sechailer(src)
А, вижу. Пофиксил

2022-05-04 21:39 UTC, TrashDoxx approved these changes

2022-05-07 16:51 UTC, merged