feat: Плащи, мантии и слот для шеи
ss220-space/Paradise pull request #833
Opened 2022-04-28 21:49 UTC by dj-34

_Это пересоздание полугодовалого PR'а._

### Что делает этот PR
Этот PR добавляет слот "Шея" для персонажа, соответственно, на шею в данный момент можно нацепить:

- [ ]  Плащи, мантии, шали
- [ ]  Покрывала, простыни
- [ ]  Цепочки, ожерелья

Также вышеперечисленные предметы вы можете выбрать в Лодаутах (Setup Character > Loadouts).

**Примеры на скриншотах ниже:**

![image](https://user-images.githubusercontent.com/20109643/165852020-692fff28-2233-4a92-897b-860f0b4c672c.png)
![image](https://user-images.githubusercontent.com/20109643/165852048-568c70aa-48f0-4fca-b8c1-3c72813b1a63.png)
![image](https://user-images.githubusercontent.com/20109643/165852065-086cb488-b8c3-4cd8-a924-e1851189c737.png)

## Changelog
:cl:
[Порт плащей + слота шеи](https://github.com/ss220-space/Paradise/commit/d3842c487fac8473a048260aaa4f53931f7104fc)
[Мелкие изменения](https://github.com/ss220-space/Paradise/commit/33e64c994b8d90406c8d8956938d437b237d91ee)
/:cl:

2022-04-30 06:45 UTC, Vallat requested changes

2022-04-30 06:45 UTC, Vallat commented on code/modules/clothing/neck/cloaks.dm
> +	usr.update_inv_neck()
```suggestion
/obj/item/clothing/neck/toggle/attack_self(mob/user)
	if(icon_state == initial(icon_state))
		icon_state = icon_state + "_t"
		item_state = icon_state + "_t"
	else
		icon_state = initial(icon_state)
		item_state = initial(item_state)
	user.update_inv_neck()
```

2022-04-30 14:55 UTC, Vallat approved these changes

2022-05-02 18:43 UTC, dj-34 commented
Прошло голосовалку
https://discord.com/channels/617003227182792704/755125334097133628/970753539250999356

2022-05-07 17:08 UTC, dj-34 commented
@Bizzonium Конфликт решён.

2022-05-08 18:59 UTC, merged