Fix: Spell now checks phasing or user in rod
ss220-space/Paradise pull request #837
Opened 2022-04-30 15:47 UTC by BeebBeebBoob

## What Does This PR Do

Устраняет баг когда маг мог стать богом внутри rod и на своё пожелание выйти. Теперь нельзя использовать заклинания когда в ethernal jaunt или rod. 
И ещё мелкие коды-фиксы в синди-карго.

## Why It's Good For The Game

Меньше багоюзов. И багов.

## Changelog
:cl:
Fix: Spell now checks phasing or user in rod. Also minor code-fix in syndie base.
/:cl:

2022-04-30 18:22 UTC, Vallat approved these changes

2022-05-02 13:28 UTC, TrashDoxx commented
Раздели коммиты.

2022-05-02 13:30 UTC, TrashDoxx requested changes
Раздели коммит на две части. Никакой пользы от того, что ты всё в кучу сложил.

2022-05-02 16:44 UTC, closed without merging

2022-05-02 16:44 UTC, BeebBeebBoob commented
переделаю ыыыы