Add: RD hardsuit
ss220-space/Paradise pull request #838
Opened 2022-04-30 21:06 UTC by captainnelly

## What Does This PR Do
Добавляет в кабинет РД риг РД.
ВАЖНО. МЕРДЖИТЬ ПОСЛЕ -> https://github.com/ss220-space/Paradise/pull/812 ВО ИЗБЕЖАНИЕ КОНФЛИКТОВ.
## Why It's Good For The Game
Предложка - > https://discord.com/channels/617003227182792704/755125334097133628/970039661344989267

## Changelog
:cl:
add: New hardusit for RD to his office.
/:cl:

2022-05-02 06:18 UTC, Vallat reviewed
Вижу функцию `sense_explosion`, вижу смысл её применения, не вижу, собственно, самого применения. Либо доделывай этой, либо удаляй эту фичу в принципе.

2022-05-02 12:09 UTC, captainnelly commented
> Вижу функцию `sense_explosion`, вижу смысл её применения, не вижу, собственно, самого применения. Либо доделывай этой, либо удаляй эту фичу в принципе.

Она определяет взрывы и выводит на экран информацию о взрывах, если шлем одет. В игре я проверял и это работает

2022-05-02 12:10 UTC, captainnelly commented
> Вижу функцию `sense_explosion`, вижу смысл её применения, не вижу, собственно, самого применения. Либо доделывай этой, либо удаляй эту фичу в принципе.

И да, код спизжен с оффов практически полностью, только конфликты пофиксил

2022-05-02 13:04 UTC, Vallat commented
Я в твоем коде нигде не вижу вызова этой функции, как оно может работать, если оно не вызывается?

2022-05-02 15:19 UTC, captainnelly commented
Все обновил и проверил 🤡

2022-05-02 15:42 UTC, captainnelly commented
> Все обновил и проверил 🤡

Наебал

2022-05-02 15:46 UTC, Vallat requested changes
У нас принят кодстиль snake_case, соблюдай его

2022-05-02 15:46 UTC, Vallat commented on code/game/objects/explosion.dm
> +				Helm_Array.sense_explosion(x0,y0,z0,devastation_range,heavy_impact_range,light_impact_range,took,orig_dev_range,orig_heavy_range,orig_light_range)
```suggestion
				var/obj/item/clothing/head/helmet/space/hardsuit/rd/helm_array = array
				helm_array.sense_explosion(x0,y0,z0,devastation_range,heavy_impact_range,light_impact_range,took,orig_dev_range,orig_heavy_range,orig_light_range)
```

2022-05-02 15:46 UTC, Vallat commented on code/game/objects/explosion.dm
>  				Array.sense_explosion(x0,y0,z0,devastation_range,heavy_impact_range,light_impact_range,took,orig_dev_range,orig_heavy_range,orig_light_range)
```suggestion
				var/obj/machinery/doppler_array/doppler_array = array
				doppler_array.sense_explosion(x0,y0,z0,devastation_range,heavy_impact_range,light_impact_range,took,orig_dev_range,orig_heavy_range,orig_light_range)
```

2022-05-02 15:48 UTC, captainnelly commented
👌

2022-05-02 15:49 UTC, Vallat approved these changes

2022-05-19 16:25 UTC, Bizzonium commented
![image](https://user-images.githubusercontent.com/8555356/169350429-2434760f-a8e9-4b96-9f22-45c9e64e242f.png)

2022-06-05 14:14 UTC, closed without merging