feat: added search input for equipments in uplink
ss220-space/Paradise pull request #848
Opened 2022-05-04 18:25 UTC by TheKekMan

## What Does This PR Do
Добавил поиск в аплинке

## Images of changes
[
](https://cdn.discordapp.com/attachments/734823601110515882/971469428615184434/2022-05-04_20-51-50.mp4)

## Changelog
:cl:
add: Added search input for equipment in uplink
/:cl:

2022-05-05 22:21 UTC, Ohar requested changes

2022-05-05 22:21 UTC, Ohar commented on tgui/packages/tgui/interfaces/Uplink.js
> +      sortBy(item => item.name),
Если в 102 строке проверяешь наличие `item`, то и тут, наверное, надо?
```suggestion
      sortBy(item => item?.name),
```

2022-05-05 22:21 UTC, Ohar commented on tgui/packages/tgui/interfaces/Uplink.js
> +          .map(item => item.items.map(item => item))
В чём смысл мапить `item.items.map(item => item)` на самого себя?

2022-05-05 22:21 UTC, Ohar commented on tgui/packages/tgui/interfaces/Uplink.js
> +        placeholder="Search equipment"
Вроде бы `Find` уместнее, нет?
```suggestion
        placeholder="Find equipment"
```

2022-05-05 22:24 UTC, TheKekMan commented on tgui/packages/tgui/interfaces/Uplink.js
> +        placeholder="Search equipment"
Ну не знаю, во второй вкладке серч использовался

2022-05-05 22:25 UTC, TheKekMan commented on tgui/packages/tgui/interfaces/Uplink.js
> +          .map(item => item.items.map(item => item))
Я же смапил item.items

2022-05-05 22:27 UTC, TheKekMan commented on tgui/packages/tgui/interfaces/Uplink.js
> +      sortBy(item => item.name),
Честно, это я скопипастил с блока ниже. Там оказывается была готовая реализация поиска. Можно и добавить

2022-05-05 23:05 UTC, Ohar approved these changes

2022-05-07 16:14 UTC, Bizzonium commented
А почему yarn.lock изменился?

2022-05-07 16:29 UTC, merged