Перевод Боевых искусств, броски. Дополнения фраз, описаний и пьяных драк.
ss220-space/Paradise pull request #875
Opened 2022-05-10 10:48 UTC by PhantornRU

## What Does This PR Do
Боевые искусства:
- Переведены боевые искусства: Спящий Карп, Борьба(Реслинг с борцовским поясом), Бокс, Пьяные Драки, CQC, Крав Мага, Мимдзютсу, Плазменный Кулак, Синтдзютсу (Боевой Модуль IPC), Путь -Танцующего Админа
- Переведены удары бо посохом
- Корректные именные наименования при изучении боевых искусств через мануалы и свитки, а также при использовании бо посоха
- Категория Боевые Искусства теперь русифицирована
- Переведена помощь для каждого из боевых искусств (кроме наименований интентов, для удобств)
- Увеличен словарный запас фраз боевого искусства Спящего Карпа
- Дополнены текстовые описания ударов CQC
- Дополнены текстовые описание ударов крав мага
- Дополнены текстовые описание ударов боксирования, борьбы и драк
- Логирование и дебаг не переведены для удобства администрации и разработчиков.
- Добавлены дополнительные описания ударов боевых искусств.

Драки:
- Переведены общие удары, обезоруживание, захваты.
- Дополнены описания общих ударов, укусов.
- Переведены удары разных рас, укусы, уколы.
- Добавлены дополнительные текстовые удары при драках
- Добавлены расширенные удары и приемы при пьяных драках (случайны и зависят от удачи)
- Пьяные драки мутят вам желудок. Хорошо покушайте перед показыванием мастерства, если драка будет долгой.
- Добавлены разнообразные шансы на нанесение дополнительного урона в пьяных драках (а также на его отсутствие), а также бафы/дебафы от использования приемов
- Добавлено пьяное мастерство при пьяных драках которое с некоторыми шансами способно равноценно нанести урон по стамине и дыхалке оппоненту и пьяному мастеру.
- Перевод ударов карбонных ксеносов

Species/Mob/Carbon:
- Переведены описания действий трейта пацифизма
- Переведены некоторые действия и укусы вампира, укусы цели с отсутствием крови
- Перевод проверки прикрепления на комбинезон
- Перевод экипирования предметов
- Перевод [РОСКОМНАДЗОР] действий при прописывании команды /suicide для всех игровых рас (да, даже для скелетов и армалисов)
- Перевод фраз и описаний IPC, в том числе смерти.
- Перевод текстовых описаний возгораний плазмамена, а также акцент речи с заменой "с"/"ш" на "шш"
- Перевод текстовых описаний урона тенелинга
- Перевод тектовых описаний слайма и его восстановительных процессов
- Перевод текстовых описаний врина, его укалывание жалом, отрывание антены 
- Перевод блевания и рвоты (теперь намордник задерживает вашу рвоту в вас)
- Перевод связывание ног/рук
- Зачем-то переведены удары кенгуру
- Попутно с кенгуру переведен паук-сб Сержант Аранеус
- Переведены броски и опускания на землю.
- Переведена атака блоба вне скриптовых папок с блобом.
- Переведены удары током
- Перевод встрясок лежачего + лежачего ССД
- Перевод состояния лечь/встать
- Перевод тушения руками
- Перевод поглаживаний по голове
- Перевод и дополнение текстового описания объятий
- Перевод повреждений, застревающих объектов
- Перевод состояния куклы
- Перевод ползаний по вентиляции
- Перевод подскальзывания
- Перевод кубов и броска кубов (Зачем переведено? Ну... У него были броски... Кубик судьбы требует жертвоприношений и перевода)
- Переведена сердечно-легочная реанимация

## Why It's Good For The Game
Более лучшее и красочное описание действий в чате словно ты играешь в настолку

## Images of changes

![image](https://user-images.githubusercontent.com/41479614/167611890-5545850d-2da8-4db5-acf6-dd1bf40908db.png)

2022-05-10 12:52 UTC, dj-34 reviewed
1. Не понятно почему усики Вринов называются "антентой"?
2. Стоит ли переводить название предметов?
3. Следует еще раз проверить весь текст, ибо я мог пропустить логические и граматические ошибки.
4. В чем надобность переименовывать [src] в [src.name]?

2022-05-10 12:52 UTC, dj-34 commented on code/game/atoms_movable.dm
> +			visible_message("<span class='warning'>[src] слегка схватил [M]!</span>")
"Слегка" выглядит вообще не к месту
```suggestion
			visible_message("<span class='warning'>[src] схватил [M]!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/game/atoms_movable.dm
> +			to_chat(user, "<span class='warning'>[src.name] слишком тяжелый чтобы тащить!</span>")
Как вариант
```suggestion
			to_chat(user, "<span class='warning'>[src.name] слишком тяжелый!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/game/objects/items/weapons/dice.dm
> +	name = "Мешок игральных костей"
Стоит ли переводить названия предметов?

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/adminfu.dm
> +		D.visible_message("<span class='warning'>[A] демонстрирует большой светящийся ящик с инструментами и пихает его в [D] грудь!</span>", \
```suggestion
		D.visible_message("<span class='warning'>[A] демонстрирует большой светящийся ящик с инструментами и пихает его в грудь [D]!</span>", \
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/combos/cqc/consecutive.dm
> +		target.visible_message("<span class='warning'>[user] последовательно бьет [target] в живот, шею и спину !</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] последовательно бьет [target] в живот, шею и спину!</span>", \
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/combos/cqc/kick.dm
> +	explaination_text = "Пинает оппонента. Отключает сознание у лежачего оппонента, отшвыривая его."
```suggestion
	explaination_text = "Сбивает с ног оппонента. Нокаутирует лежачего оппонента, отшвыривая его."
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/combos/cqc/slam.dm
> +	explaination_text = "Бросьте противника на землю, сбивая его с ног."
```suggestion
	explaination_text = "Бросает оппонента на землю, сбивая его с ног."
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/combos/krav_maga/leg_sweep.dm
> +	explaination_text = "Выбивает ноги жертвы, в результате чего она падает и не может двигаться в течении короткого времени."
```suggestion
	explaination_text = "Сбивает с ног жертву, в результате чего она падает и не может двигаться в течении короткого времени."
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/combos/plasma_fist/tornado_sweep.dm
> +	explaination_text = "Отталкивает цель и все что рядом рядом."
```suggestion
	explaination_text = "Отталкивает цель и все что рядом."
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +			user.say(pick("СУРПРАЙЗО!","УДАР В СПИНУ!","ВУОПХАА!", "ВУАТАА", "ЗУОТАА!", "ОБЕРНИСЬ!", "СЛЕДИ ЗА ТЫЛОМ!", "ПОДЗАТЫЛЬНИК!", "Никогда не показывай спину!", "Не поворачивайся спиной к врагу!", "Теб
```suggestion
			user.say(pick("СУРПРАЙЗО!","УДАР В СПИНУ!","ВУОПХАА!", "ВУАТАА", "ЗУОТАА!", "ОБЕРНИСЬ!", "СЛЕДИ ЗА ТЫЛОМ!", "ПОДЗАТЫЛЬНИК!", "Никогда не показывай спину!", "Не поворачивайся спиной к врагу!", "Тебе передали привет!", "Я передаю привет!"))
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/martial.dm
> +					H.visible_message("<span class='warning'>[user] наносит сильный удар по [H] голове, выбивая [H.p_them()] из строя!</span>", \
```suggestion
					H.visible_message("<span class='warning'>[user] наносит сильный удар по голове [H], выбивая [H.p_them()] из строя!</span>", \
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/mimejutsu.dm
> +	desc =	"К берету прикреплена степлером старая записка..."
```suggestion
	desc =	"Берет, к которому степлером прикреплена старая записка..."
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/sleeping_carp.dm
> +	var/atk_verb = pick("провел удары руками по", "ударил кулаком", "ударил локтем", "бьет ногой", "пнул", "пинает", "провел рубящий удар по", "проводит серию ударов по", "разносит ударами")
"Проводит серию ударов по тебя" - звучит так себе
```suggestion
	var/atk_verb = pick("ударил кулаком", "ударил локтем", "бьет ногой", "пнул", "пинает", "разносит ударами")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/sleeping_carp.dm
> +	to_chat(usr, "<b><i>Вы погружаете свое сознание в себя и вспоминаете учения Свящего Карпа...</i></b>")
```suggestion
	to_chat(usr, "<b><i>Вы погружаетесь в свое сознание и вспоминаете учения Спящего Карпа...</i></b>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/martial_arts/wrestling.dm
> +	to_chat(usr, "<b><i>Вы напрягаете мышцы и осознаете...</i></b>")
```suggestion
	to_chat(usr, "<b><i>Вы напрягаете мускулы и испытываете озарение...</i></b>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/_species.dm
> +				target.visible_message("<span class='danger'>[user] разорвал [target] хватку [target.pulling]!</span>")
```suggestion
				target.visible_message("<span class='danger'>[user] разорвал хватку [target] на [target.pulling]!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/_species.dm
> +					target.visible_message("<span class='danger'>[user] разорвал [target] хватку [lgrab.affecting]!</span>")
```suggestion
					target.visible_message("<span class='danger'>[user] разорвал хватку [target] на [lgrab.affecting]!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/_species.dm
> +					target.visible_message("<span class='danger'>[user] разорвал [target] хватку [rgrab.affecting]!</span>")
```suggestion
					target.visible_message("<span class='danger'>[user] разорвал хватку [target] на [rgrab.affecting]!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/_species.dm
> +	attack_verb = list("охлестали", "тыжело стукнули", "хлестанули лозой", "щелкнули ветвью по")
```suggestion
	attack_verb = list("охлестали", "тяжело стукнули", "хлестанули лозой", "щелкнули ветвью по")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/machine.dm
> +		to_chat(H, "<span class='warning'>Куда делась голова? Не могу сменить монитор/display без неё.</span>")
```suggestion
		to_chat(H, "<span class='warning'>Куда делась голова? Невозможно сменить монитор/дисплей без неё.</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/plasmaman.dm
> +						H.visible_message("<span class='danger'>[H] тело реагирует с атмосферой и загорается!</span>","<span class='userdanger'>Ваше тело реагирует с атмосферой и загорается!</span>")
```suggestion
						H.visible_message("<span class='danger'>Тело [H] вступает в реакцию с атмосферой и загорается!</span>","<span class='userdanger'>Ваше тело вступает в реакцию с атмосферой и загорается!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/slime.dm
> +			to_chat(H, "<span class='warning'>Вы не можете регенерировать недостающие конечности в текузем состоянии</span>")
```suggestion
			to_chat(H, "<span class='warning'>Вы не можете регенерировать недостающие конечности в текущем состоянии</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/vox.dm
> +
Лишний пробел
```suggestion

```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/vulpkanin.dm
> +		"задерживает дыхание!")
Где пробел?

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +		user.visible_message("<span class='warning'> [user] готовится использовать жала Врина!</span>")
```suggestion
		user.visible_message("<span class='warning'> [user] готовится использовать жало Врина!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +		to_chat(user, "<span class='warning'>Вы далеко от цели [target]. Вы убираете свое жало.</span>")
```suggestion
		to_chat(user, "<span class='warning'>Вы далеко от [target]. Вы убираете свое жало.</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +			to_chat(C, "<span class='danger'><B>Ваша антенна покалывает, когда вас одолевает боль...</B></span>")
Почему "антенна" то используется везде, если это усики?
```suggestion
			to_chat(C, "<span class='danger'><B>Ваши усики дрожат, когда вас одолевает боль...</B></span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/living_defense.dm
> +			to_chat(src, "<span class='userdanger'>Ваша броня выдерживает удар!</span>")
```suggestion
			to_chat(src, "<span class='userdanger'>Ваша броня поглощает удар!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/living_defense.dm
> +		visible_message("<span class='warning'>[user] слегка схватил [src]!</span>")
Опять же, "слегка" выглядит имхо неуместно.
```suggestion
		visible_message("<span class='warning'>[user] схватил [src]!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/living_defense.dm
> +		to_chat(M, "<span class='warning'>Вы больше не хотите никому навредить!</span>")
```suggestion
		to_chat(M, "<span class='warning'>Вы не хотите никому навредить!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/living_defense.dm
> +		to_chat(M, "<span class='warning'>Вы больше не хотите никому навредить!</span>")
```suggestion
		to_chat(M, "<span class='warning'>Вы не хотите никому навредить!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/living_defense.dm
> +				to_chat(L, "<span class='warning'>Вы больше не хотите никому навредить!</span>")
```suggestion
				to_chat(L, "<span class='warning'>Вы не хотите никому навредить!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/living/living_defense.dm
> +				to_chat(M, "<span class='warning'>Вы больше не хотите никому навредить!</span>")
```suggestion
				to_chat(M, "<span class='warning'>Вы не хотите никому навредить!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/mob_grab.dm
> +			user.visible_message("<span class='danger'>[user] поглощает \the [affecting]!</span>")
```suggestion
			user.visible_message("<span class='danger'>[user] поглощает [affecting]!</span>")
```

2022-05-10 12:52 UTC, dj-34 commented on code/modules/mob/mob_movement.dm
> +					to_chat(src, "<span class='warning'>Вы задержаны и не можете пошевелиться!</span>")
```suggestion
					to_chat(src, "<span class='warning'>Вы скованы и не можете пошевелиться!</span>")
```

2022-05-10 14:04 UTC, PhantornRU commented on code/game/atoms_movable.dm
> +			visible_message("<span class='warning'>[src] слегка схватил [M]!</span>")
[src] в [src.name] - вынужденная мера чтобы не было приставок The перед предметами.
Иначе получится условно: USER удалил его the книгой

2022-05-10 14:14 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	name = "Мешок игральных костей"
если русифицировать, то стоит русифицировать до конца. Данное название больше нигде не используется и вполне приемлимо.

2022-05-10 14:25 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	name = "Мешок игральных костей"
антену заменил на усики. Я на тот момент походу про другую расу подумал. Глаз замылился.

2022-05-10 14:28 UTC, PhantornRU commented on code/modules/mob/living/living_defense.dm
> +		visible_message("<span class='warning'>[user] слегка схватил [src]!</span>")
Соглашусь, хватка будет получше

2022-05-10 14:30 UTC, PhantornRU commented on code/modules/mob/living/living_defense.dm
> +			to_chat(src, "<span class='userdanger'>Ваша броня выдерживает удар!</span>")
Изначально так и хотел, но подумал что "поглощает" будет приемлемей. Значит возвращаюсь к изначальному варианту

2022-05-10 14:58 UTC, PhantornRU commented on code/modules/martial_arts/combos/krav_maga/leg_sweep.dm
> +	explaination_text = "Выбивает ноги жертвы, в результате чего она падает и не может двигаться в течении короткого времени."
Подножка именно что выбивает ноги, сбивает с ног здесь может быть разве что всем телом. Изначально хам вообще подобия лег-кика.
Это не совсем понятие деревенской подножки где ты просто выставляешь ногу. Это именно выбивание.

2022-05-10 15:05 UTC, PhantornRU commented
Внёс изменения и исправления. Повторно прошелся по тексту. Вроде всё. Завтра попробую повторно пройтись если не забуду.
Местоимения пока не трогал, так как собираюсь их дорабатывать в ближайшем будущем.

2022-05-10 16:20 UTC, TrashDoxx commented
Не забывай потом вместе правки от ревью собирать, чтобы не портить историю лишними коммитами.

2022-05-10 18:34 UTC, Vallat requested changes

2022-05-10 18:34 UTC, Vallat commented on code/__HELPERS/pronouns.dm
> +//pronoun procs, for getting  without using the text macros that only work in certain positions
for getting without

2022-05-10 18:34 UTC, Vallat commented on code/modules/martial_arts/brawling.dm
> +	if(atk_verb == "апперкотом")
весь вот этот вот огромный кусок ифов перенести в свич-кейс. А еще не одобряю сравнение по русским строкам, но че поделать

2022-05-10 18:34 UTC, Vallat commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +						  "<span class='userdanger'>[user] добивает вас решающим ударом локтем сверху!</span>") //[user.p_their()]
Компилировать кто будет?

2022-05-10 18:34 UTC, Vallat commented on code/modules/mob/living/carbon/human/species/plasmaman.dm
> +//внёс перевод акцента речи, шипящий звук. Но я не смог осилить и он почему-то по прежнему не работает, похоже не тут настраивается -- ПУПС
саму функцию stutter глянь

2022-05-10 20:24 UTC, Ohar requested changes
10% отсмотрел, уф. Остальное позже. Не делай таких мега-PR, пожалуйста.

2022-05-10 20:24 UTC, Ohar commented on code/game/atoms_movable.dm
> +			visible_message("<span class='warning'>[src] слегка схватил [M]!</span>")
Да, лучше «мягко».

И пол забыл, 
```suggestion
			visible_message("<span class='warning'>[src] мягко хвата[pluralize_ru(src.gender,"ет","ют")] [M]!</span>")
```

2022-05-10 20:24 UTC, Ohar commented on code/game/atoms_movable.dm
> +			to_chat(user, "<span class='warning'>[src.name] похоже прикреплен к полу!</span>")
Запятые забыл. Ну и пол.
```suggestion
			to_chat(user, "<span class='warning'>Похоже, [src.name] прикрепл[genderize_ru(src.gender,"ён","ена","ено","ены")] к полу!</span>")
```

2022-05-10 20:24 UTC, Ohar commented on code/game/atoms_movable.dm
> +			to_chat(user, "<span class='warning'>[src.name] слишком тяжелый чтобы тащить!</span>")
```suggestion
			to_chat(user, "<span class='warning'>[src.name] слишком тяж[genderize_ru(src.gender,"ёл","ела","ело","елы")], чтобы [genderize_ru(src.gender,"его","её","его","их")] тащить!</span>")
```

2022-05-10 20:24 UTC, Ohar commented on code/game/atoms_movable.dm
> +		visible_message("<span class='warning'>[src] сильно толкает [AM]!</span>", "<span class='warning'>Вы сильно толкаете [AM]!</span>")
Не учитывается потенциальное множественное число (например, у дион бывает такой пол)
```suggestion
		visible_message("<span class='warning'>[src] сильно толка[pluralize_ru(src.gender,"ет","ют")] [AM]!</span>", "<span class='warning'>Вы сильно толкаете [AM]!</span>")
```

2022-05-10 20:24 UTC, Ohar commented on code/game/atoms_movable.dm
> +		visible_message("<span class='danger'>[src] сокрушил [AM]!</span>", "<span class='danger'>Вы сокрушили [AM]!</span>")
Обрати внимание что в оригинале описание действий всегда здесь и сейчас. Поэтому нужно использовать настоящее время. Ну и учитывать число, да
```suggestion
		visible_message("<span class='danger'>[src] сокруша[pluralize_ru(src.gender,"ет","ют")] [AM]!</span>", "<span class='danger'>Вы сокрушили [AM]!</span>")
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	name = "Мешок игральных костей"
Если ты переводишь названия предметов — будь добр указывать их пол для нормальных склонений.

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	user.visible_message("<span class='suicide'>[user] Играет со смертью! Похоже [user.p_theyre()] пытается покончить жизнь самоубийством!</span>")
```suggestion
	user.visible_message("<span class='suicide'>[user] Игра[pluralize_ru(user.gender,"ет","ют")] со смертью! Похоже, он[genderize_ru(user.gender,"","а","о","и")] пыта[pluralize_ru(user.gender,"ется","ются")] покончить жизнь самоубийством!</span>")
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Купик с четырьмя гранями. Игрушка зануд."
> caltrop

Не игрушка.
Эта фраза — отсылка.

Форма игральной кости d4 — пирамида, из-за чего его очень легко воткнуть себе в ногу, если наступить. 
A «caltrop» — это [«чеснок», острые железные фиговины, которые разбрасывали на дорогах в средневековье, чтобы по ним невозможно было пройти людям и коннице](https://ru.wikipedia.org/wiki/Чеснок_(противоконное_заграждение) ). Как танковые ежи, только мелкие.
Слово «нерд»  именно в указанном здесь контексте в русский уже вошло и его стоит оставить как есть.

![](https://static.wikia.nocookie.net/rpg/images/2/23/Dice_d4.jpg/revision/latest?cb=20070904150458&path-prefix=ru)
![](https://upload.wikimedia.org/wikipedia/commons/2/23/Roman_caltrop.jpg)
```suggestion
	desc = "Кость с четырьмя гранями. По-нердски — «чеснок»."
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кубик с двумя гранями. Монеты не достойны!"
Это игральная кость, не кубик. Она не кубическая

Прямой перевод описания теряет насмешливый укор монет в том что они для простаков
```suggestion
	desc = "Кость с двумя гранями. Если монеты вас не достойны."
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Куб с одной гранью. Детерминированный!"
Это игральная кость, не кубик. Она не кубическая
```suggestion
	desc = "Кость с одной гранью. Очень детерминировано!"
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	name = "куб обмана"
Это лучше вообще не переводи, тут игра слов.

С одной стороны «fudge die» — мошенничество, подкрученный кубик.

С другой стороны «FUDGE» — это название игровой системы, которая использует кубы с плюсом, минусом и пустой гранью.

Как ты эту игру смысла сможешь передать — я не представляю. Могу предложить сделать только такой аляповатый вариант, который сохранит обе отсылки, но будет при этом кривым. ![](https://upload.wikimedia.org/wikipedia/commons/3/34/White_Fudge_Dice.jpg)
```suggestion
	name = "фудж-кость"
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кубик с шестью гранями, но только с тремя результатами. Это плюс или минус? Твой разум не понимает..."
```suggestion
	desc = "Кость с шестью гранями, но только с тремя результатами. Это плюс или минус? Вы залипаете на «пусто»…"
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Куб с восемью гранями. Кажется... удачливым."
```suggestion
	desc = "Кость с восемью гранями. Кажется… везучей."
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Куб с десятью гранями. Полезно для процентов."
```suggestion
	desc = "Кость с десятью гранями. Полезно для процентов."
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Куб с десятью гранями. Лучше подходит для рола d100, чем мяч для гольфа."
```suggestion
	desc = "Кость с десятью гранями. Подходит для броска d100 лучше мяча для гольфа."
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Куб с двенадцатью гранями. Ощущается пренебрежение. Похоже им никогда не пользовались..."
Двенадцатигранники почти нигде не используются, поэтому в настолках их считают дурацкими.
```suggestion
	desc = "Кость с двенадцатью гранями. В воздухе вокруг неё ощущается стойкое пренебрежение."
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Куб с двадцатью гранями. Настоящий выбор Игрового Мастера."
Утратил шутку при переводе
```suggestion
	desc = "Кость с двадцатью гранями. Именно такими чаще всего бросаются в игровых мастеров."
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Игральная кость с сотней граней! Наверное неправильно взвешана..."
```suggestion
	desc = "Игральная кость с сотней граней! Вряд ли развесовка выверена…"
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +		user.visible_message("[user] бросил [src.name]. Приземлившись выдав результат [result]. [comment]",
Не забывай про настоящее время. И про числа.
```suggestion
		user.visible_message("[user] броса[pluralize_ru(user.gender,"ет","ют")] [src.name]. На [src.name] выпадает [result]. [comment]",
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +							 "<span class='notice'>Вы бросили [src.name]. Приземлившись выдав результат [result]. [comment]</span>",
Пожалуйста, уделяй чуть больше внимания согласованию слов в предложении
```suggestion
							 "<span class='notice'>Вы бросили [src.name] и выпало [result]. [comment]</span>",
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +		to_chat(user, "<span class='danger'>Твоя линия судьбы обрывается, и ты умираешь.</span>")
Это мем из настолок. Самый простой и тупой способ убить персонажа игрока для мастера — сказать что на него упали камни и тот умер. 
```suggestion
		to_chat(user, "<span class='danger'>На вас упали камни и вы умерли.</span>")
```

2022-05-10 20:24 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "ЕЩЕ ОДИН!? ДА БЛЯТЬ!"
Во-первых, это описание самой коробки и её содержимого — нового набора игровых костей. 
Коробка женского рода, а кости — множественное число. А у тебя мужской род.
Во-вторых, это мем. Мем в том что среди настольщиков часто включается «синдром гоблина» и они начинают обмазываться игровыми костями, постоянно покупая всё новые и новые. Поэтому тут и ругань. И поэтому это описание именно самих костей, а не коробки. Поэтому нужно во множественном числе.
В-третьих, «блядь» пишется через «д».
```suggestion
	desc = "ЕЩЁ ОДНИ!? ДА БЛЯДЬ!"
```

2022-05-10 20:24 UTC, Ohar commented on code/modules/martial_arts/adminfu.dm
> +	name = "Путь Танцующего Админа"
На английском в заголовках все слова пишутся с заглавной буквы. На русском это не так.
```suggestion
	name = "Путь танцующего админа"
```

2022-05-10 20:24 UTC, Ohar commented on code/modules/martial_arts/adminfu.dm
> +		D.visible_message("<span class='warning'>[A] демонстрирует большой светящийся ящик с инструментами и пихает его в [D] грудь!</span>", \
> manifests

Во-первых тут имеется в виду что он как админ будто бы достаёт его из воздуха, а не просто «демонстрирует».
Во-вторых, тулбокс это уже достаточно знаковый термин, его не надо переводить.
В-третьих, тут речь не о пихании или ударе, а о том что тулбокс магически помещают тебе прямо внутрь груди и ты умираешь.
В-четвёртых, пол.
```suggestion
		D.visible_message("<span class='warning'>[A] проявля[pluralize_ru(A.gender,"ет","ют")] большой светящийся тулбокс и запихива[pluralize_ru(A.gender,"ет","ют")] его прямо в грудь [D]!</span>", \
```

2022-05-10 20:24 UTC, Ohar commented on code/modules/martial_arts/adminfu.dm
> +							"<spac class='userdanger'>[A] пихает мистический ящик с инструментами в вашу грудь!</span>")
```suggestion
							"<spac class='userdanger'>[A] запихивает мистический тулбокс в вашу грудь!</span>")
```

2022-05-10 20:24 UTC, Ohar commented on code/modules/martial_arts/adminfu.dm
> +	name = "потертый свиток"
Пропустил «ё»
```suggestion
	name = "потёртый свиток"
```

2022-05-10 20:24 UTC, Ohar commented on code/modules/martial_arts/adminfu.dm
> +	desc = "Старый и потертый клочок бумаги, исписанный меняющимися рунами. Есть рисованные иллюстрации кулачного боя."
```suggestion
	desc = "Старый потёртый клочок бумаги, исписанный меняющимися рунами. Есть рисованные иллюстрации кулачного боя."
```

2022-05-10 20:24 UTC, Ohar commented on code/modules/martial_arts/adminfu.dm
> +		desc = "Он совершенно пустой."
```suggestion
		desc = "Он совершенно пуст."
```

2022-05-10 20:24 UTC, Ohar commented on code/modules/martial_arts/brawling.dm
> +	to_chat(A, "<span class='warning'>Не могу обеззоруживать пока боксирую!</span>")
Это предупредительное сообщение для самого игрока о невозможности действия, оно должно быть не от первого лица.
```suggestion
	to_chat(A, "<span class='warning'>При боксировании не получается обезоруживать!</span>")
```

2022-05-10 20:24 UTC, Ohar commented on code/modules/martial_arts/brawling.dm
> +	to_chat(A, "<span class='warning'>Не могу схватить пока боксирую!</span>")
```suggestion
	to_chat(A, "<span class='warning'>При боксировании не получается хватать!</span>")
```

2022-05-10 20:24 UTC, Ohar commented on code/modules/martial_arts/brawling.dm
> +		D.visible_message("<span class='warning'>[A] попытался ударить [D] [atk_verb]!</span>")
Пол, настоящее время
```suggestion
		D.visible_message("<span class='warning'>[A] пыта[pluralize_ru(A.gender,"ется","ются")] ударить [D] [atk_verb]!</span>")
```

2022-05-11 01:04 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/plasmaman.dm
> +//внёс перевод акцента речи, шипящий звук. Но я не смог осилить и он почему-то по прежнему не работает, похоже не тут настраивается -- ПУПС
смотрел, он должен работать и с русскими символами. Но что-то идет не так.

2022-05-11 01:10 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	desc = "ЕЩЕ ОДИН!? ДА БЛЯТЬ!"
Неа. Блядь - существо женского пола. А как раз Блять - это ругательство.
У меня научная степень по матам :)))

2022-05-11 06:55 UTC, dj-34 commented
Да, согласен с Ohar, в след. раз разбивай на мелкие ПРы хотяб до 10-15 измененных файлов, ревьювить тяжко такое.

2022-05-11 08:12 UTC, PhantornRU commented
> 

Да, стоило бы. Просто здесь всё так комплексно и "удары" разбросаны буквально по всему проекту неоднократно повторяясь. И то я еще не затрагивал симпл мобов.

2022-05-11 17:55 UTC, Vallat commented
@dj-34 @Ohar 

https://user-images.githubusercontent.com/10997188/167915073-ea93636b-e422-4bb1-a57f-b7ff300f97cc.mp4

2022-05-11 18:19 UTC, dj-34 commented
![image](https://user-images.githubusercontent.com/20109643/167918922-3061c902-0f4e-4c25-bc98-3a57e6632853.png)
Спасибо поел

2022-05-13 11:40 UTC, closed without merging

2022-05-13 11:41 UTC, PhantornRU commented
Закрыл ПР ибо я нихера не понял и запутался как что делать. + он слишком большой
Попробую заного.