Tweak: перевод интерфейса медицинского  Body Scanner (сканера тела)
ss220-space/Paradise pull request #878
Opened 2022-05-10 20:18 UTC by Ohar

## What Does This PR Do
Перевод интерфейса Body Scanner (сканера тела).

## Why It's Good For The Game
* Упрощается игра для медиков, особенно для новичков в медицинском отделе

## Images of changes
TODO

## Changelog
:cl:
tweak: tweaked a few things
/:cl:

2022-05-14 18:31 UTC, TrashDoxx requested changes

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +	name = "сканер тела"
```suggestion
	name = "Сканер тела"
```
Не вижу никаких причин использовать нижний регистр для наименований каких-либо объектов.

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +			to_chat(user, "<span class='notice'>Сначала закройте панель техобслуживания.</span>")
```suggestion
			to_chat(user, "<span class='notice'>Сначала закройте панель технического обслуживания.</span>")
```
Не вижу смысла экономить на символах.

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +			to_chat(user, "<span class='warning'>[TYPECAST_YOUR_SHIT.affecting] не влез[pluralize_ru(TYPECAST_YOUR_SHIT.affecting.gender,"ет","ут")] в [src], потому что к [genderize_ru(TYPECAST_YOUR_SHIT.affe
```suggestion
			to_chat(user, "<span class='warning'>[TYPECAST_YOUR_SHIT.affecting] не влез[pluralize_ru(TYPECAST_YOUR_SHIT.affecting.gender,"ет","ут")] в [src], потому что к [genderize_ru(TYPECAST_YOUR_SHIT.affecting.gender,"его","её","его","их")] голове прилип чёртов слайм.</span>")
```
Если честно, у меня неприязнь к слову «прилеплен».

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +			to_chat(user, "<span class='notice'>Субъект не должен держать в руках абиотические предметы.</span>")
```suggestion
			to_chat(user, "<span class='notice'>Субъект не должен держать в руках сторонние предметы.</span>")
```
Выражение «‎абиотические» тут вообще не к месту. ‎‎Можно было бы перевести как «неорганические»‎, но это также довольно тупо, к тому же это выражение зачастую используется в контексте химический соединений.

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +		to_chat(user, "<span class='notice'>Сначала закройте панель техобслуживания.</span>")
```suggestion
		to_chat(user, "<span class='notice'>Сначала закройте панель технического обслуживания.</span>")
```
Не вижу смысла экономить на символах.

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +		to_chat(user, "<span class='notice'>Сначала закройте панель техобслуживания.</span>")
```suggestion
		to_chat(user, "<span class='notice'>Сначала закройте панель технического обслуживания.</span>")
```
Не вижу смысла экономить на символах.

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +		to_chat(user, "<span class='notice'>Субъект не должен держать в руках абиотические предметы.</span>")
```suggestion
		to_chat(user, "<span class='notice'>Субъект не должен держать в руках сторонние предметы.</span>")
```
Выражение «‎абиотические» тут вообще не к месту. ‎‎Можно было бы перевести как «неорганические»‎, но это также довольно тупо, к тому же это выражение зачастую используется в контексте химический соединений.

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +	dat = "<font color='blue'><b>Параметры пациента:</b></font><br>" //Blah obvious
```suggestion
	dat = "<font color='blue'><b>Параметры обследуемого:</b></font><br>" //Blah obvious
```
Может лучше так? Хотя я не уверен. Просто предлагаю.

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +				t1 = "*ТРУП*"
```suggestion
				t1 = "*Мёртв*"
```

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +		dat += "<th>Прочие раны</th>"
```suggestion
		dat += "<th>Прочие повреждения</th>"
```
Так мы избежим пересечений с грубым уроном.

2022-05-14 18:31 UTC, TrashDoxx commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +  ['bad', 'ТРУП'],
```suggestion
  ['bad', 'Мёртв'],
```
Зачем кричишь? 🥺

2022-05-14 18:31 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +				robot = "Робопротез:"
Ты используешь два выражения: робопротез и киберпротез. Выбери какое-то одно. Я бы склонился к первому.

2022-05-14 18:31 UTC, TrashDoxx commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +                  !!o.status.robotic && <Box color="label">Киберпротез</Box>,
Ты используешь два выражения: робопротез и киберпротез. Выбери какое-то одно. Я бы склонился к первому.

2022-05-14 18:31 UTC, TrashDoxx commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +                  (o.robotic === 1) && <Box color="label">Киберпротез</Box>,
Ты используешь два выражения: робопротез и киберпротез. Выбери какое-то одно. Я бы склонился к первому.

2022-05-15 13:33 UTC, Ohar commented on code/game/machinery/adv_med.dm
> +	name = "сканер тела"
Причина очень простая: они используются в формировании строк

2022-05-15 13:34 UTC, Ohar commented on code/game/machinery/adv_med.dm
> +			to_chat(user, "<span class='notice'>Субъект не должен держать в руках абиотические предметы.</span>")
@TrashDoxx А как ты предлагаешь?

2022-05-15 13:35 UTC, Ohar commented on code/game/machinery/adv_med.dm
> +		dat += "<th>Прочие раны</th>"
Уже сам поправил

2022-05-15 13:36 UTC, Ohar commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +  ['bad', 'ТРУП'],
Унифицирую, чтобы везде одинакого было. В большинстве мест используется именно написание заглавными.

2022-05-15 13:37 UTC, Ohar commented on code/game/machinery/adv_med.dm
> +				robot = "Робопротез:"
Спасибо, поправил

2022-05-15 13:40 UTC, Ohar commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +                  !!o.status.robotic && <Box color="label">Киберпротез</Box>,
Поправил

2022-05-15 13:49 UTC, Ohar commented on code/game/machinery/adv_med.dm
> +			to_chat(user, "<span class='notice'>Субъект не должен держать в руках абиотические предметы.</span>")
Я посмотрел код, там идёт проверка на вообще что угодно в руках.
Поменяю на «посторонние»

2022-05-15 13:52 UTC, Ohar commented on code/game/machinery/adv_med.dm
> +	dat = "<font color='blue'><b>Параметры пациента:</b></font><br>" //Blah obvious
Нет, не лучше, как минимум из-за гендерной специфичности.
Ну и это медицинское оборудование, тут пациенты.

2022-05-15 13:54 UTC, Ohar commented on code/game/machinery/adv_med.dm
> +				t1 = "*ТРУП*"
Аналогично, статус смерти лучше везде унифицировать и писать заглавными, он важный.

2022-05-15 14:38 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +	name = "сканер тела"
А, да, я как-то забыл об этом.

2022-05-15 14:41 UTC, TrashDoxx commented on code/game/machinery/adv_med.dm
> +				t1 = "*ТРУП*"
В таком случае используй «МЁРТВ», потому что это выражение везде и используется.
А «труп» встречается один-два раза, что выбивается.

2022-05-22 19:35 UTC, girafe969 requested changes
Я сделялъ

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +		to_chat(user, "<span class='warning'>[H] не влез[pluralize_ru(H.gender,"ет","ут")] в [src], потому что к [genderize_ru(H.gender,"его","её","его","их")] голове прилеплен слайм.</span>")
По аналогии с тем что выше
```suggestion
		to_chat(user, "<span class='warning'>[H] не влез[pluralize_ru(H.gender,"ет","ут")] в [src], потому что к [genderize_ru(H.gender,"его","её","его","их")] голове прилип слайм.</span>")
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +	set name = "Вылезти из сканера тела"
``` suggestion
	set name = "Извлечь пациента из сканера тела"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +				t1 = "*ТРУП*"
А почему не МЁРТВ? Как статус лучше выглядит: в сознании, без сознания, мертв

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +		dat += "[extra_font]\t-Тяжесть ожогов, %: [occupant.getFireLoss()]</font><br>"
По аналогии с другими типами урона
```suggestion
		dat += "[extra_font]\t-Ожоги, %: [occupant.getFireLoss()]</font><br>"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +		dat += "[extra_font]\tПовреждение мозга, %: [occupant.getBrainLoss()]<br>"
По аналогии с генетическими повреждениями
```suggestion
		dat += "[extra_font]\tПовреждения мозга, %: [occupant.getBrainLoss()]<br>"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +		dat += "Общий паралич, %: [occupant.paralysis] ([prlz_left_pretext] [prlz_left] [prlz_left_posttext]!)<br>"
Дословно тут перевод типа "сводка о параличе", Общий тут ни о чём не говорит, местного паралича-то нет
```suggestion
		dat += "Паралич, %: [occupant.paralysis] ([prlz_left_pretext] [prlz_left] [prlz_left_posttext]!)<br>"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +			dat += "Во фронтальной коре обнаружен крупный нарост. Потенциальная онкология. Рекомендуется хирургическое вмешательство.<br>"
```suggestion
			dat += "Во фронтальной коре обнаружена крупная опухоль, потенциально злокачественная. Рекомендуется хирургическое вмешательство.<br>"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +			var/salbutamol_powder_amount = occupant.reagents.get_reagent_amount("salbutamol")
Если уж решил выносить в отдельные переменные (не знаю зачем тебе это), называй их правильно
```suggestion
			var/salbutamol_amount = occupant.reagents.get_reagent_amount("salbutamol")
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +			dat += "[extra_font]\tСальбутамол: [salbutamol_powder_amount] единиц[declension_ru(salbutamol_powder_amount,"а","ы","")]<BR>"
Соответствие с правкой выше
```suggestion
			dat += "[extra_font]\tСальбутамол: [salbutamol_amount] единиц[declension_ru(salbutamol_powder_amount,"а","ы","")]<BR>"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +					infected = "Лёгкое заражение:"
По аналогии с острой, так как Острое заражение звучит хуже чем Лёгкая инфекция
```suggestion
					infected = "Лёгкая инфекция:"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +					infected = "Лёгкое заражение+:"
```suggestion
					infected = "Лёгкая инфекция+:"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +					infected = "Лёгкое заражение++:"
```suggestion
					infected = "Лёгкая инфекция++:"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +					infection = "Лёгкое заражение:"
```suggestion
					infection = "Лёгкая инфекция:"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +					infection = "Лёгкое заражение+:"
```suggestion
					infection = "Лёгкая инфекция+:"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +					infection = "Лёгкое заражение++:"
```suggestion
					infection = "Лёгкая инфекция++:"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/machinery/adv_med.dm
> +			dat += "<font color='red'>Обнаружено смещение сетчатки.</font><BR>"
Как хорошо, когда на английском придумали какую-то дичь, и ты тратишь пол часа на то чтобы понять, что это просто выдумка, а не реальное медицинское состояние

2022-05-22 19:35 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +		to_chat(user, "<span class='notice'>Нужно перезарядить [src] перед использованием</span>")
Это недостаточно заряда у борга для использования модуля. Нужно зарядиться, а не зарядить сканер

2022-05-22 19:35 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +		to_chat(user, "<span class='notice'>Вы спрашивали, хороший ли он[genderize_ru(M.gender,"","а","о","и")] пёсик… <b>[src.name] показывает что [genderize_ru(M.gender,"он был","она была","оно было","он
"хороший ли они пёсик" ?
Ладно, надеюсь это никогда не будет использоваться

2022-05-22 19:35 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +			t1 = "*ТРУП*"
Если решишь изменить
```suggestion
			t1 = "*МЁРТВ*"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +	dat += "[extra_font]\t-Тяжесть ожогов, %: [target.getFireLoss()]</font><br>"
```suggestion
	dat += "[extra_font]\t-Ожоги, %: [target.getFireLoss()]</font><br>"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +	dat += "[extra_font]\tПовреждение мозга, %: [target.getBrainLoss()]<br>"
```suggestion
	dat += "[extra_font]\tПовреждения мозга, %: [target.getBrainLoss()]<br>"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +	dat += "Общий паралич, %: [target.paralysis] ([prlz_left_pretext] [prlz_left] [prlz_left_posttext]!)<br>"
```suggestion
	dat += "Паралич, %: [target.paralysis] ([prlz_left_pretext] [prlz_left] [prlz_left_posttext]!)<br>"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +		dat += "Во фронтальной коре обнаружен крупный нарост. Потенциальная онкология. Рекомендуется хирургическое вмешательство.<br>"
```suggestion
		dat += "Во фронтальной коре обнаружена крупная опухоль, потенциально злокачественная. Рекомендуется хирургическое вмешательство.<br>"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +		var/salbutamol_powder_amount = target.reagents.get_reagent_amount("salbutamol")
```suggestion
		var/salbutamol_amount = target.reagents.get_reagent_amount("salbutamol")
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +		dat += "[extra_font]\tСальбутамол: [salbutamol_powder_amount] единиц[declension_ru(salbutamol_powder_amount,"а","ы","")]<BR>"
```suggestion
		dat += "[extra_font]\tСальбутамол: [salbutamol_powder_amount] единиц[declension_ru(salbutamol_amount,"а","ы","")]<BR>"
```

2022-05-22 19:35 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +				infected = "Лёгкое заражение:"
Я заебался писать одно и то же, исправь сам тут и ниже "Лёгкое заражение" на "Лёгкая инфекция"

2022-05-22 19:35 UTC, girafe969 commented on code/modules/surgery/organs/organ_external.dm
> +		broken_description = "[frac_damage] [frac_type] перелом"
А точно все сочетания существуют ирл?

2022-05-22 19:35 UTC, girafe969 commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +  ['bad', 'ТРУП'],
Подскажешь примеры где это будет нужно? Просто не могу припомнить места где бы был медицинский статус не в контексте пациента, да и они вроде везде вида "активен/без сознания/критическое состояние/мертв", так что всё равно гендеры нужно будет обрабатывать в других вариантах

2022-05-22 19:35 UTC, girafe969 commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +  ['hasBorer', 'bad', 'Во фронтальной коре обнаружен крупный нарост. Потенциальная онкология. Рекомендуется хирургическое вмешательство.'],
```suggestion
  ['hasBorer', 'bad', 'Во фронтальной коре обнаружена крупная опухоль, потенциально злокачественная. Рекомендуется хирургическое вмешательство.'],
```

2022-05-22 19:35 UTC, girafe969 commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +  ['Мозг', 'brainLoss'],
Повреждения мозга. Либо исправляй тут, либо делай склонение в менюшке где ты это вставляешь
```suggestion
  ['Мозга', 'brainLoss'],
```

2022-05-22 19:35 UTC, girafe969 commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +  ['Радиационные', 'radLoss'],
Понравилось такое название из печатных сканов. Само по себе это не повреждение - тем же нуклеациям от этого по-боку. (Если бы работал механ, наоборот хилится должны бы были)
```suggestion
  ['Уровень радиации', 'radLoss'],
```

2022-05-22 19:35 UTC, girafe969 commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +          <AnimatedNumber value={round(occupant.bodyTempC, 0)} /> °C
А фаренгейты-то за что зарубил? Может вместо них тогда хоть Кельвины поставишь?

2022-05-22 19:35 UTC, girafe969 commented on tgui/packages/tgui/interfaces/BodyScanner.js
> +                  (o.robotic === 1) && <Box color="label">Робопротез</Box>,
Для внутренних органов уместно такое название?

2022-05-22 19:35 UTC, girafe969 commented on tgui/packages/tgui/interfaces/BodyScanner.js
>                    (o.robotic === 2) && <Box color="label">Assisted</Box>,
Нет перевода (да, я знаю что это нигде не используется)

2022-05-23 08:13 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +		to_chat(user, "<span class='notice'>Вы спрашивали, хороший ли он[genderize_ru(M.gender,"","а","о","и")] пёсик… <b>[src.name] показывает что [genderize_ru(M.gender,"он был","она была","оно было","он
А, кстати, тут надо прошедшее время. Это же скан мертвого корги

2022-05-23 08:19 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +		to_chat(user, "<span class='notice'>Вы спрашивали, хороший ли он[genderize_ru(M.gender,"","а","о","и")] пёсик… <b>[src.name] показывает что [genderize_ru(M.gender,"он был","она была","оно было","он
```suggestion
		to_chat(user, "<span class='notice'>Вы спрашиваете, хорош[genderize_ru(M.gender,"им","ей","им","ими")] ли он[genderize_ru(M.gender,"","а","о","и")] был[genderize_ru(M.gender,"","а","о","и")] genderize_ru(M.gender,"пёсиком","собачкой","пёсиком","пёсиками")]... <b>[src.name] показывает что [genderize_ru(M.gender,"он был","она была","оно было","они были")] самым лучшим пёсиком</b>.</span>") // :'(
```

2022-05-23 08:24 UTC, girafe969 commented on code/game/objects/items/devices/scanners.dm
> +		to_chat(user, "<span class='notice'>Вы спрашивали, хороший ли он[genderize_ru(M.gender,"","а","о","и")] пёсик… <b>[src.name] показывает что [genderize_ru(M.gender,"он был","она была","оно было","он
У меня нет троеточия на телефоне, поправь там

2024-02-12 20:59 UTC, closed without merging