Перевод игральных костей
ss220-space/Paradise pull request #883
Opened 2022-05-13 14:40 UTC by PhantornRU

## What Does This PR Do
Переведены игральные кости

## Why It's Good For The Game
Русский язык - хорошо

2022-05-14 04:03 UTC, Ohar requested changes

2022-05-14 04:03 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с шестью гранями. Непримечательный и лёгкий в обращении."
```suggestion
	desc = "Кость с шестью гранями. Непримечательна и лёгка в обращении."
```

2022-05-14 07:40 UTC, Vallat approved these changes

2022-05-14 14:55 UTC, TrashDoxx commented
Пока не мержить. Отсматриваю перевод.

2022-05-14 15:37 UTC, TrashDoxx requested changes

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с шестью гранями. Непримечательна и лёгка в обращении."
```suggestion
	name = "Игральная кость"
	desc = "Кость с шестью гранями. Непримечательна и проста в обращении."
```

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с четырьмя гранями. По-нердски — «чеснок»."
Подобный сленг («нерд, по-нердски») у нас не распространён. А употребления слова «чеснок» в таком значении я не встречал вовсе. Это исключительно западная тема. Лучше придумать что-то приближённое к нашим реалиям.

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с четырьмя гранями. По-нердски — «чеснок»."
Подобный сленг («нерд», «по-нердски») у нас не распространён. «Задрот» или «ботаник» звучит более приемлемо, но если хочется впихнуть англицизм, то можно использовать слово «гик», оно вполне себе известно русскому народу. А употребления слова «чеснок» в таком значении я не встречал вовсе. Это исключительно западная тема. Лучше придумать что-то приближённое к нашим реалиям. Например, обозвать клевером или что-то в этом духе.

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	sides = 3 //shhh --- Мы никому не скажем
```suggestion
	name = "Fudge-кость"
	desc = "Кость с шестью гранями, но только с тремя результатами. Это плюс или минус? Ваш разум опустел..."
	sides = 3
```
Fudge невозможно перевести, так как это акроним для ролевой системы. А вторая часть предложения это идиома.

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с десятью гранями. Подходит для броска d100 лучше мяча для гольфа."
```suggestion
	desc = "Кость с десятью гранями. Подходит для бросков d100 лучше мяча для гольфа."
```

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с двенадцатью гранями. В воздухе вокруг неё ощущается стойкое пренебрежение."
```suggestion
	desc = "Кость с двенадцатью гранями. Вокруг неё царит атмосфера запустения."
```
Звучит довольно всрато, но всё равно лучше отражает оригинал.

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с двадцатью гранями. Именно такими чаще всего бросаются в игровых мастеров."
```suggestion
	desc = "Кость с двадцатью гранями. Именно такой предпочтительно бросать в мастера."
```

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Игральная кость с сотней граней! Вряд ли развесовка выверена…"
Не совсем понимаю, что здесь подразумевается, но пусть будет так.

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +		comment = "Ауч, невезуха."
```suggestion
		comment = "М-да, невезуха."
```

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +		to_chat(user, "<span class='danger'>На вас упали камни и вы умерли.</span>")
```suggestion
		to_chat(user, "<span class='danger'>Камни падают и вы погибаете.</span>")
```

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	desc = "ЕЩЁ ОДНИ!? ДА БЛЯДЬ!"
```suggestion
	desc = "ЕЩЁ ОДНА!? ДА БЛЯДЬ!"
```
Возможно подразумевается, кхм, ЕЩЁ ОДНА ПАРТИЯ!?, но я не уверен. Пусть будет так.

2022-05-14 15:37 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +		visible_message("<span class='notice'>[src.name] прекращает катиться, останавливаясь на [result]. [comment]</span>")
```suggestion
		visible_message("<span class='notice'>[src.name] прекращает катиться, остановившись на [result]. [comment]</span>")
```

2022-05-14 23:57 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	sides = 3 //shhh --- Мы никому не скажем
![image](https://user-images.githubusercontent.com/41479614/168451778-b8d96f3d-84e2-4f9e-b1b7-6fed68f4c830.png)

2022-05-14 23:58 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +		to_chat(user, "<span class='danger'>На вас упали камни и вы умерли.</span>")
Здесь идет мем с самым тупым способом смерти.
![image](https://user-images.githubusercontent.com/41479614/168451809-036b1507-e0d7-45a3-89b8-2b77d8e12f00.png)

2022-05-15 00:00 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с четырьмя гранями. По-нердски — «чеснок»."
![image](https://user-images.githubusercontent.com/41479614/168451838-3a5e427e-5b97-4291-9bb1-354b6a4d372a.png)

2022-05-15 00:30 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с двенадцатью гранями. В воздухе вокруг неё ощущается стойкое пренебрежение."
![image](https://user-images.githubusercontent.com/41479614/168452463-735a6ebb-23c4-4127-8a49-daf52d4e27d1.png)

2022-05-15 00:31 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с двадцатью гранями. Именно такими чаще всего бросаются в игровых мастеров."
![image](https://user-images.githubusercontent.com/41479614/168452471-e4ea6fae-36d7-449a-8b39-2c01baee4649.png)

2022-05-15 00:33 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	desc = "ЕЩЁ ОДНИ!? ДА БЛЯДЬ!"
![image](https://user-images.githubusercontent.com/41479614/168452503-2b7de367-8f60-411d-90e7-81f74b234ae1.png)

2022-05-15 02:16 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с четырьмя гранями. По-нердски — «чеснок»."
![image](https://user-images.githubusercontent.com/41479614/168454348-72ca29c1-fe46-4161-8e2d-1485620204b9.png)

2022-05-15 02:16 UTC, PhantornRU commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с двенадцатью гранями. В воздухе вокруг неё ощущается стойкое пренебрежение."
Вышел конфликт перевода

2022-05-15 02:18 UTC, PhantornRU commented
Внёс изменения.
Самые спорные конфликты 2-х ревьюверов с переводами оставил пока не разрешенными, остальным внес правки.

Жду продолжения банкета

2022-05-15 09:19 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с двенадцатью гранями. В воздухе вокруг неё ощущается стойкое пренебрежение."
Оставь «Похоже им никогда не пользовались...» в описании. Больше ничего не нужно.

2022-05-15 09:19 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с двадцатью гранями. Именно такими чаще всего бросаются в игровых мастеров."
Не суть важно, сам напиши.

2022-05-15 09:22 UTC, TrashDoxx commented on code/game/objects/items/weapons/dice.dm
> +		to_chat(user, "<span class='danger'>На вас упали камни и вы умерли.</span>")
Как угодно. Но в первом варианте нет трагизма. Лучше убрать предлоги, чтобы звучало брутальнее.

2022-05-15 14:09 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "Кость с четырьмя гранями. По-нердски — «чеснок»."
Про гика согласен.
Чеснок ещё называют калтропами, потому что слово «чеснок» (как и сама эта фиговина) устаревшее и людям непривычно это называть чесноком. Но это неправильно же.

2022-05-15 14:21 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +		to_chat(user, "<span class='danger'>На вас упали камни и вы умерли.</span>")
А здесь и нет трагизма, в этом и суть

2022-05-15 14:31 UTC, Ohar commented on code/game/objects/items/weapons/dice.dm
> +	desc = "ЕЩЁ ОДНИ!? ДА БЛЯДЬ!"
![](https://ahseeit.com//king-include/uploads/2021/06/ooae65f-1143843928.png)

2022-05-25 14:47 UTC, PhantornRU commented
Одобрено Авоутом
https://discord.com/channels/617003227182792704/755125334097133628/978974080814424074

2022-05-25 19:48 UTC, TrashDoxx approved these changes

2022-05-29 16:23 UTC, merged