Перевод боевых искусств. Дополнение и расширение с улучшением пьяных драк
ss220-space/Paradise pull request #884
Opened 2022-05-13 14:51 UTC by PhantornRU

## What Does This PR Do
Боевые искусства:
- Переведены боевые искусства: Спящий Карп, Борьба(Реслинг с борцовским поясом), Бокс, Пьяные Драки, CQC, Крав Мага, Мимдзютсу, Плазменный Кулак, Синтдзютсу (Боевой Модуль IPC), Путь -Танцующего Админа
- Переведены удары бо посохом
- Корректные именные наименования при изучении боевых искусств через мануалы и свитки, а также при использовании бо посоха
- Категория Боевые Искусства теперь русифицирована
- Переведена помощь для каждого из боевых искусств (кроме наименований интентов, для удобств)
- Увеличен словарный запас фраз боевого искусства Спящего Карпа
- Дополнены текстовые описания ударов CQC
- Дополнены текстовые описание ударов крав мага
- Дополнены текстовые описание ударов боксирования, борьбы и драк
- Логирование и дебаг не переведены для удобства администрации и разработчиков.
- Добавлены дополнительные описания ударов боевых искусств.

Пьяные драки:
- Добавлены расширенные удары и приемы при пьяных драках (случайны и зависят от удачи)
- Пьяные драки мутят вам желудок. Хорошо покушайте перед показыванием мастерства, если драка будет долгой.
- Добавлены разнообразные шансы на нанесение дополнительного урона в пьяных драках (а также на его отсутствие), а также бафы/дебафы от использования приемов
- Добавлено пьяное мастерство при пьяных драках которое с некоторыми шансами способно равноценно нанести урон по стамине и дыхалке оппоненту и пьяному мастеру.

## Why It's Good For The Game
Русский язык это хорошо.
Драки и боевые искусства теперь более оживленные и имеют больше описаний ударов.
Пьяные драки в баре теперь залог хорошего настроения ассистентов и бармена. С сотрудниками СБ. Ведь можно проворачивать пьяное мастерство. Правда пьяное мастерство случайно и в каждом оно таится...

2022-05-14 07:41 UTC, Vallat commented on code/modules/martial_arts/brawling.dm
> +		D.adjustStaminaLoss(rand(0, 15)) //но зато измотает противника пытающегося понять что это пьяное рудо вытворяет
```suggestion
		D.adjustStaminaLoss(rand(0, 15)) //но зато измотает противника пытающегося понять что это пьяное чудо вытворяет
```

2022-05-14 07:45 UTC, Vallat commented on code/modules/martial_arts/mimejutsu.dm
> +//не работает Grab. Будет пофикшено в следующих коммитах
Ладно

2022-05-14 07:46 UTC, Vallat approved these changes

2022-05-14 14:56 UTC, TrashDoxx commented
Пока не мержить. Отсматриваю перевод.

2022-05-19 03:15 UTC, Ohar requested changes
Две трети отсмотрел. Дальше — потом.

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/brawling.dm
> +								"<span class='userdanger'>[D] нокаутирован[genderize_ru(D.gender,"","а","о","ы")]  [A] мощным ударом в челюсть!</span>")
Ты поменял местами и теперь это выглядит странно, не находишь?
> Вася нокаутирован Петя мощным ударом в челюсть!


Нихуя не понятно — кто кого…

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/brawling.dm
> +	name = "Пьяная Драка"
```suggestion
	name = "Пьяная драка"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/brawling.dm
> +							"<span class='warning'>Тебе не удалось ухватиться за [D]!</span>")
```suggestion
							"<span class='warning'>Вам не удалось ухватиться за [D]!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/brawling.dm
> +		D.visible_message("<span class='danger'>[A] пьяно хвата[pluralize_ru(A.gender,"ет","ют")] [hit_name] [D]!</span>", \
```suggestion
		D.visible_message("<span class='danger'>[A] пьяно хвата[pluralize_ru(A.gender,"ет","ют")] [D] за [hit_name]!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/brawling.dm
> +								"<span class='userdanger'>[D] попал[genderize_ru(D.gender,"","а","о","и")]  в пьяный захват [A]! Он[genderize_ru(A.gender,"","а", "о","и")] схватил[genderize_ru(A.gender,"","а", "о","и")] [ge
```suggestion
								"<span class='userdanger'>[D] попал[genderize_ru(D.gender,"","а","о","и")]  в пьяный захват [A]! Он[genderize_ru(A.gender,"","а", "о","и")] схватил[genderize_ru(A.gender,"","а", "о","и")] [genderize_ru(D.gender,"его","её", "у этого","их")] за [hit_name]!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/brawling.dm
> +								"<span class='userdanger'>[D] нокаутирован[genderize_ru(D.gender,"","а","о","ы")] [A] мощным пьяным ударом!</span>")
Аналогично — смена объекта и субъекта вносит путаницу

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/adminfu/healing_palm.dm
> +	name = "Исцеляющая Ладонь"
```suggestion
	name = "Исцеляющая ладонь"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/adminfu/healing_palm.dm
> +			to_chat(target, "<span class='notice'>Ты восстал, ты живой!!!</span>")
```suggestion
			to_chat(target, "<span class='notice'>Вы восстали, вы живы!!!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/consecutive.dm
> +	explaination_text = "Ориентированный на урон удар, огромный физических урон и гигантский удар по выносливости."
```suggestion
	explaination_text = "Атакующий приём: огромный физический урон и значительное выбивание выносливости."
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/consecutive.dm
> +		target.visible_message("<span class='warning'>[user] последовательно бь[pluralize_ru(user.gender,"ет","ют")] [target] в живот, шею и спину!</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] последовательно бь[pluralize_ru(user.gender,"ёт","ют")] [target] в живот, шею и спину!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/consecutive.dm
> +							"<span class='userdanger'>[user] последовательно бь[pluralize_ru(user.gender,"ет","ют")] вас в живот, шею и спину!</span>")
```suggestion
							"<span class='userdanger'>[user] последовательно бь[pluralize_ru(user.gender,"ёт","ют")] вас в живот, шею и спину!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/consecutive.dm
> +	name = "Последовательный CQC"
```suggestion
	name = "CQC-триплет"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/kick.dm
> +	name = "CQC Пинок"
```suggestion
	name = "CQC-пинок"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/kick.dm
> +		target.visible_message("<span class='warning'>[user] пина[pluralize_ru(user.gender,"ет","ют")] [target] оттолкнув!</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] отбрасыва[pluralize_ru(user.gender,"ет","ют")] [target] пинком!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/kick.dm
> +							"<span class='userdanger'>[user] пина[pluralize_ru(user.gender,"ет","ют")]  вас оттолкнув!</span>")
```suggestion
							"<span class='userdanger'>[user] отбрасыва[pluralize_ru(user.gender,"ет","ют")] вас пинком!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/kick.dm
> +		target.visible_message("<span class='warning'>[user] пина[pluralize_ru(user.gender,"ет","ют")] в голову [target], нокаутируя [genderize_ru(target.gender,"его","её","его","их")]!</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] нокаутиру[pluralize_ru(user.gender,"ет","ют")] [target] пинком в голову!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/kick.dm
> +					  		"<span class='userdanger'>[user] пина[pluralize_ru(user.gender,"ет","ют")] вас в голову, нокаутировав!</span>")
```suggestion
					  		"<span class='userdanger'>[user] нокаутиру[pluralize_ru(user.gender,"ет","ют")] вас пинком в голову!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/pressure.dm
> +	explaination_text = "Наносит удар по выносливости сжимая горло цели."
```suggestion
	explaination_text = "Выдавливает из оппонента всю выносливость."
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/restrain.dm
> +	name = "Захват"
Нужно иное название, чтобы не путать с 3 интентом.
```suggestion
	name = "Залом"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/restrain.dm
> +	combo_text_override = "Grab, сменить руки, Grab"
```suggestion
	combo_text_override = "Захват, смена рук, захват"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/restrain.dm
> +	explaination_text = "Применяет болевой приём, который сдерживает противника в беспомощном положении, дополнительно используя обезоруживания нокаутирует цель."
```suggestion
	explaination_text = "Болевым приёмос, ставит оппонента в беспомощное положение, и удушающим приёмом нокаутирует его."
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/adminfu/healing_palm.dm
> +	combo_text_override = "Захватить, сменить руки, Помочь"
```suggestion
	combo_text_override = "Захват, смена рук, помощь"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/restrain.dm
> +		target.visible_message("<span class='warning'>[user] захватыва[pluralize_ru(user.gender,"ет","ют")] [target] в удерживающее положение!</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] заламыва[pluralize_ru(user.gender,"ет","ют")] [target] в удерживающее положение!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/restrain.dm
> +							"<span class='userdanger'>[user] захватил[pluralize_ru(user.gender,"","и")] вас в удерживаемом положении!</span>")
```suggestion
							"<span class='userdanger'>[user] заламыва[pluralize_ru(user.gender,"ет","ют")] вас в удерживаемом положении!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/cqc/slam.dm
> +	combo_text_override = "Grab, Сменить руки, Harm"
```suggestion
	combo_text_override = "Захват, смена рук, вред"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/krav_maga/leg_sweep.dm
> +	explaination_text = "Выбивает ноги жертвы, в результате чего она падает и не может двигаться в течении короткого времени."
```suggestion
	explaination_text = "Подсекает ноги оппонента, из-за чего он падает и некоторое время не может двигаться."
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/krav_maga/leg_sweep.dm
> +	target.visible_message("<span class='warning'>[user] выбива[pluralize_ru(user.gender,"ет","ют")] ногу [target]!</span>", \
```suggestion
	target.visible_message("<span class='warning'>[user] подсека[pluralize_ru(user.gender,"ет","ют")] ноги [target]!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/krav_maga/leg_sweep.dm
> +					  	"<span class='userdanger'>[user] выбил[pluralize_ru(user.gender,"","и")] вам ногу!</span>")
```suggestion
					  	"<span class='userdanger'>[user] подсека[pluralize_ru(user.gender,"ет","ют")] вам ноги!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/krav_maga/lung_punch.dm
> +	name = "Удар под Дых"
```suggestion
	name = "Удар под дых"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/krav_maga/lung_punch.dm
> +	explaination_text = "Наносит сильный удар под дых, сдавливая лёгкие, отчего жертва временно не может дышать."
```suggestion
	explaination_text = "Наносит сильный удар под дых, выбивая воздух из лёгких, и временно лишает оппонента возможности дышать."
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/krav_maga/lung_punch.dm
> +	target.visible_message("<span class='warning'>[user] бь[pluralize_ru(user.gender,"ет","ют")] [target] в солнечное сплетение!</span>", \
```suggestion
	target.visible_message("<span class='warning'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] [target] в солнечное сплетение!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/krav_maga/lung_punch.dm
> +				  	"<span class='userdanger'>[user] бь[pluralize_ru(user.gender,"ет","ют")] тебя в солнечное сплетение! Вы не можете дышать!</span>")
```suggestion
				  	"<span class='userdanger'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] вас в солнечное сплетение! Вы не можете дышать!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/krav_maga/neck_chop.dm
> +	name = "Удар по горлу"
```suggestion
	name = "Удар в горло"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/krav_maga/neck_chop.dm
> +	target.visible_message("<span class='warning'>[user] бь[pluralize_ru(user.gender,"ет","ют")] ударом каратэ в горло [target]!</span>", \
```suggestion
	target.visible_message("<span class='warning'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] ударом каратэ в горло [target]!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/krav_maga/neck_chop.dm
> +		"<span class='userdanger'>[user] бь[pluralize_ru(user.gender,"ет","ют")] ударом каратэ в горло, временно лишая вас возможности говорить!</span>")
```suggestion
		"<span class='userdanger'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] ударом каратэ в горло, временно лишая вас возможности говорить!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/martial_combo.dm
> +	var/explaination_text = "Способность ломать лица"
```suggestion
	var/explaination_text = "Умение ломать лица"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/mimejutsu/mimechucks.dm
> +			target.visible_message("<span class='warning'>[user] размахива[pluralize_ru(user.gender,"ет","ют")] невидимыми нунчаками по [target]..и промахивается?</span>")
```suggestion
			target.visible_message("<span class='warning'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] невидимыми нунчаками по [target]… и промахива[pluralize_ru(user.gender,"ется","ются")]?</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/mimejutsu/mimechucks.dm
> +		target.visible_message("<span class='danger'>[user] попа[genderize_ru(user.gender,"","а","о","и")] в [target] невидимыми нунчаками!</span>", \
```suggestion
		target.visible_message("<span class='danger'>[user] ударя[pluralize_ru(user.gender,"ет","ют")] по [target] невидимыми нунчаками!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/mimejutsu/mimechucks.dm
> +								"<span class='userdanger'>[user] попал[genderize_ru(user.gender,"","а","о","и")] в [target] невидимыми нунчаками!</span>")
```suggestion
								"<span class='userdanger'>[user] ударя[pluralize_ru(user.gender,"ет","ют")] по [target] невидимыми нунчаками!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/mimejutsu/silent_palm.dm
> +	name = "Ладонь Тишины"
```suggestion
	name = "Тихая ладонь"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/mimejutsu/silent_palm.dm
> +		target.visible_message("<span class='danger'>[user] едва коснул[genderize_ru(user.gender,"ся","ась","ось","ись")] [target] своей ладонью!</span>", \
```suggestion
		target.visible_message("<span class='danger'>[user] едва коснул[genderize_ru(user.gender,"ся","ась","ось","ись")] [target] ладонью!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/mimejutsu/silent_palm.dm
> +						"<span class='userdanger'>[user] наводит свою ладонь на ваше лицо!</span>")
```suggestion
						"<span class='userdanger'>[user] протягива[pluralize_ru(user.gender,"ет","ют")] ладонь к вашему лицу!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/mimejutsu/smokebomb.dm
> +	explaination_text = "Бросить пантомимовую дымовую шашку."
```suggestion
	explaination_text = "Бросить мимскую дымовую шашку."
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/plasma_fist.dm
> +	name = "Плазменный Кулак"
```suggestion
	name = "Плазменный кулак"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/plasma_fist.dm
> +	steps = list(MARTIAL_COMBO_STEP_HARM, MARTIAL_COMBO_STEP_DISARM, MARTIAL_COMBO_STEP_DISARM, MARTIAL_COMBO_STEP_DISARM, MARTIAL_COMBO_STEP_GRAB, MARTIAL_COMBO_STEP_HARM)
Зачем ты усложнил комбо?

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/plasma_fist.dm
> +	target.visible_message("<span class='danger'>[user] поразил[genderize_ru(user.gender,"","а","о","и")] [target] ТЕХНИКОЙ ПЛАЗМЕННОГО КУЛАКА!</span>", \
```suggestion
	target.visible_message("<span class='danger'>[user] поража[pluralize_ru(user.gender,"ет","ют")] [target] ТЕХНИКОЙ ПЛАЗМЕННОГО КУЛАКА!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/plasma_fist.dm
> +								"<span class='userdanger'>[user] поразил[genderize_ru(user.gender,"","а","о","и")] [target] ТЕХНИКОЙ ПЛАЗМЕННОГО КУЛАКА!</span>")
```suggestion
								"<span class='userdanger'>[user] поража[pluralize_ru(user.gender,"ет","ют")] [target] ТЕХНИКОЙ ПЛАЗМЕННОГО КУЛАКА!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/throwback.dm
> +	target.visible_message("<span class='danger'>[user] попал[genderize_ru(user.gender,"","а","о","и")] в [target] Плазменным Ударом!</span>", \
```suggestion
	target.visible_message("<span class='danger'>[user] попада[pluralize_ru(user.gender,"ет","ют")] в [target] Плазменным ударом!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/throwback.dm
> +								"<span class='userdanger'>[user] попал[genderize_ru(user.gender,"","а","о","и")] в [target] Плазменным Ударом!</span>")
```suggestion
								"<span class='userdanger'>[user] попада[pluralize_ru(user.gender,"ет","ют")] в [target] Плазменным ударом!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/throwback.dm
> +	user.say("ХЬЙА!")
```suggestion
	user.say("КИЙЯ!")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/throwback.dm
> +	target.throw_at(throw_target, 10, 4, user)
Уверен что дальность надо так снизить?

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/tornado_sweep.dm
> +	name = "Кручение Торнадо"
```suggestion
	name = "Вихрь торнадо"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/tornado_sweep.dm
> +	explaination_text = "Отталкивает цель и все что рядом."
```suggestion
	explaination_text = "Отталкивает оппонента и всех вокруг."
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/tornado_sweep.dm
> +	user.say("КРУЧЕНОЕ ТОРНАДО!")
```suggestion
	user.say("ТОРНАДО!")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +	explaination_text = "Оппонент должен быть отвернут. Сбивает его с ног."
```suggestion
	explaination_text = "Используется только сзади. Сбивает оппонента с ног."
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +			user.say(pick("СУРПРАЙЗО!","УДАР В СПИНУ!","ВУОПХАА!", "ВУАТАА", "ЗУОТАА!", "ОБЕРНИСЬ!", "СЛЕДИ ЗА ТЫЛОМ!", "ПОДЗАТЫЛЬНИК!", "Никогда не показывай спину!", "Не поворачивайся спиной к врагу!", "Теб
```suggestion
			user.say(pick("СУРПРАЙЗО!","УДАР В СПИНУ!","УДАР В ПСИНУ!","ВУОПХАА!", "ВУАТАА", "ЗУОТАА!", "ОБЕРНИСЬ!", "СЗАДИ!", "СЛЕДИ ЗА ТЫЛОМ!", "ПОДЗАТЫЛЬНИК!", "ПЕНДЕЛЬ!", "Никогда не показывай спину!", "Не поворачивайся спиной к врагу!", "Тебе передали привет!", "Я передаю привет!"))
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +	name = "Выпад Элбоу"
```suggestion
	name = "Локтевой выпад"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +						  "<span class='userdanger'>[user] добива[pluralize_ru(user.gender,"ет","ют")] вас решающим ударом локтем сверху!</span>") //[user.p_their()]
```suggestion
						  "<span class='userdanger'>[user] в прыжке добива[pluralize_ru(user.gender,"ет","ют")] вас коронным локтевым выпадом!</span>") 
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +		target.visible_message("<span class='warning'>[user] падением сверху наносит решающий удар локтем по [target]!</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] в прыжке сверху наносит решающий удар локтем по [target]!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +			user.say(pick("БАНЗАИИИИ!", "КИЙААААА!", "OMAE WA MOU SHINDEIRU!", "ЗАДЕРЖИ ДЫХАНИЕ!", "ТЫ БОЛЬШЕ НЕ УВИДИШЬ МЕНЯ!", "ПРИШЛО МОЕ ВРЕМЯ!", "КАВАБАНГА!", "ИСПУСКАЙ ДУХ!"))
Мем хоть и японский, всё равно надо транслитерировать. Он же не иероглифами написан.
```suggestion
			user.say(pick("БАНЗАИИИИ!", "КИЙААААА!", "ОМАЕВА МО ШИНДЕРУ!", "ЗАДЕРЖИ ДЫХАНИЕ!", "ТЫ МЕНЯ БОЛЬШЕ НЕ УВИДИШЬ!", "ПРИШЛО МОЁ ВРЕМЯ!", "КАВАБАНГА!", "ИСПУСКАЙ ДУХ!"))
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/head_kick.dm
> +	name = "Удар ногой в голову!"
```suggestion
	name = "Пинок в голову!"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/head_kick.dm
> +		target.visible_message("<span class='warning'>[user] с разворота ударил[genderize_ru(user.gender,"","а","о","и")] [target] ногой в голову!</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] с разворота пина[pluralize_ru(user.gender,"ет","ют")] [target] в голову!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/stomach_knee.dm
> +	combo_text_override = "Grab, Сменить руки, Harm"
```suggestion
	combo_text_override = "Захват, смена рук, захват"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/wrist_wrench.dm
> +		target.visible_message("<span class='warning'>[user] схватил[genderize_ru(user.gender,"","а","о","и")] запястье [target] и выворачива[pluralize_ru(user.gender,"ет","ют")] его в неправильную сторону
```suggestion
		target.visible_message("<span class='warning'>[user] схватил[genderize_ru(user.gender,"","а","о","и")] запястье [target] и выворачива[pluralize_ru(user.gender,"ет","ют")] его назад!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/sleeping_carp/wrist_wrench.dm
> +						  "<span class='userdanger'>[user] схватил[genderize_ru(user.gender,"","а","о","и")] тебя за запястье и яростно вывернул[genderize_ru(user.gender,"","а","о","и")] его в неправильную сторону изг
```suggestion
						  "<span class='userdanger'>[user] схватил[genderize_ru(user.gender,"","а","о","и")] вас за запястье и яростно вывернул[genderize_ru(user.gender,"","а","о","и")] его назад!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/synthojitsu/lock.dm
> +	name = "Заблокировать"
```suggestion
	name = "Зажим"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/synthojitsu/lock.dm
> +	explaination_text = "Позволяет пользователю быстро захватить противника."
```suggestion
	explaination_text = "Позволяет быстро захватить оппонента."
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/synthojitsu/overload.dm
> +	name = "Перезагрузка"
```suggestion
	name = "Перегрузка"
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/synthojitsu/reanimate.dm
> +		to_chat(user, "<span class='notice'>[target] глубоко вдохнул[genderize_ru(user.gender,"","а","о","и")]!</span>")
```suggestion
		to_chat(user, "<span class='notice'>[target] глубоко вдыха[pluralize_ru(user.gender,"ет","ют")]!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/synthojitsu/overload.dm
> +	target.visible_message("<span class='warning'>[user] ударил[genderize_ru(user.gender,"","а","о","и")] током [target]!</span>", \
```suggestion
	target.visible_message("<span class='warning'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] током [target]!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/synthojitsu/overload.dm
> +						"<span class='userdanger'>[user] ударил[genderize_ru(user.gender,"","а","о","и")] вас током!</span>")
```suggestion
						"<span class='userdanger'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] вас током!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/synthojitsu/reanimate.dm
> +		target.visible_message("<span class='warning'>[user] ударил[genderize_ru(user.gender,"","а","о","и")] током [target]!</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] током [target]!</span>", \
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/synthojitsu/reanimate.dm
> +				"<span class='userdanger'>[user] ударил[genderize_ru(user.gender,"","а","о","и")] вас током!</span>")
```suggestion
				"<span class='userdanger'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] вас током!</span>")
```

2022-05-19 03:15 UTC, Ohar commented on code/modules/martial_arts/combos/synthojitsu/reanimate.dm
> +		to_chat(user, "<span class='notice'>[target] не требует ударом тока. Прервано...</span>")
```suggestion
		to_chat(user, "<span class='notice'>[target] больше не требуется бить током. Отмена…</span>")
```

2022-05-25 14:46 UTC, PhantornRU commented
Одобрено Авоутом
https://discord.com/channels/617003227182792704/755125334097133628/978973826106916915

2022-05-25 16:02 UTC, PhantornRU commented on code/modules/martial_arts/brawling.dm
> +								"<span class='userdanger'>[D] нокаутирован[genderize_ru(D.gender,"","а","о","ы")]  [A] мощным ударом в челюсть!</span>")
```suggestion
								"<span class='userdanger'>[A] нокаутировал[genderize_ru(A.gender,"","а","о","и")] [D] мощным ударом в челюсть!</span>")
```

2022-05-25 16:03 UTC, PhantornRU commented on code/modules/martial_arts/brawling.dm
> +								"<span class='userdanger'>[D] нокаутирован[genderize_ru(D.gender,"","а","о","ы")] [A] мощным пьяным ударом!</span>")
```suggestion
								"<span class='userdanger'>[A] нокаутировал[genderize_ru(A.gender,"","а","о","и")] [D] мощным пьяным ударом!</span>")
```

2022-05-25 16:03 UTC, PhantornRU commented on code/modules/martial_arts/brawling.dm
> +			D.visible_message("<span class='danger'>[A] нокаутировал[genderize_ru(A.gender,"","а","о","и")]  [D] мощным ударом в челюсть!</span>", \
```suggestion
			D.visible_message("<span class='danger'>[A] нокаутировал[genderize_ru(A.gender,"","а","о","и")] [D] мощным ударом в челюсть!</span>", \
```

2022-05-25 16:09 UTC, PhantornRU commented on code/modules/martial_arts/combos/mimejutsu/smokebomb.dm
> +	explaination_text = "Бросить пантомимовую дымовую шашку."
Оставлю пока "пантомиму" для будущего ПРа с мимдзюцу и там уже сделаю нормальные переводы.

2022-05-25 16:10 UTC, PhantornRU commented on code/modules/martial_arts/combos/plasma_fist/plasma_fist.dm
> +	steps = list(MARTIAL_COMBO_STEP_HARM, MARTIAL_COMBO_STEP_DISARM, MARTIAL_COMBO_STEP_DISARM, MARTIAL_COMBO_STEP_DISARM, MARTIAL_COMBO_STEP_GRAB, MARTIAL_COMBO_STEP_HARM)
Это первая наработка была для будущего ПРа с переработкой плазменного кулака.
Комбо еще будет переделываться.

2022-05-25 16:11 UTC, PhantornRU commented on code/modules/martial_arts/combos/plasma_fist/throwback.dm
> +	target.throw_at(throw_target, 10, 4, user)
Пересмотрю в ПРе плазменного кулака. Это было временное значение для теста

2022-05-25 16:12 UTC, PhantornRU commented on code/modules/martial_arts/combos/plasma_fist/throwback.dm
> +	user.say("ХЬЙА!")
"Кийа" используются в других боевых искусствах. Так как Плазменный кулак нацелен на дыхалку и обжигающий урон. У него будут высказывания при ударах включающих в себя букву "Х", якобы он выдыхает фразы.

2022-05-25 16:13 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +			user.say(pick("СУРПРАЙЗО!","УДАР В СПИНУ!","ВУОПХАА!", "ВУАТАА", "ЗУОТАА!", "ОБЕРНИСЬ!", "СЛЕДИ ЗА ТЫЛОМ!", "ПОДЗАТЫЛЬНИК!", "Никогда не показывай спину!", "Не поворачивайся спиной к врагу!", "Теб
А вот это мощно xD

2022-05-25 16:14 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +	name = "Выпад Элбоу"
Данный момент тогда поправлю сразу и на вики, т.к. название брал оттуда

2022-05-25 16:28 UTC, PhantornRU commented on code/modules/martial_arts/combos/plasma_fist/tornado_sweep.dm
> +	name = "Кручение Торнадо"
Масло масленное, поэтому и отказался от этого. Но пускай.
```suggestion
	name = "Вихрь Торнадо"
```

2022-05-25 16:31 UTC, PhantornRU commented on code/modules/martial_arts/combos/plasma_fist/tornado_sweep.dm
> +	explaination_text = "Отталкивает цель и все что рядом."
```suggestion
	explaination_text = "Отталкивает оппонента и всех вокруг."
```

2022-05-25 16:32 UTC, PhantornRU commented on code/modules/martial_arts/combos/plasma_fist/tornado_sweep.dm
> +	user.say("КРУЧЕНОЕ ТОРНАДО!")
Оставлю как есть на будущее переделывание названия для приема в следующем ПРе.

2022-05-25 16:33 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +	explaination_text = "Оппонент должен быть отвернут. Сбивает его с ног."
```suggestion
	explaination_text = "Используется только сзади. Сбивает оппонента с ног."
```

2022-05-25 16:34 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/back_kick.dm
> +			user.say(pick("СУРПРАЙЗО!","УДАР В СПИНУ!","ВУОПХАА!", "ВУАТАА", "ЗУОТАА!", "ОБЕРНИСЬ!", "СЛЕДИ ЗА ТЫЛОМ!", "ПОДЗАТЫЛЬНИК!", "Никогда не показывай спину!", "Не поворачивайся спиной к врагу!", "Теб
```suggestion
			user.say(pick("СУРПРАЙЗО!","УДАР В СПИНУ!","УДАР В ПСИНУ!","ВУОПХАА!", "ВУАТАА", "ЗУОТАА!", "ОБЕРНИСЬ!", "СЗАДИ!", "СЛЕДИ ЗА ТЫЛОМ!", "ПОДЗАТЫЛЬНИК!", "ПЕНДЕЛЬ!", "Никогда не показывай спину!", "Не поворачивайся спиной к врагу!", "Тебе передали привет!", "Я передаю привет!"))
```

2022-05-25 16:35 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +	name = "Выпад Элбоу"
```suggestion
	name = "Локтевой выпад"
```

2022-05-25 16:35 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +		target.visible_message("<span class='warning'>[user] падением сверху наносит решающий удар локтем по [target]!</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] в прыжке сверху наносит решающий удар локтем по [target]!</span>", \
```

2022-05-25 16:35 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +						  "<span class='userdanger'>[user] добива[pluralize_ru(user.gender,"ет","ют")] вас решающим ударом локтем сверху!</span>") //[user.p_their()]
```suggestion
						  "<span class='userdanger'>[user] в прыжке добива[pluralize_ru(user.gender,"ет","ют")] вас коронным локтевым выпадом!</span>") 
```

2022-05-25 16:36 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/elbow_drop.dm
> +			user.say(pick("БАНЗАИИИИ!", "КИЙААААА!", "OMAE WA MOU SHINDEIRU!", "ЗАДЕРЖИ ДЫХАНИЕ!", "ТЫ БОЛЬШЕ НЕ УВИДИШЬ МЕНЯ!", "ПРИШЛО МОЕ ВРЕМЯ!", "КАВАБАНГА!", "ИСПУСКАЙ ДУХ!"))
```suggestion
			user.say(pick("БАНЗАИИИИ!", "КИЙААААА!", "ОМАЕВА МО ШИНДЕРУ!", "ЗАДЕРЖИ ДЫХАНИЕ!", "ТЫ МЕНЯ БОЛЬШЕ НЕ УВИДИШЬ!", "ПРИШЛО МОЁ ВРЕМЯ!", "КАВАБАНГА!", "ИСПУСКАЙ ДУХ!"))
```

2022-05-25 16:36 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/head_kick.dm
> +	name = "Удар ногой в голову!"
```suggestion
	name = "Пинок в голову!"
```

2022-05-25 16:37 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/head_kick.dm
> +		target.visible_message("<span class='warning'>[user] с разворота ударил[genderize_ru(user.gender,"","а","о","и")] [target] ногой в голову!</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] с разворота пина[pluralize_ru(user.gender,"ет","ют")] [target] в голову!</span>", \
```

2022-05-25 16:38 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/stomach_knee.dm
> +	combo_text_override = "Grab, Сменить руки, Harm"
```suggestion
	combo_text_override = "Захват, смена рук, захват"
```

2022-05-25 16:38 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/wrist_wrench.dm
> +		target.visible_message("<span class='warning'>[user] схватил[genderize_ru(user.gender,"","а","о","и")] запястье [target] и выворачива[pluralize_ru(user.gender,"ет","ют")] его в неправильную сторону
```suggestion
		target.visible_message("<span class='warning'>[user] схватил[genderize_ru(user.gender,"","а","о","и")] запястье [target] и выворачива[pluralize_ru(user.gender,"ет","ют")] его назад!</span>", \
```

2022-05-25 16:39 UTC, PhantornRU commented on code/modules/martial_arts/combos/sleeping_carp/wrist_wrench.dm
> +						  "<span class='userdanger'>[user] схватил[genderize_ru(user.gender,"","а","о","и")] тебя за запястье и яростно вывернул[genderize_ru(user.gender,"","а","о","и")] его в неправильную сторону изг
```suggestion
						  "<span class='userdanger'>[user] схватил[genderize_ru(user.gender,"","а","о","и")] вас за запястье и яростно вывернул[genderize_ru(user.gender,"","а","о","и")] его назад!</span>")
```

2022-05-25 16:39 UTC, PhantornRU commented on code/modules/martial_arts/combos/synthojitsu/lock.dm
> +	name = "Заблокировать"
```suggestion
	name = "Зажим"
```

2022-05-25 16:39 UTC, PhantornRU commented on code/modules/martial_arts/combos/synthojitsu/lock.dm
> +	explaination_text = "Позволяет пользователю быстро захватить противника."
```suggestion
	explaination_text = "Позволяет быстро захватить оппонента."
```

2022-05-25 16:40 UTC, PhantornRU commented on code/modules/martial_arts/combos/synthojitsu/overload.dm
> +	name = "Перезагрузка"
```suggestion
	name = "Перегрузка"
```

2022-05-25 16:40 UTC, PhantornRU commented on code/modules/martial_arts/combos/synthojitsu/overload.dm
> +	target.visible_message("<span class='warning'>[user] ударил[genderize_ru(user.gender,"","а","о","и")] током [target]!</span>", \
```suggestion
	target.visible_message("<span class='warning'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] током [target]!</span>", \
```

2022-05-25 16:41 UTC, PhantornRU commented on code/modules/martial_arts/combos/synthojitsu/overload.dm
> +						"<span class='userdanger'>[user] ударил[genderize_ru(user.gender,"","а","о","и")] вас током!</span>")
```suggestion
						"<span class='userdanger'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] вас током!</span>")
```

2022-05-25 16:41 UTC, PhantornRU commented on code/modules/martial_arts/combos/synthojitsu/reanimate.dm
> +		to_chat(user, "<span class='notice'>[target] глубоко вдохнул[genderize_ru(user.gender,"","а","о","и")]!</span>")
```suggestion
		to_chat(user, "<span class='notice'>[target] глубоко вдыха[pluralize_ru(user.gender,"ет","ют")]!</span>")
```

2022-05-25 16:41 UTC, PhantornRU commented on code/modules/martial_arts/combos/synthojitsu/reanimate.dm
> +		target.visible_message("<span class='warning'>[user] ударил[genderize_ru(user.gender,"","а","о","и")] током [target]!</span>", \
```suggestion
		target.visible_message("<span class='warning'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] током [target]!</span>", \
```

2022-05-25 16:42 UTC, PhantornRU commented on code/modules/martial_arts/combos/synthojitsu/reanimate.dm
> +				"<span class='userdanger'>[user] ударил[genderize_ru(user.gender,"","а","о","и")] вас током!</span>")
```suggestion
				"<span class='userdanger'>[user] бь[pluralize_ru(user.gender,"ёт","ют")] вас током!</span>")
```

2022-05-25 16:42 UTC, PhantornRU commented on code/modules/martial_arts/combos/synthojitsu/reanimate.dm
> +		to_chat(user, "<span class='notice'>[target] не требует ударом тока. Прервано...</span>")
```suggestion
		to_chat(user, "<span class='notice'>[target] больше не требуется бить током. Отмена…</span>")
```

2022-05-25 16:58 UTC, PhantornRU commented
Правки внесены

2022-05-25 20:44 UTC, TrashDoxx commented
Не заливать, попозже отсмотрю. По диагонали уже вижу косяки.

2022-05-26 03:01 UTC, PhantornRU commented on code/modules/martial_arts/combos/synthojitsu/reanimate.dm
> +		to_chat(user, "<span class='notice'>[target] глубоко вдохнул[genderize_ru(user.gender,"","а","о","и")]!</span>")
```suggestion
		to_chat(user, "<span class='notice'>[target] глубоко вдыха[pluralize_ru(user.gender,"ет","ют")]!</span>")
```

2022-05-29 16:49 UTC, TrashDoxx approved these changes
Слишком мало мотивации сейчас пялиться в код. Как-нибудь в другой раз.

2022-05-29 16:50 UTC, TrashDoxx commented
@Ohar Досмотри ту треть, что оставил на потом. Если есть возможность, конечно.

2022-05-29 17:07 UTC, PhantornRU commented
> Слишком мало мотивации сейчас пялиться в код. Как-нибудь в другой раз.

Да ты издеваешься xD

За что ты мне даешь ложные надежды?)

2022-05-29 18:10 UTC, Ohar requested changes

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/wrestling.dm
> +	set name = "Вспомнить Уроки"
```suggestion
	set name = "Вспомнить уроки"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/wrestling.dm
> +	to_chat(usr, "<b><i>Вы напрягаете мускулы и испытываете озарение...</i></b>")
```suggestion
	to_chat(usr, "<b><i>Вы напрягаете мускулы и испытываете озарение…</i></b>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/wrestling.dm
> +	to_chat(usr, "<span class='notice'>Клинч</span>: Схватить. Дает пассивный шанс немедленно взять в агрессивный захват. Не всегда успешно.")
```suggestion
	to_chat(usr, "<span class='notice'>Клинч</span>: Схватить. Даёт пассивный шанс немедленно взять в агрессивный захват. Не всегда успешно.")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/wrestling.dm
> +	to_chat(usr, "<span class='notice'>Суплекс</span>: Обезоружьте того, кого захватываете, захватывая в суплекс на полу. Сильно ранит вашу цель, оставляя её и вас на полу.")
```suggestion
	to_chat(usr, "<span class='notice'>Суплекс</span>: Обезоружьте того, кого хватаете, захватывая в суплекс на полу. Сильно ранит вашу цель, оставляя её и вас на полу.")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/wrestling.dm
> +	to_chat(usr, "<span class='notice'>Продвинутый захват</span>: Захват. Пассивно наносит урон выносливосте сопернику при попытках захвата.")
```suggestion
	to_chat(usr, "<span class='notice'>Продвинутый захват</span>: Захват. Пассивно наносит урон выносливости оппонента при попытках захвата.")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/wrestling.dm
> +	D.visible_message("<span class='danger'>[A] захватыва[pluralize_ru(A.gender,"ет","ют")] [D]!</span>", \
**Захватывают** заложников или конечности, а людей в драке **хватают**.
```suggestion
	D.visible_message("<span class='danger'>[A] хвата[pluralize_ru(A.gender,"ет","ют")] [D]!</span>", \
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/wrestling.dm
> +	D.visible_message("<span class='danger'>[A] бер[pluralize_ru(A.gender,"ет","ут")] в суплекс [D]!</span>", \
```suggestion
	D.visible_message("<span class='danger'>[A] бер[pluralize_ru(A.gender,"ёт","ут")] в суплекс [D]!</span>", \
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/wrestling.dm
> +		D.visible_message("<span class='danger'>[A] бер[pluralize_ru(A.gender,"ет","ут")] [D] в клинч!</span>", \
```suggestion
		D.visible_message("<span class='danger'>[A] бер[pluralize_ru(A.gender,"ёт","ут")] [D] в клинч!</span>", \
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/synthojitsu.dm
> +		desc = "Продвинутая база данных совместимая с позитронными системами. Хранит в себе алгоритмы ближнего боя и протоколы переписывания безопасности микробатарей. Жестко заблокировано."
```suggestion
		desc = "Продвинутая база данных, совместимая с позитронными системами. Содержит алгоритмы ближнего боя и процедуры перезаписи протоколов безопасности микробатарей. Стоит блокировка."
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/synthojitsu.dm
> +		to_chat(H, "<span class='boldannounce'>Алгоритмы ближнего боя установлены. Безопасность отключена.</span>")
```suggestion
		to_chat(H, "<span class='boldannounce'>Алгоритмы ближнего боя установлены. Протоколы безопасности отключены.</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/synthojitsu.dm
> +	to_chat(user, "<span class='notice'>Инициализирована установка. Ожидание завершения работы...</span>")
```suggestion
	to_chat(user, "<span class='notice'>Начата установка. Ожидание завершения работы…</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/synthojitsu.dm
> +	name = "боевое улучшение IPC"
```suggestion
	name = "боевое улучшение КПБ
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/synthojitsu.dm
> +	desc = "Продвинутая база данных совместимая с позитронными системами. Хранит в себе алгоритмы ближнего боя и протоколы переписывания безопасности микробатарей."
```suggestion
	desc = "Продвинутая база данных, совместимая с позитронными системами. Содержит алгоритмы ближнего боя и процедуры перезаписи протоколов безопасности микробатарей."
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/sleeping_carp.dm
> +	to_chat(usr, "<b><i>Вы погружаетесь в свое сознание и вспоминаете учения Спящего Карпа...</i></b>")
```suggestion
	to_chat(usr, "<b><i>Вы погружаетесь в глубины своей памяти и вспоминаете учение Спящего карпа…</i></b>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/sleeping_carp.dm
> +	name = "Спящий Карп"
```suggestion
	name = "Спящий карп"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/plasma_fist.dm
> +	to_chat(user, "<b><i>Вы сжимаете кулаки и вас навевают воспоминания...</i></b>")
```suggestion
	to_chat(user, "<b><i>Вы сжимаете кулаки и вас озаряют воспоминания…</i></b>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/plasma_fist.dm
> +	name = "Плазменный Кулак"
```suggestion
	name = "Плазменный кулак"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/mimejutsu.dm
> +		desc = "Похоже к нему что-то было прикреплено скобой степлера..."
```suggestion
		desc = "Похоже, к нему что-то было приколото степплером…"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/mimejutsu.dm
> +		to_chat(H, "<span class='boldannounce'>Вы изучили древнее боевое искусство пантомимы...</span>")
```suggestion
		to_chat(H, "<span class='boldannounce'>Вы изучили древнее боевое искусство пантомимы…</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/mimejutsu.dm
> +	name = "Берет мастера Мимдзюцу"
```suggestion
	name = "Берет мастера мимдзюцу"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/mimejutsu.dm
> +	desc =	"Берет, к которому степлером прикреплена старая записка..."
```suggestion
	desc =	"Берет, к которому степлером прикреплена старая записка…"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +		to_chat(user, "<span class ='warning'>Вы бьете себя по голове [src.name].</span>")
```suggestion
		to_chat(user, "<span class ='warning'>Вы бьёте себя по голове [src.name].</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	name = "бо посох"
```suggestion
	name = "бо"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	desc = "Небольшой черный мануал. В нём нарисованы инструкции тактического рукопашного боя."
```suggestion
	desc = "Небольшой чёрный мануал. Он полон рисованных инструкций по тактике рукопашного боя."
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	name = "Старый мануал"
```suggestion
	name = "старый мануал"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	visible_message("<span class='warning'>[src.name] вспыхнул пламенем и сгорел до тла.</span>")
```suggestion
	visible_message("<span class='warning'>[src.name] вспыхивает пламенем и сгорает дотла.</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	to_chat(user, "<span class='sciradio'>Вы изучили древнее искусство Спящего Карпа! \
```suggestion
	to_chat(user, "<span class='sciradio'>Вы изучили древнее искусство Спящего карпа! \
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +					Ваши рукопашные навыки стали более эффективными, способные отразить любой пущеный в вас снаряд. \
```suggestion
					Ваши рукопашные навыки стали эффективнее, вы теперь способны отражать любые пущенные в вас снаряды. \
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +					Вы можете узнать больше о древнем искусстве нажав Recall во вкладке Sleeping Carp</span>")
```suggestion
					Вы можете узнать больше об этом древнем искусстве, нажав <kbd>Recall</kbd> во вкладке <kbd>Sleeping Carp</kbd>.</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	name = "Загадочный свиток"
```suggestion
	name = "загадочный свиток"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +		to_chat(H, "<span class='boldannounce'>Вы изучили древнее искусство Плазменного Кулака</span>")
```suggestion
		to_chat(H, "<span class='boldannounce'>Вы изучили древнее искусство Плазменного кулака</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	desc = "Старый и потертый клочок бумаги, исписанный изменчивыми рунами. С рисованные иллюстрации кулачного боя."
```suggestion
	desc = "Старый потёртый клочок бумаги, исписанный меняющимися рунами. На нём изображены рисованные иллюстрации кулачного боя."
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +		to_chat(user, "<span class='sciradio'>Ваши мышцы напряглись и желают драки. Вы заигрываете вашими мускулами! Вам известны знания тысячи предшествующих бойцов до вас. Вы можете запомнить больше испо
```suggestion
		to_chat(user, "<span class='sciradio'>Вы поигрываете мускулами! Они напряжены и желают драки. Вам известны знания тысяч предшествующих вам бойцов. Подробности можно вспомнить, используя <kbd>Recall</kbd> во вкладке <kbd>Wrestling</kbd>.</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	name = "Борцовский Пояс"
```suggestion
	name = "Борцовский пояс"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	set name = "Показать Информацию"
```suggestion
	set name = "Показать информацию"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	set desc = "Получить информациб о изученых тобой боевых искусствах"
```suggestion
	set desc = "Получить информацию о изученных тобой боевых искусствах"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	set category = "Боевые Искусства"
```suggestion
	set category = "Боевые искусства"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	var/name = "Боевые Искусства"
```suggestion
	var/name = "Боевые искусства"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/krav_maga.dm
> +	name = "Перчатки Крав Мага"
```suggestion
	name = "Перчатки крав-маги"
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/krav_maga.dm
> +	desc = "Наночипы печаток позволят вам овладеть искусством Крав Мага."
```suggestion
	desc = "Наночипы печаток позволят вам овладеть искусством Крав-мага."
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/krav_maga.dm
> +	to_chat(H, "<span class = 'userdanger'>Вы забываете искусство Крав Мага...</span>")
```suggestion
	to_chat(H, "<span class = 'userdanger'>Вы забываете искусство Крав-мага…</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/krav_maga.dm
> +	to_chat(H, "<span class = 'userdanger'>Вами изучено искусство Крав Мага!</span>")
```suggestion
	to_chat(H, "<span class = 'userdanger'>Вами изучено искусство Крав-мага!</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/krav_maga.dm
> +		to_chat(owner, "<span class='warning'>Вы не можете использовать Крав Мага пока выведены из строя.</span>")
```suggestion
		to_chat(owner, "<span class='warning'>Вы не можете использовать Крав-мага, пока вы выведены из строя.</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/krav_maga.dm
> +	name = "Удар под дых - наносит сильный удар под дых, сдавливая лёгкие, отчего жертва временно не может дышать."
```suggestion
	name = "Удар под дых — наносит сильный удар под дых, сдавливая лёгкие, отчего оппонент временно не может дышать."
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/krav_maga.dm
> +		to_chat(owner, "<span class='warning'>Вы не можете использовать Крав Мага пока выведены из строя.</span>")
```suggestion
		to_chat(owner, "<span class='warning'>Вы не можете использовать Крав-мага, пока вы выведены из строя.</span>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/krav_maga.dm
> +	name = "Удар по горлу - Повреждает шею, временно лишая жертву возможности говорить."
```suggestion
	name = "Удар в горло — повреждает шею, временно лишая жертву возможности говорить."
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/krav_maga.dm
> +	to_chat(owner, "<b><i>Ваша следующая атака будет Ударом в Горло.</i></b>")
```suggestion
	to_chat(owner, "<b><i>Ваша следующая атака будет Ударом в горло.</i></b>")
```

2022-05-29 18:10 UTC, Ohar commented on code/modules/martial_arts/krav_maga.dm
> +		to_chat(owner, "<span class='warning'>Вы не можете использовать Крав Мага пока выведены из строя.</span>")
```suggestion
		to_chat(owner, "<span class='warning'>Вы не можете использовать Крав-мага пока выведены из строя.</span>")
```

2022-05-29 18:12 UTC, Ohar commented
@TrashDoxx Досмотрел
@PhantornRU Ещё 40+ правок

2022-05-29 18:22 UTC, PhantornRU commented
> @TrashDoxx Досмотрел
> @PhantornRU Ещё 40+ правок

Спасибо)
Правки внёс.

По сути дела судя по правкам уже ничего из косяков толком не осталось. Надеюсь... Столько уже мутузим пр.
Ибо основные замены "е" на "ё" которые я так забываю.

2022-05-29 18:41 UTC, Ohar approved these changes

2022-05-30 02:28 UTC, PhantornRU commented
@Bizzonium 3/3 одобрено, голосование пройдено. Прошу замержить.

2022-06-03 04:28 UTC, PhantornRU commented
Скоро пройдет месяц, ждем мержа

2022-06-06 01:19 UTC, merged