Малый перевод взаимодействий и действий МОБов, кукол
ss220-space/Paradise pull request #885
Opened 2022-05-13 14:57 UTC by PhantornRU

Перевод:
- отталкиваний
- блокирования передвижения
- грабы, захваты, вырывание из захватов
- некоторые действия: Отдых, вставание, сон, выбор имени для роли.
- описание действий со снаряжением
- перевод блевания
- перевод сержанта Аранеуса
- перевод кенгуру и его пинка

2022-05-14 07:48 UTC, Vallat requested changes

2022-05-14 07:48 UTC, Vallat commented on code/modules/mob/mob_grab.dm
> +				to_chat(user, "<span class='warning'>[affecting] пристегнут[genderize_ru(affecting.gender,"","а","о","и")]!</span>")
```suggestion
				to_chat(user, "<span class='warning'>[affecting] пристегнут[genderize_ru(affecting.gender,"","а","о","ы")]!</span>")
```

2022-05-14 08:29 UTC, Vallat approved these changes

2022-05-14 14:55 UTC, TrashDoxx commented
Пока не мержить. Отсматриваю перевод.

2022-05-14 15:56 UTC, TrashDoxx requested changes

2022-05-14 15:56 UTC, TrashDoxx commented on code/modules/mob/living/simple_animal/hostile/retaliate/pet.dm
> +	desc = "Свирепый компаньон любого влиятельного лица, этот паук был тщательно обучен специалистами Нанотрасен. Его пристальные глаза-бусинки вызывают мурашки у вас по спине."
```suggestion
	desc = "Свирепый компаньон любого влиятельного лица, этот паук был тщательно обучен специалистами NanoTrasen. Его пристальные глаза-бусинки вызывают мурашки у вас по спине."
```
Согласно правилам перевода, название корпорации записывается оригинальным образом, на латинице.

2022-05-14 15:56 UTC, TrashDoxx commented on code/modules/mob/mob.dm
> +		to_chat(src, "<I>... Вы почти можете слышите чей-то разговор ...</I>")
```suggestion
		to_chat(src, "<I>... Вам почти что удаётся расслышать чей-то разговор...</I>")
```

2022-05-14 15:56 UTC, TrashDoxx commented on code/modules/mob/mob_grab.dm
> +		assailant.visible_message("<span class='warning'>[assailant] усиленно хвата[pluralize_ru(assailant.gender,"ет","ют")] [affecting] (за шею)!</span>") // [assailant.p_their()]
```suggestion
		assailant.visible_message("<span class='warning'>[assailant] крепко хвата[pluralize_ru(assailant.gender,"ет","ют")] [affecting] (за шею)!</span>") // [assailant.p_their()]
```

2022-05-14 15:56 UTC, TrashDoxx commented on code/modules/mob/mob_grab.dm
> +		assailant.visible_message("<span class='danger'>[assailant] начина[pluralize_ru(assailant.gender,"ет","ют")] крепко сдавливать шею [affecting]!</span>") //[assailant.p_their()]
```suggestion
		assailant.visible_message("<span class='danger'>[assailant] начина[pluralize_ru(assailant.gender,"ет","ют")] сдавливать шею [affecting]!</span>") //[assailant.p_their()]
```

2022-05-14 15:56 UTC, TrashDoxx commented on code/modules/mob/mob_grab.dm
> +		assailant.visible_message("<span class='danger'>[assailant] крепко сжал[genderize_ru(assailant.gender,"","а","о","и")] шею [affecting]!</span>") //[assailant.p_their()]
```suggestion
		assailant.visible_message("<span class='danger'>[assailant] сдавил[genderize_ru(assailant.gender,"","а","о","и")] шею [affecting]!</span>") //[assailant.p_their()]
```

2022-05-14 15:56 UTC, TrashDoxx commented on code/modules/mob/mob_grab.dm
> +				to_chat(user, "<span class='warning'>[affecting] пристегнут[genderize_ru(affecting.gender,"","а","о","и")]!</span>")
```suggestion
				to_chat(user, "<span class='warning'>[affecting] пристегнут[genderize_ru(affecting.gender,"","а","о","ы")]!</span>")
```

2022-05-14 15:56 UTC, TrashDoxx commented on code/modules/mob/mob_grab.dm
> +				to_chat(user, "<span class='warning'>[affecting] пристегнут[genderize_ru(affecting.gender,"","а","о","ы")]!</span>")
Не понял, зачем здесь дублируется код, ну да ладно.

2022-05-14 15:56 UTC, TrashDoxx commented on code/modules/mob/mob_helpers.dm
> +				alert(src, "К сожалению, для выбора имени 3 минуты прошло. Если вы робот, используйте Namepick verb; иначе, Adminhelp.", "Name Change")
```suggestion
				alert(src, "К сожалению, время для выбора имени кончилось. Если вы робот, используйте Namepick verb; иначе, Adminhelp.", "Name Change")
```

2022-05-14 15:56 UTC, TrashDoxx commented on code/modules/mob/mob_movement.dm
> +			to_chat(C, "<span class='notice'>Ваши ноги связаны! Вы не можете бежать пока не снимете [C.legcuffed]!</span>")
```suggestion
			to_chat(C, "<span class='notice'>Ваши ноги скованы! Вы не можете бежать, пока не снимете [C.legcuffed]!</span>")
```

2022-05-15 00:36 UTC, PhantornRU commented on code/modules/mob/mob_grab.dm
> +				to_chat(user, "<span class='warning'>[affecting] пристегнут[genderize_ru(affecting.gender,"","а","о","ы")]!</span>")
С драками и парадайзом такое очень часто.

2022-05-19 02:27 UTC, Ohar requested changes
Накидал кучу придирок и исправлений

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/living/simple_animal/hostile/retaliate/kangaroo.dm
> +	L.visible_message("<span class='danger'>[L] сильно пинает!</span>", "<span class='userdanger'>Пинок [name] отправил вас в полет!</span>")
```suggestion
	L.visible_message("<span class='danger'>[L] сильно пинает!</span>", "<span class='userdanger'>Пинок [name] посылает вас в полёт!</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/living/simple_animal/hostile/retaliate/pet.dm
> +	name = "Сержант Аранеус"
```suggestion
	name = "Сержант Арахний"
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/living/simple_animal/hostile/retaliate/pet.dm
> +	real_name = "Сержант Аранеус"
```suggestion
	real_name = "Сержант Арахний"
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/living/simple_animal/hostile/retaliate/pet.dm
> +	desc = "Свирепый компаньон любого влиятельного лица, этот паук был тщательно обучен специалистами NanoTrasen. Его пристальные глаза-бусинки вызывают мурашки у вас по спине."
```suggestion
	desc = "Свирепый компаньон любого влиятельного лица, этот паук был тщательно обучен специалистами NanoTrasen. От пристального взгляда его глаз-бусинок у вас по спине бегают мурашки."
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +		to_chat(src, "<I>... Вам почти что удаётся расслышать чей-то разговор...</I>")
```suggestion
		to_chat(src, "<I>…Вам почти удаётся расслышать чьи-то слова…</I>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +				to_chat(src, "<span class='warning'>Вы не можете это экипировать.</span>")//Only print if del_on_fail is false
```suggestion
				to_chat(src, "<span class='warning'>Вы не можете это надеть.</span>")//Only print if del_on_fail is false
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +						to_chat(H, "<span class='warning'>Вам нужен комбинезон перед тем как вы сможете прикрепить [name].</span>")
```suggestion
						to_chat(H, "<span class='warning'>Наденьте комбинезон, чтобы навесить [name] на него.</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +						to_chat(H, "<span class='warning'>Вам нужен комбинезон перед тем как вы сможете прикрепить [name].</span>")
```suggestion
						to_chat(H, "<span class='warning'>Наденьте комбинезон, чтобы прикрепить к нему [name].</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +						to_chat(H, "<span class='warning'>Вам нужен комбинезон перед тем как вы сможете прикрепить [name].</span>")
```suggestion
						to_chat(H, "<span class='warning'>Наденьте комбинезон, чтобы положить [name] в карман.</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +						to_chat(H, "<span class='warning'>Вам нужен комбинезон перед тем как вы сможете прикрепить [name].</span>")
```suggestion
						to_chat(H, "<span class='warning'>Наденьте комбинезон, чтобы положить [name] в карман.</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +						to_chat(H, "<span class='warning'>Вам нужен костюм перед тем как вы сможете прикрепить [name].</span>")
```suggestion
						to_chat(H, "<span class='warning'>Наденьте верхнюю одежду, чтобы положить [name] в карман.</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +						to_chat(usr, "[name] слишком большой, чтобы прикрепить.")
```suggestion
						to_chat(usr, "[name] слишком большого размера и не влезает в карман верхней одежды.")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +		to_chat(src, "<span class='notice'>Что-то здесь есть, но вы не можете разглядеть.</span>")
```suggestion
		to_chat(src, "<span class='notice'>Здесь что-то есть, но вы не видите — что именно.</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +				visible_message("<span class='warning'>[src.name] вырвало зеленой липкой массой!</span>","<span class='warning'>Вас вырвало зеленой липкой массой!</span>")
```suggestion
				visible_message("<span class='warning'>[src.name] вырвало зелёной липкой массой!</span>","<span class='warning'>Вас вырвало зелёной липкой массой!</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob.dm
> +				visible_message("<span class='warning'>[src.name] наблевал на себя!</span>","<span class='warning'>Вы наблевали на себя!</span>")
Забыл учесть пол

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_grab.dm
> +			to_chat(assailant, "<span class='notice'>Вы давите на [affecting], но ничего интересного не происходит.</span>")
```suggestion
			to_chat(assailant, "<span class='notice'>Вы сжимаете [affecting], но ничего интересного не происходит.</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_grab.dm
> +		assailant.visible_message("<span class='danger'>[assailant] сдавил[genderize_ru(assailant.gender,"","а","о","и")] шею [affecting]!</span>") //[assailant.p_their()]
```suggestion
		assailant.visible_message("<span class='danger'>[assailant] сдавлива[pluralize_ru(assailant.gender,"ет","ют")] шею [affecting]!</span>") //[assailant.p_their()]
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_grab.dm
> +						assailant.visible_message("<span class='danger'>[assailant] с размаха бь[pluralize_ru(assailant.gender,"ет","ют")] [genderize_ru(assailant.gender,"его","её","своей","их")]  головой о череп [aff
```suggestion
						assailant.visible_message("<span class='danger'>[assailant] с размаха бь[pluralize_ru(assailant.gender,"ёт","ют")] [genderize_ru(assailant.gender,"его","её","своей","их")]  головой о череп [affecting]!</span>") //A visible message for what is going on.
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_grab.dm
> +				to_chat(user, "<span class='warning'>[affecting] пристегнут[genderize_ru(affecting.gender,"","а","о","ы")]!</span>")
```suggestion
				to_chat(user, "<span class='warning'>[affecting] пристёгнут[genderize_ru(affecting.gender,"","а","о","ы")]!</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_grab.dm
> +				to_chat(user, "<span class='warning'>[affecting] пристегнут[genderize_ru(affecting.gender,"","а","о","ы")]!</span>")
```suggestion
				to_chat(user, "<span class='warning'>[affecting] пристёгнут[genderize_ru(affecting.gender,"","а","о","ы")]!</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_helpers.dm
> +		to_chat(src, "<span class='notice'>Вы встали.</span>")
```suggestion
		to_chat(src, "<span class='notice'>Вы встаёте.</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_helpers.dm
>  				newname = clean_input("Pick a new name.", "Name Change", oldname, src)
```suggestion
				newname = clean_input("Выберите новое имя.", "Смена имени", oldname, src)
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_helpers.dm
> +				newname = clean_input("Вы [role]. Не хотите поменять свое имя на другое? (У вас есть 3 минуты для выбора нового имени)", "Name Change", oldname, src)
```suggestion
				newname = clean_input("Вы [role]. Не хотите поменять своё имя на другое? У вас есть 3 минуты для выбора нового имени.", "Смена имени", oldname, src)
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_helpers.dm
> +				alert(src, "К сожалению, время для выбора имени кончилось. Если вы робот, используйте Namepick verb; иначе, Adminhelp.", "Name Change")
```suggestion
				alert(src, "К сожалению, время для выбора имени кончилось. Если вы киборг, используйте команду «Namepick»; иначе — «Adminhelp».", "Смена имени")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_helpers.dm
> +			to_chat(src, "Извини, но имя для роли [role] не подходит. Возможно оно слишком длинное или короткое, содержит плохие наименования или уже занято.")
```suggestion
			to_chat(src, "Извините, но это имя не подходит для роли «[role]». Возможно, оно слишком длинное или короткое, содержит неподходящие символы, либо уже занято.")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_movement.dm
> +		to_chat(usr, "<span class='danger'>Этот тип моба не может бросать предметы.</span>")
```suggestion
		to_chat(usr, "<span class='danger'>Это существо не может бросать предметы.</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_movement.dm
> +					mob.visible_message("<span class='danger'>[mob] вырвал[genderize_ru(mob.gender,"ся","ась","ось","ись")] из хватки [G.assailant]!</span>")
```suggestion
					mob.visible_message("<span class='danger'>[mob] вырыва[pluralize_ru(mob.gender,"ется","ются")] из хватки [G.assailant]!</span>")
```

2022-05-19 02:27 UTC, Ohar commented on code/modules/mob/mob_movement.dm
> +					mob.visible_message("<span class='danger'>[mob] вырвал[genderize_ru(mob.gender,"ся","ась","ось","ись")] из захвата головы [G.assailant]!</span>")
```suggestion
					mob.visible_message("<span class='danger'>[mob] вырыва[pluralize_ru(mob.gender,"ется","ются")] из захвата головы [G.assailant]!</span>")
```

2022-05-25 14:47 UTC, PhantornRU commented
Одобрено Авоутом
https://discord.com/channels/617003227182792704/755125334097133628/978973826106916915

2022-05-25 15:44 UTC, PhantornRU commented on code/modules/mob/mob.dm
> +				visible_message("<span class='warning'>[src.name] наблевал на себя!</span>","<span class='warning'>Вы наблевали на себя!</span>")
```suggestion
				visible_message("<span class='warning'>[src.name] наблевал[genderize_ru(src.gender,"","а","о","и")] на себя!</span>","<span class='warning'>Вы наблевали на себя!</span>")
```

2022-05-25 16:58 UTC, PhantornRU commented
Правки внесены

2022-05-28 16:03 UTC, TrashDoxx approved these changes
Лень ещё раз отсматривать.

2022-05-29 17:06 UTC, merged