Перевод воздействий и дополнение драк куклы
ss220-space/Paradise pull request #886
Opened 2022-05-13 15:02 UTC by PhantornRU

- Перевод тушения руками
- Перевод поглаживаний по голове
- Перевод и дополнение текстового описания объятий
- Перевод повреждений, застревающих объектов
- Перевод состояния куклы
- Перевод ползаний по вентиляции
- Перевод подскальзывания
- Перевод блевания и рвоты (теперь намордник задерживает вашу рвоту в вас)
- Перевод связывание ног/рук
- Переведены броски и опускания на землю.
- Переведена атака блоба вне скриптовых папок с блобом.
- Переведены удары током
- Перевод встрясок лежачего + лежачего ССД
- Перевод состояния лечь/встать

2022-05-14 07:51 UTC, Vallat requested changes

2022-05-14 07:51 UTC, Vallat commented on code/modules/mob/living/living_defense.dm
> +			"<span class='danger'>[src.name] шокирован током [source]!</span>",
током не шокируют

2022-05-14 08:27 UTC, Vallat approved these changes

2022-05-14 14:56 UTC, TrashDoxx commented
Пока не мержить. Отсматриваю перевод.

2022-05-14 16:21 UTC, TrashDoxx requested changes

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/alien/humanoid/humanoid_defense.dm
> +								"<span class='danger'>Вы услышали как кто-то упал.</span>")
```suggestion
								"<span class='danger'>Вы слышите, как кто-то упал.</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +					M.show_message(text("<span class='warning'>Вы слышите как что-то журчит в животе [src.name]...</span>"), 2)
```suggestion
					M.show_message(text("<span class='warning'>Вы слышите как что-то урчит в животе [src.name]...</span>"), 2)
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +						M.show_message(text("<span class='warning'><B>[user] атаку[pluralize_ru(user.gender,"ет","ют")] стенку желудка [src.name] используя [I.name]!</span>"), 2)
```suggestion
						M.show_message(text("<span class='warning'><B>[user] атаку[pluralize_ru(user.gender,"ет","ют")] стенку желудка [src.name], используя [I.name]!</span>"), 2)
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +			to_chat(src, "<span class='warning'>Намордник задерживает вашу рвоту в себе!</span>")
```suggestion
			to_chat(src, "<span class='warning'>Намордник препятствует рвоте!</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +		"<span class='userdanger'>Вы чувствуете электрический разряд проходящий через всё ваше тело!</span>",
```suggestion
		"<span class='danger'>[src.name] получил[genderize_ru(src.gender,"","а","о","и")] разряд током [source]!</span>",
		"<span class='userdanger'>Вы чувствуете электрический разряд проходящий через ваше тело!</span>",
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +				to_chat(src, "<span class='warning'>Ваши глаза щиплят.</span>")
```suggestion
				to_chat(src, "<span class='warning'>Ваши глаза немного щиплет.</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +				to_chat(src, "Глаза сильно щиплят и пылают!</span>")
```suggestion
				to_chat(src, "Глаза сильно чешутся и пылают!</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +			to_chat(src, "<span class='notice'>Что-то яркое промелькнуло в уголке вашего зрения!</span>")
```suggestion
			to_chat(src, "<span class='notice'>Что-то яркое вспыхнуло на периферии вашего зрения!</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +						to_chat(src, "<span class='warning'>Нельзя ползать по вентиляции с предметами</span>")
```suggestion
						to_chat(src, "<span class='warning'>Вы не можете ползать по вентиляции с предметами</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +			visible_message("<b>[src.name] лез[pluralize_ru(src.gender,"ет","ют")] в вентиляционные системы!</b>", "Вы залезли в вентиляционные системы.")
```suggestion
			visible_message("<b>[src.name] лез[pluralize_ru(src.gender,"ет","ют")] в вентиляцию!</b>", "Вы залезли в вентиляцию.")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +				to_chat(src, "<span class='notice'>Вы осторожно опускаете [throwable_mob].</span>")
```suggestion
				to_chat(src, "<span class='notice'>Вы осторожно отпускаете [throwable_mob].</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +				to_chat(src, "<span class='warning'>Вы не можете себя отстегнуть!</span>")
```suggestion
				to_chat(src, "<span class='warning'>Вам не удалось себя отстегнуть!</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +		"<span class='notice'>Вы остановились, упали и катитесь!</span>")
```suggestion
		"<span class='notice'>Вы остановились, упали и катаетесь!</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/carbon/carbon.dm
> +		to_chat(src, "<span class='notice'>Вы пытаетесь избываться от [I]... (Это займет около [time/10] секунд и вам не нужно двигаться.)</span>")
```suggestion
		to_chat(src, "<span class='notice'>Вы пытаетесь избавиться от [I]... (Это займет около [time/10] секунд и вам не нужно двигаться.)</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/living_defense.dm
> +			"<span class='userdanger'>Вы чувствуете электрический разряд проходящий через всё ваше тело!</span>",
```suggestion
			"<span class='danger'>[src.name] получил разряд током [source]!</span>",
			"<span class='userdanger'>Вы чувствуете электрический разряд проходящий через ваше тело!</span>",
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/living_defense.dm
> +							"<span class='userdanger'>[src] был ударен [I].</span>")
```suggestion
			visible_message("<span class='danger'>[src] получил удар [I].</span>",
							"<span class='userdanger'>[src] получил удар [I].</span>")
```

2022-05-14 16:21 UTC, TrashDoxx commented on code/modules/mob/living/living_defense.dm
> +				add_attack_logs(I.thrownby, src, "был ударен брошенным [I]", !I.throwforce ? ATKLOG_ALMOSTALL : null) // Only message if the person gets damages
```suggestion
				add_attack_logs(I.thrownby, src, "получил удар брошенным [I]", !I.throwforce ? ATKLOG_ALMOSTALL : null) // Only message if the person gets damages
```

2022-05-25 14:47 UTC, PhantornRU commented
Одобрено Авоутом
https://discord.com/channels/617003227182792704/755125334097133628/978973948018565161

2022-05-25 19:50 UTC, TrashDoxx approved these changes

2022-05-26 04:55 UTC, dj-34 commented on code/modules/mob/living/carbon/carbon.dm
> +				to_chat(src, "<span class='warning'>Вашы глаза пылают.</span>")
```suggestion
				to_chat(src, "<span class='warning'>Ваши глаза пылают.</span>")
```

2022-05-26 04:59 UTC, dj-34 commented on code/modules/mob/living/carbon/carbon.dm
> +/mob/living/carbon/proc/slip(description, stun, weaken, tilesSlipped, walkSafely, slipAny, slipVerb = "подскользнулись")
```suggestion
/mob/living/carbon/proc/slip(description, stun, weaken, tilesSlipped, walkSafely, slipAny, slipVerb = "поскользнулись")
```

2022-05-26 05:00 UTC, dj-34 approved these changes

2022-05-29 16:25 UTC, merged