Перевод расовых действий
ss220-space/Paradise pull request #888
Opened 2022-05-13 15:19 UTC by PhantornRU

- Перевод [РОСКОМНАДЗОР] действий при прописывании команды /suicide для всех игровых рас (да, даже для скелетов и армалисов)
- Перевод фраз и описаний IPC, в том числе смерти.
- Перевод текстовых описаний возгораний плазмамена, а также акцент речи с заменой "с"/"ш" на "шш"
- Перевод текстовых описаний урона тенелинга
- Перевод тектовых описаний слайма и его восстановительных процессов
- Перевод текстовых описаний врина, его укалывание жалом, отрывание антены

2022-05-13 16:52 UTC, Ohar requested changes
Общее замечание: почти нигде не учтён пол персонажей (не забывай про множественное число).
Строки с названиями органов нужно сильно перестроить или родить способ их склонять. «Вася бьёт вашу голова» - неприемлемый вариант.

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/diona.dm
> +		"растаскивается на части!",
Растаскивается кем?

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/drask.dm
> +		"нагревается самотрением!",
Самотрение лучше заменить на иной словесный оборот
```suggestion
		"трёт себя до возгорания!",
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +		"разбивает свое тело на части!")
Ё пропустил
```suggestion
		"разбивает своё тело на части!")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/kidan.dm
> -
А куда делась проверка конечностей?

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/kidan.dm
> +		"вонзает когти в свои глазницы!",
Замени «свои» на «себе» в обоих случаях

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/kidan.dm
> +		"трескается экзоскелетом!",
```suggestion
		"разбивает свой панцирь",
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/machine.dm
> +	death_message = "издает серию коротких пронзительных звуков, корпус вздрагивает перед тем как отключиться, больше не работоспособно."
```suggestion
	death_message = "издаёт резкие пронзительные звуки и, конвульсивно подёргивая шасси,  окончательно отключается."
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/machine.dm
> +			to_chat(H, "<span class='warning'>Вас прервали, при смене цвета оптики.</span>")
```suggestion
			to_chat(H, "<span class='warning'>Ваша попытка сменить отображаемый цвет была прервана.</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/machine.dm
> +			to_chat(H, "<span class='warning'>Вас прервали, при смене изображения на дисплее.</span>")
Аналогично

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/plasmaman.dm
> +		"осознает экзистенциальную проблему рожденным из плазмы!",
```suggestion
		"осознает экзистенциальную проблему быть рождённым из плазмы!",
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/plasmaman.dm
> +		"показывает свое истинное лицо, которое оказалось цветом плазмы!")
```suggestion
		"показывает свою истинную природу, которая оказывается плазмой!")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/shadow.dm
> +		"выдавливает свои глазницы большими пальцами!",
```suggestion
		"выдавливает большими пальцами себе глазницы!",
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/shadow.dm
> +		to_chat(H, "<span class='notice'>Вы расширяете свой взор, чтобы видеть сквозь тьму.</span>")
```suggestion
		to_chat(H, "<span class='notice'>Вы изменяете свой взор, чтобы видеть сквозь тьму.</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/shadow.dm
> +		to_chat(H, "<span class='notice'>Вы расширяете свой взор, чтобы распознавать тени.</span>")
```suggestion
		to_chat(H, "<span class='notice'>Вы изменяете свой взор, чтобы вновь различать свет и тени.</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/shadowling.dm
> +				to_chat(H, "<span class='userdanger'>Свет обжигает тебя!</span>")//Message spam to say "GET THE FUCK OUT"
```suggestion
				to_chat(H, "<span class='userdanger'>Свет жжёт вас!</span>")//Message spam to say "GET THE FUCK OUT"
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/skeleton.dm
> +		"ломает свои кости!",
```suggestion
		"ломает себе кости!",
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/skrell.dm
> +		"пытается откусить свой язык!",
```suggestion
		"пытается откусить себе язык!",
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/slime.dm
> +		to_chat(H, "Вы настраиваете свою внутреннюю химию, чтобы отфильтровывать пигменты из продуктов, которые вы потребляете.")
```suggestion
		to_chat(H, "Вы настраиваете свою внутреннюю химию, чтобы отфильтровывать пигменты из употребляемых продуктов.")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/slime.dm
> +		to_chat(H, "Вы настраиваете свою внутреннюю химию, чтобы позволить употребленным пигментам в химических веществах, окрасить вас.")
```suggestion
		to_chat(H, "Вы настраиваете свою внутреннюю химию, позволяя окрашивать себя пигментами употребляемых веществ.")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/slime.dm
> +	H.visible_message("<span class='notice'>[H] замирает и концентрируется на [H.p_their()] потерянной [limb_select]...</span>", "<span class='notice'>Вы концентрируетесь на отращивании [limb_select]...
Сложное место
Придумай как склонять название конечности
Добавь склонение числа секунд функцией `declension_ru`
```suggestion
	H.visible_message("<span class='notice'>[H] замирает и концентрируется на своей потерянной [limb_select]...</span>", "<span class='notice'>Вы концентрируетесь на отращивании [limb_select]... (Это займет [round(SLIMEPERSON_REGROWTHDELAY/10)] секунд, нужно подождать в спокойствии.)</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/slime.dm
> +			to_chat(H, "<span class='warning'>Вы распределяете поврежденную ткань по всему телу, освобождая место, для ложноножки!</span>")
Запятая лишняя 
```suggestion
			to_chat(H, "<span class='warning'>Вы распределяете поврежденную ткань по всему телу, освобождая место для ложноножки!</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/slime.dm
> +			to_chat(H, "<span class='danger'>Вы потеряли орган, на котором выращивали вашу новую часть!</span>")
```suggestion
			to_chat(H, "<span class='danger'>Вы потеряли орган, на котором выращивали новую конечность!</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/slime.dm
> +		H.visible_message("<span class='notice'>[H] завершает отращивание [H.p_their()] потерянной [new_limb]!</span>", "<span class='notice'>Вы завершили отращивание [limb_select]</span>")
```suggestion
		H.visible_message("<span class='notice'>[H] отращивает [H.p_their()] потерянную [new_limb]!</span>", "<span class='notice'>Вы отрастили [limb_select]</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/slime.dm
> +		to_chat(H, "<span class='warning'>Вам нужно подождать в спокойствии чтобы отрастить конечность!</span>")
```suggestion
		to_chat(H, "<span class='warning'>Для отращивания конечности вам нужно стоять на месте!</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/tajaran.dm
> +		"вонзает когти в глазницы!",
```suggestion
		"вонзает когти себе в глазницы!",
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +		"вонзает когти в глазницы!",
```suggestion
		"вонзает когти себе в глазницы!",
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/vox.dm
> +		"пытается откусить свой язык!",
```suggestion
		"пытается откусить себе язык!",
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/vox.dm
> +		"вонзает когти в глазницы!",
```suggestion
		"вонзает когти себе в глазницы!",
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/vox.dm
> +		"вонзает когти в глазницы!",
Аналогично

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +	name = "Жало Врина"
На русском названия рас не считаются именами собственными и пишутся со строчной буквы
```suggestion
	name = "Жало врина"
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +	desc = "Подготовка жала Врина для ужаливания."
```suggestion
	desc = "Подготовка жала к ужаливанию."
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +		to_chat(user, "<span class='notice'>Нужно снять верхнюю одежду перед тем как использовать жало Врина.</span>")
```suggestion
		to_chat(user, "<span class='notice'>Для использования жала нужно снять верхнюю одежду.</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +		to_chat(user, "<span class='notice'>Вы чувствуете себя слишком усталым чтобы использовать жало Врина.</span>")
```suggestion
		to_chat(user, "<span class='notice'>Вы слишком устали для использования жала.</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +		to_chat(user, "<span class='warning'>Вокруг некого ужалить! Жало втягивается обратно.</span>")
```suggestion
		to_chat(user, "<span class='warning'>Вокруг некого жалить! Жало втягивается обратно.</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +		user.visible_message("<span class='warning'[user] втягивает свое жало.</span>")
```suggestion
		user.visible_message("<span class='warning'[user] втягивает своё жало.</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +		user.visible_message("<span class='warning'> [user] готовится использовать жало Врина!</span>")
```suggestion
		user.visible_message("<span class='warning'> [user] собирается применить жало!</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +		to_chat(user, "<span class='warning'>Вы далеко от [target]. Вы убираете свое жало.</span>")
```suggestion
		to_chat(user, "<span class='warning'>Вы слишком далеко от [target]. Жало втягивается.</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +		to_chat(user, "<span class='danger'> Вы жалите [target] в [organ] своим жалом!</span>")
Масло масляное
```suggestion
		to_chat(user, "<span class='danger'> Вы жалите [target] в [organ]!</span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +		user.visible_message("<span class='danger'>[user] жалит [target] в [organ] его жалом! </span>")
```suggestion
		user.visible_message("<span class='danger'>[user] жалит [target] в [organ]! </span>")
```

2022-05-13 16:52 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/wryn.dm
> +			to_chat(target, "<span class='danger'>Вы слышите невыносимый громкий хруст, когда ваши усики оторваны [user].</span>")
```suggestion
			to_chat(target, "<span class='danger'>Вы слышите невыносимый хруст, когда [user] вырывает усики из вашей головы.</span>")
```

2022-05-13 16:56 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/kidan.dm
> -
проверка конечностей не мой коммит, это кто-то недавно выкатывал его из-за бага с головой Кидана.
В общем конфликт возник. Завтра тогда сравню с ПРом головы киданов

2022-05-14 07:57 UTC, Vallat approved these changes

2022-05-14 14:56 UTC, TrashDoxx commented
Пока не мержить. Отсматриваю перевод.

2022-05-14 18:08 UTC, Ohar requested changes

2022-05-14 18:08 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Адамантиновый Голем</span>, вы обладаете особенным голосовыми связками, позволяющие вас \"резонировать\" послания всем големам."
```suggestion
	info_text = "Как <span class='danger'>Адамантиновый Голем</span>, вы обладаете особенным голосовыми связками, позволяющие вам «резонировать» послания всем големам."
```

2022-05-14 18:08 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Плазма Голем</span>, вы легко сгораете. Будьте отсторожны, если вы сильно нагреетесь - вы взорветесь!"
Прилагательное, не существительное.
Дублирование «вы» излишне.
Тире вместо дефиса.
```suggestion
	info_text = "Как <span class='danger'>Плазменный голем</span>, вы легко сгораете. Будьте отсторожны, если вы сильно нагреетесь &mdash; взорвётесь!"
```

2022-05-14 18:08 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Алмазный Голем</span>, вы более устойчивы, чем обычный голем."
Со строчных букв, пожалуйста.
И старайся использовать причастия, вместо зависимых предложений. Они ёмче, чище и короче.
Аналогично прочие типы големов
```suggestion
	info_text = "Будучи <span class='danger'>алмазным големом</span>, вы прочнее обычных големом."
```

2022-05-14 18:08 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +			"<span class='userdanger'>The [P.name] отразился от стеклянной кожи [H]!</span>")
Отражается

2022-05-14 18:08 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "As a <span class='danger'>Бананиумовый Голем</span>, вы созданы для розыгрышей. Ваше тело издает естественные гудки, и удары по людям издают безвредные гудки. Ваша кожа также истекает б
Бананий, не бананиум

2022-05-14 18:08 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "As a <span class='danger'>Транквиллитовый Голем</span>, вы можете создавать невидимые стены и регенерировать выпивая бутылки с ничем."
Транквилит - с одной «т»

2022-05-14 18:08 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/grey.dm
> +		to_chat(H, "<span class='warning'>Вади жжет вас[volume < 10 ? ", но она недостаточно сконцентрирована, чтобы вам навредить" : null]!</span>")
Ваши?

2022-05-14 20:05 UTC, TrashDoxx requested changes
Частично вычитал перевод. Из общих замечаний: переведены не все префиксы, а также не все имена для големов. Следует дополнить перевод. Остальное вычитаю завтра, сил и мотивации уже нет на это. Лучше бы ты ещё более точечно дробил переводы.

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/diona.dm
> +		"разваливается на множество нимф!")
```suggestion
		"разваливается на множество нимф!")
```
То ли дублированный перевод, то ли что. В любом случае, первый вариант коряво написан.

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/drask.dm
> +		"всасывает теплый воздух!",
```suggestion
		"втягивает теплый воздух!",
```
Может лучше без отсосов?

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +		"разбивает его тело на части!")
```suggestion
		"разбивает своё тело на части!")
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	var/info_text = "Как <span class='danger'>Железный Голем</span>, у вас нет отличительных особенностей."
```suggestion
	var/info_text = "Будучи <span class='danger'>железным големом</span>, вы не обладаете отличительными особенностями."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Адамантиновый Голем</span>, вы обладаете особенным голосовыми связками, позволяющие вас \"резонировать\" послания всем големам."
```suggestion
	info_text = "Будучи <span class='danger'>адамантиновым големом</span>, вы обладаете особыми голосовыми связками, позволяющими вас \"резонировать\" послания всем големам."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Плазма Голем</span>, вы легко сгораете. Будьте отсторожны, если вы сильно нагреетесь - вы взорветесь!"
```suggestion
	info_text = "Будучи <span class='danger'>плазменным големом</span>, вы уязвимы к огню. Будьте осторожны, если вы сильно нагреетесь — взорвётесь!"
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +			to_chat(H, "<span class='userdanger'>Вы чувствуете что можете взорваться в любой момент!</span>")
```suggestion
			to_chat(H, "<span class='userdanger'>Вы чувствуете, что можете взорваться в любой момент!</span>")
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +			to_chat(owner, "<span class='warning'>Вы попытались поджечь себя, но провалились!</span>")
```suggestion
			to_chat(owner, "<span class='warning'>Вы попытались поджечь себя, но неудачно!</span>")
```
Провалиться можно разве что под землю, кхм.

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Алмазный Голем</span>, вы более устойчивы, чем обычный голем."
```suggestion
	info_text = "Будучи <span class='danger'>алмазным големом</span>, вы прочнее обычных големов."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Золотой Голем</span>, вы быстрее, но менее устойчивы, чем обычный голем."
```suggestion
	info_text = "Будучи <span class='danger'>золотым големом</span>, вы более быстры, но менее прочны, нежели обычный голем."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Серебрянный Голем</span>, ваши атаки имеют более высокий шанс оглушения."
```suggestion
	info_text = "Будучи <span class='danger'>серебряный големом</span>, вы имеете больший шанс оглушения для своих атак."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Пласталиевый Голем</span>, вы медленнее, но вас сложнее оглушить и вы наносите сильные удары кулаком."
```suggestion
	info_text = "Будучи <span class='danger'>пласталиевым големом</span>, вы более медлительные, но вас сложнее оглушить и ваши кулаки причиняют серьёзные повреждения."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Титаниевый Голем</span>, вы устойчивы к урону от ожогов и невосприимчивы к пепельным бурям."
```suggestion
	info_text = "Будучи <span class='danger'>титановым големом</span>, вы частично устойчивы к урону от ожогов и невосприимчивы к пепельным бурям."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Пластитаниумный Голем</span>, вы очень устойчивы к ожогам и невосприимчивы к пепельным бурям и лаве."
```suggestion
	info_text = "Будучи <span class='danger'>пластитановым големом</span>, вы крайне устойчивы к ожогам и невосприимчивы к пепельным бурям и лаве."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Голем из инопланетных сплавов</span>, вы сделаны из передовых инопланетных материалов: вы быстрее и со временем регенерируете. Однако, вы можете разговаривать т
```suggestion
	info_text = "Будучи <span class='danger'>големом из инопланетных сплавов</span>, вы быстрее и со временем регенерируете. Однако, вы можете разговаривать только с големами из того же материала, что и вы."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	dietflags = DIET_HERB		// Plants eat...plants? -- естественное развитие растений в природе
```suggestion
	dietflags = DIET_HERB		// Plants eat...plants?
```
Кыш-кыш со своими комментариями.

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Деревянный Голем</span>, вы обладаете особенностями растений: вы получаете урон от экстремальных температур, способный вас поджечь, и у вас меньше брони, чем у
```suggestion
	info_text = "Будучи <span class='danger'>деревянным големом</span>, вы обладаете некоторыми особенностями растений: вы получаете урон от экстремальных температур, вас можно поджечь и у вас меньше брони, чем у обычного голема. Вы регенерируете на свету и увядаете во тьме."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Урановый Голем</span>, вы излучаете радиацию. Это не вредит другим големам, но влияет на органические формы жизни."
```suggestion
	info_text = "Будучи <span class='danger'>урановым големом</span>, вы излучаете радиацию. Это не вредит другим големам, но влияет на органические формы жизни."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Пластиковый Голем</span>, вы способны ползать по вентиляции, если вы раздеты."
```suggestion
	info_text = "Будучи <span class='danger'>пластиковым големом</span>, вы способны ползать по вентиляции, если вы раздеты."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Песчаный Голем</span>, вы невосприимчивы к физическим пулям и получаете очень мало грубого урона, но чрезвычайно уязвимы к урону от горения и энергетического ор
```suggestion
	info_text = "Будучи <span class='danger'>песчаным големом</span>, вы невосприимчивы к физическим боеприпасам и получаете очень мало грубого урона. Однако вы чрезвычайно уязвимы к лучам лазерного и энергетического оружия, а также к ожогам. К тому же, вы превратитесь в песок после смерти, что предотвратит любую форму восстановления."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +			"<span class='userdanger'>[P.name] безвредно тонет в песчаном теле  [H]!</span>")
```suggestion
			H.visible_message("<span class='danger'>[P.name] тонет в песчаном теле [H] без видимого вреда здоровью!</span>", \
			"<span class='userdanger'>[P.name] тонет в песчаном теле [H] без видимого вреда здоровью!</span>")
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Стеклянный Голем</span>, вы отражаете лазеры и энергетическое оружие и очень устойчивы к урону от горения. Однако вы чрезвычайно уязвимы к грубому урону. После
```suggestion
	info_text = "Будучи <span class='danger'>стеклянным големом</span>, вы отражаете лучи лазерного и энергетического оружия, а также крайне устойчивы к урону от ожогов. Однако вы чрезвычайно уязвимы к грубому урону и физическим боеприпасам. К тому же, после смерти вы разобьётесь без всякой надежды на восстановление."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	H.visible_message("<span class='danger'>[H] разбился в дребезги!</span>")
```suggestion
	H.visible_message("<span class='danger'>[H] разбился вдребезги!</span>")
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Блюспейс Голем</span>, вы пространственно нестабильны: Вы будете телепортироваться при ударе, и вы можете телепортироваться вручную на большое расстояние.."
```suggestion
	info_text = "Будучи <span class='danger'>блюспейс-големом</span>, вы пространственно нестабильны: вы будете телепортироваться при получении ударов. Также вы можете телепортироваться вручную на большое расстояние."
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	H.visible_message("<span class='warning'>[H] начинает вибрировать!</span>", "<span class='danger'>Вы начали заряжать свое блюспейс ядро...</span>")
```suggestion
	H.visible_message("<span class='warning'>[H] начинает вибрировать!</span>", "<span class='danger'>Вы начали заряжать своё блюспейс-ядро...</span>")
```

2022-05-14 20:05 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "As a <span class='danger'>Транквиллитовый Голем</span>, вы можете создавать невидимые стены и регенерировать выпивая бутылки с ничем."
```suggestion
	info_text = "Будучи <span class='danger'>транквилитовым големом</span>, вы можете создавать невидимые стены и регенерировать, выпивая бутылки с ничем."
```

2022-05-14 20:43 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "As a <span class='danger'>Бананиумовый Голем</span>, вы созданы для розыгрышей. Ваше тело издает естественные гудки, и удары по людям издают безвредные гудки. Ваша кожа также истекает б
Как раз таки бананиум. Так на вики указано.

2022-05-15 01:00 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Плазма Голем</span>, вы легко сгораете. Будьте отсторожны, если вы сильно нагреетесь - вы взорветесь!"
Объединил оба варианта

2022-05-15 01:00 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Как <span class='danger'>Плазма Голем</span>, вы легко сгораете. Будьте отсторожны, если вы сильно нагреетесь - вы взорветесь!"
Объединил оба варианта

2022-05-15 01:06 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/golem.dm
> +			"<span class='userdanger'>The [P.name] отразился от стеклянной кожи [H]!</span>")
внес

2022-05-15 01:11 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/slime.dm
> +		H.visible_message("<span class='notice'>[H] завершает отращивание [H.p_their()] потерянной [new_limb]!</span>", "<span class='notice'>Вы завершили отращивание [limb_select]</span>")
Внёс

2022-05-15 01:25 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/slime.dm
> +	H.visible_message("<span class='notice'>[H] замирает и концентрируется на [H.p_their()] потерянной [limb_select]...</span>", "<span class='notice'>Вы концентрируетесь на отращивании [limb_select]...
это цифры, им не нужны склонения
![image](https://user-images.githubusercontent.com/41479614/168453397-dc7fab40-6699-4167-927c-a8e8b9d280ef.png)

2022-05-15 02:01 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/slime.dm
> +	H.visible_message("<span class='notice'>[H] замирает и концентрируется на [H.p_their()] потерянной [limb_select]...</span>", "<span class='notice'>Вы концентрируетесь на отращивании [limb_select]...
Конечности русифицированы
![image](https://user-images.githubusercontent.com/41479614/168454017-b69f4ce4-fd65-44c0-9a30-23663f95a749.png)
![image](https://user-images.githubusercontent.com/41479614/168454019-f8be693d-f7da-4b27-8902-c472e4d946f9.png)

2022-05-15 02:05 UTC, PhantornRU commented
Големов откатил. Я их изначально тут откатывал, но просто не убрал некоторых по ошибке.
Големы будут отдельным ПРом.
Перевел отращивание конечностей слаймов, поправил пересекающиеся коммиты
Драски больше не отсасывают
Воксы, машины  и греи теперь еще больше русоязычные, ведь убрана косоязычность по саггестам

2022-05-25 14:47 UTC, PhantornRU commented
Одобрено Авоутом
https://discord.com/channels/617003227182792704/755125334097133628/978973948018565161

2022-05-25 20:34 UTC, TrashDoxx requested changes
Бегло пробежался, лень трудиться.

2022-05-25 20:34 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/vulpkanin.dm
> +
```suggestion

```

2022-05-25 20:34 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/vox.dm
> +	to_chat(H, "<span class='notice'>Теперь вы живете на азоте из [internal_tank]. Ваш вид считает кислород токсичным, поэтому вы должны дышать только азотом.</span>")
```suggestion
	to_chat(H, "<span class='notice'>Теперь вы живете на азоте из [internal_tank]. Кислород токсичен для вашего вида, поэтому вы должны дышать только азотом.</span>")
```

2022-05-25 20:34 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +				to_chat(user, "<span class='warning'>Вы вышли из инерции!</span>")
```suggestion
				to_chat(user, "<span class='warning'>Вы выбились из сил!</span>")
```
Насколько я понял из контекста, речь именно об этом.

2022-05-25 20:34 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/slime.dm
> +		to_chat(H, "<span class='warning'>Вы не потеряли ни одной конечности!</span>")
```suggestion
		to_chat(H, "<span class='warning'>Ваши конечности на месте!</span>")
```

2022-05-25 20:34 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "As a <span class='danger'>Бананиумовый Голем</span>, вы созданы для розыгрышей. Ваше тело издает естественные гудки, и удары по людям издают безвредные гудки. Ваша кожа также истекает б
```suggestion
	info_text = "Будучи <span class='danger'>бананиумовым голем</span>, вы созданы для розыгрышей. Ваше тело издает естественные гудки, и удары по людям издают безвредные гудки. Ваша кожа также истекает бананами, когда она повреждена."
```

2022-05-25 20:34 UTC, TrashDoxx commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	prefix = "Gold"
Зачем изменён префикс?

2022-05-26 02:54 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	prefix = "Gold"
Временный возврат к големам. Их изменения в ПРе с именами

2022-05-26 02:57 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +				to_chat(user, "<span class='warning'>Вы вышли из инерции!</span>")
Здесь идет окончание махов хвостами когда ты прекращаешь вращаться по инерции. Но в принципе. Пускай выбивается из сил, коль зависимость идет от стамины

2022-05-29 16:23 UTC, Bizzonium commented
![image](https://user-images.githubusercontent.com/8555356/170880408-faec3a8e-5f62-4c99-8b8e-4c4c0a36092d.png)

2022-05-29 17:47 UTC, PhantornRU commented
> ![image](https://user-images.githubusercontent.com/8555356/170880408-faec3a8e-5f62-4c99-8b8e-4c4c0a36092d.png)

Конфликт решил

2022-05-29 17:56 UTC, merged