Перевод и склонение с генерацией имен големов + дополнение имен
ss220-space/Paradise pull request #898
Opened 2022-05-15 09:05 UTC by PhantornRU

## What Does This PR Do
Русифицирует имена и названия големов.
Улучшенная генерация имён.
Добавлены дополнительные текстовые файлы "списки" с именами.
Дополнительные имена.
Сортировка имен по склонениям и полам.

## Why It's Good For The Game
Големы теперь индивидуальны и уникальны.

## Images of changes
![image](https://user-images.githubusercontent.com/41479614/168465296-023dc1e5-6f18-4936-94d5-e7fe7a835350.png)
![image](https://user-images.githubusercontent.com/41479614/168465299-a1a28f7a-292e-495c-a59b-faebe52fc3cc.png)
![image](https://user-images.githubusercontent.com/41479614/168465303-d2be5572-71b4-46e3-99b0-dfb1cc36562d.png)
![image](https://user-images.githubusercontent.com/41479614/168465306-895be053-4364-4eb3-b2ae-ab9454903676.png)
![image](https://user-images.githubusercontent.com/41479614/168465310-9ba6fc71-6644-4d1f-a9c0-cf835decb822.png)
![image](https://user-images.githubusercontent.com/41479614/168465314-05c1e596-b5fc-45fd-aeed-bf65f8c5c699.png)
![image](https://user-images.githubusercontent.com/41479614/168465321-c278cb5f-3a62-4106-921c-ada8360efbf7.png)
![image](https://user-images.githubusercontent.com/41479614/168465326-b68bcfff-b1d4-4adc-a194-d73839d715e0.png)

## Changelog
Здесь должны быть все коммиты по переводу.

2022-05-15 11:59 UTC, Ohar commented
Предложения для имён

**MALE**
> "Металл", "Болван", "Скол", "Осколок", "Крепыш", "Здоровяк", "Парень", "Пацан", "Шаблон", "Слиток", "Муляж", "Штырь", "Шкаф", "Запас", "Шлак", "Шар", "Куб", "Слой", "Абразив", "Абсолют", "Феррит", "Заруб", "Дождь", "Молот", "Провод", "Гвоздь", "Винт", "Шуруп", "Кристалл", "Хрусталь", "Элемент", "Порошок", "Электрод", "Образец", "Отжиг", "Вал", "Анод", "Катод", "Анолит", "Резак", "Блеск", "Чугун", "Дровосек", "Пресс", "Рельеф", "Баббит", "Жар", "Холод", "Лёд", "Шов", "Прут", "Ковш", "Излом", "Изгиб", "Бентонит", "Литник", "Пузырь", "Штамп", "Блюм", "Алмаз", "Человек", "Унатх", "Слаймомен", "Плазмамен", "Вульпканин", "Скрелл", "Драск", "Вокс", "Кидан", "Лист", "Нагар", "Карбид", "Католит", "Катион", "Анион", "Пар", "Стан", "Разрыв", "Рулон", "Кокс"

**FEMALE**
> "Болванка", "Дубина", "Биба", "Боба", "Наковальня", "Заготовка", "Баба", "Колодка", "Плашка", "Зазубрина", "Отливка", "Поковка", "Колода", "Канга", "Палка", "Пластина", "Сфера", "Оболочка", "Лента", "Стойкость", "Игла", "Плотность", "Сталь", "Зарубка", "Засечка", "Выплавка", "Коррозия", "Ржавчина", "Проводка", "Пудра", "Латунь", "Ось", "Плёнка", "Дуга", "Тяга", "Пламя", "Корка", "Печь", "Станина", "Балка", "Стена", "Форма", "Связь", "Медь", "Ковка", "Таяра", "Диона", "Соль", "Бронза", "Сажа", "Втулка", "Выплавка", "Плавка", "Усадка", "Грань", "Сода", "Фаска", "Просечка", "Сеть", "Чеканка", "Машина"

**NEUTER**
> "Клепало", "Стекло", "Олово", "Золото", "Долото", "Серебро", "Зерно", "Клеймо", "Поле", "Кольцо", "Железо", "Литьё"

2022-05-15 12:22 UTC, Ohar requested changes

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +			golem_surname = "[pick(GLOB.golem_neuter)]"
Здесь и выше ты сначала объявляешь строку через `"…"`, а потом выражение через `[…]`.
Кажется, что это можно упростить вот так (тут и выше)
```suggestion
			golem_surname = pick(GLOB.golem_neuter)
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Будучи <span class='danger'>серебряный големом</span>, вы имеете больший шанс оглушения для своих атак."
```suggestion
	info_text = "Будучи <span class='danger'>серебряным големом</span>, вы с большей вероятностью можете оглушить противников атаками."
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +		MALE = list("Серфер", "Чарриот", "Мужик", "Глушитель", "Тихон", "Анестетик", "Ювелир", "Пупс"),
«Чарриот» точно тут уместно?

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Будучи <span class='danger'>пласталиевым големом</span>, вы более медлительные, но вас сложнее оглушить и ваши кулаки причиняют серьёзные повреждения."
```suggestion
	info_text = "Будучи <span class='danger'>пласталиевым големом</span>, вы медлительны, но вас сложнее оглушить, а ваши кулаки причиняют серьёзные повреждения."
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	name = "Титаниевый Голем"
```suggestion
	name = "Титановый Голем"
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Будучи <span class='danger'>титановым големом</span>, вы частично устойчивы к урону от ожогов и невосприимчивы к пепельным бурям."
```suggestion
	info_text = "Будучи <span class='danger'>титановым големом</span>, вы частично устойчивы к ожогам и невосприимчивы к пепельным бурям."
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	prefix = "Титаниев" //неполное окончание т.к. гендеризация идет через другую функцию (/datum/species/golem/get_random_name())
```suggestion
	prefix = "Титанов" //неполное окончание т.к. гендеризация идет через другую функцию (/datum/species/golem/get_random_name())
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	name = "Пластитаниумовый Голем"
```suggestion
	name = "Пластитановый Голем"
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Будучи <span class='danger'>пластитаниумовым големом</span>, вы крайне устойчивы к ожогам и невосприимчивы к пепельным бурям и лаве."
```suggestion
	info_text = "Будучи <span class='danger'>пластитановым големом</span>, вы крайне устойчивы к ожогам и невосприимчивы к пепельным бурям и лаве."
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	prefix = "Пластаниумн" //неполное окончание т.к. гендеризация идет через другую функцию (/datum/species/golem/get_random_name())
```suggestion
	prefix = "Пластитанов" //неполное окончание т.к. гендеризация идет через другую функцию (/datum/species/golem/get_random_name())
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Будучи <span class='danger'>големом из инопланетных сплавов</span>, вы быстрее и со временем регенерируете. Однако, вы можете разговаривать только с големами из того же материала, что и
```suggestion
	info_text = "Будучи <span class='danger'>големом из инопланетных сплавов</span>, вы быстрее двигаетесь и со временем регенерируете. Однако, вы можете разговаривать только с големами из того же материала, что и вы."
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +		MALE = list("Инопришеленец", "Технологичный Голем", "Наблюдатель", "Незнакомец", "Странник", "Чужак", "Посланник", "Минерал", "Мужик", "Пришеленец", "Пупс"),
```suggestion
		MALE = list("Технологичный Голем", "Наблюдатель", "Незнакомец", "Странник", "Чужак", "Посланник", "Минерал", "Мужик", "Пришеленец", "Пупс"),
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Будучи <span class='danger'>стеклянным големом</span>, вы отражаете лучи лазерного и энергетического оружия, а также крайне устойчивы к урону от ожогов. Однако вы чрезвычайно уязвимы к
```suggestion
	info_text = "Будучи <span class='danger'>стеклянным големом</span>, вы отражаете лучи лазерного и энергетического оружия, а также крайне устойчивы к ожогам. Однако вы чрезвычайно уязвимы к грубому урону и баллистическому оружию. К тому же, после смерти вы разобьётесь без всякой надежды на восстановление."
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +			"<span class='userdanger'>The [P.name] отражается от стеклянной кожи [H]!</span>")
```suggestion
			"<span class='userdanger'>[P.name] отражается от стеклянной кожи [H]!</span>")
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	name = "Блюспейс Голем"
```suggestion
	name = "Блюспейс-Голем"
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	H.visible_message("<span class='warning'>[H] телепортировался!</span>", "<span class='danger'>Вы дестабилизируетесь и телепортируетесь!</span>")
> телепортировался

Забыл пол

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	H.visible_message("<span class='warning'>[H] начинает вибрировать!</span>", "<span class='danger'>Вы начали заряжать свое блюспейс-ядро...</span>")
```suggestion
	H.visible_message("<span class='warning'>[H] начинает вибрировать!</span>", "<span class='danger'>Вы начали заряжать своё блюспейс-ядро…</span>")
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	H.visible_message("<span class='warning'>[H] телепортировался!</span>", "<span class='danger'>Вы телепортировались!</span>")
> телепортировался

Забыл пол

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	name = "Бананиумный Голем"
Минерал называется «Бананий». «Бананиум» — неправильная калька с английского.
```suggestion
	name = "Бананиевый Голем"
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Будучи <span class='danger'>бананиумным големом</span>, вы созданы для розыгрышей. Ваше тело издает естественные гудки, и удары по людям издают безвредные гудки. Ваша кожа также истекае
```suggestion
	info_text = "Будучи <span class='danger'>бананиевым големом</span>, вы созданы для розыгрышей. Ваше тело издает естественные гудки, и удары по людям издают безвредные гудки. Если вас ранить, вы будете бананоточить."
```

2022-05-15 12:22 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	prefix = "Бананиумн" //неполное окончание т.к. гендеризация идет через другую функцию (/datum/species/golem/get_random_name())
```suggestion
	prefix = "Бананиев" //неполное окончание т.к. гендеризация идет через другую функцию (/datum/species/golem/get_random_name())
```

2022-05-15 12:37 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/golem.dm
> +			golem_surname = "[pick(GLOB.golem_neuter)]"
Так и есть, только разницы это никакой не приносит. Но в некоторых местах каким-то образом без добавления строковых кавычек он... умудряется ломать логику. От того на всякий тут их оставляю, если они ничего не усложняют.

2022-05-15 12:41 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/golem.dm
> +		MALE = list("Инопришеленец", "Технологичный Голем", "Наблюдатель", "Незнакомец", "Странник", "Чужак", "Посланник", "Минерал", "Мужик", "Пришеленец", "Пупс"),
А почему не оставить Инопришеленец? Это очень хороший и смешной мем)

2022-05-15 12:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/golem.dm
> +		MALE = list("Серфер", "Чарриот", "Мужик", "Глушитель", "Тихон", "Анестетик", "Ювелир", "Пупс"),
Да, это отсылка. Отсылку стоит сохранить, даже если она русифицирована. Те кто прочитают, те всеравно поймут

2022-05-15 12:47 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	H.visible_message("<span class='warning'>[H] телепортировался!</span>", "<span class='danger'>Вы телепортировались!</span>")
У големов нет пола. То что у их имени есть пол - это внутренняя фишка для русификации имен.
Но в принципе. От того что гендеризирую хуже не будет

2022-05-15 13:07 UTC, PhantornRU commented
Расширены имена. Сохранено мемное имя для инопланетного голема "Инопришеленец"
+ корректировка гендеризации бесполых големов, у которых есть гендерные имена... Но сам пол бесполый...

2022-05-18 11:15 UTC, Ohar approved these changes
Написал небольшое число замечаний.
Следовать им или нет - на твое усмотрение они некритичные

2022-05-18 11:15 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +					to_chat(L, "<span class='danger'>Вас окутывает мягкое зеленое свечение, исходящее от [H].</span>")
```suggestion
					to_chat(L, "<span class='danger'>Вас окутывает мягкое зелёное свечение, исходящее от [H].</span>")
```

2022-05-18 11:15 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	prefix = "Блюспейс"
Выбери, пожалуйста, у тебя это 
* Либо первый корень сложного слова (Блюспейс-Прыгун) и тогда надо избавиться от пробела, заменив его на дефис.
* Либо прилагательное, как в остальных случаях (Блюспейсовый Прыгун) и тогда надо тип генерации имени поменять.

2022-05-18 11:15 UTC, Ohar commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	info_text = "Будучи <span class='danger'>транквилитовым големом</span>, вы можете создавать невидимые стены и регенерировать выпивая бутылки с ничем."
```suggestion
	info_text = "Будучи <span class='danger'>транквилитовым големом</span>, вы можете создавать невидимые стены и регенерировать, выпивая бутылки с ничем."
```

2022-05-25 14:48 UTC, PhantornRU commented
Одобрено Авоутом
https://discord.com/channels/617003227182792704/755125334097133628/978974133184512063

2022-05-25 17:29 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/golem.dm
> +	prefix = "Блюспейс"
Изменения внесены, теперь от суфикса он будет добавлять "-"
![image](https://user-images.githubusercontent.com/41479614/170326667-17d9484a-c897-4f11-9760-7226bd4c86b7.png)
![image](https://user-images.githubusercontent.com/41479614/170326886-866c05ad-f0e1-4877-9d63-f3fe6c2c4c5f.png)

2022-05-29 16:23 UTC, Bizzonium commented
![image](https://user-images.githubusercontent.com/8555356/170880363-fa3182eb-d587-4b54-bc43-92269f23faea.png)

2022-05-29 17:46 UTC, PhantornRU commented
> ![image](https://user-images.githubusercontent.com/8555356/170880363-fa3182eb-d587-4b54-bc43-92269f23faea.png)

Конфликт решил

2022-05-29 17:56 UTC, Bizzonium commented
![image](https://user-images.githubusercontent.com/8555356/170884653-832286cf-f627-4a66-90aa-7c36f3ac9c24.png)

2022-05-29 18:13 UTC, PhantornRU commented
> ![image](https://user-images.githubusercontent.com/8555356/170884653-832286cf-f627-4a66-90aa-7c36f3ac9c24.png)

Всё, разобрался с решением конфликтов. Просто недогрузил моменты.

Пойду спать

2022-05-29 18:26 UTC, merged