Fix: Правильно показывать антагонистов в Orbit
ss220-space/Paradise pull request #908
Opened 2022-05-17 23:07 UTC by Ohar

## What Does This PR Do

Orbit теперь будет показывать как антагонистов. 

### Всегда (видны как антаги для всех игроков)
* Пауки ужаса
* TODO: Блоб
* TODO: Блоббернауты
* TODO: Свармеры
### При включённом Antag HUD
* Главы революции (отдельно от революционеров)
* Жертвы абдукторов
* Дьяволы
* Рабы вампиров
* Ксеноморфы (только рождённых из яйца в гуманоиде или раундстартовых, но не щитспавн)
* Ивентовые роли

## Why It's Good For The Game
Всех антагов теперь легко находить через Orbit

## Images of changes
Не смотрите что на скринах есть перевод меню — он не входит в эту правку.
![Ксеноморфы](https://user-images.githubusercontent.com/3854741/168926147-39039db6-e280-4300-a8a2-0648b91a9eb2.png)
![Хэдревы](https://user-images.githubusercontent.com/3854741/168926150-2d13a0ac-1c66-4f1c-bc57-0895d330fecd.png)
![похищенные абдукторами](https://user-images.githubusercontent.com/3854741/168926151-04fd5354-18af-4a00-aa09-1bd1824352ea.png)
![ивентрольки](https://user-images.githubusercontent.com/3854741/168926155-9dfff402-7f7f-4a85-8fed-d616fa23d2f2.png)
![Дьяволы](https://user-images.githubusercontent.com/3854741/168926156-422d1e34-2a40-46a0-a1ed-f2ab5d3fb26e.png)
![паук ужаса](https://user-images.githubusercontent.com/3854741/168926379-dd861ce3-9571-44a7-95b1-eee862e6cdc4.png)

## Changelog

:cl:
fix: Правильно показываются антагонисты в Orbit
/:cl:

2022-05-18 05:04 UTC, Gaxeer commented on code/modules/mob/dead/observer/orbit.dm
> +				if(GLOB.ts_spiderlist.len && M.ckey)
```suggestion
				if (length(GLOB.ts_spiderlist) && M.ckey)
```
Null safe. Ну и плюс, насколько я видел, используют его в основном

2022-05-18 05:10 UTC, Gaxeer commented on code/modules/mob/dead/observer/orbit.dm
> +					antagonists += list(antag_serialized)
ты точно хотел это вынести из блока `if(user.antagHUD)` ?

2022-05-18 05:13 UTC, Gaxeer commented on code/modules/mob/dead/observer/orbit.dm
> +						"Terror Spiders" = GLOB.ts_spiderlist.Find(mind.current),
Find() - возвращает позицию элемента в списке, а не булевое значение, как ожидается в этом списке, судя по комменту на 99 строке.
По этому:
```suggestion
						"Terror Spiders" =(mind.current in GLOB.ts_spiderlist)
```

2022-05-18 10:41 UTC, Ohar commented on code/modules/mob/dead/observer/orbit.dm
> +					antagonists += list(antag_serialized)
Да, чтобы пауки показывались без него

2022-05-21 10:51 UTC, Ohar commented on code/modules/mob/dead/observer/orbit.dm
> +					antagonists += list(antag_serialized)
Пауков убрал пока, с ними много проблем

2022-05-22 18:43 UTC, Gaxeer commented on code/modules/mob/dead/observer/orbit.dm
> +			var/antag_serialized = serialized.Copy()
```suggestion
			var/list/antag_serialized = serialized.Copy()
```

2022-05-23 06:15 UTC, Vallat requested changes

2022-05-23 06:15 UTC, Vallat commented on code/modules/mob/dead/observer/orbit.dm
> +				other_antags += list("Blob Cores" = (core.overmind?.mind in SSticker.mode.blob_overminds))
```suggestion
			if(core.overmind && core.overmind.mind && core.overmind.key)
				other_antags += list("Blob Cores" = (core.overmind.mind in SSticker.mode.blob_overminds))
```

2022-05-23 06:15 UTC, Vallat commented on code/modules/mob/dead/observer/orbit.dm
> +				misc += list(serialized)
К вопросу о надписи в комментарии, что срабатывает даже при `core.overmind = null`. Уверен, что эта строчка нужна?

2022-05-29 12:39 UTC, Ohar commented on code/modules/mob/dead/observer/orbit.dm
> +				misc += list(serialized)
> К вопросу о надписи в комментарии, что срабатывает даже при `core.overmind = null`. Уверен, что эта строчка нужна?

Если ты про то — надо ли добавлять ядро блоба без игрока в раздел «Misc», то сейчас это делается так, я не намеревался тут менять текущую логику. Пусть как добавлялось, так и продолжает добавляться.

2022-06-22 15:03 UTC, Vallat approved these changes

2022-06-22 15:05 UTC, Gaxeer approved these changes

2022-06-22 15:25 UTC, merged