Feat: Месть Библии
ss220-space/Paradise pull request #920
Opened 2022-05-21 06:25 UTC by Den109G

## What Does This PR Do
Добавляет ограничение на Библию в виде смайта (70 урона и сообщение).
[Окончание голосования.](https://discord.com/channels/617003227182792704/755125334097133628/977413194433847326)

## Why It's Good For The Game
Священник получит дебафф к своей самой сильной стороне.

## Changelog
:cl:
add: smite for bible abusers
/:cl:

2022-05-21 13:09 UTC, Vallat requested changes

2022-05-21 13:09 UTC, Vallat commented on code/game/objects/items/weapons/storage/bible.dm
> +	god_punishment = max(0, god_punishment)
```suggestion
/obj/item/storage/bible/proc/god_forgive()
	god_punishment = max(0, god_punishment - round((world.time - last_used) / 30 SECONDS)) //forgive 1 sin every 30 seconds
	last_used = world.time
```

2022-05-21 13:09 UTC, Vallat commented on code/game/objects/items/weapons/storage/bible.dm
> +				to_chat(chaplain, "<h1><span class='danger'>Вы злоупотребляете покровительством бога [deity_name], остановитесь и подумайте.</span></h1>")
Фразы конечно будто не совсем на русском написаны, но тут не моя компетенция.
```suggestion
		if(H == chaplain)
			god_punishment++
		
		if(god_punishment == 5)
			to_chat(chaplain, "<h1><span class='danger'>Вы злоупотребляете покровительством бога [deity_name], остановитесь и подумайте.</span></h1>")
		else if(god_punishment > 5) //lets apply punishment AFTER heal
			chaplain.electrocute_act(5, "Lightning Bolt", safety = TRUE, override = TRUE)
			playsound(get_turf(chaplain), 'sound/magic/lightningshock.ogg', 50, 1, -1)
			chaplain.adjustFireLoss(65)
			chaplain.Weaken(5)
			to_chat(chaplain, "<span class='userdanger'>Вы злоупотребили волей бога и за что были наказаны!</span>")
```

2022-05-21 21:20 UTC, Den109G commented on code/game/objects/items/weapons/storage/bible.dm
> +	god_punishment = max(0, god_punishment)
Тут всегда возвращает 1 в игре, поэтому не могу добавить в игру.

2022-05-21 21:30 UTC, Den109G commented on code/game/objects/items/weapons/storage/bible.dm
> +	god_punishment = max(0, god_punishment)
Добавил в код.

2022-05-22 06:30 UTC, Vallat approved these changes

2022-05-29 16:09 UTC, merged