Tweak: Перевод текстов при прибытии на роль
ss220-space/Paradise pull request #925
Opened 2022-05-21 19:25 UTC by Ohar

## What Does This PR Do
* Перевод текста «X» во фразе «На этой должности вы отвечаете непосредственно перед X» при входе на роль
* Перевод стартовых окон выбора религии и божества у священника

## Why It's Good For The Game
* Текст приятнее читать
* Упрощается игра для новичков
* Книга священника переименовывается в зависимости от русскоязычных названий религии

## Images of changes
![изображение](https://user-images.githubusercontent.com/3854741/169666235-ef89dbd6-eae1-4f4a-bc83-5446b82d915f.png)

## Changelog
:cl:
tweak: Перевод частей стартовых сообщшенией при входе на роль
/:cl:

2022-05-22 17:29 UTC, girafe969 requested changes
Ку

2022-05-22 17:29 UTC, girafe969 commented on code/game/jobs/job/support_chaplain.dm
> +					B.name = pick("Принципы относительности", "Очумелые ручки: Построй собственный варп-двигатель", "Тайны Блюспейса", "Игра в бога: коллекционное издание")
Игра в бога в женском роде.
И что тут со свитчем? Выбор между мужским и женским, а названия либо в множественном числе, либо в единственном числе женского рода.

2022-05-22 17:29 UTC, girafe969 commented on code/game/jobs/job/support_chaplain.dm
> +	var/new_deity = copytext_char(clean_input("Кому или чему вы поклоняетесь? По-умолчанию это Космический Иисус.", "Название религии", deity_name, user), 1, MAX_NAME_LEN)
```suggestion
	var/new_deity = copytext_char(clean_input("Кому или чему вы поклоняетесь? По-умолчанию это Космический Иисус.", "Имя или название идола", deity_name, user), 1, MAX_NAME_LEN)
```

2022-05-22 17:29 UTC, girafe969 commented on code/game/jobs/job/silicon.dm
> +	supervisors = "вашими законами и вашим ИИ"	//Nodrak
Вашим ИИ? Понимаю что подразумевается, но звучит неправильно. Может "Синхронизированным ИИ"?

2022-05-23 00:42 UTC, Ohar commented on code/game/jobs/job/support_chaplain.dm
> +					B.name = pick("Принципы относительности", "Очумелые ручки: Построй собственный варп-двигатель", "Тайны Блюспейса", "Игра в бога: коллекционное издание")
Игру убрал, Switch починил

2022-05-23 00:44 UTC, Ohar commented on code/game/jobs/job/silicon.dm
> +	supervisors = "вашими законами и вашим ИИ"	//Nodrak
Там «the», то есть говорится совершенно конкретный ИИ-мастер этого конкретного киборга

Может уточнить _«вашими законами и вашим ИИ-хозяином»_?

2022-05-23 00:47 UTC, Ohar commented on code/game/jobs/job/support_chaplain.dm
> +	var/new_deity = copytext_char(clean_input("Кому или чему вы поклоняетесь? По-умолчанию это Космический Иисус.", "Название религии", deity_name, user), 1, MAX_NAME_LEN)
Поменял на нейтральное «Объект поклонения»

2022-05-23 06:36 UTC, Vallat approved these changes

2022-05-23 07:59 UTC, girafe969 commented on code/game/jobs/job/silicon.dm
> +	supervisors = "вашими законами и вашим ИИ"	//Nodrak
"вашими законами и синхронизированным с вами ИИ"
Ну, если не нравится этот вариант подойдёт и твой

2022-05-23 08:05 UTC, girafe969 requested changes
Ещё нашел момент

2022-05-23 08:05 UTC, girafe969 commented on code/game/jobs/job/support_chaplain.dm
> +					B.name = "Программирование Вселенной"
Это тут типо на всякий случай, если свитч проебется? Добавь B.gender под него

2022-05-29 12:26 UTC, Ohar commented on code/game/jobs/job/support_chaplain.dm
> +					B.name = "Программирование Вселенной"
Поправил

2023-05-10 01:04 UTC, closed without merging