Tweak: перевод морфа
ss220-space/Paradise pull request #926
Opened 2022-05-21 21:30 UTC by Ohar

## What Does This PR Do
Перевод всего текста морфа — вводного текста, глаголов разговора, описаний поглощаения, превращений и всего прочего.

## Why It's Good For The Game
+ Текст приятнее читать
+ Упрощается игра на морфе и против морфа

## Changelog
:cl:
tweak: tweaked a few things
/:cl:

2022-06-03 13:13 UTC, Furukia requested changes
Я тут посмотрела на это... Дорабатывай 🐀

2022-06-03 13:13 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph.dm
> +	var/playstyle_string = {"<b><font size=3 color='red'>Вы — морф.</font><br>Вы — мерзость, созданная в основном из генокрадских клеток. Вы можете принять форму чего угодно поблизости, кликнув по нему
Во первых. Писать такие тексты в одну строчку, это ужас. Пользуйся \ для переноса строки текста в коде.
Дальше:
* Abomination - в данном контексте явно значит монстр/тварь/чудище, но никак не "мерзость"
* "Те кто видят, заметят" - слабая, но тавтология. Причём написано очевидное. Важно я считаю приметить, что они не просто заметят процесс если будут прямо смотреть, а реально обратят на это внимание. (текст покажется в чате) Даже если морф из капли крови обратится в ручку, а они на него прямо не смотрели!
* Поглощённое существо восстановИТ, а не восстановят.
```suggestion
	var/playstyle_string = {"<b><font size=3 color='red'>Вы — морф.</font><br>Вы — чудовище, созданное в основном из клеток генокрада. \
Вы можете принять форму чего угодно поблизости, кликнув по нему <kbd>Shift</kbd> + <kbd>ЛКМ</kbd>. Это можно делать не чаще одного раза в 5 секунд, \
а сама смена формы очень легко притягивает внимание других живых существ. <br> \
Будучи превращённым, вы двигаетесь быстрее, но наносите меньше урона. Кроме того, любой в пределах трёх плиток от вас заметит странную неправильность, если осмотрит вас. \
Вы можете восстановить свою первоначальную форму, кликнув по себе <kbd>Shift</kbd> + <kbd>ЛКМ</kbd>.<br> \
Кроме этого, вы можете атаковать любой предмет или мёртвое существо, чтобы поглотить его. Поглощённое существо восстановит ⅓ вашего максимального здоровья.</b>"}
```

2022-06-03 13:13 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph.dm
> +			. += "<span class='warning'>Во внешнем виде [src] вы замечаете что-то очень неправильное…</span>"
Слишком длинно, зачем то ещё и имя самого морфа вписали сюда. Много внимания маленькой неприметной строчке. Главное передать смысл, что морф подозрителен. Кем бы, чем бы он не был в этот момент
```suggestion
			. += "<span class='warning'>Вам кажется, что что-то не так...</span>"
```

2022-06-03 13:13 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph.dm
> +		to_chat(src, "<span class='warning'>Ваша маскировочная кожа всё ещё восстанавливается!</span>")
Маскировочная кожа? Серьёзно? Не всё нуждается в БУКВАЛЬНОМ переводе. Буквальней было бы только кожа хамелиона и это даже звучало бы в разы лучше.
```suggestion
		to_chat(src, "<span class='warning'>Ваши клетки всё ещё восстанавливаются!</span>")
```

2022-06-03 13:13 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph.dm
> +	visible_message("<span class='warning'>[src] резко провалива[pluralize_ru(src.gender,"ется","ются")] сам[genderize_ru(src.gender,"","а","о","и")] в себя, расползаясь массой зелёной плоти!</span>", \
Есть такое необычное слово - "схлопывается" Буквально значащее резкое уменьшение в размерах. И звучащее гораздо лучше и логичнее чем "проваливается сам в себя"!
dissolving - значит растворяться/разлагаться, а не расползаться.
```suggestion
	visible_message("<span class='warning'>[src] резко схлопы[pluralize_ru(src.gender,"ется","ются")], разлагаясь на массу зелёной плоти!</span>", \
```

2022-06-03 13:13 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph.dm
> +		visible_message("<span class='warning'>[src] искривля[pluralize_ru(src.gender,"ется","ются")] и располза[pluralize_ru(src.gender,"ется","ются")] массой зелёной плоти!</span>", \
Тоже самое.
```suggestion
		visible_message("<span class='warning'>[src] искривля[pluralize_ru(src.gender,"ется","ются")] и разлага[pluralize_ru(src.gender,"ется","ются")] на массу зелёной плоти!</span>", \
```

2022-06-03 13:13 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph.dm
> +						"<span class='userdanger'>Ваша кожа рвётся! Ваша плоть распадается! Никакая маскировка не сможет защитить ва…</span>")
Предполагаю что незаконченное предложение звучит так:
No disguise can ward off deATH!
а значит переводится примерно так:
```suggestion
						"<span class='userdanger'>Ваша кожа рвётся! Ваша плоть распадается! Никакая маскировка не предотвратит сме…</span>")
```

2022-06-03 13:13 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph_event.dm
> +		var/list/candidates = SSghost_spawns.poll_candidates("Вы хотите занять роль морфа?", ROLE_MORPH, TRUE, source = /mob/living/simple_animal/hostile/morph)
А зачем писать "занять роль", когда есть уже простой и логичный перевод "сыграть за", без этих ненужных перефразировок.
```suggestion
		var/list/candidates = SSghost_spawns.poll_candidates("Вы хотите сыграть за морфа?", ROLE_MORPH, TRUE, source = /mob/living/simple_animal/hostile/morph)
```

2022-06-03 14:54 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph.dm
> +						"<span class='userdanger'>Ваша кожа рвётся! Ваша плоть распадается! Никакая маскировка не сможет защитить ва…</span>")
ещё можно написать "не спрячет вас от сме..."

2022-06-07 12:19 UTC, Ohar commented on code/game/gamemodes/miniantags/morph/morph.dm
> +	var/playstyle_string = {"<b><font size=3 color='red'>Вы — морф.</font><br>Вы — мерзость, созданная в основном из генокрадских клеток. Вы можете принять форму чего угодно поблизости, кликнув по нему
Я пользуюсь автопереносами и не вижу проблемы всем так делать. Другой вопрос — что для нормального отображения можно использовать `<br>`.

Про «чудовище» согласен.
> из клеток генокрада
Клетки не принадлежат одному конкретному генокраду, здесь нельзя использовать единственное число.
> сама смена формы очень легко притягивает внимание других живых существ
Неудачная формулировка. Совершенно непонятно что тут имеется в виду. Можно подумать что если ты меняешь форму, на тебя начинает рычать собака, например. Всё-таки тут говорится о том что смена формы заметна всем видящим морфа игрокам и они обращают на неё внимание.

2022-06-07 12:29 UTC, Ohar commented on code/game/gamemodes/miniantags/morph/morph.dm
> +			. += "<span class='warning'>Во внешнем виде [src] вы замечаете что-то очень неправильное…</span>"
Согласен, но формулировку нужно другую

2022-06-07 12:33 UTC, Ohar commented on code/game/gamemodes/miniantags/morph/morph.dm
> +	visible_message("<span class='warning'>[src] резко провалива[pluralize_ru(src.gender,"ется","ются")] сам[genderize_ru(src.gender,"","а","о","и")] в себя, расползаясь массой зелёной плоти!</span>", \
>схлопываться

предполагает хлопок, которого вроде как нет

> разлагаясь на массу

Разлагаются не на что-то, а просто. Здесь же речь именно о том что остаётся жижа.

2022-06-07 12:34 UTC, Ohar commented on code/game/gamemodes/miniantags/morph/morph.dm
> +						"<span class='userdanger'>Ваша кожа рвётся! Ваша плоть распадается! Никакая маскировка не сможет защитить ва…</span>")
Я предполагал «вашу смерть»

2022-06-07 16:00 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph.dm
> +	var/playstyle_string = {"<b><font size=3 color='red'>Вы — морф.</font><br>Вы — мерзость, созданная в основном из генокрадских клеток. Вы можете принять форму чего угодно поблизости, кликнув по нему
> Я пользуюсь автопереносами и не вижу проблемы всем так делать. Другой вопрос — что для нормального отображения можно использовать `<br>`.

`<br>` здесь не к месту, я тебе о читабельности кода, а не об html переносе для игрока. Код в одну строку, читать совершенно не удобно!
> Клетки не принадлежат одному конкретному генокраду, здесь нельзя использовать единственное число.

Нельзя? Ну не то чтобы нельзя, ибо никто не запрещает. Не стоит? Возможно. Но вариант "клеток генокрадов" звучит тоже так себе.

> Неудачная формулировка. Совершенно непонятно что тут имеется в виду. Можно подумать что если ты меняешь форму, на тебя начинает рычать собака, например. Всё-таки тут говорится о том что смена формы заметна всем видящим морфа игрокам и они обращают на неё внимание.

Возможно, но и твоя прошлая формулировка не особо удачна. Конкретно `"если осмотрит вас."` совершенно лишний текст. Не надо осматривать морфа, чтобы в чат написало о его трансформации!

2022-06-07 16:04 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph.dm
> +			. += "<span class='warning'>Во внешнем виде [src] вы замечаете что-то очень неправильное…</span>"
Главная проблема здесь в том, что там где в английском используют "it" у нас оно переведётся как "оно" Для фикса этой проблемы нужно учесть пол нынешней внешности морфа. `"Вам кажется, что с ним/ней что то не так"` Но так же встаёт проблема, а что если морф вещь? У которой нет пола? Кхм. В общем как по мне тут нужна замена на нейтральную к полу формулировку. И при этом фраза должна быть короткой. Хочешь другую фразу? Пробуй. Меня моя формулировка в целом устраивает тут.

2022-06-07 16:07 UTC, Furukia commented on code/game/gamemodes/miniantags/morph/morph.dm
> +	visible_message("<span class='warning'>[src] резко провалива[pluralize_ru(src.gender,"ется","ются")] сам[genderize_ru(src.gender,"","а","о","и")] в себя, расползаясь массой зелёной плоти!</span>", \
> предполагает хлопок, которого вроде как нет

Бред. 

> Разлагаются не на что-то, а просто. Здесь же речь именно о том что остаётся жижа.

Базовая химия. "Разлагается на оксид и воду" и другие подобные примеры. В общем разлагается именно НА что-то. В данном случае на массу зелёной плоти.

2024-02-12 20:59 UTC, closed without merging