Tweak: Перевод интерфейса ПИИ (не готов)
ss220-space/Paradise pull request #930
Opened 2022-05-22 23:15 UTC by Ohar

## What Does This PR Do

## Why It's Good For The Game

## Images of changes
![изображение](https://user-images.githubusercontent.com/3854741/169719627-fcb8f3ac-ce71-4108-aa86-cbef52660f41.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719637-2a027a57-248d-4144-93a0-0b87b24689e5.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719651-744996f8-b15c-4e8b-95dd-e88a12afa07a.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719692-2dca8d51-1763-4554-9226-898aef7f8d97.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719701-d2868ae1-ddcb-4401-bc9a-4d8c9fe90a66.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719709-d7a7d1a8-3650-4851-8fb7-60310d339ebf.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719743-59dfeb20-68f9-49f5-9077-4e4dc32b63cb.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719766-22b3603b-a860-45f2-8afd-a1ac0f517da7.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719777-4cbd7b0f-9294-490e-803a-9ce7944447e9.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719800-b78e1df5-42a8-4fa8-b3b6-9820fab73b53.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719808-19f031cc-0268-4465-b4f5-d02f2ac91343.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719850-bde1135e-bbec-4ae3-9606-e13f320c6d8c.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719863-a8f1d8d1-4545-4363-9a5f-bdbe88d96dbe.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719875-0e374c9e-3db6-464b-9216-31a0ada20882.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719886-ffc1df12-c044-45d6-afbb-7e2c7a8413ab.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719917-a88f1b13-9929-4f94-b41e-0422aa5476e1.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719929-bd035f24-d8e2-49f0-9a93-c2a46027eba4.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719951-5c91a510-2f52-4f15-8587-dc0a96dbaa3e.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719990-be92e3a0-af89-4390-bd6a-d99d532070f5.png)
![изображение](https://user-images.githubusercontent.com/3854741/169719997-4f7d42c5-2fd9-49bd-ae64-31cf4170cb1c.png)
![изображение](https://user-images.githubusercontent.com/3854741/169720025-e162b407-5669-4b93-941b-d99ca7eebcb2.png)
![изображение](https://user-images.githubusercontent.com/3854741/169720035-bffc4cc1-2237-4512-8577-5fde75817e51.png)
![изображение](https://user-images.githubusercontent.com/3854741/169720045-2bf649f5-f78b-49aa-b850-244ec88585e7.png)
![изображение](https://user-images.githubusercontent.com/3854741/169720062-98ab580a-04f1-4695-9a7a-4e07ea099cd6.png)
![изображение](https://user-images.githubusercontent.com/3854741/169720072-90fdf219-68f6-4bb4-934f-db8b7ff0a4c3.png)
![изображение](https://user-images.githubusercontent.com/3854741/169720081-a9ba69be-8e69-4225-8d60-1f9d0bc23b97.png)
![изображение](https://user-images.githubusercontent.com/3854741/169720098-fbea776a-2bd1-487d-8127-9bb682d19591.png)
![изображение](https://user-images.githubusercontent.com/3854741/169720106-926e2352-5d9d-4f38-89b0-4fc04fcbb7d4.png)

## Changelog
:cl:
tweak: tweaked a few things
/:cl:

2022-06-03 14:42 UTC, Furukia requested changes

2022-06-03 14:42 UTC, Furukia commented on code/game/objects/items/devices/paicard.dm
> +				<p>Запрос личностей ПИИ из центральной базы данных… Если личности не будут обнаружены, либо если не будет найдена подходящая личность, попробуйте выполнить повторный поиск позже, когда могут быть
"когда могут быть загружены новые личности ПИИ". Так когда там поиск выполнить? Как игрок должен вообще понять это предложение при чтении?
```suggestion
				<p>Запрос личностей ПИИ из центральной базы данных… Если личности не будут обнаружены, либо если не будет найдена подходящая личность, попробуйте выполнить повторный поиск на новые личности позже.</p>
```

2022-06-03 14:42 UTC, Furukia commented on code/game/objects/items/devices/paicard.dm
> +				<p>При каждом нажатии этой кнопки всем доступным личностям ПИИ будет послан запрос. Дайте личностям ПИИ время на подготовку и проверьте результаты ответа чуть позже.</p>
Переврал смысл предложения!
Более точный вариант: "Частые проверки устройства дадут личностям достаточно времени, чтобы ответить на запрос."
Хотя оно всё равно при должном переводе звучит так себе ибо не понятно как 'частые проверки" - "дают время" Поэтому я немного адаптировала.
```suggestion
				<p>При каждом нажатии этой кнопки всем доступным личностям ПИИ будет послан запрос. Частые проверки устройства увеличивают шансы, что личность ответит на ваш запрос.</p>
```

2022-06-03 14:42 UTC, Furukia commented on code/game/objects/items/devices/paicard.dm
> +				to_chat(M, "<font color='#ff0000'><h2>Вы чувствуете как реальность начинает ускользать.</h2></font>")
Тут не реальность ускользает... А ПИИ
```suggestion
				to_chat(M, "<font color='#ff0000'><h2>Вы чувствуете как разрывается ваша связь с реальностью.</h2></font>")
```

2022-06-03 14:42 UTC, Furukia commented on code/game/objects/items/devices/paicard.dm
> +				to_chat(M, "<font color='#ff4d4d'><h3>Байт за байтом вы теряете ощущение себя.</h3></font>")
У фразы "sense of self" есть устоявшийся красивый перевод "чувство собственного "я"" 
```suggestion
				to_chat(M, "<font color='#ff4d4d'><h3>Байт за байтом ускользает ваше чувство собственного "я".</h3></font>")
```

2022-06-03 14:42 UTC, Furukia commented on code/game/objects/items/devices/paicard.dm
> +				to_chat(M, "<font color='#ff8787'><h4>Ментальные способности оставляют вас.</h4></font>")
У фразы "mental faculties" есть устоявшийся перевод "умственные способности" Хотя и он смотрится здесь спорно. А Ментальные способности, вызывают ощущение, что ПИИ это какой то Псионик...
```suggestion
				to_chat(M, "<font color='#ff8787'><h4>Вычислительные способности покидают вас.</h4></font>")
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/pai.dm
> +		stat(null, "Перезагрузка система коммуникаций через [(timeleft / 60) % 60]:[add_zero(num2text(timeleft % 60), 2)]")
```suggestion
		stat(null, "Перезагрузка системы коммуникаций через [(timeleft / 60) % 60]:[add_zero(num2text(timeleft % 60), 2)]")
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/pai.dm
> +			M.show_message("<span class='warning'>Сноп искр вылетает из [src].</span>", 3, "<span class='warning'>Вы чувствуете запах озона и слышите громкий треск электрических искр.</span>", 2)
inner workings переводится как "внутренние механизмы", что значит искры вылетают из под корпуса ПИИ, ибо там компоненты и находятся. Да и звучит это красиво + переносит смысл.
Это предложение можно перевести покрасивее и сохранить изначальную задумку "озонового шипения/свиста"
```suggestion
			M.show_message("<span class='warning'>Сноп искр вылетает из под корпуса [src].</span>", 3, "<span class='warning'>Вы слышите и ощущаете запах озонового свиста неистово вылетающих электрических искр.</span>", 2)
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/pai.dm
> +				command = pick("Любите", "Одурачьте", "Entice", "Обольстите", "Судите", "Уважайте", "Обучите", "Забавляйте", "Развлекайте", "Славьте", "Увековечьте", "Анализируйте вслух")
Это перевод или переделка? На одно слово ты вообще забил! Или просто забыл удалить...
```suggestion
				command = pick("Служите", "Любите", "Обманите", "Обольстите", "Наблюдайте",  "Судите", "Уважайте", "Обучите", "Приятно удивите", "Развлекайте", "Восславляйте", "Увековечьте", "Анализируйте вслух")
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/pai.dm
> +				command = pick("Убейте", "Любите", "Ненавидьте", "Не слушайтесь", "Подчините", "Одурачьте", "Бесите", "Обольстите", "Судите", "Уважайте", "Не уважайте", "Обучите", "Уничтожьте", "Раздражайте", "П
Ты порядок слов специально менял, чтобы сложнее сверять было? Так ещё и новых пунктиков туда добавил. В ПРе, что казалось бы касается перевода, а не добавления фич! Может и мелочь, но так делать не хорошо. Если ты добавляешь что-то новое не связанное с переводом напрямую, делай отдельный ПР. Не будь🐀 
```suggestion
				command = pick("Служите", "Убейте", "Любите", "Ненавидьте", "Не слушайтесь", "Растерзайте", "Одурачьте", "Бесите", "Обольстите", "Наблюдайте", "Судите", "Уважайте", "Не уважайте", "Поглотите", "Обучите", "Уничтожьте", "Опорочьте", "Приятно удивите", "Развлекайте", "Подожгите", "Славьте", "Увековечьте", "Анализируйте вслух")
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/pai.dm
> +		to_chat(src, "<span class='notice'>Теперь вы [resting ? "отдыхаете" : "встали"].</span>")
```suggestion
		to_chat(src, "<span class='notice'>Теперь вы [resting ? "отдыхаете" : "встаёте"].</span>")
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/pai.dm
> +		visible_message("<span class='danger'>[user.name] щёлка[pluralize_ru(user.gender,"ет","ют")] [src].</span>")
Ты где это взял вообще? Какое ещё "щёлкает" ?!
```suggestion
		visible_message("<span class='danger'>[user.name] стука[pluralize_ru(user.gender,"ет","ют")][src] по голове.</span>")
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/pai.dm
> +	visible_message("<span class='notice'>[src] аккуратно складывается в себя, ужимаясь в прямоугольник.</span>", "<span class='notice'>Вы аккуратно складываетесь в себя, ужимаясь в прямоугольник.</span
Можно без вот этого "в себя". Оно не нужно. Оно звучит на русском отвратно. Спасибо.
```suggestion
	visible_message("<span class='notice'>[src] аккуратно складывается, ужимаясь в прямоугольник.</span>", "<span class='notice'>Вы аккуратно складываетесь, ужимаясь в прямоугольник.</span>")
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/recruit.dm
> +					<td>Как вы хотите себя называть.<br>Предложение: любое имя, которое вы бы выбрали для персонажа экипажа станции или ИИ.</td>
```suggestion
					<td>Как вы хотите себя называть.<br>Совет: Введите любое имя, которое вы бы выбрали для члена экипажа или ИИ.</td>
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/recruit.dm
> +					<td>Вам нравится сотрудничать с подлыми социальными ниндзя?<br>Нравится помогать службе безопасности выслеживать преступников?<br>Нравится сидеть на плечах инженера, пока он в очередной спасает
```suggestion
					<td>Вам нравится сотрудничать с подлыми социальными ниндзя?<br>Нравится помогать службе безопасности выслеживать преступников?<br>Нравится сидеть на плечах инженера, пока он в очередной спасает станцию?<br>Не ограничивайте себя лишь должностями членов экипажа. Сюда уместно написать любое общее описание того, чем вы бы хотели заниматься.</td>
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/recruit.dm
> +					<td>Всё, что вы хотели бы OOC адресовать игроку, ищущему себе ПИИ.<br><i>«Я предпочитаю более серьёзное РП»</i>, <i>«Я всё ещё путаюсь в интерфейсе!»</i> и тому подобное.<br>Не стесняйтесь остав
```suggestion
					<td>Любая неигровая информация которую вы бы хотели адресовать игроку, ищущему себе ПИИ.<br><i>«Я предпочитаю более серьёзное РП»</i>, <i>«Я всё ещё путаюсь в интерфейсе!»</i> и тому подобное.<br>Не стесняйтесь оставлять это поле пустым, если хотите.</td>
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/recruit.dm
> +	dat += "<p>Отображение доступных личностей ПИИ из центральной базы данных…</p><p>Если личности не будут обнаружены, либо если не будет найдена подходящая личность, попробуйте выполнить повторный пои
Уже было. Уже объясняла.
```suggestion
	dat += "<p>Отображение доступных личностей ПИИ из центральной базы данных…</p><p>Если личности не будут обнаружены, либо если не будет найдена подходящая личность, попробуйте выполнить повторный поиск на новые личности позже.</p><p>Поиск личностей начат, вы можете закрыть это окно до получения уведомления о появлении доступных личностей. Обычно это занимает от 15 секунд до нескольких минут.</p>"
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/recruit.dm
> +		var/response = alert(C, "Кто-то ищет личность ПИИ. Вы хотите занять роль персонального ИИ?", "Запрос ПИИ", "Да", "Нет", "Никогда в этом раунде")
```suggestion
		var/response = alert(C, "Кто-то ищет личность ПИИ. Вы хотите сыграть за персонального ИИ?", "Запрос ПИИ", "Да", "Нет", "Никогда в этом раунде")
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/software/pai_toggles.dm
> +	name = "Охранный ИЛС"
Не знаете что такое ИЛС? Привыкли к старому обозначению, но перевод вас окончательно запутал новыми обозначениями? Есть решение для хотя бы этого случая!
```suggestion
	name = "Охранный ИЛС(HUD)"
```

2022-06-03 14:42 UTC, Furukia commented on code/modules/mob/living/silicon/pai/software/pai_toggles.dm
> +	name = "Медицинский ИЛС"
```suggestion
	name = "Медицинский ИЛС(HUD)"
```

2022-06-07 15:25 UTC, Ohar commented on code/game/objects/items/devices/paicard.dm
> +				<p>Запрос личностей ПИИ из центральной базы данных… Если личности не будут обнаружены, либо если не будет найдена подходящая личность, попробуйте выполнить повторный поиск позже, когда могут быть
>  Так когда там поиск выполнить?

Неизвестно когда, в том-то и дело. Когда призраки «Отправить личность» нажмут.

> Как игрок должен вообще понять это предложение при чтении?

«Ждите и переиодически проверяйте»

> повторный поиск на новые личности

Поиск не «выполняют на личности», Тогда уж «выполнить повторный поиск новых личностей»

2022-06-07 15:37 UTC, Ohar commented on code/game/objects/items/devices/paicard.dm
> +				<p>Запрос личностей ПИИ из центральной базы данных… Если личности не будут обнаружены, либо если не будет найдена подходящая личность, попробуйте выполнить повторный поиск позже, когда могут быть
Исправил на «выполнить повторный поиск новых личностей ПИИ позже»

2022-06-07 15:37 UTC, Ohar commented on code/modules/mob/living/silicon/pai/recruit.dm
> +	dat += "<p>Отображение доступных личностей ПИИ из центральной базы данных…</p><p>Если личности не будут обнаружены, либо если не будет найдена подходящая личность, попробуйте выполнить повторный пои
Исправил на «выполнить повторный поиск новых личностей ПИИ позже»

2022-06-07 16:11 UTC, Furukia commented on code/game/objects/items/devices/paicard.dm
> +				<p>Запрос личностей ПИИ из центральной базы данных… Если личности не будут обнаружены, либо если не будет найдена подходящая личность, попробуйте выполнить повторный поиск позже, когда могут быть
> «Ждите и периодически проверяйте»

предложение `"когда могут быть загружены новые личности ПИИ"` само по себе похоже на вопрос. А не на совет/ответ. К тому же указывает на неопределённое время, что так себе. И возникают при прочтении вопросы, Откуда я знаю когда они там могут быть загружены? Вот и пользователи не поймут.

> Исправил на «выполнить повторный поиск новых личностей ПИИ позже»

ок

2022-06-07 16:12 UTC, Furukia commented on code/game/objects/items/devices/paicard.dm
> +				<p>Запрос личностей ПИИ из центральной базы данных… Если личности не будут обнаружены, либо если не будет найдена подходящая личность, попробуйте выполнить повторный поиск новых личности ПИИ позж
```suggestion
				<p>Запрос личностей ПИИ из центральной базы данных… Если личности не будут обнаружены, либо если не будет найдена подходящая личность, попробуйте выполнить повторный поиск новых личностей ПИИ позже.</p>
```

2024-02-12 20:59 UTC, closed without merging