Tweak: Перевод общения со слаймами
ss220-space/Paradise pull request #933
Opened 2022-05-24 01:53 UTC by Ohar

## What Does This PR Do
— Переводит фразы слаймов на русский язык
— Переводит речевые глаголы слаймов на русский язык
— Позволяет слаймам понимать команды на русском языке

## Why It's Good For The Game
Позволяет общаться со слаймами и командовать им на русском языке

### Обращение к слаймам
Все команды должны включать обращение
#### Было 
- номер слайма
- slimes
#### Добавлены варианты обращений к слаймам
- слайм
- слаймы
### Приветствие
#### Было 
- hello
- hi
#### Добавлены команды приветствия
- привет
- здравствуй
### Следование за говорящим
#### Было 
- follow
#### Добавлены команды приветствия
- пойдём
- за мной
- идём
- иди
- пошли
- ко мне
- сюда
### Прекращение действия (прекратить жрать, прекратить гнаться, прекратить следовать)
#### Было 
- stop
#### Добавлены команды приветствия
- стоп
- стой
- фу
- стоять
### Стоять на месте
#### Было 
- stay
#### Добавлены команды приветствия
- сидеть
- ждать
- жди
### Атаковать
#### Было 
- attack
#### Добавлены команды атаки
- фас
- бей
- ешь

## Changelog
:cl:
tweak: tweaked a few things
/:cl:

2022-05-24 06:13 UTC, Vallat requested changes

2022-05-24 06:13 UTC, Vallat commented on code/modules/mob/living/simple_animal/slime/life.dm
> +		if((findtext(phrase, num2text(number)) || findtext(phrase, "slimes") || findtext(phrase, "слаймы") || findtext(phrase, "слайм"))) // Talking to us
```suggestion
		if((findtext(phrase, num2text(number)) || findtext(phrase, "slimes") || findtext_char(phrase, "слайм"))) // Talking to us
```

2022-05-24 06:13 UTC, Vallat commented on code/modules/mob/living/simple_animal/slime/life.dm
> +							to_say = "Нет… [pick("Всё равно", "Буду")] идти…"
```suggestion
							to_say = "Нет… [pick("всё равно", "буду")] идти…"
```

2022-05-24 06:13 UTC, Vallat commented on code/modules/mob/living/simple_animal/slime/life.dm
> +						to_say = "Нет… [pick("Всё равно", "Буду")] [pick("идти", "ходить")]…"
```suggestion
						to_say = "Нет… [pick("всё равно", "буду")] [pick("идти", "ходить")]…"
```

2022-05-24 06:13 UTC, Vallat commented on code/modules/mob/living/simple_animal/slime/life.dm
> +								to_say = "Нет… [pick("Нравиться", "Любить")] [L]…"
```suggestion
								to_say = "Нет… [pick("нравится", "любить")] [L]…"
```

2022-05-24 11:02 UTC, Ohar commented on code/modules/mob/living/simple_animal/slime/life.dm
> +							to_say = "Нет… [pick("Всё равно", "Буду")] идти…"
Там новое предложение же

2022-05-24 15:10 UTC, Vallat commented on code/modules/mob/living/simple_animal/slime/life.dm
> +							to_say = "Нет… [pick("Всё равно", "Буду")] идти…"
Лан

2022-05-24 15:11 UTC, Vallat approved these changes

2022-05-25 04:36 UTC, PhantornRU reviewed
Лучше дополнить словарный запас и ввести к пониманию слаймов оба написания разговорных слов с Ё и Е

2022-05-25 04:36 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/slime/life.dm
> +			else if(findtext(phrase, "stop") || findtext_char(phrase, "фу") || findtext_char(phrase, "стоп"))
```suggestion
			else if(findtext(phrase, "stop") || findtext_char(phrase, "фу") || findtext_char(phrase, "стоп") || findtext_char(phrase, "стой") || findtext_char(phrase, "стоять"))
```

2022-05-25 04:36 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/slime/life.dm
> +			else if(findtext(phrase, "attack") || findtext_char(phrase, "фас") || findtext_char(phrase, "бей") || findtext_char(phrase, "ешь"))
```suggestion
			else if(findtext(phrase, "attack") || findtext_char(phrase, "фас") || findtext_char(phrase, "бей") || findtext_char(phrase, "ешь") || findtext_char(phrase, "атакуй") || findtext_char(phrase, "съешь") || findtext_char(phrase, "уничтожь"))
```

2022-05-25 04:36 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/slime/life.dm
> +			else if(findtext(phrase, "follow") || findtext_char(phrase, "пойдём") || findtext_char(phrase, "за мной") || findtext_char(phrase, "идём") || findtext_char(phrase, "пошли") || findtext_char(phrase
Некоторые как я не используют букву "Ё" при разговорном написании. Лучше добавить несколько вариантов с учетом наличия и отсутствия "Ё"
```suggestion
			else if(findtext(phrase, "follow") || findtext_char(phrase, "пойдём") || findtext_char(phrase, "пойдем") || findtext_char(phrase, "за мной") || findtext_char(phrase, "идём") || findtext_char(phrase, "идем") || findtext_char(phrase, "пошли") || findtext_char(phrase, "ко мне") || findtext_char(phrase, "вперёд") || findtext_char(phrase, "вперед") || findtext_char(phrase, "погнали") || findtext_char(phrase, "следуй"))
```

2022-05-29 11:11 UTC, Ohar commented
> Лучше дополнить словарный запас и ввести к пониманию слаймов оба написания разговорных слов с Ё и Е

Я тоже сначала понаписал туда командных фраз целый мешок.
Но потом почистил их.
Обрати внимание что на английском команда одна.
Эта штука просто просчитывается для каждого слайма на каждую фразу и каждый раз делается поиск. Даже если ты не командуешь.
Если у 2 два слайма и ты при них сказал 2 фразы и есть 2 управляющих команды, то для их обработки и поиска нужно будет выполнить 2×2×2 = 8 поисков текста.
А если у 30 слаймов и ты при них сказал 2 фразы и есть 5 управляющих команд, то для их обработки и поиска нужно будет выполнить 30×2×5 = 300 поисков текста.
Этр крайне печально может сказаться на происзводительности.

2022-06-02 20:16 UTC, merged