Автозаполнение для документов [paper_field]
ss220-space/Paradise pull request #934
Opened 2022-05-24 15:05 UTC by PhantornRU

## What Does This PR Do
Теперь по нажатию на маленькую кнопку возле редактирования текста - у вас есть возможность выбрать пункт текста из меню автозаполнения.
Работает только с [paper_field] и не относится к другим вариантам написания текста.
Не требует переделывания всех документов, т.к. работает напрямую с полем.
![image](https://user-images.githubusercontent.com/41479614/170067771-fed45441-a576-4fb4-9998-75875b0e1771.png)

Меню выбора пунктов заполнения текстом:
![image](https://user-images.githubusercontent.com/41479614/170067802-1f7feb6f-9ba9-41b8-afab-318f15b55a96.png)

Результаты выбора заполнения, где по прежнему можно редактировать:
![image](https://user-images.githubusercontent.com/41479614/170067835-e7556a89-1ddb-4398-9f64-ec80ccce55c0.png)

Результаты, когда не пользуешься ручкой:
![image](https://user-images.githubusercontent.com/41479614/170068197-0f2971dd-5dc0-4987-85f7-abdc37eac347.png)

Заполнение пустого документа:
По прежнему не имеет кнопки автозаполнения в связи с ненадобностью.
![image](https://user-images.githubusercontent.com/41479614/170068295-1bfefd63-4fc6-4044-815a-8bfc328ccad0.png)

## Why It's Good For The Game
Бюрократия будет гораздо проще и веселее.

## Images of changes
![image](https://user-images.githubusercontent.com/41479614/170067656-c57729c2-a239-49e7-b632-b8fbeea52458.png)

2022-05-24 15:11 UTC, Vallat approved these changes

2022-05-24 15:14 UTC, Vallat requested changes

2022-05-24 15:14 UTC, Vallat commented on code/modules/paperwork/paper.dm
> +		var/list/L = list()
👺 переименовать

2022-05-24 15:14 UTC, Vallat commented on code/modules/paperwork/paper.dm
> +		if (usr.real_name != (usr.name || "unknown"))
Это не сработает
```suggestion
		if (usr.real_name != usr.name || usr.real_name != "unknown"))
```

2022-05-24 15:14 UTC, Vallat commented on code/modules/paperwork/paper.dm
> +		var/t = input("Выберите текст который хотите добавить:", "Выбор пункта") as null|anything in L
переименовать переменную

2022-05-24 15:14 UTC, Vallat commented on code/modules/paperwork/paper.dm
> +		var/obj/item/i = usr.get_active_hand() // Check to see if he still got that darn pen, also check if he's using a crayon or pen.
переименовать переменную

2022-05-24 16:19 UTC, PhantornRU commented
Внес правки.

Также забыл упомянуть:
Если вы скрываетесь за другим именем, то добавится дополнительный пункт с данным именем на выбор.

2022-05-24 16:43 UTC, Vallat requested changes

2022-05-24 16:43 UTC, Vallat commented on code/modules/paperwork/paper.dm
> +		//	menu_list.Add("[usr.voice_name]")
```suggestion
```

2022-05-25 04:35 UTC, Vallat approved these changes

2022-05-29 16:19 UTC, merged