Add: Система склонений предметов
ss220-space/Paradise pull request #935
Opened 2022-05-24 16:04 UTC by Ohar

## What Does This PR Do
Добавлена система склонений предметов (через свойство `name_ru`, процедуру `declent_ru` и константы падежей), которую можно применять для безболезненного использования называния предметов на русском языке в правильных падежах

Включает пример использования в сообщении о суициде челюстями жизни.

## Why It's Good For The Game

Система будет применяться во всех будущих переводах и послужит основой для нормального перевода названий предметов и одной из точек использования будущего переключателя языка.

## Changelog
:cl:
add: Добавлена система склонений предметов
/:cl:

2022-05-25 04:37 UTC, Vallat requested changes

2022-05-25 04:37 UTC, Vallat commented on code/game/atoms.dm
> +	if(name_ru != null && length(name_ru))
`length()` уже проверяет на нулл-кейс
```suggestion
	if(length(name_ru))
```

2022-05-25 04:37 UTC, Vallat commented on code/game/atoms.dm
> +		return name
```suggestion
	return name
```

2022-05-25 04:37 UTC, Vallat commented on code/game/atoms.dm
> +	var/list/name_ru
Рекомендую в комментарий добавить пример заполнения списка для корректной работы

2022-05-25 16:07 UTC, Ohar commented on code/game/atoms.dm
> +	var/list/name_ru
```suggestion
	/// Список склонений названия атома. Пример заполнения в любом наследнике атома
	/// name_ru = list(NOMINATIVE = "челюсти жизни", GENITIVE = "челюстей жизни", DATIVE = "челюстям жизни", ACCUSATIVE = "челюсти жизни", INSTRUMENTAL = "челюстями жизни", PREPOSITIONAL = "челюстях жизни")
	var/list/name_ru
```

2022-05-25 16:37 UTC, Vallat commented on code/game/atoms.dm
> +#define PREPOSITIONAL "prepositional" // Предложный: прохладная история о ком? О клоуне и об ассистухе
```suggestion
#define NOMINATIVE 1 // Именительный: кто это? Клоун и ассистуха
#define GENITIVE 2 // Родительный: откусить кусок от кого? От клоуна и ассистухи
#define DATIVE 3 // Дательный: дать полный доступ кому? Клоуну и ассистухе
#define ACCUSATIVE 4 // Винительный: обвинить кого? Клоуна и ассистуху
#define INSTRUMENTAL 5 // Творительный: возить по полу кем? Клоуном и ассистухой
#define PREPOSITIONAL 6 // Предложный: прохладная история о ком? О клоуне и об ассистухе
```

2022-05-25 16:37 UTC, Vallat commented on code/game/atoms.dm
> +	return name
```suggestion
/atom/proc/declent_ru(case_id, list/ru_names_override)
	var/list/list_to_use = ru_names_override || name_ru
	if(length(list_to_use))
		return list_to_use[case_id] || name
	return name
```

2022-05-25 16:51 UTC, Ohar commented on code/game/atoms.dm
> +#define PREPOSITIONAL "prepositional" // Предложный: прохладная история о ком? О клоуне и об ассистухе
Уже влил сам

2022-05-25 16:51 UTC, Ohar commented on code/game/atoms.dm
> +	return name
Аналогично, уже сам написал это

2022-05-25 16:54 UTC, Vallat approved these changes

2022-05-29 16:22 UTC, merged

2022-05-29 17:15 UTC, Bizzonium commented on code/game/objects/items/tools/crowbar.dm
> +    	playsound(loc, 'sound/items/jaws_pry.ogg', 50, 1, -1)
тут ошибка с отступом, советую компилить в след раз

2022-05-29 17:19 UTC, Bizzonium commented on code/game/objects/items/tools/crowbar.dm
> +	user.visible_message("<span class='suicide'>[user] помеща[pluralize_ru(user.gender,'ет','ют')] свою голову между лезвиями [src.declent_ru(GENITIVE)]. Похоже, [genderize_ru(user.gender,'он','она','он
Одинарные кавычки вызывают ошибки