fix: Code warnings to 0
ss220-space/Paradise pull request #940
Opened 2022-05-26 16:16 UTC by BeebBeebBoob

## What Does This PR Do

Чистим код
## Images of changes

![image](https://user-images.githubusercontent.com/32985153/170529324-6b2983a1-ce31-41b4-acff-afcf5ff24fa4.png)

## Changelog
:cl:
fix: some warnings 
/:cl:

2022-05-26 19:12 UTC, Gaxeer requested changes

2022-05-26 19:12 UTC, Gaxeer commented on code/game/machinery/computer/syndie_cargo.dm
> +			playsound(get_turf(P), 'sound/weapons/emitter2.ogg', 25, 1, extrarange = 3, falloff = 5)
```suggestion
		for(var/obj/machinery/syndiepad/recieving_pad as anything in recievingPads)
			recieving_pad .use_power(10000 / recieving_pad .power_efficiency)
			flick("sqpad-beam", recieving_pad )
			playsound(get_turf(P), 'sound/weapons/emitter2.ogg', 25, 1, extrarange = 3, falloff = 5)
```
Ты код сломал, если что. Там рантаймит

2022-05-26 19:12 UTC, Gaxeer commented on code/game/machinery/computer/syndie_cargo.dm
> +					P.checks(usr)
```suggestion
				for(var/obj/machinery/syndiepad/linked_pad as anything in DSLP)
					linked_pad.checks(usr)
```

2022-06-03 06:03 UTC, Vallat requested changes

2022-06-03 06:03 UTC, Vallat commented on code/game/machinery/computer/syndie_cargo.dm
> +			playsound(get_turf(P), 'sound/weapons/emitter2.ogg', 25, 1, extrarange = 3, falloff = 5)
```suggestion
			playsound(get_turf(recieving_pad), 'sound/weapons/emitter2.ogg', 25, 1, extrarange = 3, falloff = 5)
```

2022-06-04 07:12 UTC, Vallat approved these changes

2022-06-05 21:17 UTC, merged