Боевое искусство клана Плазменного Кулака [+uplink]
ss220-space/Paradise pull request #943
Opened 2022-05-27 10:43 UTC by PhantornRU

## What Does This PR Do
### Введение нового боевого искусства клана Плазменного Кулака
![image](https://user-images.githubusercontent.com/41479614/170680892-449dd651-eff4-4780-8bef-0056481e5a54.png)

### Особенности:
- 5 уникальных приемов
- Приемы взаимосвязаны с плазмой и обжигающим уроном.
- Обжигающие харм-атаки 13-18
- Выбивающие воздух дизарм-атаки
- Возможность буквально вышибить мозги поверженного оппонента.
- Устойчивость к огню.
- Полная устойчивость к лазерному оружию.
- 50% шанс блокирования энерго-оружия.
- Восприимчивость к грубому урону.
- Невозможность использования дальнего оружия в угоду баланса отражения лазерного и частично энерго-оружия.
- Возможность покупки в Аплинке за 14 Т.К. с возвратом.
![image](https://user-images.githubusercontent.com/41479614/170681348-ac75e1ab-a78b-449c-9304-c51e388693bd.png)

Аплинк:
![image](https://user-images.githubusercontent.com/41479614/170681504-c79cc4eb-b3e7-4b1d-a8f7-81204c4e53fa.png)

## Приемы
Вихрь торнадо: Harm Harm Disarm. Раскидывает всех кто находится рядом.
![image](https://user-images.githubusercontent.com/41479614/170681964-6cbfcac8-f670-48bd-9d03-0f29b499aaf5.png) 
![image](https://user-images.githubusercontent.com/41479614/170682046-20e26ca2-ed3c-440b-af23-ba24ad463f17.png)

### Плазма-торнадо: 
Harm Disarm Harm Disarm Disarm. Распыляет плазму вокруг, поджигая всех кто находится рядом. Прием требующий мастерства.
![image](https://user-images.githubusercontent.com/41479614/170682381-a09d3627-7c47-487f-900b-932cb63f77b2.png)
![image](https://user-images.githubusercontent.com/41479614/170682433-9554abfd-06d3-4e8a-baa4-04571ed2422d.png)

###Плазмо-дыхание: 
Disarm Disarm Disarm Help. Выдывливает воздух из лёгких, заменяя её плазмой и заставляя её изрыгнуть!
![image](https://user-images.githubusercontent.com/41479614/170682313-513410e2-39e9-4568-a4a9-cfbad935b582.png)

###Отбросить:
Disarm Harm Disarm. Отбрасывает цель далеко вперед, приводя его в замешательство
![image](https://user-images.githubusercontent.com/41479614/170682168-2499810b-ca61-4096-ad9f-20274cb10a59.png)
![image](https://user-images.githubusercontent.com/41479614/170682225-c5a87207-a64b-4eab-81a0-9cb2dbf03e9f.png)

###Плазменный кулак: 
Harm, Disarm, Disarm, Disarm, Grab, switch hands, Harm. Выбивает мозги из оппонента, разрывая его тело на части, если он он достаточно поражен и прожжен. Иначе заставляет его ослепительно вспыхнуть!

Плазменный Кулак - Когда противник достаточно повержен:
![image](https://user-images.githubusercontent.com/41479614/170684159-88b87240-bf72-40d0-bbb3-11dbb22f53cb.png)
![image](https://user-images.githubusercontent.com/41479614/170684237-45c43a11-90ef-4fdf-aab3-790cfc9bb821.png)
![image](https://user-images.githubusercontent.com/41479614/170684269-42eff751-f69a-4371-a897-0395bebad324.png)

Плазменный Кулак - Когда противник недостаточно повержен:
![image](https://user-images.githubusercontent.com/41479614/170684335-b8dba32e-df65-4f76-b76c-a6c941bac525.png)
![image](https://user-images.githubusercontent.com/41479614/170684383-11153571-5998-4ddc-af13-25c7c42fbc0c.png)

## Why It's Good For The Game
Новое боевое искусство для разнообразия боевых искусств.

## Images of changes
![image](https://user-images.githubusercontent.com/41479614/170680913-fda9214d-ce03-44f4-9e94-8113a440b4b5.png)
![image](https://user-images.githubusercontent.com/41479614/170681348-ac75e1ab-a78b-449c-9304-c51e388693bd.png)

Стойкость к огню:
![image](https://user-images.githubusercontent.com/41479614/170682581-a72ebc12-f21d-44a9-b38d-cfbdad0f69b4.png)

Отражение снарядов:
![image](https://user-images.githubusercontent.com/41479614/170682956-25517867-c2fe-4b4c-b109-9443b4dd734e.png)

2022-05-27 10:46 UTC, PhantornRU commented
##Одобрено Авоутами:

###Фиксы и дополнение заброшенных боевых искусств:
####Плазменный Кулак
####Мимдзюцу
https://discord.com/channels/617003227182792704/755125334097133628/978974221084545054

###Внесение боевого искусства Плазменный Кулак в Аплинк 
Изначально планировалось 12 тк. Но для баланса установлена цена в 14 тк. Это всё еще не карп, но хорошее боевое искусство для борьбы против толп.
https://discord.com/channels/617003227182792704/755125334097133628/978974330438426674

2022-05-27 11:03 UTC, Gaxeer commented on code/datums/uplink_item.dm
> +			Свиток древнего клана, не приемлющего использование орудий дальнего боя."
```suggestion
	desc = "Знания древней техники боевых искусств рукопашной борьбы огнём и плазмой, \
			нацеленное на превосходящее число противников. \
			В нём сокрыты секреты сопротивления лазеру и энергии. \
			Свиток древнего клана, не приемлющего использование орудий дальнего боя."
```

2022-05-27 11:11 UTC, Gaxeer commented on code/modules/martial_arts/combos/plasma_fist/plasma_fist.dm
> +	explaination_text = "Выбивает мозги из оппонента, разрывая его тело на части, если он он достаточно поражен и прожжен. Иначе заставляет его ослепительно вспыхнуть!"
```suggestion
	explaination_text = "Выбивает мозги из оппонента, разрывая его тело на части, если он достаточно поражен и прожжен. Иначе заставляет его ослепительно вспыхнуть!"
```

2022-05-27 19:30 UTC, Vallat requested changes

2022-05-27 19:30 UTC, Vallat commented on code/game/dna/genes/powers.dm
> +		return "cold_s"
```suggestion
	if (!M.mind?.martial_art?.fire_resistance)
		return "cold_s"
	return ""
```

2022-05-27 19:30 UTC, Vallat commented on code/modules/martial_arts/combos/plasma_fist/plasma_tornado.dm
> +		var/atom/movable/AM = am
Поменяй еще `M` чуть ниже по коду
```suggestion
	for(var/atom/movable/AM as anything in thrownatoms)
```

2022-05-27 19:30 UTC, Vallat commented on code/modules/martial_arts/combos/plasma_fist/tornado_sweep.dm
> +		var/atom/movable/AM = am
Поменяй еще `M` чуть ниже по коду
```suggestion
	for(var/atom/movable/AM as anything in thrownatoms)
```

2022-05-28 03:11 UTC, PhantornRU commented on code/modules/martial_arts/combos/plasma_fist/plasma_tornado.dm
> +		var/atom/movable/AM = am
Не совсем понял какие именно изменения к М нужно внести, кроме как к АМ

2022-05-28 05:14 UTC, Vallat commented on code/modules/martial_arts/combos/plasma_fist/plasma_tornado.dm
> +		var/atom/movable/AM = am
Переименовать её

2022-05-28 06:19 UTC, PhantornRU commented on code/modules/martial_arts/combos/plasma_fist/plasma_tornado.dm
> +		var/atom/movable/AM = am
Переименовал, щас залью.

2022-05-28 07:33 UTC, Vallat approved these changes

2022-05-28 09:43 UTC, PhantornRU commented
Данный ПР переведен в драфт до момента балансировки.

2022-05-28 11:49 UTC, PhantornRU commented
В планах перенести приемы плазмо-торнадо, торнадо, плазмо-дыхание в абилки с кулдауном.

Переработан крит-прием плазменного кулака, теперь он дезоориентирует цель при недостаточных условий нанесения урона.
Из неё вынесена вспышка в отдельный прием.

2022-05-28 17:49 UTC, Jordanstolethepreciousslam commented on code/modules/martial_arts/plasma_fist.dm
> +		D.apply_damage(60, OXY)
Окей я понимаю что это окси урон и для этого надо лечь, но это совсем конское значение. Для боевого искусства не направленного на дуэли это слишком большой урон по не ожидающей нападения цели. В бою ты не ляжешь а подлавливать в крысу ты вроде не собираешся ведь искусство то против толпы а не для дуэлей

2022-05-28 17:49 UTC, Jordanstolethepreciousslam commented on code/modules/martial_arts/combos/plasma_fist/throwback.dm
> +	target.Jitter(15)		//дрожь
Если ты хочешь замешательство тебе нужен Confuse. И 15 это слишком дохуя. Ты делаешь чела инвалидом до конца драки по сути. Да, стрелять он может но будет ли у него время если он горит и задыхается?

2022-05-28 17:49 UTC, Jordanstolethepreciousslam commented on code/modules/martial_arts/combos/plasma_fist/plasma_breath.dm
> +	target.adjustToxLoss(60) //получение токсинов. Плазмаменам повезло.
Вместе с дамагом от дизарма общий урон с комбы - 150+. Плюс цель задыхается 5 тиков что еще 25 урона. Эта абилка дамажит сильнее чем комба на вышибание мозгов взрывом. Ты определись хочешь ли ты абилку для засирания плазмой толпы врагов или абилку для для унижения одиночек

2022-05-28 17:49 UTC, Jordanstolethepreciousslam commented on code/modules/martial_arts/combos/plasma_fist/plasma_blink.dm
> +	target.AdjustEyeBlind(8) 	//потеря зрения
Не перебарщивай. 14 секунд полной слепоты это практически вся драка.

2022-05-28 17:49 UTC, Jordanstolethepreciousslam commented on code/modules/martial_arts/combos/plasma_fist/plasma_blink.dm
> +	target.AdjustConfused(15)	//потерянность (ходьба в разные стороны)
Серьезно не сходи с ума со смятением. Я понимаю что это не полный контроль типа стана но 25 секунд инвалидности это слишком. У тебя ведь искусство против толпы а не крыса-пироман отлавливающий одиночек и превращающий их в беспомощных инвалидов на пол минуты

2022-05-28 17:49 UTC, Jordanstolethepreciousslam commented on code/modules/martial_arts/plasma_fist.dm
> +			D.Jitter(2)	//замешательство на 2 секунды
Confuse. И ты уверен что тебе надо его каждый второй удар накладывать? Обойдись замедлением

2022-05-29 02:05 UTC, PhantornRU commented on code/modules/martial_arts/plasma_fist.dm
> +			D.Jitter(2)	//замешательство на 2 секунды
Jitter - это дрожь, не конфуз.
Ничего не делает для человека кроме как заставляет его дергаться.

2022-05-29 08:59 UTC, Jordanstolethepreciousslam commented on code/modules/martial_arts/plasma_fist.dm
> +			D.Jitter(2)	//замешательство на 2 секунды
Я про комментарий

2022-05-29 09:08 UTC, PhantornRU commented on code/modules/martial_arts/plasma_fist.dm
> +			D.Jitter(2)	//замешательство на 2 секунды
А, не поправил при копировании.

2022-05-29 11:08 UTC, Ohar requested changes

2022-05-29 11:08 UTC, Ohar commented on code/datums/uplink_item.dm
> +	name = "Истлевший Свиток"
```suggestion
	name = "истлевший свиток"
```

2022-05-29 11:08 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/plasma_breath.dm
> +	explaination_text = "Выдывливает воздух из лёгких, заменяя её плазмой и заставляя её изрыгнуть!"
```suggestion
	explaination_text = "Выдавливает воздух из лёгких, заменяя его плазмой и заставляя её изрыгнуть!"
```

2022-05-29 11:08 UTC, Ohar commented on code/modules/martial_arts/combos/plasma_fist/plasma_tornado.dm
> +	explaination_text = "Распыляет плазму вокруг, поджигая всех кто находится рядом. Прием требующий мастерства."
```suggestion
	explaination_text = "Распыляет плазму вокруг, поджигая всех, кто находится рядом. Приём, требующий мастерства."
```

2022-05-29 11:08 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +	desc = "Старый истлевший пергамент, исписаный выжжеными рунами с иллюстрациями приемов рукопашного боя."
```suggestion
	desc = "Старый истлевший пергамент, исписаный выжжеными рунами с иллюстрациями приёмов рукопашного боя."
```

2022-05-29 11:08 UTC, Ohar commented on code/modules/martial_arts/martial.dm
> +		to_chat(H, "<span class='boldannounce'>Вы изучили древнее искусство Плазменного Кулака</span>")
```suggestion
		to_chat(H, "<span class='boldannounce'>Вы изучили древнее искусство Плазменного кулака</span>")
```

2022-05-29 11:08 UTC, Ohar commented on code/modules/martial_arts/plasma_fist.dm
> +	name = "Плазменный Кулак"
```suggestion
	name = "Плазменный кулак"
```

2022-05-29 11:08 UTC, Ohar commented on code/modules/martial_arts/plasma_fist.dm
> +	var/picked_hit_type = pick("ударил[gender_hit] пылающим кулаком", "прожига[pluralize_ru(A.gender,"ет","ют")] пылающим кулаком", "пробил[gender_hit] пылающим кулаком", "пробил[gender_hit] кулаком в с
```suggestion
	var/picked_hit_type = pick("ударил[gender_hit] пылающим кулаком", "прожига[pluralize_ru(A.gender,"ет","ют")] пылающим кулаком", "пробил[gender_hit] пылающим кулаком", "пробил[gender_hit] кулаком в солнечное сплетение", "ударил[gender_hit] под рёбра", "ударил[gender_hit] под дых", "пробил[gender_hit]", "ударил[gender_hit] в нутро", "размашисто ударил[gender_hit] по рёбрам сбоку")
```

2022-05-29 11:08 UTC, Ohar commented on code/modules/martial_arts/plasma_fist.dm
> +	to_chat(user, "<b><i>Вы сжимаете кулаки и чувствуете внутреннее пламя расползающее по вашему телу...</i></b>")
```suggestion
	to_chat(user, "<b><i>Вы сжимаете кулаки и чувствуете внутреннее пламя, расползающее по телу…</i></b>")
```

2022-05-29 11:08 UTC, Ohar commented on code/modules/mob/living/carbon/human/human_defense.dm
> +			visible_message("<span class='danger'>[src] отразил снаряд.</span>", "<span class='userdanger'>Вы отразили снаряд!</span>")
Забыл гендеризацию

2023-07-19 05:28 UTC, closed without merging