Fish Rework: MMO grinding Edition
ss220-space/Paradise pull request #944
Opened 2022-05-29 21:02 UTC by Jordanstolethepreciousslam

Рандомизирует отлавливаемую рыбу и добавляет дополнительные эффекты для нее

Общие изменения
-Теперь каждая рыба имеет размер который изменяет её прочие характеристики
-Каждая рыба имеет "Легендарную" версию со своими особенностями. Шанс получения = 1%
-Цены на икру увеличены в 100 раз. Теперь раундстартовых денег может не хватить даже на стартовую пару икринок+инструменты
-цена рестока увеличена в 10 раз

Электрический угорь
-Теперь наносит урон стамине(до 25) и ожогами(до 10) при ударе(зависит от размера).
-Легендарка наносит 50 стамины и 20 ожогов

Акула
-Теперь дропает кости(крафт брони ага и оружия да) при разделке если размер выше 50
-Легендарная версия при разделке дропает очень много мяса, кожи и костей.

Люминисцентные рыбки
-Теперь сила освещения зависит от света
-Легендарка освещает как станционарный прожектор

сОм
-Количество мяса при разделке теперь зависит от размера(до 10)
-Легендарка слапает людей так что они отлетают(урона правда нет практически, но можно в стену впечатать) и трясет экран при броске

Лосось
-Количество мясо при разделке зависит от размера(до 30)
-Легендарка дропает 60 мяса

Карпики
-Теперь грызут пятки брутом(сквозь армора да), До 24  урона.
-Теперь "сьедают" любую рыбу попавшую к ним на тайл(застакать 100 карпиков не получится да). Сьедение увеличивает урон силу отгрызания пяток.
-Легендарка грызет пятки на 40 урона

Рыба-клоун
-Размер ни на что не влияет
-Легендарка дропает 10 патчей шутостерона и 10 бананиума

Зачем нам это не нужно
-От растянутого мыла кровоточат глаза. Спецдефекты на уровне российского кино
-Полстанции не сможет купить рыбок из-за рандомного стартового капитала
-Грифозная хуита
-Безбалансная хуита
-Ассистухи в фулл костяном арморе с угрями в руках штурмуют бриг
-Кто то будет всерьез заниматся разведением рыбы
-Серьезно не надо

2022-05-30 05:41 UTC, Gaxeer requested changes
Пока так, а дальше посмотрим

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +	if(sizemod == 10)	adj ="colossal"
sizemodы вынеси в одноименные локальные макросы.
#define SIZEMOD_TINY 1
...
#define SIZEMOD_COLOSSAL 10

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +	if(sizemod == 10)	adj ="colossal"
можно эти adj тоже в макросы.
#define ADJ_TINY "tiny"
...
#define ADJ_COLOSSAL "colossal"

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +	if(sizemod == 10)	adj ="colossal"
но второе не обязательно, а первое желательно

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +		sizemod = 20
#define SIZEMODE_UNIQUE 20

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +	if(size == 100)
```suggestion
	switch (size)
		if(1 to 40) w_class = WEIGHT_CLASS_NORMAL
		if(41 to 100) w_class = WEIGHT_CLASS_BULKY
		
	if(size == 100)
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +	var/icon/unique_underlay
Зачем обьявлять переменную для целого класса обьектов, если она используется один раз и только локально, и потом помещается в underlays?

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +	AddComponent(/datum/component/slippery, src, 2, 2, 100, 0, FALSE)
передавай параметры либо именовано, либо оставляй dm-doc
комментарий типа
/*
*
*
*/
где ты распишешь, что какое значение в это процедуре значит

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +/obj/item/fish/clownfish/attackby(var/obj/item/O, var/mob/user as mob)
as в проках не имеет смысла, проверять на тип нужно внутри прока. Это работает только в verbах

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +/obj/item/fish/clownfish/attackby(var/obj/item/O, var/mob/user as mob)
И замени O на weapon

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +	if(istype(AM, /obj/item/fish))
посмотри, есть ли макрос isfish - если нет. то можешь сделать. Но это на твой выбор,  я не принуждаю

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  /obj/item/fish/salmon/attackby(var/obj/item/O, var/mob/user as mob)
```suggestion
/obj/item/fish/salmon/attackby(var/obj/item/weapon, var/mob/user as mob)
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  	if(is_sharp(O))
```suggestion
	if(!is_sharp(weapon))
		return ..()
		
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  		return
```suggestion
	for(var/i = 1 to (sizemod*3))
		new /obj/item/reagent_containers/food/snacks/salmonmeat(get_turf(src))
	qdel(src)
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> -		to_chat(user, "You carefully clean and gut \the [src.name].")
а куда сообщение в чат дел?

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +	..()
```suggestion
	. = ..()
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +	..()
```suggestion
	. = ..()
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
> +		if(!M.stat && !istype(M, /mob/living/silicon/ai))\
```suggestion
		if(!M.stat && !isAI(M))\
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  /obj/item/fish/catfish/attackby(var/obj/item/O, var/mob/user as mob)
```suggestion
/obj/item/fish/catfish/attackby(var/obj/item/weapon, var/mob/user)
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  	..()
```suggestion
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  	if(is_sharp(O))
```suggestion
	if(!is_sharp(weapon))
		return ..()
		
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  	..()
```suggestion
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  		return
```suggestion
	for(var/i = 1 to sizemod)
		new /obj/item/reagent_containers/food/snacks/catfishmeat(get_turf(src))
	qdel(src)
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  		to_chat(user, "You carefully clean and gut \the [src.name].")
```suggestion
	to_chat(user, "You carefully clean and gut \the [src.name].")
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  	if(istype(O, /obj/item/wirecutters))
```suggestion
	if(iswirecutter(weapon))
```

2022-05-30 05:41 UTC, Gaxeer commented on code/modules/fish/fish_items.dm
>  /obj/item/fish/shark/attackby(var/obj/item/O, var/mob/user as mob)
```suggestion
/obj/item/fish/shark/attackby(var/obj/item/weapon, var/mob/user)
```

2022-06-06 07:55 UTC, Vallat requested changes

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +	var/unique_desc
Прописать базовые значения

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +	..()
```suggestion
/obj/item/fish/Initialize()
	. = ..()
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +		if(41 to 100) w_class = WEIGHT_CLASS_BULKY
Однострочный свич - плохо, так еще и отступы разные, отчего читаемость сильнее падает

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +		underlays += unique_underlay
Почему бы это не перенести в свич выше?

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +	..()
```suggestion
	. = ..()
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
>  	..()
Понимаю, что так было, но надо исправлять
```suggestion
	. = ..()
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
>  		return
Понимаю, что так было, но надо исправлять
```suggestion
		return TRUE
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +	qdel(src)
```suggestion
	qdel(src)
	return TRUE
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +	qdel(src)
```suggestion
	qdel(src)
	return TRUE
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +	for(var/i = 1 to (sizemod*3))
```suggestion
	for(var/i in 1 to (sizemod*3))
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +	for(var/i = 1 to sizemod)
```suggestion
	for(var/i in 1 to sizemod)
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +	if(istype(AM, /obj/item/fish))
```suggestion
	else if(istype(AM, /obj/item/fish))
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +	..()
```suggestion
	. = ..()
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +		return
```suggestion
		return TRUE
```

2022-06-06 07:55 UTC, Vallat commented on code/modules/fish/fish_items.dm
> +	..()
```suggestion
	. = ..()
```

2022-09-07 13:43 UTC, Jordanstolethepreciousslam commented
Голосовалки не прошли

2022-09-07 13:43 UTC, closed without merging

2022-09-07 14:24 UTC, PhantornRU commented
mericCat