Замена смотрителя на Клоуна-Смотрителя
ss220-space/Paradise pull request #948
Opened 2022-05-30 11:44 UTC by PhantornRU

Красавец брига, гроза врагов компании Нанотрейзен. 
Он поступил на службу к НТ чтобы вершить правосудие, карать антагов и щиткьюров.
Эта роль предназначена для настоящих робастов своего дела и теперь их статус возвышается над всеми со своей новой робастной экипировкой
![image](https://user-images.githubusercontent.com/41479614/170978386-1117e0e6-1581-443b-8d95-97e0b0163903.png)

Для подробностей - пролистайте до конца ПР'а.

## What Does This PR Do
Данный ПР вносит новые спрайты и изменения для замены роли Warden на роль уникальную роль Клоуна-Смотрителя.
Данное введение позволит по новому взглянуть на роль смотрителя и осуществить мечту людей.
Также это внесет уникальную особенность билда в возможности сыграть за клоуна-брига или за знаменитого и известного детектива/смотрителя Хонкерсона.

У клоуна-смотрителя отсутствует ген неуклюжести, он не сможет себя случайно застрелить при лазанье в оружейной.

Часы для клоуна-смотрителя по прежнему сохранены как для вардена.

## Why It's Good For The Game
Предложка от голосования:
> Чтоб было 2 клоуна в раунде, и уменьшились ситуации, когда единственный клоун так зашивается, что просто идёт в крио только чтобы от него отъебались
> 
> Очень часто в раундах клоун бегает как банан по всему бригу, ибо ему надо одновременно
> — развлекать трёх недоклоунов офицеров, которые даже не выставили аресты, а тупо притащили в допросную и убежали
> — заказывать в карго мартышек для вампиров
> — вызывать инжей для починки пермы после себя
> — вызывать уборщика для замены ламп, уборки крови и неприличных надписей
> — вскрывать арсенал и мимскую
> — вешать сибилы на оружие шахтеров и бумажки на спины персонала,
> — ставить импланты и собирать H.O.N.K.
> 
> Клоуна постоянно куда-либо зовут и у него дела накапливаются, нету времени заниматься тем что накопилось
> При наличии помощника работа будет идти легче и плавнее, быстрее. А не как сейчас при игроках больше 60-70 и антагонистах больше 5, клоун только бегает от одного места к другому не успевая даже понять что от него хотят, быстро говорит «Да», «Нет», «Иди наHONK!» и бежит дальше. Как и не может успеть обыскать поскользнутого ибо его зовут ещё куда-то
> 
> Совершенно типичной ситуацией является еле бредущий клоун, который умирает от голода просто потому что ему некогда было поесть
> 
> Плюсы:
> — Возможность неадекватного допроса подозреваемых и таскание тел от одной камеры до другой без возможности рассмотреть док-ва.
> — Возможность пополнять и освобождать каторгу, и проверять каторгу, пока второй клоун работает в комнате досмотра
> — Офицеры получат более адекватное времяпровождение, может быть, даже начнут что-то обсуждать, а не молча таскать в камеры как мешки с говном
> — Антагам в поле будет проще — офицер занимается клоуном, значит будет меньше патрульных
> 
> Минусы:
> — Антагам будет сложнее обокрасть бриг и кабинет клоуна — за ним теперь следит не один потный клоун с выпученными глазами, а двое
> 

Голосование было пройдена. Клоуну-смотрителю быть.
https://discord.com/channels/617003227182792704/755125334097133628/961908277464170546

## Изменения:
Изменения были в расчете на сохранения общей стилистики вардена, службы безопасности и клоуна.

### Выбор названия профессии в консоли ГП / в Preferenc'ах перед началом игры.
![image](https://user-images.githubusercontent.com/41479614/170984941-01639cc0-7d0d-4494-a9a5-1be4ca785511.png)

### HUD
HUD-Иконка была слегка изменена.
![image](https://user-images.githubusercontent.com/41479614/170985148-088d62d8-0242-4017-bb8e-a7348bc57092.png)

### ID-карта
Изменен спрайт и описание карты.
![image](https://user-images.githubusercontent.com/41479614/170978934-a262f905-0e34-4dc9-8ece-ceb00e7e2e45.png)
![image](https://user-images.githubusercontent.com/41479614/170979063-e8120efd-99e3-4da4-b13d-e9ee885e8aa8.png)

### PDA 
Изменен спрайт пда и его описание.
Изначально вставлен клоунских картридж для подскальзываний.
Секьюрити картридж перемещен в рюкзак.
![image](https://user-images.githubusercontent.com/41479614/170979974-898a5945-43d8-4824-bafe-2f3731332a4e.png)
![image](https://user-images.githubusercontent.com/41479614/170980098-b5143398-692a-4f1a-8809-c800ad86da23.png)

### Наушник
В наушник добавлен канал сервиса для связи со своими собратьями
![image](https://user-images.githubusercontent.com/41479614/170984236-28f76acf-6ee4-40e4-b42c-bd9ddc81c586.png)

### Снаряжение
У смотрителя теперь отличное снаряжения для своей работы, позволяющий выполнять его гораздо эффективнее.
![image](https://user-images.githubusercontent.com/41479614/170980443-0f5f1bf0-837c-4220-9e08-43ff1a6fcea0.png)

### Хонк-ружье
Смотритель-клоунов - всё-таки не лыком шит. У него имеется боевая подготовка. В том числе и доступ к ХОНК-ружью с хлопушками, доступные только для самых умелых клоунов.
![image](https://user-images.githubusercontent.com/41479614/170980662-f1827c23-594d-44d4-bc97-a882829a8f83.png)

### Одежда
У смотрителя отныне еще одна уникальная одежда, его оригинальный костюм убран в шкаф, заместо него добавлены широкие штаны где он может прятать контрабанду и тела мимов, что также увеличивает эффективность работы.
Плазмамен-Варден аналогично получает свои шаровары.
![image](https://user-images.githubusercontent.com/41479614/170980894-05a24d9b-c0ff-4ab8-98fa-afe825e5a650.png)

#### Иконки одежды:
![image](https://user-images.githubusercontent.com/41479614/170984377-eab6d50c-49ae-438b-8306-f665110ad38b.png)

- Сдавай пост, старый смотритель. Ведь теперь я пишу здесь историю
![image](https://user-images.githubusercontent.com/41479614/170983361-ce2433f8-5e83-40b2-82ec-abe35d50ed2a.png)
![image](https://user-images.githubusercontent.com/41479614/170983293-203a6f5b-c1ca-4d7a-be88-f44264ef2885.png)
![image](https://user-images.githubusercontent.com/41479614/170983390-d3ba17c8-4add-48d1-bd4b-c9e8046adfe7.png)

#### Сравнение униформ
![image](https://user-images.githubusercontent.com/41479614/170981923-4b2d9b3b-ddd0-409a-8708-e433f213c325.png)
1 - Старый плазмамен-варден без накидки и рюкзака
2 - Старый Варден без накидки и рюкзака
3 - Старый Варден с накидкой и рюкзаком
4 - Клоун-смотритель плазмамен без накидки и рюкзака
5 - Клоун-смотритель без накидки и рюкзака
6 - Оригинальный клоун

Вид спереди:
![image](https://user-images.githubusercontent.com/41479614/170981780-77597272-5273-439b-9762-81ab8aed620f.png)

Вид сбоку:
![image](https://user-images.githubusercontent.com/41479614/170982384-fbfb8ec2-467b-4040-8f6e-e7104c0f8b9a.png)

Вид сзади:
![image](https://user-images.githubusercontent.com/41479614/170982516-e34c6f69-4d4b-4a21-90ab-155e7870318d.png)

## Админские ништяки
Для администрации сохранены обе вариации одежды в Select equipment:
![image](https://user-images.githubusercontent.com/41479614/170983592-b79956db-473e-4b6d-ba28-04f74a791262.png)

Аналогично для плазмамена:
![image](https://user-images.githubusercontent.com/41479614/170983669-557bdc78-7a51-4625-8200-98c1bd2b2021.png)

2022-05-30 11:45 UTC, PhantornRU commented
А-воут пройден и одобрен.
https://discord.com/channels/617003227182792704/755125334097133628/961908277464170546

2022-05-30 11:49 UTC, Den109G commented
Да! Погнали, с этими изменениями наш сервер станет вторым ТГ!

2022-05-30 11:53 UTC, PhantornRU commented
А еще интересный факт. Я в коде и спрайтах нашел кучу ЦКшных одежд для ЦКшных невведенных ролей.
Если этот ПР будет замержен, я займусь созданием экипировки для щитспавнов педалей.

2022-05-30 11:53 UTC, Ohar requested changes

2022-05-30 11:53 UTC, Ohar commented on code/game/jobs/job/security.dm
> -	alt_titles = list("Forensic Technician")
Почему убрал профу детектива? Верни

2022-05-30 11:53 UTC, Ohar commented on code/modules/pda/pdas.dm
> +	desc = "Переносной микрокомпьютер от Синктроник Системс, LTD. ПДА разработаный по заказу тайного покупателя, пожелавший хонкнуться нераскрытым. Поверхность покрыта политетрафторэтиленом и банановым
```suggestion
	desc = "Переносной микрокомпьютер от Синктроник Системс, LTD. Этот КПК разработан по заказу тайного покупателя, пожелавшего хонкнуться нераскрытым. Поверхность покрыта политетрафторэтиленом и банановым налётом."
```

2022-05-30 11:54 UTC, PhantornRU commented on code/game/jobs/job/security.dm
> -	alt_titles = list("Forensic Technician")
Это дубликат. У него выше уже она есть.
Это альтернативные названия

2022-05-30 11:58 UTC, Den109G commented on code/game/jobs/job/security.dm
> -	alt_titles = list("Forensic Technician")
Верни, кому сказали.

2022-05-30 12:24 UTC, Ohar approved these changes

2022-05-30 12:24 UTC, keIgaras requested changes

2022-05-30 12:24 UTC, keIgaras commented on code/modules/clothing/spacesuits/plasmamen.dm
> -	item_state = "clown_envirohelm"
верни item_state pepeAngry

2022-05-30 12:35 UTC, PhantornRU commented on code/modules/clothing/spacesuits/plasmamen.dm
>  	icon_state = "clown_envirohelm"
```suggestion
	icon_state = "clown_envirohelm"
	item_state = "clown_envirohelm"
```

2022-05-30 12:36 UTC, PhantornRU commented on code/modules/clothing/spacesuits/plasmamen.dm
> -	item_state = "clown_envirohelm"
Возвращено

2022-05-30 12:39 UTC, keIgaras approved these changes

2022-05-30 15:11 UTC, PhantornRU commented
У личного ружья вардена доделан спрайт. В том числе спрайт держания в руках во всех состояниях. Теперь он совсем красивый.
![image](https://user-images.githubusercontent.com/41479614/171020628-22efb05a-0d0d-4727-9cbf-550dc893e757.png)

2022-05-30 16:18 UTC, Ohar commented
@PhantornRU 

1. Крав-маги не дают клоунскую борьбу
2. Нет клоунского стиля речи

2022-05-31 00:11 UTC, PhantornRU commented
> Нет клоунского стиля речи

Клоунскую борьбу точно не выдам, так как в разработке + кравмаги это кравмаги.
А вот клоунский стиль речи добавлю чуть позже если не забуду.

2022-05-31 03:11 UTC, PhantornRU commented
Смотритель говорит на комик сансе.
Если смотритель - машина, то в него вставляется комичный имплант Comic. 
(не неуклюжести CLumsy, его по прежнему нет)
![image](https://user-images.githubusercontent.com/41479614/171085179-2dd03b11-ae71-4fab-a1a2-dc9ba6b2b281.png)

2022-05-31 07:19 UTC, kelgaras commented
> Смотритель говорит на комик сансе. Если смотритель - машина, то в него вставляется комичный имплант Comic. (не неуклюжести CLumsy, его по прежнему нет) ![image](https://user-images.githubusercontent.com/41479614/171085179-2dd03b11-ae71-4fab-a1a2-dc9ba6b2b281.png)

белая тема 👎🏻

2022-06-01 09:29 UTC, PhantornRU commented
Ждет мержа.

2022-06-02 16:34 UTC, PhantornRU commented
Все еще ждет мержа

2022-07-23 13:31 UTC, PhantornRU commented
Пофикшены пересечения слияния в иконках.

2022-10-27 13:03 UTC, PhantornRU commented
Ставим крест над ПРом. Он был слишком хорош для этого сервера. Закрыто.

2022-10-27 13:03 UTC, closed without merging

2022-12-03 05:39 UTC, PhantornRU commented on code/modules/clothing/under/jobs/security.dm
> +	desc = "It's made of a slightly sturdier material than standard jumpsuits, to allow for more robust protection. It has the word \"Warden\" written on the shoulders. HONK!"
```suggestion
	desc = "«Он сделан из более прочного материала, чем стандартные комбинезоны, что обеспечивает более надежную защиту. На его плечах написано слово \"Надзиратель\". ХОНК!"
	```