fix: Игрушечные мечи больше не убивают
ss220-space/Paradise pull request #954
Opened 2022-05-31 15:11 UTC by Den109G

## What Does This PR Do
Добавляет проверку для dualsaber'а на урон, чтобы любой с геном CLUMSY не помирал от ударов по себе.

## Why It's Good For The Game
Клоуны смогут бегать с двойными игрушечными мечами и не помирать

## Changelog
:cl:
fix: now clown cannot die by toy swords
/:cl:

2022-05-31 15:41 UTC, Gaxeer approved these changes

2022-06-01 07:56 UTC, Vallat requested changes

2022-06-01 07:56 UTC, Vallat commented on code/game/objects/items/weapons/twohanded.dm
> +		if(force == 0)//so toy swords cannot kill clowns
```suggestion
		if(!force)//so toy swords cannot kill clowns
```

2022-06-01 11:39 UTC, Vallat approved these changes

2022-06-02 20:20 UTC, merged