[BOUNTY] Шпионские паучки
ss220-space/Paradise pull request #956
Opened 2022-06-01 12:49 UTC by Vallat

Добавляет в игру шпионских паучков, прямо как из всеми известных фильмов. 3 паучка поставляются в комплекте с 2 энкрипт кеями, вставляющимися в наушник, в закрытом на доступ детектива ящике. 

Паучки изначально выключены, включаются/выключаются кликом, выключаются так же от EMP.
Крепятся на верхнюю одежду человека (или униформу, если не закрыта верхней одеждой) кликом по человеку с 3х секундным делеем, либо же без делея кликом конкретно на объект одежды. Все паучки вещают в один канал, доступ к которому открывается путем вставки энкрипт кея в наушник. Они слышат всё, что говорится в радиусе трёх тайлов от одежды, к которой прикреплены.

Обнаружить паучка можно сканированием предмета одежды детективным сканером, после чего появляется действие "снять жучок" в меню на ПКМ и во вкладке "Object".

Данный PR создан для Прайм сервера

2022-06-01 13:24 UTC, Gaxeer approved these changes
Заебись. Павуки на месте

2022-06-01 14:33 UTC, TrashDoxx requested changes

2022-06-01 14:33 UTC, TrashDoxx commented on code/game/objects/items/devices/radio/spy_spider.dm
> +	. += "<span class='info>Сейчас он [broadcasting ? "включен" : "выключен"]</span>"
```suggestion
	. += "<span class='info'>Сейчас он [broadcasting ? "включен" : "выключен"]</span>"
```

2022-06-01 14:48 UTC, dj-34 commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='warning'>У тебя нет желания лезть к [genderize_ru(gender, "нему", "ней", "ним", "ним")] в трусы. Жучок надо крепить на одежду!</span>")
```suggestion
		to_chat(user, "<span class='warning'>У тебя нет желания лезть к [genderize_ru(gender, "нему", "ней", "ним")] в трусы. Жучок надо крепить на одежду!</span>")
```

2022-06-01 14:48 UTC, dj-34 commented on code/game/objects/items/devices/radio/spy_spider.dm
> +	to_chat(user, "<span class='info'>Ты незаметно прикрепил жучка к одежде [src].</span>")
```suggestion
	to_chat(user, "<span class='info'>Ты незаметно прикрепил жучок к одежде [src].</span>")
```

2022-06-01 14:48 UTC, dj-34 commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='info'>Ты включил жучка.</span>")
Как вариант "Ты активировал/деактивировал жучок."

2022-06-01 14:48 UTC, dj-34 commented on code/game/objects/items/devices/radio/spy_spider.dm
> +	to_chat(user, "<span class='info'>Ты незаметно прикрепил жучка к [src].</span>")
```suggestion
	to_chat(user, "<span class='info'>Ты незаметно прикрепил жучок к [src].</span>")
```

2022-06-01 14:52 UTC, Vallat commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='warning'>У тебя нет желания лезть к [genderize_ru(gender, "нему", "ней", "ним", "ним")] в трусы. Жучок надо крепить на одежду!</span>")
```suggestion
		to_chat(user, "<span class='warning'>У тебя нет желания лезть к [genderize_ru(gender, "нему", "ней", "этому", "ним")] в трусы. Жучок надо крепить на одежду!</span>")
```

2022-06-02 00:00 UTC, Ohar requested changes

2022-06-02 00:00 UTC, Ohar commented on code/game/objects/items/devices/radio/spy_spider.dm
> +	canhear_range = 3
Если на русском, то сразу локализация, пожалуйста
```suggestion
	canhear_range = 3
	gender = MALE
	name_ru = list(NOMINATIVE = "жучок", GENITIVE = "жучка", DATIVE = "жучку", ACCUSATIVE = "жучок", INSTRUMENTAL = "жучком", PREPOSITIONAL = "жучке")
```

2022-06-02 00:00 UTC, Ohar commented on code/game/objects/items/devices/radio/spy_spider.dm
> +	. += "<span class='info'>Сейчас он [broadcasting ? "включен" : "выключен"]</span>"
```suggestion
	. += "<span class='info'>Сейчас он [broadcasting ? "включён" : "выключен"]</span>"
```

2022-06-02 00:00 UTC, Ohar commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='info'>Ты включил жучка.</span>")
Описание всегда в настоящем времени + падеж
```suggestion
		to_chat(user, "<span class='info'>Ты включаешь жучок.</span>")
```

2022-06-02 00:00 UTC, Ohar commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='warning'>Ты не нашел места для жучка!</span>")
```suggestion
		to_chat(user, "<span class='warning'>Ты не находишь места для жучка!</span>")
```

2022-06-02 00:00 UTC, Ohar commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='warning'>Жучок выключен!</span>")
```suggestion
		to_chat(user, "<span class='warning'>Жучок выключается!</span>")
```

2022-06-02 00:00 UTC, Ohar commented on code/game/objects/items/devices/radio/spy_spider.dm
> +	to_chat(user, "<span class='info'>Ты незаметно прикрепил жучок к [src].</span>")
```suggestion
	to_chat(user, "<span class='info'>Ты незаметно прикрепляешь жучок к [src.declent_ru(DATIVE)].</span>")
```

2022-06-02 00:00 UTC, Ohar commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='warning'>Ты не нашел места для жучка!</span>")
```suggestion
		to_chat(user, "<span class='warning'>Ты не находишь места для жучка!</span>")
```

2022-06-02 00:00 UTC, Ohar commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='warning'>Жучок выключен!</span>")
```suggestion
		to_chat(user, "<span class='warning'>Жучок выключается!</span>")
```

2022-06-02 00:00 UTC, Ohar commented on code/game/objects/items/devices/radio/spy_spider.dm
> +	var/attempt_cancel_message = "<span class='warning'>Ты не успел установить жучок.</span>"
```suggestion
	var/attempt_cancel_message = "<span class='warning'>Ты не успеваешь установить жучок.</span>"
```

2022-06-02 00:00 UTC, Ohar commented on code/game/objects/items/devices/radio/spy_spider.dm
> +	to_chat(user, "<span class='info'>Ты незаметно прикрепил жучок к одежде [src].</span>")
```suggestion
	to_chat(user, "<span class='info'>Ты незаметно прикрепляешь жучок к одежде [src.declent_ru(GENITIVE)].</span>")
```

2022-06-02 00:00 UTC, Ohar commented on goon/browserassets/css/browserOutput-dark.css
> +.deptradio				{color: #993399;}
Все эти строки — дубликаты из `browserOutput.css`. Удали их, пожалуйста, они не нужны.

2022-06-02 05:25 UTC, Vallat commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='warning'>Жучок выключен!</span>")
Он не выключается, он уже выключен

2022-06-02 05:25 UTC, Vallat commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='warning'>Жучок выключен!</span>")
Он не выключается, он уже выключен

2022-06-02 05:26 UTC, Vallat commented on code/game/objects/items/devices/radio/spy_spider.dm
> +	canhear_range = 3
Буду делать на английском 🤡

2022-06-02 05:29 UTC, Vallat commented on code/game/objects/items/devices/radio/spy_spider.dm
> +		to_chat(user, "<span class='info'>Ты включил жучка.</span>")
Включаешь жучок, но "прикрепляешь **жучка**". В чем разница?

2022-06-02 11:46 UTC, Vallat commented on goon/browserassets/css/browserOutput-dark.css
> +.deptradio				{color: #993399;}
```suggestion
```

2022-06-02 19:20 UTC, dj-34 approved these changes

2022-06-02 20:23 UTC, merged

2022-06-03 06:13 UTC, PhantornRU commented
Пришло предложение реализовать балансировку жучков и внесение дополнительного геймплея путем проверки условия на расстояния от жучка и слушателя.

Чем жучок дальше от слушателя, тем больше помех, вплоть до неразборчивой речи.