add: Goblin
ss220-space/Paradise pull request #964
Opened 2022-06-02 17:16 UTC by Den109G

## What Does This PR Do
Добавляет админам ещё один способ раздражать игроков.

## Why It's Good For The Game
Это не гуд, это хорошо, когда за набегатором бежит гномик.

## Changelog
:cl:
add: shitcur_goblin - the ultimate unit from nabegov
/:cl:

2022-06-06 06:28 UTC, Vallat requested changes

2022-06-06 06:28 UTC, Vallat commented on code/modules/admin/topic.dm
> +				var/mob/living/simple_animal/hostile/shitcur_goblin/goblin = new /mob/living/simple_animal/hostile/shitcur_goblin(T)
```suggestion
				var/mob/living/simple_animal/hostile/shitcur_goblin/goblin = new (T)
```

2022-06-06 06:28 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/shitcur_goblin.dm
> +	Destroy() //so we dont shitcur after banning
```suggestion
	qdel(src) //so we dont shitcur after banning
```

2022-06-06 18:59 UTC, Vallat approved these changes

2022-08-22 17:59 UTC, Den109G commented
Обновлено, вот видео как работает.

https://user-images.githubusercontent.com/87372121/185987898-0705c8ac-af70-4d3a-9008-534f50206c8f.mp4

2022-08-23 04:40 UTC, Vallat requested changes

2022-08-23 04:40 UTC, Vallat commented on code/modules/admin/topic.dm
> +			. += "|[ADMIN_FLW(O.mind.current,"BDY")]"
Верни пустую строку в конце файла

2022-08-23 04:40 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/shitcur_goblin.dm
> +/mob/living/simple_animal/hostile/shitcur_goblin/New()
```suggestion
/mob/living/simple_animal/hostile/shitcur_goblin/Initialize()
```

2022-08-23 04:40 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/shitcur_goblin.dm
> +	playsound(loc, 'sound/misc/BAAN.ogg', 50, 1, -1)
Добавь пустую строку

2022-08-27 08:35 UTC, Den109G commented
Спасибо за очередную помощь.

2022-09-10 19:19 UTC, merged