Add: space ID
ss220-space/Paradise pull request #981
Opened 2022-06-06 11:12 UTC by captainnelly

## What Does This PR Do
Добавляет новую красивую карту в космическом стиле для донатеров(и педалей) в лоадаут. Также добавляет ее в автомат с призами, и как возможный подарок из коробочки.

## Why It's Good For The Game
Задействуем спрайт из файлов. Никому не помешает, спрайт очень красивый.

## Changelog
:cl:
add: New space styled ID
/:cl:

2022-06-06 15:52 UTC, dj-34 commented
Так это же спрайт для Эксплореров, нет?

2022-06-06 15:59 UTC, captainnelly commented
> Так это же спрайт для Эксплореров, нет?

С чего ты это взял? То что там написано "exploration" ничего не значит.

2022-06-06 19:53 UTC, dikers93 commented
> Так это же спрайт для Эксплореров, нет?

это давно уже было сделано, там еще чемоданчик с этой текстуркой есть

2022-06-08 06:15 UTC, Vallat requested changes
На последнем фрейме у иконки появляется белый пиксель в левом верхнем углу

2022-07-21 10:53 UTC, closed without merging